# Notebook 02: Real Arm Baselines

**Purpose**: Run all 7 Family A demo-selection conditions on all real datasets, ID and OOD test sets, 2 models, 5 seeds, at both `k_primary` and `k_sensitivity` demo counts.

**Compute budget**: 7 conditions x 5 seeds x 1000 rows x N datasets x 2 models x 2 k-values LLM calls (~12-24h wall time at k_primary alone; the k_sensitivity sweep roughly doubles this, minus zero-shot which is k-independent and only ever run once).

## Why this notebook exists (thesis framing)

This notebook answers **RQ2**: *which kinds of demonstration diversity matter most for OOD performance?* It is also the primary evidence source for **RQ1** (alongside Notebook 01's pilot) and feeds the "best-performing protocol" selection used by Notebook 03's faithfulness evaluation and Notebook 05/06's SATA comparisons.

**Why compare 7 conditions rather than just testing SATA directly?** The lit review's Task 2 (Section 3) lays out four baselines specifically to isolate *which component* of the intervention is doing the work: (1) random demonstrations, to check whether demonstration design matters *at all*; (2) similarity-based retrieval (Liu et al. 2022, "What makes good in-context examples for GPT-3?"), to check whether the current best-practice retrieval method already solves OOD tabular tasks; (3) the four diversity protocols, to check whether principled, hand-designed selection closes the gap without any learning; and (4) SATA (Notebook 06), to check whether *learned, query-conditioned* reweighting adds anything beyond hand-designed diversity. This notebook covers baselines 1–3; SATA is evaluated on top of them in Notebook 06.

**Why also sweep k?** `configs/default.yaml`'s `k_sensitivity` existed as an unused placeholder until this sweep was added — a condition ranking that only holds at one specific demo count (k=8) would be a much weaker RQ2 result than one that's stable across k. All 4 downstream consumers of this notebook's summary (Notebook 03, 05, 06, 08) key off `k == config.k_primary` for their "headline" numbers; the k_sensitivity rows are an additional robustness check, not a replacement.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.config import load_config, set_seed, resolve_path

config = load_config()
set_seed(config.seed_accuracy[0])

## Conditions (7 total)

1. Zero-shot
2. Random-k
3. Similarity-k (all-MiniLM-L6-v2 cosine similarity)
4. Label diversity (stratified k/2 per class)
5. Feature-range diversity (quantile-bin coverage on top-3 continuous features)
6. Rule diversity (depth-3 decision tree leaf coverage)
7. Counter-spurious diversity (minority-cell over-sampling)

### Why these specific four diversity protocols, and why they're expected to differ

Two empirical findings from the lit review directly motivate this design:

- **Min et al. (2022), "Rethinking the role of demonstrations"** — across twelve LLMs including GPT-3, randomly corrupting demonstration *labels* barely hurts ICL accuracy. Ground-truth input–label mapping isn't the key signal; what matters is the **label space**, the **input-text distribution** the demonstrations sample, and the **input-label format** the demonstrations span. This is why demonstration design has room to operate on *which regions of input space and label space* the demos cover — that's exactly what protocols 4–7 manipulate — rather than needing to retrieve "more correct" examples.
- **Harutyunyan et al. (2024) and Chen et al. (2026)** — in-context learners are themselves susceptible to spurious correlations carried in the demonstration set, and this is a distinct failure mode from the base model's pretraining biases. Protocol 7 (counter-spurious) exists specifically to counteract this at the demonstration level, by denying the model the option of relying on the shortcut.

Each protocol targets a **different point in the covariate/concept shift taxonomy** (Lit-review §2.1.1), which is the basis for RQ2's success criterion:
- **Label diversity** guards against *label (prior-probability) shift* — a skewed class prior in the demo pool would bias the model's implicit prior even when `P(y|x)` hasn't moved.
- **Feature-range diversity** targets *covariate shift* (`P(x)` moves, `P(y|x)` stable) — forcing demos to span the full input range denies the model a narrow, spuriously-correlated cluster to anchor on.
- **Rule diversity** and **counter-spurious diversity** both target *concept shift* (`P(y|x)` itself moves) — the harder regime, per WHYSHIFT (Liu et al. 2023, Lit-review §2.1.3), because no amount of reweighting recovers a moved conditional without information about *how* the decision rule varies across regimes.

**RQ2 succeeds** only if at least one protocol beats random selection *and* different protocols win on different shift types — i.e. the interaction effect is the point, not any single protocol dominating everywhere. A protocol that's uniformly best (or uniformly no better than random) would actually be a weaker result for RQ2 than protocols that trade off differently across shift types.

In [2]:
from src.selection import (
    random_select,
    similarity_select,
    label_diversity,
    feature_range,
    rule_diversity,
    counter_spurious,
)

CONDITIONS = [
    'zero_shot', 'random', 'similarity', 'label_diversity',
    'feature_range', 'rule_diversity', 'counter_spurious',
]

## Prompt template & LLM runner

See `src/inference/prompts.py::build_classification_prompt` and `src/inference/llm_runner.py::VLLMRunner`.

SamplingParams: `logprobs=True, max_tokens=1, temperature=0`. Top token not in the label set -> log as `INVALID`, exclude from accuracy but include in the count.

**Why constrained single-token decoding instead of free-text generation?** This makes the prediction a clean forced choice between exactly the label tokens, so `logprob_0`/`logprob_1` are directly comparable across every condition/dataset/model combination and feed straight into the uncertainty analysis in Notebook 07 (R-AUC, F1@95%) — see `src/inference/llm_runner.py::get_confidence`'s constrained softmax. `temperature=0` makes predictions deterministic given the prompt, so any variation in results across seeds is attributable entirely to which demonstrations were selected, not to sampling noise in generation.

In [3]:
import json

import numpy as np
import pandas as pd
from tqdm import tqdm

from src.data.tableshift_loader import (
    SELECTED_DATASETS, TASK_DESCRIPTIONS, load_codebook, select_top_features,
)
from src.data.serialisation import serialise_row, ordered_feature_names
from src.inference.llm_runner import VLLMWorkerRunner
from src.inference.prompts import build_classification_prompt
from src.selection.rule_diversity import fit_leaf_tree
from src.selection.counter_spurious import find_spurious_proxy_features
from src.utils.results_schema import append_results, new_results_frame, load_results

# TableShift's domain_split_varname per dataset (tableshift/configs/benchmark_configs.py)
# — the variable that defines the OOD shift, used by the counter-spurious protocol
# to find features that proxy for it.
RESULTS_PATH = resolve_path('results/real_arm_baselines.parquet')

# k-sensitivity sweep: run every condition at both k_primary (the headline
# number) and k_sensitivity, on every dataset -- not just the one dataset the
# config comment originally scoped this to. K_VALUES[0] must stay k_primary:
# zero-shot dedup and the "headline" summary filter below both key off it.
K_VALUES = [config.k_primary, config.k_sensitivity]


def prepare_condition_artifacts(dataset_name, train_pool, feature_cols, test_id, test_ood, k, codebook=None):
    """One-time-per-dataset setup shared across seeds/queries/k-values for the
    feature_range, rule_diversity, and counter_spurious protocols.

    `k` here should be max(K_VALUES): similarity ranks are k-independent (a
    cosine-similarity argsort doesn't change when you later take a smaller
    prefix of it), so computing the top-max(K_VALUES) once and slicing per
    k in select_demos avoids re-embedding the same pool/queries once per k.
    """
    artifacts = {}

    # Feature-range: top-3 continuous (numeric, >10 unique values) features by MI.
    continuous_cols = [
        c for c in feature_cols
        if pd.api.types.is_numeric_dtype(train_pool[c]) and train_pool[c].nunique() > 10
    ]
    if continuous_cols:
        artifacts['top3_continuous'] = select_top_features(
            train_pool[continuous_cols + ['label']], n_features=min(3, len(continuous_cols))
        )
    else:
        artifacts['top3_continuous'] = feature_cols[:3]

    # Rule diversity: depth-3 tree fit on the pool.
    artifacts['tree'] = fit_leaf_tree(train_pool, feature_cols)

    # Counter-spurious: proxy feature most correlated with both the label and
    # the actual ID->OOD shift. TableShift's own domain-split covariate (e.g.
    # race/geography/year) is deliberately excluded from X -- it's the exact
    # variable tableshift thresholds to build the ood split, so a model can't
    # just read it directly -- and extract_tableshift_cache.py, which only
    # ever saves X, never had it to cache. Proxy against literal
    # train-vs-OOD-test row membership instead: a feature correlated with
    # *that* carries the same shift signal the raw covariate would have,
    # without needing the excluded column.
    shift_frame = pd.concat(
        [
            train_pool[feature_cols + ['label']].assign(_is_ood=0),
            test_ood[feature_cols + ['label']].assign(_is_ood=1),
        ],
        ignore_index=True,
    )
    proxy_features = find_spurious_proxy_features(shift_frame, feature_cols, 'label', '_is_ood', top_n=3)
    proxy_col = proxy_features[0] if proxy_features else feature_cols[0]
    proxy_high = train_pool[proxy_col] > train_pool[proxy_col].median()
    artifacts['proxy_col'] = proxy_col
    artifacts['proxy_majority_label'] = train_pool.loc[proxy_high, 'label'].mode().iloc[0]

    # Similarity is deterministic (no seed dependency) and reuses the same
    # pool/query embeddings across every one of the 5 seeds -- precompute it
    # once here (one batched encode() call per split) instead of re-embedding
    # one query at a time, identically, on every seed's pass through the data.
    pool_texts = [
        serialise_row(
            {f: train_pool.loc[i, f] for f in ordered_feature_names({f: train_pool.loc[i, f] for f in feature_cols})},
            label=str(int(train_pool.loc[i, 'label'])),
            codebook=codebook,
        )
        for i in train_pool.index
    ]
    similarity_demo_ids = {}
    for environment, test_df in [('id', test_id), ('ood', test_ood)]:
        query_texts = [
            serialise_row(
                {f: row[f] for f in ordered_feature_names({f: row[f] for f in feature_cols})},
                codebook=codebook,
            )
            for _, row in test_df.iterrows()
        ]
        local_idx_per_query = similarity_select.select_batch(pool_texts, query_texts, k)
        similarity_demo_ids[environment] = [
            [train_pool.index[i] for i in local_idx] for local_idx in local_idx_per_query
        ]
    artifacts['similarity_demo_ids'] = similarity_demo_ids

    return artifacts


def select_demos(condition, pool, query, k, seed, feature_cols, artifacts, environment, query_id):
    if condition == 'zero_shot':
        return []
    if condition == 'random':
        return random_select.select(pool, query, k, seed)
    if condition == 'similarity':
        # artifacts['similarity_demo_ids'] holds the top-max(K_VALUES) ranking;
        # a smaller k's top-k is just its prefix (see prepare_condition_artifacts).
        return artifacts['similarity_demo_ids'][environment][query_id][:k]
    if condition == 'label_diversity':
        return label_diversity.select(pool, query, k, seed)
    if condition == 'feature_range':
        return feature_range.select(pool, query, k, seed, top_features=artifacts['top3_continuous'])
    if condition == 'rule_diversity':
        return rule_diversity.select(pool, query, k, seed, feature_cols=feature_cols, tree=artifacts['tree'])
    if condition == 'counter_spurious':
        return counter_spurious.select(
            pool, query, k, seed, proxy_col=artifacts['proxy_col'], proxy_majority_label=artifacts['proxy_majority_label']
        )
    raise ValueError(f"Unknown condition: {condition}")


def build_demo_lines(pool, demo_ids, feature_cols, codebook=None):
    lines = []
    for i in demo_ids:
        row = pool.loc[i]
        ordered = ordered_feature_names({f: row[f] for f in feature_cols})
        lines.append(serialise_row({f: row[f] for f in ordered}, label=str(int(row['label'])), codebook=codebook))
    return lines


def build_query_line(query, feature_cols, codebook=None):
    ordered = ordered_feature_names({f: query[f] for f in feature_cols})
    return serialise_row({f: query[f] for f in ordered}, codebook=codebook)


try:
    import vllm  # noqa: F401
    VLLM_AVAILABLE = True
except ImportError:
    VLLM_AVAILABLE = False
    print("vLLM not installed in this environment — skipping real-arm inference. "
          "Run this notebook on a GPU box with vllm + the model weights available.")

# Model-outer / dataset-inner so each model's weights load exactly once
# (vLLM model load is the expensive step, not iterating datasets/conditions/seeds).
# Compute budget per the docstring above, now roughly doubled by the k=16
# sensitivity sweep (zero-shot is deduped across k, see below) — nested tqdm
# bars below give a glanceable readout of exactly which
# (model, dataset, k, condition, seed) is running.
models_to_run = config.base_llms if VLLM_AVAILABLE else []

# Resume support: append_results always appends and never dedupes, and this
# loop had no way to know what's already been done -- so a restart (e.g.
# after a walltime kill partway through this ~12-24h run) would otherwise
# redo *and duplicate* every combo from scratch. Skip any
# (model, dataset, condition, seed, k) already present in RESULTS_PATH instead,
# so re-running (interactively, or via a resubmitted gadi_run_notebook.pbs
# batch job) picks up exactly where the last run left off. zero_shot always
# has 0 demos regardless of which k in K_VALUES is being swept, so its
# combo-key uses k=0 -- this also means the k=16 pass naturally skips
# re-running zero_shot once the k=8 pass has already produced that row.
if RESULTS_PATH.exists():
    _existing_results = load_results(RESULTS_PATH)
    completed_combos = set(
        zip(_existing_results['model'], _existing_results['dataset'],
            _existing_results['method'], _existing_results['seed'].astype(int),
            _existing_results['k'].astype(int))
    )
else:
    completed_combos = set()

model_bar = tqdm(models_to_run, desc="Models", position=0)
for model_cfg in model_bar:
    model_bar.set_postfix(model=model_cfg.name)
    # VLLMWorkerRunner (not VLLMRunner): runs vLLM in a separate OS subprocess
    # so its GPU memory is guaranteed to be released on shutdown() -- vLLM's
    # in-process engine does not reliably free GPU memory after explicit
    # teardown (confirmed: a second in-process model still failed to init
    # with "Free memory ... is less than desired GPU memory utilization"),
    # which matters here since this loop constructs one runner per model.
    runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))

    dataset_bar = tqdm(SELECTED_DATASETS, desc="Datasets", position=1, leave=False)
    for dataset_name in dataset_bar:
        dataset_bar.set_postfix(dataset=dataset_name)
        data_dir = resolve_path(config.paths.data_real) / dataset_name
        train_pool = pd.read_parquet(data_dir / 'train_pool.parquet')
        test_id = pd.read_parquet(data_dir / 'test_id.parquet')
        test_ood = pd.read_parquet(data_dir / 'test_ood.parquet')
        feature_cols = json.load(open(data_dir / 'feature_list.json'))
        label_tokens = tuple(json.load(open(data_dir / 'label_tokens.json')))
        codebook = load_codebook(data_dir)
        task_description, _task_noun, label_meaning_0, label_meaning_1 = TASK_DESCRIPTIONS[dataset_name]

        artifacts = prepare_condition_artifacts(
            dataset_name, train_pool, feature_cols, test_id, test_ood, max(K_VALUES), codebook=codebook
        )

        k_bar = tqdm(K_VALUES, desc="k", position=2, leave=False)
        for k in k_bar:
            k_bar.set_postfix(k=k)
            condition_bar = tqdm(CONDITIONS, desc="Conditions", position=3, leave=False)
            for condition in condition_bar:
                # Zero-shot has no demos, so it's identical at every k in
                # K_VALUES -- only run it at the primary k, not once per
                # sweep value (the completed_combos key above also catches
                # this on resume, but skip explicitly here too rather than
                # relying solely on that to avoid the wasted inference calls).
                if condition == 'zero_shot' and k != K_VALUES[0]:
                    continue
                condition_bar.set_postfix(condition=condition)
                seed_bar = tqdm(config.seed_accuracy, desc="Seeds", position=4, leave=False)
                for seed in seed_bar:
                    seed_bar.set_postfix(seed=int(seed))
                    combo_k = 0 if condition == 'zero_shot' else k
                    if (model_cfg.name, dataset_name, condition, int(seed), combo_k) in completed_combos:
                        continue
                    batch_rows = []
                    prompts = []
                    for environment, test_df in [('id', test_id), ('ood', test_ood)]:
                        for query_id, (_, query) in enumerate(test_df.iterrows()):
                            demo_ids = select_demos(condition, train_pool, query, k, seed, feature_cols, artifacts, environment, query_id)
                            demo_lines = build_demo_lines(train_pool, demo_ids, feature_cols, codebook)
                            query_line = build_query_line(query, feature_cols, codebook)
                            prompt = build_classification_prompt(
                                task_description, label_tokens, demo_lines, query_line,
                                label_meanings=(label_meaning_0, label_meaning_1),
                            )
                            prompts.append(prompt)
                            batch_rows.append({
                                'arm': 'real', 'dataset': dataset_name, 'environment': environment,
                                'model': model_cfg.name, 'method': condition, 'seed': int(seed),
                                'query_id': query_id, 'label': str(int(query['label'])),
                                'demo_ids': [int(i) for i in demo_ids], 'k': len(demo_ids),
                            })

                    predictions = runner.batch_predict(prompts, label_tokens)
                    for row, pred in zip(batch_rows, predictions):
                        row['prediction'] = pred.prediction
                        row['logprob_0'] = pred.logprob_0
                        row['logprob_1'] = pred.logprob_1

                    append_results(pd.DataFrame(batch_rows), RESULTS_PATH)
                    completed_combos.add((model_cfg.name, dataset_name, condition, int(seed), combo_k))
                    tqdm.write(f"{model_cfg.name} | {dataset_name} | k={k} | {condition} | seed={seed}: {len(batch_rows)} rows")

    runner.shutdown()

Models:   0%|          | 0/2 [00:00<?, ?it/s]

Models:   0%|          | 0/2 [00:00<?, ?it/s, model=Llama-3.1-8B-Instruct]

INFO 09-12 09:16:17 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:16:18 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:16:18 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:16:18 [model.py:2021] Using max model len 8192
INFO 09-12 09:16:18 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:16:18 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:16:20 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:16:21 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_f24efd67a703477899d5ee3d24151653 backend=nccl
INFO 09-12 09:16:21 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:16:21 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:16:22 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:16:22 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:16:22 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:16:23 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 926.59 GiB.
INFO 09-12 09:16:23 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  1.57it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.47it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.31it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.78it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.62it/s]

INFO 09-12 09:16:25 [default_loader.py:430] Loading weights took 2.48 seconds

INFO 09-12 09:16:26 [model_runner.py:404] Model loading took 15.0 GiB memory and 3.850438 seconds
INFO 09-12 09:16:26 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:16:26 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:16:26 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:16:26 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:16:26 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:16:27 [monitor.py:81] Initial profiling/warmup run took 0.14 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:25,  1.06s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:27,  2.74it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  5.00it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.38it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.59it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.28it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 12.84it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 14.08it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 14.92it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 16.12it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 16.29it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 17.30it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.90it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.52it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.47it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 17.60it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.60it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.62it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 17.27it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:08<00:00, 17.06it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.99it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.89it/s]

INFO 09-12 09:16:37 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:16:38 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:16:38 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:16:38 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:16:38 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:16:38 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:16:38 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:16:38 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:16:38 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:16:38 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:16:38 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:16:38 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:16:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:16:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:16:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:16:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:16:38 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:16:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:16:38 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:16:38 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:16:38 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:16:38 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:16:38 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.50it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:07, 10.97it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.54it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.07it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.64it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.44it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:03, 14.40it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.22it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 16.11it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 17.15it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 18.13it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:01, 18.85it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 18.95it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 19.04it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 18.04it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 18.57it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 18.90it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.03it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.01it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 19.20it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.20it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.88it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.74it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.44it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.69it/s]

Capturing CUDA graphs (FULL):  37%|███▋      | 31/83 [00:01<00:01, 28.55it/s]

Capturing CUDA graphs (FULL):  47%|████▋     | 39/83 [00:01<00:01, 32.03it/s]

Capturing CUDA graphs (FULL):  58%|█████▊    | 48/83 [00:01<00:00, 35.99it/s]

Capturing CUDA graphs (FULL):  69%|██████▊   | 57/83 [00:01<00:00, 37.99it/s]

Capturing CUDA graphs (FULL):  81%|████████  | 67/83 [00:02<00:00, 39.15it/s]

Capturing CUDA graphs (FULL):  92%|█████████▏| 76/83 [00:02<00:00, 38.73it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:06<00:00, 13.79it/s]

INFO 09-12 09:16:50 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.30 GiB
INFO 09-12 09:16:50 [gpu_worker.py:797] CUDA graph pool memory: 0.3 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (157.9%).
INFO 09-12 09:16:50 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.3 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152270358426` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170764578304` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:16:56 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:16:56 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:16:56 [core.py:361] init engine (profile, create kv cache, warmup model) took 30.48 s (compilation: 0.16 s)

INFO 09-12 09:16:58 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Datasets:   0%|          | 0/4 [00:00<?, ?it/s]

Datasets:   0%|          | 0/4 [00:00<?, ?it/s, dataset=brfss_diabetes]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.52it/s, k=16]

Datasets:  25%|██▌       | 1/4 [00:06<00:20,  6.96s/it, dataset=brfss_diabetes]

Datasets:  25%|██▌       | 1/4 [00:06<00:20,  6.96s/it, dataset=acsincome]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.59it/s, k=16]

Datasets:  50%|█████     | 2/4 [00:07<00:06,  3.19s/it, dataset=acsincome]

Datasets:  50%|█████     | 2/4 [00:07<00:06,  3.19s/it, dataset=acspubcov]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.41it/s, k=16]

Datasets:  75%|███████▌  | 3/4 [00:07<00:01,  1.95s/it, dataset=acspubcov]

Datasets:  75%|███████▌  | 3/4 [00:07<00:01,  1.95s/it, dataset=anes]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.64it/s, k=16]

Datasets: 100%|██████████| 4/4 [00:08<00:00,  1.39s/it, dataset=anes]

[rank0]:[W912 09:17:07.066785613 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Models:  50%|█████     | 1/2 [00:58<00:58, 58.43s/it, model=Llama-3.1-8B-Instruct]

Models:  50%|█████     | 1/2 [00:58<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

INFO 09-12 09:17:16 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-12 09:17:16 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:17:24 [model.py:684] Resolved architecture: Qwen2ForCausalLM
INFO 09-12 09:17:24 [model.py:2021] Using max model len 8192
INFO 09-12 09:17:24 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:17:24 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:17:27 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:17:28 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_16b33a6c48214ff1acdaee8d78ed454b backend=nccl
INFO 09-12 09:17:28 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:17:28 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:17:29 [model_runner.py:382] Loading model from scratch...
INFO 09-12 09:17:29 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:17:29 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:17:40 [weight_utils.py:526] Time spent downloading weights for Qwen/Qwen2.5-7B-Instruct: 10.236612 seconds
INFO 09-12 09:17:40 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.19 GiB. Available RAM: 910.95 GiB.
INFO 09-12 09:17:40 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.04it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.93it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:01<00:00,  1.90it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.94it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.94it/s]

INFO 09-12 09:17:42 [default_loader.py:430] Loading weights took 2.11 seconds

INFO 09-12 09:17:42 [model_runner.py:404] Model loading took 14.29 GiB memory and 13.710448 seconds
INFO 09-12 09:17:42 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:17:42 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:17:47 [backends.py:1094] Using cache directory: /root/.cache/vllm/torch_compile_cache/e4bb9957a2/rank_0_0/backbone for vLLM's torch.compile
INFO 09-12 09:17:48 [backends.py:1155] Dynamo bytecode transform time: 4.39 s

INFO 09-12 09:17:54 [backends.py:393] Compiling a graph for compile range (1, 16384) takes 5.96 s

INFO 09-12 09:17:57 [backends.py:920] collected artifacts: 29 entries, 3 artifacts, 4793120 bytes total
INFO 09-12 09:17:57 [decorators.py:719] saved AOT compiled function to /root/.cache/vllm/torch_compile_cache/torch_aot_compile/512c95ff7caead1e7699a3cd900d810fbcfbd9ecb7a9f3782617a1a8c613762b/rank_0_0/model
INFO 09-12 09:17:57 [monitor.py:53] torch.compile took 14.14 s in total
INFO 09-12 09:17:57 [monitor.py:81] Initial profiling/warmup run took 0.19 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:24,  1.06s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:26,  2.90it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:12,  5.68it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:04<00:07,  8.98it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:04<00:05, 12.36it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:04, 14.89it/s]

Capturing CUDA graphs (PIECEWISE):  34%|███▎      | 28/83 [00:05<00:03, 17.59it/s]

Capturing CUDA graphs (PIECEWISE):  39%|███▊      | 32/83 [00:05<00:02, 18.41it/s]

Capturing CUDA graphs (PIECEWISE):  45%|████▍     | 37/83 [00:05<00:02, 19.54it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:06<00:02, 19.19it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:06<00:01, 18.82it/s]

Capturing CUDA graphs (PIECEWISE):  63%|██████▎   | 52/83 [00:06<00:01, 19.46it/s]

Capturing CUDA graphs (PIECEWISE):  67%|██████▋   | 56/83 [00:06<00:01, 19.54it/s]

Capturing CUDA graphs (PIECEWISE):  72%|███████▏  | 60/83 [00:07<00:01, 19.50it/s]

Capturing CUDA graphs (PIECEWISE):  77%|███████▋  | 64/83 [00:07<00:01, 18.95it/s]

Capturing CUDA graphs (PIECEWISE):  82%|████████▏ | 68/83 [00:07<00:00, 19.17it/s]

Capturing CUDA graphs (PIECEWISE):  87%|████████▋ | 72/83 [00:07<00:00, 19.00it/s]

Capturing CUDA graphs (PIECEWISE):  92%|█████████▏| 76/83 [00:07<00:00, 19.11it/s]

Capturing CUDA graphs (PIECEWISE):  96%|█████████▋| 80/83 [00:08<00:00, 18.99it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.99it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 28.65it/s]

INFO 09-12 09:18:07 [model_runner.py:960] Graph capturing finished in 9 secs, took 0.57 GiB

INFO 09-12 09:18:08 [gpu_worker.py:625] Available KV cache memory: 141.47 GiB
INFO 09-12 09:18:08 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8955 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9045. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:18:08 [kv_cache_utils.py:2032] GPU KV cache size: 2,648,896 tokens, Maximum concurrency for 8,192 tokens per request: 323.35x
INFO 09-12 09:18:08 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:18:08 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:18:08 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:18:08 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:18:08 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:18:08 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:18:08 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:18:08 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:18:08 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:18:08 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:18:08 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:18:08 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:18:08 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:18:08 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:18:08 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:18:08 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:18:08 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:18:08 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:18:08 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:05, 15.48it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:04, 16.39it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:04, 16.68it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:00<00:04, 16.74it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:03, 17.77it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:03, 18.68it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:01<00:02, 19.63it/s]

Capturing CUDA graphs (PIECEWISE):  39%|███▊      | 32/83 [00:01<00:02, 19.74it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 20.79it/s]

Capturing CUDA graphs (PIECEWISE):  53%|█████▎    | 44/83 [00:02<00:01, 21.22it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:02<00:01, 21.38it/s]

Capturing CUDA graphs (PIECEWISE):  67%|██████▋   | 56/83 [00:02<00:01, 20.84it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:03<00:00, 21.14it/s]

Capturing CUDA graphs (PIECEWISE):  82%|████████▏ | 68/83 [00:03<00:00, 21.14it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:03<00:00, 21.20it/s]

Capturing CUDA graphs (PIECEWISE):  96%|█████████▋| 80/83 [00:04<00:00, 20.98it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:04<00:00, 19.92it/s]
Capturing CUDA graphs (FULL):   4%|▎         | 3/83 [00:00<00:02, 29.06it/s]

Capturing CUDA graphs (FULL):  13%|█▎        | 11/83 [00:00<00:02, 30.62it/s]

Capturing CUDA graphs (FULL):  23%|██▎       | 19/83 [00:00<00:02, 30.65it/s]

Capturing CUDA graphs (FULL):  33%|███▎      | 27/83 [00:00<00:01, 34.10it/s]

Capturing CUDA graphs (FULL):  45%|████▍     | 37/83 [00:01<00:01, 38.08it/s]

Capturing CUDA graphs (FULL):  57%|█████▋    | 47/83 [00:01<00:00, 40.49it/s]

Capturing CUDA graphs (FULL):  69%|██████▊   | 57/83 [00:01<00:00, 42.05it/s]

Capturing CUDA graphs (FULL):  81%|████████  | 67/83 [00:01<00:00, 42.78it/s]

Capturing CUDA graphs (FULL):  93%|█████████▎| 77/83 [00:01<00:00, 44.09it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL):  99%|█████████▉| 82/83 [00:05<00:00,  4.19it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:06<00:00, 13.78it/s]

INFO 09-12 09:18:19 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.33 GiB
INFO 09-12 09:18:19 [gpu_worker.py:797] CUDA graph pool memory: 0.33 GiB (actual), 0.8 GiB (estimated), difference: 0.47 GiB (139.8%).
INFO 09-12 09:18:19 [gpu_worker.py:860] Free memory on device (176.55/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 16.19 GiB for consumed memory (weights + non-torch), 2.86 GiB for peak activation, and 0.33 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=151383263130` (140.99 GiB) to fit into requested memory, or `--kv-cache-memory=168600251904` (157.02 GiB) to fully utilize gpu memory. Current kv cache memory in use is 141.47 GiB.

INFO 09-12 09:18:25 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:18:25 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:18:25 [core.py:361] init engine (profile, create kv cache, warmup model) took 43.09 s (compilation: 14.14 s)

INFO 09-12 09:18:27 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Datasets:   0%|          | 0/4 [00:00<?, ?it/s]

Datasets:   0%|          | 0/4 [00:00<?, ?it/s, dataset=brfss_diabetes]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.54it/s, k=16]

Datasets:  25%|██▌       | 1/4 [00:00<00:01,  1.73it/s, dataset=brfss_diabetes]

Datasets:  25%|██▌       | 1/4 [00:00<00:01,  1.73it/s, dataset=acsincome]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.53it/s, k=16]

Datasets:  50%|█████     | 2/4 [00:01<00:01,  1.93it/s, dataset=acsincome]

Datasets:  50%|█████     | 2/4 [00:01<00:01,  1.93it/s, dataset=acspubcov]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=16]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=label_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=feature_range]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=rule_diversity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=counter_spurious]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

k: 100%|██████████| 2/2 [00:00<00:00, 19.46it/s, k=16]

Datasets:  75%|███████▌  | 3/4 [00:01<00:00,  2.09it/s, dataset=acspubcov]

Datasets:  75%|███████▌  | 3/4 [00:01<00:00,  2.09it/s, dataset=anes]

k:   0%|          | 0/2 [00:00<?, ?it/s]

k:   0%|          | 0/2 [00:00<?, ?it/s, k=8]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=zero_shot]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=1024]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=similarity]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=123]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=456]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=789]

Rendering prompts:   4%|▍         | 45/1000 [00:00<00:02, 448.38it/s]

Rendering prompts:  15%|█▍        | 146/1000 [00:00<00:01, 487.45it/s]

Rendering prompts:  25%|██▍       | 247/1000 [00:00<00:01, 494.36it/s]

Rendering prompts:  35%|███▍      | 347/1000 [00:00<00:01, 496.87it/s]

Rendering prompts:  45%|████▍     | 447/1000 [00:00<00:01, 494.22it/s]

Rendering prompts:  55%|█████▍    | 547/1000 [00:01<00:00, 495.02it/s]

Rendering prompts:  65%|██████▍   | 647/1000 [00:01<00:00, 491.63it/s]

Rendering prompts:  75%|███████▍  | 747/1000 [00:01<00:00, 491.74it/s]

Rendering prompts:  85%|████████▍ | 847/1000 [00:01<00:00, 491.12it/s]

Rendering prompts:  95%|█████████▍| 946/1000 [00:01<00:00, 486.21it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 490.60it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:18:31 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 09:18:36 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

Processed prompts:   3%|▎         | 32/1000 [00:05<01:49,  8.84it/s, est. speed input: 7120.41 toks/s, output: 6.34 toks/s]

Processed prompts:   8%|▊         | 78/1000 [00:05<00:34, 26.80it/s, est. speed input: 16247.83 toks/s, output: 14.47 toks/s]

Processed prompts:  11%|█         | 106/1000 [00:05<00:21, 41.37it/s, est. speed input: 21407.79 toks/s, output: 19.06 toks/s]

Processed prompts:  19%|█▉        | 194/1000 [00:06<00:08, 92.23it/s, est. speed input: 35716.40 toks/s, output: 31.79 toks/s]

Processed prompts:  23%|██▎       | 230/1000 [00:06<00:08, 95.83it/s, est. speed input: 40085.96 toks/s, output: 35.68 toks/s]

Processed prompts:  37%|███▋      | 367/1000 [00:06<00:03, 185.26it/s, est. speed input: 60425.10 toks/s, output: 53.77 toks/s]

Processed prompts:  42%|████▏     | 420/1000 [00:06<00:02, 213.44it/s, est. speed input: 67552.37 toks/s, output: 60.09 toks/s]

Processed prompts:  46%|████▌     | 455/1000 [00:07<00:03, 169.66it/s, est. speed input: 69688.43 toks/s, output: 61.99 toks/s]

Processed prompts:  54%|█████▍    | 543/1000 [00:07<00:02, 194.84it/s, est. speed input: 79177.21 toks/s, output: 70.43 toks/s]

Processed prompts:  66%|██████▌   | 655/1000 [00:08<00:01, 229.61it/s, est. speed input: 91003.83 toks/s, output: 80.95 toks/s]

Processed prompts:  77%|███████▋  | 767/1000 [00:08<00:00, 292.64it/s, est. speed input: 103769.45 toks/s, output: 92.30 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:08<00:00, 112.96it/s, est. speed input: 127066.69 toks/s, output: 112.96 toks/s]

Models:  50%|█████     | 1/2 [02:31<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:12<?, ?it/s, seed=789]

Conditions:   0%|          | 0/7 [00:12<?, ?it/s, condition=similarity]

k:   0%|          | 0/2 [00:12<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:13<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:12<00:03,  3.02s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:12<00:03,  3.02s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=8 | similarity | seed=789: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 459.05it/s]

Rendering prompts:  14%|█▍        | 140/1000 [00:00<00:01, 464.31it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:01, 461.27it/s]

Rendering prompts:  33%|███▎      | 328/1000 [00:00<00:01, 460.68it/s]

Rendering prompts:  42%|████▏     | 422/1000 [00:00<00:01, 462.51it/s]

Rendering prompts:  52%|█████▏    | 516/1000 [00:01<00:01, 464.78it/s]

Rendering prompts:  61%|██████    | 610/1000 [00:01<00:00, 463.03it/s]

Rendering prompts:  70%|███████   | 705/1000 [00:01<00:00, 467.24it/s]

Rendering prompts:  80%|███████▉  | 799/1000 [00:01<00:00, 462.87it/s]

Rendering prompts:  90%|████████▉ | 895/1000 [00:01<00:00, 467.57it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 465.46it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1150.78it/s, est. speed input: 1294683.56 toks/s, output: 1150.95 toks/s]

Models:  50%|█████     | 1/2 [02:35<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:16<00:03,  3.02s/it, seed=1024]

Conditions:   0%|          | 0/7 [00:16<?, ?it/s, condition=similarity]

k:   0%|          | 0/2 [00:16<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:18<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:16<00:00,  3.32s/it, seed=1024]

Conditions:  43%|████▎     | 3/7 [00:16<00:21,  5.42s/it, condition=similarity]

Conditions:  43%|████▎     | 3/7 [00:16<00:21,  5.42s/it, condition=label_diversity]

Qwen2.5-7B-Instruct | anes | k=8 | similarity | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   5%|▍         | 47/1000 [00:00<00:02, 463.04it/s]

Rendering prompts:  14%|█▍        | 142/1000 [00:00<00:01, 468.06it/s]

Rendering prompts:  24%|██▍       | 238/1000 [00:00<00:01, 469.86it/s]

Rendering prompts:  33%|███▎      | 332/1000 [00:00<00:01, 461.85it/s]

Rendering prompts:  42%|████▎     | 425/1000 [00:00<00:01, 454.89it/s]

Rendering prompts:  52%|█████▏    | 518/1000 [00:01<00:01, 455.32it/s]

Rendering prompts:  61%|██████    | 611/1000 [00:01<00:00, 459.41it/s]

Rendering prompts:  71%|███████   | 707/1000 [00:01<00:00, 468.06it/s]

Rendering prompts:  80%|████████  | 803/1000 [00:01<00:00, 471.60it/s]

Rendering prompts:  90%|█████████ | 900/1000 [00:01<00:00, 476.58it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 467.44it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:46,  1.90it/s, est. speed input: 2141.90 toks/s, output: 1.90 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1255.20it/s, est. speed input: 1411154.33 toks/s, output: 1255.37 toks/s]

Models:  50%|█████     | 1/2 [02:39<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:04<?, ?it/s, seed=42]

Conditions:  43%|████▎     | 3/7 [00:20<00:21,  5.42s/it, condition=label_diversity]

k:   0%|          | 0/2 [00:20<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:22<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:04<00:17,  4.33s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:04<00:17,  4.33s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=8 | label_diversity | seed=42: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 458.72it/s]

Rendering prompts:  14%|█▍        | 140/1000 [00:00<00:02, 411.02it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:01, 441.80it/s]

Rendering prompts:  33%|███▎      | 328/1000 [00:00<00:01, 453.91it/s]

Rendering prompts:  42%|████▏     | 421/1000 [00:00<00:01, 457.70it/s]

Rendering prompts:  52%|█████▏    | 515/1000 [00:01<00:01, 459.61it/s]

Rendering prompts:  61%|██████    | 608/1000 [00:01<00:00, 455.34it/s]

Rendering prompts:  70%|███████   | 700/1000 [00:01<00:00, 449.55it/s]

Rendering prompts:  80%|███████▉  | 795/1000 [00:01<00:00, 459.60it/s]

Rendering prompts:  89%|████████▉ | 890/1000 [00:01<00:00, 461.63it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 455.34it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:41,  1.92it/s, est. speed input: 2162.81 toks/s, output: 1.92 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1263.09it/s, est. speed input: 1420006.12 toks/s, output: 1263.25 toks/s]

Models:  50%|█████     | 1/2 [02:44<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:08<00:17,  4.33s/it, seed=123]

Conditions:  43%|████▎     | 3/7 [00:24<00:21,  5.42s/it, condition=label_diversity]

k:   0%|          | 0/2 [00:25<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:26<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:08<00:13,  4.38s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:08<00:13,  4.38s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=8 | label_diversity | seed=123: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 456.98it/s]

Rendering prompts:  14%|█▍        | 140/1000 [00:00<00:01, 458.86it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:01, 459.77it/s]

Rendering prompts:  33%|███▎      | 326/1000 [00:00<00:01, 458.34it/s]

Rendering prompts:  42%|████▏     | 418/1000 [00:00<00:01, 431.93it/s]

Rendering prompts:  51%|█████     | 510/1000 [00:01<00:01, 444.63it/s]

Rendering prompts:  60%|██████    | 602/1000 [00:01<00:00, 451.30it/s]

Rendering prompts:  70%|██████▉   | 695/1000 [00:01<00:00, 453.13it/s]

Rendering prompts:  79%|███████▉  | 789/1000 [00:01<00:00, 457.06it/s]

Rendering prompts:  88%|████████▊ | 882/1000 [00:01<00:00, 420.33it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 445.50it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:57,  1.39it/s, est. speed input: 1576.94 toks/s, output: 1.39 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 993.67it/s, est. speed input: 1121066.74 toks/s, output: 993.77 toks/s]

Models:  50%|█████     | 1/2 [02:49<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:13<00:13,  4.38s/it, seed=456]

Conditions:  43%|████▎     | 3/7 [00:29<00:21,  5.42s/it, condition=label_diversity]

k:   0%|          | 0/2 [00:29<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:31<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:13<00:09,  4.50s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:13<00:09,  4.50s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=8 | label_diversity | seed=456: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 452.34it/s]

Rendering prompts:  14%|█▍        | 139/1000 [00:00<00:01, 455.30it/s]

Rendering prompts:  23%|██▎       | 233/1000 [00:00<00:01, 459.51it/s]

Rendering prompts:  33%|███▎      | 327/1000 [00:00<00:01, 458.64it/s]

Rendering prompts:  42%|████▏     | 419/1000 [00:00<00:01, 454.20it/s]

Rendering prompts:  56%|█████▌    | 557/1000 [00:01<00:00, 457.73it/s]

Rendering prompts:  65%|██████▍   | 649/1000 [00:01<00:00, 453.60it/s]

Rendering prompts:  74%|███████▍  | 742/1000 [00:01<00:00, 431.95it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:01<00:00, 448.12it/s]

Rendering prompts:  93%|█████████▎| 929/1000 [00:02<00:00, 453.39it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 452.88it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:20,  2.00it/s, est. speed input: 2261.24 toks/s, output: 2.00 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1266.88it/s, est. speed input: 1429355.49 toks/s, output: 1267.05 toks/s]

Models:  50%|█████     | 1/2 [02:53<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:17<00:09,  4.50s/it, seed=789]

Conditions:  43%|████▎     | 3/7 [00:34<00:21,  5.42s/it, condition=label_diversity]

k:   0%|          | 0/2 [00:34<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:35<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:17<00:04,  4.46s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:17<00:04,  4.46s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=8 | label_diversity | seed=789: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 456.53it/s]

Rendering prompts:  14%|█▍        | 139/1000 [00:00<00:01, 460.05it/s]

Rendering prompts:  23%|██▎       | 233/1000 [00:00<00:01, 461.07it/s]

Rendering prompts:  33%|███▎      | 327/1000 [00:00<00:01, 463.03it/s]

Rendering prompts:  42%|████▏     | 421/1000 [00:00<00:01, 458.75it/s]

Rendering prompts:  52%|█████▏    | 515/1000 [00:01<00:01, 459.86it/s]

Rendering prompts:  61%|██████    | 608/1000 [00:01<00:00, 460.41it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:01<00:00, 456.86it/s]

Rendering prompts:  80%|███████▉  | 796/1000 [00:01<00:00, 459.81it/s]

Rendering prompts:  89%|████████▉ | 890/1000 [00:01<00:00, 462.18it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 453.43it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:02,  1.38it/s, est. speed input: 1557.09 toks/s, output: 1.38 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 968.90it/s, est. speed input: 1086344.09 toks/s, output: 969.00 toks/s]

Models:  50%|█████     | 1/2 [02:58<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:22<00:04,  4.46s/it, seed=1024]

Conditions:  43%|████▎     | 3/7 [00:38<00:21,  5.42s/it, condition=label_diversity]

k:   0%|          | 0/2 [00:38<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:40<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:22<00:00,  4.53s/it, seed=1024]

Conditions:  57%|█████▋    | 4/7 [00:38<00:32, 10.91s/it, condition=label_diversity]

Conditions:  57%|█████▋    | 4/7 [00:38<00:32, 10.91s/it, condition=feature_range]

Qwen2.5-7B-Instruct | anes | k=8 | label_diversity | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   5%|▍         | 47/1000 [00:00<00:02, 460.83it/s]

Rendering prompts:  14%|█▍        | 141/1000 [00:00<00:01, 464.54it/s]

Rendering prompts:  24%|██▎       | 235/1000 [00:00<00:01, 464.87it/s]

Rendering prompts:  33%|███▎      | 331/1000 [00:00<00:01, 468.66it/s]

Rendering prompts:  43%|████▎     | 426/1000 [00:00<00:01, 461.56it/s]

Rendering prompts:  52%|█████▏    | 520/1000 [00:01<00:01, 462.91it/s]

Rendering prompts:  61%|██████▏   | 614/1000 [00:01<00:00, 465.77it/s]

Rendering prompts:  71%|███████   | 708/1000 [00:01<00:00, 457.28it/s]

Rendering prompts:  80%|████████  | 802/1000 [00:01<00:00, 462.07it/s]

Rendering prompts:  90%|████████▉ | 897/1000 [00:01<00:00, 466.23it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 463.80it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<10:20,  1.61it/s, est. speed input: 1805.83 toks/s, output: 1.61 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1073.22it/s, est. speed input: 1199034.07 toks/s, output: 1073.35 toks/s]

Models:  50%|█████     | 1/2 [03:08<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:10<?, ?it/s, seed=42]

Conditions:  57%|█████▋    | 4/7 [00:49<00:32, 10.91s/it, condition=feature_range]

k:   0%|          | 0/2 [00:49<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [00:50<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:10<00:41, 10.42s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:10<00:41, 10.42s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=8 | feature_range | seed=42: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 455.20it/s]

Rendering prompts:  14%|█▍        | 140/1000 [00:00<00:01, 464.00it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:01, 462.52it/s]

Rendering prompts:  33%|███▎      | 328/1000 [00:00<00:01, 462.08it/s]

Rendering prompts:  42%|████▏     | 422/1000 [00:00<00:01, 463.58it/s]

Rendering prompts:  52%|█████▏    | 516/1000 [00:01<00:01, 461.36it/s]

Rendering prompts:  61%|██████    | 610/1000 [00:01<00:00, 462.25it/s]

Rendering prompts:  70%|███████   | 704/1000 [00:01<00:00, 460.86it/s]

Rendering prompts:  80%|███████▉  | 798/1000 [00:01<00:00, 464.92it/s]

Rendering prompts:  89%|████████▉ | 892/1000 [00:01<00:00, 467.29it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 463.97it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:30,  1.96it/s, est. speed input: 2204.74 toks/s, output: 1.96 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1225.09it/s, est. speed input: 1373671.67 toks/s, output: 1225.30 toks/s]

Models:  50%|█████     | 1/2 [03:18<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:20<00:41, 10.42s/it, seed=123]

Conditions:  57%|█████▋    | 4/7 [00:59<00:32, 10.91s/it, condition=feature_range]

k:   0%|          | 0/2 [00:59<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:01<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:20<00:30, 10.29s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:20<00:30, 10.29s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=8 | feature_range | seed=123: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 453.83it/s]

Rendering prompts:  14%|█▍        | 140/1000 [00:00<00:01, 460.23it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:01, 455.20it/s]

Rendering prompts:  33%|███▎      | 326/1000 [00:00<00:01, 455.05it/s]

Rendering prompts:  46%|████▋     | 464/1000 [00:01<00:01, 457.36it/s]

Rendering prompts:  56%|█████▌    | 556/1000 [00:01<00:00, 455.57it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:01<00:00, 459.80it/s]

Rendering prompts:  74%|███████▍  | 744/1000 [00:01<00:00, 457.52it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:01<00:00, 455.77it/s]

Rendering prompts:  93%|█████████▎| 928/1000 [00:02<00:00, 455.97it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 456.95it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<07:48,  2.13it/s, est. speed input: 2427.10 toks/s, output: 2.13 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1236.56it/s, est. speed input: 1401334.17 toks/s, output: 1236.73 toks/s]

Models:  50%|█████     | 1/2 [03:28<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:30<00:30, 10.29s/it, seed=456]

Conditions:  57%|█████▋    | 4/7 [01:09<00:32, 10.91s/it, condition=feature_range]

k:   0%|          | 0/2 [01:09<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:11<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:30<00:20, 10.29s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:30<00:20, 10.29s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=8 | feature_range | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 28/1000 [00:00<00:03, 278.10it/s]

Rendering prompts:  12%|█▏        | 122/1000 [00:00<00:02, 423.66it/s]

Rendering prompts:  22%|██▏       | 216/1000 [00:00<00:01, 449.78it/s]

Rendering prompts:  31%|███       | 309/1000 [00:00<00:01, 453.09it/s]

Rendering prompts:  40%|████      | 403/1000 [00:00<00:01, 458.80it/s]

Rendering prompts:  50%|████▉     | 496/1000 [00:01<00:01, 459.49it/s]

Rendering prompts:  59%|█████▉    | 589/1000 [00:01<00:00, 457.97it/s]

Rendering prompts:  68%|██████▊   | 683/1000 [00:01<00:00, 460.66it/s]

Rendering prompts:  78%|███████▊  | 777/1000 [00:01<00:00, 459.16it/s]

Rendering prompts:  87%|████████▋ | 871/1000 [00:01<00:00, 462.49it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 453.47it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:40,  1.92it/s, est. speed input: 2166.94 toks/s, output: 1.92 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1214.21it/s, est. speed input: 1363870.03 toks/s, output: 1214.39 toks/s]

Models:  50%|█████     | 1/2 [03:39<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:41<00:20, 10.29s/it, seed=789]

Conditions:  57%|█████▋    | 4/7 [01:20<00:32, 10.91s/it, condition=feature_range]

k:   0%|          | 0/2 [01:20<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:21<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:41<00:10, 10.33s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:41<00:10, 10.33s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=8 | feature_range | seed=789: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 454.22it/s]

Rendering prompts:  14%|█▍        | 138/1000 [00:00<00:01, 456.30it/s]

Rendering prompts:  23%|██▎       | 231/1000 [00:00<00:01, 458.68it/s]

Rendering prompts:  32%|███▏      | 324/1000 [00:00<00:01, 456.05it/s]

Rendering prompts:  42%|████▏     | 416/1000 [00:00<00:01, 455.36it/s]

Rendering prompts:  51%|█████     | 509/1000 [00:01<00:01, 457.34it/s]

Rendering prompts:  60%|██████    | 602/1000 [00:01<00:00, 457.55it/s]

Rendering prompts:  70%|██████▉   | 696/1000 [00:01<00:00, 460.64it/s]

Rendering prompts:  79%|███████▉  | 790/1000 [00:01<00:00, 458.48it/s]

Rendering prompts:  88%|████████▊ | 884/1000 [00:01<00:00, 463.01it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 459.82it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<07:55,  2.10it/s, est. speed input: 2364.48 toks/s, output: 2.10 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1223.99it/s, est. speed input: 1372400.73 toks/s, output: 1224.16 toks/s]

Models:  50%|█████     | 1/2 [03:49<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:51<00:10, 10.33s/it, seed=1024]

Conditions:  57%|█████▋    | 4/7 [01:30<00:32, 10.91s/it, condition=feature_range]

k:   0%|          | 0/2 [01:30<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:32<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:51<00:00, 10.29s/it, seed=1024]

Conditions:  71%|███████▏  | 5/7 [01:30<00:47, 23.72s/it, condition=feature_range]

Conditions:  71%|███████▏  | 5/7 [01:30<00:47, 23.72s/it, condition=rule_diversity]

Qwen2.5-7B-Instruct | anes | k=8 | feature_range | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   4%|▍         | 44/1000 [00:00<00:02, 435.25it/s]

Rendering prompts:  13%|█▎        | 133/1000 [00:00<00:01, 442.94it/s]

Rendering prompts:  22%|██▎       | 225/1000 [00:00<00:01, 449.55it/s]

Rendering prompts:  32%|███▏      | 316/1000 [00:00<00:01, 449.25it/s]

Rendering prompts:  41%|████      | 407/1000 [00:00<00:01, 446.85it/s]

Rendering prompts:  50%|████▉     | 498/1000 [00:01<00:01, 449.31it/s]

Rendering prompts:  59%|█████▉    | 589/1000 [00:01<00:00, 447.01it/s]

Rendering prompts:  68%|██████▊   | 681/1000 [00:01<00:00, 452.09it/s]

Rendering prompts:  77%|███████▋  | 773/1000 [00:01<00:00, 450.80it/s]

Rendering prompts:  87%|████████▋ | 866/1000 [00:01<00:00, 452.90it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 450.46it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<09:19,  1.79it/s, est. speed input: 2047.15 toks/s, output: 1.79 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1212.67it/s, est. speed input: 1383950.39 toks/s, output: 1212.83 toks/s]

Models:  50%|█████     | 1/2 [03:55<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:05<?, ?it/s, seed=42]

Conditions:  71%|███████▏  | 5/7 [01:35<00:47, 23.72s/it, condition=rule_diversity]

k:   0%|          | 0/2 [01:35<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:37<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:05<00:21,  5.44s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:05<00:21,  5.44s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=8 | rule_diversity | seed=42: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 451.17it/s]

Rendering prompts:  14%|█▍        | 140/1000 [00:00<00:01, 459.85it/s]

Rendering prompts:  23%|██▎       | 232/1000 [00:00<00:01, 422.19it/s]

Rendering prompts:  32%|███▎      | 325/1000 [00:00<00:01, 442.51it/s]

Rendering prompts:  42%|████▏     | 417/1000 [00:00<00:01, 447.50it/s]

Rendering prompts:  51%|█████     | 508/1000 [00:01<00:01, 449.18it/s]

Rendering prompts:  60%|██████    | 600/1000 [00:01<00:00, 452.36it/s]

Rendering prompts:  69%|██████▉   | 692/1000 [00:01<00:00, 451.75it/s]

Rendering prompts:  78%|███████▊  | 785/1000 [00:01<00:00, 456.07it/s]

Rendering prompts:  88%|████████▊ | 879/1000 [00:01<00:00, 459.86it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 452.01it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:17,  2.01it/s, est. speed input: 2285.10 toks/s, output: 2.01 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1241.78it/s, est. speed input: 1405989.75 toks/s, output: 1241.94 toks/s]

Models:  50%|█████     | 1/2 [04:00<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:10<00:21,  5.44s/it, seed=123]

Conditions:  71%|███████▏  | 5/7 [01:41<00:47, 23.72s/it, condition=rule_diversity]

k:   0%|          | 0/2 [01:41<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:42<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:10<00:16,  5.42s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:10<00:16,  5.42s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=8 | rule_diversity | seed=123: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 451.30it/s]

Rendering prompts:  14%|█▍        | 139/1000 [00:00<00:01, 458.01it/s]

Rendering prompts:  23%|██▎       | 232/1000 [00:00<00:01, 455.98it/s]

Rendering prompts:  33%|███▎      | 326/1000 [00:00<00:01, 459.01it/s]

Rendering prompts:  42%|████▏     | 420/1000 [00:00<00:01, 460.51it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:01, 415.23it/s]

Rendering prompts:  60%|██████    | 605/1000 [00:01<00:00, 434.95it/s]

Rendering prompts:  70%|██████▉   | 699/1000 [00:01<00:00, 447.61it/s]

Rendering prompts:  79%|███████▉  | 792/1000 [00:01<00:00, 451.31it/s]

Rendering prompts:  89%|████████▊ | 886/1000 [00:01<00:00, 456.70it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 450.82it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<07:48,  2.13it/s, est. speed input: 2432.70 toks/s, output: 2.13 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1279.56it/s, est. speed input: 1452621.83 toks/s, output: 1279.74 toks/s]

Models:  50%|█████     | 1/2 [04:05<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:16<00:16,  5.42s/it, seed=456]

Conditions:  71%|███████▏  | 5/7 [01:46<00:47, 23.72s/it, condition=rule_diversity]

k:   0%|          | 0/2 [01:46<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:48<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:16<00:10,  5.40s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:16<00:10,  5.40s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=8 | rule_diversity | seed=456: 1000 rows

Rendering prompts:   4%|▍         | 45/1000 [00:00<00:02, 443.88it/s]

Rendering prompts:  14%|█▎        | 137/1000 [00:00<00:01, 450.72it/s]

Rendering prompts:  23%|██▎       | 229/1000 [00:00<00:01, 452.88it/s]

Rendering prompts:  32%|███▏      | 321/1000 [00:00<00:01, 450.75it/s]

Rendering prompts:  41%|████▏     | 413/1000 [00:00<00:01, 454.17it/s]

Rendering prompts:  50%|█████     | 505/1000 [00:01<00:01, 450.09it/s]

Rendering prompts:  60%|█████▉    | 597/1000 [00:01<00:00, 448.94it/s]

Rendering prompts:  69%|██████▉   | 689/1000 [00:01<00:00, 452.11it/s]

Rendering prompts:  78%|███████▊  | 781/1000 [00:01<00:00, 447.11it/s]

Rendering prompts:  87%|████████▋ | 872/1000 [00:01<00:00, 410.26it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 442.40it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<07:51,  2.12it/s, est. speed input: 2416.03 toks/s, output: 2.12 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1272.71it/s, est. speed input: 1444863.77 toks/s, output: 1272.90 toks/s]

Models:  50%|█████     | 1/2 [04:11<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:21<00:10,  5.40s/it, seed=789]

Conditions:  71%|███████▏  | 5/7 [01:51<00:47, 23.72s/it, condition=rule_diversity]

k:   0%|          | 0/2 [01:51<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:53<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:21<00:05,  5.41s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:21<00:05,  5.41s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=8 | rule_diversity | seed=789: 1000 rows

Rendering prompts:   4%|▍         | 45/1000 [00:00<00:02, 447.51it/s]

Rendering prompts:  14%|█▎        | 136/1000 [00:00<00:01, 451.93it/s]

Rendering prompts:  23%|██▎       | 229/1000 [00:00<00:01, 455.20it/s]

Rendering prompts:  32%|███▏      | 321/1000 [00:00<00:01, 457.24it/s]

Rendering prompts:  41%|████▏     | 413/1000 [00:00<00:01, 455.07it/s]

Rendering prompts:  50%|█████     | 505/1000 [00:01<00:01, 451.38it/s]

Rendering prompts:  60%|█████▉    | 597/1000 [00:01<00:00, 449.07it/s]

Rendering prompts:  69%|██████▉   | 689/1000 [00:01<00:00, 451.91it/s]

Rendering prompts:  78%|███████▊  | 781/1000 [00:01<00:00, 455.07it/s]

Rendering prompts:  87%|████████▋ | 873/1000 [00:01<00:00, 451.15it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 452.60it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:29,  1.96it/s, est. speed input: 2236.18 toks/s, output: 1.96 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1212.18it/s, est. speed input: 1376128.63 toks/s, output: 1212.35 toks/s]

Models:  50%|█████     | 1/2 [04:16<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:27<00:05,  5.41s/it, seed=1024]

Conditions:  71%|███████▏  | 5/7 [01:57<00:47, 23.72s/it, condition=rule_diversity]

k:   0%|          | 0/2 [01:57<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [01:59<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:27<00:00,  5.42s/it, seed=1024]

Conditions:  86%|████████▌ | 6/7 [01:57<00:24, 24.77s/it, condition=rule_diversity]

Conditions:  86%|████████▌ | 6/7 [01:57<00:24, 24.77s/it, condition=counter_spurious]

Qwen2.5-7B-Instruct | anes | k=8 | rule_diversity | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 453.25it/s]

Rendering prompts:  14%|█▍        | 138/1000 [00:00<00:01, 450.96it/s]

Rendering prompts:  23%|██▎       | 231/1000 [00:00<00:01, 456.53it/s]

Rendering prompts:  32%|███▎      | 325/1000 [00:00<00:01, 458.82it/s]

Rendering prompts:  42%|████▏     | 417/1000 [00:00<00:01, 452.40it/s]

Rendering prompts:  51%|█████     | 510/1000 [00:01<00:01, 456.35it/s]

Rendering prompts:  60%|██████    | 604/1000 [00:01<00:00, 460.04it/s]

Rendering prompts:  70%|██████▉   | 698/1000 [00:01<00:00, 460.48it/s]

Rendering prompts:  79%|███████▉  | 792/1000 [00:01<00:00, 464.28it/s]

Rendering prompts:  89%|████████▊ | 887/1000 [00:01<00:00, 463.68it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 460.23it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:23,  1.98it/s, est. speed input: 2233.94 toks/s, output: 1.98 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1233.20it/s, est. speed input: 1382739.45 toks/s, output: 1233.38 toks/s]

Models:  50%|█████     | 1/2 [04:21<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:04<?, ?it/s, seed=42]

Conditions:  86%|████████▌ | 6/7 [02:02<00:24, 24.77s/it, condition=counter_spurious]

k:   0%|          | 0/2 [02:02<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [02:03<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:04<00:19,  4.75s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:04<00:19,  4.75s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=8 | counter_spurious | seed=42: 1000 rows

Rendering prompts:   4%|▍         | 45/1000 [00:00<00:02, 447.81it/s]

Rendering prompts:  14%|█▎        | 137/1000 [00:00<00:01, 452.66it/s]

Rendering prompts:  23%|██▎       | 229/1000 [00:00<00:01, 448.47it/s]

Rendering prompts:  32%|███▏      | 321/1000 [00:00<00:01, 451.39it/s]

Rendering prompts:  41%|████▏     | 413/1000 [00:00<00:01, 454.29it/s]

Rendering prompts:  50%|█████     | 505/1000 [00:01<00:01, 453.16it/s]

Rendering prompts:  60%|█████▉    | 597/1000 [00:01<00:00, 454.43it/s]

Rendering prompts:  69%|██████▉   | 689/1000 [00:01<00:00, 452.80it/s]

Rendering prompts:  78%|███████▊  | 783/1000 [00:01<00:00, 457.90it/s]

Rendering prompts:  88%|████████▊ | 876/1000 [00:01<00:00, 424.80it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 449.51it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<08:48,  1.89it/s, est. speed input: 2144.50 toks/s, output: 1.89 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1218.46it/s, est. speed input: 1375937.75 toks/s, output: 1218.62 toks/s]

Models:  50%|█████     | 1/2 [04:26<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:09<00:19,  4.75s/it, seed=123]

Conditions:  86%|████████▌ | 6/7 [02:06<00:24, 24.77s/it, condition=counter_spurious]

k:   0%|          | 0/2 [02:06<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [02:08<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:09<00:14,  4.79s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:09<00:14,  4.79s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=8 | counter_spurious | seed=123: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 450.81it/s]

Rendering prompts:  14%|█▍        | 138/1000 [00:00<00:01, 456.29it/s]

Rendering prompts:  23%|██▎       | 230/1000 [00:00<00:01, 452.02it/s]

Rendering prompts:  32%|███▏      | 323/1000 [00:00<00:01, 454.25it/s]

Rendering prompts:  42%|████▏     | 415/1000 [00:00<00:01, 454.03it/s]

Rendering prompts:  51%|█████     | 508/1000 [00:01<00:01, 454.27it/s]

Rendering prompts:  60%|██████    | 602/1000 [00:01<00:00, 458.80it/s]

Rendering prompts:  70%|██████▉   | 696/1000 [00:01<00:00, 461.61it/s]

Rendering prompts:  79%|███████▉  | 790/1000 [00:01<00:00, 459.51it/s]

Rendering prompts:  88%|████████▊ | 884/1000 [00:01<00:00, 463.72it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 458.23it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<07:47,  2.14it/s, est. speed input: 2400.94 toks/s, output: 2.14 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1237.35it/s, est. speed input: 1384893.70 toks/s, output: 1237.51 toks/s]

Models:  50%|█████     | 1/2 [04:31<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:14<00:14,  4.79s/it, seed=456]

Conditions:  86%|████████▌ | 6/7 [02:11<00:24, 24.77s/it, condition=counter_spurious]

k:   0%|          | 0/2 [02:11<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [02:13<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:14<00:09,  4.78s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:14<00:09,  4.78s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=8 | counter_spurious | seed=456: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 450.50it/s]

Rendering prompts:  14%|█▍        | 139/1000 [00:00<00:01, 455.16it/s]

Rendering prompts:  23%|██▎       | 233/1000 [00:00<00:01, 458.50it/s]

Rendering prompts:  33%|███▎      | 326/1000 [00:00<00:01, 455.61it/s]

Rendering prompts:  42%|████▏     | 418/1000 [00:00<00:01, 454.85it/s]

Rendering prompts:  51%|█████     | 510/1000 [00:01<00:01, 455.02it/s]

Rendering prompts:  60%|██████    | 602/1000 [00:01<00:00, 452.93it/s]

Rendering prompts:  69%|██████▉   | 694/1000 [00:01<00:00, 455.64it/s]

Rendering prompts:  79%|███████▊  | 787/1000 [00:01<00:00, 454.79it/s]

Rendering prompts:  88%|████████▊ | 881/1000 [00:01<00:00, 459.35it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 457.04it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<09:47,  1.70it/s, est. speed input: 1908.11 toks/s, output: 1.70 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1072.55it/s, est. speed input: 1199353.62 toks/s, output: 1072.68 toks/s]

Models:  50%|█████     | 1/2 [04:35<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:19<00:09,  4.78s/it, seed=789]

Conditions:  86%|████████▌ | 6/7 [02:16<00:24, 24.77s/it, condition=counter_spurious]

k:   0%|          | 0/2 [02:16<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [02:18<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:19<00:04,  4.82s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:19<00:04,  4.82s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=8 | counter_spurious | seed=789: 1000 rows

Rendering prompts:   5%|▍         | 46/1000 [00:00<00:02, 450.98it/s]

Rendering prompts:  14%|█▍        | 138/1000 [00:00<00:01, 453.34it/s]

Rendering prompts:  23%|██▎       | 230/1000 [00:00<00:01, 455.52it/s]

Rendering prompts:  32%|███▏      | 322/1000 [00:00<00:01, 450.73it/s]

Rendering prompts:  41%|████▏     | 414/1000 [00:00<00:01, 452.21it/s]

Rendering prompts:  51%|█████     | 506/1000 [00:01<00:01, 454.78it/s]

Rendering prompts:  60%|█████▉    | 599/1000 [00:01<00:00, 454.04it/s]

Rendering prompts:  69%|██████▉   | 692/1000 [00:01<00:00, 457.82it/s]

Rendering prompts:  79%|███████▊  | 786/1000 [00:01<00:00, 461.09it/s]

Rendering prompts:  88%|████████▊ | 880/1000 [00:01<00:00, 459.85it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:02<00:00, 456.94it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<07:53,  2.11it/s, est. speed input: 2373.97 toks/s, output: 2.11 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:00<00:00, 1268.75it/s, est. speed input: 1420052.68 toks/s, output: 1268.93 toks/s]

Models:  50%|█████     | 1/2 [04:40<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:23<00:04,  4.82s/it, seed=1024]

Conditions:  86%|████████▌ | 6/7 [02:21<00:24, 24.77s/it, condition=counter_spurious]

k:   0%|          | 0/2 [02:21<?, ?it/s, k=8]

Datasets:  75%|███████▌  | 3/4 [02:23<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:23<00:00,  4.80s/it, seed=1024]

Conditions: 100%|██████████| 7/7 [02:21<00:00, 24.53s/it, condition=counter_spurious]

k:  50%|█████     | 1/2 [02:21<02:21, 141.31s/it, k=8]

k:  50%|█████     | 1/2 [02:21<02:21, 141.31s/it, k=16]

Qwen2.5-7B-Instruct | anes | k=8 | counter_spurious | seed=1024: 1000 rows

Conditions:   0%|          | 0/7 [00:00<?, ?it/s]

Conditions:   0%|          | 0/7 [00:00<?, ?it/s, condition=random]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 267.98it/s]

Rendering prompts:   8%|▊         | 83/1000 [00:00<00:03, 273.85it/s]

Rendering prompts:  14%|█▍        | 139/1000 [00:00<00:03, 271.66it/s]

Rendering prompts:  20%|█▉        | 195/1000 [00:00<00:03, 259.37it/s]

Rendering prompts:  25%|██▌       | 251/1000 [00:00<00:02, 268.86it/s]

Rendering prompts:  31%|███       | 307/1000 [00:01<00:02, 274.19it/s]

Rendering prompts:  36%|███▋      | 363/1000 [00:01<00:02, 276.80it/s]

Rendering prompts:  42%|████▏     | 419/1000 [00:01<00:02, 273.93it/s]

Rendering prompts:  48%|████▊     | 475/1000 [00:01<00:01, 274.25it/s]

Rendering prompts:  53%|█████▎    | 531/1000 [00:01<00:01, 275.27it/s]

Rendering prompts:  59%|█████▊    | 587/1000 [00:02<00:01, 275.31it/s]

Rendering prompts:  64%|██████▍   | 643/1000 [00:02<00:01, 269.87it/s]

Rendering prompts:  70%|██████▉   | 699/1000 [00:02<00:01, 271.32it/s]

Rendering prompts:  76%|███████▌  | 755/1000 [00:02<00:00, 273.61it/s]

Rendering prompts:  81%|████████  | 811/1000 [00:02<00:00, 274.99it/s]

Rendering prompts:  87%|████████▋ | 867/1000 [00:03<00:00, 275.02it/s]

Rendering prompts:  92%|█████████▏| 923/1000 [00:03<00:00, 272.53it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 271.95it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:09,  1.37it/s, est. speed input: 2861.73 toks/s, output: 1.37 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 857.25it/s, est. speed input: 1788478.08 toks/s, output: 857.33 toks/s]

Models:  50%|█████     | 1/2 [04:47<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:06<?, ?it/s, seed=42]

Conditions:   0%|          | 0/7 [00:06<?, ?it/s, condition=random]

k:  50%|█████     | 1/2 [02:27<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [02:29<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:06<00:25,  6.48s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:06<00:25,  6.48s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=16 | random | seed=42: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 256.56it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 260.63it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 262.32it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 258.70it/s]

Rendering prompts:  24%|██▍       | 241/1000 [00:00<00:02, 259.63it/s]

Rendering prompts:  29%|██▉       | 294/1000 [00:01<00:02, 259.92it/s]

Rendering prompts:  35%|███▍      | 348/1000 [00:01<00:02, 260.39it/s]

Rendering prompts:  40%|████      | 402/1000 [00:01<00:02, 260.98it/s]

Rendering prompts:  46%|████▌     | 456/1000 [00:01<00:02, 226.88it/s]

Rendering prompts:  51%|█████     | 510/1000 [00:02<00:02, 242.93it/s]

Rendering prompts:  56%|█████▋    | 564/1000 [00:02<00:01, 252.98it/s]

Rendering prompts:  62%|██████▏   | 619/1000 [00:02<00:01, 261.39it/s]

Rendering prompts:  68%|██████▊   | 675/1000 [00:02<00:01, 267.95it/s]

Rendering prompts:  73%|███████▎  | 730/1000 [00:02<00:01, 268.32it/s]

Rendering prompts:  79%|███████▊  | 786/1000 [00:03<00:00, 269.63it/s]

Rendering prompts:  84%|████████▍ | 842/1000 [00:03<00:00, 270.96it/s]

Rendering prompts:  90%|████████▉ | 898/1000 [00:03<00:00, 271.20it/s]

Rendering prompts:  95%|█████████▌| 954/1000 [00:03<00:00, 268.03it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 261.26it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:09,  1.49it/s, est. speed input: 3127.87 toks/s, output: 1.49 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 874.33it/s, est. speed input: 1827610.48 toks/s, output: 874.41 toks/s]

Models:  50%|█████     | 1/2 [04:53<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:13<00:25,  6.48s/it, seed=123]

Conditions:   0%|          | 0/7 [00:13<?, ?it/s, condition=random]

k:  50%|█████     | 1/2 [02:34<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [02:36<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:13<00:19,  6.57s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:13<00:19,  6.57s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=16 | random | seed=123: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 259.08it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 264.53it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 227.10it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 248.07it/s]

Rendering prompts:  24%|██▍       | 241/1000 [00:00<00:02, 253.79it/s]

Rendering prompts:  30%|██▉       | 295/1000 [00:01<00:02, 261.70it/s]

Rendering prompts:  35%|███▍      | 349/1000 [00:01<00:02, 264.26it/s]

Rendering prompts:  40%|████      | 403/1000 [00:01<00:02, 265.47it/s]

Rendering prompts:  46%|████▌     | 457/1000 [00:01<00:02, 265.71it/s]

Rendering prompts:  51%|█████     | 511/1000 [00:01<00:01, 264.04it/s]

Rendering prompts:  56%|█████▋    | 565/1000 [00:02<00:01, 266.29it/s]

Rendering prompts:  62%|██████▏   | 619/1000 [00:02<00:01, 267.47it/s]

Rendering prompts:  67%|██████▋   | 674/1000 [00:02<00:01, 269.05it/s]

Rendering prompts:  73%|███████▎  | 728/1000 [00:02<00:01, 265.82it/s]

Rendering prompts:  78%|███████▊  | 782/1000 [00:03<00:00, 245.17it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:03<00:00, 256.88it/s]

Rendering prompts:  89%|████████▉ | 892/1000 [00:03<00:00, 263.45it/s]

Rendering prompts:  95%|█████████▍| 948/1000 [00:03<00:00, 267.14it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 260.46it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<13:15,  1.26it/s, est. speed input: 2637.70 toks/s, output: 1.26 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 771.22it/s, est. speed input: 1616712.40 toks/s, output: 771.30 toks/s]

Models:  50%|█████     | 1/2 [05:00<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:19<00:19,  6.57s/it, seed=456]

Conditions:   0%|          | 0/7 [00:19<?, ?it/s, condition=random]

k:  50%|█████     | 1/2 [02:41<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [02:43<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:19<00:13,  6.68s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:19<00:13,  6.68s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=16 | random | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 260.31it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 262.37it/s]

Rendering prompts:  14%|█▎        | 135/1000 [00:00<00:03, 265.05it/s]

Rendering prompts:  19%|█▉        | 189/1000 [00:00<00:03, 265.43it/s]

Rendering prompts:  24%|██▍       | 243/1000 [00:00<00:02, 265.41it/s]

Rendering prompts:  30%|██▉       | 297/1000 [00:01<00:02, 266.13it/s]

Rendering prompts:  35%|███▌      | 351/1000 [00:01<00:02, 263.34it/s]

Rendering prompts:  40%|████      | 405/1000 [00:01<00:02, 264.47it/s]

Rendering prompts:  46%|████▌     | 459/1000 [00:01<00:02, 264.41it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:01, 264.48it/s]

Rendering prompts:  57%|█████▋    | 567/1000 [00:02<00:01, 261.54it/s]

Rendering prompts:  62%|██████▏   | 621/1000 [00:02<00:01, 264.12it/s]

Rendering prompts:  68%|██████▊   | 675/1000 [00:02<00:01, 265.59it/s]

Rendering prompts:  73%|███████▎  | 729/1000 [00:02<00:01, 266.17it/s]

Rendering prompts:  78%|███████▊  | 783/1000 [00:02<00:00, 266.68it/s]

Rendering prompts:  84%|████████▎ | 837/1000 [00:03<00:00, 264.53it/s]

Rendering prompts:  89%|████████▉ | 891/1000 [00:03<00:00, 266.08it/s]

Rendering prompts:  94%|█████████▍| 945/1000 [00:03<00:00, 266.63it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 264.95it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:49,  1.41it/s, est. speed input: 2952.00 toks/s, output: 1.41 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 841.29it/s, est. speed input: 1759388.10 toks/s, output: 841.37 toks/s]

Models:  50%|█████     | 1/2 [05:07<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:26<00:13,  6.68s/it, seed=789]

Conditions:   0%|          | 0/7 [00:26<?, ?it/s, condition=random]

k:  50%|█████     | 1/2 [02:47<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [02:49<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:26<00:06,  6.67s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:26<00:06,  6.67s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=16 | random | seed=789: 1000 rows

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 261.12it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 264.84it/s]

Rendering prompts:  14%|█▎        | 135/1000 [00:00<00:03, 264.04it/s]

Rendering prompts:  19%|█▉        | 189/1000 [00:00<00:03, 266.22it/s]

Rendering prompts:  24%|██▍       | 243/1000 [00:00<00:02, 266.79it/s]

Rendering prompts:  30%|██▉       | 297/1000 [00:01<00:02, 267.26it/s]

Rendering prompts:  35%|███▌      | 351/1000 [00:01<00:02, 267.10it/s]

Rendering prompts:  40%|████      | 405/1000 [00:01<00:02, 263.96it/s]

Rendering prompts:  46%|████▌     | 459/1000 [00:01<00:02, 264.69it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:01, 265.25it/s]

Rendering prompts:  57%|█████▋    | 567/1000 [00:02<00:01, 265.14it/s]

Rendering prompts:  62%|██████▏   | 621/1000 [00:02<00:01, 261.71it/s]

Rendering prompts:  68%|██████▊   | 675/1000 [00:02<00:01, 265.28it/s]

Rendering prompts:  73%|███████▎  | 729/1000 [00:02<00:01, 266.56it/s]

Rendering prompts:  78%|███████▊  | 783/1000 [00:02<00:00, 267.41it/s]

Rendering prompts:  84%|████████▎ | 837/1000 [00:03<00:00, 267.13it/s]

Rendering prompts:  89%|████████▉ | 891/1000 [00:03<00:00, 264.45it/s]

Rendering prompts:  94%|█████████▍| 945/1000 [00:03<00:00, 266.38it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 265.76it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:20,  1.35it/s, est. speed input: 2821.26 toks/s, output: 1.35 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 845.37it/s, est. speed input: 1763689.29 toks/s, output: 845.45 toks/s]

Models:  50%|█████     | 1/2 [05:13<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:33<00:06,  6.67s/it, seed=1024]

Conditions:   0%|          | 0/7 [00:33<?, ?it/s, condition=random]

k:  50%|█████     | 1/2 [02:54<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [02:56<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:33<00:00,  6.64s/it, seed=1024]

Conditions:  29%|██▊       | 2/7 [00:33<01:22, 16.59s/it, condition=random]

Conditions:  29%|██▊       | 2/7 [00:33<01:22, 16.59s/it, condition=similarity]

Qwen2.5-7B-Instruct | anes | k=16 | random | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 250.40it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 254.89it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 255.39it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 254.83it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:02, 255.50it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:02, 256.20it/s]

Rendering prompts:  34%|███▍      | 338/1000 [00:01<00:02, 256.10it/s]

Rendering prompts:  39%|███▉      | 390/1000 [00:01<00:02, 250.79it/s]

Rendering prompts:  44%|████▍     | 442/1000 [00:01<00:02, 252.62it/s]

Rendering prompts:  49%|████▉     | 494/1000 [00:01<00:01, 253.36it/s]

Rendering prompts:  55%|█████▍    | 546/1000 [00:02<00:01, 253.39it/s]

Rendering prompts:  60%|█████▉    | 598/1000 [00:02<00:01, 254.24it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:02<00:01, 251.81it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:02<00:01, 253.14it/s]

Rendering prompts:  75%|███████▌  | 754/1000 [00:02<00:00, 254.28it/s]

Rendering prompts:  81%|████████  | 806/1000 [00:03<00:00, 253.54it/s]

Rendering prompts:  86%|████████▌ | 858/1000 [00:03<00:00, 254.11it/s]

Rendering prompts:  91%|█████████ | 910/1000 [00:03<00:00, 250.02it/s]

Rendering prompts:  96%|█████████▌| 962/1000 [00:03<00:00, 252.93it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 254.25it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   2%|▏         | 16/1000 [00:00<00:19, 51.59it/s, est. speed input: 92549.30 toks/s, output: 44.26 toks/s]

Processed prompts:   5%|▍         | 49/1000 [00:00<00:11, 79.84it/s, est. speed input: 142010.32 toks/s, output: 68.09 toks/s]

Processed prompts:   9%|▉         | 91/1000 [00:01<00:08, 102.36it/s, est. speed input: 176303.51 toks/s, output: 84.58 toks/s]

Processed prompts:  13%|█▎        | 132/1000 [00:01<00:07, 109.59it/s, est. speed input: 192726.91 toks/s, output: 92.46 toks/s]

Processed prompts:  18%|█▊        | 178/1000 [00:01<00:06, 120.83it/s, est. speed input: 208326.12 toks/s, output: 99.91 toks/s]

Processed prompts:  24%|██▎       | 235/1000 [00:02<00:05, 143.96it/s, est. speed input: 229129.62 toks/s, output: 109.90 toks/s]

Processed prompts:  30%|██▉       | 295/1000 [00:02<00:04, 160.02it/s, est. speed input: 246738.17 toks/s, output: 118.40 toks/s]

Processed prompts:  35%|███▌      | 352/1000 [00:02<00:03, 163.09it/s, est. speed input: 257645.20 toks/s, output: 123.66 toks/s]

Processed prompts:  42%|████▏     | 417/1000 [00:03<00:03, 178.47it/s, est. speed input: 271974.51 toks/s, output: 130.45 toks/s]

Processed prompts:  44%|████▍     | 438/1000 [00:03<00:04, 121.55it/s, est. speed input: 256489.39 toks/s, output: 123.04 toks/s]

Processed prompts:  52%|█████▏    | 523/1000 [00:03<00:02, 164.38it/s, est. speed input: 276650.90 toks/s, output: 132.72 toks/s]

Processed prompts:  57%|█████▋    | 570/1000 [00:04<00:02, 146.51it/s, est. speed input: 276515.99 toks/s, output: 132.66 toks/s]

Processed prompts:  60%|█████▉    | 597/1000 [00:04<00:02, 145.27it/s, est. speed input: 277385.03 toks/s, output: 133.07 toks/s]

Processed prompts:  67%|██████▋   | 673/1000 [00:04<00:01, 184.84it/s, est. speed input: 290403.63 toks/s, output: 139.31 toks/s]

Processed prompts:  74%|███████▍  | 740/1000 [00:05<00:01, 187.84it/s, est. speed input: 297399.87 toks/s, output: 142.65 toks/s]

Processed prompts:  80%|████████  | 802/1000 [00:05<00:01, 179.98it/s, est. speed input: 301977.10 toks/s, output: 144.83 toks/s]

Processed prompts:  87%|████████▋ | 868/1000 [00:05<00:00, 182.69it/s, est. speed input: 306881.70 toks/s, output: 147.17 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:06<00:00, 159.36it/s, est. speed input: 332405.23 toks/s, output: 159.37 toks/s]

Models:  50%|█████     | 1/2 [05:25<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:11<?, ?it/s, seed=42]

Conditions:  29%|██▊       | 2/7 [00:44<01:22, 16.59s/it, condition=similarity]

k:  50%|█████     | 1/2 [03:06<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:08<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:11<00:47, 11.82s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:11<00:47, 11.82s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=16 | similarity | seed=42: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 251.64it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 255.04it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 250.83it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 253.36it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:03, 254.30it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:02, 251.08it/s]

Rendering prompts:  34%|███▍      | 338/1000 [00:01<00:02, 253.66it/s]

Rendering prompts:  39%|███▉      | 390/1000 [00:01<00:02, 254.35it/s]

Rendering prompts:  44%|████▍     | 442/1000 [00:01<00:02, 254.90it/s]

Rendering prompts:  49%|████▉     | 494/1000 [00:01<00:01, 254.82it/s]

Rendering prompts:  55%|█████▍    | 546/1000 [00:02<00:01, 251.13it/s]

Rendering prompts:  60%|█████▉    | 598/1000 [00:02<00:01, 254.37it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:02<00:01, 255.11it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:02<00:01, 254.90it/s]

Rendering prompts:  75%|███████▌  | 754/1000 [00:02<00:00, 254.09it/s]

Rendering prompts:  81%|████████  | 806/1000 [00:03<00:00, 251.45it/s]

Rendering prompts:  86%|████████▌ | 858/1000 [00:03<00:00, 253.87it/s]

Rendering prompts:  91%|█████████ | 910/1000 [00:03<00:00, 254.13it/s]

Rendering prompts:  96%|█████████▌| 962/1000 [00:03<00:00, 255.43it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 253.99it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 757.40it/s, est. speed input: 1579950.40 toks/s, output: 757.48 toks/s]

Models:  50%|█████     | 1/2 [05:32<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:18<00:47, 11.82s/it, seed=123]

Conditions:  29%|██▊       | 2/7 [00:51<01:22, 16.59s/it, condition=similarity]

k:  50%|█████     | 1/2 [03:13<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:14<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:18<00:26,  8.89s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:18<00:26,  8.89s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=16 | similarity | seed=123: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 259.22it/s]

Rendering prompts:   8%|▊         | 79/1000 [00:00<00:03, 260.25it/s]

Rendering prompts:  13%|█▎        | 133/1000 [00:00<00:03, 262.51it/s]

Rendering prompts:  19%|█▊        | 187/1000 [00:00<00:03, 264.46it/s]

Rendering prompts:  24%|██▍       | 241/1000 [00:00<00:02, 264.51it/s]

Rendering prompts:  30%|██▉       | 295/1000 [00:01<00:02, 261.51it/s]

Rendering prompts:  35%|███▍      | 349/1000 [00:01<00:02, 263.66it/s]

Rendering prompts:  40%|████      | 403/1000 [00:01<00:02, 263.66it/s]

Rendering prompts:  46%|████▌     | 457/1000 [00:01<00:02, 263.71it/s]

Rendering prompts:  51%|█████     | 511/1000 [00:01<00:01, 263.82it/s]

Rendering prompts:  56%|█████▋    | 565/1000 [00:02<00:01, 262.13it/s]

Rendering prompts:  62%|██████▏   | 619/1000 [00:02<00:01, 265.00it/s]

Rendering prompts:  67%|██████▋   | 673/1000 [00:02<00:01, 266.01it/s]

Rendering prompts:  73%|███████▎  | 727/1000 [00:02<00:01, 266.20it/s]

Rendering prompts:  78%|███████▊  | 781/1000 [00:02<00:00, 264.15it/s]

Rendering prompts:  84%|████████▎ | 835/1000 [00:03<00:00, 265.89it/s]

Rendering prompts:  89%|████████▉ | 889/1000 [00:03<00:00, 266.14it/s]

Rendering prompts:  94%|█████████▍| 943/1000 [00:03<00:00, 267.30it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 264.65it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 800.27it/s, est. speed input: 1669381.11 toks/s, output: 800.35 toks/s]

Models:  50%|█████     | 1/2 [05:39<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:25<00:26,  8.89s/it, seed=456]

Conditions:  29%|██▊       | 2/7 [00:58<01:22, 16.59s/it, condition=similarity]

k:  50%|█████     | 1/2 [03:19<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:21<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:25<00:15,  7.85s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:25<00:15,  7.85s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=16 | similarity | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 252.86it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 255.09it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 236.85it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 248.51it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:03, 253.33it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:02, 256.00it/s]

Rendering prompts:  34%|███▍      | 338/1000 [00:01<00:02, 253.69it/s]

Rendering prompts:  39%|███▉      | 390/1000 [00:01<00:02, 254.87it/s]

Rendering prompts:  44%|████▍     | 442/1000 [00:01<00:02, 256.17it/s]

Rendering prompts:  49%|████▉     | 494/1000 [00:01<00:01, 256.22it/s]

Rendering prompts:  55%|█████▍    | 546/1000 [00:02<00:01, 256.99it/s]

Rendering prompts:  60%|█████▉    | 598/1000 [00:02<00:01, 254.88it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:02<00:01, 255.73it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:02<00:01, 255.85it/s]

Rendering prompts:  75%|███████▌  | 754/1000 [00:02<00:00, 256.36it/s]

Rendering prompts:  81%|████████  | 806/1000 [00:03<00:00, 256.07it/s]

Rendering prompts:  86%|████████▌ | 858/1000 [00:03<00:00, 254.42it/s]

Rendering prompts:  91%|█████████ | 910/1000 [00:03<00:00, 254.37it/s]

Rendering prompts:  96%|█████████▌| 962/1000 [00:03<00:00, 256.53it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 254.00it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 806.96it/s, est. speed input: 1683354.67 toks/s, output: 807.05 toks/s]

Models:  50%|█████     | 1/2 [05:45<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:32<00:15,  7.85s/it, seed=789]

Conditions:  29%|██▊       | 2/7 [01:05<01:22, 16.59s/it, condition=similarity]

k:  50%|█████     | 1/2 [03:26<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:28<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:32<00:07,  7.43s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:32<00:07,  7.43s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=16 | similarity | seed=789: 1000 rows

Rendering prompts:   2%|▎         | 25/1000 [00:00<00:03, 249.37it/s]

Rendering prompts:   8%|▊         | 77/1000 [00:00<00:03, 253.05it/s]

Rendering prompts:  13%|█▎        | 129/1000 [00:00<00:03, 254.17it/s]

Rendering prompts:  18%|█▊        | 181/1000 [00:00<00:03, 254.70it/s]

Rendering prompts:  23%|██▎       | 233/1000 [00:00<00:03, 255.28it/s]

Rendering prompts:  28%|██▊       | 285/1000 [00:01<00:02, 251.55it/s]

Rendering prompts:  34%|███▎      | 337/1000 [00:01<00:02, 235.76it/s]

Rendering prompts:  39%|███▉      | 389/1000 [00:01<00:02, 244.62it/s]

Rendering prompts:  44%|████▍     | 441/1000 [00:01<00:02, 249.94it/s]

Rendering prompts:  49%|████▉     | 493/1000 [00:01<00:02, 251.73it/s]

Rendering prompts:  55%|█████▍    | 545/1000 [00:02<00:01, 249.80it/s]

Rendering prompts:  60%|█████▉    | 597/1000 [00:02<00:01, 253.66it/s]

Rendering prompts:  65%|██████▍   | 649/1000 [00:02<00:01, 256.26it/s]

Rendering prompts:  70%|███████   | 701/1000 [00:02<00:01, 257.38it/s]

Rendering prompts:  75%|███████▌  | 753/1000 [00:02<00:00, 257.39it/s]

Rendering prompts:  80%|████████  | 805/1000 [00:03<00:00, 253.92it/s]

Rendering prompts:  86%|████████▌ | 857/1000 [00:03<00:00, 255.75it/s]

Rendering prompts:  91%|█████████ | 909/1000 [00:03<00:00, 255.77it/s]

Rendering prompts:  96%|█████████▌| 961/1000 [00:03<00:00, 257.47it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 252.76it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 798.02it/s, est. speed input: 1664684.91 toks/s, output: 798.10 toks/s]

Models:  50%|█████     | 1/2 [05:52<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:38<00:07,  7.43s/it, seed=1024]

Conditions:  29%|██▊       | 2/7 [01:12<01:22, 16.59s/it, condition=similarity]

k:  50%|█████     | 1/2 [03:33<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:35<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:38<00:00,  7.21s/it, seed=1024]

Conditions:  43%|████▎     | 3/7 [01:12<01:43, 25.88s/it, condition=similarity]

Conditions:  43%|████▎     | 3/7 [01:12<01:43, 25.88s/it, condition=label_diversity]

Qwen2.5-7B-Instruct | anes | k=16 | similarity | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 263.23it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 266.76it/s]

Rendering prompts:  14%|█▎        | 135/1000 [00:00<00:03, 267.77it/s]

Rendering prompts:  19%|█▉        | 189/1000 [00:00<00:03, 267.75it/s]

Rendering prompts:  24%|██▍       | 243/1000 [00:00<00:02, 264.37it/s]

Rendering prompts:  30%|██▉       | 297/1000 [00:01<00:02, 266.36it/s]

Rendering prompts:  35%|███▌      | 351/1000 [00:01<00:02, 266.91it/s]

Rendering prompts:  40%|████      | 405/1000 [00:01<00:02, 266.88it/s]

Rendering prompts:  46%|████▌     | 459/1000 [00:01<00:02, 266.60it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:01, 263.36it/s]

Rendering prompts:  57%|█████▋    | 567/1000 [00:02<00:01, 244.76it/s]

Rendering prompts:  62%|██████▏   | 621/1000 [00:02<00:01, 256.11it/s]

Rendering prompts:  68%|██████▊   | 675/1000 [00:02<00:01, 261.19it/s]

Rendering prompts:  73%|███████▎  | 729/1000 [00:02<00:01, 263.97it/s]

Rendering prompts:  78%|███████▊  | 783/1000 [00:02<00:00, 263.35it/s]

Rendering prompts:  84%|████████▎ | 837/1000 [00:03<00:00, 265.62it/s]

Rendering prompts:  89%|████████▉ | 891/1000 [00:03<00:00, 267.30it/s]

Rendering prompts:  94%|█████████▍| 945/1000 [00:03<00:00, 267.49it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 263.45it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:04,  1.50it/s, est. speed input: 3147.55 toks/s, output: 1.50 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 878.45it/s, est. speed input: 1836234.50 toks/s, output: 878.54 toks/s]

Models:  50%|█████     | 1/2 [05:59<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:06<?, ?it/s, seed=42]

Conditions:  43%|████▎     | 3/7 [01:18<01:43, 25.88s/it, condition=label_diversity]

k:  50%|█████     | 1/2 [03:40<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:41<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:06<00:27,  6.78s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:06<00:27,  6.78s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=16 | label_diversity | seed=42: 1000 rows

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 260.66it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 265.27it/s]

Rendering prompts:  14%|█▎        | 135/1000 [00:00<00:03, 266.45it/s]

Rendering prompts:  19%|█▉        | 189/1000 [00:00<00:03, 266.91it/s]

Rendering prompts:  24%|██▍       | 243/1000 [00:00<00:02, 266.32it/s]

Rendering prompts:  30%|██▉       | 297/1000 [00:01<00:02, 263.55it/s]

Rendering prompts:  35%|███▌      | 351/1000 [00:01<00:02, 264.45it/s]

Rendering prompts:  40%|████      | 405/1000 [00:01<00:02, 265.15it/s]

Rendering prompts:  46%|████▌     | 459/1000 [00:01<00:02, 265.37it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:01, 265.50it/s]

Rendering prompts:  57%|█████▋    | 567/1000 [00:02<00:01, 262.52it/s]

Rendering prompts:  62%|██████▏   | 621/1000 [00:02<00:01, 264.02it/s]

Rendering prompts:  68%|██████▊   | 675/1000 [00:02<00:01, 265.59it/s]

Rendering prompts:  73%|███████▎  | 729/1000 [00:02<00:01, 265.99it/s]

Rendering prompts:  78%|███████▊  | 783/1000 [00:02<00:00, 263.11it/s]

Rendering prompts:  84%|████████▎ | 837/1000 [00:03<00:00, 241.15it/s]

Rendering prompts:  89%|████████▉ | 891/1000 [00:03<00:00, 253.44it/s]

Rendering prompts:  94%|█████████▍| 945/1000 [00:03<00:00, 260.41it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 261.92it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:12,  1.49it/s, est. speed input: 3102.00 toks/s, output: 1.49 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 877.73it/s, est. speed input: 1827696.64 toks/s, output: 877.82 toks/s]

Models:  50%|█████     | 1/2 [06:06<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:13<00:27,  6.78s/it, seed=123]

Conditions:  43%|████▎     | 3/7 [01:25<01:43, 25.88s/it, condition=label_diversity]

k:  50%|█████     | 1/2 [03:46<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:48<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:13<00:20,  6.81s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:13<00:20,  6.81s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=16 | label_diversity | seed=123: 1000 rows

Rendering prompts:   2%|▏         | 15/1000 [00:00<00:06, 148.91it/s]

Rendering prompts:   5%|▍         | 49/1000 [00:00<00:05, 163.23it/s]

Rendering prompts:  10%|█         | 102/1000 [00:00<00:04, 222.29it/s]

Rendering prompts:  18%|█▊        | 180/1000 [00:00<00:03, 248.06it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:01<00:03, 254.52it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:02, 252.38it/s]

Rendering prompts:  34%|███▍      | 340/1000 [00:01<00:02, 256.49it/s]

Rendering prompts:  39%|███▉      | 392/1000 [00:01<00:02, 255.49it/s]

Rendering prompts:  44%|████▍     | 444/1000 [00:01<00:02, 256.48it/s]

Rendering prompts:  50%|████▉     | 496/1000 [00:02<00:01, 256.52it/s]

Rendering prompts:  55%|█████▍    | 548/1000 [00:02<00:01, 251.97it/s]

Rendering prompts:  60%|██████    | 600/1000 [00:02<00:01, 254.88it/s]

Rendering prompts:  65%|██████▌   | 652/1000 [00:02<00:01, 256.66it/s]

Rendering prompts:  70%|███████   | 705/1000 [00:02<00:01, 258.13it/s]

Rendering prompts:  76%|███████▌  | 759/1000 [00:03<00:00, 263.20it/s]

Rendering prompts:  81%|████████▏ | 813/1000 [00:03<00:00, 261.18it/s]

Rendering prompts:  87%|████████▋ | 867/1000 [00:03<00:00, 265.03it/s]

Rendering prompts:  92%|█████████▏| 921/1000 [00:03<00:00, 264.72it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 252.15it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:00,  1.39it/s, est. speed input: 2906.93 toks/s, output: 1.39 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 822.02it/s, est. speed input: 1719097.58 toks/s, output: 822.10 toks/s]

Models:  50%|█████     | 1/2 [06:13<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:20<00:20,  6.81s/it, seed=456]

Conditions:  43%|████▎     | 3/7 [01:33<01:43, 25.88s/it, condition=label_diversity]

k:  50%|█████     | 1/2 [03:54<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [03:56<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:20<00:14,  7.07s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:20<00:14,  7.07s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=16 | label_diversity | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 259.84it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 265.84it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 265.84it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 266.66it/s]

Rendering prompts:  24%|██▍       | 242/1000 [00:00<00:02, 266.64it/s]

Rendering prompts:  30%|██▉       | 296/1000 [00:01<00:02, 267.54it/s]

Rendering prompts:  35%|███▌      | 350/1000 [00:01<00:02, 261.50it/s]

Rendering prompts:  40%|████      | 404/1000 [00:01<00:02, 262.86it/s]

Rendering prompts:  46%|████▌     | 458/1000 [00:01<00:02, 264.37it/s]

Rendering prompts:  51%|█████     | 512/1000 [00:01<00:01, 265.19it/s]

Rendering prompts:  57%|█████▋    | 566/1000 [00:02<00:01, 266.03it/s]

Rendering prompts:  62%|██████▏   | 620/1000 [00:02<00:01, 261.92it/s]

Rendering prompts:  67%|██████▋   | 674/1000 [00:02<00:01, 264.74it/s]

Rendering prompts:  73%|███████▎  | 728/1000 [00:02<00:01, 264.50it/s]

Rendering prompts:  78%|███████▊  | 782/1000 [00:02<00:00, 264.03it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:03<00:00, 265.14it/s]

Rendering prompts:  89%|████████▉ | 890/1000 [00:03<00:00, 261.18it/s]

Rendering prompts:  94%|█████████▍| 944/1000 [00:03<00:00, 263.24it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 264.61it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:12,  1.36it/s, est. speed input: 2856.80 toks/s, output: 1.36 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 832.94it/s, est. speed input: 1740253.12 toks/s, output: 833.02 toks/s]

Models:  50%|█████     | 1/2 [06:20<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:27<00:14,  7.07s/it, seed=789]

Conditions:  43%|████▎     | 3/7 [01:39<01:43, 25.88s/it, condition=label_diversity]

k:  50%|█████     | 1/2 [04:01<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [04:03<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:27<00:06,  6.98s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:27<00:06,  6.98s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=16 | label_diversity | seed=789: 1000 rows

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 260.83it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 264.57it/s]

Rendering prompts:  14%|█▎        | 135/1000 [00:00<00:03, 265.27it/s]

Rendering prompts:  19%|█▉        | 189/1000 [00:00<00:03, 262.92it/s]

Rendering prompts:  24%|██▍       | 243/1000 [00:00<00:02, 263.99it/s]

Rendering prompts:  30%|██▉       | 297/1000 [00:01<00:02, 265.31it/s]

Rendering prompts:  35%|███▌      | 351/1000 [00:01<00:02, 265.94it/s]

Rendering prompts:  40%|████      | 405/1000 [00:01<00:02, 265.65it/s]

Rendering prompts:  46%|████▌     | 459/1000 [00:01<00:02, 262.20it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:01, 259.99it/s]

Rendering prompts:  57%|█████▋    | 566/1000 [00:02<00:01, 254.74it/s]

Rendering prompts:  62%|██████▏   | 619/1000 [00:02<00:01, 256.77it/s]

Rendering prompts:  67%|██████▋   | 672/1000 [00:02<00:01, 253.54it/s]

Rendering prompts:  73%|███████▎  | 726/1000 [00:02<00:01, 259.28it/s]

Rendering prompts:  78%|███████▊  | 780/1000 [00:02<00:00, 263.00it/s]

Rendering prompts:  83%|████████▎ | 834/1000 [00:03<00:00, 262.28it/s]

Rendering prompts:  89%|████████▉ | 888/1000 [00:03<00:00, 264.48it/s]

Rendering prompts:  94%|█████████▍| 942/1000 [00:03<00:00, 262.24it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 261.96it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:09,  1.37it/s, est. speed input: 2866.26 toks/s, output: 1.37 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 833.94it/s, est. speed input: 1742364.35 toks/s, output: 834.03 toks/s]

Models:  50%|█████     | 1/2 [06:27<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:34<00:06,  6.98s/it, seed=1024]

Conditions:  43%|████▎     | 3/7 [01:46<01:43, 25.88s/it, condition=label_diversity]

k:  50%|█████     | 1/2 [04:08<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [04:09<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:34<00:00,  6.94s/it, seed=1024]

Conditions:  57%|█████▋    | 4/7 [01:46<01:27, 29.17s/it, condition=label_diversity]

Conditions:  57%|█████▋    | 4/7 [01:46<01:27, 29.17s/it, condition=feature_range]

Qwen2.5-7B-Instruct | anes | k=16 | label_diversity | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 253.19it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 257.65it/s]

Rendering prompts:  13%|█▎        | 131/1000 [00:00<00:03, 259.09it/s]

Rendering prompts:  18%|█▊        | 185/1000 [00:00<00:03, 260.09it/s]

Rendering prompts:  26%|██▋       | 264/1000 [00:01<00:02, 258.37it/s]

Rendering prompts:  32%|███▏      | 316/1000 [00:01<00:02, 258.53it/s]

Rendering prompts:  37%|███▋      | 369/1000 [00:01<00:02, 258.46it/s]

Rendering prompts:  42%|████▏     | 421/1000 [00:01<00:02, 258.71it/s]

Rendering prompts:  47%|████▋     | 473/1000 [00:01<00:02, 255.40it/s]

Rendering prompts:  52%|█████▎    | 525/1000 [00:02<00:01, 256.95it/s]

Rendering prompts:  58%|█████▊    | 577/1000 [00:02<00:01, 257.56it/s]

Rendering prompts:  63%|██████▎   | 629/1000 [00:02<00:01, 258.39it/s]

Rendering prompts:  68%|██████▊   | 681/1000 [00:02<00:01, 254.82it/s]

Rendering prompts:  74%|███████▎  | 735/1000 [00:02<00:01, 259.97it/s]

Rendering prompts:  79%|███████▉  | 789/1000 [00:03<00:00, 262.71it/s]

Rendering prompts:  84%|████████▍ | 843/1000 [00:03<00:00, 264.41it/s]

Rendering prompts:  90%|████████▉ | 897/1000 [00:03<00:00, 264.67it/s]

Rendering prompts:  95%|█████████▌| 951/1000 [00:03<00:00, 226.31it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 252.91it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<10:44,  1.55it/s, est. speed input: 3232.70 toks/s, output: 1.55 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 836.40it/s, est. speed input: 1739964.18 toks/s, output: 836.48 toks/s]

Models:  50%|█████     | 1/2 [06:40<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:12<?, ?it/s, seed=42]

Conditions:  57%|█████▋    | 4/7 [01:59<01:27, 29.17s/it, condition=feature_range]

k:  50%|█████     | 1/2 [04:20<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [04:22<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:12<00:51, 12.87s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:12<00:51, 12.87s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=16 | feature_range | seed=42: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 251.32it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 254.93it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 256.81it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 256.64it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:02, 257.97it/s]

Rendering prompts:  29%|██▊       | 287/1000 [00:01<00:02, 255.48it/s]

Rendering prompts:  34%|███▍      | 339/1000 [00:01<00:02, 257.41it/s]

Rendering prompts:  39%|███▉      | 391/1000 [00:01<00:02, 257.59it/s]

Rendering prompts:  44%|████▍     | 443/1000 [00:01<00:02, 257.89it/s]

Rendering prompts:  50%|████▉     | 495/1000 [00:01<00:01, 257.87it/s]

Rendering prompts:  55%|█████▍    | 547/1000 [00:02<00:01, 246.99it/s]

Rendering prompts:  60%|█████▉    | 599/1000 [00:02<00:01, 252.26it/s]

Rendering prompts:  65%|██████▌   | 651/1000 [00:02<00:01, 255.21it/s]

Rendering prompts:  70%|███████   | 704/1000 [00:02<00:01, 257.67it/s]

Rendering prompts:  76%|███████▌  | 758/1000 [00:02<00:00, 258.38it/s]

Rendering prompts:  81%|████████  | 812/1000 [00:03<00:00, 262.82it/s]

Rendering prompts:  87%|████████▋ | 866/1000 [00:03<00:00, 265.19it/s]

Rendering prompts:  92%|█████████▏| 920/1000 [00:03<00:00, 266.24it/s]

Rendering prompts:  97%|█████████▋| 974/1000 [00:03<00:00, 267.18it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 258.25it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<10:44,  1.55it/s, est. speed input: 3257.55 toks/s, output: 1.55 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 840.84it/s, est. speed input: 1763486.87 toks/s, output: 840.92 toks/s]

Models:  50%|█████     | 1/2 [06:53<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:25<00:51, 12.87s/it, seed=123]

Conditions:  57%|█████▋    | 4/7 [02:12<01:27, 29.17s/it, condition=feature_range]

k:  50%|█████     | 1/2 [04:33<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [04:35<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:25<00:38, 12.87s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:25<00:38, 12.87s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=16 | feature_range | seed=123: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 253.13it/s]

Rendering prompts:   8%|▊         | 79/1000 [00:00<00:03, 257.99it/s]

Rendering prompts:  13%|█▎        | 131/1000 [00:00<00:03, 257.25it/s]

Rendering prompts:  18%|█▊        | 184/1000 [00:00<00:03, 258.67it/s]

Rendering prompts:  26%|██▌       | 262/1000 [00:01<00:02, 259.21it/s]

Rendering prompts:  32%|███▏      | 315/1000 [00:01<00:02, 259.75it/s]

Rendering prompts:  37%|███▋      | 367/1000 [00:01<00:02, 256.74it/s]

Rendering prompts:  42%|████▏     | 419/1000 [00:01<00:02, 257.46it/s]

Rendering prompts:  47%|████▋     | 471/1000 [00:01<00:02, 258.23it/s]

Rendering prompts:  52%|█████▏    | 523/1000 [00:02<00:01, 258.93it/s]

Rendering prompts:  57%|█████▊    | 575/1000 [00:02<00:01, 255.33it/s]

Rendering prompts:  63%|██████▎   | 628/1000 [00:02<00:01, 257.30it/s]

Rendering prompts:  68%|██████▊   | 680/1000 [00:02<00:01, 258.09it/s]

Rendering prompts:  73%|███████▎  | 732/1000 [00:02<00:01, 258.10it/s]

Rendering prompts:  78%|███████▊  | 784/1000 [00:03<00:00, 258.14it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:03<00:00, 249.62it/s]

Rendering prompts:  89%|████████▉ | 888/1000 [00:03<00:00, 253.24it/s]

Rendering prompts:  94%|█████████▍| 940/1000 [00:03<00:00, 255.69it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 256.79it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<10:52,  1.53it/s, est. speed input: 3208.82 toks/s, output: 1.53 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 886.50it/s, est. speed input: 1854837.28 toks/s, output: 886.59 toks/s]

Models:  50%|█████     | 1/2 [07:05<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:38<00:38, 12.87s/it, seed=456]

Conditions:  57%|█████▋    | 4/7 [02:25<01:27, 29.17s/it, condition=feature_range]

k:  50%|█████     | 1/2 [04:46<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [04:48<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:38<00:25, 12.84s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:38<00:25, 12.84s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=16 | feature_range | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 260.11it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 267.18it/s]

Rendering prompts:  14%|█▎        | 136/1000 [00:00<00:03, 268.70it/s]

Rendering prompts:  19%|█▉        | 192/1000 [00:00<00:02, 269.61it/s]

Rendering prompts:  25%|██▍       | 247/1000 [00:00<00:03, 249.05it/s]

Rendering prompts:  30%|███       | 302/1000 [00:01<00:02, 259.25it/s]

Rendering prompts:  36%|███▌      | 357/1000 [00:01<00:02, 264.45it/s]

Rendering prompts:  41%|████      | 411/1000 [00:01<00:02, 266.52it/s]

Rendering prompts:  46%|████▋     | 465/1000 [00:01<00:02, 263.25it/s]

Rendering prompts:  52%|█████▏    | 519/1000 [00:01<00:01, 265.39it/s]

Rendering prompts:  57%|█████▋    | 573/1000 [00:02<00:01, 266.39it/s]

Rendering prompts:  65%|██████▌   | 654/1000 [00:02<00:01, 267.51it/s]

Rendering prompts:  71%|███████   | 708/1000 [00:02<00:01, 264.29it/s]

Rendering prompts:  76%|███████▌  | 762/1000 [00:02<00:00, 266.06it/s]

Rendering prompts:  82%|████████▏ | 816/1000 [00:03<00:00, 267.29it/s]

Rendering prompts:  87%|████████▋ | 870/1000 [00:03<00:00, 268.08it/s]

Rendering prompts:  92%|█████████▏| 924/1000 [00:03<00:00, 268.52it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 264.69it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:23,  1.46it/s, est. speed input: 3052.28 toks/s, output: 1.46 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 886.94it/s, est. speed input: 1847766.80 toks/s, output: 887.03 toks/s]

Models:  50%|█████     | 1/2 [07:18<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:51<00:25, 12.84s/it, seed=789]

Conditions:  57%|█████▋    | 4/7 [02:37<01:27, 29.17s/it, condition=feature_range]

k:  50%|█████     | 1/2 [04:59<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:00<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:51<00:12, 12.69s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:51<00:12, 12.69s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=16 | feature_range | seed=789: 1000 rows

Rendering prompts:   3%|▎         | 27/1000 [00:00<00:03, 260.69it/s]

Rendering prompts:   8%|▊         | 81/1000 [00:00<00:03, 264.36it/s]

Rendering prompts:  14%|█▎        | 135/1000 [00:00<00:03, 265.26it/s]

Rendering prompts:  19%|█▉        | 189/1000 [00:00<00:03, 265.85it/s]

Rendering prompts:  24%|██▍       | 243/1000 [00:00<00:02, 261.94it/s]

Rendering prompts:  30%|██▉       | 297/1000 [00:01<00:02, 264.67it/s]

Rendering prompts:  35%|███▌      | 351/1000 [00:01<00:02, 265.62it/s]

Rendering prompts:  40%|████      | 405/1000 [00:01<00:02, 265.78it/s]

Rendering prompts:  46%|████▌     | 459/1000 [00:01<00:02, 265.25it/s]

Rendering prompts:  51%|█████▏    | 513/1000 [00:01<00:02, 231.82it/s]

Rendering prompts:  57%|█████▋    | 567/1000 [00:02<00:01, 247.55it/s]

Rendering prompts:  62%|██████▏   | 621/1000 [00:02<00:01, 255.16it/s]

Rendering prompts:  68%|██████▊   | 675/1000 [00:02<00:01, 260.02it/s]

Rendering prompts:  73%|███████▎  | 729/1000 [00:02<00:01, 263.12it/s]

Rendering prompts:  78%|███████▊  | 783/1000 [00:03<00:00, 262.07it/s]

Rendering prompts:  84%|████████▎ | 837/1000 [00:03<00:00, 263.61it/s]

Rendering prompts:  89%|████████▉ | 891/1000 [00:03<00:00, 264.73it/s]

Rendering prompts:  94%|█████████▍| 945/1000 [00:03<00:00, 265.20it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 260.97it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:44,  1.42it/s, est. speed input: 2965.13 toks/s, output: 1.42 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 871.52it/s, est. speed input: 1817408.81 toks/s, output: 871.62 toks/s]

Models:  50%|█████     | 1/2 [07:31<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [01:03<00:12, 12.69s/it, seed=1024]

Conditions:  57%|█████▋    | 4/7 [02:50<01:27, 29.17s/it, condition=feature_range]

k:  50%|█████     | 1/2 [05:11<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:13<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [01:03<00:00, 12.66s/it, seed=1024]

Conditions:  71%|███████▏  | 5/7 [02:50<01:22, 41.15s/it, condition=feature_range]

Conditions:  71%|███████▏  | 5/7 [02:50<01:22, 41.15s/it, condition=rule_diversity]

Qwen2.5-7B-Instruct | anes | k=16 | feature_range | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   2%|▎         | 25/1000 [00:00<00:03, 245.81it/s]

Rendering prompts:   8%|▊         | 77/1000 [00:00<00:03, 251.80it/s]

Rendering prompts:  13%|█▎        | 129/1000 [00:00<00:03, 253.74it/s]

Rendering prompts:  18%|█▊        | 181/1000 [00:00<00:03, 253.53it/s]

Rendering prompts:  23%|██▎       | 233/1000 [00:00<00:03, 254.48it/s]

Rendering prompts:  28%|██▊       | 285/1000 [00:01<00:02, 250.89it/s]

Rendering prompts:  34%|███▎      | 337/1000 [00:01<00:02, 252.80it/s]

Rendering prompts:  39%|███▉      | 389/1000 [00:01<00:02, 253.60it/s]

Rendering prompts:  44%|████▍     | 441/1000 [00:01<00:02, 254.39it/s]

Rendering prompts:  49%|████▉     | 493/1000 [00:01<00:01, 254.48it/s]

Rendering prompts:  55%|█████▍    | 545/1000 [00:02<00:01, 250.33it/s]

Rendering prompts:  60%|█████▉    | 597/1000 [00:02<00:01, 253.30it/s]

Rendering prompts:  65%|██████▍   | 649/1000 [00:02<00:01, 253.64it/s]

Rendering prompts:  70%|███████   | 701/1000 [00:02<00:01, 254.34it/s]

Rendering prompts:  75%|███████▌  | 753/1000 [00:02<00:00, 254.66it/s]

Rendering prompts:  80%|████████  | 805/1000 [00:03<00:00, 221.12it/s]

Rendering prompts:  86%|████████▌ | 857/1000 [00:03<00:00, 236.88it/s]

Rendering prompts:  91%|█████████ | 909/1000 [00:03<00:00, 245.05it/s]

Rendering prompts:  96%|█████████▌| 961/1000 [00:03<00:00, 249.21it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 250.39it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:35,  1.44it/s, est. speed input: 2997.65 toks/s, output: 1.44 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 874.41it/s, est. speed input: 1820802.28 toks/s, output: 874.50 toks/s]

Models:  50%|█████     | 1/2 [07:39<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:07<?, ?it/s, seed=42]

Conditions:  71%|███████▏  | 5/7 [02:58<01:22, 41.15s/it, condition=rule_diversity]

k:  50%|█████     | 1/2 [05:19<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:21<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:07<00:31,  7.99s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:07<00:31,  7.99s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=16 | rule_diversity | seed=42: 1000 rows

Rendering prompts:   2%|▎         | 25/1000 [00:00<00:04, 240.67it/s]

Rendering prompts:   8%|▊         | 79/1000 [00:00<00:03, 254.61it/s]

Rendering prompts:  13%|█▎        | 133/1000 [00:00<00:03, 259.37it/s]

Rendering prompts:  19%|█▊        | 186/1000 [00:00<00:03, 259.93it/s]

Rendering prompts:  24%|██▍       | 240/1000 [00:00<00:02, 260.78it/s]

Rendering prompts:  29%|██▉       | 294/1000 [00:01<00:02, 260.39it/s]

Rendering prompts:  35%|███▍      | 347/1000 [00:01<00:02, 257.51it/s]

Rendering prompts:  40%|████      | 401/1000 [00:01<00:02, 259.07it/s]

Rendering prompts:  45%|████▌     | 453/1000 [00:01<00:02, 257.14it/s]

Rendering prompts:  51%|█████     | 506/1000 [00:01<00:01, 256.60it/s]

Rendering prompts:  56%|█████▌    | 558/1000 [00:02<00:01, 251.60it/s]

Rendering prompts:  61%|██████    | 611/1000 [00:02<00:01, 252.71it/s]

Rendering prompts:  66%|██████▋   | 663/1000 [00:02<00:01, 252.47it/s]

Rendering prompts:  72%|███████▏  | 716/1000 [00:02<00:01, 256.22it/s]

Rendering prompts:  77%|███████▋  | 768/1000 [00:02<00:00, 257.15it/s]

Rendering prompts:  82%|████████▏ | 821/1000 [00:03<00:00, 254.05it/s]

Rendering prompts:  87%|████████▋ | 873/1000 [00:03<00:00, 255.58it/s]

Rendering prompts:  92%|█████████▎| 925/1000 [00:03<00:00, 256.47it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 256.61it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<14:50,  1.12it/s, est. speed input: 2359.29 toks/s, output: 1.12 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 754.32it/s, est. speed input: 1583530.60 toks/s, output: 754.39 toks/s]

Models:  50%|█████     | 1/2 [07:47<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:16<00:31,  7.99s/it, seed=123]

Conditions:  71%|███████▏  | 5/7 [03:06<01:22, 41.15s/it, condition=rule_diversity]

k:  50%|█████     | 1/2 [05:27<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:29<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:16<00:24,  8.03s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:16<00:24,  8.03s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=16 | rule_diversity | seed=123: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 258.51it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 263.60it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 265.14it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 263.91it/s]

Rendering prompts:  24%|██▍       | 242/1000 [00:00<00:02, 265.04it/s]

Rendering prompts:  30%|██▉       | 296/1000 [00:01<00:02, 265.60it/s]

Rendering prompts:  35%|███▌      | 350/1000 [00:01<00:02, 264.50it/s]

Rendering prompts:  40%|████      | 404/1000 [00:01<00:02, 261.08it/s]

Rendering prompts:  46%|████▌     | 458/1000 [00:01<00:02, 262.42it/s]

Rendering prompts:  51%|█████     | 512/1000 [00:01<00:01, 263.19it/s]

Rendering prompts:  57%|█████▋    | 566/1000 [00:02<00:01, 263.16it/s]

Rendering prompts:  62%|██████▏   | 620/1000 [00:02<00:01, 262.99it/s]

Rendering prompts:  67%|██████▋   | 674/1000 [00:02<00:01, 261.31it/s]

Rendering prompts:  73%|███████▎  | 728/1000 [00:02<00:01, 262.70it/s]

Rendering prompts:  78%|███████▊  | 782/1000 [00:02<00:00, 263.36it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:03<00:00, 263.42it/s]

Rendering prompts:  89%|████████▉ | 890/1000 [00:03<00:00, 264.67it/s]

Rendering prompts:  94%|█████████▍| 944/1000 [00:03<00:00, 262.53it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 263.29it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:51,  1.40it/s, est. speed input: 2952.09 toks/s, output: 1.40 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 840.34it/s, est. speed input: 1762444.47 toks/s, output: 840.42 toks/s]

Models:  50%|█████     | 1/2 [07:54<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:23<00:24,  8.03s/it, seed=456]

Conditions:  71%|███████▏  | 5/7 [03:14<01:22, 41.15s/it, condition=rule_diversity]

k:  50%|█████     | 1/2 [05:35<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:37<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:23<00:15,  7.94s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:23<00:15,  7.94s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=16 | rule_diversity | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 259.75it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 264.11it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 265.15it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 261.87it/s]

Rendering prompts:  24%|██▍       | 242/1000 [00:00<00:02, 263.91it/s]

Rendering prompts:  30%|██▉       | 296/1000 [00:01<00:02, 264.35it/s]

Rendering prompts:  35%|███▌      | 350/1000 [00:01<00:02, 264.45it/s]

Rendering prompts:  40%|████      | 404/1000 [00:01<00:02, 264.51it/s]

Rendering prompts:  46%|████▌     | 458/1000 [00:01<00:02, 261.26it/s]

Rendering prompts:  51%|█████     | 512/1000 [00:01<00:01, 262.26it/s]

Rendering prompts:  57%|█████▋    | 566/1000 [00:02<00:01, 263.03it/s]

Rendering prompts:  62%|██████▏   | 620/1000 [00:02<00:01, 263.32it/s]

Rendering prompts:  67%|██████▋   | 674/1000 [00:02<00:01, 263.33it/s]

Rendering prompts:  73%|███████▎  | 728/1000 [00:02<00:01, 261.42it/s]

Rendering prompts:  78%|███████▊  | 782/1000 [00:02<00:00, 263.49it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:03<00:00, 264.57it/s]

Rendering prompts:  89%|████████▉ | 890/1000 [00:03<00:00, 264.85it/s]

Rendering prompts:  94%|█████████▍| 944/1000 [00:03<00:00, 261.49it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 263.27it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:08,  1.37it/s, est. speed input: 2873.00 toks/s, output: 1.37 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 840.64it/s, est. speed input: 1757188.58 toks/s, output: 840.72 toks/s]

Models:  50%|█████     | 1/2 [08:02<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:31<00:15,  7.94s/it, seed=789]

Conditions:  71%|███████▏  | 5/7 [03:22<01:22, 41.15s/it, condition=rule_diversity]

k:  50%|█████     | 1/2 [05:43<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:45<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:31<00:07,  7.90s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:31<00:07,  7.90s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=16 | rule_diversity | seed=789: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 257.50it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 262.17it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 263.99it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 264.35it/s]

Rendering prompts:  24%|██▍       | 242/1000 [00:00<00:02, 261.61it/s]

Rendering prompts:  30%|██▉       | 296/1000 [00:01<00:02, 263.67it/s]

Rendering prompts:  35%|███▌      | 350/1000 [00:01<00:02, 264.72it/s]

Rendering prompts:  40%|████      | 404/1000 [00:01<00:02, 264.90it/s]

Rendering prompts:  46%|████▌     | 458/1000 [00:01<00:02, 264.38it/s]

Rendering prompts:  51%|█████     | 512/1000 [00:01<00:01, 261.38it/s]

Rendering prompts:  57%|█████▋    | 566/1000 [00:02<00:01, 262.99it/s]

Rendering prompts:  62%|██████▏   | 620/1000 [00:02<00:01, 263.77it/s]

Rendering prompts:  67%|██████▋   | 674/1000 [00:02<00:01, 264.64it/s]

Rendering prompts:  73%|███████▎  | 728/1000 [00:02<00:01, 261.42it/s]

Rendering prompts:  78%|███████▊  | 782/1000 [00:02<00:00, 263.33it/s]

Rendering prompts:  84%|████████▎ | 836/1000 [00:03<00:00, 263.70it/s]

Rendering prompts:  89%|████████▉ | 890/1000 [00:03<00:00, 264.61it/s]

Rendering prompts:  94%|█████████▍| 944/1000 [00:03<00:00, 265.46it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 263.45it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<12:17,  1.35it/s, est. speed input: 2830.58 toks/s, output: 1.35 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 835.23it/s, est. speed input: 1741678.69 toks/s, output: 835.30 toks/s]

Models:  50%|█████     | 1/2 [08:10<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:39<00:07,  7.90s/it, seed=1024]

Conditions:  71%|███████▏  | 5/7 [03:29<01:22, 41.15s/it, condition=rule_diversity]

k:  50%|█████     | 1/2 [05:51<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [05:53<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:39<00:00,  7.87s/it, seed=1024]

Conditions:  86%|████████▌ | 6/7 [03:29<00:40, 40.62s/it, condition=rule_diversity]

Conditions:  86%|████████▌ | 6/7 [03:29<00:40, 40.62s/it, condition=counter_spurious]

Qwen2.5-7B-Instruct | anes | k=16 | rule_diversity | seed=1024: 1000 rows

Seeds:   0%|          | 0/5 [00:00<?, ?it/s]

Seeds:   0%|          | 0/5 [00:00<?, ?it/s, seed=42]

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 251.25it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 253.49it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 255.02it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 255.64it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:02, 255.50it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:02, 255.72it/s]

Rendering prompts:  34%|███▍      | 338/1000 [00:01<00:02, 253.07it/s]

Rendering prompts:  39%|███▉      | 390/1000 [00:01<00:02, 253.95it/s]

Rendering prompts:  44%|████▍     | 442/1000 [00:01<00:02, 254.09it/s]

Rendering prompts:  49%|████▉     | 494/1000 [00:01<00:01, 253.95it/s]

Rendering prompts:  55%|█████▍    | 546/1000 [00:02<00:01, 250.42it/s]

Rendering prompts:  60%|█████▉    | 598/1000 [00:02<00:01, 251.97it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:02<00:01, 253.43it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:02<00:01, 254.39it/s]

Rendering prompts:  75%|███████▌  | 754/1000 [00:02<00:00, 254.48it/s]

Rendering prompts:  81%|████████  | 806/1000 [00:03<00:00, 252.62it/s]

Rendering prompts:  86%|████████▌ | 860/1000 [00:03<00:00, 258.55it/s]

Rendering prompts:  91%|█████████▏| 914/1000 [00:03<00:00, 261.95it/s]

Rendering prompts:  97%|█████████▋| 968/1000 [00:03<00:00, 263.79it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 255.84it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:30,  1.45it/s, est. speed input: 3027.09 toks/s, output: 1.45 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 844.62it/s, est. speed input: 1762152.34 toks/s, output: 844.71 toks/s]

Models:  50%|█████     | 1/2 [08:17<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/5 [00:07<?, ?it/s, seed=42]

Conditions:  86%|████████▌ | 6/7 [03:37<00:40, 40.62s/it, condition=counter_spurious]

k:  50%|█████     | 1/2 [05:58<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [06:00<00:00,  2.09it/s, dataset=anes]

Seeds:  20%|██        | 1/5 [00:07<00:29,  7.33s/it, seed=42]

Seeds:  20%|██        | 1/5 [00:07<00:29,  7.33s/it, seed=123]

Qwen2.5-7B-Instruct | anes | k=16 | counter_spurious | seed=42: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 253.14it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 255.82it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 254.99it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 257.06it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:02, 257.69it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:02, 258.12it/s]

Rendering prompts:  34%|███▍      | 338/1000 [00:01<00:02, 258.07it/s]

Rendering prompts:  39%|███▉      | 390/1000 [00:01<00:02, 254.92it/s]

Rendering prompts:  44%|████▍     | 442/1000 [00:01<00:02, 255.57it/s]

Rendering prompts:  49%|████▉     | 494/1000 [00:01<00:01, 255.62it/s]

Rendering prompts:  55%|█████▍    | 546/1000 [00:02<00:01, 255.83it/s]

Rendering prompts:  60%|█████▉    | 598/1000 [00:02<00:01, 252.50it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:02<00:01, 254.38it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:02<00:01, 256.51it/s]

Rendering prompts:  76%|███████▌  | 756/1000 [00:02<00:00, 262.06it/s]

Rendering prompts:  81%|████████  | 810/1000 [00:03<00:00, 264.80it/s]

Rendering prompts:  86%|████████▋ | 864/1000 [00:03<00:00, 263.89it/s]

Rendering prompts:  92%|█████████▏| 918/1000 [00:03<00:00, 266.11it/s]

Rendering prompts:  97%|█████████▋| 972/1000 [00:03<00:00, 267.10it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 259.01it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<10:53,  1.53it/s, est. speed input: 3178.56 toks/s, output: 1.53 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 886.27it/s, est. speed input: 1839267.11 toks/s, output: 886.35 toks/s]

Models:  50%|█████     | 1/2 [08:25<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  20%|██        | 1/5 [00:14<00:29,  7.33s/it, seed=123]

Conditions:  86%|████████▌ | 6/7 [03:44<00:40, 40.62s/it, condition=counter_spurious]

k:  50%|█████     | 1/2 [06:05<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [06:07<00:00,  2.09it/s, dataset=anes]

Seeds:  40%|████      | 2/5 [00:14<00:21,  7.28s/it, seed=123]

Seeds:  40%|████      | 2/5 [00:14<00:21,  7.28s/it, seed=456]

Qwen2.5-7B-Instruct | anes | k=16 | counter_spurious | seed=123: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 252.78it/s]

Rendering prompts:   8%|▊         | 78/1000 [00:00<00:03, 255.77it/s]

Rendering prompts:  13%|█▎        | 130/1000 [00:00<00:03, 257.01it/s]

Rendering prompts:  18%|█▊        | 182/1000 [00:00<00:03, 257.00it/s]

Rendering prompts:  23%|██▎       | 234/1000 [00:00<00:03, 254.07it/s]

Rendering prompts:  29%|██▊       | 286/1000 [00:01<00:03, 237.26it/s]

Rendering prompts:  34%|███▍      | 338/1000 [00:01<00:02, 246.02it/s]

Rendering prompts:  39%|███▉      | 390/1000 [00:01<00:02, 251.16it/s]

Rendering prompts:  44%|████▍     | 442/1000 [00:01<00:02, 253.12it/s]

Rendering prompts:  49%|████▉     | 494/1000 [00:01<00:02, 250.47it/s]

Rendering prompts:  55%|█████▍    | 546/1000 [00:02<00:01, 252.28it/s]

Rendering prompts:  60%|█████▉    | 598/1000 [00:02<00:01, 253.55it/s]

Rendering prompts:  65%|██████▌   | 650/1000 [00:02<00:01, 254.41it/s]

Rendering prompts:  70%|███████   | 702/1000 [00:02<00:01, 255.64it/s]

Rendering prompts:  75%|███████▌  | 754/1000 [00:02<00:00, 253.31it/s]

Rendering prompts:  81%|████████  | 806/1000 [00:03<00:00, 254.30it/s]

Rendering prompts:  86%|████████▌ | 858/1000 [00:03<00:00, 254.85it/s]

Rendering prompts:  91%|█████████ | 910/1000 [00:03<00:00, 255.22it/s]

Rendering prompts:  96%|█████████▌| 962/1000 [00:03<00:00, 251.99it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 252.26it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<10:42,  1.56it/s, est. speed input: 3244.13 toks/s, output: 1.56 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 871.06it/s, est. speed input: 1812092.32 toks/s, output: 871.16 toks/s]

Models:  50%|█████     | 1/2 [08:32<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  40%|████      | 2/5 [00:21<00:21,  7.28s/it, seed=456]

Conditions:  86%|████████▌ | 6/7 [03:51<00:40, 40.62s/it, condition=counter_spurious]

k:  50%|█████     | 1/2 [06:13<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [06:15<00:00,  2.09it/s, dataset=anes]

Seeds:  60%|██████    | 3/5 [00:21<00:14,  7.33s/it, seed=456]

Seeds:  60%|██████    | 3/5 [00:21<00:14,  7.33s/it, seed=789]

Qwen2.5-7B-Instruct | anes | k=16 | counter_spurious | seed=456: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 253.49it/s]

Rendering prompts:  10%|█         | 104/1000 [00:00<00:03, 257.91it/s]

Rendering prompts:  16%|█▌        | 157/1000 [00:00<00:03, 258.73it/s]

Rendering prompts:  21%|██        | 211/1000 [00:00<00:03, 259.96it/s]

Rendering prompts:  26%|██▋       | 265/1000 [00:01<00:02, 259.99it/s]

Rendering prompts:  32%|███▏      | 318/1000 [00:01<00:02, 257.84it/s]

Rendering prompts:  37%|███▋      | 371/1000 [00:01<00:02, 258.26it/s]

Rendering prompts:  42%|████▏     | 424/1000 [00:01<00:02, 261.45it/s]

Rendering prompts:  48%|████▊     | 478/1000 [00:01<00:01, 264.41it/s]

Rendering prompts:  53%|█████▎    | 532/1000 [00:02<00:01, 266.19it/s]

Rendering prompts:  59%|█████▊    | 586/1000 [00:02<00:01, 242.70it/s]

Rendering prompts:  64%|██████▍   | 639/1000 [00:02<00:01, 250.12it/s]

Rendering prompts:  69%|██████▉   | 693/1000 [00:02<00:01, 258.73it/s]

Rendering prompts:  75%|███████▍  | 747/1000 [00:02<00:00, 262.59it/s]

Rendering prompts:  80%|████████  | 801/1000 [00:03<00:00, 260.00it/s]

Rendering prompts:  86%|████████▌ | 855/1000 [00:03<00:00, 263.28it/s]

Rendering prompts:  91%|█████████ | 909/1000 [00:03<00:00, 264.81it/s]

Rendering prompts:  96%|█████████▋| 963/1000 [00:03<00:00, 265.23it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 259.19it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:16,  1.48it/s, est. speed input: 3070.75 toks/s, output: 1.48 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 868.28it/s, est. speed input: 1801917.14 toks/s, output: 868.35 toks/s]

Models:  50%|█████     | 1/2 [08:39<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  60%|██████    | 3/5 [00:29<00:14,  7.33s/it, seed=789]

Conditions:  86%|████████▌ | 6/7 [03:59<00:40, 40.62s/it, condition=counter_spurious]

k:  50%|█████     | 1/2 [06:20<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [06:22<00:00,  2.09it/s, dataset=anes]

Seeds:  80%|████████  | 4/5 [00:29<00:07,  7.30s/it, seed=789]

Seeds:  80%|████████  | 4/5 [00:29<00:07,  7.30s/it, seed=1024]

Qwen2.5-7B-Instruct | anes | k=16 | counter_spurious | seed=789: 1000 rows

Rendering prompts:   3%|▎         | 26/1000 [00:00<00:03, 259.13it/s]

Rendering prompts:   8%|▊         | 80/1000 [00:00<00:03, 264.09it/s]

Rendering prompts:  13%|█▎        | 134/1000 [00:00<00:03, 264.93it/s]

Rendering prompts:  19%|█▉        | 188/1000 [00:00<00:03, 265.23it/s]

Rendering prompts:  24%|██▍       | 242/1000 [00:00<00:02, 266.10it/s]

Rendering prompts:  30%|██▉       | 296/1000 [00:01<00:02, 266.60it/s]

Rendering prompts:  35%|███▌      | 350/1000 [00:01<00:02, 262.54it/s]

Rendering prompts:  40%|████      | 404/1000 [00:01<00:02, 264.37it/s]

Rendering prompts:  46%|████▌     | 458/1000 [00:01<00:02, 265.14it/s]

Rendering prompts:  51%|█████     | 512/1000 [00:01<00:01, 265.35it/s]

Rendering prompts:  57%|█████▋    | 566/1000 [00:02<00:01, 265.88it/s]

Rendering prompts:  62%|██████▏   | 620/1000 [00:02<00:01, 262.77it/s]

Rendering prompts:  67%|██████▋   | 674/1000 [00:02<00:01, 265.73it/s]

Rendering prompts:  73%|███████▎  | 728/1000 [00:02<00:01, 266.93it/s]

Rendering prompts:  78%|███████▊  | 782/1000 [00:02<00:00, 268.02it/s]

Rendering prompts:  84%|████████▎ | 837/1000 [00:03<00:00, 268.53it/s]

Rendering prompts:  89%|████████▉ | 891/1000 [00:03<00:00, 222.83it/s]

Rendering prompts:  94%|█████████▍| 945/1000 [00:03<00:00, 244.23it/s]

Rendering prompts: 100%|██████████| 1000/1000 [00:03<00:00, 261.38it/s]
Processed prompts:   0%|          | 0/1000 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/1000 [00:00<11:05,  1.50it/s, est. speed input: 3147.28 toks/s, output: 1.50 toks/s]

Processed prompts: 100%|██████████| 1000/1000 [00:01<00:00, 879.26it/s, est. speed input: 1837955.36 toks/s, output: 879.36 toks/s]

Models:  50%|█████     | 1/2 [08:47<00:58, 58.43s/it, model=Qwen2.5-7B-Instruct]

Seeds:  80%|████████  | 4/5 [00:36<00:07,  7.30s/it, seed=1024]

Conditions:  86%|████████▌ | 6/7 [04:06<00:40, 40.62s/it, condition=counter_spurious]

k:  50%|█████     | 1/2 [06:27<02:21, 141.31s/it, k=16]

Datasets:  75%|███████▌  | 3/4 [06:29<00:00,  2.09it/s, dataset=anes]

Seeds: 100%|██████████| 5/5 [00:36<00:00,  7.27s/it, seed=1024]

Conditions: 100%|██████████| 7/7 [04:06<00:00, 39.27s/it, condition=counter_spurious]

k: 100%|██████████| 2/2 [06:27<00:00, 203.11s/it, k=16]

Datasets: 100%|██████████| 4/4 [06:29<00:00, 153.48s/it, dataset=anes]

Qwen2.5-7B-Instruct | anes | k=16 | counter_spurious | seed=1024: 1000 rows

[rank0]:[W912 09:24:57.672906075 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Models: 100%|██████████| 2/2 [08:48<00:00, 300.37s/it, model=Qwen2.5-7B-Instruct]

Models: 100%|██████████| 2/2 [08:48<00:00, 264.08s/it, model=Qwen2.5-7B-Instruct]

## Output

- `results/real_arm_baselines.parquet`
- Summary table: accuracy, macro-F1, shift gap per (dataset, model, condition), averaged over seeds with std.

In [4]:
from src.evaluation.accuracy import summarise
from src.utils.results_schema import load_results

try:
    results = load_results(RESULTS_PATH)
except FileNotFoundError:
    results = None

if results is None or results.empty:
    print("No results yet — results/real_arm_baselines.parquet doesn't exist "
          "(the inference cell above was skipped since vLLM isn't available here).")
    summary = pd.DataFrame(columns=[
        'dataset', 'model', 'method', 'environment', 'k', 'accuracy_mean', 'accuracy_std',
        'macro_f1_mean', 'macro_f1_std', 'invalid_rate_mean', 'n', 'shift_gap',
    ])
else:
    # 'k' is included in every group_cols/groupby below -- without it, the
    # k_primary and k_sensitivity sweep rows would get silently averaged
    # together into one number per (dataset, model, method, environment),
    # which would blend two different experiments instead of comparing them.
    # Per-seed accuracy/macro-F1 first, then mean +/- std *across seeds* (not a
    # single pooled accuracy over all seeds' rows).
    per_seed = summarise(results, group_cols=['dataset', 'model', 'method', 'environment', 'k', 'seed'])
    summary = per_seed.groupby(['dataset', 'model', 'method', 'environment', 'k']).agg(
        accuracy_mean=('accuracy', 'mean'),
        accuracy_std=('accuracy', 'std'),
        macro_f1_mean=('macro_f1', 'mean'),
        macro_f1_std=('macro_f1', 'std'),
        invalid_rate_mean=('invalid_rate', 'mean'),
        n=('n', 'sum'),
    ).reset_index()

    shift_gap = summary.pivot_table(index=['dataset', 'model', 'method', 'k'], columns='environment', values='accuracy_mean')
    shift_gap = (shift_gap['id'] - shift_gap['ood']).rename('shift_gap').reset_index()
    summary = summary.merge(shift_gap, on=['dataset', 'model', 'method', 'k'], how='left')

# Saved separately from the schema'd per-prediction parquet — Notebook 03 reads
# this to pick the "best-performing protocol from Notebook 02" per (dataset, model),
# filtered to k == config.k_primary (see Notebook 03's best_protocol_for).
summary.to_parquet(resolve_path('results/real_arm_baselines_summary.parquet'), index=False)

# k-sensitivity view: does the k=8 ranking of conditions hold at k=16? Printed
# separately rather than folded into `summary` above so the headline
# k_primary table (what every other notebook consumes) stays exactly the
# shape it was before this sweep was added.
if not summary.empty and len(summary['k'].unique()) > 1:
    k_sensitivity = summary.pivot_table(index=['dataset', 'model', 'method'], columns='k', values='accuracy_mean')
    print("k-sensitivity (OOD+ID accuracy_mean, k_primary vs k_sensitivity):")
    display(k_sensitivity)

summary

k-sensitivity (OOD+ID accuracy_mean, k_primary vs k_sensitivity):

k                                                         0       8       16
dataset        model                 method
acsincome      Llama-3.1-8B-Instruct counter_spurious    NaN  0.5968  0.6256
                                     feature_range       NaN  0.5688  0.6156
                                     label_diversity     NaN  0.6848  0.6684
                                     random              NaN  0.6304  0.6576
                                     rule_diversity      NaN  0.6456  0.6908
                                     similarity          NaN  0.6090  0.6560
                                     zero_shot         0.624     NaN     NaN
               Qwen2.5-7B-Instruct   counter_spurious    NaN  0.7044  0.7214
                                     feature_range       NaN  0.7192  0.6932
                                     label_diversity     NaN  0.6924  0.7396
                                     random              NaN  0.7172  0.7040
                                     rule_diversity      NaN  0.7202  0.7240
                                     similarity          NaN  0.6980  0.6930
                                     zero_shot         0.689     NaN     NaN
acspubcov      Llama-3.1-8B-Instruct counter_spurious    NaN  0.5102  0.4658
                                     feature_range       NaN  0.4970  0.4380
                                     label_diversity     NaN  0.5086  0.5500
                                     random              NaN  0.4562  0.4854
                                     rule_diversity      NaN  0.5012  0.4954
                                     similarity          NaN  0.5070  0.4700
                                     zero_shot         0.598     NaN     NaN
               Qwen2.5-7B-Instruct   counter_spurious    NaN  0.4520  0.4658
                                     feature_range       NaN  0.4794  0.5146
                                     label_diversity     NaN  0.4968  0.5340
                                     random              NaN  0.4576  0.5008
                                     rule_diversity      NaN  0.4616  0.5024
                                     similarity          NaN  0.5210  0.5500
                                     zero_shot         0.429     NaN     NaN
anes           Llama-3.1-8B-Instruct counter_spurious    NaN  0.6714  0.6638
                                     feature_range       NaN  0.7090  0.7310
                                     label_diversity     NaN  0.6312  0.6600
                                     random              NaN  0.7204  0.7442
                                     rule_diversity      NaN  0.7038  0.7062
                                     similarity          NaN  0.6130  0.6870
                                     zero_shot         0.320     NaN     NaN
               Qwen2.5-7B-Instruct   counter_spurious    NaN  0.6782  0.6126
                                     feature_range       NaN  0.6818  0.6926
                                     label_diversity     NaN  0.6804  0.6410
                                     random              NaN  0.6682  0.6094
                                     rule_diversity      NaN  0.6750  0.6384
                                     similarity          NaN  0.6120  0.6280
                                     zero_shot         0.529     NaN     NaN
brfss_diabetes Llama-3.1-8B-Instruct counter_spurious    NaN  0.3432  0.4612
                                     feature_range       NaN  0.6182  0.6370
                                     label_diversity     NaN  0.6936  0.6636
                                     random              NaN  0.5524  0.5256
                                     rule_diversity      NaN  0.4080  0.5300
                                     similarity          NaN  0.4660  0.5240
                                     zero_shot         0.427     NaN     NaN
               Qwen2.5-7B-Instruct   counter_spurious    NaN  0.7154  0.7444
                                     feature_range       NaN  0.7690  0.7608
                                     label_diversity     NaN  0.7274  0.7122
                                     random              NaN  0.6360  0.6888
                                     rule_diversity      NaN  0.6186  0.7126
                                     similarity          NaN  0.7020  0.7040
                                     zero_shot         0.782     NaN     NaN

,dataset,model,method,environment,k,accuracy_mean,accuracy_std,macro_f1_mean,macro_f1_std,invalid_rate_mean,n,shift_gap
0,acsincome,Llama-3.1-8B-Instruct,counter_spurious,id,8,0.5848,0.159013,0.563731,0.188627,0.0,2500,-0.0240
1,acsincome,Llama-3.1-8B-Instruct,counter_spurious,id,16,0.6132,0.101485,0.601681,0.100636,0.0,2500,-0.0248
2,acsincome,Llama-3.1-8B-Instruct,counter_spurious,ood,8,0.6088,0.131929,0.583539,0.177532,0.0,2500,-0.0240
3,acsincome,Llama-3.1-8B-Instruct,counter_spurious,ood,16,0.6380,0.086394,0.625771,0.098578,0.0,2500,-0.0248
4,acsincome,Llama-3.1-8B-Instruct,feature_range,id,8,0.5412,0.126662,0.526379,0.139671,0.0,2500,-0.0552
...,...,...,...,...,...,...,...,...,...,...,...,...
203,brfss_diabetes,Qwen2.5-7B-Instruct,similarity,id,16,0.6760,0.000000,0.521684,0.000000,0.0,2500,-0.0560
204,brfss_diabetes,Qwen2.5-7B-Instruct,similarity,ood,8,0.7380,0.000000,0.639870,0.000000,0.0,2500,-0.0720
205,brfss_diabetes,Qwen2.5-7B-Instruct,similarity,ood,16,0.7320,0.000000,0.628405,0.000000,0.0,2500,-0.0560
206,brfss_diabetes,Qwen2.5-7B-Instruct,zero_shot,id,0,0.7840,0.000000,0.561916,0.000000,0.0,2500,0.0040
207,brfss_diabetes,Qwen2.5-7B-Instruct,zero_shot,ood,0,0.7800,0.000000,0.642625,0.000000,0.0,2500,0.0040