# Notebook 03: Faithfulness on Real Data

**Purpose**: Compute internal-consistency faithfulness rho(pi_self, pi_behav) on real datasets — answers RQ3's internal-consistency component.

**Conditions evaluated (3 only)**: Random-k, best-performing protocol from Notebook 02, and (later, Week 8) SATA if real-data transfer works.

## Why this notebook exists (thesis framing)

Accuracy alone can't tell us whether a model is generalising *for the right reasons* — that's the central move the lit review makes in §2.5, going from **invariance** (does the decision rule stay stable across environments?) to **faithfulness** (does the model's stated or measured feature reliance match what actually drives its predictions?). A model can be invariant yet unfaithful (consistently wrong feature, every environment) or faithful yet non-invariant (correctly shifts reliance as the environment shifts). This project's evaluation targets faithfulness specifically because the intervention — demonstration design — operates on a *frozen* model: nothing about the LLM's internal decision rule can be retrained, only which features it's nudged to attend to via which demonstrations it sees.

**RQ3** asks: do configurations that improve OOD accuracy also improve faithfulness, or can accuracy gains coexist with continued reliance on spurious features? This is not a foregone conclusion — Turpin et al. (2023) showed chain-of-thought explanations can be systematically unfaithful (the model changes its answer to match a bias but never mentions the bias in its stated reasoning), and STaDS (Li et al. 2025) found frontier LLMs can be highly *accurate* yet globally *unfaithful* on tabular tasks. RQ3 succeeds specifically if there exist configurations where accuracy improves but ρ(π_self, π_behav) doesn't — that would confirm predictive gains and faithful reliance are genuinely separable outcomes, not the same thing measured twice.

**Why only 3 conditions here, not all 7 from Notebook 02?** This notebook's per-condition compute cost is dominated by the leave-one-out ablation (Step 2), which reruns inference once per feature per query. Running all 7 conditions at that cost isn't affordable within the project's timeline, so the spec narrows to the two conditions most informative for RQ3: random (the no-design baseline) and whichever protocol performed best in Notebook 02 (the condition most likely to show an accuracy/faithfulness split, if one exists).

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.config import load_config, set_seed, resolve_path

config = load_config()
set_seed(config.seed_accuracy[0])

## Step 1: Elicit pi_self (self-reported feature ranking)

Prompt the LLM once per (dataset, condition, seed) via `src/inference/prompts.py::build_feature_ranking_prompt`; parse with `src/evaluation/faithfulness.py::parse_feature_ranking`.

**This is a *global* faithfulness measure, not an instance-level one.** The chain-of-thought faithfulness literature (Turpin et al. 2023; Lanham et al. 2023) asks whether a *single prediction's* stated reasoning matches the computation that produced *that* prediction. STaDS (Li et al. 2025) introduces a complementary, domain-level notion instead: does the model's self-reported feature ranking *for the task as a whole* correspond to its *behavioural* feature ranking, computed independently via ablation (Step 2)? π_self here is elicited once per (dataset, condition, seed) — not per query — because it's a claim about the task ("which features matter for this kind of prediction"), not about any individual row.

In [2]:
import json

import numpy as np
import pandas as pd

from src.data.tableshift_loader import SELECTED_DATASETS, TASK_DESCRIPTIONS, load_codebook
from src.inference.llm_runner import VLLMWorkerRunner
from src.inference.prompts import build_feature_ranking_prompt
from src.evaluation.faithfulness import parse_feature_ranking
from src.utils.results_schema import load_results

FAITHFULNESS_DATASETS = SELECTED_DATASETS
FAITHFULNESS_SEEDS = config.seed_faithfulness

try:
    import vllm  # noqa: F401
    VLLM_AVAILABLE = True
except ImportError:
    VLLM_AVAILABLE = False
    print("vLLM not installed in this environment — skipping pi_self elicitation. "
          "Run this notebook on a GPU box with vllm + the model weights available.")


def best_protocol_for(dataset_name, model_name, baseline_summary):
    """Best non-zero-shot, non-random OOD-accuracy protocol from Notebook 02's
    summary (falls back to 'label_diversity' if Notebook 02 hasn't run yet).

    Filtered to k == config.k_primary: Notebook 02's summary now sweeps both
    k_primary and k_sensitivity (has a 'k' column), and this notebook's own
    demo construction below always uses config.k_primary -- without this
    filter, a k_sensitivity-only row could get picked as "best", naming a
    protocol whose ranking was never actually validated at the k this
    notebook runs with. `'k' in baseline_summary` guards the empty-frame
    fallback below, which predates the k column.
    """
    candidates = baseline_summary[
        (baseline_summary.dataset == dataset_name)
        & (baseline_summary.model == model_name)
        & (baseline_summary.environment == 'ood')
        & (~baseline_summary.method.isin(['zero_shot', 'random']))
    ]
    if 'k' in baseline_summary.columns:
        candidates = candidates[candidates.k == config.k_primary]
    if candidates.empty:
        return 'label_diversity'
    return candidates.sort_values('accuracy_mean', ascending=False).iloc[0]['method']


try:
    baseline_summary = pd.read_parquet(resolve_path('results/real_arm_baselines_summary.parquet'))
except FileNotFoundError:
    baseline_summary = pd.DataFrame(columns=['dataset', 'model', 'method', 'environment', 'k', 'accuracy_mean'])

# pi_self doesn't depend on demos or query rows (see the prompt template) so, like
# zero-shot in Notebook 02, it's deterministic (temperature=0) per (dataset, model):
# elicit it once and reuse across the 3 conditions x 3 seeds it's nominally "per".
pi_self_store = {}  # (dataset_name, model_name) -> ranked feature list (raw column codes)

for dataset_name in (FAITHFULNESS_DATASETS if VLLM_AVAILABLE else []):
    data_dir = resolve_path(config.paths.data_real) / dataset_name
    feature_list = json.load(open(data_dir / 'feature_list.json'))
    label_tokens = json.load(open(data_dir / 'label_tokens.json'))
    codebook = load_codebook(data_dir)
    _task_sentence, task_noun, meaning_0, meaning_1 = TASK_DESCRIPTIONS[dataset_name]
    label_description = f"{label_tokens[0]} ({meaning_0}) vs {label_tokens[1]} ({meaning_1})"

    # Ask the model to rank human-readable feature names, then map the ranking
    # back to raw column codes (the axis pi_behav / the behavioural side use).
    # parse_feature_ranking already degrades gracefully to original order for
    # names the model doesn't echo verbatim.
    display_names = [(codebook.get(f, {}).get('name_extended') or f) for f in feature_list]
    display_to_code = {d: c for c, d in zip(feature_list, display_names)}

    for model_cfg in config.base_llms:
        # VLLMWorkerRunner (not VLLMRunner): runs vLLM in a separate OS
        # subprocess so its GPU memory is guaranteed to be released on
        # shutdown() -- vLLM's in-process engine does not reliably free GPU
        # memory after explicit teardown, which matters here since this loop
        # constructs a fresh runner per (dataset, model) pair.
        runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))
        prompt = build_feature_ranking_prompt(task_noun, display_names, label_description)
        response_text = runner.generate_text([prompt], max_tokens=128)[0]
        ranking_display = parse_feature_ranking(response_text, display_names)
        ranking = [display_to_code[d] for d in ranking_display]
        pi_self_store[(dataset_name, model_cfg.name)] = ranking
        print(dataset_name, model_cfg.name, '->', ranking)
        runner.shutdown()

INFO 09-12 09:46:14 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:46:14 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:46:15 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:46:15 [model.py:2021] Using max model len 8192
INFO 09-12 09:46:15 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:46:15 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:46:17 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:46:18 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_c9162481aa49442c9b3bdb6b2d586838 backend=nccl
INFO 09-12 09:46:18 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:46:18 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:46:19 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:46:19 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:46:19 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:46:19 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.85 GiB.
INFO 09-12 09:46:19 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.25it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.19it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.18it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.64it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.45it/s]

INFO 09-12 09:46:22 [default_loader.py:430] Loading weights took 2.78 seconds

INFO 09-12 09:46:23 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.029799 seconds
INFO 09-12 09:46:23 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:46:23 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:46:24 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:46:24 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:46:24 [monitor.py:53] torch.compile took 0.17 s in total
INFO 09-12 09:46:24 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:03<02:11,  1.63s/it]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:04<00:30,  2.53it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:04<00:14,  4.90it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:04<00:09,  7.19it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:05<00:06,  9.40it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:05<00:05, 11.07it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:05<00:04, 12.40it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:06<00:04, 12.79it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:06<00:03, 13.66it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:06<00:02, 15.13it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:06<00:02, 15.51it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:07<00:02, 16.41it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:07<00:01, 17.18it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:07<00:01, 17.32it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:07<00:01, 17.18it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:08<00:01, 17.26it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:08<00:01, 16.89it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:08<00:00, 17.53it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:08<00:00, 17.39it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:09<00:00, 17.06it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.91it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.93it/s]

INFO 09-12 09:46:34 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:46:34 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:46:34 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:46:34 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:46:34 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:46:34 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:46:35 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:46:35 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:46:35 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:46:35 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:46:35 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:46:35 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:46:35 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:46:35 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:46:35 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:46:35 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:46:35 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:46:35 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:46:35 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:46:35 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:46:35 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:46:35 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:46:35 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.48it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.01it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.29it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:06, 11.38it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.34it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.22it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:04, 13.92it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 14.86it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 15.85it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 16.84it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:03<00:02, 17.34it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:02, 18.22it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 18.96it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 19.33it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 19.43it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 18.81it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 18.97it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.07it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.08it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 19.20it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.02it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.77it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.83it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.53it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 24.57it/s]

Capturing CUDA graphs (FULL):  39%|███▊      | 32/83 [00:01<00:01, 28.28it/s]

Capturing CUDA graphs (FULL):  48%|████▊     | 40/83 [00:01<00:01, 32.02it/s]

Capturing CUDA graphs (FULL):  59%|█████▉    | 49/83 [00:01<00:00, 36.16it/s]

Capturing CUDA graphs (FULL):  71%|███████   | 59/83 [00:01<00:00, 38.47it/s]

Capturing CUDA graphs (FULL):  83%|████████▎ | 69/83 [00:02<00:00, 39.76it/s]

Capturing CUDA graphs (FULL):  95%|█████████▌| 79/83 [00:02<00:00, 40.90it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 13.85it/s]

INFO 09-12 09:46:46 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:46:46 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:46:46 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:46:47 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:46:48 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:46:48 [core.py:361] init engine (profile, create kv cache, warmup model) took 24.87 s (compilation: 0.17 s)

INFO 09-12 09:46:49 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 110.14it/s]
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:46:49 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.18s/it, est. speed input: 38.74 toks/s, output: 30.61 toks/s]
[rank0]:[W912 09:46:54.594728371 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

brfss_diabetes Llama-3.1-8B-Instruct -> ['MICHD', 'TOLDHI', 'HIGH_BLOOD_PRESS', 'INCOME', 'HEALTH_COV', 'CHOL_CHK_PAST_5_YEARS', 'CHECKUP1', 'PHYSHLTH', 'BMI5', 'BMI5CAT']

INFO 09-12 09:47:03 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:47:03 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:47:03 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:47:03 [model.py:2021] Using max model len 8192
INFO 09-12 09:47:03 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:47:03 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:47:06 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:47:06 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_2b7b46579a33466b8555ad17f2a9724a backend=nccl
INFO 09-12 09:47:06 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:47:06 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:47:08 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:47:08 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:47:08 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:47:08 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.88 GiB.
INFO 09-12 09:47:08 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.24it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.20it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.19it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.66it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.46it/s]

INFO 09-12 09:47:11 [default_loader.py:430] Loading weights took 2.76 seconds

INFO 09-12 09:47:12 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.250921 seconds
INFO 09-12 09:47:12 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:47:12 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:47:12 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:47:12 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:47:12 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:47:13 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:25,  1.06s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:27,  2.74it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  4.99it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.35it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.56it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.23it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 12.75it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 13.97it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 14.73it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 15.88it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 16.00it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 16.94it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.50it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.14it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.18it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 16.54it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.11it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.15it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 17.24it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:09<00:00, 16.74it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.93it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 20.02it/s]

INFO 09-12 09:47:23 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:47:24 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:47:24 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:47:24 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:47:24 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:47:24 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:47:24 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:47:24 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:47:24 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:47:24 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:47:24 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:47:24 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:47:24 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:47:24 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:47:24 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:47:24 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:47:24 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:47:24 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:47:24 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:47:24 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:47:24 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:47:24 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:47:24 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.30it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.03it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.49it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 11.87it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.59it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 12.97it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:04, 14.01it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 14.48it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 15.54it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 16.06it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:03<00:02, 17.23it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:02, 18.13it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 18.41it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 18.83it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 19.00it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 19.07it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 18.90it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 18.60it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 18.77it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 18.83it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 15.91it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.94it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.99it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.70it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.89it/s]

Capturing CUDA graphs (FULL):  39%|███▊      | 32/83 [00:01<00:01, 29.10it/s]

Capturing CUDA graphs (FULL):  48%|████▊     | 40/83 [00:01<00:01, 31.25it/s]

Capturing CUDA graphs (FULL):  59%|█████▉    | 49/83 [00:01<00:00, 35.99it/s]

Capturing CUDA graphs (FULL):  71%|███████   | 59/83 [00:01<00:00, 38.36it/s]

Capturing CUDA graphs (FULL):  83%|████████▎ | 69/83 [00:02<00:00, 39.95it/s]

Capturing CUDA graphs (FULL):  95%|█████████▌| 79/83 [00:02<00:00, 41.14it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 13.85it/s]

INFO 09-12 09:47:35 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:47:35 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:47:35 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:47:36 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:47:37 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:47:37 [core.py:361] init engine (profile, create kv cache, warmup model) took 25.16 s (compilation: 0.16 s)

INFO 09-12 09:47:38 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
WARNING 09-12 09:47:38 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 108.56it/s]
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.20s/it, est. speed input: 36.65 toks/s, output: 30.46 toks/s]
[rank0]:[W912 09:47:43.735465223 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

acsincome Llama-3.1-8B-Instruct -> ['WKHP', 'WKHP', 'FER', 'HINS1', 'SCHL', 'OCCP', 'POBP', 'RELP', 'AGEP', 'HINS4', 'WKW']

INFO 09-12 09:47:52 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:47:52 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:47:52 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:47:52 [model.py:2021] Using max model len 8192
INFO 09-12 09:47:52 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:47:52 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:47:55 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:47:56 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_4ad95314ef6849569858375827213a03 backend=nccl
INFO 09-12 09:47:56 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:47:56 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:47:57 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:47:57 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:47:57 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:47:57 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.87 GiB.
INFO 09-12 09:47:57 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.26it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.20it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.19it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.65it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.46it/s]

INFO 09-12 09:48:00 [default_loader.py:430] Loading weights took 2.76 seconds

INFO 09-12 09:48:00 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.079989 seconds
INFO 09-12 09:48:00 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:48:00 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:48:01 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:48:01 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:48:01 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:48:01 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:24,  1.06s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:27,  2.76it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  5.02it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.24it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.53it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.04it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 12.64it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 13.91it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 14.60it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 15.87it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 16.24it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 17.18it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.81it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.48it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.40it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 17.59it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.64it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.66it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 17.07it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:09<00:00, 16.89it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.98it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.97it/s]

INFO 09-12 09:48:12 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:48:12 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:48:12 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:48:12 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:48:12 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:48:12 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:48:13 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:48:13 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:48:13 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:48:13 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:48:13 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:48:13 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:48:13 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:48:13 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:48:13 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:48:13 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:48:13 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:48:13 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:48:13 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:48:13 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:48:13 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:48:13 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:48:13 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.58it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:07, 10.93it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.47it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.03it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.71it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.37it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:03, 14.31it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.26it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 16.02it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 17.13it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 18.11it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:02, 18.08it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 18.92it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 18.96it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 19.24it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 19.25it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 19.24it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.26it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.00it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 18.45it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.14it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.89it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.90it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.56it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.40it/s]

Capturing CUDA graphs (FULL):  37%|███▋      | 31/83 [00:01<00:01, 28.31it/s]

Capturing CUDA graphs (FULL):  47%|████▋     | 39/83 [00:01<00:01, 31.80it/s]

Capturing CUDA graphs (FULL):  57%|█████▋    | 47/83 [00:01<00:01, 35.36it/s]

Capturing CUDA graphs (FULL):  69%|██████▊   | 57/83 [00:01<00:00, 38.09it/s]

Capturing CUDA graphs (FULL):  81%|████████  | 67/83 [00:02<00:00, 39.32it/s]

Capturing CUDA graphs (FULL):  93%|█████████▎| 77/83 [00:02<00:00, 40.29it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:06<00:00, 13.83it/s]

INFO 09-12 09:48:24 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:48:24 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:48:24 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:48:25 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:48:25 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:48:25 [core.py:361] init engine (profile, create kv cache, warmup model) took 24.82 s (compilation: 0.16 s)

INFO 09-12 09:48:27 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 103.75it/s]
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:48:28 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.24s/it, est. speed input: 22.64 toks/s, output: 30.19 toks/s]
[rank0]:[W912 09:48:32.024401183 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

acspubcov Llama-3.1-8B-Instruct -> ['AGEP', 'CIT', 'DIVISION', 'ESR', 'MAR', 'PINCP', 'RAC1P', 'SCHL', 'PINCP', 'CIT', 'ESR', 'MAR', 'RAC1P', 'SCHL', 'ACS_YEAR', 'DIVISION', 'ST']

INFO 09-12 09:48:41 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:48:41 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:48:42 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:48:42 [model.py:2021] Using max model len 8192
INFO 09-12 09:48:42 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:48:42 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:48:44 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:48:45 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_69c4c4bea5ee4656bbfac5de534c9d54 backend=nccl
INFO 09-12 09:48:45 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:48:45 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:48:46 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:48:46 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:48:46 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:48:46 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.54 GiB.
INFO 09-12 09:48:46 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.26it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.20it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.19it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.65it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.45it/s]

INFO 09-12 09:48:49 [default_loader.py:430] Loading weights took 2.77 seconds

INFO 09-12 09:48:50 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.040714 seconds
INFO 09-12 09:48:50 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:48:50 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:48:50 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:48:50 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:48:50 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:48:51 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:24,  1.06s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:27,  2.76it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  5.00it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.38it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.63it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.24it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 12.54it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 13.81it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 14.91it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 15.41it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 15.39it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 16.70it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.45it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.45it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.06it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 17.08it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.40it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.46it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 17.25it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:09<00:00, 16.71it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.91it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.95it/s]

INFO 09-12 09:49:01 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:49:01 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:49:01 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:49:01 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:49:01 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:49:01 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:49:02 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:49:02 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:49:02 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:49:02 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:49:02 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:49:02 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:49:02 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:49:02 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:49:02 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:49:02 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:49:02 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:49:02 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:49:02 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:49:02 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:49:02 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:49:02 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:49:02 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.69it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.19it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.54it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 11.52it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.54it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.25it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:04, 14.21it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.18it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 16.17it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 17.00it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 17.99it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:01, 18.76it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 19.21it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 19.38it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 18.82it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 19.03it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 19.05it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.08it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.11it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 18.60it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.17it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.94it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.92it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.28it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.49it/s]

Capturing CUDA graphs (FULL):  36%|███▌      | 30/83 [00:01<00:01, 26.63it/s]

Capturing CUDA graphs (FULL):  46%|████▌     | 38/83 [00:01<00:01, 30.93it/s]

Capturing CUDA graphs (FULL):  55%|█████▌    | 46/83 [00:01<00:01, 34.41it/s]

Capturing CUDA graphs (FULL):  66%|██████▋   | 55/83 [00:01<00:00, 37.02it/s]

Capturing CUDA graphs (FULL):  78%|███████▊  | 65/83 [00:02<00:00, 39.11it/s]

Capturing CUDA graphs (FULL):  89%|████████▉ | 74/83 [00:02<00:00, 39.01it/s]

Capturing CUDA graphs (FULL):  95%|█████████▌| 79/83 [00:02<00:00, 40.03it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:06<00:00, 13.73it/s]

INFO 09-12 09:49:13 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:49:13 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:49:13 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:49:14 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:49:15 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:49:15 [core.py:361] init engine (profile, create kv cache, warmup model) took 24.94 s (compilation: 0.16 s)

INFO 09-12 09:49:16 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Rendering prompts: 100%|██████████| 1/1 [00:00<00:00, 105.41it/s]
Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:49:17 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

Processed prompts: 100%|██████████| 1/1 [00:04<00:00,  4.27s/it, est. speed input: 34.18 toks/s, output: 29.97 toks/s]
[rank0]:[W912 09:49:21.230021124 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

anes Llama-3.1-8B-Instruct -> ['VCF0310', 'VCF0606', 'VCF0717', 'VCF0718', 'VCF0720', 'VCF0721', 'VCF0724', 'VCF0725', 'VCF9201', 'VCF0717', 'VCF0720', 'VCF0721', 'VCF9202']

## Step 2: Compute pi_behav via kNN hot-deck LOO ablation

For each feature j: hot-deck-impute it (5 nearest neighbours in the training pool, Euclidean distance on all features except j), re-run inference on the faithfulness subset (200 rows from OOD-test), compute the accuracy drop Delta_j. Rank features by Delta_j descending.

### Why hot-deck imputation, and not just zeroing/masking the feature?

This design choice is a direct application of a principle from **Zhu et al. (2026), "Faithfulness Under the Distribution: A New Look at Attribution Evaluation"** (ICLR 2026), which the lit review cites (ref [29]) specifically for this purpose. That paper's core finding, in the vision domain: standard attribution-evaluation methods (Insertion/Deletion, Infidelity) ablate a feature by zeroing or masking it, which silently introduces new, semantically meaningful evidence rather than removing information — their canonical example is a black-cat-vs-white-cat classifier, where zeroing pixels (making them black) doesn't remove information about "catness," it actively strengthens the "black cat" evidence. The perturbed sample also drifts off the training manifold entirely, and *model behaviour on out-of-distribution inputs is not a reliable signal of the model's real behaviour on the distribution it was trained on*. Using OOD model behaviour to evaluate ID feature importance is, in their words, "highly counterintuitive."

FUD's fix in the vision domain is to use a score-based diffusion model to resynthesise the masked region so it stays on the data manifold. **This project doesn't have (or need) a diffusion model for tabular data** — the equivalent, much cheaper fix for structured features is **hot-deck imputation**: replace the ablated feature's value with a real value sampled from the k=5 nearest neighbours in the training pool (by Euclidean distance on every *other* feature). This keeps the replacement value in-distribution and consistent with the row's other feature values, rather than an artificial zero the model was never trained to see meaningfully. The accuracy drop Δ_j this produces reflects the model's genuine reliance on feature j, not an artefact of showing the model a value it would never encounter naturally.

In [3]:
from tqdm import tqdm

from src.evaluation.faithfulness import hot_deck_impute_feature, compute_accuracy_drop, rank_from_deltas
from src.data.tableshift_loader import select_top_features, TASK_DESCRIPTIONS, load_codebook
from src.data.serialisation import serialise_row, ordered_feature_names
from src.inference.prompts import build_classification_prompt
from src.selection import random_select, similarity_select, label_diversity, feature_range, rule_diversity, counter_spurious
from src.selection.rule_diversity import fit_leaf_tree
from src.selection.counter_spurious import find_spurious_proxy_features

# Same dispatch logic as Notebook 02 — duplicated rather than imported since
# each notebook here is meant to be a self-contained phase of the pipeline.
def prepare_condition_artifacts(dataset_name, train_pool, feature_cols, test_ood):
    artifacts = {}
    continuous_cols = [
        c for c in feature_cols
        if pd.api.types.is_numeric_dtype(train_pool[c]) and train_pool[c].nunique() > 10
    ]
    artifacts['top3_continuous'] = (
        select_top_features(train_pool[continuous_cols + ['label']], n_features=min(3, len(continuous_cols)))
        if continuous_cols else feature_cols[:3]
    )
    artifacts['tree'] = fit_leaf_tree(train_pool, feature_cols)

    # Counter-spurious: proxy feature most correlated with both the label and
    # the actual ID->OOD shift. TableShift's own domain-split covariate (e.g.
    # race/geography/year) is deliberately excluded from X -- it's the exact
    # variable tableshift thresholds to build the ood split, so a model can't
    # just read it directly -- and extract_tableshift_cache.py, which only
    # ever saves X, never had it to cache. Proxy against literal
    # train-vs-OOD-test row membership instead: a feature correlated with
    # *that* carries the same shift signal the raw covariate would have,
    # without needing the excluded column. (Same fix as Notebook 02 -- see
    # that notebook's comment for the full rationale; duplicated here since
    # this notebook is meant to be self-contained.)
    shift_frame = pd.concat(
        [
            train_pool[feature_cols + ['label']].assign(_is_ood=0),
            test_ood[feature_cols + ['label']].assign(_is_ood=1),
        ],
        ignore_index=True,
    )
    proxy_features = find_spurious_proxy_features(shift_frame, feature_cols, 'label', '_is_ood', top_n=3)
    proxy_col = proxy_features[0] if proxy_features else feature_cols[0]
    proxy_high = train_pool[proxy_col] > train_pool[proxy_col].median()
    artifacts['proxy_col'] = proxy_col
    artifacts['proxy_majority_label'] = train_pool.loc[proxy_high, 'label'].mode().iloc[0]
    return artifacts


def select_demos(condition, pool, query, k, seed, feature_cols, artifacts):
    if condition == 'zero_shot':
        return []
    if condition == 'random':
        return random_select.select(pool, query, k, seed)
    if condition == 'label_diversity':
        return label_diversity.select(pool, query, k, seed)
    if condition == 'feature_range':
        return feature_range.select(pool, query, k, seed, top_features=artifacts['top3_continuous'])
    if condition == 'rule_diversity':
        return rule_diversity.select(pool, query, k, seed, feature_cols=feature_cols, tree=artifacts['tree'])
    if condition == 'counter_spurious':
        return counter_spurious.select(
            pool, query, k, seed, proxy_col=artifacts['proxy_col'], proxy_majority_label=artifacts['proxy_majority_label']
        )
    raise ValueError(f"Unknown condition: {condition}")


def build_demo_lines(pool, demo_ids, feature_cols, codebook=None):
    lines = []
    for i in demo_ids:
        row = pool.loc[i]
        ordered = ordered_feature_names({f: row[f] for f in feature_cols})
        lines.append(serialise_row({f: row[f] for f in ordered}, label=str(int(row['label'])), codebook=codebook))
    return lines


def build_query_line(query, feature_cols, codebook=None):
    ordered = ordered_feature_names({f: query[f] for f in feature_cols})
    return serialise_row({f: query[f] for f in ordered}, codebook=codebook)


FAITHFULNESS_SUBSET_SEED = FAITHFULNESS_SEEDS[0]
faithfulness_rows = []       # -> results/faithfulness_real.parquet (one row per feature/condition/dataset/seed)
per_row_correct_store = {}   # (dataset, model, condition, seed) -> {feature: bool array}
delta_store = {}             # (dataset, model, condition, seed) -> {feature: delta}

# ~130,000 LLM calls total (see the compute-budget note below) -- the nested
# tqdm bars give a glanceable readout of which (dataset, model, condition,
# seed, feature) is currently running its LOO ablation rerun.
dataset_bar = tqdm(FAITHFULNESS_DATASETS if VLLM_AVAILABLE else [], desc="Datasets", position=0)
for dataset_name in dataset_bar:
    dataset_bar.set_postfix(dataset=dataset_name)
    data_dir = resolve_path(config.paths.data_real) / dataset_name
    train_pool = pd.read_parquet(data_dir / 'train_pool.parquet')
    test_ood_full = pd.read_parquet(data_dir / 'test_ood.parquet')
    feature_cols = json.load(open(data_dir / 'feature_list.json'))
    label_tokens = tuple(json.load(open(data_dir / 'label_tokens.json')))
    codebook = load_codebook(data_dir)
    task_description, _task_noun, label_meaning_0, label_meaning_1 = TASK_DESCRIPTIONS[dataset_name]

    # Fixed across every condition/seed for this dataset, per the spec.
    faith_subset = test_ood_full.sample(
        n=min(config.faithfulness_subset, len(test_ood_full)), random_state=FAITHFULNESS_SUBSET_SEED
    ).reset_index(drop=True)

    artifacts = prepare_condition_artifacts(dataset_name, train_pool, feature_cols, test_ood_full)

    for model_cfg in config.base_llms:
        # VLLMWorkerRunner (not VLLMRunner): runs vLLM in a separate OS
        # subprocess so its GPU memory is guaranteed to be released on
        # shutdown() -- vLLM's in-process engine does not reliably free GPU
        # memory after explicit teardown, which matters here since this loop
        # constructs a fresh runner per (dataset, model) pair.
        runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))
        best_protocol = best_protocol_for(dataset_name, model_cfg.name, baseline_summary)
        conditions_to_eval = ['random', best_protocol]

        # Similarity is deterministic (no seed dependency), so if it's one of
        # this dataset/model's 2 conditions, precompute its demo ids once here
        # (one batched encode() call) rather than inside the seed loop below,
        # which would otherwise re-embed the same faith_subset queries
        # identically on every one of the 3 seeds.
        similarity_demo_ids = None
        if 'similarity' in conditions_to_eval:
            pool_texts = [
                serialise_row(
                    {f: train_pool.loc[i, f] for f in ordered_feature_names({f: train_pool.loc[i, f] for f in feature_cols})},
                    label=str(int(train_pool.loc[i, 'label'])),
                    codebook=codebook,
                )
                for i in train_pool.index
            ]
            query_texts = [
                serialise_row(
                    {f: row[f] for f in ordered_feature_names({f: row[f] for f in feature_cols})},
                    codebook=codebook,
                )
                for _, row in faith_subset.iterrows()
            ]
            local_idx_per_query = similarity_select.select_batch(pool_texts, query_texts, config.k_primary)
            similarity_demo_ids = [[train_pool.index[i] for i in local_idx] for local_idx in local_idx_per_query]

        condition_bar = tqdm(conditions_to_eval, desc="Conditions", position=1, leave=False)
        for condition in condition_bar:
            condition_bar.set_postfix(condition=condition, model=model_cfg.name)
            seed_bar = tqdm(FAITHFULNESS_SEEDS, desc="Seeds", position=2, leave=False)
            for seed in seed_bar:
                seed_bar.set_postfix(seed=int(seed))
                # Demos are fixed per query across the original run and every feature
                # ablation rerun below, so only the ablated feature can flip a prediction.
                if condition == 'similarity':
                    demo_ids_per_query = similarity_demo_ids
                else:
                    demo_ids_per_query = [
                        select_demos(condition, train_pool, row, config.k_primary, seed, feature_cols, artifacts)
                        for _, row in faith_subset.iterrows()
                    ]

                def run_inference(df):
                    prompts = [
                        build_classification_prompt(
                            task_description, label_tokens,
                            build_demo_lines(train_pool, demo_ids, feature_cols, codebook),
                            build_query_line(row, feature_cols, codebook),
                            label_meanings=(label_meaning_0, label_meaning_1),
                        )
                        for (_, row), demo_ids in zip(df.iterrows(), demo_ids_per_query)
                    ]
                    preds = runner.batch_predict(prompts, label_tokens)
                    return np.array([p.prediction == str(int(row['label'])) for p, (_, row) in zip(preds, df.iterrows())])

                original_correct = run_inference(faith_subset)

                deltas, per_row_correct = {}, {}
                feature_bar = tqdm(feature_cols, desc="Features (LOO ablation)", position=3, leave=False)
                for feature in feature_bar:
                    feature_bar.set_postfix(feature=feature)
                    modified = hot_deck_impute_feature(faith_subset, feature, train_pool, feature_cols, seed=seed)
                    modified_correct = run_inference(modified)
                    deltas[feature] = compute_accuracy_drop(original_correct, modified_correct)
                    per_row_correct[feature] = modified_correct

                    faithfulness_rows.append({
                        'dataset': dataset_name, 'model': model_cfg.name, 'method': condition,
                        'seed': int(seed), 'feature': feature, 'delta': deltas[feature],
                    })

                per_row_correct_store[(dataset_name, model_cfg.name, condition, seed)] = per_row_correct
                delta_store[(dataset_name, model_cfg.name, condition, seed)] = deltas
                tqdm.write(f"{dataset_name} {model_cfg.name} {condition} {seed} pi_behav done")

        runner.shutdown()

if not VLLM_AVAILABLE:
    print("Skipped — vLLM not installed in this environment.")

Datasets:   0%|          | 0/4 [00:00<?, ?it/s]

Datasets:   0%|          | 0/4 [00:00<?, ?it/s, dataset=brfss_diabetes]

INFO 09-12 09:49:30 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:49:30 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:49:31 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:49:31 [model.py:2021] Using max model len 8192
INFO 09-12 09:49:31 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:49:31 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:49:33 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:49:34 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_eb1f39e4d5e4459ba33010e676221a3d backend=nccl
INFO 09-12 09:49:34 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:49:34 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:49:35 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:49:35 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:49:35 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:49:35 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.46 GiB.
INFO 09-12 09:49:35 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.26it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.20it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.19it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.65it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.46it/s]

INFO 09-12 09:49:38 [default_loader.py:430] Loading weights took 2.76 seconds

INFO 09-12 09:49:38 [model_runner.py:404] Model loading took 15.0 GiB memory and 3.985984 seconds
INFO 09-12 09:49:38 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:49:38 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:49:39 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:49:39 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:49:39 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:49:39 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:25,  1.06s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:27,  2.75it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  4.96it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.29it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.29it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 10.78it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:06<00:04, 12.45it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 13.80it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 14.98it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 16.00it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 16.27it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 17.36it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.98it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.66it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.40it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 17.62it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.78it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.34it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 16.88it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:09<00:00, 16.94it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.95it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 20.00it/s]

INFO 09-12 09:49:50 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:49:50 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:49:50 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:49:50 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:49:50 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:49:50 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:49:51 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:49:51 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:49:51 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:49:51 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:49:51 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:49:51 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:49:51 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:49:51 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:49:51 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:49:51 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:49:51 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:49:51 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:49:51 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:49:51 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:49:51 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:49:51 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:49:51 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.69it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:07, 10.85it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.50it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.07it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.73it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.47it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:03, 14.42it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.39it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 16.17it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 17.04it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 18.09it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:02, 17.92it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 18.85it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 18.96it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 18.93it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 19.23it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 19.18it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.21it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.06it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 18.97it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.22it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.96it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.94it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.59it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.80it/s]

Capturing CUDA graphs (FULL):  39%|███▊      | 32/83 [00:01<00:01, 28.93it/s]

Capturing CUDA graphs (FULL):  48%|████▊     | 40/83 [00:01<00:01, 32.42it/s]

Capturing CUDA graphs (FULL):  58%|█████▊    | 48/83 [00:01<00:00, 35.74it/s]

Capturing CUDA graphs (FULL):  70%|██████▉   | 58/83 [00:01<00:00, 38.51it/s]

Capturing CUDA graphs (FULL):  82%|████████▏ | 68/83 [00:02<00:00, 39.76it/s]

Capturing CUDA graphs (FULL):  94%|█████████▍| 78/83 [00:02<00:00, 40.81it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 13.91it/s]

INFO 09-12 09:50:02 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:50:02 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:50:02 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:50:03 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:50:03 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:50:03 [core.py:361] init engine (profile, create kv cache, warmup model) took 24.79 s (compilation: 0.16 s)

INFO 09-12 09:50:05 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]

Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 327.93it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 345.35it/s]

Rendering prompts:  52%|█████▎    | 105/200 [00:00<00:00, 348.34it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 350.96it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 349.96it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:50:06 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 09:50:10 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CachedTokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Processed prompts:  40%|████      | 81/200 [00:04<00:04, 24.87it/s, est. speed input: 30970.78 toks/s, output: 17.68 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:04<00:00, 43.47it/s, est. speed input: 76116.55 toks/s, output: 43.47 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=BMI5]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  18%|█▊        | 35/200 [00:00<00:00, 343.03it/s]

Rendering prompts:  35%|███▌      | 70/200 [00:00<00:00, 343.81it/s]

Rendering prompts:  52%|█████▎    | 105/200 [00:00<00:00, 344.06it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 343.36it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 342.81it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 428.13it/s, est. speed input: 749767.33 toks/s, output: 428.21 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.20s/it, feature=BMI5]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.20s/it, feature=BMI5CAT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 329.30it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 334.00it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 334.73it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 336.13it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.65it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 851.35it/s, est. speed input: 1491230.40 toks/s, output: 851.67 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.07s/it, feature=BMI5CAT]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.07s/it, feature=CHECKUP1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.93it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.42it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.95it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 338.04it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.43it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 615.55it/s, est. speed input: 1078019.25 toks/s, output: 615.72 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.06s/it, feature=CHECKUP1]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.06s/it, feature=CHOL_CHK_PAST_5_YEARS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.30it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.24it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.37it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 336.01it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 334.47it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 549.79it/s, est. speed input: 962636.66 toks/s, output: 549.94 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.08s/it, feature=CHOL_CHK_PAST_5_YEARS]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.08s/it, feature=HEALTH_COV]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▌        | 31/200 [00:00<00:00, 307.60it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 322.33it/s]

Rendering prompts:  50%|████▉     | 99/200 [00:00<00:00, 327.50it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 326.08it/s]

Rendering prompts:  83%|████████▎ | 166/200 [00:00<00:00, 329.35it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 328.10it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 574.07it/s, est. speed input: 1006966.83 toks/s, output: 574.25 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.09s/it, feature=HEALTH_COV]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.09s/it, feature=HIGH_BLOOD_PRESS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 332.44it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 334.46it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.67it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 334.58it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 650.17it/s, est. speed input: 1138727.70 toks/s, output: 650.36 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.08s/it, feature=HIGH_BLOOD_PRESS]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.08s/it, feature=INCOME]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.23it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.31it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.24it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 337.80it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.79it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 522.06it/s, est. speed input: 916727.39 toks/s, output: 522.19 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=INCOME]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=MICHD]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 338.66it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 338.84it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 340.28it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 340.62it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 815.01it/s, est. speed input: 1427502.00 toks/s, output: 815.31 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=MICHD]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=PHYSHLTH]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 333.86it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.44it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 338.26it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 340.05it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 339.84it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 839.65it/s, est. speed input: 1470815.45 toks/s, output: 839.97 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=PHYSHLTH]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=TOLDHI]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.63it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 334.91it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 324.01it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 327.67it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 331.67it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 876.90it/s, est. speed input: 1536065.57 toks/s, output: 877.31 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:10<00:00,  1.01s/it, feature=TOLDHI]

Datasets:   0%|          | 0/4 [00:58<?, ?it/s, dataset=brfss_diabetes]

Conditions:   0%|          | 0/2 [00:15<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:15<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:15<00:31, 15.88s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:15<00:31, 15.88s/it, seed=123]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

brfss_diabetes Llama-3.1-8B-Instruct random 42 pi_behav done

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.83it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.26it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.50it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 337.65it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.33it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  40%|███▉      | 79/200 [00:00<00:00, 203.04it/s, est. speed input: 291627.12 toks/s, output: 165.83 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 400.44it/s, est. speed input: 704115.83 toks/s, output: 400.54 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=BMI5]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 337.11it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 340.04it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 340.43it/s]

Rendering prompts:  70%|██████▉   | 139/200 [00:00<00:00, 337.98it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 339.80it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 438.98it/s, est. speed input: 771835.22 toks/s, output: 439.06 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.19s/it, feature=BMI5]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.19s/it, feature=BMI5CAT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 339.81it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 341.10it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 341.37it/s]

Rendering prompts:  70%|██████▉   | 139/200 [00:00<00:00, 342.07it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 340.92it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 869.58it/s, est. speed input: 1529274.74 toks/s, output: 869.92 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.05s/it, feature=BMI5CAT]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.05s/it, feature=CHECKUP1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.73it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.71it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 338.38it/s]

Rendering prompts:  85%|████████▌ | 170/200 [00:00<00:00, 338.78it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.72it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 645.87it/s, est. speed input: 1135707.99 toks/s, output: 646.07 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.05s/it, feature=CHECKUP1]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.05s/it, feature=CHOL_CHK_PAST_5_YEARS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 333.04it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.77it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.83it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 338.88it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.82it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 574.52it/s, est. speed input: 1009976.11 toks/s, output: 574.67 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.06s/it, feature=CHOL_CHK_PAST_5_YEARS]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.06s/it, feature=HEALTH_COV]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.68it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 335.48it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 329.51it/s]

Rendering prompts:  85%|████████▌ | 170/200 [00:00<00:00, 335.48it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.06it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 567.75it/s, est. speed input: 1000149.17 toks/s, output: 567.90 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.07s/it, feature=HEALTH_COV]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.07s/it, feature=HIGH_BLOOD_PRESS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 338.43it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.94it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.50it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 339.51it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 340.25it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 619.73it/s, est. speed input: 1089736.47 toks/s, output: 619.90 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=HIGH_BLOOD_PRESS]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=INCOME]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.56it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.13it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.28it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.63it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.83it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 527.04it/s, est. speed input: 927971.38 toks/s, output: 527.17 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.08s/it, feature=INCOME]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.08s/it, feature=MICHD]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 332.90it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 334.61it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.08it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 336.09it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 334.95it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 826.45it/s, est. speed input: 1453207.16 toks/s, output: 826.76 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=MICHD]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=PHYSHLTH]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.28it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.38it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 336.76it/s]

Rendering prompts:  85%|████████▌ | 170/200 [00:00<00:00, 338.21it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.49it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 822.95it/s, est. speed input: 1447265.17 toks/s, output: 823.27 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=PHYSHLTH]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=TOLDHI]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 338.78it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 338.72it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 339.85it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 340.04it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 889.27it/s, est. speed input: 1563813.11 toks/s, output: 889.62 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:10<00:00,  1.01s/it, feature=TOLDHI]

Datasets:   0%|          | 0/4 [01:10<?, ?it/s, dataset=brfss_diabetes]

Conditions:   0%|          | 0/2 [00:27<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:27<00:31, 15.88s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:27<00:13, 13.44s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:27<00:13, 13.44s/it, seed=456]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

brfss_diabetes Llama-3.1-8B-Instruct random 123 pi_behav done

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 322.35it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 333.00it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.93it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 337.10it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.98it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 359.17it/s, est. speed input: 631875.48 toks/s, output: 359.24 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=BMI5]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.16it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 335.68it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.36it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 338.80it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.86it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 446.61it/s, est. speed input: 785734.70 toks/s, output: 446.71 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.19s/it, feature=BMI5]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.19s/it, feature=BMI5CAT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.06it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.42it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.63it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 336.31it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.07it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 861.29it/s, est. speed input: 1515657.34 toks/s, output: 861.69 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.06s/it, feature=BMI5CAT]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.06s/it, feature=CHECKUP1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.83it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 338.15it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 338.65it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 339.71it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.38it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 654.35it/s, est. speed input: 1151238.38 toks/s, output: 654.55 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.05s/it, feature=CHECKUP1]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.05s/it, feature=CHOL_CHK_PAST_5_YEARS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.55it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.02it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.74it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.77it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 333.56it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 572.87it/s, est. speed input: 1007656.06 toks/s, output: 573.03 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=CHOL_CHK_PAST_5_YEARS]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=HEALTH_COV]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 332.68it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 335.38it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.51it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.89it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.01it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 552.74it/s, est. speed input: 974222.51 toks/s, output: 552.89 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HEALTH_COV]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HIGH_BLOOD_PRESS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 312.86it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 325.53it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 329.47it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 334.46it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.42it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 619.00it/s, est. speed input: 1089088.77 toks/s, output: 619.18 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.08s/it, feature=HIGH_BLOOD_PRESS]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.08s/it, feature=INCOME]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.83it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.76it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 342.28it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 519.39it/s, est. speed input: 915002.52 toks/s, output: 519.51 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=INCOME]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=MICHD]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  18%|█▊        | 35/200 [00:00<00:00, 342.82it/s]

Rendering prompts:  35%|███▌      | 70/200 [00:00<00:00, 342.58it/s]

Rendering prompts:  52%|█████▎    | 105/200 [00:00<00:00, 343.44it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 344.52it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 345.11it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 830.65it/s, est. speed input: 1461518.75 toks/s, output: 830.96 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=MICHD]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=PHYSHLTH]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.12it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.71it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.81it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 337.61it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.91it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 832.56it/s, est. speed input: 1465026.02 toks/s, output: 832.90 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=PHYSHLTH]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=TOLDHI]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.67it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 338.85it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 339.05it/s]

Rendering prompts:  69%|██████▉   | 138/200 [00:00<00:00, 335.96it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.94it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 873.67it/s, est. speed input: 1537243.68 toks/s, output: 874.05 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:10<00:00,  1.01s/it, feature=TOLDHI]

Datasets:   0%|          | 0/4 [01:22<?, ?it/s, dataset=brfss_diabetes]

Conditions:   0%|          | 0/2 [00:39<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:39<00:13, 13.44s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:39<00:00, 12.69s/it, seed=456]

Conditions:  50%|█████     | 1/2 [00:39<00:39, 39.41s/it, condition=random, model=Llama-3.1-8B-Instruct]

Conditions:  50%|█████     | 1/2 [00:39<00:39, 39.41s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

brfss_diabetes Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▌        | 32/200 [00:00<00:00, 314.40it/s]

Rendering prompts:  33%|███▎      | 66/200 [00:00<00:00, 326.49it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 330.00it/s]

Rendering prompts:  67%|██████▋   | 134/200 [00:00<00:00, 332.49it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 330.00it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  42%|████▎     | 85/200 [00:00<00:00, 222.88it/s, est. speed input: 325752.93 toks/s, output: 184.94 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 421.28it/s, est. speed input: 742084.66 toks/s, output: 421.42 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=BMI5]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 319.08it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 330.59it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 333.10it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 334.48it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 334.63it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 434.35it/s, est. speed input: 765022.76 toks/s, output: 434.44 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.20s/it, feature=BMI5]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.20s/it, feature=BMI5CAT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.35it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 335.09it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.98it/s]

Rendering prompts:  85%|████████▌ | 170/200 [00:00<00:00, 337.98it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.60it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 877.58it/s, est. speed input: 1545986.81 toks/s, output: 877.93 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.06s/it, feature=BMI5CAT]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.06s/it, feature=CHECKUP1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.54it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.53it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.44it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 336.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.34it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 623.87it/s, est. speed input: 1098835.52 toks/s, output: 624.04 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.06s/it, feature=CHECKUP1]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.06s/it, feature=CHOL_CHK_PAST_5_YEARS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 335.69it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 338.62it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 338.41it/s]

Rendering prompts:  69%|██████▉   | 138/200 [00:00<00:00, 336.06it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.62it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 558.94it/s, est. speed input: 984244.80 toks/s, output: 559.09 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=CHOL_CHK_PAST_5_YEARS]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=HEALTH_COV]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 332.51it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 334.41it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.08it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 334.60it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 332.87it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 565.00it/s, est. speed input: 996670.19 toks/s, output: 565.15 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HEALTH_COV]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HIGH_BLOOD_PRESS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  18%|█▊        | 35/200 [00:00<00:00, 342.45it/s]

Rendering prompts:  35%|███▌      | 70/200 [00:00<00:00, 346.60it/s]

Rendering prompts:  52%|█████▎    | 105/200 [00:00<00:00, 347.03it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 347.52it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 348.23it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 635.26it/s, est. speed input: 1118966.76 toks/s, output: 635.45 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=HIGH_BLOOD_PRESS]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=INCOME]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 318.07it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 328.47it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 331.40it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 333.46it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 333.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 521.51it/s, est. speed input: 920963.29 toks/s, output: 521.63 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=INCOME]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=MICHD]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 333.91it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 335.91it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 336.52it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 334.13it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.18it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 820.46it/s, est. speed input: 1445276.25 toks/s, output: 820.78 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=MICHD]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.05s/it, feature=PHYSHLTH]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 330.79it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 330.41it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 330.65it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 333.02it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.65it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 819.62it/s, est. speed input: 1443858.52 toks/s, output: 819.94 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=PHYSHLTH]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.03s/it, feature=TOLDHI]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 324.09it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 330.24it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 328.40it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 333.16it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.18it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 878.05it/s, est. speed input: 1546765.52 toks/s, output: 878.41 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:10<00:00,  1.01s/it, feature=TOLDHI]

Datasets:   0%|          | 0/4 [01:34<?, ?it/s, dataset=brfss_diabetes]

Conditions:  50%|█████     | 1/2 [00:51<00:39, 39.41s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:11<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:11<00:23, 11.80s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:11<00:23, 11.80s/it, seed=123]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

brfss_diabetes Llama-3.1-8B-Instruct label_diversity 42 pi_behav done

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 333.84it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 335.48it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.94it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.61it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 334.43it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  40%|████      | 81/200 [00:00<00:00, 213.98it/s, est. speed input: 312121.75 toks/s, output: 178.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 420.73it/s, est. speed input: 737703.79 toks/s, output: 420.84 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=BMI5]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 333.17it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 334.50it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.28it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.15it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.00it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 442.26it/s, est. speed input: 775399.28 toks/s, output: 442.34 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.19s/it, feature=BMI5]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.19s/it, feature=BMI5CAT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 329.00it/s]

Rendering prompts:  33%|███▎      | 66/200 [00:00<00:00, 322.68it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 328.14it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 334.14it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.74it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 860.68it/s, est. speed input: 1509349.12 toks/s, output: 861.04 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.07s/it, feature=BMI5CAT]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.07s/it, feature=CHECKUP1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 333.52it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 333.72it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 334.99it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.96it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.41it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 621.45it/s, est. speed input: 1089673.59 toks/s, output: 621.65 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.06s/it, feature=CHECKUP1]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.06s/it, feature=CHOL_CHK_PAST_5_YEARS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 327.41it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 331.57it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 330.52it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 334.79it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.10it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 578.28it/s, est. speed input: 1013684.68 toks/s, output: 578.43 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=CHOL_CHK_PAST_5_YEARS]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=HEALTH_COV]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 338.65it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 341.40it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 342.10it/s]

Rendering prompts:  70%|██████▉   | 139/200 [00:00<00:00, 340.39it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 342.35it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 574.01it/s, est. speed input: 1008303.21 toks/s, output: 574.16 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HEALTH_COV]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HIGH_BLOOD_PRESS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.68it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.30it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 336.27it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 337.00it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.86it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 630.48it/s, est. speed input: 1105559.40 toks/s, output: 630.70 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=HIGH_BLOOD_PRESS]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=INCOME]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.19it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 338.00it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 338.10it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 339.06it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 339.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 520.16it/s, est. speed input: 913234.98 toks/s, output: 520.28 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=INCOME]

Features (LOO ablation):  70%|███████   | 7/10 [00:07<00:03,  1.09s/it, feature=MICHD]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▌        | 31/200 [00:00<00:00, 307.80it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 325.12it/s]

Rendering prompts:  50%|████▉     | 99/200 [00:00<00:00, 330.19it/s]

Rendering prompts:  66%|██████▋   | 133/200 [00:00<00:00, 332.89it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 332.30it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 787.58it/s, est. speed input: 1380933.08 toks/s, output: 787.88 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.06s/it, feature=MICHD]

Features (LOO ablation):  80%|████████  | 8/10 [00:08<00:02,  1.06s/it, feature=PHYSHLTH]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▌        | 32/200 [00:00<00:00, 319.70it/s]

Rendering prompts:  33%|███▎      | 66/200 [00:00<00:00, 327.71it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 331.50it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 336.32it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.15it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 818.84it/s, est. speed input: 1435950.11 toks/s, output: 819.16 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.04s/it, feature=PHYSHLTH]

Features (LOO ablation):  90%|█████████ | 9/10 [00:09<00:01,  1.04s/it, feature=TOLDHI]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  18%|█▊        | 35/200 [00:00<00:00, 341.66it/s]

Rendering prompts:  35%|███▌      | 70/200 [00:00<00:00, 345.76it/s]

Rendering prompts:  52%|█████▎    | 105/200 [00:00<00:00, 346.01it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 346.62it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 347.23it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 868.23it/s, est. speed input: 1522529.27 toks/s, output: 868.60 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:10<00:00,  1.01s/it, feature=TOLDHI]

Datasets:   0%|          | 0/4 [01:46<?, ?it/s, dataset=brfss_diabetes]

Conditions:  50%|█████     | 1/2 [01:03<00:39, 39.41s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:23<00:23, 11.80s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:23<00:11, 11.79s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:23<00:11, 11.79s/it, seed=456]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

brfss_diabetes Llama-3.1-8B-Instruct label_diversity 123 pi_behav done

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.33it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.49it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 335.78it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 339.11it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 341.48it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  41%|████      | 82/200 [00:00<00:00, 215.39it/s, est. speed input: 310763.56 toks/s, output: 179.17 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 419.87it/s, est. speed input: 728214.26 toks/s, output: 419.98 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=BMI5]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.11it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 338.72it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 338.75it/s]

Rendering prompts:  69%|██████▉   | 138/200 [00:00<00:00, 339.58it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 338.39it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 447.30it/s, est. speed input: 775754.92 toks/s, output: 447.40 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.18s/it, feature=BMI5]

Features (LOO ablation):  10%|█         | 1/10 [00:01<00:10,  1.18s/it, feature=BMI5CAT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 325.35it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 331.63it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 332.37it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 333.05it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 333.53it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 835.39it/s, est. speed input: 1449129.81 toks/s, output: 835.74 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.07s/it, feature=BMI5CAT]

Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.07s/it, feature=CHECKUP1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▌        | 32/200 [00:00<00:00, 319.77it/s]

Rendering prompts:  32%|███▏      | 64/200 [00:00<00:00, 309.86it/s]

Rendering prompts:  49%|████▉     | 98/200 [00:00<00:00, 320.91it/s]

Rendering prompts:  66%|██████▋   | 133/200 [00:00<00:00, 328.86it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 331.62it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 635.34it/s, est. speed input: 1101918.44 toks/s, output: 635.54 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.07s/it, feature=CHECKUP1]

Features (LOO ablation):  30%|███       | 3/10 [00:03<00:07,  1.07s/it, feature=CHOL_CHK_PAST_5_YEARS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  18%|█▊        | 35/200 [00:00<00:00, 345.46it/s]

Rendering prompts:  35%|███▌      | 70/200 [00:00<00:00, 343.55it/s]

Rendering prompts:  52%|█████▎    | 105/200 [00:00<00:00, 345.49it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 346.83it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 347.35it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 561.04it/s, est. speed input: 972788.28 toks/s, output: 561.18 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=CHOL_CHK_PAST_5_YEARS]

Features (LOO ablation):  40%|████      | 4/10 [00:04<00:06,  1.07s/it, feature=HEALTH_COV]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.03it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.67it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 336.04it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 337.13it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.99it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 570.61it/s, est. speed input: 991441.55 toks/s, output: 570.76 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HEALTH_COV]

Features (LOO ablation):  50%|█████     | 5/10 [00:05<00:05,  1.08s/it, feature=HIGH_BLOOD_PRESS]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 336.30it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 337.60it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 337.87it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 336.39it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 337.42it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 628.92it/s, est. speed input: 1090814.60 toks/s, output: 629.10 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=HIGH_BLOOD_PRESS]

Features (LOO ablation):  60%|██████    | 6/10 [00:06<00:04,  1.07s/it, feature=INCOME]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 337.45it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 338.94it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 338.57it/s]

Rendering prompts:  69%|██████▉   | 138/200 [00:00<00:00, 340.68it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 341.68it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Processed prompts: 100%|██████████| 200/200 [00:04<00:00, 48.49it/s, est. speed input: 84201.46 toks/s, output: 48.50 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:11<00:06,  2.31s/it, feature=INCOME]

Features (LOO ablation):  70%|███████   | 7/10 [00:11<00:06,  2.31s/it, feature=MICHD]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.84it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.90it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 338.82it/s]

Rendering prompts:  69%|██████▉   | 138/200 [00:00<00:00, 339.58it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 339.66it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 814.51it/s, est. speed input: 1412771.23 toks/s, output: 814.83 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:12<00:03,  1.89s/it, feature=MICHD]

Features (LOO ablation):  80%|████████  | 8/10 [00:12<00:03,  1.89s/it, feature=PHYSHLTH]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  17%|█▋        | 34/200 [00:00<00:00, 334.88it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 336.66it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 336.08it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 336.26it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 336.29it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 783.19it/s, est. speed input: 1358552.00 toks/s, output: 783.50 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:13<00:01,  1.61s/it, feature=PHYSHLTH]

Features (LOO ablation):  90%|█████████ | 9/10 [00:13<00:01,  1.61s/it, feature=TOLDHI]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  16%|█▋        | 33/200 [00:00<00:00, 321.11it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 329.40it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 333.35it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 335.94it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 335.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 861.51it/s, est. speed input: 1494293.12 toks/s, output: 861.88 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:14<00:00,  1.41s/it, feature=TOLDHI]

Datasets:   0%|          | 0/4 [02:01<?, ?it/s, dataset=brfss_diabetes]

Conditions:  50%|█████     | 1/2 [01:18<00:39, 39.41s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:39<00:11, 11.79s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:39<00:00, 13.50s/it, seed=456]

Conditions: 100%|██████████| 2/2 [01:18<00:00, 39.25s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

[rank0]:[W912 09:51:24.734940983 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

brfss_diabetes Llama-3.1-8B-Instruct label_diversity 456 pi_behav done

Datasets:  25%|██▌       | 1/4 [02:02<06:07, 122.48s/it, dataset=brfss_diabetes]

Datasets:  25%|██▌       | 1/4 [02:02<06:07, 122.48s/it, dataset=acsincome]

INFO 09-12 09:51:33 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:51:33 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:51:33 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:51:33 [model.py:2021] Using max model len 8192
INFO 09-12 09:51:33 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:51:33 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:51:36 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:51:37 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_d4fd0c0f4d794c0fb8d50cde470ce92a backend=nccl
INFO 09-12 09:51:37 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:51:37 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:51:38 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:51:38 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:51:38 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:51:38 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.78 GiB.
INFO 09-12 09:51:38 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.24it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.18it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.17it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.63it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.44it/s]

INFO 09-12 09:51:41 [default_loader.py:430] Loading weights took 2.80 seconds

INFO 09-12 09:51:42 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.127657 seconds
INFO 09-12 09:51:42 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:51:42 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:51:42 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:51:42 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:51:42 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:51:43 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:25,  1.07s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:27,  2.75it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  4.98it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.34it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.65it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.26it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 12.58it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 13.87it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 14.97it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 16.04it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 15.47it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 16.73it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.44it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.50it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.00it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 17.04it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.31it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.44it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 17.15it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:09<00:00, 16.56it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.92it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.96it/s]

INFO 09-12 09:51:53 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:51:54 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:51:54 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:51:54 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:51:54 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:51:54 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:51:54 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:51:54 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:51:54 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:51:54 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:51:54 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:51:54 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:51:54 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:51:54 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:51:54 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:51:54 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:51:54 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:51:54 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:51:54 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:51:54 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:51:54 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:51:54 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:51:54 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.64it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.14it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.44it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.02it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.16it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.10it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:04, 14.20it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.25it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 16.26it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 17.12it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 17.90it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:01, 18.77it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 19.28it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 19.39it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 19.44it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 19.15it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 19.17it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.21it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.25it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 19.30it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.21it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 21.04it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 22.04it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.54it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.49it/s]

Capturing CUDA graphs (FULL):  39%|███▊      | 32/83 [00:01<00:01, 28.80it/s]

Capturing CUDA graphs (FULL):  48%|████▊     | 40/83 [00:01<00:01, 31.56it/s]

Capturing CUDA graphs (FULL):  59%|█████▉    | 49/83 [00:01<00:00, 34.70it/s]

Capturing CUDA graphs (FULL):  70%|██████▉   | 58/83 [00:01<00:00, 36.85it/s]

Capturing CUDA graphs (FULL):  82%|████████▏ | 68/83 [00:02<00:00, 39.00it/s]

Capturing CUDA graphs (FULL):  94%|█████████▍| 78/83 [00:02<00:00, 40.57it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:06<00:00, 13.78it/s]

INFO 09-12 09:52:05 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:52:05 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:52:05 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:52:06 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:52:07 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:52:07 [core.py:361] init engine (profile, create kv cache, warmup model) took 24.99 s (compilation: 0.16 s)

INFO 09-12 09:52:08 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]

Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  44%|████▍     | 89/200 [00:00<00:00, 447.52it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 457.43it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:52:09 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 09:52:13 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CachedTokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Processed prompts: 100%|██████████| 200/200 [00:04<00:00, 45.11it/s, est. speed input: 54413.14 toks/s, output: 45.12 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 466.41it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 471.16it/s]

Rendering prompts:  72%|███████▏  | 143/200 [00:00<00:00, 470.64it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 470.18it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 650.16it/s, est. speed input: 784403.46 toks/s, output: 650.36 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=AGEP]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=FER]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 464.00it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 465.65it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 468.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.88it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 883.78it/s, est. speed input: 1065731.82 toks/s, output: 884.14 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.20it/s, feature=FER]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.20it/s, feature=HINS1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 462.73it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 465.87it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 466.67it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 468.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 860.05it/s, est. speed input: 1037769.93 toks/s, output: 860.43 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=HINS1]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=HINS4]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 464.11it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 464.70it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 459.87it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 465.22it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 978.87it/s, est. speed input: 1181180.83 toks/s, output: 979.33 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=HINS4]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=OCCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 465.36it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.49it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 469.16it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 719.30it/s, est. speed input: 867915.19 toks/s, output: 719.57 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=OCCP]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=POBP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 465.22it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 468.90it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 465.07it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.84it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 723.81it/s, est. speed input: 873249.78 toks/s, output: 724.04 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.21it/s, feature=POBP]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.21it/s, feature=RELP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 469.97it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 471.43it/s]

Rendering prompts:  72%|███████▏  | 143/200 [00:00<00:00, 472.02it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 471.09it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 892.47it/s, est. speed input: 1076927.60 toks/s, output: 892.88 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.23it/s, feature=RELP]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.23it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 468.59it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 471.50it/s]

Rendering prompts:  72%|███████▏  | 143/200 [00:00<00:00, 471.66it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 471.19it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 829.89it/s, est. speed input: 1001505.69 toks/s, output: 830.21 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.23it/s, feature=SCHL]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.23it/s, feature=WKHP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 466.78it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 453.72it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 460.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 464.03it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 950.47it/s, est. speed input: 1146951.10 toks/s, output: 950.95 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.24it/s, feature=WKHP]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.24it/s, feature=WKW]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 453.75it/s]

Rendering prompts:  46%|████▌     | 92/200 [00:00<00:00, 449.41it/s]

Rendering prompts:  70%|██████▉   | 139/200 [00:00<00:00, 457.60it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 458.63it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1066.65it/s, est. speed input: 1287245.66 toks/s, output: 1067.27 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.26it/s, feature=WKW]

Datasets:  25%|██▌       | 1/4 [02:59<06:07, 122.48s/it, dataset=acsincome]

Seeds:   0%|          | 0/3 [00:13<?, ?it/s, seed=42]

Conditions:   0%|          | 0/2 [00:13<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:13<00:26, 13.12s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:13<00:26, 13.12s/it, seed=123]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

acsincome Llama-3.1-8B-Instruct random 42 pi_behav done

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 468.38it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 469.64it/s]

Rendering prompts:  72%|███████▏  | 143/200 [00:00<00:00, 470.26it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 471.24it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 586.93it/s, est. speed input: 702266.70 toks/s, output: 587.13 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 467.94it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 468.43it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.27it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 469.81it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 647.80it/s, est. speed input: 775105.40 toks/s, output: 648.02 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=AGEP]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=FER]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 469.17it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.49it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 874.01it/s, est. speed input: 1045710.26 toks/s, output: 874.36 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.21it/s, feature=FER]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.21it/s, feature=HINS1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 464.31it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 467.52it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 468.95it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.43it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 875.16it/s, est. speed input: 1047192.69 toks/s, output: 875.50 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=HINS1]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=HINS4]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 462.72it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 465.62it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 466.35it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 466.44it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 950.86it/s, est. speed input: 1137841.31 toks/s, output: 951.28 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=HINS4]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=OCCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  22%|██▎       | 45/200 [00:00<00:00, 448.05it/s]

Rendering prompts:  70%|██████▉   | 139/200 [00:00<00:00, 464.39it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 464.69it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 700.24it/s, est. speed input: 837836.02 toks/s, output: 700.46 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=OCCP]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=POBP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 463.32it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.36it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.90it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 763.70it/s, est. speed input: 913776.08 toks/s, output: 763.95 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.21it/s, feature=POBP]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.21it/s, feature=RELP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 462.98it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 466.79it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.69it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 849.77it/s, est. speed input: 1016856.36 toks/s, output: 850.12 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.22it/s, feature=RELP]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.22it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 470.75it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 468.73it/s]

Rendering prompts:  72%|███████▏  | 144/200 [00:00<00:00, 470.55it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 471.40it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 877.49it/s, est. speed input: 1049880.70 toks/s, output: 877.83 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.23it/s, feature=SCHL]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.23it/s, feature=WKHP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 462.44it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 464.78it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 462.25it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 465.14it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1026.11it/s, est. speed input: 1228011.60 toks/s, output: 1026.67 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.26it/s, feature=WKHP]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.26it/s, feature=WKW]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 467.06it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 467.49it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.49it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 460.83it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1033.72it/s, est. speed input: 1237029.04 toks/s, output: 1034.20 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.27it/s, feature=WKW]

Datasets:  25%|██▌       | 1/4 [03:08<06:07, 122.48s/it, dataset=acsincome]

Seeds:  33%|███▎      | 1/3 [00:22<00:26, 13.12s/it, seed=123]

Conditions:   0%|          | 0/2 [00:22<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:22<00:10, 10.69s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:22<00:10, 10.69s/it, seed=456]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

acsincome Llama-3.1-8B-Instruct random 123 pi_behav done

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 476.63it/s]

Rendering prompts:  48%|████▊     | 97/200 [00:00<00:00, 479.22it/s]

Rendering prompts:  73%|███████▎  | 146/200 [00:00<00:00, 480.12it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 479.58it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 556.43it/s, est. speed input: 650205.08 toks/s, output: 556.63 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 473.39it/s]

Rendering prompts:  48%|████▊     | 97/200 [00:00<00:00, 478.12it/s]

Rendering prompts:  73%|███████▎  | 146/200 [00:00<00:00, 480.94it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 480.44it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 678.08it/s, est. speed input: 792309.42 toks/s, output: 678.29 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.17it/s, feature=AGEP]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.17it/s, feature=FER]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 470.77it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 475.26it/s]

Rendering prompts:  72%|███████▎  | 145/200 [00:00<00:00, 478.32it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 478.80it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 937.44it/s, est. speed input: 1094721.67 toks/s, output: 937.90 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.24it/s, feature=FER]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.24it/s, feature=HINS1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 474.47it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 473.47it/s]

Rendering prompts:  72%|███████▏  | 144/200 [00:00<00:00, 476.02it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 477.61it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 918.42it/s, est. speed input: 1073272.93 toks/s, output: 918.81 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.26it/s, feature=HINS1]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.26it/s, feature=HINS4]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 478.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 478.48it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1011.46it/s, est. speed input: 1182034.12 toks/s, output: 1011.92 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.28it/s, feature=HINS4]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.28it/s, feature=OCCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 473.69it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 475.34it/s]

Rendering prompts:  72%|███████▎  | 145/200 [00:00<00:00, 477.97it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 476.52it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 744.29it/s, est. speed input: 869765.66 toks/s, output: 744.56 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.25it/s, feature=OCCP]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.25it/s, feature=POBP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 453.56it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 472.37it/s]

Rendering prompts:  95%|█████████▌| 190/200 [00:00<00:00, 474.99it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 468.61it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 744.89it/s, est. speed input: 870375.82 toks/s, output: 745.15 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.23it/s, feature=POBP]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.23it/s, feature=RELP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 472.31it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 472.38it/s]

Rendering prompts:  96%|█████████▌| 192/200 [00:00<00:00, 476.09it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 475.30it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 872.94it/s, est. speed input: 1020016.36 toks/s, output: 873.30 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.23it/s, feature=RELP]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.23it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 479.57it/s]

Rendering prompts:  48%|████▊     | 97/200 [00:00<00:00, 481.64it/s]

Rendering prompts:  73%|███████▎  | 146/200 [00:00<00:00, 482.83it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 483.61it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 881.05it/s, est. speed input: 1029610.10 toks/s, output: 881.40 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.24it/s, feature=SCHL]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.24it/s, feature=WKHP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 476.42it/s]

Rendering prompts:  48%|████▊     | 97/200 [00:00<00:00, 481.03it/s]

Rendering prompts:  73%|███████▎  | 146/200 [00:00<00:00, 470.30it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 475.57it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1016.90it/s, est. speed input: 1188482.88 toks/s, output: 1017.44 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.27it/s, feature=WKHP]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.27it/s, feature=WKW]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 479.18it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 477.63it/s]

Rendering prompts:  72%|███████▎  | 145/200 [00:00<00:00, 481.71it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 482.81it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1134.93it/s, est. speed input: 1326414.60 toks/s, output: 1135.52 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.30it/s, feature=WKW]

Datasets:  25%|██▌       | 1/4 [03:17<06:07, 122.48s/it, dataset=acsincome]

Seeds:  67%|██████▋   | 2/3 [00:30<00:10, 10.69s/it, seed=456]

Conditions:   0%|          | 0/2 [00:30<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:30<00:00,  9.85s/it, seed=456]

Conditions:  50%|█████     | 1/2 [00:30<00:30, 30.96s/it, condition=random, model=Llama-3.1-8B-Instruct]

Conditions:  50%|█████     | 1/2 [00:30<00:30, 30.96s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

acsincome Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 463.81it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 466.98it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 463.08it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.20it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 597.89it/s, est. speed input: 722603.31 toks/s, output: 598.13 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 468.47it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 468.41it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 466.02it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 658.18it/s, est. speed input: 795390.17 toks/s, output: 658.38 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=AGEP]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=FER]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 464.47it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.63it/s]

Rendering prompts:  94%|█████████▍| 188/200 [00:00<00:00, 467.99it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.47it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 883.89it/s, est. speed input: 1067630.65 toks/s, output: 884.24 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.21it/s, feature=FER]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.21it/s, feature=HINS1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 459.14it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 464.14it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 465.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 466.49it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 830.38it/s, est. speed input: 1003583.22 toks/s, output: 830.71 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=HINS1]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=HINS4]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 457.67it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 461.75it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 462.50it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 463.64it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 963.30it/s, est. speed input: 1164291.76 toks/s, output: 963.73 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.24it/s, feature=HINS4]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.24it/s, feature=OCCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  46%|████▌     | 92/200 [00:00<00:00, 458.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 464.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 712.81it/s, est. speed input: 861470.99 toks/s, output: 713.04 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=OCCP]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=POBP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 459.36it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 460.33it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 456.58it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 460.01it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 692.14it/s, est. speed input: 836431.24 toks/s, output: 692.37 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.19it/s, feature=POBP]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.19it/s, feature=RELP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 456.43it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 460.25it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 461.73it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 459.88it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 859.74it/s, est. speed input: 1039123.25 toks/s, output: 860.11 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.21it/s, feature=RELP]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.21it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  22%|██▎       | 45/200 [00:00<00:00, 448.15it/s]

Rendering prompts:  46%|████▌     | 91/200 [00:00<00:00, 454.04it/s]

Rendering prompts:  69%|██████▉   | 138/200 [00:00<00:00, 457.31it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 453.08it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 822.89it/s, est. speed input: 994729.12 toks/s, output: 823.22 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.21it/s, feature=SCHL]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.21it/s, feature=WKHP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 455.29it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 460.80it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 462.57it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 463.21it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 960.53it/s, est. speed input: 1160954.62 toks/s, output: 960.97 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.23it/s, feature=WKHP]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.23it/s, feature=WKW]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  46%|████▌     | 92/200 [00:00<00:00, 458.24it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 459.91it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1068.22it/s, est. speed input: 1291177.43 toks/s, output: 1068.75 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.25it/s, feature=WKW]

Datasets:  25%|██▌       | 1/4 [03:26<06:07, 122.48s/it, dataset=acsincome]

Seeds:   0%|          | 0/3 [00:09<?, ?it/s, seed=42]

Conditions:  50%|█████     | 1/2 [00:40<00:30, 30.96s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.13s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.13s/it, seed=123]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

acsincome Llama-3.1-8B-Instruct label_diversity 42 pi_behav done

Rendering prompts:  22%|██▏       | 43/200 [00:00<00:00, 424.32it/s]

Rendering prompts:  45%|████▌     | 90/200 [00:00<00:00, 450.46it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 445.26it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 452.46it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 587.93it/s, est. speed input: 695824.71 toks/s, output: 588.14 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 467.63it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 467.88it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 462.86it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.07it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 635.00it/s, est. speed input: 751484.93 toks/s, output: 635.18 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.13it/s, feature=AGEP]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.13it/s, feature=FER]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 461.16it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.78it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 465.92it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 899.33it/s, est. speed input: 1064341.47 toks/s, output: 899.71 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.20it/s, feature=FER]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.20it/s, feature=HINS1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 468.16it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 468.18it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 469.17it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.05it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 877.43it/s, est. speed input: 1038524.02 toks/s, output: 877.79 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=HINS1]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=HINS4]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 464.48it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 469.12it/s]

Rendering prompts:  72%|███████▏  | 143/200 [00:00<00:00, 469.89it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 471.09it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 977.28it/s, est. speed input: 1156744.93 toks/s, output: 977.71 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=HINS4]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=OCCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 473.20it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 474.05it/s]

Rendering prompts:  72%|███████▏  | 144/200 [00:00<00:00, 473.20it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 472.14it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 696.07it/s, est. speed input: 823814.87 toks/s, output: 696.30 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=OCCP]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=POBP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  21%|██        | 42/200 [00:00<00:00, 419.49it/s]

Rendering prompts:  44%|████▎     | 87/200 [00:00<00:00, 434.89it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 451.62it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 453.18it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 727.18it/s, est. speed input: 860633.89 toks/s, output: 727.43 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.20it/s, feature=POBP]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.20it/s, feature=RELP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 462.94it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 462.48it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 464.64it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 466.38it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 819.82it/s, est. speed input: 970327.55 toks/s, output: 820.14 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.21it/s, feature=RELP]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.21it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 462.97it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 469.17it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 467.95it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 469.61it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 870.14it/s, est. speed input: 1029797.90 toks/s, output: 870.50 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.22it/s, feature=SCHL]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.22it/s, feature=WKHP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 469.42it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 470.11it/s]

Rendering prompts:  95%|█████████▌| 190/200 [00:00<00:00, 466.90it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 462.33it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1019.85it/s, est. speed input: 1207178.28 toks/s, output: 1020.34 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.24it/s, feature=WKHP]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.24it/s, feature=WKW]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 459.56it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 470.01it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 473.41it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 472.84it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1114.54it/s, est. speed input: 1319302.34 toks/s, output: 1115.11 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.27it/s, feature=WKW]

Datasets:  25%|██▌       | 1/4 [03:35<06:07, 122.48s/it, dataset=acsincome]

Seeds:  33%|███▎      | 1/3 [00:18<00:18,  9.13s/it, seed=123]

Conditions:  50%|█████     | 1/2 [00:49<00:30, 30.96s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:18<00:09,  9.10s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:09,  9.10s/it, seed=456]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

acsincome Llama-3.1-8B-Instruct label_diversity 123 pi_behav done

Rendering prompts:  24%|██▍       | 48/200 [00:00<00:00, 471.49it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 472.52it/s]

Rendering prompts:  72%|███████▏  | 144/200 [00:00<00:00, 474.62it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 474.74it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 587.80it/s, est. speed input: 700364.36 toks/s, output: 588.00 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 452.39it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 462.51it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 467.53it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.90it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 647.20it/s, est. speed input: 771105.73 toks/s, output: 647.39 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=AGEP]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.14it/s, feature=FER]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 460.67it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 460.32it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 465.19it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 466.61it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 872.77it/s, est. speed input: 1039184.37 toks/s, output: 873.12 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.20it/s, feature=FER]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.20it/s, feature=HINS1]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 465.27it/s]

Rendering prompts:  48%|████▊     | 95/200 [00:00<00:00, 469.26it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 466.68it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 469.07it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 880.53it/s, est. speed input: 1049232.27 toks/s, output: 880.89 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=HINS1]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=HINS4]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 467.86it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 467.47it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 465.12it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.88it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 947.72it/s, est. speed input: 1129328.50 toks/s, output: 948.13 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=HINS4]

Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=OCCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 453.43it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 460.95it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 463.89it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 462.72it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 717.35it/s, est. speed input: 854772.27 toks/s, output: 717.59 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=OCCP]

Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.22it/s, feature=POBP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 463.82it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 465.63it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 466.15it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 466.81it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 722.45it/s, est. speed input: 860753.26 toks/s, output: 722.68 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.19it/s, feature=POBP]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.19it/s, feature=RELP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 460.76it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 463.84it/s]

Rendering prompts:  70%|███████   | 141/200 [00:00<00:00, 461.26it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 460.90it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 842.75it/s, est. speed input: 1004145.40 toks/s, output: 843.11 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.20it/s, feature=RELP]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.20it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 459.02it/s]

Rendering prompts:  46%|████▋     | 93/200 [00:00<00:00, 462.67it/s]

Rendering prompts:  70%|███████   | 140/200 [00:00<00:00, 462.98it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 464.52it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 792.65it/s, est. speed input: 944520.58 toks/s, output: 792.95 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.21it/s, feature=SCHL]

Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.21it/s, feature=WKHP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▎       | 47/200 [00:00<00:00, 464.99it/s]

Rendering prompts:  47%|████▋     | 94/200 [00:00<00:00, 462.91it/s]

Rendering prompts:  71%|███████   | 142/200 [00:00<00:00, 466.39it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 467.18it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 976.37it/s, est. speed input: 1163480.56 toks/s, output: 976.80 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.23it/s, feature=WKHP]

Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.23it/s, feature=WKW]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  18%|█▊        | 37/200 [00:00<00:00, 366.94it/s]

Rendering prompts:  42%|████▎     | 85/200 [00:00<00:00, 429.80it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 447.06it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 447.59it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1092.22it/s, est. speed input: 1301608.20 toks/s, output: 1092.76 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.25it/s, feature=WKW]

Datasets:  25%|██▌       | 1/4 [03:44<06:07, 122.48s/it, dataset=acsincome]

Seeds:  67%|██████▋   | 2/3 [00:27<00:09,  9.10s/it, seed=456]

Conditions:  50%|█████     | 1/2 [00:58<00:30, 30.96s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:27<00:00,  9.11s/it, seed=456]

Conditions: 100%|██████████| 2/2 [00:58<00:00, 28.82s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

[rank0]:[W912 09:53:07.017725766 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

acsincome Llama-3.1-8B-Instruct label_diversity 456 pi_behav done

Datasets:  50%|█████     | 2/4 [03:45<03:42, 111.23s/it, dataset=acsincome]

Datasets:  50%|█████     | 2/4 [03:45<03:42, 111.23s/it, dataset=acspubcov]

INFO 09-12 09:53:16 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:53:16 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:53:17 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:53:17 [model.py:2021] Using max model len 8192
INFO 09-12 09:53:17 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:53:17 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:53:19 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:53:20 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_c51f72a46be246e6bd9fc570907c8880 backend=nccl
INFO 09-12 09:53:20 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:53:20 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:53:21 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:53:21 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:53:21 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:53:22 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.46 GiB.
INFO 09-12 09:53:22 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.25it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.19it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.18it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.64it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.44it/s]

INFO 09-12 09:53:24 [default_loader.py:430] Loading weights took 2.79 seconds

INFO 09-12 09:53:25 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.118765 seconds
INFO 09-12 09:53:25 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:53:25 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:53:26 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:53:26 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:53:26 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:53:26 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:03<02:14,  1.66s/it]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:04<00:31,  2.48it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:04<00:15,  4.80it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:05<00:09,  7.05it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:05<00:07,  9.24it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:05<00:05, 10.97it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:05<00:04, 12.38it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:06<00:03, 13.60it/s]

Capturing CUDA graphs (PIECEWISE):  39%|███▊      | 32/83 [00:06<00:03, 13.13it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:06<00:04, 11.25it/s]

Capturing CUDA graphs (PIECEWISE):  43%|████▎     | 36/83 [00:06<00:04, 10.35it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:07<00:04,  9.40it/s]

Capturing CUDA graphs (PIECEWISE):  49%|████▉     | 41/83 [00:07<00:05,  8.02it/s]

Capturing CUDA graphs (PIECEWISE):  54%|█████▍    | 45/83 [00:07<00:03, 11.55it/s]

Capturing CUDA graphs (PIECEWISE):  59%|█████▉    | 49/83 [00:08<00:02, 14.16it/s]

Capturing CUDA graphs (PIECEWISE):  64%|██████▍   | 53/83 [00:08<00:01, 16.10it/s]

Capturing CUDA graphs (PIECEWISE):  69%|██████▊   | 57/83 [00:08<00:01, 16.54it/s]

Capturing CUDA graphs (PIECEWISE):  73%|███████▎  | 61/83 [00:08<00:01, 16.73it/s]

Capturing CUDA graphs (PIECEWISE):  78%|███████▊  | 65/83 [00:08<00:01, 16.95it/s]

Capturing CUDA graphs (PIECEWISE):  83%|████████▎ | 69/83 [00:09<00:00, 17.62it/s]

Capturing CUDA graphs (PIECEWISE):  88%|████████▊ | 73/83 [00:09<00:00, 17.46it/s]

Capturing CUDA graphs (PIECEWISE):  93%|█████████▎| 77/83 [00:09<00:00, 16.99it/s]

Capturing CUDA graphs (PIECEWISE):  98%|█████████▊| 81/83 [00:09<00:00, 17.04it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.33it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.82it/s]

INFO 09-12 09:53:37 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:53:37 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:53:37 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:53:37 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:53:37 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:53:37 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:53:38 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:53:38 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:53:38 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:53:38 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:53:38 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:53:38 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:53:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:53:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:53:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:53:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:53:38 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:53:38 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:53:38 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:53:38 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:53:38 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:53:38 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:53:38 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.60it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.11it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.43it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.00it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.82it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.50it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:03, 14.32it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.33it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 16.32it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 16.85it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 17.97it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:01, 18.82it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 19.34it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 19.44it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 19.40it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:03<00:01, 19.20it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 18.80it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 19.10it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 19.23it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 18.99it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.27it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.95it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.96it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.49it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.78it/s]

Capturing CUDA graphs (FULL):  39%|███▊      | 32/83 [00:01<00:01, 29.01it/s]

Capturing CUDA graphs (FULL):  48%|████▊     | 40/83 [00:01<00:01, 32.56it/s]

Capturing CUDA graphs (FULL):  59%|█████▉    | 49/83 [00:01<00:00, 36.26it/s]

Capturing CUDA graphs (FULL):  71%|███████   | 59/83 [00:01<00:00, 38.54it/s]

Capturing CUDA graphs (FULL):  82%|████████▏ | 68/83 [00:02<00:00, 39.01it/s]

Capturing CUDA graphs (FULL):  93%|█████████▎| 77/83 [00:02<00:00, 40.13it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:06<00:00, 13.81it/s]

INFO 09-12 09:53:49 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:53:49 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:53:49 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272455578` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766675456` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:53:50 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:53:50 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:53:50 [core.py:361] init engine (profile, create kv cache, warmup model) took 25.57 s (compilation: 0.16 s)

INFO 09-12 09:53:52 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]

Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 664.46it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.42it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:53:52 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 09:53:56 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CachedTokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Processed prompts: 100%|██████████| 200/200 [00:04<00:00, 47.37it/s, est. speed input: 38376.62 toks/s, output: 47.37 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=ACS_YEAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  68%|██████▊   | 135/200 [00:00<00:00, 674.16it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.14it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 855.36it/s, est. speed input: 693197.58 toks/s, output: 855.70 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.48it/s, feature=ACS_YEAR]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.48it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 669.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 672.20it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 795.06it/s, est. speed input: 644316.97 toks/s, output: 795.36 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.45it/s, feature=AGEP]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.45it/s, feature=CIT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 662.77it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 667.28it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1058.97it/s, est. speed input: 858548.77 toks/s, output: 1059.50 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.51it/s, feature=CIT]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.51it/s, feature=DIVISION]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▏      | 64/200 [00:00<00:00, 633.07it/s]

Rendering prompts:  65%|██████▌   | 130/200 [00:00<00:00, 648.28it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 654.89it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 894.63it/s, est. speed input: 724915.30 toks/s, output: 894.98 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.50it/s, feature=DIVISION]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.50it/s, feature=ESR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.59it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.00it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1056.58it/s, est. speed input: 856705.93 toks/s, output: 1057.09 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.53it/s, feature=ESR]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.53it/s, feature=MAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 664.70it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 669.75it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1057.61it/s, est. speed input: 857364.64 toks/s, output: 1058.13 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.55it/s, feature=MAR]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.55it/s, feature=PINCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  33%|███▎      | 66/200 [00:00<00:00, 655.14it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 675.81it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1097.64it/s, est. speed input: 889607.50 toks/s, output: 1098.22 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=PINCP]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=RAC1P]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.26it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 668.78it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1229.49it/s, est. speed input: 996593.70 toks/s, output: 1230.21 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.59it/s, feature=RAC1P]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.59it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.17it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 669.41it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1234.26it/s, est. speed input: 1000237.90 toks/s, output: 1235.02 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.61it/s, feature=SCHL]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.61it/s, feature=ST]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 641.40it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 653.53it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 658.75it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1346.89it/s, est. speed input: 1091879.85 toks/s, output: 1347.84 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.63it/s, feature=ST]

Datasets:  50%|█████     | 2/4 [04:40<03:42, 111.23s/it, dataset=acspubcov]

Conditions:   0%|          | 0/2 [00:11<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:11<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:11<00:22, 11.04s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:11<00:22, 11.04s/it, seed=123]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

acspubcov Llama-3.1-8B-Instruct random 42 pi_behav done

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 674.08it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 682.48it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 725.83it/s, est. speed input: 583110.59 toks/s, output: 726.08 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=ACS_YEAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  68%|██████▊   | 137/200 [00:00<00:00, 685.12it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 685.54it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 847.08it/s, est. speed input: 680580.22 toks/s, output: 847.45 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.50it/s, feature=ACS_YEAR]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.50it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 664.90it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 666.43it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 791.59it/s, est. speed input: 635984.52 toks/s, output: 791.92 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.47it/s, feature=AGEP]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.47it/s, feature=CIT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 667.94it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 669.10it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1130.48it/s, est. speed input: 908483.00 toks/s, output: 1131.07 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.53it/s, feature=CIT]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.53it/s, feature=DIVISION]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 669.92it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.96it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 844.49it/s, est. speed input: 678507.00 toks/s, output: 844.83 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.51it/s, feature=DIVISION]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.51it/s, feature=ESR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.73it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 667.82it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1061.52it/s, est. speed input: 853351.42 toks/s, output: 1062.11 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=ESR]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=MAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 648.62it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 667.87it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1068.31it/s, est. speed input: 858345.23 toks/s, output: 1068.85 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.56it/s, feature=MAR]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.56it/s, feature=PINCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.32it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1079.03it/s, est. speed input: 867036.91 toks/s, output: 1079.56 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=PINCP]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=RAC1P]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 665.45it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 672.98it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1241.12it/s, est. speed input: 997399.18 toks/s, output: 1241.94 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.61it/s, feature=RAC1P]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.61it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 669.04it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 672.01it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1222.46it/s, est. speed input: 982145.44 toks/s, output: 1223.17 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.62it/s, feature=SCHL]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.62it/s, feature=ST]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 672.16it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 673.85it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1304.81it/s, est. speed input: 1048513.98 toks/s, output: 1305.59 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.65it/s, feature=ST]

Datasets:  50%|█████     | 2/4 [04:47<03:42, 111.23s/it, dataset=acspubcov]

Conditions:   0%|          | 0/2 [00:18<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:18<00:22, 11.04s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:08,  8.68s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:08,  8.68s/it, seed=456]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

acspubcov Llama-3.1-8B-Instruct random 123 pi_behav done

Rendering prompts:  67%|██████▋   | 134/200 [00:00<00:00, 671.28it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 670.54it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 681.14it/s, est. speed input: 567619.79 toks/s, output: 681.34 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=ACS_YEAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  33%|███▎      | 66/200 [00:00<00:00, 655.81it/s]

Rendering prompts:  66%|██████▋   | 133/200 [00:00<00:00, 659.32it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 657.32it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 835.25it/s, est. speed input: 696101.78 toks/s, output: 835.56 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.47it/s, feature=ACS_YEAR]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.47it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 645.46it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 657.92it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 659.62it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 748.05it/s, est. speed input: 623402.69 toks/s, output: 748.30 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.43it/s, feature=AGEP]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.43it/s, feature=CIT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 667.46it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 672.71it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1133.72it/s, est. speed input: 945194.71 toks/s, output: 1134.40 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.52it/s, feature=CIT]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.52it/s, feature=DIVISION]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 661.26it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 668.64it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 826.14it/s, est. speed input: 688569.65 toks/s, output: 826.46 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.50it/s, feature=DIVISION]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.50it/s, feature=ESR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 663.42it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 669.45it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1034.77it/s, est. speed input: 862923.11 toks/s, output: 1035.27 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.53it/s, feature=ESR]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.53it/s, feature=MAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 647.04it/s]

Rendering prompts:  66%|██████▌   | 131/200 [00:00<00:00, 652.96it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 656.95it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1027.84it/s, est. speed input: 856867.59 toks/s, output: 1028.41 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.54it/s, feature=MAR]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.54it/s, feature=PINCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 665.02it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 664.97it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1059.01it/s, est. speed input: 882671.75 toks/s, output: 1059.54 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.56it/s, feature=PINCP]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.56it/s, feature=RAC1P]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 643.71it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 657.82it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 657.64it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1251.12it/s, est. speed input: 1042911.27 toks/s, output: 1251.84 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.58it/s, feature=RAC1P]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.58it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  33%|███▎      | 66/200 [00:00<00:00, 655.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 667.16it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1239.80it/s, est. speed input: 1033205.48 toks/s, output: 1240.53 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.56it/s, feature=SCHL]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.56it/s, feature=ST]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  32%|███▎      | 65/200 [00:00<00:00, 649.74it/s]

Rendering prompts:  66%|██████▌   | 132/200 [00:00<00:00, 660.32it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 662.74it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1326.51it/s, est. speed input: 1105823.43 toks/s, output: 1327.36 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.60it/s, feature=ST]

Datasets:  50%|█████     | 2/4 [04:55<03:42, 111.23s/it, dataset=acspubcov]

Conditions:   0%|          | 0/2 [00:25<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:25<00:08,  8.68s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:25<00:00,  8.00s/it, seed=456]

Conditions:  50%|█████     | 1/2 [00:25<00:25, 25.27s/it, condition=random, model=Llama-3.1-8B-Instruct]

Conditions:  50%|█████     | 1/2 [00:25<00:25, 25.27s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

acspubcov Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:  70%|██████▉   | 139/200 [00:00<00:00, 695.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 697.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 684.33it/s, est. speed input: 543596.48 toks/s, output: 684.55 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=ACS_YEAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  35%|███▌      | 70/200 [00:00<00:00, 690.63it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 686.09it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 839.26it/s, est. speed input: 666722.63 toks/s, output: 839.60 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.49it/s, feature=ACS_YEAR]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.49it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 678.05it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 676.78it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 802.40it/s, est. speed input: 637441.54 toks/s, output: 802.73 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.47it/s, feature=AGEP]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.47it/s, feature=CIT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 672.36it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 674.27it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1071.07it/s, est. speed input: 851224.30 toks/s, output: 1071.62 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.53it/s, feature=CIT]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.53it/s, feature=DIVISION]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 679.83it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.32it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 856.53it/s, est. speed input: 680337.70 toks/s, output: 856.87 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.51it/s, feature=DIVISION]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.51it/s, feature=ESR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 679.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 674.16it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1041.42it/s, est. speed input: 827746.31 toks/s, output: 1041.93 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=ESR]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=MAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 69/200 [00:00<00:00, 680.66it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 692.01it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 965.95it/s, est. speed input: 767570.71 toks/s, output: 966.39 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.54it/s, feature=MAR]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.54it/s, feature=PINCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 672.20it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 680.65it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1110.65it/s, est. speed input: 882354.86 toks/s, output: 1111.22 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=PINCP]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=RAC1P]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 675.52it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 690.96it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1216.70it/s, est. speed input: 966768.14 toks/s, output: 1217.44 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.60it/s, feature=RAC1P]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.60it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 677.29it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 676.92it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1244.18it/s, est. speed input: 988324.53 toks/s, output: 1244.90 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.63it/s, feature=SCHL]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.63it/s, feature=ST]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 677.44it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 678.70it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1374.73it/s, est. speed input: 1092550.80 toks/s, output: 1375.84 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.66it/s, feature=ST]

Datasets:  50%|█████     | 2/4 [05:02<03:42, 111.23s/it, dataset=acspubcov]

Conditions:  50%|█████     | 1/2 [00:32<00:25, 25.27s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.24s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.24s/it, seed=123]

acspubcov Llama-3.1-8B-Instruct rule_diversity 42 pi_behav done

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 664.29it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 667.73it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 719.24it/s, est. speed input: 592906.28 toks/s, output: 719.47 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=ACS_YEAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.81it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 664.24it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 817.44it/s, est. speed input: 673901.09 toks/s, output: 817.75 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.46it/s, feature=ACS_YEAR]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.46it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 672.75it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 670.06it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 802.92it/s, est. speed input: 661930.47 toks/s, output: 803.22 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.46it/s, feature=AGEP]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.46it/s, feature=CIT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 666.23it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 666.87it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1115.51it/s, est. speed input: 919904.21 toks/s, output: 1116.11 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.52it/s, feature=CIT]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.52it/s, feature=DIVISION]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 667.01it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 668.32it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 903.07it/s, est. speed input: 744569.08 toks/s, output: 903.46 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.52it/s, feature=DIVISION]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.52it/s, feature=ESR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 670.39it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 668.90it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1030.85it/s, est. speed input: 850285.12 toks/s, output: 1031.33 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=ESR]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=MAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 668.93it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 666.66it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1096.86it/s, est. speed input: 904397.93 toks/s, output: 1097.49 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.56it/s, feature=MAR]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.56it/s, feature=PINCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 671.81it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 669.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1067.09it/s, est. speed input: 879859.04 toks/s, output: 1067.61 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=PINCP]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=RAC1P]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 675.74it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 675.71it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1227.83it/s, est. speed input: 1012431.76 toks/s, output: 1228.53 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.60it/s, feature=RAC1P]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.60it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 673.85it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 671.40it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1222.63it/s, est. speed input: 1007941.44 toks/s, output: 1223.31 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.62it/s, feature=SCHL]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.62it/s, feature=ST]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 664.55it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 664.64it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1373.39it/s, est. speed input: 1132525.02 toks/s, output: 1374.26 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.65it/s, feature=ST]

Datasets:  50%|█████     | 2/4 [05:09<03:42, 111.23s/it, dataset=acspubcov]

Conditions:  50%|█████     | 1/2 [00:39<00:25, 25.27s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:14<00:14,  7.24s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.24s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.24s/it, seed=456]

acspubcov Llama-3.1-8B-Instruct rule_diversity 123 pi_behav done

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 669.14it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 670.81it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 733.39it/s, est. speed input: 589174.67 toks/s, output: 733.63 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=ACS_YEAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 672.67it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 674.49it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 851.72it/s, est. speed input: 684273.79 toks/s, output: 852.05 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.49it/s, feature=ACS_YEAR]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.49it/s, feature=AGEP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 661.94it/s]

Rendering prompts:  67%|██████▋   | 134/200 [00:00<00:00, 664.24it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 648.68it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 773.07it/s, est. speed input: 621079.33 toks/s, output: 773.36 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.45it/s, feature=AGEP]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.45it/s, feature=CIT]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 668.53it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 669.11it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1099.30it/s, est. speed input: 883488.70 toks/s, output: 1099.94 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.52it/s, feature=CIT]

Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.52it/s, feature=DIVISION]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 677.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 679.34it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 824.74it/s, est. speed input: 662645.44 toks/s, output: 825.05 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.50it/s, feature=DIVISION]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.50it/s, feature=ESR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 673.52it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 677.50it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1069.86it/s, est. speed input: 860071.85 toks/s, output: 1070.38 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=ESR]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.54it/s, feature=MAR]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▎      | 67/200 [00:00<00:00, 669.09it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 677.20it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1078.85it/s, est. speed input: 866961.10 toks/s, output: 1079.39 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.56it/s, feature=MAR]

Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.56it/s, feature=PINCP]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 677.15it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 677.37it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1090.46it/s, est. speed input: 876151.09 toks/s, output: 1091.01 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=PINCP]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=RAC1P]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 678.29it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 667.07it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1262.77it/s, est. speed input: 1014742.51 toks/s, output: 1263.52 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.61it/s, feature=RAC1P]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.61it/s, feature=SCHL]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  34%|███▍      | 68/200 [00:00<00:00, 673.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 683.69it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1239.84it/s, est. speed input: 996018.18 toks/s, output: 1240.56 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.63it/s, feature=SCHL]

Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.63it/s, feature=ST]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  68%|██████▊   | 136/200 [00:00<00:00, 678.30it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 675.62it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1374.06it/s, est. speed input: 1104191.17 toks/s, output: 1374.91 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.66it/s, feature=ST]

Datasets:  50%|█████     | 2/4 [05:16<03:42, 111.23s/it, dataset=acspubcov]

Conditions:  50%|█████     | 1/2 [00:46<00:25, 25.27s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:21<00:07,  7.24s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:21<00:00,  7.23s/it, seed=456]

Conditions: 100%|██████████| 2/2 [00:46<00:00, 23.18s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

[rank0]:[W912 09:54:39.046191796 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

acspubcov Llama-3.1-8B-Instruct rule_diversity 456 pi_behav done

Datasets:  75%|███████▌  | 3/4 [05:17<01:42, 102.44s/it, dataset=acspubcov]

Datasets:  75%|███████▌  | 3/4 [05:17<01:42, 102.44s/it, dataset=anes]

INFO 09-12 09:54:48 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 09:54:48 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 09:54:49 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 09:54:49 [model.py:2021] Using max model len 8192
INFO 09-12 09:54:49 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 09:54:49 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 09:54:51 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 09:54:52 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_9f3ec3f672374ccfbf5446d3344942c1 backend=nccl
INFO 09-12 09:54:52 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 09:54:52 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 09:54:53 [model_runner.py:382] Loading model from scratch...

INFO 09-12 09:54:53 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 09:54:53 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 09:54:53 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 910.57 GiB.
INFO 09-12 09:54:53 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.25it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.18it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.14it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.59it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.41it/s]

INFO 09-12 09:54:56 [default_loader.py:430] Loading weights took 2.86 seconds

INFO 09-12 09:54:57 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.213692 seconds
INFO 09-12 09:54:57 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 09:54:57 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 09:54:58 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 09:54:58 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 09:54:58 [monitor.py:53] torch.compile took 0.16 s in total
INFO 09-12 09:54:58 [monitor.py:81] Initial profiling/warmup run took 0.15 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:04<01:25,  1.07s/it]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:04<00:28,  2.71it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:14,  4.95it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:05<00:09,  7.33it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:05<00:06,  9.66it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.22it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 12.81it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:06<00:03, 14.10it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:06<00:03, 15.01it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 15.93it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 16.01it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:07<00:02, 17.04it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:07<00:01, 17.66it/s]

Capturing CUDA graphs (PIECEWISE):  66%|██████▋   | 55/83 [00:07<00:01, 17.13it/s]

Capturing CUDA graphs (PIECEWISE):  71%|███████   | 59/83 [00:07<00:01, 17.06it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:08<00:01, 17.30it/s]

Capturing CUDA graphs (PIECEWISE):  81%|████████  | 67/83 [00:08<00:00, 17.42it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:08<00:00, 17.35it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:08<00:00, 16.97it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:09<00:00, 16.79it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:09<00:00,  8.90it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/2 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 19.90it/s]

INFO 09-12 09:55:08 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.56 GiB

INFO 09-12 09:55:09 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 09:55:09 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8957 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9043. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 09:55:09 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,360 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 09:55:09 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 09:55:09 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 09:55:09 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 09:55:09 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 09:55:09 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 09:55:09 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 09:55:09 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 09:55:09 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 09:55:09 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 09:55:09 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 09:55:09 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 09:55:09 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 09:55:09 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 09:55:09 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 09:55:09 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 09:55:09 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 09:55:09 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 09:55:09 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 09:55:09 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.61it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:07, 10.98it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 11.55it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 11.91it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:05, 12.59it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 13.45it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:02<00:03, 14.34it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 15.25it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:03, 15.78it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 16.85it/s]

Capturing CUDA graphs (PIECEWISE):  51%|█████     | 42/83 [00:02<00:02, 17.78it/s]

Capturing CUDA graphs (PIECEWISE):  55%|█████▌    | 46/83 [00:03<00:01, 18.60it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 19.04it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:01, 18.85it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:03<00:01, 19.08it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:04<00:01, 18.30it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:00, 18.75it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 18.98it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 18.74it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:04<00:00, 19.02it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 16.07it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 20.92it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 21.89it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 23.56it/s]

Capturing CUDA graphs (FULL):  29%|██▉       | 24/83 [00:01<00:02, 25.66it/s]

Capturing CUDA graphs (FULL):  37%|███▋      | 31/83 [00:01<00:01, 28.52it/s]

Capturing CUDA graphs (FULL):  47%|████▋     | 39/83 [00:01<00:01, 31.11it/s]

Capturing CUDA graphs (FULL):  57%|█████▋    | 47/83 [00:01<00:01, 34.97it/s]

Capturing CUDA graphs (FULL):  67%|██████▋   | 56/83 [00:01<00:00, 37.67it/s]

Capturing CUDA graphs (FULL):  80%|███████▉  | 66/83 [00:02<00:00, 39.42it/s]

Capturing CUDA graphs (FULL):  92%|█████████▏| 76/83 [00:02<00:00, 40.31it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 13.85it/s]

INFO 09-12 09:55:20 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.29 GiB
INFO 09-12 09:55:20 [gpu_worker.py:797] CUDA graph pool memory: 0.29 GiB (actual), 0.77 GiB (estimated), difference: 0.47 GiB (159.6%).
INFO 09-12 09:55:20 [gpu_worker.py:860] Free memory on device (177.74/178.35 GiB) on startup. Desired GPU memory utilization is (0.9, 160.52 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.45 GiB for peak activation, and 0.29 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152272390042` (141.81 GiB) to fit into requested memory, or `--kv-cache-memory=170766609920` (159.04 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 09:55:21 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 09:55:22 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 09:55:22 [core.py:361] init engine (profile, create kv cache, warmup model) took 24.92 s (compilation: 0.16 s)

INFO 09-12 09:55:23 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]

Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  23%|██▎       | 46/200 [00:00<00:00, 459.76it/s]

Rendering prompts:  48%|████▊     | 96/200 [00:00<00:00, 478.98it/s]

Rendering prompts:  74%|███████▍  | 148/200 [00:00<00:00, 494.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 492.48it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 09:55:25 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 09:55:28 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CachedTokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Processed prompts: 100%|██████████| 200/200 [00:04<00:00, 47.52it/s, est. speed input: 52757.71 toks/s, output: 47.52 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=VCF0310]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 504.08it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 498.45it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 995.92it/s, est. speed input: 1106140.41 toks/s, output: 996.40 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.40it/s, feature=VCF0310]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.40it/s, feature=VCF0606]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 498.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 500.32it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1045.29it/s, est. speed input: 1160914.32 toks/s, output: 1045.78 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.41it/s, feature=VCF0606]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.41it/s, feature=VCF0717]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 497.48it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 501.04it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 501.62it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1055.02it/s, est. speed input: 1171769.23 toks/s, output: 1055.52 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.42it/s, feature=VCF0717]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.42it/s, feature=VCF0718]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 497.74it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 462.64it/s]

Rendering prompts:  74%|███████▎  | 147/200 [00:00<00:00, 400.59it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 401.58it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1121.43it/s, est. speed input: 1245661.95 toks/s, output: 1122.08 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.36it/s, feature=VCF0718]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.36it/s, feature=VCF0720]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 498.34it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 503.30it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 503.47it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1114.28it/s, est. speed input: 1237635.97 toks/s, output: 1114.85 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.39it/s, feature=VCF0720]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.39it/s, feature=VCF0721]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 499.37it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 498.33it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 501.20it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1122.84it/s, est. speed input: 1247159.44 toks/s, output: 1123.43 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.41it/s, feature=VCF0721]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.41it/s, feature=VCF0724]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 503.77it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 504.99it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 503.26it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1048.21it/s, est. speed input: 1164292.32 toks/s, output: 1048.76 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.42it/s, feature=VCF0724]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.42it/s, feature=VCF0725]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.19it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 506.51it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 503.86it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1107.83it/s, est. speed input: 1230495.15 toks/s, output: 1108.47 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF0725]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF9201]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 504.44it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 505.03it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 505.57it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1136.89it/s, est. speed input: 1262783.29 toks/s, output: 1137.50 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=VCF9201]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=VCF9202]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  24%|██▍       | 49/200 [00:00<00:00, 489.89it/s]

Rendering prompts:  50%|█████     | 100/200 [00:00<00:00, 499.72it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.27it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1126.42it/s, est. speed input: 1251114.38 toks/s, output: 1126.99 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.45it/s, feature=VCF9202]

Datasets:  75%|███████▌  | 3/4 [06:13<01:42, 102.44s/it, dataset=anes]

Seeds:   0%|          | 0/3 [00:11<?, ?it/s, seed=42]

Conditions:   0%|          | 0/2 [00:11<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:11<00:23, 11.77s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:11<00:23, 11.77s/it, seed=123]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

anes Llama-3.1-8B-Instruct random 42 pi_behav done

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 505.28it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 506.13it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.83it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 804.92it/s, est. speed input: 892269.85 toks/s, output: 805.20 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=VCF0310]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 492.69it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 500.73it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 503.31it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1039.55it/s, est. speed input: 1152528.08 toks/s, output: 1040.06 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.28it/s, feature=VCF0310]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.28it/s, feature=VCF0606]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 502.64it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 499.38it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.70it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1059.01it/s, est. speed input: 1174073.90 toks/s, output: 1059.53 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.29it/s, feature=VCF0606]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.29it/s, feature=VCF0717]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.44it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 512.18it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.83it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1122.85it/s, est. speed input: 1244901.47 toks/s, output: 1123.42 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.32it/s, feature=VCF0717]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.32it/s, feature=VCF0718]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 514.40it/s]

Rendering prompts:  78%|███████▊  | 156/200 [00:00<00:00, 516.97it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 514.20it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1089.99it/s, est. speed input: 1208446.85 toks/s, output: 1090.52 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.37it/s, feature=VCF0718]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.37it/s, feature=VCF0720]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 512.89it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 513.61it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 511.03it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1155.16it/s, est. speed input: 1280744.67 toks/s, output: 1155.76 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.41it/s, feature=VCF0720]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.41it/s, feature=VCF0721]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 510.85it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 512.71it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.94it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1121.41it/s, est. speed input: 1243299.04 toks/s, output: 1121.97 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.43it/s, feature=VCF0721]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.43it/s, feature=VCF0724]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 513.28it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 513.90it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 514.52it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1127.18it/s, est. speed input: 1249643.45 toks/s, output: 1127.75 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.45it/s, feature=VCF0724]

Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.45it/s, feature=VCF0725]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 508.76it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 512.23it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.98it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1111.82it/s, est. speed input: 1232657.24 toks/s, output: 1112.39 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.41it/s, feature=VCF0725]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.41it/s, feature=VCF9201]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 514.75it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 512.73it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 515.49it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1161.71it/s, est. speed input: 1288001.07 toks/s, output: 1162.31 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.39it/s, feature=VCF9201]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.39it/s, feature=VCF9202]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 517.42it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 517.29it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 516.95it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1186.97it/s, est. speed input: 1316017.15 toks/s, output: 1187.59 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.39it/s, feature=VCF9202]

Datasets:  75%|███████▌  | 3/4 [06:21<01:42, 102.44s/it, dataset=anes]

Seeds:  33%|███▎      | 1/3 [00:19<00:23, 11.77s/it, seed=123]

Conditions:   0%|          | 0/2 [00:19<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:19<00:09,  9.54s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:19<00:09,  9.54s/it, seed=456]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

anes Llama-3.1-8B-Instruct random 123 pi_behav done

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 515.43it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 516.11it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 514.19it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 821.51it/s, est. speed input: 909858.56 toks/s, output: 821.81 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=VCF0310]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 508.11it/s]

Rendering prompts:  76%|███████▋  | 153/200 [00:00<00:00, 508.90it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.17it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1065.90it/s, est. speed input: 1180645.60 toks/s, output: 1066.40 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.44it/s, feature=VCF0310]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.44it/s, feature=VCF0606]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 513.46it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 514.11it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 514.88it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1078.51it/s, est. speed input: 1194585.92 toks/s, output: 1079.02 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.46it/s, feature=VCF0606]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.46it/s, feature=VCF0717]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 511.16it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 512.02it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.74it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1102.27it/s, est. speed input: 1221194.41 toks/s, output: 1103.01 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.46it/s, feature=VCF0717]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.46it/s, feature=VCF0718]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.84it/s]

Rendering prompts:  52%|█████▏    | 103/200 [00:00<00:00, 511.59it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.80it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1121.73it/s, est. speed input: 1242573.84 toks/s, output: 1122.32 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.46it/s, feature=VCF0718]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.46it/s, feature=VCF0720]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 504.90it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 504.36it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 508.02it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1113.83it/s, est. speed input: 1233777.13 toks/s, output: 1114.38 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.42it/s, feature=VCF0720]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.42it/s, feature=VCF0721]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 515.59it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 516.41it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 514.21it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1144.27it/s, est. speed input: 1267503.44 toks/s, output: 1144.85 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.39it/s, feature=VCF0721]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.39it/s, feature=VCF0724]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 518.20it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 516.57it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1164.81it/s, est. speed input: 1290251.61 toks/s, output: 1165.41 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.41it/s, feature=VCF0724]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.41it/s, feature=VCF0725]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 514.51it/s]

Rendering prompts:  78%|███████▊  | 156/200 [00:00<00:00, 517.33it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 513.97it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1158.88it/s, est. speed input: 1283620.87 toks/s, output: 1159.47 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF0725]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF9201]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 513.01it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 513.15it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.87it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1168.71it/s, est. speed input: 1294584.32 toks/s, output: 1169.31 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.45it/s, feature=VCF9201]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.45it/s, feature=VCF9202]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 510.81it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 511.68it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 512.95it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1234.12it/s, est. speed input: 1367237.74 toks/s, output: 1234.93 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.47it/s, feature=VCF9202]

Datasets:  75%|███████▌  | 3/4 [06:29<01:42, 102.44s/it, dataset=anes]

Seeds:  67%|██████▋   | 2/3 [00:27<00:09,  9.54s/it, seed=456]

Conditions:   0%|          | 0/2 [00:27<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:27<00:00,  8.69s/it, seed=456]

Conditions:  50%|█████     | 1/2 [00:27<00:27, 27.44s/it, condition=random, model=Llama-3.1-8B-Instruct]

Conditions:  50%|█████     | 1/2 [00:27<00:27, 27.44s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

anes Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s, seed=42]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 495.32it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 500.85it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 793.17it/s, est. speed input: 891188.78 toks/s, output: 793.48 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=VCF0310]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 504.02it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 497.97it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.64it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1047.22it/s, est. speed input: 1176735.93 toks/s, output: 1047.72 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.32it/s, feature=VCF0310]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.32it/s, feature=VCF0606]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.70it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.86it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.73it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1088.99it/s, est. speed input: 1223719.35 toks/s, output: 1089.59 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.33it/s, feature=VCF0606]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.33it/s, feature=VCF0717]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.30it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 503.40it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 503.67it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1113.30it/s, est. speed input: 1251005.37 toks/s, output: 1113.85 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.38it/s, feature=VCF0717]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.38it/s, feature=VCF0718]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 503.77it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 501.95it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.00it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1151.64it/s, est. speed input: 1294107.10 toks/s, output: 1152.22 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.42it/s, feature=VCF0718]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.42it/s, feature=VCF0720]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 511.08it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 509.38it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 511.00it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1127.99it/s, est. speed input: 1267519.56 toks/s, output: 1128.55 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.44it/s, feature=VCF0720]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.44it/s, feature=VCF0721]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 505.42it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 503.68it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 505.77it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1118.79it/s, est. speed input: 1257199.79 toks/s, output: 1119.37 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.44it/s, feature=VCF0721]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.44it/s, feature=VCF0724]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 499.64it/s]

Rendering prompts:  50%|█████     | 101/200 [00:00<00:00, 500.43it/s]

Rendering prompts:  76%|███████▌  | 152/200 [00:00<00:00, 502.04it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 496.03it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1118.70it/s, est. speed input: 1257212.68 toks/s, output: 1119.35 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.45it/s, feature=VCF0724]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.45it/s, feature=VCF0725]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 500.58it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 503.15it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 505.60it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1140.29it/s, est. speed input: 1281311.94 toks/s, output: 1140.89 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.45it/s, feature=VCF0725]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.45it/s, feature=VCF9201]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.68it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 501.71it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.26it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1143.41it/s, est. speed input: 1284901.26 toks/s, output: 1144.02 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.45it/s, feature=VCF9201]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.45it/s, feature=VCF9202]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 505.08it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.46it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 501.84it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1216.05it/s, est. speed input: 1366529.18 toks/s, output: 1216.70 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.46it/s, feature=VCF9202]

Datasets:  75%|███████▌  | 3/4 [06:37<01:42, 102.44s/it, dataset=anes]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]

Conditions:  50%|█████     | 1/2 [00:35<00:27, 27.44s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.96s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.96s/it, seed=123]

anes Llama-3.1-8B-Instruct rule_diversity 42 pi_behav done

Rendering prompts:  25%|██▌       | 50/200 [00:00<00:00, 496.50it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 500.41it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 756.37it/s, est. speed input: 843734.28 toks/s, output: 756.62 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=VCF0310]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 510.13it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 507.21it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 507.16it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 954.89it/s, est. speed input: 1065292.93 toks/s, output: 955.30 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.40it/s, feature=VCF0310]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.40it/s, feature=VCF0606]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 512.00it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 509.73it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 509.41it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1013.79it/s, est. speed input: 1130986.27 toks/s, output: 1014.24 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.42it/s, feature=VCF0606]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.42it/s, feature=VCF0717]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.66it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 504.90it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.07it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1050.67it/s, est. speed input: 1172179.58 toks/s, output: 1051.15 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.43it/s, feature=VCF0717]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.43it/s, feature=VCF0718]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 503.29it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 497.92it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 501.39it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1063.26it/s, est. speed input: 1186225.09 toks/s, output: 1063.75 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.43it/s, feature=VCF0718]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.43it/s, feature=VCF0720]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 508.52it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 504.97it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1072.81it/s, est. speed input: 1196922.77 toks/s, output: 1073.34 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.43it/s, feature=VCF0720]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.43it/s, feature=VCF0721]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.96it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 506.02it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 503.67it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1074.55it/s, est. speed input: 1198853.29 toks/s, output: 1075.08 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.44it/s, feature=VCF0721]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.44it/s, feature=VCF0724]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 509.11it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 507.47it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.07it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1006.02it/s, est. speed input: 1122328.30 toks/s, output: 1006.49 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.43it/s, feature=VCF0724]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.43it/s, feature=VCF0725]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 504.30it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.44it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 502.31it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1033.46it/s, est. speed input: 1153037.70 toks/s, output: 1034.01 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF0725]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF9201]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 52/200 [00:00<00:00, 510.53it/s]

Rendering prompts:  52%|█████▏    | 104/200 [00:00<00:00, 508.14it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 508.60it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1088.24it/s, est. speed input: 1214126.59 toks/s, output: 1088.77 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=VCF9201]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=VCF9202]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.39it/s]

Rendering prompts:  76%|███████▋  | 153/200 [00:00<00:00, 508.33it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 508.44it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1129.45it/s, est. speed input: 1260215.23 toks/s, output: 1130.10 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.44it/s, feature=VCF9202]

Datasets:  75%|███████▌  | 3/4 [06:45<01:42, 102.44s/it, dataset=anes]

Seeds:  33%|███▎      | 1/3 [00:15<00:15,  7.96s/it, seed=123]

Conditions:  50%|█████     | 1/2 [00:43<00:27, 27.44s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.97s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.97s/it, seed=456]

anes Llama-3.1-8B-Instruct rule_diversity 123 pi_behav done

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 505.94it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 505.71it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 776.43it/s, est. speed input: 868443.88 toks/s, output: 776.69 toks/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]

Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s, feature=VCF0310]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 508.61it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 507.38it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 507.19it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 991.03it/s, est. speed input: 1108591.97 toks/s, output: 991.47 toks/s]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.42it/s, feature=VCF0310]

Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.42it/s, feature=VCF0606]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.94it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 506.89it/s]

Rendering prompts:  76%|███████▋  | 153/200 [00:00<00:00, 507.37it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 497.20it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1014.94it/s, est. speed input: 1135338.24 toks/s, output: 1015.41 toks/s]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.41it/s, feature=VCF0606]

Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.41it/s, feature=VCF0717]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.63it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 505.64it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 501.34it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1010.00it/s, est. speed input: 1129924.62 toks/s, output: 1010.54 toks/s]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.41it/s, feature=VCF0717]

Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.41it/s, feature=VCF0718]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 505.87it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 504.27it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.06it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1045.54it/s, est. speed input: 1169616.48 toks/s, output: 1046.03 toks/s]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.42it/s, feature=VCF0718]

Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.42it/s, feature=VCF0720]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 506.06it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 505.83it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 507.95it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1041.29it/s, est. speed input: 1164834.71 toks/s, output: 1041.76 toks/s]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.43it/s, feature=VCF0720]

Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.43it/s, feature=VCF0721]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.19it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.81it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.84it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1053.97it/s, est. speed input: 1179037.71 toks/s, output: 1054.47 toks/s]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.43it/s, feature=VCF0721]

Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.43it/s, feature=VCF0724]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.74it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 502.94it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.61it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1043.22it/s, est. speed input: 1166986.93 toks/s, output: 1043.70 toks/s]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.43it/s, feature=VCF0724]

Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.43it/s, feature=VCF0725]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 508.57it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 507.12it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 500.19it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1046.83it/s, est. speed input: 1170988.26 toks/s, output: 1047.32 toks/s]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF0725]

Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=VCF9201]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 507.44it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 506.34it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 506.33it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1069.65it/s, est. speed input: 1196598.35 toks/s, output: 1070.17 toks/s]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=VCF9201]

Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=VCF9202]

Rendering prompts:   0%|          | 0/200 [00:00<?, ?it/s]

Rendering prompts:  26%|██▌       | 51/200 [00:00<00:00, 504.79it/s]

Rendering prompts:  51%|█████     | 102/200 [00:00<00:00, 503.74it/s]

Rendering prompts: 100%|██████████| 200/200 [00:00<00:00, 504.06it/s]
Processed prompts:   0%|          | 0/200 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1082.78it/s, est. speed input: 1211269.42 toks/s, output: 1083.29 toks/s]

Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.44it/s, feature=VCF9202]

Datasets:  75%|███████▌  | 3/4 [06:53<01:42, 102.44s/it, dataset=anes]

Seeds:  67%|██████▋   | 2/3 [00:23<00:07,  7.97s/it, seed=456]

Conditions:  50%|█████     | 1/2 [00:51<00:27, 27.44s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:23<00:00,  7.97s/it, seed=456]

Conditions: 100%|██████████| 2/2 [00:51<00:00, 25.37s/it, condition=rule_diversity, model=Llama-3.1-8B-Instruct]

[rank0]:[W912 09:56:15.339107620 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

anes Llama-3.1-8B-Instruct rule_diversity 456 pi_behav done

Datasets: 100%|██████████| 4/4 [06:54<00:00, 100.04s/it, dataset=anes]

Datasets: 100%|██████████| 4/4 [06:54<00:00, 103.54s/it, dataset=anes]

## Step 3: Spearman rho with bootstrap CIs

ρ(π_self, π_behav) is the headline faithfulness number: a **high** ρ means the model relies on the features it *claims* to rely on (self-report and behaviour agree on ranking); a **low or negative** ρ means the model's stated rationale diverges from what actually drives its predictions — exactly the STaDS-style global unfaithfulness result (Li et al. 2025) this evaluation is designed to detect. Bootstrap CIs (resampling the 200 test rows) give a sense of how much ρ could plausibly vary under a different sample of the same OOD-test distribution, which matters for comparing ρ across conditions (random vs. best-protocol) without over-interpreting small differences.

In [4]:
from src.evaluation.faithfulness import spearman_with_bootstrap

rho_rows = []
for (dataset_name, model_name, condition, seed), deltas in delta_store.items():
    pi_self = pi_self_store[(dataset_name, model_name)]
    per_row_correct = per_row_correct_store[(dataset_name, model_name, condition, seed)]
    result = spearman_with_bootstrap(pi_self, deltas, per_row_correct, n_bootstrap=1000, seed=seed)
    rho_rows.append({
        'dataset': dataset_name, 'model': model_name, 'method': condition, 'seed': int(seed),
        **result,
    })

RHO_PER_SEED_COLS = ['dataset', 'model', 'method', 'seed', 'rho', 'pval', 'ci_low', 'ci_high']
rho_per_seed = pd.DataFrame(rho_rows, columns=RHO_PER_SEED_COLS)

if rho_per_seed.empty:
    print("No faithfulness results yet — skipped (vLLM not available in this environment).")
    rho_summary = pd.DataFrame(columns=['dataset', 'model', 'method', 'rho_mean', 'rho_std', 'ci_low_mean', 'ci_high_mean'])
else:
    # rho +/- CI per (dataset, model, condition): mean/std of the per-seed point
    # estimates, plus the mean of each seed's own bootstrap CI bounds.
    rho_summary = rho_per_seed.groupby(['dataset', 'model', 'method']).agg(
        rho_mean=('rho', 'mean'),
        rho_std=('rho', 'std'),
        ci_low_mean=('ci_low', 'mean'),
        ci_high_mean=('ci_high', 'mean'),
    ).reset_index()

rho_summary

,dataset,model,method,rho_mean,rho_std,ci_low_mean,ci_high_mean
0,acsincome,Llama-3.1-8B-Instruct,label_diversity,0.018182,0.052835,-0.377980,0.535455
1,acsincome,Llama-3.1-8B-Instruct,random,0.329293,0.371695,-0.579798,0.188081
2,acspubcov,Llama-3.1-8B-Instruct,random,0.082828,0.213531,-0.414343,0.491010
3,acspubcov,Llama-3.1-8B-Instruct,rule_diversity,0.074747,0.598785,-0.333333,0.495051
4,anes,Llama-3.1-8B-Instruct,random,0.058586,0.201494,-0.426364,0.543535
5,anes,Llama-3.1-8B-Instruct,rule_diversity,0.232323,0.436588,-0.515152,0.483030
6,brfss_diabetes,Llama-3.1-8B-Instruct,label_diversity,0.410101,0.240701,-0.701111,-0.054545
7,brfss_diabetes,Llama-3.1-8B-Instruct,random,0.216162,0.359846,-0.696970,0.010202

In [5]:
FAITHFULNESS_COLS = ['dataset', 'model', 'method', 'seed', 'feature', 'delta']
faithfulness_df = pd.DataFrame(faithfulness_rows, columns=FAITHFULNESS_COLS)
faithfulness_df.to_parquet(resolve_path('results/faithfulness_real.parquet'), index=False)
rho_per_seed.to_parquet(resolve_path('results/faithfulness_real_rho_per_seed.parquet'), index=False)
rho_summary.to_parquet(resolve_path('results/faithfulness_real_rho_summary.parquet'), index=False)

print(f"faithfulness_real.parquet: {len(faithfulness_df)} rows")
rho_summary

faithfulness_real.parquet: 240 rows

,dataset,model,method,rho_mean,rho_std,ci_low_mean,ci_high_mean
0,acsincome,Llama-3.1-8B-Instruct,label_diversity,0.018182,0.052835,-0.377980,0.535455
1,acsincome,Llama-3.1-8B-Instruct,random,0.329293,0.371695,-0.579798,0.188081
2,acspubcov,Llama-3.1-8B-Instruct,random,0.082828,0.213531,-0.414343,0.491010
3,acspubcov,Llama-3.1-8B-Instruct,rule_diversity,0.074747,0.598785,-0.333333,0.495051
4,anes,Llama-3.1-8B-Instruct,random,0.058586,0.201494,-0.426364,0.543535
5,anes,Llama-3.1-8B-Instruct,rule_diversity,0.232323,0.436588,-0.515152,0.483030
6,brfss_diabetes,Llama-3.1-8B-Instruct,label_diversity,0.410101,0.240701,-0.701111,-0.054545
7,brfss_diabetes,Llama-3.1-8B-Instruct,random,0.216162,0.359846,-0.696970,0.010202

## Compute budget

Per condition: 200 rows x ~12 features x 1 forward pass = 2,400 calls. 3 conditions x 3 seeds x 3 datasets x 2 models ~= 130,000 calls.

## Output

- `results/faithfulness_real.parquet` (one row per feature per condition per dataset per seed)
- Summary: rho +/- CI per (dataset, model, condition)