# Notebook 03: Faithfulness on Real Data

**Purpose**: Compute internal-consistency faithfulness rho(pi_self, pi_behav) on real datasets — answers RQ3's internal-consistency component.

**Conditions evaluated (3 only)**: Random-k, best-performing protocol from Notebook 02, and (later, Week 8) SATA if real-data transfer works.

## Why this notebook exists (thesis framing)

Accuracy alone can't tell us whether a model is generalising *for the right reasons* — that's the central move the lit review makes in §2.5, going from **invariance** (does the decision rule stay stable across environments?) to **faithfulness** (does the model's stated or measured feature reliance match what actually drives its predictions?). A model can be invariant yet unfaithful (consistently wrong feature, every environment) or faithful yet non-invariant (correctly shifts reliance as the environment shifts). This project's evaluation targets faithfulness specifically because the intervention — demonstration design — operates on a *frozen* model: nothing about the LLM's internal decision rule can be retrained, only which features it's nudged to attend to via which demonstrations it sees.

**RQ3** asks: do configurations that improve OOD accuracy also improve faithfulness, or can accuracy gains coexist with continued reliance on spurious features? This is not a foregone conclusion — Turpin et al. (2023) showed chain-of-thought explanations can be systematically unfaithful (the model changes its answer to match a bias but never mentions the bias in its stated reasoning), and STaDS (Li et al. 2025) found frontier LLMs can be highly *accurate* yet globally *unfaithful* on tabular tasks. RQ3 succeeds specifically if there exist configurations where accuracy improves but ρ(π_self, π_behav) doesn't — that would confirm predictive gains and faithful reliance are genuinely separable outcomes, not the same thing measured twice.

**Why only 3 conditions here, not all 7 from Notebook 02?** This notebook's per-condition compute cost is dominated by the leave-one-out ablation (Step 2), which reruns inference once per feature per query. Running all 7 conditions at that cost isn't affordable within the project's timeline, so the spec narrows to the two conditions most informative for RQ3: random (the no-design baseline) and whichever protocol performed best in Notebook 02 (the condition most likely to show an accuracy/faithfulness split, if one exists).

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.config import load_config, set_seed, resolve_path

config = load_config()
set_seed(config.seed_accuracy[0])

## Step 1: Elicit pi_self (self-reported feature ranking)

Prompt the LLM once per (dataset, condition, seed) via `src/inference/prompts.py::build_feature_ranking_prompt`; parse with `src/evaluation/faithfulness.py::parse_feature_ranking`.

**This is a *global* faithfulness measure, not an instance-level one.** The chain-of-thought faithfulness literature (Turpin et al. 2023; Lanham et al. 2023) asks whether a *single prediction's* stated reasoning matches the computation that produced *that* prediction. STaDS (Li et al. 2025) introduces a complementary, domain-level notion instead: does the model's self-reported feature ranking *for the task as a whole* correspond to its *behavioural* feature ranking, computed independently via ablation (Step 2)? π_self here is elicited once per (dataset, condition, seed) — not per query — because it's a claim about the task ("which features matter for this kind of prediction"), not about any individual row.

In [2]:
import json

import numpy as np
import pandas as pd

from src.data.tableshift_loader import SELECTED_DATASETS
from src.inference.llm_runner import VLLMWorkerRunner
from src.inference.prompts import build_feature_ranking_prompt
from src.evaluation.faithfulness import parse_feature_ranking
from src.utils.results_schema import load_results

FAITHFULNESS_DATASETS = SELECTED_DATASETS
FAITHFULNESS_SEEDS = config.seed_faithfulness

try:
    import vllm  # noqa: F401
    VLLM_AVAILABLE = True
except ImportError:
    VLLM_AVAILABLE = False
    print("vLLM not installed in this environment — skipping pi_self elicitation. "
          "Run this notebook on a GPU box with vllm + the model weights available.")


def best_protocol_for(dataset_name, model_name, baseline_summary):
    """Best non-zero-shot, non-random OOD-accuracy protocol from Notebook 02's
    summary (falls back to 'label_diversity' if Notebook 02 hasn't run yet)."""
    candidates = baseline_summary[
        (baseline_summary.dataset == dataset_name)
        & (baseline_summary.model == model_name)
        & (baseline_summary.environment == 'ood')
        & (~baseline_summary.method.isin(['zero_shot', 'random']))
    ]
    if candidates.empty:
        return 'label_diversity'
    return candidates.sort_values('accuracy_mean', ascending=False).iloc[0]['method']


try:
    baseline_summary = pd.read_parquet(resolve_path('results/real_arm_baselines_summary.parquet'))
except FileNotFoundError:
    baseline_summary = pd.DataFrame(columns=['dataset', 'model', 'method', 'environment', 'accuracy_mean'])

# pi_self doesn't depend on demos or query rows (see the prompt template) so, like
# zero-shot in Notebook 02, it's deterministic (temperature=0) per (dataset, model):
# elicit it once and reuse across the 3 conditions x 3 seeds it's nominally "per".
pi_self_store = {}  # (dataset_name, model_name) -> ranked feature list

for dataset_name in (FAITHFULNESS_DATASETS if VLLM_AVAILABLE else []):
    data_dir = resolve_path(config.paths.data_real) / dataset_name
    feature_list = json.load(open(data_dir / 'feature_list.json'))
    label_tokens = json.load(open(data_dir / 'label_tokens.json'))
    task_description = f"the '{dataset_name}' outcome"
    label_description = f"label {label_tokens[0]} vs {label_tokens[1]}"

    for model_cfg in config.base_llms:
        # VLLMWorkerRunner (not VLLMRunner): runs vLLM in a separate OS
        # subprocess so its GPU memory is guaranteed to be released on
        # shutdown() -- vLLM's in-process engine does not reliably free GPU
        # memory after explicit teardown, which matters here since this loop
        # constructs a fresh runner per (dataset, model) pair.
        runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))
        prompt = build_feature_ranking_prompt(task_description, feature_list, label_description)
        response_text = runner.generate_text([prompt], max_tokens=128)[0]
        ranking = parse_feature_ranking(response_text, feature_list)
        pi_self_store[(dataset_name, model_cfg.name)] = ranking
        print(dataset_name, model_cfg.name, '->', ranking)
        runner.shutdown()

INFO 09-05 14:17:26 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:17:31 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:17:31 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:17:32 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:17:32 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:17:33 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:17:34 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:17:38.082000 1780623 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:17:38.082000 1780623 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:17:40 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:17:40 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:17:40 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:17:40 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:17:41 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:17:42 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.70it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.05s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.29s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.40s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.26s/it]

INFO 09-05 14:17:48 [default_loader.py:267] Loading weights took 5.08 seconds
INFO 09-05 14:17:48 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 7.082003 seconds
INFO 09-05 14:17:56 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:17:56 [backends.py:559] Dynamo bytecode transform time: 7.78 s
INFO 09-05 14:18:01 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 4.284 s
INFO 09-05 14:18:01 [monitor.py:34] torch.compile takes 7.78 s in total
INFO 09-05 14:18:03 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:18:03 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:18:03 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:18:03,920 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:18:04,271 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:02<00:00, 33.32it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 44.55it/s]

INFO 09-05 14:18:08 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:18:08 [core.py:210] init engine (profile, create kv cache, warmup model) took 19.82 seconds
INFO 09-05 14:18:09 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 105.25it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.44it/s, est. speed input: 169.78 toks/s, output: 184.17 toks/s]

brfss_diabetes Llama-3.1-8B-Instruct -> ['HIGH_BLOOD_PRESS_10', 'HIGH_BLOOD_PRESS_20', 'MICHD_10', 'VEG_ONCE_PER_DAY_20', 'SMOKE100_20', 'TOLDHI_10', 'BMI5', 'BMI5CAT_40', 'BMI5CAT_20', 'PHYSHLTH']

[rank0]:[W905 14:18:11.145714354 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:18:21 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:18:25 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:18:25 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:18:27 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:18:27 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:18:27 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:18:28 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:18:31.390000 1780749 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:18:31.390000 1780749 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:18:32 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:18:32 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:18:32 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:18:32 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:18:32 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:18:33 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:05,  1.90s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:03<00:03,  1.98s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:05<00:01,  1.99s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.99s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:07<00:00,  1.98s/it]

INFO 09-05 14:18:41 [default_loader.py:267] Loading weights took 7.98 seconds
INFO 09-05 14:18:42 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 9.115254 seconds
INFO 09-05 14:18:45 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:18:45 [backends.py:559] Dynamo bytecode transform time: 2.85 s
INFO 09-05 14:18:55 [backends.py:197] Cache the graph for dynamic shape for later use
INFO 09-05 14:19:11 [backends.py:218] Compiling a graph for dynamic shape takes 25.49 s
INFO 09-05 14:19:17 [monitor.py:34] torch.compile takes 28.34 s in total
INFO 09-05 14:19:18 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:19:18 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:19:18 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:19:18,497 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:19:18,841 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.93it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 55.49it/s]

INFO 09-05 14:19:22 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:19:22 [core.py:210] init engine (profile, create kv cache, warmup model) took 40.06 seconds
INFO 09-05 14:19:23 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 113.35it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.46it/s, est. speed input: 185.94 toks/s, output: 187.40 toks/s]

brfss_diabetes Qwen2.5-7B-Instruct -> ['BMI5', 'BMI5CAT_20', 'BMI5CAT_40', 'HIGH_BLOOD_PRESS_10', 'HIGH_BLOOD_PRESS_20', 'MICHD_10', 'PHYSHLTH', 'SMOKE100_20', 'TOLDHI_10', 'VEG_ONCE_PER_DAY_20']

[rank0]:[W905 14:19:25.379362417 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:19:31 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:19:35 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:19:35 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:19:36 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:19:36 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:19:37 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:19:38 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:19:41.268000 1781109 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:19:41.268000 1781109 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:19:42 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:19:42 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:19:42 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:19:42 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:19:42 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:19:43 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.18it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.09s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.31s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.42s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.29s/it]

INFO 09-05 14:19:49 [default_loader.py:267] Loading weights took 5.20 seconds
INFO 09-05 14:19:49 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.330836 seconds
INFO 09-05 14:19:52 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:19:52 [backends.py:559] Dynamo bytecode transform time: 3.07 s
INFO 09-05 14:19:56 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.749 s
INFO 09-05 14:19:57 [monitor.py:34] torch.compile takes 3.07 s in total
INFO 09-05 14:19:58 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:19:58 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:19:58 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:19:58,846 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:19:59,210 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.39it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 47.50it/s]

INFO 09-05 14:20:03 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:20:03 [core.py:210] init engine (profile, create kv cache, warmup model) took 13.59 seconds
INFO 09-05 14:20:04 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 167.73it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, est. speed input: 137.88 toks/s, output: 180.09 toks/s]

acsincome Llama-3.1-8B-Instruct -> ['HINS1_02', 'HINS4_02', 'MAR_01', 'OCCP_MGR', 'RELP_02', 'SCHL_22', 'SEX', 'WKHP', 'AGEP', 'WKW']

[rank0]:[W905 14:20:06.098585716 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:20:12 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:20:15 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:20:16 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:20:17 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:20:17 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:20:17 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:20:18 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:20:21.485000 1781228 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:20:21.485000 1781228 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:20:22 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:20:22 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:20:22 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:20:22 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:20:22 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:20:23 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:03,  1.15s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.22s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.24s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.24s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.23s/it]

INFO 09-05 14:20:29 [default_loader.py:267] Loading weights took 5.04 seconds
INFO 09-05 14:20:29 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 6.127555 seconds
INFO 09-05 14:20:32 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:20:32 [backends.py:559] Dynamo bytecode transform time: 2.82 s
INFO 09-05 14:20:36 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.607 s
INFO 09-05 14:20:36 [monitor.py:34] torch.compile takes 2.82 s in total
INFO 09-05 14:20:37 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:20:38 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:20:38 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:20:38,140 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:20:38,484 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 37.44it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 56.03it/s]

INFO 09-05 14:20:42 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:20:42 [core.py:210] init engine (profile, create kv cache, warmup model) took 12.53 seconds
INFO 09-05 14:20:42 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 146.03it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.47it/s, est. speed input: 149.95 toks/s, output: 188.17 toks/s]

acsincome Qwen2.5-7B-Instruct -> ['AGEP', 'HINS1_02', 'HINS4_02', 'MAR_01', 'OCCP_MGR', 'RELP_02', 'SCHL_22', 'SEX', 'WKHP', 'WKW']

[rank0]:[W905 14:20:44.682236600 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:20:50 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:20:55 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:20:55 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:20:56 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:20:56 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:20:57 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:20:58 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:21:00.938000 1781357 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:21:00.938000 1781357 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:21:01 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:21:01 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:21:02 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:21:02 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:21:02 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:21:03 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.14it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.10s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.32s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.43s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.29s/it]

INFO 09-05 14:21:08 [default_loader.py:267] Loading weights took 5.23 seconds
INFO 09-05 14:21:09 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.412689 seconds
INFO 09-05 14:21:12 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:21:12 [backends.py:559] Dynamo bytecode transform time: 3.05 s
INFO 09-05 14:21:17 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 4.581 s
INFO 09-05 14:21:17 [monitor.py:34] torch.compile takes 3.05 s in total
INFO 09-05 14:21:19 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:21:19 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:21:19 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:21:19,442 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:21:19,795 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.97it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 48.45it/s]

INFO 09-05 14:21:23 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:21:23 [core.py:210] init engine (profile, create kv cache, warmup model) took 14.31 seconds
INFO 09-05 14:21:24 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 171.08it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, est. speed input: 136.52 toks/s, output: 180.15 toks/s]

acspubcov Llama-3.1-8B-Instruct -> ['CIT_02', 'DIVISION_00', 'ESR_01', 'FER_00', 'FER_01', 'MAR_03', 'PINCP', 'RAC1P', 'SCHL_21', 'ST_CT']

[rank0]:[W905 14:21:26.191154276 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:21:32 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:21:36 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:21:36 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:21:37 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:21:37 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:21:38 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:21:39 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:21:42.032000 1781498 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:21:42.032000 1781498 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:21:42 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:21:43 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:21:43 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:21:43 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:21:43 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:21:44 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:03,  1.15s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.17s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.17s/it]

INFO 09-05 14:21:49 [default_loader.py:267] Loading weights took 4.70 seconds
INFO 09-05 14:21:49 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 5.806801 seconds
INFO 09-05 14:21:52 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:21:52 [backends.py:559] Dynamo bytecode transform time: 2.82 s
INFO 09-05 14:21:56 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.403 s
INFO 09-05 14:21:56 [monitor.py:34] torch.compile takes 2.82 s in total
INFO 09-05 14:21:57 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:21:58 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:21:58 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:21:58,084 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:21:58,431 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:02<00:00, 29.71it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 55.02it/s]

INFO 09-05 14:22:02 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:22:02 [core.py:210] init engine (profile, create kv cache, warmup model) took 12.81 seconds
INFO 09-05 14:22:03 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 145.28it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.47it/s, est. speed input: 151.48 toks/s, output: 188.25 toks/s]

acspubcov Qwen2.5-7B-Instruct -> ['CIT_02', 'DIVISION_00', 'ESR_01', 'FER_00', 'FER_01', 'MAR_03', 'PINCP', 'RAC1P', 'SCHL_21', 'ST_CT']

[rank0]:[W905 14:22:05.685407043 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:22:11 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:22:15 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:22:15 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:22:17 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:22:17 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:22:17 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:22:19 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:22:21.982000 1781617 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:22:21.982000 1781617 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:22:23 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:22:23 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:22:23 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:22:23 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:22:23 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:22:24 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.15it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.09s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.30s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.43s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.29s/it]

INFO 09-05 14:22:29 [default_loader.py:267] Loading weights took 5.21 seconds
INFO 09-05 14:22:30 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.363903 seconds
INFO 09-05 14:22:33 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:22:33 [backends.py:559] Dynamo bytecode transform time: 3.05 s
INFO 09-05 14:22:37 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.961 s
INFO 09-05 14:22:38 [monitor.py:34] torch.compile takes 3.05 s in total
INFO 09-05 14:22:39 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:22:39 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:22:39 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:22:39,886 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:22:40,254 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.97it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 49.03it/s]

INFO 09-05 14:22:43 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:22:44 [core.py:210] init engine (profile, create kv cache, warmup model) took 13.63 seconds
INFO 09-05 14:22:44 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 183.76it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, est. speed input: 168.06 toks/s, output: 179.26 toks/s]

anes Llama-3.1-8B-Instruct -> ['VCF0301_40', 'VCF0606_00', 'VCF0717_00', 'VCF0717_20', 'VCF0718_00', 'VCF0720_00', 'VCF0721_00', 'VCF0803_90', 'VCF9201_-90', 'VCF9202_-90']

[rank0]:[W905 14:22:47.151569158 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:22:53 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:22:57 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:22:57 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:22:59 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:22:59 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:22:59 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:23:00 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:23:03.471000 1781747 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:23:03.471000 1781747 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:23:04 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:23:04 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:23:04 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:23:04 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:23:05 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:23:05 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:03,  1.16s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.18s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.17s/it]

INFO 09-05 14:23:10 [default_loader.py:267] Loading weights took 4.71 seconds
INFO 09-05 14:23:11 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 5.848529 seconds
INFO 09-05 14:23:14 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:23:14 [backends.py:559] Dynamo bytecode transform time: 2.91 s
INFO 09-05 14:23:17 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.276 s
INFO 09-05 14:23:18 [monitor.py:34] torch.compile takes 2.91 s in total
INFO 09-05 14:23:19 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:23:19 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:23:19 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:23:19,737 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:23:20,063 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 37.07it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 54.53it/s]

INFO 09-05 14:23:23 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:23:23 [core.py:210] init engine (profile, create kv cache, warmup model) took 12.45 seconds
INFO 09-05 14:23:24 [llm.py:306] Supported_tasks: ('generate',)

Adding requests: 100%|██████████| 1/1 [00:00<00:00, 144.26it/s]
Processed prompts: 100%|██████████| 1/1 [00:00<00:00,  1.46it/s, est. speed input: 217.93 toks/s, output: 187.21 toks/s]

anes Qwen2.5-7B-Instruct -> ['VCF0301_40', 'VCF0606_00', 'VCF0717_00', 'VCF0717_20', 'VCF0718_00', 'VCF0720_00', 'VCF0721_00', 'VCF0803_90', 'VCF9201_-90', 'VCF9202_-90']

[rank0]:[W905 14:23:26.642902921 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

## Step 2: Compute pi_behav via kNN hot-deck LOO ablation

For each feature j: hot-deck-impute it (5 nearest neighbours in the training pool, Euclidean distance on all features except j), re-run inference on the faithfulness subset (200 rows from OOD-test), compute the accuracy drop Delta_j. Rank features by Delta_j descending.

### Why hot-deck imputation, and not just zeroing/masking the feature?

This design choice is a direct application of a principle from **Zhu et al. (2026), "Faithfulness Under the Distribution: A New Look at Attribution Evaluation"** (ICLR 2026), which the lit review cites (ref [29]) specifically for this purpose. That paper's core finding, in the vision domain: standard attribution-evaluation methods (Insertion/Deletion, Infidelity) ablate a feature by zeroing or masking it, which silently introduces new, semantically meaningful evidence rather than removing information — their canonical example is a black-cat-vs-white-cat classifier, where zeroing pixels (making them black) doesn't remove information about "catness," it actively strengthens the "black cat" evidence. The perturbed sample also drifts off the training manifold entirely, and *model behaviour on out-of-distribution inputs is not a reliable signal of the model's real behaviour on the distribution it was trained on*. Using OOD model behaviour to evaluate ID feature importance is, in their words, "highly counterintuitive."

FUD's fix in the vision domain is to use a score-based diffusion model to resynthesise the masked region so it stays on the data manifold. **This project doesn't have (or need) a diffusion model for tabular data** — the equivalent, much cheaper fix for structured features is **hot-deck imputation**: replace the ablated feature's value with a real value sampled from the k=5 nearest neighbours in the training pool (by Euclidean distance on every *other* feature). This keeps the replacement value in-distribution and consistent with the row's other feature values, rather than an artificial zero the model was never trained to see meaningfully. The accuracy drop Δ_j this produces reflects the model's genuine reliance on feature j, not an artefact of showing the model a value it would never encounter naturally.

In [3]:
from tqdm import tqdm

from src.evaluation.faithfulness import hot_deck_impute_feature, compute_accuracy_drop, rank_from_deltas
from src.data.tableshift_loader import select_top_features
from src.data.serialisation import serialise_row, ordered_feature_names
from src.inference.prompts import build_classification_prompt
from src.selection import random_select, similarity_select, label_diversity, feature_range, rule_diversity, counter_spurious
from src.selection.rule_diversity import fit_leaf_tree
from src.selection.counter_spurious import find_spurious_proxy_features

# Same dispatch logic as Notebook 02 — duplicated rather than imported since
# each notebook here is meant to be a self-contained phase of the pipeline.
def prepare_condition_artifacts(dataset_name, train_pool, feature_cols, test_ood):
    artifacts = {}
    continuous_cols = [
        c for c in feature_cols
        if pd.api.types.is_numeric_dtype(train_pool[c]) and train_pool[c].nunique() > 10
    ]
    artifacts['top3_continuous'] = (
        select_top_features(train_pool[continuous_cols + ['label']], n_features=min(3, len(continuous_cols)))
        if continuous_cols else feature_cols[:3]
    )
    artifacts['tree'] = fit_leaf_tree(train_pool, feature_cols)

    # Counter-spurious: proxy feature most correlated with both the label and
    # the actual ID->OOD shift. TableShift's own domain-split covariate (e.g.
    # race/geography/year) is deliberately excluded from X -- it's the exact
    # variable tableshift thresholds to build the ood split, so a model can't
    # just read it directly -- and extract_tableshift_cache.py, which only
    # ever saves X, never had it to cache. Proxy against literal
    # train-vs-OOD-test row membership instead: a feature correlated with
    # *that* carries the same shift signal the raw covariate would have,
    # without needing the excluded column. (Same fix as Notebook 02 -- see
    # that notebook's comment for the full rationale; duplicated here since
    # this notebook is meant to be self-contained.)
    shift_frame = pd.concat(
        [
            train_pool[feature_cols + ['label']].assign(_is_ood=0),
            test_ood[feature_cols + ['label']].assign(_is_ood=1),
        ],
        ignore_index=True,
    )
    proxy_features = find_spurious_proxy_features(shift_frame, feature_cols, 'label', '_is_ood', top_n=3)
    proxy_col = proxy_features[0] if proxy_features else feature_cols[0]
    proxy_high = train_pool[proxy_col] > train_pool[proxy_col].median()
    artifacts['proxy_col'] = proxy_col
    artifacts['proxy_majority_label'] = train_pool.loc[proxy_high, 'label'].mode().iloc[0]
    return artifacts


def select_demos(condition, pool, query, k, seed, feature_cols, artifacts):
    if condition == 'zero_shot':
        return []
    if condition == 'random':
        return random_select.select(pool, query, k, seed)
    if condition == 'label_diversity':
        return label_diversity.select(pool, query, k, seed)
    if condition == 'feature_range':
        return feature_range.select(pool, query, k, seed, top_features=artifacts['top3_continuous'])
    if condition == 'rule_diversity':
        return rule_diversity.select(pool, query, k, seed, feature_cols=feature_cols, tree=artifacts['tree'])
    if condition == 'counter_spurious':
        return counter_spurious.select(
            pool, query, k, seed, proxy_col=artifacts['proxy_col'], proxy_majority_label=artifacts['proxy_majority_label']
        )
    raise ValueError(f"Unknown condition: {condition}")


def build_demo_lines(pool, demo_ids, feature_cols):
    lines = []
    for i in demo_ids:
        row = pool.loc[i]
        ordered = ordered_feature_names({f: row[f] for f in feature_cols})
        lines.append(serialise_row({f: row[f] for f in ordered}, label=str(row['label'])))
    return lines


def build_query_line(query, feature_cols):
    ordered = ordered_feature_names({f: query[f] for f in feature_cols})
    return serialise_row({f: query[f] for f in ordered})


FAITHFULNESS_SUBSET_SEED = FAITHFULNESS_SEEDS[0]
faithfulness_rows = []       # -> results/faithfulness_real.parquet (one row per feature/condition/dataset/seed)
per_row_correct_store = {}   # (dataset, model, condition, seed) -> {feature: bool array}
delta_store = {}             # (dataset, model, condition, seed) -> {feature: delta}

# ~130,000 LLM calls total (see the compute-budget note below) -- the nested
# tqdm bars give a glanceable readout of which (dataset, model, condition,
# seed, feature) is currently running its LOO ablation rerun.
dataset_bar = tqdm(FAITHFULNESS_DATASETS if VLLM_AVAILABLE else [], desc="Datasets", position=0)
for dataset_name in dataset_bar:
    dataset_bar.set_postfix(dataset=dataset_name)
    data_dir = resolve_path(config.paths.data_real) / dataset_name
    train_pool = pd.read_parquet(data_dir / 'train_pool.parquet')
    test_ood_full = pd.read_parquet(data_dir / 'test_ood.parquet')
    feature_cols = json.load(open(data_dir / 'feature_list.json'))
    label_tokens = tuple(json.load(open(data_dir / 'label_tokens.json')))
    task_description = f"the '{dataset_name}' outcome"

    # Fixed across every condition/seed for this dataset, per the spec.
    faith_subset = test_ood_full.sample(
        n=min(config.faithfulness_subset, len(test_ood_full)), random_state=FAITHFULNESS_SUBSET_SEED
    ).reset_index(drop=True)

    artifacts = prepare_condition_artifacts(dataset_name, train_pool, feature_cols, test_ood_full)

    for model_cfg in config.base_llms:
        # VLLMWorkerRunner (not VLLMRunner): runs vLLM in a separate OS
        # subprocess so its GPU memory is guaranteed to be released on
        # shutdown() -- vLLM's in-process engine does not reliably free GPU
        # memory after explicit teardown, which matters here since this loop
        # constructs a fresh runner per (dataset, model) pair.
        runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))
        best_protocol = best_protocol_for(dataset_name, model_cfg.name, baseline_summary)
        conditions_to_eval = ['random', best_protocol]

        # Similarity is deterministic (no seed dependency), so if it's one of
        # this dataset/model's 2 conditions, precompute its demo ids once here
        # (one batched encode() call) rather than inside the seed loop below,
        # which would otherwise re-embed the same faith_subset queries
        # identically on every one of the 3 seeds.
        similarity_demo_ids = None
        if 'similarity' in conditions_to_eval:
            pool_texts = [
                serialise_row(
                    {f: train_pool.loc[i, f] for f in ordered_feature_names({f: train_pool.loc[i, f] for f in feature_cols})},
                    label=str(train_pool.loc[i, 'label']),
                )
                for i in train_pool.index
            ]
            query_texts = [
                serialise_row({f: row[f] for f in ordered_feature_names({f: row[f] for f in feature_cols})})
                for _, row in faith_subset.iterrows()
            ]
            local_idx_per_query = similarity_select.select_batch(pool_texts, query_texts, config.k_primary)
            similarity_demo_ids = [[train_pool.index[i] for i in local_idx] for local_idx in local_idx_per_query]

        condition_bar = tqdm(conditions_to_eval, desc="Conditions", position=1, leave=False)
        for condition in condition_bar:
            condition_bar.set_postfix(condition=condition, model=model_cfg.name)
            seed_bar = tqdm(FAITHFULNESS_SEEDS, desc="Seeds", position=2, leave=False)
            for seed in seed_bar:
                seed_bar.set_postfix(seed=int(seed))
                # Demos are fixed per query across the original run and every feature
                # ablation rerun below, so only the ablated feature can flip a prediction.
                if condition == 'similarity':
                    demo_ids_per_query = similarity_demo_ids
                else:
                    demo_ids_per_query = [
                        select_demos(condition, train_pool, row, config.k_primary, seed, feature_cols, artifacts)
                        for _, row in faith_subset.iterrows()
                    ]

                def run_inference(df):
                    prompts = [
                        build_classification_prompt(
                            task_description, label_tokens,
                            build_demo_lines(train_pool, demo_ids, feature_cols),
                            build_query_line(row, feature_cols),
                        )
                        for (_, row), demo_ids in zip(df.iterrows(), demo_ids_per_query)
                    ]
                    preds = runner.batch_predict(prompts, label_tokens)
                    return np.array([p.prediction == str(row['label']) for p, (_, row) in zip(preds, df.iterrows())])

                original_correct = run_inference(faith_subset)

                deltas, per_row_correct = {}, {}
                feature_bar = tqdm(feature_cols, desc="Features (LOO ablation)", position=3, leave=False)
                for feature in feature_bar:
                    feature_bar.set_postfix(feature=feature)
                    modified = hot_deck_impute_feature(faith_subset, feature, train_pool, feature_cols, seed=seed)
                    modified_correct = run_inference(modified)
                    deltas[feature] = compute_accuracy_drop(original_correct, modified_correct)
                    per_row_correct[feature] = modified_correct

                    faithfulness_rows.append({
                        'dataset': dataset_name, 'model': model_cfg.name, 'method': condition,
                        'seed': int(seed), 'feature': feature, 'delta': deltas[feature],
                    })

                per_row_correct_store[(dataset_name, model_cfg.name, condition, seed)] = per_row_correct
                delta_store[(dataset_name, model_cfg.name, condition, seed)] = deltas
                tqdm.write(f"{dataset_name} {model_cfg.name} {condition} {seed} pi_behav done")

        runner.shutdown()

if not VLLM_AVAILABLE:
    print("Skipped — vLLM not installed in this environment.")

Datasets:   0%|          | 0/4 [00:00<?, ?it/s, dataset=brfss_diabetes]

INFO 09-05 14:23:33 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:23:36 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:23:37 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:23:38 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:23:38 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:23:38 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:23:40 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:23:42.721000 1781875 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:23:42.721000 1781875 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:23:43 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:23:43 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:23:43 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:23:44 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:23:44 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:23:44 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.15it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.09s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.31s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.41s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.28s/it]

INFO 09-05 14:23:50 [default_loader.py:267] Loading weights took 5.19 seconds
INFO 09-05 14:23:50 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.376044 seconds
INFO 09-05 14:23:54 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:23:54 [backends.py:559] Dynamo bytecode transform time: 3.06 s
INFO 09-05 14:23:58 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.931 s
INFO 09-05 14:23:59 [monitor.py:34] torch.compile takes 3.06 s in total
INFO 09-05 14:24:00 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:24:00 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:24:00 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:24:00,692 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:24:01,063 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.49it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 48.60it/s]

INFO 09-05 14:24:04 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:24:04 [core.py:210] init engine (profile, create kv cache, warmup model) took 13.90 seconds
INFO 09-05 14:24:05 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 532.60it/s]
Processed prompts: 100%|██████████| 200/200 [00:01<00:00, 154.13it/s, est. speed input: 178482.10 toks/s, output: 154.14 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 545.66it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 573.96it/s, est. speed input: 664692.93 toks/s, output: 574.07 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.08it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 542.91it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1618.97it/s, est. speed input: 1875681.09 toks/s, output: 1619.81 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.26it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 531.60it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1560.40it/s, est. speed input: 1807814.02 toks/s, output: 1561.20 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.32it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 532.14it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1849.41it/s, est. speed input: 2142833.38 toks/s, output: 1850.52 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.36it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 535.62it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2029.42it/s, est. speed input: 2352305.19 toks/s, output: 2031.40 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.40it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 534.77it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1516.91it/s, est. speed input: 1757388.63 toks/s, output: 1517.65 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.40it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 538.56it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 935.78it/s, est. speed input: 1083927.31 toks/s, output: 936.07 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.35it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.17it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1560.37it/s, est. speed input: 1807800.56 toks/s, output: 1561.19 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.36it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 543.36it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1946.97it/s, est. speed input: 2255976.08 toks/s, output: 1948.22 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.40it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.29it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2773.12it/s, est. speed input: 3215236.00 toks/s, output: 2776.58 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.43it/s, feature=VEG_ONCE_PER_DAY_20]





Datasets:   0%|          | 0/4 [00:47<?, ?it/s, dataset=brfss_diabetes]
Conditions:   0%|          | 0/2 [00:09<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:09<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.13s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.13s/it, seed=123]

brfss_diabetes Llama-3.1-8B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 540.31it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 326.51it/s, est. speed input: 378445.45 toks/s, output: 326.55 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.27it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 552.62it/s, est. speed input: 640527.49 toks/s, output: 552.72 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.05it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.64it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1554.21it/s, est. speed input: 1802187.34 toks/s, output: 1555.00 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.23it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.86it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1393.78it/s, est. speed input: 1616048.68 toks/s, output: 1394.40 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.29it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 541.45it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 439.72it/s, est. speed input: 509682.40 toks/s, output: 439.78 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:05,  1.14it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 531.58it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2056.99it/s, est. speed input: 2386270.57 toks/s, output: 2058.96 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.24it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.40it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1719.94it/s, est. speed input: 1994491.44 toks/s, output: 1720.92 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.30it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 521.61it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 989.57it/s, est. speed input: 1147246.12 toks/s, output: 989.90 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.29it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 521.59it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1426.57it/s, est. speed input: 1654086.29 toks/s, output: 1427.21 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.31it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 535.92it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1904.81it/s, est. speed input: 2209010.15 toks/s, output: 1906.01 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.35it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.16it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2565.51it/s, est. speed input: 2976935.94 toks/s, output: 2568.59 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.40it/s, feature=VEG_ONCE_PER_DAY_20]






Datasets:   0%|          | 0/4 [00:56<?, ?it/s, dataset=brfss_diabetes]el=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:18<00:18,  9.13s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:09,  9.00s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:09,  9.00s/it, seed=456]

brfss_diabetes Llama-3.1-8B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.41it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 329.22it/s, est. speed input: 380922.62 toks/s, output: 329.25 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.53it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 573.41it/s, est. speed input: 663484.22 toks/s, output: 573.52 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.07it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 531.52it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1749.92it/s, est. speed input: 2025717.92 toks/s, output: 1750.89 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.25it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 541.50it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1586.49it/s, est. speed input: 1836456.96 toks/s, output: 1587.31 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.33it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 541.25it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2304.29it/s, est. speed input: 2668761.77 toks/s, output: 2306.67 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.39it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 545.55it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2462.86it/s, est. speed input: 2852642.54 toks/s, output: 2465.60 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.44it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.63it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1632.69it/s, est. speed input: 1889984.43 toks/s, output: 1633.57 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.42it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 544.25it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1019.38it/s, est. speed input: 1179760.49 toks/s, output: 1019.70 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.38it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 539.78it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1640.16it/s, est. speed input: 1898599.34 toks/s, output: 1641.02 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.39it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 544.46it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2118.91it/s, est. speed input: 2453857.83 toks/s, output: 2120.93 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.42it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 545.45it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 3047.55it/s, est. speed input: 3530746.04 toks/s, output: 3051.68 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.46it/s, feature=VEG_ONCE_PER_DAY_20]






Datasets:   0%|          | 0/4 [01:04<?, ?it/s, dataset=brfss_diabetes]el=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:26<00:09,  9.00s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:26<00:00,  8.72s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:26<00:26, 26.43s/it, condition=random, model=Llama-3.1-8B-Instruct]
Conditions:  50%|█████     | 1/2 [00:26<00:26, 26.43s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

brfss_diabetes Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 548.67it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 324.76it/s, est. speed input: 376736.59 toks/s, output: 324.79 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.46it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 578.44it/s, est. speed input: 671022.45 toks/s, output: 578.54 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.07it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 536.47it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1500.51it/s, est. speed input: 1741360.14 toks/s, output: 1501.22 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.24it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 521.06it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1417.10it/s, est. speed input: 1644514.58 toks/s, output: 1417.73 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.29it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.79it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1811.88it/s, est. speed input: 2102935.42 toks/s, output: 1812.92 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.34it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 271.16it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1923.43it/s, est. speed input: 2232475.10 toks/s, output: 1924.60 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.17it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.52it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1533.53it/s, est. speed input: 1779669.04 toks/s, output: 1534.25 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.24it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 523.41it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 891.07it/s, est. speed input: 1033900.04 toks/s, output: 891.33 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.23it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 511.21it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1438.52it/s, est. speed input: 1669417.19 toks/s, output: 1439.20 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.27it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 513.73it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1781.59it/s, est. speed input: 2067813.13 toks/s, output: 1782.65 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.31it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 530.30it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2542.20it/s, est. speed input: 2952311.31 toks/s, output: 2545.14 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.36it/s, feature=VEG_ONCE_PER_DAY_20]






Datasets:   0%|          | 0/4 [01:13<?, ?it/s, dataset=brfss_diabetes]el_diversity, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:09<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.04s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.04s/it, seed=123]

brfss_diabetes Llama-3.1-8B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.06it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 321.61it/s, est. speed input: 373086.84 toks/s, output: 321.64 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 536.07it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 544.77it/s, est. speed input: 631997.59 toks/s, output: 544.89 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.05it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 523.38it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1534.52it/s, est. speed input: 1780851.40 toks/s, output: 1535.27 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.23it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.74it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1359.64it/s, est. speed input: 1577810.26 toks/s, output: 1360.23 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.29it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.61it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1859.87it/s, est. speed input: 2158644.51 toks/s, output: 1860.95 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.34it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 535.93it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1911.93it/s, est. speed input: 2219109.97 toks/s, output: 1913.08 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.38it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 542.06it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1589.98it/s, est. speed input: 1845269.45 toks/s, output: 1590.80 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.39it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 522.53it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 926.94it/s, est. speed input: 1075524.86 toks/s, output: 927.22 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.34it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 522.95it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1383.49it/s, est. speed input: 1605500.18 toks/s, output: 1384.10 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.34it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.38it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1856.94it/s, est. speed input: 2155235.38 toks/s, output: 1858.01 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.37it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.75it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2530.32it/s, est. speed input: 2938323.07 toks/s, output: 2533.08 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.41it/s, feature=VEG_ONCE_PER_DAY_20]






Datasets:   0%|          | 0/4 [01:22<?, ?it/s, dataset=brfss_diabetes]el_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:17<00:18,  9.04s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:17<00:08,  8.83s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:17<00:08,  8.83s/it, seed=456]

brfss_diabetes Llama-3.1-8B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 523.80it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 326.78it/s, est. speed input: 378424.28 toks/s, output: 326.81 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.33it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 567.18it/s, est. speed input: 656824.12 toks/s, output: 567.28 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.07it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.79it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1660.33it/s, est. speed input: 1923628.71 toks/s, output: 1661.21 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.24it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.18it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1502.76it/s, est. speed input: 1740937.38 toks/s, output: 1503.45 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.31it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 539.81it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2216.57it/s, est. speed input: 2569253.05 toks/s, output: 2218.76 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.37it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 532.84it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2306.56it/s, est. speed input: 2673641.80 toks/s, output: 2308.90 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.41it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 240.42it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1543.91it/s, est. speed input: 1788718.44 toks/s, output: 1544.72 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.15it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 521.68it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 966.90it/s, est. speed input: 1119996.07 toks/s, output: 967.21 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.18it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 514.99it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1551.43it/s, est. speed input: 1797393.65 toks/s, output: 1552.20 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.24it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 532.32it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2028.01it/s, est. speed input: 2350574.70 toks/s, output: 2029.91 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.30it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 522.31it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2941.10it/s, est. speed input: 3410287.95 toks/s, output: 2945.01 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.36it/s, feature=VEG_ONCE_PER_DAY_20]






Datasets:   0%|          | 0/4 [01:31<?, ?it/s, dataset=brfss_diabetes]el_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:26<00:08,  8.83s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:26<00:00,  8.92s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:53<00:00, 26.63s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

brfss_diabetes Llama-3.1-8B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:25:00.465911110 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:25:06 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:25:10 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:25:10 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:25:11 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:25:11 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:25:12 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:25:13 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:25:16.244000 1782011 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:25:16.244000 1782011 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:25:17 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:25:17 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:25:17 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:25:17 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:25:17 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:25:18 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:03,  1.15s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.17s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.16s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.17s/it]

INFO 09-05 14:25:23 [default_loader.py:267] Loading weights took 4.69 seconds
INFO 09-05 14:25:23 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 5.788046 seconds
INFO 09-05 14:25:26 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:25:26 [backends.py:559] Dynamo bytecode transform time: 2.82 s
INFO 09-05 14:25:31 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.826 s
INFO 09-05 14:25:31 [monitor.py:34] torch.compile takes 2.82 s in total
INFO 09-05 14:25:32 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:25:32 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:25:32 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:25:32,796 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:25:33,137 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 37.24it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 55.41it/s]

INFO 09-05 14:25:36 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:25:36 [core.py:210] init engine (profile, create kv cache, warmup model) took 12.83 seconds
INFO 09-05 14:25:37 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 504.01it/s]
Processed prompts: 100%|██████████| 200/200 [00:03<00:00, 52.74it/s, est. speed input: 75494.25 toks/s, output: 52.74 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 491.44it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 511.83it/s, est. speed input: 732685.76 toks/s, output: 511.92 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:01<00:09,  1.00s/it, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.64it/s]/it, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1499.71it/s, est. speed input: 2147845.32 toks/s, output: 1500.43 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.18it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 275.23it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1368.10it/s, est. speed input: 1959269.50 toks/s, output: 1368.69 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:06,  1.04it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 487.78it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1791.14it/s, est. speed input: 2565401.10 toks/s, output: 1792.10 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:05,  1.15it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.56it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1857.50it/s, est. speed input: 2660558.69 toks/s, output: 1858.58 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.23it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 505.54it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1490.00it/s, est. speed input: 2133905.96 toks/s, output: 1490.69 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:05<00:03,  1.27it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 496.68it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 775.93it/s, est. speed input: 1111049.72 toks/s, output: 776.11 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.22it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 501.78it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1503.63it/s, est. speed input: 2153442.07 toks/s, output: 1504.33 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.26it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 497.98it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1899.01it/s, est. speed input: 2719968.68 toks/s, output: 1900.08 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.30it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 535.19it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2546.56it/s, est. speed input: 3649565.35 toks/s, output: 2549.46 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.36it/s, feature=VEG_ONCE_PER_DAY_20]







Datasets:   0%|          | 0/4 [02:23<?, ?it/s, dataset=brfss_diabetes]
Conditions:   0%|          | 0/2 [00:12<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:12<00:24, 12.44s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:12<00:24, 12.44s/it, seed=123]

brfss_diabetes Qwen2.5-7B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 494.96it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 286.50it/s, est. speed input: 409288.37 toks/s, output: 286.52 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.47it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 486.99it/s, est. speed input: 695679.32 toks/s, output: 487.07 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:01<00:09,  1.02s/it, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 503.27it/s]/it, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1582.90it/s, est. speed input: 2262219.85 toks/s, output: 1583.64 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.18it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.98it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1497.52it/s, est. speed input: 2140170.41 toks/s, output: 1498.21 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.25it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.90it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2075.34it/s, est. speed input: 2967265.21 toks/s, output: 2077.19 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.31it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 493.06it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2154.02it/s, est. speed input: 3079904.46 toks/s, output: 2156.04 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.35it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.22it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1538.14it/s, est. speed input: 2198258.50 toks/s, output: 1538.87 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.35it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.65it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 877.34it/s, est. speed input: 1253607.09 toks/s, output: 877.57 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.29it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 493.46it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1598.20it/s, est. speed input: 2284121.53 toks/s, output: 1598.98 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.31it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.38it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2280.07it/s, est. speed input: 3260227.97 toks/s, output: 2282.27 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.35it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.07it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2831.85it/s, est. speed input: 4050319.12 toks/s, output: 2835.35 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.38it/s, feature=VEG_ONCE_PER_DAY_20]







Datasets:   0%|          | 0/4 [02:32<?, ?it/s, dataset=brfss_diabetes]
Conditions:   0%|          | 0/2 [00:21<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:21<00:10, 10.39s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:21<00:10, 10.39s/it, seed=456]

brfss_diabetes Qwen2.5-7B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 502.38it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 282.54it/s, est. speed input: 404200.92 toks/s, output: 282.57 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 490.71it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 505.04it/s, est. speed input: 722474.99 toks/s, output: 505.12 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:01<00:09,  1.01s/it, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.45it/s]/it, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1522.17it/s, est. speed input: 2178567.48 toks/s, output: 1522.95 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.17it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.96it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1439.38it/s, est. speed input: 2059912.44 toks/s, output: 1440.01 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.24it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 501.68it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2127.68it/s, est. speed input: 3046435.85 toks/s, output: 2129.63 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.31it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.78it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2335.75it/s, est. speed input: 3344617.53 toks/s, output: 2338.07 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.35it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.72it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 379.39it/s, est. speed input: 542768.82 toks/s, output: 379.44 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:05<00:03,  1.14it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 489.57it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 847.24it/s, est. speed input: 1212315.26 toks/s, output: 847.49 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.15it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 491.26it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1597.09it/s, est. speed input: 2285681.36 toks/s, output: 1597.83 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.21it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 496.67it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1924.69it/s, est. speed input: 2754917.58 toks/s, output: 1925.84 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.26it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 492.22it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2774.04it/s, est. speed input: 3973010.29 toks/s, output: 2777.34 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.32it/s, feature=VEG_ONCE_PER_DAY_20]







Datasets:   0%|          | 0/4 [02:41<?, ?it/s, dataset=brfss_diabetes]
Conditions:   0%|          | 0/2 [00:30<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds: 100%|██████████| 3/3 [00:30<00:00,  9.92s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:30<00:30, 30.77s/it, condition=random, model=Qwen2.5-7B-Instruct]
Conditions:  50%|█████     | 1/2 [00:30<00:30, 30.77s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

brfss_diabetes Qwen2.5-7B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.38it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 277.44it/s, est. speed input: 397739.46 toks/s, output: 277.47 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 501.40it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 506.85it/s, est. speed input: 726565.20 toks/s, output: 506.93 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.00it/s, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.53it/s]t/s, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1412.21it/s, est. speed input: 2025245.16 toks/s, output: 1412.81 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.17it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 500.52it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1305.00it/s, est. speed input: 1871412.72 toks/s, output: 1305.50 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.85it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1685.26it/s, est. speed input: 2417073.40 toks/s, output: 1686.14 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.28it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 493.08it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1743.16it/s, est. speed input: 2500155.97 toks/s, output: 1744.10 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.32it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 501.36it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1404.90it/s, est. speed input: 2014850.87 toks/s, output: 1405.56 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.32it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 489.46it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 767.78it/s, est. speed input: 1100914.85 toks/s, output: 767.96 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.26it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.98it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1470.36it/s, est. speed input: 2108685.08 toks/s, output: 1471.01 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.28it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 496.68it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1779.29it/s, est. speed input: 2551969.40 toks/s, output: 1780.24 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.31it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.68it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2386.08it/s, est. speed input: 3423855.83 toks/s, output: 2388.45 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.35it/s, feature=VEG_ONCE_PER_DAY_20]







Datasets:   0%|          | 0/4 [02:50<?, ?it/s, dataset=brfss_diabetes]
Conditions:  50%|█████     | 1/2 [00:39<00:30, 30.77s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.16s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.16s/it, seed=123]

brfss_diabetes Qwen2.5-7B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 497.77it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 277.18it/s, est. speed input: 397355.54 toks/s, output: 277.20 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 492.90it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 467.94it/s, est. speed input: 670823.73 toks/s, output: 468.03 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:01<00:09,  1.04s/it, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 489.81it/s]/it, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1390.50it/s, est. speed input: 1994068.22 toks/s, output: 1391.06 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:07,  1.14it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 494.88it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1316.72it/s, est. speed input: 1888251.54 toks/s, output: 1317.24 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.21it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 491.15it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1671.67it/s, est. speed input: 2397516.91 toks/s, output: 1672.50 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.26it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 496.59it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1785.06it/s, est. speed input: 2560282.87 toks/s, output: 1786.04 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:03,  1.31it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 496.78it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1436.58it/s, est. speed input: 2060211.34 toks/s, output: 1437.21 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.31it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.75it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 810.14it/s, est. speed input: 1161638.14 toks/s, output: 810.35 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.26it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 498.21it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1402.63it/s, est. speed input: 2011551.10 toks/s, output: 1403.26 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.28it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 503.43it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1788.92it/s, est. speed input: 2565866.29 toks/s, output: 1789.93 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.32it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 500.84it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 381.71it/s, est. speed input: 547235.92 toks/s, output: 381.76 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.15it/s, feature=VEG_ONCE_PER_DAY_20]







Datasets:   0%|          | 0/4 [03:00<?, ?it/s, dataset=brfss_diabetes]
Conditions:  50%|█████     | 1/2 [00:49<00:30, 30.77s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:18<00:09,  9.43s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:09,  9.43s/it, seed=456]

brfss_diabetes Qwen2.5-7B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 492.10it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 278.51it/s, est. speed input: 398987.33 toks/s, output: 278.53 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 493.79it/s]ture=BMI5]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 493.59it/s, est. speed input: 707078.98 toks/s, output: 493.67 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:01<00:09,  1.01s/it, feature=BMI5]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 492.26it/s]/it, feature=BMI5CAT_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1506.38it/s, est. speed input: 2158864.52 toks/s, output: 1507.07 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.17it/s, feature=BMI5CAT_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 485.61it/s]t/s, feature=BMI5CAT_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1337.45it/s, est. speed input: 1916692.30 toks/s, output: 1338.02 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.22it/s, feature=BMI5CAT_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 487.18it/s]t/s, feature=HIGH_BLOOD_PRESS_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1898.71it/s, est. speed input: 2721535.93 toks/s, output: 1899.84 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.28it/s, feature=HIGH_BLOOD_PRESS_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.21it/s]t/s, feature=HIGH_BLOOD_PRESS_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2086.78it/s, est. speed input: 2991977.79 toks/s, output: 2088.65 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.33it/s, feature=HIGH_BLOOD_PRESS_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 496.10it/s]t/s, feature=MICHD_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1523.49it/s, est. speed input: 2183413.17 toks/s, output: 1524.21 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.33it/s, feature=MICHD_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 489.41it/s]t/s, feature=PHYSHLTH]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 821.95it/s, est. speed input: 1177724.24 toks/s, output: 822.16 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.27it/s, feature=PHYSHLTH]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 499.08it/s]t/s, feature=SMOKE100_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1503.42it/s, est. speed input: 2154621.87 toks/s, output: 1504.11 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.29it/s, feature=SMOKE100_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 500.92it/s]t/s, feature=TOLDHI_10]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1857.63it/s, est. speed input: 2662505.82 toks/s, output: 1858.65 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.32it/s, feature=TOLDHI_10]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 497.16it/s]t/s, feature=VEG_ONCE_PER_DAY_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2390.27it/s, est. speed input: 3427635.43 toks/s, output: 2392.75 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.36it/s, feature=VEG_ONCE_PER_DAY_20]







Datasets:   0%|          | 0/4 [03:09<?, ?it/s, dataset=brfss_diabetes]
Conditions:  50%|█████     | 1/2 [00:58<00:30, 30.77s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

Seeds: 100%|██████████| 3/3 [00:27<00:00,  9.29s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:58<00:00, 29.09s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

brfss_diabetes Qwen2.5-7B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:26:38.228698515 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Datasets:  25%|██▌       | 1/4 [03:11<09:34, 191.49s/it, dataset=acsincome]

INFO 09-05 14:26:44 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:26:48 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:26:48 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:26:49 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:26:49 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:26:50 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:26:51 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:26:54.350000 1782216 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:26:54.350000 1782216 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:26:55 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:26:55 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:26:55 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:26:55 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:26:56 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:26:56 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.15it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.08s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.29s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.39s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.26s/it]

INFO 09-05 14:27:02 [default_loader.py:267] Loading weights took 5.10 seconds
INFO 09-05 14:27:02 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.246496 seconds
INFO 09-05 14:27:05 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:27:05 [backends.py:559] Dynamo bytecode transform time: 3.04 s
INFO 09-05 14:27:10 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 4.286 s
INFO 09-05 14:27:11 [monitor.py:34] torch.compile takes 3.04 s in total
INFO 09-05 14:27:12 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:27:12 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:27:12 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:27:12,524 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:27:12,896 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.99it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 48.69it/s]

INFO 09-05 14:27:16 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:27:16 [core.py:210] init engine (profile, create kv cache, warmup model) took 13.99 seconds
INFO 09-05 14:27:17 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 587.70it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 282.28it/s, est. speed input: 293523.28 toks/s, output: 282.34 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 587.53it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 736.15it/s, est. speed input: 765518.63 toks/s, output: 736.33 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.21it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 598.19it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1044.07it/s, est. speed input: 1085803.90 toks/s, output: 1044.42 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.29it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 592.77it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1223.68it/s, est. speed input: 1272668.71 toks/s, output: 1224.16 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.34it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 587.60it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1131.47it/s, est. speed input: 1176724.16 toks/s, output: 1131.88 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.35it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 592.32it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1428.60it/s, est. speed input: 1485905.95 toks/s, output: 1429.27 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.38it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 585.22it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1551.43it/s, est. speed input: 1613731.17 toks/s, output: 1552.22 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.41it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 590.30it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1527.70it/s, est. speed input: 1589046.22 toks/s, output: 1528.48 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.42it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.86it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1357.49it/s, est. speed input: 1411904.39 toks/s, output: 1358.09 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 595.13it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1132.07it/s, est. speed input: 1177355.94 toks/s, output: 1132.47 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.41it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.43it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1756.17it/s, est. speed input: 1826847.92 toks/s, output: 1757.16 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.44it/s, feature=WKW]







Seeds:   0%|          | 0/3 [00:08<?, ?it/s, seed=42]
Datasets:  25%|██▌       | 1/4 [03:59<09:34, 191.49s/it, dataset=acsincome]lama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:08<00:16,  8.44s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:08<00:16,  8.44s/it, seed=123]

acsincome Llama-3.1-8B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 586.45it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 472.42it/s, est. speed input: 489311.57 toks/s, output: 472.49 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.78it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 733.76it/s, est. speed input: 760090.65 toks/s, output: 733.93 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.21it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 591.72it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1231.84it/s, est. speed input: 1276227.52 toks/s, output: 1232.33 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.32it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 586.81it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1397.47it/s, est. speed input: 1447924.42 toks/s, output: 1398.12 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.37it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 283.54it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1313.31it/s, est. speed input: 1360677.02 toks/s, output: 1313.87 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:05,  1.16it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.86it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1557.27it/s, est. speed input: 1613562.40 toks/s, output: 1558.05 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:04,  1.25it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 584.76it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1810.26it/s, est. speed input: 1875836.45 toks/s, output: 1811.29 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.32it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 577.29it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1673.11it/s, est. speed input: 1733631.03 toks/s, output: 1673.99 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.37it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 585.56it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1315.42it/s, est. speed input: 1362856.48 toks/s, output: 1315.98 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.38it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 586.45it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1323.56it/s, est. speed input: 1371274.23 toks/s, output: 1324.11 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.39it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 585.45it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2115.94it/s, est. speed input: 2193378.45 toks/s, output: 2117.93 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.44it/s, feature=WKW]







Seeds:  33%|███▎      | 1/3 [00:16<00:16,  8.44s/it, seed=123]
Datasets:  25%|██▌       | 1/4 [04:07<09:34, 191.49s/it, dataset=acsincome]lama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:16<00:08,  8.43s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:16<00:08,  8.43s/it, seed=456]

acsincome Llama-3.1-8B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.97it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 392.47it/s, est. speed input: 407746.27 toks/s, output: 392.58 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 591.00it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 734.87it/s, est. speed input: 763466.08 toks/s, output: 735.04 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.22it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.41it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1135.22it/s, est. speed input: 1179501.07 toks/s, output: 1135.64 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.29it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 581.80it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1267.81it/s, est. speed input: 1317289.56 toks/s, output: 1268.30 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.34it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.04it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1246.40it/s, est. speed input: 1295055.51 toks/s, output: 1246.89 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.36it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 578.63it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1478.59it/s, est. speed input: 1536401.10 toks/s, output: 1479.26 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.39it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 590.24it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1600.65it/s, est. speed input: 1663301.83 toks/s, output: 1601.44 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.42it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 581.68it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1547.95it/s, est. speed input: 1608526.76 toks/s, output: 1548.70 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.43it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.46it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1402.35it/s, est. speed input: 1457175.44 toks/s, output: 1402.98 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 583.20it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1212.15it/s, est. speed input: 1259447.46 toks/s, output: 1212.62 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.42it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.50it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1839.39it/s, est. speed input: 1911592.48 toks/s, output: 1840.44 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.44it/s, feature=WKW]







Seeds:  67%|██████▋   | 2/3 [00:25<00:08,  8.43s/it, seed=456]
Datasets:  25%|██▌       | 1/4 [04:15<09:34, 191.49s/it, dataset=acsincome]lama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:25<00:00,  8.34s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:25<00:25, 25.09s/it, condition=random, model=Llama-3.1-8B-Instruct]
Conditions:  50%|█████     | 1/2 [00:25<00:25, 25.09s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

acsincome Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.44it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 444.14it/s, est. speed input: 461814.89 toks/s, output: 444.22 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 585.00it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 727.03it/s, est. speed input: 756025.46 toks/s, output: 727.20 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.21it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 578.94it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1045.28it/s, est. speed input: 1087034.17 toks/s, output: 1045.61 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.28it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 577.59it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1230.72it/s, est. speed input: 1279976.06 toks/s, output: 1231.19 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.33it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 594.55it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1149.26it/s, est. speed input: 1195214.22 toks/s, output: 1149.66 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.35it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 593.56it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 358.88it/s, est. speed input: 373143.04 toks/s, output: 358.93 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:04,  1.15it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.89it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1544.50it/s, est. speed input: 1606474.84 toks/s, output: 1545.24 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.24it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 585.03it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1510.00it/s, est. speed input: 1570604.44 toks/s, output: 1510.74 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.30it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 563.92it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1364.31it/s, est. speed input: 1418964.04 toks/s, output: 1364.88 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.33it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 578.19it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1153.23it/s, est. speed input: 1199368.84 toks/s, output: 1153.64 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.34it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.68it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1774.15it/s, est. speed input: 1845489.14 toks/s, output: 1775.09 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.39it/s, feature=WKW]






Datasets:  25%|██▌       | 1/4 [04:24<09:34, 191.49s/it, dataset=acsincome]iversity, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:08<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:08<00:17,  8.68s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:08<00:17,  8.68s/it, seed=123]

acsincome Llama-3.1-8B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.36it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 441.79it/s, est. speed input: 459369.14 toks/s, output: 441.87 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.22it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 732.57it/s, est. speed input: 761792.70 toks/s, output: 732.74 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.21it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.80it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1099.41it/s, est. speed input: 1143366.18 toks/s, output: 1099.79 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.29it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.47it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1225.74it/s, est. speed input: 1274821.20 toks/s, output: 1226.23 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.33it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.01it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1147.52it/s, est. speed input: 1193401.98 toks/s, output: 1147.92 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.34it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.46it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1342.27it/s, est. speed input: 1396040.04 toks/s, output: 1342.83 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.37it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.31it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1557.17it/s, est. speed input: 1619641.35 toks/s, output: 1557.90 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.39it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 587.76it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1510.57it/s, est. speed input: 1571153.39 toks/s, output: 1511.26 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.41it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.86it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1372.64it/s, est. speed input: 1427677.53 toks/s, output: 1373.26 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.42it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.65it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1156.30it/s, est. speed input: 1202549.26 toks/s, output: 1156.72 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.40it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 581.17it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1808.93it/s, est. speed input: 1881628.57 toks/s, output: 1809.92 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.43it/s, feature=WKW]






Datasets:  25%|██▌       | 1/4 [04:32<09:34, 191.49s/it, dataset=acsincome]iversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:16<00:17,  8.68s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:16<00:08,  8.45s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:16<00:08,  8.45s/it, seed=456]

acsincome Llama-3.1-8B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 579.36it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 444.87it/s, est. speed input: 462578.19 toks/s, output: 444.95 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 589.06it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 733.82it/s, est. speed input: 763103.18 toks/s, output: 733.98 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:07,  1.21it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 583.37it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1063.35it/s, est. speed input: 1105853.88 toks/s, output: 1063.71 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.29it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 586.54it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1261.71it/s, est. speed input: 1312228.78 toks/s, output: 1262.21 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.34it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 594.35it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1198.05it/s, est. speed input: 1245990.10 toks/s, output: 1198.50 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.36it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 591.80it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1447.01it/s, est. speed input: 1505025.82 toks/s, output: 1447.66 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.39it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 285.49it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1548.91it/s, est. speed input: 1611063.02 toks/s, output: 1549.66 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.21it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 595.29it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1469.96it/s, est. speed input: 1528939.71 toks/s, output: 1470.66 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.28it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 578.64it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1315.20it/s, est. speed input: 1367901.62 toks/s, output: 1315.77 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.32it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 590.23it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1173.60it/s, est. speed input: 1220560.03 toks/s, output: 1174.05 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.34it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 589.54it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1816.04it/s, est. speed input: 1889152.19 toks/s, output: 1817.09 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.39it/s, feature=WKW]






Datasets:  25%|██▌       | 1/4 [04:41<09:34, 191.49s/it, dataset=acsincome]iversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:25<00:08,  8.45s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:25<00:00,  8.51s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:50<00:00, 25.36s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

acsincome Llama-3.1-8B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:28:10.961870416 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:28:16 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:28:19 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:28:20 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:28:21 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:28:21 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:28:22 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:28:23 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:28:25.736000 1782437 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:28:25.736000 1782437 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:28:26 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:28:26 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:28:27 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:28:27 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:28:27 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:28:28 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:03,  1.16s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.19s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.18s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.18s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.18s/it]

INFO 09-05 14:28:33 [default_loader.py:267] Loading weights took 4.74 seconds
INFO 09-05 14:28:33 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 5.862835 seconds
INFO 09-05 14:28:36 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:28:36 [backends.py:559] Dynamo bytecode transform time: 2.81 s
INFO 09-05 14:28:40 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 3.403 s
INFO 09-05 14:28:40 [monitor.py:34] torch.compile takes 2.81 s in total
INFO 09-05 14:28:41 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:28:42 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:28:42 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:28:42,197 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:28:42,542 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 37.10it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 54.71it/s]

INFO 09-05 14:28:46 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:28:46 [core.py:210] init engine (profile, create kv cache, warmup model) took 12.45 seconds
INFO 09-05 14:28:47 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 775.56it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 224.11it/s, est. speed input: 304138.92 toks/s, output: 224.13 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.45it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 573.50it/s, est. speed input: 778396.75 toks/s, output: 573.61 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.07it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 537.38it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 914.58it/s, est. speed input: 1241455.25 toks/s, output: 914.86 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.16it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.22it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1189.56it/s, est. speed input: 1614853.96 toks/s, output: 1190.02 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 533.47it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1023.81it/s, est. speed input: 1389768.00 toks/s, output: 1024.15 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.88it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1370.34it/s, est. speed input: 1860361.90 toks/s, output: 1370.93 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:03,  1.29it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 536.36it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1553.81it/s, est. speed input: 2109573.42 toks/s, output: 1554.58 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.33it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 530.29it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1578.31it/s, est. speed input: 2142828.25 toks/s, output: 1579.08 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.35it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.20it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 408.36it/s, est. speed input: 554219.91 toks/s, output: 408.42 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.18it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 504.75it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 960.26it/s, est. speed input: 1303459.27 toks/s, output: 960.56 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.19it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 521.38it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1634.36it/s, est. speed input: 2219110.44 toks/s, output: 1635.22 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:08<00:00,  1.25it/s, feature=WKW]





Datasets:  25%|██▌       | 1/4 [05:28<09:34, 191.49s/it, dataset=acsincome]

Seeds:   0%|          | 0/3 [00:09<?, ?it/s, seed=42]
Conditions:   0%|          | 0/2 [00:09<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.44s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.44s/it, seed=123]

acsincome Qwen2.5-7B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 509.42it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 376.92it/s, est. speed input: 510401.49 toks/s, output: 376.96 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 533.70it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 590.40it/s, est. speed input: 799587.11 toks/s, output: 590.50 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.09it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 533.86it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1072.77it/s, est. speed input: 1453033.07 toks/s, output: 1073.14 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.26it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 537.53it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1337.79it/s, est. speed input: 1812147.37 toks/s, output: 1338.36 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.30it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.21it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1157.57it/s, est. speed input: 1567933.70 toks/s, output: 1158.00 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.31it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.09it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1439.28it/s, est. speed input: 1949704.16 toks/s, output: 1439.96 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.33it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 533.72it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1794.64it/s, est. speed input: 2431322.61 toks/s, output: 1795.64 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.36it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.30it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1704.27it/s, est. speed input: 2308854.24 toks/s, output: 1705.19 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.38it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 532.08it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1169.17it/s, est. speed input: 1583630.35 toks/s, output: 1169.60 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.36it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 533.26it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 912.21it/s, est. speed input: 1235443.27 toks/s, output: 912.48 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.32it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 534.06it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1762.82it/s, est. speed input: 2388180.34 toks/s, output: 1763.80 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.35it/s, feature=WKW]





Datasets:  25%|██▌       | 1/4 [05:37<09:34, 191.49s/it, dataset=acsincome]

Seeds:  33%|███▎      | 1/3 [00:18<00:18,  9.44s/it, seed=123]
Conditions:   0%|          | 0/2 [00:18<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:18<00:08,  9.00s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:18<00:08,  9.00s/it, seed=456]

acsincome Qwen2.5-7B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 534.57it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 370.56it/s, est. speed input: 503263.63 toks/s, output: 370.60 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 530.57it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 567.18it/s, est. speed input: 770481.64 toks/s, output: 567.28 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.06it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.72it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 952.96it/s, est. speed input: 1294502.32 toks/s, output: 953.25 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.16it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.14it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1170.92it/s, est. speed input: 1590686.41 toks/s, output: 1171.34 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.23it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.14it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1076.16it/s, est. speed input: 1462106.70 toks/s, output: 1076.66 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.25it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.21it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1371.20it/s, est. speed input: 1862947.69 toks/s, output: 1371.82 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:03,  1.29it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.73it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1484.33it/s, est. speed input: 2016661.95 toks/s, output: 1485.01 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.32it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.86it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1485.06it/s, est. speed input: 2017644.22 toks/s, output: 1485.74 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.34it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 534.23it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1111.89it/s, est. speed input: 1510465.55 toks/s, output: 1112.27 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.33it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.02it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 951.65it/s, est. speed input: 1292743.81 toks/s, output: 951.92 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.30it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 529.37it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1545.81it/s, est. speed input: 2100314.75 toks/s, output: 1546.54 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.33it/s, feature=WKW]





Datasets:  25%|██▌       | 1/4 [05:46<09:34, 191.49s/it, dataset=acsincome]

Seeds:  67%|██████▋   | 2/3 [00:27<00:08,  9.00s/it, seed=456]
Conditions:   0%|          | 0/2 [00:27<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds: 100%|██████████| 3/3 [00:27<00:00,  8.96s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:27<00:27, 27.04s/it, condition=random, model=Qwen2.5-7B-Instruct]
Conditions:  50%|█████     | 1/2 [00:27<00:27, 27.04s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

acsincome Qwen2.5-7B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 252.03it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 372.89it/s, est. speed input: 506798.59 toks/s, output: 372.93 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 516.37it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 586.79it/s, est. speed input: 797624.53 toks/s, output: 586.91 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.07it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 501.38it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 915.45it/s, est. speed input: 1244450.84 toks/s, output: 915.71 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.22it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.55it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1147.37it/s, est. speed input: 1559805.08 toks/s, output: 1147.76 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.26it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 521.16it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1015.75it/s, est. speed input: 1380847.97 toks/s, output: 1016.08 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.26it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 523.57it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1384.27it/s, est. speed input: 1882035.70 toks/s, output: 1384.86 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.29it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.82it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1515.01it/s, est. speed input: 2059886.78 toks/s, output: 1515.73 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.32it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.36it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1566.01it/s, est. speed input: 2129256.06 toks/s, output: 1566.77 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.35it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 530.09it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1058.15it/s, est. speed input: 1438488.94 toks/s, output: 1058.49 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.33it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 621.59it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 906.30it/s, est. speed input: 1232002.72 toks/s, output: 906.56 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.33it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 522.23it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1529.11it/s, est. speed input: 2079115.04 toks/s, output: 1529.81 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.34it/s, feature=WKW]





Datasets:  25%|██▌       | 1/4 [05:55<09:34, 191.49s/it, dataset=acsincome]

Seeds:   0%|          | 0/3 [00:09<?, ?it/s, seed=42]
Conditions:  50%|█████     | 1/2 [00:36<00:27, 27.04s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.28s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:09<00:18,  9.28s/it, seed=123]

acsincome Qwen2.5-7B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 530.13it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 372.55it/s, est. speed input: 508210.69 toks/s, output: 372.59 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 522.43it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 599.94it/s, est. speed input: 818531.63 toks/s, output: 600.06 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.08it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.46it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1165.97it/s, est. speed input: 1590947.72 toks/s, output: 1166.39 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.21it/s, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.68it/s]t/s, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1571.46it/s, est. speed input: 2144524.39 toks/s, output: 1572.23 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.28it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 711.03it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1259.43it/s, est. speed input: 1718551.97 toks/s, output: 1259.93 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.37it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 516.80it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1705.67it/s, est. speed input: 2327761.62 toks/s, output: 1706.55 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.38it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 520.02it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2292.61it/s, est. speed input: 3130299.92 toks/s, output: 2294.90 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.40it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 518.42it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2022.45it/s, est. speed input: 2761114.42 toks/s, output: 2024.25 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.42it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 528.64it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1306.73it/s, est. speed input: 1783107.67 toks/s, output: 1307.26 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.39it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.06it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 885.95it/s, est. speed input: 1208719.71 toks/s, output: 886.20 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.33it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.12it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2206.14it/s, est. speed input: 3012004.67 toks/s, output: 2208.21 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.37it/s, feature=WKW]





Datasets:  25%|██▌       | 1/4 [06:04<09:34, 191.49s/it, dataset=acsincome]

Seeds:  33%|███▎      | 1/3 [00:17<00:18,  9.28s/it, seed=123]
Conditions:  50%|█████     | 1/2 [00:44<00:27, 27.04s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:17<00:08,  8.88s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:17<00:08,  8.88s/it, seed=456]

acsincome Qwen2.5-7B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 526.26it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 373.78it/s, est. speed input: 508769.22 toks/s, output: 373.83 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 532.40it/s]ture=AGEP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 570.73it/s, est. speed input: 777010.39 toks/s, output: 570.83 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:08,  1.07it/s, feature=AGEP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 525.42it/s]t/s, feature=HINS1_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 356.39it/s, est. speed input: 485099.57 toks/s, output: 356.43 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:02<00:08,  1.06s/it, feature=HINS1_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 520.58it/s]/it, feature=HINS4_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1399.41it/s, est. speed input: 1905454.31 toks/s, output: 1400.03 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:06,  1.09it/s, feature=HINS4_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 518.78it/s]t/s, feature=MAR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1227.42it/s, est. speed input: 1671144.93 toks/s, output: 1227.88 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:05,  1.17it/s, feature=MAR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 518.01it/s]t/s, feature=OCCP_MGR]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1943.39it/s, est. speed input: 2646576.71 toks/s, output: 1944.55 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:04<00:03,  1.25it/s, feature=OCCP_MGR]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 523.07it/s]t/s, feature=RELP_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1875.26it/s, est. speed input: 2553704.82 toks/s, output: 1876.32 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.31it/s, feature=RELP_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 527.83it/s]t/s, feature=SCHL_22]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1814.97it/s, est. speed input: 2471552.30 toks/s, output: 1815.96 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.35it/s, feature=SCHL_22]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 520.17it/s]t/s, feature=SEX]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1204.43it/s, est. speed input: 1639870.01 toks/s, output: 1204.90 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:06<00:01,  1.33it/s, feature=SEX]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 522.49it/s]t/s, feature=WKHP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 975.93it/s, est. speed input: 1328683.58 toks/s, output: 976.23 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:07<00:00,  1.31it/s, feature=WKHP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 524.22it/s]t/s, feature=WKW]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1866.96it/s, est. speed input: 2542637.60 toks/s, output: 1868.09 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.34it/s, feature=WKW]





Datasets:  25%|██▌       | 1/4 [06:13<09:34, 191.49s/it, dataset=acsincome]

Seeds:  67%|██████▋   | 2/3 [00:27<00:08,  8.88s/it, seed=456]
Conditions:  50%|█████     | 1/2 [00:54<00:27, 27.04s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

Seeds: 100%|██████████| 3/3 [00:27<00:00,  8.99s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:54<00:00, 27.03s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

acsincome Qwen2.5-7B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:29:42.069436463 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Datasets:  50%|█████     | 2/4 [06:15<06:13, 186.97s/it, dataset=acspubcov]

INFO 09-05 14:29:48 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:29:52 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:29:52 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:29:53 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:29:53 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:29:54 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:29:55 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:29:58.156000 1782570 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:29:58.156000 1782570 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:29:59 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:29:59 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:29:59 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:29:59 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:30:00 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:30:00 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.15it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.09s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.31s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.41s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.28s/it]

INFO 09-05 14:30:06 [default_loader.py:267] Loading weights took 5.18 seconds
INFO 09-05 14:30:06 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.327981 seconds
INFO 09-05 14:30:10 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:30:10 [backends.py:559] Dynamo bytecode transform time: 3.05 s
INFO 09-05 14:30:14 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 4.107 s
INFO 09-05 14:30:15 [monitor.py:34] torch.compile takes 3.05 s in total
INFO 09-05 14:30:16 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:30:16 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:30:16 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:30:16,554 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:30:16,923 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.94it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 48.68it/s]

INFO 09-05 14:30:20 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:30:20 [core.py:210] init engine (profile, create kv cache, warmup model) took 13.91 seconds
INFO 09-05 14:30:21 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 595.79it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 470.12it/s, est. speed input: 457972.66 toks/s, output: 470.23 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 606.32it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1901.06it/s, est. speed input: 1852722.22 toks/s, output: 1902.26 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.55it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.98it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1895.96it/s, est. speed input: 1847660.66 toks/s, output: 1897.06 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.54it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.29it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1295.33it/s, est. speed input: 1262084.22 toks/s, output: 1295.84 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.47it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 595.84it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1465.43it/s, est. speed input: 1427880.46 toks/s, output: 1466.07 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.47it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.03it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1794.43it/s, est. speed input: 1748711.47 toks/s, output: 1795.47 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.47it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 586.15it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1527.87it/s, est. speed input: 1488753.10 toks/s, output: 1528.57 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.47it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.49it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1491.76it/s, est. speed input: 1453637.04 toks/s, output: 1492.45 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.46it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 578.15it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1740.98it/s, est. speed input: 1696564.67 toks/s, output: 1741.93 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.47it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 553.81it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1890.31it/s, est. speed input: 1842219.50 toks/s, output: 1891.48 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.47it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.29it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1953.91it/s, est. speed input: 1904204.47 toks/s, output: 1955.12 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.49it/s, feature=ST_CT]





Datasets:  50%|█████     | 2/4 [07:02<06:13, 186.97s/it, dataset=acspubcov]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]
Conditions:   0%|          | 0/2 [00:07<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.75s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.75s/it, seed=123]

acspubcov Llama-3.1-8B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 551.95it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 812.63it/s, est. speed input: 792455.89 toks/s, output: 812.83 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.73it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1769.84it/s, est. speed input: 1726483.00 toks/s, output: 1770.83 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:06,  1.48it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 596.11it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1800.29it/s, est. speed input: 1756190.63 toks/s, output: 1801.30 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.51it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 617.63it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1236.24it/s, est. speed input: 1205735.63 toks/s, output: 1236.72 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.48it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 287.45it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1331.14it/s, est. speed input: 1298357.60 toks/s, output: 1331.72 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.21it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 615.90it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1776.48it/s, est. speed input: 1732932.64 toks/s, output: 1777.45 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.31it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 597.08it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1568.88it/s, est. speed input: 1530340.80 toks/s, output: 1569.66 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.37it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 616.42it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1481.07it/s, est. speed input: 1444641.41 toks/s, output: 1481.74 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.40it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 602.45it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1558.37it/s, est. speed input: 1520066.85 toks/s, output: 1559.12 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.43it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 617.70it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1863.77it/s, est. speed input: 1818151.51 toks/s, output: 1864.85 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.47it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 600.38it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1876.56it/s, est. speed input: 1830629.41 toks/s, output: 1877.65 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.49it/s, feature=ST_CT]





Datasets:  50%|█████     | 2/4 [07:10<06:13, 186.97s/it, dataset=acspubcov]

Seeds:  33%|███▎      | 1/3 [00:15<00:15,  7.75s/it, seed=123]
Conditions:   0%|          | 0/2 [00:15<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.83s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.83s/it, seed=456]

acspubcov Llama-3.1-8B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.71it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 838.87it/s, est. speed input: 817230.22 toks/s, output: 839.10 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.69it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1858.03it/s, est. speed input: 1810671.17 toks/s, output: 1859.08 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 622.48it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1914.63it/s, est. speed input: 1865864.67 toks/s, output: 1915.75 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.56it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 605.30it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1292.82it/s, est. speed input: 1259644.06 toks/s, output: 1293.34 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.50it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 623.12it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1500.44it/s, est. speed input: 1462036.58 toks/s, output: 1501.14 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.50it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 599.14it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1864.23it/s, est. speed input: 1816682.39 toks/s, output: 1865.26 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.51it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 611.55it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1523.81it/s, est. speed input: 1484800.11 toks/s, output: 1524.51 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.51it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 609.30it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1602.71it/s, est. speed input: 1561727.53 toks/s, output: 1603.47 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.51it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 618.24it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1678.34it/s, est. speed input: 1635473.10 toks/s, output: 1679.21 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.52it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 615.65it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1941.91it/s, est. speed input: 1892445.17 toks/s, output: 1943.04 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.53it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 600.18it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1950.35it/s, est. speed input: 1900673.75 toks/s, output: 1951.49 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.54it/s, feature=ST_CT]





Datasets:  50%|█████     | 2/4 [07:17<06:13, 186.97s/it, dataset=acspubcov]

Seeds:  67%|██████▋   | 2/3 [00:22<00:07,  7.83s/it, seed=456]
Conditions:   0%|          | 0/2 [00:22<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:22<00:00,  7.61s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:22<00:22, 23.00s/it, condition=random, model=Llama-3.1-8B-Instruct]
Conditions:  50%|█████     | 1/2 [00:22<00:22, 23.00s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

acspubcov Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 619.19it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 814.11it/s, est. speed input: 793904.44 toks/s, output: 814.31 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.85it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1879.61it/s, est. speed input: 1833596.84 toks/s, output: 1880.69 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 606.56it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1800.83it/s, est. speed input: 1756681.03 toks/s, output: 1801.80 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.55it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 593.68it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1261.34it/s, est. speed input: 1230198.87 toks/s, output: 1261.81 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.48it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.68it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1432.63it/s, est. speed input: 1397332.14 toks/s, output: 1433.23 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.48it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.86it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 420.80it/s, est. speed input: 410308.64 toks/s, output: 420.86 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.25it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 586.74it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1485.30it/s, est. speed input: 1448777.78 toks/s, output: 1486.00 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.32it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 617.15it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1443.75it/s, est. speed input: 1408245.88 toks/s, output: 1444.37 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.37it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 592.60it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1600.48it/s, est. speed input: 1561136.56 toks/s, output: 1601.25 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.40it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.21it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1856.39it/s, est. speed input: 1810908.87 toks/s, output: 1857.42 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.44it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 597.95it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1808.20it/s, est. speed input: 1763887.34 toks/s, output: 1809.20 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.46it/s, feature=ST_CT]





Datasets:  50%|█████     | 2/4 [07:25<06:13, 186.97s/it, dataset=acspubcov]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]
Conditions:  50%|█████     | 1/2 [00:30<00:22, 23.00s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.87s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.87s/it, seed=123]

acspubcov Llama-3.1-8B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 620.59it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 816.41it/s, est. speed input: 796146.50 toks/s, output: 816.61 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.39it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1788.90it/s, est. speed input: 1745046.19 toks/s, output: 1789.87 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.54it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 616.74it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1885.33it/s, est. speed input: 1839180.08 toks/s, output: 1886.42 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.56it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.60it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1233.51it/s, est. speed input: 1203052.05 toks/s, output: 1233.96 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.49it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 618.00it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1309.96it/s, est. speed input: 1277654.06 toks/s, output: 1310.48 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.48it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 609.89it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1765.22it/s, est. speed input: 1721982.61 toks/s, output: 1766.22 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.50it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 621.39it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1490.67it/s, est. speed input: 1453996.25 toks/s, output: 1491.35 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.50it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 613.96it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1489.43it/s, est. speed input: 1452776.27 toks/s, output: 1490.08 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.50it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 611.21it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1555.30it/s, est. speed input: 1517061.04 toks/s, output: 1556.04 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.50it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 607.89it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1884.26it/s, est. speed input: 1838125.98 toks/s, output: 1885.34 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.52it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.75it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1852.46it/s, est. speed input: 1807063.55 toks/s, output: 1853.48 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.52it/s, feature=ST_CT]





Datasets:  50%|█████     | 2/4 [07:32<06:13, 186.97s/it, dataset=acspubcov]

Seeds:  33%|███▎      | 1/3 [00:15<00:15,  7.87s/it, seed=123]
Conditions:  50%|█████     | 1/2 [00:38<00:22, 23.00s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.63s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.63s/it, seed=456]

acspubcov Llama-3.1-8B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 617.49it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 827.83it/s, est. speed input: 806464.75 toks/s, output: 828.04 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 606.79it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1880.39it/s, est. speed input: 1832430.95 toks/s, output: 1881.42 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 613.64it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1913.95it/s, est. speed input: 1865195.88 toks/s, output: 1915.06 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.56it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 613.07it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1296.02it/s, est. speed input: 1262768.93 toks/s, output: 1296.55 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.51it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 615.06it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1514.56it/s, est. speed input: 1475777.56 toks/s, output: 1515.24 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.51it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 613.43it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1855.23it/s, est. speed input: 1807922.46 toks/s, output: 1856.26 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.53it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 266.96it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1511.75it/s, est. speed input: 1473034.23 toks/s, output: 1512.43 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.24it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 621.04it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1570.46it/s, est. speed input: 1530304.48 toks/s, output: 1571.21 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.32it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.58it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1689.89it/s, est. speed input: 1646700.71 toks/s, output: 1690.74 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.37it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 616.26it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1928.72it/s, est. speed input: 1879592.66 toks/s, output: 1929.85 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.42it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 589.05it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1943.12it/s, est. speed input: 1893651.43 toks/s, output: 1944.28 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.46it/s, feature=ST_CT]





Datasets:  50%|█████     | 2/4 [07:40<06:13, 186.97s/it, dataset=acspubcov]

Seeds:  67%|██████▋   | 2/3 [00:23<00:07,  7.63s/it, seed=456]
Conditions:  50%|█████     | 1/2 [00:46<00:22, 23.00s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:23<00:00,  7.72s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:46<00:00, 23.11s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

acspubcov Llama-3.1-8B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:31:09.429518656 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:31:16 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:31:20 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:31:20 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:31:22 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:31:22 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:31:22 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:31:24 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:31:26.695000 1782700 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:31:26.695000 1782700 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:31:27 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:31:27 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:31:28 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:31:28 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:31:28 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:31:28 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:01<00:03,  1.15s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:02<00:02,  1.17s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.16s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:04<00:00,  1.16s/it]

INFO 09-05 14:31:34 [default_loader.py:267] Loading weights took 4.68 seconds
INFO 09-05 14:31:34 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 5.789787 seconds
INFO 09-05 14:31:37 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:31:37 [backends.py:559] Dynamo bytecode transform time: 2.89 s
INFO 09-05 14:31:44 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 6.516 s
INFO 09-05 14:31:44 [monitor.py:34] torch.compile takes 2.89 s in total
INFO 09-05 14:31:45 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:31:46 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:31:46 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:31:46,141 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:31:46,486 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 37.25it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 55.15it/s]

INFO 09-05 14:31:50 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:31:50 [core.py:210] init engine (profile, create kv cache, warmup model) took 15.61 seconds
INFO 09-05 14:31:51 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 592.91it/s]
Processed prompts: 100%|██████████| 200/200 [00:01<00:00, 166.33it/s, est. speed input: 188018.07 toks/s, output: 166.34 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 591.27it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2309.53it/s, est. speed input: 2613223.75 toks/s, output: 2311.91 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.58it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 587.78it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2360.53it/s, est. speed input: 2670982.28 toks/s, output: 2363.00 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.58it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 574.71it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1275.40it/s, est. speed input: 1442202.70 toks/s, output: 1275.93 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.49it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 572.40it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1542.68it/s, est. speed input: 1744578.94 toks/s, output: 1543.44 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.47it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.91it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2123.21it/s, est. speed input: 2402170.65 toks/s, output: 2125.20 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.49it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 742.35it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1667.89it/s, est. speed input: 1886235.68 toks/s, output: 1668.75 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.55it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.29it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1621.47it/s, est. speed input: 1833641.70 toks/s, output: 1622.28 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.52it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 568.33it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2017.81it/s, est. speed input: 2282782.45 toks/s, output: 2019.58 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.52it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 308.58it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2215.57it/s, est. speed input: 2506850.33 toks/s, output: 2217.81 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.34it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 570.28it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2456.87it/s, est. speed input: 2780067.65 toks/s, output: 2459.50 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.40it/s, feature=ST_CT]







Seeds:   0%|          | 0/3 [00:08<?, ?it/s, seed=42]
Datasets:  50%|█████     | 2/4 [08:32<06:13, 186.97s/it, dataset=acspubcov]wen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:08<00:17,  8.63s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:08<00:17,  8.63s/it, seed=123]

acspubcov Qwen2.5-7B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 563.51it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 752.05it/s, est. speed input: 850245.14 toks/s, output: 752.23 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 581.01it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2254.85it/s, est. speed input: 2551179.25 toks/s, output: 2257.02 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 572.26it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2376.56it/s, est. speed input: 2689109.97 toks/s, output: 2379.04 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.55it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 577.78it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1236.47it/s, est. speed input: 1398146.69 toks/s, output: 1236.95 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:04,  1.47it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.38it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1386.83it/s, est. speed input: 1568249.78 toks/s, output: 1387.44 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.45it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 567.37it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2187.75it/s, est. speed input: 2475286.38 toks/s, output: 2189.88 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.47it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 584.23it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1726.77it/s, est. speed input: 1952862.95 toks/s, output: 1727.70 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.48it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.38it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1671.45it/s, est. speed input: 1890190.79 toks/s, output: 1672.32 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.48it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 578.69it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1962.99it/s, est. speed input: 2220152.23 toks/s, output: 1964.16 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.50it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 893.43it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2271.70it/s, est. speed input: 2570259.76 toks/s, output: 2273.90 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.61it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 583.48it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2423.12it/s, est. speed input: 2741840.82 toks/s, output: 2425.68 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.59it/s, feature=ST_CT]







Seeds:  33%|███▎      | 1/3 [00:16<00:17,  8.63s/it, seed=123]
Datasets:  50%|█████     | 2/4 [08:39<06:13, 186.97s/it, dataset=acspubcov]wen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:16<00:07,  7.90s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:16<00:07,  7.90s/it, seed=456]

acspubcov Qwen2.5-7B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 577.08it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 770.28it/s, est. speed input: 870101.68 toks/s, output: 770.47 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.18it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2395.74it/s, est. speed input: 2708493.05 toks/s, output: 2398.31 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.16it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2489.11it/s, est. speed input: 2814086.26 toks/s, output: 2491.81 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.57it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 572.36it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1336.87it/s, est. speed input: 1510395.62 toks/s, output: 1337.44 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.49it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 572.44it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1743.92it/s, est. speed input: 1970490.22 toks/s, output: 1744.84 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.49it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.33it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2375.08it/s, est. speed input: 2685002.22 toks/s, output: 2377.51 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.51it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.69it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1733.59it/s, est. speed input: 1958841.12 toks/s, output: 1734.52 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.50it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 584.25it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1781.14it/s, est. speed input: 2012527.04 toks/s, output: 1782.08 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.50it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 579.02it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2130.06it/s, est. speed input: 2407725.30 toks/s, output: 2132.00 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.52it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 579.67it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2381.23it/s, est. speed input: 2691991.27 toks/s, output: 2383.70 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.53it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 581.39it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2499.35it/s, est. speed input: 2825644.54 toks/s, output: 2502.04 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.54it/s, feature=ST_CT]







Seeds:  67%|██████▋   | 2/3 [00:23<00:07,  7.90s/it, seed=456]
Datasets:  50%|█████     | 2/4 [08:47<06:13, 186.97s/it, dataset=acspubcov]wen2.5-7B-Instruct]

Seeds: 100%|██████████| 3/3 [00:23<00:00,  7.67s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:23<00:23, 23.43s/it, condition=random, model=Qwen2.5-7B-Instruct]
Conditions:  50%|█████     | 1/2 [00:23<00:23, 23.43s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

acspubcov Qwen2.5-7B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 299.95it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 777.38it/s, est. speed input: 877350.08 toks/s, output: 777.58 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 566.28it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2612.61it/s, est. speed input: 2951270.19 toks/s, output: 2615.60 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.57it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 564.80it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2520.37it/s, est. speed input: 2846945.00 toks/s, output: 2523.14 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.56it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.03it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1388.04it/s, est. speed input: 1566804.26 toks/s, output: 1388.62 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.50it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 569.92it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1711.05it/s, est. speed input: 1931631.63 toks/s, output: 1711.94 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.49it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.64it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2433.03it/s, est. speed input: 2748162.77 toks/s, output: 2435.60 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.52it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.19it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1858.64it/s, est. speed input: 2098379.46 toks/s, output: 1859.72 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.52it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.96it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1799.29it/s, est. speed input: 2031280.82 toks/s, output: 1800.31 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.51it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 582.67it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2231.74it/s, est. speed input: 2520520.82 toks/s, output: 2233.86 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.52it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 570.96it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2448.48it/s, est. speed input: 2765620.35 toks/s, output: 2451.05 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.53it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 567.55it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2631.41it/s, est. speed input: 2972644.92 toks/s, output: 2634.53 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.54it/s, feature=ST_CT]






Datasets:  50%|█████     | 2/4 [08:54<06:13, 186.97s/it, dataset=acspubcov]iversity, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.74s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.74s/it, seed=123]

acspubcov Qwen2.5-7B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 567.53it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 787.44it/s, est. speed input: 888684.44 toks/s, output: 787.63 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 566.38it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2544.39it/s, est. speed input: 2874107.99 toks/s, output: 2547.20 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.47it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2662.97it/s, est. speed input: 3008121.17 toks/s, output: 2665.98 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.57it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 568.77it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1364.20it/s, est. speed input: 1539887.92 toks/s, output: 1364.76 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.49it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 566.82it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1516.07it/s, est. speed input: 1711394.65 toks/s, output: 1516.76 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.47it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 558.41it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2480.12it/s, est. speed input: 2801425.02 toks/s, output: 2482.80 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.49it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 565.56it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1851.02it/s, est. speed input: 2089761.92 toks/s, output: 1852.08 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.49it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 563.14it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1891.65it/s, est. speed input: 2135571.81 toks/s, output: 1892.77 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.49it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.54it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2135.30it/s, est. speed input: 2411636.90 toks/s, output: 2137.36 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.51it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.58it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2489.66it/s, est. speed input: 2812237.61 toks/s, output: 2492.37 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.52it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 572.28it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2714.85it/s, est. speed input: 3066847.64 toks/s, output: 2718.01 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.54it/s, feature=ST_CT]






Datasets:  50%|█████     | 2/4 [09:02<06:13, 186.97s/it, dataset=acspubcov]iversity, model=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:15<00:15,  7.74s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.58s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:15<00:07,  7.58s/it, seed=456]

acspubcov Qwen2.5-7B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 579.90it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 747.17it/s, est. speed input: 846256.93 toks/s, output: 747.38 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.39it/s]ture=CIT_02]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2019.31it/s, est. speed input: 2288584.94 toks/s, output: 2021.13 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.52it/s, feature=CIT_02]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 286.42it/s]t/s, feature=DIVISION_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2163.44it/s, est. speed input: 2452227.90 toks/s, output: 2165.65 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.16it/s, feature=DIVISION_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 568.08it/s]t/s, feature=ESR_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1259.42it/s, est. speed input: 1426613.70 toks/s, output: 1259.91 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.26it/s, feature=ESR_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 560.18it/s]t/s, feature=FER_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1568.32it/s, est. speed input: 1776715.15 toks/s, output: 1569.09 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:03<00:04,  1.33it/s, feature=FER_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 575.61it/s]t/s, feature=FER_01]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2056.79it/s, est. speed input: 2331000.36 toks/s, output: 2058.59 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.40it/s, feature=FER_01]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 562.65it/s]t/s, feature=MAR_03]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1568.74it/s, est. speed input: 1777197.18 toks/s, output: 1569.52 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.41it/s, feature=MAR_03]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.08it/s]t/s, feature=PINCP]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1577.82it/s, est. speed input: 1787461.16 toks/s, output: 1578.60 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:05<00:02,  1.43it/s, feature=PINCP]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.28it/s]t/s, feature=RAC1P]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1914.94it/s, est. speed input: 2169590.48 toks/s, output: 1916.03 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.45it/s, feature=RAC1P]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 573.41it/s]t/s, feature=SCHL_21]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2170.72it/s, est. speed input: 2460218.29 toks/s, output: 2172.70 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.48it/s, feature=SCHL_21]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 580.14it/s]t/s, feature=ST_CT]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2209.71it/s, est. speed input: 2504578.10 toks/s, output: 2211.88 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:07<00:00,  1.50it/s, feature=ST_CT]






Datasets:  50%|█████     | 2/4 [09:10<06:13, 186.97s/it, dataset=acspubcov]iversity, model=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:23<00:07,  7.58s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:23<00:00,  7.75s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:46<00:00, 23.27s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

acspubcov Qwen2.5-7B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:32:39.110524643 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Datasets:  75%|███████▌  | 3/4 [09:12<03:02, 182.44s/it, dataset=anes]

INFO 09-05 14:32:45 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:32:49 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-05 14:32:49 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:32:50 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 09-05 14:32:50 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:32:51 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:32:52 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:32:55.155000 1782848 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:32:55.155000 1782848 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:32:56 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:32:56 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:32:56 [gpu_model_runner.py:2602] Starting to load model meta-llama/Llama-3.1-8B-Instruct...
INFO 09-05 14:32:56 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:32:56 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:32:57 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  2.17it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:02,  1.09s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:03<00:01,  1.30s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.40s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.27s/it]

INFO 09-05 14:33:02 [default_loader.py:267] Loading weights took 5.15 seconds
INFO 09-05 14:33:03 [gpu_model_runner.py:2653] Model loading took 14.9889 GiB and 6.318005 seconds
INFO 09-05 14:33:06 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/305d31652b/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:33:06 [backends.py:559] Dynamo bytecode transform time: 3.06 s
INFO 09-05 14:33:12 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 5.304 s
INFO 09-05 14:33:12 [monitor.py:34] torch.compile takes 3.06 s in total
INFO 09-05 14:33:14 [gpu_worker.py:298] Available KV cache memory: 106.11 GiB
INFO 09-05 14:33:14 [kv_cache_utils.py:1087] GPU KV cache size: 869,264 tokens
INFO 09-05 14:33:14 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 212.22x

2026-09-05 14:33:14,307 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:33:14,678 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 36.23it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 48.53it/s]

INFO 09-05 14:33:18 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -1.56 GiB
INFO 09-05 14:33:18 [core.py:210] init engine (profile, create kv cache, warmup model) took 15.09 seconds
INFO 09-05 14:33:19 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 622.88it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 452.24it/s, est. speed input: 432468.46 toks/s, output: 452.37 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 615.86it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2113.12it/s, est. speed input: 2022156.64 toks/s, output: 2115.16 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.63it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 609.35it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2053.45it/s, est. speed input: 1964954.35 toks/s, output: 2055.32 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:04,  1.62it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 592.54it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2053.30it/s, est. speed input: 1964814.74 toks/s, output: 2055.18 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.60it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 589.43it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2102.99it/s, est. speed input: 2012373.40 toks/s, output: 2104.91 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.60it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 599.56it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2153.89it/s, est. speed input: 2061189.00 toks/s, output: 2155.98 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.61it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 589.11it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2090.20it/s, est. speed input: 2000087.10 toks/s, output: 2092.07 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.60it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 597.73it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2086.09it/s, est. speed input: 1996159.09 toks/s, output: 2087.96 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.60it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 583.88it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2091.88it/s, est. speed input: 2001694.62 toks/s, output: 2093.74 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.59it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 595.38it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2150.67it/s, est. speed input: 2058215.98 toks/s, output: 2152.87 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.59it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 579.26it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2184.40it/s, est. speed input: 2090319.11 toks/s, output: 2186.44 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.59it/s, feature=VCF9202_-90]







Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]
Datasets:  75%|███████▌  | 3/4 [09:59<03:02, 182.44s/it, dataset=anes]del=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.25s/it, seed=42]

Adding requests:   0%|          | 0/200 [00:00<?, ?it/s]d=123]

anes Llama-3.1-8B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 577.46it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1484.62it/s, est. speed input: 1420002.95 toks/s, output: 1485.32 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 588.68it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2085.57it/s, est. speed input: 1995707.04 toks/s, output: 2087.49 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.59it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 583.76it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2133.77it/s, est. speed input: 2041834.52 toks/s, output: 2135.74 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.58it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 593.01it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2079.40it/s, est. speed input: 1989799.61 toks/s, output: 2081.31 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.58it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 293.01it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2192.95it/s, est. speed input: 2098771.08 toks/s, output: 2195.29 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.30it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 610.15it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2147.74it/s, est. speed input: 2055198.86 toks/s, output: 2149.72 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.40it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 602.29it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2116.45it/s, est. speed input: 2025246.23 toks/s, output: 2118.38 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.47it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.50it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2081.57it/s, est. speed input: 1991845.66 toks/s, output: 2083.44 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.51it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.05it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2156.66it/s, est. speed input: 2063788.14 toks/s, output: 2158.70 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.55it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.33it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2160.23it/s, est. speed input: 2067144.88 toks/s, output: 2162.21 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.57it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 592.61it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2191.11it/s, est. speed input: 2096806.55 toks/s, output: 2193.23 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.58it/s, feature=VCF9202_-90]







Seeds:  33%|███▎      | 1/3 [00:14<00:14,  7.25s/it, seed=123]
Datasets:  75%|███████▌  | 3/4 [10:06<03:02, 182.44s/it, dataset=anes]del=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.27s/it, seed=123]

Adding requests:   0%|          | 0/200 [00:00<?, ?it/s]d=456]

anes Llama-3.1-8B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 609.55it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1509.59it/s, est. speed input: 1443889.96 toks/s, output: 1510.30 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 618.13it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2081.54it/s, est. speed input: 1991771.46 toks/s, output: 2083.38 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.63it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.19it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2111.94it/s, est. speed input: 2020872.52 toks/s, output: 2113.80 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:04,  1.62it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 615.87it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2081.24it/s, est. speed input: 1991558.76 toks/s, output: 2083.15 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.62it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 610.85it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2163.21it/s, est. speed input: 2070004.84 toks/s, output: 2165.20 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.62it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 605.72it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2090.21it/s, est. speed input: 2000057.17 toks/s, output: 2092.04 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.62it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 600.55it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2072.62it/s, est. speed input: 1983205.83 toks/s, output: 2074.41 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.62it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 604.41it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2137.98it/s, est. speed input: 2045819.27 toks/s, output: 2139.90 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.62it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.49it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2119.45it/s, est. speed input: 2028083.66 toks/s, output: 2121.35 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:04<00:01,  1.62it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 593.60it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2156.04it/s, est. speed input: 2063103.24 toks/s, output: 2157.98 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.61it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 610.44it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2162.82it/s, est. speed input: 2069566.80 toks/s, output: 2164.74 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.62it/s, feature=VCF9202_-90]







Seeds:  67%|██████▋   | 2/3 [00:21<00:07,  7.27s/it, seed=456]
Datasets:  75%|███████▌  | 3/4 [10:13<03:02, 182.44s/it, dataset=anes]del=Llama-3.1-8B-Instruct]

Seeds: 100%|██████████| 3/3 [00:21<00:00,  7.09s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:21<00:21, 21.41s/it, condition=random, model=Llama-3.1-8B-Instruct]
Conditions:  50%|█████     | 1/2 [00:21<00:21, 21.41s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

anes Llama-3.1-8B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.40it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1474.24it/s, est. speed input: 1410036.00 toks/s, output: 1474.89 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 602.08it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2184.50it/s, est. speed input: 2090373.59 toks/s, output: 2186.51 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.62it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.21it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1982.17it/s, est. speed input: 1896160.93 toks/s, output: 1983.36 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.60it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 612.47it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2080.97it/s, est. speed input: 1991202.73 toks/s, output: 2082.78 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.60it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 593.96it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2117.45it/s, est. speed input: 2026172.38 toks/s, output: 2119.35 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.60it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 600.76it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 438.72it/s, est. speed input: 419483.93 toks/s, output: 438.79 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.33it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 606.19it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2084.34it/s, est. speed input: 1994495.96 toks/s, output: 2086.22 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.41it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 610.15it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2064.22it/s, est. speed input: 1975209.66 toks/s, output: 2066.05 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.47it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 591.23it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2115.71it/s, est. speed input: 2024494.67 toks/s, output: 2117.59 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.50it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 608.30it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2172.00it/s, est. speed input: 2078476.15 toks/s, output: 2174.05 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.54it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 596.55it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2156.55it/s, est. speed input: 2063681.93 toks/s, output: 2158.59 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.56it/s, feature=VCF9202_-90]






Datasets:  75%|███████▌  | 3/4 [10:21<03:02, 182.44s/it, dataset=anes]bel_diversity, model=Llama-3.1-8B-Instruct]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.32s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.32s/it, seed=123]

anes Llama-3.1-8B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 614.79it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1492.05it/s, est. speed input: 1427098.60 toks/s, output: 1492.74 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 606.65it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2117.75it/s, est. speed input: 2026494.95 toks/s, output: 2119.69 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.61it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 602.03it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2160.84it/s, est. speed input: 2067693.85 toks/s, output: 2162.78 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:04,  1.61it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 611.59it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2077.32it/s, est. speed input: 1987733.11 toks/s, output: 2079.15 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.61it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 618.39it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2156.42it/s, est. speed input: 2063474.84 toks/s, output: 2158.36 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.62it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.08it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2150.80it/s, est. speed input: 2058078.64 toks/s, output: 2152.73 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.62it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 601.96it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2071.84it/s, est. speed input: 1982524.35 toks/s, output: 2073.69 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.61it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 600.28it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2073.79it/s, est. speed input: 1984314.85 toks/s, output: 2075.57 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.60it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 585.85it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2148.20it/s, est. speed input: 2055620.30 toks/s, output: 2150.15 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:04<00:01,  1.60it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 601.92it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2189.42it/s, est. speed input: 2095097.45 toks/s, output: 2191.44 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.60it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 616.91it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2155.70it/s, est. speed input: 2062816.68 toks/s, output: 2157.67 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.60it/s, feature=VCF9202_-90]






Datasets:  75%|███████▌  | 3/4 [10:28<03:02, 182.44s/it, dataset=anes]bel_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:14<00:14,  7.32s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.10s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.10s/it, seed=456]

anes Llama-3.1-8B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 611.20it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1472.28it/s, est. speed input: 1408203.77 toks/s, output: 1472.98 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.70it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2069.08it/s, est. speed input: 1979803.11 toks/s, output: 2070.85 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.60it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 588.57it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2103.08it/s, est. speed input: 2012403.70 toks/s, output: 2104.96 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.59it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 600.49it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2113.69it/s, est. speed input: 2022564.64 toks/s, output: 2115.57 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.59it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 583.40it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2099.57it/s, est. speed input: 2009428.67 toks/s, output: 2101.84 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.58it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 591.26it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2117.94it/s, est. speed input: 2026710.05 toks/s, output: 2119.91 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.59it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 286.17it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2060.64it/s, est. speed input: 1971853.69 toks/s, output: 2062.54 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:03,  1.33it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 611.05it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2100.31it/s, est. speed input: 2009856.73 toks/s, output: 2102.28 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:02,  1.41it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 599.79it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2120.45it/s, est. speed input: 2029063.75 toks/s, output: 2122.38 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.46it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 611.69it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2145.63it/s, est. speed input: 2053136.28 toks/s, output: 2147.56 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.51it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 603.66it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2191.88it/s, est. speed input: 2097426.25 toks/s, output: 2193.88 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.54it/s, feature=VCF9202_-90]






Datasets:  75%|███████▌  | 3/4 [10:35<03:02, 182.44s/it, dataset=anes]bel_diversity, model=Llama-3.1-8B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:21<00:07,  7.10s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:21<00:00,  7.22s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:43<00:00, 21.54s/it, condition=label_diversity, model=Llama-3.1-8B-Instruct]

anes Llama-3.1-8B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:34:04.245425776 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

INFO 09-05 14:34:10 [__init__.py:216] Automatically detected platform cuda.
INFO 09-05 14:34:14 [utils.py:233] non-default args: {'max_model_len': 4096, 'disable_log_stats': True, 'model': 'Qwen/Qwen2.5-7B-Instruct'}
WARNING 09-05 14:34:14 [model.py:371] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.
INFO 09-05 14:34:16 [model.py:547] Resolved architecture: Qwen2ForCausalLM
INFO 09-05 14:34:16 [model.py:1510] Using max model len 4096

`torch_dtype` is deprecated! Use `dtype` instead!

INFO 09-05 14:34:16 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-05 14:34:17 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":[2,1],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}

W0905 14:34:20.435000 1782973 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
W0905 14:34:20.435000 1782973 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 09-05 14:34:21 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
WARNING 09-05 14:34:21 [topk_topp_sampler.py:59] FlashInfer is available, but it is not enabled. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please set VLLM_USE_FLASHINFER_SAMPLER=1.
INFO 09-05 14:34:21 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen2.5-7B-Instruct...
INFO 09-05 14:34:21 [gpu_model_runner.py:2634] Loading model from scratch...
INFO 09-05 14:34:21 [cuda.py:366] Using Flash Attention backend on V1 engine.
INFO 09-05 14:34:22 [weight_utils.py:392] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:05<00:17,  5.88s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:07<00:06,  3.16s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:08<00:02,  2.24s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:09<00:00,  1.81s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:09<00:00,  2.36s/it]

INFO 09-05 14:34:32 [default_loader.py:267] Loading weights took 9.47 seconds
INFO 09-05 14:34:33 [gpu_model_runner.py:2653] Model loading took 14.2488 GiB and 10.622805 seconds
INFO 09-05 14:34:36 [backends.py:548] Using cache directory: /home/562/cg3543/.cache/vllm/torch_compile_cache/50331a83ba/rank_0_0/backbone for vLLM's torch.compile
INFO 09-05 14:34:36 [backends.py:559] Dynamo bytecode transform time: 2.85 s
INFO 09-05 14:34:40 [backends.py:164] Directly load the compiled graph(s) for dynamic shape from the cache, took 4.382 s
INFO 09-05 14:34:41 [monitor.py:34] torch.compile takes 2.85 s in total
INFO 09-05 14:34:42 [gpu_worker.py:298] Available KV cache memory: 106.01 GiB
INFO 09-05 14:34:42 [kv_cache_utils.py:1087] GPU KV cache size: 1,984,976 tokens
INFO 09-05 14:34:42 [kv_cache_utils.py:1091] Maximum concurrency for 4,096 tokens per request: 484.61x

2026-09-05 14:34:42,477 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
2026-09-05 14:34:42,822 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 67/67 [00:01<00:00, 37.27it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 67/67 [00:01<00:00, 55.69it/s]

INFO 09-05 14:34:46 [gpu_model_runner.py:3480] Graph capturing finished in 4 secs, took -2.07 GiB
INFO 09-05 14:34:46 [core.py:210] init engine (profile, create kv cache, warmup model) took 13.36 seconds
INFO 09-05 14:34:47 [llm.py:306] Supported_tasks: ('generate',)

Conditions:   0%|          | 0/2 [00:00<?, ?it/s]
Conditions:   0%|          | 0/2 [00:00<?, ?it/s, condition=random, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 576.41it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 401.73it/s, est. speed input: 492235.44 toks/s, output: 401.82 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 559.16it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2430.01it/s, est. speed input: 2980101.27 toks/s, output: 2432.63 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.59it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 565.06it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2404.73it/s, est. speed input: 2949039.13 toks/s, output: 2407.28 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.58it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 563.87it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2571.27it/s, est. speed input: 3153389.45 toks/s, output: 2574.08 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.59it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 561.49it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2450.31it/s, est. speed input: 3004998.99 toks/s, output: 2452.97 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.59it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 559.97it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2492.34it/s, est. speed input: 3056572.76 toks/s, output: 2495.06 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.58it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 569.95it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2543.16it/s, est. speed input: 3118848.62 toks/s, output: 2545.89 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.59it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 557.60it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2500.24it/s, est. speed input: 3066267.86 toks/s, output: 2502.97 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 554.19it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2516.04it/s, est. speed input: 3085649.15 toks/s, output: 2518.79 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.58it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 318.54it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2545.91it/s, est. speed input: 3122430.84 toks/s, output: 2548.81 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.39it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 495.13it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2642.34it/s, est. speed input: 3240642.45 toks/s, output: 2645.31 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.42it/s, feature=VCF9202_-90]







Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]
Datasets:  75%|███████▌  | 3/4 [11:27<03:02, 182.44s/it, dataset=anes]del=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:07<00:15,  7.70s/it, seed=42]

Adding requests:   0%|          | 0/200 [00:00<?, ?it/s]d=123]

anes Qwen2.5-7B-Instruct random 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 563.16it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1559.23it/s, est. speed input: 1911036.54 toks/s, output: 1559.99 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 565.10it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2484.20it/s, est. speed input: 3046812.31 toks/s, output: 2487.09 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.59it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 789.28it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2493.33it/s, est. speed input: 3057837.03 toks/s, output: 2496.09 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:04,  1.75it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 570.00it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2503.37it/s, est. speed input: 3069996.21 toks/s, output: 2506.01 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.67it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 558.34it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2586.78it/s, est. speed input: 3172460.84 toks/s, output: 2589.66 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.64it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 566.24it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2566.38it/s, est. speed input: 3147420.54 toks/s, output: 2569.22 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.62it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 558.00it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2590.04it/s, est. speed input: 3176510.98 toks/s, output: 2592.96 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.61it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 553.18it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2554.35it/s, est. speed input: 3132577.57 toks/s, output: 2557.10 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.59it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 567.04it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2621.81it/s, est. speed input: 3215353.53 toks/s, output: 2624.67 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:04<00:01,  1.59it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 552.25it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2566.30it/s, est. speed input: 3147324.14 toks/s, output: 2569.14 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.59it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 560.80it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2578.12it/s, est. speed input: 3161791.84 toks/s, output: 2580.94 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.59it/s, feature=VCF9202_-90]







Seeds:  33%|███▎      | 1/3 [00:14<00:15,  7.70s/it, seed=123]
Datasets:  75%|███████▌  | 3/4 [11:34<03:02, 182.44s/it, dataset=anes]del=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.24s/it, seed=123]

Adding requests:   0%|          | 0/200 [00:00<?, ?it/s]d=456]

anes Qwen2.5-7B-Instruct random 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 550.54it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1578.85it/s, est. speed input: 1935119.32 toks/s, output: 1579.64 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 564.62it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2507.77it/s, est. speed input: 3075536.72 toks/s, output: 2510.54 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.59it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 545.47it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2363.00it/s, est. speed input: 2897876.74 toks/s, output: 2365.53 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.56it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 559.79it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2510.91it/s, est. speed input: 3079370.70 toks/s, output: 2513.67 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.57it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 555.06it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2462.31it/s, est. speed input: 3019754.92 toks/s, output: 2465.01 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.57it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 553.04it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2519.99it/s, est. speed input: 3090558.38 toks/s, output: 2522.81 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.57it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 558.38it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2485.75it/s, est. speed input: 3048511.59 toks/s, output: 2488.48 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.57it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 557.38it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2559.56it/s, est. speed input: 3139161.39 toks/s, output: 2562.48 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.57it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 550.35it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2496.27it/s, est. speed input: 3061353.35 toks/s, output: 2498.97 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.57it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 561.05it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2569.93it/s, est. speed input: 3151803.26 toks/s, output: 2572.80 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.57it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 545.66it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 436.06it/s, est. speed input: 534260.13 toks/s, output: 436.13 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.33it/s, feature=VCF9202_-90]







Seeds:  67%|██████▋   | 2/3 [00:22<00:07,  7.24s/it, seed=456]
Datasets:  75%|███████▌  | 3/4 [11:41<03:02, 182.44s/it, dataset=anes]del=Qwen2.5-7B-Instruct]

Seeds: 100%|██████████| 3/3 [00:22<00:00,  7.34s/it, seed=456]


Conditions:  50%|█████     | 1/2 [00:22<00:22, 22.09s/it, condition=random, model=Qwen2.5-7B-Instruct]
Conditions:  50%|█████     | 1/2 [00:22<00:22, 22.09s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

anes Qwen2.5-7B-Instruct random 456 pi_behav done

Seeds:   0%|          | 0/3 [00:00<?, ?it/s]

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 547.78it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1558.66it/s, est. speed input: 1910340.22 toks/s, output: 1559.42 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 557.43it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2592.67it/s, est. speed input: 3179715.26 toks/s, output: 2595.58 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.60it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 556.33it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2465.85it/s, est. speed input: 3024082.73 toks/s, output: 2468.54 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.59it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 558.15it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2481.56it/s, est. speed input: 3043482.52 toks/s, output: 2484.38 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.59it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 569.09it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2488.03it/s, est. speed input: 3051254.32 toks/s, output: 2490.72 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.59it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 553.34it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2582.31it/s, est. speed input: 3166936.78 toks/s, output: 2585.15 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.59it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 549.34it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2566.35it/s, est. speed input: 3147420.54 toks/s, output: 2569.21 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.58it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 557.21it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2512.42it/s, est. speed input: 3081217.37 toks/s, output: 2515.17 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 568.64it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2501.02it/s, est. speed input: 3067228.85 toks/s, output: 2503.76 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.59it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 550.83it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2546.12it/s, est. speed input: 3122573.16 toks/s, output: 2548.94 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.58it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 548.04it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2569.16it/s, est. speed input: 3151010.77 toks/s, output: 2572.15 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.58it/s, feature=VCF9202_-90]






Datasets:  75%|███████▌  | 3/4 [11:48<03:02, 182.44s/it, dataset=anes]bel_diversity, model=Qwen2.5-7B-Instruct]

Seeds:   0%|          | 0/3 [00:07<?, ?it/s, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.07s/it, seed=42]

Seeds:  33%|███▎      | 1/3 [00:07<00:14,  7.07s/it, seed=123]

anes Qwen2.5-7B-Instruct label_diversity 42 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 552.50it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1553.62it/s, est. speed input: 1904145.48 toks/s, output: 1554.36 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 556.50it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2459.97it/s, est. speed input: 3016820.49 toks/s, output: 2462.61 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.58it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 552.43it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2526.32it/s, est. speed input: 3098264.48 toks/s, output: 2529.10 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:05,  1.58it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 544.36it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2512.12it/s, est. speed input: 3080792.44 toks/s, output: 2514.83 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:01<00:04,  1.57it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 560.45it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2543.29it/s, est. speed input: 3119019.01 toks/s, output: 2546.01 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:03,  1.57it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 545.51it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2581.70it/s, est. speed input: 3166390.31 toks/s, output: 2584.70 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.57it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 560.09it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2517.20it/s, est. speed input: 3087048.87 toks/s, output: 2519.94 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:03<00:02,  1.58it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 557.40it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2583.83it/s, est. speed input: 3168811.82 toks/s, output: 2586.67 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.58it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 570.48it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2581.36it/s, est. speed input: 3165883.05 toks/s, output: 2584.29 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.58it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 554.33it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2553.01it/s, est. speed input: 3130964.54 toks/s, output: 2555.78 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:05<00:00,  1.58it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 552.49it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2596.20it/s, est. speed input: 3184010.86 toks/s, output: 2599.09 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.58it/s, feature=VCF9202_-90]






Datasets:  75%|███████▌  | 3/4 [11:55<03:02, 182.44s/it, dataset=anes]bel_diversity, model=Qwen2.5-7B-Instruct]

Seeds:  33%|███▎      | 1/3 [00:14<00:14,  7.07s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.09s/it, seed=123]

Seeds:  67%|██████▋   | 2/3 [00:14<00:07,  7.09s/it, seed=456]

anes Qwen2.5-7B-Instruct label_diversity 123 pi_behav done

Adding requests: 100%|██████████| 200/200 [00:00<00:00, 556.02it/s]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 1562.96it/s, est. speed input: 1915585.75 toks/s, output: 1563.70 toks/s]



Features (LOO ablation):   0%|          | 0/10 [00:00<?, ?it/s]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 541.08it/s]ture=VCF0301_40]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2511.06it/s, est. speed input: 3079518.36 toks/s, output: 2513.79 toks/s]



Features (LOO ablation):  10%|█         | 1/10 [00:00<00:05,  1.56it/s, feature=VCF0301_40]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 265.59it/s]t/s, feature=VCF0606_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2424.98it/s, est. speed input: 2974003.57 toks/s, output: 2427.67 toks/s]



Features (LOO ablation):  20%|██        | 2/10 [00:01<00:06,  1.15it/s, feature=VCF0606_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 560.63it/s]t/s, feature=VCF0717_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2568.37it/s, est. speed input: 3150006.22 toks/s, output: 2571.32 toks/s]



Features (LOO ablation):  30%|███       | 3/10 [00:02<00:05,  1.31it/s, feature=VCF0717_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 565.00it/s]t/s, feature=VCF0717_20]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2480.18it/s, est. speed input: 3041635.77 toks/s, output: 2482.87 toks/s]



Features (LOO ablation):  40%|████      | 4/10 [00:02<00:04,  1.41it/s, feature=VCF0717_20]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 562.91it/s]t/s, feature=VCF0718_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2492.44it/s, est. speed input: 3056790.98 toks/s, output: 2495.24 toks/s]



Features (LOO ablation):  50%|█████     | 5/10 [00:03<00:03,  1.47it/s, feature=VCF0718_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 557.63it/s]t/s, feature=VCF0720_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2528.17it/s, est. speed input: 3100479.97 toks/s, output: 2530.89 toks/s]



Features (LOO ablation):  60%|██████    | 6/10 [00:04<00:02,  1.50it/s, feature=VCF0720_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 571.05it/s]t/s, feature=VCF0721_00]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2498.36it/s, est. speed input: 3063973.07 toks/s, output: 2501.10 toks/s]



Features (LOO ablation):  70%|███████   | 7/10 [00:04<00:01,  1.53it/s, feature=VCF0721_00]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 550.23it/s]t/s, feature=VCF0803_90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2578.12it/s, est. speed input: 3161821.02 toks/s, output: 2580.97 toks/s]



Features (LOO ablation):  80%|████████  | 8/10 [00:05<00:01,  1.55it/s, feature=VCF0803_90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 549.25it/s]t/s, feature=VCF9201_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2560.89it/s, est. speed input: 3140667.68 toks/s, output: 2563.71 toks/s]



Features (LOO ablation):  90%|█████████ | 9/10 [00:06<00:00,  1.55it/s, feature=VCF9201_-90]


Adding requests: 100%|██████████| 200/200 [00:00<00:00, 559.98it/s]t/s, feature=VCF9202_-90]
Processed prompts: 100%|██████████| 200/200 [00:00<00:00, 2539.55it/s, est. speed input: 3114547.57 toks/s, output: 2542.39 toks/s]



Features (LOO ablation): 100%|██████████| 10/10 [00:06<00:00,  1.56it/s, feature=VCF9202_-90]






Datasets:  75%|███████▌  | 3/4 [12:03<03:02, 182.44s/it, dataset=anes]bel_diversity, model=Qwen2.5-7B-Instruct]

Seeds:  67%|██████▋   | 2/3 [00:21<00:07,  7.09s/it, seed=456]

Seeds: 100%|██████████| 3/3 [00:21<00:00,  7.27s/it, seed=456]


Conditions: 100%|██████████| 2/2 [00:43<00:00, 21.84s/it, condition=label_diversity, model=Qwen2.5-7B-Instruct]

anes Qwen2.5-7B-Instruct label_diversity 456 pi_behav done

[rank0]:[W905 14:35:32.075523414 ProcessGroupNCCL.cpp:1538] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Datasets: 100%|██████████| 4/4 [12:05<00:00, 181.33s/it, dataset=anes]

## Step 3: Spearman rho with bootstrap CIs

ρ(π_self, π_behav) is the headline faithfulness number: a **high** ρ means the model relies on the features it *claims* to rely on (self-report and behaviour agree on ranking); a **low or negative** ρ means the model's stated rationale diverges from what actually drives its predictions — exactly the STaDS-style global unfaithfulness result (Li et al. 2025) this evaluation is designed to detect. Bootstrap CIs (resampling the 200 test rows) give a sense of how much ρ could plausibly vary under a different sample of the same OOD-test distribution, which matters for comparing ρ across conditions (random vs. best-protocol) without over-interpreting small differences.

In [4]:
from src.evaluation.faithfulness import spearman_with_bootstrap

rho_rows = []
for (dataset_name, model_name, condition, seed), deltas in delta_store.items():
    pi_self = pi_self_store[(dataset_name, model_name)]
    per_row_correct = per_row_correct_store[(dataset_name, model_name, condition, seed)]
    result = spearman_with_bootstrap(pi_self, deltas, per_row_correct, n_bootstrap=1000, seed=seed)
    rho_rows.append({
        'dataset': dataset_name, 'model': model_name, 'method': condition, 'seed': int(seed),
        **result,
    })

RHO_PER_SEED_COLS = ['dataset', 'model', 'method', 'seed', 'rho', 'pval', 'ci_low', 'ci_high']
rho_per_seed = pd.DataFrame(rho_rows, columns=RHO_PER_SEED_COLS)

if rho_per_seed.empty:
    print("No faithfulness results yet — skipped (vLLM not available in this environment).")
    rho_summary = pd.DataFrame(columns=['dataset', 'model', 'method', 'rho_mean', 'rho_std', 'ci_low_mean', 'ci_high_mean'])
else:
    # rho +/- CI per (dataset, model, condition): mean/std of the per-seed point
    # estimates, plus the mean of each seed's own bootstrap CI bounds.
    rho_summary = rho_per_seed.groupby(['dataset', 'model', 'method']).agg(
        rho_mean=('rho', 'mean'),
        rho_std=('rho', 'std'),
        ci_low_mean=('ci_low', 'mean'),
        ci_high_mean=('ci_high', 'mean'),
    ).reset_index()

rho_summary

,dataset,model,method,rho_mean,rho_std,ci_low_mean,ci_high_mean
0,acsincome,Llama-3.1-8B-Instruct,label_diversity,0.563636,0.000000,0.563636,0.563636
1,acsincome,Llama-3.1-8B-Instruct,random,0.563636,0.000000,0.563636,0.563636
2,acsincome,Qwen2.5-7B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
3,acsincome,Qwen2.5-7B-Instruct,random,1.000000,0.000000,1.000000,1.000000
4,acspubcov,Llama-3.1-8B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
5,acspubcov,Llama-3.1-8B-Instruct,random,1.000000,0.000000,1.000000,1.000000
6,acspubcov,Qwen2.5-7B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
7,acspubcov,Qwen2.5-7B-Instruct,random,1.000000,0.000000,1.000000,1.000000
8,anes,Llama-3.1-8B-Instruct,label_diversity,0.454545,0.267492,-0.155556,0.749495
9,anes,Llama-3.1-8B-Instruct,random,0.236364,0.515544,0.260606,0.830303
10,anes,Qwen2.5-7B-Instruct,label_diversity,0.785859,0.272750,0.115152,0.834343
11,anes,Qwen2.5-7B-Instruct,random,0.260606,0.751808,0.595960,0.963636
12,brfss_diabetes,Llama-3.1-8B-Instruct,label_diversity,-0.212121,0.000000,-0.212121,-0.212121
13,brfss_diabetes,Llama-3.1-8B-Instruct,random,-0.212121,0.000000,-0.212121,-0.212121
14,brfss_diabetes,Qwen2.5-7B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
15,brfss_diabetes,Qwen2.5-7B-Instruct,random,1.000000,0.000000,1.000000,1.000000

In [5]:
FAITHFULNESS_COLS = ['dataset', 'model', 'method', 'seed', 'feature', 'delta']
faithfulness_df = pd.DataFrame(faithfulness_rows, columns=FAITHFULNESS_COLS)
faithfulness_df.to_parquet(resolve_path('results/faithfulness_real.parquet'), index=False)
rho_per_seed.to_parquet(resolve_path('results/faithfulness_real_rho_per_seed.parquet'), index=False)
rho_summary.to_parquet(resolve_path('results/faithfulness_real_rho_summary.parquet'), index=False)

print(f"faithfulness_real.parquet: {len(faithfulness_df)} rows")
rho_summary

faithfulness_real.parquet: 480 rows

,dataset,model,method,rho_mean,rho_std,ci_low_mean,ci_high_mean
0,acsincome,Llama-3.1-8B-Instruct,label_diversity,0.563636,0.000000,0.563636,0.563636
1,acsincome,Llama-3.1-8B-Instruct,random,0.563636,0.000000,0.563636,0.563636
2,acsincome,Qwen2.5-7B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
3,acsincome,Qwen2.5-7B-Instruct,random,1.000000,0.000000,1.000000,1.000000
4,acspubcov,Llama-3.1-8B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
5,acspubcov,Llama-3.1-8B-Instruct,random,1.000000,0.000000,1.000000,1.000000
6,acspubcov,Qwen2.5-7B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
7,acspubcov,Qwen2.5-7B-Instruct,random,1.000000,0.000000,1.000000,1.000000
8,anes,Llama-3.1-8B-Instruct,label_diversity,0.454545,0.267492,-0.155556,0.749495
9,anes,Llama-3.1-8B-Instruct,random,0.236364,0.515544,0.260606,0.830303
10,anes,Qwen2.5-7B-Instruct,label_diversity,0.785859,0.272750,0.115152,0.834343
11,anes,Qwen2.5-7B-Instruct,random,0.260606,0.751808,0.595960,0.963636
12,brfss_diabetes,Llama-3.1-8B-Instruct,label_diversity,-0.212121,0.000000,-0.212121,-0.212121
13,brfss_diabetes,Llama-3.1-8B-Instruct,random,-0.212121,0.000000,-0.212121,-0.212121
14,brfss_diabetes,Qwen2.5-7B-Instruct,label_diversity,1.000000,0.000000,1.000000,1.000000
15,brfss_diabetes,Qwen2.5-7B-Instruct,random,1.000000,0.000000,1.000000,1.000000

## Compute budget

Per condition: 200 rows x ~12 features x 1 forward pass = 2,400 calls. 3 conditions x 3 seeds x 3 datasets x 2 models ~= 130,000 calls.

## Output

- `results/faithfulness_real.parquet` (one row per feature per condition per dataset per seed)
- Summary: rho +/- CI per (dataset, model, condition)