# Notebook 05: SATA Architecture and Training

**Purpose**: Define, train, and validate SATA on synthetic tasks.

**Gate 2 (end of Week 5)**: does SATA top-k selection beat the best protocol and random selection on validation tasks (XGBoost proxy accuracy)? If not, RQ4 becomes a rigorous negative result — document why and pivot to ablation analysis.

## What SATA is — and, explicitly, what it is not

This is worth stating plainly because it was genuinely unclear during the literature-review stage (see the margin questions in `Lit-review.pdf` around §2.4.1): **SATA never predicts a label.** It has no classification head, is never shown a label to predict, and its output is not a prediction — it's a set of relevance *scores* over the demo pool. The frozen base LLM (Llama-3.1-8B / Qwen2.5-7B) is the only thing in this whole pipeline that ever classifies anything, via ordinary text-serialised ICL (Notebook 01/02). SATA's entire job is choosing *which* rows from the pool get serialised into that LLM's prompt, and in what order of relevance.

This makes SATA architecturally unlike **TabPFN** (Hollmann et al.) — TabPFN *is* the classifier, trained end-to-end to map a support set + query directly to a label in one forward pass. It's also unlike simply "training a pretrained LLM further" — that would still leave the model doing its own classification, just with different weights, and would break the "frozen base model" premise the whole faithfulness evaluation (Notebook 03) depends on. SATA is a small, separately-trained **demonstration selector** that sits *upstream* of an unmodified frozen LLM.

## Where the architecture comes from

SATA's design is adapted from **In-Context Risk Minimization / "Context is environment"** (Gupta, Jegelka, Lopez-Paz & Ahuja, 2023, Lit-review §3 ref [31]) — the finding that a transformer attending over contextual examples *at inference time* can learn to extract environment-specific representations that improve OOD generalisation, without touching the base predictor's weights. SATA specialises this idea to the tabular ICL setting: instead of learning environment representations for a downstream classifier it owns, SATA learns to score *which demonstrations* would make the environment/regime legible to a downstream classifier (here, the frozen LLM) that it doesn't own or modify.

Concretely, per `src/models/sata.py`: demo features + demo labels get embedded together (`feature_embed(demo_features) + label_embed(demo_labels)`), the query gets embedded from its features alone (it has no label yet — that's what's being predicted), all tokens go through a small transformer encoder with self-attention (so every demo's relevance can depend on every other demo *and* on the query), and a scoring head converts each demo position's output into a single relevance logit. A softmax over demo positions turns those logits into a probability distribution — the top-k highest-probability demos are what get serialised into the LLM's prompt in Notebook 06.

**Why query-conditioned, specifically?** This is SATA's core empirical bet, and it's what the query-agnostic ablation (below) exists to test in isolation. Goddard et al.'s (2025) task-diversity result (Lit-review §2.3.1) shows ICL-like systems undergo a sharp phase transition from "solutions specialised to pretraining-like tasks" to "solutions that generalise across the task space" once pretraining task diversity crosses a threshold. That's a lever at *training* time. SATA's hypothesis is that an analogous lever exists at *inference* time: if which demonstrations are relevant genuinely depends on the specific query (not just the task in the abstract), a selector that conditions its scores on the query should transfer better across environments than one that scores the pool once and reuses the same ranking for every query in a task.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.config import load_config, set_seed, resolve_path

config = load_config()
set_seed(config.seed_accuracy[0])

## Architecture

See `src/models/sata.py::SATA` and `SATAQueryAgnostic` (ablation: masks the query token so scores don't depend on query identity).

`SATA.forward(demo_features, demo_labels, query_features) -> scores` where `scores` has shape `(batch, n_demos)` and sums to 1 (softmax over demo positions). `SATAQueryAgnostic` overrides `forward` to zero out the query before the parent's logic runs — everything else (embeddings, transformer, scoring head) is identical, so any accuracy difference between the two models isolates the effect of query-conditioning specifically, not some other architectural change. See the intro above for why that isolation is the point of this ablation.

In [2]:
from src.models.sata import SATA, SATAQueryAgnostic

model = SATA(
    n_features=config.generator.n_features,
    d_model=config.sata.d_model,
    n_heads=config.sata.n_heads,
    n_layers=config.sata.n_layers,
)
model

SATA(
  (feature_embed): Linear(in_features=10, out_features=128, bias=True)
  (label_embed): Embedding(2, 128)
  (transformer): TransformerEncoder(
    (layers): ModuleList(
      (0-3): 4 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=128, out_features=128, bias=True)
        )
        (linear1): Linear(in_features=128, out_features=512, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=512, out_features=128, bias=True)
        (norm1): LayerNorm((128,), eps=1e-05, elementwise_affine=True, bias=True)
        (norm2): LayerNorm((128,), eps=1e-05, elementwise_affine=True, bias=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
    )
  )
  (score_head): Linear(in_features=128, out_features=1, bias=True)
)

## Target score computation

See `src/models/sata_targets.py::compute_target_scores` — high weight for same-regime and counter-spurious demos, mild bonus for label match, near-zero for spurious-only demos from irrelevant regimes.

**This is SATA's supervision signal, and it's deliberately not "does the demo have the same label as the query."** A demo that merely shares the query's label but comes from an unrelated regime, or agrees with the query only via the spurious feature, is exactly the kind of demonstration that would teach the frozen LLM a shortcut rather than the task's real structure — the same failure mode Section 2.2 of the lit review documents at the model level. Weighting by **same regime** (does this demo sit in the same decision-rule leaf/branch as the query?) rewards structural relevance: a demo from the query's own region of the input space is informative about the local decision boundary regardless of whether its label happens to match. Weighting by **counter-spurious** (does this demo's spurious-feature value disagree with its label?) is the training-time analogue of Notebook 02's counter-spurious diversity protocol — it directly rewards demonstrations that *can't* be explained by the shortcut. The label-match term is kept deliberately mild (`+0.5`, vs. `+2.0` for regime and `+1.5` for counter-spurious) so SATA doesn't degenerate into a label-matching heuristic, which per Min et al. (2022, Lit-review §2.6.1) isn't even what drives ICL performance in the first place.

## Training loop

See `src/models/sata_train.py::train_sata` (KL-divergence loss) and `evaluate_sata_proxy` (XGBoost proxy validation, no LLM calls).

**Why KL divergence, not cross-entropy against a single "correct" demo?** SATA's target (above) is a full probability distribution over the demo pool, not a one-hot label — several demos can be simultaneously relevant. KL divergence trains SATA's predicted distribution to match that target distribution's *shape*, not just to spike on one "best" demo, which is the right objective when the supervision itself is graded relevance rather than a single ground-truth choice.

**Why validate with an XGBoost proxy instead of the frozen LLM?** Running the actual frozen LLM once per validation task per epoch would be prohibitively slow and expensive — validation needs to run every epoch, for potentially 50 epochs, just to pick the best checkpoint. `evaluate_sata_proxy` substitutes a cheap, deterministic stand-in: fit an XGBoost classifier on SATA's top-k selected demos, then check whether it predicts the query correctly. This isn't a claim that XGBoost behaves like the LLM — it's a fast, LLM-free signal for "did SATA select demos that are informative about the query's regime," which is exactly the property SATA's training target was built to reward. The real test of whether this transfers to the frozen LLM happens downstream in Notebook 06, which does use the actual LLM.

**Early stopping and crash resume.** The loop originally always ran the full `sata.epochs` (50) regardless of how val_proxy behaved — on the first real run, val_proxy peaked at epoch 0 and never recovered through epoch 35+, meaning most of a ~5-hour run was spent on epochs that never improved the checkpoint actually used downstream. `train_sata` now stops once `sata.patience` (10) epochs pass with no val_proxy improvement over the best seen so far; 10 is deliberately mild given val_proxy is a somewhat noisy proxy metric (a point or two of movement between consecutive epochs on its own), so a short patience risks stopping on noise rather than a genuine plateau. Separately, a multi-hour run that gets interrupted (kernel killed, walltime hit, OnDemand connection dropped — this happened mid-run once already) previously had no way to resume; it restarted from epoch 0 every time. `train_sata` now also takes a `resume_checkpoint_path`: full training state (model + optimizer, current epoch, best-so-far bookkeeping, log-so-far) is written there after every epoch, and automatically loaded from if the file already exists, so an interrupted run picks up at the next epoch instead of redoing everything. That file is deleted automatically once training actually finishes (full epoch budget or early stop) so a later *intentional* fresh run (e.g. after changing hyperparameters) doesn't silently inherit stale state — delete it manually only if you need to abandon an in-progress run and start over.

In [3]:
import json
from types import SimpleNamespace

import numpy as np
import pandas as pd

from src.data.generator import SyntheticTask
from src.models.sata_train import train_sata, evaluate_sata_proxy

# train_sata/evaluate_sata_proxy read config.lr/.epochs/.max_demos/... (the `sata`
# block) *and* config.environments (the `generator` block) -- merge them so a
# single namespace satisfies both.
sata_cfg = SimpleNamespace(**vars(config.sata), environments=config.generator.environments)

SYN_ROOT = resolve_path(config.paths.data_synthetic)
gen_meta = json.load(open(SYN_ROOT / 'generator_config.json'))
if not gen_meta.get('frozen', False):
    print(f"Warning: generator gate not passed (pass_rate={gen_meta['gate_pass_rate']:.0%}) — "
          "training against Notebook 04's provisional data. Re-run Notebook 04 once it's frozen "
          "before treating anything downstream of this as a final result.")


def load_task_suite(group_dir):
    tasks = []
    for meta_path in sorted(Path(group_dir).glob('*_meta.json')):
        meta = json.load(open(meta_path))
        tasks.append(SyntheticTask(
            task_id=meta['task_id'],
            rule_family=meta['rule_family'],
            causal_features=meta['causal_features'],
            coefficients=np.array(meta['coefficients']),
            spurious_strength=meta['spurious_strength'],
            n_features=config.generator.n_features,
            label_noise=config.generator.label_noise,
            threshold=meta['threshold'],
            # 'threshold'/'tree' families only (see src/data/generator.py);
            # None for 'linear'/'sparse_interaction', which is what
            # SyntheticTask's defaults already are.
            thresholds3=meta.get('thresholds3'),
            leaf_labels=meta.get('leaf_labels'),
        ))
    return tasks


train_tasks = load_task_suite(SYN_ROOT / 'tasks_train')
val_tasks = load_task_suite(SYN_ROOT / 'tasks_val')
print(f"Loaded {len(train_tasks)} train tasks, {len(val_tasks)} val tasks")

resolve_path('models').mkdir(parents=True, exist_ok=True)
# resume_checkpoint_path: if this file already exists (e.g. the kernel died
# or lost its connection partway through a multi-hour run), train_sata picks
# back up at the next epoch instead of restarting from epoch 0 -- delete the
# file first if you deliberately want a fresh run. Separate from
# checkpoint_path, which stays a bare state_dict for downstream loading.
log = train_sata(
    model, train_tasks, val_tasks, sata_cfg,
    checkpoint_path=resolve_path('models/sata_best.pt'),
    resume_checkpoint_path=resolve_path('models/sata_best_resume.pt'),
)
training_log_df = pd.DataFrame(log)
training_log_df['model'] = 'sata'
training_log_df

Loaded 2000 train tasks, 200 val tasks

Resumed from /root/repo/sata-project/models/sata_best_resume.pt: starting at epoch 4, best_val_score=0.9578 (epoch 0)

Epoch 4:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 4:   0%|          | 1/2000 [00:00<15:47,  2.11it/s]

Epoch 4:   0%|          | 3/2000 [00:00<05:25,  6.14it/s]

Epoch 4:   0%|          | 5/2000 [00:00<03:33,  9.36it/s]

Epoch 4:   0%|          | 7/2000 [00:00<02:48, 11.84it/s]

Epoch 4:   0%|          | 9/2000 [00:00<02:25, 13.71it/s]

Epoch 4:   1%|          | 11/2000 [00:01<02:11, 15.10it/s]

Epoch 4:   1%|          | 13/2000 [00:01<02:03, 16.10it/s]

Epoch 4:   1%|          | 15/2000 [00:01<01:57, 16.83it/s]

Epoch 4:   1%|          | 17/2000 [00:01<01:54, 17.35it/s]

Epoch 4:   1%|          | 19/2000 [00:01<01:51, 17.72it/s]

Epoch 4:   1%|          | 21/2000 [00:01<01:49, 18.00it/s]

Epoch 4:   1%|          | 23/2000 [00:01<01:48, 18.16it/s]

Epoch 4:   1%|▏         | 25/2000 [00:01<01:47, 18.29it/s]

Epoch 4:   1%|▏         | 27/2000 [00:01<01:47, 18.37it/s]

Epoch 4:   1%|▏         | 29/2000 [00:01<01:46, 18.43it/s]

Epoch 4:   2%|▏         | 31/2000 [00:02<01:46, 18.47it/s]

Epoch 4:   2%|▏         | 33/2000 [00:02<01:46, 18.50it/s]

Epoch 4:   2%|▏         | 35/2000 [00:02<01:46, 18.52it/s]

Epoch 4:   2%|▏         | 37/2000 [00:02<01:45, 18.53it/s]

Epoch 4:   2%|▏         | 39/2000 [00:02<01:45, 18.53it/s]

Epoch 4:   2%|▏         | 41/2000 [00:02<01:45, 18.55it/s]

Epoch 4:   2%|▏         | 43/2000 [00:02<01:45, 18.56it/s]

Epoch 4:   2%|▏         | 45/2000 [00:02<01:45, 18.57it/s]

Epoch 4:   2%|▏         | 47/2000 [00:02<01:45, 18.58it/s]

Epoch 4:   2%|▏         | 49/2000 [00:03<01:44, 18.58it/s]

Epoch 4:   3%|▎         | 51/2000 [00:03<01:45, 18.49it/s]

Epoch 4:   3%|▎         | 53/2000 [00:03<01:45, 18.49it/s]

Epoch 4:   3%|▎         | 55/2000 [00:03<01:45, 18.51it/s]

Epoch 4:   3%|▎         | 57/2000 [00:03<01:44, 18.52it/s]

Epoch 4:   3%|▎         | 59/2000 [00:03<01:44, 18.55it/s]

Epoch 4:   3%|▎         | 61/2000 [00:03<01:44, 18.56it/s]

Epoch 4:   3%|▎         | 63/2000 [00:03<01:44, 18.57it/s]

Epoch 4:   3%|▎         | 65/2000 [00:03<01:44, 18.56it/s]

Epoch 4:   3%|▎         | 67/2000 [00:04<01:44, 18.56it/s]

Epoch 4:   3%|▎         | 69/2000 [00:04<01:43, 18.57it/s]

Epoch 4:   4%|▎         | 71/2000 [00:04<01:43, 18.58it/s]

Epoch 4:   4%|▎         | 73/2000 [00:04<01:43, 18.58it/s]

Epoch 4:   4%|▍         | 75/2000 [00:04<01:43, 18.59it/s]

Epoch 4:   4%|▍         | 77/2000 [00:04<01:43, 18.59it/s]

Epoch 4:   4%|▍         | 79/2000 [00:04<01:43, 18.59it/s]

Epoch 4:   4%|▍         | 81/2000 [00:04<01:43, 18.59it/s]

Epoch 4:   4%|▍         | 83/2000 [00:04<01:43, 18.59it/s]

Epoch 4:   4%|▍         | 85/2000 [00:04<01:42, 18.59it/s]

Epoch 4:   4%|▍         | 87/2000 [00:05<01:42, 18.60it/s]

Epoch 4:   4%|▍         | 89/2000 [00:05<01:42, 18.59it/s]

Epoch 4:   5%|▍         | 91/2000 [00:05<01:42, 18.59it/s]

Epoch 4:   5%|▍         | 93/2000 [00:05<01:42, 18.59it/s]

Epoch 4:   5%|▍         | 95/2000 [00:05<01:42, 18.59it/s]

Epoch 4:   5%|▍         | 97/2000 [00:05<01:42, 18.59it/s]

Epoch 4:   5%|▍         | 99/2000 [00:05<01:42, 18.58it/s]

Epoch 4:   5%|▌         | 101/2000 [00:05<01:42, 18.58it/s]

Epoch 4:   5%|▌         | 103/2000 [00:05<01:42, 18.58it/s]

Epoch 4:   5%|▌         | 105/2000 [00:06<01:41, 18.58it/s]

Epoch 4:   5%|▌         | 107/2000 [00:06<01:41, 18.59it/s]

Epoch 4:   5%|▌         | 109/2000 [00:06<01:41, 18.59it/s]

Epoch 4:   6%|▌         | 111/2000 [00:06<01:41, 18.60it/s]

Epoch 4:   6%|▌         | 113/2000 [00:06<01:41, 18.61it/s]

Epoch 4:   6%|▌         | 115/2000 [00:06<01:41, 18.61it/s]

Epoch 4:   6%|▌         | 117/2000 [00:06<01:41, 18.62it/s]

Epoch 4:   6%|▌         | 119/2000 [00:06<01:41, 18.60it/s]

Epoch 4:   6%|▌         | 121/2000 [00:06<01:42, 18.38it/s]

Epoch 4:   6%|▌         | 123/2000 [00:07<01:41, 18.43it/s]

Epoch 4:   6%|▋         | 125/2000 [00:07<01:41, 18.46it/s]

Epoch 4:   6%|▋         | 127/2000 [00:07<01:41, 18.47it/s]

Epoch 4:   6%|▋         | 129/2000 [00:07<01:41, 18.52it/s]

Epoch 4:   7%|▋         | 131/2000 [00:07<01:40, 18.54it/s]

Epoch 4:   7%|▋         | 133/2000 [00:07<01:40, 18.56it/s]

Epoch 4:   7%|▋         | 135/2000 [00:07<01:40, 18.59it/s]

Epoch 4:   7%|▋         | 137/2000 [00:07<01:40, 18.60it/s]

Epoch 4:   7%|▋         | 139/2000 [00:07<01:40, 18.59it/s]

Epoch 4:   7%|▋         | 141/2000 [00:08<01:39, 18.61it/s]

Epoch 4:   7%|▋         | 143/2000 [00:08<01:39, 18.61it/s]

Epoch 4:   7%|▋         | 145/2000 [00:08<01:39, 18.63it/s]

Epoch 4:   7%|▋         | 147/2000 [00:08<01:39, 18.65it/s]

Epoch 4:   7%|▋         | 149/2000 [00:08<01:39, 18.66it/s]

Epoch 4:   8%|▊         | 151/2000 [00:08<01:39, 18.65it/s]

Epoch 4:   8%|▊         | 153/2000 [00:08<01:39, 18.65it/s]

Epoch 4:   8%|▊         | 155/2000 [00:08<01:38, 18.64it/s]

Epoch 4:   8%|▊         | 157/2000 [00:08<01:38, 18.65it/s]

Epoch 4:   8%|▊         | 159/2000 [00:08<01:38, 18.65it/s]

Epoch 4:   8%|▊         | 161/2000 [00:09<01:39, 18.46it/s]

Epoch 4:   8%|▊         | 163/2000 [00:09<01:39, 18.52it/s]

Epoch 4:   8%|▊         | 165/2000 [00:09<01:38, 18.56it/s]

Epoch 4:   8%|▊         | 167/2000 [00:09<01:38, 18.59it/s]

Epoch 4:   8%|▊         | 169/2000 [00:09<01:38, 18.62it/s]

Epoch 4:   9%|▊         | 171/2000 [00:09<01:38, 18.62it/s]

Epoch 4:   9%|▊         | 173/2000 [00:09<01:37, 18.64it/s]

Epoch 4:   9%|▉         | 175/2000 [00:09<01:37, 18.67it/s]

Epoch 4:   9%|▉         | 177/2000 [00:09<01:37, 18.68it/s]

Epoch 4:   9%|▉         | 179/2000 [00:10<01:37, 18.68it/s]

Epoch 4:   9%|▉         | 181/2000 [00:10<01:37, 18.67it/s]

Epoch 4:   9%|▉         | 183/2000 [00:10<01:37, 18.68it/s]

Epoch 4:   9%|▉         | 185/2000 [00:10<01:37, 18.68it/s]

Epoch 4:   9%|▉         | 187/2000 [00:10<01:37, 18.68it/s]

Epoch 4:   9%|▉         | 189/2000 [00:10<01:36, 18.70it/s]

Epoch 4:  10%|▉         | 191/2000 [00:10<01:36, 18.71it/s]

Epoch 4:  10%|▉         | 193/2000 [00:10<01:36, 18.72it/s]

Epoch 4:  10%|▉         | 195/2000 [00:10<01:36, 18.71it/s]

Epoch 4:  10%|▉         | 197/2000 [00:11<01:36, 18.70it/s]

Epoch 4:  10%|▉         | 199/2000 [00:11<01:36, 18.69it/s]

Epoch 4:  10%|█         | 201/2000 [00:11<01:36, 18.68it/s]

Epoch 4:  10%|█         | 203/2000 [00:11<01:36, 18.68it/s]

Epoch 4:  10%|█         | 205/2000 [00:11<01:36, 18.67it/s]

Epoch 4:  10%|█         | 207/2000 [00:11<01:36, 18.68it/s]

Epoch 4:  10%|█         | 209/2000 [00:11<01:35, 18.67it/s]

Epoch 4:  11%|█         | 211/2000 [00:11<01:35, 18.70it/s]

Epoch 4:  11%|█         | 213/2000 [00:11<01:35, 18.69it/s]

Epoch 4:  11%|█         | 215/2000 [00:11<01:35, 18.70it/s]

Epoch 4:  11%|█         | 217/2000 [00:12<01:35, 18.70it/s]

Epoch 4:  11%|█         | 219/2000 [00:12<01:35, 18.69it/s]

Epoch 4:  11%|█         | 221/2000 [00:12<01:35, 18.68it/s]

Epoch 4:  11%|█         | 223/2000 [00:12<01:35, 18.69it/s]

Epoch 4:  11%|█▏        | 225/2000 [00:12<01:34, 18.69it/s]

Epoch 4:  11%|█▏        | 227/2000 [00:12<01:34, 18.69it/s]

Epoch 4:  11%|█▏        | 229/2000 [00:12<01:34, 18.69it/s]

Epoch 4:  12%|█▏        | 231/2000 [00:12<01:34, 18.68it/s]

Epoch 4:  12%|█▏        | 233/2000 [00:12<01:34, 18.65it/s]

Epoch 4:  12%|█▏        | 235/2000 [00:13<01:34, 18.66it/s]

Epoch 4:  12%|█▏        | 237/2000 [00:13<01:34, 18.67it/s]

Epoch 4:  12%|█▏        | 239/2000 [00:13<01:34, 18.68it/s]

Epoch 4:  12%|█▏        | 241/2000 [00:13<01:34, 18.69it/s]

Epoch 4:  12%|█▏        | 243/2000 [00:13<01:33, 18.70it/s]

Epoch 4:  12%|█▏        | 245/2000 [00:13<01:33, 18.71it/s]

Epoch 4:  12%|█▏        | 247/2000 [00:13<01:33, 18.71it/s]

Epoch 4:  12%|█▏        | 249/2000 [00:13<01:33, 18.72it/s]

Epoch 4:  13%|█▎        | 251/2000 [00:13<01:33, 18.71it/s]

Epoch 4:  13%|█▎        | 253/2000 [00:14<01:33, 18.70it/s]

Epoch 4:  13%|█▎        | 255/2000 [00:14<01:33, 18.66it/s]

Epoch 4:  13%|█▎        | 257/2000 [00:14<01:33, 18.66it/s]

Epoch 4:  13%|█▎        | 259/2000 [00:14<01:33, 18.65it/s]

Epoch 4:  13%|█▎        | 261/2000 [00:14<01:33, 18.64it/s]

Epoch 4:  13%|█▎        | 263/2000 [00:14<01:33, 18.58it/s]

Epoch 4:  13%|█▎        | 265/2000 [00:14<01:33, 18.56it/s]

Epoch 4:  13%|█▎        | 267/2000 [00:14<01:33, 18.58it/s]

Epoch 4:  13%|█▎        | 269/2000 [00:14<01:33, 18.58it/s]

Epoch 4:  14%|█▎        | 271/2000 [00:14<01:33, 18.59it/s]

Epoch 4:  14%|█▎        | 273/2000 [00:15<01:32, 18.60it/s]

Epoch 4:  14%|█▍        | 275/2000 [00:15<01:32, 18.61it/s]

Epoch 4:  14%|█▍        | 277/2000 [00:15<01:32, 18.61it/s]

Epoch 4:  14%|█▍        | 279/2000 [00:15<01:32, 18.61it/s]

Epoch 4:  14%|█▍        | 281/2000 [00:15<01:32, 18.62it/s]

Epoch 4:  14%|█▍        | 283/2000 [00:15<01:32, 18.61it/s]

Epoch 4:  14%|█▍        | 285/2000 [00:15<01:32, 18.62it/s]

Epoch 4:  14%|█▍        | 287/2000 [00:15<01:32, 18.61it/s]

Epoch 4:  14%|█▍        | 289/2000 [00:15<01:31, 18.62it/s]

Epoch 4:  15%|█▍        | 291/2000 [00:16<01:31, 18.61it/s]

Epoch 4:  15%|█▍        | 293/2000 [00:16<01:31, 18.61it/s]

Epoch 4:  15%|█▍        | 295/2000 [00:16<01:31, 18.61it/s]

Epoch 4:  15%|█▍        | 297/2000 [00:16<01:31, 18.60it/s]

Epoch 4:  15%|█▍        | 299/2000 [00:16<01:31, 18.60it/s]

Epoch 4:  15%|█▌        | 301/2000 [00:16<01:31, 18.60it/s]

Epoch 4:  15%|█▌        | 303/2000 [00:16<01:31, 18.60it/s]

Epoch 4:  15%|█▌        | 305/2000 [00:16<01:31, 18.61it/s]

Epoch 4:  15%|█▌        | 307/2000 [00:16<01:31, 18.60it/s]

Epoch 4:  15%|█▌        | 309/2000 [00:17<01:30, 18.60it/s]

Epoch 4:  16%|█▌        | 311/2000 [00:17<01:30, 18.60it/s]

Epoch 4:  16%|█▌        | 313/2000 [00:17<01:30, 18.61it/s]

Epoch 4:  16%|█▌        | 315/2000 [00:17<01:30, 18.62it/s]

Epoch 4:  16%|█▌        | 317/2000 [00:17<01:30, 18.63it/s]

Epoch 4:  16%|█▌        | 319/2000 [00:17<01:30, 18.62it/s]

Epoch 4:  16%|█▌        | 321/2000 [00:17<01:30, 18.63it/s]

Epoch 4:  16%|█▌        | 323/2000 [00:17<01:30, 18.53it/s]

Epoch 4:  16%|█▋        | 325/2000 [00:17<01:30, 18.54it/s]

Epoch 4:  16%|█▋        | 327/2000 [00:17<01:30, 18.55it/s]

Epoch 4:  16%|█▋        | 329/2000 [00:18<01:30, 18.56it/s]

Epoch 4:  17%|█▋        | 331/2000 [00:18<01:30, 18.46it/s]

Epoch 4:  17%|█▋        | 333/2000 [00:18<01:30, 18.47it/s]

Epoch 4:  17%|█▋        | 335/2000 [00:18<01:30, 18.48it/s]

Epoch 4:  17%|█▋        | 337/2000 [00:18<01:29, 18.50it/s]

Epoch 4:  17%|█▋        | 339/2000 [00:18<01:29, 18.53it/s]

Epoch 4:  17%|█▋        | 341/2000 [00:18<01:29, 18.55it/s]

Epoch 4:  17%|█▋        | 343/2000 [00:18<01:29, 18.55it/s]

Epoch 4:  17%|█▋        | 345/2000 [00:18<01:29, 18.56it/s]

Epoch 4:  17%|█▋        | 347/2000 [00:19<01:29, 18.57it/s]

Epoch 4:  17%|█▋        | 349/2000 [00:19<01:28, 18.57it/s]

Epoch 4:  18%|█▊        | 351/2000 [00:19<01:28, 18.56it/s]

Epoch 4:  18%|█▊        | 353/2000 [00:19<01:28, 18.56it/s]

Epoch 4:  18%|█▊        | 355/2000 [00:19<01:28, 18.56it/s]

Epoch 4:  18%|█▊        | 357/2000 [00:19<01:28, 18.56it/s]

Epoch 4:  18%|█▊        | 359/2000 [00:19<01:28, 18.55it/s]

Epoch 4:  18%|█▊        | 361/2000 [00:19<01:28, 18.56it/s]

Epoch 4:  18%|█▊        | 363/2000 [00:19<01:28, 18.55it/s]

Epoch 4:  18%|█▊        | 365/2000 [00:20<01:28, 18.56it/s]

Epoch 4:  18%|█▊        | 367/2000 [00:20<01:28, 18.55it/s]

Epoch 4:  18%|█▊        | 369/2000 [00:20<01:28, 18.44it/s]

Epoch 4:  19%|█▊        | 371/2000 [00:20<01:28, 18.47it/s]

Epoch 4:  19%|█▊        | 373/2000 [00:20<01:30, 18.01it/s]

Epoch 4:  19%|█▉        | 375/2000 [00:20<01:34, 17.25it/s]

Epoch 4:  19%|█▉        | 377/2000 [00:20<01:34, 17.13it/s]

Epoch 4:  19%|█▉        | 379/2000 [00:20<01:36, 16.78it/s]

Epoch 4:  19%|█▉        | 381/2000 [00:20<01:41, 16.02it/s]

Epoch 4:  19%|█▉        | 383/2000 [00:21<01:43, 15.57it/s]

Epoch 4:  19%|█▉        | 385/2000 [00:21<01:38, 16.37it/s]

Epoch 4:  19%|█▉        | 387/2000 [00:21<01:35, 16.98it/s]

Epoch 4:  19%|█▉        | 389/2000 [00:21<01:32, 17.43it/s]

Epoch 4:  20%|█▉        | 391/2000 [00:21<01:30, 17.77it/s]

Epoch 4:  20%|█▉        | 393/2000 [00:21<01:29, 18.02it/s]

Epoch 4:  20%|█▉        | 395/2000 [00:21<01:28, 18.20it/s]

Epoch 4:  20%|█▉        | 397/2000 [00:21<01:27, 18.30it/s]

Epoch 4:  20%|█▉        | 399/2000 [00:21<01:27, 18.39it/s]

Epoch 4:  20%|██        | 401/2000 [00:22<01:26, 18.46it/s]

Epoch 4:  20%|██        | 403/2000 [00:22<01:26, 18.50it/s]

Epoch 4:  20%|██        | 405/2000 [00:22<01:25, 18.55it/s]

Epoch 4:  20%|██        | 407/2000 [00:22<01:25, 18.55it/s]

Epoch 4:  20%|██        | 409/2000 [00:22<01:25, 18.58it/s]

Epoch 4:  21%|██        | 411/2000 [00:22<01:25, 18.59it/s]

Epoch 4:  21%|██        | 413/2000 [00:22<01:26, 18.37it/s]

Epoch 4:  21%|██        | 415/2000 [00:22<01:25, 18.45it/s]

Epoch 4:  21%|██        | 417/2000 [00:22<01:25, 18.50it/s]

Epoch 4:  21%|██        | 419/2000 [00:23<01:25, 18.55it/s]

Epoch 4:  21%|██        | 421/2000 [00:23<01:24, 18.58it/s]

Epoch 4:  21%|██        | 423/2000 [00:23<01:24, 18.59it/s]

Epoch 4:  21%|██▏       | 425/2000 [00:23<01:24, 18.61it/s]

Epoch 4:  21%|██▏       | 427/2000 [00:23<01:24, 18.61it/s]

Epoch 4:  21%|██▏       | 429/2000 [00:23<01:24, 18.61it/s]

Epoch 4:  22%|██▏       | 431/2000 [00:23<01:24, 18.61it/s]

Epoch 4:  22%|██▏       | 433/2000 [00:23<01:24, 18.61it/s]

Epoch 4:  22%|██▏       | 435/2000 [00:23<01:24, 18.61it/s]

Epoch 4:  22%|██▏       | 437/2000 [00:24<01:23, 18.61it/s]

Epoch 4:  22%|██▏       | 439/2000 [00:24<01:23, 18.62it/s]

Epoch 4:  22%|██▏       | 441/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  22%|██▏       | 443/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  22%|██▏       | 445/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  22%|██▏       | 447/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  22%|██▏       | 449/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  23%|██▎       | 451/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  23%|██▎       | 453/2000 [00:24<01:23, 18.63it/s]

Epoch 4:  23%|██▎       | 455/2000 [00:25<01:22, 18.63it/s]

Epoch 4:  23%|██▎       | 457/2000 [00:25<01:22, 18.63it/s]

Epoch 4:  23%|██▎       | 459/2000 [00:25<01:22, 18.64it/s]

Epoch 4:  23%|██▎       | 461/2000 [00:25<01:23, 18.43it/s]

Epoch 4:  23%|██▎       | 463/2000 [00:25<01:23, 18.49it/s]

Epoch 4:  23%|██▎       | 465/2000 [00:25<01:22, 18.54it/s]

Epoch 4:  23%|██▎       | 467/2000 [00:25<01:22, 18.58it/s]

Epoch 4:  23%|██▎       | 469/2000 [00:25<01:22, 18.60it/s]

Epoch 4:  24%|██▎       | 471/2000 [00:25<01:22, 18.61it/s]

Epoch 4:  24%|██▎       | 473/2000 [00:25<01:22, 18.62it/s]

Epoch 4:  24%|██▍       | 475/2000 [00:26<01:21, 18.63it/s]

Epoch 4:  24%|██▍       | 477/2000 [00:26<01:21, 18.63it/s]

Epoch 4:  24%|██▍       | 479/2000 [00:26<01:21, 18.63it/s]

Epoch 4:  24%|██▍       | 481/2000 [00:26<01:21, 18.63it/s]

Epoch 4:  24%|██▍       | 483/2000 [00:26<01:21, 18.64it/s]

Epoch 4:  24%|██▍       | 485/2000 [00:26<01:21, 18.64it/s]

Epoch 4:  24%|██▍       | 487/2000 [00:26<01:21, 18.65it/s]

Epoch 4:  24%|██▍       | 489/2000 [00:26<01:20, 18.66it/s]

Epoch 4:  25%|██▍       | 491/2000 [00:26<01:20, 18.65it/s]

Epoch 4:  25%|██▍       | 493/2000 [00:27<01:20, 18.65it/s]

Epoch 4:  25%|██▍       | 495/2000 [00:27<01:20, 18.64it/s]

Epoch 4:  25%|██▍       | 497/2000 [00:27<01:20, 18.64it/s]

Epoch 4:  25%|██▍       | 499/2000 [00:27<01:20, 18.63it/s]

Epoch 4:  25%|██▌       | 501/2000 [00:27<01:20, 18.65it/s]

Epoch 4:  25%|██▌       | 503/2000 [00:27<01:20, 18.65it/s]

Epoch 4:  25%|██▌       | 505/2000 [00:27<01:20, 18.66it/s]

Epoch 4:  25%|██▌       | 507/2000 [00:27<01:20, 18.66it/s]

Epoch 4:  25%|██▌       | 509/2000 [00:27<01:19, 18.66it/s]

Epoch 4:  26%|██▌       | 511/2000 [00:28<01:19, 18.65it/s]

Epoch 4:  26%|██▌       | 513/2000 [00:28<01:19, 18.66it/s]

Epoch 4:  26%|██▌       | 515/2000 [00:28<01:19, 18.66it/s]

Epoch 4:  26%|██▌       | 517/2000 [00:28<01:19, 18.65it/s]

Epoch 4:  26%|██▌       | 519/2000 [00:28<01:19, 18.65it/s]

Epoch 4:  26%|██▌       | 521/2000 [00:28<01:19, 18.65it/s]

Epoch 4:  26%|██▌       | 523/2000 [00:28<01:19, 18.65it/s]

Epoch 4:  26%|██▋       | 525/2000 [00:28<01:19, 18.64it/s]

Epoch 4:  26%|██▋       | 527/2000 [00:28<01:18, 18.65it/s]

Epoch 4:  26%|██▋       | 529/2000 [00:28<01:18, 18.64it/s]

Epoch 4:  27%|██▋       | 531/2000 [00:29<01:18, 18.63it/s]

Epoch 4:  27%|██▋       | 533/2000 [00:29<01:18, 18.61it/s]

Epoch 4:  27%|██▋       | 535/2000 [00:29<01:18, 18.63it/s]

Epoch 4:  27%|██▋       | 537/2000 [00:29<01:18, 18.64it/s]

Epoch 4:  27%|██▋       | 539/2000 [00:29<01:18, 18.64it/s]

Epoch 4:  27%|██▋       | 541/2000 [00:29<01:18, 18.65it/s]

Epoch 4:  27%|██▋       | 543/2000 [00:29<01:18, 18.66it/s]

Epoch 4:  27%|██▋       | 545/2000 [00:29<01:18, 18.65it/s]

Epoch 4:  27%|██▋       | 547/2000 [00:29<01:17, 18.65it/s]

Epoch 4:  27%|██▋       | 549/2000 [00:30<01:17, 18.65it/s]

Epoch 4:  28%|██▊       | 551/2000 [00:30<01:17, 18.64it/s]

Epoch 4:  28%|██▊       | 553/2000 [00:30<01:17, 18.65it/s]

Epoch 4:  28%|██▊       | 555/2000 [00:30<01:17, 18.65it/s]

Epoch 4:  28%|██▊       | 557/2000 [00:30<01:17, 18.63it/s]

Epoch 4:  28%|██▊       | 559/2000 [00:30<01:17, 18.63it/s]

Epoch 4:  28%|██▊       | 561/2000 [00:30<01:17, 18.64it/s]

Epoch 4:  28%|██▊       | 563/2000 [00:30<01:17, 18.63it/s]

Epoch 4:  28%|██▊       | 565/2000 [00:30<01:17, 18.63it/s]

Epoch 4:  28%|██▊       | 567/2000 [00:31<01:16, 18.63it/s]

Epoch 4:  28%|██▊       | 569/2000 [00:31<01:16, 18.63it/s]

Epoch 4:  29%|██▊       | 571/2000 [00:31<01:16, 18.63it/s]

Epoch 4:  29%|██▊       | 573/2000 [00:31<01:16, 18.62it/s]

Epoch 4:  29%|██▉       | 575/2000 [00:31<01:16, 18.64it/s]

Epoch 4:  29%|██▉       | 577/2000 [00:31<01:16, 18.63it/s]

Epoch 4:  29%|██▉       | 579/2000 [00:31<01:16, 18.63it/s]

Epoch 4:  29%|██▉       | 581/2000 [00:31<01:16, 18.61it/s]

Epoch 4:  29%|██▉       | 583/2000 [00:31<01:16, 18.62it/s]

Epoch 4:  29%|██▉       | 585/2000 [00:31<01:16, 18.61it/s]

Epoch 4:  29%|██▉       | 587/2000 [00:32<01:15, 18.63it/s]

Epoch 4:  29%|██▉       | 589/2000 [00:32<01:15, 18.62it/s]

Epoch 4:  30%|██▉       | 591/2000 [00:32<01:15, 18.62it/s]

Epoch 4:  30%|██▉       | 593/2000 [00:32<01:15, 18.63it/s]

Epoch 4:  30%|██▉       | 595/2000 [00:32<01:15, 18.63it/s]

Epoch 4:  30%|██▉       | 597/2000 [00:32<01:15, 18.64it/s]

Epoch 4:  30%|██▉       | 599/2000 [00:32<01:15, 18.59it/s]

Epoch 4:  30%|███       | 601/2000 [00:32<01:15, 18.62it/s]

Epoch 4:  30%|███       | 603/2000 [00:32<01:15, 18.62it/s]

Epoch 4:  30%|███       | 605/2000 [00:33<01:14, 18.61it/s]

Epoch 4:  30%|███       | 607/2000 [00:33<01:14, 18.63it/s]

Epoch 4:  30%|███       | 609/2000 [00:33<01:14, 18.62it/s]

Epoch 4:  31%|███       | 611/2000 [00:33<01:14, 18.65it/s]

Epoch 4:  31%|███       | 613/2000 [00:33<01:14, 18.68it/s]

Epoch 4:  31%|███       | 615/2000 [00:33<01:14, 18.70it/s]

Epoch 4:  31%|███       | 617/2000 [00:33<01:13, 18.71it/s]

Epoch 4:  31%|███       | 619/2000 [00:33<01:13, 18.71it/s]

Epoch 4:  31%|███       | 621/2000 [00:33<01:13, 18.71it/s]

Epoch 4:  31%|███       | 623/2000 [00:34<01:13, 18.73it/s]

Epoch 4:  31%|███▏      | 625/2000 [00:34<01:13, 18.74it/s]

Epoch 4:  31%|███▏      | 627/2000 [00:34<01:13, 18.74it/s]

Epoch 4:  31%|███▏      | 629/2000 [00:34<01:13, 18.73it/s]

Epoch 4:  32%|███▏      | 631/2000 [00:34<01:13, 18.74it/s]

Epoch 4:  32%|███▏      | 633/2000 [00:34<01:12, 18.75it/s]

Epoch 4:  32%|███▏      | 635/2000 [00:34<01:12, 18.75it/s]

Epoch 4:  32%|███▏      | 637/2000 [00:34<01:12, 18.74it/s]

Epoch 4:  32%|███▏      | 639/2000 [00:34<01:12, 18.75it/s]

Epoch 4:  32%|███▏      | 641/2000 [00:34<01:12, 18.74it/s]

Epoch 4:  32%|███▏      | 643/2000 [00:35<01:12, 18.73it/s]

Epoch 4:  32%|███▏      | 645/2000 [00:35<01:12, 18.73it/s]

Epoch 4:  32%|███▏      | 647/2000 [00:35<01:12, 18.74it/s]

Epoch 4:  32%|███▏      | 649/2000 [00:35<01:12, 18.75it/s]

Epoch 4:  33%|███▎      | 651/2000 [00:35<01:11, 18.75it/s]

Epoch 4:  33%|███▎      | 653/2000 [00:35<01:11, 18.75it/s]

Epoch 4:  33%|███▎      | 655/2000 [00:35<01:11, 18.76it/s]

Epoch 4:  33%|███▎      | 657/2000 [00:35<01:11, 18.76it/s]

Epoch 4:  33%|███▎      | 659/2000 [00:35<01:11, 18.74it/s]

Epoch 4:  33%|███▎      | 661/2000 [00:36<01:11, 18.76it/s]

Epoch 4:  33%|███▎      | 663/2000 [00:36<01:11, 18.76it/s]

Epoch 4:  33%|███▎      | 665/2000 [00:36<01:11, 18.77it/s]

Epoch 4:  33%|███▎      | 667/2000 [00:36<01:11, 18.76it/s]

Epoch 4:  33%|███▎      | 669/2000 [00:36<01:10, 18.76it/s]

Epoch 4:  34%|███▎      | 671/2000 [00:36<01:10, 18.76it/s]

Epoch 4:  34%|███▎      | 673/2000 [00:36<01:10, 18.77it/s]

Epoch 4:  34%|███▍      | 675/2000 [00:36<01:10, 18.77it/s]

Epoch 4:  34%|███▍      | 677/2000 [00:36<01:10, 18.78it/s]

Epoch 4:  34%|███▍      | 679/2000 [00:37<01:10, 18.78it/s]

Epoch 4:  34%|███▍      | 681/2000 [00:37<01:10, 18.77it/s]

Epoch 4:  34%|███▍      | 683/2000 [00:37<01:10, 18.77it/s]

Epoch 4:  34%|███▍      | 685/2000 [00:37<01:10, 18.75it/s]

Epoch 4:  34%|███▍      | 687/2000 [00:37<01:09, 18.76it/s]

Epoch 4:  34%|███▍      | 689/2000 [00:37<01:09, 18.77it/s]

Epoch 4:  35%|███▍      | 691/2000 [00:37<01:09, 18.77it/s]

Epoch 4:  35%|███▍      | 693/2000 [00:37<01:09, 18.77it/s]

Epoch 4:  35%|███▍      | 695/2000 [00:37<01:09, 18.76it/s]

Epoch 4:  35%|███▍      | 697/2000 [00:37<01:09, 18.76it/s]

Epoch 4:  35%|███▍      | 699/2000 [00:38<01:09, 18.76it/s]

Epoch 4:  35%|███▌      | 701/2000 [00:38<01:09, 18.76it/s]

Epoch 4:  35%|███▌      | 703/2000 [00:38<01:09, 18.76it/s]

Epoch 4:  35%|███▌      | 705/2000 [00:38<01:09, 18.76it/s]

Epoch 4:  35%|███▌      | 707/2000 [00:38<01:08, 18.76it/s]

Epoch 4:  35%|███▌      | 709/2000 [00:38<01:08, 18.76it/s]

Epoch 4:  36%|███▌      | 711/2000 [00:38<01:08, 18.76it/s]

Epoch 4:  36%|███▌      | 713/2000 [00:38<01:08, 18.76it/s]

Epoch 4:  36%|███▌      | 715/2000 [00:38<01:08, 18.76it/s]

Epoch 4:  36%|███▌      | 717/2000 [00:39<01:08, 18.76it/s]

Epoch 4:  36%|███▌      | 719/2000 [00:39<01:08, 18.75it/s]

Epoch 4:  36%|███▌      | 721/2000 [00:39<01:08, 18.75it/s]

Epoch 4:  36%|███▌      | 723/2000 [00:39<01:08, 18.74it/s]

Epoch 4:  36%|███▋      | 725/2000 [00:39<01:08, 18.74it/s]

Epoch 4:  36%|███▋      | 727/2000 [00:39<01:07, 18.75it/s]

Epoch 4:  36%|███▋      | 729/2000 [00:39<01:07, 18.76it/s]

Epoch 4:  37%|███▋      | 731/2000 [00:39<01:07, 18.76it/s]

Epoch 4:  37%|███▋      | 733/2000 [00:39<01:07, 18.75it/s]

Epoch 4:  37%|███▋      | 735/2000 [00:39<01:07, 18.64it/s]

Epoch 4:  37%|███▋      | 737/2000 [00:40<01:07, 18.67it/s]

Epoch 4:  37%|███▋      | 739/2000 [00:40<01:07, 18.69it/s]

Epoch 4:  37%|███▋      | 741/2000 [00:40<01:07, 18.72it/s]

Epoch 4:  37%|███▋      | 743/2000 [00:40<01:07, 18.73it/s]

Epoch 4:  37%|███▋      | 745/2000 [00:40<01:07, 18.73it/s]

Epoch 4:  37%|███▋      | 747/2000 [00:40<01:06, 18.74it/s]

Epoch 4:  37%|███▋      | 749/2000 [00:40<01:06, 18.74it/s]

Epoch 4:  38%|███▊      | 751/2000 [00:40<01:06, 18.74it/s]

Epoch 4:  38%|███▊      | 753/2000 [00:40<01:06, 18.75it/s]

Epoch 4:  38%|███▊      | 755/2000 [00:41<01:06, 18.75it/s]

Epoch 4:  38%|███▊      | 757/2000 [00:41<01:06, 18.75it/s]

Epoch 4:  38%|███▊      | 759/2000 [00:41<01:06, 18.76it/s]

Epoch 4:  38%|███▊      | 761/2000 [00:41<01:05, 18.78it/s]

Epoch 4:  38%|███▊      | 763/2000 [00:41<01:05, 18.77it/s]

Epoch 4:  38%|███▊      | 765/2000 [00:41<01:05, 18.76it/s]

Epoch 4:  38%|███▊      | 767/2000 [00:41<01:05, 18.76it/s]

Epoch 4:  38%|███▊      | 769/2000 [00:41<01:05, 18.75it/s]

Epoch 4:  39%|███▊      | 771/2000 [00:41<01:05, 18.74it/s]

Epoch 4:  39%|███▊      | 773/2000 [00:42<01:05, 18.74it/s]

Epoch 4:  39%|███▉      | 775/2000 [00:42<01:05, 18.75it/s]

Epoch 4:  39%|███▉      | 777/2000 [00:42<01:05, 18.74it/s]

Epoch 4:  39%|███▉      | 779/2000 [00:42<01:05, 18.74it/s]

Epoch 4:  39%|███▉      | 781/2000 [00:42<01:05, 18.68it/s]

Epoch 4:  39%|███▉      | 783/2000 [00:42<01:05, 18.67it/s]

Epoch 4:  39%|███▉      | 785/2000 [00:42<01:04, 18.70it/s]

Epoch 4:  39%|███▉      | 787/2000 [00:42<01:04, 18.70it/s]

Epoch 4:  39%|███▉      | 789/2000 [00:42<01:04, 18.72it/s]

Epoch 4:  40%|███▉      | 791/2000 [00:42<01:04, 18.74it/s]

Epoch 4:  40%|███▉      | 793/2000 [00:43<01:04, 18.74it/s]

Epoch 4:  40%|███▉      | 795/2000 [00:43<01:04, 18.74it/s]

Epoch 4:  40%|███▉      | 797/2000 [00:43<01:04, 18.76it/s]

Epoch 4:  40%|███▉      | 799/2000 [00:43<01:03, 18.77it/s]

Epoch 4:  40%|████      | 801/2000 [00:43<01:03, 18.77it/s]

Epoch 4:  40%|████      | 803/2000 [00:43<01:03, 18.77it/s]

Epoch 4:  40%|████      | 805/2000 [00:43<01:03, 18.76it/s]

Epoch 4:  40%|████      | 807/2000 [00:43<01:03, 18.76it/s]

Epoch 4:  40%|████      | 809/2000 [00:43<01:03, 18.77it/s]

Epoch 4:  41%|████      | 811/2000 [00:44<01:03, 18.77it/s]

Epoch 4:  41%|████      | 813/2000 [00:44<01:03, 18.77it/s]

Epoch 4:  41%|████      | 815/2000 [00:44<01:03, 18.77it/s]

Epoch 4:  41%|████      | 817/2000 [00:44<01:03, 18.76it/s]

Epoch 4:  41%|████      | 819/2000 [00:44<01:02, 18.77it/s]

Epoch 4:  41%|████      | 821/2000 [00:44<01:02, 18.76it/s]

Epoch 4:  41%|████      | 823/2000 [00:44<01:02, 18.76it/s]

Epoch 4:  41%|████▏     | 825/2000 [00:44<01:02, 18.75it/s]

Epoch 4:  41%|████▏     | 827/2000 [00:44<01:02, 18.74it/s]

Epoch 4:  41%|████▏     | 829/2000 [00:45<01:02, 18.74it/s]

Epoch 4:  42%|████▏     | 831/2000 [00:45<01:02, 18.74it/s]

Epoch 4:  42%|████▏     | 833/2000 [00:45<01:02, 18.76it/s]

Epoch 4:  42%|████▏     | 835/2000 [00:45<01:02, 18.77it/s]

Epoch 4:  42%|████▏     | 837/2000 [00:45<01:02, 18.75it/s]

Epoch 4:  42%|████▏     | 839/2000 [00:45<01:01, 18.76it/s]

Epoch 4:  42%|████▏     | 841/2000 [00:45<01:01, 18.75it/s]

Epoch 4:  42%|████▏     | 843/2000 [00:45<01:01, 18.75it/s]

Epoch 4:  42%|████▏     | 845/2000 [00:45<01:01, 18.74it/s]

Epoch 4:  42%|████▏     | 847/2000 [00:45<01:01, 18.75it/s]

Epoch 4:  42%|████▏     | 849/2000 [00:46<01:01, 18.74it/s]

Epoch 4:  43%|████▎     | 851/2000 [00:46<01:01, 18.74it/s]

Epoch 4:  43%|████▎     | 853/2000 [00:46<01:01, 18.74it/s]

Epoch 4:  43%|████▎     | 855/2000 [00:46<01:01, 18.73it/s]

Epoch 4:  43%|████▎     | 857/2000 [00:46<01:00, 18.74it/s]

Epoch 4:  43%|████▎     | 859/2000 [00:46<01:00, 18.74it/s]

Epoch 4:  43%|████▎     | 861/2000 [00:46<01:00, 18.75it/s]

Epoch 4:  43%|████▎     | 863/2000 [00:46<01:00, 18.75it/s]

Epoch 4:  43%|████▎     | 865/2000 [00:46<01:00, 18.75it/s]

Epoch 4:  43%|████▎     | 867/2000 [00:47<01:00, 18.74it/s]

Epoch 4:  43%|████▎     | 869/2000 [00:47<01:00, 18.73it/s]

Epoch 4:  44%|████▎     | 871/2000 [00:47<01:00, 18.73it/s]

Epoch 4:  44%|████▎     | 873/2000 [00:47<01:00, 18.58it/s]

Epoch 4:  44%|████▍     | 875/2000 [00:47<01:00, 18.62it/s]

Epoch 4:  44%|████▍     | 877/2000 [00:47<01:00, 18.64it/s]

Epoch 4:  44%|████▍     | 879/2000 [00:47<01:00, 18.67it/s]

Epoch 4:  44%|████▍     | 881/2000 [00:47<00:59, 18.69it/s]

Epoch 4:  44%|████▍     | 883/2000 [00:47<00:59, 18.68it/s]

Epoch 4:  44%|████▍     | 885/2000 [00:47<00:59, 18.70it/s]

Epoch 4:  44%|████▍     | 887/2000 [00:48<00:59, 18.69it/s]

Epoch 4:  44%|████▍     | 889/2000 [00:48<00:59, 18.69it/s]

Epoch 4:  45%|████▍     | 891/2000 [00:48<00:59, 18.68it/s]

Epoch 4:  45%|████▍     | 893/2000 [00:48<00:59, 18.69it/s]

Epoch 4:  45%|████▍     | 895/2000 [00:48<00:59, 18.70it/s]

Epoch 4:  45%|████▍     | 897/2000 [00:48<00:58, 18.71it/s]

Epoch 4:  45%|████▍     | 899/2000 [00:48<00:58, 18.70it/s]

Epoch 4:  45%|████▌     | 901/2000 [00:48<00:58, 18.70it/s]

Epoch 4:  45%|████▌     | 903/2000 [00:48<00:58, 18.71it/s]

Epoch 4:  45%|████▌     | 905/2000 [00:49<00:58, 18.72it/s]

Epoch 4:  45%|████▌     | 907/2000 [00:49<00:58, 18.73it/s]

Epoch 4:  45%|████▌     | 909/2000 [00:49<00:58, 18.73it/s]

Epoch 4:  46%|████▌     | 911/2000 [00:49<00:58, 18.72it/s]

Epoch 4:  46%|████▌     | 913/2000 [00:49<00:58, 18.72it/s]

Epoch 4:  46%|████▌     | 915/2000 [00:49<00:57, 18.73it/s]

Epoch 4:  46%|████▌     | 917/2000 [00:49<00:57, 18.72it/s]

Epoch 4:  46%|████▌     | 919/2000 [00:49<00:57, 18.72it/s]

Epoch 4:  46%|████▌     | 921/2000 [00:49<00:57, 18.68it/s]

Epoch 4:  46%|████▌     | 923/2000 [00:50<00:57, 18.64it/s]

Epoch 4:  46%|████▋     | 925/2000 [00:50<00:57, 18.61it/s]

Epoch 4:  46%|████▋     | 927/2000 [00:50<00:57, 18.62it/s]

Epoch 4:  46%|████▋     | 929/2000 [00:50<00:57, 18.62it/s]

Epoch 4:  47%|████▋     | 931/2000 [00:50<00:57, 18.61it/s]

Epoch 4:  47%|████▋     | 933/2000 [00:50<00:57, 18.61it/s]

Epoch 4:  47%|████▋     | 935/2000 [00:50<00:57, 18.61it/s]

Epoch 4:  47%|████▋     | 937/2000 [00:50<00:57, 18.57it/s]

Epoch 4:  47%|████▋     | 939/2000 [00:50<00:57, 18.58it/s]

Epoch 4:  47%|████▋     | 941/2000 [00:50<00:56, 18.59it/s]

Epoch 4:  47%|████▋     | 943/2000 [00:51<00:56, 18.60it/s]

Epoch 4:  47%|████▋     | 945/2000 [00:51<00:56, 18.61it/s]

Epoch 4:  47%|████▋     | 947/2000 [00:51<00:56, 18.62it/s]

Epoch 4:  47%|████▋     | 949/2000 [00:51<00:56, 18.61it/s]

Epoch 4:  48%|████▊     | 951/2000 [00:51<00:56, 18.61it/s]

Epoch 4:  48%|████▊     | 953/2000 [00:51<00:56, 18.63it/s]

Epoch 4:  48%|████▊     | 955/2000 [00:51<00:56, 18.62it/s]

Epoch 4:  48%|████▊     | 957/2000 [00:51<00:56, 18.62it/s]

Epoch 4:  48%|████▊     | 959/2000 [00:51<00:55, 18.62it/s]

Epoch 4:  48%|████▊     | 961/2000 [00:52<00:55, 18.64it/s]

Epoch 4:  48%|████▊     | 963/2000 [00:52<00:55, 18.64it/s]

Epoch 4:  48%|████▊     | 965/2000 [00:52<00:55, 18.64it/s]

Epoch 4:  48%|████▊     | 967/2000 [00:52<00:55, 18.64it/s]

Epoch 4:  48%|████▊     | 969/2000 [00:52<00:55, 18.63it/s]

Epoch 4:  49%|████▊     | 971/2000 [00:52<00:55, 18.64it/s]

Epoch 4:  49%|████▊     | 973/2000 [00:52<00:55, 18.63it/s]

Epoch 4:  49%|████▉     | 975/2000 [00:52<00:54, 18.64it/s]

Epoch 4:  49%|████▉     | 977/2000 [00:52<00:54, 18.64it/s]

Epoch 4:  49%|████▉     | 979/2000 [00:53<00:54, 18.64it/s]

Epoch 4:  49%|████▉     | 981/2000 [00:53<00:54, 18.63it/s]

Epoch 4:  49%|████▉     | 983/2000 [00:53<00:54, 18.63it/s]

Epoch 4:  49%|████▉     | 985/2000 [00:53<00:54, 18.62it/s]

Epoch 4:  49%|████▉     | 987/2000 [00:53<00:54, 18.63it/s]

Epoch 4:  49%|████▉     | 989/2000 [00:53<00:54, 18.61it/s]

Epoch 4:  50%|████▉     | 991/2000 [00:53<00:54, 18.42it/s]

Epoch 4:  50%|████▉     | 993/2000 [00:53<00:56, 17.88it/s]

Epoch 4:  50%|████▉     | 995/2000 [00:53<00:56, 17.88it/s]

Epoch 4:  50%|████▉     | 997/2000 [00:54<00:55, 18.03it/s]

Epoch 4:  50%|████▉     | 999/2000 [00:54<00:55, 18.17it/s]

Epoch 4:  50%|█████     | 1001/2000 [00:54<00:54, 18.27it/s]

Epoch 4:  50%|█████     | 1003/2000 [00:54<00:54, 18.38it/s]

Epoch 4:  50%|█████     | 1005/2000 [00:54<00:53, 18.44it/s]

Epoch 4:  50%|█████     | 1007/2000 [00:54<00:53, 18.49it/s]

Epoch 4:  50%|█████     | 1009/2000 [00:54<00:53, 18.54it/s]

Epoch 4:  51%|█████     | 1011/2000 [00:54<00:53, 18.57it/s]

Epoch 4:  51%|█████     | 1013/2000 [00:54<00:53, 18.60it/s]

Epoch 4:  51%|█████     | 1015/2000 [00:54<00:52, 18.62it/s]

Epoch 4:  51%|█████     | 1017/2000 [00:55<00:52, 18.62it/s]

Epoch 4:  51%|█████     | 1019/2000 [00:55<00:52, 18.63it/s]

Epoch 4:  51%|█████     | 1021/2000 [00:55<00:52, 18.65it/s]

Epoch 4:  51%|█████     | 1023/2000 [00:55<00:52, 18.64it/s]

Epoch 4:  51%|█████▏    | 1025/2000 [00:55<00:52, 18.63it/s]

Epoch 4:  51%|█████▏    | 1027/2000 [00:55<00:52, 18.63it/s]

Epoch 4:  51%|█████▏    | 1029/2000 [00:55<00:52, 18.63it/s]

Epoch 4:  52%|█████▏    | 1031/2000 [00:55<00:52, 18.61it/s]

Epoch 4:  52%|█████▏    | 1033/2000 [00:55<00:51, 18.62it/s]

Epoch 4:  52%|█████▏    | 1035/2000 [00:56<00:51, 18.63it/s]

Epoch 4:  52%|█████▏    | 1037/2000 [00:56<00:51, 18.64it/s]

Epoch 4:  52%|█████▏    | 1039/2000 [00:56<00:51, 18.65it/s]

Epoch 4:  52%|█████▏    | 1041/2000 [00:56<00:51, 18.64it/s]

Epoch 4:  52%|█████▏    | 1043/2000 [00:56<00:51, 18.64it/s]

Epoch 4:  52%|█████▏    | 1045/2000 [00:56<00:51, 18.63it/s]

Epoch 4:  52%|█████▏    | 1047/2000 [00:56<00:51, 18.63it/s]

Epoch 4:  52%|█████▏    | 1049/2000 [00:56<00:51, 18.60it/s]

Epoch 4:  53%|█████▎    | 1051/2000 [00:56<00:51, 18.60it/s]

Epoch 4:  53%|█████▎    | 1053/2000 [00:57<00:50, 18.62it/s]

Epoch 4:  53%|█████▎    | 1055/2000 [00:57<00:50, 18.63it/s]

Epoch 4:  53%|█████▎    | 1057/2000 [00:57<00:50, 18.63it/s]

Epoch 4:  53%|█████▎    | 1059/2000 [00:57<00:50, 18.64it/s]

Epoch 4:  53%|█████▎    | 1061/2000 [00:57<00:50, 18.64it/s]

Epoch 4:  53%|█████▎    | 1063/2000 [00:57<00:50, 18.64it/s]

Epoch 4:  53%|█████▎    | 1065/2000 [00:57<00:50, 18.63it/s]

Epoch 4:  53%|█████▎    | 1067/2000 [00:57<00:50, 18.62it/s]

Epoch 4:  53%|█████▎    | 1069/2000 [00:57<00:50, 18.62it/s]

Epoch 4:  54%|█████▎    | 1071/2000 [00:57<00:49, 18.63it/s]

Epoch 4:  54%|█████▎    | 1073/2000 [00:58<00:49, 18.64it/s]

Epoch 4:  54%|█████▍    | 1075/2000 [00:58<00:49, 18.64it/s]

Epoch 4:  54%|█████▍    | 1077/2000 [00:58<00:49, 18.65it/s]

Epoch 4:  54%|█████▍    | 1079/2000 [00:58<00:49, 18.66it/s]

Epoch 4:  54%|█████▍    | 1081/2000 [00:58<00:49, 18.66it/s]

Epoch 4:  54%|█████▍    | 1083/2000 [00:58<00:49, 18.64it/s]

Epoch 4:  54%|█████▍    | 1085/2000 [00:58<00:49, 18.63it/s]

Epoch 4:  54%|█████▍    | 1087/2000 [00:58<00:48, 18.64it/s]

Epoch 4:  54%|█████▍    | 1089/2000 [00:58<00:48, 18.64it/s]

Epoch 4:  55%|█████▍    | 1091/2000 [00:59<00:48, 18.65it/s]

Epoch 4:  55%|█████▍    | 1093/2000 [00:59<00:48, 18.66it/s]

Epoch 4:  55%|█████▍    | 1095/2000 [00:59<00:48, 18.67it/s]

Epoch 4:  55%|█████▍    | 1097/2000 [00:59<00:48, 18.66it/s]

Epoch 4:  55%|█████▍    | 1099/2000 [00:59<00:48, 18.65it/s]

Epoch 4:  55%|█████▌    | 1101/2000 [00:59<00:48, 18.64it/s]

Epoch 4:  55%|█████▌    | 1103/2000 [00:59<00:48, 18.65it/s]

Epoch 4:  55%|█████▌    | 1105/2000 [00:59<00:47, 18.65it/s]

Epoch 4:  55%|█████▌    | 1107/2000 [00:59<00:47, 18.65it/s]

Epoch 4:  55%|█████▌    | 1109/2000 [01:00<00:48, 18.55it/s]

Epoch 4:  56%|█████▌    | 1111/2000 [01:00<00:47, 18.57it/s]

Epoch 4:  56%|█████▌    | 1113/2000 [01:00<00:47, 18.60it/s]

Epoch 4:  56%|█████▌    | 1115/2000 [01:00<00:47, 18.62it/s]

Epoch 4:  56%|█████▌    | 1117/2000 [01:00<00:47, 18.61it/s]

Epoch 4:  56%|█████▌    | 1119/2000 [01:00<00:47, 18.60it/s]

Epoch 4:  56%|█████▌    | 1121/2000 [01:00<00:47, 18.61it/s]

Epoch 4:  56%|█████▌    | 1123/2000 [01:00<00:47, 18.63it/s]

Epoch 4:  56%|█████▋    | 1125/2000 [01:00<00:46, 18.62it/s]

Epoch 4:  56%|█████▋    | 1127/2000 [01:01<00:46, 18.63it/s]

Epoch 4:  56%|█████▋    | 1129/2000 [01:01<00:46, 18.62it/s]

Epoch 4:  57%|█████▋    | 1131/2000 [01:01<00:46, 18.63it/s]

Epoch 4:  57%|█████▋    | 1133/2000 [01:01<00:46, 18.64it/s]

Epoch 4:  57%|█████▋    | 1135/2000 [01:01<00:46, 18.64it/s]

Epoch 4:  57%|█████▋    | 1137/2000 [01:01<00:46, 18.63it/s]

Epoch 4:  57%|█████▋    | 1139/2000 [01:01<00:46, 18.64it/s]

Epoch 4:  57%|█████▋    | 1141/2000 [01:01<00:46, 18.62it/s]

Epoch 4:  57%|█████▋    | 1143/2000 [01:01<00:46, 18.60it/s]

Epoch 4:  57%|█████▋    | 1145/2000 [01:01<00:45, 18.62it/s]

Epoch 4:  57%|█████▋    | 1147/2000 [01:02<00:45, 18.63it/s]

Epoch 4:  57%|█████▋    | 1149/2000 [01:02<00:45, 18.63it/s]

Epoch 4:  58%|█████▊    | 1151/2000 [01:02<00:45, 18.62it/s]

Epoch 4:  58%|█████▊    | 1153/2000 [01:02<00:45, 18.63it/s]

Epoch 4:  58%|█████▊    | 1155/2000 [01:02<00:45, 18.64it/s]

Epoch 4:  58%|█████▊    | 1157/2000 [01:02<00:45, 18.66it/s]

Epoch 4:  58%|█████▊    | 1159/2000 [01:02<00:45, 18.67it/s]

Epoch 4:  58%|█████▊    | 1161/2000 [01:02<00:44, 18.67it/s]

Epoch 4:  58%|█████▊    | 1163/2000 [01:02<00:44, 18.66it/s]

Epoch 4:  58%|█████▊    | 1165/2000 [01:03<00:44, 18.67it/s]

Epoch 4:  58%|█████▊    | 1167/2000 [01:03<00:44, 18.66it/s]

Epoch 4:  58%|█████▊    | 1169/2000 [01:03<00:44, 18.65it/s]

Epoch 4:  59%|█████▊    | 1171/2000 [01:03<00:44, 18.66it/s]

Epoch 4:  59%|█████▊    | 1173/2000 [01:03<00:44, 18.67it/s]

Epoch 4:  59%|█████▉    | 1175/2000 [01:03<00:44, 18.68it/s]

Epoch 4:  59%|█████▉    | 1177/2000 [01:03<00:44, 18.67it/s]

Epoch 4:  59%|█████▉    | 1179/2000 [01:03<00:44, 18.66it/s]

Epoch 4:  59%|█████▉    | 1181/2000 [01:03<00:43, 18.64it/s]

Epoch 4:  59%|█████▉    | 1183/2000 [01:04<00:43, 18.66it/s]

Epoch 4:  59%|█████▉    | 1185/2000 [01:04<00:43, 18.67it/s]

Epoch 4:  59%|█████▉    | 1187/2000 [01:04<00:43, 18.66it/s]

Epoch 4:  59%|█████▉    | 1189/2000 [01:04<00:43, 18.66it/s]

Epoch 4:  60%|█████▉    | 1191/2000 [01:04<00:43, 18.67it/s]

Epoch 4:  60%|█████▉    | 1193/2000 [01:04<00:43, 18.67it/s]

Epoch 4:  60%|█████▉    | 1195/2000 [01:04<00:43, 18.66it/s]

Epoch 4:  60%|█████▉    | 1197/2000 [01:04<00:43, 18.64it/s]

Epoch 4:  60%|█████▉    | 1199/2000 [01:04<00:42, 18.64it/s]

Epoch 4:  60%|██████    | 1201/2000 [01:04<00:42, 18.65it/s]

Epoch 4:  60%|██████    | 1203/2000 [01:05<00:42, 18.66it/s]

Epoch 4:  60%|██████    | 1205/2000 [01:05<00:42, 18.67it/s]

Epoch 4:  60%|██████    | 1207/2000 [01:05<00:42, 18.66it/s]

Epoch 4:  60%|██████    | 1209/2000 [01:05<00:42, 18.67it/s]

Epoch 4:  61%|██████    | 1211/2000 [01:05<00:42, 18.67it/s]

Epoch 4:  61%|██████    | 1213/2000 [01:05<00:42, 18.70it/s]

Epoch 4:  61%|██████    | 1215/2000 [01:05<00:41, 18.69it/s]

Epoch 4:  61%|██████    | 1217/2000 [01:05<00:41, 18.68it/s]

Epoch 4:  61%|██████    | 1219/2000 [01:05<00:41, 18.67it/s]

Epoch 4:  61%|██████    | 1221/2000 [01:06<00:41, 18.68it/s]

Epoch 4:  61%|██████    | 1223/2000 [01:06<00:41, 18.68it/s]

Epoch 4:  61%|██████▏   | 1225/2000 [01:06<00:41, 18.67it/s]

Epoch 4:  61%|██████▏   | 1227/2000 [01:06<00:41, 18.65it/s]

Epoch 4:  61%|██████▏   | 1229/2000 [01:06<00:41, 18.67it/s]

Epoch 4:  62%|██████▏   | 1231/2000 [01:06<00:41, 18.68it/s]

Epoch 4:  62%|██████▏   | 1233/2000 [01:06<00:41, 18.67it/s]

Epoch 4:  62%|██████▏   | 1235/2000 [01:06<00:40, 18.67it/s]

Epoch 4:  62%|██████▏   | 1237/2000 [01:06<00:40, 18.68it/s]

Epoch 4:  62%|██████▏   | 1239/2000 [01:07<00:40, 18.68it/s]

Epoch 4:  62%|██████▏   | 1241/2000 [01:07<00:40, 18.68it/s]

Epoch 4:  62%|██████▏   | 1243/2000 [01:07<00:40, 18.67it/s]

Epoch 4:  62%|██████▏   | 1245/2000 [01:07<00:40, 18.66it/s]

Epoch 4:  62%|██████▏   | 1247/2000 [01:07<00:40, 18.66it/s]

Epoch 4:  62%|██████▏   | 1249/2000 [01:07<00:40, 18.66it/s]

Epoch 4:  63%|██████▎   | 1251/2000 [01:07<00:40, 18.68it/s]

Epoch 4:  63%|██████▎   | 1253/2000 [01:07<00:39, 18.68it/s]

Epoch 4:  63%|██████▎   | 1255/2000 [01:07<00:39, 18.67it/s]

Epoch 4:  63%|██████▎   | 1257/2000 [01:07<00:39, 18.67it/s]

Epoch 4:  63%|██████▎   | 1259/2000 [01:08<00:39, 18.67it/s]

Epoch 4:  63%|██████▎   | 1261/2000 [01:08<00:39, 18.68it/s]

Epoch 4:  63%|██████▎   | 1263/2000 [01:08<00:39, 18.69it/s]

Epoch 4:  63%|██████▎   | 1265/2000 [01:08<00:39, 18.69it/s]

Epoch 4:  63%|██████▎   | 1267/2000 [01:08<00:39, 18.69it/s]

Epoch 4:  63%|██████▎   | 1269/2000 [01:08<00:39, 18.68it/s]

Epoch 4:  64%|██████▎   | 1271/2000 [01:08<00:39, 18.68it/s]

Epoch 4:  64%|██████▎   | 1273/2000 [01:08<00:38, 18.67it/s]

Epoch 4:  64%|██████▍   | 1275/2000 [01:08<00:38, 18.67it/s]

Epoch 4:  64%|██████▍   | 1277/2000 [01:09<00:38, 18.66it/s]

Epoch 4:  64%|██████▍   | 1279/2000 [01:09<00:38, 18.66it/s]

Epoch 4:  64%|██████▍   | 1281/2000 [01:09<00:38, 18.67it/s]

Epoch 4:  64%|██████▍   | 1283/2000 [01:09<00:38, 18.66it/s]

Epoch 4:  64%|██████▍   | 1285/2000 [01:09<00:38, 18.66it/s]

Epoch 4:  64%|██████▍   | 1287/2000 [01:09<00:38, 18.66it/s]

Epoch 4:  64%|██████▍   | 1289/2000 [01:09<00:38, 18.67it/s]

Epoch 4:  65%|██████▍   | 1291/2000 [01:09<00:37, 18.68it/s]

Epoch 4:  65%|██████▍   | 1293/2000 [01:09<00:37, 18.68it/s]

Epoch 4:  65%|██████▍   | 1295/2000 [01:10<00:37, 18.68it/s]

Epoch 4:  65%|██████▍   | 1297/2000 [01:10<00:37, 18.67it/s]

Epoch 4:  65%|██████▍   | 1299/2000 [01:10<00:37, 18.67it/s]

Epoch 4:  65%|██████▌   | 1301/2000 [01:10<00:37, 18.69it/s]

Epoch 4:  65%|██████▌   | 1303/2000 [01:10<00:37, 18.69it/s]

Epoch 4:  65%|██████▌   | 1305/2000 [01:10<00:37, 18.69it/s]

Epoch 4:  65%|██████▌   | 1307/2000 [01:10<00:37, 18.70it/s]

Epoch 4:  65%|██████▌   | 1309/2000 [01:10<00:36, 18.70it/s]

Epoch 4:  66%|██████▌   | 1311/2000 [01:10<00:36, 18.69it/s]

Epoch 4:  66%|██████▌   | 1313/2000 [01:10<00:36, 18.68it/s]

Epoch 4:  66%|██████▌   | 1315/2000 [01:11<00:36, 18.69it/s]

Epoch 4:  66%|██████▌   | 1317/2000 [01:11<00:36, 18.69it/s]

Epoch 4:  66%|██████▌   | 1319/2000 [01:11<00:36, 18.69it/s]

Epoch 4:  66%|██████▌   | 1321/2000 [01:11<00:36, 18.66it/s]

Epoch 4:  66%|██████▌   | 1323/2000 [01:11<00:36, 18.66it/s]

Epoch 4:  66%|██████▋   | 1325/2000 [01:11<00:36, 18.66it/s]

Epoch 4:  66%|██████▋   | 1327/2000 [01:11<00:36, 18.66it/s]

Epoch 4:  66%|██████▋   | 1329/2000 [01:11<00:35, 18.65it/s]

Epoch 4:  67%|██████▋   | 1331/2000 [01:11<00:35, 18.65it/s]

Epoch 4:  67%|██████▋   | 1333/2000 [01:12<00:35, 18.68it/s]

Epoch 4:  67%|██████▋   | 1335/2000 [01:12<00:35, 18.67it/s]

Epoch 4:  67%|██████▋   | 1337/2000 [01:12<00:35, 18.67it/s]

Epoch 4:  67%|██████▋   | 1339/2000 [01:12<00:35, 18.68it/s]

Epoch 4:  67%|██████▋   | 1341/2000 [01:12<00:35, 18.65it/s]

Epoch 4:  67%|██████▋   | 1343/2000 [01:12<00:35, 18.65it/s]

Epoch 4:  67%|██████▋   | 1345/2000 [01:12<00:35, 18.65it/s]

Epoch 4:  67%|██████▋   | 1347/2000 [01:12<00:35, 18.65it/s]

Epoch 4:  67%|██████▋   | 1349/2000 [01:12<00:34, 18.66it/s]

Epoch 4:  68%|██████▊   | 1351/2000 [01:13<00:34, 18.67it/s]

Epoch 4:  68%|██████▊   | 1353/2000 [01:13<00:34, 18.67it/s]

Epoch 4:  68%|██████▊   | 1355/2000 [01:13<00:34, 18.67it/s]

Epoch 4:  68%|██████▊   | 1357/2000 [01:13<00:34, 18.64it/s]

Epoch 4:  68%|██████▊   | 1359/2000 [01:13<00:34, 18.66it/s]

Epoch 4:  68%|██████▊   | 1361/2000 [01:13<00:34, 18.67it/s]

Epoch 4:  68%|██████▊   | 1363/2000 [01:13<00:34, 18.66it/s]

Epoch 4:  68%|██████▊   | 1365/2000 [01:13<00:34, 18.67it/s]

Epoch 4:  68%|██████▊   | 1367/2000 [01:13<00:33, 18.67it/s]

Epoch 4:  68%|██████▊   | 1369/2000 [01:13<00:33, 18.66it/s]

Epoch 4:  69%|██████▊   | 1371/2000 [01:14<00:33, 18.66it/s]

Epoch 4:  69%|██████▊   | 1373/2000 [01:14<00:33, 18.66it/s]

Epoch 4:  69%|██████▉   | 1375/2000 [01:14<00:33, 18.66it/s]

Epoch 4:  69%|██████▉   | 1377/2000 [01:14<00:33, 18.66it/s]

Epoch 4:  69%|██████▉   | 1379/2000 [01:14<00:33, 18.66it/s]

Epoch 4:  69%|██████▉   | 1381/2000 [01:14<00:33, 18.65it/s]

Epoch 4:  69%|██████▉   | 1383/2000 [01:14<00:33, 18.65it/s]

Epoch 4:  69%|██████▉   | 1385/2000 [01:14<00:32, 18.66it/s]

Epoch 4:  69%|██████▉   | 1387/2000 [01:14<00:32, 18.66it/s]

Epoch 4:  69%|██████▉   | 1389/2000 [01:15<00:32, 18.65it/s]

Epoch 4:  70%|██████▉   | 1391/2000 [01:15<00:32, 18.66it/s]

Epoch 4:  70%|██████▉   | 1393/2000 [01:15<00:32, 18.67it/s]

Epoch 4:  70%|██████▉   | 1395/2000 [01:15<00:32, 18.67it/s]

Epoch 4:  70%|██████▉   | 1397/2000 [01:15<00:32, 18.66it/s]

Epoch 4:  70%|██████▉   | 1399/2000 [01:15<00:32, 18.65it/s]

Epoch 4:  70%|███████   | 1401/2000 [01:15<00:32, 18.67it/s]

Epoch 4:  70%|███████   | 1403/2000 [01:15<00:31, 18.66it/s]

Epoch 4:  70%|███████   | 1405/2000 [01:15<00:31, 18.64it/s]

Epoch 4:  70%|███████   | 1407/2000 [01:16<00:31, 18.65it/s]

Epoch 4:  70%|███████   | 1409/2000 [01:16<00:31, 18.65it/s]

Epoch 4:  71%|███████   | 1411/2000 [01:16<00:31, 18.66it/s]

Epoch 4:  71%|███████   | 1413/2000 [01:16<00:31, 18.66it/s]

Epoch 4:  71%|███████   | 1415/2000 [01:16<00:31, 18.66it/s]

Epoch 4:  71%|███████   | 1417/2000 [01:16<00:31, 18.65it/s]

Epoch 4:  71%|███████   | 1419/2000 [01:16<00:31, 18.67it/s]

Epoch 4:  71%|███████   | 1421/2000 [01:16<00:31, 18.68it/s]

Epoch 4:  71%|███████   | 1423/2000 [01:16<00:30, 18.67it/s]

Epoch 4:  71%|███████▏  | 1425/2000 [01:16<00:30, 18.68it/s]

Epoch 4:  71%|███████▏  | 1427/2000 [01:17<00:30, 18.66it/s]

Epoch 4:  71%|███████▏  | 1429/2000 [01:17<00:30, 18.67it/s]

Epoch 4:  72%|███████▏  | 1431/2000 [01:17<00:30, 18.66it/s]

Epoch 4:  72%|███████▏  | 1433/2000 [01:17<00:30, 18.67it/s]

Epoch 4:  72%|███████▏  | 1435/2000 [01:17<00:30, 18.67it/s]

Epoch 4:  72%|███████▏  | 1437/2000 [01:17<00:30, 18.66it/s]

Epoch 4:  72%|███████▏  | 1439/2000 [01:17<00:30, 18.68it/s]

Epoch 4:  72%|███████▏  | 1441/2000 [01:17<00:29, 18.68it/s]

Epoch 4:  72%|███████▏  | 1443/2000 [01:17<00:29, 18.67it/s]

Epoch 4:  72%|███████▏  | 1445/2000 [01:18<00:29, 18.67it/s]

Epoch 4:  72%|███████▏  | 1447/2000 [01:18<00:29, 18.67it/s]

Epoch 4:  72%|███████▏  | 1449/2000 [01:18<00:29, 18.67it/s]

Epoch 4:  73%|███████▎  | 1451/2000 [01:18<00:29, 18.66it/s]

Epoch 4:  73%|███████▎  | 1453/2000 [01:18<00:29, 18.67it/s]

Epoch 4:  73%|███████▎  | 1455/2000 [01:18<00:29, 18.66it/s]

Epoch 4:  73%|███████▎  | 1457/2000 [01:18<00:29, 18.66it/s]

Epoch 4:  73%|███████▎  | 1459/2000 [01:18<00:28, 18.67it/s]

Epoch 4:  73%|███████▎  | 1461/2000 [01:18<00:28, 18.68it/s]

Epoch 4:  73%|███████▎  | 1463/2000 [01:19<00:28, 18.68it/s]

Epoch 4:  73%|███████▎  | 1465/2000 [01:19<00:28, 18.67it/s]

Epoch 4:  73%|███████▎  | 1467/2000 [01:19<00:28, 18.67it/s]

Epoch 4:  73%|███████▎  | 1469/2000 [01:19<00:28, 18.67it/s]

Epoch 4:  74%|███████▎  | 1471/2000 [01:19<00:28, 18.66it/s]

Epoch 4:  74%|███████▎  | 1473/2000 [01:19<00:28, 18.67it/s]

Epoch 4:  74%|███████▍  | 1475/2000 [01:19<00:28, 18.67it/s]

Epoch 4:  74%|███████▍  | 1477/2000 [01:19<00:28, 18.66it/s]

Epoch 4:  74%|███████▍  | 1479/2000 [01:19<00:27, 18.65it/s]

Epoch 4:  74%|███████▍  | 1481/2000 [01:19<00:27, 18.65it/s]

Epoch 4:  74%|███████▍  | 1483/2000 [01:20<00:27, 18.67it/s]

Epoch 4:  74%|███████▍  | 1485/2000 [01:20<00:27, 18.68it/s]

Epoch 4:  74%|███████▍  | 1487/2000 [01:20<00:27, 18.68it/s]

Epoch 4:  74%|███████▍  | 1489/2000 [01:20<00:27, 18.67it/s]

Epoch 4:  75%|███████▍  | 1491/2000 [01:20<00:27, 18.68it/s]

Epoch 4:  75%|███████▍  | 1493/2000 [01:20<00:27, 18.68it/s]

Epoch 4:  75%|███████▍  | 1495/2000 [01:20<00:27, 18.68it/s]

Epoch 4:  75%|███████▍  | 1497/2000 [01:20<00:26, 18.68it/s]

Epoch 4:  75%|███████▍  | 1499/2000 [01:20<00:26, 18.69it/s]

Epoch 4:  75%|███████▌  | 1501/2000 [01:21<00:26, 18.70it/s]

Epoch 4:  75%|███████▌  | 1503/2000 [01:21<00:26, 18.69it/s]

Epoch 4:  75%|███████▌  | 1505/2000 [01:21<00:26, 18.69it/s]

Epoch 4:  75%|███████▌  | 1507/2000 [01:21<00:26, 18.69it/s]

Epoch 4:  75%|███████▌  | 1509/2000 [01:21<00:26, 18.70it/s]

Epoch 4:  76%|███████▌  | 1511/2000 [01:21<00:26, 18.70it/s]

Epoch 4:  76%|███████▌  | 1513/2000 [01:21<00:26, 18.69it/s]

Epoch 4:  76%|███████▌  | 1515/2000 [01:21<00:25, 18.69it/s]

Epoch 4:  76%|███████▌  | 1517/2000 [01:21<00:25, 18.68it/s]

Epoch 4:  76%|███████▌  | 1519/2000 [01:22<00:25, 18.69it/s]

Epoch 4:  76%|███████▌  | 1521/2000 [01:22<00:25, 18.67it/s]

Epoch 4:  76%|███████▌  | 1523/2000 [01:22<00:25, 18.67it/s]

Epoch 4:  76%|███████▋  | 1525/2000 [01:22<00:25, 18.66it/s]

Epoch 4:  76%|███████▋  | 1527/2000 [01:22<00:25, 18.67it/s]

Epoch 4:  76%|███████▋  | 1529/2000 [01:22<00:25, 18.66it/s]

Epoch 4:  77%|███████▋  | 1531/2000 [01:22<00:25, 18.67it/s]

Epoch 4:  77%|███████▋  | 1533/2000 [01:22<00:25, 18.67it/s]

Epoch 4:  77%|███████▋  | 1535/2000 [01:22<00:24, 18.67it/s]

Epoch 4:  77%|███████▋  | 1537/2000 [01:22<00:24, 18.68it/s]

Epoch 4:  77%|███████▋  | 1539/2000 [01:23<00:24, 18.68it/s]

Epoch 4:  77%|███████▋  | 1541/2000 [01:23<00:24, 18.67it/s]

Epoch 4:  77%|███████▋  | 1543/2000 [01:23<00:24, 18.66it/s]

Epoch 4:  77%|███████▋  | 1545/2000 [01:23<00:24, 18.66it/s]

Epoch 4:  77%|███████▋  | 1547/2000 [01:23<00:24, 18.66it/s]

Epoch 4:  77%|███████▋  | 1549/2000 [01:23<00:24, 18.64it/s]

Epoch 4:  78%|███████▊  | 1551/2000 [01:23<00:24, 18.65it/s]

Epoch 4:  78%|███████▊  | 1553/2000 [01:23<00:23, 18.65it/s]

Epoch 4:  78%|███████▊  | 1555/2000 [01:23<00:23, 18.65it/s]

Epoch 4:  78%|███████▊  | 1557/2000 [01:24<00:23, 18.65it/s]

Epoch 4:  78%|███████▊  | 1559/2000 [01:24<00:23, 18.65it/s]

Epoch 4:  78%|███████▊  | 1561/2000 [01:24<00:23, 18.64it/s]

Epoch 4:  78%|███████▊  | 1563/2000 [01:24<00:23, 18.64it/s]

Epoch 4:  78%|███████▊  | 1565/2000 [01:24<00:23, 18.64it/s]

Epoch 4:  78%|███████▊  | 1567/2000 [01:24<00:23, 18.66it/s]

Epoch 4:  78%|███████▊  | 1569/2000 [01:24<00:23, 18.66it/s]

Epoch 4:  79%|███████▊  | 1571/2000 [01:24<00:22, 18.65it/s]

Epoch 4:  79%|███████▊  | 1573/2000 [01:24<00:22, 18.66it/s]

Epoch 4:  79%|███████▉  | 1575/2000 [01:25<00:22, 18.66it/s]

Epoch 4:  79%|███████▉  | 1577/2000 [01:25<00:22, 18.66it/s]

Epoch 4:  79%|███████▉  | 1579/2000 [01:25<00:22, 18.67it/s]

Epoch 4:  79%|███████▉  | 1581/2000 [01:25<00:22, 18.68it/s]

Epoch 4:  79%|███████▉  | 1583/2000 [01:25<00:22, 18.66it/s]

Epoch 4:  79%|███████▉  | 1585/2000 [01:25<00:22, 18.67it/s]

Epoch 4:  79%|███████▉  | 1587/2000 [01:25<00:22, 18.65it/s]

Epoch 4:  79%|███████▉  | 1589/2000 [01:25<00:22, 18.65it/s]

Epoch 4:  80%|███████▉  | 1591/2000 [01:25<00:21, 18.64it/s]

Epoch 4:  80%|███████▉  | 1593/2000 [01:25<00:21, 18.65it/s]

Epoch 4:  80%|███████▉  | 1595/2000 [01:26<00:21, 18.65it/s]

Epoch 4:  80%|███████▉  | 1597/2000 [01:26<00:21, 18.66it/s]

Epoch 4:  80%|███████▉  | 1599/2000 [01:26<00:21, 18.66it/s]

Epoch 4:  80%|████████  | 1601/2000 [01:26<00:21, 18.67it/s]

Epoch 4:  80%|████████  | 1603/2000 [01:26<00:21, 18.67it/s]

Epoch 4:  80%|████████  | 1605/2000 [01:26<00:21, 18.68it/s]

Epoch 4:  80%|████████  | 1607/2000 [01:26<00:21, 18.67it/s]

Epoch 4:  80%|████████  | 1609/2000 [01:26<00:20, 18.68it/s]

Epoch 4:  81%|████████  | 1611/2000 [01:26<00:21, 18.49it/s]

Epoch 4:  81%|████████  | 1613/2000 [01:27<00:21, 17.96it/s]

Epoch 4:  81%|████████  | 1615/2000 [01:27<00:21, 17.96it/s]

Epoch 4:  81%|████████  | 1617/2000 [01:27<00:21, 18.10it/s]

Epoch 4:  81%|████████  | 1619/2000 [01:27<00:20, 18.23it/s]

Epoch 4:  81%|████████  | 1621/2000 [01:27<00:20, 18.30it/s]

Epoch 4:  81%|████████  | 1623/2000 [01:27<00:20, 18.40it/s]

Epoch 4:  81%|████████▏ | 1625/2000 [01:27<00:20, 18.48it/s]

Epoch 4:  81%|████████▏ | 1627/2000 [01:27<00:20, 18.54it/s]

Epoch 4:  81%|████████▏ | 1629/2000 [01:27<00:19, 18.57it/s]

Epoch 4:  82%|████████▏ | 1631/2000 [01:28<00:19, 18.60it/s]

Epoch 4:  82%|████████▏ | 1633/2000 [01:28<00:19, 18.63it/s]

Epoch 4:  82%|████████▏ | 1635/2000 [01:28<00:19, 18.65it/s]

Epoch 4:  82%|████████▏ | 1637/2000 [01:28<00:19, 18.66it/s]

Epoch 4:  82%|████████▏ | 1639/2000 [01:28<00:19, 18.56it/s]

Epoch 4:  82%|████████▏ | 1641/2000 [01:28<00:19, 18.58it/s]

Epoch 4:  82%|████████▏ | 1643/2000 [01:28<00:19, 18.60it/s]

Epoch 4:  82%|████████▏ | 1645/2000 [01:28<00:19, 18.63it/s]

Epoch 4:  82%|████████▏ | 1647/2000 [01:28<00:18, 18.63it/s]

Epoch 4:  82%|████████▏ | 1649/2000 [01:28<00:18, 18.63it/s]

Epoch 4:  83%|████████▎ | 1651/2000 [01:29<00:18, 18.64it/s]

Epoch 4:  83%|████████▎ | 1653/2000 [01:29<00:18, 18.65it/s]

Epoch 4:  83%|████████▎ | 1655/2000 [01:29<00:18, 18.65it/s]

Epoch 4:  83%|████████▎ | 1657/2000 [01:29<00:18, 18.64it/s]

Epoch 4:  83%|████████▎ | 1659/2000 [01:29<00:18, 18.65it/s]

Epoch 4:  83%|████████▎ | 1661/2000 [01:29<00:18, 18.64it/s]

Epoch 4:  83%|████████▎ | 1663/2000 [01:29<00:18, 18.65it/s]

Epoch 4:  83%|████████▎ | 1665/2000 [01:29<00:17, 18.66it/s]

Epoch 4:  83%|████████▎ | 1667/2000 [01:29<00:17, 18.65it/s]

Epoch 4:  83%|████████▎ | 1669/2000 [01:30<00:17, 18.63it/s]

Epoch 4:  84%|████████▎ | 1671/2000 [01:30<00:17, 18.63it/s]

Epoch 4:  84%|████████▎ | 1673/2000 [01:30<00:17, 18.65it/s]

Epoch 4:  84%|████████▍ | 1675/2000 [01:30<00:17, 18.64it/s]

Epoch 4:  84%|████████▍ | 1677/2000 [01:30<00:17, 18.64it/s]

Epoch 4:  84%|████████▍ | 1679/2000 [01:30<00:17, 18.64it/s]

Epoch 4:  84%|████████▍ | 1681/2000 [01:30<00:17, 18.64it/s]

Epoch 4:  84%|████████▍ | 1683/2000 [01:30<00:16, 18.65it/s]

Epoch 4:  84%|████████▍ | 1685/2000 [01:30<00:16, 18.66it/s]

Epoch 4:  84%|████████▍ | 1687/2000 [01:31<00:16, 18.64it/s]

Epoch 4:  84%|████████▍ | 1689/2000 [01:31<00:16, 18.64it/s]

Epoch 4:  85%|████████▍ | 1691/2000 [01:31<00:16, 18.65it/s]

Epoch 4:  85%|████████▍ | 1693/2000 [01:31<00:16, 18.65it/s]

Epoch 4:  85%|████████▍ | 1695/2000 [01:31<00:16, 18.66it/s]

Epoch 4:  85%|████████▍ | 1697/2000 [01:31<00:16, 18.65it/s]

Epoch 4:  85%|████████▍ | 1699/2000 [01:31<00:16, 18.66it/s]

Epoch 4:  85%|████████▌ | 1701/2000 [01:31<00:16, 18.64it/s]

Epoch 4:  85%|████████▌ | 1703/2000 [01:31<00:15, 18.64it/s]

Epoch 4:  85%|████████▌ | 1705/2000 [01:31<00:15, 18.64it/s]

Epoch 4:  85%|████████▌ | 1707/2000 [01:32<00:15, 18.64it/s]

Epoch 4:  85%|████████▌ | 1709/2000 [01:32<00:15, 18.63it/s]

Epoch 4:  86%|████████▌ | 1711/2000 [01:32<00:15, 18.63it/s]

Epoch 4:  86%|████████▌ | 1713/2000 [01:32<00:15, 18.64it/s]

Epoch 4:  86%|████████▌ | 1715/2000 [01:32<00:15, 18.64it/s]

Epoch 4:  86%|████████▌ | 1717/2000 [01:32<00:15, 18.65it/s]

Epoch 4:  86%|████████▌ | 1719/2000 [01:32<00:15, 18.65it/s]

Epoch 4:  86%|████████▌ | 1721/2000 [01:32<00:14, 18.67it/s]

Epoch 4:  86%|████████▌ | 1723/2000 [01:32<00:14, 18.64it/s]

Epoch 4:  86%|████████▋ | 1725/2000 [01:33<00:14, 18.64it/s]

Epoch 4:  86%|████████▋ | 1727/2000 [01:33<00:14, 18.64it/s]

Epoch 4:  86%|████████▋ | 1729/2000 [01:33<00:14, 18.65it/s]

Epoch 4:  87%|████████▋ | 1731/2000 [01:33<00:14, 18.64it/s]

Epoch 4:  87%|████████▋ | 1733/2000 [01:33<00:14, 18.64it/s]

Epoch 4:  87%|████████▋ | 1735/2000 [01:33<00:14, 18.64it/s]

Epoch 4:  87%|████████▋ | 1737/2000 [01:33<00:14, 18.63it/s]

Epoch 4:  87%|████████▋ | 1739/2000 [01:33<00:13, 18.65it/s]

Epoch 4:  87%|████████▋ | 1741/2000 [01:33<00:13, 18.63it/s]

Epoch 4:  87%|████████▋ | 1743/2000 [01:34<00:13, 18.63it/s]

Epoch 4:  87%|████████▋ | 1745/2000 [01:34<00:13, 18.65it/s]

Epoch 4:  87%|████████▋ | 1747/2000 [01:34<00:13, 18.65it/s]

Epoch 4:  87%|████████▋ | 1749/2000 [01:34<00:13, 18.65it/s]

Epoch 4:  88%|████████▊ | 1751/2000 [01:34<00:13, 18.65it/s]

Epoch 4:  88%|████████▊ | 1753/2000 [01:34<00:13, 18.65it/s]

Epoch 4:  88%|████████▊ | 1755/2000 [01:34<00:13, 18.65it/s]

Epoch 4:  88%|████████▊ | 1757/2000 [01:34<00:13, 18.67it/s]

Epoch 4:  88%|████████▊ | 1759/2000 [01:34<00:12, 18.66it/s]

Epoch 4:  88%|████████▊ | 1761/2000 [01:35<00:12, 18.65it/s]

Epoch 4:  88%|████████▊ | 1763/2000 [01:35<00:12, 18.67it/s]

Epoch 4:  88%|████████▊ | 1765/2000 [01:35<00:12, 18.66it/s]

Epoch 4:  88%|████████▊ | 1767/2000 [01:35<00:12, 18.66it/s]

Epoch 4:  88%|████████▊ | 1769/2000 [01:35<00:12, 18.66it/s]

Epoch 4:  89%|████████▊ | 1771/2000 [01:35<00:12, 18.67it/s]

Epoch 4:  89%|████████▊ | 1773/2000 [01:35<00:12, 18.65it/s]

Epoch 4:  89%|████████▉ | 1775/2000 [01:35<00:12, 18.65it/s]

Epoch 4:  89%|████████▉ | 1777/2000 [01:35<00:11, 18.65it/s]

Epoch 4:  89%|████████▉ | 1779/2000 [01:35<00:11, 18.64it/s]

Epoch 4:  89%|████████▉ | 1781/2000 [01:36<00:11, 18.64it/s]

Epoch 4:  89%|████████▉ | 1783/2000 [01:36<00:11, 18.66it/s]

Epoch 4:  89%|████████▉ | 1785/2000 [01:36<00:11, 18.66it/s]

Epoch 4:  89%|████████▉ | 1787/2000 [01:36<00:11, 18.66it/s]

Epoch 4:  89%|████████▉ | 1789/2000 [01:36<00:11, 18.66it/s]

Epoch 4:  90%|████████▉ | 1791/2000 [01:36<00:11, 18.66it/s]

Epoch 4:  90%|████████▉ | 1793/2000 [01:36<00:11, 18.65it/s]

Epoch 4:  90%|████████▉ | 1795/2000 [01:36<00:10, 18.66it/s]

Epoch 4:  90%|████████▉ | 1797/2000 [01:36<00:10, 18.65it/s]

Epoch 4:  90%|████████▉ | 1799/2000 [01:37<00:10, 18.66it/s]

Epoch 4:  90%|█████████ | 1801/2000 [01:37<00:10, 18.67it/s]

Epoch 4:  90%|█████████ | 1803/2000 [01:37<00:10, 18.67it/s]

Epoch 4:  90%|█████████ | 1805/2000 [01:37<00:10, 18.67it/s]

Epoch 4:  90%|█████████ | 1807/2000 [01:37<00:10, 18.68it/s]

Epoch 4:  90%|█████████ | 1809/2000 [01:37<00:10, 18.68it/s]

Epoch 4:  91%|█████████ | 1811/2000 [01:37<00:10, 18.69it/s]

Epoch 4:  91%|█████████ | 1813/2000 [01:37<00:10, 18.69it/s]

Epoch 4:  91%|█████████ | 1815/2000 [01:37<00:09, 18.68it/s]

Epoch 4:  91%|█████████ | 1817/2000 [01:38<00:09, 18.67it/s]

Epoch 4:  91%|█████████ | 1819/2000 [01:38<00:09, 18.68it/s]

Epoch 4:  91%|█████████ | 1821/2000 [01:38<00:09, 18.68it/s]

Epoch 4:  91%|█████████ | 1823/2000 [01:38<00:09, 18.66it/s]

Epoch 4:  91%|█████████▏| 1825/2000 [01:38<00:09, 18.67it/s]

Epoch 4:  91%|█████████▏| 1827/2000 [01:38<00:09, 18.67it/s]

Epoch 4:  91%|█████████▏| 1829/2000 [01:38<00:09, 18.68it/s]

Epoch 4:  92%|█████████▏| 1831/2000 [01:38<00:09, 18.68it/s]

Epoch 4:  92%|█████████▏| 1833/2000 [01:38<00:08, 18.69it/s]

Epoch 4:  92%|█████████▏| 1835/2000 [01:38<00:08, 18.68it/s]

Epoch 4:  92%|█████████▏| 1837/2000 [01:39<00:08, 18.68it/s]

Epoch 4:  92%|█████████▏| 1839/2000 [01:39<00:08, 18.63it/s]

Epoch 4:  92%|█████████▏| 1841/2000 [01:39<00:08, 18.64it/s]

Epoch 4:  92%|█████████▏| 1843/2000 [01:39<00:08, 18.64it/s]

Epoch 4:  92%|█████████▏| 1845/2000 [01:39<00:08, 18.65it/s]

Epoch 4:  92%|█████████▏| 1847/2000 [01:39<00:08, 18.65it/s]

Epoch 4:  92%|█████████▏| 1849/2000 [01:39<00:08, 18.66it/s]

Epoch 4:  93%|█████████▎| 1851/2000 [01:39<00:07, 18.65it/s]

Epoch 4:  93%|█████████▎| 1853/2000 [01:39<00:07, 18.65it/s]

Epoch 4:  93%|█████████▎| 1855/2000 [01:40<00:07, 18.64it/s]

Epoch 4:  93%|█████████▎| 1857/2000 [01:40<00:07, 18.65it/s]

Epoch 4:  93%|█████████▎| 1859/2000 [01:40<00:07, 18.66it/s]

Epoch 4:  93%|█████████▎| 1861/2000 [01:40<00:07, 18.67it/s]

Epoch 4:  93%|█████████▎| 1863/2000 [01:40<00:07, 18.66it/s]

Epoch 4:  93%|█████████▎| 1865/2000 [01:40<00:07, 18.67it/s]

Epoch 4:  93%|█████████▎| 1867/2000 [01:40<00:07, 18.63it/s]

Epoch 4:  93%|█████████▎| 1869/2000 [01:40<00:07, 18.65it/s]

Epoch 4:  94%|█████████▎| 1871/2000 [01:40<00:06, 18.66it/s]

Epoch 4:  94%|█████████▎| 1873/2000 [01:41<00:06, 18.65it/s]

Epoch 4:  94%|█████████▍| 1875/2000 [01:41<00:06, 18.65it/s]

Epoch 4:  94%|█████████▍| 1877/2000 [01:41<00:06, 18.66it/s]

Epoch 4:  94%|█████████▍| 1879/2000 [01:41<00:06, 18.67it/s]

Epoch 4:  94%|█████████▍| 1881/2000 [01:41<00:06, 18.66it/s]

Epoch 4:  94%|█████████▍| 1883/2000 [01:41<00:06, 18.67it/s]

Epoch 4:  94%|█████████▍| 1885/2000 [01:41<00:06, 18.68it/s]

Epoch 4:  94%|█████████▍| 1887/2000 [01:41<00:06, 18.67it/s]

Epoch 4:  94%|█████████▍| 1889/2000 [01:41<00:05, 18.66it/s]

Epoch 4:  95%|█████████▍| 1891/2000 [01:41<00:05, 18.67it/s]

Epoch 4:  95%|█████████▍| 1893/2000 [01:42<00:05, 18.67it/s]

Epoch 4:  95%|█████████▍| 1895/2000 [01:42<00:05, 18.66it/s]

Epoch 4:  95%|█████████▍| 1897/2000 [01:42<00:05, 18.67it/s]

Epoch 4:  95%|█████████▍| 1899/2000 [01:42<00:05, 18.66it/s]

Epoch 4:  95%|█████████▌| 1901/2000 [01:42<00:05, 18.67it/s]

Epoch 4:  95%|█████████▌| 1903/2000 [01:42<00:05, 18.68it/s]

Epoch 4:  95%|█████████▌| 1905/2000 [01:42<00:05, 18.68it/s]

Epoch 4:  95%|█████████▌| 1907/2000 [01:42<00:04, 18.67it/s]

Epoch 4:  95%|█████████▌| 1909/2000 [01:42<00:04, 18.67it/s]

Epoch 4:  96%|█████████▌| 1911/2000 [01:43<00:04, 18.66it/s]

Epoch 4:  96%|█████████▌| 1913/2000 [01:43<00:04, 18.65it/s]

Epoch 4:  96%|█████████▌| 1915/2000 [01:43<00:04, 18.67it/s]

Epoch 4:  96%|█████████▌| 1917/2000 [01:43<00:04, 18.68it/s]

Epoch 4:  96%|█████████▌| 1919/2000 [01:43<00:04, 18.68it/s]

Epoch 4:  96%|█████████▌| 1921/2000 [01:43<00:04, 18.66it/s]

Epoch 4:  96%|█████████▌| 1923/2000 [01:43<00:04, 18.65it/s]

Epoch 4:  96%|█████████▋| 1925/2000 [01:43<00:04, 18.66it/s]

Epoch 4:  96%|█████████▋| 1927/2000 [01:43<00:03, 18.66it/s]

Epoch 4:  96%|█████████▋| 1929/2000 [01:44<00:03, 18.67it/s]

Epoch 4:  97%|█████████▋| 1931/2000 [01:44<00:03, 18.68it/s]

Epoch 4:  97%|█████████▋| 1933/2000 [01:44<00:03, 18.67it/s]

Epoch 4:  97%|█████████▋| 1935/2000 [01:44<00:03, 18.66it/s]

Epoch 4:  97%|█████████▋| 1937/2000 [01:44<00:03, 18.66it/s]

Epoch 4:  97%|█████████▋| 1939/2000 [01:44<00:03, 18.66it/s]

Epoch 4:  97%|█████████▋| 1941/2000 [01:44<00:03, 18.67it/s]

Epoch 4:  97%|█████████▋| 1943/2000 [01:44<00:03, 18.66it/s]

Epoch 4:  97%|█████████▋| 1945/2000 [01:44<00:02, 18.61it/s]

Epoch 4:  97%|█████████▋| 1947/2000 [01:44<00:02, 18.63it/s]

Epoch 4:  97%|█████████▋| 1949/2000 [01:45<00:02, 18.63it/s]

Epoch 4:  98%|█████████▊| 1951/2000 [01:45<00:02, 18.64it/s]

Epoch 4:  98%|█████████▊| 1953/2000 [01:45<00:02, 18.65it/s]

Epoch 4:  98%|█████████▊| 1955/2000 [01:45<00:02, 18.65it/s]

Epoch 4:  98%|█████████▊| 1957/2000 [01:45<00:02, 18.66it/s]

Epoch 4:  98%|█████████▊| 1959/2000 [01:45<00:02, 18.68it/s]

Epoch 4:  98%|█████████▊| 1961/2000 [01:45<00:02, 18.68it/s]

Epoch 4:  98%|█████████▊| 1963/2000 [01:45<00:01, 18.68it/s]

Epoch 4:  98%|█████████▊| 1965/2000 [01:45<00:01, 18.68it/s]

Epoch 4:  98%|█████████▊| 1967/2000 [01:46<00:01, 18.67it/s]

Epoch 4:  98%|█████████▊| 1969/2000 [01:46<00:01, 18.67it/s]

Epoch 4:  99%|█████████▊| 1971/2000 [01:46<00:01, 18.68it/s]

Epoch 4:  99%|█████████▊| 1973/2000 [01:46<00:01, 18.68it/s]

Epoch 4:  99%|█████████▉| 1975/2000 [01:46<00:01, 18.68it/s]

Epoch 4:  99%|█████████▉| 1977/2000 [01:46<00:01, 18.67it/s]

Epoch 4:  99%|█████████▉| 1979/2000 [01:46<00:01, 18.68it/s]

Epoch 4:  99%|█████████▉| 1981/2000 [01:46<00:01, 18.67it/s]

Epoch 4:  99%|█████████▉| 1983/2000 [01:46<00:00, 18.68it/s]

Epoch 4:  99%|█████████▉| 1985/2000 [01:47<00:00, 18.69it/s]

Epoch 4:  99%|█████████▉| 1987/2000 [01:47<00:00, 18.69it/s]

Epoch 4:  99%|█████████▉| 1989/2000 [01:47<00:00, 18.68it/s]

Epoch 4: 100%|█████████▉| 1991/2000 [01:47<00:00, 18.69it/s]

Epoch 4: 100%|█████████▉| 1993/2000 [01:47<00:00, 18.69it/s]

Epoch 4: 100%|█████████▉| 1995/2000 [01:47<00:00, 18.68it/s]

Epoch 4: 100%|█████████▉| 1997/2000 [01:47<00:00, 18.67it/s]

Epoch 4: 100%|█████████▉| 1999/2000 [01:47<00:00, 18.67it/s]

Epoch 4: loss=0.2243, val_proxy=0.9402

Epoch 5:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 5:   0%|          | 2/2000 [00:00<01:50, 18.15it/s]

Epoch 5:   0%|          | 4/2000 [00:00<01:48, 18.46it/s]

Epoch 5:   0%|          | 6/2000 [00:00<01:47, 18.54it/s]

Epoch 5:   0%|          | 8/2000 [00:00<01:47, 18.58it/s]

Epoch 5:   0%|          | 10/2000 [00:00<01:46, 18.62it/s]

Epoch 5:   1%|          | 12/2000 [00:00<01:46, 18.64it/s]

Epoch 5:   1%|          | 14/2000 [00:00<01:46, 18.66it/s]

Epoch 5:   1%|          | 16/2000 [00:00<01:46, 18.67it/s]

Epoch 5:   1%|          | 18/2000 [00:00<01:46, 18.67it/s]

Epoch 5:   1%|          | 20/2000 [00:01<01:46, 18.67it/s]

Epoch 5:   1%|          | 22/2000 [00:01<01:45, 18.68it/s]

Epoch 5:   1%|          | 24/2000 [00:01<01:45, 18.66it/s]

Epoch 5:   1%|▏         | 26/2000 [00:01<01:45, 18.67it/s]

Epoch 5:   1%|▏         | 28/2000 [00:01<01:45, 18.67it/s]

Epoch 5:   2%|▏         | 30/2000 [00:01<01:45, 18.69it/s]

Epoch 5:   2%|▏         | 32/2000 [00:01<01:45, 18.68it/s]

Epoch 5:   2%|▏         | 34/2000 [00:01<01:45, 18.68it/s]

Epoch 5:   2%|▏         | 36/2000 [00:01<01:45, 18.69it/s]

Epoch 5:   2%|▏         | 38/2000 [00:02<01:44, 18.70it/s]

Epoch 5:   2%|▏         | 40/2000 [00:02<01:44, 18.69it/s]

Epoch 5:   2%|▏         | 42/2000 [00:02<01:44, 18.68it/s]

Epoch 5:   2%|▏         | 44/2000 [00:02<01:44, 18.68it/s]

Epoch 5:   2%|▏         | 46/2000 [00:02<01:44, 18.69it/s]

Epoch 5:   2%|▏         | 48/2000 [00:02<01:44, 18.68it/s]

Epoch 5:   2%|▎         | 50/2000 [00:02<01:44, 18.70it/s]

Epoch 5:   3%|▎         | 52/2000 [00:02<01:44, 18.69it/s]

Epoch 5:   3%|▎         | 54/2000 [00:02<01:44, 18.68it/s]

Epoch 5:   3%|▎         | 56/2000 [00:03<01:44, 18.69it/s]

Epoch 5:   3%|▎         | 58/2000 [00:03<01:43, 18.70it/s]

Epoch 5:   3%|▎         | 60/2000 [00:03<01:43, 18.71it/s]

Epoch 5:   3%|▎         | 62/2000 [00:03<01:43, 18.71it/s]

Epoch 5:   3%|▎         | 64/2000 [00:03<01:43, 18.70it/s]

Epoch 5:   3%|▎         | 66/2000 [00:03<01:43, 18.71it/s]

Epoch 5:   3%|▎         | 68/2000 [00:03<01:43, 18.71it/s]

Epoch 5:   4%|▎         | 70/2000 [00:03<01:43, 18.71it/s]

Epoch 5:   4%|▎         | 72/2000 [00:03<01:43, 18.71it/s]

Epoch 5:   4%|▎         | 74/2000 [00:03<01:43, 18.70it/s]

Epoch 5:   4%|▍         | 76/2000 [00:04<01:42, 18.70it/s]

Epoch 5:   4%|▍         | 78/2000 [00:04<01:42, 18.70it/s]

Epoch 5:   4%|▍         | 80/2000 [00:04<01:42, 18.70it/s]

Epoch 5:   4%|▍         | 82/2000 [00:04<01:42, 18.70it/s]

Epoch 5:   4%|▍         | 84/2000 [00:04<01:42, 18.71it/s]

Epoch 5:   4%|▍         | 86/2000 [00:04<01:42, 18.71it/s]

Epoch 5:   4%|▍         | 88/2000 [00:04<01:42, 18.71it/s]

Epoch 5:   4%|▍         | 90/2000 [00:04<01:42, 18.70it/s]

Epoch 5:   5%|▍         | 92/2000 [00:04<01:42, 18.70it/s]

Epoch 5:   5%|▍         | 94/2000 [00:05<01:42, 18.68it/s]

Epoch 5:   5%|▍         | 96/2000 [00:05<01:41, 18.67it/s]

Epoch 5:   5%|▍         | 98/2000 [00:05<01:41, 18.68it/s]

Epoch 5:   5%|▌         | 100/2000 [00:05<01:41, 18.69it/s]

Epoch 5:   5%|▌         | 102/2000 [00:05<01:41, 18.69it/s]

Epoch 5:   5%|▌         | 104/2000 [00:05<01:41, 18.69it/s]

Epoch 5:   5%|▌         | 106/2000 [00:05<01:41, 18.71it/s]

Epoch 5:   5%|▌         | 108/2000 [00:05<01:41, 18.71it/s]

Epoch 5:   6%|▌         | 110/2000 [00:05<01:41, 18.71it/s]

Epoch 5:   6%|▌         | 112/2000 [00:05<01:40, 18.71it/s]

Epoch 5:   6%|▌         | 114/2000 [00:06<01:40, 18.71it/s]

Epoch 5:   6%|▌         | 116/2000 [00:06<01:40, 18.71it/s]

Epoch 5:   6%|▌         | 118/2000 [00:06<01:40, 18.68it/s]

Epoch 5:   6%|▌         | 120/2000 [00:06<01:40, 18.69it/s]

Epoch 5:   6%|▌         | 122/2000 [00:06<01:40, 18.70it/s]

Epoch 5:   6%|▌         | 124/2000 [00:06<01:40, 18.70it/s]

Epoch 5:   6%|▋         | 126/2000 [00:06<01:40, 18.70it/s]

Epoch 5:   6%|▋         | 128/2000 [00:06<01:40, 18.69it/s]

Epoch 5:   6%|▋         | 130/2000 [00:06<01:40, 18.68it/s]

Epoch 5:   7%|▋         | 132/2000 [00:07<01:39, 18.68it/s]

Epoch 5:   7%|▋         | 134/2000 [00:07<01:39, 18.69it/s]

Epoch 5:   7%|▋         | 136/2000 [00:07<01:39, 18.70it/s]

Epoch 5:   7%|▋         | 138/2000 [00:07<01:39, 18.69it/s]

Epoch 5:   7%|▋         | 140/2000 [00:07<01:39, 18.70it/s]

Epoch 5:   7%|▋         | 142/2000 [00:07<01:39, 18.68it/s]

Epoch 5:   7%|▋         | 144/2000 [00:07<01:39, 18.69it/s]

Epoch 5:   7%|▋         | 146/2000 [00:07<01:39, 18.70it/s]

Epoch 5:   7%|▋         | 148/2000 [00:07<01:39, 18.71it/s]

Epoch 5:   8%|▊         | 150/2000 [00:08<01:38, 18.71it/s]

Epoch 5:   8%|▊         | 152/2000 [00:08<01:38, 18.70it/s]

Epoch 5:   8%|▊         | 154/2000 [00:08<01:38, 18.70it/s]

Epoch 5:   8%|▊         | 156/2000 [00:08<01:38, 18.69it/s]

Epoch 5:   8%|▊         | 158/2000 [00:08<01:38, 18.70it/s]

Epoch 5:   8%|▊         | 160/2000 [00:08<01:38, 18.69it/s]

Epoch 5:   8%|▊         | 162/2000 [00:08<01:38, 18.70it/s]

Epoch 5:   8%|▊         | 164/2000 [00:08<01:38, 18.70it/s]

Epoch 5:   8%|▊         | 166/2000 [00:08<01:38, 18.70it/s]

Epoch 5:   8%|▊         | 168/2000 [00:08<01:37, 18.71it/s]

Epoch 5:   8%|▊         | 170/2000 [00:09<01:37, 18.71it/s]

Epoch 5:   9%|▊         | 172/2000 [00:09<01:37, 18.71it/s]

Epoch 5:   9%|▊         | 174/2000 [00:09<01:37, 18.71it/s]

Epoch 5:   9%|▉         | 176/2000 [00:09<01:37, 18.70it/s]

Epoch 5:   9%|▉         | 178/2000 [00:09<01:37, 18.71it/s]

Epoch 5:   9%|▉         | 180/2000 [00:09<01:37, 18.71it/s]

Epoch 5:   9%|▉         | 182/2000 [00:09<01:37, 18.71it/s]

Epoch 5:   9%|▉         | 184/2000 [00:09<01:37, 18.72it/s]

Epoch 5:   9%|▉         | 186/2000 [00:09<01:36, 18.72it/s]

Epoch 5:   9%|▉         | 188/2000 [00:10<01:36, 18.71it/s]

Epoch 5:  10%|▉         | 190/2000 [00:10<01:36, 18.70it/s]

Epoch 5:  10%|▉         | 192/2000 [00:10<01:36, 18.70it/s]

Epoch 5:  10%|▉         | 194/2000 [00:10<01:36, 18.68it/s]

Epoch 5:  10%|▉         | 196/2000 [00:10<01:36, 18.70it/s]

Epoch 5:  10%|▉         | 198/2000 [00:10<01:36, 18.71it/s]

Epoch 5:  10%|█         | 200/2000 [00:10<01:36, 18.69it/s]

Epoch 5:  10%|█         | 202/2000 [00:10<01:36, 18.70it/s]

Epoch 5:  10%|█         | 204/2000 [00:10<01:36, 18.68it/s]

Epoch 5:  10%|█         | 206/2000 [00:11<01:36, 18.68it/s]

Epoch 5:  10%|█         | 208/2000 [00:11<01:35, 18.68it/s]

Epoch 5:  10%|█         | 210/2000 [00:11<01:35, 18.69it/s]

Epoch 5:  11%|█         | 212/2000 [00:11<01:35, 18.69it/s]

Epoch 5:  11%|█         | 214/2000 [00:11<01:35, 18.69it/s]

Epoch 5:  11%|█         | 216/2000 [00:11<01:35, 18.70it/s]

Epoch 5:  11%|█         | 218/2000 [00:11<01:35, 18.71it/s]

Epoch 5:  11%|█         | 220/2000 [00:11<01:35, 18.71it/s]

Epoch 5:  11%|█         | 222/2000 [00:11<01:35, 18.71it/s]

Epoch 5:  11%|█         | 224/2000 [00:11<01:34, 18.71it/s]

Epoch 5:  11%|█▏        | 226/2000 [00:12<01:34, 18.72it/s]

Epoch 5:  11%|█▏        | 228/2000 [00:12<01:34, 18.71it/s]

Epoch 5:  12%|█▏        | 230/2000 [00:12<01:34, 18.71it/s]

Epoch 5:  12%|█▏        | 232/2000 [00:12<01:34, 18.68it/s]

Epoch 5:  12%|█▏        | 234/2000 [00:12<01:34, 18.68it/s]

Epoch 5:  12%|█▏        | 236/2000 [00:12<01:34, 18.68it/s]

Epoch 5:  12%|█▏        | 238/2000 [00:12<01:34, 18.69it/s]

Epoch 5:  12%|█▏        | 240/2000 [00:12<01:34, 18.68it/s]

Epoch 5:  12%|█▏        | 242/2000 [00:12<01:34, 18.68it/s]

Epoch 5:  12%|█▏        | 244/2000 [00:13<01:33, 18.69it/s]

Epoch 5:  12%|█▏        | 246/2000 [00:13<01:33, 18.69it/s]

Epoch 5:  12%|█▏        | 248/2000 [00:13<01:33, 18.69it/s]

Epoch 5:  12%|█▎        | 250/2000 [00:13<01:33, 18.70it/s]

Epoch 5:  13%|█▎        | 252/2000 [00:13<01:33, 18.69it/s]

Epoch 5:  13%|█▎        | 254/2000 [00:13<01:33, 18.68it/s]

Epoch 5:  13%|█▎        | 256/2000 [00:13<01:33, 18.69it/s]

Epoch 5:  13%|█▎        | 258/2000 [00:13<01:33, 18.70it/s]

Epoch 5:  13%|█▎        | 260/2000 [00:13<01:33, 18.68it/s]

Epoch 5:  13%|█▎        | 262/2000 [00:14<01:33, 18.67it/s]

Epoch 5:  13%|█▎        | 264/2000 [00:14<01:32, 18.67it/s]

Epoch 5:  13%|█▎        | 266/2000 [00:14<01:32, 18.68it/s]

Epoch 5:  13%|█▎        | 268/2000 [00:14<01:32, 18.69it/s]

Epoch 5:  14%|█▎        | 270/2000 [00:14<01:32, 18.68it/s]

Epoch 5:  14%|█▎        | 272/2000 [00:14<01:32, 18.68it/s]

Epoch 5:  14%|█▎        | 274/2000 [00:14<01:32, 18.67it/s]

Epoch 5:  14%|█▍        | 276/2000 [00:14<01:32, 18.67it/s]

Epoch 5:  14%|█▍        | 278/2000 [00:14<01:32, 18.67it/s]

Epoch 5:  14%|█▍        | 280/2000 [00:14<01:32, 18.67it/s]

Epoch 5:  14%|█▍        | 282/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  14%|█▍        | 284/2000 [00:15<01:31, 18.69it/s]

Epoch 5:  14%|█▍        | 286/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  14%|█▍        | 288/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  14%|█▍        | 290/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  15%|█▍        | 292/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  15%|█▍        | 294/2000 [00:15<01:31, 18.67it/s]

Epoch 5:  15%|█▍        | 296/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  15%|█▍        | 298/2000 [00:15<01:31, 18.68it/s]

Epoch 5:  15%|█▌        | 300/2000 [00:16<01:30, 18.68it/s]

Epoch 5:  15%|█▌        | 302/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  15%|█▌        | 304/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  15%|█▌        | 306/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  15%|█▌        | 308/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  16%|█▌        | 310/2000 [00:16<01:30, 18.66it/s]

Epoch 5:  16%|█▌        | 312/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  16%|█▌        | 314/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  16%|█▌        | 316/2000 [00:16<01:30, 18.67it/s]

Epoch 5:  16%|█▌        | 318/2000 [00:17<01:30, 18.68it/s]

Epoch 5:  16%|█▌        | 320/2000 [00:17<01:29, 18.68it/s]

Epoch 5:  16%|█▌        | 322/2000 [00:17<01:29, 18.69it/s]

Epoch 5:  16%|█▌        | 324/2000 [00:17<01:29, 18.69it/s]

Epoch 5:  16%|█▋        | 326/2000 [00:17<01:29, 18.69it/s]

Epoch 5:  16%|█▋        | 328/2000 [00:17<01:29, 18.68it/s]

Epoch 5:  16%|█▋        | 330/2000 [00:17<01:29, 18.68it/s]

Epoch 5:  17%|█▋        | 332/2000 [00:17<01:29, 18.69it/s]

Epoch 5:  17%|█▋        | 334/2000 [00:17<01:29, 18.69it/s]

Epoch 5:  17%|█▋        | 336/2000 [00:17<01:29, 18.68it/s]

Epoch 5:  17%|█▋        | 338/2000 [00:18<01:28, 18.69it/s]

Epoch 5:  17%|█▋        | 340/2000 [00:18<01:28, 18.69it/s]

Epoch 5:  17%|█▋        | 342/2000 [00:18<01:28, 18.69it/s]

Epoch 5:  17%|█▋        | 344/2000 [00:18<01:28, 18.70it/s]

Epoch 5:  17%|█▋        | 346/2000 [00:18<01:28, 18.70it/s]

Epoch 5:  17%|█▋        | 348/2000 [00:18<01:28, 18.71it/s]

Epoch 5:  18%|█▊        | 350/2000 [00:18<01:28, 18.70it/s]

Epoch 5:  18%|█▊        | 352/2000 [00:18<01:28, 18.71it/s]

Epoch 5:  18%|█▊        | 354/2000 [00:18<01:27, 18.71it/s]

Epoch 5:  18%|█▊        | 356/2000 [00:19<01:27, 18.71it/s]

Epoch 5:  18%|█▊        | 358/2000 [00:19<01:27, 18.69it/s]

Epoch 5:  18%|█▊        | 360/2000 [00:19<01:27, 18.69it/s]

Epoch 5:  18%|█▊        | 362/2000 [00:19<01:27, 18.69it/s]

Epoch 5:  18%|█▊        | 364/2000 [00:19<01:27, 18.70it/s]

Epoch 5:  18%|█▊        | 366/2000 [00:19<01:27, 18.70it/s]

Epoch 5:  18%|█▊        | 368/2000 [00:19<01:27, 18.69it/s]

Epoch 5:  18%|█▊        | 370/2000 [00:19<01:27, 18.69it/s]

Epoch 5:  19%|█▊        | 372/2000 [00:19<01:27, 18.69it/s]

Epoch 5:  19%|█▊        | 374/2000 [00:20<01:27, 18.68it/s]

Epoch 5:  19%|█▉        | 376/2000 [00:20<01:26, 18.68it/s]

Epoch 5:  19%|█▉        | 378/2000 [00:20<01:26, 18.68it/s]

Epoch 5:  19%|█▉        | 380/2000 [00:20<01:26, 18.69it/s]

Epoch 5:  19%|█▉        | 382/2000 [00:20<01:26, 18.68it/s]

Epoch 5:  19%|█▉        | 384/2000 [00:20<01:26, 18.68it/s]

Epoch 5:  19%|█▉        | 386/2000 [00:20<01:26, 18.68it/s]

Epoch 5:  19%|█▉        | 388/2000 [00:20<01:26, 18.68it/s]

Epoch 5:  20%|█▉        | 390/2000 [00:20<01:26, 18.69it/s]

Epoch 5:  20%|█▉        | 392/2000 [00:20<01:26, 18.67it/s]

Epoch 5:  20%|█▉        | 394/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|█▉        | 396/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|█▉        | 398/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|██        | 400/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|██        | 402/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|██        | 404/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|██        | 406/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  20%|██        | 408/2000 [00:21<01:25, 18.67it/s]

Epoch 5:  20%|██        | 410/2000 [00:21<01:25, 18.68it/s]

Epoch 5:  21%|██        | 412/2000 [00:22<01:25, 18.68it/s]

Epoch 5:  21%|██        | 414/2000 [00:22<01:24, 18.68it/s]

Epoch 5:  21%|██        | 416/2000 [00:22<01:24, 18.69it/s]

Epoch 5:  21%|██        | 418/2000 [00:22<01:24, 18.68it/s]

Epoch 5:  21%|██        | 420/2000 [00:22<01:24, 18.69it/s]

Epoch 5:  21%|██        | 422/2000 [00:22<01:24, 18.68it/s]

Epoch 5:  21%|██        | 424/2000 [00:22<01:24, 18.67it/s]

Epoch 5:  21%|██▏       | 426/2000 [00:22<01:24, 18.67it/s]

Epoch 5:  21%|██▏       | 428/2000 [00:22<01:24, 18.67it/s]

Epoch 5:  22%|██▏       | 430/2000 [00:23<01:24, 18.67it/s]

Epoch 5:  22%|██▏       | 432/2000 [00:23<01:23, 18.68it/s]

Epoch 5:  22%|██▏       | 434/2000 [00:23<01:23, 18.67it/s]

Epoch 5:  22%|██▏       | 436/2000 [00:23<01:23, 18.68it/s]

Epoch 5:  22%|██▏       | 438/2000 [00:23<01:23, 18.68it/s]

Epoch 5:  22%|██▏       | 440/2000 [00:23<01:23, 18.68it/s]

Epoch 5:  22%|██▏       | 442/2000 [00:23<01:23, 18.67it/s]

Epoch 5:  22%|██▏       | 444/2000 [00:23<01:23, 18.69it/s]

Epoch 5:  22%|██▏       | 446/2000 [00:23<01:23, 18.69it/s]

Epoch 5:  22%|██▏       | 448/2000 [00:23<01:23, 18.68it/s]

Epoch 5:  22%|██▎       | 450/2000 [00:24<01:22, 18.69it/s]

Epoch 5:  23%|██▎       | 452/2000 [00:24<01:22, 18.69it/s]

Epoch 5:  23%|██▎       | 454/2000 [00:24<01:22, 18.69it/s]

Epoch 5:  23%|██▎       | 456/2000 [00:24<01:22, 18.68it/s]

Epoch 5:  23%|██▎       | 458/2000 [00:24<01:22, 18.69it/s]

Epoch 5:  23%|██▎       | 460/2000 [00:24<01:22, 18.69it/s]

Epoch 5:  23%|██▎       | 462/2000 [00:24<01:22, 18.70it/s]

Epoch 5:  23%|██▎       | 464/2000 [00:24<01:22, 18.71it/s]

Epoch 5:  23%|██▎       | 466/2000 [00:24<01:22, 18.70it/s]

Epoch 5:  23%|██▎       | 468/2000 [00:25<01:21, 18.68it/s]

Epoch 5:  24%|██▎       | 470/2000 [00:25<01:22, 18.57it/s]

Epoch 5:  24%|██▎       | 472/2000 [00:25<01:22, 18.59it/s]

Epoch 5:  24%|██▎       | 474/2000 [00:25<01:22, 18.43it/s]

Epoch 5:  24%|██▍       | 476/2000 [00:25<01:24, 18.03it/s]

Epoch 5:  24%|██▍       | 478/2000 [00:25<01:24, 17.94it/s]

Epoch 5:  24%|██▍       | 480/2000 [00:25<01:24, 17.93it/s]

Epoch 5:  24%|██▍       | 482/2000 [00:25<01:23, 18.11it/s]

Epoch 5:  24%|██▍       | 484/2000 [00:25<01:23, 18.19it/s]

Epoch 5:  24%|██▍       | 486/2000 [00:26<01:23, 18.22it/s]

Epoch 5:  24%|██▍       | 488/2000 [00:26<01:22, 18.29it/s]

Epoch 5:  24%|██▍       | 490/2000 [00:26<01:22, 18.40it/s]

Epoch 5:  25%|██▍       | 492/2000 [00:26<01:21, 18.46it/s]

Epoch 5:  25%|██▍       | 494/2000 [00:26<01:21, 18.48it/s]

Epoch 5:  25%|██▍       | 496/2000 [00:26<01:21, 18.52it/s]

Epoch 5:  25%|██▍       | 498/2000 [00:26<01:20, 18.57it/s]

Epoch 5:  25%|██▌       | 500/2000 [00:26<01:20, 18.60it/s]

Epoch 5:  25%|██▌       | 502/2000 [00:26<01:20, 18.62it/s]

Epoch 5:  25%|██▌       | 504/2000 [00:27<01:20, 18.64it/s]

Epoch 5:  25%|██▌       | 506/2000 [00:27<01:20, 18.65it/s]

Epoch 5:  25%|██▌       | 508/2000 [00:27<01:19, 18.67it/s]

Epoch 5:  26%|██▌       | 510/2000 [00:27<01:19, 18.69it/s]

Epoch 5:  26%|██▌       | 512/2000 [00:27<01:19, 18.69it/s]

Epoch 5:  26%|██▌       | 514/2000 [00:27<01:19, 18.69it/s]

Epoch 5:  26%|██▌       | 516/2000 [00:27<01:19, 18.70it/s]

Epoch 5:  26%|██▌       | 518/2000 [00:27<01:19, 18.72it/s]

Epoch 5:  26%|██▌       | 520/2000 [00:27<01:19, 18.71it/s]

Epoch 5:  26%|██▌       | 522/2000 [00:27<01:18, 18.71it/s]

Epoch 5:  26%|██▌       | 524/2000 [00:28<01:18, 18.71it/s]

Epoch 5:  26%|██▋       | 526/2000 [00:28<01:18, 18.70it/s]

Epoch 5:  26%|██▋       | 528/2000 [00:28<01:18, 18.70it/s]

Epoch 5:  26%|██▋       | 530/2000 [00:28<01:18, 18.71it/s]

Epoch 5:  27%|██▋       | 532/2000 [00:28<01:18, 18.72it/s]

Epoch 5:  27%|██▋       | 534/2000 [00:28<01:18, 18.71it/s]

Epoch 5:  27%|██▋       | 536/2000 [00:28<01:18, 18.71it/s]

Epoch 5:  27%|██▋       | 538/2000 [00:28<01:18, 18.72it/s]

Epoch 5:  27%|██▋       | 540/2000 [00:28<01:17, 18.72it/s]

Epoch 5:  27%|██▋       | 542/2000 [00:29<01:17, 18.71it/s]

Epoch 5:  27%|██▋       | 544/2000 [00:29<01:17, 18.72it/s]

Epoch 5:  27%|██▋       | 546/2000 [00:29<01:17, 18.70it/s]

Epoch 5:  27%|██▋       | 548/2000 [00:29<01:17, 18.70it/s]

Epoch 5:  28%|██▊       | 550/2000 [00:29<01:17, 18.70it/s]

Epoch 5:  28%|██▊       | 552/2000 [00:29<01:17, 18.70it/s]

Epoch 5:  28%|██▊       | 554/2000 [00:29<01:17, 18.70it/s]

Epoch 5:  28%|██▊       | 556/2000 [00:29<01:17, 18.69it/s]

Epoch 5:  28%|██▊       | 558/2000 [00:29<01:17, 18.68it/s]

Epoch 5:  28%|██▊       | 560/2000 [00:29<01:17, 18.67it/s]

Epoch 5:  28%|██▊       | 562/2000 [00:30<01:16, 18.69it/s]

Epoch 5:  28%|██▊       | 564/2000 [00:30<01:16, 18.70it/s]

Epoch 5:  28%|██▊       | 566/2000 [00:30<01:16, 18.68it/s]

Epoch 5:  28%|██▊       | 568/2000 [00:30<01:16, 18.69it/s]

Epoch 5:  28%|██▊       | 570/2000 [00:30<01:16, 18.68it/s]

Epoch 5:  29%|██▊       | 572/2000 [00:30<01:16, 18.67it/s]

Epoch 5:  29%|██▊       | 574/2000 [00:30<01:16, 18.68it/s]

Epoch 5:  29%|██▉       | 576/2000 [00:30<01:16, 18.68it/s]

Epoch 5:  29%|██▉       | 578/2000 [00:30<01:16, 18.67it/s]

Epoch 5:  29%|██▉       | 580/2000 [00:31<01:16, 18.68it/s]

Epoch 5:  29%|██▉       | 582/2000 [00:31<01:15, 18.69it/s]

Epoch 5:  29%|██▉       | 584/2000 [00:31<01:15, 18.68it/s]

Epoch 5:  29%|██▉       | 586/2000 [00:31<01:15, 18.68it/s]

Epoch 5:  29%|██▉       | 588/2000 [00:31<01:15, 18.68it/s]

Epoch 5:  30%|██▉       | 590/2000 [00:31<01:15, 18.69it/s]

Epoch 5:  30%|██▉       | 592/2000 [00:31<01:15, 18.69it/s]

Epoch 5:  30%|██▉       | 594/2000 [00:31<01:15, 18.69it/s]

Epoch 5:  30%|██▉       | 596/2000 [00:31<01:15, 18.69it/s]

Epoch 5:  30%|██▉       | 598/2000 [00:32<01:14, 18.69it/s]

Epoch 5:  30%|███       | 600/2000 [00:32<01:14, 18.69it/s]

Epoch 5:  30%|███       | 602/2000 [00:32<01:14, 18.69it/s]

Epoch 5:  30%|███       | 604/2000 [00:32<01:14, 18.69it/s]

Epoch 5:  30%|███       | 606/2000 [00:32<01:14, 18.69it/s]

Epoch 5:  30%|███       | 608/2000 [00:32<01:14, 18.68it/s]

Epoch 5:  30%|███       | 610/2000 [00:32<01:14, 18.68it/s]

Epoch 5:  31%|███       | 612/2000 [00:32<01:14, 18.68it/s]

Epoch 5:  31%|███       | 614/2000 [00:32<01:14, 18.69it/s]

Epoch 5:  31%|███       | 616/2000 [00:32<01:14, 18.68it/s]

Epoch 5:  31%|███       | 618/2000 [00:33<01:13, 18.69it/s]

Epoch 5:  31%|███       | 620/2000 [00:33<01:13, 18.69it/s]

Epoch 5:  31%|███       | 622/2000 [00:33<01:13, 18.69it/s]

Epoch 5:  31%|███       | 624/2000 [00:33<01:13, 18.69it/s]

Epoch 5:  31%|███▏      | 626/2000 [00:33<01:13, 18.69it/s]

Epoch 5:  31%|███▏      | 628/2000 [00:33<01:13, 18.68it/s]

Epoch 5:  32%|███▏      | 630/2000 [00:33<01:13, 18.68it/s]

Epoch 5:  32%|███▏      | 632/2000 [00:33<01:13, 18.68it/s]

Epoch 5:  32%|███▏      | 634/2000 [00:33<01:13, 18.67it/s]

Epoch 5:  32%|███▏      | 636/2000 [00:34<01:13, 18.68it/s]

Epoch 5:  32%|███▏      | 638/2000 [00:34<01:12, 18.68it/s]

Epoch 5:  32%|███▏      | 640/2000 [00:34<01:12, 18.68it/s]

Epoch 5:  32%|███▏      | 642/2000 [00:34<01:12, 18.68it/s]

Epoch 5:  32%|███▏      | 644/2000 [00:34<01:12, 18.68it/s]

Epoch 5:  32%|███▏      | 646/2000 [00:34<01:12, 18.69it/s]

Epoch 5:  32%|███▏      | 648/2000 [00:34<01:12, 18.69it/s]

Epoch 5:  32%|███▎      | 650/2000 [00:34<01:12, 18.68it/s]

Epoch 5:  33%|███▎      | 652/2000 [00:34<01:12, 18.69it/s]

Epoch 5:  33%|███▎      | 654/2000 [00:35<01:12, 18.69it/s]

Epoch 5:  33%|███▎      | 656/2000 [00:35<01:11, 18.69it/s]

Epoch 5:  33%|███▎      | 658/2000 [00:35<01:11, 18.69it/s]

Epoch 5:  33%|███▎      | 660/2000 [00:35<01:11, 18.69it/s]

Epoch 5:  33%|███▎      | 662/2000 [00:35<01:11, 18.69it/s]

Epoch 5:  33%|███▎      | 664/2000 [00:35<01:11, 18.69it/s]

Epoch 5:  33%|███▎      | 666/2000 [00:35<01:11, 18.69it/s]

Epoch 5:  33%|███▎      | 668/2000 [00:35<01:11, 18.70it/s]

Epoch 5:  34%|███▎      | 670/2000 [00:35<01:11, 18.71it/s]

Epoch 5:  34%|███▎      | 672/2000 [00:35<01:11, 18.70it/s]

Epoch 5:  34%|███▎      | 674/2000 [00:36<01:10, 18.69it/s]

Epoch 5:  34%|███▍      | 676/2000 [00:36<01:10, 18.70it/s]

Epoch 5:  34%|███▍      | 678/2000 [00:36<01:10, 18.71it/s]

Epoch 5:  34%|███▍      | 680/2000 [00:36<01:10, 18.71it/s]

Epoch 5:  34%|███▍      | 682/2000 [00:36<01:10, 18.70it/s]

Epoch 5:  34%|███▍      | 684/2000 [00:36<01:10, 18.70it/s]

Epoch 5:  34%|███▍      | 686/2000 [00:36<01:10, 18.70it/s]

Epoch 5:  34%|███▍      | 688/2000 [00:36<01:10, 18.70it/s]

Epoch 5:  34%|███▍      | 690/2000 [00:36<01:10, 18.71it/s]

Epoch 5:  35%|███▍      | 692/2000 [00:37<01:09, 18.70it/s]

Epoch 5:  35%|███▍      | 694/2000 [00:37<01:09, 18.70it/s]

Epoch 5:  35%|███▍      | 696/2000 [00:37<01:09, 18.70it/s]

Epoch 5:  35%|███▍      | 698/2000 [00:37<01:09, 18.70it/s]

Epoch 5:  35%|███▌      | 700/2000 [00:37<01:09, 18.68it/s]

Epoch 5:  35%|███▌      | 702/2000 [00:37<01:09, 18.68it/s]

Epoch 5:  35%|███▌      | 704/2000 [00:37<01:09, 18.68it/s]

Epoch 5:  35%|███▌      | 706/2000 [00:37<01:09, 18.69it/s]

Epoch 5:  35%|███▌      | 708/2000 [00:37<01:09, 18.70it/s]

Epoch 5:  36%|███▌      | 710/2000 [00:38<01:09, 18.69it/s]

Epoch 5:  36%|███▌      | 712/2000 [00:38<01:08, 18.70it/s]

Epoch 5:  36%|███▌      | 714/2000 [00:38<01:08, 18.70it/s]

Epoch 5:  36%|███▌      | 716/2000 [00:38<01:08, 18.68it/s]

Epoch 5:  36%|███▌      | 718/2000 [00:38<01:08, 18.69it/s]

Epoch 5:  36%|███▌      | 720/2000 [00:38<01:08, 18.69it/s]

Epoch 5:  36%|███▌      | 722/2000 [00:38<01:08, 18.69it/s]

Epoch 5:  36%|███▌      | 724/2000 [00:38<01:08, 18.69it/s]

Epoch 5:  36%|███▋      | 726/2000 [00:38<01:08, 18.70it/s]

Epoch 5:  36%|███▋      | 728/2000 [00:38<01:08, 18.70it/s]

Epoch 5:  36%|███▋      | 730/2000 [00:39<01:07, 18.70it/s]

Epoch 5:  37%|███▋      | 732/2000 [00:39<01:07, 18.70it/s]

Epoch 5:  37%|███▋      | 734/2000 [00:39<01:07, 18.70it/s]

Epoch 5:  37%|███▋      | 736/2000 [00:39<01:07, 18.70it/s]

Epoch 5:  37%|███▋      | 738/2000 [00:39<01:07, 18.70it/s]

Epoch 5:  37%|███▋      | 740/2000 [00:39<01:07, 18.69it/s]

Epoch 5:  37%|███▋      | 742/2000 [00:39<01:07, 18.69it/s]

Epoch 5:  37%|███▋      | 744/2000 [00:39<01:07, 18.69it/s]

Epoch 5:  37%|███▋      | 746/2000 [00:39<01:07, 18.69it/s]

Epoch 5:  37%|███▋      | 748/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 750/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 752/2000 [00:40<01:06, 18.68it/s]

Epoch 5:  38%|███▊      | 754/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 756/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 758/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 760/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 762/2000 [00:40<01:06, 18.68it/s]

Epoch 5:  38%|███▊      | 764/2000 [00:40<01:06, 18.69it/s]

Epoch 5:  38%|███▊      | 766/2000 [00:41<01:06, 18.70it/s]

Epoch 5:  38%|███▊      | 768/2000 [00:41<01:05, 18.68it/s]

Epoch 5:  38%|███▊      | 770/2000 [00:41<01:05, 18.68it/s]

Epoch 5:  39%|███▊      | 772/2000 [00:41<01:05, 18.69it/s]

Epoch 5:  39%|███▊      | 774/2000 [00:41<01:05, 18.68it/s]

Epoch 5:  39%|███▉      | 776/2000 [00:41<01:05, 18.67it/s]

Epoch 5:  39%|███▉      | 778/2000 [00:41<01:05, 18.67it/s]

Epoch 5:  39%|███▉      | 780/2000 [00:41<01:05, 18.67it/s]

Epoch 5:  39%|███▉      | 782/2000 [00:41<01:05, 18.68it/s]

Epoch 5:  39%|███▉      | 784/2000 [00:41<01:05, 18.68it/s]

Epoch 5:  39%|███▉      | 786/2000 [00:42<01:05, 18.68it/s]

Epoch 5:  39%|███▉      | 788/2000 [00:42<01:04, 18.68it/s]

Epoch 5:  40%|███▉      | 790/2000 [00:42<01:04, 18.68it/s]

Epoch 5:  40%|███▉      | 792/2000 [00:42<01:04, 18.68it/s]

Epoch 5:  40%|███▉      | 794/2000 [00:42<01:04, 18.68it/s]

Epoch 5:  40%|███▉      | 796/2000 [00:42<01:04, 18.68it/s]

Epoch 5:  40%|███▉      | 798/2000 [00:42<01:04, 18.69it/s]

Epoch 5:  40%|████      | 800/2000 [00:42<01:04, 18.69it/s]

Epoch 5:  40%|████      | 802/2000 [00:42<01:04, 18.68it/s]

Epoch 5:  40%|████      | 804/2000 [00:43<01:04, 18.68it/s]

Epoch 5:  40%|████      | 806/2000 [00:43<01:03, 18.68it/s]

Epoch 5:  40%|████      | 808/2000 [00:43<01:03, 18.69it/s]

Epoch 5:  40%|████      | 810/2000 [00:43<01:03, 18.69it/s]

Epoch 5:  41%|████      | 812/2000 [00:43<01:03, 18.68it/s]

Epoch 5:  41%|████      | 814/2000 [00:43<01:03, 18.68it/s]

Epoch 5:  41%|████      | 816/2000 [00:43<01:03, 18.69it/s]

Epoch 5:  41%|████      | 818/2000 [00:43<01:03, 18.68it/s]

Epoch 5:  41%|████      | 820/2000 [00:43<01:03, 18.68it/s]

Epoch 5:  41%|████      | 822/2000 [00:44<01:03, 18.69it/s]

Epoch 5:  41%|████      | 824/2000 [00:44<01:02, 18.69it/s]

Epoch 5:  41%|████▏     | 826/2000 [00:44<01:02, 18.68it/s]

Epoch 5:  41%|████▏     | 828/2000 [00:44<01:02, 18.70it/s]

Epoch 5:  42%|████▏     | 830/2000 [00:44<01:02, 18.68it/s]

Epoch 5:  42%|████▏     | 832/2000 [00:44<01:02, 18.71it/s]

Epoch 5:  42%|████▏     | 834/2000 [00:44<01:02, 18.70it/s]

Epoch 5:  42%|████▏     | 836/2000 [00:44<01:02, 18.69it/s]

Epoch 5:  42%|████▏     | 838/2000 [00:44<01:02, 18.69it/s]

Epoch 5:  42%|████▏     | 840/2000 [00:44<01:02, 18.69it/s]

Epoch 5:  42%|████▏     | 842/2000 [00:45<01:01, 18.68it/s]

Epoch 5:  42%|████▏     | 844/2000 [00:45<01:01, 18.68it/s]

Epoch 5:  42%|████▏     | 846/2000 [00:45<01:01, 18.68it/s]

Epoch 5:  42%|████▏     | 848/2000 [00:45<01:01, 18.69it/s]

Epoch 5:  42%|████▎     | 850/2000 [00:45<01:01, 18.66it/s]

Epoch 5:  43%|████▎     | 852/2000 [00:45<01:01, 18.66it/s]

Epoch 5:  43%|████▎     | 854/2000 [00:45<01:01, 18.67it/s]

Epoch 5:  43%|████▎     | 856/2000 [00:45<01:01, 18.68it/s]

Epoch 5:  43%|████▎     | 858/2000 [00:45<01:01, 18.70it/s]

Epoch 5:  43%|████▎     | 860/2000 [00:46<01:00, 18.70it/s]

Epoch 5:  43%|████▎     | 862/2000 [00:46<01:00, 18.71it/s]

Epoch 5:  43%|████▎     | 864/2000 [00:46<01:00, 18.71it/s]

Epoch 5:  43%|████▎     | 866/2000 [00:46<01:00, 18.71it/s]

Epoch 5:  43%|████▎     | 868/2000 [00:46<01:00, 18.70it/s]

Epoch 5:  44%|████▎     | 870/2000 [00:46<01:00, 18.70it/s]

Epoch 5:  44%|████▎     | 872/2000 [00:46<01:00, 18.70it/s]

Epoch 5:  44%|████▎     | 874/2000 [00:46<01:00, 18.70it/s]

Epoch 5:  44%|████▍     | 876/2000 [00:46<01:00, 18.71it/s]

Epoch 5:  44%|████▍     | 878/2000 [00:47<00:59, 18.71it/s]

Epoch 5:  44%|████▍     | 880/2000 [00:47<00:59, 18.72it/s]

Epoch 5:  44%|████▍     | 882/2000 [00:47<00:59, 18.72it/s]

Epoch 5:  44%|████▍     | 884/2000 [00:47<00:59, 18.73it/s]

Epoch 5:  44%|████▍     | 886/2000 [00:47<00:59, 18.73it/s]

Epoch 5:  44%|████▍     | 888/2000 [00:47<00:59, 18.71it/s]

Epoch 5:  44%|████▍     | 890/2000 [00:47<00:59, 18.72it/s]

Epoch 5:  45%|████▍     | 892/2000 [00:47<00:59, 18.71it/s]

Epoch 5:  45%|████▍     | 894/2000 [00:47<00:59, 18.72it/s]

Epoch 5:  45%|████▍     | 896/2000 [00:47<00:58, 18.72it/s]

Epoch 5:  45%|████▍     | 898/2000 [00:48<00:58, 18.71it/s]

Epoch 5:  45%|████▌     | 900/2000 [00:48<00:58, 18.71it/s]

Epoch 5:  45%|████▌     | 902/2000 [00:48<00:58, 18.69it/s]

Epoch 5:  45%|████▌     | 904/2000 [00:48<00:58, 18.71it/s]

Epoch 5:  45%|████▌     | 906/2000 [00:48<00:58, 18.70it/s]

Epoch 5:  45%|████▌     | 908/2000 [00:48<00:58, 18.71it/s]

Epoch 5:  46%|████▌     | 910/2000 [00:48<00:58, 18.72it/s]

Epoch 5:  46%|████▌     | 912/2000 [00:48<00:58, 18.72it/s]

Epoch 5:  46%|████▌     | 914/2000 [00:48<00:57, 18.73it/s]

Epoch 5:  46%|████▌     | 916/2000 [00:49<00:57, 18.73it/s]

Epoch 5:  46%|████▌     | 918/2000 [00:49<00:57, 18.73it/s]

Epoch 5:  46%|████▌     | 920/2000 [00:49<00:57, 18.74it/s]

Epoch 5:  46%|████▌     | 922/2000 [00:49<00:57, 18.73it/s]

Epoch 5:  46%|████▌     | 924/2000 [00:49<00:57, 18.71it/s]

Epoch 5:  46%|████▋     | 926/2000 [00:49<00:57, 18.72it/s]

Epoch 5:  46%|████▋     | 928/2000 [00:49<00:57, 18.73it/s]

Epoch 5:  46%|████▋     | 930/2000 [00:49<00:57, 18.72it/s]

Epoch 5:  47%|████▋     | 932/2000 [00:49<00:57, 18.72it/s]

Epoch 5:  47%|████▋     | 934/2000 [00:50<00:56, 18.72it/s]

Epoch 5:  47%|████▋     | 936/2000 [00:50<00:56, 18.73it/s]

Epoch 5:  47%|████▋     | 938/2000 [00:50<00:56, 18.72it/s]

Epoch 5:  47%|████▋     | 940/2000 [00:50<00:56, 18.70it/s]

Epoch 5:  47%|████▋     | 942/2000 [00:50<00:56, 18.70it/s]

Epoch 5:  47%|████▋     | 944/2000 [00:50<00:56, 18.70it/s]

Epoch 5:  47%|████▋     | 946/2000 [00:50<00:56, 18.71it/s]

Epoch 5:  47%|████▋     | 948/2000 [00:50<00:56, 18.73it/s]

Epoch 5:  48%|████▊     | 950/2000 [00:50<00:56, 18.72it/s]

Epoch 5:  48%|████▊     | 952/2000 [00:50<00:55, 18.72it/s]

Epoch 5:  48%|████▊     | 954/2000 [00:51<00:55, 18.72it/s]

Epoch 5:  48%|████▊     | 956/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 958/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 960/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 962/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 964/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 966/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 968/2000 [00:51<00:55, 18.71it/s]

Epoch 5:  48%|████▊     | 970/2000 [00:51<00:54, 18.73it/s]

Epoch 5:  49%|████▊     | 972/2000 [00:52<00:54, 18.72it/s]

Epoch 5:  49%|████▊     | 974/2000 [00:52<00:54, 18.73it/s]

Epoch 5:  49%|████▉     | 976/2000 [00:52<00:54, 18.74it/s]

Epoch 5:  49%|████▉     | 978/2000 [00:52<00:54, 18.72it/s]

Epoch 5:  49%|████▉     | 980/2000 [00:52<00:54, 18.71it/s]

Epoch 5:  49%|████▉     | 982/2000 [00:52<00:54, 18.71it/s]

Epoch 5:  49%|████▉     | 984/2000 [00:52<00:54, 18.71it/s]

Epoch 5:  49%|████▉     | 986/2000 [00:52<00:54, 18.70it/s]

Epoch 5:  49%|████▉     | 988/2000 [00:52<00:54, 18.70it/s]

Epoch 5:  50%|████▉     | 990/2000 [00:52<00:53, 18.71it/s]

Epoch 5:  50%|████▉     | 992/2000 [00:53<00:53, 18.71it/s]

Epoch 5:  50%|████▉     | 994/2000 [00:53<00:53, 18.72it/s]

Epoch 5:  50%|████▉     | 996/2000 [00:53<00:53, 18.74it/s]

Epoch 5:  50%|████▉     | 998/2000 [00:53<00:53, 18.74it/s]

Epoch 5:  50%|█████     | 1000/2000 [00:53<00:53, 18.75it/s]

Epoch 5:  50%|█████     | 1002/2000 [00:53<00:53, 18.74it/s]

Epoch 5:  50%|█████     | 1004/2000 [00:53<00:53, 18.74it/s]

Epoch 5:  50%|█████     | 1006/2000 [00:53<00:53, 18.73it/s]

Epoch 5:  50%|█████     | 1008/2000 [00:53<00:52, 18.74it/s]

Epoch 5:  50%|█████     | 1010/2000 [00:54<00:52, 18.73it/s]

Epoch 5:  51%|█████     | 1012/2000 [00:54<00:52, 18.73it/s]

Epoch 5:  51%|█████     | 1014/2000 [00:54<00:52, 18.73it/s]

Epoch 5:  51%|█████     | 1016/2000 [00:54<00:52, 18.73it/s]

Epoch 5:  51%|█████     | 1018/2000 [00:54<00:52, 18.74it/s]

Epoch 5:  51%|█████     | 1020/2000 [00:54<00:52, 18.73it/s]

Epoch 5:  51%|█████     | 1022/2000 [00:54<00:52, 18.74it/s]

Epoch 5:  51%|█████     | 1024/2000 [00:54<00:52, 18.75it/s]

Epoch 5:  51%|█████▏    | 1026/2000 [00:54<00:51, 18.74it/s]

Epoch 5:  51%|█████▏    | 1028/2000 [00:55<00:51, 18.73it/s]

Epoch 5:  52%|█████▏    | 1030/2000 [00:55<00:51, 18.71it/s]

Epoch 5:  52%|█████▏    | 1032/2000 [00:55<00:51, 18.71it/s]

Epoch 5:  52%|█████▏    | 1034/2000 [00:55<00:51, 18.72it/s]

Epoch 5:  52%|█████▏    | 1036/2000 [00:55<00:51, 18.63it/s]

Epoch 5:  52%|█████▏    | 1038/2000 [00:55<00:51, 18.64it/s]

Epoch 5:  52%|█████▏    | 1040/2000 [00:55<00:51, 18.66it/s]

Epoch 5:  52%|█████▏    | 1042/2000 [00:55<00:51, 18.68it/s]

Epoch 5:  52%|█████▏    | 1044/2000 [00:55<00:51, 18.69it/s]

Epoch 5:  52%|█████▏    | 1046/2000 [00:55<00:51, 18.70it/s]

Epoch 5:  52%|█████▏    | 1048/2000 [00:56<00:50, 18.71it/s]

Epoch 5:  52%|█████▎    | 1050/2000 [00:56<00:50, 18.72it/s]

Epoch 5:  53%|█████▎    | 1052/2000 [00:56<00:50, 18.71it/s]

Epoch 5:  53%|█████▎    | 1054/2000 [00:56<00:50, 18.72it/s]

Epoch 5:  53%|█████▎    | 1056/2000 [00:56<00:50, 18.72it/s]

Epoch 5:  53%|█████▎    | 1058/2000 [00:56<00:50, 18.72it/s]

Epoch 5:  53%|█████▎    | 1060/2000 [00:56<00:50, 18.70it/s]

Epoch 5:  53%|█████▎    | 1062/2000 [00:56<00:50, 18.72it/s]

Epoch 5:  53%|█████▎    | 1064/2000 [00:56<00:49, 18.72it/s]

Epoch 5:  53%|█████▎    | 1066/2000 [00:57<00:49, 18.73it/s]

Epoch 5:  53%|█████▎    | 1068/2000 [00:57<00:49, 18.72it/s]

Epoch 5:  54%|█████▎    | 1070/2000 [00:57<00:49, 18.73it/s]

Epoch 5:  54%|█████▎    | 1072/2000 [00:57<00:49, 18.73it/s]

Epoch 5:  54%|█████▎    | 1074/2000 [00:57<00:49, 18.72it/s]

Epoch 5:  54%|█████▍    | 1076/2000 [00:57<00:49, 18.72it/s]

Epoch 5:  54%|█████▍    | 1078/2000 [00:57<00:49, 18.72it/s]

Epoch 5:  54%|█████▍    | 1080/2000 [00:57<00:49, 18.73it/s]

Epoch 5:  54%|█████▍    | 1082/2000 [00:57<00:49, 18.73it/s]

Epoch 5:  54%|█████▍    | 1084/2000 [00:58<00:48, 18.71it/s]

Epoch 5:  54%|█████▍    | 1086/2000 [00:58<00:48, 18.71it/s]

Epoch 5:  54%|█████▍    | 1088/2000 [00:58<00:48, 18.71it/s]

Epoch 5:  55%|█████▍    | 1090/2000 [00:58<00:48, 18.72it/s]

Epoch 5:  55%|█████▍    | 1092/2000 [00:58<00:48, 18.72it/s]

Epoch 5:  55%|█████▍    | 1094/2000 [00:58<00:48, 18.73it/s]

Epoch 5:  55%|█████▍    | 1096/2000 [00:58<00:48, 18.60it/s]

Epoch 5:  55%|█████▍    | 1098/2000 [00:58<00:49, 18.23it/s]

Epoch 5:  55%|█████▌    | 1100/2000 [00:58<00:49, 18.05it/s]

Epoch 5:  55%|█████▌    | 1102/2000 [00:59<00:49, 18.04it/s]

Epoch 5:  55%|█████▌    | 1104/2000 [00:59<00:49, 18.19it/s]

Epoch 5:  55%|█████▌    | 1106/2000 [00:59<00:48, 18.30it/s]

Epoch 5:  55%|█████▌    | 1108/2000 [00:59<00:48, 18.40it/s]

Epoch 5:  56%|█████▌    | 1110/2000 [00:59<00:48, 18.51it/s]

Epoch 5:  56%|█████▌    | 1112/2000 [00:59<00:47, 18.55it/s]

Epoch 5:  56%|█████▌    | 1114/2000 [00:59<00:47, 18.60it/s]

Epoch 5:  56%|█████▌    | 1116/2000 [00:59<00:47, 18.64it/s]

Epoch 5:  56%|█████▌    | 1118/2000 [00:59<00:47, 18.66it/s]

Epoch 5:  56%|█████▌    | 1120/2000 [00:59<00:47, 18.67it/s]

Epoch 5:  56%|█████▌    | 1122/2000 [01:00<00:47, 18.66it/s]

Epoch 5:  56%|█████▌    | 1124/2000 [01:00<00:46, 18.68it/s]

Epoch 5:  56%|█████▋    | 1126/2000 [01:00<00:46, 18.69it/s]

Epoch 5:  56%|█████▋    | 1128/2000 [01:00<00:46, 18.70it/s]

Epoch 5:  56%|█████▋    | 1130/2000 [01:00<00:46, 18.71it/s]

Epoch 5:  57%|█████▋    | 1132/2000 [01:00<00:46, 18.71it/s]

Epoch 5:  57%|█████▋    | 1134/2000 [01:00<00:46, 18.73it/s]

Epoch 5:  57%|█████▋    | 1136/2000 [01:00<00:46, 18.73it/s]

Epoch 5:  57%|█████▋    | 1138/2000 [01:00<00:46, 18.73it/s]

Epoch 5:  57%|█████▋    | 1140/2000 [01:01<00:45, 18.72it/s]

Epoch 5:  57%|█████▋    | 1142/2000 [01:01<00:45, 18.73it/s]

Epoch 5:  57%|█████▋    | 1144/2000 [01:01<00:45, 18.73it/s]

Epoch 5:  57%|█████▋    | 1146/2000 [01:01<00:45, 18.74it/s]

Epoch 5:  57%|█████▋    | 1148/2000 [01:01<00:45, 18.72it/s]

Epoch 5:  57%|█████▊    | 1150/2000 [01:01<00:45, 18.71it/s]

Epoch 5:  58%|█████▊    | 1152/2000 [01:01<00:45, 18.73it/s]

Epoch 5:  58%|█████▊    | 1154/2000 [01:01<00:45, 18.73it/s]

Epoch 5:  58%|█████▊    | 1156/2000 [01:01<00:45, 18.72it/s]

Epoch 5:  58%|█████▊    | 1158/2000 [01:01<00:44, 18.73it/s]

Epoch 5:  58%|█████▊    | 1160/2000 [01:02<00:44, 18.73it/s]

Epoch 5:  58%|█████▊    | 1162/2000 [01:02<00:44, 18.74it/s]

Epoch 5:  58%|█████▊    | 1164/2000 [01:02<00:44, 18.74it/s]

Epoch 5:  58%|█████▊    | 1166/2000 [01:02<00:44, 18.74it/s]

Epoch 5:  58%|█████▊    | 1168/2000 [01:02<00:44, 18.75it/s]

Epoch 5:  58%|█████▊    | 1170/2000 [01:02<00:44, 18.75it/s]

Epoch 5:  59%|█████▊    | 1172/2000 [01:02<00:44, 18.76it/s]

Epoch 5:  59%|█████▊    | 1174/2000 [01:02<00:44, 18.77it/s]

Epoch 5:  59%|█████▉    | 1176/2000 [01:02<00:43, 18.75it/s]

Epoch 5:  59%|█████▉    | 1178/2000 [01:03<00:43, 18.75it/s]

Epoch 5:  59%|█████▉    | 1180/2000 [01:03<00:43, 18.73it/s]

Epoch 5:  59%|█████▉    | 1182/2000 [01:03<00:43, 18.74it/s]

Epoch 5:  59%|█████▉    | 1184/2000 [01:03<00:43, 18.75it/s]

Epoch 5:  59%|█████▉    | 1186/2000 [01:03<00:43, 18.74it/s]

Epoch 5:  59%|█████▉    | 1188/2000 [01:03<00:43, 18.73it/s]

Epoch 5:  60%|█████▉    | 1190/2000 [01:03<00:43, 18.72it/s]

Epoch 5:  60%|█████▉    | 1192/2000 [01:03<00:43, 18.72it/s]

Epoch 5:  60%|█████▉    | 1194/2000 [01:03<00:43, 18.74it/s]

Epoch 5:  60%|█████▉    | 1196/2000 [01:04<00:42, 18.74it/s]

Epoch 5:  60%|█████▉    | 1198/2000 [01:04<00:42, 18.74it/s]

Epoch 5:  60%|██████    | 1200/2000 [01:04<00:42, 18.74it/s]

Epoch 5:  60%|██████    | 1202/2000 [01:04<00:42, 18.74it/s]

Epoch 5:  60%|██████    | 1204/2000 [01:04<00:42, 18.75it/s]

Epoch 5:  60%|██████    | 1206/2000 [01:04<00:42, 18.75it/s]

Epoch 5:  60%|██████    | 1208/2000 [01:04<00:42, 18.75it/s]

Epoch 5:  60%|██████    | 1210/2000 [01:04<00:42, 18.75it/s]

Epoch 5:  61%|██████    | 1212/2000 [01:04<00:41, 18.77it/s]

Epoch 5:  61%|██████    | 1214/2000 [01:04<00:41, 18.77it/s]

Epoch 5:  61%|██████    | 1216/2000 [01:05<00:41, 18.75it/s]

Epoch 5:  61%|██████    | 1218/2000 [01:05<00:41, 18.74it/s]

Epoch 5:  61%|██████    | 1220/2000 [01:05<00:41, 18.74it/s]

Epoch 5:  61%|██████    | 1222/2000 [01:05<00:41, 18.74it/s]

Epoch 5:  61%|██████    | 1224/2000 [01:05<00:41, 18.74it/s]

Epoch 5:  61%|██████▏   | 1226/2000 [01:05<00:41, 18.73it/s]

Epoch 5:  61%|██████▏   | 1228/2000 [01:05<00:41, 18.74it/s]

Epoch 5:  62%|██████▏   | 1230/2000 [01:05<00:41, 18.75it/s]

Epoch 5:  62%|██████▏   | 1232/2000 [01:05<00:40, 18.75it/s]

Epoch 5:  62%|██████▏   | 1234/2000 [01:06<00:40, 18.75it/s]

Epoch 5:  62%|██████▏   | 1236/2000 [01:06<00:40, 18.75it/s]

Epoch 5:  62%|██████▏   | 1238/2000 [01:06<00:40, 18.76it/s]

Epoch 5:  62%|██████▏   | 1240/2000 [01:06<00:40, 18.76it/s]

Epoch 5:  62%|██████▏   | 1242/2000 [01:06<00:40, 18.76it/s]

Epoch 5:  62%|██████▏   | 1244/2000 [01:06<00:40, 18.76it/s]

Epoch 5:  62%|██████▏   | 1246/2000 [01:06<00:40, 18.76it/s]

Epoch 5:  62%|██████▏   | 1248/2000 [01:06<00:40, 18.75it/s]

Epoch 5:  62%|██████▎   | 1250/2000 [01:06<00:39, 18.76it/s]

Epoch 5:  63%|██████▎   | 1252/2000 [01:07<00:39, 18.77it/s]

Epoch 5:  63%|██████▎   | 1254/2000 [01:07<00:39, 18.76it/s]

Epoch 5:  63%|██████▎   | 1256/2000 [01:07<00:39, 18.76it/s]

Epoch 5:  63%|██████▎   | 1258/2000 [01:07<00:39, 18.76it/s]

Epoch 5:  63%|██████▎   | 1260/2000 [01:07<00:39, 18.76it/s]

Epoch 5:  63%|██████▎   | 1262/2000 [01:07<00:39, 18.77it/s]

Epoch 5:  63%|██████▎   | 1264/2000 [01:07<00:39, 18.77it/s]

Epoch 5:  63%|██████▎   | 1266/2000 [01:07<00:39, 18.77it/s]

Epoch 5:  63%|██████▎   | 1268/2000 [01:07<00:39, 18.77it/s]

Epoch 5:  64%|██████▎   | 1270/2000 [01:07<00:38, 18.76it/s]

Epoch 5:  64%|██████▎   | 1272/2000 [01:08<00:38, 18.77it/s]

Epoch 5:  64%|██████▎   | 1274/2000 [01:08<00:38, 18.76it/s]

Epoch 5:  64%|██████▍   | 1276/2000 [01:08<00:38, 18.66it/s]

Epoch 5:  64%|██████▍   | 1278/2000 [01:08<00:38, 18.66it/s]

Epoch 5:  64%|██████▍   | 1280/2000 [01:08<00:38, 18.69it/s]

Epoch 5:  64%|██████▍   | 1282/2000 [01:08<00:38, 18.71it/s]

Epoch 5:  64%|██████▍   | 1284/2000 [01:08<00:38, 18.72it/s]

Epoch 5:  64%|██████▍   | 1286/2000 [01:08<00:38, 18.72it/s]

Epoch 5:  64%|██████▍   | 1288/2000 [01:08<00:38, 18.73it/s]

Epoch 5:  64%|██████▍   | 1290/2000 [01:09<00:37, 18.75it/s]

Epoch 5:  65%|██████▍   | 1292/2000 [01:09<00:37, 18.73it/s]

Epoch 5:  65%|██████▍   | 1294/2000 [01:09<00:37, 18.74it/s]

Epoch 5:  65%|██████▍   | 1296/2000 [01:09<00:37, 18.74it/s]

Epoch 5:  65%|██████▍   | 1298/2000 [01:09<00:37, 18.75it/s]

Epoch 5:  65%|██████▌   | 1300/2000 [01:09<00:37, 18.76it/s]

Epoch 5:  65%|██████▌   | 1302/2000 [01:09<00:37, 18.73it/s]

Epoch 5:  65%|██████▌   | 1304/2000 [01:09<00:37, 18.73it/s]

Epoch 5:  65%|██████▌   | 1306/2000 [01:09<00:37, 18.74it/s]

Epoch 5:  65%|██████▌   | 1308/2000 [01:09<00:36, 18.74it/s]

Epoch 5:  66%|██████▌   | 1310/2000 [01:10<00:36, 18.73it/s]

Epoch 5:  66%|██████▌   | 1312/2000 [01:10<00:36, 18.74it/s]

Epoch 5:  66%|██████▌   | 1314/2000 [01:10<00:36, 18.74it/s]

Epoch 5:  66%|██████▌   | 1316/2000 [01:10<00:36, 18.75it/s]

Epoch 5:  66%|██████▌   | 1318/2000 [01:10<00:36, 18.75it/s]

Epoch 5:  66%|██████▌   | 1320/2000 [01:10<00:36, 18.75it/s]

Epoch 5:  66%|██████▌   | 1322/2000 [01:10<00:36, 18.75it/s]

Epoch 5:  66%|██████▌   | 1324/2000 [01:10<00:36, 18.75it/s]

Epoch 5:  66%|██████▋   | 1326/2000 [01:10<00:35, 18.75it/s]

Epoch 5:  66%|██████▋   | 1328/2000 [01:11<00:35, 18.76it/s]

Epoch 5:  66%|██████▋   | 1330/2000 [01:11<00:35, 18.76it/s]

Epoch 5:  67%|██████▋   | 1332/2000 [01:11<00:35, 18.75it/s]

Epoch 5:  67%|██████▋   | 1334/2000 [01:11<00:35, 18.77it/s]

Epoch 5:  67%|██████▋   | 1336/2000 [01:11<00:35, 18.76it/s]

Epoch 5:  67%|██████▋   | 1338/2000 [01:11<00:35, 18.77it/s]

Epoch 5:  67%|██████▋   | 1340/2000 [01:11<00:35, 18.76it/s]

Epoch 5:  67%|██████▋   | 1342/2000 [01:11<00:35, 18.74it/s]

Epoch 5:  67%|██████▋   | 1344/2000 [01:11<00:35, 18.74it/s]

Epoch 5:  67%|██████▋   | 1346/2000 [01:12<00:34, 18.73it/s]

Epoch 5:  67%|██████▋   | 1348/2000 [01:12<00:34, 18.74it/s]

Epoch 5:  68%|██████▊   | 1350/2000 [01:12<00:34, 18.75it/s]

Epoch 5:  68%|██████▊   | 1352/2000 [01:12<00:34, 18.74it/s]

Epoch 5:  68%|██████▊   | 1354/2000 [01:12<00:34, 18.73it/s]

Epoch 5:  68%|██████▊   | 1356/2000 [01:12<00:34, 18.74it/s]

Epoch 5:  68%|██████▊   | 1358/2000 [01:12<00:34, 18.75it/s]

Epoch 5:  68%|██████▊   | 1360/2000 [01:12<00:34, 18.75it/s]

Epoch 5:  68%|██████▊   | 1362/2000 [01:12<00:34, 18.76it/s]

Epoch 5:  68%|██████▊   | 1364/2000 [01:12<00:33, 18.75it/s]

Epoch 5:  68%|██████▊   | 1366/2000 [01:13<00:33, 18.75it/s]

Epoch 5:  68%|██████▊   | 1368/2000 [01:13<00:33, 18.76it/s]

Epoch 5:  68%|██████▊   | 1370/2000 [01:13<00:33, 18.76it/s]

Epoch 5:  69%|██████▊   | 1372/2000 [01:13<00:33, 18.75it/s]

Epoch 5:  69%|██████▊   | 1374/2000 [01:13<00:33, 18.76it/s]

Epoch 5:  69%|██████▉   | 1376/2000 [01:13<00:33, 18.75it/s]

Epoch 5:  69%|██████▉   | 1378/2000 [01:13<00:33, 18.76it/s]

Epoch 5:  69%|██████▉   | 1380/2000 [01:13<00:33, 18.76it/s]

Epoch 5:  69%|██████▉   | 1382/2000 [01:13<00:32, 18.74it/s]

Epoch 5:  69%|██████▉   | 1384/2000 [01:14<00:32, 18.75it/s]

Epoch 5:  69%|██████▉   | 1386/2000 [01:14<00:32, 18.75it/s]

Epoch 5:  69%|██████▉   | 1388/2000 [01:14<00:32, 18.74it/s]

Epoch 5:  70%|██████▉   | 1390/2000 [01:14<00:32, 18.74it/s]

Epoch 5:  70%|██████▉   | 1392/2000 [01:14<00:32, 18.75it/s]

Epoch 5:  70%|██████▉   | 1394/2000 [01:14<00:32, 18.74it/s]

Epoch 5:  70%|██████▉   | 1396/2000 [01:14<00:32, 18.74it/s]

Epoch 5:  70%|██████▉   | 1398/2000 [01:14<00:32, 18.73it/s]

Epoch 5:  70%|███████   | 1400/2000 [01:14<00:32, 18.74it/s]

Epoch 5:  70%|███████   | 1402/2000 [01:15<00:31, 18.76it/s]

Epoch 5:  70%|███████   | 1404/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  70%|███████   | 1406/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  70%|███████   | 1408/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  70%|███████   | 1410/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  71%|███████   | 1412/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  71%|███████   | 1414/2000 [01:15<00:31, 18.74it/s]

Epoch 5:  71%|███████   | 1416/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  71%|███████   | 1418/2000 [01:15<00:31, 18.75it/s]

Epoch 5:  71%|███████   | 1420/2000 [01:15<00:30, 18.75it/s]

Epoch 5:  71%|███████   | 1422/2000 [01:16<00:30, 18.75it/s]

Epoch 5:  71%|███████   | 1424/2000 [01:16<00:30, 18.75it/s]

Epoch 5:  71%|███████▏  | 1426/2000 [01:16<00:30, 18.76it/s]

Epoch 5:  71%|███████▏  | 1428/2000 [01:16<00:30, 18.76it/s]

Epoch 5:  72%|███████▏  | 1430/2000 [01:16<00:30, 18.76it/s]

Epoch 5:  72%|███████▏  | 1432/2000 [01:16<00:30, 18.76it/s]

Epoch 5:  72%|███████▏  | 1434/2000 [01:16<00:30, 18.75it/s]

Epoch 5:  72%|███████▏  | 1436/2000 [01:16<00:30, 18.76it/s]

Epoch 5:  72%|███████▏  | 1438/2000 [01:16<00:29, 18.76it/s]

Epoch 5:  72%|███████▏  | 1440/2000 [01:17<00:29, 18.77it/s]

Epoch 5:  72%|███████▏  | 1442/2000 [01:17<00:29, 18.76it/s]

Epoch 5:  72%|███████▏  | 1444/2000 [01:17<00:29, 18.76it/s]

Epoch 5:  72%|███████▏  | 1446/2000 [01:17<00:29, 18.76it/s]

Epoch 5:  72%|███████▏  | 1448/2000 [01:17<00:29, 18.76it/s]

Epoch 5:  72%|███████▎  | 1450/2000 [01:17<00:29, 18.75it/s]

Epoch 5:  73%|███████▎  | 1452/2000 [01:17<00:29, 18.75it/s]

Epoch 5:  73%|███████▎  | 1454/2000 [01:17<00:29, 18.76it/s]

Epoch 5:  73%|███████▎  | 1456/2000 [01:17<00:29, 18.74it/s]

Epoch 5:  73%|███████▎  | 1458/2000 [01:17<00:28, 18.74it/s]

Epoch 5:  73%|███████▎  | 1460/2000 [01:18<00:28, 18.75it/s]

Epoch 5:  73%|███████▎  | 1462/2000 [01:18<00:28, 18.76it/s]

Epoch 5:  73%|███████▎  | 1464/2000 [01:18<00:28, 18.76it/s]

Epoch 5:  73%|███████▎  | 1466/2000 [01:18<00:28, 18.75it/s]

Epoch 5:  73%|███████▎  | 1468/2000 [01:18<00:28, 18.75it/s]

Epoch 5:  74%|███████▎  | 1470/2000 [01:18<00:28, 18.75it/s]

Epoch 5:  74%|███████▎  | 1472/2000 [01:18<00:28, 18.75it/s]

Epoch 5:  74%|███████▎  | 1474/2000 [01:18<00:28, 18.75it/s]

Epoch 5:  74%|███████▍  | 1476/2000 [01:18<00:27, 18.76it/s]

Epoch 5:  74%|███████▍  | 1478/2000 [01:19<00:27, 18.76it/s]

Epoch 5:  74%|███████▍  | 1480/2000 [01:19<00:27, 18.75it/s]

Epoch 5:  74%|███████▍  | 1482/2000 [01:19<00:27, 18.76it/s]

Epoch 5:  74%|███████▍  | 1484/2000 [01:19<00:27, 18.76it/s]

Epoch 5:  74%|███████▍  | 1486/2000 [01:19<00:27, 18.77it/s]

Epoch 5:  74%|███████▍  | 1488/2000 [01:19<00:27, 18.77it/s]

Epoch 5:  74%|███████▍  | 1490/2000 [01:19<00:27, 18.76it/s]

Epoch 5:  75%|███████▍  | 1492/2000 [01:19<00:27, 18.75it/s]

Epoch 5:  75%|███████▍  | 1494/2000 [01:19<00:27, 18.74it/s]

Epoch 5:  75%|███████▍  | 1496/2000 [01:20<00:26, 18.74it/s]

Epoch 5:  75%|███████▍  | 1498/2000 [01:20<00:26, 18.73it/s]

Epoch 5:  75%|███████▌  | 1500/2000 [01:20<00:26, 18.74it/s]

Epoch 5:  75%|███████▌  | 1502/2000 [01:20<00:26, 18.74it/s]

Epoch 5:  75%|███████▌  | 1504/2000 [01:20<00:26, 18.75it/s]

Epoch 5:  75%|███████▌  | 1506/2000 [01:20<00:26, 18.76it/s]

Epoch 5:  75%|███████▌  | 1508/2000 [01:20<00:26, 18.76it/s]

Epoch 5:  76%|███████▌  | 1510/2000 [01:20<00:26, 18.77it/s]

Epoch 5:  76%|███████▌  | 1512/2000 [01:20<00:25, 18.78it/s]

Epoch 5:  76%|███████▌  | 1514/2000 [01:20<00:25, 18.78it/s]

Epoch 5:  76%|███████▌  | 1516/2000 [01:21<00:25, 18.65it/s]

Epoch 5:  76%|███████▌  | 1518/2000 [01:21<00:25, 18.66it/s]

Epoch 5:  76%|███████▌  | 1520/2000 [01:21<00:25, 18.68it/s]

Epoch 5:  76%|███████▌  | 1522/2000 [01:21<00:25, 18.70it/s]

Epoch 5:  76%|███████▌  | 1524/2000 [01:21<00:25, 18.70it/s]

Epoch 5:  76%|███████▋  | 1526/2000 [01:21<00:25, 18.71it/s]

Epoch 5:  76%|███████▋  | 1528/2000 [01:21<00:25, 18.71it/s]

Epoch 5:  76%|███████▋  | 1530/2000 [01:21<00:25, 18.71it/s]

Epoch 5:  77%|███████▋  | 1532/2000 [01:21<00:25, 18.71it/s]

Epoch 5:  77%|███████▋  | 1534/2000 [01:22<00:24, 18.71it/s]

Epoch 5:  77%|███████▋  | 1536/2000 [01:22<00:24, 18.71it/s]

Epoch 5:  77%|███████▋  | 1538/2000 [01:22<00:24, 18.71it/s]

Epoch 5:  77%|███████▋  | 1540/2000 [01:22<00:24, 18.71it/s]

Epoch 5:  77%|███████▋  | 1542/2000 [01:22<00:24, 18.71it/s]

Epoch 5:  77%|███████▋  | 1544/2000 [01:22<00:24, 18.70it/s]

Epoch 5:  77%|███████▋  | 1546/2000 [01:22<00:24, 18.71it/s]

Epoch 5:  77%|███████▋  | 1548/2000 [01:22<00:24, 18.72it/s]

Epoch 5:  78%|███████▊  | 1550/2000 [01:22<00:24, 18.72it/s]

Epoch 5:  78%|███████▊  | 1552/2000 [01:23<00:23, 18.72it/s]

Epoch 5:  78%|███████▊  | 1554/2000 [01:23<00:23, 18.70it/s]

Epoch 5:  78%|███████▊  | 1556/2000 [01:23<00:23, 18.71it/s]

Epoch 5:  78%|███████▊  | 1558/2000 [01:23<00:23, 18.71it/s]

Epoch 5:  78%|███████▊  | 1560/2000 [01:23<00:23, 18.70it/s]

Epoch 5:  78%|███████▊  | 1562/2000 [01:23<00:23, 18.71it/s]

Epoch 5:  78%|███████▊  | 1564/2000 [01:23<00:23, 18.71it/s]

Epoch 5:  78%|███████▊  | 1566/2000 [01:23<00:23, 18.72it/s]

Epoch 5:  78%|███████▊  | 1568/2000 [01:23<00:23, 18.72it/s]

Epoch 5:  78%|███████▊  | 1570/2000 [01:23<00:22, 18.71it/s]

Epoch 5:  79%|███████▊  | 1572/2000 [01:24<00:22, 18.72it/s]

Epoch 5:  79%|███████▊  | 1574/2000 [01:24<00:22, 18.72it/s]

Epoch 5:  79%|███████▉  | 1576/2000 [01:24<00:22, 18.72it/s]

Epoch 5:  79%|███████▉  | 1578/2000 [01:24<00:22, 18.73it/s]

Epoch 5:  79%|███████▉  | 1580/2000 [01:24<00:22, 18.73it/s]

Epoch 5:  79%|███████▉  | 1582/2000 [01:24<00:22, 18.71it/s]

Epoch 5:  79%|███████▉  | 1584/2000 [01:24<00:22, 18.72it/s]

Epoch 5:  79%|███████▉  | 1586/2000 [01:24<00:22, 18.73it/s]

Epoch 5:  79%|███████▉  | 1588/2000 [01:24<00:22, 18.72it/s]

Epoch 5:  80%|███████▉  | 1590/2000 [01:25<00:21, 18.72it/s]

Epoch 5:  80%|███████▉  | 1592/2000 [01:25<00:21, 18.72it/s]

Epoch 5:  80%|███████▉  | 1594/2000 [01:25<00:21, 18.73it/s]

Epoch 5:  80%|███████▉  | 1596/2000 [01:25<00:21, 18.73it/s]

Epoch 5:  80%|███████▉  | 1598/2000 [01:25<00:21, 18.73it/s]

Epoch 5:  80%|████████  | 1600/2000 [01:25<00:21, 18.73it/s]

Epoch 5:  80%|████████  | 1602/2000 [01:25<00:21, 18.72it/s]

Epoch 5:  80%|████████  | 1604/2000 [01:25<00:21, 18.72it/s]

Epoch 5:  80%|████████  | 1606/2000 [01:25<00:21, 18.73it/s]

Epoch 5:  80%|████████  | 1608/2000 [01:26<00:20, 18.73it/s]

Epoch 5:  80%|████████  | 1610/2000 [01:26<00:20, 18.75it/s]

Epoch 5:  81%|████████  | 1612/2000 [01:26<00:20, 18.75it/s]

Epoch 5:  81%|████████  | 1614/2000 [01:26<00:20, 18.74it/s]

Epoch 5:  81%|████████  | 1616/2000 [01:26<00:20, 18.74it/s]

Epoch 5:  81%|████████  | 1618/2000 [01:26<00:20, 18.74it/s]

Epoch 5:  81%|████████  | 1620/2000 [01:26<00:20, 18.75it/s]

Epoch 5:  81%|████████  | 1622/2000 [01:26<00:20, 18.74it/s]

Epoch 5:  81%|████████  | 1624/2000 [01:26<00:20, 18.75it/s]

Epoch 5:  81%|████████▏ | 1626/2000 [01:26<00:19, 18.74it/s]

Epoch 5:  81%|████████▏ | 1628/2000 [01:27<00:19, 18.73it/s]

Epoch 5:  82%|████████▏ | 1630/2000 [01:27<00:19, 18.74it/s]

Epoch 5:  82%|████████▏ | 1632/2000 [01:27<00:19, 18.73it/s]

Epoch 5:  82%|████████▏ | 1634/2000 [01:27<00:19, 18.74it/s]

Epoch 5:  82%|████████▏ | 1636/2000 [01:27<00:19, 18.74it/s]

Epoch 5:  82%|████████▏ | 1638/2000 [01:27<00:19, 18.73it/s]

Epoch 5:  82%|████████▏ | 1640/2000 [01:27<00:19, 18.73it/s]

Epoch 5:  82%|████████▏ | 1642/2000 [01:27<00:19, 18.74it/s]

Epoch 5:  82%|████████▏ | 1644/2000 [01:27<00:19, 18.73it/s]

Epoch 5:  82%|████████▏ | 1646/2000 [01:28<00:18, 18.74it/s]

Epoch 5:  82%|████████▏ | 1648/2000 [01:28<00:18, 18.74it/s]

Epoch 5:  82%|████████▎ | 1650/2000 [01:28<00:18, 18.72it/s]

Epoch 5:  83%|████████▎ | 1652/2000 [01:28<00:18, 18.73it/s]

Epoch 5:  83%|████████▎ | 1654/2000 [01:28<00:18, 18.73it/s]

Epoch 5:  83%|████████▎ | 1656/2000 [01:28<00:18, 18.73it/s]

Epoch 5:  83%|████████▎ | 1658/2000 [01:28<00:18, 18.73it/s]

Epoch 5:  83%|████████▎ | 1660/2000 [01:28<00:18, 18.73it/s]

Epoch 5:  83%|████████▎ | 1662/2000 [01:28<00:18, 18.74it/s]

Epoch 5:  83%|████████▎ | 1664/2000 [01:28<00:17, 18.73it/s]

Epoch 5:  83%|████████▎ | 1666/2000 [01:29<00:17, 18.74it/s]

Epoch 5:  83%|████████▎ | 1668/2000 [01:29<00:17, 18.74it/s]

Epoch 5:  84%|████████▎ | 1670/2000 [01:29<00:17, 18.73it/s]

Epoch 5:  84%|████████▎ | 1672/2000 [01:29<00:17, 18.73it/s]

Epoch 5:  84%|████████▎ | 1674/2000 [01:29<00:17, 18.74it/s]

Epoch 5:  84%|████████▍ | 1676/2000 [01:29<00:17, 18.73it/s]

Epoch 5:  84%|████████▍ | 1678/2000 [01:29<00:17, 18.74it/s]

Epoch 5:  84%|████████▍ | 1680/2000 [01:29<00:17, 18.73it/s]

Epoch 5:  84%|████████▍ | 1682/2000 [01:29<00:16, 18.74it/s]

Epoch 5:  84%|████████▍ | 1684/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  84%|████████▍ | 1686/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  84%|████████▍ | 1688/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  84%|████████▍ | 1690/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  85%|████████▍ | 1692/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  85%|████████▍ | 1694/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  85%|████████▍ | 1696/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  85%|████████▍ | 1698/2000 [01:30<00:16, 18.73it/s]

Epoch 5:  85%|████████▌ | 1700/2000 [01:30<00:16, 18.74it/s]

Epoch 5:  85%|████████▌ | 1702/2000 [01:31<00:15, 18.74it/s]

Epoch 5:  85%|████████▌ | 1704/2000 [01:31<00:15, 18.74it/s]

Epoch 5:  85%|████████▌ | 1706/2000 [01:31<00:15, 18.74it/s]

Epoch 5:  85%|████████▌ | 1708/2000 [01:31<00:15, 18.73it/s]

Epoch 5:  86%|████████▌ | 1710/2000 [01:31<00:15, 18.56it/s]

Epoch 5:  86%|████████▌ | 1712/2000 [01:31<00:15, 18.02it/s]

Epoch 5:  86%|████████▌ | 1714/2000 [01:31<00:15, 18.08it/s]

Epoch 5:  86%|████████▌ | 1716/2000 [01:31<00:15, 18.11it/s]

Epoch 5:  86%|████████▌ | 1718/2000 [01:31<00:15, 18.23it/s]

Epoch 5:  86%|████████▌ | 1720/2000 [01:32<00:15, 18.24it/s]

Epoch 5:  86%|████████▌ | 1722/2000 [01:32<00:15, 18.37it/s]

Epoch 5:  86%|████████▌ | 1724/2000 [01:32<00:14, 18.48it/s]

Epoch 5:  86%|████████▋ | 1726/2000 [01:32<00:14, 18.55it/s]

Epoch 5:  86%|████████▋ | 1728/2000 [01:32<00:14, 18.60it/s]

Epoch 5:  86%|████████▋ | 1730/2000 [01:32<00:14, 18.64it/s]

Epoch 5:  87%|████████▋ | 1732/2000 [01:32<00:14, 18.66it/s]

Epoch 5:  87%|████████▋ | 1734/2000 [01:32<00:14, 18.69it/s]

Epoch 5:  87%|████████▋ | 1736/2000 [01:32<00:14, 18.69it/s]

Epoch 5:  87%|████████▋ | 1738/2000 [01:32<00:14, 18.70it/s]

Epoch 5:  87%|████████▋ | 1740/2000 [01:33<00:13, 18.71it/s]

Epoch 5:  87%|████████▋ | 1742/2000 [01:33<00:13, 18.72it/s]

Epoch 5:  87%|████████▋ | 1744/2000 [01:33<00:13, 18.71it/s]

Epoch 5:  87%|████████▋ | 1746/2000 [01:33<00:13, 18.72it/s]

Epoch 5:  87%|████████▋ | 1748/2000 [01:33<00:13, 18.71it/s]

Epoch 5:  88%|████████▊ | 1750/2000 [01:33<00:13, 18.71it/s]

Epoch 5:  88%|████████▊ | 1752/2000 [01:33<00:13, 18.72it/s]

Epoch 5:  88%|████████▊ | 1754/2000 [01:33<00:13, 18.73it/s]

Epoch 5:  88%|████████▊ | 1756/2000 [01:33<00:13, 18.73it/s]

Epoch 5:  88%|████████▊ | 1758/2000 [01:34<00:12, 18.74it/s]

Epoch 5:  88%|████████▊ | 1760/2000 [01:34<00:12, 18.74it/s]

Epoch 5:  88%|████████▊ | 1762/2000 [01:34<00:12, 18.75it/s]

Epoch 5:  88%|████████▊ | 1764/2000 [01:34<00:12, 18.74it/s]

Epoch 5:  88%|████████▊ | 1766/2000 [01:34<00:12, 18.74it/s]

Epoch 5:  88%|████████▊ | 1768/2000 [01:34<00:12, 18.76it/s]

Epoch 5:  88%|████████▊ | 1770/2000 [01:34<00:12, 18.74it/s]

Epoch 5:  89%|████████▊ | 1772/2000 [01:34<00:12, 18.73it/s]

Epoch 5:  89%|████████▊ | 1774/2000 [01:34<00:12, 18.72it/s]

Epoch 5:  89%|████████▉ | 1776/2000 [01:35<00:11, 18.73it/s]

Epoch 5:  89%|████████▉ | 1778/2000 [01:35<00:11, 18.72it/s]

Epoch 5:  89%|████████▉ | 1780/2000 [01:35<00:11, 18.73it/s]

Epoch 5:  89%|████████▉ | 1782/2000 [01:35<00:11, 18.73it/s]

Epoch 5:  89%|████████▉ | 1784/2000 [01:35<00:11, 18.73it/s]

Epoch 5:  89%|████████▉ | 1786/2000 [01:35<00:11, 18.73it/s]

Epoch 5:  89%|████████▉ | 1788/2000 [01:35<00:11, 18.74it/s]

Epoch 5:  90%|████████▉ | 1790/2000 [01:35<00:11, 18.74it/s]

Epoch 5:  90%|████████▉ | 1792/2000 [01:35<00:11, 18.74it/s]

Epoch 5:  90%|████████▉ | 1794/2000 [01:35<00:10, 18.73it/s]

Epoch 5:  90%|████████▉ | 1796/2000 [01:36<00:10, 18.73it/s]

Epoch 5:  90%|████████▉ | 1798/2000 [01:36<00:10, 18.72it/s]

Epoch 5:  90%|█████████ | 1800/2000 [01:36<00:10, 18.72it/s]

Epoch 5:  90%|█████████ | 1802/2000 [01:36<00:10, 18.72it/s]

Epoch 5:  90%|█████████ | 1804/2000 [01:36<00:10, 18.72it/s]

Epoch 5:  90%|█████████ | 1806/2000 [01:36<00:10, 18.74it/s]

Epoch 5:  90%|█████████ | 1808/2000 [01:36<00:10, 18.74it/s]

Epoch 5:  90%|█████████ | 1810/2000 [01:36<00:10, 18.75it/s]

Epoch 5:  91%|█████████ | 1812/2000 [01:36<00:10, 18.75it/s]

Epoch 5:  91%|█████████ | 1814/2000 [01:37<00:09, 18.75it/s]

Epoch 5:  91%|█████████ | 1816/2000 [01:37<00:09, 18.74it/s]

Epoch 5:  91%|█████████ | 1818/2000 [01:37<00:09, 18.74it/s]

Epoch 5:  91%|█████████ | 1820/2000 [01:37<00:09, 18.73it/s]

Epoch 5:  91%|█████████ | 1822/2000 [01:37<00:09, 18.74it/s]

Epoch 5:  91%|█████████ | 1824/2000 [01:37<00:09, 18.74it/s]

Epoch 5:  91%|█████████▏| 1826/2000 [01:37<00:09, 18.74it/s]

Epoch 5:  91%|█████████▏| 1828/2000 [01:37<00:09, 18.74it/s]

Epoch 5:  92%|█████████▏| 1830/2000 [01:37<00:09, 18.73it/s]

Epoch 5:  92%|█████████▏| 1832/2000 [01:37<00:08, 18.72it/s]

Epoch 5:  92%|█████████▏| 1834/2000 [01:38<00:08, 18.73it/s]

Epoch 5:  92%|█████████▏| 1836/2000 [01:38<00:08, 18.73it/s]

Epoch 5:  92%|█████████▏| 1838/2000 [01:38<00:08, 18.72it/s]

Epoch 5:  92%|█████████▏| 1840/2000 [01:38<00:08, 18.73it/s]

Epoch 5:  92%|█████████▏| 1842/2000 [01:38<00:08, 18.72it/s]

Epoch 5:  92%|█████████▏| 1844/2000 [01:38<00:08, 18.72it/s]

Epoch 5:  92%|█████████▏| 1846/2000 [01:38<00:08, 18.73it/s]

Epoch 5:  92%|█████████▏| 1848/2000 [01:38<00:08, 18.74it/s]

Epoch 5:  92%|█████████▎| 1850/2000 [01:38<00:08, 18.73it/s]

Epoch 5:  93%|█████████▎| 1852/2000 [01:39<00:07, 18.74it/s]

Epoch 5:  93%|█████████▎| 1854/2000 [01:39<00:07, 18.73it/s]

Epoch 5:  93%|█████████▎| 1856/2000 [01:39<00:07, 18.75it/s]

Epoch 5:  93%|█████████▎| 1858/2000 [01:39<00:07, 18.74it/s]

Epoch 5:  93%|█████████▎| 1860/2000 [01:39<00:07, 18.74it/s]

Epoch 5:  93%|█████████▎| 1862/2000 [01:39<00:07, 18.73it/s]

Epoch 5:  93%|█████████▎| 1864/2000 [01:39<00:07, 18.74it/s]

Epoch 5:  93%|█████████▎| 1866/2000 [01:39<00:07, 18.75it/s]

Epoch 5:  93%|█████████▎| 1868/2000 [01:39<00:07, 18.74it/s]

Epoch 5:  94%|█████████▎| 1870/2000 [01:40<00:06, 18.74it/s]

Epoch 5:  94%|█████████▎| 1872/2000 [01:40<00:06, 18.73it/s]

Epoch 5:  94%|█████████▎| 1874/2000 [01:40<00:06, 18.74it/s]

Epoch 5:  94%|█████████▍| 1876/2000 [01:40<00:06, 18.73it/s]

Epoch 5:  94%|█████████▍| 1878/2000 [01:40<00:06, 18.74it/s]

Epoch 5:  94%|█████████▍| 1880/2000 [01:40<00:06, 18.73it/s]

Epoch 5:  94%|█████████▍| 1882/2000 [01:40<00:06, 18.74it/s]

Epoch 5:  94%|█████████▍| 1884/2000 [01:40<00:06, 18.75it/s]

Epoch 5:  94%|█████████▍| 1886/2000 [01:40<00:06, 18.74it/s]

Epoch 5:  94%|█████████▍| 1888/2000 [01:40<00:05, 18.75it/s]

Epoch 5:  94%|█████████▍| 1890/2000 [01:41<00:05, 18.74it/s]

Epoch 5:  95%|█████████▍| 1892/2000 [01:41<00:05, 18.75it/s]

Epoch 5:  95%|█████████▍| 1894/2000 [01:41<00:05, 18.74it/s]

Epoch 5:  95%|█████████▍| 1896/2000 [01:41<00:05, 18.74it/s]

Epoch 5:  95%|█████████▍| 1898/2000 [01:41<00:05, 18.75it/s]

Epoch 5:  95%|█████████▌| 1900/2000 [01:41<00:05, 18.75it/s]

Epoch 5:  95%|█████████▌| 1902/2000 [01:41<00:05, 18.74it/s]

Epoch 5:  95%|█████████▌| 1904/2000 [01:41<00:05, 18.75it/s]

Epoch 5:  95%|█████████▌| 1906/2000 [01:41<00:05, 18.73it/s]

Epoch 5:  95%|█████████▌| 1908/2000 [01:42<00:04, 18.74it/s]

Epoch 5:  96%|█████████▌| 1910/2000 [01:42<00:04, 18.74it/s]

Epoch 5:  96%|█████████▌| 1912/2000 [01:42<00:04, 18.75it/s]

Epoch 5:  96%|█████████▌| 1914/2000 [01:42<00:04, 18.75it/s]

Epoch 5:  96%|█████████▌| 1916/2000 [01:42<00:04, 18.75it/s]

Epoch 5:  96%|█████████▌| 1918/2000 [01:42<00:04, 18.75it/s]

Epoch 5:  96%|█████████▌| 1920/2000 [01:42<00:04, 18.75it/s]

Epoch 5:  96%|█████████▌| 1922/2000 [01:42<00:04, 18.75it/s]

Epoch 5:  96%|█████████▌| 1924/2000 [01:42<00:04, 18.74it/s]

Epoch 5:  96%|█████████▋| 1926/2000 [01:43<00:03, 18.75it/s]

Epoch 5:  96%|█████████▋| 1928/2000 [01:43<00:03, 18.75it/s]

Epoch 5:  96%|█████████▋| 1930/2000 [01:43<00:03, 18.75it/s]

Epoch 5:  97%|█████████▋| 1932/2000 [01:43<00:03, 18.76it/s]

Epoch 5:  97%|█████████▋| 1934/2000 [01:43<00:03, 18.76it/s]

Epoch 5:  97%|█████████▋| 1936/2000 [01:43<00:03, 18.75it/s]

Epoch 5:  97%|█████████▋| 1938/2000 [01:43<00:03, 18.75it/s]

Epoch 5:  97%|█████████▋| 1940/2000 [01:43<00:03, 18.74it/s]

Epoch 5:  97%|█████████▋| 1942/2000 [01:43<00:03, 18.74it/s]

Epoch 5:  97%|█████████▋| 1944/2000 [01:43<00:02, 18.74it/s]

Epoch 5:  97%|█████████▋| 1946/2000 [01:44<00:02, 18.74it/s]

Epoch 5:  97%|█████████▋| 1948/2000 [01:44<00:02, 18.74it/s]

Epoch 5:  98%|█████████▊| 1950/2000 [01:44<00:02, 18.74it/s]

Epoch 5:  98%|█████████▊| 1952/2000 [01:44<00:02, 18.75it/s]

Epoch 5:  98%|█████████▊| 1954/2000 [01:44<00:02, 18.75it/s]

Epoch 5:  98%|█████████▊| 1956/2000 [01:44<00:02, 18.75it/s]

Epoch 5:  98%|█████████▊| 1958/2000 [01:44<00:02, 18.75it/s]

Epoch 5:  98%|█████████▊| 1960/2000 [01:44<00:02, 18.74it/s]

Epoch 5:  98%|█████████▊| 1962/2000 [01:44<00:02, 18.76it/s]

Epoch 5:  98%|█████████▊| 1964/2000 [01:45<00:01, 18.77it/s]

Epoch 5:  98%|█████████▊| 1966/2000 [01:45<00:01, 18.75it/s]

Epoch 5:  98%|█████████▊| 1968/2000 [01:45<00:01, 18.76it/s]

Epoch 5:  98%|█████████▊| 1970/2000 [01:45<00:01, 18.75it/s]

Epoch 5:  99%|█████████▊| 1972/2000 [01:45<00:01, 18.76it/s]

Epoch 5:  99%|█████████▊| 1974/2000 [01:45<00:01, 18.76it/s]

Epoch 5:  99%|█████████▉| 1976/2000 [01:45<00:01, 18.75it/s]

Epoch 5:  99%|█████████▉| 1978/2000 [01:45<00:01, 18.75it/s]

Epoch 5:  99%|█████████▉| 1980/2000 [01:45<00:01, 18.76it/s]

Epoch 5:  99%|█████████▉| 1982/2000 [01:45<00:00, 18.74it/s]

Epoch 5:  99%|█████████▉| 1984/2000 [01:46<00:00, 18.75it/s]

Epoch 5:  99%|█████████▉| 1986/2000 [01:46<00:00, 18.76it/s]

Epoch 5:  99%|█████████▉| 1988/2000 [01:46<00:00, 18.76it/s]

Epoch 5: 100%|█████████▉| 1990/2000 [01:46<00:00, 18.76it/s]

Epoch 5: 100%|█████████▉| 1992/2000 [01:46<00:00, 18.77it/s]

Epoch 5: 100%|█████████▉| 1994/2000 [01:46<00:00, 18.77it/s]

Epoch 5: 100%|█████████▉| 1996/2000 [01:46<00:00, 18.76it/s]

Epoch 5: 100%|█████████▉| 1998/2000 [01:46<00:00, 18.75it/s]

Epoch 5: 100%|██████████| 2000/2000 [01:46<00:00, 18.74it/s]

Epoch 5: loss=0.2162, val_proxy=0.9409

Epoch 6:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 6:   0%|          | 2/2000 [00:00<01:49, 18.29it/s]

Epoch 6:   0%|          | 4/2000 [00:00<01:48, 18.46it/s]

Epoch 6:   0%|          | 6/2000 [00:00<01:47, 18.52it/s]

Epoch 6:   0%|          | 8/2000 [00:00<01:47, 18.52it/s]

Epoch 6:   0%|          | 10/2000 [00:00<01:47, 18.53it/s]

Epoch 6:   1%|          | 12/2000 [00:00<01:47, 18.54it/s]

Epoch 6:   1%|          | 14/2000 [00:00<01:47, 18.54it/s]

Epoch 6:   1%|          | 16/2000 [00:00<01:46, 18.56it/s]

Epoch 6:   1%|          | 18/2000 [00:00<01:46, 18.58it/s]

Epoch 6:   1%|          | 20/2000 [00:01<01:46, 18.57it/s]

Epoch 6:   1%|          | 22/2000 [00:01<01:46, 18.57it/s]

Epoch 6:   1%|          | 24/2000 [00:01<01:46, 18.57it/s]

Epoch 6:   1%|▏         | 26/2000 [00:01<01:46, 18.58it/s]

Epoch 6:   1%|▏         | 28/2000 [00:01<01:46, 18.57it/s]

Epoch 6:   2%|▏         | 30/2000 [00:01<01:46, 18.57it/s]

Epoch 6:   2%|▏         | 32/2000 [00:01<01:45, 18.57it/s]

Epoch 6:   2%|▏         | 34/2000 [00:01<01:45, 18.57it/s]

Epoch 6:   2%|▏         | 36/2000 [00:01<01:45, 18.59it/s]

Epoch 6:   2%|▏         | 38/2000 [00:02<01:45, 18.59it/s]

Epoch 6:   2%|▏         | 40/2000 [00:02<01:45, 18.58it/s]

Epoch 6:   2%|▏         | 42/2000 [00:02<01:45, 18.58it/s]

Epoch 6:   2%|▏         | 44/2000 [00:02<01:45, 18.60it/s]

Epoch 6:   2%|▏         | 46/2000 [00:02<01:44, 18.61it/s]

Epoch 6:   2%|▏         | 48/2000 [00:02<01:44, 18.61it/s]

Epoch 6:   2%|▎         | 50/2000 [00:02<01:44, 18.61it/s]

Epoch 6:   3%|▎         | 52/2000 [00:02<01:44, 18.59it/s]

Epoch 6:   3%|▎         | 54/2000 [00:02<01:44, 18.59it/s]

Epoch 6:   3%|▎         | 56/2000 [00:03<01:44, 18.59it/s]

Epoch 6:   3%|▎         | 58/2000 [00:03<01:44, 18.58it/s]

Epoch 6:   3%|▎         | 60/2000 [00:03<01:44, 18.59it/s]

Epoch 6:   3%|▎         | 62/2000 [00:03<01:44, 18.60it/s]

Epoch 6:   3%|▎         | 64/2000 [00:03<01:44, 18.59it/s]

Epoch 6:   3%|▎         | 66/2000 [00:03<01:43, 18.60it/s]

Epoch 6:   3%|▎         | 68/2000 [00:03<01:43, 18.58it/s]

Epoch 6:   4%|▎         | 70/2000 [00:03<01:43, 18.59it/s]

Epoch 6:   4%|▎         | 72/2000 [00:03<01:43, 18.59it/s]

Epoch 6:   4%|▎         | 74/2000 [00:03<01:43, 18.59it/s]

Epoch 6:   4%|▍         | 76/2000 [00:04<01:43, 18.59it/s]

Epoch 6:   4%|▍         | 78/2000 [00:04<01:43, 18.59it/s]

Epoch 6:   4%|▍         | 80/2000 [00:04<01:43, 18.59it/s]

Epoch 6:   4%|▍         | 82/2000 [00:04<01:43, 18.60it/s]

Epoch 6:   4%|▍         | 84/2000 [00:04<01:43, 18.60it/s]

Epoch 6:   4%|▍         | 86/2000 [00:04<01:42, 18.58it/s]

Epoch 6:   4%|▍         | 88/2000 [00:04<01:42, 18.57it/s]

Epoch 6:   4%|▍         | 90/2000 [00:04<01:42, 18.59it/s]

Epoch 6:   5%|▍         | 92/2000 [00:04<01:42, 18.59it/s]

Epoch 6:   5%|▍         | 94/2000 [00:05<01:42, 18.59it/s]

Epoch 6:   5%|▍         | 96/2000 [00:05<01:42, 18.61it/s]

Epoch 6:   5%|▍         | 98/2000 [00:05<01:41, 18.68it/s]

Epoch 6:   5%|▌         | 100/2000 [00:05<01:41, 18.73it/s]

Epoch 6:   5%|▌         | 102/2000 [00:05<01:41, 18.74it/s]

Epoch 6:   5%|▌         | 104/2000 [00:05<01:41, 18.75it/s]

Epoch 6:   5%|▌         | 106/2000 [00:05<01:40, 18.76it/s]

Epoch 6:   5%|▌         | 108/2000 [00:05<01:40, 18.78it/s]

Epoch 6:   6%|▌         | 110/2000 [00:05<01:40, 18.78it/s]

Epoch 6:   6%|▌         | 112/2000 [00:06<01:40, 18.78it/s]

Epoch 6:   6%|▌         | 114/2000 [00:06<01:40, 18.79it/s]

Epoch 6:   6%|▌         | 116/2000 [00:06<01:40, 18.80it/s]

Epoch 6:   6%|▌         | 118/2000 [00:06<01:40, 18.79it/s]

Epoch 6:   6%|▌         | 120/2000 [00:06<01:40, 18.80it/s]

Epoch 6:   6%|▌         | 122/2000 [00:06<01:39, 18.81it/s]

Epoch 6:   6%|▌         | 124/2000 [00:06<01:39, 18.82it/s]

Epoch 6:   6%|▋         | 126/2000 [00:06<01:39, 18.81it/s]

Epoch 6:   6%|▋         | 128/2000 [00:06<01:39, 18.81it/s]

Epoch 6:   6%|▋         | 130/2000 [00:06<01:39, 18.80it/s]

Epoch 6:   7%|▋         | 132/2000 [00:07<01:39, 18.80it/s]

Epoch 6:   7%|▋         | 134/2000 [00:07<01:39, 18.80it/s]

Epoch 6:   7%|▋         | 136/2000 [00:07<01:39, 18.80it/s]

Epoch 6:   7%|▋         | 138/2000 [00:07<01:39, 18.80it/s]

Epoch 6:   7%|▋         | 140/2000 [00:07<01:38, 18.79it/s]

Epoch 6:   7%|▋         | 142/2000 [00:07<01:38, 18.79it/s]

Epoch 6:   7%|▋         | 144/2000 [00:07<01:38, 18.80it/s]

Epoch 6:   7%|▋         | 146/2000 [00:07<01:38, 18.80it/s]

Epoch 6:   7%|▋         | 148/2000 [00:07<01:38, 18.81it/s]

Epoch 6:   8%|▊         | 150/2000 [00:08<01:38, 18.81it/s]

Epoch 6:   8%|▊         | 152/2000 [00:08<01:38, 18.81it/s]

Epoch 6:   8%|▊         | 154/2000 [00:08<01:38, 18.81it/s]

Epoch 6:   8%|▊         | 156/2000 [00:08<01:37, 18.82it/s]

Epoch 6:   8%|▊         | 158/2000 [00:08<01:37, 18.82it/s]

Epoch 6:   8%|▊         | 160/2000 [00:08<01:37, 18.82it/s]

Epoch 6:   8%|▊         | 162/2000 [00:08<01:37, 18.83it/s]

Epoch 6:   8%|▊         | 164/2000 [00:08<01:37, 18.82it/s]

Epoch 6:   8%|▊         | 166/2000 [00:08<01:37, 18.82it/s]

Epoch 6:   8%|▊         | 168/2000 [00:08<01:37, 18.82it/s]

Epoch 6:   8%|▊         | 170/2000 [00:09<01:37, 18.80it/s]

Epoch 6:   9%|▊         | 172/2000 [00:09<01:37, 18.80it/s]

Epoch 6:   9%|▊         | 174/2000 [00:09<01:37, 18.81it/s]

Epoch 6:   9%|▉         | 176/2000 [00:09<01:36, 18.81it/s]

Epoch 6:   9%|▉         | 178/2000 [00:09<01:36, 18.81it/s]

Epoch 6:   9%|▉         | 180/2000 [00:09<01:36, 18.81it/s]

Epoch 6:   9%|▉         | 182/2000 [00:09<01:36, 18.81it/s]

Epoch 6:   9%|▉         | 184/2000 [00:09<01:36, 18.81it/s]

Epoch 6:   9%|▉         | 186/2000 [00:09<01:36, 18.81it/s]

Epoch 6:   9%|▉         | 188/2000 [00:10<01:36, 18.81it/s]

Epoch 6:  10%|▉         | 190/2000 [00:10<01:36, 18.82it/s]

Epoch 6:  10%|▉         | 192/2000 [00:10<01:36, 18.81it/s]

Epoch 6:  10%|▉         | 194/2000 [00:10<01:36, 18.81it/s]

Epoch 6:  10%|▉         | 196/2000 [00:10<01:35, 18.81it/s]

Epoch 6:  10%|▉         | 198/2000 [00:10<01:35, 18.81it/s]

Epoch 6:  10%|█         | 200/2000 [00:10<01:35, 18.81it/s]

Epoch 6:  10%|█         | 202/2000 [00:10<01:35, 18.82it/s]

Epoch 6:  10%|█         | 204/2000 [00:10<01:35, 18.80it/s]

Epoch 6:  10%|█         | 206/2000 [00:11<01:35, 18.80it/s]

Epoch 6:  10%|█         | 208/2000 [00:11<01:35, 18.81it/s]

Epoch 6:  10%|█         | 210/2000 [00:11<01:35, 18.82it/s]

Epoch 6:  11%|█         | 212/2000 [00:11<01:35, 18.81it/s]

Epoch 6:  11%|█         | 214/2000 [00:11<01:34, 18.81it/s]

Epoch 6:  11%|█         | 216/2000 [00:11<01:34, 18.79it/s]

Epoch 6:  11%|█         | 218/2000 [00:11<01:34, 18.80it/s]

Epoch 6:  11%|█         | 220/2000 [00:11<01:34, 18.80it/s]

Epoch 6:  11%|█         | 222/2000 [00:11<01:34, 18.80it/s]

Epoch 6:  11%|█         | 224/2000 [00:11<01:34, 18.80it/s]

Epoch 6:  11%|█▏        | 226/2000 [00:12<01:34, 18.80it/s]

Epoch 6:  11%|█▏        | 228/2000 [00:12<01:34, 18.81it/s]

Epoch 6:  12%|█▏        | 230/2000 [00:12<01:34, 18.80it/s]

Epoch 6:  12%|█▏        | 232/2000 [00:12<01:34, 18.79it/s]

Epoch 6:  12%|█▏        | 234/2000 [00:12<01:33, 18.81it/s]

Epoch 6:  12%|█▏        | 236/2000 [00:12<01:33, 18.81it/s]

Epoch 6:  12%|█▏        | 238/2000 [00:12<01:33, 18.81it/s]

Epoch 6:  12%|█▏        | 240/2000 [00:12<01:33, 18.80it/s]

Epoch 6:  12%|█▏        | 242/2000 [00:12<01:33, 18.80it/s]

Epoch 6:  12%|█▏        | 244/2000 [00:13<01:33, 18.80it/s]

Epoch 6:  12%|█▏        | 246/2000 [00:13<01:33, 18.79it/s]

Epoch 6:  12%|█▏        | 248/2000 [00:13<01:33, 18.79it/s]

Epoch 6:  12%|█▎        | 250/2000 [00:13<01:33, 18.78it/s]

Epoch 6:  13%|█▎        | 252/2000 [00:13<01:33, 18.78it/s]

Epoch 6:  13%|█▎        | 254/2000 [00:13<01:32, 18.78it/s]

Epoch 6:  13%|█▎        | 256/2000 [00:13<01:32, 18.79it/s]

Epoch 6:  13%|█▎        | 258/2000 [00:13<01:32, 18.81it/s]

Epoch 6:  13%|█▎        | 260/2000 [00:13<01:32, 18.80it/s]

Epoch 6:  13%|█▎        | 262/2000 [00:13<01:32, 18.79it/s]

Epoch 6:  13%|█▎        | 264/2000 [00:14<01:32, 18.79it/s]

Epoch 6:  13%|█▎        | 266/2000 [00:14<01:32, 18.77it/s]

Epoch 6:  13%|█▎        | 268/2000 [00:14<01:32, 18.77it/s]

Epoch 6:  14%|█▎        | 270/2000 [00:14<01:32, 18.77it/s]

Epoch 6:  14%|█▎        | 272/2000 [00:14<01:32, 18.77it/s]

Epoch 6:  14%|█▎        | 274/2000 [00:14<01:31, 18.78it/s]

Epoch 6:  14%|█▍        | 276/2000 [00:14<01:31, 18.80it/s]

Epoch 6:  14%|█▍        | 278/2000 [00:14<01:31, 18.79it/s]

Epoch 6:  14%|█▍        | 280/2000 [00:14<01:31, 18.79it/s]

Epoch 6:  14%|█▍        | 282/2000 [00:15<01:31, 18.80it/s]

Epoch 6:  14%|█▍        | 284/2000 [00:15<01:31, 18.80it/s]

Epoch 6:  14%|█▍        | 286/2000 [00:15<01:31, 18.78it/s]

Epoch 6:  14%|█▍        | 288/2000 [00:15<01:31, 18.79it/s]

Epoch 6:  14%|█▍        | 290/2000 [00:15<01:30, 18.80it/s]

Epoch 6:  15%|█▍        | 292/2000 [00:15<01:30, 18.79it/s]

Epoch 6:  15%|█▍        | 294/2000 [00:15<01:30, 18.79it/s]

Epoch 6:  15%|█▍        | 296/2000 [00:15<01:30, 18.80it/s]

Epoch 6:  15%|█▍        | 298/2000 [00:15<01:30, 18.80it/s]

Epoch 6:  15%|█▌        | 300/2000 [00:16<01:30, 18.80it/s]

Epoch 6:  15%|█▌        | 302/2000 [00:16<01:30, 18.80it/s]

Epoch 6:  15%|█▌        | 304/2000 [00:16<01:30, 18.79it/s]

Epoch 6:  15%|█▌        | 306/2000 [00:16<01:30, 18.78it/s]

Epoch 6:  15%|█▌        | 308/2000 [00:16<01:30, 18.77it/s]

Epoch 6:  16%|█▌        | 310/2000 [00:16<01:29, 18.78it/s]

Epoch 6:  16%|█▌        | 312/2000 [00:16<01:29, 18.78it/s]

Epoch 6:  16%|█▌        | 314/2000 [00:16<01:29, 18.79it/s]

Epoch 6:  16%|█▌        | 316/2000 [00:16<01:29, 18.78it/s]

Epoch 6:  16%|█▌        | 318/2000 [00:16<01:29, 18.78it/s]

Epoch 6:  16%|█▌        | 320/2000 [00:17<01:29, 18.78it/s]

Epoch 6:  16%|█▌        | 322/2000 [00:17<01:29, 18.79it/s]

Epoch 6:  16%|█▌        | 324/2000 [00:17<01:29, 18.79it/s]

Epoch 6:  16%|█▋        | 326/2000 [00:17<01:29, 18.79it/s]

Epoch 6:  16%|█▋        | 328/2000 [00:17<01:28, 18.79it/s]

Epoch 6:  16%|█▋        | 330/2000 [00:17<01:28, 18.80it/s]

Epoch 6:  17%|█▋        | 332/2000 [00:17<01:28, 18.81it/s]

Epoch 6:  17%|█▋        | 334/2000 [00:17<01:28, 18.81it/s]

Epoch 6:  17%|█▋        | 336/2000 [00:17<01:28, 18.80it/s]

Epoch 6:  17%|█▋        | 338/2000 [00:18<01:28, 18.81it/s]

Epoch 6:  17%|█▋        | 340/2000 [00:18<01:28, 18.82it/s]

Epoch 6:  17%|█▋        | 342/2000 [00:18<01:28, 18.82it/s]

Epoch 6:  17%|█▋        | 344/2000 [00:18<01:27, 18.84it/s]

Epoch 6:  17%|█▋        | 346/2000 [00:18<01:27, 18.84it/s]

Epoch 6:  17%|█▋        | 348/2000 [00:18<01:27, 18.83it/s]

Epoch 6:  18%|█▊        | 350/2000 [00:18<01:27, 18.82it/s]

Epoch 6:  18%|█▊        | 352/2000 [00:18<01:27, 18.81it/s]

Epoch 6:  18%|█▊        | 354/2000 [00:18<01:27, 18.80it/s]

Epoch 6:  18%|█▊        | 356/2000 [00:18<01:27, 18.81it/s]

Epoch 6:  18%|█▊        | 358/2000 [00:19<01:27, 18.80it/s]

Epoch 6:  18%|█▊        | 360/2000 [00:19<01:27, 18.79it/s]

Epoch 6:  18%|█▊        | 362/2000 [00:19<01:27, 18.78it/s]

Epoch 6:  18%|█▊        | 364/2000 [00:19<01:27, 18.80it/s]

Epoch 6:  18%|█▊        | 366/2000 [00:19<01:26, 18.79it/s]

Epoch 6:  18%|█▊        | 368/2000 [00:19<01:26, 18.79it/s]

Epoch 6:  18%|█▊        | 370/2000 [00:19<01:26, 18.79it/s]

Epoch 6:  19%|█▊        | 372/2000 [00:19<01:26, 18.77it/s]

Epoch 6:  19%|█▊        | 374/2000 [00:19<01:26, 18.77it/s]

Epoch 6:  19%|█▉        | 376/2000 [00:20<01:26, 18.77it/s]

Epoch 6:  19%|█▉        | 378/2000 [00:20<01:26, 18.78it/s]

Epoch 6:  19%|█▉        | 380/2000 [00:20<01:26, 18.78it/s]

Epoch 6:  19%|█▉        | 382/2000 [00:20<01:26, 18.79it/s]

Epoch 6:  19%|█▉        | 384/2000 [00:20<01:25, 18.79it/s]

Epoch 6:  19%|█▉        | 386/2000 [00:20<01:25, 18.78it/s]

Epoch 6:  19%|█▉        | 388/2000 [00:20<01:25, 18.80it/s]

Epoch 6:  20%|█▉        | 390/2000 [00:20<01:25, 18.80it/s]

Epoch 6:  20%|█▉        | 392/2000 [00:20<01:25, 18.78it/s]

Epoch 6:  20%|█▉        | 394/2000 [00:21<01:25, 18.79it/s]

Epoch 6:  20%|█▉        | 396/2000 [00:21<01:25, 18.79it/s]

Epoch 6:  20%|█▉        | 398/2000 [00:21<01:25, 18.79it/s]

Epoch 6:  20%|██        | 400/2000 [00:21<01:25, 18.78it/s]

Epoch 6:  20%|██        | 402/2000 [00:21<01:25, 18.79it/s]

Epoch 6:  20%|██        | 404/2000 [00:21<01:24, 18.79it/s]

Epoch 6:  20%|██        | 406/2000 [00:21<01:24, 18.79it/s]

Epoch 6:  20%|██        | 408/2000 [00:21<01:24, 18.79it/s]

Epoch 6:  20%|██        | 410/2000 [00:21<01:24, 18.80it/s]

Epoch 6:  21%|██        | 412/2000 [00:21<01:24, 18.79it/s]

Epoch 6:  21%|██        | 414/2000 [00:22<01:24, 18.77it/s]

Epoch 6:  21%|██        | 416/2000 [00:22<01:24, 18.79it/s]

Epoch 6:  21%|██        | 418/2000 [00:22<01:24, 18.79it/s]

Epoch 6:  21%|██        | 420/2000 [00:22<01:24, 18.80it/s]

Epoch 6:  21%|██        | 422/2000 [00:22<01:23, 18.80it/s]

Epoch 6:  21%|██        | 424/2000 [00:22<01:23, 18.80it/s]

Epoch 6:  21%|██▏       | 426/2000 [00:22<01:23, 18.81it/s]

Epoch 6:  21%|██▏       | 428/2000 [00:22<01:23, 18.79it/s]

Epoch 6:  22%|██▏       | 430/2000 [00:22<01:23, 18.79it/s]

Epoch 6:  22%|██▏       | 432/2000 [00:23<01:23, 18.79it/s]

Epoch 6:  22%|██▏       | 434/2000 [00:23<01:23, 18.78it/s]

Epoch 6:  22%|██▏       | 436/2000 [00:23<01:23, 18.79it/s]

Epoch 6:  22%|██▏       | 438/2000 [00:23<01:23, 18.79it/s]

Epoch 6:  22%|██▏       | 440/2000 [00:23<01:23, 18.79it/s]

Epoch 6:  22%|██▏       | 442/2000 [00:23<01:22, 18.79it/s]

Epoch 6:  22%|██▏       | 444/2000 [00:23<01:22, 18.79it/s]

Epoch 6:  22%|██▏       | 446/2000 [00:23<01:22, 18.78it/s]

Epoch 6:  22%|██▏       | 448/2000 [00:23<01:22, 18.79it/s]

Epoch 6:  22%|██▎       | 450/2000 [00:23<01:22, 18.80it/s]

Epoch 6:  23%|██▎       | 452/2000 [00:24<01:22, 18.80it/s]

Epoch 6:  23%|██▎       | 454/2000 [00:24<01:22, 18.80it/s]

Epoch 6:  23%|██▎       | 456/2000 [00:24<01:22, 18.79it/s]

Epoch 6:  23%|██▎       | 458/2000 [00:24<01:22, 18.79it/s]

Epoch 6:  23%|██▎       | 460/2000 [00:24<01:21, 18.80it/s]

Epoch 6:  23%|██▎       | 462/2000 [00:24<01:21, 18.79it/s]

Epoch 6:  23%|██▎       | 464/2000 [00:24<01:21, 18.80it/s]

Epoch 6:  23%|██▎       | 466/2000 [00:24<01:21, 18.79it/s]

Epoch 6:  23%|██▎       | 468/2000 [00:24<01:21, 18.80it/s]

Epoch 6:  24%|██▎       | 470/2000 [00:25<01:21, 18.81it/s]

Epoch 6:  24%|██▎       | 472/2000 [00:25<01:21, 18.80it/s]

Epoch 6:  24%|██▎       | 474/2000 [00:25<01:21, 18.81it/s]

Epoch 6:  24%|██▍       | 476/2000 [00:25<01:21, 18.81it/s]

Epoch 6:  24%|██▍       | 478/2000 [00:25<01:20, 18.81it/s]

Epoch 6:  24%|██▍       | 480/2000 [00:25<01:20, 18.78it/s]

Epoch 6:  24%|██▍       | 482/2000 [00:25<01:20, 18.79it/s]

Epoch 6:  24%|██▍       | 484/2000 [00:25<01:20, 18.78it/s]

Epoch 6:  24%|██▍       | 486/2000 [00:25<01:20, 18.80it/s]

Epoch 6:  24%|██▍       | 488/2000 [00:26<01:20, 18.80it/s]

Epoch 6:  24%|██▍       | 490/2000 [00:26<01:20, 18.80it/s]

Epoch 6:  25%|██▍       | 492/2000 [00:26<01:20, 18.78it/s]

Epoch 6:  25%|██▍       | 494/2000 [00:26<01:20, 18.79it/s]

Epoch 6:  25%|██▍       | 496/2000 [00:26<01:20, 18.79it/s]

Epoch 6:  25%|██▍       | 498/2000 [00:26<01:19, 18.78it/s]

Epoch 6:  25%|██▌       | 500/2000 [00:26<01:19, 18.78it/s]

Epoch 6:  25%|██▌       | 502/2000 [00:26<01:19, 18.79it/s]

Epoch 6:  25%|██▌       | 504/2000 [00:26<01:19, 18.78it/s]

Epoch 6:  25%|██▌       | 506/2000 [00:26<01:19, 18.79it/s]

Epoch 6:  25%|██▌       | 508/2000 [00:27<01:19, 18.78it/s]

Epoch 6:  26%|██▌       | 510/2000 [00:27<01:19, 18.78it/s]

Epoch 6:  26%|██▌       | 512/2000 [00:27<01:19, 18.78it/s]

Epoch 6:  26%|██▌       | 514/2000 [00:27<01:19, 18.79it/s]

Epoch 6:  26%|██▌       | 516/2000 [00:27<01:19, 18.78it/s]

Epoch 6:  26%|██▌       | 518/2000 [00:27<01:18, 18.79it/s]

Epoch 6:  26%|██▌       | 520/2000 [00:27<01:18, 18.79it/s]

Epoch 6:  26%|██▌       | 522/2000 [00:27<01:18, 18.79it/s]

Epoch 6:  26%|██▌       | 524/2000 [00:27<01:18, 18.78it/s]

Epoch 6:  26%|██▋       | 526/2000 [00:28<01:18, 18.77it/s]

Epoch 6:  26%|██▋       | 528/2000 [00:28<01:18, 18.78it/s]

Epoch 6:  26%|██▋       | 530/2000 [00:28<01:18, 18.78it/s]

Epoch 6:  27%|██▋       | 532/2000 [00:28<01:18, 18.78it/s]

Epoch 6:  27%|██▋       | 534/2000 [00:28<01:18, 18.78it/s]

Epoch 6:  27%|██▋       | 536/2000 [00:28<01:17, 18.78it/s]

Epoch 6:  27%|██▋       | 538/2000 [00:28<01:17, 18.79it/s]

Epoch 6:  27%|██▋       | 540/2000 [00:28<01:17, 18.79it/s]

Epoch 6:  27%|██▋       | 542/2000 [00:28<01:17, 18.79it/s]

Epoch 6:  27%|██▋       | 544/2000 [00:29<01:17, 18.79it/s]

Epoch 6:  27%|██▋       | 546/2000 [00:29<01:17, 18.79it/s]

Epoch 6:  27%|██▋       | 548/2000 [00:29<01:17, 18.79it/s]

Epoch 6:  28%|██▊       | 550/2000 [00:29<01:17, 18.81it/s]

Epoch 6:  28%|██▊       | 552/2000 [00:29<01:17, 18.80it/s]

Epoch 6:  28%|██▊       | 554/2000 [00:29<01:16, 18.80it/s]

Epoch 6:  28%|██▊       | 556/2000 [00:29<01:16, 18.78it/s]

Epoch 6:  28%|██▊       | 558/2000 [00:29<01:16, 18.79it/s]

Epoch 6:  28%|██▊       | 560/2000 [00:29<01:16, 18.80it/s]

Epoch 6:  28%|██▊       | 562/2000 [00:29<01:16, 18.80it/s]

Epoch 6:  28%|██▊       | 564/2000 [00:30<01:16, 18.80it/s]

Epoch 6:  28%|██▊       | 566/2000 [00:30<01:16, 18.79it/s]

Epoch 6:  28%|██▊       | 568/2000 [00:30<01:16, 18.78it/s]

Epoch 6:  28%|██▊       | 570/2000 [00:30<01:16, 18.61it/s]

Epoch 6:  29%|██▊       | 572/2000 [00:30<01:19, 18.03it/s]

Epoch 6:  29%|██▊       | 574/2000 [00:30<01:19, 18.03it/s]

Epoch 6:  29%|██▉       | 576/2000 [00:30<01:18, 18.16it/s]

Epoch 6:  29%|██▉       | 578/2000 [00:30<01:17, 18.31it/s]

Epoch 6:  29%|██▉       | 580/2000 [00:30<01:17, 18.41it/s]

Epoch 6:  29%|██▉       | 582/2000 [00:31<01:16, 18.51it/s]

Epoch 6:  29%|██▉       | 584/2000 [00:31<01:16, 18.60it/s]

Epoch 6:  29%|██▉       | 586/2000 [00:31<01:15, 18.64it/s]

Epoch 6:  29%|██▉       | 588/2000 [00:31<01:15, 18.68it/s]

Epoch 6:  30%|██▉       | 590/2000 [00:31<01:15, 18.72it/s]

Epoch 6:  30%|██▉       | 592/2000 [00:31<01:15, 18.73it/s]

Epoch 6:  30%|██▉       | 594/2000 [00:31<01:14, 18.76it/s]

Epoch 6:  30%|██▉       | 596/2000 [00:31<01:14, 18.78it/s]

Epoch 6:  30%|██▉       | 598/2000 [00:31<01:14, 18.77it/s]

Epoch 6:  30%|███       | 600/2000 [00:32<01:14, 18.79it/s]

Epoch 6:  30%|███       | 602/2000 [00:32<01:14, 18.79it/s]

Epoch 6:  30%|███       | 604/2000 [00:32<01:14, 18.79it/s]

Epoch 6:  30%|███       | 606/2000 [00:32<01:14, 18.80it/s]

Epoch 6:  30%|███       | 608/2000 [00:32<01:14, 18.79it/s]

Epoch 6:  30%|███       | 610/2000 [00:32<01:14, 18.78it/s]

Epoch 6:  31%|███       | 612/2000 [00:32<01:13, 18.78it/s]

Epoch 6:  31%|███       | 614/2000 [00:32<01:13, 18.79it/s]

Epoch 6:  31%|███       | 616/2000 [00:32<01:13, 18.80it/s]

Epoch 6:  31%|███       | 618/2000 [00:32<01:13, 18.80it/s]

Epoch 6:  31%|███       | 620/2000 [00:33<01:13, 18.80it/s]

Epoch 6:  31%|███       | 622/2000 [00:33<01:13, 18.79it/s]

Epoch 6:  31%|███       | 624/2000 [00:33<01:13, 18.80it/s]

Epoch 6:  31%|███▏      | 626/2000 [00:33<01:13, 18.80it/s]

Epoch 6:  31%|███▏      | 628/2000 [00:33<01:12, 18.80it/s]

Epoch 6:  32%|███▏      | 630/2000 [00:33<01:12, 18.79it/s]

Epoch 6:  32%|███▏      | 632/2000 [00:33<01:12, 18.76it/s]

Epoch 6:  32%|███▏      | 634/2000 [00:33<01:12, 18.77it/s]

Epoch 6:  32%|███▏      | 636/2000 [00:33<01:12, 18.77it/s]

Epoch 6:  32%|███▏      | 638/2000 [00:34<01:12, 18.77it/s]

Epoch 6:  32%|███▏      | 640/2000 [00:34<01:12, 18.76it/s]

Epoch 6:  32%|███▏      | 642/2000 [00:34<01:12, 18.78it/s]

Epoch 6:  32%|███▏      | 644/2000 [00:34<01:12, 18.77it/s]

Epoch 6:  32%|███▏      | 646/2000 [00:34<01:12, 18.77it/s]

Epoch 6:  32%|███▏      | 648/2000 [00:34<01:12, 18.77it/s]

Epoch 6:  32%|███▎      | 650/2000 [00:34<01:11, 18.77it/s]

Epoch 6:  33%|███▎      | 652/2000 [00:34<01:11, 18.77it/s]

Epoch 6:  33%|███▎      | 654/2000 [00:34<01:11, 18.78it/s]

Epoch 6:  33%|███▎      | 656/2000 [00:34<01:11, 18.79it/s]

Epoch 6:  33%|███▎      | 658/2000 [00:35<01:11, 18.79it/s]

Epoch 6:  33%|███▎      | 660/2000 [00:35<01:11, 18.78it/s]

Epoch 6:  33%|███▎      | 662/2000 [00:35<01:11, 18.79it/s]

Epoch 6:  33%|███▎      | 664/2000 [00:35<01:11, 18.79it/s]

Epoch 6:  33%|███▎      | 666/2000 [00:35<01:11, 18.78it/s]

Epoch 6:  33%|███▎      | 668/2000 [00:35<01:10, 18.79it/s]

Epoch 6:  34%|███▎      | 670/2000 [00:35<01:10, 18.79it/s]

Epoch 6:  34%|███▎      | 672/2000 [00:35<01:10, 18.78it/s]

Epoch 6:  34%|███▎      | 674/2000 [00:35<01:10, 18.79it/s]

Epoch 6:  34%|███▍      | 676/2000 [00:36<01:10, 18.79it/s]

Epoch 6:  34%|███▍      | 678/2000 [00:36<01:10, 18.80it/s]

Epoch 6:  34%|███▍      | 680/2000 [00:36<01:10, 18.79it/s]

Epoch 6:  34%|███▍      | 682/2000 [00:36<01:10, 18.78it/s]

Epoch 6:  34%|███▍      | 684/2000 [00:36<01:10, 18.77it/s]

Epoch 6:  34%|███▍      | 686/2000 [00:36<01:09, 18.78it/s]

Epoch 6:  34%|███▍      | 688/2000 [00:36<01:09, 18.80it/s]

Epoch 6:  34%|███▍      | 690/2000 [00:36<01:09, 18.80it/s]

Epoch 6:  35%|███▍      | 692/2000 [00:36<01:09, 18.80it/s]

Epoch 6:  35%|███▍      | 694/2000 [00:37<01:09, 18.79it/s]

Epoch 6:  35%|███▍      | 696/2000 [00:37<01:09, 18.79it/s]

Epoch 6:  35%|███▍      | 698/2000 [00:37<01:09, 18.79it/s]

Epoch 6:  35%|███▌      | 700/2000 [00:37<01:09, 18.80it/s]

Epoch 6:  35%|███▌      | 702/2000 [00:37<01:09, 18.79it/s]

Epoch 6:  35%|███▌      | 704/2000 [00:37<01:08, 18.79it/s]

Epoch 6:  35%|███▌      | 706/2000 [00:37<01:08, 18.79it/s]

Epoch 6:  35%|███▌      | 708/2000 [00:37<01:08, 18.79it/s]

Epoch 6:  36%|███▌      | 710/2000 [00:37<01:08, 18.79it/s]

Epoch 6:  36%|███▌      | 712/2000 [00:37<01:08, 18.78it/s]

Epoch 6:  36%|███▌      | 714/2000 [00:38<01:08, 18.79it/s]

Epoch 6:  36%|███▌      | 716/2000 [00:38<01:08, 18.78it/s]

Epoch 6:  36%|███▌      | 718/2000 [00:38<01:08, 18.79it/s]

Epoch 6:  36%|███▌      | 720/2000 [00:38<01:08, 18.78it/s]

Epoch 6:  36%|███▌      | 722/2000 [00:38<01:08, 18.78it/s]

Epoch 6:  36%|███▌      | 724/2000 [00:38<01:07, 18.78it/s]

Epoch 6:  36%|███▋      | 726/2000 [00:38<01:07, 18.80it/s]

Epoch 6:  36%|███▋      | 728/2000 [00:38<01:07, 18.81it/s]

Epoch 6:  36%|███▋      | 730/2000 [00:38<01:07, 18.80it/s]

Epoch 6:  37%|███▋      | 732/2000 [00:39<01:07, 18.79it/s]

Epoch 6:  37%|███▋      | 734/2000 [00:39<01:07, 18.80it/s]

Epoch 6:  37%|███▋      | 736/2000 [00:39<01:07, 18.80it/s]

Epoch 6:  37%|███▋      | 738/2000 [00:39<01:07, 18.78it/s]

Epoch 6:  37%|███▋      | 740/2000 [00:39<01:07, 18.79it/s]

Epoch 6:  37%|███▋      | 742/2000 [00:39<01:06, 18.79it/s]

Epoch 6:  37%|███▋      | 744/2000 [00:39<01:06, 18.78it/s]

Epoch 6:  37%|███▋      | 746/2000 [00:39<01:06, 18.77it/s]

Epoch 6:  37%|███▋      | 748/2000 [00:39<01:06, 18.78it/s]

Epoch 6:  38%|███▊      | 750/2000 [00:39<01:06, 18.78it/s]

Epoch 6:  38%|███▊      | 752/2000 [00:40<01:06, 18.79it/s]

Epoch 6:  38%|███▊      | 754/2000 [00:40<01:06, 18.79it/s]

Epoch 6:  38%|███▊      | 756/2000 [00:40<01:06, 18.79it/s]

Epoch 6:  38%|███▊      | 758/2000 [00:40<01:06, 18.79it/s]

Epoch 6:  38%|███▊      | 760/2000 [00:40<01:05, 18.79it/s]

Epoch 6:  38%|███▊      | 762/2000 [00:40<01:05, 18.79it/s]

Epoch 6:  38%|███▊      | 764/2000 [00:40<01:05, 18.79it/s]

Epoch 6:  38%|███▊      | 766/2000 [00:40<01:05, 18.80it/s]

Epoch 6:  38%|███▊      | 768/2000 [00:40<01:05, 18.79it/s]

Epoch 6:  38%|███▊      | 770/2000 [00:41<01:05, 18.80it/s]

Epoch 6:  39%|███▊      | 772/2000 [00:41<01:05, 18.79it/s]

Epoch 6:  39%|███▊      | 774/2000 [00:41<01:05, 18.78it/s]

Epoch 6:  39%|███▉      | 776/2000 [00:41<01:05, 18.78it/s]

Epoch 6:  39%|███▉      | 778/2000 [00:41<01:05, 18.78it/s]

Epoch 6:  39%|███▉      | 780/2000 [00:41<01:04, 18.79it/s]

Epoch 6:  39%|███▉      | 782/2000 [00:41<01:04, 18.79it/s]

Epoch 6:  39%|███▉      | 784/2000 [00:41<01:04, 18.80it/s]

Epoch 6:  39%|███▉      | 786/2000 [00:41<01:04, 18.80it/s]

Epoch 6:  39%|███▉      | 788/2000 [00:42<01:04, 18.79it/s]

Epoch 6:  40%|███▉      | 790/2000 [00:42<01:04, 18.79it/s]

Epoch 6:  40%|███▉      | 792/2000 [00:42<01:04, 18.79it/s]

Epoch 6:  40%|███▉      | 794/2000 [00:42<01:04, 18.80it/s]

Epoch 6:  40%|███▉      | 796/2000 [00:42<01:04, 18.81it/s]

Epoch 6:  40%|███▉      | 798/2000 [00:42<01:03, 18.80it/s]

Epoch 6:  40%|████      | 800/2000 [00:42<01:03, 18.81it/s]

Epoch 6:  40%|████      | 802/2000 [00:42<01:03, 18.81it/s]

Epoch 6:  40%|████      | 804/2000 [00:42<01:03, 18.80it/s]

Epoch 6:  40%|████      | 806/2000 [00:42<01:03, 18.80it/s]

Epoch 6:  40%|████      | 808/2000 [00:43<01:03, 18.80it/s]

Epoch 6:  40%|████      | 810/2000 [00:43<01:03, 18.80it/s]

Epoch 6:  41%|████      | 812/2000 [00:43<01:03, 18.79it/s]

Epoch 6:  41%|████      | 814/2000 [00:43<01:03, 18.80it/s]

Epoch 6:  41%|████      | 816/2000 [00:43<01:02, 18.82it/s]

Epoch 6:  41%|████      | 818/2000 [00:43<01:02, 18.80it/s]

Epoch 6:  41%|████      | 820/2000 [00:43<01:02, 18.79it/s]

Epoch 6:  41%|████      | 822/2000 [00:43<01:02, 18.80it/s]

Epoch 6:  41%|████      | 824/2000 [00:43<01:02, 18.79it/s]

Epoch 6:  41%|████▏     | 826/2000 [00:44<01:02, 18.79it/s]

Epoch 6:  41%|████▏     | 828/2000 [00:44<01:02, 18.80it/s]

Epoch 6:  42%|████▏     | 830/2000 [00:44<01:02, 18.80it/s]

Epoch 6:  42%|████▏     | 832/2000 [00:44<01:02, 18.79it/s]

Epoch 6:  42%|████▏     | 834/2000 [00:44<01:02, 18.81it/s]

Epoch 6:  42%|████▏     | 836/2000 [00:44<01:01, 18.80it/s]

Epoch 6:  42%|████▏     | 838/2000 [00:44<01:01, 18.80it/s]

Epoch 6:  42%|████▏     | 840/2000 [00:44<01:01, 18.81it/s]

Epoch 6:  42%|████▏     | 842/2000 [00:44<01:01, 18.80it/s]

Epoch 6:  42%|████▏     | 844/2000 [00:44<01:01, 18.81it/s]

Epoch 6:  42%|████▏     | 846/2000 [00:45<01:01, 18.81it/s]

Epoch 6:  42%|████▏     | 848/2000 [00:45<01:01, 18.82it/s]

Epoch 6:  42%|████▎     | 850/2000 [00:45<01:01, 18.80it/s]

Epoch 6:  43%|████▎     | 852/2000 [00:45<01:01, 18.80it/s]

Epoch 6:  43%|████▎     | 854/2000 [00:45<01:00, 18.80it/s]

Epoch 6:  43%|████▎     | 856/2000 [00:45<01:00, 18.80it/s]

Epoch 6:  43%|████▎     | 858/2000 [00:45<01:00, 18.79it/s]

Epoch 6:  43%|████▎     | 860/2000 [00:45<01:00, 18.81it/s]

Epoch 6:  43%|████▎     | 862/2000 [00:45<01:00, 18.81it/s]

Epoch 6:  43%|████▎     | 864/2000 [00:46<01:00, 18.81it/s]

Epoch 6:  43%|████▎     | 866/2000 [00:46<01:00, 18.82it/s]

Epoch 6:  43%|████▎     | 868/2000 [00:46<01:00, 18.81it/s]

Epoch 6:  44%|████▎     | 870/2000 [00:46<01:00, 18.78it/s]

Epoch 6:  44%|████▎     | 872/2000 [00:46<01:00, 18.78it/s]

Epoch 6:  44%|████▎     | 874/2000 [00:46<00:59, 18.79it/s]

Epoch 6:  44%|████▍     | 876/2000 [00:46<00:59, 18.80it/s]

Epoch 6:  44%|████▍     | 878/2000 [00:46<00:59, 18.79it/s]

Epoch 6:  44%|████▍     | 880/2000 [00:46<00:59, 18.80it/s]

Epoch 6:  44%|████▍     | 882/2000 [00:47<00:59, 18.80it/s]

Epoch 6:  44%|████▍     | 884/2000 [00:47<00:59, 18.78it/s]

Epoch 6:  44%|████▍     | 886/2000 [00:47<00:59, 18.79it/s]

Epoch 6:  44%|████▍     | 888/2000 [00:47<00:59, 18.78it/s]

Epoch 6:  44%|████▍     | 890/2000 [00:47<00:59, 18.79it/s]

Epoch 6:  45%|████▍     | 892/2000 [00:47<00:58, 18.79it/s]

Epoch 6:  45%|████▍     | 894/2000 [00:47<00:58, 18.79it/s]

Epoch 6:  45%|████▍     | 896/2000 [00:47<00:58, 18.81it/s]

Epoch 6:  45%|████▍     | 898/2000 [00:47<00:58, 18.80it/s]

Epoch 6:  45%|████▌     | 900/2000 [00:47<00:58, 18.80it/s]

Epoch 6:  45%|████▌     | 902/2000 [00:48<00:58, 18.80it/s]

Epoch 6:  45%|████▌     | 904/2000 [00:48<00:58, 18.80it/s]

Epoch 6:  45%|████▌     | 906/2000 [00:48<00:58, 18.81it/s]

Epoch 6:  45%|████▌     | 908/2000 [00:48<00:58, 18.81it/s]

Epoch 6:  46%|████▌     | 910/2000 [00:48<00:57, 18.81it/s]

Epoch 6:  46%|████▌     | 912/2000 [00:48<00:57, 18.80it/s]

Epoch 6:  46%|████▌     | 914/2000 [00:48<00:57, 18.79it/s]

Epoch 6:  46%|████▌     | 916/2000 [00:48<00:57, 18.80it/s]

Epoch 6:  46%|████▌     | 918/2000 [00:48<00:57, 18.81it/s]

Epoch 6:  46%|████▌     | 920/2000 [00:49<00:57, 18.81it/s]

Epoch 6:  46%|████▌     | 922/2000 [00:49<00:57, 18.79it/s]

Epoch 6:  46%|████▌     | 924/2000 [00:49<00:57, 18.77it/s]

Epoch 6:  46%|████▋     | 926/2000 [00:49<00:57, 18.78it/s]

Epoch 6:  46%|████▋     | 928/2000 [00:49<00:57, 18.79it/s]

Epoch 6:  46%|████▋     | 930/2000 [00:49<00:56, 18.80it/s]

Epoch 6:  47%|████▋     | 932/2000 [00:49<00:56, 18.80it/s]

Epoch 6:  47%|████▋     | 934/2000 [00:49<00:56, 18.79it/s]

Epoch 6:  47%|████▋     | 936/2000 [00:49<00:56, 18.79it/s]

Epoch 6:  47%|████▋     | 938/2000 [00:49<00:56, 18.79it/s]

Epoch 6:  47%|████▋     | 940/2000 [00:50<00:56, 18.80it/s]

Epoch 6:  47%|████▋     | 942/2000 [00:50<00:56, 18.81it/s]

Epoch 6:  47%|████▋     | 944/2000 [00:50<00:56, 18.81it/s]

Epoch 6:  47%|████▋     | 946/2000 [00:50<00:56, 18.81it/s]

Epoch 6:  47%|████▋     | 948/2000 [00:50<00:55, 18.81it/s]

Epoch 6:  48%|████▊     | 950/2000 [00:50<00:55, 18.81it/s]

Epoch 6:  48%|████▊     | 952/2000 [00:50<00:55, 18.81it/s]

Epoch 6:  48%|████▊     | 954/2000 [00:50<00:55, 18.82it/s]

Epoch 6:  48%|████▊     | 956/2000 [00:50<00:55, 18.82it/s]

Epoch 6:  48%|████▊     | 958/2000 [00:51<00:55, 18.81it/s]

Epoch 6:  48%|████▊     | 960/2000 [00:51<00:55, 18.81it/s]

Epoch 6:  48%|████▊     | 962/2000 [00:51<00:55, 18.80it/s]

Epoch 6:  48%|████▊     | 964/2000 [00:51<00:55, 18.80it/s]

Epoch 6:  48%|████▊     | 966/2000 [00:51<00:54, 18.81it/s]

Epoch 6:  48%|████▊     | 968/2000 [00:51<00:54, 18.81it/s]

Epoch 6:  48%|████▊     | 970/2000 [00:51<00:54, 18.82it/s]

Epoch 6:  49%|████▊     | 972/2000 [00:51<00:54, 18.80it/s]

Epoch 6:  49%|████▊     | 974/2000 [00:51<00:54, 18.81it/s]

Epoch 6:  49%|████▉     | 976/2000 [00:52<00:54, 18.81it/s]

Epoch 6:  49%|████▉     | 978/2000 [00:52<00:54, 18.80it/s]

Epoch 6:  49%|████▉     | 980/2000 [00:52<00:54, 18.79it/s]

Epoch 6:  49%|████▉     | 982/2000 [00:52<00:54, 18.80it/s]

Epoch 6:  49%|████▉     | 984/2000 [00:52<00:54, 18.79it/s]

Epoch 6:  49%|████▉     | 986/2000 [00:52<00:53, 18.79it/s]

Epoch 6:  49%|████▉     | 988/2000 [00:52<00:53, 18.78it/s]

Epoch 6:  50%|████▉     | 990/2000 [00:52<00:53, 18.78it/s]

Epoch 6:  50%|████▉     | 992/2000 [00:52<00:53, 18.79it/s]

Epoch 6:  50%|████▉     | 994/2000 [00:52<00:53, 18.80it/s]

Epoch 6:  50%|████▉     | 996/2000 [00:53<00:53, 18.81it/s]

Epoch 6:  50%|████▉     | 998/2000 [00:53<00:53, 18.80it/s]

Epoch 6:  50%|█████     | 1000/2000 [00:53<00:53, 18.80it/s]

Epoch 6:  50%|█████     | 1002/2000 [00:53<00:53, 18.80it/s]

Epoch 6:  50%|█████     | 1004/2000 [00:53<00:52, 18.80it/s]

Epoch 6:  50%|█████     | 1006/2000 [00:53<00:52, 18.80it/s]

Epoch 6:  50%|█████     | 1008/2000 [00:53<00:52, 18.80it/s]

Epoch 6:  50%|█████     | 1010/2000 [00:53<00:52, 18.81it/s]

Epoch 6:  51%|█████     | 1012/2000 [00:53<00:52, 18.80it/s]

Epoch 6:  51%|█████     | 1014/2000 [00:54<00:52, 18.80it/s]

Epoch 6:  51%|█████     | 1016/2000 [00:54<00:52, 18.81it/s]

Epoch 6:  51%|█████     | 1018/2000 [00:54<00:52, 18.79it/s]

Epoch 6:  51%|█████     | 1020/2000 [00:54<00:52, 18.79it/s]

Epoch 6:  51%|█████     | 1022/2000 [00:54<00:52, 18.80it/s]

Epoch 6:  51%|█████     | 1024/2000 [00:54<00:51, 18.79it/s]

Epoch 6:  51%|█████▏    | 1026/2000 [00:54<00:51, 18.80it/s]

Epoch 6:  51%|█████▏    | 1028/2000 [00:54<00:51, 18.79it/s]

Epoch 6:  52%|█████▏    | 1030/2000 [00:54<00:51, 18.77it/s]

Epoch 6:  52%|█████▏    | 1032/2000 [00:54<00:51, 18.77it/s]

Epoch 6:  52%|█████▏    | 1034/2000 [00:55<00:51, 18.78it/s]

Epoch 6:  52%|█████▏    | 1036/2000 [00:55<00:51, 18.77it/s]

Epoch 6:  52%|█████▏    | 1038/2000 [00:55<00:51, 18.77it/s]

Epoch 6:  52%|█████▏    | 1040/2000 [00:55<00:51, 18.77it/s]

Epoch 6:  52%|█████▏    | 1042/2000 [00:55<00:50, 18.79it/s]

Epoch 6:  52%|█████▏    | 1044/2000 [00:55<00:50, 18.77it/s]

Epoch 6:  52%|█████▏    | 1046/2000 [00:55<00:50, 18.79it/s]

Epoch 6:  52%|█████▏    | 1048/2000 [00:55<00:50, 18.78it/s]

Epoch 6:  52%|█████▎    | 1050/2000 [00:55<00:50, 18.77it/s]

Epoch 6:  53%|█████▎    | 1052/2000 [00:56<00:50, 18.77it/s]

Epoch 6:  53%|█████▎    | 1054/2000 [00:56<00:50, 18.78it/s]

Epoch 6:  53%|█████▎    | 1056/2000 [00:56<00:50, 18.79it/s]

Epoch 6:  53%|█████▎    | 1058/2000 [00:56<00:50, 18.79it/s]

Epoch 6:  53%|█████▎    | 1060/2000 [00:56<00:50, 18.78it/s]

Epoch 6:  53%|█████▎    | 1062/2000 [00:56<00:49, 18.80it/s]

Epoch 6:  53%|█████▎    | 1064/2000 [00:56<00:49, 18.80it/s]

Epoch 6:  53%|█████▎    | 1066/2000 [00:56<00:49, 18.81it/s]

Epoch 6:  53%|█████▎    | 1068/2000 [00:56<00:49, 18.79it/s]

Epoch 6:  54%|█████▎    | 1070/2000 [00:57<00:49, 18.81it/s]

Epoch 6:  54%|█████▎    | 1072/2000 [00:57<00:49, 18.80it/s]

Epoch 6:  54%|█████▎    | 1074/2000 [00:57<00:49, 18.79it/s]

Epoch 6:  54%|█████▍    | 1076/2000 [00:57<00:49, 18.79it/s]

Epoch 6:  54%|█████▍    | 1078/2000 [00:57<00:49, 18.79it/s]

Epoch 6:  54%|█████▍    | 1080/2000 [00:57<00:48, 18.80it/s]

Epoch 6:  54%|█████▍    | 1082/2000 [00:57<00:48, 18.80it/s]

Epoch 6:  54%|█████▍    | 1084/2000 [00:57<00:48, 18.79it/s]

Epoch 6:  54%|█████▍    | 1086/2000 [00:57<00:48, 18.79it/s]

Epoch 6:  54%|█████▍    | 1088/2000 [00:57<00:48, 18.80it/s]

Epoch 6:  55%|█████▍    | 1090/2000 [00:58<00:48, 18.80it/s]

Epoch 6:  55%|█████▍    | 1092/2000 [00:58<00:48, 18.80it/s]

Epoch 6:  55%|█████▍    | 1094/2000 [00:58<00:48, 18.81it/s]

Epoch 6:  55%|█████▍    | 1096/2000 [00:58<00:48, 18.81it/s]

Epoch 6:  55%|█████▍    | 1098/2000 [00:58<00:47, 18.80it/s]

Epoch 6:  55%|█████▌    | 1100/2000 [00:58<00:47, 18.81it/s]

Epoch 6:  55%|█████▌    | 1102/2000 [00:58<00:47, 18.81it/s]

Epoch 6:  55%|█████▌    | 1104/2000 [00:58<00:47, 18.80it/s]

Epoch 6:  55%|█████▌    | 1106/2000 [00:58<00:47, 18.81it/s]

Epoch 6:  55%|█████▌    | 1108/2000 [00:59<00:47, 18.82it/s]

Epoch 6:  56%|█████▌    | 1110/2000 [00:59<00:47, 18.81it/s]

Epoch 6:  56%|█████▌    | 1112/2000 [00:59<00:47, 18.82it/s]

Epoch 6:  56%|█████▌    | 1114/2000 [00:59<00:47, 18.83it/s]

Epoch 6:  56%|█████▌    | 1116/2000 [00:59<00:46, 18.81it/s]

Epoch 6:  56%|█████▌    | 1118/2000 [00:59<00:46, 18.80it/s]

Epoch 6:  56%|█████▌    | 1120/2000 [00:59<00:46, 18.80it/s]

Epoch 6:  56%|█████▌    | 1122/2000 [00:59<00:46, 18.79it/s]

Epoch 6:  56%|█████▌    | 1124/2000 [00:59<00:46, 18.78it/s]

Epoch 6:  56%|█████▋    | 1126/2000 [00:59<00:46, 18.79it/s]

Epoch 6:  56%|█████▋    | 1128/2000 [01:00<00:46, 18.79it/s]

Epoch 6:  56%|█████▋    | 1130/2000 [01:00<00:46, 18.79it/s]

Epoch 6:  57%|█████▋    | 1132/2000 [01:00<00:46, 18.80it/s]

Epoch 6:  57%|█████▋    | 1134/2000 [01:00<00:46, 18.80it/s]

Epoch 6:  57%|█████▋    | 1136/2000 [01:00<00:45, 18.79it/s]

Epoch 6:  57%|█████▋    | 1138/2000 [01:00<00:45, 18.79it/s]

Epoch 6:  57%|█████▋    | 1140/2000 [01:00<00:45, 18.79it/s]

Epoch 6:  57%|█████▋    | 1142/2000 [01:00<00:45, 18.79it/s]

Epoch 6:  57%|█████▋    | 1144/2000 [01:00<00:45, 18.80it/s]

Epoch 6:  57%|█████▋    | 1146/2000 [01:01<00:45, 18.81it/s]

Epoch 6:  57%|█████▋    | 1148/2000 [01:01<00:45, 18.81it/s]

Epoch 6:  57%|█████▊    | 1150/2000 [01:01<00:45, 18.81it/s]

Epoch 6:  58%|█████▊    | 1152/2000 [01:01<00:45, 18.81it/s]

Epoch 6:  58%|█████▊    | 1154/2000 [01:01<00:44, 18.81it/s]

Epoch 6:  58%|█████▊    | 1156/2000 [01:01<00:44, 18.80it/s]

Epoch 6:  58%|█████▊    | 1158/2000 [01:01<00:44, 18.81it/s]

Epoch 6:  58%|█████▊    | 1160/2000 [01:01<00:44, 18.81it/s]

Epoch 6:  58%|█████▊    | 1162/2000 [01:01<00:44, 18.80it/s]

Epoch 6:  58%|█████▊    | 1164/2000 [01:02<00:44, 18.80it/s]

Epoch 6:  58%|█████▊    | 1166/2000 [01:02<00:44, 18.82it/s]

Epoch 6:  58%|█████▊    | 1168/2000 [01:02<00:44, 18.81it/s]

Epoch 6:  58%|█████▊    | 1170/2000 [01:02<00:44, 18.79it/s]

Epoch 6:  59%|█████▊    | 1172/2000 [01:02<00:44, 18.79it/s]

Epoch 6:  59%|█████▊    | 1174/2000 [01:02<00:43, 18.80it/s]

Epoch 6:  59%|█████▉    | 1176/2000 [01:02<00:43, 18.79it/s]

Epoch 6:  59%|█████▉    | 1178/2000 [01:02<00:43, 18.78it/s]

Epoch 6:  59%|█████▉    | 1180/2000 [01:02<00:43, 18.78it/s]

Epoch 6:  59%|█████▉    | 1182/2000 [01:02<00:43, 18.78it/s]

Epoch 6:  59%|█████▉    | 1184/2000 [01:03<00:43, 18.76it/s]

Epoch 6:  59%|█████▉    | 1186/2000 [01:03<00:44, 18.23it/s]

Epoch 6:  59%|█████▉    | 1188/2000 [01:03<00:44, 18.11it/s]

Epoch 6:  60%|█████▉    | 1190/2000 [01:03<00:44, 18.12it/s]

Epoch 6:  60%|█████▉    | 1192/2000 [01:03<00:44, 18.29it/s]

Epoch 6:  60%|█████▉    | 1194/2000 [01:03<00:43, 18.40it/s]

Epoch 6:  60%|█████▉    | 1196/2000 [01:03<00:43, 18.50it/s]

Epoch 6:  60%|█████▉    | 1198/2000 [01:03<00:43, 18.59it/s]

Epoch 6:  60%|██████    | 1200/2000 [01:03<00:42, 18.65it/s]

Epoch 6:  60%|██████    | 1202/2000 [01:04<00:42, 18.70it/s]

Epoch 6:  60%|██████    | 1204/2000 [01:04<00:42, 18.73it/s]

Epoch 6:  60%|██████    | 1206/2000 [01:04<00:42, 18.75it/s]

Epoch 6:  60%|██████    | 1208/2000 [01:04<00:42, 18.76it/s]

Epoch 6:  60%|██████    | 1210/2000 [01:04<00:42, 18.78it/s]

Epoch 6:  61%|██████    | 1212/2000 [01:04<00:41, 18.80it/s]

Epoch 6:  61%|██████    | 1214/2000 [01:04<00:41, 18.81it/s]

Epoch 6:  61%|██████    | 1216/2000 [01:04<00:41, 18.81it/s]

Epoch 6:  61%|██████    | 1218/2000 [01:04<00:41, 18.80it/s]

Epoch 6:  61%|██████    | 1220/2000 [01:05<00:41, 18.77it/s]

Epoch 6:  61%|██████    | 1222/2000 [01:05<00:41, 18.76it/s]

Epoch 6:  61%|██████    | 1224/2000 [01:05<00:41, 18.77it/s]

Epoch 6:  61%|██████▏   | 1226/2000 [01:05<00:41, 18.77it/s]

Epoch 6:  61%|██████▏   | 1228/2000 [01:05<00:41, 18.78it/s]

Epoch 6:  62%|██████▏   | 1230/2000 [01:05<00:40, 18.80it/s]

Epoch 6:  62%|██████▏   | 1232/2000 [01:05<00:40, 18.81it/s]

Epoch 6:  62%|██████▏   | 1234/2000 [01:05<00:40, 18.82it/s]

Epoch 6:  62%|██████▏   | 1236/2000 [01:05<00:40, 18.81it/s]

Epoch 6:  62%|██████▏   | 1238/2000 [01:05<00:40, 18.81it/s]

Epoch 6:  62%|██████▏   | 1240/2000 [01:06<00:40, 18.82it/s]

Epoch 6:  62%|██████▏   | 1242/2000 [01:06<00:40, 18.82it/s]

Epoch 6:  62%|██████▏   | 1244/2000 [01:06<00:40, 18.81it/s]

Epoch 6:  62%|██████▏   | 1246/2000 [01:06<00:40, 18.82it/s]

Epoch 6:  62%|██████▏   | 1248/2000 [01:06<00:39, 18.82it/s]

Epoch 6:  62%|██████▎   | 1250/2000 [01:06<00:39, 18.82it/s]

Epoch 6:  63%|██████▎   | 1252/2000 [01:06<00:39, 18.82it/s]

Epoch 6:  63%|██████▎   | 1254/2000 [01:06<00:39, 18.82it/s]

Epoch 6:  63%|██████▎   | 1256/2000 [01:06<00:39, 18.80it/s]

Epoch 6:  63%|██████▎   | 1258/2000 [01:07<00:39, 18.80it/s]

Epoch 6:  63%|██████▎   | 1260/2000 [01:07<00:39, 18.80it/s]

Epoch 6:  63%|██████▎   | 1262/2000 [01:07<00:39, 18.80it/s]

Epoch 6:  63%|██████▎   | 1264/2000 [01:07<00:39, 18.81it/s]

Epoch 6:  63%|██████▎   | 1266/2000 [01:07<00:39, 18.81it/s]

Epoch 6:  63%|██████▎   | 1268/2000 [01:07<00:38, 18.81it/s]

Epoch 6:  64%|██████▎   | 1270/2000 [01:07<00:38, 18.79it/s]

Epoch 6:  64%|██████▎   | 1272/2000 [01:07<00:38, 18.80it/s]

Epoch 6:  64%|██████▎   | 1274/2000 [01:07<00:38, 18.80it/s]

Epoch 6:  64%|██████▍   | 1276/2000 [01:07<00:38, 18.80it/s]

Epoch 6:  64%|██████▍   | 1278/2000 [01:08<00:38, 18.81it/s]

Epoch 6:  64%|██████▍   | 1280/2000 [01:08<00:38, 18.81it/s]

Epoch 6:  64%|██████▍   | 1282/2000 [01:08<00:38, 18.81it/s]

Epoch 6:  64%|██████▍   | 1284/2000 [01:08<00:38, 18.80it/s]

Epoch 6:  64%|██████▍   | 1286/2000 [01:08<00:37, 18.80it/s]

Epoch 6:  64%|██████▍   | 1288/2000 [01:08<00:37, 18.80it/s]

Epoch 6:  64%|██████▍   | 1290/2000 [01:08<00:37, 18.80it/s]

Epoch 6:  65%|██████▍   | 1292/2000 [01:08<00:37, 18.80it/s]

Epoch 6:  65%|██████▍   | 1294/2000 [01:08<00:37, 18.80it/s]

Epoch 6:  65%|██████▍   | 1296/2000 [01:09<00:37, 18.80it/s]

Epoch 6:  65%|██████▍   | 1298/2000 [01:09<00:37, 18.80it/s]

Epoch 6:  65%|██████▌   | 1300/2000 [01:09<00:37, 18.82it/s]

Epoch 6:  65%|██████▌   | 1302/2000 [01:09<00:37, 18.82it/s]

Epoch 6:  65%|██████▌   | 1304/2000 [01:09<00:37, 18.81it/s]

Epoch 6:  65%|██████▌   | 1306/2000 [01:09<00:36, 18.82it/s]

Epoch 6:  65%|██████▌   | 1308/2000 [01:09<00:36, 18.82it/s]

Epoch 6:  66%|██████▌   | 1310/2000 [01:09<00:36, 18.82it/s]

Epoch 6:  66%|██████▌   | 1312/2000 [01:09<00:36, 18.80it/s]

Epoch 6:  66%|██████▌   | 1314/2000 [01:10<00:36, 18.80it/s]

Epoch 6:  66%|██████▌   | 1316/2000 [01:10<00:36, 18.80it/s]

Epoch 6:  66%|██████▌   | 1318/2000 [01:10<00:36, 18.80it/s]

Epoch 6:  66%|██████▌   | 1320/2000 [01:10<00:36, 18.80it/s]

Epoch 6:  66%|██████▌   | 1322/2000 [01:10<00:36, 18.79it/s]

Epoch 6:  66%|██████▌   | 1324/2000 [01:10<00:35, 18.80it/s]

Epoch 6:  66%|██████▋   | 1326/2000 [01:10<00:35, 18.80it/s]

Epoch 6:  66%|██████▋   | 1328/2000 [01:10<00:35, 18.80it/s]

Epoch 6:  66%|██████▋   | 1330/2000 [01:10<00:35, 18.80it/s]

Epoch 6:  67%|██████▋   | 1332/2000 [01:10<00:35, 18.81it/s]

Epoch 6:  67%|██████▋   | 1334/2000 [01:11<00:35, 18.81it/s]

Epoch 6:  67%|██████▋   | 1336/2000 [01:11<00:35, 18.81it/s]

Epoch 6:  67%|██████▋   | 1338/2000 [01:11<00:35, 18.80it/s]

Epoch 6:  67%|██████▋   | 1340/2000 [01:11<00:35, 18.79it/s]

Epoch 6:  67%|██████▋   | 1342/2000 [01:11<00:35, 18.67it/s]

Epoch 6:  67%|██████▋   | 1344/2000 [01:11<00:35, 18.71it/s]

Epoch 6:  67%|██████▋   | 1346/2000 [01:11<00:34, 18.72it/s]

Epoch 6:  67%|██████▋   | 1348/2000 [01:11<00:34, 18.75it/s]

Epoch 6:  68%|██████▊   | 1350/2000 [01:11<00:34, 18.76it/s]

Epoch 6:  68%|██████▊   | 1352/2000 [01:12<00:34, 18.78it/s]

Epoch 6:  68%|██████▊   | 1354/2000 [01:12<00:34, 18.50it/s]

Epoch 6:  68%|██████▊   | 1356/2000 [01:12<00:34, 18.58it/s]

Epoch 6:  68%|██████▊   | 1358/2000 [01:12<00:34, 18.64it/s]

Epoch 6:  68%|██████▊   | 1360/2000 [01:12<00:34, 18.69it/s]

Epoch 6:  68%|██████▊   | 1362/2000 [01:12<00:34, 18.65it/s]

Epoch 6:  68%|██████▊   | 1364/2000 [01:12<00:34, 18.68it/s]

Epoch 6:  68%|██████▊   | 1366/2000 [01:12<00:33, 18.72it/s]

Epoch 6:  68%|██████▊   | 1368/2000 [01:12<00:33, 18.75it/s]

Epoch 6:  68%|██████▊   | 1370/2000 [01:13<00:33, 18.75it/s]

Epoch 6:  69%|██████▊   | 1372/2000 [01:13<00:33, 18.76it/s]

Epoch 6:  69%|██████▊   | 1374/2000 [01:13<00:33, 18.77it/s]

Epoch 6:  69%|██████▉   | 1376/2000 [01:13<00:33, 18.78it/s]

Epoch 6:  69%|██████▉   | 1378/2000 [01:13<00:33, 18.78it/s]

Epoch 6:  69%|██████▉   | 1380/2000 [01:13<00:33, 18.77it/s]

Epoch 6:  69%|██████▉   | 1382/2000 [01:13<00:32, 18.77it/s]

Epoch 6:  69%|██████▉   | 1384/2000 [01:13<00:32, 18.78it/s]

Epoch 6:  69%|██████▉   | 1386/2000 [01:13<00:32, 18.78it/s]

Epoch 6:  69%|██████▉   | 1388/2000 [01:13<00:32, 18.79it/s]

Epoch 6:  70%|██████▉   | 1390/2000 [01:14<00:32, 18.80it/s]

Epoch 6:  70%|██████▉   | 1392/2000 [01:14<00:32, 18.81it/s]

Epoch 6:  70%|██████▉   | 1394/2000 [01:14<00:32, 18.81it/s]

Epoch 6:  70%|██████▉   | 1396/2000 [01:14<00:32, 18.80it/s]

Epoch 6:  70%|██████▉   | 1398/2000 [01:14<00:32, 18.80it/s]

Epoch 6:  70%|███████   | 1400/2000 [01:14<00:31, 18.80it/s]

Epoch 6:  70%|███████   | 1402/2000 [01:14<00:31, 18.81it/s]

Epoch 6:  70%|███████   | 1404/2000 [01:14<00:31, 18.81it/s]

Epoch 6:  70%|███████   | 1406/2000 [01:14<00:31, 18.81it/s]

Epoch 6:  70%|███████   | 1408/2000 [01:15<00:31, 18.81it/s]

Epoch 6:  70%|███████   | 1410/2000 [01:15<00:31, 18.82it/s]

Epoch 6:  71%|███████   | 1412/2000 [01:15<00:31, 18.81it/s]

Epoch 6:  71%|███████   | 1414/2000 [01:15<00:31, 18.80it/s]

Epoch 6:  71%|███████   | 1416/2000 [01:15<00:31, 18.80it/s]

Epoch 6:  71%|███████   | 1418/2000 [01:15<00:30, 18.81it/s]

Epoch 6:  71%|███████   | 1420/2000 [01:15<00:30, 18.82it/s]

Epoch 6:  71%|███████   | 1422/2000 [01:15<00:30, 18.82it/s]

Epoch 6:  71%|███████   | 1424/2000 [01:15<00:30, 18.80it/s]

Epoch 6:  71%|███████▏  | 1426/2000 [01:15<00:30, 18.81it/s]

Epoch 6:  71%|███████▏  | 1428/2000 [01:16<00:30, 18.81it/s]

Epoch 6:  72%|███████▏  | 1430/2000 [01:16<00:30, 18.82it/s]

Epoch 6:  72%|███████▏  | 1432/2000 [01:16<00:30, 18.82it/s]

Epoch 6:  72%|███████▏  | 1434/2000 [01:16<00:30, 18.81it/s]

Epoch 6:  72%|███████▏  | 1436/2000 [01:16<00:29, 18.82it/s]

Epoch 6:  72%|███████▏  | 1438/2000 [01:16<00:29, 18.81it/s]

Epoch 6:  72%|███████▏  | 1440/2000 [01:16<00:29, 18.82it/s]

Epoch 6:  72%|███████▏  | 1442/2000 [01:16<00:29, 18.82it/s]

Epoch 6:  72%|███████▏  | 1444/2000 [01:16<00:29, 18.83it/s]

Epoch 6:  72%|███████▏  | 1446/2000 [01:17<00:29, 18.83it/s]

Epoch 6:  72%|███████▏  | 1448/2000 [01:17<00:29, 18.82it/s]

Epoch 6:  72%|███████▎  | 1450/2000 [01:17<00:29, 18.79it/s]

Epoch 6:  73%|███████▎  | 1452/2000 [01:17<00:29, 18.79it/s]

Epoch 6:  73%|███████▎  | 1454/2000 [01:17<00:29, 18.80it/s]

Epoch 6:  73%|███████▎  | 1456/2000 [01:17<00:28, 18.79it/s]

Epoch 6:  73%|███████▎  | 1458/2000 [01:17<00:28, 18.79it/s]

Epoch 6:  73%|███████▎  | 1460/2000 [01:17<00:28, 18.79it/s]

Epoch 6:  73%|███████▎  | 1462/2000 [01:17<00:28, 18.79it/s]

Epoch 6:  73%|███████▎  | 1464/2000 [01:18<00:28, 18.80it/s]

Epoch 6:  73%|███████▎  | 1466/2000 [01:18<00:28, 18.80it/s]

Epoch 6:  73%|███████▎  | 1468/2000 [01:18<00:28, 18.80it/s]

Epoch 6:  74%|███████▎  | 1470/2000 [01:18<00:28, 18.78it/s]

Epoch 6:  74%|███████▎  | 1472/2000 [01:18<00:28, 18.71it/s]

Epoch 6:  74%|███████▎  | 1474/2000 [01:18<00:28, 18.68it/s]

Epoch 6:  74%|███████▍  | 1476/2000 [01:18<00:28, 18.66it/s]

Epoch 6:  74%|███████▍  | 1478/2000 [01:18<00:28, 18.64it/s]

Epoch 6:  74%|███████▍  | 1480/2000 [01:18<00:27, 18.62it/s]

Epoch 6:  74%|███████▍  | 1482/2000 [01:18<00:27, 18.62it/s]

Epoch 6:  74%|███████▍  | 1484/2000 [01:19<00:27, 18.63it/s]

Epoch 6:  74%|███████▍  | 1486/2000 [01:19<00:27, 18.63it/s]

Epoch 6:  74%|███████▍  | 1488/2000 [01:19<00:27, 18.63it/s]

Epoch 6:  74%|███████▍  | 1490/2000 [01:19<00:27, 18.61it/s]

Epoch 6:  75%|███████▍  | 1492/2000 [01:19<00:27, 18.62it/s]

Epoch 6:  75%|███████▍  | 1494/2000 [01:19<00:27, 18.61it/s]

Epoch 6:  75%|███████▍  | 1496/2000 [01:19<00:27, 18.60it/s]

Epoch 6:  75%|███████▍  | 1498/2000 [01:19<00:26, 18.60it/s]

Epoch 6:  75%|███████▌  | 1500/2000 [01:19<00:26, 18.60it/s]

Epoch 6:  75%|███████▌  | 1502/2000 [01:20<00:26, 18.60it/s]

Epoch 6:  75%|███████▌  | 1504/2000 [01:20<00:26, 18.61it/s]

Epoch 6:  75%|███████▌  | 1506/2000 [01:20<00:26, 18.60it/s]

Epoch 6:  75%|███████▌  | 1508/2000 [01:20<00:26, 18.60it/s]

Epoch 6:  76%|███████▌  | 1510/2000 [01:20<00:26, 18.59it/s]

Epoch 6:  76%|███████▌  | 1512/2000 [01:20<00:26, 18.58it/s]

Epoch 6:  76%|███████▌  | 1514/2000 [01:20<00:26, 18.59it/s]

Epoch 6:  76%|███████▌  | 1516/2000 [01:20<00:26, 18.59it/s]

Epoch 6:  76%|███████▌  | 1518/2000 [01:20<00:25, 18.59it/s]

Epoch 6:  76%|███████▌  | 1520/2000 [01:21<00:25, 18.59it/s]

Epoch 6:  76%|███████▌  | 1522/2000 [01:21<00:25, 18.59it/s]

Epoch 6:  76%|███████▌  | 1524/2000 [01:21<00:25, 18.59it/s]

Epoch 6:  76%|███████▋  | 1526/2000 [01:21<00:25, 18.60it/s]

Epoch 6:  76%|███████▋  | 1528/2000 [01:21<00:25, 18.60it/s]

Epoch 6:  76%|███████▋  | 1530/2000 [01:21<00:25, 18.60it/s]

Epoch 6:  77%|███████▋  | 1532/2000 [01:21<00:25, 18.59it/s]

Epoch 6:  77%|███████▋  | 1534/2000 [01:21<00:25, 18.60it/s]

Epoch 6:  77%|███████▋  | 1536/2000 [01:21<00:24, 18.59it/s]

Epoch 6:  77%|███████▋  | 1538/2000 [01:21<00:24, 18.59it/s]

Epoch 6:  77%|███████▋  | 1540/2000 [01:22<00:24, 18.59it/s]

Epoch 6:  77%|███████▋  | 1542/2000 [01:22<00:24, 18.58it/s]

Epoch 6:  77%|███████▋  | 1544/2000 [01:22<00:24, 18.59it/s]

Epoch 6:  77%|███████▋  | 1546/2000 [01:22<00:24, 18.59it/s]

Epoch 6:  77%|███████▋  | 1548/2000 [01:22<00:24, 18.56it/s]

Epoch 6:  78%|███████▊  | 1550/2000 [01:22<00:24, 18.56it/s]

Epoch 6:  78%|███████▊  | 1552/2000 [01:22<00:24, 18.58it/s]

Epoch 6:  78%|███████▊  | 1554/2000 [01:22<00:24, 18.58it/s]

Epoch 6:  78%|███████▊  | 1556/2000 [01:22<00:23, 18.57it/s]

Epoch 6:  78%|███████▊  | 1558/2000 [01:23<00:23, 18.57it/s]

Epoch 6:  78%|███████▊  | 1560/2000 [01:23<00:23, 18.58it/s]

Epoch 6:  78%|███████▊  | 1562/2000 [01:23<00:23, 18.57it/s]

Epoch 6:  78%|███████▊  | 1564/2000 [01:23<00:23, 18.57it/s]

Epoch 6:  78%|███████▊  | 1566/2000 [01:23<00:23, 18.59it/s]

Epoch 6:  78%|███████▊  | 1568/2000 [01:23<00:23, 18.37it/s]

Epoch 6:  78%|███████▊  | 1570/2000 [01:23<00:24, 17.82it/s]

Epoch 6:  79%|███████▊  | 1572/2000 [01:23<00:23, 18.04it/s]

Epoch 6:  79%|███████▊  | 1574/2000 [01:23<00:23, 18.15it/s]

Epoch 6:  79%|███████▉  | 1576/2000 [01:24<00:23, 18.29it/s]

Epoch 6:  79%|███████▉  | 1578/2000 [01:24<00:22, 18.38it/s]

Epoch 6:  79%|███████▉  | 1580/2000 [01:24<00:23, 18.26it/s]

Epoch 6:  79%|███████▉  | 1582/2000 [01:24<00:23, 17.78it/s]

Epoch 6:  79%|███████▉  | 1584/2000 [01:24<00:23, 17.81it/s]

Epoch 6:  79%|███████▉  | 1586/2000 [01:24<00:23, 17.98it/s]

Epoch 6:  79%|███████▉  | 1588/2000 [01:24<00:22, 18.11it/s]

Epoch 6:  80%|███████▉  | 1590/2000 [01:24<00:22, 18.21it/s]

Epoch 6:  80%|███████▉  | 1592/2000 [01:24<00:22, 18.29it/s]

Epoch 6:  80%|███████▉  | 1594/2000 [01:25<00:22, 18.38it/s]

Epoch 6:  80%|███████▉  | 1596/2000 [01:25<00:21, 18.45it/s]

Epoch 6:  80%|███████▉  | 1598/2000 [01:25<00:21, 18.49it/s]

Epoch 6:  80%|████████  | 1600/2000 [01:25<00:21, 18.52it/s]

Epoch 6:  80%|████████  | 1602/2000 [01:25<00:21, 18.53it/s]

Epoch 6:  80%|████████  | 1604/2000 [01:25<00:21, 18.55it/s]

Epoch 6:  80%|████████  | 1606/2000 [01:25<00:21, 18.58it/s]

Epoch 6:  80%|████████  | 1608/2000 [01:25<00:21, 18.59it/s]

Epoch 6:  80%|████████  | 1610/2000 [01:25<00:20, 18.60it/s]

Epoch 6:  81%|████████  | 1612/2000 [01:25<00:20, 18.61it/s]

Epoch 6:  81%|████████  | 1614/2000 [01:26<00:20, 18.62it/s]

Epoch 6:  81%|████████  | 1616/2000 [01:26<00:20, 18.60it/s]

Epoch 6:  81%|████████  | 1618/2000 [01:26<00:20, 18.60it/s]

Epoch 6:  81%|████████  | 1620/2000 [01:26<00:20, 18.61it/s]

Epoch 6:  81%|████████  | 1622/2000 [01:26<00:20, 18.60it/s]

Epoch 6:  81%|████████  | 1624/2000 [01:26<00:20, 18.61it/s]

Epoch 6:  81%|████████▏ | 1626/2000 [01:26<00:20, 18.60it/s]

Epoch 6:  81%|████████▏ | 1628/2000 [01:26<00:19, 18.61it/s]

Epoch 6:  82%|████████▏ | 1630/2000 [01:26<00:19, 18.62it/s]

Epoch 6:  82%|████████▏ | 1632/2000 [01:27<00:19, 18.61it/s]

Epoch 6:  82%|████████▏ | 1634/2000 [01:27<00:19, 18.62it/s]

Epoch 6:  82%|████████▏ | 1636/2000 [01:27<00:19, 18.61it/s]

Epoch 6:  82%|████████▏ | 1638/2000 [01:27<00:19, 18.62it/s]

Epoch 6:  82%|████████▏ | 1640/2000 [01:27<00:19, 18.62it/s]

Epoch 6:  82%|████████▏ | 1642/2000 [01:27<00:19, 18.60it/s]

Epoch 6:  82%|████████▏ | 1644/2000 [01:27<00:19, 18.58it/s]

Epoch 6:  82%|████████▏ | 1646/2000 [01:27<00:19, 18.59it/s]

Epoch 6:  82%|████████▏ | 1648/2000 [01:27<00:18, 18.59it/s]

Epoch 6:  82%|████████▎ | 1650/2000 [01:28<00:18, 18.59it/s]

Epoch 6:  83%|████████▎ | 1652/2000 [01:28<00:18, 18.60it/s]

Epoch 6:  83%|████████▎ | 1654/2000 [01:28<00:18, 18.60it/s]

Epoch 6:  83%|████████▎ | 1656/2000 [01:28<00:18, 18.60it/s]

Epoch 6:  83%|████████▎ | 1658/2000 [01:28<00:18, 18.59it/s]

Epoch 6:  83%|████████▎ | 1660/2000 [01:28<00:18, 18.59it/s]

Epoch 6:  83%|████████▎ | 1662/2000 [01:28<00:18, 18.59it/s]

Epoch 6:  83%|████████▎ | 1664/2000 [01:28<00:18, 18.60it/s]

Epoch 6:  83%|████████▎ | 1666/2000 [01:28<00:17, 18.61it/s]

Epoch 6:  83%|████████▎ | 1668/2000 [01:29<00:17, 18.60it/s]

Epoch 6:  84%|████████▎ | 1670/2000 [01:29<00:17, 18.58it/s]

Epoch 6:  84%|████████▎ | 1672/2000 [01:29<00:17, 18.58it/s]

Epoch 6:  84%|████████▎ | 1674/2000 [01:29<00:17, 18.58it/s]

Epoch 6:  84%|████████▍ | 1676/2000 [01:29<00:17, 18.59it/s]

Epoch 6:  84%|████████▍ | 1678/2000 [01:29<00:17, 18.60it/s]

Epoch 6:  84%|████████▍ | 1680/2000 [01:29<00:17, 18.59it/s]

Epoch 6:  84%|████████▍ | 1682/2000 [01:29<00:17, 18.60it/s]

Epoch 6:  84%|████████▍ | 1684/2000 [01:29<00:16, 18.60it/s]

Epoch 6:  84%|████████▍ | 1686/2000 [01:29<00:16, 18.58it/s]

Epoch 6:  84%|████████▍ | 1688/2000 [01:30<00:16, 18.58it/s]

Epoch 6:  84%|████████▍ | 1690/2000 [01:30<00:16, 18.59it/s]

Epoch 6:  85%|████████▍ | 1692/2000 [01:30<00:16, 18.59it/s]

Epoch 6:  85%|████████▍ | 1694/2000 [01:30<00:16, 18.58it/s]

Epoch 6:  85%|████████▍ | 1696/2000 [01:30<00:16, 18.58it/s]

Epoch 6:  85%|████████▍ | 1698/2000 [01:30<00:16, 18.57it/s]

Epoch 6:  85%|████████▌ | 1700/2000 [01:30<00:16, 18.57it/s]

Epoch 6:  85%|████████▌ | 1702/2000 [01:30<00:16, 18.59it/s]

Epoch 6:  85%|████████▌ | 1704/2000 [01:30<00:15, 18.59it/s]

Epoch 6:  85%|████████▌ | 1706/2000 [01:31<00:15, 18.60it/s]

Epoch 6:  85%|████████▌ | 1708/2000 [01:31<00:15, 18.60it/s]

Epoch 6:  86%|████████▌ | 1710/2000 [01:31<00:15, 18.60it/s]

Epoch 6:  86%|████████▌ | 1712/2000 [01:31<00:15, 18.59it/s]

Epoch 6:  86%|████████▌ | 1714/2000 [01:31<00:15, 18.58it/s]

Epoch 6:  86%|████████▌ | 1716/2000 [01:31<00:15, 18.59it/s]

Epoch 6:  86%|████████▌ | 1718/2000 [01:31<00:15, 18.59it/s]

Epoch 6:  86%|████████▌ | 1720/2000 [01:31<00:15, 18.58it/s]

Epoch 6:  86%|████████▌ | 1722/2000 [01:31<00:14, 18.58it/s]

Epoch 6:  86%|████████▌ | 1724/2000 [01:32<00:14, 18.58it/s]

Epoch 6:  86%|████████▋ | 1726/2000 [01:32<00:14, 18.60it/s]

Epoch 6:  86%|████████▋ | 1728/2000 [01:32<00:14, 18.59it/s]

Epoch 6:  86%|████████▋ | 1730/2000 [01:32<00:14, 18.59it/s]

Epoch 6:  87%|████████▋ | 1732/2000 [01:32<00:14, 18.60it/s]

Epoch 6:  87%|████████▋ | 1734/2000 [01:32<00:14, 18.60it/s]

Epoch 6:  87%|████████▋ | 1736/2000 [01:32<00:14, 18.59it/s]

Epoch 6:  87%|████████▋ | 1738/2000 [01:32<00:14, 18.58it/s]

Epoch 6:  87%|████████▋ | 1740/2000 [01:32<00:13, 18.59it/s]

Epoch 6:  87%|████████▋ | 1742/2000 [01:32<00:13, 18.59it/s]

Epoch 6:  87%|████████▋ | 1744/2000 [01:33<00:13, 18.58it/s]

Epoch 6:  87%|████████▋ | 1746/2000 [01:33<00:13, 18.58it/s]

Epoch 6:  87%|████████▋ | 1748/2000 [01:33<00:13, 18.58it/s]

Epoch 6:  88%|████████▊ | 1750/2000 [01:33<00:13, 18.58it/s]

Epoch 6:  88%|████████▊ | 1752/2000 [01:33<00:13, 18.58it/s]

Epoch 6:  88%|████████▊ | 1754/2000 [01:33<00:13, 18.60it/s]

Epoch 6:  88%|████████▊ | 1756/2000 [01:33<00:13, 18.60it/s]

Epoch 6:  88%|████████▊ | 1758/2000 [01:33<00:13, 18.60it/s]

Epoch 6:  88%|████████▊ | 1760/2000 [01:33<00:12, 18.61it/s]

Epoch 6:  88%|████████▊ | 1762/2000 [01:34<00:12, 18.61it/s]

Epoch 6:  88%|████████▊ | 1764/2000 [01:34<00:12, 18.60it/s]

Epoch 6:  88%|████████▊ | 1766/2000 [01:34<00:12, 18.61it/s]

Epoch 6:  88%|████████▊ | 1768/2000 [01:34<00:12, 18.59it/s]

Epoch 6:  88%|████████▊ | 1770/2000 [01:34<00:12, 18.57it/s]

Epoch 6:  89%|████████▊ | 1772/2000 [01:34<00:12, 18.56it/s]

Epoch 6:  89%|████████▊ | 1774/2000 [01:34<00:12, 18.56it/s]

Epoch 6:  89%|████████▉ | 1776/2000 [01:34<00:12, 18.56it/s]

Epoch 6:  89%|████████▉ | 1778/2000 [01:34<00:11, 18.55it/s]

Epoch 6:  89%|████████▉ | 1780/2000 [01:35<00:11, 18.55it/s]

Epoch 6:  89%|████████▉ | 1782/2000 [01:35<00:11, 18.55it/s]

Epoch 6:  89%|████████▉ | 1784/2000 [01:35<00:11, 18.53it/s]

Epoch 6:  89%|████████▉ | 1786/2000 [01:35<00:11, 18.53it/s]

Epoch 6:  89%|████████▉ | 1788/2000 [01:35<00:11, 18.52it/s]

Epoch 6:  90%|████████▉ | 1790/2000 [01:35<00:11, 18.57it/s]

Epoch 6:  90%|████████▉ | 1792/2000 [01:35<00:11, 18.62it/s]

Epoch 6:  90%|████████▉ | 1794/2000 [01:35<00:11, 18.65it/s]

Epoch 6:  90%|████████▉ | 1796/2000 [01:35<00:10, 18.67it/s]

Epoch 6:  90%|████████▉ | 1798/2000 [01:36<00:10, 18.69it/s]

Epoch 6:  90%|█████████ | 1800/2000 [01:36<00:10, 18.71it/s]

Epoch 6:  90%|█████████ | 1802/2000 [01:36<00:10, 18.72it/s]

Epoch 6:  90%|█████████ | 1804/2000 [01:36<00:10, 18.74it/s]

Epoch 6:  90%|█████████ | 1806/2000 [01:36<00:10, 18.74it/s]

Epoch 6:  90%|█████████ | 1808/2000 [01:36<00:10, 18.75it/s]

Epoch 6:  90%|█████████ | 1810/2000 [01:36<00:10, 18.76it/s]

Epoch 6:  91%|█████████ | 1812/2000 [01:36<00:10, 18.76it/s]

Epoch 6:  91%|█████████ | 1814/2000 [01:36<00:09, 18.76it/s]

Epoch 6:  91%|█████████ | 1816/2000 [01:36<00:09, 18.75it/s]

Epoch 6:  91%|█████████ | 1818/2000 [01:37<00:09, 18.76it/s]

Epoch 6:  91%|█████████ | 1820/2000 [01:37<00:09, 18.74it/s]

Epoch 6:  91%|█████████ | 1822/2000 [01:37<00:09, 18.75it/s]

Epoch 6:  91%|█████████ | 1824/2000 [01:37<00:09, 18.75it/s]

Epoch 6:  91%|█████████▏| 1826/2000 [01:37<00:09, 18.77it/s]

Epoch 6:  91%|█████████▏| 1828/2000 [01:37<00:09, 18.76it/s]

Epoch 6:  92%|█████████▏| 1830/2000 [01:37<00:09, 18.78it/s]

Epoch 6:  92%|█████████▏| 1832/2000 [01:37<00:08, 18.77it/s]

Epoch 6:  92%|█████████▏| 1834/2000 [01:37<00:08, 18.77it/s]

Epoch 6:  92%|█████████▏| 1836/2000 [01:38<00:08, 18.76it/s]

Epoch 6:  92%|█████████▏| 1838/2000 [01:38<00:08, 18.77it/s]

Epoch 6:  92%|█████████▏| 1840/2000 [01:38<00:08, 18.77it/s]

Epoch 6:  92%|█████████▏| 1842/2000 [01:38<00:08, 18.76it/s]

Epoch 6:  92%|█████████▏| 1844/2000 [01:38<00:08, 18.76it/s]

Epoch 6:  92%|█████████▏| 1846/2000 [01:38<00:08, 18.77it/s]

Epoch 6:  92%|█████████▏| 1848/2000 [01:38<00:08, 18.76it/s]

Epoch 6:  92%|█████████▎| 1850/2000 [01:38<00:07, 18.75it/s]

Epoch 6:  93%|█████████▎| 1852/2000 [01:38<00:07, 18.77it/s]

Epoch 6:  93%|█████████▎| 1854/2000 [01:38<00:07, 18.71it/s]

Epoch 6:  93%|█████████▎| 1856/2000 [01:39<00:07, 18.71it/s]

Epoch 6:  93%|█████████▎| 1858/2000 [01:39<00:07, 18.72it/s]

Epoch 6:  93%|█████████▎| 1860/2000 [01:39<00:07, 18.73it/s]

Epoch 6:  93%|█████████▎| 1862/2000 [01:39<00:07, 18.73it/s]

Epoch 6:  93%|█████████▎| 1864/2000 [01:39<00:07, 18.75it/s]

Epoch 6:  93%|█████████▎| 1866/2000 [01:39<00:07, 18.76it/s]

Epoch 6:  93%|█████████▎| 1868/2000 [01:39<00:07, 18.75it/s]

Epoch 6:  94%|█████████▎| 1870/2000 [01:39<00:06, 18.76it/s]

Epoch 6:  94%|█████████▎| 1872/2000 [01:39<00:06, 18.76it/s]

Epoch 6:  94%|█████████▎| 1874/2000 [01:40<00:06, 18.75it/s]

Epoch 6:  94%|█████████▍| 1876/2000 [01:40<00:06, 18.74it/s]

Epoch 6:  94%|█████████▍| 1878/2000 [01:40<00:06, 18.76it/s]

Epoch 6:  94%|█████████▍| 1880/2000 [01:40<00:06, 18.75it/s]

Epoch 6:  94%|█████████▍| 1882/2000 [01:40<00:06, 18.76it/s]

Epoch 6:  94%|█████████▍| 1884/2000 [01:40<00:06, 18.78it/s]

Epoch 6:  94%|█████████▍| 1886/2000 [01:40<00:06, 18.78it/s]

Epoch 6:  94%|█████████▍| 1888/2000 [01:40<00:05, 18.78it/s]

Epoch 6:  94%|█████████▍| 1890/2000 [01:40<00:05, 18.77it/s]

Epoch 6:  95%|█████████▍| 1892/2000 [01:41<00:05, 18.78it/s]

Epoch 6:  95%|█████████▍| 1894/2000 [01:41<00:05, 18.78it/s]

Epoch 6:  95%|█████████▍| 1896/2000 [01:41<00:05, 18.76it/s]

Epoch 6:  95%|█████████▍| 1898/2000 [01:41<00:05, 18.76it/s]

Epoch 6:  95%|█████████▌| 1900/2000 [01:41<00:05, 18.77it/s]

Epoch 6:  95%|█████████▌| 1902/2000 [01:41<00:05, 18.76it/s]

Epoch 6:  95%|█████████▌| 1904/2000 [01:41<00:05, 18.77it/s]

Epoch 6:  95%|█████████▌| 1906/2000 [01:41<00:05, 18.76it/s]

Epoch 6:  95%|█████████▌| 1908/2000 [01:41<00:04, 18.76it/s]

Epoch 6:  96%|█████████▌| 1910/2000 [01:41<00:04, 18.77it/s]

Epoch 6:  96%|█████████▌| 1912/2000 [01:42<00:04, 18.77it/s]

Epoch 6:  96%|█████████▌| 1914/2000 [01:42<00:04, 18.78it/s]

Epoch 6:  96%|█████████▌| 1916/2000 [01:42<00:04, 18.77it/s]

Epoch 6:  96%|█████████▌| 1918/2000 [01:42<00:04, 18.77it/s]

Epoch 6:  96%|█████████▌| 1920/2000 [01:42<00:04, 18.78it/s]

Epoch 6:  96%|█████████▌| 1922/2000 [01:42<00:04, 18.77it/s]

Epoch 6:  96%|█████████▌| 1924/2000 [01:42<00:04, 18.76it/s]

Epoch 6:  96%|█████████▋| 1926/2000 [01:42<00:03, 18.77it/s]

Epoch 6:  96%|█████████▋| 1928/2000 [01:42<00:03, 18.76it/s]

Epoch 6:  96%|█████████▋| 1930/2000 [01:43<00:03, 18.74it/s]

Epoch 6:  97%|█████████▋| 1932/2000 [01:43<00:03, 18.74it/s]

Epoch 6:  97%|█████████▋| 1934/2000 [01:43<00:03, 18.74it/s]

Epoch 6:  97%|█████████▋| 1936/2000 [01:43<00:03, 18.74it/s]

Epoch 6:  97%|█████████▋| 1938/2000 [01:43<00:03, 18.76it/s]

Epoch 6:  97%|█████████▋| 1940/2000 [01:43<00:03, 18.75it/s]

Epoch 6:  97%|█████████▋| 1942/2000 [01:43<00:03, 18.76it/s]

Epoch 6:  97%|█████████▋| 1944/2000 [01:43<00:02, 18.77it/s]

Epoch 6:  97%|█████████▋| 1946/2000 [01:43<00:02, 18.76it/s]

Epoch 6:  97%|█████████▋| 1948/2000 [01:43<00:02, 18.76it/s]

Epoch 6:  98%|█████████▊| 1950/2000 [01:44<00:02, 18.74it/s]

Epoch 6:  98%|█████████▊| 1952/2000 [01:44<00:02, 18.76it/s]

Epoch 6:  98%|█████████▊| 1954/2000 [01:44<00:02, 18.78it/s]

Epoch 6:  98%|█████████▊| 1956/2000 [01:44<00:02, 18.78it/s]

Epoch 6:  98%|█████████▊| 1958/2000 [01:44<00:02, 18.79it/s]

Epoch 6:  98%|█████████▊| 1960/2000 [01:44<00:02, 18.78it/s]

Epoch 6:  98%|█████████▊| 1962/2000 [01:44<00:02, 18.78it/s]

Epoch 6:  98%|█████████▊| 1964/2000 [01:44<00:01, 18.77it/s]

Epoch 6:  98%|█████████▊| 1966/2000 [01:44<00:01, 18.76it/s]

Epoch 6:  98%|█████████▊| 1968/2000 [01:45<00:01, 18.77it/s]

Epoch 6:  98%|█████████▊| 1970/2000 [01:45<00:01, 18.74it/s]

Epoch 6:  99%|█████████▊| 1972/2000 [01:45<00:01, 18.73it/s]

Epoch 6:  99%|█████████▊| 1974/2000 [01:45<00:01, 18.72it/s]

Epoch 6:  99%|█████████▉| 1976/2000 [01:45<00:01, 18.71it/s]

Epoch 6:  99%|█████████▉| 1978/2000 [01:45<00:01, 18.71it/s]

Epoch 6:  99%|█████████▉| 1980/2000 [01:45<00:01, 18.70it/s]

Epoch 6:  99%|█████████▉| 1982/2000 [01:45<00:00, 18.70it/s]

Epoch 6:  99%|█████████▉| 1984/2000 [01:45<00:00, 18.70it/s]

Epoch 6:  99%|█████████▉| 1986/2000 [01:46<00:00, 18.71it/s]

Epoch 6:  99%|█████████▉| 1988/2000 [01:46<00:00, 18.69it/s]

Epoch 6: 100%|█████████▉| 1990/2000 [01:46<00:00, 18.70it/s]

Epoch 6: 100%|█████████▉| 1992/2000 [01:46<00:00, 18.70it/s]

Epoch 6: 100%|█████████▉| 1994/2000 [01:46<00:00, 18.72it/s]

Epoch 6: 100%|█████████▉| 1996/2000 [01:46<00:00, 18.71it/s]

Epoch 6: 100%|█████████▉| 1998/2000 [01:46<00:00, 18.72it/s]

Epoch 6: 100%|██████████| 2000/2000 [01:46<00:00, 18.70it/s]

Epoch 6: loss=0.2080, val_proxy=0.9309

Epoch 7:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 7:   0%|          | 2/2000 [00:00<01:48, 18.39it/s]

Epoch 7:   0%|          | 4/2000 [00:00<01:47, 18.52it/s]

Epoch 7:   0%|          | 6/2000 [00:00<01:47, 18.57it/s]

Epoch 7:   0%|          | 8/2000 [00:00<01:47, 18.59it/s]

Epoch 7:   0%|          | 10/2000 [00:00<01:47, 18.59it/s]

Epoch 7:   1%|          | 12/2000 [00:00<01:46, 18.60it/s]

Epoch 7:   1%|          | 14/2000 [00:00<01:46, 18.60it/s]

Epoch 7:   1%|          | 16/2000 [00:00<01:46, 18.61it/s]

Epoch 7:   1%|          | 18/2000 [00:00<01:46, 18.61it/s]

Epoch 7:   1%|          | 20/2000 [00:01<01:46, 18.62it/s]

Epoch 7:   1%|          | 22/2000 [00:01<01:46, 18.63it/s]

Epoch 7:   1%|          | 24/2000 [00:01<01:46, 18.64it/s]

Epoch 7:   1%|▏         | 26/2000 [00:01<01:45, 18.65it/s]

Epoch 7:   1%|▏         | 28/2000 [00:01<01:45, 18.66it/s]

Epoch 7:   2%|▏         | 30/2000 [00:01<01:45, 18.66it/s]

Epoch 7:   2%|▏         | 32/2000 [00:01<01:45, 18.65it/s]

Epoch 7:   2%|▏         | 34/2000 [00:01<01:45, 18.65it/s]

Epoch 7:   2%|▏         | 36/2000 [00:01<01:45, 18.66it/s]

Epoch 7:   2%|▏         | 38/2000 [00:02<01:45, 18.67it/s]

Epoch 7:   2%|▏         | 40/2000 [00:02<01:45, 18.66it/s]

Epoch 7:   2%|▏         | 42/2000 [00:02<01:44, 18.66it/s]

Epoch 7:   2%|▏         | 44/2000 [00:02<01:44, 18.67it/s]

Epoch 7:   2%|▏         | 46/2000 [00:02<01:44, 18.68it/s]

Epoch 7:   2%|▏         | 48/2000 [00:02<01:44, 18.67it/s]

Epoch 7:   2%|▎         | 50/2000 [00:02<01:44, 18.68it/s]

Epoch 7:   3%|▎         | 52/2000 [00:02<01:44, 18.69it/s]

Epoch 7:   3%|▎         | 54/2000 [00:02<01:44, 18.69it/s]

Epoch 7:   3%|▎         | 56/2000 [00:03<01:44, 18.69it/s]

Epoch 7:   3%|▎         | 58/2000 [00:03<01:43, 18.68it/s]

Epoch 7:   3%|▎         | 60/2000 [00:03<01:43, 18.68it/s]

Epoch 7:   3%|▎         | 62/2000 [00:03<01:43, 18.68it/s]

Epoch 7:   3%|▎         | 64/2000 [00:03<01:43, 18.68it/s]

Epoch 7:   3%|▎         | 66/2000 [00:03<01:43, 18.67it/s]

Epoch 7:   3%|▎         | 68/2000 [00:03<01:43, 18.67it/s]

Epoch 7:   4%|▎         | 70/2000 [00:03<01:43, 18.67it/s]

Epoch 7:   4%|▎         | 72/2000 [00:03<01:43, 18.67it/s]

Epoch 7:   4%|▎         | 74/2000 [00:03<01:43, 18.67it/s]

Epoch 7:   4%|▍         | 76/2000 [00:04<01:43, 18.66it/s]

Epoch 7:   4%|▍         | 78/2000 [00:04<01:43, 18.64it/s]

Epoch 7:   4%|▍         | 80/2000 [00:04<01:43, 18.63it/s]

Epoch 7:   4%|▍         | 82/2000 [00:04<01:42, 18.63it/s]

Epoch 7:   4%|▍         | 84/2000 [00:04<01:42, 18.65it/s]

Epoch 7:   4%|▍         | 86/2000 [00:04<01:42, 18.65it/s]

Epoch 7:   4%|▍         | 88/2000 [00:04<01:42, 18.64it/s]

Epoch 7:   4%|▍         | 90/2000 [00:04<01:42, 18.64it/s]

Epoch 7:   5%|▍         | 92/2000 [00:04<01:42, 18.64it/s]

Epoch 7:   5%|▍         | 94/2000 [00:05<01:42, 18.63it/s]

Epoch 7:   5%|▍         | 96/2000 [00:05<01:42, 18.62it/s]

Epoch 7:   5%|▍         | 98/2000 [00:05<01:42, 18.63it/s]

Epoch 7:   5%|▌         | 100/2000 [00:05<01:41, 18.64it/s]

Epoch 7:   5%|▌         | 102/2000 [00:05<01:41, 18.64it/s]

Epoch 7:   5%|▌         | 104/2000 [00:05<01:41, 18.63it/s]

Epoch 7:   5%|▌         | 106/2000 [00:05<01:41, 18.63it/s]

Epoch 7:   5%|▌         | 108/2000 [00:05<01:41, 18.64it/s]

Epoch 7:   6%|▌         | 110/2000 [00:05<01:41, 18.64it/s]

Epoch 7:   6%|▌         | 112/2000 [00:06<01:41, 18.64it/s]

Epoch 7:   6%|▌         | 114/2000 [00:06<01:41, 18.64it/s]

Epoch 7:   6%|▌         | 116/2000 [00:06<01:41, 18.63it/s]

Epoch 7:   6%|▌         | 118/2000 [00:06<01:41, 18.63it/s]

Epoch 7:   6%|▌         | 120/2000 [00:06<01:40, 18.65it/s]

Epoch 7:   6%|▌         | 122/2000 [00:06<01:40, 18.64it/s]

Epoch 7:   6%|▌         | 124/2000 [00:06<01:40, 18.65it/s]

Epoch 7:   6%|▋         | 126/2000 [00:06<01:40, 18.63it/s]

Epoch 7:   6%|▋         | 128/2000 [00:06<01:40, 18.63it/s]

Epoch 7:   6%|▋         | 130/2000 [00:06<01:40, 18.62it/s]

Epoch 7:   7%|▋         | 132/2000 [00:07<01:40, 18.63it/s]

Epoch 7:   7%|▋         | 134/2000 [00:07<01:40, 18.64it/s]

Epoch 7:   7%|▋         | 136/2000 [00:07<01:39, 18.65it/s]

Epoch 7:   7%|▋         | 138/2000 [00:07<01:39, 18.64it/s]

Epoch 7:   7%|▋         | 140/2000 [00:07<01:39, 18.64it/s]

Epoch 7:   7%|▋         | 142/2000 [00:07<01:39, 18.63it/s]

Epoch 7:   7%|▋         | 144/2000 [00:07<01:39, 18.63it/s]

Epoch 7:   7%|▋         | 146/2000 [00:07<01:39, 18.64it/s]

Epoch 7:   7%|▋         | 148/2000 [00:07<01:39, 18.64it/s]

Epoch 7:   8%|▊         | 150/2000 [00:08<01:39, 18.63it/s]

Epoch 7:   8%|▊         | 152/2000 [00:08<01:39, 18.63it/s]

Epoch 7:   8%|▊         | 154/2000 [00:08<01:39, 18.64it/s]

Epoch 7:   8%|▊         | 156/2000 [00:08<01:38, 18.64it/s]

Epoch 7:   8%|▊         | 158/2000 [00:08<01:38, 18.64it/s]

Epoch 7:   8%|▊         | 160/2000 [00:08<01:38, 18.64it/s]

Epoch 7:   8%|▊         | 162/2000 [00:08<01:38, 18.64it/s]

Epoch 7:   8%|▊         | 164/2000 [00:08<01:38, 18.65it/s]

Epoch 7:   8%|▊         | 166/2000 [00:08<01:38, 18.64it/s]

Epoch 7:   8%|▊         | 168/2000 [00:09<01:38, 18.65it/s]

Epoch 7:   8%|▊         | 170/2000 [00:09<01:38, 18.66it/s]

Epoch 7:   9%|▊         | 172/2000 [00:09<01:38, 18.64it/s]

Epoch 7:   9%|▊         | 174/2000 [00:09<01:37, 18.64it/s]

Epoch 7:   9%|▉         | 176/2000 [00:09<01:37, 18.64it/s]

Epoch 7:   9%|▉         | 178/2000 [00:09<01:37, 18.64it/s]

Epoch 7:   9%|▉         | 180/2000 [00:09<01:37, 18.64it/s]

Epoch 7:   9%|▉         | 182/2000 [00:09<01:37, 18.65it/s]

Epoch 7:   9%|▉         | 184/2000 [00:09<01:37, 18.64it/s]

Epoch 7:   9%|▉         | 186/2000 [00:09<01:37, 18.64it/s]

Epoch 7:   9%|▉         | 188/2000 [00:10<01:37, 18.65it/s]

Epoch 7:  10%|▉         | 190/2000 [00:10<01:37, 18.65it/s]

Epoch 7:  10%|▉         | 192/2000 [00:10<01:36, 18.65it/s]

Epoch 7:  10%|▉         | 194/2000 [00:10<01:36, 18.65it/s]

Epoch 7:  10%|▉         | 196/2000 [00:10<01:36, 18.64it/s]

Epoch 7:  10%|▉         | 198/2000 [00:10<01:36, 18.65it/s]

Epoch 7:  10%|█         | 200/2000 [00:10<01:36, 18.64it/s]

Epoch 7:  10%|█         | 202/2000 [00:10<01:36, 18.64it/s]

Epoch 7:  10%|█         | 204/2000 [00:10<01:36, 18.63it/s]

Epoch 7:  10%|█         | 206/2000 [00:11<01:36, 18.63it/s]

Epoch 7:  10%|█         | 208/2000 [00:11<01:36, 18.62it/s]

Epoch 7:  10%|█         | 210/2000 [00:11<01:36, 18.62it/s]

Epoch 7:  11%|█         | 212/2000 [00:11<01:35, 18.63it/s]

Epoch 7:  11%|█         | 214/2000 [00:11<01:35, 18.62it/s]

Epoch 7:  11%|█         | 216/2000 [00:11<01:35, 18.62it/s]

Epoch 7:  11%|█         | 218/2000 [00:11<01:35, 18.63it/s]

Epoch 7:  11%|█         | 220/2000 [00:11<01:35, 18.62it/s]

Epoch 7:  11%|█         | 222/2000 [00:11<01:35, 18.63it/s]

Epoch 7:  11%|█         | 224/2000 [00:12<01:35, 18.62it/s]

Epoch 7:  11%|█▏        | 226/2000 [00:12<01:35, 18.63it/s]

Epoch 7:  11%|█▏        | 228/2000 [00:12<01:35, 18.64it/s]

Epoch 7:  12%|█▏        | 230/2000 [00:12<01:34, 18.63it/s]

Epoch 7:  12%|█▏        | 232/2000 [00:12<01:34, 18.62it/s]

Epoch 7:  12%|█▏        | 234/2000 [00:12<01:34, 18.62it/s]

Epoch 7:  12%|█▏        | 236/2000 [00:12<01:34, 18.64it/s]

Epoch 7:  12%|█▏        | 238/2000 [00:12<01:34, 18.65it/s]

Epoch 7:  12%|█▏        | 240/2000 [00:12<01:34, 18.65it/s]

Epoch 7:  12%|█▏        | 242/2000 [00:12<01:34, 18.65it/s]

Epoch 7:  12%|█▏        | 244/2000 [00:13<01:34, 18.65it/s]

Epoch 7:  12%|█▏        | 246/2000 [00:13<01:34, 18.64it/s]

Epoch 7:  12%|█▏        | 248/2000 [00:13<01:34, 18.64it/s]

Epoch 7:  12%|█▎        | 250/2000 [00:13<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 252/2000 [00:13<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 254/2000 [00:13<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 256/2000 [00:13<01:33, 18.64it/s]

Epoch 7:  13%|█▎        | 258/2000 [00:13<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 260/2000 [00:13<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 262/2000 [00:14<01:33, 18.64it/s]

Epoch 7:  13%|█▎        | 264/2000 [00:14<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 266/2000 [00:14<01:33, 18.63it/s]

Epoch 7:  13%|█▎        | 268/2000 [00:14<01:32, 18.63it/s]

Epoch 7:  14%|█▎        | 270/2000 [00:14<01:32, 18.62it/s]

Epoch 7:  14%|█▎        | 272/2000 [00:14<01:32, 18.63it/s]

Epoch 7:  14%|█▎        | 274/2000 [00:14<01:32, 18.63it/s]

Epoch 7:  14%|█▍        | 276/2000 [00:14<01:32, 18.63it/s]

Epoch 7:  14%|█▍        | 278/2000 [00:14<01:32, 18.61it/s]

Epoch 7:  14%|█▍        | 280/2000 [00:15<01:32, 18.62it/s]

Epoch 7:  14%|█▍        | 282/2000 [00:15<01:32, 18.63it/s]

Epoch 7:  14%|█▍        | 284/2000 [00:15<01:32, 18.64it/s]

Epoch 7:  14%|█▍        | 286/2000 [00:15<01:31, 18.64it/s]

Epoch 7:  14%|█▍        | 288/2000 [00:15<01:31, 18.63it/s]

Epoch 7:  14%|█▍        | 290/2000 [00:15<01:31, 18.63it/s]

Epoch 7:  15%|█▍        | 292/2000 [00:15<01:31, 18.63it/s]

Epoch 7:  15%|█▍        | 294/2000 [00:15<01:31, 18.64it/s]

Epoch 7:  15%|█▍        | 296/2000 [00:15<01:31, 18.64it/s]

Epoch 7:  15%|█▍        | 298/2000 [00:15<01:31, 18.63it/s]

Epoch 7:  15%|█▌        | 300/2000 [00:16<01:31, 18.64it/s]

Epoch 7:  15%|█▌        | 302/2000 [00:16<01:31, 18.63it/s]

Epoch 7:  15%|█▌        | 304/2000 [00:16<01:30, 18.64it/s]

Epoch 7:  15%|█▌        | 306/2000 [00:16<01:30, 18.64it/s]

Epoch 7:  15%|█▌        | 308/2000 [00:16<01:31, 18.59it/s]

Epoch 7:  16%|█▌        | 310/2000 [00:16<01:30, 18.59it/s]

Epoch 7:  16%|█▌        | 312/2000 [00:16<01:30, 18.60it/s]

Epoch 7:  16%|█▌        | 314/2000 [00:16<01:30, 18.61it/s]

Epoch 7:  16%|█▌        | 316/2000 [00:16<01:30, 18.62it/s]

Epoch 7:  16%|█▌        | 318/2000 [00:17<01:30, 18.62it/s]

Epoch 7:  16%|█▌        | 320/2000 [00:17<01:30, 18.61it/s]

Epoch 7:  16%|█▌        | 322/2000 [00:17<01:30, 18.62it/s]

Epoch 7:  16%|█▌        | 324/2000 [00:17<01:30, 18.61it/s]

Epoch 7:  16%|█▋        | 326/2000 [00:17<01:29, 18.63it/s]

Epoch 7:  16%|█▋        | 328/2000 [00:17<01:29, 18.63it/s]

Epoch 7:  16%|█▋        | 330/2000 [00:17<01:29, 18.63it/s]

Epoch 7:  17%|█▋        | 332/2000 [00:17<01:29, 18.63it/s]

Epoch 7:  17%|█▋        | 334/2000 [00:17<01:29, 18.62it/s]

Epoch 7:  17%|█▋        | 336/2000 [00:18<01:29, 18.62it/s]

Epoch 7:  17%|█▋        | 338/2000 [00:18<01:29, 18.63it/s]

Epoch 7:  17%|█▋        | 340/2000 [00:18<01:29, 18.63it/s]

Epoch 7:  17%|█▋        | 342/2000 [00:18<01:28, 18.63it/s]

Epoch 7:  17%|█▋        | 344/2000 [00:18<01:28, 18.63it/s]

Epoch 7:  17%|█▋        | 346/2000 [00:18<01:28, 18.63it/s]

Epoch 7:  17%|█▋        | 348/2000 [00:18<01:28, 18.65it/s]

Epoch 7:  18%|█▊        | 350/2000 [00:18<01:28, 18.64it/s]

Epoch 7:  18%|█▊        | 352/2000 [00:18<01:28, 18.65it/s]

Epoch 7:  18%|█▊        | 354/2000 [00:18<01:28, 18.63it/s]

Epoch 7:  18%|█▊        | 356/2000 [00:19<01:28, 18.63it/s]

Epoch 7:  18%|█▊        | 358/2000 [00:19<01:28, 18.62it/s]

Epoch 7:  18%|█▊        | 360/2000 [00:19<01:28, 18.63it/s]

Epoch 7:  18%|█▊        | 362/2000 [00:19<01:28, 18.61it/s]

Epoch 7:  18%|█▊        | 364/2000 [00:19<01:27, 18.61it/s]

Epoch 7:  18%|█▊        | 366/2000 [00:19<01:27, 18.60it/s]

Epoch 7:  18%|█▊        | 368/2000 [00:19<01:27, 18.60it/s]

Epoch 7:  18%|█▊        | 370/2000 [00:19<01:27, 18.61it/s]

Epoch 7:  19%|█▊        | 372/2000 [00:19<01:27, 18.61it/s]

Epoch 7:  19%|█▊        | 374/2000 [00:20<01:27, 18.60it/s]

Epoch 7:  19%|█▉        | 376/2000 [00:20<01:27, 18.59it/s]

Epoch 7:  19%|█▉        | 378/2000 [00:20<01:27, 18.61it/s]

Epoch 7:  19%|█▉        | 380/2000 [00:20<01:27, 18.61it/s]

Epoch 7:  19%|█▉        | 382/2000 [00:20<01:26, 18.62it/s]

Epoch 7:  19%|█▉        | 384/2000 [00:20<01:26, 18.62it/s]

Epoch 7:  19%|█▉        | 386/2000 [00:20<01:26, 18.62it/s]

Epoch 7:  19%|█▉        | 388/2000 [00:20<01:26, 18.62it/s]

Epoch 7:  20%|█▉        | 390/2000 [00:20<01:26, 18.63it/s]

Epoch 7:  20%|█▉        | 392/2000 [00:21<01:26, 18.62it/s]

Epoch 7:  20%|█▉        | 394/2000 [00:21<01:26, 18.62it/s]

Epoch 7:  20%|█▉        | 396/2000 [00:21<01:26, 18.62it/s]

Epoch 7:  20%|█▉        | 398/2000 [00:21<01:26, 18.61it/s]

Epoch 7:  20%|██        | 400/2000 [00:21<01:25, 18.61it/s]

Epoch 7:  20%|██        | 402/2000 [00:21<01:25, 18.62it/s]

Epoch 7:  20%|██        | 404/2000 [00:21<01:25, 18.63it/s]

Epoch 7:  20%|██        | 406/2000 [00:21<01:25, 18.63it/s]

Epoch 7:  20%|██        | 408/2000 [00:21<01:25, 18.63it/s]

Epoch 7:  20%|██        | 410/2000 [00:22<01:25, 18.63it/s]

Epoch 7:  21%|██        | 412/2000 [00:22<01:25, 18.63it/s]

Epoch 7:  21%|██        | 414/2000 [00:22<01:25, 18.62it/s]

Epoch 7:  21%|██        | 416/2000 [00:22<01:25, 18.62it/s]

Epoch 7:  21%|██        | 418/2000 [00:22<01:25, 18.61it/s]

Epoch 7:  21%|██        | 420/2000 [00:22<01:24, 18.61it/s]

Epoch 7:  21%|██        | 422/2000 [00:22<01:24, 18.61it/s]

Epoch 7:  21%|██        | 424/2000 [00:22<01:25, 18.44it/s]

Epoch 7:  21%|██▏       | 426/2000 [00:22<01:27, 18.01it/s]

Epoch 7:  21%|██▏       | 428/2000 [00:22<01:27, 17.93it/s]

Epoch 7:  22%|██▏       | 430/2000 [00:23<01:27, 17.94it/s]

Epoch 7:  22%|██▏       | 432/2000 [00:23<01:26, 18.10it/s]

Epoch 7:  22%|██▏       | 434/2000 [00:23<01:26, 18.20it/s]

Epoch 7:  22%|██▏       | 436/2000 [00:23<01:25, 18.31it/s]

Epoch 7:  22%|██▏       | 438/2000 [00:23<01:24, 18.40it/s]

Epoch 7:  22%|██▏       | 440/2000 [00:23<01:24, 18.46it/s]

Epoch 7:  22%|██▏       | 442/2000 [00:23<01:24, 18.52it/s]

Epoch 7:  22%|██▏       | 444/2000 [00:23<01:23, 18.55it/s]

Epoch 7:  22%|██▏       | 446/2000 [00:23<01:23, 18.58it/s]

Epoch 7:  22%|██▏       | 448/2000 [00:24<01:23, 18.60it/s]

Epoch 7:  22%|██▎       | 450/2000 [00:24<01:23, 18.62it/s]

Epoch 7:  23%|██▎       | 452/2000 [00:24<01:23, 18.63it/s]

Epoch 7:  23%|██▎       | 454/2000 [00:24<01:22, 18.64it/s]

Epoch 7:  23%|██▎       | 456/2000 [00:24<01:22, 18.64it/s]

Epoch 7:  23%|██▎       | 458/2000 [00:24<01:22, 18.64it/s]

Epoch 7:  23%|██▎       | 460/2000 [00:24<01:22, 18.65it/s]

Epoch 7:  23%|██▎       | 462/2000 [00:24<01:23, 18.45it/s]

Epoch 7:  23%|██▎       | 464/2000 [00:24<01:23, 18.50it/s]

Epoch 7:  23%|██▎       | 466/2000 [00:25<01:22, 18.53it/s]

Epoch 7:  23%|██▎       | 468/2000 [00:25<01:22, 18.57it/s]

Epoch 7:  24%|██▎       | 470/2000 [00:25<01:22, 18.60it/s]

Epoch 7:  24%|██▎       | 472/2000 [00:25<01:22, 18.61it/s]

Epoch 7:  24%|██▎       | 474/2000 [00:25<01:21, 18.61it/s]

Epoch 7:  24%|██▍       | 476/2000 [00:25<01:21, 18.61it/s]

Epoch 7:  24%|██▍       | 478/2000 [00:25<01:21, 18.60it/s]

Epoch 7:  24%|██▍       | 480/2000 [00:25<01:21, 18.59it/s]

Epoch 7:  24%|██▍       | 482/2000 [00:25<01:21, 18.59it/s]

Epoch 7:  24%|██▍       | 484/2000 [00:26<01:21, 18.59it/s]

Epoch 7:  24%|██▍       | 486/2000 [00:26<01:21, 18.59it/s]

Epoch 7:  24%|██▍       | 488/2000 [00:26<01:21, 18.58it/s]

Epoch 7:  24%|██▍       | 490/2000 [00:26<01:21, 18.59it/s]

Epoch 7:  25%|██▍       | 492/2000 [00:26<01:21, 18.58it/s]

Epoch 7:  25%|██▍       | 494/2000 [00:26<01:20, 18.59it/s]

Epoch 7:  25%|██▍       | 496/2000 [00:26<01:20, 18.60it/s]

Epoch 7:  25%|██▍       | 498/2000 [00:26<01:20, 18.62it/s]

Epoch 7:  25%|██▌       | 500/2000 [00:26<01:20, 18.64it/s]

Epoch 7:  25%|██▌       | 502/2000 [00:26<01:20, 18.64it/s]

Epoch 7:  25%|██▌       | 504/2000 [00:27<01:20, 18.64it/s]

Epoch 7:  25%|██▌       | 506/2000 [00:27<01:20, 18.65it/s]

Epoch 7:  25%|██▌       | 508/2000 [00:27<01:19, 18.65it/s]

Epoch 7:  26%|██▌       | 510/2000 [00:27<01:19, 18.65it/s]

Epoch 7:  26%|██▌       | 512/2000 [00:27<01:19, 18.66it/s]

Epoch 7:  26%|██▌       | 514/2000 [00:27<01:19, 18.67it/s]

Epoch 7:  26%|██▌       | 516/2000 [00:27<01:19, 18.67it/s]

Epoch 7:  26%|██▌       | 518/2000 [00:27<01:19, 18.66it/s]

Epoch 7:  26%|██▌       | 520/2000 [00:27<01:19, 18.67it/s]

Epoch 7:  26%|██▌       | 522/2000 [00:28<01:19, 18.67it/s]

Epoch 7:  26%|██▌       | 524/2000 [00:28<01:19, 18.67it/s]

Epoch 7:  26%|██▋       | 526/2000 [00:28<01:18, 18.66it/s]

Epoch 7:  26%|██▋       | 528/2000 [00:28<01:18, 18.67it/s]

Epoch 7:  26%|██▋       | 530/2000 [00:28<01:18, 18.67it/s]

Epoch 7:  27%|██▋       | 532/2000 [00:28<01:18, 18.67it/s]

Epoch 7:  27%|██▋       | 534/2000 [00:28<01:18, 18.67it/s]

Epoch 7:  27%|██▋       | 536/2000 [00:28<01:18, 18.68it/s]

Epoch 7:  27%|██▋       | 538/2000 [00:28<01:18, 18.70it/s]

Epoch 7:  27%|██▋       | 540/2000 [00:29<01:18, 18.69it/s]

Epoch 7:  27%|██▋       | 542/2000 [00:29<01:17, 18.70it/s]

Epoch 7:  27%|██▋       | 544/2000 [00:29<01:17, 18.69it/s]

Epoch 7:  27%|██▋       | 546/2000 [00:29<01:17, 18.68it/s]

Epoch 7:  27%|██▋       | 548/2000 [00:29<01:17, 18.68it/s]

Epoch 7:  28%|██▊       | 550/2000 [00:29<01:17, 18.69it/s]

Epoch 7:  28%|██▊       | 552/2000 [00:29<01:17, 18.68it/s]

Epoch 7:  28%|██▊       | 554/2000 [00:29<01:17, 18.68it/s]

Epoch 7:  28%|██▊       | 556/2000 [00:29<01:17, 18.68it/s]

Epoch 7:  28%|██▊       | 558/2000 [00:29<01:17, 18.67it/s]

Epoch 7:  28%|██▊       | 560/2000 [00:30<01:17, 18.66it/s]

Epoch 7:  28%|██▊       | 562/2000 [00:30<01:17, 18.67it/s]

Epoch 7:  28%|██▊       | 564/2000 [00:30<01:16, 18.68it/s]

Epoch 7:  28%|██▊       | 566/2000 [00:30<01:16, 18.67it/s]

Epoch 7:  28%|██▊       | 568/2000 [00:30<01:16, 18.65it/s]

Epoch 7:  28%|██▊       | 570/2000 [00:30<01:16, 18.65it/s]

Epoch 7:  29%|██▊       | 572/2000 [00:30<01:16, 18.64it/s]

Epoch 7:  29%|██▊       | 574/2000 [00:30<01:16, 18.67it/s]

Epoch 7:  29%|██▉       | 576/2000 [00:30<01:16, 18.65it/s]

Epoch 7:  29%|██▉       | 578/2000 [00:31<01:16, 18.67it/s]

Epoch 7:  29%|██▉       | 580/2000 [00:31<01:16, 18.67it/s]

Epoch 7:  29%|██▉       | 582/2000 [00:31<01:15, 18.66it/s]

Epoch 7:  29%|██▉       | 584/2000 [00:31<01:15, 18.66it/s]

Epoch 7:  29%|██▉       | 586/2000 [00:31<01:15, 18.65it/s]

Epoch 7:  29%|██▉       | 588/2000 [00:31<01:15, 18.65it/s]

Epoch 7:  30%|██▉       | 590/2000 [00:31<01:15, 18.66it/s]

Epoch 7:  30%|██▉       | 592/2000 [00:31<01:15, 18.66it/s]

Epoch 7:  30%|██▉       | 594/2000 [00:31<01:15, 18.67it/s]

Epoch 7:  30%|██▉       | 596/2000 [00:32<01:15, 18.67it/s]

Epoch 7:  30%|██▉       | 598/2000 [00:32<01:15, 18.66it/s]

Epoch 7:  30%|███       | 600/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  30%|███       | 602/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  30%|███       | 604/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  30%|███       | 606/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  30%|███       | 608/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  30%|███       | 610/2000 [00:32<01:14, 18.67it/s]

Epoch 7:  31%|███       | 612/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  31%|███       | 614/2000 [00:32<01:14, 18.68it/s]

Epoch 7:  31%|███       | 616/2000 [00:33<01:14, 18.67it/s]

Epoch 7:  31%|███       | 618/2000 [00:33<01:14, 18.66it/s]

Epoch 7:  31%|███       | 620/2000 [00:33<01:13, 18.66it/s]

Epoch 7:  31%|███       | 622/2000 [00:33<01:13, 18.67it/s]

Epoch 7:  31%|███       | 624/2000 [00:33<01:13, 18.67it/s]

Epoch 7:  31%|███▏      | 626/2000 [00:33<01:13, 18.67it/s]

Epoch 7:  31%|███▏      | 628/2000 [00:33<01:13, 18.67it/s]

Epoch 7:  32%|███▏      | 630/2000 [00:33<01:13, 18.66it/s]

Epoch 7:  32%|███▏      | 632/2000 [00:33<01:13, 18.67it/s]

Epoch 7:  32%|███▏      | 634/2000 [00:34<01:13, 18.67it/s]

Epoch 7:  32%|███▏      | 636/2000 [00:34<01:13, 18.66it/s]

Epoch 7:  32%|███▏      | 638/2000 [00:34<01:12, 18.66it/s]

Epoch 7:  32%|███▏      | 640/2000 [00:34<01:12, 18.66it/s]

Epoch 7:  32%|███▏      | 642/2000 [00:34<01:12, 18.67it/s]

Epoch 7:  32%|███▏      | 644/2000 [00:34<01:12, 18.67it/s]

Epoch 7:  32%|███▏      | 646/2000 [00:34<01:12, 18.67it/s]

Epoch 7:  32%|███▏      | 648/2000 [00:34<01:12, 18.67it/s]

Epoch 7:  32%|███▎      | 650/2000 [00:34<01:12, 18.67it/s]

Epoch 7:  33%|███▎      | 652/2000 [00:35<01:12, 18.66it/s]

Epoch 7:  33%|███▎      | 654/2000 [00:35<01:12, 18.67it/s]

Epoch 7:  33%|███▎      | 656/2000 [00:35<01:11, 18.67it/s]

Epoch 7:  33%|███▎      | 658/2000 [00:35<01:11, 18.68it/s]

Epoch 7:  33%|███▎      | 660/2000 [00:35<01:11, 18.66it/s]

Epoch 7:  33%|███▎      | 662/2000 [00:35<01:11, 18.66it/s]

Epoch 7:  33%|███▎      | 664/2000 [00:35<01:11, 18.67it/s]

Epoch 7:  33%|███▎      | 666/2000 [00:35<01:11, 18.66it/s]

Epoch 7:  33%|███▎      | 668/2000 [00:35<01:11, 18.66it/s]

Epoch 7:  34%|███▎      | 670/2000 [00:35<01:11, 18.66it/s]

Epoch 7:  34%|███▎      | 672/2000 [00:36<01:11, 18.67it/s]

Epoch 7:  34%|███▎      | 674/2000 [00:36<01:11, 18.67it/s]

Epoch 7:  34%|███▍      | 676/2000 [00:36<01:10, 18.67it/s]

Epoch 7:  34%|███▍      | 678/2000 [00:36<01:10, 18.68it/s]

Epoch 7:  34%|███▍      | 680/2000 [00:36<01:10, 18.66it/s]

Epoch 7:  34%|███▍      | 682/2000 [00:36<01:10, 18.65it/s]

Epoch 7:  34%|███▍      | 684/2000 [00:36<01:10, 18.66it/s]

Epoch 7:  34%|███▍      | 686/2000 [00:36<01:10, 18.67it/s]

Epoch 7:  34%|███▍      | 688/2000 [00:36<01:10, 18.67it/s]

Epoch 7:  34%|███▍      | 690/2000 [00:37<01:10, 18.67it/s]

Epoch 7:  35%|███▍      | 692/2000 [00:37<01:09, 18.69it/s]

Epoch 7:  35%|███▍      | 694/2000 [00:37<01:09, 18.69it/s]

Epoch 7:  35%|███▍      | 696/2000 [00:37<01:09, 18.69it/s]

Epoch 7:  35%|███▍      | 698/2000 [00:37<01:09, 18.68it/s]

Epoch 7:  35%|███▌      | 700/2000 [00:37<01:09, 18.67it/s]

Epoch 7:  35%|███▌      | 702/2000 [00:37<01:09, 18.67it/s]

Epoch 7:  35%|███▌      | 704/2000 [00:37<01:09, 18.69it/s]

Epoch 7:  35%|███▌      | 706/2000 [00:37<01:09, 18.68it/s]

Epoch 7:  35%|███▌      | 708/2000 [00:38<01:09, 18.69it/s]

Epoch 7:  36%|███▌      | 710/2000 [00:38<01:09, 18.68it/s]

Epoch 7:  36%|███▌      | 712/2000 [00:38<01:08, 18.69it/s]

Epoch 7:  36%|███▌      | 714/2000 [00:38<01:08, 18.68it/s]

Epoch 7:  36%|███▌      | 716/2000 [00:38<01:08, 18.67it/s]

Epoch 7:  36%|███▌      | 718/2000 [00:38<01:08, 18.69it/s]

Epoch 7:  36%|███▌      | 720/2000 [00:38<01:08, 18.67it/s]

Epoch 7:  36%|███▌      | 722/2000 [00:38<01:08, 18.67it/s]

Epoch 7:  36%|███▌      | 724/2000 [00:38<01:08, 18.67it/s]

Epoch 7:  36%|███▋      | 726/2000 [00:38<01:08, 18.67it/s]

Epoch 7:  36%|███▋      | 728/2000 [00:39<01:08, 18.67it/s]

Epoch 7:  36%|███▋      | 730/2000 [00:39<01:08, 18.67it/s]

Epoch 7:  37%|███▋      | 732/2000 [00:39<01:07, 18.68it/s]

Epoch 7:  37%|███▋      | 734/2000 [00:39<01:07, 18.69it/s]

Epoch 7:  37%|███▋      | 736/2000 [00:39<01:07, 18.68it/s]

Epoch 7:  37%|███▋      | 738/2000 [00:39<01:07, 18.68it/s]

Epoch 7:  37%|███▋      | 740/2000 [00:39<01:07, 18.68it/s]

Epoch 7:  37%|███▋      | 742/2000 [00:39<01:07, 18.67it/s]

Epoch 7:  37%|███▋      | 744/2000 [00:39<01:07, 18.67it/s]

Epoch 7:  37%|███▋      | 746/2000 [00:40<01:07, 18.68it/s]

Epoch 7:  37%|███▋      | 748/2000 [00:40<01:07, 18.68it/s]

Epoch 7:  38%|███▊      | 750/2000 [00:40<01:06, 18.69it/s]

Epoch 7:  38%|███▊      | 752/2000 [00:40<01:06, 18.70it/s]

Epoch 7:  38%|███▊      | 754/2000 [00:40<01:06, 18.69it/s]

Epoch 7:  38%|███▊      | 756/2000 [00:40<01:06, 18.70it/s]

Epoch 7:  38%|███▊      | 758/2000 [00:40<01:06, 18.69it/s]

Epoch 7:  38%|███▊      | 760/2000 [00:40<01:06, 18.69it/s]

Epoch 7:  38%|███▊      | 762/2000 [00:40<01:06, 18.68it/s]

Epoch 7:  38%|███▊      | 764/2000 [00:41<01:06, 18.67it/s]

Epoch 7:  38%|███▊      | 766/2000 [00:41<01:06, 18.66it/s]

Epoch 7:  38%|███▊      | 768/2000 [00:41<01:06, 18.65it/s]

Epoch 7:  38%|███▊      | 770/2000 [00:41<01:06, 18.63it/s]

Epoch 7:  39%|███▊      | 772/2000 [00:41<01:05, 18.66it/s]

Epoch 7:  39%|███▊      | 774/2000 [00:41<01:05, 18.65it/s]

Epoch 7:  39%|███▉      | 776/2000 [00:41<01:05, 18.65it/s]

Epoch 7:  39%|███▉      | 778/2000 [00:41<01:05, 18.66it/s]

Epoch 7:  39%|███▉      | 780/2000 [00:41<01:05, 18.67it/s]

Epoch 7:  39%|███▉      | 782/2000 [00:41<01:05, 18.66it/s]

Epoch 7:  39%|███▉      | 784/2000 [00:42<01:05, 18.66it/s]

Epoch 7:  39%|███▉      | 786/2000 [00:42<01:05, 18.66it/s]

Epoch 7:  39%|███▉      | 788/2000 [00:42<01:04, 18.67it/s]

Epoch 7:  40%|███▉      | 790/2000 [00:42<01:04, 18.67it/s]

Epoch 7:  40%|███▉      | 792/2000 [00:42<01:04, 18.67it/s]

Epoch 7:  40%|███▉      | 794/2000 [00:42<01:04, 18.68it/s]

Epoch 7:  40%|███▉      | 796/2000 [00:42<01:04, 18.69it/s]

Epoch 7:  40%|███▉      | 798/2000 [00:42<01:04, 18.69it/s]

Epoch 7:  40%|████      | 800/2000 [00:42<01:04, 18.70it/s]

Epoch 7:  40%|████      | 802/2000 [00:43<01:04, 18.70it/s]

Epoch 7:  40%|████      | 804/2000 [00:43<01:03, 18.69it/s]

Epoch 7:  40%|████      | 806/2000 [00:43<01:03, 18.68it/s]

Epoch 7:  40%|████      | 808/2000 [00:43<01:03, 18.68it/s]

Epoch 7:  40%|████      | 810/2000 [00:43<01:03, 18.69it/s]

Epoch 7:  41%|████      | 812/2000 [00:43<01:03, 18.67it/s]

Epoch 7:  41%|████      | 814/2000 [00:43<01:03, 18.67it/s]

Epoch 7:  41%|████      | 816/2000 [00:43<01:03, 18.67it/s]

Epoch 7:  41%|████      | 818/2000 [00:43<01:03, 18.67it/s]

Epoch 7:  41%|████      | 820/2000 [00:44<01:03, 18.66it/s]

Epoch 7:  41%|████      | 822/2000 [00:44<01:03, 18.67it/s]

Epoch 7:  41%|████      | 824/2000 [00:44<01:02, 18.67it/s]

Epoch 7:  41%|████▏     | 826/2000 [00:44<01:02, 18.66it/s]

Epoch 7:  41%|████▏     | 828/2000 [00:44<01:02, 18.66it/s]

Epoch 7:  42%|████▏     | 830/2000 [00:44<01:02, 18.66it/s]

Epoch 7:  42%|████▏     | 832/2000 [00:44<01:02, 18.67it/s]

Epoch 7:  42%|████▏     | 834/2000 [00:44<01:02, 18.67it/s]

Epoch 7:  42%|████▏     | 836/2000 [00:44<01:02, 18.66it/s]

Epoch 7:  42%|████▏     | 838/2000 [00:44<01:02, 18.67it/s]

Epoch 7:  42%|████▏     | 840/2000 [00:45<01:02, 18.67it/s]

Epoch 7:  42%|████▏     | 842/2000 [00:45<01:02, 18.66it/s]

Epoch 7:  42%|████▏     | 844/2000 [00:45<01:01, 18.66it/s]

Epoch 7:  42%|████▏     | 846/2000 [00:45<01:01, 18.67it/s]

Epoch 7:  42%|████▏     | 848/2000 [00:45<01:01, 18.68it/s]

Epoch 7:  42%|████▎     | 850/2000 [00:45<01:01, 18.68it/s]

Epoch 7:  43%|████▎     | 852/2000 [00:45<01:01, 18.68it/s]

Epoch 7:  43%|████▎     | 854/2000 [00:45<01:01, 18.67it/s]

Epoch 7:  43%|████▎     | 856/2000 [00:45<01:01, 18.66it/s]

Epoch 7:  43%|████▎     | 858/2000 [00:46<01:01, 18.68it/s]

Epoch 7:  43%|████▎     | 860/2000 [00:46<01:01, 18.67it/s]

Epoch 7:  43%|████▎     | 862/2000 [00:46<01:00, 18.66it/s]

Epoch 7:  43%|████▎     | 864/2000 [00:46<01:00, 18.67it/s]

Epoch 7:  43%|████▎     | 866/2000 [00:46<01:00, 18.66it/s]

Epoch 7:  43%|████▎     | 868/2000 [00:46<01:00, 18.65it/s]

Epoch 7:  44%|████▎     | 870/2000 [00:46<01:00, 18.65it/s]

Epoch 7:  44%|████▎     | 872/2000 [00:46<01:00, 18.66it/s]

Epoch 7:  44%|████▎     | 874/2000 [00:46<01:00, 18.67it/s]

Epoch 7:  44%|████▍     | 876/2000 [00:47<01:00, 18.67it/s]

Epoch 7:  44%|████▍     | 878/2000 [00:47<01:00, 18.67it/s]

Epoch 7:  44%|████▍     | 880/2000 [00:47<00:59, 18.68it/s]

Epoch 7:  44%|████▍     | 882/2000 [00:47<00:59, 18.68it/s]

Epoch 7:  44%|████▍     | 884/2000 [00:47<00:59, 18.67it/s]

Epoch 7:  44%|████▍     | 886/2000 [00:47<00:59, 18.67it/s]

Epoch 7:  44%|████▍     | 888/2000 [00:47<00:59, 18.66it/s]

Epoch 7:  44%|████▍     | 890/2000 [00:47<00:59, 18.67it/s]

Epoch 7:  45%|████▍     | 892/2000 [00:47<00:59, 18.66it/s]

Epoch 7:  45%|████▍     | 894/2000 [00:47<00:59, 18.66it/s]

Epoch 7:  45%|████▍     | 896/2000 [00:48<00:59, 18.68it/s]

Epoch 7:  45%|████▍     | 898/2000 [00:48<00:59, 18.67it/s]

Epoch 7:  45%|████▌     | 900/2000 [00:48<00:58, 18.67it/s]

Epoch 7:  45%|████▌     | 902/2000 [00:48<00:58, 18.66it/s]

Epoch 7:  45%|████▌     | 904/2000 [00:48<00:58, 18.66it/s]

Epoch 7:  45%|████▌     | 906/2000 [00:48<00:58, 18.67it/s]

Epoch 7:  45%|████▌     | 908/2000 [00:48<00:58, 18.67it/s]

Epoch 7:  46%|████▌     | 910/2000 [00:48<00:58, 18.67it/s]

Epoch 7:  46%|████▌     | 912/2000 [00:48<00:58, 18.66it/s]

Epoch 7:  46%|████▌     | 914/2000 [00:49<00:58, 18.66it/s]

Epoch 7:  46%|████▌     | 916/2000 [00:49<00:58, 18.65it/s]

Epoch 7:  46%|████▌     | 918/2000 [00:49<00:57, 18.67it/s]

Epoch 7:  46%|████▌     | 920/2000 [00:49<00:57, 18.67it/s]

Epoch 7:  46%|████▌     | 922/2000 [00:49<00:57, 18.67it/s]

Epoch 7:  46%|████▌     | 924/2000 [00:49<00:57, 18.67it/s]

Epoch 7:  46%|████▋     | 926/2000 [00:49<00:57, 18.68it/s]

Epoch 7:  46%|████▋     | 928/2000 [00:49<00:57, 18.68it/s]

Epoch 7:  46%|████▋     | 930/2000 [00:49<00:57, 18.68it/s]

Epoch 7:  47%|████▋     | 932/2000 [00:50<00:57, 18.68it/s]

Epoch 7:  47%|████▋     | 934/2000 [00:50<00:57, 18.67it/s]

Epoch 7:  47%|████▋     | 936/2000 [00:50<00:56, 18.67it/s]

Epoch 7:  47%|████▋     | 938/2000 [00:50<00:56, 18.67it/s]

Epoch 7:  47%|████▋     | 940/2000 [00:50<00:56, 18.68it/s]

Epoch 7:  47%|████▋     | 942/2000 [00:50<00:56, 18.68it/s]

Epoch 7:  47%|████▋     | 944/2000 [00:50<00:56, 18.68it/s]

Epoch 7:  47%|████▋     | 946/2000 [00:50<00:56, 18.69it/s]

Epoch 7:  47%|████▋     | 948/2000 [00:50<00:56, 18.68it/s]

Epoch 7:  48%|████▊     | 950/2000 [00:50<00:56, 18.66it/s]

Epoch 7:  48%|████▊     | 952/2000 [00:51<00:56, 18.67it/s]

Epoch 7:  48%|████▊     | 954/2000 [00:51<00:55, 18.69it/s]

Epoch 7:  48%|████▊     | 956/2000 [00:51<00:55, 18.69it/s]

Epoch 7:  48%|████▊     | 958/2000 [00:51<00:55, 18.68it/s]

Epoch 7:  48%|████▊     | 960/2000 [00:51<00:55, 18.68it/s]

Epoch 7:  48%|████▊     | 962/2000 [00:51<00:55, 18.67it/s]

Epoch 7:  48%|████▊     | 964/2000 [00:51<00:55, 18.67it/s]

Epoch 7:  48%|████▊     | 966/2000 [00:51<00:55, 18.68it/s]

Epoch 7:  48%|████▊     | 968/2000 [00:51<00:55, 18.68it/s]

Epoch 7:  48%|████▊     | 970/2000 [00:52<00:55, 18.69it/s]

Epoch 7:  49%|████▊     | 972/2000 [00:52<00:55, 18.68it/s]

Epoch 7:  49%|████▊     | 974/2000 [00:52<00:54, 18.68it/s]

Epoch 7:  49%|████▉     | 976/2000 [00:52<00:54, 18.68it/s]

Epoch 7:  49%|████▉     | 978/2000 [00:52<00:54, 18.66it/s]

Epoch 7:  49%|████▉     | 980/2000 [00:52<00:54, 18.67it/s]

Epoch 7:  49%|████▉     | 982/2000 [00:52<00:54, 18.66it/s]

Epoch 7:  49%|████▉     | 984/2000 [00:52<00:54, 18.66it/s]

Epoch 7:  49%|████▉     | 986/2000 [00:52<00:54, 18.66it/s]

Epoch 7:  49%|████▉     | 988/2000 [00:53<00:54, 18.67it/s]

Epoch 7:  50%|████▉     | 990/2000 [00:53<00:54, 18.69it/s]

Epoch 7:  50%|████▉     | 992/2000 [00:53<00:53, 18.69it/s]

Epoch 7:  50%|████▉     | 994/2000 [00:53<00:53, 18.68it/s]

Epoch 7:  50%|████▉     | 996/2000 [00:53<00:53, 18.68it/s]

Epoch 7:  50%|████▉     | 998/2000 [00:53<00:53, 18.69it/s]

Epoch 7:  50%|█████     | 1000/2000 [00:53<00:53, 18.69it/s]

Epoch 7:  50%|█████     | 1002/2000 [00:53<00:53, 18.67it/s]

Epoch 7:  50%|█████     | 1004/2000 [00:53<00:53, 18.67it/s]

Epoch 7:  50%|█████     | 1006/2000 [00:53<00:53, 18.66it/s]

Epoch 7:  50%|█████     | 1008/2000 [00:54<00:53, 18.67it/s]

Epoch 7:  50%|█████     | 1010/2000 [00:54<00:53, 18.67it/s]

Epoch 7:  51%|█████     | 1012/2000 [00:54<00:52, 18.67it/s]

Epoch 7:  51%|█████     | 1014/2000 [00:54<00:52, 18.68it/s]

Epoch 7:  51%|█████     | 1016/2000 [00:54<00:52, 18.69it/s]

Epoch 7:  51%|█████     | 1018/2000 [00:54<00:52, 18.69it/s]

Epoch 7:  51%|█████     | 1020/2000 [00:54<00:52, 18.69it/s]

Epoch 7:  51%|█████     | 1022/2000 [00:54<00:52, 18.69it/s]

Epoch 7:  51%|█████     | 1024/2000 [00:54<00:52, 18.70it/s]

Epoch 7:  51%|█████▏    | 1026/2000 [00:55<00:52, 18.69it/s]

Epoch 7:  51%|█████▏    | 1028/2000 [00:55<00:52, 18.68it/s]

Epoch 7:  52%|█████▏    | 1030/2000 [00:55<00:51, 18.67it/s]

Epoch 7:  52%|█████▏    | 1032/2000 [00:55<00:51, 18.66it/s]

Epoch 7:  52%|█████▏    | 1034/2000 [00:55<00:51, 18.67it/s]

Epoch 7:  52%|█████▏    | 1036/2000 [00:55<00:51, 18.68it/s]

Epoch 7:  52%|█████▏    | 1038/2000 [00:55<00:51, 18.68it/s]

Epoch 7:  52%|█████▏    | 1040/2000 [00:55<00:51, 18.67it/s]

Epoch 7:  52%|█████▏    | 1042/2000 [00:55<00:51, 18.67it/s]

Epoch 7:  52%|█████▏    | 1044/2000 [00:56<00:51, 18.53it/s]

Epoch 7:  52%|█████▏    | 1046/2000 [00:56<00:53, 17.95it/s]

Epoch 7:  52%|█████▏    | 1048/2000 [00:56<00:53, 17.94it/s]

Epoch 7:  52%|█████▎    | 1050/2000 [00:56<00:52, 18.10it/s]

Epoch 7:  53%|█████▎    | 1052/2000 [00:56<00:51, 18.24it/s]

Epoch 7:  53%|█████▎    | 1054/2000 [00:56<00:51, 18.32it/s]

Epoch 7:  53%|█████▎    | 1056/2000 [00:56<00:51, 18.44it/s]

Epoch 7:  53%|█████▎    | 1058/2000 [00:56<00:50, 18.50it/s]

Epoch 7:  53%|█████▎    | 1060/2000 [00:56<00:50, 18.54it/s]

Epoch 7:  53%|█████▎    | 1062/2000 [00:56<00:50, 18.59it/s]

Epoch 7:  53%|█████▎    | 1064/2000 [00:57<00:50, 18.61it/s]

Epoch 7:  53%|█████▎    | 1066/2000 [00:57<00:50, 18.63it/s]

Epoch 7:  53%|█████▎    | 1068/2000 [00:57<00:50, 18.63it/s]

Epoch 7:  54%|█████▎    | 1070/2000 [00:57<00:50, 18.54it/s]

Epoch 7:  54%|█████▎    | 1072/2000 [00:57<00:49, 18.58it/s]

Epoch 7:  54%|█████▎    | 1074/2000 [00:57<00:49, 18.59it/s]

Epoch 7:  54%|█████▍    | 1076/2000 [00:57<00:49, 18.62it/s]

Epoch 7:  54%|█████▍    | 1078/2000 [00:57<00:49, 18.64it/s]

Epoch 7:  54%|█████▍    | 1080/2000 [00:57<00:49, 18.65it/s]

Epoch 7:  54%|█████▍    | 1082/2000 [00:58<00:49, 18.66it/s]

Epoch 7:  54%|█████▍    | 1084/2000 [00:58<00:49, 18.65it/s]

Epoch 7:  54%|█████▍    | 1086/2000 [00:58<00:49, 18.65it/s]

Epoch 7:  54%|█████▍    | 1088/2000 [00:58<00:48, 18.67it/s]

Epoch 7:  55%|█████▍    | 1090/2000 [00:58<00:48, 18.66it/s]

Epoch 7:  55%|█████▍    | 1092/2000 [00:58<00:48, 18.67it/s]

Epoch 7:  55%|█████▍    | 1094/2000 [00:58<00:48, 18.68it/s]

Epoch 7:  55%|█████▍    | 1096/2000 [00:58<00:48, 18.68it/s]

Epoch 7:  55%|█████▍    | 1098/2000 [00:58<00:48, 18.67it/s]

Epoch 7:  55%|█████▌    | 1100/2000 [00:59<00:48, 18.68it/s]

Epoch 7:  55%|█████▌    | 1102/2000 [00:59<00:48, 18.67it/s]

Epoch 7:  55%|█████▌    | 1104/2000 [00:59<00:48, 18.66it/s]

Epoch 7:  55%|█████▌    | 1106/2000 [00:59<00:47, 18.66it/s]

Epoch 7:  55%|█████▌    | 1108/2000 [00:59<00:47, 18.66it/s]

Epoch 7:  56%|█████▌    | 1110/2000 [00:59<00:47, 18.67it/s]

Epoch 7:  56%|█████▌    | 1112/2000 [00:59<00:47, 18.67it/s]

Epoch 7:  56%|█████▌    | 1114/2000 [00:59<00:47, 18.68it/s]

Epoch 7:  56%|█████▌    | 1116/2000 [00:59<00:47, 18.67it/s]

Epoch 7:  56%|█████▌    | 1118/2000 [00:59<00:47, 18.66it/s]

Epoch 7:  56%|█████▌    | 1120/2000 [01:00<00:47, 18.67it/s]

Epoch 7:  56%|█████▌    | 1122/2000 [01:00<00:47, 18.67it/s]

Epoch 7:  56%|█████▌    | 1124/2000 [01:00<00:46, 18.67it/s]

Epoch 7:  56%|█████▋    | 1126/2000 [01:00<00:46, 18.67it/s]

Epoch 7:  56%|█████▋    | 1128/2000 [01:00<00:46, 18.67it/s]

Epoch 7:  56%|█████▋    | 1130/2000 [01:00<00:46, 18.67it/s]

Epoch 7:  57%|█████▋    | 1132/2000 [01:00<00:46, 18.67it/s]

Epoch 7:  57%|█████▋    | 1134/2000 [01:00<00:46, 18.68it/s]

Epoch 7:  57%|█████▋    | 1136/2000 [01:00<00:46, 18.67it/s]

Epoch 7:  57%|█████▋    | 1138/2000 [01:01<00:46, 18.66it/s]

Epoch 7:  57%|█████▋    | 1140/2000 [01:01<00:46, 18.66it/s]

Epoch 7:  57%|█████▋    | 1142/2000 [01:01<00:45, 18.66it/s]

Epoch 7:  57%|█████▋    | 1144/2000 [01:01<00:45, 18.67it/s]

Epoch 7:  57%|█████▋    | 1146/2000 [01:01<00:45, 18.67it/s]

Epoch 7:  57%|█████▋    | 1148/2000 [01:01<00:45, 18.67it/s]

Epoch 7:  57%|█████▊    | 1150/2000 [01:01<00:45, 18.66it/s]

Epoch 7:  58%|█████▊    | 1152/2000 [01:01<00:45, 18.67it/s]

Epoch 7:  58%|█████▊    | 1154/2000 [01:01<00:45, 18.67it/s]

Epoch 7:  58%|█████▊    | 1156/2000 [01:02<00:45, 18.66it/s]

Epoch 7:  58%|█████▊    | 1158/2000 [01:02<00:45, 18.67it/s]

Epoch 7:  58%|█████▊    | 1160/2000 [01:02<00:45, 18.67it/s]

Epoch 7:  58%|█████▊    | 1162/2000 [01:02<00:44, 18.66it/s]

Epoch 7:  58%|█████▊    | 1164/2000 [01:02<00:44, 18.65it/s]

Epoch 7:  58%|█████▊    | 1166/2000 [01:02<00:44, 18.66it/s]

Epoch 7:  58%|█████▊    | 1168/2000 [01:02<00:44, 18.66it/s]

Epoch 7:  58%|█████▊    | 1170/2000 [01:02<00:44, 18.67it/s]

Epoch 7:  59%|█████▊    | 1172/2000 [01:02<00:44, 18.68it/s]

Epoch 7:  59%|█████▊    | 1174/2000 [01:02<00:44, 18.68it/s]

Epoch 7:  59%|█████▉    | 1176/2000 [01:03<00:44, 18.68it/s]

Epoch 7:  59%|█████▉    | 1178/2000 [01:03<00:43, 18.68it/s]

Epoch 7:  59%|█████▉    | 1180/2000 [01:03<00:43, 18.67it/s]

Epoch 7:  59%|█████▉    | 1182/2000 [01:03<00:43, 18.66it/s]

Epoch 7:  59%|█████▉    | 1184/2000 [01:03<00:43, 18.66it/s]

Epoch 7:  59%|█████▉    | 1186/2000 [01:03<00:43, 18.66it/s]

Epoch 7:  59%|█████▉    | 1188/2000 [01:03<00:43, 18.67it/s]

Epoch 7:  60%|█████▉    | 1190/2000 [01:03<00:43, 18.66it/s]

Epoch 7:  60%|█████▉    | 1192/2000 [01:03<00:43, 18.66it/s]

Epoch 7:  60%|█████▉    | 1194/2000 [01:04<00:43, 18.66it/s]

Epoch 7:  60%|█████▉    | 1196/2000 [01:04<00:43, 18.67it/s]

Epoch 7:  60%|█████▉    | 1198/2000 [01:04<00:42, 18.67it/s]

Epoch 7:  60%|██████    | 1200/2000 [01:04<00:42, 18.67it/s]

Epoch 7:  60%|██████    | 1202/2000 [01:04<00:42, 18.67it/s]

Epoch 7:  60%|██████    | 1204/2000 [01:04<00:42, 18.66it/s]

Epoch 7:  60%|██████    | 1206/2000 [01:04<00:42, 18.67it/s]

Epoch 7:  60%|██████    | 1208/2000 [01:04<00:42, 18.66it/s]

Epoch 7:  60%|██████    | 1210/2000 [01:04<00:42, 18.67it/s]

Epoch 7:  61%|██████    | 1212/2000 [01:05<00:42, 18.68it/s]

Epoch 7:  61%|██████    | 1214/2000 [01:05<00:42, 18.67it/s]

Epoch 7:  61%|██████    | 1216/2000 [01:05<00:42, 18.67it/s]

Epoch 7:  61%|██████    | 1218/2000 [01:05<00:41, 18.67it/s]

Epoch 7:  61%|██████    | 1220/2000 [01:05<00:41, 18.66it/s]

Epoch 7:  61%|██████    | 1222/2000 [01:05<00:41, 18.66it/s]

Epoch 7:  61%|██████    | 1224/2000 [01:05<00:41, 18.66it/s]

Epoch 7:  61%|██████▏   | 1226/2000 [01:05<00:41, 18.67it/s]

Epoch 7:  61%|██████▏   | 1228/2000 [01:05<00:41, 18.67it/s]

Epoch 7:  62%|██████▏   | 1230/2000 [01:05<00:41, 18.68it/s]

Epoch 7:  62%|██████▏   | 1232/2000 [01:06<00:41, 18.68it/s]

Epoch 7:  62%|██████▏   | 1234/2000 [01:06<00:41, 18.60it/s]

Epoch 7:  62%|██████▏   | 1236/2000 [01:06<00:41, 18.61it/s]

Epoch 7:  62%|██████▏   | 1238/2000 [01:06<00:41, 18.54it/s]

Epoch 7:  62%|██████▏   | 1240/2000 [01:06<00:40, 18.56it/s]

Epoch 7:  62%|██████▏   | 1242/2000 [01:06<00:40, 18.58it/s]

Epoch 7:  62%|██████▏   | 1244/2000 [01:06<00:40, 18.59it/s]

Epoch 7:  62%|██████▏   | 1246/2000 [01:06<00:40, 18.61it/s]

Epoch 7:  62%|██████▏   | 1248/2000 [01:06<00:40, 18.63it/s]

Epoch 7:  62%|██████▎   | 1250/2000 [01:07<00:40, 18.55it/s]

Epoch 7:  63%|██████▎   | 1252/2000 [01:07<00:40, 18.58it/s]

Epoch 7:  63%|██████▎   | 1254/2000 [01:07<00:40, 18.61it/s]

Epoch 7:  63%|██████▎   | 1256/2000 [01:07<00:39, 18.61it/s]

Epoch 7:  63%|██████▎   | 1258/2000 [01:07<00:39, 18.63it/s]

Epoch 7:  63%|██████▎   | 1260/2000 [01:07<00:39, 18.63it/s]

Epoch 7:  63%|██████▎   | 1262/2000 [01:07<00:39, 18.64it/s]

Epoch 7:  63%|██████▎   | 1264/2000 [01:07<00:39, 18.65it/s]

Epoch 7:  63%|██████▎   | 1266/2000 [01:07<00:39, 18.65it/s]

Epoch 7:  63%|██████▎   | 1268/2000 [01:08<00:39, 18.66it/s]

Epoch 7:  64%|██████▎   | 1270/2000 [01:08<00:39, 18.65it/s]

Epoch 7:  64%|██████▎   | 1272/2000 [01:08<00:39, 18.66it/s]

Epoch 7:  64%|██████▎   | 1274/2000 [01:08<00:38, 18.66it/s]

Epoch 7:  64%|██████▍   | 1276/2000 [01:08<00:38, 18.65it/s]

Epoch 7:  64%|██████▍   | 1278/2000 [01:08<00:38, 18.67it/s]

Epoch 7:  64%|██████▍   | 1280/2000 [01:08<00:38, 18.67it/s]

Epoch 7:  64%|██████▍   | 1282/2000 [01:08<00:38, 18.67it/s]

Epoch 7:  64%|██████▍   | 1284/2000 [01:08<00:38, 18.65it/s]

Epoch 7:  64%|██████▍   | 1286/2000 [01:08<00:38, 18.65it/s]

Epoch 7:  64%|██████▍   | 1288/2000 [01:09<00:38, 18.64it/s]

Epoch 7:  64%|██████▍   | 1290/2000 [01:09<00:38, 18.67it/s]

Epoch 7:  65%|██████▍   | 1292/2000 [01:09<00:37, 18.66it/s]

Epoch 7:  65%|██████▍   | 1294/2000 [01:09<00:37, 18.65it/s]

Epoch 7:  65%|██████▍   | 1296/2000 [01:09<00:37, 18.65it/s]

Epoch 7:  65%|██████▍   | 1298/2000 [01:09<00:37, 18.65it/s]

Epoch 7:  65%|██████▌   | 1300/2000 [01:09<00:37, 18.66it/s]

Epoch 7:  65%|██████▌   | 1302/2000 [01:09<00:37, 18.66it/s]

Epoch 7:  65%|██████▌   | 1304/2000 [01:09<00:37, 18.66it/s]

Epoch 7:  65%|██████▌   | 1306/2000 [01:10<00:37, 18.67it/s]

Epoch 7:  65%|██████▌   | 1308/2000 [01:10<00:37, 18.67it/s]

Epoch 7:  66%|██████▌   | 1310/2000 [01:10<00:36, 18.66it/s]

Epoch 7:  66%|██████▌   | 1312/2000 [01:10<00:36, 18.66it/s]

Epoch 7:  66%|██████▌   | 1314/2000 [01:10<00:36, 18.66it/s]

Epoch 7:  66%|██████▌   | 1316/2000 [01:10<00:36, 18.67it/s]

Epoch 7:  66%|██████▌   | 1318/2000 [01:10<00:36, 18.67it/s]

Epoch 7:  66%|██████▌   | 1320/2000 [01:10<00:36, 18.67it/s]

Epoch 7:  66%|██████▌   | 1322/2000 [01:10<00:36, 18.66it/s]

Epoch 7:  66%|██████▌   | 1324/2000 [01:11<00:36, 18.67it/s]

Epoch 7:  66%|██████▋   | 1326/2000 [01:11<00:36, 18.67it/s]

Epoch 7:  66%|██████▋   | 1328/2000 [01:11<00:36, 18.66it/s]

Epoch 7:  66%|██████▋   | 1330/2000 [01:11<00:35, 18.66it/s]

Epoch 7:  67%|██████▋   | 1332/2000 [01:11<00:35, 18.67it/s]

Epoch 7:  67%|██████▋   | 1334/2000 [01:11<00:35, 18.66it/s]

Epoch 7:  67%|██████▋   | 1336/2000 [01:11<00:35, 18.67it/s]

Epoch 7:  67%|██████▋   | 1338/2000 [01:11<00:35, 18.67it/s]

Epoch 7:  67%|██████▋   | 1340/2000 [01:11<00:35, 18.67it/s]

Epoch 7:  67%|██████▋   | 1342/2000 [01:11<00:35, 18.67it/s]

Epoch 7:  67%|██████▋   | 1344/2000 [01:12<00:35, 18.67it/s]

Epoch 7:  67%|██████▋   | 1346/2000 [01:12<00:35, 18.66it/s]

Epoch 7:  67%|██████▋   | 1348/2000 [01:12<00:35, 18.47it/s]

Epoch 7:  68%|██████▊   | 1350/2000 [01:12<00:35, 18.53it/s]

Epoch 7:  68%|██████▊   | 1352/2000 [01:12<00:34, 18.58it/s]

Epoch 7:  68%|██████▊   | 1354/2000 [01:12<00:34, 18.62it/s]

Epoch 7:  68%|██████▊   | 1356/2000 [01:12<00:34, 18.63it/s]

Epoch 7:  68%|██████▊   | 1358/2000 [01:12<00:34, 18.66it/s]

Epoch 7:  68%|██████▊   | 1360/2000 [01:12<00:34, 18.68it/s]

Epoch 7:  68%|██████▊   | 1362/2000 [01:13<00:34, 18.67it/s]

Epoch 7:  68%|██████▊   | 1364/2000 [01:13<00:34, 18.68it/s]

Epoch 7:  68%|██████▊   | 1366/2000 [01:13<00:33, 18.67it/s]

Epoch 7:  68%|██████▊   | 1368/2000 [01:13<00:33, 18.68it/s]

Epoch 7:  68%|██████▊   | 1370/2000 [01:13<00:33, 18.68it/s]

Epoch 7:  69%|██████▊   | 1372/2000 [01:13<00:33, 18.68it/s]

Epoch 7:  69%|██████▊   | 1374/2000 [01:13<00:33, 18.67it/s]

Epoch 7:  69%|██████▉   | 1376/2000 [01:13<00:33, 18.66it/s]

Epoch 7:  69%|██████▉   | 1378/2000 [01:13<00:33, 18.66it/s]

Epoch 7:  69%|██████▉   | 1380/2000 [01:14<00:33, 18.66it/s]

Epoch 7:  69%|██████▉   | 1382/2000 [01:14<00:33, 18.66it/s]

Epoch 7:  69%|██████▉   | 1384/2000 [01:14<00:32, 18.67it/s]

Epoch 7:  69%|██████▉   | 1386/2000 [01:14<00:32, 18.67it/s]

Epoch 7:  69%|██████▉   | 1388/2000 [01:14<00:32, 18.68it/s]

Epoch 7:  70%|██████▉   | 1390/2000 [01:14<00:32, 18.68it/s]

Epoch 7:  70%|██████▉   | 1392/2000 [01:14<00:32, 18.69it/s]

Epoch 7:  70%|██████▉   | 1394/2000 [01:14<00:32, 18.53it/s]

Epoch 7:  70%|██████▉   | 1396/2000 [01:14<00:32, 18.57it/s]

Epoch 7:  70%|██████▉   | 1398/2000 [01:14<00:32, 18.62it/s]

Epoch 7:  70%|███████   | 1400/2000 [01:15<00:32, 18.64it/s]

Epoch 7:  70%|███████   | 1402/2000 [01:15<00:32, 18.66it/s]

Epoch 7:  70%|███████   | 1404/2000 [01:15<00:31, 18.68it/s]

Epoch 7:  70%|███████   | 1406/2000 [01:15<00:31, 18.69it/s]

Epoch 7:  70%|███████   | 1408/2000 [01:15<00:31, 18.70it/s]

Epoch 7:  70%|███████   | 1410/2000 [01:15<00:31, 18.71it/s]

Epoch 7:  71%|███████   | 1412/2000 [01:15<00:31, 18.70it/s]

Epoch 7:  71%|███████   | 1414/2000 [01:15<00:31, 18.70it/s]

Epoch 7:  71%|███████   | 1416/2000 [01:15<00:31, 18.71it/s]

Epoch 7:  71%|███████   | 1418/2000 [01:16<00:31, 18.71it/s]

Epoch 7:  71%|███████   | 1420/2000 [01:16<00:31, 18.66it/s]

Epoch 7:  71%|███████   | 1422/2000 [01:16<00:30, 18.67it/s]

Epoch 7:  71%|███████   | 1424/2000 [01:16<00:30, 18.68it/s]

Epoch 7:  71%|███████▏  | 1426/2000 [01:16<00:30, 18.64it/s]

Epoch 7:  71%|███████▏  | 1428/2000 [01:16<00:30, 18.65it/s]

Epoch 7:  72%|███████▏  | 1430/2000 [01:16<00:30, 18.67it/s]

Epoch 7:  72%|███████▏  | 1432/2000 [01:16<00:30, 18.69it/s]

Epoch 7:  72%|███████▏  | 1434/2000 [01:16<00:30, 18.69it/s]

Epoch 7:  72%|███████▏  | 1436/2000 [01:17<00:30, 18.71it/s]

Epoch 7:  72%|███████▏  | 1438/2000 [01:17<00:30, 18.71it/s]

Epoch 7:  72%|███████▏  | 1440/2000 [01:17<00:29, 18.71it/s]

Epoch 7:  72%|███████▏  | 1442/2000 [01:17<00:29, 18.71it/s]

Epoch 7:  72%|███████▏  | 1444/2000 [01:17<00:29, 18.71it/s]

Epoch 7:  72%|███████▏  | 1446/2000 [01:17<00:29, 18.72it/s]

Epoch 7:  72%|███████▏  | 1448/2000 [01:17<00:29, 18.72it/s]

Epoch 7:  72%|███████▎  | 1450/2000 [01:17<00:29, 18.72it/s]

Epoch 7:  73%|███████▎  | 1452/2000 [01:17<00:29, 18.72it/s]

Epoch 7:  73%|███████▎  | 1454/2000 [01:17<00:29, 18.71it/s]

Epoch 7:  73%|███████▎  | 1456/2000 [01:18<00:29, 18.71it/s]

Epoch 7:  73%|███████▎  | 1458/2000 [01:18<00:28, 18.70it/s]

Epoch 7:  73%|███████▎  | 1460/2000 [01:18<00:28, 18.69it/s]

Epoch 7:  73%|███████▎  | 1462/2000 [01:18<00:28, 18.68it/s]

Epoch 7:  73%|███████▎  | 1464/2000 [01:18<00:28, 18.68it/s]

Epoch 7:  73%|███████▎  | 1466/2000 [01:18<00:28, 18.69it/s]

Epoch 7:  73%|███████▎  | 1468/2000 [01:18<00:28, 18.70it/s]

Epoch 7:  74%|███████▎  | 1470/2000 [01:18<00:28, 18.71it/s]

Epoch 7:  74%|███████▎  | 1472/2000 [01:18<00:28, 18.72it/s]

Epoch 7:  74%|███████▎  | 1474/2000 [01:19<00:28, 18.72it/s]

Epoch 7:  74%|███████▍  | 1476/2000 [01:19<00:27, 18.72it/s]

Epoch 7:  74%|███████▍  | 1478/2000 [01:19<00:27, 18.72it/s]

Epoch 7:  74%|███████▍  | 1480/2000 [01:19<00:27, 18.71it/s]

Epoch 7:  74%|███████▍  | 1482/2000 [01:19<00:27, 18.70it/s]

Epoch 7:  74%|███████▍  | 1484/2000 [01:19<00:27, 18.70it/s]

Epoch 7:  74%|███████▍  | 1486/2000 [01:19<00:27, 18.71it/s]

Epoch 7:  74%|███████▍  | 1488/2000 [01:19<00:27, 18.72it/s]

Epoch 7:  74%|███████▍  | 1490/2000 [01:19<00:27, 18.71it/s]

Epoch 7:  75%|███████▍  | 1492/2000 [01:20<00:27, 18.72it/s]

Epoch 7:  75%|███████▍  | 1494/2000 [01:20<00:27, 18.71it/s]

Epoch 7:  75%|███████▍  | 1496/2000 [01:20<00:26, 18.70it/s]

Epoch 7:  75%|███████▍  | 1498/2000 [01:20<00:26, 18.69it/s]

Epoch 7:  75%|███████▌  | 1500/2000 [01:20<00:26, 18.71it/s]

Epoch 7:  75%|███████▌  | 1502/2000 [01:20<00:26, 18.72it/s]

Epoch 7:  75%|███████▌  | 1504/2000 [01:20<00:26, 18.72it/s]

Epoch 7:  75%|███████▌  | 1506/2000 [01:20<00:26, 18.72it/s]

Epoch 7:  75%|███████▌  | 1508/2000 [01:20<00:26, 18.72it/s]

Epoch 7:  76%|███████▌  | 1510/2000 [01:20<00:26, 18.72it/s]

Epoch 7:  76%|███████▌  | 1512/2000 [01:21<00:26, 18.70it/s]

Epoch 7:  76%|███████▌  | 1514/2000 [01:21<00:25, 18.70it/s]

Epoch 7:  76%|███████▌  | 1516/2000 [01:21<00:25, 18.70it/s]

Epoch 7:  76%|███████▌  | 1518/2000 [01:21<00:25, 18.71it/s]

Epoch 7:  76%|███████▌  | 1520/2000 [01:21<00:25, 18.70it/s]

Epoch 7:  76%|███████▌  | 1522/2000 [01:21<00:25, 18.71it/s]

Epoch 7:  76%|███████▌  | 1524/2000 [01:21<00:25, 18.72it/s]

Epoch 7:  76%|███████▋  | 1526/2000 [01:21<00:25, 18.72it/s]

Epoch 7:  76%|███████▋  | 1528/2000 [01:21<00:25, 18.72it/s]

Epoch 7:  76%|███████▋  | 1530/2000 [01:22<00:25, 18.73it/s]

Epoch 7:  77%|███████▋  | 1532/2000 [01:22<00:24, 18.73it/s]

Epoch 7:  77%|███████▋  | 1534/2000 [01:22<00:24, 18.72it/s]

Epoch 7:  77%|███████▋  | 1536/2000 [01:22<00:24, 18.72it/s]

Epoch 7:  77%|███████▋  | 1538/2000 [01:22<00:24, 18.71it/s]

Epoch 7:  77%|███████▋  | 1540/2000 [01:22<00:24, 18.72it/s]

Epoch 7:  77%|███████▋  | 1542/2000 [01:22<00:24, 18.72it/s]

Epoch 7:  77%|███████▋  | 1544/2000 [01:22<00:24, 18.71it/s]

Epoch 7:  77%|███████▋  | 1546/2000 [01:22<00:24, 18.70it/s]

Epoch 7:  77%|███████▋  | 1548/2000 [01:23<00:24, 18.70it/s]

Epoch 7:  78%|███████▊  | 1550/2000 [01:23<00:24, 18.70it/s]

Epoch 7:  78%|███████▊  | 1552/2000 [01:23<00:23, 18.70it/s]

Epoch 7:  78%|███████▊  | 1554/2000 [01:23<00:23, 18.69it/s]

Epoch 7:  78%|███████▊  | 1556/2000 [01:23<00:23, 18.70it/s]

Epoch 7:  78%|███████▊  | 1558/2000 [01:23<00:23, 18.70it/s]

Epoch 7:  78%|███████▊  | 1560/2000 [01:23<00:23, 18.69it/s]

Epoch 7:  78%|███████▊  | 1562/2000 [01:23<00:23, 18.69it/s]

Epoch 7:  78%|███████▊  | 1564/2000 [01:23<00:23, 18.70it/s]

Epoch 7:  78%|███████▊  | 1566/2000 [01:23<00:23, 18.70it/s]

Epoch 7:  78%|███████▊  | 1568/2000 [01:24<00:23, 18.71it/s]

Epoch 7:  78%|███████▊  | 1570/2000 [01:24<00:22, 18.70it/s]

Epoch 7:  79%|███████▊  | 1572/2000 [01:24<00:22, 18.70it/s]

Epoch 7:  79%|███████▊  | 1574/2000 [01:24<00:22, 18.71it/s]

Epoch 7:  79%|███████▉  | 1576/2000 [01:24<00:22, 18.71it/s]

Epoch 7:  79%|███████▉  | 1578/2000 [01:24<00:22, 18.70it/s]

Epoch 7:  79%|███████▉  | 1580/2000 [01:24<00:22, 18.72it/s]

Epoch 7:  79%|███████▉  | 1582/2000 [01:24<00:22, 18.71it/s]

Epoch 7:  79%|███████▉  | 1584/2000 [01:24<00:22, 18.70it/s]

Epoch 7:  79%|███████▉  | 1586/2000 [01:25<00:22, 18.71it/s]

Epoch 7:  79%|███████▉  | 1588/2000 [01:25<00:22, 18.68it/s]

Epoch 7:  80%|███████▉  | 1590/2000 [01:25<00:21, 18.70it/s]

Epoch 7:  80%|███████▉  | 1592/2000 [01:25<00:21, 18.68it/s]

Epoch 7:  80%|███████▉  | 1594/2000 [01:25<00:21, 18.68it/s]

Epoch 7:  80%|███████▉  | 1596/2000 [01:25<00:21, 18.68it/s]

Epoch 7:  80%|███████▉  | 1598/2000 [01:25<00:21, 18.70it/s]

Epoch 7:  80%|████████  | 1600/2000 [01:25<00:21, 18.71it/s]

Epoch 7:  80%|████████  | 1602/2000 [01:25<00:21, 18.70it/s]

Epoch 7:  80%|████████  | 1604/2000 [01:26<00:21, 18.70it/s]

Epoch 7:  80%|████████  | 1606/2000 [01:26<00:21, 18.72it/s]

Epoch 7:  80%|████████  | 1608/2000 [01:26<00:20, 18.73it/s]

Epoch 7:  80%|████████  | 1610/2000 [01:26<00:20, 18.72it/s]

Epoch 7:  81%|████████  | 1612/2000 [01:26<00:20, 18.72it/s]

Epoch 7:  81%|████████  | 1614/2000 [01:26<00:20, 18.72it/s]

Epoch 7:  81%|████████  | 1616/2000 [01:26<00:20, 18.72it/s]

Epoch 7:  81%|████████  | 1618/2000 [01:26<00:20, 18.72it/s]

Epoch 7:  81%|████████  | 1620/2000 [01:26<00:20, 18.72it/s]

Epoch 7:  81%|████████  | 1622/2000 [01:26<00:20, 18.71it/s]

Epoch 7:  81%|████████  | 1624/2000 [01:27<00:20, 18.71it/s]

Epoch 7:  81%|████████▏ | 1626/2000 [01:27<00:20, 18.69it/s]

Epoch 7:  81%|████████▏ | 1628/2000 [01:27<00:19, 18.70it/s]

Epoch 7:  82%|████████▏ | 1630/2000 [01:27<00:19, 18.70it/s]

Epoch 7:  82%|████████▏ | 1632/2000 [01:27<00:19, 18.71it/s]

Epoch 7:  82%|████████▏ | 1634/2000 [01:27<00:19, 18.73it/s]

Epoch 7:  82%|████████▏ | 1636/2000 [01:27<00:19, 18.73it/s]

Epoch 7:  82%|████████▏ | 1638/2000 [01:27<00:19, 18.73it/s]

Epoch 7:  82%|████████▏ | 1640/2000 [01:27<00:19, 18.72it/s]

Epoch 7:  82%|████████▏ | 1642/2000 [01:28<00:19, 18.72it/s]

Epoch 7:  82%|████████▏ | 1644/2000 [01:28<00:19, 18.72it/s]

Epoch 7:  82%|████████▏ | 1646/2000 [01:28<00:18, 18.73it/s]

Epoch 7:  82%|████████▏ | 1648/2000 [01:28<00:18, 18.72it/s]

Epoch 7:  82%|████████▎ | 1650/2000 [01:28<00:18, 18.72it/s]

Epoch 7:  83%|████████▎ | 1652/2000 [01:28<00:18, 18.73it/s]

Epoch 7:  83%|████████▎ | 1654/2000 [01:28<00:18, 18.70it/s]

Epoch 7:  83%|████████▎ | 1656/2000 [01:28<00:18, 18.53it/s]

Epoch 7:  83%|████████▎ | 1658/2000 [01:28<00:19, 17.98it/s]

Epoch 7:  83%|████████▎ | 1660/2000 [01:29<00:18, 17.96it/s]

Epoch 7:  83%|████████▎ | 1662/2000 [01:29<00:18, 18.05it/s]

Epoch 7:  83%|████████▎ | 1664/2000 [01:29<00:18, 18.20it/s]

Epoch 7:  83%|████████▎ | 1666/2000 [01:29<00:18, 18.32it/s]

Epoch 7:  83%|████████▎ | 1668/2000 [01:29<00:18, 18.42it/s]

Epoch 7:  84%|████████▎ | 1670/2000 [01:29<00:17, 18.50it/s]

Epoch 7:  84%|████████▎ | 1672/2000 [01:29<00:17, 18.56it/s]

Epoch 7:  84%|████████▎ | 1674/2000 [01:29<00:17, 18.60it/s]

Epoch 7:  84%|████████▍ | 1676/2000 [01:29<00:17, 18.62it/s]

Epoch 7:  84%|████████▍ | 1678/2000 [01:29<00:17, 18.64it/s]

Epoch 7:  84%|████████▍ | 1680/2000 [01:30<00:17, 18.65it/s]

Epoch 7:  84%|████████▍ | 1682/2000 [01:30<00:17, 18.67it/s]

Epoch 7:  84%|████████▍ | 1684/2000 [01:30<00:16, 18.68it/s]

Epoch 7:  84%|████████▍ | 1686/2000 [01:30<00:16, 18.70it/s]

Epoch 7:  84%|████████▍ | 1688/2000 [01:30<00:16, 18.70it/s]

Epoch 7:  84%|████████▍ | 1690/2000 [01:30<00:16, 18.70it/s]

Epoch 7:  85%|████████▍ | 1692/2000 [01:30<00:16, 18.71it/s]

Epoch 7:  85%|████████▍ | 1694/2000 [01:30<00:16, 18.71it/s]

Epoch 7:  85%|████████▍ | 1696/2000 [01:30<00:16, 18.71it/s]

Epoch 7:  85%|████████▍ | 1698/2000 [01:31<00:16, 18.70it/s]

Epoch 7:  85%|████████▌ | 1700/2000 [01:31<00:16, 18.71it/s]

Epoch 7:  85%|████████▌ | 1702/2000 [01:31<00:15, 18.72it/s]

Epoch 7:  85%|████████▌ | 1704/2000 [01:31<00:15, 18.73it/s]

Epoch 7:  85%|████████▌ | 1706/2000 [01:31<00:15, 18.73it/s]

Epoch 7:  85%|████████▌ | 1708/2000 [01:31<00:15, 18.73it/s]

Epoch 7:  86%|████████▌ | 1710/2000 [01:31<00:15, 18.71it/s]

Epoch 7:  86%|████████▌ | 1712/2000 [01:31<00:15, 18.71it/s]

Epoch 7:  86%|████████▌ | 1714/2000 [01:31<00:15, 18.71it/s]

Epoch 7:  86%|████████▌ | 1716/2000 [01:32<00:15, 18.71it/s]

Epoch 7:  86%|████████▌ | 1718/2000 [01:32<00:15, 18.70it/s]

Epoch 7:  86%|████████▌ | 1720/2000 [01:32<00:14, 18.72it/s]

Epoch 7:  86%|████████▌ | 1722/2000 [01:32<00:14, 18.72it/s]

Epoch 7:  86%|████████▌ | 1724/2000 [01:32<00:14, 18.71it/s]

Epoch 7:  86%|████████▋ | 1726/2000 [01:32<00:14, 18.71it/s]

Epoch 7:  86%|████████▋ | 1728/2000 [01:32<00:14, 18.71it/s]

Epoch 7:  86%|████████▋ | 1730/2000 [01:32<00:14, 18.71it/s]

Epoch 7:  87%|████████▋ | 1732/2000 [01:32<00:14, 18.71it/s]

Epoch 7:  87%|████████▋ | 1734/2000 [01:32<00:14, 18.71it/s]

Epoch 7:  87%|████████▋ | 1736/2000 [01:33<00:14, 18.71it/s]

Epoch 7:  87%|████████▋ | 1738/2000 [01:33<00:13, 18.72it/s]

Epoch 7:  87%|████████▋ | 1740/2000 [01:33<00:13, 18.73it/s]

Epoch 7:  87%|████████▋ | 1742/2000 [01:33<00:13, 18.71it/s]

Epoch 7:  87%|████████▋ | 1744/2000 [01:33<00:13, 18.71it/s]

Epoch 7:  87%|████████▋ | 1746/2000 [01:33<00:13, 18.72it/s]

Epoch 7:  87%|████████▋ | 1748/2000 [01:33<00:13, 18.71it/s]

Epoch 7:  88%|████████▊ | 1750/2000 [01:33<00:13, 18.70it/s]

Epoch 7:  88%|████████▊ | 1752/2000 [01:33<00:13, 18.71it/s]

Epoch 7:  88%|████████▊ | 1754/2000 [01:34<00:13, 18.73it/s]

Epoch 7:  88%|████████▊ | 1756/2000 [01:34<00:13, 18.73it/s]

Epoch 7:  88%|████████▊ | 1758/2000 [01:34<00:12, 18.73it/s]

Epoch 7:  88%|████████▊ | 1760/2000 [01:34<00:12, 18.72it/s]

Epoch 7:  88%|████████▊ | 1762/2000 [01:34<00:12, 18.72it/s]

Epoch 7:  88%|████████▊ | 1764/2000 [01:34<00:12, 18.71it/s]

Epoch 7:  88%|████████▊ | 1766/2000 [01:34<00:12, 18.71it/s]

Epoch 7:  88%|████████▊ | 1768/2000 [01:34<00:12, 18.71it/s]

Epoch 7:  88%|████████▊ | 1770/2000 [01:34<00:12, 18.73it/s]

Epoch 7:  89%|████████▊ | 1772/2000 [01:35<00:12, 18.72it/s]

Epoch 7:  89%|████████▊ | 1774/2000 [01:35<00:12, 18.70it/s]

Epoch 7:  89%|████████▉ | 1776/2000 [01:35<00:11, 18.71it/s]

Epoch 7:  89%|████████▉ | 1778/2000 [01:35<00:11, 18.72it/s]

Epoch 7:  89%|████████▉ | 1780/2000 [01:35<00:11, 18.71it/s]

Epoch 7:  89%|████████▉ | 1782/2000 [01:35<00:11, 18.70it/s]

Epoch 7:  89%|████████▉ | 1784/2000 [01:35<00:11, 18.72it/s]

Epoch 7:  89%|████████▉ | 1786/2000 [01:35<00:11, 18.71it/s]

Epoch 7:  89%|████████▉ | 1788/2000 [01:35<00:11, 18.71it/s]

Epoch 7:  90%|████████▉ | 1790/2000 [01:35<00:11, 18.72it/s]

Epoch 7:  90%|████████▉ | 1792/2000 [01:36<00:11, 18.72it/s]

Epoch 7:  90%|████████▉ | 1794/2000 [01:36<00:11, 18.72it/s]

Epoch 7:  90%|████████▉ | 1796/2000 [01:36<00:10, 18.71it/s]

Epoch 7:  90%|████████▉ | 1798/2000 [01:36<00:10, 18.71it/s]

Epoch 7:  90%|█████████ | 1800/2000 [01:36<00:10, 18.72it/s]

Epoch 7:  90%|█████████ | 1802/2000 [01:36<00:10, 18.71it/s]

Epoch 7:  90%|█████████ | 1804/2000 [01:36<00:10, 18.72it/s]

Epoch 7:  90%|█████████ | 1806/2000 [01:36<00:10, 18.73it/s]

Epoch 7:  90%|█████████ | 1808/2000 [01:36<00:10, 18.74it/s]

Epoch 7:  90%|█████████ | 1810/2000 [01:37<00:10, 18.74it/s]

Epoch 7:  91%|█████████ | 1812/2000 [01:37<00:10, 18.72it/s]

Epoch 7:  91%|█████████ | 1814/2000 [01:37<00:09, 18.71it/s]

Epoch 7:  91%|█████████ | 1816/2000 [01:37<00:09, 18.71it/s]

Epoch 7:  91%|█████████ | 1818/2000 [01:37<00:09, 18.72it/s]

Epoch 7:  91%|█████████ | 1820/2000 [01:37<00:09, 18.71it/s]

Epoch 7:  91%|█████████ | 1822/2000 [01:37<00:09, 18.72it/s]

Epoch 7:  91%|█████████ | 1824/2000 [01:37<00:09, 18.72it/s]

Epoch 7:  91%|█████████▏| 1826/2000 [01:37<00:09, 18.73it/s]

Epoch 7:  91%|█████████▏| 1828/2000 [01:38<00:09, 18.73it/s]

Epoch 7:  92%|█████████▏| 1830/2000 [01:38<00:09, 18.63it/s]

Epoch 7:  92%|█████████▏| 1832/2000 [01:38<00:09, 18.64it/s]

Epoch 7:  92%|█████████▏| 1834/2000 [01:38<00:08, 18.67it/s]

Epoch 7:  92%|█████████▏| 1836/2000 [01:38<00:08, 18.66it/s]

Epoch 7:  92%|█████████▏| 1838/2000 [01:38<00:08, 18.67it/s]

Epoch 7:  92%|█████████▏| 1840/2000 [01:38<00:08, 18.68it/s]

Epoch 7:  92%|█████████▏| 1842/2000 [01:38<00:08, 18.68it/s]

Epoch 7:  92%|█████████▏| 1844/2000 [01:38<00:08, 18.69it/s]

Epoch 7:  92%|█████████▏| 1846/2000 [01:38<00:08, 18.70it/s]

Epoch 7:  92%|█████████▏| 1848/2000 [01:39<00:08, 18.61it/s]

Epoch 7:  92%|█████████▎| 1850/2000 [01:39<00:08, 18.63it/s]

Epoch 7:  93%|█████████▎| 1852/2000 [01:39<00:07, 18.66it/s]

Epoch 7:  93%|█████████▎| 1854/2000 [01:39<00:07, 18.67it/s]

Epoch 7:  93%|█████████▎| 1856/2000 [01:39<00:07, 18.69it/s]

Epoch 7:  93%|█████████▎| 1858/2000 [01:39<00:07, 18.70it/s]

Epoch 7:  93%|█████████▎| 1860/2000 [01:39<00:07, 18.71it/s]

Epoch 7:  93%|█████████▎| 1862/2000 [01:39<00:07, 18.72it/s]

Epoch 7:  93%|█████████▎| 1864/2000 [01:39<00:07, 18.72it/s]

Epoch 7:  93%|█████████▎| 1866/2000 [01:40<00:07, 18.71it/s]

Epoch 7:  93%|█████████▎| 1868/2000 [01:40<00:07, 18.70it/s]

Epoch 7:  94%|█████████▎| 1870/2000 [01:40<00:06, 18.71it/s]

Epoch 7:  94%|█████████▎| 1872/2000 [01:40<00:06, 18.70it/s]

Epoch 7:  94%|█████████▎| 1874/2000 [01:40<00:06, 18.71it/s]

Epoch 7:  94%|█████████▍| 1876/2000 [01:40<00:06, 18.72it/s]

Epoch 7:  94%|█████████▍| 1878/2000 [01:40<00:06, 18.73it/s]

Epoch 7:  94%|█████████▍| 1880/2000 [01:40<00:06, 18.71it/s]

Epoch 7:  94%|█████████▍| 1882/2000 [01:40<00:06, 18.72it/s]

Epoch 7:  94%|█████████▍| 1884/2000 [01:41<00:06, 18.73it/s]

Epoch 7:  94%|█████████▍| 1886/2000 [01:41<00:06, 18.72it/s]

Epoch 7:  94%|█████████▍| 1888/2000 [01:41<00:05, 18.72it/s]

Epoch 7:  94%|█████████▍| 1890/2000 [01:41<00:05, 18.70it/s]

Epoch 7:  95%|█████████▍| 1892/2000 [01:41<00:05, 18.71it/s]

Epoch 7:  95%|█████████▍| 1894/2000 [01:41<00:05, 18.71it/s]

Epoch 7:  95%|█████████▍| 1896/2000 [01:41<00:05, 18.71it/s]

Epoch 7:  95%|█████████▍| 1898/2000 [01:41<00:05, 18.71it/s]

Epoch 7:  95%|█████████▌| 1900/2000 [01:41<00:05, 18.71it/s]

Epoch 7:  95%|█████████▌| 1902/2000 [01:41<00:05, 18.72it/s]

Epoch 7:  95%|█████████▌| 1904/2000 [01:42<00:05, 18.73it/s]

Epoch 7:  95%|█████████▌| 1906/2000 [01:42<00:05, 18.72it/s]

Epoch 7:  95%|█████████▌| 1908/2000 [01:42<00:04, 18.71it/s]

Epoch 7:  96%|█████████▌| 1910/2000 [01:42<00:04, 18.72it/s]

Epoch 7:  96%|█████████▌| 1912/2000 [01:42<00:04, 18.71it/s]

Epoch 7:  96%|█████████▌| 1914/2000 [01:42<00:04, 18.72it/s]

Epoch 7:  96%|█████████▌| 1916/2000 [01:42<00:04, 18.71it/s]

Epoch 7:  96%|█████████▌| 1918/2000 [01:42<00:04, 18.72it/s]

Epoch 7:  96%|█████████▌| 1920/2000 [01:42<00:04, 18.71it/s]

Epoch 7:  96%|█████████▌| 1922/2000 [01:43<00:04, 18.72it/s]

Epoch 7:  96%|█████████▌| 1924/2000 [01:43<00:04, 18.72it/s]

Epoch 7:  96%|█████████▋| 1926/2000 [01:43<00:03, 18.73it/s]

Epoch 7:  96%|█████████▋| 1928/2000 [01:43<00:03, 18.72it/s]

Epoch 7:  96%|█████████▋| 1930/2000 [01:43<00:03, 18.72it/s]

Epoch 7:  97%|█████████▋| 1932/2000 [01:43<00:03, 18.72it/s]

Epoch 7:  97%|█████████▋| 1934/2000 [01:43<00:03, 18.72it/s]

Epoch 7:  97%|█████████▋| 1936/2000 [01:43<00:03, 18.72it/s]

Epoch 7:  97%|█████████▋| 1938/2000 [01:43<00:03, 18.73it/s]

Epoch 7:  97%|█████████▋| 1940/2000 [01:43<00:03, 18.72it/s]

Epoch 7:  97%|█████████▋| 1942/2000 [01:44<00:03, 18.71it/s]

Epoch 7:  97%|█████████▋| 1944/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  97%|█████████▋| 1946/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  97%|█████████▋| 1948/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1950/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1952/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1954/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1956/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1958/2000 [01:44<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1960/2000 [01:45<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1962/2000 [01:45<00:02, 18.72it/s]

Epoch 7:  98%|█████████▊| 1964/2000 [01:45<00:01, 18.72it/s]

Epoch 7:  98%|█████████▊| 1966/2000 [01:45<00:01, 18.72it/s]

Epoch 7:  98%|█████████▊| 1968/2000 [01:45<00:01, 18.72it/s]

Epoch 7:  98%|█████████▊| 1970/2000 [01:45<00:01, 18.72it/s]

Epoch 7:  99%|█████████▊| 1972/2000 [01:45<00:01, 18.72it/s]

Epoch 7:  99%|█████████▊| 1974/2000 [01:45<00:01, 18.72it/s]

Epoch 7:  99%|█████████▉| 1976/2000 [01:45<00:01, 18.71it/s]

Epoch 7:  99%|█████████▉| 1978/2000 [01:46<00:01, 18.72it/s]

Epoch 7:  99%|█████████▉| 1980/2000 [01:46<00:01, 18.72it/s]

Epoch 7:  99%|█████████▉| 1982/2000 [01:46<00:00, 18.72it/s]

Epoch 7:  99%|█████████▉| 1984/2000 [01:46<00:00, 18.73it/s]

Epoch 7:  99%|█████████▉| 1986/2000 [01:46<00:00, 18.73it/s]

Epoch 7:  99%|█████████▉| 1988/2000 [01:46<00:00, 18.72it/s]

Epoch 7: 100%|█████████▉| 1990/2000 [01:46<00:00, 18.73it/s]

Epoch 7: 100%|█████████▉| 1992/2000 [01:46<00:00, 18.74it/s]

Epoch 7: 100%|█████████▉| 1994/2000 [01:46<00:00, 18.75it/s]

Epoch 7: 100%|█████████▉| 1996/2000 [01:46<00:00, 18.74it/s]

Epoch 7: 100%|█████████▉| 1998/2000 [01:47<00:00, 18.72it/s]

Epoch 7: 100%|██████████| 2000/2000 [01:47<00:00, 18.71it/s]

Epoch 7: loss=0.2004, val_proxy=0.9317

Epoch 8:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 8:   0%|          | 2/2000 [00:00<01:49, 18.18it/s]

Epoch 8:   0%|          | 4/2000 [00:00<01:48, 18.39it/s]

Epoch 8:   0%|          | 6/2000 [00:00<01:47, 18.47it/s]

Epoch 8:   0%|          | 8/2000 [00:00<01:47, 18.51it/s]

Epoch 8:   0%|          | 10/2000 [00:00<01:47, 18.52it/s]

Epoch 8:   1%|          | 12/2000 [00:00<01:47, 18.52it/s]

Epoch 8:   1%|          | 14/2000 [00:00<01:47, 18.52it/s]

Epoch 8:   1%|          | 16/2000 [00:00<01:47, 18.52it/s]

Epoch 8:   1%|          | 18/2000 [00:00<01:47, 18.51it/s]

Epoch 8:   1%|          | 20/2000 [00:01<01:46, 18.53it/s]

Epoch 8:   1%|          | 22/2000 [00:01<01:46, 18.56it/s]

Epoch 8:   1%|          | 24/2000 [00:01<01:46, 18.56it/s]

Epoch 8:   1%|▏         | 26/2000 [00:01<01:46, 18.58it/s]

Epoch 8:   1%|▏         | 28/2000 [00:01<01:46, 18.59it/s]

Epoch 8:   2%|▏         | 30/2000 [00:01<01:46, 18.57it/s]

Epoch 8:   2%|▏         | 32/2000 [00:01<01:45, 18.57it/s]

Epoch 8:   2%|▏         | 34/2000 [00:01<01:45, 18.57it/s]

Epoch 8:   2%|▏         | 36/2000 [00:01<01:45, 18.58it/s]

Epoch 8:   2%|▏         | 38/2000 [00:02<01:45, 18.57it/s]

Epoch 8:   2%|▏         | 40/2000 [00:02<01:46, 18.47it/s]

Epoch 8:   2%|▏         | 42/2000 [00:02<01:45, 18.49it/s]

Epoch 8:   2%|▏         | 44/2000 [00:02<01:45, 18.51it/s]

Epoch 8:   2%|▏         | 46/2000 [00:02<01:45, 18.54it/s]

Epoch 8:   2%|▏         | 48/2000 [00:02<01:45, 18.55it/s]

Epoch 8:   2%|▎         | 50/2000 [00:02<01:45, 18.56it/s]

Epoch 8:   3%|▎         | 52/2000 [00:02<01:44, 18.56it/s]

Epoch 8:   3%|▎         | 54/2000 [00:02<01:44, 18.55it/s]

Epoch 8:   3%|▎         | 56/2000 [00:03<01:44, 18.56it/s]

Epoch 8:   3%|▎         | 58/2000 [00:03<01:44, 18.57it/s]

Epoch 8:   3%|▎         | 60/2000 [00:03<01:44, 18.58it/s]

Epoch 8:   3%|▎         | 62/2000 [00:03<01:44, 18.58it/s]

Epoch 8:   3%|▎         | 64/2000 [00:03<01:44, 18.58it/s]

Epoch 8:   3%|▎         | 66/2000 [00:03<01:44, 18.57it/s]

Epoch 8:   3%|▎         | 68/2000 [00:03<01:44, 18.56it/s]

Epoch 8:   4%|▎         | 70/2000 [00:03<01:44, 18.53it/s]

Epoch 8:   4%|▎         | 72/2000 [00:03<01:44, 18.53it/s]

Epoch 8:   4%|▎         | 74/2000 [00:03<01:43, 18.55it/s]

Epoch 8:   4%|▍         | 76/2000 [00:04<01:43, 18.57it/s]

Epoch 8:   4%|▍         | 78/2000 [00:04<01:43, 18.57it/s]

Epoch 8:   4%|▍         | 80/2000 [00:04<01:43, 18.58it/s]

Epoch 8:   4%|▍         | 82/2000 [00:04<01:43, 18.58it/s]

Epoch 8:   4%|▍         | 84/2000 [00:04<01:43, 18.59it/s]

Epoch 8:   4%|▍         | 86/2000 [00:04<01:42, 18.59it/s]

Epoch 8:   4%|▍         | 88/2000 [00:04<01:42, 18.58it/s]

Epoch 8:   4%|▍         | 90/2000 [00:04<01:43, 18.44it/s]

Epoch 8:   5%|▍         | 92/2000 [00:04<01:43, 18.47it/s]

Epoch 8:   5%|▍         | 94/2000 [00:05<01:43, 18.49it/s]

Epoch 8:   5%|▍         | 96/2000 [00:05<01:42, 18.51it/s]

Epoch 8:   5%|▍         | 98/2000 [00:05<01:42, 18.53it/s]

Epoch 8:   5%|▌         | 100/2000 [00:05<01:42, 18.54it/s]

Epoch 8:   5%|▌         | 102/2000 [00:05<01:42, 18.55it/s]

Epoch 8:   5%|▌         | 104/2000 [00:05<01:42, 18.55it/s]

Epoch 8:   5%|▌         | 106/2000 [00:05<01:42, 18.56it/s]

Epoch 8:   5%|▌         | 108/2000 [00:05<01:41, 18.56it/s]

Epoch 8:   6%|▌         | 110/2000 [00:05<01:41, 18.56it/s]

Epoch 8:   6%|▌         | 112/2000 [00:06<01:42, 18.48it/s]

Epoch 8:   6%|▌         | 114/2000 [00:06<01:41, 18.50it/s]

Epoch 8:   6%|▌         | 116/2000 [00:06<01:41, 18.52it/s]

Epoch 8:   6%|▌         | 118/2000 [00:06<01:41, 18.53it/s]

Epoch 8:   6%|▌         | 120/2000 [00:06<01:41, 18.54it/s]

Epoch 8:   6%|▌         | 122/2000 [00:06<01:41, 18.56it/s]

Epoch 8:   6%|▌         | 124/2000 [00:06<01:40, 18.58it/s]

Epoch 8:   6%|▋         | 126/2000 [00:06<01:40, 18.58it/s]

Epoch 8:   6%|▋         | 128/2000 [00:06<01:40, 18.57it/s]

Epoch 8:   6%|▋         | 130/2000 [00:07<01:40, 18.57it/s]

Epoch 8:   7%|▋         | 132/2000 [00:07<01:41, 18.48it/s]

Epoch 8:   7%|▋         | 134/2000 [00:07<01:40, 18.51it/s]

Epoch 8:   7%|▋         | 136/2000 [00:07<01:40, 18.53it/s]

Epoch 8:   7%|▋         | 138/2000 [00:07<01:40, 18.54it/s]

Epoch 8:   7%|▋         | 140/2000 [00:07<01:40, 18.55it/s]

Epoch 8:   7%|▋         | 142/2000 [00:07<01:40, 18.54it/s]

Epoch 8:   7%|▋         | 144/2000 [00:07<01:40, 18.55it/s]

Epoch 8:   7%|▋         | 146/2000 [00:07<01:39, 18.55it/s]

Epoch 8:   7%|▋         | 148/2000 [00:07<01:39, 18.57it/s]

Epoch 8:   8%|▊         | 150/2000 [00:08<01:39, 18.56it/s]

Epoch 8:   8%|▊         | 152/2000 [00:08<01:39, 18.57it/s]

Epoch 8:   8%|▊         | 154/2000 [00:08<01:39, 18.57it/s]

Epoch 8:   8%|▊         | 156/2000 [00:08<01:39, 18.57it/s]

Epoch 8:   8%|▊         | 158/2000 [00:08<01:39, 18.50it/s]

Epoch 8:   8%|▊         | 160/2000 [00:08<01:39, 18.51it/s]

Epoch 8:   8%|▊         | 162/2000 [00:08<01:39, 18.54it/s]

Epoch 8:   8%|▊         | 164/2000 [00:08<01:39, 18.53it/s]

Epoch 8:   8%|▊         | 166/2000 [00:08<01:38, 18.54it/s]

Epoch 8:   8%|▊         | 168/2000 [00:09<01:38, 18.56it/s]

Epoch 8:   8%|▊         | 170/2000 [00:09<01:38, 18.55it/s]

Epoch 8:   9%|▊         | 172/2000 [00:09<01:38, 18.55it/s]

Epoch 8:   9%|▊         | 174/2000 [00:09<01:38, 18.56it/s]

Epoch 8:   9%|▉         | 176/2000 [00:09<01:38, 18.56it/s]

Epoch 8:   9%|▉         | 178/2000 [00:09<01:38, 18.57it/s]

Epoch 8:   9%|▉         | 180/2000 [00:09<01:37, 18.58it/s]

Epoch 8:   9%|▉         | 182/2000 [00:09<01:37, 18.58it/s]

Epoch 8:   9%|▉         | 184/2000 [00:09<01:37, 18.57it/s]

Epoch 8:   9%|▉         | 186/2000 [00:10<01:37, 18.57it/s]

Epoch 8:   9%|▉         | 188/2000 [00:10<01:37, 18.57it/s]

Epoch 8:  10%|▉         | 190/2000 [00:10<01:37, 18.57it/s]

Epoch 8:  10%|▉         | 192/2000 [00:10<01:37, 18.58it/s]

Epoch 8:  10%|▉         | 194/2000 [00:10<01:37, 18.57it/s]

Epoch 8:  10%|▉         | 196/2000 [00:10<01:37, 18.58it/s]

Epoch 8:  10%|▉         | 198/2000 [00:10<01:36, 18.58it/s]

Epoch 8:  10%|█         | 200/2000 [00:10<01:36, 18.58it/s]

Epoch 8:  10%|█         | 202/2000 [00:10<01:36, 18.58it/s]

Epoch 8:  10%|█         | 204/2000 [00:10<01:36, 18.57it/s]

Epoch 8:  10%|█         | 206/2000 [00:11<01:36, 18.57it/s]

Epoch 8:  10%|█         | 208/2000 [00:11<01:36, 18.57it/s]

Epoch 8:  10%|█         | 210/2000 [00:11<01:36, 18.56it/s]

Epoch 8:  11%|█         | 212/2000 [00:11<01:36, 18.56it/s]

Epoch 8:  11%|█         | 214/2000 [00:11<01:36, 18.56it/s]

Epoch 8:  11%|█         | 216/2000 [00:11<01:36, 18.55it/s]

Epoch 8:  11%|█         | 218/2000 [00:11<01:36, 18.56it/s]

Epoch 8:  11%|█         | 220/2000 [00:11<01:35, 18.56it/s]

Epoch 8:  11%|█         | 222/2000 [00:11<01:35, 18.57it/s]

Epoch 8:  11%|█         | 224/2000 [00:12<01:35, 18.58it/s]

Epoch 8:  11%|█▏        | 226/2000 [00:12<01:35, 18.59it/s]

Epoch 8:  11%|█▏        | 228/2000 [00:12<01:35, 18.57it/s]

Epoch 8:  12%|█▏        | 230/2000 [00:12<01:35, 18.57it/s]

Epoch 8:  12%|█▏        | 232/2000 [00:12<01:35, 18.57it/s]

Epoch 8:  12%|█▏        | 234/2000 [00:12<01:35, 18.58it/s]

Epoch 8:  12%|█▏        | 236/2000 [00:12<01:34, 18.57it/s]

Epoch 8:  12%|█▏        | 238/2000 [00:12<01:34, 18.58it/s]

Epoch 8:  12%|█▏        | 240/2000 [00:12<01:34, 18.57it/s]

Epoch 8:  12%|█▏        | 242/2000 [00:13<01:34, 18.58it/s]

Epoch 8:  12%|█▏        | 244/2000 [00:13<01:34, 18.59it/s]

Epoch 8:  12%|█▏        | 246/2000 [00:13<01:34, 18.59it/s]

Epoch 8:  12%|█▏        | 248/2000 [00:13<01:34, 18.59it/s]

Epoch 8:  12%|█▎        | 250/2000 [00:13<01:34, 18.58it/s]

Epoch 8:  13%|█▎        | 252/2000 [00:13<01:34, 18.58it/s]

Epoch 8:  13%|█▎        | 254/2000 [00:13<01:34, 18.57it/s]

Epoch 8:  13%|█▎        | 256/2000 [00:13<01:33, 18.58it/s]

Epoch 8:  13%|█▎        | 258/2000 [00:13<01:33, 18.60it/s]

Epoch 8:  13%|█▎        | 260/2000 [00:14<01:33, 18.59it/s]

Epoch 8:  13%|█▎        | 262/2000 [00:14<01:33, 18.58it/s]

Epoch 8:  13%|█▎        | 264/2000 [00:14<01:33, 18.57it/s]

Epoch 8:  13%|█▎        | 266/2000 [00:14<01:33, 18.57it/s]

Epoch 8:  13%|█▎        | 268/2000 [00:14<01:33, 18.58it/s]

Epoch 8:  14%|█▎        | 270/2000 [00:14<01:33, 18.58it/s]

Epoch 8:  14%|█▎        | 272/2000 [00:14<01:32, 18.58it/s]

Epoch 8:  14%|█▎        | 274/2000 [00:14<01:32, 18.58it/s]

Epoch 8:  14%|█▍        | 276/2000 [00:14<01:32, 18.58it/s]

Epoch 8:  14%|█▍        | 278/2000 [00:14<01:32, 18.58it/s]

Epoch 8:  14%|█▍        | 280/2000 [00:15<01:32, 18.58it/s]

Epoch 8:  14%|█▍        | 282/2000 [00:15<01:32, 18.59it/s]

Epoch 8:  14%|█▍        | 284/2000 [00:15<01:32, 18.59it/s]

Epoch 8:  14%|█▍        | 286/2000 [00:15<01:32, 18.57it/s]

Epoch 8:  14%|█▍        | 288/2000 [00:15<01:32, 18.57it/s]

Epoch 8:  14%|█▍        | 290/2000 [00:15<01:32, 18.58it/s]

Epoch 8:  15%|█▍        | 292/2000 [00:15<01:31, 18.58it/s]

Epoch 8:  15%|█▍        | 294/2000 [00:15<01:31, 18.58it/s]

Epoch 8:  15%|█▍        | 296/2000 [00:15<01:31, 18.59it/s]

Epoch 8:  15%|█▍        | 298/2000 [00:16<01:31, 18.57it/s]

Epoch 8:  15%|█▌        | 300/2000 [00:16<01:31, 18.59it/s]

Epoch 8:  15%|█▌        | 302/2000 [00:16<01:31, 18.57it/s]

Epoch 8:  15%|█▌        | 304/2000 [00:16<01:31, 18.56it/s]

Epoch 8:  15%|█▌        | 306/2000 [00:16<01:31, 18.56it/s]

Epoch 8:  15%|█▌        | 308/2000 [00:16<01:31, 18.56it/s]

Epoch 8:  16%|█▌        | 310/2000 [00:16<01:31, 18.57it/s]

Epoch 8:  16%|█▌        | 312/2000 [00:16<01:30, 18.56it/s]

Epoch 8:  16%|█▌        | 314/2000 [00:16<01:30, 18.56it/s]

Epoch 8:  16%|█▌        | 316/2000 [00:17<01:30, 18.54it/s]

Epoch 8:  16%|█▌        | 318/2000 [00:17<01:30, 18.50it/s]

Epoch 8:  16%|█▌        | 320/2000 [00:17<01:30, 18.49it/s]

Epoch 8:  16%|█▌        | 322/2000 [00:17<01:30, 18.51it/s]

Epoch 8:  16%|█▌        | 324/2000 [00:17<01:30, 18.53it/s]

Epoch 8:  16%|█▋        | 326/2000 [00:17<01:30, 18.55it/s]

Epoch 8:  16%|█▋        | 328/2000 [00:17<01:30, 18.55it/s]

Epoch 8:  16%|█▋        | 330/2000 [00:17<01:30, 18.55it/s]

Epoch 8:  17%|█▋        | 332/2000 [00:17<01:29, 18.55it/s]

Epoch 8:  17%|█▋        | 334/2000 [00:18<01:29, 18.56it/s]

Epoch 8:  17%|█▋        | 336/2000 [00:18<01:29, 18.55it/s]

Epoch 8:  17%|█▋        | 338/2000 [00:18<01:29, 18.56it/s]

Epoch 8:  17%|█▋        | 340/2000 [00:18<01:29, 18.57it/s]

Epoch 8:  17%|█▋        | 342/2000 [00:18<01:29, 18.57it/s]

Epoch 8:  17%|█▋        | 344/2000 [00:18<01:29, 18.56it/s]

Epoch 8:  17%|█▋        | 346/2000 [00:18<01:29, 18.57it/s]

Epoch 8:  17%|█▋        | 348/2000 [00:18<01:28, 18.57it/s]

Epoch 8:  18%|█▊        | 350/2000 [00:18<01:28, 18.56it/s]

Epoch 8:  18%|█▊        | 352/2000 [00:18<01:28, 18.58it/s]

Epoch 8:  18%|█▊        | 354/2000 [00:19<01:28, 18.58it/s]

Epoch 8:  18%|█▊        | 356/2000 [00:19<01:28, 18.57it/s]

Epoch 8:  18%|█▊        | 358/2000 [00:19<01:28, 18.57it/s]

Epoch 8:  18%|█▊        | 360/2000 [00:19<01:28, 18.57it/s]

Epoch 8:  18%|█▊        | 362/2000 [00:19<01:28, 18.57it/s]

Epoch 8:  18%|█▊        | 364/2000 [00:19<01:28, 18.58it/s]

Epoch 8:  18%|█▊        | 366/2000 [00:19<01:27, 18.58it/s]

Epoch 8:  18%|█▊        | 368/2000 [00:19<01:27, 18.57it/s]

Epoch 8:  18%|█▊        | 370/2000 [00:19<01:27, 18.56it/s]

Epoch 8:  19%|█▊        | 372/2000 [00:20<01:27, 18.57it/s]

Epoch 8:  19%|█▊        | 374/2000 [00:20<01:27, 18.56it/s]

Epoch 8:  19%|█▉        | 376/2000 [00:20<01:27, 18.55it/s]

Epoch 8:  19%|█▉        | 378/2000 [00:20<01:27, 18.57it/s]

Epoch 8:  19%|█▉        | 380/2000 [00:20<01:27, 18.56it/s]

Epoch 8:  19%|█▉        | 382/2000 [00:20<01:27, 18.56it/s]

Epoch 8:  19%|█▉        | 384/2000 [00:20<01:27, 18.55it/s]

Epoch 8:  19%|█▉        | 386/2000 [00:20<01:26, 18.56it/s]

Epoch 8:  19%|█▉        | 388/2000 [00:20<01:26, 18.55it/s]

Epoch 8:  20%|█▉        | 390/2000 [00:21<01:26, 18.57it/s]

Epoch 8:  20%|█▉        | 392/2000 [00:21<01:26, 18.57it/s]

Epoch 8:  20%|█▉        | 394/2000 [00:21<01:26, 18.59it/s]

Epoch 8:  20%|█▉        | 396/2000 [00:21<01:26, 18.58it/s]

Epoch 8:  20%|█▉        | 398/2000 [00:21<01:26, 18.57it/s]

Epoch 8:  20%|██        | 400/2000 [00:21<01:26, 18.57it/s]

Epoch 8:  20%|██        | 402/2000 [00:21<01:26, 18.58it/s]

Epoch 8:  20%|██        | 404/2000 [00:21<01:25, 18.59it/s]

Epoch 8:  20%|██        | 406/2000 [00:21<01:25, 18.59it/s]

Epoch 8:  20%|██        | 408/2000 [00:21<01:25, 18.58it/s]

Epoch 8:  20%|██        | 410/2000 [00:22<01:25, 18.57it/s]

Epoch 8:  21%|██        | 412/2000 [00:22<01:25, 18.57it/s]

Epoch 8:  21%|██        | 414/2000 [00:22<01:25, 18.57it/s]

Epoch 8:  21%|██        | 416/2000 [00:22<01:25, 18.58it/s]

Epoch 8:  21%|██        | 418/2000 [00:22<01:25, 18.57it/s]

Epoch 8:  21%|██        | 420/2000 [00:22<01:25, 18.57it/s]

Epoch 8:  21%|██        | 422/2000 [00:22<01:24, 18.58it/s]

Epoch 8:  21%|██        | 424/2000 [00:22<01:24, 18.59it/s]

Epoch 8:  21%|██▏       | 426/2000 [00:22<01:24, 18.59it/s]

Epoch 8:  21%|██▏       | 428/2000 [00:23<01:24, 18.58it/s]

Epoch 8:  22%|██▏       | 430/2000 [00:23<01:24, 18.59it/s]

Epoch 8:  22%|██▏       | 432/2000 [00:23<01:24, 18.58it/s]

Epoch 8:  22%|██▏       | 434/2000 [00:23<01:24, 18.58it/s]

Epoch 8:  22%|██▏       | 436/2000 [00:23<01:24, 18.58it/s]

Epoch 8:  22%|██▏       | 438/2000 [00:23<01:24, 18.59it/s]

Epoch 8:  22%|██▏       | 440/2000 [00:23<01:23, 18.59it/s]

Epoch 8:  22%|██▏       | 442/2000 [00:23<01:23, 18.60it/s]

Epoch 8:  22%|██▏       | 444/2000 [00:23<01:23, 18.58it/s]

Epoch 8:  22%|██▏       | 446/2000 [00:24<01:23, 18.58it/s]

Epoch 8:  22%|██▏       | 448/2000 [00:24<01:23, 18.57it/s]

Epoch 8:  22%|██▎       | 450/2000 [00:24<01:23, 18.58it/s]

Epoch 8:  23%|██▎       | 452/2000 [00:24<01:23, 18.58it/s]

Epoch 8:  23%|██▎       | 454/2000 [00:24<01:23, 18.58it/s]

Epoch 8:  23%|██▎       | 456/2000 [00:24<01:23, 18.58it/s]

Epoch 8:  23%|██▎       | 458/2000 [00:24<01:22, 18.59it/s]

Epoch 8:  23%|██▎       | 460/2000 [00:24<01:22, 18.59it/s]

Epoch 8:  23%|██▎       | 462/2000 [00:24<01:22, 18.59it/s]

Epoch 8:  23%|██▎       | 464/2000 [00:24<01:22, 18.57it/s]

Epoch 8:  23%|██▎       | 466/2000 [00:25<01:24, 18.10it/s]

Epoch 8:  23%|██▎       | 468/2000 [00:25<01:25, 17.86it/s]

Epoch 8:  24%|██▎       | 470/2000 [00:25<01:25, 17.91it/s]

Epoch 8:  24%|██▎       | 472/2000 [00:25<01:24, 18.07it/s]

Epoch 8:  24%|██▎       | 474/2000 [00:25<01:23, 18.18it/s]

Epoch 8:  24%|██▍       | 476/2000 [00:25<01:23, 18.31it/s]

Epoch 8:  24%|██▍       | 478/2000 [00:25<01:22, 18.38it/s]

Epoch 8:  24%|██▍       | 480/2000 [00:25<01:22, 18.42it/s]

Epoch 8:  24%|██▍       | 482/2000 [00:25<01:22, 18.46it/s]

Epoch 8:  24%|██▍       | 484/2000 [00:26<01:21, 18.49it/s]

Epoch 8:  24%|██▍       | 486/2000 [00:26<01:21, 18.53it/s]

Epoch 8:  24%|██▍       | 488/2000 [00:26<01:21, 18.54it/s]

Epoch 8:  24%|██▍       | 490/2000 [00:26<01:21, 18.56it/s]

Epoch 8:  25%|██▍       | 492/2000 [00:26<01:21, 18.56it/s]

Epoch 8:  25%|██▍       | 494/2000 [00:26<01:22, 18.36it/s]

Epoch 8:  25%|██▍       | 496/2000 [00:26<01:21, 18.40it/s]

Epoch 8:  25%|██▍       | 498/2000 [00:26<01:21, 18.45it/s]

Epoch 8:  25%|██▌       | 500/2000 [00:26<01:21, 18.49it/s]

Epoch 8:  25%|██▌       | 502/2000 [00:27<01:20, 18.51it/s]

Epoch 8:  25%|██▌       | 504/2000 [00:27<01:20, 18.53it/s]

Epoch 8:  25%|██▌       | 506/2000 [00:27<01:20, 18.55it/s]

Epoch 8:  25%|██▌       | 508/2000 [00:27<01:20, 18.57it/s]

Epoch 8:  26%|██▌       | 510/2000 [00:27<01:20, 18.57it/s]

Epoch 8:  26%|██▌       | 512/2000 [00:27<01:20, 18.58it/s]

Epoch 8:  26%|██▌       | 514/2000 [00:27<01:19, 18.59it/s]

Epoch 8:  26%|██▌       | 516/2000 [00:27<01:19, 18.59it/s]

Epoch 8:  26%|██▌       | 518/2000 [00:27<01:19, 18.59it/s]

Epoch 8:  26%|██▌       | 520/2000 [00:28<01:19, 18.58it/s]

Epoch 8:  26%|██▌       | 522/2000 [00:28<01:19, 18.57it/s]

Epoch 8:  26%|██▌       | 524/2000 [00:28<01:19, 18.59it/s]

Epoch 8:  26%|██▋       | 526/2000 [00:28<01:19, 18.59it/s]

Epoch 8:  26%|██▋       | 528/2000 [00:28<01:19, 18.59it/s]

Epoch 8:  26%|██▋       | 530/2000 [00:28<01:19, 18.59it/s]

Epoch 8:  27%|██▋       | 532/2000 [00:28<01:18, 18.60it/s]

Epoch 8:  27%|██▋       | 534/2000 [00:28<01:18, 18.60it/s]

Epoch 8:  27%|██▋       | 536/2000 [00:28<01:18, 18.60it/s]

Epoch 8:  27%|██▋       | 538/2000 [00:29<01:18, 18.60it/s]

Epoch 8:  27%|██▋       | 540/2000 [00:29<01:18, 18.61it/s]

Epoch 8:  27%|██▋       | 542/2000 [00:29<01:18, 18.61it/s]

Epoch 8:  27%|██▋       | 544/2000 [00:29<01:18, 18.60it/s]

Epoch 8:  27%|██▋       | 546/2000 [00:29<01:18, 18.59it/s]

Epoch 8:  27%|██▋       | 548/2000 [00:29<01:18, 18.60it/s]

Epoch 8:  28%|██▊       | 550/2000 [00:29<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 552/2000 [00:29<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 554/2000 [00:29<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 556/2000 [00:29<01:17, 18.58it/s]

Epoch 8:  28%|██▊       | 558/2000 [00:30<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 560/2000 [00:30<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 562/2000 [00:30<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 564/2000 [00:30<01:17, 18.59it/s]

Epoch 8:  28%|██▊       | 566/2000 [00:30<01:17, 18.58it/s]

Epoch 8:  28%|██▊       | 568/2000 [00:30<01:17, 18.58it/s]

Epoch 8:  28%|██▊       | 570/2000 [00:30<01:17, 18.57it/s]

Epoch 8:  29%|██▊       | 572/2000 [00:30<01:16, 18.56it/s]

Epoch 8:  29%|██▊       | 574/2000 [00:30<01:16, 18.57it/s]

Epoch 8:  29%|██▉       | 576/2000 [00:31<01:16, 18.56it/s]

Epoch 8:  29%|██▉       | 578/2000 [00:31<01:16, 18.58it/s]

Epoch 8:  29%|██▉       | 580/2000 [00:31<01:16, 18.59it/s]

Epoch 8:  29%|██▉       | 582/2000 [00:31<01:16, 18.56it/s]

Epoch 8:  29%|██▉       | 584/2000 [00:31<01:16, 18.57it/s]

Epoch 8:  29%|██▉       | 586/2000 [00:31<01:16, 18.56it/s]

Epoch 8:  29%|██▉       | 588/2000 [00:31<01:16, 18.56it/s]

Epoch 8:  30%|██▉       | 590/2000 [00:31<01:15, 18.57it/s]

Epoch 8:  30%|██▉       | 592/2000 [00:31<01:15, 18.55it/s]

Epoch 8:  30%|██▉       | 594/2000 [00:32<01:15, 18.54it/s]

Epoch 8:  30%|██▉       | 596/2000 [00:32<01:15, 18.55it/s]

Epoch 8:  30%|██▉       | 598/2000 [00:32<01:15, 18.56it/s]

Epoch 8:  30%|███       | 600/2000 [00:32<01:15, 18.57it/s]

Epoch 8:  30%|███       | 602/2000 [00:32<01:15, 18.58it/s]

Epoch 8:  30%|███       | 604/2000 [00:32<01:15, 18.58it/s]

Epoch 8:  30%|███       | 606/2000 [00:32<01:14, 18.61it/s]

Epoch 8:  30%|███       | 608/2000 [00:32<01:14, 18.58it/s]

Epoch 8:  30%|███       | 610/2000 [00:32<01:14, 18.57it/s]

Epoch 8:  31%|███       | 612/2000 [00:32<01:14, 18.58it/s]

Epoch 8:  31%|███       | 614/2000 [00:33<01:14, 18.57it/s]

Epoch 8:  31%|███       | 616/2000 [00:33<01:14, 18.57it/s]

Epoch 8:  31%|███       | 618/2000 [00:33<01:14, 18.58it/s]

Epoch 8:  31%|███       | 620/2000 [00:33<01:14, 18.58it/s]

Epoch 8:  31%|███       | 622/2000 [00:33<01:14, 18.60it/s]

Epoch 8:  31%|███       | 624/2000 [00:33<01:13, 18.60it/s]

Epoch 8:  31%|███▏      | 626/2000 [00:33<01:13, 18.60it/s]

Epoch 8:  31%|███▏      | 628/2000 [00:33<01:13, 18.59it/s]

Epoch 8:  32%|███▏      | 630/2000 [00:33<01:13, 18.60it/s]

Epoch 8:  32%|███▏      | 632/2000 [00:34<01:13, 18.60it/s]

Epoch 8:  32%|███▏      | 634/2000 [00:34<01:13, 18.58it/s]

Epoch 8:  32%|███▏      | 636/2000 [00:34<01:13, 18.57it/s]

Epoch 8:  32%|███▏      | 638/2000 [00:34<01:13, 18.56it/s]

Epoch 8:  32%|███▏      | 640/2000 [00:34<01:13, 18.58it/s]

Epoch 8:  32%|███▏      | 642/2000 [00:34<01:13, 18.59it/s]

Epoch 8:  32%|███▏      | 644/2000 [00:34<01:12, 18.59it/s]

Epoch 8:  32%|███▏      | 646/2000 [00:34<01:12, 18.59it/s]

Epoch 8:  32%|███▏      | 648/2000 [00:34<01:12, 18.59it/s]

Epoch 8:  32%|███▎      | 650/2000 [00:35<01:12, 18.59it/s]

Epoch 8:  33%|███▎      | 652/2000 [00:35<01:12, 18.59it/s]

Epoch 8:  33%|███▎      | 654/2000 [00:35<01:12, 18.59it/s]

Epoch 8:  33%|███▎      | 656/2000 [00:35<01:12, 18.60it/s]

Epoch 8:  33%|███▎      | 658/2000 [00:35<01:12, 18.59it/s]

Epoch 8:  33%|███▎      | 660/2000 [00:35<01:12, 18.58it/s]

Epoch 8:  33%|███▎      | 662/2000 [00:35<01:12, 18.57it/s]

Epoch 8:  33%|███▎      | 664/2000 [00:35<01:11, 18.57it/s]

Epoch 8:  33%|███▎      | 666/2000 [00:35<01:11, 18.59it/s]

Epoch 8:  33%|███▎      | 668/2000 [00:36<01:11, 18.51it/s]

Epoch 8:  34%|███▎      | 670/2000 [00:36<01:11, 18.52it/s]

Epoch 8:  34%|███▎      | 672/2000 [00:36<01:11, 18.54it/s]

Epoch 8:  34%|███▎      | 674/2000 [00:36<01:11, 18.56it/s]

Epoch 8:  34%|███▍      | 676/2000 [00:36<01:11, 18.57it/s]

Epoch 8:  34%|███▍      | 678/2000 [00:36<01:11, 18.59it/s]

Epoch 8:  34%|███▍      | 680/2000 [00:36<01:10, 18.60it/s]

Epoch 8:  34%|███▍      | 682/2000 [00:36<01:10, 18.59it/s]

Epoch 8:  34%|███▍      | 684/2000 [00:36<01:10, 18.59it/s]

Epoch 8:  34%|███▍      | 686/2000 [00:36<01:10, 18.58it/s]

Epoch 8:  34%|███▍      | 688/2000 [00:37<01:10, 18.57it/s]

Epoch 8:  34%|███▍      | 690/2000 [00:37<01:10, 18.57it/s]

Epoch 8:  35%|███▍      | 692/2000 [00:37<01:10, 18.59it/s]

Epoch 8:  35%|███▍      | 694/2000 [00:37<01:10, 18.60it/s]

Epoch 8:  35%|███▍      | 696/2000 [00:37<01:10, 18.61it/s]

Epoch 8:  35%|███▍      | 698/2000 [00:37<01:09, 18.60it/s]

Epoch 8:  35%|███▌      | 700/2000 [00:37<01:09, 18.60it/s]

Epoch 8:  35%|███▌      | 702/2000 [00:37<01:09, 18.60it/s]

Epoch 8:  35%|███▌      | 704/2000 [00:37<01:09, 18.60it/s]

Epoch 8:  35%|███▌      | 706/2000 [00:38<01:09, 18.60it/s]

Epoch 8:  35%|███▌      | 708/2000 [00:38<01:09, 18.60it/s]

Epoch 8:  36%|███▌      | 710/2000 [00:38<01:09, 18.59it/s]

Epoch 8:  36%|███▌      | 712/2000 [00:38<01:09, 18.60it/s]

Epoch 8:  36%|███▌      | 714/2000 [00:38<01:09, 18.59it/s]

Epoch 8:  36%|███▌      | 716/2000 [00:38<01:09, 18.60it/s]

Epoch 8:  36%|███▌      | 718/2000 [00:38<01:08, 18.60it/s]

Epoch 8:  36%|███▌      | 720/2000 [00:38<01:08, 18.60it/s]

Epoch 8:  36%|███▌      | 722/2000 [00:38<01:08, 18.59it/s]

Epoch 8:  36%|███▌      | 724/2000 [00:39<01:08, 18.60it/s]

Epoch 8:  36%|███▋      | 726/2000 [00:39<01:08, 18.61it/s]

Epoch 8:  36%|███▋      | 728/2000 [00:39<01:08, 18.60it/s]

Epoch 8:  36%|███▋      | 730/2000 [00:39<01:08, 18.60it/s]

Epoch 8:  37%|███▋      | 732/2000 [00:39<01:08, 18.59it/s]

Epoch 8:  37%|███▋      | 734/2000 [00:39<01:08, 18.60it/s]

Epoch 8:  37%|███▋      | 736/2000 [00:39<01:07, 18.61it/s]

Epoch 8:  37%|███▋      | 738/2000 [00:39<01:07, 18.60it/s]

Epoch 8:  37%|███▋      | 740/2000 [00:39<01:07, 18.58it/s]

Epoch 8:  37%|███▋      | 742/2000 [00:39<01:07, 18.57it/s]

Epoch 8:  37%|███▋      | 744/2000 [00:40<01:07, 18.58it/s]

Epoch 8:  37%|███▋      | 746/2000 [00:40<01:07, 18.59it/s]

Epoch 8:  37%|███▋      | 748/2000 [00:40<01:07, 18.57it/s]

Epoch 8:  38%|███▊      | 750/2000 [00:40<01:07, 18.56it/s]

Epoch 8:  38%|███▊      | 752/2000 [00:40<01:07, 18.58it/s]

Epoch 8:  38%|███▊      | 754/2000 [00:40<01:07, 18.58it/s]

Epoch 8:  38%|███▊      | 756/2000 [00:40<01:06, 18.58it/s]

Epoch 8:  38%|███▊      | 758/2000 [00:40<01:06, 18.59it/s]

Epoch 8:  38%|███▊      | 760/2000 [00:40<01:06, 18.59it/s]

Epoch 8:  38%|███▊      | 762/2000 [00:41<01:06, 18.59it/s]

Epoch 8:  38%|███▊      | 764/2000 [00:41<01:06, 18.58it/s]

Epoch 8:  38%|███▊      | 766/2000 [00:41<01:06, 18.59it/s]

Epoch 8:  38%|███▊      | 768/2000 [00:41<01:06, 18.58it/s]

Epoch 8:  38%|███▊      | 770/2000 [00:41<01:06, 18.58it/s]

Epoch 8:  39%|███▊      | 772/2000 [00:41<01:06, 18.59it/s]

Epoch 8:  39%|███▊      | 774/2000 [00:41<01:05, 18.60it/s]

Epoch 8:  39%|███▉      | 776/2000 [00:41<01:05, 18.60it/s]

Epoch 8:  39%|███▉      | 778/2000 [00:41<01:05, 18.60it/s]

Epoch 8:  39%|███▉      | 780/2000 [00:42<01:05, 18.59it/s]

Epoch 8:  39%|███▉      | 782/2000 [00:42<01:05, 18.58it/s]

Epoch 8:  39%|███▉      | 784/2000 [00:42<01:05, 18.59it/s]

Epoch 8:  39%|███▉      | 786/2000 [00:42<01:05, 18.59it/s]

Epoch 8:  39%|███▉      | 788/2000 [00:42<01:05, 18.59it/s]

Epoch 8:  40%|███▉      | 790/2000 [00:42<01:05, 18.59it/s]

Epoch 8:  40%|███▉      | 792/2000 [00:42<01:05, 18.58it/s]

Epoch 8:  40%|███▉      | 794/2000 [00:42<01:04, 18.58it/s]

Epoch 8:  40%|███▉      | 796/2000 [00:42<01:04, 18.58it/s]

Epoch 8:  40%|███▉      | 798/2000 [00:42<01:04, 18.58it/s]

Epoch 8:  40%|████      | 800/2000 [00:43<01:04, 18.58it/s]

Epoch 8:  40%|████      | 802/2000 [00:43<01:04, 18.58it/s]

Epoch 8:  40%|████      | 804/2000 [00:43<01:04, 18.58it/s]

Epoch 8:  40%|████      | 806/2000 [00:43<01:04, 18.57it/s]

Epoch 8:  40%|████      | 808/2000 [00:43<01:04, 18.57it/s]

Epoch 8:  40%|████      | 810/2000 [00:43<01:04, 18.57it/s]

Epoch 8:  41%|████      | 812/2000 [00:43<01:03, 18.57it/s]

Epoch 8:  41%|████      | 814/2000 [00:43<01:03, 18.55it/s]

Epoch 8:  41%|████      | 816/2000 [00:43<01:03, 18.55it/s]

Epoch 8:  41%|████      | 818/2000 [00:44<01:03, 18.54it/s]

Epoch 8:  41%|████      | 820/2000 [00:44<01:03, 18.52it/s]

Epoch 8:  41%|████      | 822/2000 [00:44<01:03, 18.53it/s]

Epoch 8:  41%|████      | 824/2000 [00:44<01:03, 18.51it/s]

Epoch 8:  41%|████▏     | 826/2000 [00:44<01:03, 18.51it/s]

Epoch 8:  41%|████▏     | 828/2000 [00:44<01:03, 18.52it/s]

Epoch 8:  42%|████▏     | 830/2000 [00:44<01:03, 18.53it/s]

Epoch 8:  42%|████▏     | 832/2000 [00:44<01:02, 18.55it/s]

Epoch 8:  42%|████▏     | 834/2000 [00:44<01:02, 18.55it/s]

Epoch 8:  42%|████▏     | 836/2000 [00:45<01:02, 18.53it/s]

Epoch 8:  42%|████▏     | 838/2000 [00:45<01:02, 18.55it/s]

Epoch 8:  42%|████▏     | 840/2000 [00:45<01:02, 18.54it/s]

Epoch 8:  42%|████▏     | 842/2000 [00:45<01:02, 18.54it/s]

Epoch 8:  42%|████▏     | 844/2000 [00:45<01:02, 18.56it/s]

Epoch 8:  42%|████▏     | 846/2000 [00:45<01:02, 18.57it/s]

Epoch 8:  42%|████▏     | 848/2000 [00:45<01:02, 18.56it/s]

Epoch 8:  42%|████▎     | 850/2000 [00:45<01:01, 18.56it/s]

Epoch 8:  43%|████▎     | 852/2000 [00:45<01:01, 18.56it/s]

Epoch 8:  43%|████▎     | 854/2000 [00:46<01:01, 18.56it/s]

Epoch 8:  43%|████▎     | 856/2000 [00:46<01:01, 18.57it/s]

Epoch 8:  43%|████▎     | 858/2000 [00:46<01:01, 18.58it/s]

Epoch 8:  43%|████▎     | 860/2000 [00:46<01:01, 18.58it/s]

Epoch 8:  43%|████▎     | 862/2000 [00:46<01:01, 18.58it/s]

Epoch 8:  43%|████▎     | 864/2000 [00:46<01:01, 18.59it/s]

Epoch 8:  43%|████▎     | 866/2000 [00:46<01:01, 18.58it/s]

Epoch 8:  43%|████▎     | 868/2000 [00:46<01:00, 18.58it/s]

Epoch 8:  44%|████▎     | 870/2000 [00:46<01:00, 18.57it/s]

Epoch 8:  44%|████▎     | 872/2000 [00:46<01:00, 18.56it/s]

Epoch 8:  44%|████▎     | 874/2000 [00:47<01:00, 18.56it/s]

Epoch 8:  44%|████▍     | 876/2000 [00:47<01:00, 18.57it/s]

Epoch 8:  44%|████▍     | 878/2000 [00:47<01:00, 18.57it/s]

Epoch 8:  44%|████▍     | 880/2000 [00:47<01:00, 18.57it/s]

Epoch 8:  44%|████▍     | 882/2000 [00:47<01:00, 18.58it/s]

Epoch 8:  44%|████▍     | 884/2000 [00:47<00:59, 18.60it/s]

Epoch 8:  44%|████▍     | 886/2000 [00:47<00:59, 18.59it/s]

Epoch 8:  44%|████▍     | 888/2000 [00:47<00:59, 18.57it/s]

Epoch 8:  44%|████▍     | 890/2000 [00:47<00:59, 18.57it/s]

Epoch 8:  45%|████▍     | 892/2000 [00:48<00:59, 18.57it/s]

Epoch 8:  45%|████▍     | 894/2000 [00:48<00:59, 18.57it/s]

Epoch 8:  45%|████▍     | 896/2000 [00:48<00:59, 18.58it/s]

Epoch 8:  45%|████▍     | 898/2000 [00:48<00:59, 18.57it/s]

Epoch 8:  45%|████▌     | 900/2000 [00:48<00:59, 18.58it/s]

Epoch 8:  45%|████▌     | 902/2000 [00:48<00:59, 18.57it/s]

Epoch 8:  45%|████▌     | 904/2000 [00:48<00:58, 18.59it/s]

Epoch 8:  45%|████▌     | 906/2000 [00:48<00:58, 18.59it/s]

Epoch 8:  45%|████▌     | 908/2000 [00:48<00:58, 18.60it/s]

Epoch 8:  46%|████▌     | 910/2000 [00:49<00:58, 18.59it/s]

Epoch 8:  46%|████▌     | 912/2000 [00:49<00:58, 18.59it/s]

Epoch 8:  46%|████▌     | 914/2000 [00:49<00:58, 18.59it/s]

Epoch 8:  46%|████▌     | 916/2000 [00:49<00:58, 18.58it/s]

Epoch 8:  46%|████▌     | 918/2000 [00:49<00:58, 18.59it/s]

Epoch 8:  46%|████▌     | 920/2000 [00:49<00:58, 18.60it/s]

Epoch 8:  46%|████▌     | 922/2000 [00:49<00:57, 18.59it/s]

Epoch 8:  46%|████▌     | 924/2000 [00:49<00:57, 18.59it/s]

Epoch 8:  46%|████▋     | 926/2000 [00:49<00:57, 18.58it/s]

Epoch 8:  46%|████▋     | 928/2000 [00:49<00:57, 18.58it/s]

Epoch 8:  46%|████▋     | 930/2000 [00:50<00:57, 18.58it/s]

Epoch 8:  47%|████▋     | 932/2000 [00:50<00:57, 18.60it/s]

Epoch 8:  47%|████▋     | 934/2000 [00:50<00:57, 18.60it/s]

Epoch 8:  47%|████▋     | 936/2000 [00:50<00:57, 18.60it/s]

Epoch 8:  47%|████▋     | 938/2000 [00:50<00:57, 18.59it/s]

Epoch 8:  47%|████▋     | 940/2000 [00:50<00:57, 18.58it/s]

Epoch 8:  47%|████▋     | 942/2000 [00:50<00:56, 18.59it/s]

Epoch 8:  47%|████▋     | 944/2000 [00:50<00:56, 18.59it/s]

Epoch 8:  47%|████▋     | 946/2000 [00:50<00:56, 18.60it/s]

Epoch 8:  47%|████▋     | 948/2000 [00:51<00:56, 18.59it/s]

Epoch 8:  48%|████▊     | 950/2000 [00:51<00:56, 18.57it/s]

Epoch 8:  48%|████▊     | 952/2000 [00:51<00:56, 18.58it/s]

Epoch 8:  48%|████▊     | 954/2000 [00:51<00:56, 18.59it/s]

Epoch 8:  48%|████▊     | 956/2000 [00:51<00:56, 18.60it/s]

Epoch 8:  48%|████▊     | 958/2000 [00:51<00:56, 18.61it/s]

Epoch 8:  48%|████▊     | 960/2000 [00:51<00:55, 18.60it/s]

Epoch 8:  48%|████▊     | 962/2000 [00:51<00:55, 18.59it/s]

Epoch 8:  48%|████▊     | 964/2000 [00:51<00:55, 18.60it/s]

Epoch 8:  48%|████▊     | 966/2000 [00:52<00:55, 18.60it/s]

Epoch 8:  48%|████▊     | 968/2000 [00:52<00:55, 18.60it/s]

Epoch 8:  48%|████▊     | 970/2000 [00:52<00:55, 18.59it/s]

Epoch 8:  49%|████▊     | 972/2000 [00:52<00:55, 18.58it/s]

Epoch 8:  49%|████▊     | 974/2000 [00:52<00:55, 18.59it/s]

Epoch 8:  49%|████▉     | 976/2000 [00:52<00:55, 18.59it/s]

Epoch 8:  49%|████▉     | 978/2000 [00:52<00:55, 18.57it/s]

Epoch 8:  49%|████▉     | 980/2000 [00:52<00:54, 18.57it/s]

Epoch 8:  49%|████▉     | 982/2000 [00:52<00:54, 18.56it/s]

Epoch 8:  49%|████▉     | 984/2000 [00:53<00:54, 18.57it/s]

Epoch 8:  49%|████▉     | 986/2000 [00:53<00:54, 18.58it/s]

Epoch 8:  49%|████▉     | 988/2000 [00:53<00:54, 18.59it/s]

Epoch 8:  50%|████▉     | 990/2000 [00:53<00:54, 18.60it/s]

Epoch 8:  50%|████▉     | 992/2000 [00:53<00:54, 18.60it/s]

Epoch 8:  50%|████▉     | 994/2000 [00:53<00:54, 18.60it/s]

Epoch 8:  50%|████▉     | 996/2000 [00:53<00:53, 18.59it/s]

Epoch 8:  50%|████▉     | 998/2000 [00:53<00:53, 18.59it/s]

Epoch 8:  50%|█████     | 1000/2000 [00:53<00:53, 18.59it/s]

Epoch 8:  50%|█████     | 1002/2000 [00:53<00:53, 18.59it/s]

Epoch 8:  50%|█████     | 1004/2000 [00:54<00:53, 18.59it/s]

Epoch 8:  50%|█████     | 1006/2000 [00:54<00:53, 18.57it/s]

Epoch 8:  50%|█████     | 1008/2000 [00:54<00:53, 18.58it/s]

Epoch 8:  50%|█████     | 1010/2000 [00:54<00:53, 18.58it/s]

Epoch 8:  51%|█████     | 1012/2000 [00:54<00:53, 18.59it/s]

Epoch 8:  51%|█████     | 1014/2000 [00:54<00:53, 18.60it/s]

Epoch 8:  51%|█████     | 1016/2000 [00:54<00:52, 18.60it/s]

Epoch 8:  51%|█████     | 1018/2000 [00:54<00:52, 18.59it/s]

Epoch 8:  51%|█████     | 1020/2000 [00:54<00:52, 18.59it/s]

Epoch 8:  51%|█████     | 1022/2000 [00:55<00:52, 18.59it/s]

Epoch 8:  51%|█████     | 1024/2000 [00:55<00:52, 18.59it/s]

Epoch 8:  51%|█████▏    | 1026/2000 [00:55<00:52, 18.59it/s]

Epoch 8:  51%|█████▏    | 1028/2000 [00:55<00:52, 18.58it/s]

Epoch 8:  52%|█████▏    | 1030/2000 [00:55<00:52, 18.58it/s]

Epoch 8:  52%|█████▏    | 1032/2000 [00:55<00:52, 18.59it/s]

Epoch 8:  52%|█████▏    | 1034/2000 [00:55<00:51, 18.59it/s]

Epoch 8:  52%|█████▏    | 1036/2000 [00:55<00:51, 18.59it/s]

Epoch 8:  52%|█████▏    | 1038/2000 [00:55<00:51, 18.57it/s]

Epoch 8:  52%|█████▏    | 1040/2000 [00:56<00:51, 18.56it/s]

Epoch 8:  52%|█████▏    | 1042/2000 [00:56<00:51, 18.56it/s]

Epoch 8:  52%|█████▏    | 1044/2000 [00:56<00:51, 18.56it/s]

Epoch 8:  52%|█████▏    | 1046/2000 [00:56<00:51, 18.58it/s]

Epoch 8:  52%|█████▏    | 1048/2000 [00:56<00:51, 18.59it/s]

Epoch 8:  52%|█████▎    | 1050/2000 [00:56<00:51, 18.59it/s]

Epoch 8:  53%|█████▎    | 1052/2000 [00:56<00:50, 18.59it/s]

Epoch 8:  53%|█████▎    | 1054/2000 [00:56<00:50, 18.60it/s]

Epoch 8:  53%|█████▎    | 1056/2000 [00:56<00:50, 18.60it/s]

Epoch 8:  53%|█████▎    | 1058/2000 [00:56<00:50, 18.58it/s]

Epoch 8:  53%|█████▎    | 1060/2000 [00:57<00:50, 18.58it/s]

Epoch 8:  53%|█████▎    | 1062/2000 [00:57<00:50, 18.59it/s]

Epoch 8:  53%|█████▎    | 1064/2000 [00:57<00:50, 18.60it/s]

Epoch 8:  53%|█████▎    | 1066/2000 [00:57<00:50, 18.62it/s]

Epoch 8:  53%|█████▎    | 1068/2000 [00:57<00:50, 18.60it/s]

Epoch 8:  54%|█████▎    | 1070/2000 [00:57<00:49, 18.61it/s]

Epoch 8:  54%|█████▎    | 1072/2000 [00:57<00:49, 18.58it/s]

Epoch 8:  54%|█████▎    | 1074/2000 [00:57<00:50, 18.30it/s]

Epoch 8:  54%|█████▍    | 1076/2000 [00:57<00:51, 17.83it/s]

Epoch 8:  54%|█████▍    | 1078/2000 [00:58<00:51, 17.86it/s]

Epoch 8:  54%|█████▍    | 1080/2000 [00:58<00:50, 18.04it/s]

Epoch 8:  54%|█████▍    | 1082/2000 [00:58<00:50, 18.16it/s]

Epoch 8:  54%|█████▍    | 1084/2000 [00:58<00:50, 18.26it/s]

Epoch 8:  54%|█████▍    | 1086/2000 [00:58<00:49, 18.34it/s]

Epoch 8:  54%|█████▍    | 1088/2000 [00:58<00:49, 18.41it/s]

Epoch 8:  55%|█████▍    | 1090/2000 [00:58<00:49, 18.46it/s]

Epoch 8:  55%|█████▍    | 1092/2000 [00:58<00:49, 18.50it/s]

Epoch 8:  55%|█████▍    | 1094/2000 [00:58<00:48, 18.52it/s]

Epoch 8:  55%|█████▍    | 1096/2000 [00:59<00:48, 18.55it/s]

Epoch 8:  55%|█████▍    | 1098/2000 [00:59<00:48, 18.56it/s]

Epoch 8:  55%|█████▌    | 1100/2000 [00:59<00:48, 18.56it/s]

Epoch 8:  55%|█████▌    | 1102/2000 [00:59<00:48, 18.58it/s]

Epoch 8:  55%|█████▌    | 1104/2000 [00:59<00:48, 18.58it/s]

Epoch 8:  55%|█████▌    | 1106/2000 [00:59<00:48, 18.59it/s]

Epoch 8:  55%|█████▌    | 1108/2000 [00:59<00:47, 18.59it/s]

Epoch 8:  56%|█████▌    | 1110/2000 [00:59<00:47, 18.60it/s]

Epoch 8:  56%|█████▌    | 1112/2000 [00:59<00:47, 18.59it/s]

Epoch 8:  56%|█████▌    | 1114/2000 [01:00<00:47, 18.59it/s]

Epoch 8:  56%|█████▌    | 1116/2000 [01:00<00:47, 18.59it/s]

Epoch 8:  56%|█████▌    | 1118/2000 [01:00<00:47, 18.59it/s]

Epoch 8:  56%|█████▌    | 1120/2000 [01:00<00:47, 18.59it/s]

Epoch 8:  56%|█████▌    | 1122/2000 [01:00<00:47, 18.60it/s]

Epoch 8:  56%|█████▌    | 1124/2000 [01:00<00:47, 18.60it/s]

Epoch 8:  56%|█████▋    | 1126/2000 [01:00<00:47, 18.60it/s]

Epoch 8:  56%|█████▋    | 1128/2000 [01:00<00:46, 18.59it/s]

Epoch 8:  56%|█████▋    | 1130/2000 [01:00<00:46, 18.59it/s]

Epoch 8:  57%|█████▋    | 1132/2000 [01:00<00:46, 18.58it/s]

Epoch 8:  57%|█████▋    | 1134/2000 [01:01<00:46, 18.57it/s]

Epoch 8:  57%|█████▋    | 1136/2000 [01:01<00:46, 18.57it/s]

Epoch 8:  57%|█████▋    | 1138/2000 [01:01<00:46, 18.57it/s]

Epoch 8:  57%|█████▋    | 1140/2000 [01:01<00:46, 18.56it/s]

Epoch 8:  57%|█████▋    | 1142/2000 [01:01<00:46, 18.56it/s]

Epoch 8:  57%|█████▋    | 1144/2000 [01:01<00:46, 18.57it/s]

Epoch 8:  57%|█████▋    | 1146/2000 [01:01<00:45, 18.58it/s]

Epoch 8:  57%|█████▋    | 1148/2000 [01:01<00:45, 18.58it/s]

Epoch 8:  57%|█████▊    | 1150/2000 [01:01<00:45, 18.57it/s]

Epoch 8:  58%|█████▊    | 1152/2000 [01:02<00:45, 18.59it/s]

Epoch 8:  58%|█████▊    | 1154/2000 [01:02<00:45, 18.56it/s]

Epoch 8:  58%|█████▊    | 1156/2000 [01:02<00:45, 18.56it/s]

Epoch 8:  58%|█████▊    | 1158/2000 [01:02<00:45, 18.58it/s]

Epoch 8:  58%|█████▊    | 1160/2000 [01:02<00:45, 18.57it/s]

Epoch 8:  58%|█████▊    | 1162/2000 [01:02<00:45, 18.56it/s]

Epoch 8:  58%|█████▊    | 1164/2000 [01:02<00:45, 18.54it/s]

Epoch 8:  58%|█████▊    | 1166/2000 [01:02<00:44, 18.55it/s]

Epoch 8:  58%|█████▊    | 1168/2000 [01:02<00:44, 18.56it/s]

Epoch 8:  58%|█████▊    | 1170/2000 [01:03<00:44, 18.57it/s]

Epoch 8:  59%|█████▊    | 1172/2000 [01:03<00:44, 18.53it/s]

Epoch 8:  59%|█████▊    | 1174/2000 [01:03<00:44, 18.55it/s]

Epoch 8:  59%|█████▉    | 1176/2000 [01:03<00:44, 18.54it/s]

Epoch 8:  59%|█████▉    | 1178/2000 [01:03<00:44, 18.55it/s]

Epoch 8:  59%|█████▉    | 1180/2000 [01:03<00:44, 18.54it/s]

Epoch 8:  59%|█████▉    | 1182/2000 [01:03<00:44, 18.54it/s]

Epoch 8:  59%|█████▉    | 1184/2000 [01:03<00:43, 18.56it/s]

Epoch 8:  59%|█████▉    | 1186/2000 [01:03<00:43, 18.55it/s]

Epoch 8:  59%|█████▉    | 1188/2000 [01:04<00:43, 18.55it/s]

Epoch 8:  60%|█████▉    | 1190/2000 [01:04<00:43, 18.55it/s]

Epoch 8:  60%|█████▉    | 1192/2000 [01:04<00:43, 18.56it/s]

Epoch 8:  60%|█████▉    | 1194/2000 [01:04<00:43, 18.57it/s]

Epoch 8:  60%|█████▉    | 1196/2000 [01:04<00:43, 18.57it/s]

Epoch 8:  60%|█████▉    | 1198/2000 [01:04<00:43, 18.56it/s]

Epoch 8:  60%|██████    | 1200/2000 [01:04<00:43, 18.56it/s]

Epoch 8:  60%|██████    | 1202/2000 [01:04<00:42, 18.58it/s]

Epoch 8:  60%|██████    | 1204/2000 [01:04<00:42, 18.58it/s]

Epoch 8:  60%|██████    | 1206/2000 [01:04<00:42, 18.57it/s]

Epoch 8:  60%|██████    | 1208/2000 [01:05<00:42, 18.57it/s]

Epoch 8:  60%|██████    | 1210/2000 [01:05<00:42, 18.57it/s]

Epoch 8:  61%|██████    | 1212/2000 [01:05<00:42, 18.58it/s]

Epoch 8:  61%|██████    | 1214/2000 [01:05<00:42, 18.59it/s]

Epoch 8:  61%|██████    | 1216/2000 [01:05<00:42, 18.58it/s]

Epoch 8:  61%|██████    | 1218/2000 [01:05<00:42, 18.57it/s]

Epoch 8:  61%|██████    | 1220/2000 [01:05<00:42, 18.56it/s]

Epoch 8:  61%|██████    | 1222/2000 [01:05<00:41, 18.56it/s]

Epoch 8:  61%|██████    | 1224/2000 [01:05<00:41, 18.56it/s]

Epoch 8:  61%|██████▏   | 1226/2000 [01:06<00:41, 18.57it/s]

Epoch 8:  61%|██████▏   | 1228/2000 [01:06<00:41, 18.56it/s]

Epoch 8:  62%|██████▏   | 1230/2000 [01:06<00:41, 18.57it/s]

Epoch 8:  62%|██████▏   | 1232/2000 [01:06<00:41, 18.58it/s]

Epoch 8:  62%|██████▏   | 1234/2000 [01:06<00:41, 18.58it/s]

Epoch 8:  62%|██████▏   | 1236/2000 [01:06<00:41, 18.58it/s]

Epoch 8:  62%|██████▏   | 1238/2000 [01:06<00:41, 18.58it/s]

Epoch 8:  62%|██████▏   | 1240/2000 [01:06<00:40, 18.60it/s]

Epoch 8:  62%|██████▏   | 1242/2000 [01:06<00:40, 18.59it/s]

Epoch 8:  62%|██████▏   | 1244/2000 [01:07<00:40, 18.57it/s]

Epoch 8:  62%|██████▏   | 1246/2000 [01:07<00:40, 18.58it/s]

Epoch 8:  62%|██████▏   | 1248/2000 [01:07<00:40, 18.57it/s]

Epoch 8:  62%|██████▎   | 1250/2000 [01:07<00:40, 18.58it/s]

Epoch 8:  63%|██████▎   | 1252/2000 [01:07<00:40, 18.58it/s]

Epoch 8:  63%|██████▎   | 1254/2000 [01:07<00:40, 18.59it/s]

Epoch 8:  63%|██████▎   | 1256/2000 [01:07<00:40, 18.58it/s]

Epoch 8:  63%|██████▎   | 1258/2000 [01:07<00:39, 18.58it/s]

Epoch 8:  63%|██████▎   | 1260/2000 [01:07<00:39, 18.57it/s]

Epoch 8:  63%|██████▎   | 1262/2000 [01:07<00:39, 18.59it/s]

Epoch 8:  63%|██████▎   | 1264/2000 [01:08<00:39, 18.60it/s]

Epoch 8:  63%|██████▎   | 1266/2000 [01:08<00:39, 18.60it/s]

Epoch 8:  63%|██████▎   | 1268/2000 [01:08<00:39, 18.59it/s]

Epoch 8:  64%|██████▎   | 1270/2000 [01:08<00:39, 18.60it/s]

Epoch 8:  64%|██████▎   | 1272/2000 [01:08<00:39, 18.62it/s]

Epoch 8:  64%|██████▎   | 1274/2000 [01:08<00:39, 18.61it/s]

Epoch 8:  64%|██████▍   | 1276/2000 [01:08<00:38, 18.60it/s]

Epoch 8:  64%|██████▍   | 1278/2000 [01:08<00:38, 18.61it/s]

Epoch 8:  64%|██████▍   | 1280/2000 [01:08<00:38, 18.60it/s]

Epoch 8:  64%|██████▍   | 1282/2000 [01:09<00:38, 18.59it/s]

Epoch 8:  64%|██████▍   | 1284/2000 [01:09<00:38, 18.58it/s]

Epoch 8:  64%|██████▍   | 1286/2000 [01:09<00:38, 18.57it/s]

Epoch 8:  64%|██████▍   | 1288/2000 [01:09<00:38, 18.56it/s]

Epoch 8:  64%|██████▍   | 1290/2000 [01:09<00:38, 18.57it/s]

Epoch 8:  65%|██████▍   | 1292/2000 [01:09<00:38, 18.57it/s]

Epoch 8:  65%|██████▍   | 1294/2000 [01:09<00:38, 18.57it/s]

Epoch 8:  65%|██████▍   | 1296/2000 [01:09<00:37, 18.57it/s]

Epoch 8:  65%|██████▍   | 1298/2000 [01:09<00:37, 18.58it/s]

Epoch 8:  65%|██████▌   | 1300/2000 [01:10<00:37, 18.59it/s]

Epoch 8:  65%|██████▌   | 1302/2000 [01:10<00:37, 18.60it/s]

Epoch 8:  65%|██████▌   | 1304/2000 [01:10<00:37, 18.60it/s]

Epoch 8:  65%|██████▌   | 1306/2000 [01:10<00:37, 18.59it/s]

Epoch 8:  65%|██████▌   | 1308/2000 [01:10<00:37, 18.59it/s]

Epoch 8:  66%|██████▌   | 1310/2000 [01:10<00:37, 18.56it/s]

Epoch 8:  66%|██████▌   | 1312/2000 [01:10<00:37, 18.57it/s]

Epoch 8:  66%|██████▌   | 1314/2000 [01:10<00:36, 18.57it/s]

Epoch 8:  66%|██████▌   | 1316/2000 [01:10<00:36, 18.57it/s]

Epoch 8:  66%|██████▌   | 1318/2000 [01:11<00:36, 18.57it/s]

Epoch 8:  66%|██████▌   | 1320/2000 [01:11<00:36, 18.57it/s]

Epoch 8:  66%|██████▌   | 1322/2000 [01:11<00:36, 18.55it/s]

Epoch 8:  66%|██████▌   | 1324/2000 [01:11<00:36, 18.57it/s]

Epoch 8:  66%|██████▋   | 1326/2000 [01:11<00:36, 18.56it/s]

Epoch 8:  66%|██████▋   | 1328/2000 [01:11<00:36, 18.57it/s]

Epoch 8:  66%|██████▋   | 1330/2000 [01:11<00:36, 18.58it/s]

Epoch 8:  67%|██████▋   | 1332/2000 [01:11<00:35, 18.59it/s]

Epoch 8:  67%|██████▋   | 1334/2000 [01:11<00:35, 18.58it/s]

Epoch 8:  67%|██████▋   | 1336/2000 [01:11<00:35, 18.58it/s]

Epoch 8:  67%|██████▋   | 1338/2000 [01:12<00:35, 18.60it/s]

Epoch 8:  67%|██████▋   | 1340/2000 [01:12<00:35, 18.54it/s]

Epoch 8:  67%|██████▋   | 1342/2000 [01:12<00:35, 18.54it/s]

Epoch 8:  67%|██████▋   | 1344/2000 [01:12<00:35, 18.56it/s]

Epoch 8:  67%|██████▋   | 1346/2000 [01:12<00:35, 18.55it/s]

Epoch 8:  67%|██████▋   | 1348/2000 [01:12<00:35, 18.57it/s]

Epoch 8:  68%|██████▊   | 1350/2000 [01:12<00:34, 18.58it/s]

Epoch 8:  68%|██████▊   | 1352/2000 [01:12<00:34, 18.59it/s]

Epoch 8:  68%|██████▊   | 1354/2000 [01:12<00:34, 18.59it/s]

Epoch 8:  68%|██████▊   | 1356/2000 [01:13<00:34, 18.59it/s]

Epoch 8:  68%|██████▊   | 1358/2000 [01:13<00:34, 18.60it/s]

Epoch 8:  68%|██████▊   | 1360/2000 [01:13<00:34, 18.59it/s]

Epoch 8:  68%|██████▊   | 1362/2000 [01:13<00:34, 18.59it/s]

Epoch 8:  68%|██████▊   | 1364/2000 [01:13<00:34, 18.60it/s]

Epoch 8:  68%|██████▊   | 1366/2000 [01:13<00:34, 18.60it/s]

Epoch 8:  68%|██████▊   | 1368/2000 [01:13<00:33, 18.61it/s]

Epoch 8:  68%|██████▊   | 1370/2000 [01:13<00:33, 18.60it/s]

Epoch 8:  69%|██████▊   | 1372/2000 [01:13<00:33, 18.59it/s]

Epoch 8:  69%|██████▊   | 1374/2000 [01:14<00:33, 18.59it/s]

Epoch 8:  69%|██████▉   | 1376/2000 [01:14<00:33, 18.58it/s]

Epoch 8:  69%|██████▉   | 1378/2000 [01:14<00:33, 18.59it/s]

Epoch 8:  69%|██████▉   | 1380/2000 [01:14<00:33, 18.57it/s]

Epoch 8:  69%|██████▉   | 1382/2000 [01:14<00:33, 18.57it/s]

Epoch 8:  69%|██████▉   | 1384/2000 [01:14<00:33, 18.57it/s]

Epoch 8:  69%|██████▉   | 1386/2000 [01:14<00:33, 18.56it/s]

Epoch 8:  69%|██████▉   | 1388/2000 [01:14<00:32, 18.57it/s]

Epoch 8:  70%|██████▉   | 1390/2000 [01:14<00:32, 18.59it/s]

Epoch 8:  70%|██████▉   | 1392/2000 [01:14<00:32, 18.58it/s]

Epoch 8:  70%|██████▉   | 1394/2000 [01:15<00:32, 18.58it/s]

Epoch 8:  70%|██████▉   | 1396/2000 [01:15<00:32, 18.58it/s]

Epoch 8:  70%|██████▉   | 1398/2000 [01:15<00:32, 18.57it/s]

Epoch 8:  70%|███████   | 1400/2000 [01:15<00:32, 18.56it/s]

Epoch 8:  70%|███████   | 1402/2000 [01:15<00:32, 18.57it/s]

Epoch 8:  70%|███████   | 1404/2000 [01:15<00:32, 18.57it/s]

Epoch 8:  70%|███████   | 1406/2000 [01:15<00:31, 18.57it/s]

Epoch 8:  70%|███████   | 1408/2000 [01:15<00:31, 18.57it/s]

Epoch 8:  70%|███████   | 1410/2000 [01:15<00:31, 18.57it/s]

Epoch 8:  71%|███████   | 1412/2000 [01:16<00:31, 18.57it/s]

Epoch 8:  71%|███████   | 1414/2000 [01:16<00:31, 18.57it/s]

Epoch 8:  71%|███████   | 1416/2000 [01:16<00:31, 18.57it/s]

Epoch 8:  71%|███████   | 1418/2000 [01:16<00:31, 18.58it/s]

Epoch 8:  71%|███████   | 1420/2000 [01:16<00:31, 18.58it/s]

Epoch 8:  71%|███████   | 1422/2000 [01:16<00:31, 18.36it/s]

Epoch 8:  71%|███████   | 1424/2000 [01:16<00:31, 18.43it/s]

Epoch 8:  71%|███████▏  | 1426/2000 [01:16<00:31, 18.48it/s]

Epoch 8:  71%|███████▏  | 1428/2000 [01:16<00:30, 18.51it/s]

Epoch 8:  72%|███████▏  | 1430/2000 [01:17<00:30, 18.54it/s]

Epoch 8:  72%|███████▏  | 1432/2000 [01:17<00:30, 18.57it/s]

Epoch 8:  72%|███████▏  | 1434/2000 [01:17<00:30, 18.58it/s]

Epoch 8:  72%|███████▏  | 1436/2000 [01:17<00:30, 18.60it/s]

Epoch 8:  72%|███████▏  | 1438/2000 [01:17<00:30, 18.61it/s]

Epoch 8:  72%|███████▏  | 1440/2000 [01:17<00:30, 18.61it/s]

Epoch 8:  72%|███████▏  | 1442/2000 [01:17<00:29, 18.61it/s]

Epoch 8:  72%|███████▏  | 1444/2000 [01:17<00:29, 18.63it/s]

Epoch 8:  72%|███████▏  | 1446/2000 [01:17<00:29, 18.62it/s]

Epoch 8:  72%|███████▏  | 1448/2000 [01:18<00:29, 18.62it/s]

Epoch 8:  72%|███████▎  | 1450/2000 [01:18<00:29, 18.61it/s]

Epoch 8:  73%|███████▎  | 1452/2000 [01:18<00:29, 18.61it/s]

Epoch 8:  73%|███████▎  | 1454/2000 [01:18<00:29, 18.59it/s]

Epoch 8:  73%|███████▎  | 1456/2000 [01:18<00:29, 18.60it/s]

Epoch 8:  73%|███████▎  | 1458/2000 [01:18<00:29, 18.60it/s]

Epoch 8:  73%|███████▎  | 1460/2000 [01:18<00:29, 18.59it/s]

Epoch 8:  73%|███████▎  | 1462/2000 [01:18<00:28, 18.60it/s]

Epoch 8:  73%|███████▎  | 1464/2000 [01:18<00:28, 18.60it/s]

Epoch 8:  73%|███████▎  | 1466/2000 [01:18<00:28, 18.60it/s]

Epoch 8:  73%|███████▎  | 1468/2000 [01:19<00:28, 18.62it/s]

Epoch 8:  74%|███████▎  | 1470/2000 [01:19<00:28, 18.62it/s]

Epoch 8:  74%|███████▎  | 1472/2000 [01:19<00:28, 18.61it/s]

Epoch 8:  74%|███████▎  | 1474/2000 [01:19<00:28, 18.61it/s]

Epoch 8:  74%|███████▍  | 1476/2000 [01:19<00:28, 18.62it/s]

Epoch 8:  74%|███████▍  | 1478/2000 [01:19<00:28, 18.61it/s]

Epoch 8:  74%|███████▍  | 1480/2000 [01:19<00:27, 18.62it/s]

Epoch 8:  74%|███████▍  | 1482/2000 [01:19<00:27, 18.62it/s]

Epoch 8:  74%|███████▍  | 1484/2000 [01:19<00:27, 18.62it/s]

Epoch 8:  74%|███████▍  | 1486/2000 [01:20<00:27, 18.62it/s]

Epoch 8:  74%|███████▍  | 1488/2000 [01:20<00:27, 18.61it/s]

Epoch 8:  74%|███████▍  | 1490/2000 [01:20<00:27, 18.61it/s]

Epoch 8:  75%|███████▍  | 1492/2000 [01:20<00:27, 18.61it/s]

Epoch 8:  75%|███████▍  | 1494/2000 [01:20<00:27, 18.62it/s]

Epoch 8:  75%|███████▍  | 1496/2000 [01:20<00:27, 18.62it/s]

Epoch 8:  75%|███████▍  | 1498/2000 [01:20<00:26, 18.62it/s]

Epoch 8:  75%|███████▌  | 1500/2000 [01:20<00:26, 18.63it/s]

Epoch 8:  75%|███████▌  | 1502/2000 [01:20<00:26, 18.63it/s]

Epoch 8:  75%|███████▌  | 1504/2000 [01:21<00:26, 18.64it/s]

Epoch 8:  75%|███████▌  | 1506/2000 [01:21<00:26, 18.63it/s]

Epoch 8:  75%|███████▌  | 1508/2000 [01:21<00:26, 18.64it/s]

Epoch 8:  76%|███████▌  | 1510/2000 [01:21<00:26, 18.63it/s]

Epoch 8:  76%|███████▌  | 1512/2000 [01:21<00:26, 18.63it/s]

Epoch 8:  76%|███████▌  | 1514/2000 [01:21<00:26, 18.63it/s]

Epoch 8:  76%|███████▌  | 1516/2000 [01:21<00:25, 18.64it/s]

Epoch 8:  76%|███████▌  | 1518/2000 [01:21<00:25, 18.64it/s]

Epoch 8:  76%|███████▌  | 1520/2000 [01:21<00:25, 18.64it/s]

Epoch 8:  76%|███████▌  | 1522/2000 [01:21<00:25, 18.64it/s]

Epoch 8:  76%|███████▌  | 1524/2000 [01:22<00:25, 18.61it/s]

Epoch 8:  76%|███████▋  | 1526/2000 [01:22<00:25, 18.61it/s]

Epoch 8:  76%|███████▋  | 1528/2000 [01:22<00:25, 18.59it/s]

Epoch 8:  76%|███████▋  | 1530/2000 [01:22<00:25, 18.58it/s]

Epoch 8:  77%|███████▋  | 1532/2000 [01:22<00:25, 18.59it/s]

Epoch 8:  77%|███████▋  | 1534/2000 [01:22<00:25, 18.58it/s]

Epoch 8:  77%|███████▋  | 1536/2000 [01:22<00:24, 18.57it/s]

Epoch 8:  77%|███████▋  | 1538/2000 [01:22<00:24, 18.56it/s]

Epoch 8:  77%|███████▋  | 1540/2000 [01:22<00:24, 18.55it/s]

Epoch 8:  77%|███████▋  | 1542/2000 [01:23<00:24, 18.54it/s]

Epoch 8:  77%|███████▋  | 1544/2000 [01:23<00:24, 18.54it/s]

Epoch 8:  77%|███████▋  | 1546/2000 [01:23<00:24, 18.56it/s]

Epoch 8:  77%|███████▋  | 1548/2000 [01:23<00:24, 18.56it/s]

Epoch 8:  78%|███████▊  | 1550/2000 [01:23<00:24, 18.56it/s]

Epoch 8:  78%|███████▊  | 1552/2000 [01:23<00:24, 18.56it/s]

Epoch 8:  78%|███████▊  | 1554/2000 [01:23<00:24, 18.54it/s]

Epoch 8:  78%|███████▊  | 1556/2000 [01:23<00:23, 18.56it/s]

Epoch 8:  78%|███████▊  | 1558/2000 [01:23<00:23, 18.56it/s]

Epoch 8:  78%|███████▊  | 1560/2000 [01:24<00:23, 18.54it/s]

Epoch 8:  78%|███████▊  | 1562/2000 [01:24<00:23, 18.53it/s]

Epoch 8:  78%|███████▊  | 1564/2000 [01:24<00:23, 18.54it/s]

Epoch 8:  78%|███████▊  | 1566/2000 [01:24<00:23, 18.53it/s]

Epoch 8:  78%|███████▊  | 1568/2000 [01:24<00:23, 18.55it/s]

Epoch 8:  78%|███████▊  | 1570/2000 [01:24<00:23, 18.54it/s]

Epoch 8:  79%|███████▊  | 1572/2000 [01:24<00:23, 18.55it/s]

Epoch 8:  79%|███████▊  | 1574/2000 [01:24<00:22, 18.54it/s]

Epoch 8:  79%|███████▉  | 1576/2000 [01:24<00:22, 18.56it/s]

Epoch 8:  79%|███████▉  | 1578/2000 [01:25<00:22, 18.57it/s]

Epoch 8:  79%|███████▉  | 1580/2000 [01:25<00:22, 18.57it/s]

Epoch 8:  79%|███████▉  | 1582/2000 [01:25<00:22, 18.57it/s]

Epoch 8:  79%|███████▉  | 1584/2000 [01:25<00:22, 18.59it/s]

Epoch 8:  79%|███████▉  | 1586/2000 [01:25<00:22, 18.59it/s]

Epoch 8:  79%|███████▉  | 1588/2000 [01:25<00:22, 18.56it/s]

Epoch 8:  80%|███████▉  | 1590/2000 [01:25<00:22, 18.57it/s]

Epoch 8:  80%|███████▉  | 1592/2000 [01:25<00:21, 18.56it/s]

Epoch 8:  80%|███████▉  | 1594/2000 [01:25<00:21, 18.56it/s]

Epoch 8:  80%|███████▉  | 1596/2000 [01:25<00:21, 18.56it/s]

Epoch 8:  80%|███████▉  | 1598/2000 [01:26<00:21, 18.57it/s]

Epoch 8:  80%|████████  | 1600/2000 [01:26<00:21, 18.56it/s]

Epoch 8:  80%|████████  | 1602/2000 [01:26<00:21, 18.54it/s]

Epoch 8:  80%|████████  | 1604/2000 [01:26<00:21, 18.55it/s]

Epoch 8:  80%|████████  | 1606/2000 [01:26<00:21, 18.55it/s]

Epoch 8:  80%|████████  | 1608/2000 [01:26<00:21, 18.55it/s]

Epoch 8:  80%|████████  | 1610/2000 [01:26<00:21, 18.55it/s]

Epoch 8:  81%|████████  | 1612/2000 [01:26<00:20, 18.56it/s]

Epoch 8:  81%|████████  | 1614/2000 [01:26<00:20, 18.57it/s]

Epoch 8:  81%|████████  | 1616/2000 [01:27<00:20, 18.56it/s]

Epoch 8:  81%|████████  | 1618/2000 [01:27<00:20, 18.56it/s]

Epoch 8:  81%|████████  | 1620/2000 [01:27<00:20, 18.57it/s]

Epoch 8:  81%|████████  | 1622/2000 [01:27<00:20, 18.56it/s]

Epoch 8:  81%|████████  | 1624/2000 [01:27<00:20, 18.56it/s]

Epoch 8:  81%|████████▏ | 1626/2000 [01:27<00:20, 18.55it/s]

Epoch 8:  81%|████████▏ | 1628/2000 [01:27<00:20, 18.56it/s]

Epoch 8:  82%|████████▏ | 1630/2000 [01:27<00:19, 18.57it/s]

Epoch 8:  82%|████████▏ | 1632/2000 [01:27<00:19, 18.57it/s]

Epoch 8:  82%|████████▏ | 1634/2000 [01:28<00:19, 18.56it/s]

Epoch 8:  82%|████████▏ | 1636/2000 [01:28<00:19, 18.56it/s]

Epoch 8:  82%|████████▏ | 1638/2000 [01:28<00:19, 18.57it/s]

Epoch 8:  82%|████████▏ | 1640/2000 [01:28<00:19, 18.56it/s]

Epoch 8:  82%|████████▏ | 1642/2000 [01:28<00:19, 18.56it/s]

Epoch 8:  82%|████████▏ | 1644/2000 [01:28<00:19, 18.56it/s]

Epoch 8:  82%|████████▏ | 1646/2000 [01:28<00:19, 18.57it/s]

Epoch 8:  82%|████████▏ | 1648/2000 [01:28<00:18, 18.55it/s]

Epoch 8:  82%|████████▎ | 1650/2000 [01:28<00:18, 18.55it/s]

Epoch 8:  83%|████████▎ | 1652/2000 [01:28<00:18, 18.55it/s]

Epoch 8:  83%|████████▎ | 1654/2000 [01:29<00:18, 18.55it/s]

Epoch 8:  83%|████████▎ | 1656/2000 [01:29<00:18, 18.57it/s]

Epoch 8:  83%|████████▎ | 1658/2000 [01:29<00:18, 18.56it/s]

Epoch 8:  83%|████████▎ | 1660/2000 [01:29<00:18, 18.56it/s]

Epoch 8:  83%|████████▎ | 1662/2000 [01:29<00:18, 18.57it/s]

Epoch 8:  83%|████████▎ | 1664/2000 [01:29<00:18, 18.56it/s]

Epoch 8:  83%|████████▎ | 1666/2000 [01:29<00:17, 18.56it/s]

Epoch 8:  83%|████████▎ | 1668/2000 [01:29<00:17, 18.55it/s]

Epoch 8:  84%|████████▎ | 1670/2000 [01:29<00:17, 18.55it/s]

Epoch 8:  84%|████████▎ | 1672/2000 [01:30<00:17, 18.55it/s]

Epoch 8:  84%|████████▎ | 1674/2000 [01:30<00:17, 18.56it/s]

Epoch 8:  84%|████████▍ | 1676/2000 [01:30<00:17, 18.55it/s]

Epoch 8:  84%|████████▍ | 1678/2000 [01:30<00:17, 18.55it/s]

Epoch 8:  84%|████████▍ | 1680/2000 [01:30<00:17, 18.53it/s]

Epoch 8:  84%|████████▍ | 1682/2000 [01:30<00:17, 18.35it/s]

Epoch 8:  84%|████████▍ | 1684/2000 [01:30<00:17, 17.84it/s]

Epoch 8:  84%|████████▍ | 1686/2000 [01:30<00:17, 17.87it/s]

Epoch 8:  84%|████████▍ | 1688/2000 [01:30<00:17, 17.90it/s]

Epoch 8:  84%|████████▍ | 1690/2000 [01:31<00:17, 18.06it/s]

Epoch 8:  85%|████████▍ | 1692/2000 [01:31<00:16, 18.16it/s]

Epoch 8:  85%|████████▍ | 1694/2000 [01:31<00:16, 18.27it/s]

Epoch 8:  85%|████████▍ | 1696/2000 [01:31<00:16, 18.36it/s]

Epoch 8:  85%|████████▍ | 1698/2000 [01:31<00:16, 18.42it/s]

Epoch 8:  85%|████████▌ | 1700/2000 [01:31<00:16, 18.46it/s]

Epoch 8:  85%|████████▌ | 1702/2000 [01:31<00:16, 18.49it/s]

Epoch 8:  85%|████████▌ | 1704/2000 [01:31<00:15, 18.52it/s]

Epoch 8:  85%|████████▌ | 1706/2000 [01:31<00:15, 18.53it/s]

Epoch 8:  85%|████████▌ | 1708/2000 [01:32<00:15, 18.54it/s]

Epoch 8:  86%|████████▌ | 1710/2000 [01:32<00:15, 18.53it/s]

Epoch 8:  86%|████████▌ | 1712/2000 [01:32<00:15, 18.55it/s]

Epoch 8:  86%|████████▌ | 1714/2000 [01:32<00:15, 18.55it/s]

Epoch 8:  86%|████████▌ | 1716/2000 [01:32<00:15, 18.56it/s]

Epoch 8:  86%|████████▌ | 1718/2000 [01:32<00:15, 18.54it/s]

Epoch 8:  86%|████████▌ | 1720/2000 [01:32<00:15, 18.55it/s]

Epoch 8:  86%|████████▌ | 1722/2000 [01:32<00:14, 18.54it/s]

Epoch 8:  86%|████████▌ | 1724/2000 [01:32<00:14, 18.54it/s]

Epoch 8:  86%|████████▋ | 1726/2000 [01:33<00:14, 18.55it/s]

Epoch 8:  86%|████████▋ | 1728/2000 [01:33<00:14, 18.55it/s]

Epoch 8:  86%|████████▋ | 1730/2000 [01:33<00:14, 18.53it/s]

Epoch 8:  87%|████████▋ | 1732/2000 [01:33<00:14, 18.54it/s]

Epoch 8:  87%|████████▋ | 1734/2000 [01:33<00:14, 18.54it/s]

Epoch 8:  87%|████████▋ | 1736/2000 [01:33<00:14, 18.53it/s]

Epoch 8:  87%|████████▋ | 1738/2000 [01:33<00:14, 18.53it/s]

Epoch 8:  87%|████████▋ | 1740/2000 [01:33<00:14, 18.54it/s]

Epoch 8:  87%|████████▋ | 1742/2000 [01:33<00:13, 18.53it/s]

Epoch 8:  87%|████████▋ | 1744/2000 [01:33<00:13, 18.52it/s]

Epoch 8:  87%|████████▋ | 1746/2000 [01:34<00:13, 18.52it/s]

Epoch 8:  87%|████████▋ | 1748/2000 [01:34<00:13, 18.52it/s]

Epoch 8:  88%|████████▊ | 1750/2000 [01:34<00:13, 18.54it/s]

Epoch 8:  88%|████████▊ | 1752/2000 [01:34<00:13, 18.55it/s]

Epoch 8:  88%|████████▊ | 1754/2000 [01:34<00:13, 18.58it/s]

Epoch 8:  88%|████████▊ | 1756/2000 [01:34<00:13, 18.59it/s]

Epoch 8:  88%|████████▊ | 1758/2000 [01:34<00:13, 18.61it/s]

Epoch 8:  88%|████████▊ | 1760/2000 [01:34<00:12, 18.62it/s]

Epoch 8:  88%|████████▊ | 1762/2000 [01:34<00:12, 18.60it/s]

Epoch 8:  88%|████████▊ | 1764/2000 [01:35<00:12, 18.58it/s]

Epoch 8:  88%|████████▊ | 1766/2000 [01:35<00:12, 18.56it/s]

Epoch 8:  88%|████████▊ | 1768/2000 [01:35<00:12, 18.57it/s]

Epoch 8:  88%|████████▊ | 1770/2000 [01:35<00:12, 18.57it/s]

Epoch 8:  89%|████████▊ | 1772/2000 [01:35<00:12, 18.56it/s]

Epoch 8:  89%|████████▊ | 1774/2000 [01:35<00:12, 18.55it/s]

Epoch 8:  89%|████████▉ | 1776/2000 [01:35<00:12, 18.55it/s]

Epoch 8:  89%|████████▉ | 1778/2000 [01:35<00:11, 18.55it/s]

Epoch 8:  89%|████████▉ | 1780/2000 [01:35<00:11, 18.53it/s]

Epoch 8:  89%|████████▉ | 1782/2000 [01:36<00:11, 18.55it/s]

Epoch 8:  89%|████████▉ | 1784/2000 [01:36<00:11, 18.57it/s]

Epoch 8:  89%|████████▉ | 1786/2000 [01:36<00:11, 18.57it/s]

Epoch 8:  89%|████████▉ | 1788/2000 [01:36<00:11, 18.56it/s]

Epoch 8:  90%|████████▉ | 1790/2000 [01:36<00:11, 18.58it/s]

Epoch 8:  90%|████████▉ | 1792/2000 [01:36<00:11, 18.59it/s]

Epoch 8:  90%|████████▉ | 1794/2000 [01:36<00:11, 18.58it/s]

Epoch 8:  90%|████████▉ | 1796/2000 [01:36<00:10, 18.55it/s]

Epoch 8:  90%|████████▉ | 1798/2000 [01:36<00:10, 18.52it/s]

Epoch 8:  90%|█████████ | 1800/2000 [01:36<00:10, 18.49it/s]

Epoch 8:  90%|█████████ | 1802/2000 [01:37<00:10, 18.49it/s]

Epoch 8:  90%|█████████ | 1804/2000 [01:37<00:10, 18.47it/s]

Epoch 8:  90%|█████████ | 1806/2000 [01:37<00:10, 18.47it/s]

Epoch 8:  90%|█████████ | 1808/2000 [01:37<00:10, 18.48it/s]

Epoch 8:  90%|█████████ | 1810/2000 [01:37<00:10, 18.49it/s]

Epoch 8:  91%|█████████ | 1812/2000 [01:37<00:10, 18.47it/s]

Epoch 8:  91%|█████████ | 1814/2000 [01:37<00:10, 18.46it/s]

Epoch 8:  91%|█████████ | 1816/2000 [01:37<00:09, 18.47it/s]

Epoch 8:  91%|█████████ | 1818/2000 [01:37<00:09, 18.47it/s]

Epoch 8:  91%|█████████ | 1820/2000 [01:38<00:09, 18.46it/s]

Epoch 8:  91%|█████████ | 1822/2000 [01:38<00:09, 18.47it/s]

Epoch 8:  91%|█████████ | 1824/2000 [01:38<00:09, 18.46it/s]

Epoch 8:  91%|█████████▏| 1826/2000 [01:38<00:09, 18.46it/s]

Epoch 8:  91%|█████████▏| 1828/2000 [01:38<00:09, 18.47it/s]

Epoch 8:  92%|█████████▏| 1830/2000 [01:38<00:09, 18.46it/s]

Epoch 8:  92%|█████████▏| 1832/2000 [01:38<00:09, 18.45it/s]

Epoch 8:  92%|█████████▏| 1834/2000 [01:38<00:08, 18.46it/s]

Epoch 8:  92%|█████████▏| 1836/2000 [01:38<00:08, 18.45it/s]

Epoch 8:  92%|█████████▏| 1838/2000 [01:39<00:08, 18.45it/s]

Epoch 8:  92%|█████████▏| 1840/2000 [01:39<00:08, 18.45it/s]

Epoch 8:  92%|█████████▏| 1842/2000 [01:39<00:08, 18.44it/s]

Epoch 8:  92%|█████████▏| 1844/2000 [01:39<00:08, 18.45it/s]

Epoch 8:  92%|█████████▏| 1846/2000 [01:39<00:08, 18.46it/s]

Epoch 8:  92%|█████████▏| 1848/2000 [01:39<00:08, 18.45it/s]

Epoch 8:  92%|█████████▎| 1850/2000 [01:39<00:08, 18.45it/s]

Epoch 8:  93%|█████████▎| 1852/2000 [01:39<00:08, 18.46it/s]

Epoch 8:  93%|█████████▎| 1854/2000 [01:39<00:07, 18.46it/s]

Epoch 8:  93%|█████████▎| 1856/2000 [01:40<00:07, 18.46it/s]

Epoch 8:  93%|█████████▎| 1858/2000 [01:40<00:07, 18.46it/s]

Epoch 8:  93%|█████████▎| 1860/2000 [01:40<00:07, 18.46it/s]

Epoch 8:  93%|█████████▎| 1862/2000 [01:40<00:07, 18.45it/s]

Epoch 8:  93%|█████████▎| 1864/2000 [01:40<00:07, 18.46it/s]

Epoch 8:  93%|█████████▎| 1866/2000 [01:40<00:07, 18.46it/s]

Epoch 8:  93%|█████████▎| 1868/2000 [01:40<00:07, 18.45it/s]

Epoch 8:  94%|█████████▎| 1870/2000 [01:40<00:07, 18.45it/s]

Epoch 8:  94%|█████████▎| 1872/2000 [01:40<00:06, 18.44it/s]

Epoch 8:  94%|█████████▎| 1874/2000 [01:41<00:06, 18.45it/s]

Epoch 8:  94%|█████████▍| 1876/2000 [01:41<00:06, 18.45it/s]

Epoch 8:  94%|█████████▍| 1878/2000 [01:41<00:06, 18.45it/s]

Epoch 8:  94%|█████████▍| 1880/2000 [01:41<00:06, 18.45it/s]

Epoch 8:  94%|█████████▍| 1882/2000 [01:41<00:06, 18.46it/s]

Epoch 8:  94%|█████████▍| 1884/2000 [01:41<00:06, 18.46it/s]

Epoch 8:  94%|█████████▍| 1886/2000 [01:41<00:06, 18.47it/s]

Epoch 8:  94%|█████████▍| 1888/2000 [01:41<00:06, 18.47it/s]

Epoch 8:  94%|█████████▍| 1890/2000 [01:41<00:05, 18.45it/s]

Epoch 8:  95%|█████████▍| 1892/2000 [01:41<00:05, 18.46it/s]

Epoch 8:  95%|█████████▍| 1894/2000 [01:42<00:05, 18.46it/s]

Epoch 8:  95%|█████████▍| 1896/2000 [01:42<00:05, 18.44it/s]

Epoch 8:  95%|█████████▍| 1898/2000 [01:42<00:05, 18.44it/s]

Epoch 8:  95%|█████████▌| 1900/2000 [01:42<00:05, 18.45it/s]

Epoch 8:  95%|█████████▌| 1902/2000 [01:42<00:05, 18.46it/s]

Epoch 8:  95%|█████████▌| 1904/2000 [01:42<00:05, 18.46it/s]

Epoch 8:  95%|█████████▌| 1906/2000 [01:42<00:05, 18.45it/s]

Epoch 8:  95%|█████████▌| 1908/2000 [01:42<00:04, 18.45it/s]

Epoch 8:  96%|█████████▌| 1910/2000 [01:42<00:04, 18.44it/s]

Epoch 8:  96%|█████████▌| 1912/2000 [01:43<00:04, 18.46it/s]

Epoch 8:  96%|█████████▌| 1914/2000 [01:43<00:04, 18.46it/s]

Epoch 8:  96%|█████████▌| 1916/2000 [01:43<00:04, 18.46it/s]

Epoch 8:  96%|█████████▌| 1918/2000 [01:43<00:04, 18.46it/s]

Epoch 8:  96%|█████████▌| 1920/2000 [01:43<00:04, 18.46it/s]

Epoch 8:  96%|█████████▌| 1922/2000 [01:43<00:04, 18.44it/s]

Epoch 8:  96%|█████████▌| 1924/2000 [01:43<00:04, 18.44it/s]

Epoch 8:  96%|█████████▋| 1926/2000 [01:43<00:04, 18.44it/s]

Epoch 8:  96%|█████████▋| 1928/2000 [01:43<00:03, 18.43it/s]

Epoch 8:  96%|█████████▋| 1930/2000 [01:44<00:03, 18.45it/s]

Epoch 8:  97%|█████████▋| 1932/2000 [01:44<00:03, 18.44it/s]

Epoch 8:  97%|█████████▋| 1934/2000 [01:44<00:03, 18.45it/s]

Epoch 8:  97%|█████████▋| 1936/2000 [01:44<00:03, 18.45it/s]

Epoch 8:  97%|█████████▋| 1938/2000 [01:44<00:03, 18.45it/s]

Epoch 8:  97%|█████████▋| 1940/2000 [01:44<00:03, 18.45it/s]

Epoch 8:  97%|█████████▋| 1942/2000 [01:44<00:03, 18.46it/s]

Epoch 8:  97%|█████████▋| 1944/2000 [01:44<00:03, 18.45it/s]

Epoch 8:  97%|█████████▋| 1946/2000 [01:44<00:02, 18.45it/s]

Epoch 8:  97%|█████████▋| 1948/2000 [01:45<00:02, 18.46it/s]

Epoch 8:  98%|█████████▊| 1950/2000 [01:45<00:02, 18.48it/s]

Epoch 8:  98%|█████████▊| 1952/2000 [01:45<00:02, 18.51it/s]

Epoch 8:  98%|█████████▊| 1954/2000 [01:45<00:02, 18.52it/s]

Epoch 8:  98%|█████████▊| 1956/2000 [01:45<00:02, 18.55it/s]

Epoch 8:  98%|█████████▊| 1958/2000 [01:45<00:02, 18.54it/s]

Epoch 8:  98%|█████████▊| 1960/2000 [01:45<00:02, 18.52it/s]

Epoch 8:  98%|█████████▊| 1962/2000 [01:45<00:02, 18.51it/s]

Epoch 8:  98%|█████████▊| 1964/2000 [01:45<00:01, 18.52it/s]

Epoch 8:  98%|█████████▊| 1966/2000 [01:45<00:01, 18.50it/s]

Epoch 8:  98%|█████████▊| 1968/2000 [01:46<00:01, 18.52it/s]

Epoch 8:  98%|█████████▊| 1970/2000 [01:46<00:01, 18.52it/s]

Epoch 8:  99%|█████████▊| 1972/2000 [01:46<00:01, 18.52it/s]

Epoch 8:  99%|█████████▊| 1974/2000 [01:46<00:01, 18.53it/s]

Epoch 8:  99%|█████████▉| 1976/2000 [01:46<00:01, 18.52it/s]

Epoch 8:  99%|█████████▉| 1978/2000 [01:46<00:01, 18.51it/s]

Epoch 8:  99%|█████████▉| 1980/2000 [01:46<00:01, 18.51it/s]

Epoch 8:  99%|█████████▉| 1982/2000 [01:46<00:00, 18.50it/s]

Epoch 8:  99%|█████████▉| 1984/2000 [01:46<00:00, 18.52it/s]

Epoch 8:  99%|█████████▉| 1986/2000 [01:47<00:00, 18.52it/s]

Epoch 8:  99%|█████████▉| 1988/2000 [01:47<00:00, 18.54it/s]

Epoch 8: 100%|█████████▉| 1990/2000 [01:47<00:00, 18.54it/s]

Epoch 8: 100%|█████████▉| 1992/2000 [01:47<00:00, 18.54it/s]

Epoch 8: 100%|█████████▉| 1994/2000 [01:47<00:00, 18.55it/s]

Epoch 8: 100%|█████████▉| 1996/2000 [01:47<00:00, 18.55it/s]

Epoch 8: 100%|█████████▉| 1998/2000 [01:47<00:00, 18.54it/s]

Epoch 8: 100%|██████████| 2000/2000 [01:47<00:00, 18.53it/s]

Epoch 8: loss=0.1942, val_proxy=0.9248

Epoch 9:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 9:   0%|          | 2/2000 [00:00<01:56, 17.15it/s]

Epoch 9:   0%|          | 4/2000 [00:00<01:52, 17.80it/s]

Epoch 9:   0%|          | 6/2000 [00:00<01:50, 18.10it/s]

Epoch 9:   0%|          | 8/2000 [00:00<01:49, 18.24it/s]

Epoch 9:   0%|          | 10/2000 [00:00<01:48, 18.33it/s]

Epoch 9:   1%|          | 12/2000 [00:00<01:48, 18.39it/s]

Epoch 9:   1%|          | 14/2000 [00:00<01:47, 18.42it/s]

Epoch 9:   1%|          | 16/2000 [00:00<01:47, 18.45it/s]

Epoch 9:   1%|          | 18/2000 [00:00<01:47, 18.48it/s]

Epoch 9:   1%|          | 20/2000 [00:01<01:47, 18.50it/s]

Epoch 9:   1%|          | 22/2000 [00:01<01:46, 18.51it/s]

Epoch 9:   1%|          | 24/2000 [00:01<01:46, 18.50it/s]

Epoch 9:   1%|▏         | 26/2000 [00:01<01:46, 18.50it/s]

Epoch 9:   1%|▏         | 28/2000 [00:01<01:46, 18.51it/s]

Epoch 9:   2%|▏         | 30/2000 [00:01<01:46, 18.51it/s]

Epoch 9:   2%|▏         | 32/2000 [00:01<01:46, 18.50it/s]

Epoch 9:   2%|▏         | 34/2000 [00:01<01:46, 18.50it/s]

Epoch 9:   2%|▏         | 36/2000 [00:01<01:46, 18.50it/s]

Epoch 9:   2%|▏         | 38/2000 [00:02<01:46, 18.50it/s]

Epoch 9:   2%|▏         | 40/2000 [00:02<01:45, 18.49it/s]

Epoch 9:   2%|▏         | 42/2000 [00:02<01:45, 18.50it/s]

Epoch 9:   2%|▏         | 44/2000 [00:02<01:45, 18.51it/s]

Epoch 9:   2%|▏         | 46/2000 [00:02<01:45, 18.52it/s]

Epoch 9:   2%|▏         | 48/2000 [00:02<01:45, 18.52it/s]

Epoch 9:   2%|▎         | 50/2000 [00:02<01:45, 18.52it/s]

Epoch 9:   3%|▎         | 52/2000 [00:02<01:45, 18.39it/s]

Epoch 9:   3%|▎         | 54/2000 [00:02<01:45, 18.41it/s]

Epoch 9:   3%|▎         | 56/2000 [00:03<01:45, 18.42it/s]

Epoch 9:   3%|▎         | 58/2000 [00:03<01:45, 18.45it/s]

Epoch 9:   3%|▎         | 60/2000 [00:03<01:44, 18.49it/s]

Epoch 9:   3%|▎         | 62/2000 [00:03<01:44, 18.50it/s]

Epoch 9:   3%|▎         | 64/2000 [00:03<01:44, 18.52it/s]

Epoch 9:   3%|▎         | 66/2000 [00:03<01:44, 18.53it/s]

Epoch 9:   3%|▎         | 68/2000 [00:03<01:44, 18.52it/s]

Epoch 9:   4%|▎         | 70/2000 [00:03<01:44, 18.53it/s]

Epoch 9:   4%|▎         | 72/2000 [00:03<01:44, 18.54it/s]

Epoch 9:   4%|▎         | 74/2000 [00:04<01:43, 18.54it/s]

Epoch 9:   4%|▍         | 76/2000 [00:04<01:43, 18.53it/s]

Epoch 9:   4%|▍         | 78/2000 [00:04<01:43, 18.54it/s]

Epoch 9:   4%|▍         | 80/2000 [00:04<01:43, 18.56it/s]

Epoch 9:   4%|▍         | 82/2000 [00:04<01:43, 18.56it/s]

Epoch 9:   4%|▍         | 84/2000 [00:04<01:43, 18.57it/s]

Epoch 9:   4%|▍         | 86/2000 [00:04<01:43, 18.57it/s]

Epoch 9:   4%|▍         | 88/2000 [00:04<01:42, 18.56it/s]

Epoch 9:   4%|▍         | 90/2000 [00:04<01:42, 18.55it/s]

Epoch 9:   5%|▍         | 92/2000 [00:04<01:42, 18.55it/s]

Epoch 9:   5%|▍         | 94/2000 [00:05<01:42, 18.54it/s]

Epoch 9:   5%|▍         | 96/2000 [00:05<01:43, 18.36it/s]

Epoch 9:   5%|▍         | 98/2000 [00:05<01:43, 18.42it/s]

Epoch 9:   5%|▌         | 100/2000 [00:05<01:42, 18.45it/s]

Epoch 9:   5%|▌         | 102/2000 [00:05<01:43, 18.41it/s]

Epoch 9:   5%|▌         | 104/2000 [00:05<01:42, 18.43it/s]

Epoch 9:   5%|▌         | 106/2000 [00:05<01:42, 18.46it/s]

Epoch 9:   5%|▌         | 108/2000 [00:05<01:42, 18.39it/s]

Epoch 9:   6%|▌         | 110/2000 [00:05<01:42, 18.42it/s]

Epoch 9:   6%|▌         | 112/2000 [00:06<01:42, 18.46it/s]

Epoch 9:   6%|▌         | 114/2000 [00:06<01:42, 18.48it/s]

Epoch 9:   6%|▌         | 116/2000 [00:06<01:41, 18.51it/s]

Epoch 9:   6%|▌         | 118/2000 [00:06<01:41, 18.51it/s]

Epoch 9:   6%|▌         | 120/2000 [00:06<01:42, 18.33it/s]

Epoch 9:   6%|▌         | 122/2000 [00:06<01:42, 18.39it/s]

Epoch 9:   6%|▌         | 124/2000 [00:06<01:41, 18.44it/s]

Epoch 9:   6%|▋         | 126/2000 [00:06<01:41, 18.47it/s]

Epoch 9:   6%|▋         | 128/2000 [00:06<01:41, 18.48it/s]

Epoch 9:   6%|▋         | 130/2000 [00:07<01:41, 18.48it/s]

Epoch 9:   7%|▋         | 132/2000 [00:07<01:40, 18.50it/s]

Epoch 9:   7%|▋         | 134/2000 [00:07<01:40, 18.50it/s]

Epoch 9:   7%|▋         | 136/2000 [00:07<01:40, 18.51it/s]

Epoch 9:   7%|▋         | 138/2000 [00:07<01:40, 18.53it/s]

Epoch 9:   7%|▋         | 140/2000 [00:07<01:40, 18.55it/s]

Epoch 9:   7%|▋         | 142/2000 [00:07<01:40, 18.55it/s]

Epoch 9:   7%|▋         | 144/2000 [00:07<01:40, 18.56it/s]

Epoch 9:   7%|▋         | 146/2000 [00:07<01:39, 18.55it/s]

Epoch 9:   7%|▋         | 148/2000 [00:08<01:39, 18.56it/s]

Epoch 9:   8%|▊         | 150/2000 [00:08<01:39, 18.57it/s]

Epoch 9:   8%|▊         | 152/2000 [00:08<01:39, 18.55it/s]

Epoch 9:   8%|▊         | 154/2000 [00:08<01:39, 18.54it/s]

Epoch 9:   8%|▊         | 156/2000 [00:08<01:39, 18.53it/s]

Epoch 9:   8%|▊         | 158/2000 [00:08<01:39, 18.54it/s]

Epoch 9:   8%|▊         | 160/2000 [00:08<01:39, 18.54it/s]

Epoch 9:   8%|▊         | 162/2000 [00:08<01:39, 18.54it/s]

Epoch 9:   8%|▊         | 164/2000 [00:08<01:38, 18.55it/s]

Epoch 9:   8%|▊         | 166/2000 [00:08<01:38, 18.56it/s]

Epoch 9:   8%|▊         | 168/2000 [00:09<01:38, 18.58it/s]

Epoch 9:   8%|▊         | 170/2000 [00:09<01:38, 18.57it/s]

Epoch 9:   9%|▊         | 172/2000 [00:09<01:38, 18.58it/s]

Epoch 9:   9%|▊         | 174/2000 [00:09<01:38, 18.56it/s]

Epoch 9:   9%|▉         | 176/2000 [00:09<01:38, 18.56it/s]

Epoch 9:   9%|▉         | 178/2000 [00:09<01:38, 18.58it/s]

Epoch 9:   9%|▉         | 180/2000 [00:09<01:37, 18.59it/s]

Epoch 9:   9%|▉         | 182/2000 [00:09<01:37, 18.60it/s]

Epoch 9:   9%|▉         | 184/2000 [00:09<01:37, 18.60it/s]

Epoch 9:   9%|▉         | 186/2000 [00:10<01:37, 18.59it/s]

Epoch 9:   9%|▉         | 188/2000 [00:10<01:37, 18.60it/s]

Epoch 9:  10%|▉         | 190/2000 [00:10<01:37, 18.60it/s]

Epoch 9:  10%|▉         | 192/2000 [00:10<01:37, 18.57it/s]

Epoch 9:  10%|▉         | 194/2000 [00:10<01:37, 18.57it/s]

Epoch 9:  10%|▉         | 196/2000 [00:10<01:37, 18.56it/s]

Epoch 9:  10%|▉         | 198/2000 [00:10<01:37, 18.56it/s]

Epoch 9:  10%|█         | 200/2000 [00:10<01:37, 18.46it/s]

Epoch 9:  10%|█         | 202/2000 [00:10<01:37, 18.49it/s]

Epoch 9:  10%|█         | 204/2000 [00:11<01:37, 18.51it/s]

Epoch 9:  10%|█         | 206/2000 [00:11<01:36, 18.52it/s]

Epoch 9:  10%|█         | 208/2000 [00:11<01:36, 18.53it/s]

Epoch 9:  10%|█         | 210/2000 [00:11<01:36, 18.55it/s]

Epoch 9:  11%|█         | 212/2000 [00:11<01:36, 18.56it/s]

Epoch 9:  11%|█         | 214/2000 [00:11<01:36, 18.48it/s]

Epoch 9:  11%|█         | 216/2000 [00:11<01:36, 18.48it/s]

Epoch 9:  11%|█         | 218/2000 [00:11<01:36, 18.50it/s]

Epoch 9:  11%|█         | 220/2000 [00:11<01:36, 18.52it/s]

Epoch 9:  11%|█         | 222/2000 [00:12<01:35, 18.54it/s]

Epoch 9:  11%|█         | 224/2000 [00:12<01:35, 18.54it/s]

Epoch 9:  11%|█▏        | 226/2000 [00:12<01:35, 18.58it/s]

Epoch 9:  11%|█▏        | 228/2000 [00:12<01:35, 18.57it/s]

Epoch 9:  12%|█▏        | 230/2000 [00:12<01:35, 18.57it/s]

Epoch 9:  12%|█▏        | 232/2000 [00:12<01:35, 18.56it/s]

Epoch 9:  12%|█▏        | 234/2000 [00:12<01:35, 18.57it/s]

Epoch 9:  12%|█▏        | 236/2000 [00:12<01:34, 18.58it/s]

Epoch 9:  12%|█▏        | 238/2000 [00:12<01:34, 18.59it/s]

Epoch 9:  12%|█▏        | 240/2000 [00:12<01:34, 18.59it/s]

Epoch 9:  12%|█▏        | 242/2000 [00:13<01:34, 18.59it/s]

Epoch 9:  12%|█▏        | 244/2000 [00:13<01:34, 18.60it/s]

Epoch 9:  12%|█▏        | 246/2000 [00:13<01:34, 18.59it/s]

Epoch 9:  12%|█▏        | 248/2000 [00:13<01:34, 18.59it/s]

Epoch 9:  12%|█▎        | 250/2000 [00:13<01:34, 18.58it/s]

Epoch 9:  13%|█▎        | 252/2000 [00:13<01:34, 18.59it/s]

Epoch 9:  13%|█▎        | 254/2000 [00:13<01:34, 18.57it/s]

Epoch 9:  13%|█▎        | 256/2000 [00:13<01:33, 18.57it/s]

Epoch 9:  13%|█▎        | 258/2000 [00:13<01:33, 18.57it/s]

Epoch 9:  13%|█▎        | 260/2000 [00:14<01:33, 18.56it/s]

Epoch 9:  13%|█▎        | 262/2000 [00:14<01:33, 18.57it/s]

Epoch 9:  13%|█▎        | 264/2000 [00:14<01:33, 18.57it/s]

Epoch 9:  13%|█▎        | 266/2000 [00:14<01:33, 18.59it/s]

Epoch 9:  13%|█▎        | 268/2000 [00:14<01:33, 18.58it/s]

Epoch 9:  14%|█▎        | 270/2000 [00:14<01:33, 18.58it/s]

Epoch 9:  14%|█▎        | 272/2000 [00:14<01:32, 18.59it/s]

Epoch 9:  14%|█▎        | 274/2000 [00:14<01:32, 18.59it/s]

Epoch 9:  14%|█▍        | 276/2000 [00:14<01:32, 18.59it/s]

Epoch 9:  14%|█▍        | 278/2000 [00:15<01:32, 18.58it/s]

Epoch 9:  14%|█▍        | 280/2000 [00:15<01:32, 18.58it/s]

Epoch 9:  14%|█▍        | 282/2000 [00:15<01:32, 18.57it/s]

Epoch 9:  14%|█▍        | 284/2000 [00:15<01:32, 18.56it/s]

Epoch 9:  14%|█▍        | 286/2000 [00:15<01:32, 18.56it/s]

Epoch 9:  14%|█▍        | 288/2000 [00:15<01:32, 18.55it/s]

Epoch 9:  14%|█▍        | 290/2000 [00:15<01:32, 18.57it/s]

Epoch 9:  15%|█▍        | 292/2000 [00:15<01:31, 18.57it/s]

Epoch 9:  15%|█▍        | 294/2000 [00:15<01:31, 18.58it/s]

Epoch 9:  15%|█▍        | 296/2000 [00:15<01:31, 18.59it/s]

Epoch 9:  15%|█▍        | 298/2000 [00:16<01:31, 18.58it/s]

Epoch 9:  15%|█▌        | 300/2000 [00:16<01:31, 18.59it/s]

Epoch 9:  15%|█▌        | 302/2000 [00:16<01:31, 18.58it/s]

Epoch 9:  15%|█▌        | 304/2000 [00:16<01:31, 18.59it/s]

Epoch 9:  15%|█▌        | 306/2000 [00:16<01:31, 18.58it/s]

Epoch 9:  15%|█▌        | 308/2000 [00:16<01:31, 18.57it/s]

Epoch 9:  16%|█▌        | 310/2000 [00:16<01:31, 18.57it/s]

Epoch 9:  16%|█▌        | 312/2000 [00:16<01:30, 18.57it/s]

Epoch 9:  16%|█▌        | 314/2000 [00:16<01:30, 18.58it/s]

Epoch 9:  16%|█▌        | 316/2000 [00:17<01:30, 18.56it/s]

Epoch 9:  16%|█▌        | 318/2000 [00:17<01:30, 18.56it/s]

Epoch 9:  16%|█▌        | 320/2000 [00:17<01:30, 18.55it/s]

Epoch 9:  16%|█▌        | 322/2000 [00:17<01:30, 18.57it/s]

Epoch 9:  16%|█▌        | 324/2000 [00:17<01:30, 18.57it/s]

Epoch 9:  16%|█▋        | 326/2000 [00:17<01:30, 18.58it/s]

Epoch 9:  16%|█▋        | 328/2000 [00:17<01:30, 18.57it/s]

Epoch 9:  16%|█▋        | 330/2000 [00:17<01:29, 18.57it/s]

Epoch 9:  17%|█▋        | 332/2000 [00:17<01:29, 18.57it/s]

Epoch 9:  17%|█▋        | 334/2000 [00:18<01:29, 18.57it/s]

Epoch 9:  17%|█▋        | 336/2000 [00:18<01:29, 18.56it/s]

Epoch 9:  17%|█▋        | 338/2000 [00:18<01:29, 18.56it/s]

Epoch 9:  17%|█▋        | 340/2000 [00:18<01:29, 18.58it/s]

Epoch 9:  17%|█▋        | 342/2000 [00:18<01:29, 18.57it/s]

Epoch 9:  17%|█▋        | 344/2000 [00:18<01:29, 18.59it/s]

Epoch 9:  17%|█▋        | 346/2000 [00:18<01:28, 18.59it/s]

Epoch 9:  17%|█▋        | 348/2000 [00:18<01:28, 18.59it/s]

Epoch 9:  18%|█▊        | 350/2000 [00:18<01:28, 18.58it/s]

Epoch 9:  18%|█▊        | 352/2000 [00:18<01:28, 18.60it/s]

Epoch 9:  18%|█▊        | 354/2000 [00:19<01:28, 18.58it/s]

Epoch 9:  18%|█▊        | 356/2000 [00:19<01:28, 18.57it/s]

Epoch 9:  18%|█▊        | 358/2000 [00:19<01:28, 18.56it/s]

Epoch 9:  18%|█▊        | 360/2000 [00:19<01:28, 18.56it/s]

Epoch 9:  18%|█▊        | 362/2000 [00:19<01:28, 18.56it/s]

Epoch 9:  18%|█▊        | 364/2000 [00:19<01:28, 18.56it/s]

Epoch 9:  18%|█▊        | 366/2000 [00:19<01:28, 18.56it/s]

Epoch 9:  18%|█▊        | 368/2000 [00:19<01:27, 18.55it/s]

Epoch 9:  18%|█▊        | 370/2000 [00:19<01:27, 18.56it/s]

Epoch 9:  19%|█▊        | 372/2000 [00:20<01:27, 18.57it/s]

Epoch 9:  19%|█▊        | 374/2000 [00:20<01:27, 18.56it/s]

Epoch 9:  19%|█▉        | 376/2000 [00:20<01:27, 18.56it/s]

Epoch 9:  19%|█▉        | 378/2000 [00:20<01:27, 18.48it/s]

Epoch 9:  19%|█▉        | 380/2000 [00:20<01:27, 18.49it/s]

Epoch 9:  19%|█▉        | 382/2000 [00:20<01:27, 18.53it/s]

Epoch 9:  19%|█▉        | 384/2000 [00:20<01:27, 18.55it/s]

Epoch 9:  19%|█▉        | 386/2000 [00:20<01:26, 18.55it/s]

Epoch 9:  19%|█▉        | 388/2000 [00:20<01:26, 18.55it/s]

Epoch 9:  20%|█▉        | 390/2000 [00:21<01:26, 18.55it/s]

Epoch 9:  20%|█▉        | 392/2000 [00:21<01:26, 18.55it/s]

Epoch 9:  20%|█▉        | 394/2000 [00:21<01:26, 18.57it/s]

Epoch 9:  20%|█▉        | 396/2000 [00:21<01:26, 18.57it/s]

Epoch 9:  20%|█▉        | 398/2000 [00:21<01:26, 18.56it/s]

Epoch 9:  20%|██        | 400/2000 [00:21<01:26, 18.57it/s]

Epoch 9:  20%|██        | 402/2000 [00:21<01:26, 18.57it/s]

Epoch 9:  20%|██        | 404/2000 [00:21<01:25, 18.58it/s]

Epoch 9:  20%|██        | 406/2000 [00:21<01:25, 18.58it/s]

Epoch 9:  20%|██        | 408/2000 [00:22<01:25, 18.58it/s]

Epoch 9:  20%|██        | 410/2000 [00:22<01:25, 18.58it/s]

Epoch 9:  21%|██        | 412/2000 [00:22<01:25, 18.58it/s]

Epoch 9:  21%|██        | 414/2000 [00:22<01:25, 18.57it/s]

Epoch 9:  21%|██        | 416/2000 [00:22<01:25, 18.57it/s]

Epoch 9:  21%|██        | 418/2000 [00:22<01:25, 18.57it/s]

Epoch 9:  21%|██        | 420/2000 [00:22<01:25, 18.57it/s]

Epoch 9:  21%|██        | 422/2000 [00:22<01:24, 18.57it/s]

Epoch 9:  21%|██        | 424/2000 [00:22<01:24, 18.56it/s]

Epoch 9:  21%|██▏       | 426/2000 [00:22<01:24, 18.57it/s]

Epoch 9:  21%|██▏       | 428/2000 [00:23<01:24, 18.57it/s]

Epoch 9:  22%|██▏       | 430/2000 [00:23<01:24, 18.58it/s]

Epoch 9:  22%|██▏       | 432/2000 [00:23<01:24, 18.58it/s]

Epoch 9:  22%|██▏       | 434/2000 [00:23<01:24, 18.57it/s]

Epoch 9:  22%|██▏       | 436/2000 [00:23<01:24, 18.58it/s]

Epoch 9:  22%|██▏       | 438/2000 [00:23<01:24, 18.57it/s]

Epoch 9:  22%|██▏       | 440/2000 [00:23<01:24, 18.56it/s]

Epoch 9:  22%|██▏       | 442/2000 [00:23<01:23, 18.57it/s]

Epoch 9:  22%|██▏       | 444/2000 [00:23<01:23, 18.57it/s]

Epoch 9:  22%|██▏       | 446/2000 [00:24<01:23, 18.57it/s]

Epoch 9:  22%|██▏       | 448/2000 [00:24<01:23, 18.56it/s]

Epoch 9:  22%|██▎       | 450/2000 [00:24<01:23, 18.57it/s]

Epoch 9:  23%|██▎       | 452/2000 [00:24<01:23, 18.57it/s]

Epoch 9:  23%|██▎       | 454/2000 [00:24<01:23, 18.57it/s]

Epoch 9:  23%|██▎       | 456/2000 [00:24<01:23, 18.57it/s]

Epoch 9:  23%|██▎       | 458/2000 [00:24<01:23, 18.57it/s]

Epoch 9:  23%|██▎       | 460/2000 [00:24<01:22, 18.58it/s]

Epoch 9:  23%|██▎       | 462/2000 [00:24<01:22, 18.58it/s]

Epoch 9:  23%|██▎       | 464/2000 [00:25<01:22, 18.58it/s]

Epoch 9:  23%|██▎       | 466/2000 [00:25<01:22, 18.57it/s]

Epoch 9:  23%|██▎       | 468/2000 [00:25<01:22, 18.57it/s]

Epoch 9:  24%|██▎       | 470/2000 [00:25<01:22, 18.58it/s]

Epoch 9:  24%|██▎       | 472/2000 [00:25<01:22, 18.57it/s]

Epoch 9:  24%|██▎       | 474/2000 [00:25<01:22, 18.58it/s]

Epoch 9:  24%|██▍       | 476/2000 [00:25<01:21, 18.60it/s]

Epoch 9:  24%|██▍       | 478/2000 [00:25<01:21, 18.60it/s]

Epoch 9:  24%|██▍       | 480/2000 [00:25<01:21, 18.58it/s]

Epoch 9:  24%|██▍       | 482/2000 [00:26<01:21, 18.58it/s]

Epoch 9:  24%|██▍       | 484/2000 [00:26<01:21, 18.59it/s]

Epoch 9:  24%|██▍       | 486/2000 [00:26<01:21, 18.60it/s]

Epoch 9:  24%|██▍       | 488/2000 [00:26<01:21, 18.59it/s]

Epoch 9:  24%|██▍       | 490/2000 [00:26<01:21, 18.58it/s]

Epoch 9:  25%|██▍       | 492/2000 [00:26<01:21, 18.58it/s]

Epoch 9:  25%|██▍       | 494/2000 [00:26<01:21, 18.58it/s]

Epoch 9:  25%|██▍       | 496/2000 [00:26<01:21, 18.56it/s]

Epoch 9:  25%|██▍       | 498/2000 [00:26<01:20, 18.55it/s]

Epoch 9:  25%|██▌       | 500/2000 [00:26<01:20, 18.56it/s]

Epoch 9:  25%|██▌       | 502/2000 [00:27<01:20, 18.56it/s]

Epoch 9:  25%|██▌       | 504/2000 [00:27<01:20, 18.57it/s]

Epoch 9:  25%|██▌       | 506/2000 [00:27<01:20, 18.58it/s]

Epoch 9:  25%|██▌       | 508/2000 [00:27<01:21, 18.39it/s]

Epoch 9:  26%|██▌       | 510/2000 [00:27<01:23, 17.82it/s]

Epoch 9:  26%|██▌       | 512/2000 [00:27<01:23, 17.83it/s]

Epoch 9:  26%|██▌       | 514/2000 [00:27<01:22, 18.02it/s]

Epoch 9:  26%|██▌       | 516/2000 [00:27<01:21, 18.14it/s]

Epoch 9:  26%|██▌       | 518/2000 [00:27<01:21, 18.21it/s]

Epoch 9:  26%|██▌       | 520/2000 [00:28<01:20, 18.29it/s]

Epoch 9:  26%|██▌       | 522/2000 [00:28<01:20, 18.37it/s]

Epoch 9:  26%|██▌       | 524/2000 [00:28<01:20, 18.44it/s]

Epoch 9:  26%|██▋       | 526/2000 [00:28<01:19, 18.48it/s]

Epoch 9:  26%|██▋       | 528/2000 [00:28<01:19, 18.51it/s]

Epoch 9:  26%|██▋       | 530/2000 [00:28<01:19, 18.53it/s]

Epoch 9:  27%|██▋       | 532/2000 [00:28<01:19, 18.55it/s]

Epoch 9:  27%|██▋       | 534/2000 [00:28<01:18, 18.56it/s]

Epoch 9:  27%|██▋       | 536/2000 [00:28<01:18, 18.56it/s]

Epoch 9:  27%|██▋       | 538/2000 [00:29<01:18, 18.57it/s]

Epoch 9:  27%|██▋       | 540/2000 [00:29<01:18, 18.57it/s]

Epoch 9:  27%|██▋       | 542/2000 [00:29<01:18, 18.58it/s]

Epoch 9:  27%|██▋       | 544/2000 [00:29<01:18, 18.58it/s]

Epoch 9:  27%|██▋       | 546/2000 [00:29<01:18, 18.57it/s]

Epoch 9:  27%|██▋       | 548/2000 [00:29<01:18, 18.58it/s]

Epoch 9:  28%|██▊       | 550/2000 [00:29<01:18, 18.58it/s]

Epoch 9:  28%|██▊       | 552/2000 [00:29<01:17, 18.58it/s]

Epoch 9:  28%|██▊       | 554/2000 [00:29<01:17, 18.59it/s]

Epoch 9:  28%|██▊       | 556/2000 [00:30<01:17, 18.59it/s]

Epoch 9:  28%|██▊       | 558/2000 [00:30<01:17, 18.58it/s]

Epoch 9:  28%|██▊       | 560/2000 [00:30<01:17, 18.58it/s]

Epoch 9:  28%|██▊       | 562/2000 [00:30<01:17, 18.58it/s]

Epoch 9:  28%|██▊       | 564/2000 [00:30<01:17, 18.57it/s]

Epoch 9:  28%|██▊       | 566/2000 [00:30<01:17, 18.56it/s]

Epoch 9:  28%|██▊       | 568/2000 [00:30<01:17, 18.57it/s]

Epoch 9:  28%|██▊       | 570/2000 [00:30<01:16, 18.59it/s]

Epoch 9:  29%|██▊       | 572/2000 [00:30<01:16, 18.55it/s]

Epoch 9:  29%|██▊       | 574/2000 [00:30<01:16, 18.56it/s]

Epoch 9:  29%|██▉       | 576/2000 [00:31<01:17, 18.39it/s]

Epoch 9:  29%|██▉       | 578/2000 [00:31<01:17, 18.41it/s]

Epoch 9:  29%|██▉       | 580/2000 [00:31<01:17, 18.44it/s]

Epoch 9:  29%|██▉       | 582/2000 [00:31<01:16, 18.46it/s]

Epoch 9:  29%|██▉       | 584/2000 [00:31<01:17, 18.23it/s]

Epoch 9:  29%|██▉       | 586/2000 [00:31<01:17, 18.31it/s]

Epoch 9:  29%|██▉       | 588/2000 [00:31<01:16, 18.37it/s]

Epoch 9:  30%|██▉       | 590/2000 [00:31<01:16, 18.40it/s]

Epoch 9:  30%|██▉       | 592/2000 [00:31<01:16, 18.44it/s]

Epoch 9:  30%|██▉       | 594/2000 [00:32<01:17, 18.25it/s]

Epoch 9:  30%|██▉       | 596/2000 [00:32<01:16, 18.34it/s]

Epoch 9:  30%|██▉       | 598/2000 [00:32<01:16, 18.40it/s]

Epoch 9:  30%|███       | 600/2000 [00:32<01:15, 18.43it/s]

Epoch 9:  30%|███       | 602/2000 [00:32<01:15, 18.46it/s]

Epoch 9:  30%|███       | 604/2000 [00:32<01:15, 18.48it/s]

Epoch 9:  30%|███       | 606/2000 [00:32<01:15, 18.51it/s]

Epoch 9:  30%|███       | 608/2000 [00:32<01:15, 18.52it/s]

Epoch 9:  30%|███       | 610/2000 [00:32<01:15, 18.53it/s]

Epoch 9:  31%|███       | 612/2000 [00:33<01:14, 18.53it/s]

Epoch 9:  31%|███       | 614/2000 [00:33<01:14, 18.52it/s]

Epoch 9:  31%|███       | 616/2000 [00:33<01:14, 18.53it/s]

Epoch 9:  31%|███       | 618/2000 [00:33<01:14, 18.54it/s]

Epoch 9:  31%|███       | 620/2000 [00:33<01:14, 18.53it/s]

Epoch 9:  31%|███       | 622/2000 [00:33<01:14, 18.55it/s]

Epoch 9:  31%|███       | 624/2000 [00:33<01:14, 18.56it/s]

Epoch 9:  31%|███▏      | 626/2000 [00:33<01:14, 18.56it/s]

Epoch 9:  31%|███▏      | 628/2000 [00:33<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 630/2000 [00:34<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 632/2000 [00:34<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 634/2000 [00:34<01:13, 18.56it/s]

Epoch 9:  32%|███▏      | 636/2000 [00:34<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 638/2000 [00:34<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 640/2000 [00:34<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 642/2000 [00:34<01:13, 18.55it/s]

Epoch 9:  32%|███▏      | 644/2000 [00:34<01:13, 18.54it/s]

Epoch 9:  32%|███▏      | 646/2000 [00:34<01:12, 18.55it/s]

Epoch 9:  32%|███▏      | 648/2000 [00:34<01:12, 18.56it/s]

Epoch 9:  32%|███▎      | 650/2000 [00:35<01:12, 18.55it/s]

Epoch 9:  33%|███▎      | 652/2000 [00:35<01:12, 18.56it/s]

Epoch 9:  33%|███▎      | 654/2000 [00:35<01:12, 18.56it/s]

Epoch 9:  33%|███▎      | 656/2000 [00:35<01:12, 18.55it/s]

Epoch 9:  33%|███▎      | 658/2000 [00:35<01:12, 18.54it/s]

Epoch 9:  33%|███▎      | 660/2000 [00:35<01:12, 18.54it/s]

Epoch 9:  33%|███▎      | 662/2000 [00:35<01:12, 18.54it/s]

Epoch 9:  33%|███▎      | 664/2000 [00:35<01:12, 18.56it/s]

Epoch 9:  33%|███▎      | 666/2000 [00:35<01:11, 18.56it/s]

Epoch 9:  33%|███▎      | 668/2000 [00:36<01:11, 18.55it/s]

Epoch 9:  34%|███▎      | 670/2000 [00:36<01:11, 18.54it/s]

Epoch 9:  34%|███▎      | 672/2000 [00:36<01:11, 18.54it/s]

Epoch 9:  34%|███▎      | 674/2000 [00:36<01:11, 18.54it/s]

Epoch 9:  34%|███▍      | 676/2000 [00:36<01:11, 18.54it/s]

Epoch 9:  34%|███▍      | 678/2000 [00:36<01:11, 18.55it/s]

Epoch 9:  34%|███▍      | 680/2000 [00:36<01:11, 18.56it/s]

Epoch 9:  34%|███▍      | 682/2000 [00:36<01:11, 18.55it/s]

Epoch 9:  34%|███▍      | 684/2000 [00:36<01:10, 18.56it/s]

Epoch 9:  34%|███▍      | 686/2000 [00:37<01:10, 18.55it/s]

Epoch 9:  34%|███▍      | 688/2000 [00:37<01:10, 18.56it/s]

Epoch 9:  34%|███▍      | 690/2000 [00:37<01:10, 18.56it/s]

Epoch 9:  35%|███▍      | 692/2000 [00:37<01:10, 18.55it/s]

Epoch 9:  35%|███▍      | 694/2000 [00:37<01:10, 18.55it/s]

Epoch 9:  35%|███▍      | 696/2000 [00:37<01:10, 18.56it/s]

Epoch 9:  35%|███▍      | 698/2000 [00:37<01:10, 18.56it/s]

Epoch 9:  35%|███▌      | 700/2000 [00:37<01:10, 18.55it/s]

Epoch 9:  35%|███▌      | 702/2000 [00:37<01:10, 18.53it/s]

Epoch 9:  35%|███▌      | 704/2000 [00:38<01:09, 18.55it/s]

Epoch 9:  35%|███▌      | 706/2000 [00:38<01:09, 18.56it/s]

Epoch 9:  35%|███▌      | 708/2000 [00:38<01:09, 18.57it/s]

Epoch 9:  36%|███▌      | 710/2000 [00:38<01:09, 18.56it/s]

Epoch 9:  36%|███▌      | 712/2000 [00:38<01:09, 18.57it/s]

Epoch 9:  36%|███▌      | 714/2000 [00:38<01:09, 18.57it/s]

Epoch 9:  36%|███▌      | 716/2000 [00:38<01:09, 18.55it/s]

Epoch 9:  36%|███▌      | 718/2000 [00:38<01:09, 18.56it/s]

Epoch 9:  36%|███▌      | 720/2000 [00:38<01:09, 18.54it/s]

Epoch 9:  36%|███▌      | 722/2000 [00:38<01:08, 18.56it/s]

Epoch 9:  36%|███▌      | 724/2000 [00:39<01:08, 18.56it/s]

Epoch 9:  36%|███▋      | 726/2000 [00:39<01:08, 18.57it/s]

Epoch 9:  36%|███▋      | 728/2000 [00:39<01:08, 18.57it/s]

Epoch 9:  36%|███▋      | 730/2000 [00:39<01:08, 18.58it/s]

Epoch 9:  37%|███▋      | 732/2000 [00:39<01:08, 18.57it/s]

Epoch 9:  37%|███▋      | 734/2000 [00:39<01:08, 18.57it/s]

Epoch 9:  37%|███▋      | 736/2000 [00:39<01:08, 18.57it/s]

Epoch 9:  37%|███▋      | 738/2000 [00:39<01:07, 18.57it/s]

Epoch 9:  37%|███▋      | 740/2000 [00:39<01:07, 18.56it/s]

Epoch 9:  37%|███▋      | 742/2000 [00:40<01:07, 18.55it/s]

Epoch 9:  37%|███▋      | 744/2000 [00:40<01:07, 18.54it/s]

Epoch 9:  37%|███▋      | 746/2000 [00:40<01:07, 18.54it/s]

Epoch 9:  37%|███▋      | 748/2000 [00:40<01:07, 18.53it/s]

Epoch 9:  38%|███▊      | 750/2000 [00:40<01:07, 18.54it/s]

Epoch 9:  38%|███▊      | 752/2000 [00:40<01:07, 18.55it/s]

Epoch 9:  38%|███▊      | 754/2000 [00:40<01:07, 18.56it/s]

Epoch 9:  38%|███▊      | 756/2000 [00:40<01:07, 18.55it/s]

Epoch 9:  38%|███▊      | 758/2000 [00:40<01:06, 18.55it/s]

Epoch 9:  38%|███▊      | 760/2000 [00:41<01:06, 18.56it/s]

Epoch 9:  38%|███▊      | 762/2000 [00:41<01:06, 18.56it/s]

Epoch 9:  38%|███▊      | 764/2000 [00:41<01:06, 18.56it/s]

Epoch 9:  38%|███▊      | 766/2000 [00:41<01:06, 18.57it/s]

Epoch 9:  38%|███▊      | 768/2000 [00:41<01:06, 18.57it/s]

Epoch 9:  38%|███▊      | 770/2000 [00:41<01:06, 18.58it/s]

Epoch 9:  39%|███▊      | 772/2000 [00:41<01:06, 18.57it/s]

Epoch 9:  39%|███▊      | 774/2000 [00:41<01:06, 18.57it/s]

Epoch 9:  39%|███▉      | 776/2000 [00:41<01:05, 18.56it/s]

Epoch 9:  39%|███▉      | 778/2000 [00:41<01:05, 18.56it/s]

Epoch 9:  39%|███▉      | 780/2000 [00:42<01:05, 18.56it/s]

Epoch 9:  39%|███▉      | 782/2000 [00:42<01:05, 18.54it/s]

Epoch 9:  39%|███▉      | 784/2000 [00:42<01:05, 18.55it/s]

Epoch 9:  39%|███▉      | 786/2000 [00:42<01:05, 18.55it/s]

Epoch 9:  39%|███▉      | 788/2000 [00:42<01:05, 18.55it/s]

Epoch 9:  40%|███▉      | 790/2000 [00:42<01:05, 18.54it/s]

Epoch 9:  40%|███▉      | 792/2000 [00:42<01:05, 18.55it/s]

Epoch 9:  40%|███▉      | 794/2000 [00:42<01:04, 18.56it/s]

Epoch 9:  40%|███▉      | 796/2000 [00:42<01:04, 18.56it/s]

Epoch 9:  40%|███▉      | 798/2000 [00:43<01:04, 18.56it/s]

Epoch 9:  40%|████      | 800/2000 [00:43<01:04, 18.57it/s]

Epoch 9:  40%|████      | 802/2000 [00:43<01:04, 18.57it/s]

Epoch 9:  40%|████      | 804/2000 [00:43<01:04, 18.56it/s]

Epoch 9:  40%|████      | 806/2000 [00:43<01:04, 18.56it/s]

Epoch 9:  40%|████      | 808/2000 [00:43<01:04, 18.56it/s]

Epoch 9:  40%|████      | 810/2000 [00:43<01:04, 18.56it/s]

Epoch 9:  41%|████      | 812/2000 [00:43<01:04, 18.56it/s]

Epoch 9:  41%|████      | 814/2000 [00:43<01:03, 18.55it/s]

Epoch 9:  41%|████      | 816/2000 [00:44<01:03, 18.55it/s]

Epoch 9:  41%|████      | 818/2000 [00:44<01:03, 18.55it/s]

Epoch 9:  41%|████      | 820/2000 [00:44<01:03, 18.56it/s]

Epoch 9:  41%|████      | 822/2000 [00:44<01:03, 18.56it/s]

Epoch 9:  41%|████      | 824/2000 [00:44<01:03, 18.55it/s]

Epoch 9:  41%|████▏     | 826/2000 [00:44<01:03, 18.53it/s]

Epoch 9:  41%|████▏     | 828/2000 [00:44<01:03, 18.54it/s]

Epoch 9:  42%|████▏     | 830/2000 [00:44<01:03, 18.54it/s]

Epoch 9:  42%|████▏     | 832/2000 [00:44<01:02, 18.56it/s]

Epoch 9:  42%|████▏     | 834/2000 [00:45<01:02, 18.57it/s]

Epoch 9:  42%|████▏     | 836/2000 [00:45<01:02, 18.56it/s]

Epoch 9:  42%|████▏     | 838/2000 [00:45<01:02, 18.56it/s]

Epoch 9:  42%|████▏     | 840/2000 [00:45<01:02, 18.55it/s]

Epoch 9:  42%|████▏     | 842/2000 [00:45<01:02, 18.55it/s]

Epoch 9:  42%|████▏     | 844/2000 [00:45<01:02, 18.55it/s]

Epoch 9:  42%|████▏     | 846/2000 [00:45<01:02, 18.54it/s]

Epoch 9:  42%|████▏     | 848/2000 [00:45<01:02, 18.54it/s]

Epoch 9:  42%|████▎     | 850/2000 [00:45<01:02, 18.54it/s]

Epoch 9:  43%|████▎     | 852/2000 [00:45<01:01, 18.54it/s]

Epoch 9:  43%|████▎     | 854/2000 [00:46<01:01, 18.53it/s]

Epoch 9:  43%|████▎     | 856/2000 [00:46<01:01, 18.53it/s]

Epoch 9:  43%|████▎     | 858/2000 [00:46<01:01, 18.54it/s]

Epoch 9:  43%|████▎     | 860/2000 [00:46<01:01, 18.55it/s]

Epoch 9:  43%|████▎     | 862/2000 [00:46<01:01, 18.54it/s]

Epoch 9:  43%|████▎     | 864/2000 [00:46<01:01, 18.55it/s]

Epoch 9:  43%|████▎     | 866/2000 [00:46<01:01, 18.55it/s]

Epoch 9:  43%|████▎     | 868/2000 [00:46<01:01, 18.55it/s]

Epoch 9:  44%|████▎     | 870/2000 [00:46<01:00, 18.54it/s]

Epoch 9:  44%|████▎     | 872/2000 [00:47<01:00, 18.55it/s]

Epoch 9:  44%|████▎     | 874/2000 [00:47<01:00, 18.55it/s]

Epoch 9:  44%|████▍     | 876/2000 [00:47<01:00, 18.56it/s]

Epoch 9:  44%|████▍     | 878/2000 [00:47<01:00, 18.55it/s]

Epoch 9:  44%|████▍     | 880/2000 [00:47<01:00, 18.55it/s]

Epoch 9:  44%|████▍     | 882/2000 [00:47<01:00, 18.55it/s]

Epoch 9:  44%|████▍     | 884/2000 [00:47<01:00, 18.56it/s]

Epoch 9:  44%|████▍     | 886/2000 [00:47<01:00, 18.55it/s]

Epoch 9:  44%|████▍     | 888/2000 [00:47<00:59, 18.54it/s]

Epoch 9:  44%|████▍     | 890/2000 [00:48<00:59, 18.55it/s]

Epoch 9:  45%|████▍     | 892/2000 [00:48<00:59, 18.54it/s]

Epoch 9:  45%|████▍     | 894/2000 [00:48<00:59, 18.54it/s]

Epoch 9:  45%|████▍     | 896/2000 [00:48<00:59, 18.55it/s]

Epoch 9:  45%|████▍     | 898/2000 [00:48<00:59, 18.56it/s]

Epoch 9:  45%|████▌     | 900/2000 [00:48<00:59, 18.56it/s]

Epoch 9:  45%|████▌     | 902/2000 [00:48<00:59, 18.55it/s]

Epoch 9:  45%|████▌     | 904/2000 [00:48<00:59, 18.56it/s]

Epoch 9:  45%|████▌     | 906/2000 [00:48<00:58, 18.57it/s]

Epoch 9:  45%|████▌     | 908/2000 [00:48<00:58, 18.58it/s]

Epoch 9:  46%|████▌     | 910/2000 [00:49<00:58, 18.56it/s]

Epoch 9:  46%|████▌     | 912/2000 [00:49<00:58, 18.55it/s]

Epoch 9:  46%|████▌     | 914/2000 [00:49<00:58, 18.56it/s]

Epoch 9:  46%|████▌     | 916/2000 [00:49<00:58, 18.56it/s]

Epoch 9:  46%|████▌     | 918/2000 [00:49<00:58, 18.56it/s]

Epoch 9:  46%|████▌     | 920/2000 [00:49<00:58, 18.56it/s]

Epoch 9:  46%|████▌     | 922/2000 [00:49<00:58, 18.55it/s]

Epoch 9:  46%|████▌     | 924/2000 [00:49<00:58, 18.54it/s]

Epoch 9:  46%|████▋     | 926/2000 [00:49<00:57, 18.54it/s]

Epoch 9:  46%|████▋     | 928/2000 [00:50<00:57, 18.56it/s]

Epoch 9:  46%|████▋     | 930/2000 [00:50<00:57, 18.55it/s]

Epoch 9:  47%|████▋     | 932/2000 [00:50<00:57, 18.55it/s]

Epoch 9:  47%|████▋     | 934/2000 [00:50<00:57, 18.56it/s]

Epoch 9:  47%|████▋     | 936/2000 [00:50<00:57, 18.55it/s]

Epoch 9:  47%|████▋     | 938/2000 [00:50<00:57, 18.55it/s]

Epoch 9:  47%|████▋     | 940/2000 [00:50<00:57, 18.55it/s]

Epoch 9:  47%|████▋     | 942/2000 [00:50<00:57, 18.54it/s]

Epoch 9:  47%|████▋     | 944/2000 [00:50<00:56, 18.54it/s]

Epoch 9:  47%|████▋     | 946/2000 [00:51<00:56, 18.55it/s]

Epoch 9:  47%|████▋     | 948/2000 [00:51<00:56, 18.55it/s]

Epoch 9:  48%|████▊     | 950/2000 [00:51<00:56, 18.55it/s]

Epoch 9:  48%|████▊     | 952/2000 [00:51<00:56, 18.55it/s]

Epoch 9:  48%|████▊     | 954/2000 [00:51<00:56, 18.56it/s]

Epoch 9:  48%|████▊     | 956/2000 [00:51<00:56, 18.56it/s]

Epoch 9:  48%|████▊     | 958/2000 [00:51<00:56, 18.56it/s]

Epoch 9:  48%|████▊     | 960/2000 [00:51<00:56, 18.55it/s]

Epoch 9:  48%|████▊     | 962/2000 [00:51<00:55, 18.54it/s]

Epoch 9:  48%|████▊     | 964/2000 [00:52<00:55, 18.54it/s]

Epoch 9:  48%|████▊     | 966/2000 [00:52<00:55, 18.53it/s]

Epoch 9:  48%|████▊     | 968/2000 [00:52<00:55, 18.53it/s]

Epoch 9:  48%|████▊     | 970/2000 [00:52<00:55, 18.55it/s]

Epoch 9:  49%|████▊     | 972/2000 [00:52<00:55, 18.55it/s]

Epoch 9:  49%|████▊     | 974/2000 [00:52<00:55, 18.54it/s]

Epoch 9:  49%|████▉     | 976/2000 [00:52<00:55, 18.54it/s]

Epoch 9:  49%|████▉     | 978/2000 [00:52<00:55, 18.54it/s]

Epoch 9:  49%|████▉     | 980/2000 [00:52<00:55, 18.54it/s]

Epoch 9:  49%|████▉     | 982/2000 [00:52<00:54, 18.53it/s]

Epoch 9:  49%|████▉     | 984/2000 [00:53<00:54, 18.54it/s]

Epoch 9:  49%|████▉     | 986/2000 [00:53<00:54, 18.54it/s]

Epoch 9:  49%|████▉     | 988/2000 [00:53<00:54, 18.54it/s]

Epoch 9:  50%|████▉     | 990/2000 [00:53<00:54, 18.55it/s]

Epoch 9:  50%|████▉     | 992/2000 [00:53<00:54, 18.55it/s]

Epoch 9:  50%|████▉     | 994/2000 [00:53<00:54, 18.54it/s]

Epoch 9:  50%|████▉     | 996/2000 [00:53<00:54, 18.54it/s]

Epoch 9:  50%|████▉     | 998/2000 [00:53<00:54, 18.53it/s]

Epoch 9:  50%|█████     | 1000/2000 [00:53<00:53, 18.53it/s]

Epoch 9:  50%|█████     | 1002/2000 [00:54<00:53, 18.54it/s]

Epoch 9:  50%|█████     | 1004/2000 [00:54<00:53, 18.55it/s]

Epoch 9:  50%|█████     | 1006/2000 [00:54<00:53, 18.54it/s]

Epoch 9:  50%|█████     | 1008/2000 [00:54<00:53, 18.54it/s]

Epoch 9:  50%|█████     | 1010/2000 [00:54<00:53, 18.55it/s]

Epoch 9:  51%|█████     | 1012/2000 [00:54<00:53, 18.55it/s]

Epoch 9:  51%|█████     | 1014/2000 [00:54<00:53, 18.55it/s]

Epoch 9:  51%|█████     | 1016/2000 [00:54<00:53, 18.56it/s]

Epoch 9:  51%|█████     | 1018/2000 [00:54<00:52, 18.56it/s]

Epoch 9:  51%|█████     | 1020/2000 [00:55<00:52, 18.56it/s]

Epoch 9:  51%|█████     | 1022/2000 [00:55<00:52, 18.56it/s]

Epoch 9:  51%|█████     | 1024/2000 [00:55<00:52, 18.56it/s]

Epoch 9:  51%|█████▏    | 1026/2000 [00:55<00:52, 18.55it/s]

Epoch 9:  51%|█████▏    | 1028/2000 [00:55<00:52, 18.54it/s]

Epoch 9:  52%|█████▏    | 1030/2000 [00:55<00:52, 18.54it/s]

Epoch 9:  52%|█████▏    | 1032/2000 [00:55<00:52, 18.53it/s]

Epoch 9:  52%|█████▏    | 1034/2000 [00:55<00:52, 18.55it/s]

Epoch 9:  52%|█████▏    | 1036/2000 [00:55<00:52, 18.52it/s]

Epoch 9:  52%|█████▏    | 1038/2000 [00:56<00:51, 18.51it/s]

Epoch 9:  52%|█████▏    | 1040/2000 [00:56<00:51, 18.52it/s]

Epoch 9:  52%|█████▏    | 1042/2000 [00:56<00:51, 18.53it/s]

Epoch 9:  52%|█████▏    | 1044/2000 [00:56<00:51, 18.52it/s]

Epoch 9:  52%|█████▏    | 1046/2000 [00:56<00:51, 18.54it/s]

Epoch 9:  52%|█████▏    | 1048/2000 [00:56<00:51, 18.55it/s]

Epoch 9:  52%|█████▎    | 1050/2000 [00:56<00:51, 18.55it/s]

Epoch 9:  53%|█████▎    | 1052/2000 [00:56<00:51, 18.54it/s]

Epoch 9:  53%|█████▎    | 1054/2000 [00:56<00:51, 18.55it/s]

Epoch 9:  53%|█████▎    | 1056/2000 [00:56<00:50, 18.55it/s]

Epoch 9:  53%|█████▎    | 1058/2000 [00:57<00:50, 18.54it/s]

Epoch 9:  53%|█████▎    | 1060/2000 [00:57<00:50, 18.53it/s]

Epoch 9:  53%|█████▎    | 1062/2000 [00:57<00:50, 18.53it/s]

Epoch 9:  53%|█████▎    | 1064/2000 [00:57<00:50, 18.53it/s]

Epoch 9:  53%|█████▎    | 1066/2000 [00:57<00:50, 18.54it/s]

Epoch 9:  53%|█████▎    | 1068/2000 [00:57<00:50, 18.53it/s]

Epoch 9:  54%|█████▎    | 1070/2000 [00:57<00:50, 18.54it/s]

Epoch 9:  54%|█████▎    | 1072/2000 [00:57<00:50, 18.55it/s]

Epoch 9:  54%|█████▎    | 1074/2000 [00:57<00:49, 18.54it/s]

Epoch 9:  54%|█████▍    | 1076/2000 [00:58<00:49, 18.55it/s]

Epoch 9:  54%|█████▍    | 1078/2000 [00:58<00:49, 18.56it/s]

Epoch 9:  54%|█████▍    | 1080/2000 [00:58<00:49, 18.55it/s]

Epoch 9:  54%|█████▍    | 1082/2000 [00:58<00:49, 18.54it/s]

Epoch 9:  54%|█████▍    | 1084/2000 [00:58<00:49, 18.54it/s]

Epoch 9:  54%|█████▍    | 1086/2000 [00:58<00:49, 18.54it/s]

Epoch 9:  54%|█████▍    | 1088/2000 [00:58<00:49, 18.56it/s]

Epoch 9:  55%|█████▍    | 1090/2000 [00:58<00:49, 18.54it/s]

Epoch 9:  55%|█████▍    | 1092/2000 [00:58<00:48, 18.55it/s]

Epoch 9:  55%|█████▍    | 1094/2000 [00:59<00:48, 18.56it/s]

Epoch 9:  55%|█████▍    | 1096/2000 [00:59<00:48, 18.56it/s]

Epoch 9:  55%|█████▍    | 1098/2000 [00:59<00:48, 18.56it/s]

Epoch 9:  55%|█████▌    | 1100/2000 [00:59<00:48, 18.57it/s]

Epoch 9:  55%|█████▌    | 1102/2000 [00:59<00:48, 18.57it/s]

Epoch 9:  55%|█████▌    | 1104/2000 [00:59<00:48, 18.57it/s]

Epoch 9:  55%|█████▌    | 1106/2000 [00:59<00:48, 18.57it/s]

Epoch 9:  55%|█████▌    | 1108/2000 [00:59<00:48, 18.57it/s]

Epoch 9:  56%|█████▌    | 1110/2000 [00:59<00:47, 18.58it/s]

Epoch 9:  56%|█████▌    | 1112/2000 [00:59<00:47, 18.57it/s]

Epoch 9:  56%|█████▌    | 1114/2000 [01:00<00:47, 18.57it/s]

Epoch 9:  56%|█████▌    | 1116/2000 [01:00<00:48, 18.35it/s]

Epoch 9:  56%|█████▌    | 1118/2000 [01:00<00:48, 18.18it/s]

Epoch 9:  56%|█████▌    | 1120/2000 [01:00<00:49, 17.83it/s]

Epoch 9:  56%|█████▌    | 1122/2000 [01:00<00:49, 17.88it/s]

Epoch 9:  56%|█████▌    | 1124/2000 [01:00<00:48, 18.04it/s]

Epoch 9:  56%|█████▋    | 1126/2000 [01:00<00:48, 18.11it/s]

Epoch 9:  56%|█████▋    | 1128/2000 [01:00<00:47, 18.24it/s]

Epoch 9:  56%|█████▋    | 1130/2000 [01:00<00:47, 18.34it/s]

Epoch 9:  57%|█████▋    | 1132/2000 [01:01<00:47, 18.40it/s]

Epoch 9:  57%|█████▋    | 1134/2000 [01:01<00:46, 18.44it/s]

Epoch 9:  57%|█████▋    | 1136/2000 [01:01<00:46, 18.47it/s]

Epoch 9:  57%|█████▋    | 1138/2000 [01:01<00:46, 18.49it/s]

Epoch 9:  57%|█████▋    | 1140/2000 [01:01<00:46, 18.50it/s]

Epoch 9:  57%|█████▋    | 1142/2000 [01:01<00:46, 18.51it/s]

Epoch 9:  57%|█████▋    | 1144/2000 [01:01<00:46, 18.52it/s]

Epoch 9:  57%|█████▋    | 1146/2000 [01:01<00:46, 18.53it/s]

Epoch 9:  57%|█████▋    | 1148/2000 [01:01<00:45, 18.53it/s]

Epoch 9:  57%|█████▊    | 1150/2000 [01:02<00:45, 18.54it/s]

Epoch 9:  58%|█████▊    | 1152/2000 [01:02<00:45, 18.54it/s]

Epoch 9:  58%|█████▊    | 1154/2000 [01:02<00:45, 18.55it/s]

Epoch 9:  58%|█████▊    | 1156/2000 [01:02<00:45, 18.55it/s]

Epoch 9:  58%|█████▊    | 1158/2000 [01:02<00:45, 18.55it/s]

Epoch 9:  58%|█████▊    | 1160/2000 [01:02<00:45, 18.54it/s]

Epoch 9:  58%|█████▊    | 1162/2000 [01:02<00:45, 18.53it/s]

Epoch 9:  58%|█████▊    | 1164/2000 [01:02<00:45, 18.52it/s]

Epoch 9:  58%|█████▊    | 1166/2000 [01:02<00:44, 18.54it/s]

Epoch 9:  58%|█████▊    | 1168/2000 [01:03<00:44, 18.56it/s]

Epoch 9:  58%|█████▊    | 1170/2000 [01:03<00:44, 18.51it/s]

Epoch 9:  59%|█████▊    | 1172/2000 [01:03<00:44, 18.47it/s]

Epoch 9:  59%|█████▊    | 1174/2000 [01:03<00:44, 18.49it/s]

Epoch 9:  59%|█████▉    | 1176/2000 [01:03<00:44, 18.52it/s]

Epoch 9:  59%|█████▉    | 1178/2000 [01:03<00:44, 18.52it/s]

Epoch 9:  59%|█████▉    | 1180/2000 [01:03<00:44, 18.52it/s]

Epoch 9:  59%|█████▉    | 1182/2000 [01:03<00:44, 18.45it/s]

Epoch 9:  59%|█████▉    | 1184/2000 [01:03<00:44, 18.47it/s]

Epoch 9:  59%|█████▉    | 1186/2000 [01:04<00:44, 18.49it/s]

Epoch 9:  59%|█████▉    | 1188/2000 [01:04<00:43, 18.50it/s]

Epoch 9:  60%|█████▉    | 1190/2000 [01:04<00:43, 18.52it/s]

Epoch 9:  60%|█████▉    | 1192/2000 [01:04<00:43, 18.52it/s]

Epoch 9:  60%|█████▉    | 1194/2000 [01:04<00:43, 18.53it/s]

Epoch 9:  60%|█████▉    | 1196/2000 [01:04<00:43, 18.54it/s]

Epoch 9:  60%|█████▉    | 1198/2000 [01:04<00:43, 18.54it/s]

Epoch 9:  60%|██████    | 1200/2000 [01:04<00:43, 18.54it/s]

Epoch 9:  60%|██████    | 1202/2000 [01:04<00:43, 18.55it/s]

Epoch 9:  60%|██████    | 1204/2000 [01:04<00:42, 18.55it/s]

Epoch 9:  60%|██████    | 1206/2000 [01:05<00:42, 18.55it/s]

Epoch 9:  60%|██████    | 1208/2000 [01:05<00:42, 18.55it/s]

Epoch 9:  60%|██████    | 1210/2000 [01:05<00:42, 18.55it/s]

Epoch 9:  61%|██████    | 1212/2000 [01:05<00:42, 18.56it/s]

Epoch 9:  61%|██████    | 1214/2000 [01:05<00:42, 18.55it/s]

Epoch 9:  61%|██████    | 1216/2000 [01:05<00:42, 18.53it/s]

Epoch 9:  61%|██████    | 1218/2000 [01:05<00:42, 18.53it/s]

Epoch 9:  61%|██████    | 1220/2000 [01:05<00:42, 18.53it/s]

Epoch 9:  61%|██████    | 1222/2000 [01:05<00:41, 18.54it/s]

Epoch 9:  61%|██████    | 1224/2000 [01:06<00:41, 18.54it/s]

Epoch 9:  61%|██████▏   | 1226/2000 [01:06<00:41, 18.54it/s]

Epoch 9:  61%|██████▏   | 1228/2000 [01:06<00:41, 18.54it/s]

Epoch 9:  62%|██████▏   | 1230/2000 [01:06<00:41, 18.54it/s]

Epoch 9:  62%|██████▏   | 1232/2000 [01:06<00:41, 18.55it/s]

Epoch 9:  62%|██████▏   | 1234/2000 [01:06<00:41, 18.55it/s]

Epoch 9:  62%|██████▏   | 1236/2000 [01:06<00:41, 18.55it/s]

Epoch 9:  62%|██████▏   | 1238/2000 [01:06<00:41, 18.56it/s]

Epoch 9:  62%|██████▏   | 1240/2000 [01:06<00:40, 18.56it/s]

Epoch 9:  62%|██████▏   | 1242/2000 [01:07<00:40, 18.56it/s]

Epoch 9:  62%|██████▏   | 1244/2000 [01:07<00:40, 18.54it/s]

Epoch 9:  62%|██████▏   | 1246/2000 [01:07<00:40, 18.55it/s]

Epoch 9:  62%|██████▏   | 1248/2000 [01:07<00:40, 18.55it/s]

Epoch 9:  62%|██████▎   | 1250/2000 [01:07<00:40, 18.55it/s]

Epoch 9:  63%|██████▎   | 1252/2000 [01:07<00:40, 18.55it/s]

Epoch 9:  63%|██████▎   | 1254/2000 [01:07<00:40, 18.54it/s]

Epoch 9:  63%|██████▎   | 1256/2000 [01:07<00:40, 18.53it/s]

Epoch 9:  63%|██████▎   | 1258/2000 [01:07<00:40, 18.53it/s]

Epoch 9:  63%|██████▎   | 1260/2000 [01:08<00:39, 18.53it/s]

Epoch 9:  63%|██████▎   | 1262/2000 [01:08<00:39, 18.54it/s]

Epoch 9:  63%|██████▎   | 1264/2000 [01:08<00:39, 18.55it/s]

Epoch 9:  63%|██████▎   | 1266/2000 [01:08<00:39, 18.55it/s]

Epoch 9:  63%|██████▎   | 1268/2000 [01:08<00:39, 18.55it/s]

Epoch 9:  64%|██████▎   | 1270/2000 [01:08<00:39, 18.54it/s]

Epoch 9:  64%|██████▎   | 1272/2000 [01:08<00:39, 18.55it/s]

Epoch 9:  64%|██████▎   | 1274/2000 [01:08<00:39, 18.54it/s]

Epoch 9:  64%|██████▍   | 1276/2000 [01:08<00:39, 18.55it/s]

Epoch 9:  64%|██████▍   | 1278/2000 [01:08<00:38, 18.55it/s]

Epoch 9:  64%|██████▍   | 1280/2000 [01:09<00:38, 18.54it/s]

Epoch 9:  64%|██████▍   | 1282/2000 [01:09<00:38, 18.54it/s]

Epoch 9:  64%|██████▍   | 1284/2000 [01:09<00:38, 18.53it/s]

Epoch 9:  64%|██████▍   | 1286/2000 [01:09<00:38, 18.53it/s]

Epoch 9:  64%|██████▍   | 1288/2000 [01:09<00:38, 18.54it/s]

Epoch 9:  64%|██████▍   | 1290/2000 [01:09<00:38, 18.54it/s]

Epoch 9:  65%|██████▍   | 1292/2000 [01:09<00:38, 18.52it/s]

Epoch 9:  65%|██████▍   | 1294/2000 [01:09<00:38, 18.52it/s]

Epoch 9:  65%|██████▍   | 1296/2000 [01:09<00:38, 18.52it/s]

Epoch 9:  65%|██████▍   | 1298/2000 [01:10<00:37, 18.52it/s]

Epoch 9:  65%|██████▌   | 1300/2000 [01:10<00:37, 18.53it/s]

Epoch 9:  65%|██████▌   | 1302/2000 [01:10<00:37, 18.54it/s]

Epoch 9:  65%|██████▌   | 1304/2000 [01:10<00:37, 18.55it/s]

Epoch 9:  65%|██████▌   | 1306/2000 [01:10<00:37, 18.56it/s]

Epoch 9:  65%|██████▌   | 1308/2000 [01:10<00:37, 18.56it/s]

Epoch 9:  66%|██████▌   | 1310/2000 [01:10<00:37, 18.56it/s]

Epoch 9:  66%|██████▌   | 1312/2000 [01:10<00:37, 18.55it/s]

Epoch 9:  66%|██████▌   | 1314/2000 [01:10<00:36, 18.55it/s]

Epoch 9:  66%|██████▌   | 1316/2000 [01:11<00:36, 18.55it/s]

Epoch 9:  66%|██████▌   | 1318/2000 [01:11<00:36, 18.54it/s]

Epoch 9:  66%|██████▌   | 1320/2000 [01:11<00:36, 18.53it/s]

Epoch 9:  66%|██████▌   | 1322/2000 [01:11<00:36, 18.54it/s]

Epoch 9:  66%|██████▌   | 1324/2000 [01:11<00:36, 18.54it/s]

Epoch 9:  66%|██████▋   | 1326/2000 [01:11<00:36, 18.54it/s]

Epoch 9:  66%|██████▋   | 1328/2000 [01:11<00:36, 18.55it/s]

Epoch 9:  66%|██████▋   | 1330/2000 [01:11<00:36, 18.55it/s]

Epoch 9:  67%|██████▋   | 1332/2000 [01:11<00:36, 18.55it/s]

Epoch 9:  67%|██████▋   | 1334/2000 [01:11<00:35, 18.55it/s]

Epoch 9:  67%|██████▋   | 1336/2000 [01:12<00:35, 18.56it/s]

Epoch 9:  67%|██████▋   | 1338/2000 [01:12<00:35, 18.56it/s]

Epoch 9:  67%|██████▋   | 1340/2000 [01:12<00:35, 18.54it/s]

Epoch 9:  67%|██████▋   | 1342/2000 [01:12<00:35, 18.53it/s]

Epoch 9:  67%|██████▋   | 1344/2000 [01:12<00:35, 18.53it/s]

Epoch 9:  67%|██████▋   | 1346/2000 [01:12<00:35, 18.53it/s]

Epoch 9:  67%|██████▋   | 1348/2000 [01:12<00:35, 18.53it/s]

Epoch 9:  68%|██████▊   | 1350/2000 [01:12<00:35, 18.48it/s]

Epoch 9:  68%|██████▊   | 1352/2000 [01:12<00:35, 18.49it/s]

Epoch 9:  68%|██████▊   | 1354/2000 [01:13<00:34, 18.51it/s]

Epoch 9:  68%|██████▊   | 1356/2000 [01:13<00:34, 18.52it/s]

Epoch 9:  68%|██████▊   | 1358/2000 [01:13<00:34, 18.53it/s]

Epoch 9:  68%|██████▊   | 1360/2000 [01:13<00:34, 18.54it/s]

Epoch 9:  68%|██████▊   | 1362/2000 [01:13<00:34, 18.52it/s]

Epoch 9:  68%|██████▊   | 1364/2000 [01:13<00:34, 18.53it/s]

Epoch 9:  68%|██████▊   | 1366/2000 [01:13<00:34, 18.54it/s]

Epoch 9:  68%|██████▊   | 1368/2000 [01:13<00:34, 18.54it/s]

Epoch 9:  68%|██████▊   | 1370/2000 [01:13<00:33, 18.55it/s]

Epoch 9:  69%|██████▊   | 1372/2000 [01:14<00:33, 18.56it/s]

Epoch 9:  69%|██████▊   | 1374/2000 [01:14<00:33, 18.47it/s]

Epoch 9:  69%|██████▉   | 1376/2000 [01:14<00:33, 18.50it/s]

Epoch 9:  69%|██████▉   | 1378/2000 [01:14<00:33, 18.51it/s]

Epoch 9:  69%|██████▉   | 1380/2000 [01:14<00:33, 18.51it/s]

Epoch 9:  69%|██████▉   | 1382/2000 [01:14<00:33, 18.52it/s]

Epoch 9:  69%|██████▉   | 1384/2000 [01:14<00:33, 18.52it/s]

Epoch 9:  69%|██████▉   | 1386/2000 [01:14<00:33, 18.51it/s]

Epoch 9:  69%|██████▉   | 1388/2000 [01:14<00:33, 18.51it/s]

Epoch 9:  70%|██████▉   | 1390/2000 [01:15<00:32, 18.53it/s]

Epoch 9:  70%|██████▉   | 1392/2000 [01:15<00:32, 18.53it/s]

Epoch 9:  70%|██████▉   | 1394/2000 [01:15<00:32, 18.53it/s]

Epoch 9:  70%|██████▉   | 1396/2000 [01:15<00:32, 18.54it/s]

Epoch 9:  70%|██████▉   | 1398/2000 [01:15<00:32, 18.53it/s]

Epoch 9:  70%|███████   | 1400/2000 [01:15<00:32, 18.54it/s]

Epoch 9:  70%|███████   | 1402/2000 [01:15<00:32, 18.54it/s]

Epoch 9:  70%|███████   | 1404/2000 [01:15<00:32, 18.54it/s]

Epoch 9:  70%|███████   | 1406/2000 [01:15<00:32, 18.53it/s]

Epoch 9:  70%|███████   | 1408/2000 [01:15<00:31, 18.53it/s]

Epoch 9:  70%|███████   | 1410/2000 [01:16<00:31, 18.54it/s]

Epoch 9:  71%|███████   | 1412/2000 [01:16<00:31, 18.53it/s]

Epoch 9:  71%|███████   | 1414/2000 [01:16<00:31, 18.52it/s]

Epoch 9:  71%|███████   | 1416/2000 [01:16<00:31, 18.52it/s]

Epoch 9:  71%|███████   | 1418/2000 [01:16<00:31, 18.52it/s]

Epoch 9:  71%|███████   | 1420/2000 [01:16<00:31, 18.53it/s]

Epoch 9:  71%|███████   | 1422/2000 [01:16<00:31, 18.54it/s]

Epoch 9:  71%|███████   | 1424/2000 [01:16<00:31, 18.53it/s]

Epoch 9:  71%|███████▏  | 1426/2000 [01:16<00:30, 18.54it/s]

Epoch 9:  71%|███████▏  | 1428/2000 [01:17<00:30, 18.54it/s]

Epoch 9:  72%|███████▏  | 1430/2000 [01:17<00:30, 18.53it/s]

Epoch 9:  72%|███████▏  | 1432/2000 [01:17<00:30, 18.53it/s]

Epoch 9:  72%|███████▏  | 1434/2000 [01:17<00:30, 18.54it/s]

Epoch 9:  72%|███████▏  | 1436/2000 [01:17<00:30, 18.54it/s]

Epoch 9:  72%|███████▏  | 1438/2000 [01:17<00:30, 18.54it/s]

Epoch 9:  72%|███████▏  | 1440/2000 [01:17<00:30, 18.54it/s]

Epoch 9:  72%|███████▏  | 1442/2000 [01:17<00:30, 18.54it/s]

Epoch 9:  72%|███████▏  | 1444/2000 [01:17<00:29, 18.54it/s]

Epoch 9:  72%|███████▏  | 1446/2000 [01:18<00:29, 18.53it/s]

Epoch 9:  72%|███████▏  | 1448/2000 [01:18<00:29, 18.54it/s]

Epoch 9:  72%|███████▎  | 1450/2000 [01:18<00:29, 18.53it/s]

Epoch 9:  73%|███████▎  | 1452/2000 [01:18<00:29, 18.53it/s]

Epoch 9:  73%|███████▎  | 1454/2000 [01:18<00:29, 18.52it/s]

Epoch 9:  73%|███████▎  | 1456/2000 [01:18<00:29, 18.52it/s]

Epoch 9:  73%|███████▎  | 1458/2000 [01:18<00:29, 18.52it/s]

Epoch 9:  73%|███████▎  | 1460/2000 [01:18<00:29, 18.52it/s]

Epoch 9:  73%|███████▎  | 1462/2000 [01:18<00:29, 18.53it/s]

Epoch 9:  73%|███████▎  | 1464/2000 [01:19<00:28, 18.53it/s]

Epoch 9:  73%|███████▎  | 1466/2000 [01:19<00:28, 18.53it/s]

Epoch 9:  73%|███████▎  | 1468/2000 [01:19<00:28, 18.55it/s]

Epoch 9:  74%|███████▎  | 1470/2000 [01:19<00:28, 18.54it/s]

Epoch 9:  74%|███████▎  | 1472/2000 [01:19<00:28, 18.54it/s]

Epoch 9:  74%|███████▎  | 1474/2000 [01:19<00:28, 18.53it/s]

Epoch 9:  74%|███████▍  | 1476/2000 [01:19<00:28, 18.53it/s]

Epoch 9:  74%|███████▍  | 1478/2000 [01:19<00:28, 18.53it/s]

Epoch 9:  74%|███████▍  | 1480/2000 [01:19<00:28, 18.52it/s]

Epoch 9:  74%|███████▍  | 1482/2000 [01:19<00:27, 18.52it/s]

Epoch 9:  74%|███████▍  | 1484/2000 [01:20<00:27, 18.53it/s]

Epoch 9:  74%|███████▍  | 1486/2000 [01:20<00:27, 18.54it/s]

Epoch 9:  74%|███████▍  | 1488/2000 [01:20<00:27, 18.55it/s]

Epoch 9:  74%|███████▍  | 1490/2000 [01:20<00:27, 18.55it/s]

Epoch 9:  75%|███████▍  | 1492/2000 [01:20<00:27, 18.54it/s]

Epoch 9:  75%|███████▍  | 1494/2000 [01:20<00:27, 18.54it/s]

Epoch 9:  75%|███████▍  | 1496/2000 [01:20<00:27, 18.54it/s]

Epoch 9:  75%|███████▍  | 1498/2000 [01:20<00:27, 18.55it/s]

Epoch 9:  75%|███████▌  | 1500/2000 [01:20<00:26, 18.55it/s]

Epoch 9:  75%|███████▌  | 1502/2000 [01:21<00:26, 18.56it/s]

Epoch 9:  75%|███████▌  | 1504/2000 [01:21<00:26, 18.55it/s]

Epoch 9:  75%|███████▌  | 1506/2000 [01:21<00:26, 18.56it/s]

Epoch 9:  75%|███████▌  | 1508/2000 [01:21<00:26, 18.56it/s]

Epoch 9:  76%|███████▌  | 1510/2000 [01:21<00:26, 18.57it/s]

Epoch 9:  76%|███████▌  | 1512/2000 [01:21<00:26, 18.56it/s]

Epoch 9:  76%|███████▌  | 1514/2000 [01:21<00:26, 18.55it/s]

Epoch 9:  76%|███████▌  | 1516/2000 [01:21<00:26, 18.55it/s]

Epoch 9:  76%|███████▌  | 1518/2000 [01:21<00:25, 18.55it/s]

Epoch 9:  76%|███████▌  | 1520/2000 [01:22<00:25, 18.54it/s]

Epoch 9:  76%|███████▌  | 1522/2000 [01:22<00:25, 18.56it/s]

Epoch 9:  76%|███████▌  | 1524/2000 [01:22<00:25, 18.56it/s]

Epoch 9:  76%|███████▋  | 1526/2000 [01:22<00:25, 18.57it/s]

Epoch 9:  76%|███████▋  | 1528/2000 [01:22<00:25, 18.56it/s]

Epoch 9:  76%|███████▋  | 1530/2000 [01:22<00:25, 18.56it/s]

Epoch 9:  77%|███████▋  | 1532/2000 [01:22<00:25, 18.55it/s]

Epoch 9:  77%|███████▋  | 1534/2000 [01:22<00:25, 18.56it/s]

Epoch 9:  77%|███████▋  | 1536/2000 [01:22<00:24, 18.56it/s]

Epoch 9:  77%|███████▋  | 1538/2000 [01:22<00:24, 18.56it/s]

Epoch 9:  77%|███████▋  | 1540/2000 [01:23<00:24, 18.56it/s]

Epoch 9:  77%|███████▋  | 1542/2000 [01:23<00:24, 18.55it/s]

Epoch 9:  77%|███████▋  | 1544/2000 [01:23<00:24, 18.55it/s]

Epoch 9:  77%|███████▋  | 1546/2000 [01:23<00:24, 18.55it/s]

Epoch 9:  77%|███████▋  | 1548/2000 [01:23<00:24, 18.56it/s]

Epoch 9:  78%|███████▊  | 1550/2000 [01:23<00:24, 18.55it/s]

Epoch 9:  78%|███████▊  | 1552/2000 [01:23<00:24, 18.54it/s]

Epoch 9:  78%|███████▊  | 1554/2000 [01:23<00:24, 18.53it/s]

Epoch 9:  78%|███████▊  | 1556/2000 [01:23<00:23, 18.53it/s]

Epoch 9:  78%|███████▊  | 1558/2000 [01:24<00:23, 18.52it/s]

Epoch 9:  78%|███████▊  | 1560/2000 [01:24<00:23, 18.45it/s]

Epoch 9:  78%|███████▊  | 1562/2000 [01:24<00:23, 18.47it/s]

Epoch 9:  78%|███████▊  | 1564/2000 [01:24<00:23, 18.49it/s]

Epoch 9:  78%|███████▊  | 1566/2000 [01:24<00:23, 18.50it/s]

Epoch 9:  78%|███████▊  | 1568/2000 [01:24<00:23, 18.51it/s]

Epoch 9:  78%|███████▊  | 1570/2000 [01:24<00:23, 18.52it/s]

Epoch 9:  79%|███████▊  | 1572/2000 [01:24<00:23, 18.53it/s]

Epoch 9:  79%|███████▊  | 1574/2000 [01:24<00:22, 18.53it/s]

Epoch 9:  79%|███████▉  | 1576/2000 [01:25<00:22, 18.50it/s]

Epoch 9:  79%|███████▉  | 1578/2000 [01:25<00:22, 18.51it/s]

Epoch 9:  79%|███████▉  | 1580/2000 [01:25<00:22, 18.52it/s]

Epoch 9:  79%|███████▉  | 1582/2000 [01:25<00:22, 18.53it/s]

Epoch 9:  79%|███████▉  | 1584/2000 [01:25<00:22, 18.54it/s]

Epoch 9:  79%|███████▉  | 1586/2000 [01:25<00:22, 18.55it/s]

Epoch 9:  79%|███████▉  | 1588/2000 [01:25<00:22, 18.53it/s]

Epoch 9:  80%|███████▉  | 1590/2000 [01:25<00:22, 18.33it/s]

Epoch 9:  80%|███████▉  | 1592/2000 [01:25<00:22, 18.39it/s]

Epoch 9:  80%|███████▉  | 1594/2000 [01:26<00:22, 18.45it/s]

Epoch 9:  80%|███████▉  | 1596/2000 [01:26<00:21, 18.48it/s]

Epoch 9:  80%|███████▉  | 1598/2000 [01:26<00:21, 18.50it/s]

Epoch 9:  80%|████████  | 1600/2000 [01:26<00:21, 18.52it/s]

Epoch 9:  80%|████████  | 1602/2000 [01:26<00:21, 18.53it/s]

Epoch 9:  80%|████████  | 1604/2000 [01:26<00:21, 18.53it/s]

Epoch 9:  80%|████████  | 1606/2000 [01:26<00:21, 18.54it/s]

Epoch 9:  80%|████████  | 1608/2000 [01:26<00:21, 18.55it/s]

Epoch 9:  80%|████████  | 1610/2000 [01:26<00:21, 18.32it/s]

Epoch 9:  81%|████████  | 1612/2000 [01:26<00:21, 18.39it/s]

Epoch 9:  81%|████████  | 1614/2000 [01:27<00:20, 18.44it/s]

Epoch 9:  81%|████████  | 1616/2000 [01:27<00:20, 18.47it/s]

Epoch 9:  81%|████████  | 1618/2000 [01:27<00:20, 18.48it/s]

Epoch 9:  81%|████████  | 1620/2000 [01:27<00:20, 18.51it/s]

Epoch 9:  81%|████████  | 1622/2000 [01:27<00:20, 18.51it/s]

Epoch 9:  81%|████████  | 1624/2000 [01:27<00:20, 18.51it/s]

Epoch 9:  81%|████████▏ | 1626/2000 [01:27<00:20, 18.51it/s]

Epoch 9:  81%|████████▏ | 1628/2000 [01:27<00:20, 18.52it/s]

Epoch 9:  82%|████████▏ | 1630/2000 [01:27<00:19, 18.53it/s]

Epoch 9:  82%|████████▏ | 1632/2000 [01:28<00:19, 18.52it/s]

Epoch 9:  82%|████████▏ | 1634/2000 [01:28<00:19, 18.53it/s]

Epoch 9:  82%|████████▏ | 1636/2000 [01:28<00:19, 18.54it/s]

Epoch 9:  82%|████████▏ | 1638/2000 [01:28<00:19, 18.54it/s]

Epoch 9:  82%|████████▏ | 1640/2000 [01:28<00:19, 18.54it/s]

Epoch 9:  82%|████████▏ | 1642/2000 [01:28<00:19, 18.54it/s]

Epoch 9:  82%|████████▏ | 1644/2000 [01:28<00:19, 18.55it/s]

Epoch 9:  82%|████████▏ | 1646/2000 [01:28<00:19, 18.55it/s]

Epoch 9:  82%|████████▏ | 1648/2000 [01:28<00:18, 18.56it/s]

Epoch 9:  82%|████████▎ | 1650/2000 [01:29<00:18, 18.55it/s]

Epoch 9:  83%|████████▎ | 1652/2000 [01:29<00:18, 18.55it/s]

Epoch 9:  83%|████████▎ | 1654/2000 [01:29<00:18, 18.55it/s]

Epoch 9:  83%|████████▎ | 1656/2000 [01:29<00:18, 18.56it/s]

Epoch 9:  83%|████████▎ | 1658/2000 [01:29<00:18, 18.56it/s]

Epoch 9:  83%|████████▎ | 1660/2000 [01:29<00:18, 18.55it/s]

Epoch 9:  83%|████████▎ | 1662/2000 [01:29<00:18, 18.55it/s]

Epoch 9:  83%|████████▎ | 1664/2000 [01:29<00:18, 18.55it/s]

Epoch 9:  83%|████████▎ | 1666/2000 [01:29<00:18, 18.54it/s]

Epoch 9:  83%|████████▎ | 1668/2000 [01:30<00:17, 18.54it/s]

Epoch 9:  84%|████████▎ | 1670/2000 [01:30<00:17, 18.53it/s]

Epoch 9:  84%|████████▎ | 1672/2000 [01:30<00:17, 18.54it/s]

Epoch 9:  84%|████████▎ | 1674/2000 [01:30<00:17, 18.55it/s]

Epoch 9:  84%|████████▍ | 1676/2000 [01:30<00:17, 18.55it/s]

Epoch 9:  84%|████████▍ | 1678/2000 [01:30<00:17, 18.56it/s]

Epoch 9:  84%|████████▍ | 1680/2000 [01:30<00:17, 18.55it/s]

Epoch 9:  84%|████████▍ | 1682/2000 [01:30<00:17, 18.56it/s]

Epoch 9:  84%|████████▍ | 1684/2000 [01:30<00:17, 18.56it/s]

Epoch 9:  84%|████████▍ | 1686/2000 [01:30<00:16, 18.55it/s]

Epoch 9:  84%|████████▍ | 1688/2000 [01:31<00:16, 18.56it/s]

Epoch 9:  84%|████████▍ | 1690/2000 [01:31<00:16, 18.55it/s]

Epoch 9:  85%|████████▍ | 1692/2000 [01:31<00:16, 18.55it/s]

Epoch 9:  85%|████████▍ | 1694/2000 [01:31<00:16, 18.55it/s]

Epoch 9:  85%|████████▍ | 1696/2000 [01:31<00:16, 18.56it/s]

Epoch 9:  85%|████████▍ | 1698/2000 [01:31<00:16, 18.54it/s]

Epoch 9:  85%|████████▌ | 1700/2000 [01:31<00:16, 18.53it/s]

Epoch 9:  85%|████████▌ | 1702/2000 [01:31<00:16, 18.53it/s]

Epoch 9:  85%|████████▌ | 1704/2000 [01:31<00:15, 18.53it/s]

Epoch 9:  85%|████████▌ | 1706/2000 [01:32<00:15, 18.53it/s]

Epoch 9:  85%|████████▌ | 1708/2000 [01:32<00:15, 18.55it/s]

Epoch 9:  86%|████████▌ | 1710/2000 [01:32<00:15, 18.54it/s]

Epoch 9:  86%|████████▌ | 1712/2000 [01:32<00:15, 18.55it/s]

Epoch 9:  86%|████████▌ | 1714/2000 [01:32<00:15, 18.55it/s]

Epoch 9:  86%|████████▌ | 1716/2000 [01:32<00:15, 18.55it/s]

Epoch 9:  86%|████████▌ | 1718/2000 [01:32<00:15, 18.55it/s]

Epoch 9:  86%|████████▌ | 1720/2000 [01:32<00:15, 18.54it/s]

Epoch 9:  86%|████████▌ | 1722/2000 [01:32<00:15, 18.52it/s]

Epoch 9:  86%|████████▌ | 1724/2000 [01:33<00:15, 18.37it/s]

Epoch 9:  86%|████████▋ | 1726/2000 [01:33<00:15, 17.78it/s]

Epoch 9:  86%|████████▋ | 1728/2000 [01:33<00:15, 17.79it/s]

Epoch 9:  86%|████████▋ | 1730/2000 [01:33<00:15, 17.97it/s]

Epoch 9:  87%|████████▋ | 1732/2000 [01:33<00:14, 18.09it/s]

Epoch 9:  87%|████████▋ | 1734/2000 [01:33<00:14, 18.17it/s]

Epoch 9:  87%|████████▋ | 1736/2000 [01:33<00:14, 18.26it/s]

Epoch 9:  87%|████████▋ | 1738/2000 [01:33<00:14, 18.33it/s]

Epoch 9:  87%|████████▋ | 1740/2000 [01:33<00:14, 18.38it/s]

Epoch 9:  87%|████████▋ | 1742/2000 [01:34<00:14, 18.42it/s]

Epoch 9:  87%|████████▋ | 1744/2000 [01:34<00:13, 18.44it/s]

Epoch 9:  87%|████████▋ | 1746/2000 [01:34<00:13, 18.46it/s]

Epoch 9:  87%|████████▋ | 1748/2000 [01:34<00:13, 18.48it/s]

Epoch 9:  88%|████████▊ | 1750/2000 [01:34<00:13, 18.49it/s]

Epoch 9:  88%|████████▊ | 1752/2000 [01:34<00:13, 18.51it/s]

Epoch 9:  88%|████████▊ | 1754/2000 [01:34<00:13, 18.52it/s]

Epoch 9:  88%|████████▊ | 1756/2000 [01:34<00:13, 18.53it/s]

Epoch 9:  88%|████████▊ | 1758/2000 [01:34<00:13, 18.54it/s]

Epoch 9:  88%|████████▊ | 1760/2000 [01:35<00:12, 18.54it/s]

Epoch 9:  88%|████████▊ | 1762/2000 [01:35<00:12, 18.55it/s]

Epoch 9:  88%|████████▊ | 1764/2000 [01:35<00:12, 18.55it/s]

Epoch 9:  88%|████████▊ | 1766/2000 [01:35<00:12, 18.56it/s]

Epoch 9:  88%|████████▊ | 1768/2000 [01:35<00:12, 18.56it/s]

Epoch 9:  88%|████████▊ | 1770/2000 [01:35<00:12, 18.56it/s]

Epoch 9:  89%|████████▊ | 1772/2000 [01:35<00:12, 18.56it/s]

Epoch 9:  89%|████████▊ | 1774/2000 [01:35<00:12, 18.56it/s]

Epoch 9:  89%|████████▉ | 1776/2000 [01:35<00:12, 18.55it/s]

Epoch 9:  89%|████████▉ | 1778/2000 [01:35<00:11, 18.54it/s]

Epoch 9:  89%|████████▉ | 1780/2000 [01:36<00:11, 18.54it/s]

Epoch 9:  89%|████████▉ | 1782/2000 [01:36<00:11, 18.55it/s]

Epoch 9:  89%|████████▉ | 1784/2000 [01:36<00:11, 18.56it/s]

Epoch 9:  89%|████████▉ | 1786/2000 [01:36<00:11, 18.56it/s]

Epoch 9:  89%|████████▉ | 1788/2000 [01:36<00:11, 18.57it/s]

Epoch 9:  90%|████████▉ | 1790/2000 [01:36<00:11, 18.57it/s]

Epoch 9:  90%|████████▉ | 1792/2000 [01:36<00:11, 18.57it/s]

Epoch 9:  90%|████████▉ | 1794/2000 [01:36<00:11, 18.55it/s]

Epoch 9:  90%|████████▉ | 1796/2000 [01:36<00:10, 18.55it/s]

Epoch 9:  90%|████████▉ | 1798/2000 [01:37<00:10, 18.54it/s]

Epoch 9:  90%|█████████ | 1800/2000 [01:37<00:10, 18.56it/s]

Epoch 9:  90%|█████████ | 1802/2000 [01:37<00:10, 18.57it/s]

Epoch 9:  90%|█████████ | 1804/2000 [01:37<00:10, 18.57it/s]

Epoch 9:  90%|█████████ | 1806/2000 [01:37<00:10, 18.57it/s]

Epoch 9:  90%|█████████ | 1808/2000 [01:37<00:10, 18.56it/s]

Epoch 9:  90%|█████████ | 1810/2000 [01:37<00:10, 18.55it/s]

Epoch 9:  91%|█████████ | 1812/2000 [01:37<00:10, 18.55it/s]

Epoch 9:  91%|█████████ | 1814/2000 [01:37<00:10, 18.55it/s]

Epoch 9:  91%|█████████ | 1816/2000 [01:38<00:09, 18.56it/s]

Epoch 9:  91%|█████████ | 1818/2000 [01:38<00:09, 18.54it/s]

Epoch 9:  91%|█████████ | 1820/2000 [01:38<00:09, 18.54it/s]

Epoch 9:  91%|█████████ | 1822/2000 [01:38<00:09, 18.56it/s]

Epoch 9:  91%|█████████ | 1824/2000 [01:38<00:09, 18.54it/s]

Epoch 9:  91%|█████████▏| 1826/2000 [01:38<00:09, 18.51it/s]

Epoch 9:  91%|█████████▏| 1828/2000 [01:38<00:09, 18.53it/s]

Epoch 9:  92%|█████████▏| 1830/2000 [01:38<00:09, 18.54it/s]

Epoch 9:  92%|█████████▏| 1832/2000 [01:38<00:09, 18.54it/s]

Epoch 9:  92%|█████████▏| 1834/2000 [01:38<00:08, 18.54it/s]

Epoch 9:  92%|█████████▏| 1836/2000 [01:39<00:08, 18.54it/s]

Epoch 9:  92%|█████████▏| 1838/2000 [01:39<00:08, 18.54it/s]

Epoch 9:  92%|█████████▏| 1840/2000 [01:39<00:08, 18.53it/s]

Epoch 9:  92%|█████████▏| 1842/2000 [01:39<00:08, 18.52it/s]

Epoch 9:  92%|█████████▏| 1844/2000 [01:39<00:08, 18.52it/s]

Epoch 9:  92%|█████████▏| 1846/2000 [01:39<00:08, 18.53it/s]

Epoch 9:  92%|█████████▏| 1848/2000 [01:39<00:08, 18.52it/s]

Epoch 9:  92%|█████████▎| 1850/2000 [01:39<00:08, 18.52it/s]

Epoch 9:  93%|█████████▎| 1852/2000 [01:39<00:07, 18.53it/s]

Epoch 9:  93%|█████████▎| 1854/2000 [01:40<00:07, 18.54it/s]

Epoch 9:  93%|█████████▎| 1856/2000 [01:40<00:07, 18.55it/s]

Epoch 9:  93%|█████████▎| 1858/2000 [01:40<00:07, 18.55it/s]

Epoch 9:  93%|█████████▎| 1860/2000 [01:40<00:07, 18.56it/s]

Epoch 9:  93%|█████████▎| 1862/2000 [01:40<00:07, 18.56it/s]

Epoch 9:  93%|█████████▎| 1864/2000 [01:40<00:07, 18.55it/s]

Epoch 9:  93%|█████████▎| 1866/2000 [01:40<00:07, 18.56it/s]

Epoch 9:  93%|█████████▎| 1868/2000 [01:40<00:07, 18.56it/s]

Epoch 9:  94%|█████████▎| 1870/2000 [01:40<00:07, 18.56it/s]

Epoch 9:  94%|█████████▎| 1872/2000 [01:41<00:06, 18.55it/s]

Epoch 9:  94%|█████████▎| 1874/2000 [01:41<00:06, 18.56it/s]

Epoch 9:  94%|█████████▍| 1876/2000 [01:41<00:06, 18.54it/s]

Epoch 9:  94%|█████████▍| 1878/2000 [01:41<00:06, 18.54it/s]

Epoch 9:  94%|█████████▍| 1880/2000 [01:41<00:06, 18.54it/s]

Epoch 9:  94%|█████████▍| 1882/2000 [01:41<00:06, 18.55it/s]

Epoch 9:  94%|█████████▍| 1884/2000 [01:41<00:06, 18.55it/s]

Epoch 9:  94%|█████████▍| 1886/2000 [01:41<00:06, 18.55it/s]

Epoch 9:  94%|█████████▍| 1888/2000 [01:41<00:06, 18.57it/s]

Epoch 9:  94%|█████████▍| 1890/2000 [01:42<00:05, 18.55it/s]

Epoch 9:  95%|█████████▍| 1892/2000 [01:42<00:05, 18.55it/s]

Epoch 9:  95%|█████████▍| 1894/2000 [01:42<00:05, 18.56it/s]

Epoch 9:  95%|█████████▍| 1896/2000 [01:42<00:05, 18.53it/s]

Epoch 9:  95%|█████████▍| 1898/2000 [01:42<00:05, 18.53it/s]

Epoch 9:  95%|█████████▌| 1900/2000 [01:42<00:05, 18.54it/s]

Epoch 9:  95%|█████████▌| 1902/2000 [01:42<00:05, 18.54it/s]

Epoch 9:  95%|█████████▌| 1904/2000 [01:42<00:05, 18.54it/s]

Epoch 9:  95%|█████████▌| 1906/2000 [01:42<00:05, 18.53it/s]

Epoch 9:  95%|█████████▌| 1908/2000 [01:42<00:04, 18.53it/s]

Epoch 9:  96%|█████████▌| 1910/2000 [01:43<00:04, 18.54it/s]

Epoch 9:  96%|█████████▌| 1912/2000 [01:43<00:04, 18.54it/s]

Epoch 9:  96%|█████████▌| 1914/2000 [01:43<00:04, 18.54it/s]

Epoch 9:  96%|█████████▌| 1916/2000 [01:43<00:04, 18.54it/s]

Epoch 9:  96%|█████████▌| 1918/2000 [01:43<00:04, 18.54it/s]

Epoch 9:  96%|█████████▌| 1920/2000 [01:43<00:04, 18.56it/s]

Epoch 9:  96%|█████████▌| 1922/2000 [01:43<00:04, 18.55it/s]

Epoch 9:  96%|█████████▌| 1924/2000 [01:43<00:04, 18.54it/s]

Epoch 9:  96%|█████████▋| 1926/2000 [01:43<00:03, 18.54it/s]

Epoch 9:  96%|█████████▋| 1928/2000 [01:44<00:03, 18.54it/s]

Epoch 9:  96%|█████████▋| 1930/2000 [01:44<00:03, 18.55it/s]

Epoch 9:  97%|█████████▋| 1932/2000 [01:44<00:03, 18.55it/s]

Epoch 9:  97%|█████████▋| 1934/2000 [01:44<00:03, 18.56it/s]

Epoch 9:  97%|█████████▋| 1936/2000 [01:44<00:03, 18.56it/s]

Epoch 9:  97%|█████████▋| 1938/2000 [01:44<00:03, 18.57it/s]

Epoch 9:  97%|█████████▋| 1940/2000 [01:44<00:03, 18.56it/s]

Epoch 9:  97%|█████████▋| 1942/2000 [01:44<00:03, 18.56it/s]

Epoch 9:  97%|█████████▋| 1944/2000 [01:44<00:03, 18.55it/s]

Epoch 9:  97%|█████████▋| 1946/2000 [01:45<00:02, 18.55it/s]

Epoch 9:  97%|█████████▋| 1948/2000 [01:45<00:02, 18.56it/s]

Epoch 9:  98%|█████████▊| 1950/2000 [01:45<00:02, 18.54it/s]

Epoch 9:  98%|█████████▊| 1952/2000 [01:45<00:02, 18.55it/s]

Epoch 9:  98%|█████████▊| 1954/2000 [01:45<00:02, 18.56it/s]

Epoch 9:  98%|█████████▊| 1956/2000 [01:45<00:02, 18.57it/s]

Epoch 9:  98%|█████████▊| 1958/2000 [01:45<00:02, 18.57it/s]

Epoch 9:  98%|█████████▊| 1960/2000 [01:45<00:02, 18.56it/s]

Epoch 9:  98%|█████████▊| 1962/2000 [01:45<00:02, 18.56it/s]

Epoch 9:  98%|█████████▊| 1964/2000 [01:46<00:01, 18.55it/s]

Epoch 9:  98%|█████████▊| 1966/2000 [01:46<00:01, 18.54it/s]

Epoch 9:  98%|█████████▊| 1968/2000 [01:46<00:01, 18.55it/s]

Epoch 9:  98%|█████████▊| 1970/2000 [01:46<00:01, 18.57it/s]

Epoch 9:  99%|█████████▊| 1972/2000 [01:46<00:01, 18.57it/s]

Epoch 9:  99%|█████████▊| 1974/2000 [01:46<00:01, 18.57it/s]

Epoch 9:  99%|█████████▉| 1976/2000 [01:46<00:01, 18.55it/s]

Epoch 9:  99%|█████████▉| 1978/2000 [01:46<00:01, 18.55it/s]

Epoch 9:  99%|█████████▉| 1980/2000 [01:46<00:01, 18.34it/s]

Epoch 9:  99%|█████████▉| 1982/2000 [01:46<00:00, 18.40it/s]

Epoch 9:  99%|█████████▉| 1984/2000 [01:47<00:00, 18.44it/s]

Epoch 9:  99%|█████████▉| 1986/2000 [01:47<00:00, 18.48it/s]

Epoch 9:  99%|█████████▉| 1988/2000 [01:47<00:00, 18.50it/s]

Epoch 9: 100%|█████████▉| 1990/2000 [01:47<00:00, 18.51it/s]

Epoch 9: 100%|█████████▉| 1992/2000 [01:47<00:00, 18.51it/s]

Epoch 9: 100%|█████████▉| 1994/2000 [01:47<00:00, 18.54it/s]

Epoch 9: 100%|█████████▉| 1996/2000 [01:47<00:00, 18.53it/s]

Epoch 9: 100%|█████████▉| 1998/2000 [01:47<00:00, 18.52it/s]

Epoch 9: 100%|██████████| 2000/2000 [01:47<00:00, 18.53it/s]

Epoch 9: loss=0.1891, val_proxy=0.9327

Epoch 10:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 10:   0%|          | 2/2000 [00:00<01:50, 18.14it/s]

Epoch 10:   0%|          | 4/2000 [00:00<01:48, 18.37it/s]

Epoch 10:   0%|          | 6/2000 [00:00<01:48, 18.45it/s]

Epoch 10:   0%|          | 8/2000 [00:00<01:47, 18.46it/s]

Epoch 10:   0%|          | 10/2000 [00:00<01:47, 18.46it/s]

Epoch 10:   1%|          | 12/2000 [00:00<01:47, 18.47it/s]

Epoch 10:   1%|          | 14/2000 [00:00<01:47, 18.47it/s]

Epoch 10:   1%|          | 16/2000 [00:00<01:47, 18.48it/s]

Epoch 10:   1%|          | 18/2000 [00:00<01:47, 18.50it/s]

Epoch 10:   1%|          | 20/2000 [00:01<01:46, 18.51it/s]

Epoch 10:   1%|          | 22/2000 [00:01<01:47, 18.39it/s]

Epoch 10:   1%|          | 24/2000 [00:01<01:47, 18.39it/s]

Epoch 10:   1%|▏         | 26/2000 [00:01<01:47, 18.43it/s]

Epoch 10:   1%|▏         | 28/2000 [00:01<01:46, 18.47it/s]

Epoch 10:   2%|▏         | 30/2000 [00:01<01:46, 18.55it/s]

Epoch 10:   2%|▏         | 32/2000 [00:01<01:45, 18.59it/s]

Epoch 10:   2%|▏         | 34/2000 [00:01<01:45, 18.61it/s]

Epoch 10:   2%|▏         | 36/2000 [00:01<01:45, 18.65it/s]

Epoch 10:   2%|▏         | 38/2000 [00:02<01:44, 18.69it/s]

Epoch 10:   2%|▏         | 40/2000 [00:02<01:44, 18.71it/s]

Epoch 10:   2%|▏         | 42/2000 [00:02<01:44, 18.70it/s]

Epoch 10:   2%|▏         | 44/2000 [00:02<01:44, 18.70it/s]

Epoch 10:   2%|▏         | 46/2000 [00:02<01:44, 18.71it/s]

Epoch 10:   2%|▏         | 48/2000 [00:02<01:44, 18.72it/s]

Epoch 10:   2%|▎         | 50/2000 [00:02<01:44, 18.73it/s]

Epoch 10:   3%|▎         | 52/2000 [00:02<01:44, 18.73it/s]

Epoch 10:   3%|▎         | 54/2000 [00:02<01:43, 18.73it/s]

Epoch 10:   3%|▎         | 56/2000 [00:03<01:43, 18.72it/s]

Epoch 10:   3%|▎         | 58/2000 [00:03<01:43, 18.73it/s]

Epoch 10:   3%|▎         | 60/2000 [00:03<01:43, 18.73it/s]

Epoch 10:   3%|▎         | 62/2000 [00:03<01:43, 18.73it/s]

Epoch 10:   3%|▎         | 64/2000 [00:03<01:43, 18.73it/s]

Epoch 10:   3%|▎         | 66/2000 [00:03<01:43, 18.73it/s]

Epoch 10:   3%|▎         | 68/2000 [00:03<01:43, 18.72it/s]

Epoch 10:   4%|▎         | 70/2000 [00:03<01:43, 18.74it/s]

Epoch 10:   4%|▎         | 72/2000 [00:03<01:42, 18.72it/s]

Epoch 10:   4%|▎         | 74/2000 [00:03<01:42, 18.72it/s]

Epoch 10:   4%|▍         | 76/2000 [00:04<01:42, 18.73it/s]

Epoch 10:   4%|▍         | 78/2000 [00:04<01:42, 18.74it/s]

Epoch 10:   4%|▍         | 80/2000 [00:04<01:42, 18.74it/s]

Epoch 10:   4%|▍         | 82/2000 [00:04<01:42, 18.73it/s]

Epoch 10:   4%|▍         | 84/2000 [00:04<01:42, 18.75it/s]

Epoch 10:   4%|▍         | 86/2000 [00:04<01:42, 18.75it/s]

Epoch 10:   4%|▍         | 88/2000 [00:04<01:42, 18.74it/s]

Epoch 10:   4%|▍         | 90/2000 [00:04<01:41, 18.74it/s]

Epoch 10:   5%|▍         | 92/2000 [00:04<01:41, 18.73it/s]

Epoch 10:   5%|▍         | 94/2000 [00:05<01:41, 18.73it/s]

Epoch 10:   5%|▍         | 96/2000 [00:05<01:41, 18.73it/s]

Epoch 10:   5%|▍         | 98/2000 [00:05<01:41, 18.73it/s]

Epoch 10:   5%|▌         | 100/2000 [00:05<01:41, 18.75it/s]

Epoch 10:   5%|▌         | 102/2000 [00:05<01:41, 18.75it/s]

Epoch 10:   5%|▌         | 104/2000 [00:05<01:41, 18.70it/s]

Epoch 10:   5%|▌         | 106/2000 [00:05<01:41, 18.71it/s]

Epoch 10:   5%|▌         | 108/2000 [00:05<01:41, 18.72it/s]

Epoch 10:   6%|▌         | 110/2000 [00:05<01:40, 18.73it/s]

Epoch 10:   6%|▌         | 112/2000 [00:06<01:40, 18.75it/s]

Epoch 10:   6%|▌         | 114/2000 [00:06<01:40, 18.77it/s]

Epoch 10:   6%|▌         | 116/2000 [00:06<01:40, 18.77it/s]

Epoch 10:   6%|▌         | 118/2000 [00:06<01:40, 18.78it/s]

Epoch 10:   6%|▌         | 120/2000 [00:06<01:40, 18.79it/s]

Epoch 10:   6%|▌         | 122/2000 [00:06<01:39, 18.80it/s]

Epoch 10:   6%|▌         | 124/2000 [00:06<01:39, 18.80it/s]

Epoch 10:   6%|▋         | 126/2000 [00:06<01:39, 18.79it/s]

Epoch 10:   6%|▋         | 128/2000 [00:06<01:39, 18.79it/s]

Epoch 10:   6%|▋         | 130/2000 [00:06<01:39, 18.79it/s]

Epoch 10:   7%|▋         | 132/2000 [00:07<01:39, 18.79it/s]

Epoch 10:   7%|▋         | 134/2000 [00:07<01:39, 18.79it/s]

Epoch 10:   7%|▋         | 136/2000 [00:07<01:39, 18.80it/s]

Epoch 10:   7%|▋         | 138/2000 [00:07<01:39, 18.81it/s]

Epoch 10:   7%|▋         | 140/2000 [00:07<01:38, 18.80it/s]

Epoch 10:   7%|▋         | 142/2000 [00:07<01:38, 18.78it/s]

Epoch 10:   7%|▋         | 144/2000 [00:07<01:38, 18.79it/s]

Epoch 10:   7%|▋         | 146/2000 [00:07<01:38, 18.79it/s]

Epoch 10:   7%|▋         | 148/2000 [00:07<01:38, 18.79it/s]

Epoch 10:   8%|▊         | 150/2000 [00:08<01:38, 18.79it/s]

Epoch 10:   8%|▊         | 152/2000 [00:08<01:38, 18.79it/s]

Epoch 10:   8%|▊         | 154/2000 [00:08<01:38, 18.79it/s]

Epoch 10:   8%|▊         | 156/2000 [00:08<01:38, 18.78it/s]

Epoch 10:   8%|▊         | 158/2000 [00:08<01:37, 18.80it/s]

Epoch 10:   8%|▊         | 160/2000 [00:08<01:37, 18.78it/s]

Epoch 10:   8%|▊         | 162/2000 [00:08<01:37, 18.79it/s]

Epoch 10:   8%|▊         | 164/2000 [00:08<01:37, 18.79it/s]

Epoch 10:   8%|▊         | 166/2000 [00:08<01:37, 18.74it/s]

Epoch 10:   8%|▊         | 168/2000 [00:08<01:37, 18.73it/s]

Epoch 10:   8%|▊         | 170/2000 [00:09<01:37, 18.71it/s]

Epoch 10:   9%|▊         | 172/2000 [00:09<01:37, 18.72it/s]

Epoch 10:   9%|▊         | 174/2000 [00:09<01:37, 18.72it/s]

Epoch 10:   9%|▉         | 176/2000 [00:09<01:37, 18.71it/s]

Epoch 10:   9%|▉         | 178/2000 [00:09<01:37, 18.71it/s]

Epoch 10:   9%|▉         | 180/2000 [00:09<01:37, 18.72it/s]

Epoch 10:   9%|▉         | 182/2000 [00:09<01:37, 18.72it/s]

Epoch 10:   9%|▉         | 184/2000 [00:09<01:37, 18.71it/s]

Epoch 10:   9%|▉         | 186/2000 [00:09<01:37, 18.69it/s]

Epoch 10:   9%|▉         | 188/2000 [00:10<01:36, 18.70it/s]

Epoch 10:  10%|▉         | 190/2000 [00:10<01:36, 18.71it/s]

Epoch 10:  10%|▉         | 192/2000 [00:10<01:37, 18.61it/s]

Epoch 10:  10%|▉         | 194/2000 [00:10<01:37, 18.61it/s]

Epoch 10:  10%|▉         | 196/2000 [00:10<01:36, 18.63it/s]

Epoch 10:  10%|▉         | 198/2000 [00:10<01:37, 18.45it/s]

Epoch 10:  10%|█         | 200/2000 [00:10<01:37, 18.51it/s]

Epoch 10:  10%|█         | 202/2000 [00:10<01:36, 18.58it/s]

Epoch 10:  10%|█         | 204/2000 [00:10<01:36, 18.62it/s]

Epoch 10:  10%|█         | 206/2000 [00:11<01:36, 18.64it/s]

Epoch 10:  10%|█         | 208/2000 [00:11<01:36, 18.65it/s]

Epoch 10:  10%|█         | 210/2000 [00:11<01:35, 18.67it/s]

Epoch 10:  11%|█         | 212/2000 [00:11<01:35, 18.68it/s]

Epoch 10:  11%|█         | 214/2000 [00:11<01:35, 18.69it/s]

Epoch 10:  11%|█         | 216/2000 [00:11<01:35, 18.69it/s]

Epoch 10:  11%|█         | 218/2000 [00:11<01:35, 18.70it/s]

Epoch 10:  11%|█         | 220/2000 [00:11<01:35, 18.69it/s]

Epoch 10:  11%|█         | 222/2000 [00:11<01:35, 18.69it/s]

Epoch 10:  11%|█         | 224/2000 [00:11<01:34, 18.71it/s]

Epoch 10:  11%|█▏        | 226/2000 [00:12<01:34, 18.72it/s]

Epoch 10:  11%|█▏        | 228/2000 [00:12<01:34, 18.72it/s]

Epoch 10:  12%|█▏        | 230/2000 [00:12<01:34, 18.72it/s]

Epoch 10:  12%|█▏        | 232/2000 [00:12<01:34, 18.71it/s]

Epoch 10:  12%|█▏        | 234/2000 [00:12<01:34, 18.72it/s]

Epoch 10:  12%|█▏        | 236/2000 [00:12<01:34, 18.72it/s]

Epoch 10:  12%|█▏        | 238/2000 [00:12<01:34, 18.73it/s]

Epoch 10:  12%|█▏        | 240/2000 [00:12<01:34, 18.72it/s]

Epoch 10:  12%|█▏        | 242/2000 [00:12<01:33, 18.72it/s]

Epoch 10:  12%|█▏        | 244/2000 [00:13<01:33, 18.72it/s]

Epoch 10:  12%|█▏        | 246/2000 [00:13<01:33, 18.71it/s]

Epoch 10:  12%|█▏        | 248/2000 [00:13<01:33, 18.70it/s]

Epoch 10:  12%|█▎        | 250/2000 [00:13<01:33, 18.70it/s]

Epoch 10:  13%|█▎        | 252/2000 [00:13<01:33, 18.70it/s]

Epoch 10:  13%|█▎        | 254/2000 [00:13<01:33, 18.69it/s]

Epoch 10:  13%|█▎        | 256/2000 [00:13<01:33, 18.69it/s]

Epoch 10:  13%|█▎        | 258/2000 [00:13<01:33, 18.70it/s]

Epoch 10:  13%|█▎        | 260/2000 [00:13<01:33, 18.70it/s]

Epoch 10:  13%|█▎        | 262/2000 [00:14<01:32, 18.70it/s]

Epoch 10:  13%|█▎        | 264/2000 [00:14<01:32, 18.70it/s]

Epoch 10:  13%|█▎        | 266/2000 [00:14<01:32, 18.71it/s]

Epoch 10:  13%|█▎        | 268/2000 [00:14<01:32, 18.72it/s]

Epoch 10:  14%|█▎        | 270/2000 [00:14<01:32, 18.71it/s]

Epoch 10:  14%|█▎        | 272/2000 [00:14<01:32, 18.72it/s]

Epoch 10:  14%|█▎        | 274/2000 [00:14<01:32, 18.71it/s]

Epoch 10:  14%|█▍        | 276/2000 [00:14<01:32, 18.71it/s]

Epoch 10:  14%|█▍        | 278/2000 [00:14<01:32, 18.71it/s]

Epoch 10:  14%|█▍        | 280/2000 [00:14<01:31, 18.71it/s]

Epoch 10:  14%|█▍        | 282/2000 [00:15<01:31, 18.72it/s]

Epoch 10:  14%|█▍        | 284/2000 [00:15<01:31, 18.72it/s]

Epoch 10:  14%|█▍        | 286/2000 [00:15<01:31, 18.72it/s]

Epoch 10:  14%|█▍        | 288/2000 [00:15<01:31, 18.71it/s]

Epoch 10:  14%|█▍        | 290/2000 [00:15<01:31, 18.72it/s]

Epoch 10:  15%|█▍        | 292/2000 [00:15<01:31, 18.71it/s]

Epoch 10:  15%|█▍        | 294/2000 [00:15<01:31, 18.72it/s]

Epoch 10:  15%|█▍        | 296/2000 [00:15<01:31, 18.72it/s]

Epoch 10:  15%|█▍        | 298/2000 [00:15<01:30, 18.71it/s]

Epoch 10:  15%|█▌        | 300/2000 [00:16<01:30, 18.72it/s]

Epoch 10:  15%|█▌        | 302/2000 [00:16<01:30, 18.72it/s]

Epoch 10:  15%|█▌        | 304/2000 [00:16<01:30, 18.71it/s]

Epoch 10:  15%|█▌        | 306/2000 [00:16<01:30, 18.71it/s]

Epoch 10:  15%|█▌        | 308/2000 [00:16<01:30, 18.71it/s]

Epoch 10:  16%|█▌        | 310/2000 [00:16<01:30, 18.71it/s]

Epoch 10:  16%|█▌        | 312/2000 [00:16<01:30, 18.71it/s]

Epoch 10:  16%|█▌        | 314/2000 [00:16<01:30, 18.72it/s]

Epoch 10:  16%|█▌        | 316/2000 [00:16<01:30, 18.71it/s]

Epoch 10:  16%|█▌        | 318/2000 [00:17<01:29, 18.72it/s]

Epoch 10:  16%|█▌        | 320/2000 [00:17<01:29, 18.71it/s]

Epoch 10:  16%|█▌        | 322/2000 [00:17<01:29, 18.72it/s]

Epoch 10:  16%|█▌        | 324/2000 [00:17<01:29, 18.73it/s]

Epoch 10:  16%|█▋        | 326/2000 [00:17<01:29, 18.72it/s]

Epoch 10:  16%|█▋        | 328/2000 [00:17<01:29, 18.72it/s]

Epoch 10:  16%|█▋        | 330/2000 [00:17<01:29, 18.73it/s]

Epoch 10:  17%|█▋        | 332/2000 [00:17<01:29, 18.72it/s]

Epoch 10:  17%|█▋        | 334/2000 [00:17<01:29, 18.72it/s]

Epoch 10:  17%|█▋        | 336/2000 [00:17<01:28, 18.72it/s]

Epoch 10:  17%|█▋        | 338/2000 [00:18<01:28, 18.72it/s]

Epoch 10:  17%|█▋        | 340/2000 [00:18<01:28, 18.72it/s]

Epoch 10:  17%|█▋        | 342/2000 [00:18<01:28, 18.72it/s]

Epoch 10:  17%|█▋        | 344/2000 [00:18<01:28, 18.73it/s]

Epoch 10:  17%|█▋        | 346/2000 [00:18<01:28, 18.73it/s]

Epoch 10:  17%|█▋        | 348/2000 [00:18<01:28, 18.73it/s]

Epoch 10:  18%|█▊        | 350/2000 [00:18<01:28, 18.72it/s]

Epoch 10:  18%|█▊        | 352/2000 [00:18<01:28, 18.72it/s]

Epoch 10:  18%|█▊        | 354/2000 [00:18<01:27, 18.72it/s]

Epoch 10:  18%|█▊        | 356/2000 [00:19<01:27, 18.72it/s]

Epoch 10:  18%|█▊        | 358/2000 [00:19<01:27, 18.72it/s]

Epoch 10:  18%|█▊        | 360/2000 [00:19<01:27, 18.72it/s]

Epoch 10:  18%|█▊        | 362/2000 [00:19<01:27, 18.65it/s]

Epoch 10:  18%|█▊        | 364/2000 [00:19<01:27, 18.65it/s]

Epoch 10:  18%|█▊        | 366/2000 [00:19<01:27, 18.68it/s]

Epoch 10:  18%|█▊        | 368/2000 [00:19<01:27, 18.69it/s]

Epoch 10:  18%|█▊        | 370/2000 [00:19<01:27, 18.66it/s]

Epoch 10:  19%|█▊        | 372/2000 [00:19<01:27, 18.66it/s]

Epoch 10:  19%|█▊        | 374/2000 [00:20<01:27, 18.66it/s]

Epoch 10:  19%|█▉        | 376/2000 [00:20<01:26, 18.68it/s]

Epoch 10:  19%|█▉        | 378/2000 [00:20<01:26, 18.70it/s]

Epoch 10:  19%|█▉        | 380/2000 [00:20<01:26, 18.69it/s]

Epoch 10:  19%|█▉        | 382/2000 [00:20<01:26, 18.70it/s]

Epoch 10:  19%|█▉        | 384/2000 [00:20<01:26, 18.70it/s]

Epoch 10:  19%|█▉        | 386/2000 [00:20<01:26, 18.71it/s]

Epoch 10:  19%|█▉        | 388/2000 [00:20<01:26, 18.71it/s]

Epoch 10:  20%|█▉        | 390/2000 [00:20<01:26, 18.71it/s]

Epoch 10:  20%|█▉        | 392/2000 [00:20<01:25, 18.70it/s]

Epoch 10:  20%|█▉        | 394/2000 [00:21<01:25, 18.71it/s]

Epoch 10:  20%|█▉        | 396/2000 [00:21<01:25, 18.71it/s]

Epoch 10:  20%|█▉        | 398/2000 [00:21<01:25, 18.70it/s]

Epoch 10:  20%|██        | 400/2000 [00:21<01:25, 18.70it/s]

Epoch 10:  20%|██        | 402/2000 [00:21<01:25, 18.71it/s]

Epoch 10:  20%|██        | 404/2000 [00:21<01:25, 18.71it/s]

Epoch 10:  20%|██        | 406/2000 [00:21<01:25, 18.70it/s]

Epoch 10:  20%|██        | 408/2000 [00:21<01:25, 18.68it/s]

Epoch 10:  20%|██        | 410/2000 [00:21<01:25, 18.70it/s]

Epoch 10:  21%|██        | 412/2000 [00:22<01:24, 18.70it/s]

Epoch 10:  21%|██        | 414/2000 [00:22<01:24, 18.70it/s]

Epoch 10:  21%|██        | 416/2000 [00:22<01:24, 18.71it/s]

Epoch 10:  21%|██        | 418/2000 [00:22<01:24, 18.70it/s]

Epoch 10:  21%|██        | 420/2000 [00:22<01:24, 18.71it/s]

Epoch 10:  21%|██        | 422/2000 [00:22<01:24, 18.71it/s]

Epoch 10:  21%|██        | 424/2000 [00:22<01:24, 18.70it/s]

Epoch 10:  21%|██▏       | 426/2000 [00:22<01:24, 18.70it/s]

Epoch 10:  21%|██▏       | 428/2000 [00:22<01:24, 18.69it/s]

Epoch 10:  22%|██▏       | 430/2000 [00:22<01:23, 18.69it/s]

Epoch 10:  22%|██▏       | 432/2000 [00:23<01:23, 18.70it/s]

Epoch 10:  22%|██▏       | 434/2000 [00:23<01:23, 18.70it/s]

Epoch 10:  22%|██▏       | 436/2000 [00:23<01:23, 18.71it/s]

Epoch 10:  22%|██▏       | 438/2000 [00:23<01:23, 18.72it/s]

Epoch 10:  22%|██▏       | 440/2000 [00:23<01:23, 18.70it/s]

Epoch 10:  22%|██▏       | 442/2000 [00:23<01:23, 18.71it/s]

Epoch 10:  22%|██▏       | 444/2000 [00:23<01:23, 18.71it/s]

Epoch 10:  22%|██▏       | 446/2000 [00:23<01:23, 18.61it/s]

Epoch 10:  22%|██▏       | 448/2000 [00:23<01:23, 18.61it/s]

Epoch 10:  22%|██▎       | 450/2000 [00:24<01:23, 18.63it/s]

Epoch 10:  23%|██▎       | 452/2000 [00:24<01:22, 18.65it/s]

Epoch 10:  23%|██▎       | 454/2000 [00:24<01:22, 18.67it/s]

Epoch 10:  23%|██▎       | 456/2000 [00:24<01:22, 18.68it/s]

Epoch 10:  23%|██▎       | 458/2000 [00:24<01:22, 18.68it/s]

Epoch 10:  23%|██▎       | 460/2000 [00:24<01:22, 18.69it/s]

Epoch 10:  23%|██▎       | 462/2000 [00:24<01:22, 18.70it/s]

Epoch 10:  23%|██▎       | 464/2000 [00:24<01:22, 18.68it/s]

Epoch 10:  23%|██▎       | 466/2000 [00:24<01:22, 18.69it/s]

Epoch 10:  23%|██▎       | 468/2000 [00:25<01:21, 18.71it/s]

Epoch 10:  24%|██▎       | 470/2000 [00:25<01:21, 18.74it/s]

Epoch 10:  24%|██▎       | 472/2000 [00:25<01:21, 18.74it/s]

Epoch 10:  24%|██▎       | 474/2000 [00:25<01:21, 18.74it/s]

Epoch 10:  24%|██▍       | 476/2000 [00:25<01:21, 18.75it/s]

Epoch 10:  24%|██▍       | 478/2000 [00:25<01:21, 18.76it/s]

Epoch 10:  24%|██▍       | 480/2000 [00:25<01:21, 18.75it/s]

Epoch 10:  24%|██▍       | 482/2000 [00:25<01:20, 18.74it/s]

Epoch 10:  24%|██▍       | 484/2000 [00:25<01:22, 18.48it/s]

Epoch 10:  24%|██▍       | 486/2000 [00:25<01:21, 18.54it/s]

Epoch 10:  24%|██▍       | 488/2000 [00:26<01:21, 18.58it/s]

Epoch 10:  24%|██▍       | 490/2000 [00:26<01:21, 18.61it/s]

Epoch 10:  25%|██▍       | 492/2000 [00:26<01:20, 18.63it/s]

Epoch 10:  25%|██▍       | 494/2000 [00:26<01:20, 18.64it/s]

Epoch 10:  25%|██▍       | 496/2000 [00:26<01:20, 18.66it/s]

Epoch 10:  25%|██▍       | 498/2000 [00:26<01:20, 18.67it/s]

Epoch 10:  25%|██▌       | 500/2000 [00:26<01:20, 18.69it/s]

Epoch 10:  25%|██▌       | 502/2000 [00:26<01:20, 18.68it/s]

Epoch 10:  25%|██▌       | 504/2000 [00:26<01:20, 18.68it/s]

Epoch 10:  25%|██▌       | 506/2000 [00:27<01:19, 18.69it/s]

Epoch 10:  25%|██▌       | 508/2000 [00:27<01:19, 18.70it/s]

Epoch 10:  26%|██▌       | 510/2000 [00:27<01:19, 18.71it/s]

Epoch 10:  26%|██▌       | 512/2000 [00:27<01:19, 18.70it/s]

Epoch 10:  26%|██▌       | 514/2000 [00:27<01:19, 18.70it/s]

Epoch 10:  26%|██▌       | 516/2000 [00:27<01:19, 18.69it/s]

Epoch 10:  26%|██▌       | 518/2000 [00:27<01:19, 18.71it/s]

Epoch 10:  26%|██▌       | 520/2000 [00:27<01:19, 18.70it/s]

Epoch 10:  26%|██▌       | 522/2000 [00:27<01:19, 18.70it/s]

Epoch 10:  26%|██▌       | 524/2000 [00:28<01:18, 18.70it/s]

Epoch 10:  26%|██▋       | 526/2000 [00:28<01:18, 18.70it/s]

Epoch 10:  26%|██▋       | 528/2000 [00:28<01:18, 18.70it/s]

Epoch 10:  26%|██▋       | 530/2000 [00:28<01:18, 18.69it/s]

Epoch 10:  27%|██▋       | 532/2000 [00:28<01:18, 18.71it/s]

Epoch 10:  27%|██▋       | 534/2000 [00:28<01:18, 18.70it/s]

Epoch 10:  27%|██▋       | 536/2000 [00:28<01:18, 18.71it/s]

Epoch 10:  27%|██▋       | 538/2000 [00:28<01:18, 18.72it/s]

Epoch 10:  27%|██▋       | 540/2000 [00:28<01:18, 18.72it/s]

Epoch 10:  27%|██▋       | 542/2000 [00:28<01:17, 18.73it/s]

Epoch 10:  27%|██▋       | 544/2000 [00:29<01:17, 18.73it/s]

Epoch 10:  27%|██▋       | 546/2000 [00:29<01:17, 18.71it/s]

Epoch 10:  27%|██▋       | 548/2000 [00:29<01:17, 18.73it/s]

Epoch 10:  28%|██▊       | 550/2000 [00:29<01:17, 18.73it/s]

Epoch 10:  28%|██▊       | 552/2000 [00:29<01:17, 18.74it/s]

Epoch 10:  28%|██▊       | 554/2000 [00:29<01:17, 18.74it/s]

Epoch 10:  28%|██▊       | 556/2000 [00:29<01:17, 18.72it/s]

Epoch 10:  28%|██▊       | 558/2000 [00:29<01:17, 18.71it/s]

Epoch 10:  28%|██▊       | 560/2000 [00:29<01:16, 18.71it/s]

Epoch 10:  28%|██▊       | 562/2000 [00:30<01:17, 18.50it/s]

Epoch 10:  28%|██▊       | 564/2000 [00:30<01:20, 17.93it/s]

Epoch 10:  28%|██▊       | 566/2000 [00:30<01:19, 17.94it/s]

Epoch 10:  28%|██▊       | 568/2000 [00:30<01:18, 18.13it/s]

Epoch 10:  28%|██▊       | 570/2000 [00:30<01:18, 18.27it/s]

Epoch 10:  29%|██▊       | 572/2000 [00:30<01:17, 18.35it/s]

Epoch 10:  29%|██▊       | 574/2000 [00:30<01:17, 18.43it/s]

Epoch 10:  29%|██▉       | 576/2000 [00:30<01:17, 18.49it/s]

Epoch 10:  29%|██▉       | 578/2000 [00:30<01:16, 18.54it/s]

Epoch 10:  29%|██▉       | 580/2000 [00:31<01:16, 18.57it/s]

Epoch 10:  29%|██▉       | 582/2000 [00:31<01:16, 18.57it/s]

Epoch 10:  29%|██▉       | 584/2000 [00:31<01:16, 18.57it/s]

Epoch 10:  29%|██▉       | 586/2000 [00:31<01:16, 18.58it/s]

Epoch 10:  29%|██▉       | 588/2000 [00:31<01:15, 18.60it/s]

Epoch 10:  30%|██▉       | 590/2000 [00:31<01:15, 18.64it/s]

Epoch 10:  30%|██▉       | 592/2000 [00:31<01:15, 18.66it/s]

Epoch 10:  30%|██▉       | 594/2000 [00:31<01:15, 18.68it/s]

Epoch 10:  30%|██▉       | 596/2000 [00:31<01:15, 18.70it/s]

Epoch 10:  30%|██▉       | 598/2000 [00:32<01:14, 18.71it/s]

Epoch 10:  30%|███       | 600/2000 [00:32<01:14, 18.72it/s]

Epoch 10:  30%|███       | 602/2000 [00:32<01:14, 18.72it/s]

Epoch 10:  30%|███       | 604/2000 [00:32<01:14, 18.72it/s]

Epoch 10:  30%|███       | 606/2000 [00:32<01:14, 18.72it/s]

Epoch 10:  30%|███       | 608/2000 [00:32<01:14, 18.63it/s]

Epoch 10:  30%|███       | 610/2000 [00:32<01:14, 18.64it/s]

Epoch 10:  31%|███       | 612/2000 [00:32<01:14, 18.66it/s]

Epoch 10:  31%|███       | 614/2000 [00:32<01:14, 18.68it/s]

Epoch 10:  31%|███       | 616/2000 [00:32<01:14, 18.70it/s]

Epoch 10:  31%|███       | 618/2000 [00:33<01:14, 18.67it/s]

Epoch 10:  31%|███       | 620/2000 [00:33<01:13, 18.67it/s]

Epoch 10:  31%|███       | 622/2000 [00:33<01:13, 18.70it/s]

Epoch 10:  31%|███       | 624/2000 [00:33<01:13, 18.70it/s]

Epoch 10:  31%|███▏      | 626/2000 [00:33<01:13, 18.70it/s]

Epoch 10:  31%|███▏      | 628/2000 [00:33<01:13, 18.70it/s]

Epoch 10:  32%|███▏      | 630/2000 [00:33<01:13, 18.71it/s]

Epoch 10:  32%|███▏      | 632/2000 [00:33<01:13, 18.71it/s]

Epoch 10:  32%|███▏      | 634/2000 [00:33<01:12, 18.72it/s]

Epoch 10:  32%|███▏      | 636/2000 [00:34<01:13, 18.62it/s]

Epoch 10:  32%|███▏      | 638/2000 [00:34<01:13, 18.63it/s]

Epoch 10:  32%|███▏      | 640/2000 [00:34<01:12, 18.64it/s]

Epoch 10:  32%|███▏      | 642/2000 [00:34<01:12, 18.66it/s]

Epoch 10:  32%|███▏      | 644/2000 [00:34<01:12, 18.66it/s]

Epoch 10:  32%|███▏      | 646/2000 [00:34<01:12, 18.67it/s]

Epoch 10:  32%|███▏      | 648/2000 [00:34<01:12, 18.68it/s]

Epoch 10:  32%|███▎      | 650/2000 [00:34<01:12, 18.69it/s]

Epoch 10:  33%|███▎      | 652/2000 [00:34<01:12, 18.69it/s]

Epoch 10:  33%|███▎      | 654/2000 [00:35<01:12, 18.69it/s]

Epoch 10:  33%|███▎      | 656/2000 [00:35<01:11, 18.70it/s]

Epoch 10:  33%|███▎      | 658/2000 [00:35<01:11, 18.71it/s]

Epoch 10:  33%|███▎      | 660/2000 [00:35<01:11, 18.70it/s]

Epoch 10:  33%|███▎      | 662/2000 [00:35<01:11, 18.71it/s]

Epoch 10:  33%|███▎      | 664/2000 [00:35<01:11, 18.71it/s]

Epoch 10:  33%|███▎      | 666/2000 [00:35<01:11, 18.70it/s]

Epoch 10:  33%|███▎      | 668/2000 [00:35<01:11, 18.70it/s]

Epoch 10:  34%|███▎      | 670/2000 [00:35<01:11, 18.70it/s]

Epoch 10:  34%|███▎      | 672/2000 [00:35<01:11, 18.69it/s]

Epoch 10:  34%|███▎      | 674/2000 [00:36<01:10, 18.69it/s]

Epoch 10:  34%|███▍      | 676/2000 [00:36<01:10, 18.69it/s]

Epoch 10:  34%|███▍      | 678/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  34%|███▍      | 680/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  34%|███▍      | 682/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  34%|███▍      | 684/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  34%|███▍      | 686/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  34%|███▍      | 688/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  34%|███▍      | 690/2000 [00:36<01:10, 18.70it/s]

Epoch 10:  35%|███▍      | 692/2000 [00:37<01:09, 18.71it/s]

Epoch 10:  35%|███▍      | 694/2000 [00:37<01:09, 18.71it/s]

Epoch 10:  35%|███▍      | 696/2000 [00:37<01:09, 18.72it/s]

Epoch 10:  35%|███▍      | 698/2000 [00:37<01:09, 18.70it/s]

Epoch 10:  35%|███▌      | 700/2000 [00:37<01:09, 18.70it/s]

Epoch 10:  35%|███▌      | 702/2000 [00:37<01:09, 18.70it/s]

Epoch 10:  35%|███▌      | 704/2000 [00:37<01:09, 18.70it/s]

Epoch 10:  35%|███▌      | 706/2000 [00:37<01:09, 18.70it/s]

Epoch 10:  35%|███▌      | 708/2000 [00:37<01:09, 18.71it/s]

Epoch 10:  36%|███▌      | 710/2000 [00:38<01:08, 18.71it/s]

Epoch 10:  36%|███▌      | 712/2000 [00:38<01:08, 18.72it/s]

Epoch 10:  36%|███▌      | 714/2000 [00:38<01:08, 18.70it/s]

Epoch 10:  36%|███▌      | 716/2000 [00:38<01:08, 18.70it/s]

Epoch 10:  36%|███▌      | 718/2000 [00:38<01:08, 18.71it/s]

Epoch 10:  36%|███▌      | 720/2000 [00:38<01:08, 18.71it/s]

Epoch 10:  36%|███▌      | 722/2000 [00:38<01:08, 18.71it/s]

Epoch 10:  36%|███▌      | 724/2000 [00:38<01:08, 18.73it/s]

Epoch 10:  36%|███▋      | 726/2000 [00:38<01:08, 18.72it/s]

Epoch 10:  36%|███▋      | 728/2000 [00:38<01:07, 18.73it/s]

Epoch 10:  36%|███▋      | 730/2000 [00:39<01:07, 18.74it/s]

Epoch 10:  37%|███▋      | 732/2000 [00:39<01:07, 18.72it/s]

Epoch 10:  37%|███▋      | 734/2000 [00:39<01:07, 18.72it/s]

Epoch 10:  37%|███▋      | 736/2000 [00:39<01:07, 18.73it/s]

Epoch 10:  37%|███▋      | 738/2000 [00:39<01:07, 18.71it/s]

Epoch 10:  37%|███▋      | 740/2000 [00:39<01:07, 18.71it/s]

Epoch 10:  37%|███▋      | 742/2000 [00:39<01:07, 18.70it/s]

Epoch 10:  37%|███▋      | 744/2000 [00:39<01:07, 18.71it/s]

Epoch 10:  37%|███▋      | 746/2000 [00:39<01:07, 18.72it/s]

Epoch 10:  37%|███▋      | 748/2000 [00:40<01:06, 18.72it/s]

Epoch 10:  38%|███▊      | 750/2000 [00:40<01:06, 18.73it/s]

Epoch 10:  38%|███▊      | 752/2000 [00:40<01:06, 18.73it/s]

Epoch 10:  38%|███▊      | 754/2000 [00:40<01:06, 18.72it/s]

Epoch 10:  38%|███▊      | 756/2000 [00:40<01:06, 18.72it/s]

Epoch 10:  38%|███▊      | 758/2000 [00:40<01:06, 18.73it/s]

Epoch 10:  38%|███▊      | 760/2000 [00:40<01:06, 18.74it/s]

Epoch 10:  38%|███▊      | 762/2000 [00:40<01:06, 18.73it/s]

Epoch 10:  38%|███▊      | 764/2000 [00:40<01:06, 18.72it/s]

Epoch 10:  38%|███▊      | 766/2000 [00:40<01:05, 18.72it/s]

Epoch 10:  38%|███▊      | 768/2000 [00:41<01:05, 18.72it/s]

Epoch 10:  38%|███▊      | 770/2000 [00:41<01:05, 18.72it/s]

Epoch 10:  39%|███▊      | 772/2000 [00:41<01:05, 18.72it/s]

Epoch 10:  39%|███▊      | 774/2000 [00:41<01:05, 18.72it/s]

Epoch 10:  39%|███▉      | 776/2000 [00:41<01:05, 18.72it/s]

Epoch 10:  39%|███▉      | 778/2000 [00:41<01:05, 18.72it/s]

Epoch 10:  39%|███▉      | 780/2000 [00:41<01:05, 18.71it/s]

Epoch 10:  39%|███▉      | 782/2000 [00:41<01:05, 18.70it/s]

Epoch 10:  39%|███▉      | 784/2000 [00:41<01:05, 18.69it/s]

Epoch 10:  39%|███▉      | 786/2000 [00:42<01:04, 18.69it/s]

Epoch 10:  39%|███▉      | 788/2000 [00:42<01:04, 18.70it/s]

Epoch 10:  40%|███▉      | 790/2000 [00:42<01:04, 18.71it/s]

Epoch 10:  40%|███▉      | 792/2000 [00:42<01:04, 18.72it/s]

Epoch 10:  40%|███▉      | 794/2000 [00:42<01:04, 18.72it/s]

Epoch 10:  40%|███▉      | 796/2000 [00:42<01:04, 18.73it/s]

Epoch 10:  40%|███▉      | 798/2000 [00:42<01:04, 18.72it/s]

Epoch 10:  40%|████      | 800/2000 [00:42<01:04, 18.72it/s]

Epoch 10:  40%|████      | 802/2000 [00:42<01:03, 18.72it/s]

Epoch 10:  40%|████      | 804/2000 [00:43<01:03, 18.70it/s]

Epoch 10:  40%|████      | 806/2000 [00:43<01:04, 18.63it/s]

Epoch 10:  40%|████      | 808/2000 [00:43<01:03, 18.66it/s]

Epoch 10:  40%|████      | 810/2000 [00:43<01:03, 18.67it/s]

Epoch 10:  41%|████      | 812/2000 [00:43<01:03, 18.69it/s]

Epoch 10:  41%|████      | 814/2000 [00:43<01:03, 18.69it/s]

Epoch 10:  41%|████      | 816/2000 [00:43<01:03, 18.71it/s]

Epoch 10:  41%|████      | 818/2000 [00:43<01:03, 18.68it/s]

Epoch 10:  41%|████      | 820/2000 [00:43<01:03, 18.67it/s]

Epoch 10:  41%|████      | 822/2000 [00:43<01:03, 18.68it/s]

Epoch 10:  41%|████      | 824/2000 [00:44<01:02, 18.69it/s]

Epoch 10:  41%|████▏     | 826/2000 [00:44<01:02, 18.69it/s]

Epoch 10:  41%|████▏     | 828/2000 [00:44<01:02, 18.70it/s]

Epoch 10:  42%|████▏     | 830/2000 [00:44<01:02, 18.70it/s]

Epoch 10:  42%|████▏     | 832/2000 [00:44<01:02, 18.70it/s]

Epoch 10:  42%|████▏     | 834/2000 [00:44<01:02, 18.71it/s]

Epoch 10:  42%|████▏     | 836/2000 [00:44<01:02, 18.71it/s]

Epoch 10:  42%|████▏     | 838/2000 [00:44<01:02, 18.72it/s]

Epoch 10:  42%|████▏     | 840/2000 [00:44<01:01, 18.73it/s]

Epoch 10:  42%|████▏     | 842/2000 [00:45<01:01, 18.70it/s]

Epoch 10:  42%|████▏     | 844/2000 [00:45<01:01, 18.71it/s]

Epoch 10:  42%|████▏     | 846/2000 [00:45<01:01, 18.70it/s]

Epoch 10:  42%|████▏     | 848/2000 [00:45<01:01, 18.71it/s]

Epoch 10:  42%|████▎     | 850/2000 [00:45<01:01, 18.70it/s]

Epoch 10:  43%|████▎     | 852/2000 [00:45<01:01, 18.70it/s]

Epoch 10:  43%|████▎     | 854/2000 [00:45<01:01, 18.69it/s]

Epoch 10:  43%|████▎     | 856/2000 [00:45<01:01, 18.69it/s]

Epoch 10:  43%|████▎     | 858/2000 [00:45<01:01, 18.69it/s]

Epoch 10:  43%|████▎     | 860/2000 [00:46<01:00, 18.69it/s]

Epoch 10:  43%|████▎     | 862/2000 [00:46<01:00, 18.70it/s]

Epoch 10:  43%|████▎     | 864/2000 [00:46<01:00, 18.71it/s]

Epoch 10:  43%|████▎     | 866/2000 [00:46<01:00, 18.70it/s]

Epoch 10:  43%|████▎     | 868/2000 [00:46<01:00, 18.70it/s]

Epoch 10:  44%|████▎     | 870/2000 [00:46<01:00, 18.70it/s]

Epoch 10:  44%|████▎     | 872/2000 [00:46<01:00, 18.70it/s]

Epoch 10:  44%|████▎     | 874/2000 [00:46<01:00, 18.70it/s]

Epoch 10:  44%|████▍     | 876/2000 [00:46<01:00, 18.71it/s]

Epoch 10:  44%|████▍     | 878/2000 [00:46<00:59, 18.71it/s]

Epoch 10:  44%|████▍     | 880/2000 [00:47<00:59, 18.71it/s]

Epoch 10:  44%|████▍     | 882/2000 [00:47<00:59, 18.72it/s]

Epoch 10:  44%|████▍     | 884/2000 [00:47<00:59, 18.74it/s]

Epoch 10:  44%|████▍     | 886/2000 [00:47<00:59, 18.73it/s]

Epoch 10:  44%|████▍     | 888/2000 [00:47<00:59, 18.72it/s]

Epoch 10:  44%|████▍     | 890/2000 [00:47<00:59, 18.73it/s]

Epoch 10:  45%|████▍     | 892/2000 [00:47<00:59, 18.73it/s]

Epoch 10:  45%|████▍     | 894/2000 [00:47<00:59, 18.73it/s]

Epoch 10:  45%|████▍     | 896/2000 [00:47<00:58, 18.73it/s]

Epoch 10:  45%|████▍     | 898/2000 [00:48<00:58, 18.72it/s]

Epoch 10:  45%|████▌     | 900/2000 [00:48<00:58, 18.72it/s]

Epoch 10:  45%|████▌     | 902/2000 [00:48<00:58, 18.71it/s]

Epoch 10:  45%|████▌     | 904/2000 [00:48<00:58, 18.72it/s]

Epoch 10:  45%|████▌     | 906/2000 [00:48<00:58, 18.72it/s]

Epoch 10:  45%|████▌     | 908/2000 [00:48<00:58, 18.73it/s]

Epoch 10:  46%|████▌     | 910/2000 [00:48<00:58, 18.73it/s]

Epoch 10:  46%|████▌     | 912/2000 [00:48<00:58, 18.73it/s]

Epoch 10:  46%|████▌     | 914/2000 [00:48<00:58, 18.71it/s]

Epoch 10:  46%|████▌     | 916/2000 [00:49<00:57, 18.72it/s]

Epoch 10:  46%|████▌     | 918/2000 [00:49<00:57, 18.73it/s]

Epoch 10:  46%|████▌     | 920/2000 [00:49<00:57, 18.73it/s]

Epoch 10:  46%|████▌     | 922/2000 [00:49<00:57, 18.72it/s]

Epoch 10:  46%|████▌     | 924/2000 [00:49<00:57, 18.71it/s]

Epoch 10:  46%|████▋     | 926/2000 [00:49<00:57, 18.72it/s]

Epoch 10:  46%|████▋     | 928/2000 [00:49<00:57, 18.71it/s]

Epoch 10:  46%|████▋     | 930/2000 [00:49<00:57, 18.71it/s]

Epoch 10:  47%|████▋     | 932/2000 [00:49<00:57, 18.71it/s]

Epoch 10:  47%|████▋     | 934/2000 [00:49<00:56, 18.72it/s]

Epoch 10:  47%|████▋     | 936/2000 [00:50<00:56, 18.72it/s]

Epoch 10:  47%|████▋     | 938/2000 [00:50<00:56, 18.72it/s]

Epoch 10:  47%|████▋     | 940/2000 [00:50<00:56, 18.73it/s]

Epoch 10:  47%|████▋     | 942/2000 [00:50<00:56, 18.72it/s]

Epoch 10:  47%|████▋     | 944/2000 [00:50<00:56, 18.72it/s]

Epoch 10:  47%|████▋     | 946/2000 [00:50<00:56, 18.72it/s]

Epoch 10:  47%|████▋     | 948/2000 [00:50<00:56, 18.72it/s]

Epoch 10:  48%|████▊     | 950/2000 [00:50<00:56, 18.71it/s]

Epoch 10:  48%|████▊     | 952/2000 [00:50<00:56, 18.71it/s]

Epoch 10:  48%|████▊     | 954/2000 [00:51<00:55, 18.71it/s]

Epoch 10:  48%|████▊     | 956/2000 [00:51<00:55, 18.71it/s]

Epoch 10:  48%|████▊     | 958/2000 [00:51<00:55, 18.72it/s]

Epoch 10:  48%|████▊     | 960/2000 [00:51<00:55, 18.71it/s]

Epoch 10:  48%|████▊     | 962/2000 [00:51<00:55, 18.71it/s]

Epoch 10:  48%|████▊     | 964/2000 [00:51<00:55, 18.71it/s]

Epoch 10:  48%|████▊     | 966/2000 [00:51<00:55, 18.71it/s]

Epoch 10:  48%|████▊     | 968/2000 [00:51<00:55, 18.64it/s]

Epoch 10:  48%|████▊     | 970/2000 [00:51<00:55, 18.62it/s]

Epoch 10:  49%|████▊     | 972/2000 [00:52<00:55, 18.58it/s]

Epoch 10:  49%|████▊     | 974/2000 [00:52<00:55, 18.57it/s]

Epoch 10:  49%|████▉     | 976/2000 [00:52<00:55, 18.56it/s]

Epoch 10:  49%|████▉     | 978/2000 [00:52<00:55, 18.54it/s]

Epoch 10:  49%|████▉     | 980/2000 [00:52<00:55, 18.54it/s]

Epoch 10:  49%|████▉     | 982/2000 [00:52<00:54, 18.53it/s]

Epoch 10:  49%|████▉     | 984/2000 [00:52<00:54, 18.53it/s]

Epoch 10:  49%|████▉     | 986/2000 [00:52<00:54, 18.53it/s]

Epoch 10:  49%|████▉     | 988/2000 [00:52<00:54, 18.52it/s]

Epoch 10:  50%|████▉     | 990/2000 [00:52<00:54, 18.53it/s]

Epoch 10:  50%|████▉     | 992/2000 [00:53<00:54, 18.52it/s]

Epoch 10:  50%|████▉     | 994/2000 [00:53<00:54, 18.52it/s]

Epoch 10:  50%|████▉     | 996/2000 [00:53<00:54, 18.53it/s]

Epoch 10:  50%|████▉     | 998/2000 [00:53<00:54, 18.51it/s]

Epoch 10:  50%|█████     | 1000/2000 [00:53<00:54, 18.50it/s]

Epoch 10:  50%|█████     | 1002/2000 [00:53<00:53, 18.51it/s]

Epoch 10:  50%|█████     | 1004/2000 [00:53<00:53, 18.51it/s]

Epoch 10:  50%|█████     | 1006/2000 [00:53<00:53, 18.51it/s]

Epoch 10:  50%|█████     | 1008/2000 [00:53<00:53, 18.52it/s]

Epoch 10:  50%|█████     | 1010/2000 [00:54<00:53, 18.52it/s]

Epoch 10:  51%|█████     | 1012/2000 [00:54<00:53, 18.52it/s]

Epoch 10:  51%|█████     | 1014/2000 [00:54<00:53, 18.52it/s]

Epoch 10:  51%|█████     | 1016/2000 [00:54<00:53, 18.53it/s]

Epoch 10:  51%|█████     | 1018/2000 [00:54<00:53, 18.53it/s]

Epoch 10:  51%|█████     | 1020/2000 [00:54<00:52, 18.52it/s]

Epoch 10:  51%|█████     | 1022/2000 [00:54<00:52, 18.52it/s]

Epoch 10:  51%|█████     | 1024/2000 [00:54<00:52, 18.52it/s]

Epoch 10:  51%|█████▏    | 1026/2000 [00:54<00:52, 18.52it/s]

Epoch 10:  51%|█████▏    | 1028/2000 [00:55<00:52, 18.51it/s]

Epoch 10:  52%|█████▏    | 1030/2000 [00:55<00:52, 18.52it/s]

Epoch 10:  52%|█████▏    | 1032/2000 [00:55<00:52, 18.52it/s]

Epoch 10:  52%|█████▏    | 1034/2000 [00:55<00:52, 18.52it/s]

Epoch 10:  52%|█████▏    | 1036/2000 [00:55<00:52, 18.52it/s]

Epoch 10:  52%|█████▏    | 1038/2000 [00:55<00:51, 18.51it/s]

Epoch 10:  52%|█████▏    | 1040/2000 [00:55<00:51, 18.51it/s]

Epoch 10:  52%|█████▏    | 1042/2000 [00:55<00:51, 18.52it/s]

Epoch 10:  52%|█████▏    | 1044/2000 [00:55<00:51, 18.50it/s]

Epoch 10:  52%|█████▏    | 1046/2000 [00:56<00:51, 18.51it/s]

Epoch 10:  52%|█████▏    | 1048/2000 [00:56<00:51, 18.52it/s]

Epoch 10:  52%|█████▎    | 1050/2000 [00:56<00:51, 18.52it/s]

Epoch 10:  53%|█████▎    | 1052/2000 [00:56<00:51, 18.53it/s]

Epoch 10:  53%|█████▎    | 1054/2000 [00:56<00:51, 18.53it/s]

Epoch 10:  53%|█████▎    | 1056/2000 [00:56<00:50, 18.53it/s]

Epoch 10:  53%|█████▎    | 1058/2000 [00:56<00:50, 18.52it/s]

Epoch 10:  53%|█████▎    | 1060/2000 [00:56<00:50, 18.51it/s]

Epoch 10:  53%|█████▎    | 1062/2000 [00:56<00:50, 18.52it/s]

Epoch 10:  53%|█████▎    | 1064/2000 [00:56<00:50, 18.53it/s]

Epoch 10:  53%|█████▎    | 1066/2000 [00:57<00:50, 18.52it/s]

Epoch 10:  53%|█████▎    | 1068/2000 [00:57<00:50, 18.52it/s]

Epoch 10:  54%|█████▎    | 1070/2000 [00:57<00:50, 18.53it/s]

Epoch 10:  54%|█████▎    | 1072/2000 [00:57<00:50, 18.54it/s]

Epoch 10:  54%|█████▎    | 1074/2000 [00:57<00:49, 18.54it/s]

Epoch 10:  54%|█████▍    | 1076/2000 [00:57<00:49, 18.53it/s]

Epoch 10:  54%|█████▍    | 1078/2000 [00:57<00:49, 18.53it/s]

Epoch 10:  54%|█████▍    | 1080/2000 [00:57<00:49, 18.53it/s]

Epoch 10:  54%|█████▍    | 1082/2000 [00:57<00:49, 18.52it/s]

Epoch 10:  54%|█████▍    | 1084/2000 [00:58<00:49, 18.50it/s]

Epoch 10:  54%|█████▍    | 1086/2000 [00:58<00:49, 18.49it/s]

Epoch 10:  54%|█████▍    | 1088/2000 [00:58<00:49, 18.51it/s]

Epoch 10:  55%|█████▍    | 1090/2000 [00:58<00:49, 18.51it/s]

Epoch 10:  55%|█████▍    | 1092/2000 [00:58<00:49, 18.50it/s]

Epoch 10:  55%|█████▍    | 1094/2000 [00:58<00:48, 18.50it/s]

Epoch 10:  55%|█████▍    | 1096/2000 [00:58<00:48, 18.51it/s]

Epoch 10:  55%|█████▍    | 1098/2000 [00:58<00:48, 18.51it/s]

Epoch 10:  55%|█████▌    | 1100/2000 [00:58<00:48, 18.52it/s]

Epoch 10:  55%|█████▌    | 1102/2000 [00:59<00:48, 18.53it/s]

Epoch 10:  55%|█████▌    | 1104/2000 [00:59<00:48, 18.52it/s]

Epoch 10:  55%|█████▌    | 1106/2000 [00:59<00:48, 18.51it/s]

Epoch 10:  55%|█████▌    | 1108/2000 [00:59<00:48, 18.52it/s]

Epoch 10:  56%|█████▌    | 1110/2000 [00:59<00:48, 18.52it/s]

Epoch 10:  56%|█████▌    | 1112/2000 [00:59<00:47, 18.51it/s]

Epoch 10:  56%|█████▌    | 1114/2000 [00:59<00:47, 18.52it/s]

Epoch 10:  56%|█████▌    | 1116/2000 [00:59<00:47, 18.50it/s]

Epoch 10:  56%|█████▌    | 1118/2000 [00:59<00:47, 18.50it/s]

Epoch 10:  56%|█████▌    | 1120/2000 [00:59<00:47, 18.50it/s]

Epoch 10:  56%|█████▌    | 1122/2000 [01:00<00:47, 18.50it/s]

Epoch 10:  56%|█████▌    | 1124/2000 [01:00<00:47, 18.50it/s]

Epoch 10:  56%|█████▋    | 1126/2000 [01:00<00:47, 18.49it/s]

Epoch 10:  56%|█████▋    | 1128/2000 [01:00<00:47, 18.50it/s]

Epoch 10:  56%|█████▋    | 1130/2000 [01:00<00:47, 18.50it/s]

Epoch 10:  57%|█████▋    | 1132/2000 [01:00<00:46, 18.51it/s]

Epoch 10:  57%|█████▋    | 1134/2000 [01:00<00:46, 18.51it/s]

Epoch 10:  57%|█████▋    | 1136/2000 [01:00<00:46, 18.50it/s]

Epoch 10:  57%|█████▋    | 1138/2000 [01:00<00:46, 18.48it/s]

Epoch 10:  57%|█████▋    | 1140/2000 [01:01<00:46, 18.48it/s]

Epoch 10:  57%|█████▋    | 1142/2000 [01:01<00:46, 18.48it/s]

Epoch 10:  57%|█████▋    | 1144/2000 [01:01<00:46, 18.49it/s]

Epoch 10:  57%|█████▋    | 1146/2000 [01:01<00:46, 18.50it/s]

Epoch 10:  57%|█████▋    | 1148/2000 [01:01<00:46, 18.50it/s]

Epoch 10:  57%|█████▊    | 1150/2000 [01:01<00:45, 18.48it/s]

Epoch 10:  58%|█████▊    | 1152/2000 [01:01<00:45, 18.48it/s]

Epoch 10:  58%|█████▊    | 1154/2000 [01:01<00:45, 18.48it/s]

Epoch 10:  58%|█████▊    | 1156/2000 [01:01<00:45, 18.48it/s]

Epoch 10:  58%|█████▊    | 1158/2000 [01:02<00:45, 18.50it/s]

Epoch 10:  58%|█████▊    | 1160/2000 [01:02<00:45, 18.48it/s]

Epoch 10:  58%|█████▊    | 1162/2000 [01:02<00:45, 18.47it/s]

Epoch 10:  58%|█████▊    | 1164/2000 [01:02<00:45, 18.48it/s]

Epoch 10:  58%|█████▊    | 1166/2000 [01:02<00:45, 18.49it/s]

Epoch 10:  58%|█████▊    | 1168/2000 [01:02<00:44, 18.50it/s]

Epoch 10:  58%|█████▊    | 1170/2000 [01:02<00:44, 18.51it/s]

Epoch 10:  59%|█████▊    | 1172/2000 [01:02<00:44, 18.51it/s]

Epoch 10:  59%|█████▊    | 1174/2000 [01:02<00:44, 18.52it/s]

Epoch 10:  59%|█████▉    | 1176/2000 [01:03<00:44, 18.53it/s]

Epoch 10:  59%|█████▉    | 1178/2000 [01:03<00:44, 18.52it/s]

Epoch 10:  59%|█████▉    | 1180/2000 [01:03<00:44, 18.51it/s]

Epoch 10:  59%|█████▉    | 1182/2000 [01:03<00:44, 18.51it/s]

Epoch 10:  59%|█████▉    | 1184/2000 [01:03<00:44, 18.52it/s]

Epoch 10:  59%|█████▉    | 1186/2000 [01:03<00:44, 18.45it/s]

Epoch 10:  59%|█████▉    | 1188/2000 [01:03<00:44, 18.45it/s]

Epoch 10:  60%|█████▉    | 1190/2000 [01:03<00:43, 18.47it/s]

Epoch 10:  60%|█████▉    | 1192/2000 [01:03<00:44, 18.29it/s]

Epoch 10:  60%|█████▉    | 1194/2000 [01:04<00:45, 17.71it/s]

Epoch 10:  60%|█████▉    | 1196/2000 [01:04<00:45, 17.76it/s]

Epoch 10:  60%|█████▉    | 1198/2000 [01:04<00:44, 17.95it/s]

Epoch 10:  60%|██████    | 1200/2000 [01:04<00:44, 18.07it/s]

Epoch 10:  60%|██████    | 1202/2000 [01:04<00:43, 18.17it/s]

Epoch 10:  60%|██████    | 1204/2000 [01:04<00:43, 18.28it/s]

Epoch 10:  60%|██████    | 1206/2000 [01:04<00:43, 18.34it/s]

Epoch 10:  60%|██████    | 1208/2000 [01:04<00:43, 18.39it/s]

Epoch 10:  60%|██████    | 1210/2000 [01:04<00:42, 18.44it/s]

Epoch 10:  61%|██████    | 1212/2000 [01:04<00:42, 18.47it/s]

Epoch 10:  61%|██████    | 1214/2000 [01:05<00:42, 18.49it/s]

Epoch 10:  61%|██████    | 1216/2000 [01:05<00:42, 18.50it/s]

Epoch 10:  61%|██████    | 1218/2000 [01:05<00:42, 18.49it/s]

Epoch 10:  61%|██████    | 1220/2000 [01:05<00:42, 18.50it/s]

Epoch 10:  61%|██████    | 1222/2000 [01:05<00:42, 18.51it/s]

Epoch 10:  61%|██████    | 1224/2000 [01:05<00:41, 18.51it/s]

Epoch 10:  61%|██████▏   | 1226/2000 [01:05<00:41, 18.51it/s]

Epoch 10:  61%|██████▏   | 1228/2000 [01:05<00:41, 18.51it/s]

Epoch 10:  62%|██████▏   | 1230/2000 [01:05<00:41, 18.52it/s]

Epoch 10:  62%|██████▏   | 1232/2000 [01:06<00:41, 18.53it/s]

Epoch 10:  62%|██████▏   | 1234/2000 [01:06<00:41, 18.53it/s]

Epoch 10:  62%|██████▏   | 1236/2000 [01:06<00:41, 18.53it/s]

Epoch 10:  62%|██████▏   | 1238/2000 [01:06<00:41, 18.53it/s]

Epoch 10:  62%|██████▏   | 1240/2000 [01:06<00:41, 18.53it/s]

Epoch 10:  62%|██████▏   | 1242/2000 [01:06<00:40, 18.53it/s]

Epoch 10:  62%|██████▏   | 1244/2000 [01:06<00:40, 18.51it/s]

Epoch 10:  62%|██████▏   | 1246/2000 [01:06<00:40, 18.51it/s]

Epoch 10:  62%|██████▏   | 1248/2000 [01:06<00:40, 18.51it/s]

Epoch 10:  62%|██████▎   | 1250/2000 [01:07<00:40, 18.50it/s]

Epoch 10:  63%|██████▎   | 1252/2000 [01:07<00:40, 18.51it/s]

Epoch 10:  63%|██████▎   | 1254/2000 [01:07<00:40, 18.52it/s]

Epoch 10:  63%|██████▎   | 1256/2000 [01:07<00:40, 18.51it/s]

Epoch 10:  63%|██████▎   | 1258/2000 [01:07<00:40, 18.51it/s]

Epoch 10:  63%|██████▎   | 1260/2000 [01:07<00:39, 18.52it/s]

Epoch 10:  63%|██████▎   | 1262/2000 [01:07<00:39, 18.52it/s]

Epoch 10:  63%|██████▎   | 1264/2000 [01:07<00:39, 18.51it/s]

Epoch 10:  63%|██████▎   | 1266/2000 [01:07<00:39, 18.52it/s]

Epoch 10:  63%|██████▎   | 1268/2000 [01:08<00:39, 18.51it/s]

Epoch 10:  64%|██████▎   | 1270/2000 [01:08<00:39, 18.52it/s]

Epoch 10:  64%|██████▎   | 1272/2000 [01:08<00:39, 18.53it/s]

Epoch 10:  64%|██████▎   | 1274/2000 [01:08<00:39, 18.52it/s]

Epoch 10:  64%|██████▍   | 1276/2000 [01:08<00:39, 18.51it/s]

Epoch 10:  64%|██████▍   | 1278/2000 [01:08<00:38, 18.52it/s]

Epoch 10:  64%|██████▍   | 1280/2000 [01:08<00:38, 18.53it/s]

Epoch 10:  64%|██████▍   | 1282/2000 [01:08<00:38, 18.52it/s]

Epoch 10:  64%|██████▍   | 1284/2000 [01:08<00:38, 18.50it/s]

Epoch 10:  64%|██████▍   | 1286/2000 [01:08<00:38, 18.50it/s]

Epoch 10:  64%|██████▍   | 1288/2000 [01:09<00:38, 18.50it/s]

Epoch 10:  64%|██████▍   | 1290/2000 [01:09<00:38, 18.52it/s]

Epoch 10:  65%|██████▍   | 1292/2000 [01:09<00:38, 18.51it/s]

Epoch 10:  65%|██████▍   | 1294/2000 [01:09<00:38, 18.51it/s]

Epoch 10:  65%|██████▍   | 1296/2000 [01:09<00:38, 18.52it/s]

Epoch 10:  65%|██████▍   | 1298/2000 [01:09<00:37, 18.52it/s]

Epoch 10:  65%|██████▌   | 1300/2000 [01:09<00:37, 18.53it/s]

Epoch 10:  65%|██████▌   | 1302/2000 [01:09<00:37, 18.53it/s]

Epoch 10:  65%|██████▌   | 1304/2000 [01:09<00:37, 18.53it/s]

Epoch 10:  65%|██████▌   | 1306/2000 [01:10<00:37, 18.53it/s]

Epoch 10:  65%|██████▌   | 1308/2000 [01:10<00:37, 18.54it/s]

Epoch 10:  66%|██████▌   | 1310/2000 [01:10<00:37, 18.52it/s]

Epoch 10:  66%|██████▌   | 1312/2000 [01:10<00:37, 18.51it/s]

Epoch 10:  66%|██████▌   | 1314/2000 [01:10<00:37, 18.52it/s]

Epoch 10:  66%|██████▌   | 1316/2000 [01:10<00:36, 18.52it/s]

Epoch 10:  66%|██████▌   | 1318/2000 [01:10<00:36, 18.53it/s]

Epoch 10:  66%|██████▌   | 1320/2000 [01:10<00:36, 18.53it/s]

Epoch 10:  66%|██████▌   | 1322/2000 [01:10<00:36, 18.51it/s]

Epoch 10:  66%|██████▌   | 1324/2000 [01:11<00:36, 18.52it/s]

Epoch 10:  66%|██████▋   | 1326/2000 [01:11<00:36, 18.52it/s]

Epoch 10:  66%|██████▋   | 1328/2000 [01:11<00:36, 18.52it/s]

Epoch 10:  66%|██████▋   | 1330/2000 [01:11<00:36, 18.53it/s]

Epoch 10:  67%|██████▋   | 1332/2000 [01:11<00:36, 18.52it/s]

Epoch 10:  67%|██████▋   | 1334/2000 [01:11<00:35, 18.52it/s]

Epoch 10:  67%|██████▋   | 1336/2000 [01:11<00:35, 18.52it/s]

Epoch 10:  67%|██████▋   | 1338/2000 [01:11<00:35, 18.52it/s]

Epoch 10:  67%|██████▋   | 1340/2000 [01:11<00:35, 18.52it/s]

Epoch 10:  67%|██████▋   | 1342/2000 [01:12<00:35, 18.51it/s]

Epoch 10:  67%|██████▋   | 1344/2000 [01:12<00:35, 18.51it/s]

Epoch 10:  67%|██████▋   | 1346/2000 [01:12<00:35, 18.51it/s]

Epoch 10:  67%|██████▋   | 1348/2000 [01:12<00:35, 18.52it/s]

Epoch 10:  68%|██████▊   | 1350/2000 [01:12<00:35, 18.52it/s]

Epoch 10:  68%|██████▊   | 1352/2000 [01:12<00:34, 18.52it/s]

Epoch 10:  68%|██████▊   | 1354/2000 [01:12<00:34, 18.51it/s]

Epoch 10:  68%|██████▊   | 1356/2000 [01:12<00:34, 18.51it/s]

Epoch 10:  68%|██████▊   | 1358/2000 [01:12<00:34, 18.52it/s]

Epoch 10:  68%|██████▊   | 1360/2000 [01:12<00:34, 18.51it/s]

Epoch 10:  68%|██████▊   | 1362/2000 [01:13<00:34, 18.58it/s]

Epoch 10:  68%|██████▊   | 1364/2000 [01:13<00:34, 18.62it/s]

Epoch 10:  68%|██████▊   | 1366/2000 [01:13<00:33, 18.65it/s]

Epoch 10:  68%|██████▊   | 1368/2000 [01:13<00:33, 18.68it/s]

Epoch 10:  68%|██████▊   | 1370/2000 [01:13<00:33, 18.69it/s]

Epoch 10:  69%|██████▊   | 1372/2000 [01:13<00:33, 18.70it/s]

Epoch 10:  69%|██████▊   | 1374/2000 [01:13<00:33, 18.70it/s]

Epoch 10:  69%|██████▉   | 1376/2000 [01:13<00:33, 18.71it/s]

Epoch 10:  69%|██████▉   | 1378/2000 [01:13<00:33, 18.71it/s]

Epoch 10:  69%|██████▉   | 1380/2000 [01:14<00:33, 18.68it/s]

Epoch 10:  69%|██████▉   | 1382/2000 [01:14<00:33, 18.68it/s]

Epoch 10:  69%|██████▉   | 1384/2000 [01:14<00:32, 18.70it/s]

Epoch 10:  69%|██████▉   | 1386/2000 [01:14<00:32, 18.69it/s]

Epoch 10:  69%|██████▉   | 1388/2000 [01:14<00:32, 18.69it/s]

Epoch 10:  70%|██████▉   | 1390/2000 [01:14<00:32, 18.69it/s]

Epoch 10:  70%|██████▉   | 1392/2000 [01:14<00:32, 18.70it/s]

Epoch 10:  70%|██████▉   | 1394/2000 [01:14<00:32, 18.68it/s]

Epoch 10:  70%|██████▉   | 1396/2000 [01:14<00:32, 18.68it/s]

Epoch 10:  70%|██████▉   | 1398/2000 [01:15<00:32, 18.68it/s]

Epoch 10:  70%|███████   | 1400/2000 [01:15<00:32, 18.69it/s]

Epoch 10:  70%|███████   | 1402/2000 [01:15<00:31, 18.70it/s]

Epoch 10:  70%|███████   | 1404/2000 [01:15<00:32, 18.61it/s]

Epoch 10:  70%|███████   | 1406/2000 [01:15<00:31, 18.62it/s]

Epoch 10:  70%|███████   | 1408/2000 [01:15<00:31, 18.65it/s]

Epoch 10:  70%|███████   | 1410/2000 [01:15<00:31, 18.66it/s]

Epoch 10:  71%|███████   | 1412/2000 [01:15<00:31, 18.66it/s]

Epoch 10:  71%|███████   | 1414/2000 [01:15<00:31, 18.66it/s]

Epoch 10:  71%|███████   | 1416/2000 [01:15<00:31, 18.68it/s]

Epoch 10:  71%|███████   | 1418/2000 [01:16<00:31, 18.69it/s]

Epoch 10:  71%|███████   | 1420/2000 [01:16<00:30, 18.71it/s]

Epoch 10:  71%|███████   | 1422/2000 [01:16<00:30, 18.72it/s]

Epoch 10:  71%|███████   | 1424/2000 [01:16<00:30, 18.72it/s]

Epoch 10:  71%|███████▏  | 1426/2000 [01:16<00:30, 18.72it/s]

Epoch 10:  71%|███████▏  | 1428/2000 [01:16<00:30, 18.72it/s]

Epoch 10:  72%|███████▏  | 1430/2000 [01:16<00:30, 18.70it/s]

Epoch 10:  72%|███████▏  | 1432/2000 [01:16<00:30, 18.71it/s]

Epoch 10:  72%|███████▏  | 1434/2000 [01:16<00:30, 18.72it/s]

Epoch 10:  72%|███████▏  | 1436/2000 [01:17<00:30, 18.72it/s]

Epoch 10:  72%|███████▏  | 1438/2000 [01:17<00:30, 18.72it/s]

Epoch 10:  72%|███████▏  | 1440/2000 [01:17<00:29, 18.71it/s]

Epoch 10:  72%|███████▏  | 1442/2000 [01:17<00:29, 18.73it/s]

Epoch 10:  72%|███████▏  | 1444/2000 [01:17<00:29, 18.74it/s]

Epoch 10:  72%|███████▏  | 1446/2000 [01:17<00:29, 18.73it/s]

Epoch 10:  72%|███████▏  | 1448/2000 [01:17<00:29, 18.73it/s]

Epoch 10:  72%|███████▎  | 1450/2000 [01:17<00:29, 18.72it/s]

Epoch 10:  73%|███████▎  | 1452/2000 [01:17<00:29, 18.73it/s]

Epoch 10:  73%|███████▎  | 1454/2000 [01:18<00:29, 18.71it/s]

Epoch 10:  73%|███████▎  | 1456/2000 [01:18<00:29, 18.72it/s]

Epoch 10:  73%|███████▎  | 1458/2000 [01:18<00:28, 18.72it/s]

Epoch 10:  73%|███████▎  | 1460/2000 [01:18<00:28, 18.72it/s]

Epoch 10:  73%|███████▎  | 1462/2000 [01:18<00:28, 18.73it/s]

Epoch 10:  73%|███████▎  | 1464/2000 [01:18<00:28, 18.73it/s]

Epoch 10:  73%|███████▎  | 1466/2000 [01:18<00:28, 18.72it/s]

Epoch 10:  73%|███████▎  | 1468/2000 [01:18<00:28, 18.73it/s]

Epoch 10:  74%|███████▎  | 1470/2000 [01:18<00:28, 18.73it/s]

Epoch 10:  74%|███████▎  | 1472/2000 [01:18<00:28, 18.72it/s]

Epoch 10:  74%|███████▎  | 1474/2000 [01:19<00:28, 18.72it/s]

Epoch 10:  74%|███████▍  | 1476/2000 [01:19<00:27, 18.74it/s]

Epoch 10:  74%|███████▍  | 1478/2000 [01:19<00:27, 18.74it/s]

Epoch 10:  74%|███████▍  | 1480/2000 [01:19<00:27, 18.74it/s]

Epoch 10:  74%|███████▍  | 1482/2000 [01:19<00:27, 18.75it/s]

Epoch 10:  74%|███████▍  | 1484/2000 [01:19<00:27, 18.75it/s]

Epoch 10:  74%|███████▍  | 1486/2000 [01:19<00:27, 18.75it/s]

Epoch 10:  74%|███████▍  | 1488/2000 [01:19<00:27, 18.75it/s]

Epoch 10:  74%|███████▍  | 1490/2000 [01:19<00:27, 18.74it/s]

Epoch 10:  75%|███████▍  | 1492/2000 [01:20<00:27, 18.74it/s]

Epoch 10:  75%|███████▍  | 1494/2000 [01:20<00:27, 18.74it/s]

Epoch 10:  75%|███████▍  | 1496/2000 [01:20<00:26, 18.73it/s]

Epoch 10:  75%|███████▍  | 1498/2000 [01:20<00:26, 18.74it/s]

Epoch 10:  75%|███████▌  | 1500/2000 [01:20<00:26, 18.74it/s]

Epoch 10:  75%|███████▌  | 1502/2000 [01:20<00:26, 18.74it/s]

Epoch 10:  75%|███████▌  | 1504/2000 [01:20<00:26, 18.73it/s]

Epoch 10:  75%|███████▌  | 1506/2000 [01:20<00:26, 18.75it/s]

Epoch 10:  75%|███████▌  | 1508/2000 [01:20<00:26, 18.74it/s]

Epoch 10:  76%|███████▌  | 1510/2000 [01:21<00:26, 18.74it/s]

Epoch 10:  76%|███████▌  | 1512/2000 [01:21<00:26, 18.75it/s]

Epoch 10:  76%|███████▌  | 1514/2000 [01:21<00:25, 18.75it/s]

Epoch 10:  76%|███████▌  | 1516/2000 [01:21<00:25, 18.74it/s]

Epoch 10:  76%|███████▌  | 1518/2000 [01:21<00:25, 18.75it/s]

Epoch 10:  76%|███████▌  | 1520/2000 [01:21<00:25, 18.75it/s]

Epoch 10:  76%|███████▌  | 1522/2000 [01:21<00:25, 18.75it/s]

Epoch 10:  76%|███████▌  | 1524/2000 [01:21<00:25, 18.73it/s]

Epoch 10:  76%|███████▋  | 1526/2000 [01:21<00:25, 18.72it/s]

Epoch 10:  76%|███████▋  | 1528/2000 [01:21<00:25, 18.72it/s]

Epoch 10:  76%|███████▋  | 1530/2000 [01:22<00:25, 18.73it/s]

Epoch 10:  77%|███████▋  | 1532/2000 [01:22<00:24, 18.72it/s]

Epoch 10:  77%|███████▋  | 1534/2000 [01:22<00:24, 18.72it/s]

Epoch 10:  77%|███████▋  | 1536/2000 [01:22<00:24, 18.71it/s]

Epoch 10:  77%|███████▋  | 1538/2000 [01:22<00:24, 18.72it/s]

Epoch 10:  77%|███████▋  | 1540/2000 [01:22<00:24, 18.72it/s]

Epoch 10:  77%|███████▋  | 1542/2000 [01:22<00:24, 18.72it/s]

Epoch 10:  77%|███████▋  | 1544/2000 [01:22<00:24, 18.71it/s]

Epoch 10:  77%|███████▋  | 1546/2000 [01:22<00:24, 18.72it/s]

Epoch 10:  77%|███████▋  | 1548/2000 [01:23<00:24, 18.72it/s]

Epoch 10:  78%|███████▊  | 1550/2000 [01:23<00:24, 18.72it/s]

Epoch 10:  78%|███████▊  | 1552/2000 [01:23<00:23, 18.73it/s]

Epoch 10:  78%|███████▊  | 1554/2000 [01:23<00:23, 18.73it/s]

Epoch 10:  78%|███████▊  | 1556/2000 [01:23<00:23, 18.73it/s]

Epoch 10:  78%|███████▊  | 1558/2000 [01:23<00:23, 18.72it/s]

Epoch 10:  78%|███████▊  | 1560/2000 [01:23<00:23, 18.71it/s]

Epoch 10:  78%|███████▊  | 1562/2000 [01:23<00:23, 18.69it/s]

Epoch 10:  78%|███████▊  | 1564/2000 [01:23<00:23, 18.69it/s]

Epoch 10:  78%|███████▊  | 1566/2000 [01:23<00:23, 18.70it/s]

Epoch 10:  78%|███████▊  | 1568/2000 [01:24<00:23, 18.72it/s]

Epoch 10:  78%|███████▊  | 1570/2000 [01:24<00:22, 18.71it/s]

Epoch 10:  79%|███████▊  | 1572/2000 [01:24<00:22, 18.72it/s]

Epoch 10:  79%|███████▊  | 1574/2000 [01:24<00:22, 18.72it/s]

Epoch 10:  79%|███████▉  | 1576/2000 [01:24<00:22, 18.72it/s]

Epoch 10:  79%|███████▉  | 1578/2000 [01:24<00:22, 18.72it/s]

Epoch 10:  79%|███████▉  | 1580/2000 [01:24<00:22, 18.73it/s]

Epoch 10:  79%|███████▉  | 1582/2000 [01:24<00:22, 18.72it/s]

Epoch 10:  79%|███████▉  | 1584/2000 [01:24<00:22, 18.72it/s]

Epoch 10:  79%|███████▉  | 1586/2000 [01:25<00:22, 18.73it/s]

Epoch 10:  79%|███████▉  | 1588/2000 [01:25<00:22, 18.72it/s]

Epoch 10:  80%|███████▉  | 1590/2000 [01:25<00:21, 18.71it/s]

Epoch 10:  80%|███████▉  | 1592/2000 [01:25<00:21, 18.72it/s]

Epoch 10:  80%|███████▉  | 1594/2000 [01:25<00:21, 18.73it/s]

Epoch 10:  80%|███████▉  | 1596/2000 [01:25<00:21, 18.73it/s]

Epoch 10:  80%|███████▉  | 1598/2000 [01:25<00:21, 18.73it/s]

Epoch 10:  80%|████████  | 1600/2000 [01:25<00:21, 18.72it/s]

Epoch 10:  80%|████████  | 1602/2000 [01:25<00:21, 18.72it/s]

Epoch 10:  80%|████████  | 1604/2000 [01:26<00:21, 18.72it/s]

Epoch 10:  80%|████████  | 1606/2000 [01:26<00:21, 18.73it/s]

Epoch 10:  80%|████████  | 1608/2000 [01:26<00:20, 18.74it/s]

Epoch 10:  80%|████████  | 1610/2000 [01:26<00:20, 18.73it/s]

Epoch 10:  81%|████████  | 1612/2000 [01:26<00:20, 18.74it/s]

Epoch 10:  81%|████████  | 1614/2000 [01:26<00:20, 18.73it/s]

Epoch 10:  81%|████████  | 1616/2000 [01:26<00:20, 18.61it/s]

Epoch 10:  81%|████████  | 1618/2000 [01:26<00:20, 18.63it/s]

Epoch 10:  81%|████████  | 1620/2000 [01:26<00:20, 18.66it/s]

Epoch 10:  81%|████████  | 1622/2000 [01:26<00:20, 18.66it/s]

Epoch 10:  81%|████████  | 1624/2000 [01:27<00:20, 18.67it/s]

Epoch 10:  81%|████████▏ | 1626/2000 [01:27<00:20, 18.67it/s]

Epoch 10:  81%|████████▏ | 1628/2000 [01:27<00:19, 18.69it/s]

Epoch 10:  82%|████████▏ | 1630/2000 [01:27<00:19, 18.70it/s]

Epoch 10:  82%|████████▏ | 1632/2000 [01:27<00:19, 18.71it/s]

Epoch 10:  82%|████████▏ | 1634/2000 [01:27<00:19, 18.72it/s]

Epoch 10:  82%|████████▏ | 1636/2000 [01:27<00:19, 18.73it/s]

Epoch 10:  82%|████████▏ | 1638/2000 [01:27<00:19, 18.73it/s]

Epoch 10:  82%|████████▏ | 1640/2000 [01:27<00:19, 18.73it/s]

Epoch 10:  82%|████████▏ | 1642/2000 [01:28<00:19, 18.72it/s]

Epoch 10:  82%|████████▏ | 1644/2000 [01:28<00:19, 18.73it/s]

Epoch 10:  82%|████████▏ | 1646/2000 [01:28<00:18, 18.74it/s]

Epoch 10:  82%|████████▏ | 1648/2000 [01:28<00:18, 18.74it/s]

Epoch 10:  82%|████████▎ | 1650/2000 [01:28<00:18, 18.72it/s]

Epoch 10:  83%|████████▎ | 1652/2000 [01:28<00:18, 18.73it/s]

Epoch 10:  83%|████████▎ | 1654/2000 [01:28<00:18, 18.73it/s]

Epoch 10:  83%|████████▎ | 1656/2000 [01:28<00:18, 18.73it/s]

Epoch 10:  83%|████████▎ | 1658/2000 [01:28<00:18, 18.71it/s]

Epoch 10:  83%|████████▎ | 1660/2000 [01:29<00:18, 18.69it/s]

Epoch 10:  83%|████████▎ | 1662/2000 [01:29<00:18, 18.61it/s]

Epoch 10:  83%|████████▎ | 1664/2000 [01:29<00:18, 18.59it/s]

Epoch 10:  83%|████████▎ | 1666/2000 [01:29<00:17, 18.58it/s]

Epoch 10:  83%|████████▎ | 1668/2000 [01:29<00:17, 18.57it/s]

Epoch 10:  84%|████████▎ | 1670/2000 [01:29<00:17, 18.56it/s]

Epoch 10:  84%|████████▎ | 1672/2000 [01:29<00:17, 18.55it/s]

Epoch 10:  84%|████████▎ | 1674/2000 [01:29<00:17, 18.54it/s]

Epoch 10:  84%|████████▍ | 1676/2000 [01:29<00:17, 18.54it/s]

Epoch 10:  84%|████████▍ | 1678/2000 [01:29<00:17, 18.54it/s]

Epoch 10:  84%|████████▍ | 1680/2000 [01:30<00:17, 18.51it/s]

Epoch 10:  84%|████████▍ | 1682/2000 [01:30<00:17, 18.52it/s]

Epoch 10:  84%|████████▍ | 1684/2000 [01:30<00:17, 18.53it/s]

Epoch 10:  84%|████████▍ | 1686/2000 [01:30<00:16, 18.53it/s]

Epoch 10:  84%|████████▍ | 1688/2000 [01:30<00:16, 18.53it/s]

Epoch 10:  84%|████████▍ | 1690/2000 [01:30<00:16, 18.53it/s]

Epoch 10:  85%|████████▍ | 1692/2000 [01:30<00:16, 18.53it/s]

Epoch 10:  85%|████████▍ | 1694/2000 [01:30<00:16, 18.53it/s]

Epoch 10:  85%|████████▍ | 1696/2000 [01:30<00:16, 18.52it/s]

Epoch 10:  85%|████████▍ | 1698/2000 [01:31<00:16, 18.48it/s]

Epoch 10:  85%|████████▌ | 1700/2000 [01:31<00:16, 18.49it/s]

Epoch 10:  85%|████████▌ | 1702/2000 [01:31<00:16, 18.51it/s]

Epoch 10:  85%|████████▌ | 1704/2000 [01:31<00:15, 18.52it/s]

Epoch 10:  85%|████████▌ | 1706/2000 [01:31<00:15, 18.53it/s]

Epoch 10:  85%|████████▌ | 1708/2000 [01:31<00:15, 18.54it/s]

Epoch 10:  86%|████████▌ | 1710/2000 [01:31<00:15, 18.53it/s]

Epoch 10:  86%|████████▌ | 1712/2000 [01:31<00:15, 18.52it/s]

Epoch 10:  86%|████████▌ | 1714/2000 [01:31<00:15, 18.53it/s]

Epoch 10:  86%|████████▌ | 1716/2000 [01:32<00:15, 18.52it/s]

Epoch 10:  86%|████████▌ | 1718/2000 [01:32<00:15, 18.52it/s]

Epoch 10:  86%|████████▌ | 1720/2000 [01:32<00:15, 18.52it/s]

Epoch 10:  86%|████████▌ | 1722/2000 [01:32<00:15, 18.52it/s]

Epoch 10:  86%|████████▌ | 1724/2000 [01:32<00:14, 18.52it/s]

Epoch 10:  86%|████████▋ | 1726/2000 [01:32<00:14, 18.53it/s]

Epoch 10:  86%|████████▋ | 1728/2000 [01:32<00:14, 18.53it/s]

Epoch 10:  86%|████████▋ | 1730/2000 [01:32<00:14, 18.52it/s]

Epoch 10:  87%|████████▋ | 1732/2000 [01:32<00:14, 18.51it/s]

Epoch 10:  87%|████████▋ | 1734/2000 [01:33<00:14, 18.51it/s]

Epoch 10:  87%|████████▋ | 1736/2000 [01:33<00:14, 18.49it/s]

Epoch 10:  87%|████████▋ | 1738/2000 [01:33<00:14, 18.50it/s]

Epoch 10:  87%|████████▋ | 1740/2000 [01:33<00:14, 18.52it/s]

Epoch 10:  87%|████████▋ | 1742/2000 [01:33<00:13, 18.53it/s]

Epoch 10:  87%|████████▋ | 1744/2000 [01:33<00:13, 18.52it/s]

Epoch 10:  87%|████████▋ | 1746/2000 [01:33<00:13, 18.53it/s]

Epoch 10:  87%|████████▋ | 1748/2000 [01:33<00:13, 18.52it/s]

Epoch 10:  88%|████████▊ | 1750/2000 [01:33<00:13, 18.52it/s]

Epoch 10:  88%|████████▊ | 1752/2000 [01:33<00:13, 18.52it/s]

Epoch 10:  88%|████████▊ | 1754/2000 [01:34<00:13, 18.53it/s]

Epoch 10:  88%|████████▊ | 1756/2000 [01:34<00:13, 18.52it/s]

Epoch 10:  88%|████████▊ | 1758/2000 [01:34<00:13, 18.53it/s]

Epoch 10:  88%|████████▊ | 1760/2000 [01:34<00:12, 18.53it/s]

Epoch 10:  88%|████████▊ | 1762/2000 [01:34<00:12, 18.54it/s]

Epoch 10:  88%|████████▊ | 1764/2000 [01:34<00:12, 18.55it/s]

Epoch 10:  88%|████████▊ | 1766/2000 [01:34<00:12, 18.54it/s]

Epoch 10:  88%|████████▊ | 1768/2000 [01:34<00:12, 18.54it/s]

Epoch 10:  88%|████████▊ | 1770/2000 [01:34<00:12, 18.53it/s]

Epoch 10:  89%|████████▊ | 1772/2000 [01:35<00:12, 18.53it/s]

Epoch 10:  89%|████████▊ | 1774/2000 [01:35<00:12, 18.52it/s]

Epoch 10:  89%|████████▉ | 1776/2000 [01:35<00:12, 18.53it/s]

Epoch 10:  89%|████████▉ | 1778/2000 [01:35<00:11, 18.53it/s]

Epoch 10:  89%|████████▉ | 1780/2000 [01:35<00:11, 18.53it/s]

Epoch 10:  89%|████████▉ | 1782/2000 [01:35<00:11, 18.52it/s]

Epoch 10:  89%|████████▉ | 1784/2000 [01:35<00:11, 18.53it/s]

Epoch 10:  89%|████████▉ | 1786/2000 [01:35<00:11, 18.52it/s]

Epoch 10:  89%|████████▉ | 1788/2000 [01:35<00:11, 18.53it/s]

Epoch 10:  90%|████████▉ | 1790/2000 [01:36<00:11, 18.53it/s]

Epoch 10:  90%|████████▉ | 1792/2000 [01:36<00:11, 18.54it/s]

Epoch 10:  90%|████████▉ | 1794/2000 [01:36<00:11, 18.54it/s]

Epoch 10:  90%|████████▉ | 1796/2000 [01:36<00:11, 18.54it/s]

Epoch 10:  90%|████████▉ | 1798/2000 [01:36<00:10, 18.53it/s]

Epoch 10:  90%|█████████ | 1800/2000 [01:36<00:10, 18.50it/s]

Epoch 10:  90%|█████████ | 1802/2000 [01:36<00:10, 18.32it/s]

Epoch 10:  90%|█████████ | 1804/2000 [01:36<00:11, 17.76it/s]

Epoch 10:  90%|█████████ | 1806/2000 [01:36<00:10, 17.79it/s]

Epoch 10:  90%|█████████ | 1808/2000 [01:37<00:10, 17.99it/s]

Epoch 10:  90%|█████████ | 1810/2000 [01:37<00:10, 18.09it/s]

Epoch 10:  91%|█████████ | 1812/2000 [01:37<00:10, 18.21it/s]

Epoch 10:  91%|█████████ | 1814/2000 [01:37<00:10, 18.31it/s]

Epoch 10:  91%|█████████ | 1816/2000 [01:37<00:10, 18.38it/s]

Epoch 10:  91%|█████████ | 1818/2000 [01:37<00:09, 18.42it/s]

Epoch 10:  91%|█████████ | 1820/2000 [01:37<00:09, 18.46it/s]

Epoch 10:  91%|█████████ | 1822/2000 [01:37<00:09, 18.48it/s]

Epoch 10:  91%|█████████ | 1824/2000 [01:37<00:09, 18.49it/s]

Epoch 10:  91%|█████████▏| 1826/2000 [01:37<00:09, 18.52it/s]

Epoch 10:  91%|█████████▏| 1828/2000 [01:38<00:09, 18.53it/s]

Epoch 10:  92%|█████████▏| 1830/2000 [01:38<00:09, 18.54it/s]

Epoch 10:  92%|█████████▏| 1832/2000 [01:38<00:09, 18.54it/s]

Epoch 10:  92%|█████████▏| 1834/2000 [01:38<00:08, 18.54it/s]

Epoch 10:  92%|█████████▏| 1836/2000 [01:38<00:08, 18.54it/s]

Epoch 10:  92%|█████████▏| 1838/2000 [01:38<00:08, 18.54it/s]

Epoch 10:  92%|█████████▏| 1840/2000 [01:38<00:08, 18.55it/s]

Epoch 10:  92%|█████████▏| 1842/2000 [01:38<00:08, 18.54it/s]

Epoch 10:  92%|█████████▏| 1844/2000 [01:38<00:08, 18.53it/s]

Epoch 10:  92%|█████████▏| 1846/2000 [01:39<00:08, 18.53it/s]

Epoch 10:  92%|█████████▏| 1848/2000 [01:39<00:08, 18.55it/s]

Epoch 10:  92%|█████████▎| 1850/2000 [01:39<00:08, 18.54it/s]

Epoch 10:  93%|█████████▎| 1852/2000 [01:39<00:07, 18.55it/s]

Epoch 10:  93%|█████████▎| 1854/2000 [01:39<00:07, 18.55it/s]

Epoch 10:  93%|█████████▎| 1856/2000 [01:39<00:07, 18.56it/s]

Epoch 10:  93%|█████████▎| 1858/2000 [01:39<00:07, 18.56it/s]

Epoch 10:  93%|█████████▎| 1860/2000 [01:39<00:07, 18.55it/s]

Epoch 10:  93%|█████████▎| 1862/2000 [01:39<00:07, 18.55it/s]

Epoch 10:  93%|█████████▎| 1864/2000 [01:40<00:07, 18.55it/s]

Epoch 10:  93%|█████████▎| 1866/2000 [01:40<00:07, 18.55it/s]

Epoch 10:  93%|█████████▎| 1868/2000 [01:40<00:07, 18.55it/s]

Epoch 10:  94%|█████████▎| 1870/2000 [01:40<00:07, 18.56it/s]

Epoch 10:  94%|█████████▎| 1872/2000 [01:40<00:06, 18.54it/s]

Epoch 10:  94%|█████████▎| 1874/2000 [01:40<00:06, 18.55it/s]

Epoch 10:  94%|█████████▍| 1876/2000 [01:40<00:06, 18.55it/s]

Epoch 10:  94%|█████████▍| 1878/2000 [01:40<00:06, 18.54it/s]

Epoch 10:  94%|█████████▍| 1880/2000 [01:40<00:06, 18.53it/s]

Epoch 10:  94%|█████████▍| 1882/2000 [01:41<00:06, 18.53it/s]

Epoch 10:  94%|█████████▍| 1884/2000 [01:41<00:06, 18.53it/s]

Epoch 10:  94%|█████████▍| 1886/2000 [01:41<00:06, 18.53it/s]

Epoch 10:  94%|█████████▍| 1888/2000 [01:41<00:06, 18.55it/s]

Epoch 10:  94%|█████████▍| 1890/2000 [01:41<00:05, 18.55it/s]

Epoch 10:  95%|█████████▍| 1892/2000 [01:41<00:05, 18.57it/s]

Epoch 10:  95%|█████████▍| 1894/2000 [01:41<00:05, 18.56it/s]

Epoch 10:  95%|█████████▍| 1896/2000 [01:41<00:05, 18.53it/s]

Epoch 10:  95%|█████████▍| 1898/2000 [01:41<00:05, 18.53it/s]

Epoch 10:  95%|█████████▌| 1900/2000 [01:41<00:05, 18.54it/s]

Epoch 10:  95%|█████████▌| 1902/2000 [01:42<00:05, 18.55it/s]

Epoch 10:  95%|█████████▌| 1904/2000 [01:42<00:05, 18.55it/s]

Epoch 10:  95%|█████████▌| 1906/2000 [01:42<00:05, 18.55it/s]

Epoch 10:  95%|█████████▌| 1908/2000 [01:42<00:04, 18.55it/s]

Epoch 10:  96%|█████████▌| 1910/2000 [01:42<00:04, 18.56it/s]

Epoch 10:  96%|█████████▌| 1912/2000 [01:42<00:04, 18.57it/s]

Epoch 10:  96%|█████████▌| 1914/2000 [01:42<00:04, 18.55it/s]

Epoch 10:  96%|█████████▌| 1916/2000 [01:42<00:04, 18.55it/s]

Epoch 10:  96%|█████████▌| 1918/2000 [01:42<00:04, 18.55it/s]

Epoch 10:  96%|█████████▌| 1920/2000 [01:43<00:04, 18.56it/s]

Epoch 10:  96%|█████████▌| 1922/2000 [01:43<00:04, 18.55it/s]

Epoch 10:  96%|█████████▌| 1924/2000 [01:43<00:04, 18.54it/s]

Epoch 10:  96%|█████████▋| 1926/2000 [01:43<00:03, 18.53it/s]

Epoch 10:  96%|█████████▋| 1928/2000 [01:43<00:03, 18.53it/s]

Epoch 10:  96%|█████████▋| 1930/2000 [01:43<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1932/2000 [01:43<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1934/2000 [01:43<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1936/2000 [01:43<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1938/2000 [01:44<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1940/2000 [01:44<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1942/2000 [01:44<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1944/2000 [01:44<00:03, 18.55it/s]

Epoch 10:  97%|█████████▋| 1946/2000 [01:44<00:02, 18.55it/s]

Epoch 10:  97%|█████████▋| 1948/2000 [01:44<00:02, 18.57it/s]

Epoch 10:  98%|█████████▊| 1950/2000 [01:44<00:02, 18.54it/s]

Epoch 10:  98%|█████████▊| 1952/2000 [01:44<00:02, 18.55it/s]

Epoch 10:  98%|█████████▊| 1954/2000 [01:44<00:02, 18.55it/s]

Epoch 10:  98%|█████████▊| 1956/2000 [01:45<00:02, 18.55it/s]

Epoch 10:  98%|█████████▊| 1958/2000 [01:45<00:02, 18.56it/s]

Epoch 10:  98%|█████████▊| 1960/2000 [01:45<00:02, 18.56it/s]

Epoch 10:  98%|█████████▊| 1962/2000 [01:45<00:02, 18.56it/s]

Epoch 10:  98%|█████████▊| 1964/2000 [01:45<00:01, 18.56it/s]

Epoch 10:  98%|█████████▊| 1966/2000 [01:45<00:01, 18.55it/s]

Epoch 10:  98%|█████████▊| 1968/2000 [01:45<00:01, 18.56it/s]

Epoch 10:  98%|█████████▊| 1970/2000 [01:45<00:01, 18.55it/s]

Epoch 10:  99%|█████████▊| 1972/2000 [01:45<00:01, 18.55it/s]

Epoch 10:  99%|█████████▊| 1974/2000 [01:45<00:01, 18.56it/s]

Epoch 10:  99%|█████████▉| 1976/2000 [01:46<00:01, 18.55it/s]

Epoch 10:  99%|█████████▉| 1978/2000 [01:46<00:01, 18.55it/s]

Epoch 10:  99%|█████████▉| 1980/2000 [01:46<00:01, 18.55it/s]

Epoch 10:  99%|█████████▉| 1982/2000 [01:46<00:00, 18.55it/s]

Epoch 10:  99%|█████████▉| 1984/2000 [01:46<00:00, 18.56it/s]

Epoch 10:  99%|█████████▉| 1986/2000 [01:46<00:00, 18.56it/s]

Epoch 10:  99%|█████████▉| 1988/2000 [01:46<00:00, 18.56it/s]

Epoch 10: 100%|█████████▉| 1990/2000 [01:46<00:00, 18.56it/s]

Epoch 10: 100%|█████████▉| 1992/2000 [01:46<00:00, 18.57it/s]

Epoch 10: 100%|█████████▉| 1994/2000 [01:47<00:00, 18.57it/s]

Epoch 10: 100%|█████████▉| 1996/2000 [01:47<00:00, 18.56it/s]

Epoch 10: 100%|█████████▉| 1998/2000 [01:47<00:00, 18.55it/s]

Epoch 10: 100%|██████████| 2000/2000 [01:47<00:00, 18.55it/s]

Epoch 10: loss=0.1841, val_proxy=0.9244
Early stopping at epoch 10 (no val_proxy improvement in 10 epochs) -- best val_proxy=0.9578 at epoch 0.

    epoch      loss  val_proxy model
0       0  0.297522   0.957812  sata
1       1  0.263646   0.943906  sata
2       2  0.247322   0.944844  sata
3       3  0.235432   0.944531  sata
4       4  0.224317   0.940156  sata
5       5  0.216213   0.940937  sata
6       6  0.207956   0.930937  sata
7       7  0.200386   0.931719  sata
8       8  0.194182   0.924844  sata
9       9  0.189101   0.932656  sata
10     10  0.184065   0.924375  sata

## SATA ablation: query-agnostic variant

Trained identically to the main model (same data, same loss, same schedule) — the only difference is `SATAQueryAgnostic` zeroing the query before scoring (see the Architecture cell above). If this variant scores nearly as well as full SATA in the Gate 2 check below, query-conditioning isn't pulling its weight and RQ4's story becomes "demonstration reweighting helps, but not because it's query-specific."

In [4]:
query_agnostic_model = SATAQueryAgnostic(
    n_features=config.generator.n_features,
    d_model=config.sata.d_model,
    n_heads=config.sata.n_heads,
    n_layers=config.sata.n_layers,
)
query_agnostic_log = train_sata(
    query_agnostic_model, train_tasks, val_tasks, sata_cfg,
    checkpoint_path=resolve_path('models/sata_query_agnostic.pt'),
    resume_checkpoint_path=resolve_path('models/sata_query_agnostic_resume.pt'),
)
query_agnostic_log_df = pd.DataFrame(query_agnostic_log)
query_agnostic_log_df['model'] = 'sata_query_agnostic'
query_agnostic_log_df

Epoch 0:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 0:   0%|          | 3/2000 [00:00<01:33, 21.24it/s]

Epoch 0:   0%|          | 6/2000 [00:00<01:33, 21.41it/s]

Epoch 0:   0%|          | 9/2000 [00:00<01:32, 21.46it/s]

Epoch 0:   1%|          | 12/2000 [00:00<01:32, 21.51it/s]

Epoch 0:   1%|          | 15/2000 [00:00<01:32, 21.55it/s]

Epoch 0:   1%|          | 18/2000 [00:00<01:31, 21.57it/s]

Epoch 0:   1%|          | 21/2000 [00:00<01:31, 21.57it/s]

Epoch 0:   1%|          | 24/2000 [00:01<01:31, 21.58it/s]

Epoch 0:   1%|▏         | 27/2000 [00:01<01:31, 21.60it/s]

Epoch 0:   2%|▏         | 30/2000 [00:01<01:31, 21.60it/s]

Epoch 0:   2%|▏         | 33/2000 [00:01<01:31, 21.60it/s]

Epoch 0:   2%|▏         | 36/2000 [00:01<01:30, 21.59it/s]

Epoch 0:   2%|▏         | 39/2000 [00:01<01:30, 21.58it/s]

Epoch 0:   2%|▏         | 42/2000 [00:01<01:30, 21.58it/s]

Epoch 0:   2%|▏         | 45/2000 [00:02<01:30, 21.60it/s]

Epoch 0:   2%|▏         | 48/2000 [00:02<01:30, 21.55it/s]

Epoch 0:   3%|▎         | 51/2000 [00:02<01:30, 21.56it/s]

Epoch 0:   3%|▎         | 54/2000 [00:02<01:30, 21.57it/s]

Epoch 0:   3%|▎         | 57/2000 [00:02<01:30, 21.48it/s]

Epoch 0:   3%|▎         | 60/2000 [00:02<01:30, 21.50it/s]

Epoch 0:   3%|▎         | 63/2000 [00:02<01:30, 21.51it/s]

Epoch 0:   3%|▎         | 66/2000 [00:03<01:29, 21.51it/s]

Epoch 0:   3%|▎         | 69/2000 [00:03<01:29, 21.52it/s]

Epoch 0:   4%|▎         | 72/2000 [00:03<01:29, 21.53it/s]

Epoch 0:   4%|▍         | 75/2000 [00:03<01:29, 21.54it/s]

Epoch 0:   4%|▍         | 78/2000 [00:03<01:29, 21.55it/s]

Epoch 0:   4%|▍         | 81/2000 [00:03<01:29, 21.54it/s]

Epoch 0:   4%|▍         | 84/2000 [00:03<01:28, 21.56it/s]

Epoch 0:   4%|▍         | 87/2000 [00:04<01:28, 21.56it/s]

Epoch 0:   4%|▍         | 90/2000 [00:04<01:28, 21.56it/s]

Epoch 0:   5%|▍         | 93/2000 [00:04<01:28, 21.55it/s]

Epoch 0:   5%|▍         | 96/2000 [00:04<01:28, 21.55it/s]

Epoch 0:   5%|▍         | 99/2000 [00:04<01:28, 21.56it/s]

Epoch 0:   5%|▌         | 102/2000 [00:04<01:27, 21.57it/s]

Epoch 0:   5%|▌         | 105/2000 [00:04<01:27, 21.57it/s]

Epoch 0:   5%|▌         | 108/2000 [00:05<01:27, 21.56it/s]

Epoch 0:   6%|▌         | 111/2000 [00:05<01:27, 21.54it/s]

Epoch 0:   6%|▌         | 114/2000 [00:05<01:27, 21.53it/s]

Epoch 0:   6%|▌         | 117/2000 [00:05<01:27, 21.54it/s]

Epoch 0:   6%|▌         | 120/2000 [00:05<01:27, 21.54it/s]

Epoch 0:   6%|▌         | 123/2000 [00:05<01:27, 21.54it/s]

Epoch 0:   6%|▋         | 126/2000 [00:05<01:27, 21.36it/s]

Epoch 0:   6%|▋         | 129/2000 [00:05<01:27, 21.42it/s]

Epoch 0:   7%|▋         | 132/2000 [00:06<01:27, 21.46it/s]

Epoch 0:   7%|▋         | 135/2000 [00:06<01:26, 21.51it/s]

Epoch 0:   7%|▋         | 138/2000 [00:06<01:26, 21.52it/s]

Epoch 0:   7%|▋         | 141/2000 [00:06<01:26, 21.53it/s]

Epoch 0:   7%|▋         | 144/2000 [00:06<01:26, 21.55it/s]

Epoch 0:   7%|▋         | 147/2000 [00:06<01:25, 21.56it/s]

Epoch 0:   8%|▊         | 150/2000 [00:06<01:25, 21.57it/s]

Epoch 0:   8%|▊         | 153/2000 [00:07<01:25, 21.58it/s]

Epoch 0:   8%|▊         | 156/2000 [00:07<01:25, 21.58it/s]

Epoch 0:   8%|▊         | 159/2000 [00:07<01:25, 21.58it/s]

Epoch 0:   8%|▊         | 162/2000 [00:07<01:25, 21.58it/s]

Epoch 0:   8%|▊         | 165/2000 [00:07<01:25, 21.58it/s]

Epoch 0:   8%|▊         | 168/2000 [00:07<01:24, 21.58it/s]

Epoch 0:   9%|▊         | 171/2000 [00:07<01:24, 21.58it/s]

Epoch 0:   9%|▊         | 174/2000 [00:08<01:24, 21.58it/s]

Epoch 0:   9%|▉         | 177/2000 [00:08<01:24, 21.59it/s]

Epoch 0:   9%|▉         | 180/2000 [00:08<01:24, 21.60it/s]

Epoch 0:   9%|▉         | 183/2000 [00:08<01:24, 21.59it/s]

Epoch 0:   9%|▉         | 186/2000 [00:08<01:24, 21.59it/s]

Epoch 0:   9%|▉         | 189/2000 [00:08<01:23, 21.60it/s]

Epoch 0:  10%|▉         | 192/2000 [00:08<01:23, 21.60it/s]

Epoch 0:  10%|▉         | 195/2000 [00:09<01:23, 21.60it/s]

Epoch 0:  10%|▉         | 198/2000 [00:09<01:23, 21.61it/s]

Epoch 0:  10%|█         | 201/2000 [00:09<01:23, 21.61it/s]

Epoch 0:  10%|█         | 204/2000 [00:09<01:23, 21.60it/s]

Epoch 0:  10%|█         | 207/2000 [00:09<01:23, 21.59it/s]

Epoch 0:  10%|█         | 210/2000 [00:09<01:22, 21.58it/s]

Epoch 0:  11%|█         | 213/2000 [00:09<01:22, 21.59it/s]

Epoch 0:  11%|█         | 216/2000 [00:10<01:22, 21.58it/s]

Epoch 0:  11%|█         | 219/2000 [00:10<01:22, 21.59it/s]

Epoch 0:  11%|█         | 222/2000 [00:10<01:22, 21.59it/s]

Epoch 0:  11%|█▏        | 225/2000 [00:10<01:22, 21.59it/s]

Epoch 0:  11%|█▏        | 228/2000 [00:10<01:22, 21.60it/s]

Epoch 0:  12%|█▏        | 231/2000 [00:10<01:21, 21.59it/s]

Epoch 0:  12%|█▏        | 234/2000 [00:10<01:21, 21.61it/s]

Epoch 0:  12%|█▏        | 237/2000 [00:10<01:21, 21.59it/s]

Epoch 0:  12%|█▏        | 240/2000 [00:11<01:21, 21.59it/s]

Epoch 0:  12%|█▏        | 243/2000 [00:11<01:21, 21.59it/s]

Epoch 0:  12%|█▏        | 246/2000 [00:11<01:21, 21.51it/s]

Epoch 0:  12%|█▏        | 249/2000 [00:11<01:21, 21.53it/s]

Epoch 0:  13%|█▎        | 252/2000 [00:11<01:21, 21.53it/s]

Epoch 0:  13%|█▎        | 255/2000 [00:11<01:21, 21.44it/s]

Epoch 0:  13%|█▎        | 258/2000 [00:11<01:20, 21.55it/s]

Epoch 0:  13%|█▎        | 261/2000 [00:12<01:20, 21.61it/s]

Epoch 0:  13%|█▎        | 264/2000 [00:12<01:20, 21.66it/s]

Epoch 0:  13%|█▎        | 267/2000 [00:12<01:19, 21.70it/s]

Epoch 0:  14%|█▎        | 270/2000 [00:12<01:19, 21.73it/s]

Epoch 0:  14%|█▎        | 273/2000 [00:12<01:19, 21.75it/s]

Epoch 0:  14%|█▍        | 276/2000 [00:12<01:19, 21.76it/s]

Epoch 0:  14%|█▍        | 279/2000 [00:12<01:19, 21.77it/s]

Epoch 0:  14%|█▍        | 282/2000 [00:13<01:18, 21.78it/s]

Epoch 0:  14%|█▍        | 285/2000 [00:13<01:18, 21.78it/s]

Epoch 0:  14%|█▍        | 288/2000 [00:13<01:18, 21.78it/s]

Epoch 0:  15%|█▍        | 291/2000 [00:13<01:18, 21.78it/s]

Epoch 0:  15%|█▍        | 294/2000 [00:13<01:18, 21.78it/s]

Epoch 0:  15%|█▍        | 297/2000 [00:13<01:18, 21.77it/s]

Epoch 0:  15%|█▌        | 300/2000 [00:13<01:18, 21.78it/s]

Epoch 0:  15%|█▌        | 303/2000 [00:14<01:17, 21.77it/s]

Epoch 0:  15%|█▌        | 306/2000 [00:14<01:17, 21.77it/s]

Epoch 0:  15%|█▌        | 309/2000 [00:14<01:17, 21.76it/s]

Epoch 0:  16%|█▌        | 312/2000 [00:14<01:17, 21.78it/s]

Epoch 0:  16%|█▌        | 315/2000 [00:14<01:17, 21.77it/s]

Epoch 0:  16%|█▌        | 318/2000 [00:14<01:17, 21.76it/s]

Epoch 0:  16%|█▌        | 321/2000 [00:14<01:17, 21.76it/s]

Epoch 0:  16%|█▌        | 324/2000 [00:14<01:16, 21.77it/s]

Epoch 0:  16%|█▋        | 327/2000 [00:15<01:16, 21.78it/s]

Epoch 0:  16%|█▋        | 330/2000 [00:15<01:16, 21.78it/s]

Epoch 0:  17%|█▋        | 333/2000 [00:15<01:16, 21.78it/s]

Epoch 0:  17%|█▋        | 336/2000 [00:15<01:16, 21.79it/s]

Epoch 0:  17%|█▋        | 339/2000 [00:15<01:16, 21.77it/s]

Epoch 0:  17%|█▋        | 342/2000 [00:15<01:16, 21.78it/s]

Epoch 0:  17%|█▋        | 345/2000 [00:15<01:15, 21.78it/s]

Epoch 0:  17%|█▋        | 348/2000 [00:16<01:15, 21.80it/s]

Epoch 0:  18%|█▊        | 351/2000 [00:16<01:15, 21.80it/s]

Epoch 0:  18%|█▊        | 354/2000 [00:16<01:15, 21.80it/s]

Epoch 0:  18%|█▊        | 357/2000 [00:16<01:15, 21.79it/s]

Epoch 0:  18%|█▊        | 360/2000 [00:16<01:15, 21.78it/s]

Epoch 0:  18%|█▊        | 363/2000 [00:16<01:15, 21.77it/s]

Epoch 0:  18%|█▊        | 366/2000 [00:16<01:15, 21.78it/s]

Epoch 0:  18%|█▊        | 369/2000 [00:17<01:14, 21.79it/s]

Epoch 0:  19%|█▊        | 372/2000 [00:17<01:14, 21.78it/s]

Epoch 0:  19%|█▉        | 375/2000 [00:17<01:14, 21.77it/s]

Epoch 0:  19%|█▉        | 378/2000 [00:17<01:14, 21.78it/s]

Epoch 0:  19%|█▉        | 381/2000 [00:17<01:14, 21.77it/s]

Epoch 0:  19%|█▉        | 384/2000 [00:17<01:14, 21.78it/s]

Epoch 0:  19%|█▉        | 387/2000 [00:17<01:14, 21.78it/s]

Epoch 0:  20%|█▉        | 390/2000 [00:18<01:13, 21.78it/s]

Epoch 0:  20%|█▉        | 393/2000 [00:18<01:13, 21.77it/s]

Epoch 0:  20%|█▉        | 396/2000 [00:18<01:13, 21.78it/s]

Epoch 0:  20%|█▉        | 399/2000 [00:18<01:13, 21.77it/s]

Epoch 0:  20%|██        | 402/2000 [00:18<01:13, 21.78it/s]

Epoch 0:  20%|██        | 405/2000 [00:18<01:13, 21.79it/s]

Epoch 0:  20%|██        | 408/2000 [00:18<01:13, 21.78it/s]

Epoch 0:  21%|██        | 411/2000 [00:18<01:12, 21.78it/s]

Epoch 0:  21%|██        | 414/2000 [00:19<01:12, 21.77it/s]

Epoch 0:  21%|██        | 417/2000 [00:19<01:12, 21.78it/s]

Epoch 0:  21%|██        | 420/2000 [00:19<01:12, 21.79it/s]

Epoch 0:  21%|██        | 423/2000 [00:19<01:12, 21.78it/s]

Epoch 0:  21%|██▏       | 426/2000 [00:19<01:12, 21.78it/s]

Epoch 0:  21%|██▏       | 429/2000 [00:19<01:12, 21.78it/s]

Epoch 0:  22%|██▏       | 432/2000 [00:19<01:12, 21.78it/s]

Epoch 0:  22%|██▏       | 435/2000 [00:20<01:11, 21.78it/s]

Epoch 0:  22%|██▏       | 438/2000 [00:20<01:11, 21.77it/s]

Epoch 0:  22%|██▏       | 441/2000 [00:20<01:11, 21.78it/s]

Epoch 0:  22%|██▏       | 444/2000 [00:20<01:11, 21.79it/s]

Epoch 0:  22%|██▏       | 447/2000 [00:20<01:11, 21.78it/s]

Epoch 0:  22%|██▎       | 450/2000 [00:20<01:11, 21.78it/s]

Epoch 0:  23%|██▎       | 453/2000 [00:20<01:11, 21.78it/s]

Epoch 0:  23%|██▎       | 456/2000 [00:21<01:10, 21.77it/s]

Epoch 0:  23%|██▎       | 459/2000 [00:21<01:10, 21.77it/s]

Epoch 0:  23%|██▎       | 462/2000 [00:21<01:10, 21.77it/s]

Epoch 0:  23%|██▎       | 465/2000 [00:21<01:10, 21.78it/s]

Epoch 0:  23%|██▎       | 468/2000 [00:21<01:10, 21.78it/s]

Epoch 0:  24%|██▎       | 471/2000 [00:21<01:10, 21.79it/s]

Epoch 0:  24%|██▎       | 474/2000 [00:21<01:10, 21.79it/s]

Epoch 0:  24%|██▍       | 477/2000 [00:22<01:09, 21.80it/s]

Epoch 0:  24%|██▍       | 480/2000 [00:22<01:09, 21.80it/s]

Epoch 0:  24%|██▍       | 483/2000 [00:22<01:09, 21.79it/s]

Epoch 0:  24%|██▍       | 486/2000 [00:22<01:09, 21.80it/s]

Epoch 0:  24%|██▍       | 489/2000 [00:22<01:09, 21.80it/s]

Epoch 0:  25%|██▍       | 492/2000 [00:22<01:09, 21.78it/s]

Epoch 0:  25%|██▍       | 495/2000 [00:22<01:09, 21.76it/s]

Epoch 0:  25%|██▍       | 498/2000 [00:22<01:09, 21.76it/s]

Epoch 0:  25%|██▌       | 501/2000 [00:23<01:08, 21.78it/s]

Epoch 0:  25%|██▌       | 504/2000 [00:23<01:08, 21.73it/s]

Epoch 0:  25%|██▌       | 507/2000 [00:23<01:08, 21.68it/s]

Epoch 0:  26%|██▌       | 510/2000 [00:23<01:08, 21.68it/s]

Epoch 0:  26%|██▌       | 513/2000 [00:23<01:08, 21.66it/s]

Epoch 0:  26%|██▌       | 516/2000 [00:23<01:08, 21.64it/s]

Epoch 0:  26%|██▌       | 519/2000 [00:23<01:08, 21.62it/s]

Epoch 0:  26%|██▌       | 522/2000 [00:24<01:08, 21.63it/s]

Epoch 0:  26%|██▋       | 525/2000 [00:24<01:08, 21.63it/s]

Epoch 0:  26%|██▋       | 528/2000 [00:24<01:08, 21.63it/s]

Epoch 0:  27%|██▋       | 531/2000 [00:24<01:07, 21.64it/s]

Epoch 0:  27%|██▋       | 534/2000 [00:24<01:07, 21.63it/s]

Epoch 0:  27%|██▋       | 537/2000 [00:24<01:07, 21.64it/s]

Epoch 0:  27%|██▋       | 540/2000 [00:24<01:07, 21.65it/s]

Epoch 0:  27%|██▋       | 543/2000 [00:25<01:07, 21.64it/s]

Epoch 0:  27%|██▋       | 546/2000 [00:25<01:07, 21.65it/s]

Epoch 0:  27%|██▋       | 549/2000 [00:25<01:07, 21.64it/s]

Epoch 0:  28%|██▊       | 552/2000 [00:25<01:06, 21.64it/s]

Epoch 0:  28%|██▊       | 555/2000 [00:25<01:06, 21.64it/s]

Epoch 0:  28%|██▊       | 558/2000 [00:25<01:06, 21.61it/s]

Epoch 0:  28%|██▊       | 561/2000 [00:25<01:06, 21.62it/s]

Epoch 0:  28%|██▊       | 564/2000 [00:26<01:06, 21.63it/s]

Epoch 0:  28%|██▊       | 567/2000 [00:26<01:06, 21.62it/s]

Epoch 0:  28%|██▊       | 570/2000 [00:26<01:06, 21.62it/s]

Epoch 0:  29%|██▊       | 573/2000 [00:26<01:06, 21.61it/s]

Epoch 0:  29%|██▉       | 576/2000 [00:26<01:05, 21.62it/s]

Epoch 0:  29%|██▉       | 579/2000 [00:26<01:05, 21.62it/s]

Epoch 0:  29%|██▉       | 582/2000 [00:26<01:05, 21.61it/s]

Epoch 0:  29%|██▉       | 585/2000 [00:27<01:05, 21.62it/s]

Epoch 0:  29%|██▉       | 588/2000 [00:27<01:05, 21.61it/s]

Epoch 0:  30%|██▉       | 591/2000 [00:27<01:05, 21.62it/s]

Epoch 0:  30%|██▉       | 594/2000 [00:27<01:04, 21.64it/s]

Epoch 0:  30%|██▉       | 597/2000 [00:27<01:04, 21.64it/s]

Epoch 0:  30%|███       | 600/2000 [00:27<01:04, 21.63it/s]

Epoch 0:  30%|███       | 603/2000 [00:27<01:04, 21.65it/s]

Epoch 0:  30%|███       | 606/2000 [00:27<01:04, 21.66it/s]

Epoch 0:  30%|███       | 609/2000 [00:28<01:04, 21.67it/s]

Epoch 0:  31%|███       | 612/2000 [00:28<01:03, 21.69it/s]

Epoch 0:  31%|███       | 615/2000 [00:28<01:03, 21.69it/s]

Epoch 0:  31%|███       | 618/2000 [00:28<01:03, 21.69it/s]

Epoch 0:  31%|███       | 621/2000 [00:28<01:03, 21.68it/s]

Epoch 0:  31%|███       | 624/2000 [00:28<01:03, 21.69it/s]

Epoch 0:  31%|███▏      | 627/2000 [00:28<01:03, 21.69it/s]

Epoch 0:  32%|███▏      | 630/2000 [00:29<01:03, 21.66it/s]

Epoch 0:  32%|███▏      | 633/2000 [00:29<01:03, 21.67it/s]

Epoch 0:  32%|███▏      | 636/2000 [00:29<01:02, 21.68it/s]

Epoch 0:  32%|███▏      | 639/2000 [00:29<01:02, 21.69it/s]

Epoch 0:  32%|███▏      | 642/2000 [00:29<01:02, 21.68it/s]

Epoch 0:  32%|███▏      | 645/2000 [00:29<01:02, 21.67it/s]

Epoch 0:  32%|███▏      | 648/2000 [00:29<01:02, 21.68it/s]

Epoch 0:  33%|███▎      | 651/2000 [00:30<01:02, 21.67it/s]

Epoch 0:  33%|███▎      | 654/2000 [00:30<01:02, 21.67it/s]

Epoch 0:  33%|███▎      | 657/2000 [00:30<01:01, 21.66it/s]

Epoch 0:  33%|███▎      | 660/2000 [00:30<01:01, 21.66it/s]

Epoch 0:  33%|███▎      | 663/2000 [00:30<01:01, 21.68it/s]

Epoch 0:  33%|███▎      | 666/2000 [00:30<01:01, 21.68it/s]

Epoch 0:  33%|███▎      | 669/2000 [00:30<01:01, 21.68it/s]

Epoch 0:  34%|███▎      | 672/2000 [00:31<01:01, 21.68it/s]

Epoch 0:  34%|███▍      | 675/2000 [00:31<01:01, 21.67it/s]

Epoch 0:  34%|███▍      | 678/2000 [00:31<01:00, 21.68it/s]

Epoch 0:  34%|███▍      | 681/2000 [00:31<01:00, 21.67it/s]

Epoch 0:  34%|███▍      | 684/2000 [00:31<01:00, 21.68it/s]

Epoch 0:  34%|███▍      | 687/2000 [00:31<01:00, 21.68it/s]

Epoch 0:  34%|███▍      | 690/2000 [00:31<01:00, 21.68it/s]

Epoch 0:  35%|███▍      | 693/2000 [00:31<01:00, 21.69it/s]

Epoch 0:  35%|███▍      | 696/2000 [00:32<01:01, 21.37it/s]

Epoch 0:  35%|███▍      | 699/2000 [00:32<01:02, 20.86it/s]

Epoch 0:  35%|███▌      | 702/2000 [00:32<01:01, 21.03it/s]

Epoch 0:  35%|███▌      | 705/2000 [00:32<01:01, 21.15it/s]

Epoch 0:  35%|███▌      | 708/2000 [00:32<01:00, 21.29it/s]

Epoch 0:  36%|███▌      | 711/2000 [00:32<01:00, 21.41it/s]

Epoch 0:  36%|███▌      | 714/2000 [00:32<01:00, 21.41it/s]

Epoch 0:  36%|███▌      | 717/2000 [00:33<00:59, 21.48it/s]

Epoch 0:  36%|███▌      | 720/2000 [00:33<00:59, 21.53it/s]

Epoch 0:  36%|███▌      | 723/2000 [00:33<00:59, 21.57it/s]

Epoch 0:  36%|███▋      | 726/2000 [00:33<00:58, 21.61it/s]

Epoch 0:  36%|███▋      | 729/2000 [00:33<00:58, 21.62it/s]

Epoch 0:  37%|███▋      | 732/2000 [00:33<00:58, 21.65it/s]

Epoch 0:  37%|███▋      | 735/2000 [00:33<00:58, 21.65it/s]

Epoch 0:  37%|███▋      | 738/2000 [00:34<00:58, 21.67it/s]

Epoch 0:  37%|███▋      | 741/2000 [00:34<00:58, 21.68it/s]

Epoch 0:  37%|███▋      | 744/2000 [00:34<00:57, 21.68it/s]

Epoch 0:  37%|███▋      | 747/2000 [00:34<00:57, 21.68it/s]

Epoch 0:  38%|███▊      | 750/2000 [00:34<00:57, 21.68it/s]

Epoch 0:  38%|███▊      | 753/2000 [00:34<00:57, 21.69it/s]

Epoch 0:  38%|███▊      | 756/2000 [00:34<00:57, 21.68it/s]

Epoch 0:  38%|███▊      | 759/2000 [00:35<00:57, 21.68it/s]

Epoch 0:  38%|███▊      | 762/2000 [00:35<00:57, 21.68it/s]

Epoch 0:  38%|███▊      | 765/2000 [00:35<00:56, 21.69it/s]

Epoch 0:  38%|███▊      | 768/2000 [00:35<00:56, 21.68it/s]

Epoch 0:  39%|███▊      | 771/2000 [00:35<00:56, 21.68it/s]

Epoch 0:  39%|███▊      | 774/2000 [00:35<00:56, 21.68it/s]

Epoch 0:  39%|███▉      | 777/2000 [00:35<00:56, 21.68it/s]

Epoch 0:  39%|███▉      | 780/2000 [00:36<00:56, 21.67it/s]

Epoch 0:  39%|███▉      | 783/2000 [00:36<00:56, 21.66it/s]

Epoch 0:  39%|███▉      | 786/2000 [00:36<00:56, 21.66it/s]

Epoch 0:  39%|███▉      | 789/2000 [00:36<00:55, 21.66it/s]

Epoch 0:  40%|███▉      | 792/2000 [00:36<00:55, 21.67it/s]

Epoch 0:  40%|███▉      | 795/2000 [00:36<00:55, 21.68it/s]

Epoch 0:  40%|███▉      | 798/2000 [00:36<00:55, 21.67it/s]

Epoch 0:  40%|████      | 801/2000 [00:37<00:55, 21.68it/s]

Epoch 0:  40%|████      | 804/2000 [00:37<00:55, 21.68it/s]

Epoch 0:  40%|████      | 807/2000 [00:37<00:55, 21.67it/s]

Epoch 0:  40%|████      | 810/2000 [00:37<00:54, 21.69it/s]

Epoch 0:  41%|████      | 813/2000 [00:37<00:54, 21.69it/s]

Epoch 0:  41%|████      | 816/2000 [00:37<00:54, 21.69it/s]

Epoch 0:  41%|████      | 819/2000 [00:37<00:54, 21.69it/s]

Epoch 0:  41%|████      | 822/2000 [00:37<00:54, 21.69it/s]

Epoch 0:  41%|████▏     | 825/2000 [00:38<00:54, 21.68it/s]

Epoch 0:  41%|████▏     | 828/2000 [00:38<00:54, 21.68it/s]

Epoch 0:  42%|████▏     | 831/2000 [00:38<00:53, 21.67it/s]

Epoch 0:  42%|████▏     | 834/2000 [00:38<00:53, 21.68it/s]

Epoch 0:  42%|████▏     | 837/2000 [00:38<00:53, 21.68it/s]

Epoch 0:  42%|████▏     | 840/2000 [00:38<00:53, 21.69it/s]

Epoch 0:  42%|████▏     | 843/2000 [00:38<00:53, 21.68it/s]

Epoch 0:  42%|████▏     | 846/2000 [00:39<00:53, 21.69it/s]

Epoch 0:  42%|████▏     | 849/2000 [00:39<00:53, 21.68it/s]

Epoch 0:  43%|████▎     | 852/2000 [00:39<00:52, 21.68it/s]

Epoch 0:  43%|████▎     | 855/2000 [00:39<00:52, 21.67it/s]

Epoch 0:  43%|████▎     | 858/2000 [00:39<00:52, 21.66it/s]

Epoch 0:  43%|████▎     | 861/2000 [00:39<00:52, 21.65it/s]

Epoch 0:  43%|████▎     | 864/2000 [00:39<00:52, 21.65it/s]

Epoch 0:  43%|████▎     | 867/2000 [00:40<00:52, 21.65it/s]

Epoch 0:  44%|████▎     | 870/2000 [00:40<00:52, 21.64it/s]

Epoch 0:  44%|████▎     | 873/2000 [00:40<00:52, 21.64it/s]

Epoch 0:  44%|████▍     | 876/2000 [00:40<00:51, 21.65it/s]

Epoch 0:  44%|████▍     | 879/2000 [00:40<00:51, 21.65it/s]

Epoch 0:  44%|████▍     | 882/2000 [00:40<00:51, 21.66it/s]

Epoch 0:  44%|████▍     | 885/2000 [00:40<00:51, 21.66it/s]

Epoch 0:  44%|████▍     | 888/2000 [00:41<00:51, 21.65it/s]

Epoch 0:  45%|████▍     | 891/2000 [00:41<00:51, 21.66it/s]

Epoch 0:  45%|████▍     | 894/2000 [00:41<00:51, 21.67it/s]

Epoch 0:  45%|████▍     | 897/2000 [00:41<00:50, 21.67it/s]

Epoch 0:  45%|████▌     | 900/2000 [00:41<00:50, 21.67it/s]

Epoch 0:  45%|████▌     | 903/2000 [00:41<00:50, 21.57it/s]

Epoch 0:  45%|████▌     | 906/2000 [00:41<00:50, 21.59it/s]

Epoch 0:  45%|████▌     | 909/2000 [00:41<00:50, 21.61it/s]

Epoch 0:  46%|████▌     | 912/2000 [00:42<00:50, 21.61it/s]

Epoch 0:  46%|████▌     | 915/2000 [00:42<00:50, 21.63it/s]

Epoch 0:  46%|████▌     | 918/2000 [00:42<00:50, 21.63it/s]

Epoch 0:  46%|████▌     | 921/2000 [00:42<00:50, 21.58it/s]

Epoch 0:  46%|████▌     | 924/2000 [00:42<00:49, 21.59it/s]

Epoch 0:  46%|████▋     | 927/2000 [00:42<00:49, 21.60it/s]

Epoch 0:  46%|████▋     | 930/2000 [00:42<00:49, 21.62it/s]

Epoch 0:  47%|████▋     | 933/2000 [00:43<00:49, 21.64it/s]

Epoch 0:  47%|████▋     | 936/2000 [00:43<00:49, 21.65it/s]

Epoch 0:  47%|████▋     | 939/2000 [00:43<00:48, 21.66it/s]

Epoch 0:  47%|████▋     | 942/2000 [00:43<00:48, 21.67it/s]

Epoch 0:  47%|████▋     | 945/2000 [00:43<00:48, 21.68it/s]

Epoch 0:  47%|████▋     | 948/2000 [00:43<00:48, 21.67it/s]

Epoch 0:  48%|████▊     | 951/2000 [00:43<00:48, 21.67it/s]

Epoch 0:  48%|████▊     | 954/2000 [00:44<00:48, 21.68it/s]

Epoch 0:  48%|████▊     | 957/2000 [00:44<00:48, 21.67it/s]

Epoch 0:  48%|████▊     | 960/2000 [00:44<00:47, 21.67it/s]

Epoch 0:  48%|████▊     | 963/2000 [00:44<00:47, 21.68it/s]

Epoch 0:  48%|████▊     | 966/2000 [00:44<00:47, 21.67it/s]

Epoch 0:  48%|████▊     | 969/2000 [00:44<00:47, 21.68it/s]

Epoch 0:  49%|████▊     | 972/2000 [00:44<00:47, 21.67it/s]

Epoch 0:  49%|████▉     | 975/2000 [00:45<00:47, 21.68it/s]

Epoch 0:  49%|████▉     | 978/2000 [00:45<00:47, 21.68it/s]

Epoch 0:  49%|████▉     | 981/2000 [00:45<00:46, 21.68it/s]

Epoch 0:  49%|████▉     | 984/2000 [00:45<00:46, 21.69it/s]

Epoch 0:  49%|████▉     | 987/2000 [00:45<00:46, 21.68it/s]

Epoch 0:  50%|████▉     | 990/2000 [00:45<00:46, 21.68it/s]

Epoch 0:  50%|████▉     | 993/2000 [00:45<00:46, 21.69it/s]

Epoch 0:  50%|████▉     | 996/2000 [00:46<00:46, 21.69it/s]

Epoch 0:  50%|████▉     | 999/2000 [00:46<00:46, 21.68it/s]

Epoch 0:  50%|█████     | 1002/2000 [00:46<00:46, 21.67it/s]

Epoch 0:  50%|█████     | 1005/2000 [00:46<00:45, 21.69it/s]

Epoch 0:  50%|█████     | 1008/2000 [00:46<00:45, 21.69it/s]

Epoch 0:  51%|█████     | 1011/2000 [00:46<00:45, 21.69it/s]

Epoch 0:  51%|█████     | 1014/2000 [00:46<00:45, 21.69it/s]

Epoch 0:  51%|█████     | 1017/2000 [00:46<00:45, 21.69it/s]

Epoch 0:  51%|█████     | 1020/2000 [00:47<00:45, 21.70it/s]

Epoch 0:  51%|█████     | 1023/2000 [00:47<00:45, 21.66it/s]

Epoch 0:  51%|█████▏    | 1026/2000 [00:47<00:45, 21.57it/s]

Epoch 0:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.59it/s]

Epoch 0:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.61it/s]

Epoch 0:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.62it/s]

Epoch 0:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.62it/s]

Epoch 0:  52%|█████▏    | 1041/2000 [00:48<00:44, 21.64it/s]

Epoch 0:  52%|█████▏    | 1044/2000 [00:48<00:44, 21.62it/s]

Epoch 0:  52%|█████▏    | 1047/2000 [00:48<00:44, 21.61it/s]

Epoch 0:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.62it/s]

Epoch 0:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.63it/s]

Epoch 0:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.65it/s]

Epoch 0:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.66it/s]

Epoch 0:  53%|█████▎    | 1062/2000 [00:49<00:43, 21.67it/s]

Epoch 0:  53%|█████▎    | 1065/2000 [00:49<00:43, 21.67it/s]

Epoch 0:  53%|█████▎    | 1068/2000 [00:49<00:43, 21.66it/s]

Epoch 0:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.67it/s]

Epoch 0:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.67it/s]

Epoch 0:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.65it/s]

Epoch 0:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.66it/s]

Epoch 0:  54%|█████▍    | 1083/2000 [00:50<00:42, 21.65it/s]

Epoch 0:  54%|█████▍    | 1086/2000 [00:50<00:42, 21.67it/s]

Epoch 0:  54%|█████▍    | 1089/2000 [00:50<00:42, 21.67it/s]

Epoch 0:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.68it/s]

Epoch 0:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.68it/s]

Epoch 0:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.68it/s]

Epoch 0:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.68it/s]

Epoch 0:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.69it/s]

Epoch 0:  55%|█████▌    | 1107/2000 [00:51<00:41, 21.69it/s]

Epoch 0:  56%|█████▌    | 1110/2000 [00:51<00:41, 21.69it/s]

Epoch 0:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.70it/s]

Epoch 0:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.64it/s]

Epoch 0:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.64it/s]

Epoch 0:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.65it/s]

Epoch 0:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.65it/s]

Epoch 0:  56%|█████▋    | 1128/2000 [00:52<00:40, 21.64it/s]

Epoch 0:  57%|█████▋    | 1131/2000 [00:52<00:40, 21.66it/s]

Epoch 0:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.66it/s]

Epoch 0:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.64it/s]

Epoch 0:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.64it/s]

Epoch 0:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.65it/s]

Epoch 0:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.66it/s]

Epoch 0:  57%|█████▋    | 1149/2000 [00:53<00:39, 21.65it/s]

Epoch 0:  58%|█████▊    | 1152/2000 [00:53<00:39, 21.66it/s]

Epoch 0:  58%|█████▊    | 1155/2000 [00:53<00:39, 21.66it/s]

Epoch 0:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.67it/s]

Epoch 0:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.67it/s]

Epoch 0:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.67it/s]

Epoch 0:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.68it/s]

Epoch 0:  58%|█████▊    | 1170/2000 [00:54<00:38, 21.69it/s]

Epoch 0:  59%|█████▊    | 1173/2000 [00:54<00:38, 21.69it/s]

Epoch 0:  59%|█████▉    | 1176/2000 [00:54<00:37, 21.70it/s]

Epoch 0:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.69it/s]

Epoch 0:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.69it/s]

Epoch 0:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.69it/s]

Epoch 0:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.69it/s]

Epoch 0:  60%|█████▉    | 1191/2000 [00:55<00:37, 21.68it/s]

Epoch 0:  60%|█████▉    | 1194/2000 [00:55<00:37, 21.68it/s]

Epoch 0:  60%|█████▉    | 1197/2000 [00:55<00:37, 21.67it/s]

Epoch 0:  60%|██████    | 1200/2000 [00:55<00:36, 21.66it/s]

Epoch 0:  60%|██████    | 1203/2000 [00:55<00:36, 21.65it/s]

Epoch 0:  60%|██████    | 1206/2000 [00:55<00:36, 21.64it/s]

Epoch 0:  60%|██████    | 1209/2000 [00:55<00:36, 21.64it/s]

Epoch 0:  61%|██████    | 1212/2000 [00:55<00:36, 21.65it/s]

Epoch 0:  61%|██████    | 1215/2000 [00:56<00:36, 21.67it/s]

Epoch 0:  61%|██████    | 1218/2000 [00:56<00:36, 21.67it/s]

Epoch 0:  61%|██████    | 1221/2000 [00:56<00:35, 21.67it/s]

Epoch 0:  61%|██████    | 1224/2000 [00:56<00:35, 21.64it/s]

Epoch 0:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.64it/s]

Epoch 0:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.66it/s]

Epoch 0:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.67it/s]

Epoch 0:  62%|██████▏   | 1236/2000 [00:57<00:35, 21.66it/s]

Epoch 0:  62%|██████▏   | 1239/2000 [00:57<00:35, 21.66it/s]

Epoch 0:  62%|██████▏   | 1242/2000 [00:57<00:35, 21.65it/s]

Epoch 0:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.66it/s]

Epoch 0:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.57it/s]

Epoch 0:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.60it/s]

Epoch 0:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.62it/s]

Epoch 0:  63%|██████▎   | 1257/2000 [00:58<00:34, 21.62it/s]

Epoch 0:  63%|██████▎   | 1260/2000 [00:58<00:34, 21.64it/s]

Epoch 0:  63%|██████▎   | 1263/2000 [00:58<00:34, 21.66it/s]

Epoch 0:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.67it/s]

Epoch 0:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.66it/s]

Epoch 0:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.68it/s]

Epoch 0:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.68it/s]

Epoch 0:  64%|██████▍   | 1278/2000 [00:59<00:33, 21.67it/s]

Epoch 0:  64%|██████▍   | 1281/2000 [00:59<00:33, 21.67it/s]

Epoch 0:  64%|██████▍   | 1284/2000 [00:59<00:33, 21.67it/s]

Epoch 0:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.66it/s]

Epoch 0:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.67it/s]

Epoch 0:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.65it/s]

Epoch 0:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.66it/s]

Epoch 0:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.67it/s]

Epoch 0:  65%|██████▌   | 1302/2000 [01:00<00:32, 21.68it/s]

Epoch 0:  65%|██████▌   | 1305/2000 [01:00<00:32, 21.69it/s]

Epoch 0:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.70it/s]

Epoch 0:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.69it/s]

Epoch 0:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.68it/s]

Epoch 0:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.68it/s]

Epoch 0:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.68it/s]

Epoch 0:  66%|██████▌   | 1323/2000 [01:01<00:31, 21.67it/s]

Epoch 0:  66%|██████▋   | 1326/2000 [01:01<00:31, 21.67it/s]

Epoch 0:  66%|██████▋   | 1329/2000 [01:01<00:30, 21.69it/s]

Epoch 0:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.69it/s]

Epoch 0:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.68it/s]

Epoch 0:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.68it/s]

Epoch 0:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.68it/s]

Epoch 0:  67%|██████▋   | 1344/2000 [01:02<00:30, 21.68it/s]

Epoch 0:  67%|██████▋   | 1347/2000 [01:02<00:30, 21.68it/s]

Epoch 0:  68%|██████▊   | 1350/2000 [01:02<00:29, 21.68it/s]

Epoch 0:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.70it/s]

Epoch 0:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.69it/s]

Epoch 0:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.70it/s]

Epoch 0:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.71it/s]

Epoch 0:  68%|██████▊   | 1365/2000 [01:03<00:29, 21.71it/s]

Epoch 0:  68%|██████▊   | 1368/2000 [01:03<00:29, 21.72it/s]

Epoch 0:  69%|██████▊   | 1371/2000 [01:03<00:28, 21.71it/s]

Epoch 0:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.72it/s]

Epoch 0:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.70it/s]

Epoch 0:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.68it/s]

Epoch 0:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.68it/s]

Epoch 0:  69%|██████▉   | 1386/2000 [01:04<00:28, 21.67it/s]

Epoch 0:  69%|██████▉   | 1389/2000 [01:04<00:28, 21.69it/s]

Epoch 0:  70%|██████▉   | 1392/2000 [01:04<00:28, 21.69it/s]

Epoch 0:  70%|██████▉   | 1395/2000 [01:04<00:27, 21.70it/s]

Epoch 0:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.68it/s]

Epoch 0:  70%|███████   | 1401/2000 [01:04<00:27, 21.69it/s]

Epoch 0:  70%|███████   | 1404/2000 [01:04<00:27, 21.67it/s]

Epoch 0:  70%|███████   | 1407/2000 [01:04<00:28, 20.97it/s]

Epoch 0:  70%|███████   | 1410/2000 [01:05<00:28, 20.94it/s]

Epoch 0:  71%|███████   | 1413/2000 [01:05<00:27, 21.10it/s]

Epoch 0:  71%|███████   | 1416/2000 [01:05<00:27, 21.20it/s]

Epoch 0:  71%|███████   | 1419/2000 [01:05<00:27, 21.35it/s]

Epoch 0:  71%|███████   | 1422/2000 [01:05<00:26, 21.45it/s]

Epoch 0:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.52it/s]

Epoch 0:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.56it/s]

Epoch 0:  72%|███████▏  | 1431/2000 [01:06<00:26, 21.60it/s]

Epoch 0:  72%|███████▏  | 1434/2000 [01:06<00:26, 21.63it/s]

Epoch 0:  72%|███████▏  | 1437/2000 [01:06<00:26, 21.65it/s]

Epoch 0:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.65it/s]

Epoch 0:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.59it/s]

Epoch 0:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.61it/s]

Epoch 0:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.63it/s]

Epoch 0:  73%|███████▎  | 1452/2000 [01:07<00:25, 21.65it/s]

Epoch 0:  73%|███████▎  | 1455/2000 [01:07<00:25, 21.66it/s]

Epoch 0:  73%|███████▎  | 1458/2000 [01:07<00:25, 21.65it/s]

Epoch 0:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.67it/s]

Epoch 0:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.67it/s]

Epoch 0:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.68it/s]

Epoch 0:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.60it/s]

Epoch 0:  74%|███████▎  | 1473/2000 [01:08<00:24, 21.61it/s]

Epoch 0:  74%|███████▍  | 1476/2000 [01:08<00:24, 21.64it/s]

Epoch 0:  74%|███████▍  | 1479/2000 [01:08<00:24, 21.64it/s]

Epoch 0:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.65it/s]

Epoch 0:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.66it/s]

Epoch 0:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.67it/s]

Epoch 0:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.67it/s]

Epoch 0:  75%|███████▍  | 1494/2000 [01:09<00:23, 21.66it/s]

Epoch 0:  75%|███████▍  | 1497/2000 [01:09<00:23, 21.66it/s]

Epoch 0:  75%|███████▌  | 1500/2000 [01:09<00:23, 21.67it/s]

Epoch 0:  75%|███████▌  | 1503/2000 [01:09<00:22, 21.67it/s]

Epoch 0:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.68it/s]

Epoch 0:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.66it/s]

Epoch 0:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.66it/s]

Epoch 0:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.68it/s]

Epoch 0:  76%|███████▌  | 1518/2000 [01:10<00:22, 21.68it/s]

Epoch 0:  76%|███████▌  | 1521/2000 [01:10<00:22, 21.68it/s]

Epoch 0:  76%|███████▌  | 1524/2000 [01:10<00:21, 21.68it/s]

Epoch 0:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.69it/s]

Epoch 0:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.69it/s]

Epoch 0:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.68it/s]

Epoch 0:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.67it/s]

Epoch 0:  77%|███████▋  | 1539/2000 [01:11<00:21, 21.67it/s]

Epoch 0:  77%|███████▋  | 1542/2000 [01:11<00:21, 21.67it/s]

Epoch 0:  77%|███████▋  | 1545/2000 [01:11<00:20, 21.68it/s]

Epoch 0:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.68it/s]

Epoch 0:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.68it/s]

Epoch 0:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.67it/s]

Epoch 0:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.66it/s]

Epoch 0:  78%|███████▊  | 1560/2000 [01:12<00:20, 21.66it/s]

Epoch 0:  78%|███████▊  | 1563/2000 [01:12<00:20, 21.65it/s]

Epoch 0:  78%|███████▊  | 1566/2000 [01:12<00:20, 21.66it/s]

Epoch 0:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.66it/s]

Epoch 0:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.66it/s]

Epoch 0:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.67it/s]

Epoch 0:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.67it/s]

Epoch 0:  79%|███████▉  | 1581/2000 [01:13<00:19, 21.68it/s]

Epoch 0:  79%|███████▉  | 1584/2000 [01:13<00:19, 21.69it/s]

Epoch 0:  79%|███████▉  | 1587/2000 [01:13<00:19, 21.68it/s]

Epoch 0:  80%|███████▉  | 1590/2000 [01:13<00:18, 21.69it/s]

Epoch 0:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.70it/s]

Epoch 0:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.69it/s]

Epoch 0:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.69it/s]

Epoch 0:  80%|████████  | 1602/2000 [01:13<00:18, 21.69it/s]

Epoch 0:  80%|████████  | 1605/2000 [01:14<00:18, 21.69it/s]

Epoch 0:  80%|████████  | 1608/2000 [01:14<00:18, 21.69it/s]

Epoch 0:  81%|████████  | 1611/2000 [01:14<00:17, 21.70it/s]

Epoch 0:  81%|████████  | 1614/2000 [01:14<00:17, 21.71it/s]

Epoch 0:  81%|████████  | 1617/2000 [01:14<00:17, 21.69it/s]

Epoch 0:  81%|████████  | 1620/2000 [01:14<00:17, 21.71it/s]

Epoch 0:  81%|████████  | 1623/2000 [01:14<00:17, 21.70it/s]

Epoch 0:  81%|████████▏ | 1626/2000 [01:15<00:17, 21.68it/s]

Epoch 0:  81%|████████▏ | 1629/2000 [01:15<00:17, 21.69it/s]

Epoch 0:  82%|████████▏ | 1632/2000 [01:15<00:16, 21.70it/s]

Epoch 0:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.70it/s]

Epoch 0:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.69it/s]

Epoch 0:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.68it/s]

Epoch 0:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.69it/s]

Epoch 0:  82%|████████▏ | 1647/2000 [01:16<00:16, 21.69it/s]

Epoch 0:  82%|████████▎ | 1650/2000 [01:16<00:16, 21.69it/s]

Epoch 0:  83%|████████▎ | 1653/2000 [01:16<00:15, 21.70it/s]

Epoch 0:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.69it/s]

Epoch 0:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.64it/s]

Epoch 0:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.64it/s]

Epoch 0:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.66it/s]

Epoch 0:  83%|████████▎ | 1668/2000 [01:17<00:15, 21.68it/s]

Epoch 0:  84%|████████▎ | 1671/2000 [01:17<00:15, 21.68it/s]

Epoch 0:  84%|████████▎ | 1674/2000 [01:17<00:15, 21.69it/s]

Epoch 0:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.67it/s]

Epoch 0:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.67it/s]

Epoch 0:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.66it/s]

Epoch 0:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.66it/s]

Epoch 0:  84%|████████▍ | 1689/2000 [01:18<00:14, 21.66it/s]

Epoch 0:  85%|████████▍ | 1692/2000 [01:18<00:14, 21.67it/s]

Epoch 0:  85%|████████▍ | 1695/2000 [01:18<00:14, 21.67it/s]

Epoch 0:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.68it/s]

Epoch 0:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.68it/s]

Epoch 0:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.68it/s]

Epoch 0:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.69it/s]

Epoch 0:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.68it/s]

Epoch 0:  86%|████████▌ | 1713/2000 [01:19<00:13, 21.69it/s]

Epoch 0:  86%|████████▌ | 1716/2000 [01:19<00:13, 21.70it/s]

Epoch 0:  86%|████████▌ | 1719/2000 [01:19<00:12, 21.70it/s]

Epoch 0:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.70it/s]

Epoch 0:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.67it/s]

Epoch 0:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.67it/s]

Epoch 0:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.66it/s]

Epoch 0:  87%|████████▋ | 1734/2000 [01:20<00:12, 21.65it/s]

Epoch 0:  87%|████████▋ | 1737/2000 [01:20<00:12, 21.65it/s]

Epoch 0:  87%|████████▋ | 1740/2000 [01:20<00:12, 21.66it/s]

Epoch 0:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.64it/s]

Epoch 0:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.66it/s]

Epoch 0:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.65it/s]

Epoch 0:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.68it/s]

Epoch 0:  88%|████████▊ | 1755/2000 [01:21<00:11, 21.68it/s]

Epoch 0:  88%|████████▊ | 1758/2000 [01:21<00:11, 21.69it/s]

Epoch 0:  88%|████████▊ | 1761/2000 [01:21<00:11, 21.70it/s]

Epoch 0:  88%|████████▊ | 1764/2000 [01:21<00:10, 21.71it/s]

Epoch 0:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.70it/s]

Epoch 0:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.70it/s]

Epoch 0:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.69it/s]

Epoch 0:  89%|████████▉ | 1776/2000 [01:22<00:10, 21.69it/s]

Epoch 0:  89%|████████▉ | 1779/2000 [01:22<00:10, 21.69it/s]

Epoch 0:  89%|████████▉ | 1782/2000 [01:22<00:10, 21.70it/s]

Epoch 0:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.70it/s]

Epoch 0:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.71it/s]

Epoch 0:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.70it/s]

Epoch 0:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.70it/s]

Epoch 0:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.68it/s]

Epoch 0:  90%|█████████ | 1800/2000 [01:23<00:09, 21.69it/s]

Epoch 0:  90%|█████████ | 1803/2000 [01:23<00:09, 21.68it/s]

Epoch 0:  90%|█████████ | 1806/2000 [01:23<00:08, 21.68it/s]

Epoch 0:  90%|█████████ | 1809/2000 [01:23<00:08, 21.71it/s]

Epoch 0:  91%|█████████ | 1812/2000 [01:23<00:08, 21.71it/s]

Epoch 0:  91%|█████████ | 1815/2000 [01:23<00:08, 21.70it/s]

Epoch 0:  91%|█████████ | 1818/2000 [01:23<00:08, 21.69it/s]

Epoch 0:  91%|█████████ | 1821/2000 [01:24<00:08, 21.69it/s]

Epoch 0:  91%|█████████ | 1824/2000 [01:24<00:08, 21.68it/s]

Epoch 0:  91%|█████████▏| 1827/2000 [01:24<00:07, 21.69it/s]

Epoch 0:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.70it/s]

Epoch 0:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.69it/s]

Epoch 0:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.69it/s]

Epoch 0:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.70it/s]

Epoch 0:  92%|█████████▏| 1842/2000 [01:25<00:07, 21.70it/s]

Epoch 0:  92%|█████████▏| 1845/2000 [01:25<00:07, 21.69it/s]

Epoch 0:  92%|█████████▏| 1848/2000 [01:25<00:07, 21.70it/s]

Epoch 0:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.61it/s]

Epoch 0:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.62it/s]

Epoch 0:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.63it/s]

Epoch 0:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.65it/s]

Epoch 0:  93%|█████████▎| 1863/2000 [01:26<00:06, 21.66it/s]

Epoch 0:  93%|█████████▎| 1866/2000 [01:26<00:06, 21.68it/s]

Epoch 0:  93%|█████████▎| 1869/2000 [01:26<00:06, 21.68it/s]

Epoch 0:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.67it/s]

Epoch 0:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.68it/s]

Epoch 0:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.67it/s]

Epoch 0:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.67it/s]

Epoch 0:  94%|█████████▍| 1884/2000 [01:27<00:05, 21.69it/s]

Epoch 0:  94%|█████████▍| 1887/2000 [01:27<00:05, 21.69it/s]

Epoch 0:  94%|█████████▍| 1890/2000 [01:27<00:05, 21.68it/s]

Epoch 0:  95%|█████████▍| 1893/2000 [01:27<00:04, 21.69it/s]

Epoch 0:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.68it/s]

Epoch 0:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.67it/s]

Epoch 0:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.65it/s]

Epoch 0:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.68it/s]

Epoch 0:  95%|█████████▌| 1908/2000 [01:28<00:04, 21.68it/s]

Epoch 0:  96%|█████████▌| 1911/2000 [01:28<00:04, 21.69it/s]

Epoch 0:  96%|█████████▌| 1914/2000 [01:28<00:03, 21.69it/s]

Epoch 0:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.70it/s]

Epoch 0:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.70it/s]

Epoch 0:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.68it/s]

Epoch 0:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.67it/s]

Epoch 0:  96%|█████████▋| 1929/2000 [01:29<00:03, 21.67it/s]

Epoch 0:  97%|█████████▋| 1932/2000 [01:29<00:03, 21.66it/s]

Epoch 0:  97%|█████████▋| 1935/2000 [01:29<00:02, 21.68it/s]

Epoch 0:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.68it/s]

Epoch 0:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.68it/s]

Epoch 0:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.67it/s]

Epoch 0:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.67it/s]

Epoch 0:  98%|█████████▊| 1950/2000 [01:30<00:02, 21.69it/s]

Epoch 0:  98%|█████████▊| 1953/2000 [01:30<00:02, 21.69it/s]

Epoch 0:  98%|█████████▊| 1956/2000 [01:30<00:02, 21.70it/s]

Epoch 0:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.69it/s]

Epoch 0:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.69it/s]

Epoch 0:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.69it/s]

Epoch 0:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.69it/s]

Epoch 0:  99%|█████████▊| 1971/2000 [01:31<00:01, 21.70it/s]

Epoch 0:  99%|█████████▊| 1974/2000 [01:31<00:01, 21.69it/s]

Epoch 0:  99%|█████████▉| 1977/2000 [01:31<00:01, 21.68it/s]

Epoch 0:  99%|█████████▉| 1980/2000 [01:31<00:00, 21.69it/s]

Epoch 0:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.69it/s]

Epoch 0:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.69it/s]

Epoch 0:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.70it/s]

Epoch 0: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.71it/s]

Epoch 0: 100%|█████████▉| 1995/2000 [01:32<00:00, 21.69it/s]

Epoch 0: 100%|█████████▉| 1998/2000 [01:32<00:00, 21.69it/s]

Epoch 0: loss=0.3945, val_proxy=0.5122

Epoch 1:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 1:   0%|          | 3/2000 [00:00<01:32, 21.51it/s]

Epoch 1:   0%|          | 6/2000 [00:00<01:31, 21.68it/s]

Epoch 1:   0%|          | 9/2000 [00:00<01:31, 21.70it/s]

Epoch 1:   1%|          | 12/2000 [00:00<01:31, 21.75it/s]

Epoch 1:   1%|          | 15/2000 [00:00<01:31, 21.77it/s]

Epoch 1:   1%|          | 18/2000 [00:00<01:30, 21.80it/s]

Epoch 1:   1%|          | 21/2000 [00:00<01:30, 21.80it/s]

Epoch 1:   1%|          | 24/2000 [00:01<01:30, 21.79it/s]

Epoch 1:   1%|▏         | 27/2000 [00:01<01:30, 21.81it/s]

Epoch 1:   2%|▏         | 30/2000 [00:01<01:30, 21.81it/s]

Epoch 1:   2%|▏         | 33/2000 [00:01<01:30, 21.80it/s]

Epoch 1:   2%|▏         | 36/2000 [00:01<01:30, 21.80it/s]

Epoch 1:   2%|▏         | 39/2000 [00:01<01:29, 21.80it/s]

Epoch 1:   2%|▏         | 42/2000 [00:01<01:29, 21.80it/s]

Epoch 1:   2%|▏         | 45/2000 [00:02<01:29, 21.81it/s]

Epoch 1:   2%|▏         | 48/2000 [00:02<01:29, 21.81it/s]

Epoch 1:   3%|▎         | 51/2000 [00:02<01:29, 21.81it/s]

Epoch 1:   3%|▎         | 54/2000 [00:02<01:29, 21.81it/s]

Epoch 1:   3%|▎         | 57/2000 [00:02<01:29, 21.80it/s]

Epoch 1:   3%|▎         | 60/2000 [00:02<01:28, 21.82it/s]

Epoch 1:   3%|▎         | 63/2000 [00:02<01:28, 21.84it/s]

Epoch 1:   3%|▎         | 66/2000 [00:03<01:28, 21.82it/s]

Epoch 1:   3%|▎         | 69/2000 [00:03<01:28, 21.84it/s]

Epoch 1:   4%|▎         | 72/2000 [00:03<01:28, 21.83it/s]

Epoch 1:   4%|▍         | 75/2000 [00:03<01:28, 21.84it/s]

Epoch 1:   4%|▍         | 78/2000 [00:03<01:27, 21.84it/s]

Epoch 1:   4%|▍         | 81/2000 [00:03<01:27, 21.83it/s]

Epoch 1:   4%|▍         | 84/2000 [00:03<01:27, 21.84it/s]

Epoch 1:   4%|▍         | 87/2000 [00:03<01:27, 21.84it/s]

Epoch 1:   4%|▍         | 90/2000 [00:04<01:27, 21.83it/s]

Epoch 1:   5%|▍         | 93/2000 [00:04<01:27, 21.83it/s]

Epoch 1:   5%|▍         | 96/2000 [00:04<01:27, 21.82it/s]

Epoch 1:   5%|▍         | 99/2000 [00:04<01:27, 21.82it/s]

Epoch 1:   5%|▌         | 102/2000 [00:04<01:26, 21.82it/s]

Epoch 1:   5%|▌         | 105/2000 [00:04<01:26, 21.83it/s]

Epoch 1:   5%|▌         | 108/2000 [00:04<01:26, 21.84it/s]

Epoch 1:   6%|▌         | 111/2000 [00:05<01:26, 21.84it/s]

Epoch 1:   6%|▌         | 114/2000 [00:05<01:26, 21.83it/s]

Epoch 1:   6%|▌         | 117/2000 [00:05<01:26, 21.83it/s]

Epoch 1:   6%|▌         | 120/2000 [00:05<01:26, 21.83it/s]

Epoch 1:   6%|▌         | 123/2000 [00:05<01:25, 21.84it/s]

Epoch 1:   6%|▋         | 126/2000 [00:05<01:25, 21.84it/s]

Epoch 1:   6%|▋         | 129/2000 [00:05<01:25, 21.83it/s]

Epoch 1:   7%|▋         | 132/2000 [00:06<01:25, 21.84it/s]

Epoch 1:   7%|▋         | 135/2000 [00:06<01:25, 21.84it/s]

Epoch 1:   7%|▋         | 138/2000 [00:06<01:25, 21.83it/s]

Epoch 1:   7%|▋         | 141/2000 [00:06<01:25, 21.82it/s]

Epoch 1:   7%|▋         | 144/2000 [00:06<01:25, 21.83it/s]

Epoch 1:   7%|▋         | 147/2000 [00:06<01:24, 21.83it/s]

Epoch 1:   8%|▊         | 150/2000 [00:06<01:24, 21.83it/s]

Epoch 1:   8%|▊         | 153/2000 [00:07<01:24, 21.85it/s]

Epoch 1:   8%|▊         | 156/2000 [00:07<01:24, 21.84it/s]

Epoch 1:   8%|▊         | 159/2000 [00:07<01:24, 21.84it/s]

Epoch 1:   8%|▊         | 162/2000 [00:07<01:24, 21.80it/s]

Epoch 1:   8%|▊         | 165/2000 [00:07<01:24, 21.81it/s]

Epoch 1:   8%|▊         | 168/2000 [00:07<01:23, 21.81it/s]

Epoch 1:   9%|▊         | 171/2000 [00:07<01:23, 21.82it/s]

Epoch 1:   9%|▊         | 174/2000 [00:07<01:23, 21.74it/s]

Epoch 1:   9%|▉         | 177/2000 [00:08<01:23, 21.76it/s]

Epoch 1:   9%|▉         | 180/2000 [00:08<01:23, 21.80it/s]

Epoch 1:   9%|▉         | 183/2000 [00:08<01:23, 21.80it/s]

Epoch 1:   9%|▉         | 186/2000 [00:08<01:23, 21.81it/s]

Epoch 1:   9%|▉         | 189/2000 [00:08<01:22, 21.83it/s]

Epoch 1:  10%|▉         | 192/2000 [00:08<01:22, 21.82it/s]

Epoch 1:  10%|▉         | 195/2000 [00:08<01:22, 21.82it/s]

Epoch 1:  10%|▉         | 198/2000 [00:09<01:22, 21.82it/s]

Epoch 1:  10%|█         | 201/2000 [00:09<01:22, 21.82it/s]

Epoch 1:  10%|█         | 204/2000 [00:09<01:22, 21.82it/s]

Epoch 1:  10%|█         | 207/2000 [00:09<01:22, 21.81it/s]

Epoch 1:  10%|█         | 210/2000 [00:09<01:22, 21.82it/s]

Epoch 1:  11%|█         | 213/2000 [00:09<01:21, 21.81it/s]

Epoch 1:  11%|█         | 216/2000 [00:09<01:21, 21.81it/s]

Epoch 1:  11%|█         | 219/2000 [00:10<01:21, 21.82it/s]

Epoch 1:  11%|█         | 222/2000 [00:10<01:21, 21.82it/s]

Epoch 1:  11%|█▏        | 225/2000 [00:10<01:21, 21.82it/s]

Epoch 1:  11%|█▏        | 228/2000 [00:10<01:21, 21.82it/s]

Epoch 1:  12%|█▏        | 231/2000 [00:10<01:21, 21.81it/s]

Epoch 1:  12%|█▏        | 234/2000 [00:10<01:20, 21.82it/s]

Epoch 1:  12%|█▏        | 237/2000 [00:10<01:20, 21.82it/s]

Epoch 1:  12%|█▏        | 240/2000 [00:11<01:20, 21.83it/s]

Epoch 1:  12%|█▏        | 243/2000 [00:11<01:20, 21.84it/s]

Epoch 1:  12%|█▏        | 246/2000 [00:11<01:20, 21.84it/s]

Epoch 1:  12%|█▏        | 249/2000 [00:11<01:20, 21.83it/s]

Epoch 1:  13%|█▎        | 252/2000 [00:11<01:20, 21.83it/s]

Epoch 1:  13%|█▎        | 255/2000 [00:11<01:19, 21.82it/s]

Epoch 1:  13%|█▎        | 258/2000 [00:11<01:19, 21.83it/s]

Epoch 1:  13%|█▎        | 261/2000 [00:11<01:19, 21.84it/s]

Epoch 1:  13%|█▎        | 264/2000 [00:12<01:19, 21.83it/s]

Epoch 1:  13%|█▎        | 267/2000 [00:12<01:19, 21.84it/s]

Epoch 1:  14%|█▎        | 270/2000 [00:12<01:19, 21.84it/s]

Epoch 1:  14%|█▎        | 273/2000 [00:12<01:19, 21.84it/s]

Epoch 1:  14%|█▍        | 276/2000 [00:12<01:18, 21.84it/s]

Epoch 1:  14%|█▍        | 279/2000 [00:12<01:18, 21.83it/s]

Epoch 1:  14%|█▍        | 282/2000 [00:12<01:18, 21.83it/s]

Epoch 1:  14%|█▍        | 285/2000 [00:13<01:18, 21.84it/s]

Epoch 1:  14%|█▍        | 288/2000 [00:13<01:18, 21.84it/s]

Epoch 1:  15%|█▍        | 291/2000 [00:13<01:18, 21.83it/s]

Epoch 1:  15%|█▍        | 294/2000 [00:13<01:18, 21.83it/s]

Epoch 1:  15%|█▍        | 297/2000 [00:13<01:18, 21.82it/s]

Epoch 1:  15%|█▌        | 300/2000 [00:13<01:17, 21.84it/s]

Epoch 1:  15%|█▌        | 303/2000 [00:13<01:17, 21.81it/s]

Epoch 1:  15%|█▌        | 306/2000 [00:14<01:17, 21.82it/s]

Epoch 1:  15%|█▌        | 309/2000 [00:14<01:17, 21.80it/s]

Epoch 1:  16%|█▌        | 312/2000 [00:14<01:17, 21.82it/s]

Epoch 1:  16%|█▌        | 315/2000 [00:14<01:17, 21.81it/s]

Epoch 1:  16%|█▌        | 318/2000 [00:14<01:17, 21.82it/s]

Epoch 1:  16%|█▌        | 321/2000 [00:14<01:16, 21.83it/s]

Epoch 1:  16%|█▌        | 324/2000 [00:14<01:16, 21.84it/s]

Epoch 1:  16%|█▋        | 327/2000 [00:14<01:16, 21.84it/s]

Epoch 1:  16%|█▋        | 330/2000 [00:15<01:16, 21.84it/s]

Epoch 1:  17%|█▋        | 333/2000 [00:15<01:16, 21.84it/s]

Epoch 1:  17%|█▋        | 336/2000 [00:15<01:16, 21.84it/s]

Epoch 1:  17%|█▋        | 339/2000 [00:15<01:16, 21.83it/s]

Epoch 1:  17%|█▋        | 342/2000 [00:15<01:15, 21.85it/s]

Epoch 1:  17%|█▋        | 345/2000 [00:15<01:15, 21.85it/s]

Epoch 1:  17%|█▋        | 348/2000 [00:15<01:16, 21.61it/s]

Epoch 1:  18%|█▊        | 351/2000 [00:16<01:16, 21.54it/s]

Epoch 1:  18%|█▊        | 354/2000 [00:16<01:16, 21.61it/s]

Epoch 1:  18%|█▊        | 357/2000 [00:16<01:15, 21.68it/s]

Epoch 1:  18%|█▊        | 360/2000 [00:16<01:15, 21.71it/s]

Epoch 1:  18%|█▊        | 363/2000 [00:16<01:15, 21.74it/s]

Epoch 1:  18%|█▊        | 366/2000 [00:16<01:15, 21.78it/s]

Epoch 1:  18%|█▊        | 369/2000 [00:16<01:15, 21.73it/s]

Epoch 1:  19%|█▊        | 372/2000 [00:17<01:15, 21.65it/s]

Epoch 1:  19%|█▉        | 375/2000 [00:17<01:14, 21.68it/s]

Epoch 1:  19%|█▉        | 378/2000 [00:17<01:14, 21.71it/s]

Epoch 1:  19%|█▉        | 381/2000 [00:17<01:14, 21.73it/s]

Epoch 1:  19%|█▉        | 384/2000 [00:17<01:14, 21.76it/s]

Epoch 1:  19%|█▉        | 387/2000 [00:17<01:14, 21.78it/s]

Epoch 1:  20%|█▉        | 390/2000 [00:17<01:13, 21.79it/s]

Epoch 1:  20%|█▉        | 393/2000 [00:18<01:13, 21.81it/s]

Epoch 1:  20%|█▉        | 396/2000 [00:18<01:13, 21.82it/s]

Epoch 1:  20%|█▉        | 399/2000 [00:18<01:13, 21.82it/s]

Epoch 1:  20%|██        | 402/2000 [00:18<01:13, 21.82it/s]

Epoch 1:  20%|██        | 405/2000 [00:18<01:13, 21.83it/s]

Epoch 1:  20%|██        | 408/2000 [00:18<01:12, 21.82it/s]

Epoch 1:  21%|██        | 411/2000 [00:18<01:12, 21.82it/s]

Epoch 1:  21%|██        | 414/2000 [00:18<01:12, 21.82it/s]

Epoch 1:  21%|██        | 417/2000 [00:19<01:12, 21.83it/s]

Epoch 1:  21%|██        | 420/2000 [00:19<01:12, 21.84it/s]

Epoch 1:  21%|██        | 423/2000 [00:19<01:12, 21.84it/s]

Epoch 1:  21%|██▏       | 426/2000 [00:19<01:12, 21.84it/s]

Epoch 1:  21%|██▏       | 429/2000 [00:19<01:11, 21.83it/s]

Epoch 1:  22%|██▏       | 432/2000 [00:19<01:11, 21.83it/s]

Epoch 1:  22%|██▏       | 435/2000 [00:19<01:11, 21.81it/s]

Epoch 1:  22%|██▏       | 438/2000 [00:20<01:11, 21.84it/s]

Epoch 1:  22%|██▏       | 441/2000 [00:20<01:11, 21.84it/s]

Epoch 1:  22%|██▏       | 444/2000 [00:20<01:11, 21.82it/s]

Epoch 1:  22%|██▏       | 447/2000 [00:20<01:11, 21.82it/s]

Epoch 1:  22%|██▎       | 450/2000 [00:20<01:11, 21.82it/s]

Epoch 1:  23%|██▎       | 453/2000 [00:20<01:10, 21.82it/s]

Epoch 1:  23%|██▎       | 456/2000 [00:20<01:10, 21.83it/s]

Epoch 1:  23%|██▎       | 459/2000 [00:21<01:10, 21.83it/s]

Epoch 1:  23%|██▎       | 462/2000 [00:21<01:10, 21.84it/s]

Epoch 1:  23%|██▎       | 465/2000 [00:21<01:10, 21.78it/s]

Epoch 1:  23%|██▎       | 468/2000 [00:21<01:10, 21.80it/s]

Epoch 1:  24%|██▎       | 471/2000 [00:21<01:10, 21.80it/s]

Epoch 1:  24%|██▎       | 474/2000 [00:21<01:09, 21.81it/s]

Epoch 1:  24%|██▍       | 477/2000 [00:21<01:09, 21.82it/s]

Epoch 1:  24%|██▍       | 480/2000 [00:22<01:09, 21.83it/s]

Epoch 1:  24%|██▍       | 483/2000 [00:22<01:09, 21.83it/s]

Epoch 1:  24%|██▍       | 486/2000 [00:22<01:09, 21.83it/s]

Epoch 1:  24%|██▍       | 489/2000 [00:22<01:09, 21.83it/s]

Epoch 1:  25%|██▍       | 492/2000 [00:22<01:09, 21.82it/s]

Epoch 1:  25%|██▍       | 495/2000 [00:22<01:09, 21.81it/s]

Epoch 1:  25%|██▍       | 498/2000 [00:22<01:08, 21.81it/s]

Epoch 1:  25%|██▌       | 501/2000 [00:22<01:08, 21.81it/s]

Epoch 1:  25%|██▌       | 504/2000 [00:23<01:08, 21.81it/s]

Epoch 1:  25%|██▌       | 507/2000 [00:23<01:08, 21.83it/s]

Epoch 1:  26%|██▌       | 510/2000 [00:23<01:08, 21.84it/s]

Epoch 1:  26%|██▌       | 513/2000 [00:23<01:08, 21.85it/s]

Epoch 1:  26%|██▌       | 516/2000 [00:23<01:07, 21.85it/s]

Epoch 1:  26%|██▌       | 519/2000 [00:23<01:07, 21.85it/s]

Epoch 1:  26%|██▌       | 522/2000 [00:23<01:07, 21.85it/s]

Epoch 1:  26%|██▋       | 525/2000 [00:24<01:07, 21.84it/s]

Epoch 1:  26%|██▋       | 528/2000 [00:24<01:07, 21.85it/s]

Epoch 1:  27%|██▋       | 531/2000 [00:24<01:07, 21.85it/s]

Epoch 1:  27%|██▋       | 534/2000 [00:24<01:07, 21.84it/s]

Epoch 1:  27%|██▋       | 537/2000 [00:24<01:06, 21.84it/s]

Epoch 1:  27%|██▋       | 540/2000 [00:24<01:06, 21.84it/s]

Epoch 1:  27%|██▋       | 543/2000 [00:24<01:06, 21.85it/s]

Epoch 1:  27%|██▋       | 546/2000 [00:25<01:06, 21.83it/s]

Epoch 1:  27%|██▋       | 549/2000 [00:25<01:06, 21.83it/s]

Epoch 1:  28%|██▊       | 552/2000 [00:25<01:06, 21.84it/s]

Epoch 1:  28%|██▊       | 555/2000 [00:25<01:06, 21.83it/s]

Epoch 1:  28%|██▊       | 558/2000 [00:25<01:06, 21.84it/s]

Epoch 1:  28%|██▊       | 561/2000 [00:25<01:05, 21.83it/s]

Epoch 1:  28%|██▊       | 564/2000 [00:25<01:05, 21.83it/s]

Epoch 1:  28%|██▊       | 567/2000 [00:25<01:05, 21.83it/s]

Epoch 1:  28%|██▊       | 570/2000 [00:26<01:05, 21.83it/s]

Epoch 1:  29%|██▊       | 573/2000 [00:26<01:05, 21.83it/s]

Epoch 1:  29%|██▉       | 576/2000 [00:26<01:05, 21.82it/s]

Epoch 1:  29%|██▉       | 579/2000 [00:26<01:05, 21.82it/s]

Epoch 1:  29%|██▉       | 582/2000 [00:26<01:04, 21.82it/s]

Epoch 1:  29%|██▉       | 585/2000 [00:26<01:04, 21.82it/s]

Epoch 1:  29%|██▉       | 588/2000 [00:26<01:04, 21.83it/s]

Epoch 1:  30%|██▉       | 591/2000 [00:27<01:04, 21.82it/s]

Epoch 1:  30%|██▉       | 594/2000 [00:27<01:04, 21.83it/s]

Epoch 1:  30%|██▉       | 597/2000 [00:27<01:04, 21.84it/s]

Epoch 1:  30%|███       | 600/2000 [00:27<01:04, 21.84it/s]

Epoch 1:  30%|███       | 603/2000 [00:27<01:03, 21.86it/s]

Epoch 1:  30%|███       | 606/2000 [00:27<01:03, 21.86it/s]

Epoch 1:  30%|███       | 609/2000 [00:27<01:04, 21.73it/s]

Epoch 1:  31%|███       | 612/2000 [00:28<01:05, 21.15it/s]

Epoch 1:  31%|███       | 615/2000 [00:28<01:05, 21.08it/s]

Epoch 1:  31%|███       | 618/2000 [00:28<01:05, 21.26it/s]

Epoch 1:  31%|███       | 621/2000 [00:28<01:04, 21.37it/s]

Epoch 1:  31%|███       | 624/2000 [00:28<01:03, 21.52it/s]

Epoch 1:  31%|███▏      | 627/2000 [00:28<01:03, 21.62it/s]

Epoch 1:  32%|███▏      | 630/2000 [00:28<01:03, 21.69it/s]

Epoch 1:  32%|███▏      | 633/2000 [00:29<01:02, 21.74it/s]

Epoch 1:  32%|███▏      | 636/2000 [00:29<01:02, 21.76it/s]

Epoch 1:  32%|███▏      | 639/2000 [00:29<01:02, 21.79it/s]

Epoch 1:  32%|███▏      | 642/2000 [00:29<01:02, 21.81it/s]

Epoch 1:  32%|███▏      | 645/2000 [00:29<01:02, 21.81it/s]

Epoch 1:  32%|███▏      | 648/2000 [00:29<01:01, 21.83it/s]

Epoch 1:  33%|███▎      | 651/2000 [00:29<01:01, 21.84it/s]

Epoch 1:  33%|███▎      | 654/2000 [00:30<01:01, 21.84it/s]

Epoch 1:  33%|███▎      | 657/2000 [00:30<01:01, 21.83it/s]

Epoch 1:  33%|███▎      | 660/2000 [00:30<01:01, 21.84it/s]

Epoch 1:  33%|███▎      | 663/2000 [00:30<01:01, 21.83it/s]

Epoch 1:  33%|███▎      | 666/2000 [00:30<01:01, 21.78it/s]

Epoch 1:  33%|███▎      | 669/2000 [00:30<01:01, 21.80it/s]

Epoch 1:  34%|███▎      | 672/2000 [00:30<01:00, 21.81it/s]

Epoch 1:  34%|███▍      | 675/2000 [00:30<01:00, 21.82it/s]

Epoch 1:  34%|███▍      | 678/2000 [00:31<01:00, 21.84it/s]

Epoch 1:  34%|███▍      | 681/2000 [00:31<01:00, 21.82it/s]

Epoch 1:  34%|███▍      | 684/2000 [00:31<01:00, 21.83it/s]

Epoch 1:  34%|███▍      | 687/2000 [00:31<01:00, 21.58it/s]

Epoch 1:  34%|███▍      | 690/2000 [00:31<01:00, 21.60it/s]

Epoch 1:  35%|███▍      | 693/2000 [00:31<01:00, 21.63it/s]

Epoch 1:  35%|███▍      | 696/2000 [00:31<01:00, 21.66it/s]

Epoch 1:  35%|███▍      | 699/2000 [00:32<01:00, 21.58it/s]

Epoch 1:  35%|███▌      | 702/2000 [00:32<01:00, 21.61it/s]

Epoch 1:  35%|███▌      | 705/2000 [00:32<00:59, 21.63it/s]

Epoch 1:  35%|███▌      | 708/2000 [00:32<00:59, 21.65it/s]

Epoch 1:  36%|███▌      | 711/2000 [00:32<00:59, 21.65it/s]

Epoch 1:  36%|███▌      | 714/2000 [00:32<00:59, 21.66it/s]

Epoch 1:  36%|███▌      | 717/2000 [00:32<00:59, 21.66it/s]

Epoch 1:  36%|███▌      | 720/2000 [00:33<00:59, 21.67it/s]

Epoch 1:  36%|███▌      | 723/2000 [00:33<00:58, 21.68it/s]

Epoch 1:  36%|███▋      | 726/2000 [00:33<00:58, 21.69it/s]

Epoch 1:  36%|███▋      | 729/2000 [00:33<00:58, 21.70it/s]

Epoch 1:  37%|███▋      | 732/2000 [00:33<00:58, 21.70it/s]

Epoch 1:  37%|███▋      | 735/2000 [00:33<00:58, 21.72it/s]

Epoch 1:  37%|███▋      | 738/2000 [00:33<00:58, 21.70it/s]

Epoch 1:  37%|███▋      | 741/2000 [00:34<00:57, 21.71it/s]

Epoch 1:  37%|███▋      | 744/2000 [00:34<00:57, 21.71it/s]

Epoch 1:  37%|███▋      | 747/2000 [00:34<00:57, 21.71it/s]

Epoch 1:  38%|███▊      | 750/2000 [00:34<00:57, 21.70it/s]

Epoch 1:  38%|███▊      | 753/2000 [00:34<00:57, 21.70it/s]

Epoch 1:  38%|███▊      | 756/2000 [00:34<00:57, 21.70it/s]

Epoch 1:  38%|███▊      | 759/2000 [00:34<00:57, 21.70it/s]

Epoch 1:  38%|███▊      | 762/2000 [00:34<00:57, 21.71it/s]

Epoch 1:  38%|███▊      | 765/2000 [00:35<00:56, 21.71it/s]

Epoch 1:  38%|███▊      | 768/2000 [00:35<00:56, 21.71it/s]

Epoch 1:  39%|███▊      | 771/2000 [00:35<00:56, 21.72it/s]

Epoch 1:  39%|███▊      | 774/2000 [00:35<00:56, 21.70it/s]

Epoch 1:  39%|███▉      | 777/2000 [00:35<00:56, 21.69it/s]

Epoch 1:  39%|███▉      | 780/2000 [00:35<00:56, 21.69it/s]

Epoch 1:  39%|███▉      | 783/2000 [00:35<00:56, 21.69it/s]

Epoch 1:  39%|███▉      | 786/2000 [00:36<00:55, 21.68it/s]

Epoch 1:  39%|███▉      | 789/2000 [00:36<00:55, 21.68it/s]

Epoch 1:  40%|███▉      | 792/2000 [00:36<00:55, 21.69it/s]

Epoch 1:  40%|███▉      | 795/2000 [00:36<00:55, 21.69it/s]

Epoch 1:  40%|███▉      | 798/2000 [00:36<00:55, 21.70it/s]

Epoch 1:  40%|████      | 801/2000 [00:36<00:55, 21.71it/s]

Epoch 1:  40%|████      | 804/2000 [00:36<00:55, 21.70it/s]

Epoch 1:  40%|████      | 807/2000 [00:37<00:54, 21.70it/s]

Epoch 1:  40%|████      | 810/2000 [00:37<00:54, 21.71it/s]

Epoch 1:  41%|████      | 813/2000 [00:37<00:54, 21.71it/s]

Epoch 1:  41%|████      | 816/2000 [00:37<00:54, 21.71it/s]

Epoch 1:  41%|████      | 819/2000 [00:37<00:54, 21.69it/s]

Epoch 1:  41%|████      | 822/2000 [00:37<00:54, 21.70it/s]

Epoch 1:  41%|████▏     | 825/2000 [00:37<00:54, 21.69it/s]

Epoch 1:  41%|████▏     | 828/2000 [00:38<00:54, 21.70it/s]

Epoch 1:  42%|████▏     | 831/2000 [00:38<00:53, 21.70it/s]

Epoch 1:  42%|████▏     | 834/2000 [00:38<00:53, 21.71it/s]

Epoch 1:  42%|████▏     | 837/2000 [00:38<00:53, 21.71it/s]

Epoch 1:  42%|████▏     | 840/2000 [00:38<00:53, 21.71it/s]

Epoch 1:  42%|████▏     | 843/2000 [00:38<00:53, 21.71it/s]

Epoch 1:  42%|████▏     | 846/2000 [00:38<00:53, 21.70it/s]

Epoch 1:  42%|████▏     | 849/2000 [00:38<00:53, 21.70it/s]

Epoch 1:  43%|████▎     | 852/2000 [00:39<00:52, 21.70it/s]

Epoch 1:  43%|████▎     | 855/2000 [00:39<00:52, 21.70it/s]

Epoch 1:  43%|████▎     | 858/2000 [00:39<00:52, 21.71it/s]

Epoch 1:  43%|████▎     | 861/2000 [00:39<00:52, 21.70it/s]

Epoch 1:  43%|████▎     | 864/2000 [00:39<00:52, 21.70it/s]

Epoch 1:  43%|████▎     | 867/2000 [00:39<00:52, 21.69it/s]

Epoch 1:  44%|████▎     | 870/2000 [00:39<00:52, 21.69it/s]

Epoch 1:  44%|████▎     | 873/2000 [00:40<00:51, 21.69it/s]

Epoch 1:  44%|████▍     | 876/2000 [00:40<00:51, 21.71it/s]

Epoch 1:  44%|████▍     | 879/2000 [00:40<00:51, 21.71it/s]

Epoch 1:  44%|████▍     | 882/2000 [00:40<00:51, 21.70it/s]

Epoch 1:  44%|████▍     | 885/2000 [00:40<00:51, 21.72it/s]

Epoch 1:  44%|████▍     | 888/2000 [00:40<00:51, 21.70it/s]

Epoch 1:  45%|████▍     | 891/2000 [00:40<00:51, 21.70it/s]

Epoch 1:  45%|████▍     | 894/2000 [00:41<00:50, 21.70it/s]

Epoch 1:  45%|████▍     | 897/2000 [00:41<00:50, 21.70it/s]

Epoch 1:  45%|████▌     | 900/2000 [00:41<00:50, 21.70it/s]

Epoch 1:  45%|████▌     | 903/2000 [00:41<00:50, 21.70it/s]

Epoch 1:  45%|████▌     | 906/2000 [00:41<00:50, 21.70it/s]

Epoch 1:  45%|████▌     | 909/2000 [00:41<00:50, 21.71it/s]

Epoch 1:  46%|████▌     | 912/2000 [00:41<00:50, 21.72it/s]

Epoch 1:  46%|████▌     | 915/2000 [00:42<00:50, 21.67it/s]

Epoch 1:  46%|████▌     | 918/2000 [00:42<00:49, 21.68it/s]

Epoch 1:  46%|████▌     | 921/2000 [00:42<00:49, 21.69it/s]

Epoch 1:  46%|████▌     | 924/2000 [00:42<00:49, 21.68it/s]

Epoch 1:  46%|████▋     | 927/2000 [00:42<00:49, 21.70it/s]

Epoch 1:  46%|████▋     | 930/2000 [00:42<00:49, 21.69it/s]

Epoch 1:  47%|████▋     | 933/2000 [00:42<00:49, 21.71it/s]

Epoch 1:  47%|████▋     | 936/2000 [00:42<00:49, 21.70it/s]

Epoch 1:  47%|████▋     | 939/2000 [00:43<00:48, 21.71it/s]

Epoch 1:  47%|████▋     | 942/2000 [00:43<00:48, 21.71it/s]

Epoch 1:  47%|████▋     | 945/2000 [00:43<00:48, 21.70it/s]

Epoch 1:  47%|████▋     | 948/2000 [00:43<00:48, 21.70it/s]

Epoch 1:  48%|████▊     | 951/2000 [00:43<00:48, 21.71it/s]

Epoch 1:  48%|████▊     | 954/2000 [00:43<00:48, 21.71it/s]

Epoch 1:  48%|████▊     | 957/2000 [00:43<00:48, 21.70it/s]

Epoch 1:  48%|████▊     | 960/2000 [00:44<00:47, 21.72it/s]

Epoch 1:  48%|████▊     | 963/2000 [00:44<00:47, 21.71it/s]

Epoch 1:  48%|████▊     | 966/2000 [00:44<00:47, 21.70it/s]

Epoch 1:  48%|████▊     | 969/2000 [00:44<00:47, 21.70it/s]

Epoch 1:  49%|████▊     | 972/2000 [00:44<00:47, 21.70it/s]

Epoch 1:  49%|████▉     | 975/2000 [00:44<00:47, 21.70it/s]

Epoch 1:  49%|████▉     | 978/2000 [00:44<00:47, 21.69it/s]

Epoch 1:  49%|████▉     | 981/2000 [00:45<00:46, 21.69it/s]

Epoch 1:  49%|████▉     | 984/2000 [00:45<00:46, 21.68it/s]

Epoch 1:  49%|████▉     | 987/2000 [00:45<00:46, 21.69it/s]

Epoch 1:  50%|████▉     | 990/2000 [00:45<00:46, 21.69it/s]

Epoch 1:  50%|████▉     | 993/2000 [00:45<00:46, 21.70it/s]

Epoch 1:  50%|████▉     | 996/2000 [00:45<00:46, 21.71it/s]

Epoch 1:  50%|████▉     | 999/2000 [00:45<00:46, 21.71it/s]

Epoch 1:  50%|█████     | 1002/2000 [00:46<00:45, 21.70it/s]

Epoch 1:  50%|█████     | 1005/2000 [00:46<00:45, 21.70it/s]

Epoch 1:  50%|█████     | 1008/2000 [00:46<00:45, 21.71it/s]

Epoch 1:  51%|█████     | 1011/2000 [00:46<00:45, 21.71it/s]

Epoch 1:  51%|█████     | 1014/2000 [00:46<00:45, 21.71it/s]

Epoch 1:  51%|█████     | 1017/2000 [00:46<00:45, 21.71it/s]

Epoch 1:  51%|█████     | 1020/2000 [00:46<00:45, 21.72it/s]

Epoch 1:  51%|█████     | 1023/2000 [00:47<00:44, 21.72it/s]

Epoch 1:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.73it/s]

Epoch 1:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.72it/s]

Epoch 1:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.71it/s]

Epoch 1:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.72it/s]

Epoch 1:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.71it/s]

Epoch 1:  52%|█████▏    | 1041/2000 [00:47<00:44, 21.70it/s]

Epoch 1:  52%|█████▏    | 1044/2000 [00:47<00:44, 21.70it/s]

Epoch 1:  52%|█████▏    | 1047/2000 [00:48<00:43, 21.70it/s]

Epoch 1:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.70it/s]

Epoch 1:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.70it/s]

Epoch 1:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.70it/s]

Epoch 1:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.69it/s]

Epoch 1:  53%|█████▎    | 1062/2000 [00:48<00:43, 21.70it/s]

Epoch 1:  53%|█████▎    | 1065/2000 [00:48<00:43, 21.71it/s]

Epoch 1:  53%|█████▎    | 1068/2000 [00:49<00:42, 21.71it/s]

Epoch 1:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.71it/s]

Epoch 1:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.71it/s]

Epoch 1:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.71it/s]

Epoch 1:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.72it/s]

Epoch 1:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.70it/s]

Epoch 1:  54%|█████▍    | 1086/2000 [00:49<00:42, 21.70it/s]

Epoch 1:  54%|█████▍    | 1089/2000 [00:50<00:41, 21.69it/s]

Epoch 1:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.69it/s]

Epoch 1:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.71it/s]

Epoch 1:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.69it/s]

Epoch 1:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.69it/s]

Epoch 1:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.71it/s]

Epoch 1:  55%|█████▌    | 1107/2000 [00:50<00:41, 21.71it/s]

Epoch 1:  56%|█████▌    | 1110/2000 [00:51<00:40, 21.72it/s]

Epoch 1:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.72it/s]

Epoch 1:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.72it/s]

Epoch 1:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.70it/s]

Epoch 1:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.70it/s]

Epoch 1:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.65it/s]

Epoch 1:  56%|█████▋    | 1128/2000 [00:51<00:40, 21.66it/s]

Epoch 1:  57%|█████▋    | 1131/2000 [00:51<00:40, 21.67it/s]

Epoch 1:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.67it/s]

Epoch 1:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.67it/s]

Epoch 1:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.67it/s]

Epoch 1:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.68it/s]

Epoch 1:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.69it/s]

Epoch 1:  57%|█████▋    | 1149/2000 [00:52<00:39, 21.67it/s]

Epoch 1:  58%|█████▊    | 1152/2000 [00:52<00:39, 21.69it/s]

Epoch 1:  58%|█████▊    | 1155/2000 [00:53<00:38, 21.68it/s]

Epoch 1:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.69it/s]

Epoch 1:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.68it/s]

Epoch 1:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.67it/s]

Epoch 1:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.69it/s]

Epoch 1:  58%|█████▊    | 1170/2000 [00:53<00:38, 21.69it/s]

Epoch 1:  59%|█████▊    | 1173/2000 [00:53<00:38, 21.69it/s]

Epoch 1:  59%|█████▉    | 1176/2000 [00:54<00:37, 21.69it/s]

Epoch 1:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.71it/s]

Epoch 1:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.70it/s]

Epoch 1:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.70it/s]

Epoch 1:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.68it/s]

Epoch 1:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.66it/s]

Epoch 1:  60%|█████▉    | 1194/2000 [00:54<00:37, 21.67it/s]

Epoch 1:  60%|█████▉    | 1197/2000 [00:55<00:37, 21.68it/s]

Epoch 1:  60%|██████    | 1200/2000 [00:55<00:36, 21.69it/s]

Epoch 1:  60%|██████    | 1203/2000 [00:55<00:36, 21.70it/s]

Epoch 1:  60%|██████    | 1206/2000 [00:55<00:36, 21.69it/s]

Epoch 1:  60%|██████    | 1209/2000 [00:55<00:36, 21.69it/s]

Epoch 1:  61%|██████    | 1212/2000 [00:55<00:36, 21.69it/s]

Epoch 1:  61%|██████    | 1215/2000 [00:55<00:36, 21.69it/s]

Epoch 1:  61%|██████    | 1218/2000 [00:55<00:36, 21.69it/s]

Epoch 1:  61%|██████    | 1221/2000 [00:56<00:35, 21.68it/s]

Epoch 1:  61%|██████    | 1224/2000 [00:56<00:35, 21.69it/s]

Epoch 1:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.69it/s]

Epoch 1:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.70it/s]

Epoch 1:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.70it/s]

Epoch 1:  62%|██████▏   | 1236/2000 [00:56<00:35, 21.71it/s]

Epoch 1:  62%|██████▏   | 1239/2000 [00:56<00:35, 21.70it/s]

Epoch 1:  62%|██████▏   | 1242/2000 [00:57<00:34, 21.69it/s]

Epoch 1:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.69it/s]

Epoch 1:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.69it/s]

Epoch 1:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.70it/s]

Epoch 1:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.68it/s]

Epoch 1:  63%|██████▎   | 1257/2000 [00:57<00:34, 21.68it/s]

Epoch 1:  63%|██████▎   | 1260/2000 [00:57<00:34, 21.69it/s]

Epoch 1:  63%|██████▎   | 1263/2000 [00:58<00:33, 21.68it/s]

Epoch 1:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.69it/s]

Epoch 1:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.68it/s]

Epoch 1:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.67it/s]

Epoch 1:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.68it/s]

Epoch 1:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.69it/s]

Epoch 1:  64%|██████▍   | 1281/2000 [00:58<00:33, 21.69it/s]

Epoch 1:  64%|██████▍   | 1284/2000 [00:59<00:33, 21.67it/s]

Epoch 1:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.67it/s]

Epoch 1:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.68it/s]

Epoch 1:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.67it/s]

Epoch 1:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.68it/s]

Epoch 1:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.68it/s]

Epoch 1:  65%|██████▌   | 1302/2000 [00:59<00:32, 21.70it/s]

Epoch 1:  65%|██████▌   | 1305/2000 [01:00<00:32, 21.71it/s]

Epoch 1:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.72it/s]

Epoch 1:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.71it/s]

Epoch 1:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.70it/s]

Epoch 1:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.70it/s]

Epoch 1:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.67it/s]

Epoch 1:  66%|██████▌   | 1323/2000 [01:00<00:32, 20.96it/s]

Epoch 1:  66%|██████▋   | 1326/2000 [01:00<00:32, 20.94it/s]

Epoch 1:  66%|██████▋   | 1329/2000 [01:01<00:31, 21.13it/s]

Epoch 1:  67%|██████▋   | 1332/2000 [01:01<00:31, 21.24it/s]

Epoch 1:  67%|██████▋   | 1335/2000 [01:01<00:31, 21.39it/s]

Epoch 1:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.48it/s]

Epoch 1:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.54it/s]

Epoch 1:  67%|██████▋   | 1344/2000 [01:01<00:30, 21.59it/s]

Epoch 1:  67%|██████▋   | 1347/2000 [01:01<00:30, 21.61it/s]

Epoch 1:  68%|██████▊   | 1350/2000 [01:02<00:30, 21.64it/s]

Epoch 1:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.65it/s]

Epoch 1:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.66it/s]

Epoch 1:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.67it/s]

Epoch 1:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.68it/s]

Epoch 1:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.69it/s]

Epoch 1:  68%|██████▊   | 1368/2000 [01:02<00:29, 21.71it/s]

Epoch 1:  69%|██████▊   | 1371/2000 [01:03<00:28, 21.71it/s]

Epoch 1:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.71it/s]

Epoch 1:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.71it/s]

Epoch 1:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.70it/s]

Epoch 1:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.70it/s]

Epoch 1:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.69it/s]

Epoch 1:  69%|██████▉   | 1389/2000 [01:03<00:28, 21.71it/s]

Epoch 1:  70%|██████▉   | 1392/2000 [01:04<00:28, 21.48it/s]

Epoch 1:  70%|██████▉   | 1395/2000 [01:04<00:28, 21.40it/s]

Epoch 1:  70%|██████▉   | 1398/2000 [01:04<00:28, 21.49it/s]

Epoch 1:  70%|███████   | 1401/2000 [01:04<00:27, 21.53it/s]

Epoch 1:  70%|███████   | 1404/2000 [01:04<00:27, 21.58it/s]

Epoch 1:  70%|███████   | 1407/2000 [01:04<00:27, 21.59it/s]

Epoch 1:  70%|███████   | 1410/2000 [01:04<00:27, 21.63it/s]

Epoch 1:  71%|███████   | 1413/2000 [01:05<00:27, 21.64it/s]

Epoch 1:  71%|███████   | 1416/2000 [01:05<00:26, 21.64it/s]

Epoch 1:  71%|███████   | 1419/2000 [01:05<00:26, 21.65it/s]

Epoch 1:  71%|███████   | 1422/2000 [01:05<00:26, 21.68it/s]

Epoch 1:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.69it/s]

Epoch 1:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.70it/s]

Epoch 1:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.70it/s]

Epoch 1:  72%|███████▏  | 1434/2000 [01:05<00:26, 21.70it/s]

Epoch 1:  72%|███████▏  | 1437/2000 [01:06<00:25, 21.71it/s]

Epoch 1:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.69it/s]

Epoch 1:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.69it/s]

Epoch 1:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.70it/s]

Epoch 1:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.70it/s]

Epoch 1:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.70it/s]

Epoch 1:  73%|███████▎  | 1455/2000 [01:06<00:25, 21.71it/s]

Epoch 1:  73%|███████▎  | 1458/2000 [01:07<00:24, 21.70it/s]

Epoch 1:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.70it/s]

Epoch 1:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.70it/s]

Epoch 1:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.69it/s]

Epoch 1:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.68it/s]

Epoch 1:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.67it/s]

Epoch 1:  74%|███████▍  | 1476/2000 [01:07<00:24, 21.70it/s]

Epoch 1:  74%|███████▍  | 1479/2000 [01:08<00:24, 21.69it/s]

Epoch 1:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.70it/s]

Epoch 1:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.71it/s]

Epoch 1:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.70it/s]

Epoch 1:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.70it/s]

Epoch 1:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.70it/s]

Epoch 1:  75%|███████▍  | 1497/2000 [01:08<00:23, 21.69it/s]

Epoch 1:  75%|███████▌  | 1500/2000 [01:09<00:23, 21.68it/s]

Epoch 1:  75%|███████▌  | 1503/2000 [01:09<00:22, 21.69it/s]

Epoch 1:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.68it/s]

Epoch 1:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.68it/s]

Epoch 1:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.69it/s]

Epoch 1:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.69it/s]

Epoch 1:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.69it/s]

Epoch 1:  76%|███████▌  | 1521/2000 [01:09<00:22, 21.69it/s]

Epoch 1:  76%|███████▌  | 1524/2000 [01:10<00:21, 21.70it/s]

Epoch 1:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.70it/s]

Epoch 1:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.69it/s]

Epoch 1:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.70it/s]

Epoch 1:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.71it/s]

Epoch 1:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.70it/s]

Epoch 1:  77%|███████▋  | 1542/2000 [01:10<00:21, 21.70it/s]

Epoch 1:  77%|███████▋  | 1545/2000 [01:11<00:20, 21.70it/s]

Epoch 1:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.69it/s]

Epoch 1:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.70it/s]

Epoch 1:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.68it/s]

Epoch 1:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.68it/s]

Epoch 1:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.68it/s]

Epoch 1:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.64it/s]

Epoch 1:  78%|███████▊  | 1566/2000 [01:12<00:20, 21.66it/s]

Epoch 1:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.67it/s]

Epoch 1:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.68it/s]

Epoch 1:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.69it/s]

Epoch 1:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.70it/s]

Epoch 1:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.71it/s]

Epoch 1:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.42it/s]

Epoch 1:  79%|███████▉  | 1587/2000 [01:13<00:19, 21.51it/s]

Epoch 1:  80%|███████▉  | 1590/2000 [01:13<00:19, 21.56it/s]

Epoch 1:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.61it/s]

Epoch 1:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.62it/s]

Epoch 1:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.67it/s]

Epoch 1:  80%|████████  | 1602/2000 [01:13<00:18, 21.67it/s]

Epoch 1:  80%|████████  | 1605/2000 [01:13<00:18, 21.68it/s]

Epoch 1:  80%|████████  | 1608/2000 [01:14<00:18, 21.70it/s]

Epoch 1:  81%|████████  | 1611/2000 [01:14<00:17, 21.70it/s]

Epoch 1:  81%|████████  | 1614/2000 [01:14<00:17, 21.71it/s]

Epoch 1:  81%|████████  | 1617/2000 [01:14<00:17, 21.69it/s]

Epoch 1:  81%|████████  | 1620/2000 [01:14<00:17, 21.70it/s]

Epoch 1:  81%|████████  | 1623/2000 [01:14<00:17, 21.69it/s]

Epoch 1:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.69it/s]

Epoch 1:  81%|████████▏ | 1629/2000 [01:14<00:17, 21.70it/s]

Epoch 1:  82%|████████▏ | 1632/2000 [01:15<00:16, 21.70it/s]

Epoch 1:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.71it/s]

Epoch 1:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.71it/s]

Epoch 1:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.70it/s]

Epoch 1:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.70it/s]

Epoch 1:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.72it/s]

Epoch 1:  82%|████████▎ | 1650/2000 [01:15<00:16, 21.72it/s]

Epoch 1:  83%|████████▎ | 1653/2000 [01:16<00:15, 21.71it/s]

Epoch 1:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.71it/s]

Epoch 1:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.70it/s]

Epoch 1:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.70it/s]

Epoch 1:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.70it/s]

Epoch 1:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.70it/s]

Epoch 1:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.69it/s]

Epoch 1:  84%|████████▎ | 1674/2000 [01:17<00:15, 21.71it/s]

Epoch 1:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.71it/s]

Epoch 1:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.72it/s]

Epoch 1:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.72it/s]

Epoch 1:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.70it/s]

Epoch 1:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.70it/s]

Epoch 1:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.71it/s]

Epoch 1:  85%|████████▍ | 1695/2000 [01:18<00:14, 21.71it/s]

Epoch 1:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.72it/s]

Epoch 1:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.72it/s]

Epoch 1:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.72it/s]

Epoch 1:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.71it/s]

Epoch 1:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.72it/s]

Epoch 1:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.71it/s]

Epoch 1:  86%|████████▌ | 1716/2000 [01:18<00:13, 21.71it/s]

Epoch 1:  86%|████████▌ | 1719/2000 [01:19<00:12, 21.72it/s]

Epoch 1:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.72it/s]

Epoch 1:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.72it/s]

Epoch 1:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.71it/s]

Epoch 1:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.71it/s]

Epoch 1:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.70it/s]

Epoch 1:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.71it/s]

Epoch 1:  87%|████████▋ | 1740/2000 [01:20<00:12, 21.64it/s]

Epoch 1:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.65it/s]

Epoch 1:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.67it/s]

Epoch 1:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.65it/s]

Epoch 1:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.66it/s]

Epoch 1:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.68it/s]

Epoch 1:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.68it/s]

Epoch 1:  88%|████████▊ | 1761/2000 [01:21<00:11, 21.68it/s]

Epoch 1:  88%|████████▊ | 1764/2000 [01:21<00:10, 21.69it/s]

Epoch 1:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.70it/s]

Epoch 1:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.70it/s]

Epoch 1:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.69it/s]

Epoch 1:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.61it/s]

Epoch 1:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.66it/s]

Epoch 1:  89%|████████▉ | 1782/2000 [01:22<00:10, 21.70it/s]

Epoch 1:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.74it/s]

Epoch 1:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.77it/s]

Epoch 1:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.79it/s]

Epoch 1:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.79it/s]

Epoch 1:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.79it/s]

Epoch 1:  90%|█████████ | 1800/2000 [01:22<00:09, 21.81it/s]

Epoch 1:  90%|█████████ | 1803/2000 [01:22<00:09, 21.81it/s]

Epoch 1:  90%|█████████ | 1806/2000 [01:23<00:08, 21.83it/s]

Epoch 1:  90%|█████████ | 1809/2000 [01:23<00:08, 21.83it/s]

Epoch 1:  91%|█████████ | 1812/2000 [01:23<00:08, 21.84it/s]

Epoch 1:  91%|█████████ | 1815/2000 [01:23<00:08, 21.84it/s]

Epoch 1:  91%|█████████ | 1818/2000 [01:23<00:08, 21.85it/s]

Epoch 1:  91%|█████████ | 1821/2000 [01:23<00:08, 21.85it/s]

Epoch 1:  91%|█████████ | 1824/2000 [01:23<00:08, 21.86it/s]

Epoch 1:  91%|█████████▏| 1827/2000 [01:24<00:07, 21.86it/s]

Epoch 1:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.88it/s]

Epoch 1:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.88it/s]

Epoch 1:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.87it/s]

Epoch 1:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.86it/s]

Epoch 1:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.85it/s]

Epoch 1:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.86it/s]

Epoch 1:  92%|█████████▏| 1848/2000 [01:25<00:06, 21.86it/s]

Epoch 1:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.86it/s]

Epoch 1:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.85it/s]

Epoch 1:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.84it/s]

Epoch 1:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.85it/s]

Epoch 1:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.85it/s]

Epoch 1:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.86it/s]

Epoch 1:  93%|█████████▎| 1869/2000 [01:26<00:05, 21.86it/s]

Epoch 1:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.84it/s]

Epoch 1:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.83it/s]

Epoch 1:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.83it/s]

Epoch 1:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.83it/s]

Epoch 1:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.85it/s]

Epoch 1:  94%|█████████▍| 1887/2000 [01:26<00:05, 21.85it/s]

Epoch 1:  94%|█████████▍| 1890/2000 [01:26<00:05, 21.85it/s]

Epoch 1:  95%|█████████▍| 1893/2000 [01:27<00:04, 21.84it/s]

Epoch 1:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.85it/s]

Epoch 1:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.84it/s]

Epoch 1:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.84it/s]

Epoch 1:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.83it/s]

Epoch 1:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.84it/s]

Epoch 1:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.84it/s]

Epoch 1:  96%|█████████▌| 1914/2000 [01:28<00:03, 21.84it/s]

Epoch 1:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.83it/s]

Epoch 1:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.85it/s]

Epoch 1:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.83it/s]

Epoch 1:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.83it/s]

Epoch 1:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.84it/s]

Epoch 1:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.84it/s]

Epoch 1:  97%|█████████▋| 1935/2000 [01:29<00:02, 21.83it/s]

Epoch 1:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.85it/s]

Epoch 1:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.84it/s]

Epoch 1:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.84it/s]

Epoch 1:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.83it/s]

Epoch 1:  98%|█████████▊| 1950/2000 [01:29<00:02, 19.68it/s]

Epoch 1:  98%|█████████▊| 1953/2000 [01:29<00:02, 20.27it/s]

Epoch 1:  98%|█████████▊| 1956/2000 [01:30<00:02, 20.72it/s]

Epoch 1:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.03it/s]

Epoch 1:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.26it/s]

Epoch 1:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.42it/s]

Epoch 1:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.55it/s]

Epoch 1:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.67it/s]

Epoch 1:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.74it/s]

Epoch 1:  99%|█████████▉| 1977/2000 [01:31<00:01, 21.77it/s]

Epoch 1:  99%|█████████▉| 1980/2000 [01:31<00:00, 21.80it/s]

Epoch 1:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.82it/s]

Epoch 1:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.85it/s]

Epoch 1:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.85it/s]

Epoch 1: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.87it/s]

Epoch 1: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.88it/s]

Epoch 1: 100%|█████████▉| 1998/2000 [01:31<00:00, 21.86it/s]

Epoch 1: loss=0.3888, val_proxy=0.5233

Epoch 2:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 2:   0%|          | 3/2000 [00:00<01:32, 21.62it/s]

Epoch 2:   0%|          | 6/2000 [00:00<01:31, 21.74it/s]

Epoch 2:   0%|          | 9/2000 [00:00<01:31, 21.67it/s]

Epoch 2:   1%|          | 12/2000 [00:00<01:31, 21.68it/s]

Epoch 2:   1%|          | 15/2000 [00:00<01:31, 21.72it/s]

Epoch 2:   1%|          | 18/2000 [00:00<01:31, 21.76it/s]

Epoch 2:   1%|          | 21/2000 [00:00<01:30, 21.78it/s]

Epoch 2:   1%|          | 24/2000 [00:01<01:30, 21.79it/s]

Epoch 2:   1%|▏         | 27/2000 [00:01<01:30, 21.79it/s]

Epoch 2:   2%|▏         | 30/2000 [00:01<01:30, 21.77it/s]

Epoch 2:   2%|▏         | 33/2000 [00:01<01:30, 21.76it/s]

Epoch 2:   2%|▏         | 36/2000 [00:01<01:30, 21.75it/s]

Epoch 2:   2%|▏         | 39/2000 [00:01<01:30, 21.77it/s]

Epoch 2:   2%|▏         | 42/2000 [00:01<01:29, 21.77it/s]

Epoch 2:   2%|▏         | 45/2000 [00:02<01:29, 21.80it/s]

Epoch 2:   2%|▏         | 48/2000 [00:02<01:29, 21.81it/s]

Epoch 2:   3%|▎         | 51/2000 [00:02<01:29, 21.81it/s]

Epoch 2:   3%|▎         | 54/2000 [00:02<01:29, 21.82it/s]

Epoch 2:   3%|▎         | 57/2000 [00:02<01:29, 21.83it/s]

Epoch 2:   3%|▎         | 60/2000 [00:02<01:28, 21.85it/s]

Epoch 2:   3%|▎         | 63/2000 [00:02<01:28, 21.87it/s]

Epoch 2:   3%|▎         | 66/2000 [00:03<01:28, 21.81it/s]

Epoch 2:   3%|▎         | 69/2000 [00:03<01:28, 21.79it/s]

Epoch 2:   4%|▎         | 72/2000 [00:03<01:28, 21.78it/s]

Epoch 2:   4%|▍         | 75/2000 [00:03<01:28, 21.77it/s]

Epoch 2:   4%|▍         | 78/2000 [00:03<01:28, 21.76it/s]

Epoch 2:   4%|▍         | 81/2000 [00:03<01:28, 21.76it/s]

Epoch 2:   4%|▍         | 84/2000 [00:03<01:28, 21.76it/s]

Epoch 2:   4%|▍         | 87/2000 [00:03<01:27, 21.76it/s]

Epoch 2:   4%|▍         | 90/2000 [00:04<01:27, 21.75it/s]

Epoch 2:   5%|▍         | 93/2000 [00:04<01:27, 21.74it/s]

Epoch 2:   5%|▍         | 96/2000 [00:04<01:27, 21.73it/s]

Epoch 2:   5%|▍         | 99/2000 [00:04<01:27, 21.73it/s]

Epoch 2:   5%|▌         | 102/2000 [00:04<01:27, 21.72it/s]

Epoch 2:   5%|▌         | 105/2000 [00:04<01:27, 21.72it/s]

Epoch 2:   5%|▌         | 108/2000 [00:04<01:27, 21.72it/s]

Epoch 2:   6%|▌         | 111/2000 [00:05<01:26, 21.72it/s]

Epoch 2:   6%|▌         | 114/2000 [00:05<01:26, 21.71it/s]

Epoch 2:   6%|▌         | 117/2000 [00:05<01:26, 21.72it/s]

Epoch 2:   6%|▌         | 120/2000 [00:05<01:26, 21.72it/s]

Epoch 2:   6%|▌         | 123/2000 [00:05<01:26, 21.72it/s]

Epoch 2:   6%|▋         | 126/2000 [00:05<01:26, 21.72it/s]

Epoch 2:   6%|▋         | 129/2000 [00:05<01:26, 21.71it/s]

Epoch 2:   7%|▋         | 132/2000 [00:06<01:26, 21.70it/s]

Epoch 2:   7%|▋         | 135/2000 [00:06<01:25, 21.70it/s]

Epoch 2:   7%|▋         | 138/2000 [00:06<01:25, 21.71it/s]

Epoch 2:   7%|▋         | 141/2000 [00:06<01:25, 21.72it/s]

Epoch 2:   7%|▋         | 144/2000 [00:06<01:25, 21.73it/s]

Epoch 2:   7%|▋         | 147/2000 [00:06<01:25, 21.73it/s]

Epoch 2:   8%|▊         | 150/2000 [00:06<01:25, 21.75it/s]

Epoch 2:   8%|▊         | 153/2000 [00:07<01:24, 21.74it/s]

Epoch 2:   8%|▊         | 156/2000 [00:07<01:24, 21.73it/s]

Epoch 2:   8%|▊         | 159/2000 [00:07<01:24, 21.73it/s]

Epoch 2:   8%|▊         | 162/2000 [00:07<01:24, 21.74it/s]

Epoch 2:   8%|▊         | 165/2000 [00:07<01:24, 21.72it/s]

Epoch 2:   8%|▊         | 168/2000 [00:07<01:24, 21.73it/s]

Epoch 2:   9%|▊         | 171/2000 [00:07<01:24, 21.73it/s]

Epoch 2:   9%|▊         | 174/2000 [00:08<01:24, 21.72it/s]

Epoch 2:   9%|▉         | 177/2000 [00:08<01:23, 21.71it/s]

Epoch 2:   9%|▉         | 180/2000 [00:08<01:23, 21.71it/s]

Epoch 2:   9%|▉         | 183/2000 [00:08<01:23, 21.71it/s]

Epoch 2:   9%|▉         | 186/2000 [00:08<01:23, 21.70it/s]

Epoch 2:   9%|▉         | 189/2000 [00:08<01:23, 21.72it/s]

Epoch 2:  10%|▉         | 192/2000 [00:08<01:23, 21.72it/s]

Epoch 2:  10%|▉         | 195/2000 [00:08<01:23, 21.71it/s]

Epoch 2:  10%|▉         | 198/2000 [00:09<01:22, 21.71it/s]

Epoch 2:  10%|█         | 201/2000 [00:09<01:22, 21.71it/s]

Epoch 2:  10%|█         | 204/2000 [00:09<01:22, 21.72it/s]

Epoch 2:  10%|█         | 207/2000 [00:09<01:22, 21.71it/s]

Epoch 2:  10%|█         | 210/2000 [00:09<01:22, 21.73it/s]

Epoch 2:  11%|█         | 213/2000 [00:09<01:22, 21.73it/s]

Epoch 2:  11%|█         | 216/2000 [00:09<01:22, 21.74it/s]

Epoch 2:  11%|█         | 219/2000 [00:10<01:21, 21.74it/s]

Epoch 2:  11%|█         | 222/2000 [00:10<01:21, 21.73it/s]

Epoch 2:  11%|█▏        | 225/2000 [00:10<01:21, 21.72it/s]

Epoch 2:  11%|█▏        | 228/2000 [00:10<01:21, 21.72it/s]

Epoch 2:  12%|█▏        | 231/2000 [00:10<01:21, 21.70it/s]

Epoch 2:  12%|█▏        | 234/2000 [00:10<01:21, 21.71it/s]

Epoch 2:  12%|█▏        | 237/2000 [00:10<01:21, 21.71it/s]

Epoch 2:  12%|█▏        | 240/2000 [00:11<01:21, 21.72it/s]

Epoch 2:  12%|█▏        | 243/2000 [00:11<01:20, 21.72it/s]

Epoch 2:  12%|█▏        | 246/2000 [00:11<01:20, 21.72it/s]

Epoch 2:  12%|█▏        | 249/2000 [00:11<01:20, 21.72it/s]

Epoch 2:  13%|█▎        | 252/2000 [00:11<01:20, 21.71it/s]

Epoch 2:  13%|█▎        | 255/2000 [00:11<01:20, 21.70it/s]

Epoch 2:  13%|█▎        | 258/2000 [00:11<01:20, 21.72it/s]

Epoch 2:  13%|█▎        | 261/2000 [00:12<01:20, 21.71it/s]

Epoch 2:  13%|█▎        | 264/2000 [00:12<01:19, 21.71it/s]

Epoch 2:  13%|█▎        | 267/2000 [00:12<01:20, 21.50it/s]

Epoch 2:  14%|█▎        | 270/2000 [00:12<01:20, 21.54it/s]

Epoch 2:  14%|█▎        | 273/2000 [00:12<01:21, 21.31it/s]

Epoch 2:  14%|█▍        | 276/2000 [00:12<01:20, 21.42it/s]

Epoch 2:  14%|█▍        | 279/2000 [00:12<01:20, 21.48it/s]

Epoch 2:  14%|█▍        | 282/2000 [00:12<01:20, 21.23it/s]

Epoch 2:  14%|█▍        | 285/2000 [00:13<01:20, 21.34it/s]

Epoch 2:  14%|█▍        | 288/2000 [00:13<01:19, 21.41it/s]

Epoch 2:  15%|█▍        | 291/2000 [00:13<01:19, 21.46it/s]

Epoch 2:  15%|█▍        | 294/2000 [00:13<01:20, 21.26it/s]

Epoch 2:  15%|█▍        | 297/2000 [00:13<01:19, 21.36it/s]

Epoch 2:  15%|█▌        | 300/2000 [00:13<01:19, 21.44it/s]

Epoch 2:  15%|█▌        | 303/2000 [00:13<01:18, 21.49it/s]

Epoch 2:  15%|█▌        | 306/2000 [00:14<01:18, 21.52it/s]

Epoch 2:  15%|█▌        | 309/2000 [00:14<01:18, 21.54it/s]

Epoch 2:  16%|█▌        | 312/2000 [00:14<01:18, 21.58it/s]

Epoch 2:  16%|█▌        | 315/2000 [00:14<01:18, 21.60it/s]

Epoch 2:  16%|█▌        | 318/2000 [00:14<01:17, 21.62it/s]

Epoch 2:  16%|█▌        | 321/2000 [00:14<01:17, 21.63it/s]

Epoch 2:  16%|█▌        | 324/2000 [00:14<01:17, 21.63it/s]

Epoch 2:  16%|█▋        | 327/2000 [00:15<01:17, 21.63it/s]

Epoch 2:  16%|█▋        | 330/2000 [00:15<01:17, 21.63it/s]

Epoch 2:  17%|█▋        | 333/2000 [00:15<01:17, 21.64it/s]

Epoch 2:  17%|█▋        | 336/2000 [00:15<01:16, 21.61it/s]

Epoch 2:  17%|█▋        | 339/2000 [00:15<01:19, 20.90it/s]

Epoch 2:  17%|█▋        | 342/2000 [00:15<01:19, 20.89it/s]

Epoch 2:  17%|█▋        | 345/2000 [00:15<01:18, 21.05it/s]

Epoch 2:  17%|█▋        | 348/2000 [00:16<01:18, 21.15it/s]

Epoch 2:  18%|█▊        | 351/2000 [00:16<01:17, 21.29it/s]

Epoch 2:  18%|█▊        | 354/2000 [00:16<01:16, 21.39it/s]

Epoch 2:  18%|█▊        | 357/2000 [00:16<01:16, 21.50it/s]

Epoch 2:  18%|█▊        | 360/2000 [00:16<01:16, 21.56it/s]

Epoch 2:  18%|█▊        | 363/2000 [00:16<01:15, 21.60it/s]

Epoch 2:  18%|█▊        | 366/2000 [00:16<01:15, 21.64it/s]

Epoch 2:  18%|█▊        | 369/2000 [00:17<01:15, 21.65it/s]

Epoch 2:  19%|█▊        | 372/2000 [00:17<01:15, 21.67it/s]

Epoch 2:  19%|█▉        | 375/2000 [00:17<01:14, 21.68it/s]

Epoch 2:  19%|█▉        | 378/2000 [00:17<01:14, 21.69it/s]

Epoch 2:  19%|█▉        | 381/2000 [00:17<01:14, 21.61it/s]

Epoch 2:  19%|█▉        | 384/2000 [00:17<01:14, 21.63it/s]

Epoch 2:  19%|█▉        | 387/2000 [00:17<01:14, 21.65it/s]

Epoch 2:  20%|█▉        | 390/2000 [00:18<01:14, 21.66it/s]

Epoch 2:  20%|█▉        | 393/2000 [00:18<01:14, 21.67it/s]

Epoch 2:  20%|█▉        | 396/2000 [00:18<01:13, 21.68it/s]

Epoch 2:  20%|█▉        | 399/2000 [00:18<01:13, 21.68it/s]

Epoch 2:  20%|██        | 402/2000 [00:18<01:13, 21.68it/s]

Epoch 2:  20%|██        | 405/2000 [00:18<01:13, 21.69it/s]

Epoch 2:  20%|██        | 408/2000 [00:18<01:13, 21.70it/s]

Epoch 2:  21%|██        | 411/2000 [00:18<01:13, 21.68it/s]

Epoch 2:  21%|██        | 414/2000 [00:19<01:13, 21.68it/s]

Epoch 2:  21%|██        | 417/2000 [00:19<01:13, 21.68it/s]

Epoch 2:  21%|██        | 420/2000 [00:19<01:12, 21.68it/s]

Epoch 2:  21%|██        | 423/2000 [00:19<01:12, 21.70it/s]

Epoch 2:  21%|██▏       | 426/2000 [00:19<01:12, 21.70it/s]

Epoch 2:  21%|██▏       | 429/2000 [00:19<01:12, 21.70it/s]

Epoch 2:  22%|██▏       | 432/2000 [00:19<01:12, 21.68it/s]

Epoch 2:  22%|██▏       | 435/2000 [00:20<01:12, 21.69it/s]

Epoch 2:  22%|██▏       | 438/2000 [00:20<01:11, 21.70it/s]

Epoch 2:  22%|██▏       | 441/2000 [00:20<01:11, 21.70it/s]

Epoch 2:  22%|██▏       | 444/2000 [00:20<01:11, 21.70it/s]

Epoch 2:  22%|██▏       | 447/2000 [00:20<01:11, 21.69it/s]

Epoch 2:  22%|██▎       | 450/2000 [00:20<01:11, 21.71it/s]

Epoch 2:  23%|██▎       | 453/2000 [00:20<01:11, 21.71it/s]

Epoch 2:  23%|██▎       | 456/2000 [00:21<01:11, 21.70it/s]

Epoch 2:  23%|██▎       | 459/2000 [00:21<01:10, 21.71it/s]

Epoch 2:  23%|██▎       | 462/2000 [00:21<01:10, 21.72it/s]

Epoch 2:  23%|██▎       | 465/2000 [00:21<01:10, 21.72it/s]

Epoch 2:  23%|██▎       | 468/2000 [00:21<01:10, 21.73it/s]

Epoch 2:  24%|██▎       | 471/2000 [00:21<01:10, 21.72it/s]

Epoch 2:  24%|██▎       | 474/2000 [00:21<01:10, 21.73it/s]

Epoch 2:  24%|██▍       | 477/2000 [00:22<01:10, 21.73it/s]

Epoch 2:  24%|██▍       | 480/2000 [00:22<01:09, 21.72it/s]

Epoch 2:  24%|██▍       | 483/2000 [00:22<01:09, 21.71it/s]

Epoch 2:  24%|██▍       | 486/2000 [00:22<01:09, 21.72it/s]

Epoch 2:  24%|██▍       | 489/2000 [00:22<01:09, 21.72it/s]

Epoch 2:  25%|██▍       | 492/2000 [00:22<01:09, 21.71it/s]

Epoch 2:  25%|██▍       | 495/2000 [00:22<01:09, 21.71it/s]

Epoch 2:  25%|██▍       | 498/2000 [00:22<01:09, 21.71it/s]

Epoch 2:  25%|██▌       | 501/2000 [00:23<01:09, 21.71it/s]

Epoch 2:  25%|██▌       | 504/2000 [00:23<01:08, 21.70it/s]

Epoch 2:  25%|██▌       | 507/2000 [00:23<01:08, 21.70it/s]

Epoch 2:  26%|██▌       | 510/2000 [00:23<01:08, 21.71it/s]

Epoch 2:  26%|██▌       | 513/2000 [00:23<01:08, 21.71it/s]

Epoch 2:  26%|██▌       | 516/2000 [00:23<01:08, 21.70it/s]

Epoch 2:  26%|██▌       | 519/2000 [00:23<01:08, 21.71it/s]

Epoch 2:  26%|██▌       | 522/2000 [00:24<01:08, 21.71it/s]

Epoch 2:  26%|██▋       | 525/2000 [00:24<01:07, 21.71it/s]

Epoch 2:  26%|██▋       | 528/2000 [00:24<01:07, 21.72it/s]

Epoch 2:  27%|██▋       | 531/2000 [00:24<01:07, 21.73it/s]

Epoch 2:  27%|██▋       | 534/2000 [00:24<01:07, 21.73it/s]

Epoch 2:  27%|██▋       | 537/2000 [00:24<01:07, 21.72it/s]

Epoch 2:  27%|██▋       | 540/2000 [00:24<01:07, 21.73it/s]

Epoch 2:  27%|██▋       | 543/2000 [00:25<01:07, 21.71it/s]

Epoch 2:  27%|██▋       | 546/2000 [00:25<01:06, 21.71it/s]

Epoch 2:  27%|██▋       | 549/2000 [00:25<01:06, 21.71it/s]

Epoch 2:  28%|██▊       | 552/2000 [00:25<01:06, 21.72it/s]

Epoch 2:  28%|██▊       | 555/2000 [00:25<01:06, 21.73it/s]

Epoch 2:  28%|██▊       | 558/2000 [00:25<01:06, 21.73it/s]

Epoch 2:  28%|██▊       | 561/2000 [00:25<01:06, 21.72it/s]

Epoch 2:  28%|██▊       | 564/2000 [00:26<01:06, 21.72it/s]

Epoch 2:  28%|██▊       | 567/2000 [00:26<01:05, 21.72it/s]

Epoch 2:  28%|██▊       | 570/2000 [00:26<01:05, 21.72it/s]

Epoch 2:  29%|██▊       | 573/2000 [00:26<01:05, 21.71it/s]

Epoch 2:  29%|██▉       | 576/2000 [00:26<01:05, 21.71it/s]

Epoch 2:  29%|██▉       | 579/2000 [00:26<01:05, 21.72it/s]

Epoch 2:  29%|██▉       | 582/2000 [00:26<01:05, 21.71it/s]

Epoch 2:  29%|██▉       | 585/2000 [00:26<01:05, 21.69it/s]

Epoch 2:  29%|██▉       | 588/2000 [00:27<01:05, 21.69it/s]

Epoch 2:  30%|██▉       | 591/2000 [00:27<01:04, 21.70it/s]

Epoch 2:  30%|██▉       | 594/2000 [00:27<01:04, 21.71it/s]

Epoch 2:  30%|██▉       | 597/2000 [00:27<01:04, 21.70it/s]

Epoch 2:  30%|███       | 600/2000 [00:27<01:04, 21.72it/s]

Epoch 2:  30%|███       | 603/2000 [00:27<01:04, 21.73it/s]

Epoch 2:  30%|███       | 606/2000 [00:27<01:04, 21.73it/s]

Epoch 2:  30%|███       | 609/2000 [00:28<01:04, 21.69it/s]

Epoch 2:  31%|███       | 612/2000 [00:28<01:03, 21.71it/s]

Epoch 2:  31%|███       | 615/2000 [00:28<01:03, 21.70it/s]

Epoch 2:  31%|███       | 618/2000 [00:28<01:03, 21.71it/s]

Epoch 2:  31%|███       | 621/2000 [00:28<01:03, 21.71it/s]

Epoch 2:  31%|███       | 624/2000 [00:28<01:03, 21.73it/s]

Epoch 2:  31%|███▏      | 627/2000 [00:28<01:03, 21.73it/s]

Epoch 2:  32%|███▏      | 630/2000 [00:29<01:03, 21.65it/s]

Epoch 2:  32%|███▏      | 633/2000 [00:29<01:03, 21.66it/s]

Epoch 2:  32%|███▏      | 636/2000 [00:29<01:03, 21.65it/s]

Epoch 2:  32%|███▏      | 639/2000 [00:29<01:02, 21.67it/s]

Epoch 2:  32%|███▏      | 642/2000 [00:29<01:02, 21.69it/s]

Epoch 2:  32%|███▏      | 645/2000 [00:29<01:02, 21.70it/s]

Epoch 2:  32%|███▏      | 648/2000 [00:29<01:02, 21.71it/s]

Epoch 2:  33%|███▎      | 651/2000 [00:30<01:02, 21.72it/s]

Epoch 2:  33%|███▎      | 654/2000 [00:30<01:01, 21.72it/s]

Epoch 2:  33%|███▎      | 657/2000 [00:30<01:01, 21.72it/s]

Epoch 2:  33%|███▎      | 660/2000 [00:30<01:01, 21.72it/s]

Epoch 2:  33%|███▎      | 663/2000 [00:30<01:01, 21.71it/s]

Epoch 2:  33%|███▎      | 666/2000 [00:30<01:01, 21.71it/s]

Epoch 2:  33%|███▎      | 669/2000 [00:30<01:01, 21.71it/s]

Epoch 2:  34%|███▎      | 672/2000 [00:31<01:01, 21.70it/s]

Epoch 2:  34%|███▍      | 675/2000 [00:31<01:01, 21.71it/s]

Epoch 2:  34%|███▍      | 678/2000 [00:31<01:00, 21.72it/s]

Epoch 2:  34%|███▍      | 681/2000 [00:31<01:00, 21.72it/s]

Epoch 2:  34%|███▍      | 684/2000 [00:31<01:00, 21.72it/s]

Epoch 2:  34%|███▍      | 687/2000 [00:31<01:00, 21.73it/s]

Epoch 2:  34%|███▍      | 690/2000 [00:31<01:00, 21.73it/s]

Epoch 2:  35%|███▍      | 693/2000 [00:31<01:00, 21.73it/s]

Epoch 2:  35%|███▍      | 696/2000 [00:32<01:00, 21.73it/s]

Epoch 2:  35%|███▍      | 699/2000 [00:32<00:59, 21.72it/s]

Epoch 2:  35%|███▌      | 702/2000 [00:32<01:00, 21.34it/s]

Epoch 2:  35%|███▌      | 705/2000 [00:32<01:00, 21.45it/s]

Epoch 2:  35%|███▌      | 708/2000 [00:32<01:00, 21.53it/s]

Epoch 2:  36%|███▌      | 711/2000 [00:32<00:59, 21.58it/s]

Epoch 2:  36%|███▌      | 714/2000 [00:32<00:59, 21.62it/s]

Epoch 2:  36%|███▌      | 717/2000 [00:33<00:59, 21.63it/s]

Epoch 2:  36%|███▌      | 720/2000 [00:33<00:59, 21.65it/s]

Epoch 2:  36%|███▌      | 723/2000 [00:33<00:59, 21.55it/s]

Epoch 2:  36%|███▋      | 726/2000 [00:33<00:59, 21.58it/s]

Epoch 2:  36%|███▋      | 729/2000 [00:33<00:58, 21.61it/s]

Epoch 2:  37%|███▋      | 732/2000 [00:33<00:58, 21.64it/s]

Epoch 2:  37%|███▋      | 735/2000 [00:33<00:58, 21.67it/s]

Epoch 2:  37%|███▋      | 738/2000 [00:34<00:58, 21.68it/s]

Epoch 2:  37%|███▋      | 741/2000 [00:34<00:58, 21.62it/s]

Epoch 2:  37%|███▋      | 744/2000 [00:34<00:58, 21.63it/s]

Epoch 2:  37%|███▋      | 747/2000 [00:34<00:57, 21.64it/s]

Epoch 2:  38%|███▊      | 750/2000 [00:34<00:57, 21.64it/s]

Epoch 2:  38%|███▊      | 753/2000 [00:34<00:57, 21.65it/s]

Epoch 2:  38%|███▊      | 756/2000 [00:34<00:57, 21.67it/s]

Epoch 2:  38%|███▊      | 759/2000 [00:35<00:57, 21.67it/s]

Epoch 2:  38%|███▊      | 762/2000 [00:35<00:57, 21.68it/s]

Epoch 2:  38%|███▊      | 765/2000 [00:35<00:56, 21.69it/s]

Epoch 2:  38%|███▊      | 768/2000 [00:35<00:56, 21.68it/s]

Epoch 2:  39%|███▊      | 771/2000 [00:35<00:56, 21.69it/s]

Epoch 2:  39%|███▊      | 774/2000 [00:35<00:56, 21.68it/s]

Epoch 2:  39%|███▉      | 777/2000 [00:35<00:56, 21.68it/s]

Epoch 2:  39%|███▉      | 780/2000 [00:35<00:56, 21.69it/s]

Epoch 2:  39%|███▉      | 783/2000 [00:36<00:56, 21.67it/s]

Epoch 2:  39%|███▉      | 786/2000 [00:36<00:56, 21.67it/s]

Epoch 2:  39%|███▉      | 789/2000 [00:36<00:55, 21.67it/s]

Epoch 2:  40%|███▉      | 792/2000 [00:36<00:55, 21.69it/s]

Epoch 2:  40%|███▉      | 795/2000 [00:36<00:55, 21.70it/s]

Epoch 2:  40%|███▉      | 798/2000 [00:36<00:55, 21.71it/s]

Epoch 2:  40%|████      | 801/2000 [00:36<00:55, 21.70it/s]

Epoch 2:  40%|████      | 804/2000 [00:37<00:55, 21.70it/s]

Epoch 2:  40%|████      | 807/2000 [00:37<00:55, 21.69it/s]

Epoch 2:  40%|████      | 810/2000 [00:37<00:54, 21.71it/s]

Epoch 2:  41%|████      | 813/2000 [00:37<00:54, 21.69it/s]

Epoch 2:  41%|████      | 816/2000 [00:37<00:54, 21.71it/s]

Epoch 2:  41%|████      | 819/2000 [00:37<00:54, 21.72it/s]

Epoch 2:  41%|████      | 822/2000 [00:37<00:54, 21.71it/s]

Epoch 2:  41%|████▏     | 825/2000 [00:38<00:54, 21.70it/s]

Epoch 2:  41%|████▏     | 828/2000 [00:38<00:54, 21.70it/s]

Epoch 2:  42%|████▏     | 831/2000 [00:38<00:53, 21.70it/s]

Epoch 2:  42%|████▏     | 834/2000 [00:38<00:53, 21.71it/s]

Epoch 2:  42%|████▏     | 837/2000 [00:38<00:53, 21.70it/s]

Epoch 2:  42%|████▏     | 840/2000 [00:38<00:53, 21.71it/s]

Epoch 2:  42%|████▏     | 843/2000 [00:38<00:53, 21.70it/s]

Epoch 2:  42%|████▏     | 846/2000 [00:39<00:53, 21.70it/s]

Epoch 2:  42%|████▏     | 849/2000 [00:39<00:53, 21.70it/s]

Epoch 2:  43%|████▎     | 852/2000 [00:39<00:52, 21.71it/s]

Epoch 2:  43%|████▎     | 855/2000 [00:39<00:52, 21.70it/s]

Epoch 2:  43%|████▎     | 858/2000 [00:39<00:52, 21.72it/s]

Epoch 2:  43%|████▎     | 861/2000 [00:39<00:52, 21.72it/s]

Epoch 2:  43%|████▎     | 864/2000 [00:39<00:52, 21.72it/s]

Epoch 2:  43%|████▎     | 867/2000 [00:40<00:52, 21.70it/s]

Epoch 2:  44%|████▎     | 870/2000 [00:40<00:52, 21.70it/s]

Epoch 2:  44%|████▎     | 873/2000 [00:40<00:51, 21.70it/s]

Epoch 2:  44%|████▍     | 876/2000 [00:40<00:51, 21.72it/s]

Epoch 2:  44%|████▍     | 879/2000 [00:40<00:51, 21.72it/s]

Epoch 2:  44%|████▍     | 882/2000 [00:40<00:51, 21.54it/s]

Epoch 2:  44%|████▍     | 885/2000 [00:40<00:51, 21.57it/s]

Epoch 2:  44%|████▍     | 888/2000 [00:40<00:51, 21.58it/s]

Epoch 2:  45%|████▍     | 891/2000 [00:41<00:51, 21.60it/s]

Epoch 2:  45%|████▍     | 894/2000 [00:41<00:51, 21.60it/s]

Epoch 2:  45%|████▍     | 897/2000 [00:41<00:51, 21.61it/s]

Epoch 2:  45%|████▌     | 900/2000 [00:41<00:50, 21.62it/s]

Epoch 2:  45%|████▌     | 903/2000 [00:41<00:50, 21.63it/s]

Epoch 2:  45%|████▌     | 906/2000 [00:41<00:50, 21.64it/s]

Epoch 2:  45%|████▌     | 909/2000 [00:41<00:50, 21.65it/s]

Epoch 2:  46%|████▌     | 912/2000 [00:42<00:50, 21.65it/s]

Epoch 2:  46%|████▌     | 915/2000 [00:42<00:50, 21.65it/s]

Epoch 2:  46%|████▌     | 918/2000 [00:42<00:49, 21.66it/s]

Epoch 2:  46%|████▌     | 921/2000 [00:42<00:49, 21.67it/s]

Epoch 2:  46%|████▌     | 924/2000 [00:42<00:49, 21.67it/s]

Epoch 2:  46%|████▋     | 927/2000 [00:42<00:49, 21.68it/s]

Epoch 2:  46%|████▋     | 930/2000 [00:42<00:49, 21.67it/s]

Epoch 2:  47%|████▋     | 933/2000 [00:43<00:49, 21.67it/s]

Epoch 2:  47%|████▋     | 936/2000 [00:43<00:49, 21.67it/s]

Epoch 2:  47%|████▋     | 939/2000 [00:43<00:49, 21.62it/s]

Epoch 2:  47%|████▋     | 942/2000 [00:43<00:48, 21.64it/s]

Epoch 2:  47%|████▋     | 945/2000 [00:43<00:48, 21.66it/s]

Epoch 2:  47%|████▋     | 948/2000 [00:43<00:48, 21.66it/s]

Epoch 2:  48%|████▊     | 951/2000 [00:43<00:48, 21.67it/s]

Epoch 2:  48%|████▊     | 954/2000 [00:44<00:48, 21.68it/s]

Epoch 2:  48%|████▊     | 957/2000 [00:44<00:48, 21.68it/s]

Epoch 2:  48%|████▊     | 960/2000 [00:44<00:48, 21.66it/s]

Epoch 2:  48%|████▊     | 963/2000 [00:44<00:47, 21.67it/s]

Epoch 2:  48%|████▊     | 966/2000 [00:44<00:47, 21.67it/s]

Epoch 2:  48%|████▊     | 969/2000 [00:44<00:47, 21.68it/s]

Epoch 2:  49%|████▊     | 972/2000 [00:44<00:47, 21.66it/s]

Epoch 2:  49%|████▉     | 975/2000 [00:44<00:47, 21.66it/s]

Epoch 2:  49%|████▉     | 978/2000 [00:45<00:47, 21.66it/s]

Epoch 2:  49%|████▉     | 981/2000 [00:45<00:47, 21.66it/s]

Epoch 2:  49%|████▉     | 984/2000 [00:45<00:46, 21.66it/s]

Epoch 2:  49%|████▉     | 987/2000 [00:45<00:46, 21.66it/s]

Epoch 2:  50%|████▉     | 990/2000 [00:45<00:46, 21.67it/s]

Epoch 2:  50%|████▉     | 993/2000 [00:45<00:46, 21.68it/s]

Epoch 2:  50%|████▉     | 996/2000 [00:45<00:46, 21.69it/s]

Epoch 2:  50%|████▉     | 999/2000 [00:46<00:46, 21.69it/s]

Epoch 2:  50%|█████     | 1002/2000 [00:46<00:46, 21.69it/s]

Epoch 2:  50%|█████     | 1005/2000 [00:46<00:45, 21.69it/s]

Epoch 2:  50%|█████     | 1008/2000 [00:46<00:45, 21.69it/s]

Epoch 2:  51%|█████     | 1011/2000 [00:46<00:45, 21.69it/s]

Epoch 2:  51%|█████     | 1014/2000 [00:46<00:45, 21.68it/s]

Epoch 2:  51%|█████     | 1017/2000 [00:46<00:45, 21.68it/s]

Epoch 2:  51%|█████     | 1020/2000 [00:47<00:45, 21.68it/s]

Epoch 2:  51%|█████     | 1023/2000 [00:47<00:45, 21.69it/s]

Epoch 2:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.69it/s]

Epoch 2:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.69it/s]

Epoch 2:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.68it/s]

Epoch 2:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.69it/s]

Epoch 2:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.68it/s]

Epoch 2:  52%|█████▏    | 1041/2000 [00:48<00:44, 21.68it/s]

Epoch 2:  52%|█████▏    | 1044/2000 [00:48<00:44, 21.67it/s]

Epoch 2:  52%|█████▏    | 1047/2000 [00:48<00:44, 21.66it/s]

Epoch 2:  52%|█████▎    | 1050/2000 [00:48<00:45, 20.98it/s]

Epoch 2:  53%|█████▎    | 1053/2000 [00:48<00:45, 20.94it/s]

Epoch 2:  53%|█████▎    | 1056/2000 [00:48<00:44, 21.12it/s]

Epoch 2:  53%|█████▎    | 1059/2000 [00:48<00:44, 21.20it/s]

Epoch 2:  53%|█████▎    | 1062/2000 [00:49<00:43, 21.34it/s]

Epoch 2:  53%|█████▎    | 1065/2000 [00:49<00:43, 21.45it/s]

Epoch 2:  53%|█████▎    | 1068/2000 [00:49<00:43, 21.52it/s]

Epoch 2:  54%|█████▎    | 1071/2000 [00:49<00:43, 21.57it/s]

Epoch 2:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.61it/s]

Epoch 2:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.63it/s]

Epoch 2:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.66it/s]

Epoch 2:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.64it/s]

Epoch 2:  54%|█████▍    | 1086/2000 [00:50<00:42, 21.64it/s]

Epoch 2:  54%|█████▍    | 1089/2000 [00:50<00:42, 21.64it/s]

Epoch 2:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.67it/s]

Epoch 2:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.67it/s]

Epoch 2:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.68it/s]

Epoch 2:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.69it/s]

Epoch 2:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.68it/s]

Epoch 2:  55%|█████▌    | 1107/2000 [00:51<00:41, 21.68it/s]

Epoch 2:  56%|█████▌    | 1110/2000 [00:51<00:41, 21.66it/s]

Epoch 2:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.67it/s]

Epoch 2:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.67it/s]

Epoch 2:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.65it/s]

Epoch 2:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.66it/s]

Epoch 2:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.66it/s]

Epoch 2:  56%|█████▋    | 1128/2000 [00:52<00:40, 21.66it/s]

Epoch 2:  57%|█████▋    | 1131/2000 [00:52<00:40, 21.66it/s]

Epoch 2:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.67it/s]

Epoch 2:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.66it/s]

Epoch 2:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.67it/s]

Epoch 2:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.66it/s]

Epoch 2:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.69it/s]

Epoch 2:  57%|█████▋    | 1149/2000 [00:53<00:39, 21.67it/s]

Epoch 2:  58%|█████▊    | 1152/2000 [00:53<00:39, 21.68it/s]

Epoch 2:  58%|█████▊    | 1155/2000 [00:53<00:38, 21.67it/s]

Epoch 2:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.67it/s]

Epoch 2:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.67it/s]

Epoch 2:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.67it/s]

Epoch 2:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.66it/s]

Epoch 2:  58%|█████▊    | 1170/2000 [00:54<00:38, 21.66it/s]

Epoch 2:  59%|█████▊    | 1173/2000 [00:54<00:38, 21.67it/s]

Epoch 2:  59%|█████▉    | 1176/2000 [00:54<00:38, 21.67it/s]

Epoch 2:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.67it/s]

Epoch 2:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.67it/s]

Epoch 2:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.67it/s]

Epoch 2:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.65it/s]

Epoch 2:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.67it/s]

Epoch 2:  60%|█████▉    | 1194/2000 [00:55<00:37, 21.66it/s]

Epoch 2:  60%|█████▉    | 1197/2000 [00:55<00:37, 21.65it/s]

Epoch 2:  60%|██████    | 1200/2000 [00:55<00:36, 21.66it/s]

Epoch 2:  60%|██████    | 1203/2000 [00:55<00:36, 21.67it/s]

Epoch 2:  60%|██████    | 1206/2000 [00:55<00:36, 21.68it/s]

Epoch 2:  60%|██████    | 1209/2000 [00:55<00:36, 21.67it/s]

Epoch 2:  61%|██████    | 1212/2000 [00:55<00:36, 21.69it/s]

Epoch 2:  61%|██████    | 1215/2000 [00:56<00:36, 21.68it/s]

Epoch 2:  61%|██████    | 1218/2000 [00:56<00:36, 21.67it/s]

Epoch 2:  61%|██████    | 1221/2000 [00:56<00:35, 21.67it/s]

Epoch 2:  61%|██████    | 1224/2000 [00:56<00:35, 21.67it/s]

Epoch 2:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.66it/s]

Epoch 2:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.67it/s]

Epoch 2:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.67it/s]

Epoch 2:  62%|██████▏   | 1236/2000 [00:57<00:35, 21.68it/s]

Epoch 2:  62%|██████▏   | 1239/2000 [00:57<00:35, 21.68it/s]

Epoch 2:  62%|██████▏   | 1242/2000 [00:57<00:34, 21.68it/s]

Epoch 2:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.67it/s]

Epoch 2:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.66it/s]

Epoch 2:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.67it/s]

Epoch 2:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.69it/s]

Epoch 2:  63%|██████▎   | 1257/2000 [00:58<00:34, 21.68it/s]

Epoch 2:  63%|██████▎   | 1260/2000 [00:58<00:34, 21.68it/s]

Epoch 2:  63%|██████▎   | 1263/2000 [00:58<00:33, 21.68it/s]

Epoch 2:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.68it/s]

Epoch 2:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.68it/s]

Epoch 2:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.70it/s]

Epoch 2:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.70it/s]

Epoch 2:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.69it/s]

Epoch 2:  64%|██████▍   | 1281/2000 [00:59<00:33, 21.69it/s]

Epoch 2:  64%|██████▍   | 1284/2000 [00:59<00:33, 21.69it/s]

Epoch 2:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.68it/s]

Epoch 2:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.68it/s]

Epoch 2:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.67it/s]

Epoch 2:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.66it/s]

Epoch 2:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.67it/s]

Epoch 2:  65%|██████▌   | 1302/2000 [01:00<00:32, 21.68it/s]

Epoch 2:  65%|██████▌   | 1305/2000 [01:00<00:32, 21.69it/s]

Epoch 2:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.70it/s]

Epoch 2:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.69it/s]

Epoch 2:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.70it/s]

Epoch 2:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.71it/s]

Epoch 2:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.70it/s]

Epoch 2:  66%|██████▌   | 1323/2000 [01:01<00:31, 21.69it/s]

Epoch 2:  66%|██████▋   | 1326/2000 [01:01<00:31, 21.68it/s]

Epoch 2:  66%|██████▋   | 1329/2000 [01:01<00:30, 21.69it/s]

Epoch 2:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.70it/s]

Epoch 2:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.71it/s]

Epoch 2:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.72it/s]

Epoch 2:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.70it/s]

Epoch 2:  67%|██████▋   | 1344/2000 [01:02<00:30, 21.70it/s]

Epoch 2:  67%|██████▋   | 1347/2000 [01:02<00:30, 21.69it/s]

Epoch 2:  68%|██████▊   | 1350/2000 [01:02<00:29, 21.68it/s]

Epoch 2:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.68it/s]

Epoch 2:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.68it/s]

Epoch 2:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.69it/s]

Epoch 2:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.68it/s]

Epoch 2:  68%|██████▊   | 1365/2000 [01:03<00:29, 21.68it/s]

Epoch 2:  68%|██████▊   | 1368/2000 [01:03<00:29, 21.69it/s]

Epoch 2:  69%|██████▊   | 1371/2000 [01:03<00:29, 21.69it/s]

Epoch 2:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.70it/s]

Epoch 2:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.68it/s]

Epoch 2:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.68it/s]

Epoch 2:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.67it/s]

Epoch 2:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.66it/s]

Epoch 2:  69%|██████▉   | 1389/2000 [01:04<00:28, 21.67it/s]

Epoch 2:  70%|██████▉   | 1392/2000 [01:04<00:28, 21.67it/s]

Epoch 2:  70%|██████▉   | 1395/2000 [01:04<00:27, 21.68it/s]

Epoch 2:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.68it/s]

Epoch 2:  70%|███████   | 1401/2000 [01:04<00:27, 21.67it/s]

Epoch 2:  70%|███████   | 1404/2000 [01:04<00:27, 21.69it/s]

Epoch 2:  70%|███████   | 1407/2000 [01:04<00:27, 21.67it/s]

Epoch 2:  70%|███████   | 1410/2000 [01:05<00:27, 21.69it/s]

Epoch 2:  71%|███████   | 1413/2000 [01:05<00:27, 21.69it/s]

Epoch 2:  71%|███████   | 1416/2000 [01:05<00:26, 21.69it/s]

Epoch 2:  71%|███████   | 1419/2000 [01:05<00:26, 21.69it/s]

Epoch 2:  71%|███████   | 1422/2000 [01:05<00:26, 21.70it/s]

Epoch 2:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.69it/s]

Epoch 2:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.68it/s]

Epoch 2:  72%|███████▏  | 1431/2000 [01:06<00:26, 21.67it/s]

Epoch 2:  72%|███████▏  | 1434/2000 [01:06<00:26, 21.68it/s]

Epoch 2:  72%|███████▏  | 1437/2000 [01:06<00:25, 21.68it/s]

Epoch 2:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.69it/s]

Epoch 2:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.68it/s]

Epoch 2:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.68it/s]

Epoch 2:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.68it/s]

Epoch 2:  73%|███████▎  | 1452/2000 [01:07<00:25, 21.67it/s]

Epoch 2:  73%|███████▎  | 1455/2000 [01:07<00:25, 21.67it/s]

Epoch 2:  73%|███████▎  | 1458/2000 [01:07<00:24, 21.68it/s]

Epoch 2:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.68it/s]

Epoch 2:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.69it/s]

Epoch 2:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.70it/s]

Epoch 2:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.71it/s]

Epoch 2:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.70it/s]

Epoch 2:  74%|███████▍  | 1476/2000 [01:08<00:24, 21.70it/s]

Epoch 2:  74%|███████▍  | 1479/2000 [01:08<00:24, 21.68it/s]

Epoch 2:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.69it/s]

Epoch 2:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.70it/s]

Epoch 2:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.72it/s]

Epoch 2:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.70it/s]

Epoch 2:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.67it/s]

Epoch 2:  75%|███████▍  | 1497/2000 [01:09<00:23, 21.65it/s]

Epoch 2:  75%|███████▌  | 1500/2000 [01:09<00:23, 21.66it/s]

Epoch 2:  75%|███████▌  | 1503/2000 [01:09<00:22, 21.66it/s]

Epoch 2:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.68it/s]

Epoch 2:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.69it/s]

Epoch 2:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.69it/s]

Epoch 2:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.69it/s]

Epoch 2:  76%|███████▌  | 1518/2000 [01:10<00:22, 21.65it/s]

Epoch 2:  76%|███████▌  | 1521/2000 [01:10<00:22, 21.65it/s]

Epoch 2:  76%|███████▌  | 1524/2000 [01:10<00:21, 21.64it/s]

Epoch 2:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.68it/s]

Epoch 2:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.70it/s]

Epoch 2:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.71it/s]

Epoch 2:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.72it/s]

Epoch 2:  77%|███████▋  | 1539/2000 [01:11<00:21, 21.72it/s]

Epoch 2:  77%|███████▋  | 1542/2000 [01:11<00:21, 21.72it/s]

Epoch 2:  77%|███████▋  | 1545/2000 [01:11<00:20, 21.72it/s]

Epoch 2:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.73it/s]

Epoch 2:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.73it/s]

Epoch 2:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.72it/s]

Epoch 2:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.73it/s]

Epoch 2:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.72it/s]

Epoch 2:  78%|███████▊  | 1563/2000 [01:12<00:20, 21.71it/s]

Epoch 2:  78%|███████▊  | 1566/2000 [01:12<00:19, 21.73it/s]

Epoch 2:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.73it/s]

Epoch 2:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.73it/s]

Epoch 2:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.74it/s]

Epoch 2:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.74it/s]

Epoch 2:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.74it/s]

Epoch 2:  79%|███████▉  | 1584/2000 [01:13<00:19, 21.73it/s]

Epoch 2:  79%|███████▉  | 1587/2000 [01:13<00:19, 21.71it/s]

Epoch 2:  80%|███████▉  | 1590/2000 [01:13<00:18, 21.71it/s]

Epoch 2:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.72it/s]

Epoch 2:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.72it/s]

Epoch 2:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.74it/s]

Epoch 2:  80%|████████  | 1602/2000 [01:13<00:18, 21.74it/s]

Epoch 2:  80%|████████  | 1605/2000 [01:14<00:18, 21.73it/s]

Epoch 2:  80%|████████  | 1608/2000 [01:14<00:18, 21.75it/s]

Epoch 2:  81%|████████  | 1611/2000 [01:14<00:17, 21.75it/s]

Epoch 2:  81%|████████  | 1614/2000 [01:14<00:17, 21.76it/s]

Epoch 2:  81%|████████  | 1617/2000 [01:14<00:17, 21.75it/s]

Epoch 2:  81%|████████  | 1620/2000 [01:14<00:17, 21.76it/s]

Epoch 2:  81%|████████  | 1623/2000 [01:14<00:17, 21.75it/s]

Epoch 2:  81%|████████▏ | 1626/2000 [01:15<00:17, 21.73it/s]

Epoch 2:  81%|████████▏ | 1629/2000 [01:15<00:17, 21.74it/s]

Epoch 2:  82%|████████▏ | 1632/2000 [01:15<00:16, 21.76it/s]

Epoch 2:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.76it/s]

Epoch 2:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.76it/s]

Epoch 2:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.76it/s]

Epoch 2:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.76it/s]

Epoch 2:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.75it/s]

Epoch 2:  82%|████████▎ | 1650/2000 [01:16<00:16, 21.75it/s]

Epoch 2:  83%|████████▎ | 1653/2000 [01:16<00:15, 21.75it/s]

Epoch 2:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.75it/s]

Epoch 2:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.74it/s]

Epoch 2:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.75it/s]

Epoch 2:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.74it/s]

Epoch 2:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.74it/s]

Epoch 2:  84%|████████▎ | 1671/2000 [01:17<00:15, 21.73it/s]

Epoch 2:  84%|████████▎ | 1674/2000 [01:17<00:14, 21.75it/s]

Epoch 2:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.74it/s]

Epoch 2:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.73it/s]

Epoch 2:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.74it/s]

Epoch 2:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.74it/s]

Epoch 2:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.74it/s]

Epoch 2:  85%|████████▍ | 1692/2000 [01:18<00:14, 21.74it/s]

Epoch 2:  85%|████████▍ | 1695/2000 [01:18<00:14, 21.74it/s]

Epoch 2:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.75it/s]

Epoch 2:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.75it/s]

Epoch 2:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.76it/s]

Epoch 2:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.74it/s]

Epoch 2:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.73it/s]

Epoch 2:  86%|████████▌ | 1713/2000 [01:19<00:13, 21.71it/s]

Epoch 2:  86%|████████▌ | 1716/2000 [01:19<00:13, 21.72it/s]

Epoch 2:  86%|████████▌ | 1719/2000 [01:19<00:12, 21.70it/s]

Epoch 2:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.71it/s]

Epoch 2:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.69it/s]

Epoch 2:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.70it/s]

Epoch 2:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.69it/s]

Epoch 2:  87%|████████▋ | 1734/2000 [01:20<00:12, 21.67it/s]

Epoch 2:  87%|████████▋ | 1737/2000 [01:20<00:12, 21.67it/s]

Epoch 2:  87%|████████▋ | 1740/2000 [01:20<00:11, 21.68it/s]

Epoch 2:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.68it/s]

Epoch 2:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.69it/s]

Epoch 2:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.70it/s]

Epoch 2:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.71it/s]

Epoch 2:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.70it/s]

Epoch 2:  88%|████████▊ | 1758/2000 [01:21<00:11, 21.53it/s]

Epoch 2:  88%|████████▊ | 1761/2000 [01:21<00:11, 20.93it/s]

Epoch 2:  88%|████████▊ | 1764/2000 [01:21<00:11, 20.98it/s]

Epoch 2:  88%|████████▊ | 1767/2000 [01:21<00:11, 21.15it/s]

Epoch 2:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.29it/s]

Epoch 2:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.39it/s]

Epoch 2:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.48it/s]

Epoch 2:  89%|████████▉ | 1779/2000 [01:22<00:10, 21.55it/s]

Epoch 2:  89%|████████▉ | 1782/2000 [01:22<00:10, 21.59it/s]

Epoch 2:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.63it/s]

Epoch 2:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.65it/s]

Epoch 2:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.68it/s]

Epoch 2:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.68it/s]

Epoch 2:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.69it/s]

Epoch 2:  90%|█████████ | 1800/2000 [01:23<00:09, 21.67it/s]

Epoch 2:  90%|█████████ | 1803/2000 [01:23<00:09, 21.66it/s]

Epoch 2:  90%|█████████ | 1806/2000 [01:23<00:08, 21.68it/s]

Epoch 2:  90%|█████████ | 1809/2000 [01:23<00:08, 21.69it/s]

Epoch 2:  91%|█████████ | 1812/2000 [01:23<00:08, 21.70it/s]

Epoch 2:  91%|█████████ | 1815/2000 [01:23<00:08, 21.69it/s]

Epoch 2:  91%|█████████ | 1818/2000 [01:23<00:08, 21.70it/s]

Epoch 2:  91%|█████████ | 1821/2000 [01:24<00:08, 21.70it/s]

Epoch 2:  91%|█████████ | 1824/2000 [01:24<00:08, 21.70it/s]

Epoch 2:  91%|█████████▏| 1827/2000 [01:24<00:07, 21.72it/s]

Epoch 2:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.73it/s]

Epoch 2:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.72it/s]

Epoch 2:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.72it/s]

Epoch 2:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.72it/s]

Epoch 2:  92%|█████████▏| 1842/2000 [01:25<00:07, 21.70it/s]

Epoch 2:  92%|█████████▏| 1845/2000 [01:25<00:07, 21.70it/s]

Epoch 2:  92%|█████████▏| 1848/2000 [01:25<00:07, 21.71it/s]

Epoch 2:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.71it/s]

Epoch 2:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.70it/s]

Epoch 2:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.71it/s]

Epoch 2:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.71it/s]

Epoch 2:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.70it/s]

Epoch 2:  93%|█████████▎| 1866/2000 [01:26<00:06, 21.71it/s]

Epoch 2:  93%|█████████▎| 1869/2000 [01:26<00:06, 21.70it/s]

Epoch 2:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.68it/s]

Epoch 2:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.48it/s]

Epoch 2:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.52it/s]

Epoch 2:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.56it/s]

Epoch 2:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.60it/s]

Epoch 2:  94%|█████████▍| 1887/2000 [01:27<00:05, 21.60it/s]

Epoch 2:  94%|█████████▍| 1890/2000 [01:27<00:05, 21.62it/s]

Epoch 2:  95%|█████████▍| 1893/2000 [01:27<00:04, 21.64it/s]

Epoch 2:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.64it/s]

Epoch 2:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.64it/s]

Epoch 2:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.65it/s]

Epoch 2:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.67it/s]

Epoch 2:  95%|█████████▌| 1908/2000 [01:28<00:04, 21.66it/s]

Epoch 2:  96%|█████████▌| 1911/2000 [01:28<00:04, 21.66it/s]

Epoch 2:  96%|█████████▌| 1914/2000 [01:28<00:03, 21.67it/s]

Epoch 2:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.67it/s]

Epoch 2:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.69it/s]

Epoch 2:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.67it/s]

Epoch 2:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.66it/s]

Epoch 2:  96%|█████████▋| 1929/2000 [01:29<00:03, 21.66it/s]

Epoch 2:  97%|█████████▋| 1932/2000 [01:29<00:03, 21.65it/s]

Epoch 2:  97%|█████████▋| 1935/2000 [01:29<00:03, 21.66it/s]

Epoch 2:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.67it/s]

Epoch 2:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.67it/s]

Epoch 2:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.67it/s]

Epoch 2:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.67it/s]

Epoch 2:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.66it/s]

Epoch 2:  98%|█████████▊| 1953/2000 [01:30<00:02, 21.68it/s]

Epoch 2:  98%|█████████▊| 1956/2000 [01:30<00:02, 21.66it/s]

Epoch 2:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.68it/s]

Epoch 2:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.67it/s]

Epoch 2:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.66it/s]

Epoch 2:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.67it/s]

Epoch 2:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.66it/s]

Epoch 2:  99%|█████████▊| 1974/2000 [01:31<00:01, 21.66it/s]

Epoch 2:  99%|█████████▉| 1977/2000 [01:31<00:01, 21.64it/s]

Epoch 2:  99%|█████████▉| 1980/2000 [01:31<00:00, 21.64it/s]

Epoch 2:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.65it/s]

Epoch 2:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.66it/s]

Epoch 2:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.66it/s]

Epoch 2: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.67it/s]

Epoch 2: 100%|█████████▉| 1995/2000 [01:32<00:00, 21.66it/s]

Epoch 2: 100%|█████████▉| 1998/2000 [01:32<00:00, 21.65it/s]

Epoch 2: loss=0.3880, val_proxy=0.5084

Epoch 3:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 3:   0%|          | 3/2000 [00:00<01:32, 21.49it/s]

Epoch 3:   0%|          | 6/2000 [00:00<01:31, 21.69it/s]

Epoch 3:   0%|          | 9/2000 [00:00<01:31, 21.73it/s]

Epoch 3:   1%|          | 12/2000 [00:00<01:31, 21.75it/s]

Epoch 3:   1%|          | 15/2000 [00:00<01:31, 21.76it/s]

Epoch 3:   1%|          | 18/2000 [00:00<01:30, 21.79it/s]

Epoch 3:   1%|          | 21/2000 [00:00<01:30, 21.80it/s]

Epoch 3:   1%|          | 24/2000 [00:01<01:30, 21.80it/s]

Epoch 3:   1%|▏         | 27/2000 [00:01<01:30, 21.81it/s]

Epoch 3:   2%|▏         | 30/2000 [00:01<01:30, 21.83it/s]

Epoch 3:   2%|▏         | 33/2000 [00:01<01:30, 21.83it/s]

Epoch 3:   2%|▏         | 36/2000 [00:01<01:29, 21.83it/s]

Epoch 3:   2%|▏         | 39/2000 [00:01<01:30, 21.72it/s]

Epoch 3:   2%|▏         | 42/2000 [00:01<01:30, 21.73it/s]

Epoch 3:   2%|▏         | 45/2000 [00:02<01:29, 21.78it/s]

Epoch 3:   2%|▏         | 48/2000 [00:02<01:29, 21.81it/s]

Epoch 3:   3%|▎         | 51/2000 [00:02<01:29, 21.82it/s]

Epoch 3:   3%|▎         | 54/2000 [00:02<01:29, 21.83it/s]

Epoch 3:   3%|▎         | 57/2000 [00:02<01:29, 21.82it/s]

Epoch 3:   3%|▎         | 60/2000 [00:02<01:28, 21.83it/s]

Epoch 3:   3%|▎         | 63/2000 [00:02<01:28, 21.84it/s]

Epoch 3:   3%|▎         | 66/2000 [00:03<01:28, 21.84it/s]

Epoch 3:   3%|▎         | 69/2000 [00:03<01:28, 21.84it/s]

Epoch 3:   4%|▎         | 72/2000 [00:03<01:28, 21.85it/s]

Epoch 3:   4%|▍         | 75/2000 [00:03<01:28, 21.86it/s]

Epoch 3:   4%|▍         | 78/2000 [00:03<01:27, 21.86it/s]

Epoch 3:   4%|▍         | 81/2000 [00:03<01:27, 21.86it/s]

Epoch 3:   4%|▍         | 84/2000 [00:03<01:27, 21.86it/s]

Epoch 3:   4%|▍         | 87/2000 [00:03<01:27, 21.84it/s]

Epoch 3:   4%|▍         | 90/2000 [00:04<01:27, 21.83it/s]

Epoch 3:   5%|▍         | 93/2000 [00:04<01:27, 21.83it/s]

Epoch 3:   5%|▍         | 96/2000 [00:04<01:27, 21.83it/s]

Epoch 3:   5%|▍         | 99/2000 [00:04<01:27, 21.84it/s]

Epoch 3:   5%|▌         | 102/2000 [00:04<01:26, 21.83it/s]

Epoch 3:   5%|▌         | 105/2000 [00:04<01:26, 21.83it/s]

Epoch 3:   5%|▌         | 108/2000 [00:04<01:26, 21.85it/s]

Epoch 3:   6%|▌         | 111/2000 [00:05<01:26, 21.85it/s]

Epoch 3:   6%|▌         | 114/2000 [00:05<01:26, 21.84it/s]

Epoch 3:   6%|▌         | 117/2000 [00:05<01:26, 21.85it/s]

Epoch 3:   6%|▌         | 120/2000 [00:05<01:26, 21.84it/s]

Epoch 3:   6%|▌         | 123/2000 [00:05<01:25, 21.85it/s]

Epoch 3:   6%|▋         | 126/2000 [00:05<01:25, 21.84it/s]

Epoch 3:   6%|▋         | 129/2000 [00:05<01:25, 21.83it/s]

Epoch 3:   7%|▋         | 132/2000 [00:06<01:25, 21.83it/s]

Epoch 3:   7%|▋         | 135/2000 [00:06<01:25, 21.85it/s]

Epoch 3:   7%|▋         | 138/2000 [00:06<01:25, 21.83it/s]

Epoch 3:   7%|▋         | 141/2000 [00:06<01:25, 21.84it/s]

Epoch 3:   7%|▋         | 144/2000 [00:06<01:25, 21.83it/s]

Epoch 3:   7%|▋         | 147/2000 [00:06<01:24, 21.84it/s]

Epoch 3:   8%|▊         | 150/2000 [00:06<01:24, 21.85it/s]

Epoch 3:   8%|▊         | 153/2000 [00:07<01:24, 21.85it/s]

Epoch 3:   8%|▊         | 156/2000 [00:07<01:24, 21.84it/s]

Epoch 3:   8%|▊         | 159/2000 [00:07<01:24, 21.85it/s]

Epoch 3:   8%|▊         | 162/2000 [00:07<01:24, 21.86it/s]

Epoch 3:   8%|▊         | 165/2000 [00:07<01:23, 21.86it/s]

Epoch 3:   8%|▊         | 168/2000 [00:07<01:23, 21.87it/s]

Epoch 3:   9%|▊         | 171/2000 [00:07<01:23, 21.86it/s]

Epoch 3:   9%|▊         | 174/2000 [00:07<01:23, 21.86it/s]

Epoch 3:   9%|▉         | 177/2000 [00:08<01:23, 21.86it/s]

Epoch 3:   9%|▉         | 180/2000 [00:08<01:23, 21.86it/s]

Epoch 3:   9%|▉         | 183/2000 [00:08<01:23, 21.85it/s]

Epoch 3:   9%|▉         | 186/2000 [00:08<01:23, 21.84it/s]

Epoch 3:   9%|▉         | 189/2000 [00:08<01:22, 21.84it/s]

Epoch 3:  10%|▉         | 192/2000 [00:08<01:22, 21.83it/s]

Epoch 3:  10%|▉         | 195/2000 [00:08<01:22, 21.84it/s]

Epoch 3:  10%|▉         | 198/2000 [00:09<01:22, 21.85it/s]

Epoch 3:  10%|█         | 201/2000 [00:09<01:22, 21.86it/s]

Epoch 3:  10%|█         | 204/2000 [00:09<01:22, 21.85it/s]

Epoch 3:  10%|█         | 207/2000 [00:09<01:22, 21.85it/s]

Epoch 3:  10%|█         | 210/2000 [00:09<01:21, 21.86it/s]

Epoch 3:  11%|█         | 213/2000 [00:09<01:21, 21.85it/s]

Epoch 3:  11%|█         | 216/2000 [00:09<01:21, 21.85it/s]

Epoch 3:  11%|█         | 219/2000 [00:10<01:21, 21.86it/s]

Epoch 3:  11%|█         | 222/2000 [00:10<01:21, 21.84it/s]

Epoch 3:  11%|█▏        | 225/2000 [00:10<01:21, 21.85it/s]

Epoch 3:  11%|█▏        | 228/2000 [00:10<01:21, 21.85it/s]

Epoch 3:  12%|█▏        | 231/2000 [00:10<01:21, 21.84it/s]

Epoch 3:  12%|█▏        | 234/2000 [00:10<01:20, 21.82it/s]

Epoch 3:  12%|█▏        | 237/2000 [00:10<01:20, 21.84it/s]

Epoch 3:  12%|█▏        | 240/2000 [00:10<01:20, 21.84it/s]

Epoch 3:  12%|█▏        | 243/2000 [00:11<01:20, 21.86it/s]

Epoch 3:  12%|█▏        | 246/2000 [00:11<01:20, 21.86it/s]

Epoch 3:  12%|█▏        | 249/2000 [00:11<01:20, 21.84it/s]

Epoch 3:  13%|█▎        | 252/2000 [00:11<01:20, 21.84it/s]

Epoch 3:  13%|█▎        | 255/2000 [00:11<01:19, 21.84it/s]

Epoch 3:  13%|█▎        | 258/2000 [00:11<01:19, 21.86it/s]

Epoch 3:  13%|█▎        | 261/2000 [00:11<01:19, 21.85it/s]

Epoch 3:  13%|█▎        | 264/2000 [00:12<01:19, 21.84it/s]

Epoch 3:  13%|█▎        | 267/2000 [00:12<01:19, 21.85it/s]

Epoch 3:  14%|█▎        | 270/2000 [00:12<01:19, 21.85it/s]

Epoch 3:  14%|█▎        | 273/2000 [00:12<01:19, 21.86it/s]

Epoch 3:  14%|█▍        | 276/2000 [00:12<01:18, 21.85it/s]

Epoch 3:  14%|█▍        | 279/2000 [00:12<01:18, 21.84it/s]

Epoch 3:  14%|█▍        | 282/2000 [00:12<01:18, 21.84it/s]

Epoch 3:  14%|█▍        | 285/2000 [00:13<01:18, 21.85it/s]

Epoch 3:  14%|█▍        | 288/2000 [00:13<01:18, 21.83it/s]

Epoch 3:  15%|█▍        | 291/2000 [00:13<01:18, 21.83it/s]

Epoch 3:  15%|█▍        | 294/2000 [00:13<01:18, 21.84it/s]

Epoch 3:  15%|█▍        | 297/2000 [00:13<01:17, 21.85it/s]

Epoch 3:  15%|█▌        | 300/2000 [00:13<01:17, 21.85it/s]

Epoch 3:  15%|█▌        | 303/2000 [00:13<01:17, 21.85it/s]

Epoch 3:  15%|█▌        | 306/2000 [00:14<01:17, 21.85it/s]

Epoch 3:  15%|█▌        | 309/2000 [00:14<01:17, 21.85it/s]

Epoch 3:  16%|█▌        | 312/2000 [00:14<01:17, 21.85it/s]

Epoch 3:  16%|█▌        | 315/2000 [00:14<01:17, 21.86it/s]

Epoch 3:  16%|█▌        | 318/2000 [00:14<01:16, 21.85it/s]

Epoch 3:  16%|█▌        | 321/2000 [00:14<01:16, 21.84it/s]

Epoch 3:  16%|█▌        | 324/2000 [00:14<01:16, 21.85it/s]

Epoch 3:  16%|█▋        | 327/2000 [00:14<01:16, 21.86it/s]

Epoch 3:  16%|█▋        | 330/2000 [00:15<01:16, 21.86it/s]

Epoch 3:  17%|█▋        | 333/2000 [00:15<01:16, 21.86it/s]

Epoch 3:  17%|█▋        | 336/2000 [00:15<01:16, 21.86it/s]

Epoch 3:  17%|█▋        | 339/2000 [00:15<01:15, 21.86it/s]

Epoch 3:  17%|█▋        | 342/2000 [00:15<01:15, 21.85it/s]

Epoch 3:  17%|█▋        | 345/2000 [00:15<01:15, 21.85it/s]

Epoch 3:  17%|█▋        | 348/2000 [00:15<01:15, 21.87it/s]

Epoch 3:  18%|█▊        | 351/2000 [00:16<01:15, 21.86it/s]

Epoch 3:  18%|█▊        | 354/2000 [00:16<01:15, 21.84it/s]

Epoch 3:  18%|█▊        | 357/2000 [00:16<01:16, 21.58it/s]

Epoch 3:  18%|█▊        | 360/2000 [00:16<01:18, 20.97it/s]

Epoch 3:  18%|█▊        | 363/2000 [00:16<01:17, 21.14it/s]

Epoch 3:  18%|█▊        | 366/2000 [00:16<01:16, 21.27it/s]

Epoch 3:  18%|█▊        | 369/2000 [00:16<01:16, 21.42it/s]

Epoch 3:  19%|█▊        | 372/2000 [00:17<01:15, 21.54it/s]

Epoch 3:  19%|█▉        | 375/2000 [00:17<01:15, 21.62it/s]

Epoch 3:  19%|█▉        | 378/2000 [00:17<01:14, 21.69it/s]

Epoch 3:  19%|█▉        | 381/2000 [00:17<01:14, 21.75it/s]

Epoch 3:  19%|█▉        | 384/2000 [00:17<01:14, 21.78it/s]

Epoch 3:  19%|█▉        | 387/2000 [00:17<01:13, 21.80it/s]

Epoch 3:  20%|█▉        | 390/2000 [00:17<01:13, 21.82it/s]

Epoch 3:  20%|█▉        | 393/2000 [00:18<01:13, 21.83it/s]

Epoch 3:  20%|█▉        | 396/2000 [00:18<01:13, 21.84it/s]

Epoch 3:  20%|█▉        | 399/2000 [00:18<01:13, 21.84it/s]

Epoch 3:  20%|██        | 402/2000 [00:18<01:13, 21.85it/s]

Epoch 3:  20%|██        | 405/2000 [00:18<01:13, 21.85it/s]

Epoch 3:  20%|██        | 408/2000 [00:18<01:12, 21.85it/s]

Epoch 3:  21%|██        | 411/2000 [00:18<01:12, 21.82it/s]

Epoch 3:  21%|██        | 414/2000 [00:18<01:12, 21.82it/s]

Epoch 3:  21%|██        | 417/2000 [00:19<01:12, 21.83it/s]

Epoch 3:  21%|██        | 420/2000 [00:19<01:12, 21.84it/s]

Epoch 3:  21%|██        | 423/2000 [00:19<01:12, 21.84it/s]

Epoch 3:  21%|██▏       | 426/2000 [00:19<01:12, 21.84it/s]

Epoch 3:  21%|██▏       | 429/2000 [00:19<01:11, 21.82it/s]

Epoch 3:  22%|██▏       | 432/2000 [00:19<01:11, 21.84it/s]

Epoch 3:  22%|██▏       | 435/2000 [00:19<01:11, 21.83it/s]

Epoch 3:  22%|██▏       | 438/2000 [00:20<01:11, 21.84it/s]

Epoch 3:  22%|██▏       | 441/2000 [00:20<01:11, 21.84it/s]

Epoch 3:  22%|██▏       | 444/2000 [00:20<01:11, 21.84it/s]

Epoch 3:  22%|██▏       | 447/2000 [00:20<01:11, 21.84it/s]

Epoch 3:  22%|██▎       | 450/2000 [00:20<01:10, 21.86it/s]

Epoch 3:  23%|██▎       | 453/2000 [00:20<01:10, 21.84it/s]

Epoch 3:  23%|██▎       | 456/2000 [00:20<01:10, 21.82it/s]

Epoch 3:  23%|██▎       | 459/2000 [00:21<01:10, 21.83it/s]

Epoch 3:  23%|██▎       | 462/2000 [00:21<01:10, 21.85it/s]

Epoch 3:  23%|██▎       | 465/2000 [00:21<01:10, 21.86it/s]

Epoch 3:  23%|██▎       | 468/2000 [00:21<01:10, 21.86it/s]

Epoch 3:  24%|██▎       | 471/2000 [00:21<01:09, 21.86it/s]

Epoch 3:  24%|██▎       | 474/2000 [00:21<01:09, 21.87it/s]

Epoch 3:  24%|██▍       | 477/2000 [00:21<01:09, 21.88it/s]

Epoch 3:  24%|██▍       | 480/2000 [00:22<01:09, 21.86it/s]

Epoch 3:  24%|██▍       | 483/2000 [00:22<01:09, 21.85it/s]

Epoch 3:  24%|██▍       | 486/2000 [00:22<01:09, 21.87it/s]

Epoch 3:  24%|██▍       | 489/2000 [00:22<01:09, 21.87it/s]

Epoch 3:  25%|██▍       | 492/2000 [00:22<01:08, 21.86it/s]

Epoch 3:  25%|██▍       | 495/2000 [00:22<01:08, 21.86it/s]

Epoch 3:  25%|██▍       | 498/2000 [00:22<01:08, 21.86it/s]

Epoch 3:  25%|██▌       | 501/2000 [00:22<01:08, 21.86it/s]

Epoch 3:  25%|██▌       | 504/2000 [00:23<01:08, 21.85it/s]

Epoch 3:  25%|██▌       | 507/2000 [00:23<01:08, 21.84it/s]

Epoch 3:  26%|██▌       | 510/2000 [00:23<01:08, 21.85it/s]

Epoch 3:  26%|██▌       | 513/2000 [00:23<01:08, 21.86it/s]

Epoch 3:  26%|██▌       | 516/2000 [00:23<01:07, 21.86it/s]

Epoch 3:  26%|██▌       | 519/2000 [00:23<01:07, 21.85it/s]

Epoch 3:  26%|██▌       | 522/2000 [00:23<01:07, 21.84it/s]

Epoch 3:  26%|██▋       | 525/2000 [00:24<01:07, 21.84it/s]

Epoch 3:  26%|██▋       | 528/2000 [00:24<01:07, 21.86it/s]

Epoch 3:  27%|██▋       | 531/2000 [00:24<01:07, 21.87it/s]

Epoch 3:  27%|██▋       | 534/2000 [00:24<01:07, 21.86it/s]

Epoch 3:  27%|██▋       | 537/2000 [00:24<01:06, 21.86it/s]

Epoch 3:  27%|██▋       | 540/2000 [00:24<01:06, 21.85it/s]

Epoch 3:  27%|██▋       | 543/2000 [00:24<01:06, 21.86it/s]

Epoch 3:  27%|██▋       | 546/2000 [00:25<01:06, 21.85it/s]

Epoch 3:  27%|██▋       | 549/2000 [00:25<01:06, 21.86it/s]

Epoch 3:  28%|██▊       | 552/2000 [00:25<01:06, 21.86it/s]

Epoch 3:  28%|██▊       | 555/2000 [00:25<01:06, 21.88it/s]

Epoch 3:  28%|██▊       | 558/2000 [00:25<01:05, 21.87it/s]

Epoch 3:  28%|██▊       | 561/2000 [00:25<01:05, 21.85it/s]

Epoch 3:  28%|██▊       | 564/2000 [00:25<01:05, 21.86it/s]

Epoch 3:  28%|██▊       | 567/2000 [00:25<01:05, 21.85it/s]

Epoch 3:  28%|██▊       | 570/2000 [00:26<01:05, 21.86it/s]

Epoch 3:  29%|██▊       | 573/2000 [00:26<01:05, 21.85it/s]

Epoch 3:  29%|██▉       | 576/2000 [00:26<01:05, 21.85it/s]

Epoch 3:  29%|██▉       | 579/2000 [00:26<01:05, 21.86it/s]

Epoch 3:  29%|██▉       | 582/2000 [00:26<01:04, 21.85it/s]

Epoch 3:  29%|██▉       | 585/2000 [00:26<01:04, 21.83it/s]

Epoch 3:  29%|██▉       | 588/2000 [00:26<01:04, 21.83it/s]

Epoch 3:  30%|██▉       | 591/2000 [00:27<01:04, 21.84it/s]

Epoch 3:  30%|██▉       | 594/2000 [00:27<01:04, 21.84it/s]

Epoch 3:  30%|██▉       | 597/2000 [00:27<01:04, 21.85it/s]

Epoch 3:  30%|███       | 600/2000 [00:27<01:04, 21.86it/s]

Epoch 3:  30%|███       | 603/2000 [00:27<01:03, 21.86it/s]

Epoch 3:  30%|███       | 606/2000 [00:27<01:03, 21.85it/s]

Epoch 3:  30%|███       | 609/2000 [00:27<01:03, 21.84it/s]

Epoch 3:  31%|███       | 612/2000 [00:28<01:03, 21.84it/s]

Epoch 3:  31%|███       | 615/2000 [00:28<01:03, 21.85it/s]

Epoch 3:  31%|███       | 618/2000 [00:28<01:03, 21.85it/s]

Epoch 3:  31%|███       | 621/2000 [00:28<01:03, 21.86it/s]

Epoch 3:  31%|███       | 624/2000 [00:28<01:02, 21.87it/s]

Epoch 3:  31%|███▏      | 627/2000 [00:28<01:02, 21.86it/s]

Epoch 3:  32%|███▏      | 630/2000 [00:28<01:02, 21.85it/s]

Epoch 3:  32%|███▏      | 633/2000 [00:29<01:02, 21.85it/s]

Epoch 3:  32%|███▏      | 636/2000 [00:29<01:02, 21.86it/s]

Epoch 3:  32%|███▏      | 639/2000 [00:29<01:02, 21.88it/s]

Epoch 3:  32%|███▏      | 642/2000 [00:29<01:02, 21.87it/s]

Epoch 3:  32%|███▏      | 645/2000 [00:29<01:01, 21.86it/s]

Epoch 3:  32%|███▏      | 648/2000 [00:29<01:01, 21.86it/s]

Epoch 3:  33%|███▎      | 651/2000 [00:29<01:01, 21.85it/s]

Epoch 3:  33%|███▎      | 654/2000 [00:29<01:01, 21.84it/s]

Epoch 3:  33%|███▎      | 657/2000 [00:30<01:01, 21.85it/s]

Epoch 3:  33%|███▎      | 660/2000 [00:30<01:01, 21.85it/s]

Epoch 3:  33%|███▎      | 663/2000 [00:30<01:01, 21.85it/s]

Epoch 3:  33%|███▎      | 666/2000 [00:30<01:01, 21.86it/s]

Epoch 3:  33%|███▎      | 669/2000 [00:30<01:00, 21.84it/s]

Epoch 3:  34%|███▎      | 672/2000 [00:30<01:00, 21.83it/s]

Epoch 3:  34%|███▍      | 675/2000 [00:30<01:00, 21.84it/s]

Epoch 3:  34%|███▍      | 678/2000 [00:31<01:00, 21.85it/s]

Epoch 3:  34%|███▍      | 681/2000 [00:31<01:00, 21.84it/s]

Epoch 3:  34%|███▍      | 684/2000 [00:31<01:00, 21.85it/s]

Epoch 3:  34%|███▍      | 687/2000 [00:31<01:00, 21.85it/s]

Epoch 3:  34%|███▍      | 690/2000 [00:31<00:59, 21.85it/s]

Epoch 3:  35%|███▍      | 693/2000 [00:31<00:59, 21.85it/s]

Epoch 3:  35%|███▍      | 696/2000 [00:31<00:59, 21.86it/s]

Epoch 3:  35%|███▍      | 699/2000 [00:32<00:59, 21.86it/s]

Epoch 3:  35%|███▌      | 702/2000 [00:32<00:59, 21.86it/s]

Epoch 3:  35%|███▌      | 705/2000 [00:32<00:59, 21.85it/s]

Epoch 3:  35%|███▌      | 708/2000 [00:32<00:59, 21.85it/s]

Epoch 3:  36%|███▌      | 711/2000 [00:32<00:58, 21.85it/s]

Epoch 3:  36%|███▌      | 714/2000 [00:32<00:58, 21.85it/s]

Epoch 3:  36%|███▌      | 717/2000 [00:32<00:58, 21.84it/s]

Epoch 3:  36%|███▌      | 720/2000 [00:32<00:58, 21.84it/s]

Epoch 3:  36%|███▌      | 723/2000 [00:33<00:58, 21.84it/s]

Epoch 3:  36%|███▋      | 726/2000 [00:33<00:58, 21.85it/s]

Epoch 3:  36%|███▋      | 729/2000 [00:33<00:58, 21.86it/s]

Epoch 3:  37%|███▋      | 732/2000 [00:33<00:57, 21.87it/s]

Epoch 3:  37%|███▋      | 735/2000 [00:33<00:57, 21.87it/s]

Epoch 3:  37%|███▋      | 738/2000 [00:33<00:57, 21.86it/s]

Epoch 3:  37%|███▋      | 741/2000 [00:33<00:57, 21.86it/s]

Epoch 3:  37%|███▋      | 744/2000 [00:34<00:57, 21.86it/s]

Epoch 3:  37%|███▋      | 747/2000 [00:34<00:57, 21.88it/s]

Epoch 3:  38%|███▊      | 750/2000 [00:34<00:57, 21.87it/s]

Epoch 3:  38%|███▊      | 753/2000 [00:34<00:56, 21.88it/s]

Epoch 3:  38%|███▊      | 756/2000 [00:34<00:56, 21.87it/s]

Epoch 3:  38%|███▊      | 759/2000 [00:34<00:56, 21.85it/s]

Epoch 3:  38%|███▊      | 762/2000 [00:34<00:56, 21.85it/s]

Epoch 3:  38%|███▊      | 765/2000 [00:35<00:56, 21.84it/s]

Epoch 3:  38%|███▊      | 768/2000 [00:35<00:56, 21.84it/s]

Epoch 3:  39%|███▊      | 771/2000 [00:35<00:56, 21.84it/s]

Epoch 3:  39%|███▊      | 774/2000 [00:35<00:56, 21.84it/s]

Epoch 3:  39%|███▉      | 777/2000 [00:35<00:56, 21.83it/s]

Epoch 3:  39%|███▉      | 780/2000 [00:35<00:55, 21.83it/s]

Epoch 3:  39%|███▉      | 783/2000 [00:35<00:55, 21.82it/s]

Epoch 3:  39%|███▉      | 786/2000 [00:36<00:55, 21.84it/s]

Epoch 3:  39%|███▉      | 789/2000 [00:36<00:55, 21.83it/s]

Epoch 3:  40%|███▉      | 792/2000 [00:36<00:55, 21.83it/s]

Epoch 3:  40%|███▉      | 795/2000 [00:36<00:55, 21.85it/s]

Epoch 3:  40%|███▉      | 798/2000 [00:36<00:55, 21.85it/s]

Epoch 3:  40%|████      | 801/2000 [00:36<00:54, 21.85it/s]

Epoch 3:  40%|████      | 804/2000 [00:36<00:54, 21.85it/s]

Epoch 3:  40%|████      | 807/2000 [00:36<00:54, 21.84it/s]

Epoch 3:  40%|████      | 810/2000 [00:37<00:54, 21.85it/s]

Epoch 3:  41%|████      | 813/2000 [00:37<00:54, 21.85it/s]

Epoch 3:  41%|████      | 816/2000 [00:37<00:54, 21.86it/s]

Epoch 3:  41%|████      | 819/2000 [00:37<00:54, 21.84it/s]

Epoch 3:  41%|████      | 822/2000 [00:37<00:53, 21.85it/s]

Epoch 3:  41%|████▏     | 825/2000 [00:37<00:53, 21.85it/s]

Epoch 3:  41%|████▏     | 828/2000 [00:37<00:53, 21.85it/s]

Epoch 3:  42%|████▏     | 831/2000 [00:38<00:53, 21.85it/s]

Epoch 3:  42%|████▏     | 834/2000 [00:38<00:53, 21.86it/s]

Epoch 3:  42%|████▏     | 837/2000 [00:38<00:53, 21.85it/s]

Epoch 3:  42%|████▏     | 840/2000 [00:38<00:53, 21.86it/s]

Epoch 3:  42%|████▏     | 843/2000 [00:38<00:52, 21.84it/s]

Epoch 3:  42%|████▏     | 846/2000 [00:38<00:52, 21.84it/s]

Epoch 3:  42%|████▏     | 849/2000 [00:38<00:52, 21.84it/s]

Epoch 3:  43%|████▎     | 852/2000 [00:39<00:52, 21.84it/s]

Epoch 3:  43%|████▎     | 855/2000 [00:39<00:52, 21.83it/s]

Epoch 3:  43%|████▎     | 858/2000 [00:39<00:52, 21.83it/s]

Epoch 3:  43%|████▎     | 861/2000 [00:39<00:52, 21.84it/s]

Epoch 3:  43%|████▎     | 864/2000 [00:39<00:52, 21.83it/s]

Epoch 3:  43%|████▎     | 867/2000 [00:39<00:51, 21.84it/s]

Epoch 3:  44%|████▎     | 870/2000 [00:39<00:51, 21.83it/s]

Epoch 3:  44%|████▎     | 873/2000 [00:39<00:51, 21.83it/s]

Epoch 3:  44%|████▍     | 876/2000 [00:40<00:51, 21.84it/s]

Epoch 3:  44%|████▍     | 879/2000 [00:40<00:51, 21.83it/s]

Epoch 3:  44%|████▍     | 882/2000 [00:40<00:51, 21.84it/s]

Epoch 3:  44%|████▍     | 885/2000 [00:40<00:51, 21.84it/s]

Epoch 3:  44%|████▍     | 888/2000 [00:40<00:50, 21.82it/s]

Epoch 3:  45%|████▍     | 891/2000 [00:40<00:50, 21.83it/s]

Epoch 3:  45%|████▍     | 894/2000 [00:40<00:50, 21.83it/s]

Epoch 3:  45%|████▍     | 897/2000 [00:41<00:50, 21.85it/s]

Epoch 3:  45%|████▌     | 900/2000 [00:41<00:50, 21.85it/s]

Epoch 3:  45%|████▌     | 903/2000 [00:41<00:50, 21.84it/s]

Epoch 3:  45%|████▌     | 906/2000 [00:41<00:50, 21.85it/s]

Epoch 3:  45%|████▌     | 909/2000 [00:41<00:49, 21.85it/s]

Epoch 3:  46%|████▌     | 912/2000 [00:41<00:49, 21.85it/s]

Epoch 3:  46%|████▌     | 915/2000 [00:41<00:49, 21.85it/s]

Epoch 3:  46%|████▌     | 918/2000 [00:42<00:49, 21.84it/s]

Epoch 3:  46%|████▌     | 921/2000 [00:42<00:49, 21.85it/s]

Epoch 3:  46%|████▌     | 924/2000 [00:42<00:49, 21.84it/s]

Epoch 3:  46%|████▋     | 927/2000 [00:42<00:49, 21.84it/s]

Epoch 3:  46%|████▋     | 930/2000 [00:42<00:48, 21.85it/s]

Epoch 3:  47%|████▋     | 933/2000 [00:42<00:48, 21.85it/s]

Epoch 3:  47%|████▋     | 936/2000 [00:42<00:48, 21.82it/s]

Epoch 3:  47%|████▋     | 939/2000 [00:43<00:48, 21.82it/s]

Epoch 3:  47%|████▋     | 942/2000 [00:43<00:48, 21.84it/s]

Epoch 3:  47%|████▋     | 945/2000 [00:43<00:48, 21.85it/s]

Epoch 3:  47%|████▋     | 948/2000 [00:43<00:48, 21.83it/s]

Epoch 3:  48%|████▊     | 951/2000 [00:43<00:48, 21.82it/s]

Epoch 3:  48%|████▊     | 954/2000 [00:43<00:47, 21.83it/s]

Epoch 3:  48%|████▊     | 957/2000 [00:43<00:47, 21.80it/s]

Epoch 3:  48%|████▊     | 960/2000 [00:43<00:47, 21.81it/s]

Epoch 3:  48%|████▊     | 963/2000 [00:44<00:47, 21.82it/s]

Epoch 3:  48%|████▊     | 966/2000 [00:44<00:47, 21.81it/s]

Epoch 3:  48%|████▊     | 969/2000 [00:44<00:47, 21.82it/s]

Epoch 3:  49%|████▊     | 972/2000 [00:44<00:47, 21.83it/s]

Epoch 3:  49%|████▉     | 975/2000 [00:44<00:46, 21.82it/s]

Epoch 3:  49%|████▉     | 978/2000 [00:44<00:46, 21.83it/s]

Epoch 3:  49%|████▉     | 981/2000 [00:44<00:46, 21.82it/s]

Epoch 3:  49%|████▉     | 984/2000 [00:45<00:46, 21.82it/s]

Epoch 3:  49%|████▉     | 987/2000 [00:45<00:46, 21.81it/s]

Epoch 3:  50%|████▉     | 990/2000 [00:45<00:46, 21.83it/s]

Epoch 3:  50%|████▉     | 993/2000 [00:45<00:46, 21.83it/s]

Epoch 3:  50%|████▉     | 996/2000 [00:45<00:45, 21.85it/s]

Epoch 3:  50%|████▉     | 999/2000 [00:45<00:45, 21.84it/s]

Epoch 3:  50%|█████     | 1002/2000 [00:45<00:45, 21.84it/s]

Epoch 3:  50%|█████     | 1005/2000 [00:46<00:45, 21.83it/s]

Epoch 3:  50%|█████     | 1008/2000 [00:46<00:45, 21.84it/s]

Epoch 3:  51%|█████     | 1011/2000 [00:46<00:45, 21.85it/s]

Epoch 3:  51%|█████     | 1014/2000 [00:46<00:45, 21.85it/s]

Epoch 3:  51%|█████     | 1017/2000 [00:46<00:44, 21.85it/s]

Epoch 3:  51%|█████     | 1020/2000 [00:46<00:44, 21.85it/s]

Epoch 3:  51%|█████     | 1023/2000 [00:46<00:44, 21.84it/s]

Epoch 3:  51%|█████▏    | 1026/2000 [00:46<00:44, 21.85it/s]

Epoch 3:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.85it/s]

Epoch 3:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.84it/s]

Epoch 3:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.86it/s]

Epoch 3:  52%|█████▏    | 1038/2000 [00:47<00:43, 21.87it/s]

Epoch 3:  52%|█████▏    | 1041/2000 [00:47<00:43, 21.86it/s]

Epoch 3:  52%|█████▏    | 1044/2000 [00:47<00:43, 21.85it/s]

Epoch 3:  52%|█████▏    | 1047/2000 [00:47<00:43, 21.86it/s]

Epoch 3:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.85it/s]

Epoch 3:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.86it/s]

Epoch 3:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.87it/s]

Epoch 3:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.85it/s]

Epoch 3:  53%|█████▎    | 1062/2000 [00:48<00:42, 21.84it/s]

Epoch 3:  53%|█████▎    | 1065/2000 [00:48<00:42, 21.84it/s]

Epoch 3:  53%|█████▎    | 1068/2000 [00:48<00:42, 21.83it/s]

Epoch 3:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.82it/s]

Epoch 3:  54%|█████▎    | 1074/2000 [00:49<00:43, 21.17it/s]

Epoch 3:  54%|█████▍    | 1077/2000 [00:49<00:43, 21.10it/s]

Epoch 3:  54%|█████▍    | 1080/2000 [00:49<00:43, 21.27it/s]

Epoch 3:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.37it/s]

Epoch 3:  54%|█████▍    | 1086/2000 [00:49<00:42, 21.50it/s]

Epoch 3:  54%|█████▍    | 1089/2000 [00:49<00:42, 21.60it/s]

Epoch 3:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.68it/s]

Epoch 3:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.56it/s]

Epoch 3:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.63it/s]

Epoch 3:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.67it/s]

Epoch 3:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.72it/s]

Epoch 3:  55%|█████▌    | 1107/2000 [00:50<00:41, 21.76it/s]

Epoch 3:  56%|█████▌    | 1110/2000 [00:50<00:40, 21.78it/s]

Epoch 3:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.81it/s]

Epoch 3:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.81it/s]

Epoch 3:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.81it/s]

Epoch 3:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.82it/s]

Epoch 3:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.83it/s]

Epoch 3:  56%|█████▋    | 1128/2000 [00:51<00:39, 21.82it/s]

Epoch 3:  57%|█████▋    | 1131/2000 [00:51<00:39, 21.85it/s]

Epoch 3:  57%|█████▋    | 1134/2000 [00:51<00:39, 21.84it/s]

Epoch 3:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.82it/s]

Epoch 3:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.81it/s]

Epoch 3:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.80it/s]

Epoch 3:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.83it/s]

Epoch 3:  57%|█████▋    | 1149/2000 [00:52<00:39, 21.82it/s]

Epoch 3:  58%|█████▊    | 1152/2000 [00:52<00:38, 21.82it/s]

Epoch 3:  58%|█████▊    | 1155/2000 [00:52<00:38, 21.82it/s]

Epoch 3:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.83it/s]

Epoch 3:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.83it/s]

Epoch 3:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.84it/s]

Epoch 3:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.85it/s]

Epoch 3:  58%|█████▊    | 1170/2000 [00:53<00:37, 21.86it/s]

Epoch 3:  59%|█████▊    | 1173/2000 [00:53<00:37, 21.86it/s]

Epoch 3:  59%|█████▉    | 1176/2000 [00:53<00:37, 21.86it/s]

Epoch 3:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.85it/s]

Epoch 3:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.84it/s]

Epoch 3:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.85it/s]

Epoch 3:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.80it/s]

Epoch 3:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.80it/s]

Epoch 3:  60%|█████▉    | 1194/2000 [00:54<00:36, 21.80it/s]

Epoch 3:  60%|█████▉    | 1197/2000 [00:54<00:36, 21.79it/s]

Epoch 3:  60%|██████    | 1200/2000 [00:54<00:36, 21.79it/s]

Epoch 3:  60%|██████    | 1203/2000 [00:55<00:36, 21.80it/s]

Epoch 3:  60%|██████    | 1206/2000 [00:55<00:36, 21.80it/s]

Epoch 3:  60%|██████    | 1209/2000 [00:55<00:36, 21.79it/s]

Epoch 3:  61%|██████    | 1212/2000 [00:55<00:36, 21.56it/s]

Epoch 3:  61%|██████    | 1215/2000 [00:55<00:36, 21.58it/s]

Epoch 3:  61%|██████    | 1218/2000 [00:55<00:36, 21.60it/s]

Epoch 3:  61%|██████    | 1221/2000 [00:55<00:36, 21.61it/s]

Epoch 3:  61%|██████    | 1224/2000 [00:56<00:36, 21.42it/s]

Epoch 3:  61%|██████▏   | 1227/2000 [00:56<00:36, 21.47it/s]

Epoch 3:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.52it/s]

Epoch 3:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.57it/s]

Epoch 3:  62%|██████▏   | 1236/2000 [00:56<00:35, 21.36it/s]

Epoch 3:  62%|██████▏   | 1239/2000 [00:56<00:35, 21.49it/s]

Epoch 3:  62%|██████▏   | 1242/2000 [00:56<00:35, 21.59it/s]

Epoch 3:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.66it/s]

Epoch 3:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.70it/s]

Epoch 3:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.71it/s]

Epoch 3:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.71it/s]

Epoch 3:  63%|██████▎   | 1257/2000 [00:57<00:34, 21.71it/s]

Epoch 3:  63%|██████▎   | 1260/2000 [00:57<00:34, 21.70it/s]

Epoch 3:  63%|██████▎   | 1263/2000 [00:57<00:33, 21.72it/s]

Epoch 3:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.72it/s]

Epoch 3:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.73it/s]

Epoch 3:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.74it/s]

Epoch 3:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.73it/s]

Epoch 3:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.73it/s]

Epoch 3:  64%|██████▍   | 1281/2000 [00:58<00:33, 21.71it/s]

Epoch 3:  64%|██████▍   | 1284/2000 [00:58<00:32, 21.71it/s]

Epoch 3:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.71it/s]

Epoch 3:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.72it/s]

Epoch 3:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.71it/s]

Epoch 3:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.72it/s]

Epoch 3:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.72it/s]

Epoch 3:  65%|██████▌   | 1302/2000 [00:59<00:32, 21.73it/s]

Epoch 3:  65%|██████▌   | 1305/2000 [00:59<00:31, 21.73it/s]

Epoch 3:  65%|██████▌   | 1308/2000 [00:59<00:31, 21.74it/s]

Epoch 3:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.74it/s]

Epoch 3:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.74it/s]

Epoch 3:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.73it/s]

Epoch 3:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.74it/s]

Epoch 3:  66%|██████▌   | 1323/2000 [01:00<00:31, 21.71it/s]

Epoch 3:  66%|██████▋   | 1326/2000 [01:00<00:31, 21.72it/s]

Epoch 3:  66%|██████▋   | 1329/2000 [01:00<00:30, 21.74it/s]

Epoch 3:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.75it/s]

Epoch 3:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.74it/s]

Epoch 3:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.74it/s]

Epoch 3:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.74it/s]

Epoch 3:  67%|██████▋   | 1344/2000 [01:01<00:30, 21.74it/s]

Epoch 3:  67%|██████▋   | 1347/2000 [01:01<00:30, 21.72it/s]

Epoch 3:  68%|██████▊   | 1350/2000 [01:01<00:29, 21.74it/s]

Epoch 3:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.73it/s]

Epoch 3:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.73it/s]

Epoch 3:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.73it/s]

Epoch 3:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.74it/s]

Epoch 3:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.74it/s]

Epoch 3:  68%|██████▊   | 1368/2000 [01:02<00:29, 21.74it/s]

Epoch 3:  69%|██████▊   | 1371/2000 [01:02<00:28, 21.74it/s]

Epoch 3:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.76it/s]

Epoch 3:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.74it/s]

Epoch 3:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.74it/s]

Epoch 3:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.74it/s]

Epoch 3:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.74it/s]

Epoch 3:  69%|██████▉   | 1389/2000 [01:03<00:28, 21.74it/s]

Epoch 3:  70%|██████▉   | 1392/2000 [01:03<00:27, 21.74it/s]

Epoch 3:  70%|██████▉   | 1395/2000 [01:03<00:27, 21.74it/s]

Epoch 3:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.70it/s]

Epoch 3:  70%|███████   | 1401/2000 [01:04<00:27, 21.44it/s]

Epoch 3:  70%|███████   | 1404/2000 [01:04<00:27, 21.53it/s]

Epoch 3:  70%|███████   | 1407/2000 [01:04<00:27, 21.59it/s]

Epoch 3:  70%|███████   | 1410/2000 [01:04<00:27, 21.62it/s]

Epoch 3:  71%|███████   | 1413/2000 [01:04<00:27, 21.64it/s]

Epoch 3:  71%|███████   | 1416/2000 [01:04<00:26, 21.67it/s]

Epoch 3:  71%|███████   | 1419/2000 [01:05<00:26, 21.70it/s]

Epoch 3:  71%|███████   | 1422/2000 [01:05<00:26, 21.73it/s]

Epoch 3:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.74it/s]

Epoch 3:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.72it/s]

Epoch 3:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.72it/s]

Epoch 3:  72%|███████▏  | 1434/2000 [01:05<00:26, 21.73it/s]

Epoch 3:  72%|███████▏  | 1437/2000 [01:05<00:25, 21.74it/s]

Epoch 3:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.75it/s]

Epoch 3:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.76it/s]

Epoch 3:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.75it/s]

Epoch 3:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.73it/s]

Epoch 3:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.74it/s]

Epoch 3:  73%|███████▎  | 1455/2000 [01:06<00:25, 21.72it/s]

Epoch 3:  73%|███████▎  | 1458/2000 [01:06<00:24, 21.73it/s]

Epoch 3:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.74it/s]

Epoch 3:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.74it/s]

Epoch 3:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.74it/s]

Epoch 3:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.74it/s]

Epoch 3:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.74it/s]

Epoch 3:  74%|███████▍  | 1476/2000 [01:07<00:24, 21.73it/s]

Epoch 3:  74%|███████▍  | 1479/2000 [01:07<00:23, 21.73it/s]

Epoch 3:  74%|███████▍  | 1482/2000 [01:07<00:23, 21.74it/s]

Epoch 3:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.76it/s]

Epoch 3:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.75it/s]

Epoch 3:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.75it/s]

Epoch 3:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.75it/s]

Epoch 3:  75%|███████▍  | 1497/2000 [01:08<00:23, 21.74it/s]

Epoch 3:  75%|███████▌  | 1500/2000 [01:08<00:22, 21.75it/s]

Epoch 3:  75%|███████▌  | 1503/2000 [01:08<00:22, 21.74it/s]

Epoch 3:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.74it/s]

Epoch 3:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.75it/s]

Epoch 3:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.75it/s]

Epoch 3:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.76it/s]

Epoch 3:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.76it/s]

Epoch 3:  76%|███████▌  | 1521/2000 [01:09<00:22, 21.75it/s]

Epoch 3:  76%|███████▌  | 1524/2000 [01:09<00:21, 21.75it/s]

Epoch 3:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.75it/s]

Epoch 3:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.75it/s]

Epoch 3:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.74it/s]

Epoch 3:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.74it/s]

Epoch 3:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.74it/s]

Epoch 3:  77%|███████▋  | 1542/2000 [01:10<00:21, 21.73it/s]

Epoch 3:  77%|███████▋  | 1545/2000 [01:10<00:20, 21.73it/s]

Epoch 3:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.72it/s]

Epoch 3:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.72it/s]

Epoch 3:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.71it/s]

Epoch 3:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.70it/s]

Epoch 3:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.41it/s]

Epoch 3:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.52it/s]

Epoch 3:  78%|███████▊  | 1566/2000 [01:11<00:20, 21.63it/s]

Epoch 3:  78%|███████▊  | 1569/2000 [01:11<00:19, 21.69it/s]

Epoch 3:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.73it/s]

Epoch 3:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.76it/s]

Epoch 3:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.78it/s]

Epoch 3:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.81it/s]

Epoch 3:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.82it/s]

Epoch 3:  79%|███████▉  | 1587/2000 [01:12<00:18, 21.84it/s]

Epoch 3:  80%|███████▉  | 1590/2000 [01:12<00:18, 21.83it/s]

Epoch 3:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.84it/s]

Epoch 3:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.85it/s]

Epoch 3:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.86it/s]

Epoch 3:  80%|████████  | 1602/2000 [01:13<00:18, 21.87it/s]

Epoch 3:  80%|████████  | 1605/2000 [01:13<00:18, 21.86it/s]

Epoch 3:  80%|████████  | 1608/2000 [01:13<00:17, 21.87it/s]

Epoch 3:  81%|████████  | 1611/2000 [01:13<00:17, 21.87it/s]

Epoch 3:  81%|████████  | 1614/2000 [01:14<00:17, 21.88it/s]

Epoch 3:  81%|████████  | 1617/2000 [01:14<00:17, 21.87it/s]

Epoch 3:  81%|████████  | 1620/2000 [01:14<00:17, 21.88it/s]

Epoch 3:  81%|████████  | 1623/2000 [01:14<00:17, 21.87it/s]

Epoch 3:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.87it/s]

Epoch 3:  81%|████████▏ | 1629/2000 [01:14<00:16, 21.87it/s]

Epoch 3:  82%|████████▏ | 1632/2000 [01:14<00:16, 21.89it/s]

Epoch 3:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.89it/s]

Epoch 3:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.89it/s]

Epoch 3:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.88it/s]

Epoch 3:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.89it/s]

Epoch 3:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.89it/s]

Epoch 3:  82%|████████▎ | 1650/2000 [01:15<00:15, 21.88it/s]

Epoch 3:  83%|████████▎ | 1653/2000 [01:15<00:15, 21.88it/s]

Epoch 3:  83%|████████▎ | 1656/2000 [01:15<00:15, 21.89it/s]

Epoch 3:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.86it/s]

Epoch 3:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.86it/s]

Epoch 3:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.87it/s]

Epoch 3:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.86it/s]

Epoch 3:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.84it/s]

Epoch 3:  84%|████████▎ | 1674/2000 [01:16<00:14, 21.85it/s]

Epoch 3:  84%|████████▍ | 1677/2000 [01:16<00:14, 21.85it/s]

Epoch 3:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.85it/s]

Epoch 3:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.87it/s]

Epoch 3:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.85it/s]

Epoch 3:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.85it/s]

Epoch 3:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.85it/s]

Epoch 3:  85%|████████▍ | 1695/2000 [01:17<00:13, 21.84it/s]

Epoch 3:  85%|████████▍ | 1698/2000 [01:17<00:13, 21.84it/s]

Epoch 3:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.86it/s]

Epoch 3:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.86it/s]

Epoch 3:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.84it/s]

Epoch 3:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.84it/s]

Epoch 3:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.85it/s]

Epoch 3:  86%|████████▌ | 1716/2000 [01:18<00:12, 21.85it/s]

Epoch 3:  86%|████████▌ | 1719/2000 [01:18<00:12, 21.85it/s]

Epoch 3:  86%|████████▌ | 1722/2000 [01:18<00:12, 21.86it/s]

Epoch 3:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.85it/s]

Epoch 3:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.85it/s]

Epoch 3:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.85it/s]

Epoch 3:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.86it/s]

Epoch 3:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.86it/s]

Epoch 3:  87%|████████▋ | 1740/2000 [01:19<00:11, 21.88it/s]

Epoch 3:  87%|████████▋ | 1743/2000 [01:19<00:11, 21.86it/s]

Epoch 3:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.87it/s]

Epoch 3:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.86it/s]

Epoch 3:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.87it/s]

Epoch 3:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.87it/s]

Epoch 3:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.88it/s]

Epoch 3:  88%|████████▊ | 1761/2000 [01:20<00:10, 21.85it/s]

Epoch 3:  88%|████████▊ | 1764/2000 [01:20<00:10, 21.86it/s]

Epoch 3:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.86it/s]

Epoch 3:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.86it/s]

Epoch 3:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.85it/s]

Epoch 3:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.83it/s]

Epoch 3:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.84it/s]

Epoch 3:  89%|████████▉ | 1782/2000 [01:21<00:09, 21.84it/s]

Epoch 3:  89%|████████▉ | 1785/2000 [01:21<00:09, 21.63it/s]

Epoch 3:  89%|████████▉ | 1788/2000 [01:22<00:10, 21.06it/s]

Epoch 3:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.07it/s]

Epoch 3:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.26it/s]

Epoch 3:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.37it/s]

Epoch 3:  90%|█████████ | 1800/2000 [01:22<00:09, 21.52it/s]

Epoch 3:  90%|█████████ | 1803/2000 [01:22<00:09, 21.61it/s]

Epoch 3:  90%|█████████ | 1806/2000 [01:22<00:08, 21.71it/s]

Epoch 3:  90%|█████████ | 1809/2000 [01:23<00:08, 21.77it/s]

Epoch 3:  91%|█████████ | 1812/2000 [01:23<00:08, 21.78it/s]

Epoch 3:  91%|█████████ | 1815/2000 [01:23<00:08, 21.80it/s]

Epoch 3:  91%|█████████ | 1818/2000 [01:23<00:08, 21.82it/s]

Epoch 3:  91%|█████████ | 1821/2000 [01:23<00:08, 21.84it/s]

Epoch 3:  91%|█████████ | 1824/2000 [01:23<00:08, 21.84it/s]

Epoch 3:  91%|█████████▏| 1827/2000 [01:23<00:07, 21.84it/s]

Epoch 3:  92%|█████████▏| 1830/2000 [01:23<00:07, 21.85it/s]

Epoch 3:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.85it/s]

Epoch 3:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.86it/s]

Epoch 3:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.85it/s]

Epoch 3:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.85it/s]

Epoch 3:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.85it/s]

Epoch 3:  92%|█████████▏| 1848/2000 [01:24<00:06, 21.85it/s]

Epoch 3:  93%|█████████▎| 1851/2000 [01:24<00:06, 21.85it/s]

Epoch 3:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.86it/s]

Epoch 3:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.87it/s]

Epoch 3:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.87it/s]

Epoch 3:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.88it/s]

Epoch 3:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.87it/s]

Epoch 3:  93%|█████████▎| 1869/2000 [01:25<00:05, 21.85it/s]

Epoch 3:  94%|█████████▎| 1872/2000 [01:25<00:05, 21.86it/s]

Epoch 3:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.86it/s]

Epoch 3:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.87it/s]

Epoch 3:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.87it/s]

Epoch 3:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.88it/s]

Epoch 3:  94%|█████████▍| 1887/2000 [01:26<00:05, 21.88it/s]

Epoch 3:  94%|█████████▍| 1890/2000 [01:26<00:05, 21.86it/s]

Epoch 3:  95%|█████████▍| 1893/2000 [01:26<00:04, 21.86it/s]

Epoch 3:  95%|█████████▍| 1896/2000 [01:26<00:04, 21.86it/s]

Epoch 3:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.87it/s]

Epoch 3:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.88it/s]

Epoch 3:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.89it/s]

Epoch 3:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.88it/s]

Epoch 3:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.88it/s]

Epoch 3:  96%|█████████▌| 1914/2000 [01:27<00:03, 21.88it/s]

Epoch 3:  96%|█████████▌| 1917/2000 [01:27<00:03, 21.86it/s]

Epoch 3:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.87it/s]

Epoch 3:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.86it/s]

Epoch 3:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.87it/s]

Epoch 3:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.87it/s]

Epoch 3:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.87it/s]

Epoch 3:  97%|█████████▋| 1935/2000 [01:28<00:02, 21.86it/s]

Epoch 3:  97%|█████████▋| 1938/2000 [01:28<00:02, 21.87it/s]

Epoch 3:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.87it/s]

Epoch 3:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.86it/s]

Epoch 3:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.87it/s]

Epoch 3:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.86it/s]

Epoch 3:  98%|█████████▊| 1953/2000 [01:29<00:02, 21.87it/s]

Epoch 3:  98%|█████████▊| 1956/2000 [01:29<00:02, 21.87it/s]

Epoch 3:  98%|█████████▊| 1959/2000 [01:29<00:01, 21.87it/s]

Epoch 3:  98%|█████████▊| 1962/2000 [01:29<00:01, 21.88it/s]

Epoch 3:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.89it/s]

Epoch 3:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.88it/s]

Epoch 3:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.88it/s]

Epoch 3:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.87it/s]

Epoch 3:  99%|█████████▉| 1977/2000 [01:30<00:01, 21.85it/s]

Epoch 3:  99%|█████████▉| 1980/2000 [01:30<00:00, 21.86it/s]

Epoch 3:  99%|█████████▉| 1983/2000 [01:30<00:00, 21.85it/s]

Epoch 3:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.87it/s]

Epoch 3:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.86it/s]

Epoch 3: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.87it/s]

Epoch 3: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.87it/s]

Epoch 3: 100%|█████████▉| 1998/2000 [01:31<00:00, 21.87it/s]

Epoch 3: loss=0.3873, val_proxy=0.5097

Epoch 4:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 4:   0%|          | 2/2000 [00:00<01:45, 18.87it/s]

Epoch 4:   0%|          | 4/2000 [00:00<01:44, 19.14it/s]

Epoch 4:   0%|          | 6/2000 [00:00<01:43, 19.24it/s]

Epoch 4:   0%|          | 8/2000 [00:00<01:43, 19.27it/s]

Epoch 4:   0%|          | 10/2000 [00:00<01:43, 19.31it/s]

Epoch 4:   1%|          | 13/2000 [00:00<01:38, 20.15it/s]

Epoch 4:   1%|          | 16/2000 [00:00<01:35, 20.67it/s]

Epoch 4:   1%|          | 19/2000 [00:00<01:34, 20.99it/s]

Epoch 4:   1%|          | 22/2000 [00:01<01:33, 21.21it/s]

Epoch 4:   1%|▏         | 25/2000 [00:01<01:32, 21.32it/s]

Epoch 4:   1%|▏         | 28/2000 [00:01<01:32, 21.42it/s]

Epoch 4:   2%|▏         | 31/2000 [00:01<01:31, 21.49it/s]

Epoch 4:   2%|▏         | 34/2000 [00:01<01:31, 21.53it/s]

Epoch 4:   2%|▏         | 37/2000 [00:01<01:31, 21.57it/s]

Epoch 4:   2%|▏         | 40/2000 [00:01<01:30, 21.60it/s]

Epoch 4:   2%|▏         | 43/2000 [00:02<01:30, 21.60it/s]

Epoch 4:   2%|▏         | 46/2000 [00:02<01:30, 21.53it/s]

Epoch 4:   2%|▏         | 49/2000 [00:02<01:30, 21.56it/s]

Epoch 4:   3%|▎         | 52/2000 [00:02<01:30, 21.58it/s]

Epoch 4:   3%|▎         | 55/2000 [00:02<01:30, 21.58it/s]

Epoch 4:   3%|▎         | 58/2000 [00:02<01:30, 21.52it/s]

Epoch 4:   3%|▎         | 61/2000 [00:02<01:29, 21.54it/s]

Epoch 4:   3%|▎         | 64/2000 [00:03<01:29, 21.57it/s]

Epoch 4:   3%|▎         | 67/2000 [00:03<01:29, 21.59it/s]

Epoch 4:   4%|▎         | 70/2000 [00:03<01:29, 21.61it/s]

Epoch 4:   4%|▎         | 73/2000 [00:03<01:29, 21.60it/s]

Epoch 4:   4%|▍         | 76/2000 [00:03<01:29, 21.61it/s]

Epoch 4:   4%|▍         | 79/2000 [00:03<01:28, 21.62it/s]

Epoch 4:   4%|▍         | 82/2000 [00:03<01:28, 21.63it/s]

Epoch 4:   4%|▍         | 85/2000 [00:03<01:28, 21.64it/s]

Epoch 4:   4%|▍         | 88/2000 [00:04<01:28, 21.65it/s]

Epoch 4:   5%|▍         | 91/2000 [00:04<01:28, 21.64it/s]

Epoch 4:   5%|▍         | 94/2000 [00:04<01:28, 21.62it/s]

Epoch 4:   5%|▍         | 97/2000 [00:04<01:28, 21.62it/s]

Epoch 4:   5%|▌         | 100/2000 [00:04<01:27, 21.64it/s]

Epoch 4:   5%|▌         | 103/2000 [00:04<01:27, 21.63it/s]

Epoch 4:   5%|▌         | 106/2000 [00:04<01:27, 21.62it/s]

Epoch 4:   5%|▌         | 109/2000 [00:05<01:27, 21.63it/s]

Epoch 4:   6%|▌         | 112/2000 [00:05<01:27, 21.62it/s]

Epoch 4:   6%|▌         | 115/2000 [00:05<01:27, 21.62it/s]

Epoch 4:   6%|▌         | 118/2000 [00:05<01:27, 21.62it/s]

Epoch 4:   6%|▌         | 121/2000 [00:05<01:26, 21.63it/s]

Epoch 4:   6%|▌         | 124/2000 [00:05<01:26, 21.65it/s]

Epoch 4:   6%|▋         | 127/2000 [00:05<01:26, 21.65it/s]

Epoch 4:   6%|▋         | 130/2000 [00:06<01:26, 21.63it/s]

Epoch 4:   7%|▋         | 133/2000 [00:06<01:26, 21.60it/s]

Epoch 4:   7%|▋         | 136/2000 [00:06<01:26, 21.59it/s]

Epoch 4:   7%|▋         | 139/2000 [00:06<01:26, 21.59it/s]

Epoch 4:   7%|▋         | 142/2000 [00:06<01:25, 21.61it/s]

Epoch 4:   7%|▋         | 145/2000 [00:06<01:25, 21.61it/s]

Epoch 4:   7%|▋         | 148/2000 [00:06<01:25, 21.61it/s]

Epoch 4:   8%|▊         | 151/2000 [00:07<01:25, 21.61it/s]

Epoch 4:   8%|▊         | 154/2000 [00:07<01:25, 21.61it/s]

Epoch 4:   8%|▊         | 157/2000 [00:07<01:25, 21.59it/s]

Epoch 4:   8%|▊         | 160/2000 [00:07<01:25, 21.61it/s]

Epoch 4:   8%|▊         | 163/2000 [00:07<01:24, 21.61it/s]

Epoch 4:   8%|▊         | 166/2000 [00:07<01:24, 21.62it/s]

Epoch 4:   8%|▊         | 169/2000 [00:07<01:24, 21.63it/s]

Epoch 4:   9%|▊         | 172/2000 [00:08<01:24, 21.63it/s]

Epoch 4:   9%|▉         | 175/2000 [00:08<01:25, 21.42it/s]

Epoch 4:   9%|▉         | 178/2000 [00:08<01:24, 21.48it/s]

Epoch 4:   9%|▉         | 181/2000 [00:08<01:24, 21.52it/s]

Epoch 4:   9%|▉         | 184/2000 [00:08<01:24, 21.54it/s]

Epoch 4:   9%|▉         | 187/2000 [00:08<01:24, 21.55it/s]

Epoch 4:  10%|▉         | 190/2000 [00:08<01:23, 21.56it/s]

Epoch 4:  10%|▉         | 193/2000 [00:08<01:23, 21.57it/s]

Epoch 4:  10%|▉         | 196/2000 [00:09<01:23, 21.56it/s]

Epoch 4:  10%|▉         | 199/2000 [00:09<01:23, 21.55it/s]

Epoch 4:  10%|█         | 202/2000 [00:09<01:23, 21.56it/s]

Epoch 4:  10%|█         | 205/2000 [00:09<01:23, 21.55it/s]

Epoch 4:  10%|█         | 208/2000 [00:09<01:23, 21.56it/s]

Epoch 4:  11%|█         | 211/2000 [00:09<01:23, 21.55it/s]

Epoch 4:  11%|█         | 214/2000 [00:09<01:22, 21.57it/s]

Epoch 4:  11%|█         | 217/2000 [00:10<01:22, 21.59it/s]

Epoch 4:  11%|█         | 220/2000 [00:10<01:22, 21.59it/s]

Epoch 4:  11%|█         | 223/2000 [00:10<01:22, 21.60it/s]

Epoch 4:  11%|█▏        | 226/2000 [00:10<01:22, 21.61it/s]

Epoch 4:  11%|█▏        | 229/2000 [00:10<01:21, 21.62it/s]

Epoch 4:  12%|█▏        | 232/2000 [00:10<01:21, 21.61it/s]

Epoch 4:  12%|█▏        | 235/2000 [00:10<01:21, 21.61it/s]

Epoch 4:  12%|█▏        | 238/2000 [00:11<01:21, 21.63it/s]

Epoch 4:  12%|█▏        | 241/2000 [00:11<01:21, 21.63it/s]

Epoch 4:  12%|█▏        | 244/2000 [00:11<01:21, 21.59it/s]

Epoch 4:  12%|█▏        | 247/2000 [00:11<01:21, 21.57it/s]

Epoch 4:  12%|█▎        | 250/2000 [00:11<01:21, 21.59it/s]

Epoch 4:  13%|█▎        | 253/2000 [00:11<01:20, 21.60it/s]

Epoch 4:  13%|█▎        | 256/2000 [00:11<01:20, 21.59it/s]

Epoch 4:  13%|█▎        | 259/2000 [00:12<01:20, 21.61it/s]

Epoch 4:  13%|█▎        | 262/2000 [00:12<01:20, 21.61it/s]

Epoch 4:  13%|█▎        | 265/2000 [00:12<01:20, 21.61it/s]

Epoch 4:  13%|█▎        | 268/2000 [00:12<01:20, 21.62it/s]

Epoch 4:  14%|█▎        | 271/2000 [00:12<01:19, 21.62it/s]

Epoch 4:  14%|█▎        | 274/2000 [00:12<01:19, 21.62it/s]

Epoch 4:  14%|█▍        | 277/2000 [00:12<01:19, 21.62it/s]

Epoch 4:  14%|█▍        | 280/2000 [00:13<01:19, 21.62it/s]

Epoch 4:  14%|█▍        | 283/2000 [00:13<01:19, 21.62it/s]

Epoch 4:  14%|█▍        | 286/2000 [00:13<01:19, 21.61it/s]

Epoch 4:  14%|█▍        | 289/2000 [00:13<01:19, 21.61it/s]

Epoch 4:  15%|█▍        | 292/2000 [00:13<01:19, 21.60it/s]

Epoch 4:  15%|█▍        | 295/2000 [00:13<01:18, 21.62it/s]

Epoch 4:  15%|█▍        | 298/2000 [00:13<01:18, 21.62it/s]

Epoch 4:  15%|█▌        | 301/2000 [00:13<01:18, 21.63it/s]

Epoch 4:  15%|█▌        | 304/2000 [00:14<01:18, 21.62it/s]

Epoch 4:  15%|█▌        | 307/2000 [00:14<01:18, 21.62it/s]

Epoch 4:  16%|█▌        | 310/2000 [00:14<01:18, 21.61it/s]

Epoch 4:  16%|█▌        | 313/2000 [00:14<01:18, 21.61it/s]

Epoch 4:  16%|█▌        | 316/2000 [00:14<01:17, 21.62it/s]

Epoch 4:  16%|█▌        | 319/2000 [00:14<01:17, 21.62it/s]

Epoch 4:  16%|█▌        | 322/2000 [00:14<01:17, 21.63it/s]

Epoch 4:  16%|█▋        | 325/2000 [00:15<01:17, 21.63it/s]

Epoch 4:  16%|█▋        | 328/2000 [00:15<01:17, 21.62it/s]

Epoch 4:  17%|█▋        | 331/2000 [00:15<01:17, 21.63it/s]

Epoch 4:  17%|█▋        | 334/2000 [00:15<01:17, 21.63it/s]

Epoch 4:  17%|█▋        | 337/2000 [00:15<01:16, 21.63it/s]

Epoch 4:  17%|█▋        | 340/2000 [00:15<01:16, 21.62it/s]

Epoch 4:  17%|█▋        | 343/2000 [00:15<01:16, 21.63it/s]

Epoch 4:  17%|█▋        | 346/2000 [00:16<01:16, 21.63it/s]

Epoch 4:  17%|█▋        | 349/2000 [00:16<01:16, 21.63it/s]

Epoch 4:  18%|█▊        | 352/2000 [00:16<01:16, 21.64it/s]

Epoch 4:  18%|█▊        | 355/2000 [00:16<01:16, 21.62it/s]

Epoch 4:  18%|█▊        | 358/2000 [00:16<01:15, 21.62it/s]

Epoch 4:  18%|█▊        | 361/2000 [00:16<01:15, 21.62it/s]

Epoch 4:  18%|█▊        | 364/2000 [00:16<01:15, 21.62it/s]

Epoch 4:  18%|█▊        | 367/2000 [00:17<01:15, 21.62it/s]

Epoch 4:  18%|█▊        | 370/2000 [00:17<01:15, 21.54it/s]

Epoch 4:  19%|█▊        | 373/2000 [00:17<01:15, 21.55it/s]

Epoch 4:  19%|█▉        | 376/2000 [00:17<01:15, 21.56it/s]

Epoch 4:  19%|█▉        | 379/2000 [00:17<01:15, 21.57it/s]

Epoch 4:  19%|█▉        | 382/2000 [00:17<01:14, 21.59it/s]

Epoch 4:  19%|█▉        | 385/2000 [00:17<01:14, 21.59it/s]

Epoch 4:  19%|█▉        | 388/2000 [00:18<01:14, 21.60it/s]

Epoch 4:  20%|█▉        | 391/2000 [00:18<01:14, 21.60it/s]

Epoch 4:  20%|█▉        | 394/2000 [00:18<01:14, 21.60it/s]

Epoch 4:  20%|█▉        | 397/2000 [00:18<01:14, 21.59it/s]

Epoch 4:  20%|██        | 400/2000 [00:18<01:14, 21.59it/s]

Epoch 4:  20%|██        | 403/2000 [00:18<01:13, 21.59it/s]

Epoch 4:  20%|██        | 406/2000 [00:18<01:14, 21.42it/s]

Epoch 4:  20%|██        | 409/2000 [00:19<01:16, 20.84it/s]

Epoch 4:  21%|██        | 412/2000 [00:19<01:16, 20.87it/s]

Epoch 4:  21%|██        | 415/2000 [00:19<01:15, 21.05it/s]

Epoch 4:  21%|██        | 418/2000 [00:19<01:14, 21.16it/s]

Epoch 4:  21%|██        | 421/2000 [00:19<01:14, 21.30it/s]

Epoch 4:  21%|██        | 424/2000 [00:19<01:13, 21.41it/s]

Epoch 4:  21%|██▏       | 427/2000 [00:19<01:13, 21.47it/s]

Epoch 4:  22%|██▏       | 430/2000 [00:19<01:12, 21.51it/s]

Epoch 4:  22%|██▏       | 433/2000 [00:20<01:12, 21.54it/s]

Epoch 4:  22%|██▏       | 436/2000 [00:20<01:12, 21.58it/s]

Epoch 4:  22%|██▏       | 439/2000 [00:20<01:12, 21.59it/s]

Epoch 4:  22%|██▏       | 442/2000 [00:20<01:12, 21.60it/s]

Epoch 4:  22%|██▏       | 445/2000 [00:20<01:11, 21.61it/s]

Epoch 4:  22%|██▏       | 448/2000 [00:20<01:11, 21.62it/s]

Epoch 4:  23%|██▎       | 451/2000 [00:20<01:11, 21.64it/s]

Epoch 4:  23%|██▎       | 454/2000 [00:21<01:11, 21.63it/s]

Epoch 4:  23%|██▎       | 457/2000 [00:21<01:11, 21.62it/s]

Epoch 4:  23%|██▎       | 460/2000 [00:21<01:11, 21.62it/s]

Epoch 4:  23%|██▎       | 463/2000 [00:21<01:11, 21.63it/s]

Epoch 4:  23%|██▎       | 466/2000 [00:21<01:10, 21.63it/s]

Epoch 4:  23%|██▎       | 469/2000 [00:21<01:10, 21.62it/s]

Epoch 4:  24%|██▎       | 472/2000 [00:21<01:10, 21.64it/s]

Epoch 4:  24%|██▍       | 475/2000 [00:22<01:10, 21.65it/s]

Epoch 4:  24%|██▍       | 478/2000 [00:22<01:10, 21.65it/s]

Epoch 4:  24%|██▍       | 481/2000 [00:22<01:10, 21.63it/s]

Epoch 4:  24%|██▍       | 484/2000 [00:22<01:10, 21.63it/s]

Epoch 4:  24%|██▍       | 487/2000 [00:22<01:09, 21.64it/s]

Epoch 4:  24%|██▍       | 490/2000 [00:22<01:09, 21.64it/s]

Epoch 4:  25%|██▍       | 493/2000 [00:22<01:09, 21.62it/s]

Epoch 4:  25%|██▍       | 496/2000 [00:23<01:09, 21.62it/s]

Epoch 4:  25%|██▍       | 499/2000 [00:23<01:09, 21.62it/s]

Epoch 4:  25%|██▌       | 502/2000 [00:23<01:09, 21.63it/s]

Epoch 4:  25%|██▌       | 505/2000 [00:23<01:09, 21.62it/s]

Epoch 4:  25%|██▌       | 508/2000 [00:23<01:08, 21.65it/s]

Epoch 4:  26%|██▌       | 511/2000 [00:23<01:08, 21.67it/s]

Epoch 4:  26%|██▌       | 514/2000 [00:23<01:08, 21.69it/s]

Epoch 4:  26%|██▌       | 517/2000 [00:24<01:08, 21.70it/s]

Epoch 4:  26%|██▌       | 520/2000 [00:24<01:08, 21.70it/s]

Epoch 4:  26%|██▌       | 523/2000 [00:24<01:08, 21.70it/s]

Epoch 4:  26%|██▋       | 526/2000 [00:24<01:07, 21.70it/s]

Epoch 4:  26%|██▋       | 529/2000 [00:24<01:07, 21.70it/s]

Epoch 4:  27%|██▋       | 532/2000 [00:24<01:07, 21.71it/s]

Epoch 4:  27%|██▋       | 535/2000 [00:24<01:07, 21.70it/s]

Epoch 4:  27%|██▋       | 538/2000 [00:24<01:07, 21.71it/s]

Epoch 4:  27%|██▋       | 541/2000 [00:25<01:07, 21.71it/s]

Epoch 4:  27%|██▋       | 544/2000 [00:25<01:07, 21.70it/s]

Epoch 4:  27%|██▋       | 547/2000 [00:25<01:06, 21.69it/s]

Epoch 4:  28%|██▊       | 550/2000 [00:25<01:06, 21.70it/s]

Epoch 4:  28%|██▊       | 553/2000 [00:25<01:06, 21.71it/s]

Epoch 4:  28%|██▊       | 556/2000 [00:25<01:06, 21.69it/s]

Epoch 4:  28%|██▊       | 559/2000 [00:25<01:06, 21.63it/s]

Epoch 4:  28%|██▊       | 562/2000 [00:26<01:06, 21.63it/s]

Epoch 4:  28%|██▊       | 565/2000 [00:26<01:06, 21.64it/s]

Epoch 4:  28%|██▊       | 568/2000 [00:26<01:06, 21.65it/s]

Epoch 4:  29%|██▊       | 571/2000 [00:26<01:05, 21.65it/s]

Epoch 4:  29%|██▊       | 574/2000 [00:26<01:05, 21.67it/s]

Epoch 4:  29%|██▉       | 577/2000 [00:26<01:05, 21.67it/s]

Epoch 4:  29%|██▉       | 580/2000 [00:26<01:05, 21.68it/s]

Epoch 4:  29%|██▉       | 583/2000 [00:27<01:05, 21.67it/s]

Epoch 4:  29%|██▉       | 586/2000 [00:27<01:05, 21.66it/s]

Epoch 4:  29%|██▉       | 589/2000 [00:27<01:05, 21.67it/s]

Epoch 4:  30%|██▉       | 592/2000 [00:27<01:04, 21.69it/s]

Epoch 4:  30%|██▉       | 595/2000 [00:27<01:04, 21.70it/s]

Epoch 4:  30%|██▉       | 598/2000 [00:27<01:04, 21.71it/s]

Epoch 4:  30%|███       | 601/2000 [00:27<01:04, 21.65it/s]

Epoch 4:  30%|███       | 604/2000 [00:28<01:04, 21.66it/s]

Epoch 4:  30%|███       | 607/2000 [00:28<01:04, 21.67it/s]

Epoch 4:  30%|███       | 610/2000 [00:28<01:04, 21.67it/s]

Epoch 4:  31%|███       | 613/2000 [00:28<01:03, 21.68it/s]

Epoch 4:  31%|███       | 616/2000 [00:28<01:03, 21.69it/s]

Epoch 4:  31%|███       | 619/2000 [00:28<01:03, 21.68it/s]

Epoch 4:  31%|███       | 622/2000 [00:28<01:03, 21.70it/s]

Epoch 4:  31%|███▏      | 625/2000 [00:28<01:03, 21.70it/s]

Epoch 4:  31%|███▏      | 628/2000 [00:29<01:03, 21.69it/s]

Epoch 4:  32%|███▏      | 631/2000 [00:29<01:03, 21.69it/s]

Epoch 4:  32%|███▏      | 634/2000 [00:29<01:02, 21.70it/s]

Epoch 4:  32%|███▏      | 637/2000 [00:29<01:02, 21.68it/s]

Epoch 4:  32%|███▏      | 640/2000 [00:29<01:02, 21.69it/s]

Epoch 4:  32%|███▏      | 643/2000 [00:29<01:02, 21.70it/s]

Epoch 4:  32%|███▏      | 646/2000 [00:29<01:02, 21.70it/s]

Epoch 4:  32%|███▏      | 649/2000 [00:30<01:02, 21.67it/s]

Epoch 4:  33%|███▎      | 652/2000 [00:30<01:02, 21.68it/s]

Epoch 4:  33%|███▎      | 655/2000 [00:30<01:02, 21.68it/s]

Epoch 4:  33%|███▎      | 658/2000 [00:30<01:01, 21.67it/s]

Epoch 4:  33%|███▎      | 661/2000 [00:30<01:01, 21.67it/s]

Epoch 4:  33%|███▎      | 664/2000 [00:30<01:01, 21.67it/s]

Epoch 4:  33%|███▎      | 667/2000 [00:30<01:01, 21.69it/s]

Epoch 4:  34%|███▎      | 670/2000 [00:31<01:01, 21.69it/s]

Epoch 4:  34%|███▎      | 673/2000 [00:31<01:01, 21.68it/s]

Epoch 4:  34%|███▍      | 676/2000 [00:31<01:01, 21.69it/s]

Epoch 4:  34%|███▍      | 679/2000 [00:31<01:00, 21.69it/s]

Epoch 4:  34%|███▍      | 682/2000 [00:31<01:00, 21.69it/s]

Epoch 4:  34%|███▍      | 685/2000 [00:31<01:00, 21.69it/s]

Epoch 4:  34%|███▍      | 688/2000 [00:31<01:00, 21.70it/s]

Epoch 4:  35%|███▍      | 691/2000 [00:32<01:00, 21.70it/s]

Epoch 4:  35%|███▍      | 694/2000 [00:32<01:00, 21.70it/s]

Epoch 4:  35%|███▍      | 697/2000 [00:32<01:00, 21.70it/s]

Epoch 4:  35%|███▌      | 700/2000 [00:32<00:59, 21.70it/s]

Epoch 4:  35%|███▌      | 703/2000 [00:32<00:59, 21.70it/s]

Epoch 4:  35%|███▌      | 706/2000 [00:32<00:59, 21.70it/s]

Epoch 4:  35%|███▌      | 709/2000 [00:32<00:59, 21.71it/s]

Epoch 4:  36%|███▌      | 712/2000 [00:32<00:59, 21.71it/s]

Epoch 4:  36%|███▌      | 715/2000 [00:33<00:59, 21.70it/s]

Epoch 4:  36%|███▌      | 718/2000 [00:33<00:59, 21.69it/s]

Epoch 4:  36%|███▌      | 721/2000 [00:33<00:58, 21.69it/s]

Epoch 4:  36%|███▌      | 724/2000 [00:33<00:58, 21.69it/s]

Epoch 4:  36%|███▋      | 727/2000 [00:33<00:58, 21.69it/s]

Epoch 4:  36%|███▋      | 730/2000 [00:33<00:58, 21.70it/s]

Epoch 4:  37%|███▋      | 733/2000 [00:33<00:58, 21.71it/s]

Epoch 4:  37%|███▋      | 736/2000 [00:34<00:58, 21.71it/s]

Epoch 4:  37%|███▋      | 739/2000 [00:34<00:58, 21.69it/s]

Epoch 4:  37%|███▋      | 742/2000 [00:34<00:57, 21.69it/s]

Epoch 4:  37%|███▋      | 745/2000 [00:34<00:57, 21.69it/s]

Epoch 4:  37%|███▋      | 748/2000 [00:34<00:57, 21.69it/s]

Epoch 4:  38%|███▊      | 751/2000 [00:34<00:57, 21.70it/s]

Epoch 4:  38%|███▊      | 754/2000 [00:34<00:57, 21.70it/s]

Epoch 4:  38%|███▊      | 757/2000 [00:35<00:57, 21.70it/s]

Epoch 4:  38%|███▊      | 760/2000 [00:35<00:57, 21.71it/s]

Epoch 4:  38%|███▊      | 763/2000 [00:35<00:56, 21.70it/s]

Epoch 4:  38%|███▊      | 766/2000 [00:35<00:56, 21.71it/s]

Epoch 4:  38%|███▊      | 769/2000 [00:35<00:56, 21.70it/s]

Epoch 4:  39%|███▊      | 772/2000 [00:35<00:56, 21.70it/s]

Epoch 4:  39%|███▉      | 775/2000 [00:35<00:56, 21.70it/s]

Epoch 4:  39%|███▉      | 778/2000 [00:36<00:56, 21.70it/s]

Epoch 4:  39%|███▉      | 781/2000 [00:36<00:56, 21.68it/s]

Epoch 4:  39%|███▉      | 784/2000 [00:36<00:56, 21.68it/s]

Epoch 4:  39%|███▉      | 787/2000 [00:36<00:55, 21.69it/s]

Epoch 4:  40%|███▉      | 790/2000 [00:36<00:55, 21.69it/s]

Epoch 4:  40%|███▉      | 793/2000 [00:36<00:55, 21.70it/s]

Epoch 4:  40%|███▉      | 796/2000 [00:36<00:55, 21.65it/s]

Epoch 4:  40%|███▉      | 799/2000 [00:37<00:55, 21.65it/s]

Epoch 4:  40%|████      | 802/2000 [00:37<00:55, 21.68it/s]

Epoch 4:  40%|████      | 805/2000 [00:37<00:55, 21.68it/s]

Epoch 4:  40%|████      | 808/2000 [00:37<00:54, 21.69it/s]

Epoch 4:  41%|████      | 811/2000 [00:37<00:54, 21.70it/s]

Epoch 4:  41%|████      | 814/2000 [00:37<00:54, 21.69it/s]

Epoch 4:  41%|████      | 817/2000 [00:37<00:54, 21.69it/s]

Epoch 4:  41%|████      | 820/2000 [00:37<00:54, 21.70it/s]

Epoch 4:  41%|████      | 823/2000 [00:38<00:54, 21.70it/s]

Epoch 4:  41%|████▏     | 826/2000 [00:38<00:54, 21.69it/s]

Epoch 4:  41%|████▏     | 829/2000 [00:38<00:53, 21.69it/s]

Epoch 4:  42%|████▏     | 832/2000 [00:38<00:53, 21.69it/s]

Epoch 4:  42%|████▏     | 835/2000 [00:38<00:53, 21.69it/s]

Epoch 4:  42%|████▏     | 838/2000 [00:38<00:53, 21.69it/s]

Epoch 4:  42%|████▏     | 841/2000 [00:38<00:53, 21.69it/s]

Epoch 4:  42%|████▏     | 844/2000 [00:39<00:53, 21.70it/s]

Epoch 4:  42%|████▏     | 847/2000 [00:39<00:53, 21.70it/s]

Epoch 4:  42%|████▎     | 850/2000 [00:39<00:52, 21.70it/s]

Epoch 4:  43%|████▎     | 853/2000 [00:39<00:52, 21.69it/s]

Epoch 4:  43%|████▎     | 856/2000 [00:39<00:52, 21.70it/s]

Epoch 4:  43%|████▎     | 859/2000 [00:39<00:52, 21.69it/s]

Epoch 4:  43%|████▎     | 862/2000 [00:39<00:52, 21.69it/s]

Epoch 4:  43%|████▎     | 865/2000 [00:40<00:52, 21.70it/s]

Epoch 4:  43%|████▎     | 868/2000 [00:40<00:52, 21.70it/s]

Epoch 4:  44%|████▎     | 871/2000 [00:40<00:52, 21.69it/s]

Epoch 4:  44%|████▎     | 874/2000 [00:40<00:51, 21.69it/s]

Epoch 4:  44%|████▍     | 877/2000 [00:40<00:51, 21.70it/s]

Epoch 4:  44%|████▍     | 880/2000 [00:40<00:51, 21.70it/s]

Epoch 4:  44%|████▍     | 883/2000 [00:40<00:51, 21.71it/s]

Epoch 4:  44%|████▍     | 886/2000 [00:41<00:51, 21.71it/s]

Epoch 4:  44%|████▍     | 889/2000 [00:41<00:51, 21.70it/s]

Epoch 4:  45%|████▍     | 892/2000 [00:41<00:51, 21.70it/s]

Epoch 4:  45%|████▍     | 895/2000 [00:41<00:50, 21.71it/s]

Epoch 4:  45%|████▍     | 898/2000 [00:41<00:50, 21.71it/s]

Epoch 4:  45%|████▌     | 901/2000 [00:41<00:50, 21.70it/s]

Epoch 4:  45%|████▌     | 904/2000 [00:41<00:50, 21.71it/s]

Epoch 4:  45%|████▌     | 907/2000 [00:41<00:50, 21.72it/s]

Epoch 4:  46%|████▌     | 910/2000 [00:42<00:50, 21.72it/s]

Epoch 4:  46%|████▌     | 913/2000 [00:42<00:50, 21.71it/s]

Epoch 4:  46%|████▌     | 916/2000 [00:42<00:49, 21.71it/s]

Epoch 4:  46%|████▌     | 919/2000 [00:42<00:49, 21.72it/s]

Epoch 4:  46%|████▌     | 922/2000 [00:42<00:49, 21.71it/s]

Epoch 4:  46%|████▋     | 925/2000 [00:42<00:49, 21.69it/s]

Epoch 4:  46%|████▋     | 928/2000 [00:42<00:49, 21.70it/s]

Epoch 4:  47%|████▋     | 931/2000 [00:43<00:49, 21.69it/s]

Epoch 4:  47%|████▋     | 934/2000 [00:43<00:49, 21.70it/s]

Epoch 4:  47%|████▋     | 937/2000 [00:43<00:48, 21.70it/s]

Epoch 4:  47%|████▋     | 940/2000 [00:43<00:48, 21.70it/s]

Epoch 4:  47%|████▋     | 943/2000 [00:43<00:48, 21.71it/s]

Epoch 4:  47%|████▋     | 946/2000 [00:43<00:48, 21.70it/s]

Epoch 4:  47%|████▋     | 949/2000 [00:43<00:48, 21.70it/s]

Epoch 4:  48%|████▊     | 952/2000 [00:44<00:48, 21.60it/s]

Epoch 4:  48%|████▊     | 955/2000 [00:44<00:48, 21.64it/s]

Epoch 4:  48%|████▊     | 958/2000 [00:44<00:48, 21.68it/s]

Epoch 4:  48%|████▊     | 961/2000 [00:44<00:47, 21.71it/s]

Epoch 4:  48%|████▊     | 964/2000 [00:44<00:47, 21.71it/s]

Epoch 4:  48%|████▊     | 967/2000 [00:44<00:47, 21.73it/s]

Epoch 4:  48%|████▊     | 970/2000 [00:44<00:47, 21.74it/s]

Epoch 4:  49%|████▊     | 973/2000 [00:45<00:47, 21.74it/s]

Epoch 4:  49%|████▉     | 976/2000 [00:45<00:47, 21.74it/s]

Epoch 4:  49%|████▉     | 979/2000 [00:45<00:46, 21.73it/s]

Epoch 4:  49%|████▉     | 982/2000 [00:45<00:47, 21.65it/s]

Epoch 4:  49%|████▉     | 985/2000 [00:45<00:46, 21.66it/s]

Epoch 4:  49%|████▉     | 988/2000 [00:45<00:46, 21.68it/s]

Epoch 4:  50%|████▉     | 991/2000 [00:45<00:46, 21.70it/s]

Epoch 4:  50%|████▉     | 994/2000 [00:45<00:46, 21.71it/s]

Epoch 4:  50%|████▉     | 997/2000 [00:46<00:46, 21.71it/s]

Epoch 4:  50%|█████     | 1000/2000 [00:46<00:46, 21.72it/s]

Epoch 4:  50%|█████     | 1003/2000 [00:46<00:45, 21.72it/s]

Epoch 4:  50%|█████     | 1006/2000 [00:46<00:45, 21.71it/s]

Epoch 4:  50%|█████     | 1009/2000 [00:46<00:45, 21.73it/s]

Epoch 4:  51%|█████     | 1012/2000 [00:46<00:45, 21.73it/s]

Epoch 4:  51%|█████     | 1015/2000 [00:46<00:45, 21.75it/s]

Epoch 4:  51%|█████     | 1018/2000 [00:47<00:45, 21.76it/s]

Epoch 4:  51%|█████     | 1021/2000 [00:47<00:45, 21.74it/s]

Epoch 4:  51%|█████     | 1024/2000 [00:47<00:44, 21.74it/s]

Epoch 4:  51%|█████▏    | 1027/2000 [00:47<00:44, 21.72it/s]

Epoch 4:  52%|█████▏    | 1030/2000 [00:47<00:44, 21.73it/s]

Epoch 4:  52%|█████▏    | 1033/2000 [00:47<00:44, 21.73it/s]

Epoch 4:  52%|█████▏    | 1036/2000 [00:47<00:44, 21.74it/s]

Epoch 4:  52%|█████▏    | 1039/2000 [00:48<00:44, 21.73it/s]

Epoch 4:  52%|█████▏    | 1042/2000 [00:48<00:44, 21.72it/s]

Epoch 4:  52%|█████▏    | 1045/2000 [00:48<00:43, 21.72it/s]

Epoch 4:  52%|█████▏    | 1048/2000 [00:48<00:43, 21.73it/s]

Epoch 4:  53%|█████▎    | 1051/2000 [00:48<00:43, 21.73it/s]

Epoch 4:  53%|█████▎    | 1054/2000 [00:48<00:43, 21.76it/s]

Epoch 4:  53%|█████▎    | 1057/2000 [00:48<00:43, 21.77it/s]

Epoch 4:  53%|█████▎    | 1060/2000 [00:49<00:43, 21.78it/s]

Epoch 4:  53%|█████▎    | 1063/2000 [00:49<00:43, 21.78it/s]

Epoch 4:  53%|█████▎    | 1066/2000 [00:49<00:42, 21.78it/s]

Epoch 4:  53%|█████▎    | 1069/2000 [00:49<00:42, 21.78it/s]

Epoch 4:  54%|█████▎    | 1072/2000 [00:49<00:42, 21.77it/s]

Epoch 4:  54%|█████▍    | 1075/2000 [00:49<00:42, 21.78it/s]

Epoch 4:  54%|█████▍    | 1078/2000 [00:49<00:42, 21.79it/s]

Epoch 4:  54%|█████▍    | 1081/2000 [00:49<00:42, 21.79it/s]

Epoch 4:  54%|█████▍    | 1084/2000 [00:50<00:42, 21.79it/s]

Epoch 4:  54%|█████▍    | 1087/2000 [00:50<00:41, 21.78it/s]

Epoch 4:  55%|█████▍    | 1090/2000 [00:50<00:41, 21.78it/s]

Epoch 4:  55%|█████▍    | 1093/2000 [00:50<00:41, 21.77it/s]

Epoch 4:  55%|█████▍    | 1096/2000 [00:50<00:41, 21.79it/s]

Epoch 4:  55%|█████▍    | 1099/2000 [00:50<00:41, 21.80it/s]

Epoch 4:  55%|█████▌    | 1102/2000 [00:50<00:41, 21.79it/s]

Epoch 4:  55%|█████▌    | 1105/2000 [00:51<00:41, 21.79it/s]

Epoch 4:  55%|█████▌    | 1108/2000 [00:51<00:40, 21.76it/s]

Epoch 4:  56%|█████▌    | 1111/2000 [00:51<00:40, 21.77it/s]

Epoch 4:  56%|█████▌    | 1114/2000 [00:51<00:40, 21.77it/s]

Epoch 4:  56%|█████▌    | 1117/2000 [00:51<00:40, 21.60it/s]

Epoch 4:  56%|█████▌    | 1120/2000 [00:51<00:41, 21.01it/s]

Epoch 4:  56%|█████▌    | 1123/2000 [00:51<00:41, 20.99it/s]

Epoch 4:  56%|█████▋    | 1126/2000 [00:52<00:41, 21.16it/s]

Epoch 4:  56%|█████▋    | 1129/2000 [00:52<00:40, 21.26it/s]

Epoch 4:  57%|█████▋    | 1132/2000 [00:52<00:40, 21.42it/s]

Epoch 4:  57%|█████▋    | 1135/2000 [00:52<00:40, 21.53it/s]

Epoch 4:  57%|█████▋    | 1138/2000 [00:52<00:39, 21.60it/s]

Epoch 4:  57%|█████▋    | 1141/2000 [00:52<00:39, 21.64it/s]

Epoch 4:  57%|█████▋    | 1144/2000 [00:52<00:39, 21.67it/s]

Epoch 4:  57%|█████▋    | 1147/2000 [00:53<00:39, 21.70it/s]

Epoch 4:  57%|█████▊    | 1150/2000 [00:53<00:39, 21.71it/s]

Epoch 4:  58%|█████▊    | 1153/2000 [00:53<00:38, 21.74it/s]

Epoch 4:  58%|█████▊    | 1156/2000 [00:53<00:38, 21.74it/s]

Epoch 4:  58%|█████▊    | 1159/2000 [00:53<00:38, 21.76it/s]

Epoch 4:  58%|█████▊    | 1162/2000 [00:53<00:38, 21.76it/s]

Epoch 4:  58%|█████▊    | 1165/2000 [00:53<00:38, 21.77it/s]

Epoch 4:  58%|█████▊    | 1168/2000 [00:54<00:38, 21.78it/s]

Epoch 4:  59%|█████▊    | 1171/2000 [00:54<00:38, 21.77it/s]

Epoch 4:  59%|█████▊    | 1174/2000 [00:54<00:37, 21.78it/s]

Epoch 4:  59%|█████▉    | 1177/2000 [00:54<00:37, 21.77it/s]

Epoch 4:  59%|█████▉    | 1180/2000 [00:54<00:37, 21.77it/s]

Epoch 4:  59%|█████▉    | 1183/2000 [00:54<00:37, 21.78it/s]

Epoch 4:  59%|█████▉    | 1186/2000 [00:54<00:37, 21.79it/s]

Epoch 4:  59%|█████▉    | 1189/2000 [00:54<00:37, 21.79it/s]

Epoch 4:  60%|█████▉    | 1192/2000 [00:55<00:37, 21.78it/s]

Epoch 4:  60%|█████▉    | 1195/2000 [00:55<00:36, 21.77it/s]

Epoch 4:  60%|█████▉    | 1198/2000 [00:55<00:36, 21.76it/s]

Epoch 4:  60%|██████    | 1201/2000 [00:55<00:36, 21.75it/s]

Epoch 4:  60%|██████    | 1204/2000 [00:55<00:36, 21.76it/s]

Epoch 4:  60%|██████    | 1207/2000 [00:55<00:36, 21.76it/s]

Epoch 4:  60%|██████    | 1210/2000 [00:55<00:36, 21.76it/s]

Epoch 4:  61%|██████    | 1213/2000 [00:56<00:36, 21.78it/s]

Epoch 4:  61%|██████    | 1216/2000 [00:56<00:36, 21.76it/s]

Epoch 4:  61%|██████    | 1219/2000 [00:56<00:35, 21.78it/s]

Epoch 4:  61%|██████    | 1222/2000 [00:56<00:35, 21.78it/s]

Epoch 4:  61%|██████▏   | 1225/2000 [00:56<00:35, 21.79it/s]

Epoch 4:  61%|██████▏   | 1228/2000 [00:56<00:35, 21.79it/s]

Epoch 4:  62%|██████▏   | 1231/2000 [00:56<00:35, 21.78it/s]

Epoch 4:  62%|██████▏   | 1234/2000 [00:57<00:35, 21.78it/s]

Epoch 4:  62%|██████▏   | 1237/2000 [00:57<00:35, 21.78it/s]

Epoch 4:  62%|██████▏   | 1240/2000 [00:57<00:34, 21.78it/s]

Epoch 4:  62%|██████▏   | 1243/2000 [00:57<00:34, 21.77it/s]

Epoch 4:  62%|██████▏   | 1246/2000 [00:57<00:34, 21.78it/s]

Epoch 4:  62%|██████▏   | 1249/2000 [00:57<00:34, 21.79it/s]

Epoch 4:  63%|██████▎   | 1252/2000 [00:57<00:34, 21.78it/s]

Epoch 4:  63%|██████▎   | 1255/2000 [00:58<00:34, 21.79it/s]

Epoch 4:  63%|██████▎   | 1258/2000 [00:58<00:34, 21.78it/s]

Epoch 4:  63%|██████▎   | 1261/2000 [00:58<00:33, 21.77it/s]

Epoch 4:  63%|██████▎   | 1264/2000 [00:58<00:33, 21.77it/s]

Epoch 4:  63%|██████▎   | 1267/2000 [00:58<00:33, 21.76it/s]

Epoch 4:  64%|██████▎   | 1270/2000 [00:58<00:33, 21.77it/s]

Epoch 4:  64%|██████▎   | 1273/2000 [00:58<00:33, 21.77it/s]

Epoch 4:  64%|██████▍   | 1276/2000 [00:58<00:33, 21.78it/s]

Epoch 4:  64%|██████▍   | 1279/2000 [00:59<00:33, 21.77it/s]

Epoch 4:  64%|██████▍   | 1282/2000 [00:59<00:32, 21.78it/s]

Epoch 4:  64%|██████▍   | 1285/2000 [00:59<00:32, 21.77it/s]

Epoch 4:  64%|██████▍   | 1288/2000 [00:59<00:32, 21.78it/s]

Epoch 4:  65%|██████▍   | 1291/2000 [00:59<00:32, 21.79it/s]

Epoch 4:  65%|██████▍   | 1294/2000 [00:59<00:32, 21.78it/s]

Epoch 4:  65%|██████▍   | 1297/2000 [00:59<00:32, 21.80it/s]

Epoch 4:  65%|██████▌   | 1300/2000 [01:00<00:32, 21.81it/s]

Epoch 4:  65%|██████▌   | 1303/2000 [01:00<00:31, 21.80it/s]

Epoch 4:  65%|██████▌   | 1306/2000 [01:00<00:31, 21.80it/s]

Epoch 4:  65%|██████▌   | 1309/2000 [01:00<00:31, 21.80it/s]

Epoch 4:  66%|██████▌   | 1312/2000 [01:00<00:31, 21.79it/s]

Epoch 4:  66%|██████▌   | 1315/2000 [01:00<00:31, 21.79it/s]

Epoch 4:  66%|██████▌   | 1318/2000 [01:00<00:31, 21.79it/s]

Epoch 4:  66%|██████▌   | 1321/2000 [01:01<00:31, 21.77it/s]

Epoch 4:  66%|██████▌   | 1324/2000 [01:01<00:31, 21.78it/s]

Epoch 4:  66%|██████▋   | 1327/2000 [01:01<00:30, 21.77it/s]

Epoch 4:  66%|██████▋   | 1330/2000 [01:01<00:30, 21.78it/s]

Epoch 4:  67%|██████▋   | 1333/2000 [01:01<00:30, 21.79it/s]

Epoch 4:  67%|██████▋   | 1336/2000 [01:01<00:30, 21.79it/s]

Epoch 4:  67%|██████▋   | 1339/2000 [01:01<00:30, 21.80it/s]

Epoch 4:  67%|██████▋   | 1342/2000 [01:02<00:30, 21.78it/s]

Epoch 4:  67%|██████▋   | 1345/2000 [01:02<00:30, 21.77it/s]

Epoch 4:  67%|██████▋   | 1348/2000 [01:02<00:29, 21.79it/s]

Epoch 4:  68%|██████▊   | 1351/2000 [01:02<00:29, 21.77it/s]

Epoch 4:  68%|██████▊   | 1354/2000 [01:02<00:29, 21.77it/s]

Epoch 4:  68%|██████▊   | 1357/2000 [01:02<00:29, 21.77it/s]

Epoch 4:  68%|██████▊   | 1360/2000 [01:02<00:29, 21.77it/s]

Epoch 4:  68%|██████▊   | 1363/2000 [01:02<00:29, 21.76it/s]

Epoch 4:  68%|██████▊   | 1366/2000 [01:03<00:29, 21.78it/s]

Epoch 4:  68%|██████▊   | 1369/2000 [01:03<00:28, 21.77it/s]

Epoch 4:  69%|██████▊   | 1372/2000 [01:03<00:28, 21.78it/s]

Epoch 4:  69%|██████▉   | 1375/2000 [01:03<00:28, 21.77it/s]

Epoch 4:  69%|██████▉   | 1378/2000 [01:03<00:28, 21.77it/s]

Epoch 4:  69%|██████▉   | 1381/2000 [01:03<00:28, 21.75it/s]

Epoch 4:  69%|██████▉   | 1384/2000 [01:03<00:28, 21.75it/s]

Epoch 4:  69%|██████▉   | 1387/2000 [01:04<00:28, 21.76it/s]

Epoch 4:  70%|██████▉   | 1390/2000 [01:04<00:28, 21.76it/s]

Epoch 4:  70%|██████▉   | 1393/2000 [01:04<00:27, 21.78it/s]

Epoch 4:  70%|██████▉   | 1396/2000 [01:04<00:27, 21.77it/s]

Epoch 4:  70%|██████▉   | 1399/2000 [01:04<00:27, 21.77it/s]

Epoch 4:  70%|███████   | 1402/2000 [01:04<00:27, 21.77it/s]

Epoch 4:  70%|███████   | 1405/2000 [01:04<00:27, 21.77it/s]

Epoch 4:  70%|███████   | 1408/2000 [01:05<00:27, 21.76it/s]

Epoch 4:  71%|███████   | 1411/2000 [01:05<00:27, 21.77it/s]

Epoch 4:  71%|███████   | 1414/2000 [01:05<00:26, 21.76it/s]

Epoch 4:  71%|███████   | 1417/2000 [01:05<00:26, 21.78it/s]

Epoch 4:  71%|███████   | 1420/2000 [01:05<00:26, 21.79it/s]

Epoch 4:  71%|███████   | 1423/2000 [01:05<00:26, 21.79it/s]

Epoch 4:  71%|███████▏  | 1426/2000 [01:05<00:26, 21.78it/s]

Epoch 4:  71%|███████▏  | 1429/2000 [01:06<00:26, 21.77it/s]

Epoch 4:  72%|███████▏  | 1432/2000 [01:06<00:26, 21.77it/s]

Epoch 4:  72%|███████▏  | 1435/2000 [01:06<00:25, 21.76it/s]

Epoch 4:  72%|███████▏  | 1438/2000 [01:06<00:25, 21.77it/s]

Epoch 4:  72%|███████▏  | 1441/2000 [01:06<00:25, 21.76it/s]

Epoch 4:  72%|███████▏  | 1444/2000 [01:06<00:25, 21.75it/s]

Epoch 4:  72%|███████▏  | 1447/2000 [01:06<00:25, 21.75it/s]

Epoch 4:  72%|███████▎  | 1450/2000 [01:06<00:25, 21.76it/s]

Epoch 4:  73%|███████▎  | 1453/2000 [01:07<00:25, 21.76it/s]

Epoch 4:  73%|███████▎  | 1456/2000 [01:07<00:25, 21.75it/s]

Epoch 4:  73%|███████▎  | 1459/2000 [01:07<00:24, 21.75it/s]

Epoch 4:  73%|███████▎  | 1462/2000 [01:07<00:24, 21.78it/s]

Epoch 4:  73%|███████▎  | 1465/2000 [01:07<00:24, 21.78it/s]

Epoch 4:  73%|███████▎  | 1468/2000 [01:07<00:24, 21.77it/s]

Epoch 4:  74%|███████▎  | 1471/2000 [01:07<00:24, 21.76it/s]

Epoch 4:  74%|███████▎  | 1474/2000 [01:08<00:24, 21.76it/s]

Epoch 4:  74%|███████▍  | 1477/2000 [01:08<00:24, 21.76it/s]

Epoch 4:  74%|███████▍  | 1480/2000 [01:08<00:23, 21.75it/s]

Epoch 4:  74%|███████▍  | 1483/2000 [01:08<00:23, 21.76it/s]

Epoch 4:  74%|███████▍  | 1486/2000 [01:08<00:23, 21.76it/s]

Epoch 4:  74%|███████▍  | 1489/2000 [01:08<00:23, 21.77it/s]

Epoch 4:  75%|███████▍  | 1492/2000 [01:08<00:23, 21.78it/s]

Epoch 4:  75%|███████▍  | 1495/2000 [01:09<00:23, 21.77it/s]

Epoch 4:  75%|███████▍  | 1498/2000 [01:09<00:23, 21.77it/s]

Epoch 4:  75%|███████▌  | 1501/2000 [01:09<00:22, 21.78it/s]

Epoch 4:  75%|███████▌  | 1504/2000 [01:09<00:22, 21.79it/s]

Epoch 4:  75%|███████▌  | 1507/2000 [01:09<00:22, 21.78it/s]

Epoch 4:  76%|███████▌  | 1510/2000 [01:09<00:22, 21.79it/s]

Epoch 4:  76%|███████▌  | 1513/2000 [01:09<00:22, 21.78it/s]

Epoch 4:  76%|███████▌  | 1516/2000 [01:09<00:22, 21.78it/s]

Epoch 4:  76%|███████▌  | 1519/2000 [01:10<00:22, 21.76it/s]

Epoch 4:  76%|███████▌  | 1522/2000 [01:10<00:21, 21.77it/s]

Epoch 4:  76%|███████▋  | 1525/2000 [01:10<00:21, 21.77it/s]

Epoch 4:  76%|███████▋  | 1528/2000 [01:10<00:21, 21.75it/s]

Epoch 4:  77%|███████▋  | 1531/2000 [01:10<00:21, 21.77it/s]

Epoch 4:  77%|███████▋  | 1534/2000 [01:10<00:21, 21.77it/s]

Epoch 4:  77%|███████▋  | 1537/2000 [01:10<00:21, 21.78it/s]

Epoch 4:  77%|███████▋  | 1540/2000 [01:11<00:21, 21.77it/s]

Epoch 4:  77%|███████▋  | 1543/2000 [01:11<00:20, 21.76it/s]

Epoch 4:  77%|███████▋  | 1546/2000 [01:11<00:20, 21.76it/s]

Epoch 4:  77%|███████▋  | 1549/2000 [01:11<00:20, 21.76it/s]

Epoch 4:  78%|███████▊  | 1552/2000 [01:11<00:20, 21.78it/s]

Epoch 4:  78%|███████▊  | 1555/2000 [01:11<00:20, 21.77it/s]

Epoch 4:  78%|███████▊  | 1558/2000 [01:11<00:20, 21.75it/s]

Epoch 4:  78%|███████▊  | 1561/2000 [01:12<00:20, 21.74it/s]

Epoch 4:  78%|███████▊  | 1564/2000 [01:12<00:20, 21.74it/s]

Epoch 4:  78%|███████▊  | 1567/2000 [01:12<00:19, 21.75it/s]

Epoch 4:  78%|███████▊  | 1570/2000 [01:12<00:19, 21.75it/s]

Epoch 4:  79%|███████▊  | 1573/2000 [01:12<00:19, 21.74it/s]

Epoch 4:  79%|███████▉  | 1576/2000 [01:12<00:19, 21.75it/s]

Epoch 4:  79%|███████▉  | 1579/2000 [01:12<00:19, 21.76it/s]

Epoch 4:  79%|███████▉  | 1582/2000 [01:13<00:19, 21.77it/s]

Epoch 4:  79%|███████▉  | 1585/2000 [01:13<00:19, 21.76it/s]

Epoch 4:  79%|███████▉  | 1588/2000 [01:13<00:18, 21.77it/s]

Epoch 4:  80%|███████▉  | 1591/2000 [01:13<00:18, 21.76it/s]

Epoch 4:  80%|███████▉  | 1594/2000 [01:13<00:18, 21.77it/s]

Epoch 4:  80%|███████▉  | 1597/2000 [01:13<00:18, 21.76it/s]

Epoch 4:  80%|████████  | 1600/2000 [01:13<00:18, 21.78it/s]

Epoch 4:  80%|████████  | 1603/2000 [01:13<00:18, 21.78it/s]

Epoch 4:  80%|████████  | 1606/2000 [01:14<00:18, 21.77it/s]

Epoch 4:  80%|████████  | 1609/2000 [01:14<00:17, 21.77it/s]

Epoch 4:  81%|████████  | 1612/2000 [01:14<00:17, 21.78it/s]

Epoch 4:  81%|████████  | 1615/2000 [01:14<00:17, 21.76it/s]

Epoch 4:  81%|████████  | 1618/2000 [01:14<00:17, 21.78it/s]

Epoch 4:  81%|████████  | 1621/2000 [01:14<00:17, 21.78it/s]

Epoch 4:  81%|████████  | 1624/2000 [01:14<00:17, 21.77it/s]

Epoch 4:  81%|████████▏ | 1627/2000 [01:15<00:17, 21.77it/s]

Epoch 4:  82%|████████▏ | 1630/2000 [01:15<00:16, 21.78it/s]

Epoch 4:  82%|████████▏ | 1633/2000 [01:15<00:16, 21.79it/s]

Epoch 4:  82%|████████▏ | 1636/2000 [01:15<00:16, 21.78it/s]

Epoch 4:  82%|████████▏ | 1639/2000 [01:15<00:16, 21.77it/s]

Epoch 4:  82%|████████▏ | 1642/2000 [01:15<00:16, 21.79it/s]

Epoch 4:  82%|████████▏ | 1645/2000 [01:15<00:16, 21.80it/s]

Epoch 4:  82%|████████▏ | 1648/2000 [01:16<00:16, 21.80it/s]

Epoch 4:  83%|████████▎ | 1651/2000 [01:16<00:16, 21.80it/s]

Epoch 4:  83%|████████▎ | 1654/2000 [01:16<00:15, 21.79it/s]

Epoch 4:  83%|████████▎ | 1657/2000 [01:16<00:15, 21.78it/s]

Epoch 4:  83%|████████▎ | 1660/2000 [01:16<00:15, 21.77it/s]

Epoch 4:  83%|████████▎ | 1663/2000 [01:16<00:15, 21.78it/s]

Epoch 4:  83%|████████▎ | 1666/2000 [01:16<00:15, 21.79it/s]

Epoch 4:  83%|████████▎ | 1669/2000 [01:17<00:15, 21.77it/s]

Epoch 4:  84%|████████▎ | 1672/2000 [01:17<00:15, 21.76it/s]

Epoch 4:  84%|████████▍ | 1675/2000 [01:17<00:14, 21.77it/s]

Epoch 4:  84%|████████▍ | 1678/2000 [01:17<00:14, 21.78it/s]

Epoch 4:  84%|████████▍ | 1681/2000 [01:17<00:14, 21.77it/s]

Epoch 4:  84%|████████▍ | 1684/2000 [01:17<00:14, 21.78it/s]

Epoch 4:  84%|████████▍ | 1687/2000 [01:17<00:14, 21.76it/s]

Epoch 4:  84%|████████▍ | 1690/2000 [01:17<00:14, 21.77it/s]

Epoch 4:  85%|████████▍ | 1693/2000 [01:18<00:14, 21.75it/s]

Epoch 4:  85%|████████▍ | 1696/2000 [01:18<00:13, 21.76it/s]

Epoch 4:  85%|████████▍ | 1699/2000 [01:18<00:13, 21.75it/s]

Epoch 4:  85%|████████▌ | 1702/2000 [01:18<00:13, 21.76it/s]

Epoch 4:  85%|████████▌ | 1705/2000 [01:18<00:13, 21.78it/s]

Epoch 4:  85%|████████▌ | 1708/2000 [01:18<00:13, 21.78it/s]

Epoch 4:  86%|████████▌ | 1711/2000 [01:18<00:13, 21.77it/s]

Epoch 4:  86%|████████▌ | 1714/2000 [01:19<00:13, 21.78it/s]

Epoch 4:  86%|████████▌ | 1717/2000 [01:19<00:12, 21.80it/s]

Epoch 4:  86%|████████▌ | 1720/2000 [01:19<00:12, 21.80it/s]

Epoch 4:  86%|████████▌ | 1723/2000 [01:19<00:12, 21.76it/s]

Epoch 4:  86%|████████▋ | 1726/2000 [01:19<00:12, 21.76it/s]

Epoch 4:  86%|████████▋ | 1729/2000 [01:19<00:12, 21.76it/s]

Epoch 4:  87%|████████▋ | 1732/2000 [01:19<00:12, 21.77it/s]

Epoch 4:  87%|████████▋ | 1735/2000 [01:20<00:12, 21.78it/s]

Epoch 4:  87%|████████▋ | 1738/2000 [01:20<00:12, 21.76it/s]

Epoch 4:  87%|████████▋ | 1741/2000 [01:20<00:11, 21.76it/s]

Epoch 4:  87%|████████▋ | 1744/2000 [01:20<00:11, 21.76it/s]

Epoch 4:  87%|████████▋ | 1747/2000 [01:20<00:11, 21.76it/s]

Epoch 4:  88%|████████▊ | 1750/2000 [01:20<00:11, 21.75it/s]

Epoch 4:  88%|████████▊ | 1753/2000 [01:20<00:11, 21.74it/s]

Epoch 4:  88%|████████▊ | 1756/2000 [01:21<00:11, 21.75it/s]

Epoch 4:  88%|████████▊ | 1759/2000 [01:21<00:11, 21.74it/s]

Epoch 4:  88%|████████▊ | 1762/2000 [01:21<00:10, 21.76it/s]

Epoch 4:  88%|████████▊ | 1765/2000 [01:21<00:10, 21.75it/s]

Epoch 4:  88%|████████▊ | 1768/2000 [01:21<00:10, 21.78it/s]

Epoch 4:  89%|████████▊ | 1771/2000 [01:21<00:10, 21.78it/s]

Epoch 4:  89%|████████▊ | 1774/2000 [01:21<00:10, 21.77it/s]

Epoch 4:  89%|████████▉ | 1777/2000 [01:21<00:10, 21.77it/s]

Epoch 4:  89%|████████▉ | 1780/2000 [01:22<00:10, 21.77it/s]

Epoch 4:  89%|████████▉ | 1783/2000 [01:22<00:09, 21.78it/s]

Epoch 4:  89%|████████▉ | 1786/2000 [01:22<00:09, 21.78it/s]

Epoch 4:  89%|████████▉ | 1789/2000 [01:22<00:09, 21.78it/s]

Epoch 4:  90%|████████▉ | 1792/2000 [01:22<00:09, 21.79it/s]

Epoch 4:  90%|████████▉ | 1795/2000 [01:22<00:09, 21.78it/s]

Epoch 4:  90%|████████▉ | 1798/2000 [01:22<00:09, 21.77it/s]

Epoch 4:  90%|█████████ | 1801/2000 [01:23<00:09, 21.79it/s]

Epoch 4:  90%|█████████ | 1804/2000 [01:23<00:09, 21.78it/s]

Epoch 4:  90%|█████████ | 1807/2000 [01:23<00:08, 21.78it/s]

Epoch 4:  90%|█████████ | 1810/2000 [01:23<00:08, 21.78it/s]

Epoch 4:  91%|█████████ | 1813/2000 [01:23<00:08, 21.76it/s]

Epoch 4:  91%|█████████ | 1816/2000 [01:23<00:08, 21.77it/s]

Epoch 4:  91%|█████████ | 1819/2000 [01:23<00:08, 21.77it/s]

Epoch 4:  91%|█████████ | 1822/2000 [01:24<00:08, 21.77it/s]

Epoch 4:  91%|█████████▏| 1825/2000 [01:24<00:08, 21.76it/s]

Epoch 4:  91%|█████████▏| 1828/2000 [01:24<00:07, 21.75it/s]

Epoch 4:  92%|█████████▏| 1831/2000 [01:24<00:08, 21.06it/s]

Epoch 4:  92%|█████████▏| 1834/2000 [01:24<00:07, 21.04it/s]

Epoch 4:  92%|█████████▏| 1837/2000 [01:24<00:07, 21.20it/s]

Epoch 4:  92%|█████████▏| 1840/2000 [01:24<00:07, 21.32it/s]

Epoch 4:  92%|█████████▏| 1843/2000 [01:25<00:07, 21.46it/s]

Epoch 4:  92%|█████████▏| 1846/2000 [01:25<00:07, 21.55it/s]

Epoch 4:  92%|█████████▏| 1849/2000 [01:25<00:06, 21.62it/s]

Epoch 4:  93%|█████████▎| 1852/2000 [01:25<00:06, 21.67it/s]

Epoch 4:  93%|█████████▎| 1855/2000 [01:25<00:06, 21.70it/s]

Epoch 4:  93%|█████████▎| 1858/2000 [01:25<00:06, 21.74it/s]

Epoch 4:  93%|█████████▎| 1861/2000 [01:25<00:06, 21.75it/s]

Epoch 4:  93%|█████████▎| 1864/2000 [01:26<00:06, 21.75it/s]

Epoch 4:  93%|█████████▎| 1867/2000 [01:26<00:06, 21.76it/s]

Epoch 4:  94%|█████████▎| 1870/2000 [01:26<00:05, 21.77it/s]

Epoch 4:  94%|█████████▎| 1873/2000 [01:26<00:05, 21.77it/s]

Epoch 4:  94%|█████████▍| 1876/2000 [01:26<00:05, 21.76it/s]

Epoch 4:  94%|█████████▍| 1879/2000 [01:26<00:05, 21.77it/s]

Epoch 4:  94%|█████████▍| 1882/2000 [01:26<00:05, 21.76it/s]

Epoch 4:  94%|█████████▍| 1885/2000 [01:26<00:05, 21.78it/s]

Epoch 4:  94%|█████████▍| 1888/2000 [01:27<00:05, 21.78it/s]

Epoch 4:  95%|█████████▍| 1891/2000 [01:27<00:05, 21.78it/s]

Epoch 4:  95%|█████████▍| 1894/2000 [01:27<00:04, 21.79it/s]

Epoch 4:  95%|█████████▍| 1897/2000 [01:27<00:04, 21.77it/s]

Epoch 4:  95%|█████████▌| 1900/2000 [01:27<00:04, 21.78it/s]

Epoch 4:  95%|█████████▌| 1903/2000 [01:27<00:04, 21.79it/s]

Epoch 4:  95%|█████████▌| 1906/2000 [01:27<00:04, 21.80it/s]

Epoch 4:  95%|█████████▌| 1909/2000 [01:28<00:04, 21.78it/s]

Epoch 4:  96%|█████████▌| 1912/2000 [01:28<00:04, 21.79it/s]

Epoch 4:  96%|█████████▌| 1915/2000 [01:28<00:03, 21.81it/s]

Epoch 4:  96%|█████████▌| 1918/2000 [01:28<00:03, 21.80it/s]

Epoch 4:  96%|█████████▌| 1921/2000 [01:28<00:03, 21.80it/s]

Epoch 4:  96%|█████████▌| 1924/2000 [01:28<00:03, 21.79it/s]

Epoch 4:  96%|█████████▋| 1927/2000 [01:28<00:03, 21.79it/s]

Epoch 4:  96%|█████████▋| 1930/2000 [01:29<00:03, 21.81it/s]

Epoch 4:  97%|█████████▋| 1933/2000 [01:29<00:03, 21.81it/s]

Epoch 4:  97%|█████████▋| 1936/2000 [01:29<00:02, 21.80it/s]

Epoch 4:  97%|█████████▋| 1939/2000 [01:29<00:02, 21.80it/s]

Epoch 4:  97%|█████████▋| 1942/2000 [01:29<00:02, 21.78it/s]

Epoch 4:  97%|█████████▋| 1945/2000 [01:29<00:02, 21.78it/s]

Epoch 4:  97%|█████████▋| 1948/2000 [01:29<00:02, 21.79it/s]

Epoch 4:  98%|█████████▊| 1951/2000 [01:30<00:02, 21.77it/s]

Epoch 4:  98%|█████████▊| 1954/2000 [01:30<00:02, 21.78it/s]

Epoch 4:  98%|█████████▊| 1957/2000 [01:30<00:01, 21.78it/s]

Epoch 4:  98%|█████████▊| 1960/2000 [01:30<00:01, 21.77it/s]

Epoch 4:  98%|█████████▊| 1963/2000 [01:30<00:01, 21.78it/s]

Epoch 4:  98%|█████████▊| 1966/2000 [01:30<00:01, 21.77it/s]

Epoch 4:  98%|█████████▊| 1969/2000 [01:30<00:01, 21.78it/s]

Epoch 4:  99%|█████████▊| 1972/2000 [01:30<00:01, 21.79it/s]

Epoch 4:  99%|█████████▉| 1975/2000 [01:31<00:01, 21.77it/s]

Epoch 4:  99%|█████████▉| 1978/2000 [01:31<00:01, 21.78it/s]

Epoch 4:  99%|█████████▉| 1981/2000 [01:31<00:00, 21.79it/s]

Epoch 4:  99%|█████████▉| 1984/2000 [01:31<00:00, 21.80it/s]

Epoch 4:  99%|█████████▉| 1987/2000 [01:31<00:00, 21.80it/s]

Epoch 4: 100%|█████████▉| 1990/2000 [01:31<00:00, 21.79it/s]

Epoch 4: 100%|█████████▉| 1993/2000 [01:31<00:00, 21.80it/s]

Epoch 4: 100%|█████████▉| 1996/2000 [01:32<00:00, 21.80it/s]

Epoch 4: 100%|█████████▉| 1999/2000 [01:32<00:00, 21.80it/s]

Epoch 4: loss=0.3868, val_proxy=0.5128

Epoch 5:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 5:   0%|          | 3/2000 [00:00<01:33, 21.42it/s]

Epoch 5:   0%|          | 6/2000 [00:00<01:32, 21.57it/s]

Epoch 5:   0%|          | 9/2000 [00:00<01:32, 21.61it/s]

Epoch 5:   1%|          | 12/2000 [00:00<01:31, 21.64it/s]

Epoch 5:   1%|          | 15/2000 [00:00<01:31, 21.67it/s]

Epoch 5:   1%|          | 18/2000 [00:00<01:31, 21.69it/s]

Epoch 5:   1%|          | 21/2000 [00:00<01:31, 21.66it/s]

Epoch 5:   1%|          | 24/2000 [00:01<01:31, 21.66it/s]

Epoch 5:   1%|▏         | 27/2000 [00:01<01:30, 21.70it/s]

Epoch 5:   2%|▏         | 30/2000 [00:01<01:30, 21.70it/s]

Epoch 5:   2%|▏         | 33/2000 [00:01<01:30, 21.71it/s]

Epoch 5:   2%|▏         | 36/2000 [00:01<01:30, 21.72it/s]

Epoch 5:   2%|▏         | 39/2000 [00:01<01:30, 21.72it/s]

Epoch 5:   2%|▏         | 42/2000 [00:01<01:30, 21.72it/s]

Epoch 5:   2%|▏         | 45/2000 [00:02<01:29, 21.73it/s]

Epoch 5:   2%|▏         | 48/2000 [00:02<01:29, 21.73it/s]

Epoch 5:   3%|▎         | 51/2000 [00:02<01:29, 21.74it/s]

Epoch 5:   3%|▎         | 54/2000 [00:02<01:29, 21.73it/s]

Epoch 5:   3%|▎         | 57/2000 [00:02<01:29, 21.73it/s]

Epoch 5:   3%|▎         | 60/2000 [00:02<01:29, 21.74it/s]

Epoch 5:   3%|▎         | 63/2000 [00:02<01:29, 21.73it/s]

Epoch 5:   3%|▎         | 66/2000 [00:03<01:29, 21.72it/s]

Epoch 5:   3%|▎         | 69/2000 [00:03<01:28, 21.73it/s]

Epoch 5:   4%|▎         | 72/2000 [00:03<01:28, 21.74it/s]

Epoch 5:   4%|▍         | 75/2000 [00:03<01:28, 21.73it/s]

Epoch 5:   4%|▍         | 78/2000 [00:03<01:28, 21.74it/s]

Epoch 5:   4%|▍         | 81/2000 [00:03<01:28, 21.74it/s]

Epoch 5:   4%|▍         | 84/2000 [00:03<01:28, 21.75it/s]

Epoch 5:   4%|▍         | 87/2000 [00:04<01:27, 21.75it/s]

Epoch 5:   4%|▍         | 90/2000 [00:04<01:27, 21.74it/s]

Epoch 5:   5%|▍         | 93/2000 [00:04<01:27, 21.70it/s]

Epoch 5:   5%|▍         | 96/2000 [00:04<01:27, 21.71it/s]

Epoch 5:   5%|▍         | 99/2000 [00:04<01:27, 21.72it/s]

Epoch 5:   5%|▌         | 102/2000 [00:04<01:27, 21.72it/s]

Epoch 5:   5%|▌         | 105/2000 [00:04<01:27, 21.72it/s]

Epoch 5:   5%|▌         | 108/2000 [00:04<01:27, 21.74it/s]

Epoch 5:   6%|▌         | 111/2000 [00:05<01:26, 21.76it/s]

Epoch 5:   6%|▌         | 114/2000 [00:05<01:26, 21.76it/s]

Epoch 5:   6%|▌         | 117/2000 [00:05<01:26, 21.75it/s]

Epoch 5:   6%|▌         | 120/2000 [00:05<01:26, 21.75it/s]

Epoch 5:   6%|▌         | 123/2000 [00:05<01:26, 21.76it/s]

Epoch 5:   6%|▋         | 126/2000 [00:05<01:26, 21.76it/s]

Epoch 5:   6%|▋         | 129/2000 [00:05<01:26, 21.75it/s]

Epoch 5:   7%|▋         | 132/2000 [00:06<01:25, 21.73it/s]

Epoch 5:   7%|▋         | 135/2000 [00:06<01:25, 21.75it/s]

Epoch 5:   7%|▋         | 138/2000 [00:06<01:25, 21.74it/s]

Epoch 5:   7%|▋         | 141/2000 [00:06<01:25, 21.74it/s]

Epoch 5:   7%|▋         | 144/2000 [00:06<01:25, 21.74it/s]

Epoch 5:   7%|▋         | 147/2000 [00:06<01:25, 21.73it/s]

Epoch 5:   8%|▊         | 150/2000 [00:06<01:25, 21.73it/s]

Epoch 5:   8%|▊         | 153/2000 [00:07<01:25, 21.73it/s]

Epoch 5:   8%|▊         | 156/2000 [00:07<01:24, 21.74it/s]

Epoch 5:   8%|▊         | 159/2000 [00:07<01:24, 21.76it/s]

Epoch 5:   8%|▊         | 162/2000 [00:07<01:24, 21.76it/s]

Epoch 5:   8%|▊         | 165/2000 [00:07<01:24, 21.76it/s]

Epoch 5:   8%|▊         | 168/2000 [00:07<01:24, 21.78it/s]

Epoch 5:   9%|▊         | 171/2000 [00:07<01:24, 21.77it/s]

Epoch 5:   9%|▊         | 174/2000 [00:08<01:23, 21.74it/s]

Epoch 5:   9%|▉         | 177/2000 [00:08<01:23, 21.74it/s]

Epoch 5:   9%|▉         | 180/2000 [00:08<01:23, 21.75it/s]

Epoch 5:   9%|▉         | 183/2000 [00:08<01:23, 21.71it/s]

Epoch 5:   9%|▉         | 186/2000 [00:08<01:23, 21.70it/s]

Epoch 5:   9%|▉         | 189/2000 [00:08<01:23, 21.71it/s]

Epoch 5:  10%|▉         | 192/2000 [00:08<01:23, 21.72it/s]

Epoch 5:  10%|▉         | 195/2000 [00:08<01:23, 21.72it/s]

Epoch 5:  10%|▉         | 198/2000 [00:09<01:22, 21.73it/s]

Epoch 5:  10%|█         | 201/2000 [00:09<01:22, 21.73it/s]

Epoch 5:  10%|█         | 204/2000 [00:09<01:22, 21.73it/s]

Epoch 5:  10%|█         | 207/2000 [00:09<01:22, 21.74it/s]

Epoch 5:  10%|█         | 210/2000 [00:09<01:22, 21.74it/s]

Epoch 5:  11%|█         | 213/2000 [00:09<01:22, 21.75it/s]

Epoch 5:  11%|█         | 216/2000 [00:09<01:22, 21.74it/s]

Epoch 5:  11%|█         | 219/2000 [00:10<01:21, 21.74it/s]

Epoch 5:  11%|█         | 222/2000 [00:10<01:21, 21.74it/s]

Epoch 5:  11%|█▏        | 225/2000 [00:10<01:21, 21.74it/s]

Epoch 5:  11%|█▏        | 228/2000 [00:10<01:21, 21.75it/s]

Epoch 5:  12%|█▏        | 231/2000 [00:10<01:21, 21.74it/s]

Epoch 5:  12%|█▏        | 234/2000 [00:10<01:21, 21.76it/s]

Epoch 5:  12%|█▏        | 237/2000 [00:10<01:21, 21.74it/s]

Epoch 5:  12%|█▏        | 240/2000 [00:11<01:20, 21.75it/s]

Epoch 5:  12%|█▏        | 243/2000 [00:11<01:20, 21.75it/s]

Epoch 5:  12%|█▏        | 246/2000 [00:11<01:20, 21.75it/s]

Epoch 5:  12%|█▏        | 249/2000 [00:11<01:20, 21.74it/s]

Epoch 5:  13%|█▎        | 252/2000 [00:11<01:20, 21.74it/s]

Epoch 5:  13%|█▎        | 255/2000 [00:11<01:20, 21.73it/s]

Epoch 5:  13%|█▎        | 258/2000 [00:11<01:20, 21.74it/s]

Epoch 5:  13%|█▎        | 261/2000 [00:12<01:19, 21.74it/s]

Epoch 5:  13%|█▎        | 264/2000 [00:12<01:19, 21.74it/s]

Epoch 5:  13%|█▎        | 267/2000 [00:12<01:19, 21.74it/s]

Epoch 5:  14%|█▎        | 270/2000 [00:12<01:19, 21.74it/s]

Epoch 5:  14%|█▎        | 273/2000 [00:12<01:19, 21.75it/s]

Epoch 5:  14%|█▍        | 276/2000 [00:12<01:19, 21.75it/s]

Epoch 5:  14%|█▍        | 279/2000 [00:12<01:19, 21.73it/s]

Epoch 5:  14%|█▍        | 282/2000 [00:12<01:19, 21.74it/s]

Epoch 5:  14%|█▍        | 285/2000 [00:13<01:18, 21.75it/s]

Epoch 5:  14%|█▍        | 288/2000 [00:13<01:18, 21.75it/s]

Epoch 5:  15%|█▍        | 291/2000 [00:13<01:18, 21.75it/s]

Epoch 5:  15%|█▍        | 294/2000 [00:13<01:18, 21.76it/s]

Epoch 5:  15%|█▍        | 297/2000 [00:13<01:18, 21.76it/s]

Epoch 5:  15%|█▌        | 300/2000 [00:13<01:18, 21.78it/s]

Epoch 5:  15%|█▌        | 303/2000 [00:13<01:17, 21.77it/s]

Epoch 5:  15%|█▌        | 306/2000 [00:14<01:17, 21.77it/s]

Epoch 5:  15%|█▌        | 309/2000 [00:14<01:17, 21.76it/s]

Epoch 5:  16%|█▌        | 312/2000 [00:14<01:17, 21.76it/s]

Epoch 5:  16%|█▌        | 315/2000 [00:14<01:17, 21.76it/s]

Epoch 5:  16%|█▌        | 318/2000 [00:14<01:17, 21.75it/s]

Epoch 5:  16%|█▌        | 321/2000 [00:14<01:17, 21.75it/s]

Epoch 5:  16%|█▌        | 324/2000 [00:14<01:17, 21.74it/s]

Epoch 5:  16%|█▋        | 327/2000 [00:15<01:16, 21.75it/s]

Epoch 5:  16%|█▋        | 330/2000 [00:15<01:16, 21.75it/s]

Epoch 5:  17%|█▋        | 333/2000 [00:15<01:16, 21.74it/s]

Epoch 5:  17%|█▋        | 336/2000 [00:15<01:16, 21.74it/s]

Epoch 5:  17%|█▋        | 339/2000 [00:15<01:16, 21.75it/s]

Epoch 5:  17%|█▋        | 342/2000 [00:15<01:16, 21.74it/s]

Epoch 5:  17%|█▋        | 345/2000 [00:15<01:16, 21.76it/s]

Epoch 5:  17%|█▋        | 348/2000 [00:16<01:15, 21.76it/s]

Epoch 5:  18%|█▊        | 351/2000 [00:16<01:15, 21.76it/s]

Epoch 5:  18%|█▊        | 354/2000 [00:16<01:15, 21.75it/s]

Epoch 5:  18%|█▊        | 357/2000 [00:16<01:15, 21.76it/s]

Epoch 5:  18%|█▊        | 360/2000 [00:16<01:15, 21.75it/s]

Epoch 5:  18%|█▊        | 363/2000 [00:16<01:15, 21.75it/s]

Epoch 5:  18%|█▊        | 366/2000 [00:16<01:15, 21.76it/s]

Epoch 5:  18%|█▊        | 369/2000 [00:16<01:15, 21.74it/s]

Epoch 5:  19%|█▊        | 372/2000 [00:17<01:14, 21.74it/s]

Epoch 5:  19%|█▉        | 375/2000 [00:17<01:14, 21.73it/s]

Epoch 5:  19%|█▉        | 378/2000 [00:17<01:14, 21.73it/s]

Epoch 5:  19%|█▉        | 381/2000 [00:17<01:14, 21.73it/s]

Epoch 5:  19%|█▉        | 384/2000 [00:17<01:14, 21.74it/s]

Epoch 5:  19%|█▉        | 387/2000 [00:17<01:14, 21.75it/s]

Epoch 5:  20%|█▉        | 390/2000 [00:17<01:14, 21.76it/s]

Epoch 5:  20%|█▉        | 393/2000 [00:18<01:13, 21.76it/s]

Epoch 5:  20%|█▉        | 396/2000 [00:18<01:13, 21.76it/s]

Epoch 5:  20%|█▉        | 399/2000 [00:18<01:13, 21.75it/s]

Epoch 5:  20%|██        | 402/2000 [00:18<01:13, 21.75it/s]

Epoch 5:  20%|██        | 405/2000 [00:18<01:13, 21.75it/s]

Epoch 5:  20%|██        | 408/2000 [00:18<01:13, 21.76it/s]

Epoch 5:  21%|██        | 411/2000 [00:18<01:13, 21.76it/s]

Epoch 5:  21%|██        | 414/2000 [00:19<01:12, 21.76it/s]

Epoch 5:  21%|██        | 417/2000 [00:19<01:12, 21.75it/s]

Epoch 5:  21%|██        | 420/2000 [00:19<01:12, 21.75it/s]

Epoch 5:  21%|██        | 423/2000 [00:19<01:12, 21.75it/s]

Epoch 5:  21%|██▏       | 426/2000 [00:19<01:12, 21.76it/s]

Epoch 5:  21%|██▏       | 429/2000 [00:19<01:12, 21.76it/s]

Epoch 5:  22%|██▏       | 432/2000 [00:19<01:12, 21.75it/s]

Epoch 5:  22%|██▏       | 435/2000 [00:20<01:11, 21.75it/s]

Epoch 5:  22%|██▏       | 438/2000 [00:20<01:11, 21.75it/s]

Epoch 5:  22%|██▏       | 441/2000 [00:20<01:11, 21.73it/s]

Epoch 5:  22%|██▏       | 444/2000 [00:20<01:11, 21.71it/s]

Epoch 5:  22%|██▏       | 447/2000 [00:20<01:11, 21.72it/s]

Epoch 5:  22%|██▎       | 450/2000 [00:20<01:11, 21.74it/s]

Epoch 5:  23%|██▎       | 453/2000 [00:20<01:11, 21.74it/s]

Epoch 5:  23%|██▎       | 456/2000 [00:20<01:11, 21.73it/s]

Epoch 5:  23%|██▎       | 459/2000 [00:21<01:10, 21.74it/s]

Epoch 5:  23%|██▎       | 462/2000 [00:21<01:10, 21.73it/s]

Epoch 5:  23%|██▎       | 465/2000 [00:21<01:10, 21.73it/s]

Epoch 5:  23%|██▎       | 468/2000 [00:21<01:10, 21.75it/s]

Epoch 5:  24%|██▎       | 471/2000 [00:21<01:10, 21.73it/s]

Epoch 5:  24%|██▎       | 474/2000 [00:21<01:10, 21.71it/s]

Epoch 5:  24%|██▍       | 477/2000 [00:21<01:10, 21.72it/s]

Epoch 5:  24%|██▍       | 480/2000 [00:22<01:09, 21.73it/s]

Epoch 5:  24%|██▍       | 483/2000 [00:22<01:09, 21.74it/s]

Epoch 5:  24%|██▍       | 486/2000 [00:22<01:10, 21.55it/s]

Epoch 5:  24%|██▍       | 489/2000 [00:22<01:09, 21.60it/s]

Epoch 5:  25%|██▍       | 492/2000 [00:22<01:09, 21.65it/s]

Epoch 5:  25%|██▍       | 495/2000 [00:22<01:09, 21.68it/s]

Epoch 5:  25%|██▍       | 498/2000 [00:22<01:09, 21.69it/s]

Epoch 5:  25%|██▌       | 501/2000 [00:23<01:09, 21.70it/s]

Epoch 5:  25%|██▌       | 504/2000 [00:23<01:08, 21.71it/s]

Epoch 5:  25%|██▌       | 507/2000 [00:23<01:08, 21.73it/s]

Epoch 5:  26%|██▌       | 510/2000 [00:23<01:08, 21.74it/s]

Epoch 5:  26%|██▌       | 513/2000 [00:23<01:08, 21.76it/s]

Epoch 5:  26%|██▌       | 516/2000 [00:23<01:08, 21.76it/s]

Epoch 5:  26%|██▌       | 519/2000 [00:23<01:08, 21.75it/s]

Epoch 5:  26%|██▌       | 522/2000 [00:24<01:07, 21.75it/s]

Epoch 5:  26%|██▋       | 525/2000 [00:24<01:07, 21.75it/s]

Epoch 5:  26%|██▋       | 528/2000 [00:24<01:07, 21.65it/s]

Epoch 5:  27%|██▋       | 531/2000 [00:24<01:07, 21.67it/s]

Epoch 5:  27%|██▋       | 534/2000 [00:24<01:07, 21.68it/s]

Epoch 5:  27%|██▋       | 537/2000 [00:24<01:07, 21.69it/s]

Epoch 5:  27%|██▋       | 540/2000 [00:24<01:07, 21.70it/s]

Epoch 5:  27%|██▋       | 543/2000 [00:24<01:07, 21.72it/s]

Epoch 5:  27%|██▋       | 546/2000 [00:25<01:06, 21.72it/s]

Epoch 5:  27%|██▋       | 549/2000 [00:25<01:06, 21.73it/s]

Epoch 5:  28%|██▊       | 552/2000 [00:25<01:06, 21.73it/s]

Epoch 5:  28%|██▊       | 555/2000 [00:25<01:06, 21.72it/s]

Epoch 5:  28%|██▊       | 558/2000 [00:25<01:06, 21.73it/s]

Epoch 5:  28%|██▊       | 561/2000 [00:25<01:06, 21.73it/s]

Epoch 5:  28%|██▊       | 564/2000 [00:25<01:06, 21.73it/s]

Epoch 5:  28%|██▊       | 567/2000 [00:26<01:05, 21.71it/s]

Epoch 5:  28%|██▊       | 570/2000 [00:26<01:05, 21.73it/s]

Epoch 5:  29%|██▊       | 573/2000 [00:26<01:05, 21.72it/s]

Epoch 5:  29%|██▉       | 576/2000 [00:26<01:05, 21.72it/s]

Epoch 5:  29%|██▉       | 579/2000 [00:26<01:05, 21.73it/s]

Epoch 5:  29%|██▉       | 582/2000 [00:26<01:05, 21.73it/s]

Epoch 5:  29%|██▉       | 585/2000 [00:26<01:05, 21.73it/s]

Epoch 5:  29%|██▉       | 588/2000 [00:27<01:05, 21.72it/s]

Epoch 5:  30%|██▉       | 591/2000 [00:27<01:04, 21.72it/s]

Epoch 5:  30%|██▉       | 594/2000 [00:27<01:04, 21.73it/s]

Epoch 5:  30%|██▉       | 597/2000 [00:27<01:04, 21.73it/s]

Epoch 5:  30%|███       | 600/2000 [00:27<01:04, 21.74it/s]

Epoch 5:  30%|███       | 603/2000 [00:27<01:04, 21.74it/s]

Epoch 5:  30%|███       | 606/2000 [00:27<01:04, 21.75it/s]

Epoch 5:  30%|███       | 609/2000 [00:28<01:04, 21.72it/s]

Epoch 5:  31%|███       | 612/2000 [00:28<01:03, 21.74it/s]

Epoch 5:  31%|███       | 615/2000 [00:28<01:03, 21.74it/s]

Epoch 5:  31%|███       | 618/2000 [00:28<01:03, 21.75it/s]

Epoch 5:  31%|███       | 621/2000 [00:28<01:03, 21.76it/s]

Epoch 5:  31%|███       | 624/2000 [00:28<01:03, 21.60it/s]

Epoch 5:  31%|███▏      | 627/2000 [00:28<01:05, 20.99it/s]

Epoch 5:  32%|███▏      | 630/2000 [00:29<01:05, 21.00it/s]

Epoch 5:  32%|███▏      | 633/2000 [00:29<01:04, 21.17it/s]

Epoch 5:  32%|███▏      | 636/2000 [00:29<01:04, 21.30it/s]

Epoch 5:  32%|███▏      | 639/2000 [00:29<01:03, 21.42it/s]

Epoch 5:  32%|███▏      | 642/2000 [00:29<01:03, 21.51it/s]

Epoch 5:  32%|███▏      | 645/2000 [00:29<01:02, 21.57it/s]

Epoch 5:  32%|███▏      | 648/2000 [00:29<01:02, 21.63it/s]

Epoch 5:  33%|███▎      | 651/2000 [00:29<01:02, 21.66it/s]

Epoch 5:  33%|███▎      | 654/2000 [00:30<01:02, 21.69it/s]

Epoch 5:  33%|███▎      | 657/2000 [00:30<01:01, 21.70it/s]

Epoch 5:  33%|███▎      | 660/2000 [00:30<01:01, 21.71it/s]

Epoch 5:  33%|███▎      | 663/2000 [00:30<01:01, 21.72it/s]

Epoch 5:  33%|███▎      | 666/2000 [00:30<01:01, 21.73it/s]

Epoch 5:  33%|███▎      | 669/2000 [00:30<01:01, 21.73it/s]

Epoch 5:  34%|███▎      | 672/2000 [00:30<01:01, 21.73it/s]

Epoch 5:  34%|███▍      | 675/2000 [00:31<01:00, 21.73it/s]

Epoch 5:  34%|███▍      | 678/2000 [00:31<01:00, 21.74it/s]

Epoch 5:  34%|███▍      | 681/2000 [00:31<01:00, 21.74it/s]

Epoch 5:  34%|███▍      | 684/2000 [00:31<01:00, 21.75it/s]

Epoch 5:  34%|███▍      | 687/2000 [00:31<01:00, 21.76it/s]

Epoch 5:  34%|███▍      | 690/2000 [00:31<01:00, 21.76it/s]

Epoch 5:  35%|███▍      | 693/2000 [00:31<01:00, 21.76it/s]

Epoch 5:  35%|███▍      | 696/2000 [00:32<00:59, 21.76it/s]

Epoch 5:  35%|███▍      | 699/2000 [00:32<00:59, 21.74it/s]

Epoch 5:  35%|███▌      | 702/2000 [00:32<00:59, 21.75it/s]

Epoch 5:  35%|███▌      | 705/2000 [00:32<00:59, 21.75it/s]

Epoch 5:  35%|███▌      | 708/2000 [00:32<00:59, 21.76it/s]

Epoch 5:  36%|███▌      | 711/2000 [00:32<00:59, 21.75it/s]

Epoch 5:  36%|███▌      | 714/2000 [00:32<00:59, 21.76it/s]

Epoch 5:  36%|███▌      | 717/2000 [00:33<00:58, 21.75it/s]

Epoch 5:  36%|███▌      | 720/2000 [00:33<00:58, 21.75it/s]

Epoch 5:  36%|███▌      | 723/2000 [00:33<00:58, 21.74it/s]

Epoch 5:  36%|███▋      | 726/2000 [00:33<00:58, 21.75it/s]

Epoch 5:  36%|███▋      | 729/2000 [00:33<00:58, 21.75it/s]

Epoch 5:  37%|███▋      | 732/2000 [00:33<00:58, 21.75it/s]

Epoch 5:  37%|███▋      | 735/2000 [00:33<00:58, 21.75it/s]

Epoch 5:  37%|███▋      | 738/2000 [00:33<00:58, 21.74it/s]

Epoch 5:  37%|███▋      | 741/2000 [00:34<00:57, 21.75it/s]

Epoch 5:  37%|███▋      | 744/2000 [00:34<00:57, 21.74it/s]

Epoch 5:  37%|███▋      | 747/2000 [00:34<00:57, 21.75it/s]

Epoch 5:  38%|███▊      | 750/2000 [00:34<00:57, 21.76it/s]

Epoch 5:  38%|███▊      | 753/2000 [00:34<00:57, 21.75it/s]

Epoch 5:  38%|███▊      | 756/2000 [00:34<00:57, 21.76it/s]

Epoch 5:  38%|███▊      | 759/2000 [00:34<00:56, 21.77it/s]

Epoch 5:  38%|███▊      | 762/2000 [00:35<00:56, 21.77it/s]

Epoch 5:  38%|███▊      | 765/2000 [00:35<00:56, 21.77it/s]

Epoch 5:  38%|███▊      | 768/2000 [00:35<00:56, 21.76it/s]

Epoch 5:  39%|███▊      | 771/2000 [00:35<00:56, 21.77it/s]

Epoch 5:  39%|███▊      | 774/2000 [00:35<00:56, 21.76it/s]

Epoch 5:  39%|███▉      | 777/2000 [00:35<00:56, 21.75it/s]

Epoch 5:  39%|███▉      | 780/2000 [00:35<00:56, 21.67it/s]

Epoch 5:  39%|███▉      | 783/2000 [00:36<00:56, 21.67it/s]

Epoch 5:  39%|███▉      | 786/2000 [00:36<00:55, 21.70it/s]

Epoch 5:  39%|███▉      | 789/2000 [00:36<00:55, 21.70it/s]

Epoch 5:  40%|███▉      | 792/2000 [00:36<00:55, 21.71it/s]

Epoch 5:  40%|███▉      | 795/2000 [00:36<00:55, 21.71it/s]

Epoch 5:  40%|███▉      | 798/2000 [00:36<00:55, 21.72it/s]

Epoch 5:  40%|████      | 801/2000 [00:36<00:55, 21.75it/s]

Epoch 5:  40%|████      | 804/2000 [00:37<00:55, 21.74it/s]

Epoch 5:  40%|████      | 807/2000 [00:37<00:54, 21.74it/s]

Epoch 5:  40%|████      | 810/2000 [00:37<00:54, 21.74it/s]

Epoch 5:  41%|████      | 813/2000 [00:37<00:54, 21.73it/s]

Epoch 5:  41%|████      | 816/2000 [00:37<00:54, 21.74it/s]

Epoch 5:  41%|████      | 819/2000 [00:37<00:54, 21.72it/s]

Epoch 5:  41%|████      | 822/2000 [00:37<00:54, 21.74it/s]

Epoch 5:  41%|████▏     | 825/2000 [00:37<00:54, 21.73it/s]

Epoch 5:  41%|████▏     | 828/2000 [00:38<00:53, 21.73it/s]

Epoch 5:  42%|████▏     | 831/2000 [00:38<00:53, 21.73it/s]

Epoch 5:  42%|████▏     | 834/2000 [00:38<00:53, 21.74it/s]

Epoch 5:  42%|████▏     | 837/2000 [00:38<00:53, 21.73it/s]

Epoch 5:  42%|████▏     | 840/2000 [00:38<00:53, 21.75it/s]

Epoch 5:  42%|████▏     | 843/2000 [00:38<00:53, 21.75it/s]

Epoch 5:  42%|████▏     | 846/2000 [00:38<00:53, 21.74it/s]

Epoch 5:  42%|████▏     | 849/2000 [00:39<00:52, 21.74it/s]

Epoch 5:  43%|████▎     | 852/2000 [00:39<00:52, 21.75it/s]

Epoch 5:  43%|████▎     | 855/2000 [00:39<00:52, 21.74it/s]

Epoch 5:  43%|████▎     | 858/2000 [00:39<00:52, 21.75it/s]

Epoch 5:  43%|████▎     | 861/2000 [00:39<00:52, 21.74it/s]

Epoch 5:  43%|████▎     | 864/2000 [00:39<00:52, 21.73it/s]

Epoch 5:  43%|████▎     | 867/2000 [00:39<00:52, 21.71it/s]

Epoch 5:  44%|████▎     | 870/2000 [00:40<00:52, 21.71it/s]

Epoch 5:  44%|████▎     | 873/2000 [00:40<00:51, 21.73it/s]

Epoch 5:  44%|████▍     | 876/2000 [00:40<00:51, 21.74it/s]

Epoch 5:  44%|████▍     | 879/2000 [00:40<00:51, 21.73it/s]

Epoch 5:  44%|████▍     | 882/2000 [00:40<00:51, 21.75it/s]

Epoch 5:  44%|████▍     | 885/2000 [00:40<00:51, 21.76it/s]

Epoch 5:  44%|████▍     | 888/2000 [00:40<00:51, 21.74it/s]

Epoch 5:  45%|████▍     | 891/2000 [00:41<00:51, 21.73it/s]

Epoch 5:  45%|████▍     | 894/2000 [00:41<00:50, 21.74it/s]

Epoch 5:  45%|████▍     | 897/2000 [00:41<00:50, 21.76it/s]

Epoch 5:  45%|████▌     | 900/2000 [00:41<00:50, 21.76it/s]

Epoch 5:  45%|████▌     | 903/2000 [00:41<00:50, 21.76it/s]

Epoch 5:  45%|████▌     | 906/2000 [00:41<00:50, 21.76it/s]

Epoch 5:  45%|████▌     | 909/2000 [00:41<00:50, 21.77it/s]

Epoch 5:  46%|████▌     | 912/2000 [00:41<00:50, 21.75it/s]

Epoch 5:  46%|████▌     | 915/2000 [00:42<00:49, 21.76it/s]

Epoch 5:  46%|████▌     | 918/2000 [00:42<00:49, 21.76it/s]

Epoch 5:  46%|████▌     | 921/2000 [00:42<00:49, 21.76it/s]

Epoch 5:  46%|████▌     | 924/2000 [00:42<00:49, 21.74it/s]

Epoch 5:  46%|████▋     | 927/2000 [00:42<00:49, 21.74it/s]

Epoch 5:  46%|████▋     | 930/2000 [00:42<00:49, 21.75it/s]

Epoch 5:  47%|████▋     | 933/2000 [00:42<00:49, 21.75it/s]

Epoch 5:  47%|████▋     | 936/2000 [00:43<00:48, 21.75it/s]

Epoch 5:  47%|████▋     | 939/2000 [00:43<00:48, 21.75it/s]

Epoch 5:  47%|████▋     | 942/2000 [00:43<00:48, 21.75it/s]

Epoch 5:  47%|████▋     | 945/2000 [00:43<00:48, 21.76it/s]

Epoch 5:  47%|████▋     | 948/2000 [00:43<00:48, 21.76it/s]

Epoch 5:  48%|████▊     | 951/2000 [00:43<00:48, 21.67it/s]

Epoch 5:  48%|████▊     | 954/2000 [00:43<00:48, 21.69it/s]

Epoch 5:  48%|████▊     | 957/2000 [00:44<00:48, 21.70it/s]

Epoch 5:  48%|████▊     | 960/2000 [00:44<00:47, 21.71it/s]

Epoch 5:  48%|████▊     | 963/2000 [00:44<00:47, 21.70it/s]

Epoch 5:  48%|████▊     | 966/2000 [00:44<00:47, 21.72it/s]

Epoch 5:  48%|████▊     | 969/2000 [00:44<00:47, 21.73it/s]

Epoch 5:  49%|████▊     | 972/2000 [00:44<00:47, 21.73it/s]

Epoch 5:  49%|████▉     | 975/2000 [00:44<00:47, 21.72it/s]

Epoch 5:  49%|████▉     | 978/2000 [00:45<00:47, 21.72it/s]

Epoch 5:  49%|████▉     | 981/2000 [00:45<00:46, 21.71it/s]

Epoch 5:  49%|████▉     | 984/2000 [00:45<00:46, 21.72it/s]

Epoch 5:  49%|████▉     | 987/2000 [00:45<00:46, 21.71it/s]

Epoch 5:  50%|████▉     | 990/2000 [00:45<00:46, 21.72it/s]

Epoch 5:  50%|████▉     | 993/2000 [00:45<00:46, 21.72it/s]

Epoch 5:  50%|████▉     | 996/2000 [00:45<00:46, 21.74it/s]

Epoch 5:  50%|████▉     | 999/2000 [00:45<00:46, 21.72it/s]

Epoch 5:  50%|█████     | 1002/2000 [00:46<00:45, 21.73it/s]

Epoch 5:  50%|█████     | 1005/2000 [00:46<00:45, 21.73it/s]

Epoch 5:  50%|█████     | 1008/2000 [00:46<00:45, 21.75it/s]

Epoch 5:  51%|█████     | 1011/2000 [00:46<00:45, 21.74it/s]

Epoch 5:  51%|█████     | 1014/2000 [00:46<00:45, 21.73it/s]

Epoch 5:  51%|█████     | 1017/2000 [00:46<00:45, 21.73it/s]

Epoch 5:  51%|█████     | 1020/2000 [00:46<00:45, 21.72it/s]

Epoch 5:  51%|█████     | 1023/2000 [00:47<00:44, 21.74it/s]

Epoch 5:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.72it/s]

Epoch 5:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.74it/s]

Epoch 5:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.77it/s]

Epoch 5:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.79it/s]

Epoch 5:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.80it/s]

Epoch 5:  52%|█████▏    | 1041/2000 [00:47<00:43, 21.82it/s]

Epoch 5:  52%|█████▏    | 1044/2000 [00:48<00:43, 21.82it/s]

Epoch 5:  52%|█████▏    | 1047/2000 [00:48<00:43, 21.83it/s]

Epoch 5:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.82it/s]

Epoch 5:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.83it/s]

Epoch 5:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.85it/s]

Epoch 5:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.83it/s]

Epoch 5:  53%|█████▎    | 1062/2000 [00:48<00:42, 21.84it/s]

Epoch 5:  53%|█████▎    | 1065/2000 [00:49<00:42, 21.83it/s]

Epoch 5:  53%|█████▎    | 1068/2000 [00:49<00:42, 21.81it/s]

Epoch 5:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.83it/s]

Epoch 5:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.84it/s]

Epoch 5:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.85it/s]

Epoch 5:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.86it/s]

Epoch 5:  54%|█████▍    | 1083/2000 [00:49<00:41, 21.86it/s]

Epoch 5:  54%|█████▍    | 1086/2000 [00:49<00:41, 21.86it/s]

Epoch 5:  54%|█████▍    | 1089/2000 [00:50<00:41, 21.86it/s]

Epoch 5:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.86it/s]

Epoch 5:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.87it/s]

Epoch 5:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.87it/s]

Epoch 5:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.86it/s]

Epoch 5:  55%|█████▌    | 1104/2000 [00:50<00:40, 21.86it/s]

Epoch 5:  55%|█████▌    | 1107/2000 [00:50<00:40, 21.86it/s]

Epoch 5:  56%|█████▌    | 1110/2000 [00:51<00:40, 21.86it/s]

Epoch 5:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.86it/s]

Epoch 5:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.85it/s]

Epoch 5:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.84it/s]

Epoch 5:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.84it/s]

Epoch 5:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.83it/s]

Epoch 5:  56%|█████▋    | 1128/2000 [00:51<00:39, 21.85it/s]

Epoch 5:  57%|█████▋    | 1131/2000 [00:52<00:39, 21.84it/s]

Epoch 5:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.84it/s]

Epoch 5:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.83it/s]

Epoch 5:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.83it/s]

Epoch 5:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.85it/s]

Epoch 5:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.86it/s]

Epoch 5:  57%|█████▋    | 1149/2000 [00:52<00:38, 21.85it/s]

Epoch 5:  58%|█████▊    | 1152/2000 [00:52<00:38, 21.86it/s]

Epoch 5:  58%|█████▊    | 1155/2000 [00:53<00:38, 21.86it/s]

Epoch 5:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.87it/s]

Epoch 5:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.87it/s]

Epoch 5:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.86it/s]

Epoch 5:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.87it/s]

Epoch 5:  58%|█████▊    | 1170/2000 [00:53<00:37, 21.86it/s]

Epoch 5:  59%|█████▊    | 1173/2000 [00:53<00:37, 21.86it/s]

Epoch 5:  59%|█████▉    | 1176/2000 [00:54<00:37, 21.86it/s]

Epoch 5:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.85it/s]

Epoch 5:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.84it/s]

Epoch 5:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.85it/s]

Epoch 5:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.84it/s]

Epoch 5:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.83it/s]

Epoch 5:  60%|█████▉    | 1194/2000 [00:54<00:36, 21.84it/s]

Epoch 5:  60%|█████▉    | 1197/2000 [00:55<00:36, 21.83it/s]

Epoch 5:  60%|██████    | 1200/2000 [00:55<00:36, 21.84it/s]

Epoch 5:  60%|██████    | 1203/2000 [00:55<00:36, 21.86it/s]

Epoch 5:  60%|██████    | 1206/2000 [00:55<00:36, 21.85it/s]

Epoch 5:  60%|██████    | 1209/2000 [00:55<00:36, 21.85it/s]

Epoch 5:  61%|██████    | 1212/2000 [00:55<00:36, 21.86it/s]

Epoch 5:  61%|██████    | 1215/2000 [00:55<00:35, 21.87it/s]

Epoch 5:  61%|██████    | 1218/2000 [00:56<00:35, 21.85it/s]

Epoch 5:  61%|██████    | 1221/2000 [00:56<00:35, 21.84it/s]

Epoch 5:  61%|██████    | 1224/2000 [00:56<00:35, 21.86it/s]

Epoch 5:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.85it/s]

Epoch 5:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.87it/s]

Epoch 5:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.87it/s]

Epoch 5:  62%|██████▏   | 1236/2000 [00:56<00:34, 21.86it/s]

Epoch 5:  62%|██████▏   | 1239/2000 [00:56<00:34, 21.86it/s]

Epoch 5:  62%|██████▏   | 1242/2000 [00:57<00:34, 21.86it/s]

Epoch 5:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.85it/s]

Epoch 5:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.84it/s]

Epoch 5:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.84it/s]

Epoch 5:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.85it/s]

Epoch 5:  63%|██████▎   | 1257/2000 [00:57<00:33, 21.86it/s]

Epoch 5:  63%|██████▎   | 1260/2000 [00:57<00:33, 21.86it/s]

Epoch 5:  63%|██████▎   | 1263/2000 [00:58<00:33, 21.86it/s]

Epoch 5:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.86it/s]

Epoch 5:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.85it/s]

Epoch 5:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.87it/s]

Epoch 5:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.88it/s]

Epoch 5:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.86it/s]

Epoch 5:  64%|██████▍   | 1281/2000 [00:58<00:32, 21.86it/s]

Epoch 5:  64%|██████▍   | 1284/2000 [00:59<00:32, 21.86it/s]

Epoch 5:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.84it/s]

Epoch 5:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.80it/s]

Epoch 5:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.81it/s]

Epoch 5:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.82it/s]

Epoch 5:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.84it/s]

Epoch 5:  65%|██████▌   | 1302/2000 [00:59<00:31, 21.86it/s]

Epoch 5:  65%|██████▌   | 1305/2000 [00:59<00:31, 21.84it/s]

Epoch 5:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.85it/s]

Epoch 5:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.86it/s]

Epoch 5:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.86it/s]

Epoch 5:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.85it/s]

Epoch 5:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.86it/s]

Epoch 5:  66%|██████▌   | 1323/2000 [01:00<00:30, 21.86it/s]

Epoch 5:  66%|██████▋   | 1326/2000 [01:00<00:30, 21.86it/s]

Epoch 5:  66%|██████▋   | 1329/2000 [01:01<00:30, 21.88it/s]

Epoch 5:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.88it/s]

Epoch 5:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.88it/s]

Epoch 5:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.73it/s]

Epoch 5:  67%|██████▋   | 1341/2000 [01:01<00:31, 21.14it/s]

Epoch 5:  67%|██████▋   | 1344/2000 [01:01<00:31, 21.14it/s]

Epoch 5:  67%|██████▋   | 1347/2000 [01:01<00:30, 21.30it/s]

Epoch 5:  68%|██████▊   | 1350/2000 [01:02<00:30, 21.41it/s]

Epoch 5:  68%|██████▊   | 1353/2000 [01:02<00:30, 21.56it/s]

Epoch 5:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.64it/s]

Epoch 5:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.71it/s]

Epoch 5:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.77it/s]

Epoch 5:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.80it/s]

Epoch 5:  68%|██████▊   | 1368/2000 [01:02<00:28, 21.81it/s]

Epoch 5:  69%|██████▊   | 1371/2000 [01:03<00:28, 21.81it/s]

Epoch 5:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.84it/s]

Epoch 5:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.84it/s]

Epoch 5:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.83it/s]

Epoch 5:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.83it/s]

Epoch 5:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.84it/s]

Epoch 5:  69%|██████▉   | 1389/2000 [01:03<00:27, 21.85it/s]

Epoch 5:  70%|██████▉   | 1392/2000 [01:04<00:27, 21.85it/s]

Epoch 5:  70%|██████▉   | 1395/2000 [01:04<00:27, 21.85it/s]

Epoch 5:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.85it/s]

Epoch 5:  70%|███████   | 1401/2000 [01:04<00:27, 21.85it/s]

Epoch 5:  70%|███████   | 1404/2000 [01:04<00:27, 21.86it/s]

Epoch 5:  70%|███████   | 1407/2000 [01:04<00:27, 21.86it/s]

Epoch 5:  70%|███████   | 1410/2000 [01:04<00:26, 21.87it/s]

Epoch 5:  71%|███████   | 1413/2000 [01:04<00:26, 21.85it/s]

Epoch 5:  71%|███████   | 1416/2000 [01:05<00:26, 21.85it/s]

Epoch 5:  71%|███████   | 1419/2000 [01:05<00:26, 21.83it/s]

Epoch 5:  71%|███████   | 1422/2000 [01:05<00:26, 21.85it/s]

Epoch 5:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.84it/s]

Epoch 5:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.84it/s]

Epoch 5:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.83it/s]

Epoch 5:  72%|███████▏  | 1434/2000 [01:05<00:25, 21.84it/s]

Epoch 5:  72%|███████▏  | 1437/2000 [01:06<00:25, 21.83it/s]

Epoch 5:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.84it/s]

Epoch 5:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.84it/s]

Epoch 5:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.84it/s]

Epoch 5:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.82it/s]

Epoch 5:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.82it/s]

Epoch 5:  73%|███████▎  | 1455/2000 [01:06<00:24, 21.83it/s]

Epoch 5:  73%|███████▎  | 1458/2000 [01:07<00:24, 21.81it/s]

Epoch 5:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.80it/s]

Epoch 5:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.81it/s]

Epoch 5:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.82it/s]

Epoch 5:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.83it/s]

Epoch 5:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.84it/s]

Epoch 5:  74%|███████▍  | 1476/2000 [01:07<00:23, 21.84it/s]

Epoch 5:  74%|███████▍  | 1479/2000 [01:07<00:23, 21.82it/s]

Epoch 5:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.83it/s]

Epoch 5:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.84it/s]

Epoch 5:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.83it/s]

Epoch 5:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.83it/s]

Epoch 5:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.83it/s]

Epoch 5:  75%|███████▍  | 1497/2000 [01:08<00:23, 21.83it/s]

Epoch 5:  75%|███████▌  | 1500/2000 [01:08<00:22, 21.84it/s]

Epoch 5:  75%|███████▌  | 1503/2000 [01:09<00:22, 21.84it/s]

Epoch 5:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.84it/s]

Epoch 5:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.84it/s]

Epoch 5:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.84it/s]

Epoch 5:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.83it/s]

Epoch 5:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.83it/s]

Epoch 5:  76%|███████▌  | 1521/2000 [01:09<00:21, 21.83it/s]

Epoch 5:  76%|███████▌  | 1524/2000 [01:10<00:21, 21.82it/s]

Epoch 5:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.83it/s]

Epoch 5:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.82it/s]

Epoch 5:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.83it/s]

Epoch 5:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.82it/s]

Epoch 5:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.82it/s]

Epoch 5:  77%|███████▋  | 1542/2000 [01:10<00:20, 21.82it/s]

Epoch 5:  77%|███████▋  | 1545/2000 [01:11<00:20, 21.81it/s]

Epoch 5:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.81it/s]

Epoch 5:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.82it/s]

Epoch 5:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.82it/s]

Epoch 5:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.83it/s]

Epoch 5:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.81it/s]

Epoch 5:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.79it/s]

Epoch 5:  78%|███████▊  | 1566/2000 [01:11<00:19, 21.81it/s]

Epoch 5:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.80it/s]

Epoch 5:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.79it/s]

Epoch 5:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.81it/s]

Epoch 5:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.83it/s]

Epoch 5:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.84it/s]

Epoch 5:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.83it/s]

Epoch 5:  79%|███████▉  | 1587/2000 [01:12<00:18, 21.83it/s]

Epoch 5:  80%|███████▉  | 1590/2000 [01:13<00:18, 21.82it/s]

Epoch 5:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.83it/s]

Epoch 5:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.84it/s]

Epoch 5:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.85it/s]

Epoch 5:  80%|████████  | 1602/2000 [01:13<00:18, 21.84it/s]

Epoch 5:  80%|████████  | 1605/2000 [01:13<00:18, 21.83it/s]

Epoch 5:  80%|████████  | 1608/2000 [01:13<00:17, 21.85it/s]

Epoch 5:  81%|████████  | 1611/2000 [01:14<00:17, 21.85it/s]

Epoch 5:  81%|████████  | 1614/2000 [01:14<00:17, 21.86it/s]

Epoch 5:  81%|████████  | 1617/2000 [01:14<00:17, 21.86it/s]

Epoch 5:  81%|████████  | 1620/2000 [01:14<00:17, 21.88it/s]

Epoch 5:  81%|████████  | 1623/2000 [01:14<00:17, 21.86it/s]

Epoch 5:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.86it/s]

Epoch 5:  81%|████████▏ | 1629/2000 [01:14<00:16, 21.86it/s]

Epoch 5:  82%|████████▏ | 1632/2000 [01:14<00:16, 21.86it/s]

Epoch 5:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.87it/s]

Epoch 5:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.88it/s]

Epoch 5:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.88it/s]

Epoch 5:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.86it/s]

Epoch 5:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.86it/s]

Epoch 5:  82%|████████▎ | 1650/2000 [01:15<00:16, 21.86it/s]

Epoch 5:  83%|████████▎ | 1653/2000 [01:15<00:15, 21.87it/s]

Epoch 5:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.87it/s]

Epoch 5:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.86it/s]

Epoch 5:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.85it/s]

Epoch 5:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.86it/s]

Epoch 5:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.87it/s]

Epoch 5:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.86it/s]

Epoch 5:  84%|████████▎ | 1674/2000 [01:16<00:14, 21.86it/s]

Epoch 5:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.85it/s]

Epoch 5:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.85it/s]

Epoch 5:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.87it/s]

Epoch 5:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.86it/s]

Epoch 5:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.85it/s]

Epoch 5:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.85it/s]

Epoch 5:  85%|████████▍ | 1695/2000 [01:17<00:13, 21.85it/s]

Epoch 5:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.85it/s]

Epoch 5:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.85it/s]

Epoch 5:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.74it/s]

Epoch 5:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.72it/s]

Epoch 5:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.71it/s]

Epoch 5:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.70it/s]

Epoch 5:  86%|████████▌ | 1716/2000 [01:18<00:13, 21.71it/s]

Epoch 5:  86%|████████▌ | 1719/2000 [01:18<00:12, 21.69it/s]

Epoch 5:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.70it/s]

Epoch 5:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.68it/s]

Epoch 5:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.69it/s]

Epoch 5:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.69it/s]

Epoch 5:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.70it/s]

Epoch 5:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.69it/s]

Epoch 5:  87%|████████▋ | 1740/2000 [01:19<00:11, 21.70it/s]

Epoch 5:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.70it/s]

Epoch 5:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.70it/s]

Epoch 5:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.69it/s]

Epoch 5:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.71it/s]

Epoch 5:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.71it/s]

Epoch 5:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.71it/s]

Epoch 5:  88%|████████▊ | 1761/2000 [01:20<00:11, 21.71it/s]

Epoch 5:  88%|████████▊ | 1764/2000 [01:21<00:10, 21.71it/s]

Epoch 5:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.72it/s]

Epoch 5:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.73it/s]

Epoch 5:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.71it/s]

Epoch 5:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.70it/s]

Epoch 5:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.68it/s]

Epoch 5:  89%|████████▉ | 1782/2000 [01:21<00:10, 21.69it/s]

Epoch 5:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.68it/s]

Epoch 5:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.70it/s]

Epoch 5:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.72it/s]

Epoch 5:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.72it/s]

Epoch 5:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.73it/s]

Epoch 5:  90%|█████████ | 1800/2000 [01:22<00:09, 21.72it/s]

Epoch 5:  90%|█████████ | 1803/2000 [01:22<00:09, 21.72it/s]

Epoch 5:  90%|█████████ | 1806/2000 [01:22<00:08, 21.72it/s]

Epoch 5:  90%|█████████ | 1809/2000 [01:23<00:08, 21.72it/s]

Epoch 5:  91%|█████████ | 1812/2000 [01:23<00:08, 21.72it/s]

Epoch 5:  91%|█████████ | 1815/2000 [01:23<00:08, 21.73it/s]

Epoch 5:  91%|█████████ | 1818/2000 [01:23<00:08, 21.72it/s]

Epoch 5:  91%|█████████ | 1821/2000 [01:23<00:08, 21.72it/s]

Epoch 5:  91%|█████████ | 1824/2000 [01:23<00:08, 21.71it/s]

Epoch 5:  91%|█████████▏| 1827/2000 [01:23<00:07, 21.72it/s]

Epoch 5:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.72it/s]

Epoch 5:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.32it/s]

Epoch 5:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.42it/s]

Epoch 5:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.50it/s]

Epoch 5:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.55it/s]

Epoch 5:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.59it/s]

Epoch 5:  92%|█████████▏| 1848/2000 [01:24<00:07, 21.65it/s]

Epoch 5:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.69it/s]

Epoch 5:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.68it/s]

Epoch 5:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.73it/s]

Epoch 5:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.78it/s]

Epoch 5:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.81it/s]

Epoch 5:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.84it/s]

Epoch 5:  93%|█████████▎| 1869/2000 [01:25<00:05, 21.85it/s]

Epoch 5:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.84it/s]

Epoch 5:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.84it/s]

Epoch 5:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.84it/s]

Epoch 5:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.84it/s]

Epoch 5:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.85it/s]

Epoch 5:  94%|█████████▍| 1887/2000 [01:26<00:05, 21.86it/s]

Epoch 5:  94%|█████████▍| 1890/2000 [01:26<00:05, 21.87it/s]

Epoch 5:  95%|█████████▍| 1893/2000 [01:26<00:04, 21.84it/s]

Epoch 5:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.85it/s]

Epoch 5:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.85it/s]

Epoch 5:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.86it/s]

Epoch 5:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.86it/s]

Epoch 5:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.86it/s]

Epoch 5:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.87it/s]

Epoch 5:  96%|█████████▌| 1914/2000 [01:27<00:03, 21.88it/s]

Epoch 5:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.87it/s]

Epoch 5:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.89it/s]

Epoch 5:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.86it/s]

Epoch 5:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.86it/s]

Epoch 5:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.87it/s]

Epoch 5:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.87it/s]

Epoch 5:  97%|█████████▋| 1935/2000 [01:28<00:02, 21.86it/s]

Epoch 5:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.86it/s]

Epoch 5:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.87it/s]

Epoch 5:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.86it/s]

Epoch 5:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.87it/s]

Epoch 5:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.86it/s]

Epoch 5:  98%|█████████▊| 1953/2000 [01:29<00:02, 21.87it/s]

Epoch 5:  98%|█████████▊| 1956/2000 [01:29<00:02, 21.88it/s]

Epoch 5:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.87it/s]

Epoch 5:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.87it/s]

Epoch 5:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.86it/s]

Epoch 5:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.87it/s]

Epoch 5:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.88it/s]

Epoch 5:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.88it/s]

Epoch 5:  99%|█████████▉| 1977/2000 [01:30<00:01, 21.86it/s]

Epoch 5:  99%|█████████▉| 1980/2000 [01:30<00:00, 21.85it/s]

Epoch 5:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.85it/s]

Epoch 5:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.86it/s]

Epoch 5:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.87it/s]

Epoch 5: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.88it/s]

Epoch 5: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.87it/s]

Epoch 5: 100%|█████████▉| 1998/2000 [01:31<00:00, 21.88it/s]

Epoch 5: loss=0.3873, val_proxy=0.4981

Epoch 6:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 6:   0%|          | 3/2000 [00:00<01:34, 21.04it/s]

Epoch 6:   0%|          | 6/2000 [00:00<01:33, 21.23it/s]

Epoch 6:   0%|          | 9/2000 [00:00<01:33, 21.31it/s]

Epoch 6:   1%|          | 12/2000 [00:00<01:33, 21.37it/s]

Epoch 6:   1%|          | 15/2000 [00:00<01:32, 21.39it/s]

Epoch 6:   1%|          | 18/2000 [00:00<01:32, 21.41it/s]

Epoch 6:   1%|          | 21/2000 [00:00<01:32, 21.45it/s]

Epoch 6:   1%|          | 24/2000 [00:01<01:32, 21.45it/s]

Epoch 6:   1%|▏         | 27/2000 [00:01<01:32, 21.44it/s]

Epoch 6:   2%|▏         | 30/2000 [00:01<01:31, 21.43it/s]

Epoch 6:   2%|▏         | 33/2000 [00:01<01:31, 21.41it/s]

Epoch 6:   2%|▏         | 36/2000 [00:01<01:31, 21.36it/s]

Epoch 6:   2%|▏         | 39/2000 [00:01<01:31, 21.39it/s]

Epoch 6:   2%|▏         | 42/2000 [00:01<01:31, 21.43it/s]

Epoch 6:   2%|▏         | 45/2000 [00:02<01:31, 21.43it/s]

Epoch 6:   2%|▏         | 48/2000 [00:02<01:31, 21.29it/s]

Epoch 6:   3%|▎         | 51/2000 [00:02<01:34, 20.72it/s]

Epoch 6:   3%|▎         | 54/2000 [00:02<01:32, 20.93it/s]

Epoch 6:   3%|▎         | 57/2000 [00:02<01:32, 21.09it/s]

Epoch 6:   3%|▎         | 60/2000 [00:02<01:31, 21.22it/s]

Epoch 6:   3%|▎         | 63/2000 [00:02<01:30, 21.29it/s]

Epoch 6:   3%|▎         | 66/2000 [00:03<01:30, 21.32it/s]

Epoch 6:   3%|▎         | 69/2000 [00:03<01:30, 21.37it/s]

Epoch 6:   4%|▎         | 72/2000 [00:03<01:30, 21.39it/s]

Epoch 6:   4%|▍         | 75/2000 [00:03<01:29, 21.42it/s]

Epoch 6:   4%|▍         | 78/2000 [00:03<01:29, 21.43it/s]

Epoch 6:   4%|▍         | 81/2000 [00:03<01:29, 21.45it/s]

Epoch 6:   4%|▍         | 84/2000 [00:03<01:29, 21.45it/s]

Epoch 6:   4%|▍         | 87/2000 [00:04<01:29, 21.47it/s]

Epoch 6:   4%|▍         | 90/2000 [00:04<01:28, 21.49it/s]

Epoch 6:   5%|▍         | 93/2000 [00:04<01:28, 21.51it/s]

Epoch 6:   5%|▍         | 96/2000 [00:04<01:28, 21.52it/s]

Epoch 6:   5%|▍         | 99/2000 [00:04<01:28, 21.54it/s]

Epoch 6:   5%|▌         | 102/2000 [00:04<01:28, 21.53it/s]

Epoch 6:   5%|▌         | 105/2000 [00:04<01:27, 21.54it/s]

Epoch 6:   5%|▌         | 108/2000 [00:05<01:27, 21.56it/s]

Epoch 6:   6%|▌         | 111/2000 [00:05<01:27, 21.56it/s]

Epoch 6:   6%|▌         | 114/2000 [00:05<01:27, 21.57it/s]

Epoch 6:   6%|▌         | 117/2000 [00:05<01:27, 21.58it/s]

Epoch 6:   6%|▌         | 120/2000 [00:05<01:27, 21.56it/s]

Epoch 6:   6%|▌         | 123/2000 [00:05<01:27, 21.56it/s]

Epoch 6:   6%|▋         | 126/2000 [00:05<01:26, 21.56it/s]

Epoch 6:   6%|▋         | 129/2000 [00:06<01:26, 21.55it/s]

Epoch 6:   7%|▋         | 132/2000 [00:06<01:26, 21.54it/s]

Epoch 6:   7%|▋         | 135/2000 [00:06<01:26, 21.56it/s]

Epoch 6:   7%|▋         | 138/2000 [00:06<01:26, 21.56it/s]

Epoch 6:   7%|▋         | 141/2000 [00:06<01:26, 21.56it/s]

Epoch 6:   7%|▋         | 144/2000 [00:06<01:26, 21.56it/s]

Epoch 6:   7%|▋         | 147/2000 [00:06<01:25, 21.56it/s]

Epoch 6:   8%|▊         | 150/2000 [00:06<01:25, 21.57it/s]

Epoch 6:   8%|▊         | 153/2000 [00:07<01:25, 21.57it/s]

Epoch 6:   8%|▊         | 156/2000 [00:07<01:25, 21.56it/s]

Epoch 6:   8%|▊         | 159/2000 [00:07<01:25, 21.59it/s]

Epoch 6:   8%|▊         | 162/2000 [00:07<01:25, 21.59it/s]

Epoch 6:   8%|▊         | 165/2000 [00:07<01:25, 21.58it/s]

Epoch 6:   8%|▊         | 168/2000 [00:07<01:24, 21.57it/s]

Epoch 6:   9%|▊         | 171/2000 [00:07<01:24, 21.58it/s]

Epoch 6:   9%|▊         | 174/2000 [00:08<01:24, 21.59it/s]

Epoch 6:   9%|▉         | 177/2000 [00:08<01:24, 21.58it/s]

Epoch 6:   9%|▉         | 180/2000 [00:08<01:24, 21.58it/s]

Epoch 6:   9%|▉         | 183/2000 [00:08<01:24, 21.59it/s]

Epoch 6:   9%|▉         | 186/2000 [00:08<01:23, 21.60it/s]

Epoch 6:   9%|▉         | 189/2000 [00:08<01:23, 21.60it/s]

Epoch 6:  10%|▉         | 192/2000 [00:08<01:23, 21.59it/s]

Epoch 6:  10%|▉         | 195/2000 [00:09<01:23, 21.58it/s]

Epoch 6:  10%|▉         | 198/2000 [00:09<01:23, 21.58it/s]

Epoch 6:  10%|█         | 201/2000 [00:09<01:23, 21.57it/s]

Epoch 6:  10%|█         | 204/2000 [00:09<01:23, 21.57it/s]

Epoch 6:  10%|█         | 207/2000 [00:09<01:23, 21.57it/s]

Epoch 6:  10%|█         | 210/2000 [00:09<01:22, 21.58it/s]

Epoch 6:  11%|█         | 213/2000 [00:09<01:22, 21.59it/s]

Epoch 6:  11%|█         | 216/2000 [00:10<01:22, 21.58it/s]

Epoch 6:  11%|█         | 219/2000 [00:10<01:22, 21.58it/s]

Epoch 6:  11%|█         | 222/2000 [00:10<01:22, 21.59it/s]

Epoch 6:  11%|█▏        | 225/2000 [00:10<01:22, 21.59it/s]

Epoch 6:  11%|█▏        | 228/2000 [00:10<01:22, 21.57it/s]

Epoch 6:  12%|█▏        | 231/2000 [00:10<01:22, 21.56it/s]

Epoch 6:  12%|█▏        | 234/2000 [00:10<01:21, 21.57it/s]

Epoch 6:  12%|█▏        | 237/2000 [00:11<01:21, 21.57it/s]

Epoch 6:  12%|█▏        | 240/2000 [00:11<01:21, 21.58it/s]

Epoch 6:  12%|█▏        | 243/2000 [00:11<01:21, 21.58it/s]

Epoch 6:  12%|█▏        | 246/2000 [00:11<01:21, 21.59it/s]

Epoch 6:  12%|█▏        | 249/2000 [00:11<01:21, 21.59it/s]

Epoch 6:  13%|█▎        | 252/2000 [00:11<01:20, 21.59it/s]

Epoch 6:  13%|█▎        | 255/2000 [00:11<01:20, 21.58it/s]

Epoch 6:  13%|█▎        | 258/2000 [00:12<01:20, 21.59it/s]

Epoch 6:  13%|█▎        | 261/2000 [00:12<01:20, 21.59it/s]

Epoch 6:  13%|█▎        | 264/2000 [00:12<01:20, 21.58it/s]

Epoch 6:  13%|█▎        | 267/2000 [00:12<01:20, 21.59it/s]

Epoch 6:  14%|█▎        | 270/2000 [00:12<01:20, 21.60it/s]

Epoch 6:  14%|█▎        | 273/2000 [00:12<01:19, 21.60it/s]

Epoch 6:  14%|█▍        | 276/2000 [00:12<01:19, 21.60it/s]

Epoch 6:  14%|█▍        | 279/2000 [00:12<01:19, 21.60it/s]

Epoch 6:  14%|█▍        | 282/2000 [00:13<01:19, 21.60it/s]

Epoch 6:  14%|█▍        | 285/2000 [00:13<01:19, 21.60it/s]

Epoch 6:  14%|█▍        | 288/2000 [00:13<01:19, 21.57it/s]

Epoch 6:  15%|█▍        | 291/2000 [00:13<01:19, 21.56it/s]

Epoch 6:  15%|█▍        | 294/2000 [00:13<01:19, 21.57it/s]

Epoch 6:  15%|█▍        | 297/2000 [00:13<01:18, 21.57it/s]

Epoch 6:  15%|█▌        | 300/2000 [00:13<01:18, 21.58it/s]

Epoch 6:  15%|█▌        | 303/2000 [00:14<01:18, 21.57it/s]

Epoch 6:  15%|█▌        | 306/2000 [00:14<01:18, 21.58it/s]

Epoch 6:  15%|█▌        | 309/2000 [00:14<01:18, 21.57it/s]

Epoch 6:  16%|█▌        | 312/2000 [00:14<01:18, 21.58it/s]

Epoch 6:  16%|█▌        | 315/2000 [00:14<01:18, 21.57it/s]

Epoch 6:  16%|█▌        | 318/2000 [00:14<01:18, 21.56it/s]

Epoch 6:  16%|█▌        | 321/2000 [00:14<01:17, 21.57it/s]

Epoch 6:  16%|█▌        | 324/2000 [00:15<01:17, 21.57it/s]

Epoch 6:  16%|█▋        | 327/2000 [00:15<01:17, 21.58it/s]

Epoch 6:  16%|█▋        | 330/2000 [00:15<01:17, 21.59it/s]

Epoch 6:  17%|█▋        | 333/2000 [00:15<01:17, 21.58it/s]

Epoch 6:  17%|█▋        | 336/2000 [00:15<01:17, 21.58it/s]

Epoch 6:  17%|█▋        | 339/2000 [00:15<01:16, 21.58it/s]

Epoch 6:  17%|█▋        | 342/2000 [00:15<01:16, 21.58it/s]

Epoch 6:  17%|█▋        | 345/2000 [00:16<01:16, 21.60it/s]

Epoch 6:  17%|█▋        | 348/2000 [00:16<01:16, 21.61it/s]

Epoch 6:  18%|█▊        | 351/2000 [00:16<01:16, 21.60it/s]

Epoch 6:  18%|█▊        | 354/2000 [00:16<01:16, 21.59it/s]

Epoch 6:  18%|█▊        | 357/2000 [00:16<01:16, 21.42it/s]

Epoch 6:  18%|█▊        | 360/2000 [00:16<01:17, 21.15it/s]

Epoch 6:  18%|█▊        | 363/2000 [00:16<01:16, 21.31it/s]

Epoch 6:  18%|█▊        | 366/2000 [00:17<01:16, 21.45it/s]

Epoch 6:  18%|█▊        | 369/2000 [00:17<01:15, 21.55it/s]

Epoch 6:  19%|█▊        | 372/2000 [00:17<01:15, 21.44it/s]

Epoch 6:  19%|█▉        | 375/2000 [00:17<01:15, 21.52it/s]

Epoch 6:  19%|█▉        | 378/2000 [00:17<01:15, 21.59it/s]

Epoch 6:  19%|█▉        | 381/2000 [00:17<01:14, 21.62it/s]

Epoch 6:  19%|█▉        | 384/2000 [00:17<01:15, 21.44it/s]

Epoch 6:  19%|█▉        | 387/2000 [00:17<01:14, 21.53it/s]

Epoch 6:  20%|█▉        | 390/2000 [00:18<01:14, 21.57it/s]

Epoch 6:  20%|█▉        | 393/2000 [00:18<01:14, 21.65it/s]

Epoch 6:  20%|█▉        | 396/2000 [00:18<01:13, 21.69it/s]

Epoch 6:  20%|█▉        | 399/2000 [00:18<01:13, 21.69it/s]

Epoch 6:  20%|██        | 402/2000 [00:18<01:13, 21.72it/s]

Epoch 6:  20%|██        | 405/2000 [00:18<01:13, 21.73it/s]

Epoch 6:  20%|██        | 408/2000 [00:18<01:13, 21.75it/s]

Epoch 6:  21%|██        | 411/2000 [00:19<01:13, 21.75it/s]

Epoch 6:  21%|██        | 414/2000 [00:19<01:12, 21.76it/s]

Epoch 6:  21%|██        | 417/2000 [00:19<01:12, 21.75it/s]

Epoch 6:  21%|██        | 420/2000 [00:19<01:12, 21.76it/s]

Epoch 6:  21%|██        | 423/2000 [00:19<01:12, 21.77it/s]

Epoch 6:  21%|██▏       | 426/2000 [00:19<01:12, 21.78it/s]

Epoch 6:  21%|██▏       | 429/2000 [00:19<01:12, 21.78it/s]

Epoch 6:  22%|██▏       | 432/2000 [00:20<01:11, 21.78it/s]

Epoch 6:  22%|██▏       | 435/2000 [00:20<01:11, 21.79it/s]

Epoch 6:  22%|██▏       | 438/2000 [00:20<01:11, 21.79it/s]

Epoch 6:  22%|██▏       | 441/2000 [00:20<01:11, 21.79it/s]

Epoch 6:  22%|██▏       | 444/2000 [00:20<01:11, 21.79it/s]

Epoch 6:  22%|██▏       | 447/2000 [00:20<01:11, 21.79it/s]

Epoch 6:  22%|██▎       | 450/2000 [00:20<01:11, 21.79it/s]

Epoch 6:  23%|██▎       | 453/2000 [00:21<01:11, 21.79it/s]

Epoch 6:  23%|██▎       | 456/2000 [00:21<01:10, 21.79it/s]

Epoch 6:  23%|██▎       | 459/2000 [00:21<01:10, 21.78it/s]

Epoch 6:  23%|██▎       | 462/2000 [00:21<01:10, 21.79it/s]

Epoch 6:  23%|██▎       | 465/2000 [00:21<01:10, 21.80it/s]

Epoch 6:  23%|██▎       | 468/2000 [00:21<01:10, 21.81it/s]

Epoch 6:  24%|██▎       | 471/2000 [00:21<01:10, 21.81it/s]

Epoch 6:  24%|██▎       | 474/2000 [00:21<01:09, 21.80it/s]

Epoch 6:  24%|██▍       | 477/2000 [00:22<01:09, 21.81it/s]

Epoch 6:  24%|██▍       | 480/2000 [00:22<01:09, 21.79it/s]

Epoch 6:  24%|██▍       | 483/2000 [00:22<01:09, 21.77it/s]

Epoch 6:  24%|██▍       | 486/2000 [00:22<01:09, 21.78it/s]

Epoch 6:  24%|██▍       | 489/2000 [00:22<01:09, 21.78it/s]

Epoch 6:  25%|██▍       | 492/2000 [00:22<01:09, 21.77it/s]

Epoch 6:  25%|██▍       | 495/2000 [00:22<01:09, 21.77it/s]

Epoch 6:  25%|██▍       | 498/2000 [00:23<01:09, 21.76it/s]

Epoch 6:  25%|██▌       | 501/2000 [00:23<01:08, 21.76it/s]

Epoch 6:  25%|██▌       | 504/2000 [00:23<01:08, 21.77it/s]

Epoch 6:  25%|██▌       | 507/2000 [00:23<01:08, 21.77it/s]

Epoch 6:  26%|██▌       | 510/2000 [00:23<01:08, 21.78it/s]

Epoch 6:  26%|██▌       | 513/2000 [00:23<01:08, 21.79it/s]

Epoch 6:  26%|██▌       | 516/2000 [00:23<01:08, 21.79it/s]

Epoch 6:  26%|██▌       | 519/2000 [00:24<01:07, 21.78it/s]

Epoch 6:  26%|██▌       | 522/2000 [00:24<01:07, 21.78it/s]

Epoch 6:  26%|██▋       | 525/2000 [00:24<01:07, 21.78it/s]

Epoch 6:  26%|██▋       | 528/2000 [00:24<01:07, 21.79it/s]

Epoch 6:  27%|██▋       | 531/2000 [00:24<01:07, 21.78it/s]

Epoch 6:  27%|██▋       | 534/2000 [00:24<01:07, 21.79it/s]

Epoch 6:  27%|██▋       | 537/2000 [00:24<01:07, 21.80it/s]

Epoch 6:  27%|██▋       | 540/2000 [00:25<01:06, 21.81it/s]

Epoch 6:  27%|██▋       | 543/2000 [00:25<01:06, 21.80it/s]

Epoch 6:  27%|██▋       | 546/2000 [00:25<01:06, 21.79it/s]

Epoch 6:  27%|██▋       | 549/2000 [00:25<01:06, 21.81it/s]

Epoch 6:  28%|██▊       | 552/2000 [00:25<01:06, 21.80it/s]

Epoch 6:  28%|██▊       | 555/2000 [00:25<01:06, 21.79it/s]

Epoch 6:  28%|██▊       | 558/2000 [00:25<01:06, 21.79it/s]

Epoch 6:  28%|██▊       | 561/2000 [00:25<01:06, 21.78it/s]

Epoch 6:  28%|██▊       | 564/2000 [00:26<01:05, 21.77it/s]

Epoch 6:  28%|██▊       | 567/2000 [00:26<01:05, 21.76it/s]

Epoch 6:  28%|██▊       | 570/2000 [00:26<01:05, 21.74it/s]

Epoch 6:  29%|██▊       | 573/2000 [00:26<01:05, 21.74it/s]

Epoch 6:  29%|██▉       | 576/2000 [00:26<01:05, 21.72it/s]

Epoch 6:  29%|██▉       | 579/2000 [00:26<01:05, 21.73it/s]

Epoch 6:  29%|██▉       | 582/2000 [00:26<01:05, 21.71it/s]

Epoch 6:  29%|██▉       | 585/2000 [00:27<01:05, 21.71it/s]

Epoch 6:  29%|██▉       | 588/2000 [00:27<01:05, 21.70it/s]

Epoch 6:  30%|██▉       | 591/2000 [00:27<01:04, 21.71it/s]

Epoch 6:  30%|██▉       | 594/2000 [00:27<01:04, 21.72it/s]

Epoch 6:  30%|██▉       | 597/2000 [00:27<01:04, 21.72it/s]

Epoch 6:  30%|███       | 600/2000 [00:27<01:04, 21.72it/s]

Epoch 6:  30%|███       | 603/2000 [00:27<01:04, 21.73it/s]

Epoch 6:  30%|███       | 606/2000 [00:28<01:04, 21.73it/s]

Epoch 6:  30%|███       | 609/2000 [00:28<01:04, 21.70it/s]

Epoch 6:  31%|███       | 612/2000 [00:28<01:04, 21.69it/s]

Epoch 6:  31%|███       | 615/2000 [00:28<01:03, 21.69it/s]

Epoch 6:  31%|███       | 618/2000 [00:28<01:03, 21.69it/s]

Epoch 6:  31%|███       | 621/2000 [00:28<01:03, 21.68it/s]

Epoch 6:  31%|███       | 624/2000 [00:28<01:03, 21.68it/s]

Epoch 6:  31%|███▏      | 627/2000 [00:29<01:03, 21.69it/s]

Epoch 6:  32%|███▏      | 630/2000 [00:29<01:03, 21.72it/s]

Epoch 6:  32%|███▏      | 633/2000 [00:29<01:02, 21.75it/s]

Epoch 6:  32%|███▏      | 636/2000 [00:29<01:02, 21.75it/s]

Epoch 6:  32%|███▏      | 639/2000 [00:29<01:02, 21.77it/s]

Epoch 6:  32%|███▏      | 642/2000 [00:29<01:02, 21.77it/s]

Epoch 6:  32%|███▏      | 645/2000 [00:29<01:02, 21.78it/s]

Epoch 6:  32%|███▏      | 648/2000 [00:29<01:02, 21.80it/s]

Epoch 6:  33%|███▎      | 651/2000 [00:30<01:01, 21.79it/s]

Epoch 6:  33%|███▎      | 654/2000 [00:30<01:01, 21.80it/s]

Epoch 6:  33%|███▎      | 657/2000 [00:30<01:01, 21.80it/s]

Epoch 6:  33%|███▎      | 660/2000 [00:30<01:01, 21.79it/s]

Epoch 6:  33%|███▎      | 663/2000 [00:30<01:01, 21.80it/s]

Epoch 6:  33%|███▎      | 666/2000 [00:30<01:01, 21.80it/s]

Epoch 6:  33%|███▎      | 669/2000 [00:30<01:01, 21.80it/s]

Epoch 6:  34%|███▎      | 672/2000 [00:31<01:00, 21.81it/s]

Epoch 6:  34%|███▍      | 675/2000 [00:31<01:00, 21.81it/s]

Epoch 6:  34%|███▍      | 678/2000 [00:31<01:00, 21.82it/s]

Epoch 6:  34%|███▍      | 681/2000 [00:31<01:00, 21.81it/s]

Epoch 6:  34%|███▍      | 684/2000 [00:31<01:00, 21.81it/s]

Epoch 6:  34%|███▍      | 687/2000 [00:31<01:00, 21.81it/s]

Epoch 6:  34%|███▍      | 690/2000 [00:31<01:00, 21.81it/s]

Epoch 6:  35%|███▍      | 693/2000 [00:32<00:59, 21.82it/s]

Epoch 6:  35%|███▍      | 696/2000 [00:32<00:59, 21.83it/s]

Epoch 6:  35%|███▍      | 699/2000 [00:32<00:59, 21.82it/s]

Epoch 6:  35%|███▌      | 702/2000 [00:32<00:59, 21.84it/s]

Epoch 6:  35%|███▌      | 705/2000 [00:32<00:59, 21.82it/s]

Epoch 6:  35%|███▌      | 708/2000 [00:32<00:59, 21.82it/s]

Epoch 6:  36%|███▌      | 711/2000 [00:32<00:59, 21.81it/s]

Epoch 6:  36%|███▌      | 714/2000 [00:33<00:58, 21.81it/s]

Epoch 6:  36%|███▌      | 717/2000 [00:33<00:58, 21.80it/s]

Epoch 6:  36%|███▌      | 720/2000 [00:33<00:58, 21.81it/s]

Epoch 6:  36%|███▌      | 723/2000 [00:33<00:58, 21.81it/s]

Epoch 6:  36%|███▋      | 726/2000 [00:33<00:58, 21.83it/s]

Epoch 6:  36%|███▋      | 729/2000 [00:33<00:58, 21.82it/s]

Epoch 6:  37%|███▋      | 732/2000 [00:33<00:58, 21.81it/s]

Epoch 6:  37%|███▋      | 735/2000 [00:33<00:57, 21.82it/s]

Epoch 6:  37%|███▋      | 738/2000 [00:34<00:57, 21.80it/s]

Epoch 6:  37%|███▋      | 741/2000 [00:34<00:57, 21.82it/s]

Epoch 6:  37%|███▋      | 744/2000 [00:34<00:57, 21.81it/s]

Epoch 6:  37%|███▋      | 747/2000 [00:34<00:57, 21.81it/s]

Epoch 6:  38%|███▊      | 750/2000 [00:34<00:57, 21.82it/s]

Epoch 6:  38%|███▊      | 753/2000 [00:34<00:57, 21.83it/s]

Epoch 6:  38%|███▊      | 756/2000 [00:34<00:57, 21.82it/s]

Epoch 6:  38%|███▊      | 759/2000 [00:35<00:56, 21.84it/s]

Epoch 6:  38%|███▊      | 762/2000 [00:35<00:56, 21.83it/s]

Epoch 6:  38%|███▊      | 765/2000 [00:35<00:56, 21.71it/s]

Epoch 6:  38%|███▊      | 768/2000 [00:35<00:57, 21.29it/s]

Epoch 6:  39%|███▊      | 771/2000 [00:35<00:58, 21.06it/s]

Epoch 6:  39%|███▊      | 774/2000 [00:35<00:57, 21.17it/s]

Epoch 6:  39%|███▉      | 777/2000 [00:35<00:57, 21.30it/s]

Epoch 6:  39%|███▉      | 780/2000 [00:36<00:57, 21.37it/s]

Epoch 6:  39%|███▉      | 783/2000 [00:36<00:56, 21.45it/s]

Epoch 6:  39%|███▉      | 786/2000 [00:36<00:56, 21.54it/s]

Epoch 6:  39%|███▉      | 789/2000 [00:36<00:56, 21.60it/s]

Epoch 6:  40%|███▉      | 792/2000 [00:36<00:55, 21.66it/s]

Epoch 6:  40%|███▉      | 795/2000 [00:36<00:55, 21.70it/s]

Epoch 6:  40%|███▉      | 798/2000 [00:36<00:55, 21.70it/s]

Epoch 6:  40%|████      | 801/2000 [00:37<00:55, 21.72it/s]

Epoch 6:  40%|████      | 804/2000 [00:37<00:55, 21.73it/s]

Epoch 6:  40%|████      | 807/2000 [00:37<00:54, 21.74it/s]

Epoch 6:  40%|████      | 810/2000 [00:37<00:54, 21.75it/s]

Epoch 6:  41%|████      | 813/2000 [00:37<00:54, 21.74it/s]

Epoch 6:  41%|████      | 816/2000 [00:37<00:54, 21.76it/s]

Epoch 6:  41%|████      | 819/2000 [00:37<00:54, 21.74it/s]

Epoch 6:  41%|████      | 822/2000 [00:37<00:54, 21.75it/s]

Epoch 6:  41%|████▏     | 825/2000 [00:38<00:54, 21.75it/s]

Epoch 6:  41%|████▏     | 828/2000 [00:38<00:53, 21.75it/s]

Epoch 6:  42%|████▏     | 831/2000 [00:38<00:53, 21.74it/s]

Epoch 6:  42%|████▏     | 834/2000 [00:38<00:53, 21.75it/s]

Epoch 6:  42%|████▏     | 837/2000 [00:38<00:53, 21.75it/s]

Epoch 6:  42%|████▏     | 840/2000 [00:38<00:53, 21.75it/s]

Epoch 6:  42%|████▏     | 843/2000 [00:38<00:53, 21.75it/s]

Epoch 6:  42%|████▏     | 846/2000 [00:39<00:53, 21.75it/s]

Epoch 6:  42%|████▏     | 849/2000 [00:39<00:52, 21.75it/s]

Epoch 6:  43%|████▎     | 852/2000 [00:39<00:52, 21.73it/s]

Epoch 6:  43%|████▎     | 855/2000 [00:39<00:52, 21.73it/s]

Epoch 6:  43%|████▎     | 858/2000 [00:39<00:52, 21.75it/s]

Epoch 6:  43%|████▎     | 861/2000 [00:39<00:52, 21.77it/s]

Epoch 6:  43%|████▎     | 864/2000 [00:39<00:52, 21.77it/s]

Epoch 6:  43%|████▎     | 867/2000 [00:40<00:52, 21.78it/s]

Epoch 6:  44%|████▎     | 870/2000 [00:40<00:51, 21.77it/s]

Epoch 6:  44%|████▎     | 873/2000 [00:40<00:51, 21.78it/s]

Epoch 6:  44%|████▍     | 876/2000 [00:40<00:51, 21.79it/s]

Epoch 6:  44%|████▍     | 879/2000 [00:40<00:51, 21.79it/s]

Epoch 6:  44%|████▍     | 882/2000 [00:40<00:51, 21.79it/s]

Epoch 6:  44%|████▍     | 885/2000 [00:40<00:51, 21.79it/s]

Epoch 6:  44%|████▍     | 888/2000 [00:41<00:51, 21.77it/s]

Epoch 6:  45%|████▍     | 891/2000 [00:41<00:50, 21.77it/s]

Epoch 6:  45%|████▍     | 894/2000 [00:41<00:50, 21.78it/s]

Epoch 6:  45%|████▍     | 897/2000 [00:41<00:50, 21.78it/s]

Epoch 6:  45%|████▌     | 900/2000 [00:41<00:50, 21.77it/s]

Epoch 6:  45%|████▌     | 903/2000 [00:41<00:50, 21.76it/s]

Epoch 6:  45%|████▌     | 906/2000 [00:41<00:50, 21.78it/s]

Epoch 6:  45%|████▌     | 909/2000 [00:41<00:50, 21.78it/s]

Epoch 6:  46%|████▌     | 912/2000 [00:42<00:49, 21.78it/s]

Epoch 6:  46%|████▌     | 915/2000 [00:42<00:49, 21.78it/s]

Epoch 6:  46%|████▌     | 918/2000 [00:42<00:49, 21.78it/s]

Epoch 6:  46%|████▌     | 921/2000 [00:42<00:49, 21.78it/s]

Epoch 6:  46%|████▌     | 924/2000 [00:42<00:49, 21.77it/s]

Epoch 6:  46%|████▋     | 927/2000 [00:42<00:49, 21.78it/s]

Epoch 6:  46%|████▋     | 930/2000 [00:42<00:49, 21.77it/s]

Epoch 6:  47%|████▋     | 933/2000 [00:43<00:49, 21.76it/s]

Epoch 6:  47%|████▋     | 936/2000 [00:43<00:48, 21.77it/s]

Epoch 6:  47%|████▋     | 939/2000 [00:43<00:48, 21.77it/s]

Epoch 6:  47%|████▋     | 942/2000 [00:43<00:48, 21.78it/s]

Epoch 6:  47%|████▋     | 945/2000 [00:43<00:48, 21.78it/s]

Epoch 6:  47%|████▋     | 948/2000 [00:43<00:48, 21.78it/s]

Epoch 6:  48%|████▊     | 951/2000 [00:43<00:48, 21.77it/s]

Epoch 6:  48%|████▊     | 954/2000 [00:44<00:48, 21.77it/s]

Epoch 6:  48%|████▊     | 957/2000 [00:44<00:47, 21.77it/s]

Epoch 6:  48%|████▊     | 960/2000 [00:44<00:47, 21.77it/s]

Epoch 6:  48%|████▊     | 963/2000 [00:44<00:47, 21.76it/s]

Epoch 6:  48%|████▊     | 966/2000 [00:44<00:47, 21.75it/s]

Epoch 6:  48%|████▊     | 969/2000 [00:44<00:47, 21.75it/s]

Epoch 6:  49%|████▊     | 972/2000 [00:44<00:47, 21.75it/s]

Epoch 6:  49%|████▉     | 975/2000 [00:45<00:47, 21.76it/s]

Epoch 6:  49%|████▉     | 978/2000 [00:45<00:46, 21.77it/s]

Epoch 6:  49%|████▉     | 981/2000 [00:45<00:46, 21.76it/s]

Epoch 6:  49%|████▉     | 984/2000 [00:45<00:46, 21.77it/s]

Epoch 6:  49%|████▉     | 987/2000 [00:45<00:46, 21.76it/s]

Epoch 6:  50%|████▉     | 990/2000 [00:45<00:46, 21.75it/s]

Epoch 6:  50%|████▉     | 993/2000 [00:45<00:46, 21.76it/s]

Epoch 6:  50%|████▉     | 996/2000 [00:45<00:46, 21.78it/s]

Epoch 6:  50%|████▉     | 999/2000 [00:46<00:45, 21.77it/s]

Epoch 6:  50%|█████     | 1002/2000 [00:46<00:45, 21.78it/s]

Epoch 6:  50%|█████     | 1005/2000 [00:46<00:45, 21.77it/s]

Epoch 6:  50%|█████     | 1008/2000 [00:46<00:45, 21.76it/s]

Epoch 6:  51%|█████     | 1011/2000 [00:46<00:45, 21.77it/s]

Epoch 6:  51%|█████     | 1014/2000 [00:46<00:45, 21.77it/s]

Epoch 6:  51%|█████     | 1017/2000 [00:46<00:45, 21.77it/s]

Epoch 6:  51%|█████     | 1020/2000 [00:47<00:44, 21.78it/s]

Epoch 6:  51%|█████     | 1023/2000 [00:47<00:44, 21.78it/s]

Epoch 6:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.77it/s]

Epoch 6:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.79it/s]

Epoch 6:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.77it/s]

Epoch 6:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.78it/s]

Epoch 6:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.77it/s]

Epoch 6:  52%|█████▏    | 1041/2000 [00:48<00:44, 21.78it/s]

Epoch 6:  52%|█████▏    | 1044/2000 [00:48<00:43, 21.77it/s]

Epoch 6:  52%|█████▏    | 1047/2000 [00:48<00:43, 21.78it/s]

Epoch 6:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.78it/s]

Epoch 6:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.77it/s]

Epoch 6:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.78it/s]

Epoch 6:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.77it/s]

Epoch 6:  53%|█████▎    | 1062/2000 [00:49<00:43, 21.76it/s]

Epoch 6:  53%|█████▎    | 1065/2000 [00:49<00:42, 21.77it/s]

Epoch 6:  53%|█████▎    | 1068/2000 [00:49<00:42, 21.75it/s]

Epoch 6:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.75it/s]

Epoch 6:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.75it/s]

Epoch 6:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.76it/s]

Epoch 6:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.77it/s]

Epoch 6:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.76it/s]

Epoch 6:  54%|█████▍    | 1086/2000 [00:50<00:41, 21.77it/s]

Epoch 6:  54%|█████▍    | 1089/2000 [00:50<00:41, 21.75it/s]

Epoch 6:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.76it/s]

Epoch 6:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.76it/s]

Epoch 6:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.77it/s]

Epoch 6:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.80it/s]

Epoch 6:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.82it/s]

Epoch 6:  55%|█████▌    | 1107/2000 [00:51<00:40, 21.84it/s]

Epoch 6:  56%|█████▌    | 1110/2000 [00:51<00:40, 21.86it/s]

Epoch 6:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.86it/s]

Epoch 6:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.86it/s]

Epoch 6:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.84it/s]

Epoch 6:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.85it/s]

Epoch 6:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.84it/s]

Epoch 6:  56%|█████▋    | 1128/2000 [00:52<00:39, 21.85it/s]

Epoch 6:  57%|█████▋    | 1131/2000 [00:52<00:39, 21.85it/s]

Epoch 6:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.84it/s]

Epoch 6:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.83it/s]

Epoch 6:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.84it/s]

Epoch 6:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.84it/s]

Epoch 6:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.85it/s]

Epoch 6:  57%|█████▋    | 1149/2000 [00:53<00:38, 21.83it/s]

Epoch 6:  58%|█████▊    | 1152/2000 [00:53<00:38, 21.84it/s]

Epoch 6:  58%|█████▊    | 1155/2000 [00:53<00:38, 21.83it/s]

Epoch 6:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.84it/s]

Epoch 6:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.84it/s]

Epoch 6:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.85it/s]

Epoch 6:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.86it/s]

Epoch 6:  58%|█████▊    | 1170/2000 [00:53<00:37, 21.86it/s]

Epoch 6:  59%|█████▊    | 1173/2000 [00:54<00:37, 21.87it/s]

Epoch 6:  59%|█████▉    | 1176/2000 [00:54<00:37, 21.87it/s]

Epoch 6:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.86it/s]

Epoch 6:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.85it/s]

Epoch 6:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.86it/s]

Epoch 6:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.83it/s]

Epoch 6:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.84it/s]

Epoch 6:  60%|█████▉    | 1194/2000 [00:55<00:36, 21.85it/s]

Epoch 6:  60%|█████▉    | 1197/2000 [00:55<00:36, 21.85it/s]

Epoch 6:  60%|██████    | 1200/2000 [00:55<00:36, 21.85it/s]

Epoch 6:  60%|██████    | 1203/2000 [00:55<00:36, 21.86it/s]

Epoch 6:  60%|██████    | 1206/2000 [00:55<00:36, 21.86it/s]

Epoch 6:  60%|██████    | 1209/2000 [00:55<00:36, 21.86it/s]

Epoch 6:  61%|██████    | 1212/2000 [00:55<00:36, 21.87it/s]

Epoch 6:  61%|██████    | 1215/2000 [00:56<00:35, 21.87it/s]

Epoch 6:  61%|██████    | 1218/2000 [00:56<00:35, 21.84it/s]

Epoch 6:  61%|██████    | 1221/2000 [00:56<00:35, 21.84it/s]

Epoch 6:  61%|██████    | 1224/2000 [00:56<00:35, 21.83it/s]

Epoch 6:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.84it/s]

Epoch 6:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.87it/s]

Epoch 6:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.87it/s]

Epoch 6:  62%|██████▏   | 1236/2000 [00:56<00:34, 21.87it/s]

Epoch 6:  62%|██████▏   | 1239/2000 [00:57<00:34, 21.88it/s]

Epoch 6:  62%|██████▏   | 1242/2000 [00:57<00:34, 21.87it/s]

Epoch 6:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.86it/s]

Epoch 6:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.88it/s]

Epoch 6:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.88it/s]

Epoch 6:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.89it/s]

Epoch 6:  63%|██████▎   | 1257/2000 [00:57<00:33, 21.88it/s]

Epoch 6:  63%|██████▎   | 1260/2000 [00:58<00:33, 21.88it/s]

Epoch 6:  63%|██████▎   | 1263/2000 [00:58<00:33, 21.80it/s]

Epoch 6:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.82it/s]

Epoch 6:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.84it/s]

Epoch 6:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.85it/s]

Epoch 6:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.86it/s]

Epoch 6:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.87it/s]

Epoch 6:  64%|██████▍   | 1281/2000 [00:59<00:32, 21.86it/s]

Epoch 6:  64%|██████▍   | 1284/2000 [00:59<00:32, 21.85it/s]

Epoch 6:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.85it/s]

Epoch 6:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.86it/s]

Epoch 6:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.83it/s]

Epoch 6:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.85it/s]

Epoch 6:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.80it/s]

Epoch 6:  65%|██████▌   | 1302/2000 [01:00<00:31, 21.81it/s]

Epoch 6:  65%|██████▌   | 1305/2000 [01:00<00:31, 21.83it/s]

Epoch 6:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.82it/s]

Epoch 6:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.82it/s]

Epoch 6:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.83it/s]

Epoch 6:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.84it/s]

Epoch 6:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.84it/s]

Epoch 6:  66%|██████▌   | 1323/2000 [01:00<00:31, 21.83it/s]

Epoch 6:  66%|██████▋   | 1326/2000 [01:01<00:30, 21.83it/s]

Epoch 6:  66%|██████▋   | 1329/2000 [01:01<00:30, 21.83it/s]

Epoch 6:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.85it/s]

Epoch 6:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.84it/s]

Epoch 6:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.85it/s]

Epoch 6:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.84it/s]

Epoch 6:  67%|██████▋   | 1344/2000 [01:01<00:30, 21.84it/s]

Epoch 6:  67%|██████▋   | 1347/2000 [01:02<00:29, 21.84it/s]

Epoch 6:  68%|██████▊   | 1350/2000 [01:02<00:29, 21.84it/s]

Epoch 6:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.84it/s]

Epoch 6:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.83it/s]

Epoch 6:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.85it/s]

Epoch 6:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.85it/s]

Epoch 6:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.84it/s]

Epoch 6:  68%|██████▊   | 1368/2000 [01:03<00:28, 21.85it/s]

Epoch 6:  69%|██████▊   | 1371/2000 [01:03<00:28, 21.85it/s]

Epoch 6:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.86it/s]

Epoch 6:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.86it/s]

Epoch 6:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.83it/s]

Epoch 6:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.84it/s]

Epoch 6:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.83it/s]

Epoch 6:  69%|██████▉   | 1389/2000 [01:03<00:27, 21.83it/s]

Epoch 6:  70%|██████▉   | 1392/2000 [01:04<00:27, 21.84it/s]

Epoch 6:  70%|██████▉   | 1395/2000 [01:04<00:27, 21.85it/s]

Epoch 6:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.85it/s]

Epoch 6:  70%|███████   | 1401/2000 [01:04<00:27, 21.84it/s]

Epoch 6:  70%|███████   | 1404/2000 [01:04<00:27, 21.85it/s]

Epoch 6:  70%|███████   | 1407/2000 [01:04<00:27, 21.83it/s]

Epoch 6:  70%|███████   | 1410/2000 [01:04<00:27, 21.85it/s]

Epoch 6:  71%|███████   | 1413/2000 [01:05<00:26, 21.85it/s]

Epoch 6:  71%|███████   | 1416/2000 [01:05<00:26, 21.84it/s]

Epoch 6:  71%|███████   | 1419/2000 [01:05<00:26, 21.85it/s]

Epoch 6:  71%|███████   | 1422/2000 [01:05<00:26, 21.86it/s]

Epoch 6:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.85it/s]

Epoch 6:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.85it/s]

Epoch 6:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.85it/s]

Epoch 6:  72%|███████▏  | 1434/2000 [01:06<00:25, 21.84it/s]

Epoch 6:  72%|███████▏  | 1437/2000 [01:06<00:25, 21.84it/s]

Epoch 6:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.84it/s]

Epoch 6:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.84it/s]

Epoch 6:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.85it/s]

Epoch 6:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.84it/s]

Epoch 6:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.84it/s]

Epoch 6:  73%|███████▎  | 1455/2000 [01:07<00:24, 21.85it/s]

Epoch 6:  73%|███████▎  | 1458/2000 [01:07<00:24, 21.85it/s]

Epoch 6:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.84it/s]

Epoch 6:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.84it/s]

Epoch 6:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.83it/s]

Epoch 6:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.83it/s]

Epoch 6:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.83it/s]

Epoch 6:  74%|███████▍  | 1476/2000 [01:07<00:23, 21.84it/s]

Epoch 6:  74%|███████▍  | 1479/2000 [01:08<00:23, 21.84it/s]

Epoch 6:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.84it/s]

Epoch 6:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.85it/s]

Epoch 6:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.85it/s]

Epoch 6:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.53it/s]

Epoch 6:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.31it/s]

Epoch 6:  75%|███████▍  | 1497/2000 [01:08<00:23, 20.97it/s]

Epoch 6:  75%|███████▌  | 1500/2000 [01:09<00:23, 21.08it/s]

Epoch 6:  75%|███████▌  | 1503/2000 [01:09<00:23, 21.25it/s]

Epoch 6:  75%|███████▌  | 1506/2000 [01:09<00:23, 21.39it/s]

Epoch 6:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.52it/s]

Epoch 6:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.60it/s]

Epoch 6:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.67it/s]

Epoch 6:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.72it/s]

Epoch 6:  76%|███████▌  | 1521/2000 [01:10<00:22, 21.75it/s]

Epoch 6:  76%|███████▌  | 1524/2000 [01:10<00:21, 21.78it/s]

Epoch 6:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.79it/s]

Epoch 6:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.81it/s]

Epoch 6:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.81it/s]

Epoch 6:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.82it/s]

Epoch 6:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.80it/s]

Epoch 6:  77%|███████▋  | 1542/2000 [01:11<00:20, 21.81it/s]

Epoch 6:  77%|███████▋  | 1545/2000 [01:11<00:20, 21.81it/s]

Epoch 6:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.82it/s]

Epoch 6:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.82it/s]

Epoch 6:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.81it/s]

Epoch 6:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.82it/s]

Epoch 6:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.81it/s]

Epoch 6:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.80it/s]

Epoch 6:  78%|███████▊  | 1566/2000 [01:12<00:19, 21.82it/s]

Epoch 6:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.82it/s]

Epoch 6:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.83it/s]

Epoch 6:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.83it/s]

Epoch 6:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.83it/s]

Epoch 6:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.85it/s]

Epoch 6:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.84it/s]

Epoch 6:  79%|███████▉  | 1587/2000 [01:13<00:18, 21.83it/s]

Epoch 6:  80%|███████▉  | 1590/2000 [01:13<00:18, 21.82it/s]

Epoch 6:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.83it/s]

Epoch 6:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.82it/s]

Epoch 6:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.82it/s]

Epoch 6:  80%|████████  | 1602/2000 [01:13<00:18, 21.81it/s]

Epoch 6:  80%|████████  | 1605/2000 [01:13<00:18, 21.82it/s]

Epoch 6:  80%|████████  | 1608/2000 [01:14<00:17, 21.83it/s]

Epoch 6:  81%|████████  | 1611/2000 [01:14<00:17, 21.83it/s]

Epoch 6:  81%|████████  | 1614/2000 [01:14<00:17, 21.84it/s]

Epoch 6:  81%|████████  | 1617/2000 [01:14<00:17, 21.83it/s]

Epoch 6:  81%|████████  | 1620/2000 [01:14<00:17, 21.84it/s]

Epoch 6:  81%|████████  | 1623/2000 [01:14<00:17, 21.83it/s]

Epoch 6:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.81it/s]

Epoch 6:  81%|████████▏ | 1629/2000 [01:15<00:16, 21.83it/s]

Epoch 6:  82%|████████▏ | 1632/2000 [01:15<00:16, 21.83it/s]

Epoch 6:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.83it/s]

Epoch 6:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.84it/s]

Epoch 6:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.84it/s]

Epoch 6:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.84it/s]

Epoch 6:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.84it/s]

Epoch 6:  82%|████████▎ | 1650/2000 [01:15<00:16, 21.80it/s]

Epoch 6:  83%|████████▎ | 1653/2000 [01:16<00:15, 21.83it/s]

Epoch 6:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.83it/s]

Epoch 6:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.82it/s]

Epoch 6:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.82it/s]

Epoch 6:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.84it/s]

Epoch 6:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.83it/s]

Epoch 6:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.81it/s]

Epoch 6:  84%|████████▎ | 1674/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.83it/s]

Epoch 6:  85%|████████▍ | 1695/2000 [01:18<00:13, 21.83it/s]

Epoch 6:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.84it/s]

Epoch 6:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.84it/s]

Epoch 6:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.86it/s]

Epoch 6:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.86it/s]

Epoch 6:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.86it/s]

Epoch 6:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.84it/s]

Epoch 6:  86%|████████▌ | 1716/2000 [01:18<00:13, 21.84it/s]

Epoch 6:  86%|████████▌ | 1719/2000 [01:19<00:12, 21.83it/s]

Epoch 6:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.85it/s]

Epoch 6:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.84it/s]

Epoch 6:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.83it/s]

Epoch 6:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.84it/s]

Epoch 6:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.84it/s]

Epoch 6:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.82it/s]

Epoch 6:  87%|████████▋ | 1740/2000 [01:20<00:11, 21.83it/s]

Epoch 6:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.82it/s]

Epoch 6:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.81it/s]

Epoch 6:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.80it/s]

Epoch 6:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.82it/s]

Epoch 6:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.82it/s]

Epoch 6:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.82it/s]

Epoch 6:  88%|████████▊ | 1761/2000 [01:21<00:10, 21.81it/s]

Epoch 6:  88%|████████▊ | 1764/2000 [01:21<00:10, 21.82it/s]

Epoch 6:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.83it/s]

Epoch 6:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.84it/s]

Epoch 6:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.82it/s]

Epoch 6:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.82it/s]

Epoch 6:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.81it/s]

Epoch 6:  89%|████████▉ | 1782/2000 [01:22<00:09, 21.84it/s]

Epoch 6:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.84it/s]

Epoch 6:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.84it/s]

Epoch 6:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.85it/s]

Epoch 6:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.85it/s]

Epoch 6:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.83it/s]

Epoch 6:  90%|█████████ | 1800/2000 [01:22<00:09, 21.83it/s]

Epoch 6:  90%|█████████ | 1803/2000 [01:22<00:09, 21.81it/s]

Epoch 6:  90%|█████████ | 1806/2000 [01:23<00:08, 21.82it/s]

Epoch 6:  90%|█████████ | 1809/2000 [01:23<00:08, 21.82it/s]

Epoch 6:  91%|█████████ | 1812/2000 [01:23<00:08, 21.82it/s]

Epoch 6:  91%|█████████ | 1815/2000 [01:23<00:08, 21.83it/s]

Epoch 6:  91%|█████████ | 1818/2000 [01:23<00:08, 21.81it/s]

Epoch 6:  91%|█████████ | 1821/2000 [01:23<00:08, 21.82it/s]

Epoch 6:  91%|█████████ | 1824/2000 [01:23<00:08, 21.82it/s]

Epoch 6:  91%|█████████▏| 1827/2000 [01:24<00:07, 21.82it/s]

Epoch 6:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.83it/s]

Epoch 6:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.83it/s]

Epoch 6:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.84it/s]

Epoch 6:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.84it/s]

Epoch 6:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.84it/s]

Epoch 6:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.84it/s]

Epoch 6:  92%|█████████▏| 1848/2000 [01:25<00:06, 21.84it/s]

Epoch 6:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.83it/s]

Epoch 6:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.83it/s]

Epoch 6:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.83it/s]

Epoch 6:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.84it/s]

Epoch 6:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.85it/s]

Epoch 6:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.86it/s]

Epoch 6:  93%|█████████▎| 1869/2000 [01:26<00:05, 21.85it/s]

Epoch 6:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.83it/s]

Epoch 6:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.82it/s]

Epoch 6:  94%|█████████▍| 1878/2000 [01:26<00:06, 19.15it/s]

Epoch 6:  94%|█████████▍| 1881/2000 [01:26<00:05, 19.88it/s]

Epoch 6:  94%|█████████▍| 1884/2000 [01:26<00:05, 20.43it/s]

Epoch 6:  94%|█████████▍| 1887/2000 [01:26<00:05, 20.82it/s]

Epoch 6:  94%|█████████▍| 1890/2000 [01:27<00:05, 21.10it/s]

Epoch 6:  95%|█████████▍| 1893/2000 [01:27<00:05, 21.32it/s]

Epoch 6:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.46it/s]

Epoch 6:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.57it/s]

Epoch 6:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.65it/s]

Epoch 6:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.70it/s]

Epoch 6:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.74it/s]

Epoch 6:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.76it/s]

Epoch 6:  96%|█████████▌| 1914/2000 [01:28<00:03, 21.78it/s]

Epoch 6:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.80it/s]

Epoch 6:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.83it/s]

Epoch 6:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.83it/s]

Epoch 6:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.82it/s]

Epoch 6:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.83it/s]

Epoch 6:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.83it/s]

Epoch 6:  97%|█████████▋| 1935/2000 [01:29<00:02, 21.82it/s]

Epoch 6:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.84it/s]

Epoch 6:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.84it/s]

Epoch 6:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.83it/s]

Epoch 6:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.85it/s]

Epoch 6:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.84it/s]

Epoch 6:  98%|█████████▊| 1953/2000 [01:29<00:02, 21.86it/s]

Epoch 6:  98%|█████████▊| 1956/2000 [01:30<00:02, 21.85it/s]

Epoch 6:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.84it/s]

Epoch 6:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.85it/s]

Epoch 6:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.85it/s]

Epoch 6:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.85it/s]

Epoch 6:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.86it/s]

Epoch 6:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.84it/s]

Epoch 6:  99%|█████████▉| 1977/2000 [01:31<00:01, 21.84it/s]

Epoch 6:  99%|█████████▉| 1980/2000 [01:31<00:00, 21.84it/s]

Epoch 6:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.85it/s]

Epoch 6:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.86it/s]

Epoch 6:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.86it/s]

Epoch 6: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.86it/s]

Epoch 6: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.86it/s]

Epoch 6: 100%|█████████▉| 1998/2000 [01:31<00:00, 21.82it/s]

Epoch 6: loss=0.3866, val_proxy=0.4941

Epoch 7:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 7:   0%|          | 3/2000 [00:00<01:34, 21.22it/s]

Epoch 7:   0%|          | 6/2000 [00:00<01:33, 21.33it/s]

Epoch 7:   0%|          | 9/2000 [00:00<01:32, 21.51it/s]

Epoch 7:   1%|          | 12/2000 [00:00<01:31, 21.64it/s]

Epoch 7:   1%|          | 15/2000 [00:00<01:31, 21.72it/s]

Epoch 7:   1%|          | 18/2000 [00:00<01:31, 21.77it/s]

Epoch 7:   1%|          | 21/2000 [00:00<01:30, 21.81it/s]

Epoch 7:   1%|          | 24/2000 [00:01<01:30, 21.81it/s]

Epoch 7:   1%|▏         | 27/2000 [00:01<01:30, 21.84it/s]

Epoch 7:   2%|▏         | 30/2000 [00:01<01:30, 21.84it/s]

Epoch 7:   2%|▏         | 33/2000 [00:01<01:30, 21.85it/s]

Epoch 7:   2%|▏         | 36/2000 [00:01<01:29, 21.86it/s]

Epoch 7:   2%|▏         | 39/2000 [00:01<01:29, 21.87it/s]

Epoch 7:   2%|▏         | 42/2000 [00:01<01:29, 21.88it/s]

Epoch 7:   2%|▏         | 45/2000 [00:02<01:29, 21.89it/s]

Epoch 7:   2%|▏         | 48/2000 [00:02<01:29, 21.88it/s]

Epoch 7:   3%|▎         | 51/2000 [00:02<01:29, 21.87it/s]

Epoch 7:   3%|▎         | 54/2000 [00:02<01:28, 21.87it/s]

Epoch 7:   3%|▎         | 57/2000 [00:02<01:28, 21.86it/s]

Epoch 7:   3%|▎         | 60/2000 [00:02<01:28, 21.88it/s]

Epoch 7:   3%|▎         | 63/2000 [00:02<01:28, 21.90it/s]

Epoch 7:   3%|▎         | 66/2000 [00:03<01:28, 21.88it/s]

Epoch 7:   3%|▎         | 69/2000 [00:03<01:28, 21.88it/s]

Epoch 7:   4%|▎         | 72/2000 [00:03<01:28, 21.88it/s]

Epoch 7:   4%|▍         | 75/2000 [00:03<01:27, 21.89it/s]

Epoch 7:   4%|▍         | 78/2000 [00:03<01:27, 21.92it/s]

Epoch 7:   4%|▍         | 81/2000 [00:03<01:27, 21.92it/s]

Epoch 7:   4%|▍         | 84/2000 [00:03<01:27, 21.90it/s]

Epoch 7:   4%|▍         | 87/2000 [00:03<01:27, 21.89it/s]

Epoch 7:   4%|▍         | 90/2000 [00:04<01:27, 21.90it/s]

Epoch 7:   5%|▍         | 93/2000 [00:04<01:27, 21.89it/s]

Epoch 7:   5%|▍         | 96/2000 [00:04<01:26, 21.89it/s]

Epoch 7:   5%|▍         | 99/2000 [00:04<01:26, 21.90it/s]

Epoch 7:   5%|▌         | 102/2000 [00:04<01:26, 21.89it/s]

Epoch 7:   5%|▌         | 105/2000 [00:04<01:26, 21.88it/s]

Epoch 7:   5%|▌         | 108/2000 [00:04<01:26, 21.88it/s]

Epoch 7:   6%|▌         | 111/2000 [00:05<01:26, 21.87it/s]

Epoch 7:   6%|▌         | 114/2000 [00:05<01:26, 21.88it/s]

Epoch 7:   6%|▌         | 117/2000 [00:05<01:26, 21.88it/s]

Epoch 7:   6%|▌         | 120/2000 [00:05<01:25, 21.89it/s]

Epoch 7:   6%|▌         | 123/2000 [00:05<01:25, 21.88it/s]

Epoch 7:   6%|▋         | 126/2000 [00:05<01:25, 21.88it/s]

Epoch 7:   6%|▋         | 129/2000 [00:05<01:25, 21.86it/s]

Epoch 7:   7%|▋         | 132/2000 [00:06<01:25, 21.87it/s]

Epoch 7:   7%|▋         | 135/2000 [00:06<01:25, 21.88it/s]

Epoch 7:   7%|▋         | 138/2000 [00:06<01:25, 21.88it/s]

Epoch 7:   7%|▋         | 141/2000 [00:06<01:25, 21.86it/s]

Epoch 7:   7%|▋         | 144/2000 [00:06<01:24, 21.85it/s]

Epoch 7:   7%|▋         | 147/2000 [00:06<01:24, 21.85it/s]

Epoch 7:   8%|▊         | 150/2000 [00:06<01:24, 21.86it/s]

Epoch 7:   8%|▊         | 153/2000 [00:07<01:24, 21.86it/s]

Epoch 7:   8%|▊         | 156/2000 [00:07<01:24, 21.86it/s]

Epoch 7:   8%|▊         | 159/2000 [00:07<01:24, 21.86it/s]

Epoch 7:   8%|▊         | 162/2000 [00:07<01:24, 21.85it/s]

Epoch 7:   8%|▊         | 165/2000 [00:07<01:23, 21.85it/s]

Epoch 7:   8%|▊         | 168/2000 [00:07<01:23, 21.86it/s]

Epoch 7:   9%|▊         | 171/2000 [00:07<01:23, 21.86it/s]

Epoch 7:   9%|▊         | 174/2000 [00:07<01:23, 21.88it/s]

Epoch 7:   9%|▉         | 177/2000 [00:08<01:23, 21.88it/s]

Epoch 7:   9%|▉         | 180/2000 [00:08<01:23, 21.86it/s]

Epoch 7:   9%|▉         | 183/2000 [00:08<01:23, 21.86it/s]

Epoch 7:   9%|▉         | 186/2000 [00:08<01:23, 21.85it/s]

Epoch 7:   9%|▉         | 189/2000 [00:08<01:22, 21.87it/s]

Epoch 7:  10%|▉         | 192/2000 [00:08<01:22, 21.87it/s]

Epoch 7:  10%|▉         | 195/2000 [00:08<01:22, 21.88it/s]

Epoch 7:  10%|▉         | 198/2000 [00:09<01:22, 21.87it/s]

Epoch 7:  10%|█         | 201/2000 [00:09<01:22, 21.85it/s]

Epoch 7:  10%|█         | 204/2000 [00:09<01:22, 21.84it/s]

Epoch 7:  10%|█         | 207/2000 [00:09<01:22, 21.84it/s]

Epoch 7:  10%|█         | 210/2000 [00:09<01:21, 21.87it/s]

Epoch 7:  11%|█         | 213/2000 [00:09<01:21, 21.88it/s]

Epoch 7:  11%|█         | 216/2000 [00:09<01:21, 21.87it/s]

Epoch 7:  11%|█         | 219/2000 [00:10<01:21, 21.86it/s]

Epoch 7:  11%|█         | 222/2000 [00:10<01:21, 21.85it/s]

Epoch 7:  11%|█▏        | 225/2000 [00:10<01:21, 21.85it/s]

Epoch 7:  11%|█▏        | 228/2000 [00:10<01:21, 21.85it/s]

Epoch 7:  12%|█▏        | 231/2000 [00:10<01:20, 21.86it/s]

Epoch 7:  12%|█▏        | 234/2000 [00:10<01:20, 21.86it/s]

Epoch 7:  12%|█▏        | 237/2000 [00:10<01:20, 21.85it/s]

Epoch 7:  12%|█▏        | 240/2000 [00:10<01:20, 21.85it/s]

Epoch 7:  12%|█▏        | 243/2000 [00:11<01:20, 21.84it/s]

Epoch 7:  12%|█▏        | 246/2000 [00:11<01:20, 21.85it/s]

Epoch 7:  12%|█▏        | 249/2000 [00:11<01:20, 21.86it/s]

Epoch 7:  13%|█▎        | 252/2000 [00:11<01:19, 21.86it/s]

Epoch 7:  13%|█▎        | 255/2000 [00:11<01:19, 21.84it/s]

Epoch 7:  13%|█▎        | 258/2000 [00:11<01:19, 21.85it/s]

Epoch 7:  13%|█▎        | 261/2000 [00:11<01:19, 21.87it/s]

Epoch 7:  13%|█▎        | 264/2000 [00:12<01:19, 21.87it/s]

Epoch 7:  13%|█▎        | 267/2000 [00:12<01:19, 21.89it/s]

Epoch 7:  14%|█▎        | 270/2000 [00:12<01:19, 21.88it/s]

Epoch 7:  14%|█▎        | 273/2000 [00:12<01:18, 21.89it/s]

Epoch 7:  14%|█▍        | 276/2000 [00:12<01:18, 21.88it/s]

Epoch 7:  14%|█▍        | 279/2000 [00:12<01:18, 21.88it/s]

Epoch 7:  14%|█▍        | 282/2000 [00:12<01:18, 21.89it/s]

Epoch 7:  14%|█▍        | 285/2000 [00:13<01:18, 21.90it/s]

Epoch 7:  14%|█▍        | 288/2000 [00:13<01:18, 21.90it/s]

Epoch 7:  15%|█▍        | 291/2000 [00:13<01:18, 21.89it/s]

Epoch 7:  15%|█▍        | 294/2000 [00:13<01:17, 21.90it/s]

Epoch 7:  15%|█▍        | 297/2000 [00:13<01:17, 21.91it/s]

Epoch 7:  15%|█▌        | 300/2000 [00:13<01:17, 21.91it/s]

Epoch 7:  15%|█▌        | 303/2000 [00:13<01:17, 21.88it/s]

Epoch 7:  15%|█▌        | 306/2000 [00:13<01:17, 21.88it/s]

Epoch 7:  15%|█▌        | 309/2000 [00:14<01:17, 21.86it/s]

Epoch 7:  16%|█▌        | 312/2000 [00:14<01:17, 21.85it/s]

Epoch 7:  16%|█▌        | 315/2000 [00:14<01:17, 21.86it/s]

Epoch 7:  16%|█▌        | 318/2000 [00:14<01:16, 21.86it/s]

Epoch 7:  16%|█▌        | 321/2000 [00:14<01:16, 21.87it/s]

Epoch 7:  16%|█▌        | 324/2000 [00:14<01:16, 21.86it/s]

Epoch 7:  16%|█▋        | 327/2000 [00:14<01:16, 21.87it/s]

Epoch 7:  16%|█▋        | 330/2000 [00:15<01:16, 21.88it/s]

Epoch 7:  17%|█▋        | 333/2000 [00:15<01:16, 21.88it/s]

Epoch 7:  17%|█▋        | 336/2000 [00:15<01:16, 21.89it/s]

Epoch 7:  17%|█▋        | 339/2000 [00:15<01:15, 21.89it/s]

Epoch 7:  17%|█▋        | 342/2000 [00:15<01:15, 21.88it/s]

Epoch 7:  17%|█▋        | 345/2000 [00:15<01:15, 21.89it/s]

Epoch 7:  17%|█▋        | 348/2000 [00:15<01:15, 21.90it/s]

Epoch 7:  18%|█▊        | 351/2000 [00:16<01:15, 21.89it/s]

Epoch 7:  18%|█▊        | 354/2000 [00:16<01:15, 21.87it/s]

Epoch 7:  18%|█▊        | 357/2000 [00:16<01:15, 21.86it/s]

Epoch 7:  18%|█▊        | 360/2000 [00:16<01:15, 21.85it/s]

Epoch 7:  18%|█▊        | 363/2000 [00:16<01:14, 21.84it/s]

Epoch 7:  18%|█▊        | 366/2000 [00:16<01:14, 21.85it/s]

Epoch 7:  18%|█▊        | 369/2000 [00:16<01:14, 21.86it/s]

Epoch 7:  19%|█▊        | 372/2000 [00:17<01:14, 21.87it/s]

Epoch 7:  19%|█▉        | 375/2000 [00:17<01:14, 21.86it/s]

Epoch 7:  19%|█▉        | 378/2000 [00:17<01:14, 21.87it/s]

Epoch 7:  19%|█▉        | 381/2000 [00:17<01:14, 21.86it/s]

Epoch 7:  19%|█▉        | 384/2000 [00:17<01:14, 21.74it/s]

Epoch 7:  19%|█▉        | 387/2000 [00:17<01:14, 21.76it/s]

Epoch 7:  20%|█▉        | 390/2000 [00:17<01:19, 20.20it/s]

Epoch 7:  20%|█▉        | 393/2000 [00:18<01:23, 19.33it/s]

Epoch 7:  20%|█▉        | 396/2000 [00:18<01:20, 19.99it/s]

Epoch 7:  20%|█▉        | 399/2000 [00:18<01:18, 20.49it/s]

Epoch 7:  20%|██        | 402/2000 [00:18<01:16, 20.86it/s]

Epoch 7:  20%|██        | 405/2000 [00:18<01:15, 21.14it/s]

Epoch 7:  20%|██        | 408/2000 [00:18<01:14, 21.29it/s]

Epoch 7:  21%|██        | 411/2000 [00:18<01:14, 21.42it/s]

Epoch 7:  21%|██        | 414/2000 [00:19<01:13, 21.53it/s]

Epoch 7:  21%|██        | 417/2000 [00:19<01:13, 21.60it/s]

Epoch 7:  21%|██        | 420/2000 [00:19<01:12, 21.65it/s]

Epoch 7:  21%|██        | 423/2000 [00:19<01:12, 21.70it/s]

Epoch 7:  21%|██▏       | 426/2000 [00:19<01:12, 21.73it/s]

Epoch 7:  21%|██▏       | 429/2000 [00:19<01:12, 21.76it/s]

Epoch 7:  22%|██▏       | 432/2000 [00:19<01:12, 21.76it/s]

Epoch 7:  22%|██▏       | 435/2000 [00:19<01:11, 21.78it/s]

Epoch 7:  22%|██▏       | 438/2000 [00:20<01:11, 21.80it/s]

Epoch 7:  22%|██▏       | 441/2000 [00:20<01:11, 21.80it/s]

Epoch 7:  22%|██▏       | 444/2000 [00:20<01:11, 21.81it/s]

Epoch 7:  22%|██▏       | 447/2000 [00:20<01:11, 21.80it/s]

Epoch 7:  22%|██▎       | 450/2000 [00:20<01:11, 21.81it/s]

Epoch 7:  23%|██▎       | 453/2000 [00:20<01:10, 21.81it/s]

Epoch 7:  23%|██▎       | 456/2000 [00:20<01:10, 21.80it/s]

Epoch 7:  23%|██▎       | 459/2000 [00:21<01:10, 21.81it/s]

Epoch 7:  23%|██▎       | 462/2000 [00:21<01:10, 21.81it/s]

Epoch 7:  23%|██▎       | 465/2000 [00:21<01:10, 21.82it/s]

Epoch 7:  23%|██▎       | 468/2000 [00:21<01:10, 21.84it/s]

Epoch 7:  24%|██▎       | 471/2000 [00:21<01:10, 21.83it/s]

Epoch 7:  24%|██▎       | 474/2000 [00:21<01:09, 21.84it/s]

Epoch 7:  24%|██▍       | 477/2000 [00:21<01:09, 21.84it/s]

Epoch 7:  24%|██▍       | 480/2000 [00:22<01:09, 21.81it/s]

Epoch 7:  24%|██▍       | 483/2000 [00:22<01:09, 21.82it/s]

Epoch 7:  24%|██▍       | 486/2000 [00:22<01:09, 21.68it/s]

Epoch 7:  24%|██▍       | 489/2000 [00:22<01:09, 21.72it/s]

Epoch 7:  25%|██▍       | 492/2000 [00:22<01:09, 21.75it/s]

Epoch 7:  25%|██▍       | 495/2000 [00:22<01:09, 21.77it/s]

Epoch 7:  25%|██▍       | 498/2000 [00:22<01:08, 21.78it/s]

Epoch 7:  25%|██▌       | 501/2000 [00:23<01:08, 21.79it/s]

Epoch 7:  25%|██▌       | 504/2000 [00:23<01:08, 21.80it/s]

Epoch 7:  25%|██▌       | 507/2000 [00:23<01:08, 21.80it/s]

Epoch 7:  26%|██▌       | 510/2000 [00:23<01:08, 21.80it/s]

Epoch 7:  26%|██▌       | 513/2000 [00:23<01:08, 21.81it/s]

Epoch 7:  26%|██▌       | 516/2000 [00:23<01:07, 21.82it/s]

Epoch 7:  26%|██▌       | 519/2000 [00:23<01:07, 21.83it/s]

Epoch 7:  26%|██▌       | 522/2000 [00:23<01:07, 21.83it/s]

Epoch 7:  26%|██▋       | 525/2000 [00:24<01:07, 21.83it/s]

Epoch 7:  26%|██▋       | 528/2000 [00:24<01:07, 21.81it/s]

Epoch 7:  27%|██▋       | 531/2000 [00:24<01:07, 21.81it/s]

Epoch 7:  27%|██▋       | 534/2000 [00:24<01:07, 21.83it/s]

Epoch 7:  27%|██▋       | 537/2000 [00:24<01:06, 21.85it/s]

Epoch 7:  27%|██▋       | 540/2000 [00:24<01:06, 21.85it/s]

Epoch 7:  27%|██▋       | 543/2000 [00:24<01:06, 21.83it/s]

Epoch 7:  27%|██▋       | 546/2000 [00:25<01:06, 21.82it/s]

Epoch 7:  27%|██▋       | 549/2000 [00:25<01:06, 21.83it/s]

Epoch 7:  28%|██▊       | 552/2000 [00:25<01:06, 21.83it/s]

Epoch 7:  28%|██▊       | 555/2000 [00:25<01:06, 21.83it/s]

Epoch 7:  28%|██▊       | 558/2000 [00:25<01:06, 21.82it/s]

Epoch 7:  28%|██▊       | 561/2000 [00:25<01:05, 21.82it/s]

Epoch 7:  28%|██▊       | 564/2000 [00:25<01:05, 21.81it/s]

Epoch 7:  28%|██▊       | 567/2000 [00:26<01:05, 21.81it/s]

Epoch 7:  28%|██▊       | 570/2000 [00:26<01:05, 21.82it/s]

Epoch 7:  29%|██▊       | 573/2000 [00:26<01:05, 21.80it/s]

Epoch 7:  29%|██▉       | 576/2000 [00:26<01:05, 21.80it/s]

Epoch 7:  29%|██▉       | 579/2000 [00:26<01:05, 21.81it/s]

Epoch 7:  29%|██▉       | 582/2000 [00:26<01:04, 21.82it/s]

Epoch 7:  29%|██▉       | 585/2000 [00:26<01:04, 21.82it/s]

Epoch 7:  29%|██▉       | 588/2000 [00:26<01:04, 21.83it/s]

Epoch 7:  30%|██▉       | 591/2000 [00:27<01:04, 21.84it/s]

Epoch 7:  30%|██▉       | 594/2000 [00:27<01:04, 21.84it/s]

Epoch 7:  30%|██▉       | 597/2000 [00:27<01:04, 21.85it/s]

Epoch 7:  30%|███       | 600/2000 [00:27<01:04, 21.86it/s]

Epoch 7:  30%|███       | 603/2000 [00:27<01:03, 21.87it/s]

Epoch 7:  30%|███       | 606/2000 [00:27<01:03, 21.86it/s]

Epoch 7:  30%|███       | 609/2000 [00:27<01:03, 21.83it/s]

Epoch 7:  31%|███       | 612/2000 [00:28<01:03, 21.83it/s]

Epoch 7:  31%|███       | 615/2000 [00:28<01:03, 21.84it/s]

Epoch 7:  31%|███       | 618/2000 [00:28<01:03, 21.83it/s]

Epoch 7:  31%|███       | 621/2000 [00:28<01:03, 21.83it/s]

Epoch 7:  31%|███       | 624/2000 [00:28<01:03, 21.84it/s]

Epoch 7:  31%|███▏      | 627/2000 [00:28<01:02, 21.85it/s]

Epoch 7:  32%|███▏      | 630/2000 [00:28<01:02, 21.83it/s]

Epoch 7:  32%|███▏      | 633/2000 [00:29<01:02, 21.84it/s]

Epoch 7:  32%|███▏      | 636/2000 [00:29<01:02, 21.84it/s]

Epoch 7:  32%|███▏      | 639/2000 [00:29<01:02, 21.77it/s]

Epoch 7:  32%|███▏      | 642/2000 [00:29<01:02, 21.78it/s]

Epoch 7:  32%|███▏      | 645/2000 [00:29<01:02, 21.77it/s]

Epoch 7:  32%|███▏      | 648/2000 [00:29<01:02, 21.80it/s]

Epoch 7:  33%|███▎      | 651/2000 [00:29<01:01, 21.81it/s]

Epoch 7:  33%|███▎      | 654/2000 [00:30<01:01, 21.80it/s]

Epoch 7:  33%|███▎      | 657/2000 [00:30<01:01, 21.81it/s]

Epoch 7:  33%|███▎      | 660/2000 [00:30<01:01, 21.81it/s]

Epoch 7:  33%|███▎      | 663/2000 [00:30<01:01, 21.82it/s]

Epoch 7:  33%|███▎      | 666/2000 [00:30<01:01, 21.83it/s]

Epoch 7:  33%|███▎      | 669/2000 [00:30<01:01, 21.82it/s]

Epoch 7:  34%|███▎      | 672/2000 [00:30<01:00, 21.84it/s]

Epoch 7:  34%|███▍      | 675/2000 [00:30<01:00, 21.85it/s]

Epoch 7:  34%|███▍      | 678/2000 [00:31<01:00, 21.85it/s]

Epoch 7:  34%|███▍      | 681/2000 [00:31<01:00, 21.83it/s]

Epoch 7:  34%|███▍      | 684/2000 [00:31<01:00, 21.82it/s]

Epoch 7:  34%|███▍      | 687/2000 [00:31<01:00, 21.80it/s]

Epoch 7:  34%|███▍      | 690/2000 [00:31<01:00, 21.82it/s]

Epoch 7:  35%|███▍      | 693/2000 [00:31<00:59, 21.83it/s]

Epoch 7:  35%|███▍      | 696/2000 [00:31<00:59, 21.81it/s]

Epoch 7:  35%|███▍      | 699/2000 [00:32<00:59, 21.83it/s]

Epoch 7:  35%|███▌      | 702/2000 [00:32<00:59, 21.82it/s]

Epoch 7:  35%|███▌      | 705/2000 [00:32<00:59, 21.81it/s]

Epoch 7:  35%|███▌      | 708/2000 [00:32<01:00, 21.26it/s]

Epoch 7:  36%|███▌      | 711/2000 [00:32<01:01, 21.02it/s]

Epoch 7:  36%|███▌      | 714/2000 [00:32<01:00, 21.20it/s]

Epoch 7:  36%|███▌      | 717/2000 [00:32<01:00, 21.28it/s]

Epoch 7:  36%|███▌      | 720/2000 [00:33<00:59, 21.44it/s]

Epoch 7:  36%|███▌      | 723/2000 [00:33<00:59, 21.56it/s]

Epoch 7:  36%|███▋      | 726/2000 [00:33<00:58, 21.65it/s]

Epoch 7:  36%|███▋      | 729/2000 [00:33<00:58, 21.71it/s]

Epoch 7:  37%|███▋      | 732/2000 [00:33<00:58, 21.75it/s]

Epoch 7:  37%|███▋      | 735/2000 [00:33<00:58, 21.76it/s]

Epoch 7:  37%|███▋      | 738/2000 [00:33<00:57, 21.77it/s]

Epoch 7:  37%|███▋      | 741/2000 [00:34<00:57, 21.78it/s]

Epoch 7:  37%|███▋      | 744/2000 [00:34<00:57, 21.79it/s]

Epoch 7:  37%|███▋      | 747/2000 [00:34<00:57, 21.81it/s]

Epoch 7:  38%|███▊      | 750/2000 [00:34<00:57, 21.80it/s]

Epoch 7:  38%|███▊      | 753/2000 [00:34<00:57, 21.81it/s]

Epoch 7:  38%|███▊      | 756/2000 [00:34<00:56, 21.83it/s]

Epoch 7:  38%|███▊      | 759/2000 [00:34<00:56, 21.85it/s]

Epoch 7:  38%|███▊      | 762/2000 [00:34<00:56, 21.84it/s]

Epoch 7:  38%|███▊      | 765/2000 [00:35<00:56, 21.85it/s]

Epoch 7:  38%|███▊      | 768/2000 [00:35<00:56, 21.85it/s]

Epoch 7:  39%|███▊      | 771/2000 [00:35<00:56, 21.86it/s]

Epoch 7:  39%|███▊      | 774/2000 [00:35<00:56, 21.86it/s]

Epoch 7:  39%|███▉      | 777/2000 [00:35<00:55, 21.86it/s]

Epoch 7:  39%|███▉      | 780/2000 [00:35<00:55, 21.84it/s]

Epoch 7:  39%|███▉      | 783/2000 [00:35<00:55, 21.82it/s]

Epoch 7:  39%|███▉      | 786/2000 [00:36<00:55, 21.83it/s]

Epoch 7:  39%|███▉      | 789/2000 [00:36<00:55, 21.82it/s]

Epoch 7:  40%|███▉      | 792/2000 [00:36<00:55, 21.83it/s]

Epoch 7:  40%|███▉      | 795/2000 [00:36<00:55, 21.82it/s]

Epoch 7:  40%|███▉      | 798/2000 [00:36<00:55, 21.83it/s]

Epoch 7:  40%|████      | 801/2000 [00:36<00:54, 21.84it/s]

Epoch 7:  40%|████      | 804/2000 [00:36<00:54, 21.84it/s]

Epoch 7:  40%|████      | 807/2000 [00:37<00:54, 21.84it/s]

Epoch 7:  40%|████      | 810/2000 [00:37<00:54, 21.82it/s]

Epoch 7:  41%|████      | 813/2000 [00:37<00:54, 21.81it/s]

Epoch 7:  41%|████      | 816/2000 [00:37<00:54, 21.81it/s]

Epoch 7:  41%|████      | 819/2000 [00:37<00:54, 21.82it/s]

Epoch 7:  41%|████      | 822/2000 [00:37<00:53, 21.83it/s]

Epoch 7:  41%|████▏     | 825/2000 [00:37<00:53, 21.83it/s]

Epoch 7:  41%|████▏     | 828/2000 [00:38<00:53, 21.83it/s]

Epoch 7:  42%|████▏     | 831/2000 [00:38<00:53, 21.82it/s]

Epoch 7:  42%|████▏     | 834/2000 [00:38<00:53, 21.84it/s]

Epoch 7:  42%|████▏     | 837/2000 [00:38<00:53, 21.82it/s]

Epoch 7:  42%|████▏     | 840/2000 [00:38<00:53, 21.85it/s]

Epoch 7:  42%|████▏     | 843/2000 [00:38<00:53, 21.83it/s]

Epoch 7:  42%|████▏     | 846/2000 [00:38<00:52, 21.82it/s]

Epoch 7:  42%|████▏     | 849/2000 [00:38<00:52, 21.81it/s]

Epoch 7:  43%|████▎     | 852/2000 [00:39<00:52, 21.82it/s]

Epoch 7:  43%|████▎     | 855/2000 [00:39<00:52, 21.82it/s]

Epoch 7:  43%|████▎     | 858/2000 [00:39<00:52, 21.82it/s]

Epoch 7:  43%|████▎     | 861/2000 [00:39<00:52, 21.82it/s]

Epoch 7:  43%|████▎     | 864/2000 [00:39<00:52, 21.83it/s]

Epoch 7:  43%|████▎     | 867/2000 [00:39<00:51, 21.82it/s]

Epoch 7:  44%|████▎     | 870/2000 [00:39<00:51, 21.79it/s]

Epoch 7:  44%|████▎     | 873/2000 [00:40<00:51, 21.80it/s]

Epoch 7:  44%|████▍     | 876/2000 [00:40<00:51, 21.79it/s]

Epoch 7:  44%|████▍     | 879/2000 [00:40<00:51, 21.81it/s]

Epoch 7:  44%|████▍     | 882/2000 [00:40<00:51, 21.81it/s]

Epoch 7:  44%|████▍     | 885/2000 [00:40<00:51, 21.83it/s]

Epoch 7:  44%|████▍     | 888/2000 [00:40<00:50, 21.82it/s]

Epoch 7:  45%|████▍     | 891/2000 [00:40<00:50, 21.81it/s]

Epoch 7:  45%|████▍     | 894/2000 [00:41<00:50, 21.82it/s]

Epoch 7:  45%|████▍     | 897/2000 [00:41<00:50, 21.82it/s]

Epoch 7:  45%|████▌     | 900/2000 [00:41<00:50, 21.82it/s]

Epoch 7:  45%|████▌     | 903/2000 [00:41<00:50, 21.83it/s]

Epoch 7:  45%|████▌     | 906/2000 [00:41<00:50, 21.83it/s]

Epoch 7:  45%|████▌     | 909/2000 [00:41<00:49, 21.83it/s]

Epoch 7:  46%|████▌     | 912/2000 [00:41<00:49, 21.81it/s]

Epoch 7:  46%|████▌     | 915/2000 [00:41<00:49, 21.82it/s]

Epoch 7:  46%|████▌     | 918/2000 [00:42<00:49, 21.81it/s]

Epoch 7:  46%|████▌     | 921/2000 [00:42<00:49, 21.83it/s]

Epoch 7:  46%|████▌     | 924/2000 [00:42<00:49, 21.82it/s]

Epoch 7:  46%|████▋     | 927/2000 [00:42<00:49, 21.83it/s]

Epoch 7:  46%|████▋     | 930/2000 [00:42<00:48, 21.85it/s]

Epoch 7:  47%|████▋     | 933/2000 [00:42<00:48, 21.85it/s]

Epoch 7:  47%|████▋     | 936/2000 [00:42<00:48, 21.83it/s]

Epoch 7:  47%|████▋     | 939/2000 [00:43<00:48, 21.82it/s]

Epoch 7:  47%|████▋     | 942/2000 [00:43<00:48, 21.84it/s]

Epoch 7:  47%|████▋     | 945/2000 [00:43<00:48, 21.86it/s]

Epoch 7:  47%|████▋     | 948/2000 [00:43<00:48, 21.86it/s]

Epoch 7:  48%|████▊     | 951/2000 [00:43<00:47, 21.86it/s]

Epoch 7:  48%|████▊     | 954/2000 [00:43<00:47, 21.86it/s]

Epoch 7:  48%|████▊     | 957/2000 [00:43<00:47, 21.85it/s]

Epoch 7:  48%|████▊     | 960/2000 [00:44<00:47, 21.84it/s]

Epoch 7:  48%|████▊     | 963/2000 [00:44<00:47, 21.84it/s]

Epoch 7:  48%|████▊     | 966/2000 [00:44<00:47, 21.83it/s]

Epoch 7:  48%|████▊     | 969/2000 [00:44<00:47, 21.83it/s]

Epoch 7:  49%|████▊     | 972/2000 [00:44<00:47, 21.84it/s]

Epoch 7:  49%|████▉     | 975/2000 [00:44<00:46, 21.83it/s]

Epoch 7:  49%|████▉     | 978/2000 [00:44<00:46, 21.81it/s]

Epoch 7:  49%|████▉     | 981/2000 [00:45<00:46, 21.80it/s]

Epoch 7:  49%|████▉     | 984/2000 [00:45<00:46, 21.81it/s]

Epoch 7:  49%|████▉     | 987/2000 [00:45<00:46, 21.80it/s]

Epoch 7:  50%|████▉     | 990/2000 [00:45<00:46, 21.83it/s]

Epoch 7:  50%|████▉     | 993/2000 [00:45<00:46, 21.83it/s]

Epoch 7:  50%|████▉     | 996/2000 [00:45<00:45, 21.84it/s]

Epoch 7:  50%|████▉     | 999/2000 [00:45<00:45, 21.85it/s]

Epoch 7:  50%|█████     | 1002/2000 [00:45<00:45, 21.84it/s]

Epoch 7:  50%|█████     | 1005/2000 [00:46<00:45, 21.84it/s]

Epoch 7:  50%|█████     | 1008/2000 [00:46<00:45, 21.84it/s]

Epoch 7:  51%|█████     | 1011/2000 [00:46<00:45, 21.84it/s]

Epoch 7:  51%|█████     | 1014/2000 [00:46<00:45, 21.84it/s]

Epoch 7:  51%|█████     | 1017/2000 [00:46<00:44, 21.85it/s]

Epoch 7:  51%|█████     | 1020/2000 [00:46<00:44, 21.87it/s]

Epoch 7:  51%|█████     | 1023/2000 [00:46<00:44, 21.87it/s]

Epoch 7:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.86it/s]

Epoch 7:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.84it/s]

Epoch 7:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.83it/s]

Epoch 7:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.85it/s]

Epoch 7:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.86it/s]

Epoch 7:  52%|█████▏    | 1041/2000 [00:47<00:43, 21.82it/s]

Epoch 7:  52%|█████▏    | 1044/2000 [00:47<00:43, 21.82it/s]

Epoch 7:  52%|█████▏    | 1047/2000 [00:48<00:43, 21.82it/s]

Epoch 7:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.82it/s]

Epoch 7:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.83it/s]

Epoch 7:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.82it/s]

Epoch 7:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.81it/s]

Epoch 7:  53%|█████▎    | 1062/2000 [00:48<00:42, 21.82it/s]

Epoch 7:  53%|█████▎    | 1065/2000 [00:48<00:42, 21.82it/s]

Epoch 7:  53%|█████▎    | 1068/2000 [00:49<00:42, 21.82it/s]

Epoch 7:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.81it/s]

Epoch 7:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.81it/s]

Epoch 7:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.82it/s]

Epoch 7:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.82it/s]

Epoch 7:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.80it/s]

Epoch 7:  54%|█████▍    | 1086/2000 [00:49<00:41, 21.80it/s]

Epoch 7:  54%|█████▍    | 1089/2000 [00:49<00:41, 21.78it/s]

Epoch 7:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.80it/s]

Epoch 7:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.81it/s]

Epoch 7:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.82it/s]

Epoch 7:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.82it/s]

Epoch 7:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.82it/s]

Epoch 7:  55%|█████▌    | 1107/2000 [00:50<00:40, 21.82it/s]

Epoch 7:  56%|█████▌    | 1110/2000 [00:50<00:40, 21.83it/s]

Epoch 7:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.85it/s]

Epoch 7:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.84it/s]

Epoch 7:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.84it/s]

Epoch 7:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.83it/s]

Epoch 7:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.82it/s]

Epoch 7:  56%|█████▋    | 1128/2000 [00:51<00:40, 21.56it/s]

Epoch 7:  57%|█████▋    | 1131/2000 [00:51<00:40, 21.65it/s]

Epoch 7:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.70it/s]

Epoch 7:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.73it/s]

Epoch 7:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.77it/s]

Epoch 7:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.80it/s]

Epoch 7:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.83it/s]

Epoch 7:  57%|█████▋    | 1149/2000 [00:52<00:38, 21.83it/s]

Epoch 7:  58%|█████▊    | 1152/2000 [00:52<00:38, 21.84it/s]

Epoch 7:  58%|█████▊    | 1155/2000 [00:52<00:38, 21.84it/s]

Epoch 7:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.85it/s]

Epoch 7:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.84it/s]

Epoch 7:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.85it/s]

Epoch 7:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.86it/s]

Epoch 7:  58%|█████▊    | 1170/2000 [00:53<00:37, 21.87it/s]

Epoch 7:  59%|█████▊    | 1173/2000 [00:53<00:37, 21.88it/s]

Epoch 7:  59%|█████▉    | 1176/2000 [00:53<00:37, 21.88it/s]

Epoch 7:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.87it/s]

Epoch 7:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.85it/s]

Epoch 7:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.85it/s]

Epoch 7:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.84it/s]

Epoch 7:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.85it/s]

Epoch 7:  60%|█████▉    | 1194/2000 [00:54<00:36, 21.86it/s]

Epoch 7:  60%|█████▉    | 1197/2000 [00:54<00:36, 21.86it/s]

Epoch 7:  60%|██████    | 1200/2000 [00:55<00:36, 21.85it/s]

Epoch 7:  60%|██████    | 1203/2000 [00:55<00:36, 21.87it/s]

Epoch 7:  60%|██████    | 1206/2000 [00:55<00:36, 21.86it/s]

Epoch 7:  60%|██████    | 1209/2000 [00:55<00:36, 21.58it/s]

Epoch 7:  61%|██████    | 1212/2000 [00:55<00:36, 21.66it/s]

Epoch 7:  61%|██████    | 1215/2000 [00:55<00:36, 21.40it/s]

Epoch 7:  61%|██████    | 1218/2000 [00:55<00:36, 21.51it/s]

Epoch 7:  61%|██████    | 1221/2000 [00:56<00:36, 21.60it/s]

Epoch 7:  61%|██████    | 1224/2000 [00:56<00:35, 21.66it/s]

Epoch 7:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.51it/s]

Epoch 7:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.62it/s]

Epoch 7:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.69it/s]

Epoch 7:  62%|██████▏   | 1236/2000 [00:56<00:35, 21.74it/s]

Epoch 7:  62%|██████▏   | 1239/2000 [00:56<00:35, 21.57it/s]

Epoch 7:  62%|██████▏   | 1242/2000 [00:57<00:35, 21.65it/s]

Epoch 7:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.70it/s]

Epoch 7:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.75it/s]

Epoch 7:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.80it/s]

Epoch 7:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.82it/s]

Epoch 7:  63%|██████▎   | 1257/2000 [00:57<00:34, 21.84it/s]

Epoch 7:  63%|██████▎   | 1260/2000 [00:57<00:33, 21.84it/s]

Epoch 7:  63%|██████▎   | 1263/2000 [00:57<00:33, 21.85it/s]

Epoch 7:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.86it/s]

Epoch 7:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.84it/s]

Epoch 7:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.85it/s]

Epoch 7:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.84it/s]

Epoch 7:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.84it/s]

Epoch 7:  64%|██████▍   | 1281/2000 [00:58<00:32, 21.85it/s]

Epoch 7:  64%|██████▍   | 1284/2000 [00:58<00:32, 21.80it/s]

Epoch 7:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.80it/s]

Epoch 7:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.82it/s]

Epoch 7:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.81it/s]

Epoch 7:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.83it/s]

Epoch 7:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.84it/s]

Epoch 7:  65%|██████▌   | 1302/2000 [00:59<00:31, 21.85it/s]

Epoch 7:  65%|██████▌   | 1305/2000 [00:59<00:31, 21.87it/s]

Epoch 7:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.87it/s]

Epoch 7:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.85it/s]

Epoch 7:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.84it/s]

Epoch 7:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.85it/s]

Epoch 7:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.85it/s]

Epoch 7:  66%|██████▌   | 1323/2000 [01:00<00:31, 21.84it/s]

Epoch 7:  66%|██████▋   | 1326/2000 [01:00<00:30, 21.85it/s]

Epoch 7:  66%|██████▋   | 1329/2000 [01:00<00:30, 21.87it/s]

Epoch 7:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.88it/s]

Epoch 7:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.87it/s]

Epoch 7:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.86it/s]

Epoch 7:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.85it/s]

Epoch 7:  67%|██████▋   | 1344/2000 [01:01<00:30, 21.85it/s]

Epoch 7:  67%|██████▋   | 1347/2000 [01:01<00:29, 21.84it/s]

Epoch 7:  68%|██████▊   | 1350/2000 [01:01<00:29, 21.85it/s]

Epoch 7:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.87it/s]

Epoch 7:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.85it/s]

Epoch 7:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.85it/s]

Epoch 7:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.85it/s]

Epoch 7:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.86it/s]

Epoch 7:  68%|██████▊   | 1368/2000 [01:02<00:28, 21.87it/s]

Epoch 7:  69%|██████▊   | 1371/2000 [01:02<00:28, 21.86it/s]

Epoch 7:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.87it/s]

Epoch 7:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.87it/s]

Epoch 7:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.84it/s]

Epoch 7:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.84it/s]

Epoch 7:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.85it/s]

Epoch 7:  69%|██████▉   | 1389/2000 [01:03<00:27, 21.86it/s]

Epoch 7:  70%|██████▉   | 1392/2000 [01:03<00:27, 21.87it/s]

Epoch 7:  70%|██████▉   | 1395/2000 [01:04<00:27, 21.85it/s]

Epoch 7:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.83it/s]

Epoch 7:  70%|███████   | 1401/2000 [01:04<00:27, 21.83it/s]

Epoch 7:  70%|███████   | 1404/2000 [01:04<00:27, 21.85it/s]

Epoch 7:  70%|███████   | 1407/2000 [01:04<00:27, 21.85it/s]

Epoch 7:  70%|███████   | 1410/2000 [01:04<00:26, 21.87it/s]

Epoch 7:  71%|███████   | 1413/2000 [01:04<00:26, 21.87it/s]

Epoch 7:  71%|███████   | 1416/2000 [01:04<00:26, 21.85it/s]

Epoch 7:  71%|███████   | 1419/2000 [01:05<00:26, 21.84it/s]

Epoch 7:  71%|███████   | 1422/2000 [01:05<00:26, 21.59it/s]

Epoch 7:  71%|███████▏  | 1425/2000 [01:05<00:27, 21.09it/s]

Epoch 7:  71%|███████▏  | 1428/2000 [01:05<00:27, 21.16it/s]

Epoch 7:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.31it/s]

Epoch 7:  72%|███████▏  | 1434/2000 [01:05<00:26, 21.44it/s]

Epoch 7:  72%|███████▏  | 1437/2000 [01:05<00:26, 21.56it/s]

Epoch 7:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.65it/s]

Epoch 7:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.72it/s]

Epoch 7:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.76it/s]

Epoch 7:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.77it/s]

Epoch 7:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.79it/s]

Epoch 7:  73%|███████▎  | 1455/2000 [01:06<00:24, 21.81it/s]

Epoch 7:  73%|███████▎  | 1458/2000 [01:06<00:24, 21.83it/s]

Epoch 7:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.84it/s]

Epoch 7:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.85it/s]

Epoch 7:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.85it/s]

Epoch 7:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.85it/s]

Epoch 7:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.85it/s]

Epoch 7:  74%|███████▍  | 1476/2000 [01:07<00:23, 21.85it/s]

Epoch 7:  74%|███████▍  | 1479/2000 [01:07<00:23, 21.81it/s]

Epoch 7:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.83it/s]

Epoch 7:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.85it/s]

Epoch 7:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.88it/s]

Epoch 7:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.85it/s]

Epoch 7:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.84it/s]

Epoch 7:  75%|███████▍  | 1497/2000 [01:08<00:23, 21.84it/s]

Epoch 7:  75%|███████▌  | 1500/2000 [01:08<00:22, 21.85it/s]

Epoch 7:  75%|███████▌  | 1503/2000 [01:08<00:22, 21.86it/s]

Epoch 7:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.88it/s]

Epoch 7:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.87it/s]

Epoch 7:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.86it/s]

Epoch 7:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.85it/s]

Epoch 7:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.85it/s]

Epoch 7:  76%|███████▌  | 1521/2000 [01:09<00:21, 21.86it/s]

Epoch 7:  76%|███████▌  | 1524/2000 [01:09<00:21, 21.87it/s]

Epoch 7:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.87it/s]

Epoch 7:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.86it/s]

Epoch 7:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.85it/s]

Epoch 7:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.87it/s]

Epoch 7:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.87it/s]

Epoch 7:  77%|███████▋  | 1542/2000 [01:10<00:20, 21.86it/s]

Epoch 7:  77%|███████▋  | 1545/2000 [01:10<00:20, 21.84it/s]

Epoch 7:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.84it/s]

Epoch 7:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.85it/s]

Epoch 7:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.84it/s]

Epoch 7:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.87it/s]

Epoch 7:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.86it/s]

Epoch 7:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.85it/s]

Epoch 7:  78%|███████▊  | 1566/2000 [01:11<00:19, 21.84it/s]

Epoch 7:  78%|███████▊  | 1569/2000 [01:11<00:19, 21.84it/s]

Epoch 7:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.83it/s]

Epoch 7:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.84it/s]

Epoch 7:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.84it/s]

Epoch 7:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.86it/s]

Epoch 7:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.86it/s]

Epoch 7:  79%|███████▉  | 1587/2000 [01:12<00:18, 21.85it/s]

Epoch 7:  80%|███████▉  | 1590/2000 [01:12<00:18, 21.85it/s]

Epoch 7:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.86it/s]

Epoch 7:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.86it/s]

Epoch 7:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.87it/s]

Epoch 7:  80%|████████  | 1602/2000 [01:13<00:18, 21.86it/s]

Epoch 7:  80%|████████  | 1605/2000 [01:13<00:18, 21.85it/s]

Epoch 7:  80%|████████  | 1608/2000 [01:13<00:17, 21.86it/s]

Epoch 7:  81%|████████  | 1611/2000 [01:13<00:17, 21.86it/s]

Epoch 7:  81%|████████  | 1614/2000 [01:14<00:17, 21.86it/s]

Epoch 7:  81%|████████  | 1617/2000 [01:14<00:17, 21.85it/s]

Epoch 7:  81%|████████  | 1620/2000 [01:14<00:17, 21.85it/s]

Epoch 7:  81%|████████  | 1623/2000 [01:14<00:17, 21.84it/s]

Epoch 7:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.82it/s]

Epoch 7:  81%|████████▏ | 1629/2000 [01:14<00:16, 21.82it/s]

Epoch 7:  82%|████████▏ | 1632/2000 [01:14<00:16, 21.82it/s]

Epoch 7:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.83it/s]

Epoch 7:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.83it/s]

Epoch 7:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.81it/s]

Epoch 7:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.81it/s]

Epoch 7:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.83it/s]

Epoch 7:  82%|████████▎ | 1650/2000 [01:15<00:16, 21.84it/s]

Epoch 7:  83%|████████▎ | 1653/2000 [01:15<00:15, 21.86it/s]

Epoch 7:  83%|████████▎ | 1656/2000 [01:15<00:15, 21.86it/s]

Epoch 7:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.85it/s]

Epoch 7:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.83it/s]

Epoch 7:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.82it/s]

Epoch 7:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.84it/s]

Epoch 7:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.85it/s]

Epoch 7:  84%|████████▎ | 1674/2000 [01:16<00:14, 21.87it/s]

Epoch 7:  84%|████████▍ | 1677/2000 [01:16<00:14, 21.87it/s]

Epoch 7:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.86it/s]

Epoch 7:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.87it/s]

Epoch 7:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.85it/s]

Epoch 7:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.86it/s]

Epoch 7:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.88it/s]

Epoch 7:  85%|████████▍ | 1695/2000 [01:17<00:13, 21.81it/s]

Epoch 7:  85%|████████▍ | 1698/2000 [01:17<00:13, 21.81it/s]

Epoch 7:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.82it/s]

Epoch 7:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.82it/s]

Epoch 7:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.82it/s]

Epoch 7:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.83it/s]

Epoch 7:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.85it/s]

Epoch 7:  86%|████████▌ | 1716/2000 [01:18<00:12, 21.86it/s]

Epoch 7:  86%|████████▌ | 1719/2000 [01:18<00:12, 21.84it/s]

Epoch 7:  86%|████████▌ | 1722/2000 [01:18<00:12, 21.84it/s]

Epoch 7:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.81it/s]

Epoch 7:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.83it/s]

Epoch 7:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.84it/s]

Epoch 7:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.85it/s]

Epoch 7:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.83it/s]

Epoch 7:  87%|████████▋ | 1740/2000 [01:19<00:11, 21.84it/s]

Epoch 7:  87%|████████▋ | 1743/2000 [01:19<00:11, 21.84it/s]

Epoch 7:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.84it/s]

Epoch 7:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.84it/s]

Epoch 7:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.85it/s]

Epoch 7:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.85it/s]

Epoch 7:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.85it/s]

Epoch 7:  88%|████████▊ | 1761/2000 [01:20<00:10, 21.84it/s]

Epoch 7:  88%|████████▊ | 1764/2000 [01:20<00:10, 21.85it/s]

Epoch 7:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.86it/s]

Epoch 7:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.88it/s]

Epoch 7:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.84it/s]

Epoch 7:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.84it/s]

Epoch 7:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.83it/s]

Epoch 7:  89%|████████▉ | 1782/2000 [01:21<00:09, 21.83it/s]

Epoch 7:  89%|████████▉ | 1785/2000 [01:21<00:09, 21.84it/s]

Epoch 7:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.85it/s]

Epoch 7:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.87it/s]

Epoch 7:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.86it/s]

Epoch 7:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.84it/s]

Epoch 7:  90%|█████████ | 1800/2000 [01:22<00:09, 21.85it/s]

Epoch 7:  90%|█████████ | 1803/2000 [01:22<00:09, 21.84it/s]

Epoch 7:  90%|█████████ | 1806/2000 [01:22<00:08, 21.85it/s]

Epoch 7:  90%|█████████ | 1809/2000 [01:22<00:08, 21.87it/s]

Epoch 7:  91%|█████████ | 1812/2000 [01:23<00:08, 21.85it/s]

Epoch 7:  91%|█████████ | 1815/2000 [01:23<00:08, 21.85it/s]

Epoch 7:  91%|█████████ | 1818/2000 [01:23<00:08, 21.85it/s]

Epoch 7:  91%|█████████ | 1821/2000 [01:23<00:08, 21.85it/s]

Epoch 7:  91%|█████████ | 1824/2000 [01:23<00:08, 21.86it/s]

Epoch 7:  91%|█████████▏| 1827/2000 [01:23<00:07, 21.86it/s]

Epoch 7:  92%|█████████▏| 1830/2000 [01:23<00:07, 21.87it/s]

Epoch 7:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.86it/s]

Epoch 7:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.85it/s]

Epoch 7:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.84it/s]

Epoch 7:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.84it/s]

Epoch 7:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.85it/s]

Epoch 7:  92%|█████████▏| 1848/2000 [01:24<00:06, 21.87it/s]

Epoch 7:  93%|█████████▎| 1851/2000 [01:24<00:06, 21.86it/s]

Epoch 7:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.85it/s]

Epoch 7:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.84it/s]

Epoch 7:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.83it/s]

Epoch 7:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.86it/s]

Epoch 7:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.87it/s]

Epoch 7:  93%|█████████▎| 1869/2000 [01:25<00:05, 21.85it/s]

Epoch 7:  94%|█████████▎| 1872/2000 [01:25<00:05, 21.85it/s]

Epoch 7:  94%|█████████▍| 1875/2000 [01:25<00:05, 21.83it/s]

Epoch 7:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.84it/s]

Epoch 7:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.85it/s]

Epoch 7:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.85it/s]

Epoch 7:  94%|█████████▍| 1887/2000 [01:26<00:05, 21.86it/s]

Epoch 7:  94%|█████████▍| 1890/2000 [01:26<00:05, 21.86it/s]

Epoch 7:  95%|█████████▍| 1893/2000 [01:26<00:04, 21.86it/s]

Epoch 7:  95%|█████████▍| 1896/2000 [01:26<00:04, 21.85it/s]

Epoch 7:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.86it/s]

Epoch 7:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.87it/s]

Epoch 7:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.87it/s]

Epoch 7:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.86it/s]

Epoch 7:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.86it/s]

Epoch 7:  96%|█████████▌| 1914/2000 [01:27<00:03, 21.85it/s]

Epoch 7:  96%|█████████▌| 1917/2000 [01:27<00:03, 21.85it/s]

Epoch 7:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.87it/s]

Epoch 7:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.85it/s]

Epoch 7:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.83it/s]

Epoch 7:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.83it/s]

Epoch 7:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.84it/s]

Epoch 7:  97%|█████████▋| 1935/2000 [01:28<00:02, 21.85it/s]

Epoch 7:  97%|█████████▋| 1938/2000 [01:28<00:02, 21.84it/s]

Epoch 7:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.86it/s]

Epoch 7:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.86it/s]

Epoch 7:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.87it/s]

Epoch 7:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.87it/s]

Epoch 7:  98%|█████████▊| 1953/2000 [01:29<00:02, 21.86it/s]

Epoch 7:  98%|█████████▊| 1956/2000 [01:29<00:02, 21.87it/s]

Epoch 7:  98%|█████████▊| 1959/2000 [01:29<00:01, 21.87it/s]

Epoch 7:  98%|█████████▊| 1962/2000 [01:29<00:01, 21.88it/s]

Epoch 7:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.88it/s]

Epoch 7:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.88it/s]

Epoch 7:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.89it/s]

Epoch 7:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.88it/s]

Epoch 7:  99%|█████████▉| 1977/2000 [01:30<00:01, 21.87it/s]

Epoch 7:  99%|█████████▉| 1980/2000 [01:30<00:00, 21.88it/s]

Epoch 7:  99%|█████████▉| 1983/2000 [01:30<00:00, 21.87it/s]

Epoch 7:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.89it/s]

Epoch 7:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.88it/s]

Epoch 7: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.89it/s]

Epoch 7: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.89it/s]

Epoch 7: 100%|█████████▉| 1998/2000 [01:31<00:00, 21.89it/s]

Epoch 7: loss=0.3853, val_proxy=0.5066

Epoch 8:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 8:   0%|          | 3/2000 [00:00<01:33, 21.39it/s]

Epoch 8:   0%|          | 6/2000 [00:00<01:32, 21.57it/s]

Epoch 8:   0%|          | 9/2000 [00:00<01:32, 21.61it/s]

Epoch 8:   1%|          | 12/2000 [00:00<01:31, 21.65it/s]

Epoch 8:   1%|          | 15/2000 [00:00<01:31, 21.67it/s]

Epoch 8:   1%|          | 18/2000 [00:00<01:31, 21.70it/s]

Epoch 8:   1%|          | 21/2000 [00:00<01:31, 21.71it/s]

Epoch 8:   1%|          | 24/2000 [00:01<01:30, 21.72it/s]

Epoch 8:   1%|▏         | 27/2000 [00:01<01:30, 21.74it/s]

Epoch 8:   2%|▏         | 30/2000 [00:01<01:30, 21.74it/s]

Epoch 8:   2%|▏         | 33/2000 [00:01<01:30, 21.75it/s]

Epoch 8:   2%|▏         | 36/2000 [00:01<01:30, 21.75it/s]

Epoch 8:   2%|▏         | 39/2000 [00:01<01:30, 21.76it/s]

Epoch 8:   2%|▏         | 42/2000 [00:01<01:30, 21.73it/s]

Epoch 8:   2%|▏         | 45/2000 [00:02<01:29, 21.75it/s]

Epoch 8:   2%|▏         | 48/2000 [00:02<01:29, 21.73it/s]

Epoch 8:   3%|▎         | 51/2000 [00:02<01:29, 21.75it/s]

Epoch 8:   3%|▎         | 54/2000 [00:02<01:29, 21.73it/s]

Epoch 8:   3%|▎         | 57/2000 [00:02<01:29, 21.74it/s]

Epoch 8:   3%|▎         | 60/2000 [00:02<01:29, 21.74it/s]

Epoch 8:   3%|▎         | 63/2000 [00:02<01:29, 21.76it/s]

Epoch 8:   3%|▎         | 66/2000 [00:03<01:28, 21.75it/s]

Epoch 8:   3%|▎         | 69/2000 [00:03<01:28, 21.74it/s]

Epoch 8:   4%|▎         | 72/2000 [00:03<01:28, 21.74it/s]

Epoch 8:   4%|▍         | 75/2000 [00:03<01:28, 21.74it/s]

Epoch 8:   4%|▍         | 78/2000 [00:03<01:28, 21.77it/s]

Epoch 8:   4%|▍         | 81/2000 [00:03<01:28, 21.76it/s]

Epoch 8:   4%|▍         | 84/2000 [00:03<01:28, 21.76it/s]

Epoch 8:   4%|▍         | 87/2000 [00:04<01:27, 21.76it/s]

Epoch 8:   4%|▍         | 90/2000 [00:04<01:27, 21.76it/s]

Epoch 8:   5%|▍         | 93/2000 [00:04<01:27, 21.75it/s]

Epoch 8:   5%|▍         | 96/2000 [00:04<01:27, 21.74it/s]

Epoch 8:   5%|▍         | 99/2000 [00:04<01:27, 21.75it/s]

Epoch 8:   5%|▌         | 102/2000 [00:04<01:27, 21.75it/s]

Epoch 8:   5%|▌         | 105/2000 [00:04<01:27, 21.75it/s]

Epoch 8:   5%|▌         | 108/2000 [00:04<01:26, 21.76it/s]

Epoch 8:   6%|▌         | 111/2000 [00:05<01:26, 21.76it/s]

Epoch 8:   6%|▌         | 114/2000 [00:05<01:26, 21.76it/s]

Epoch 8:   6%|▌         | 117/2000 [00:05<01:26, 21.76it/s]

Epoch 8:   6%|▌         | 120/2000 [00:05<01:26, 21.77it/s]

Epoch 8:   6%|▌         | 123/2000 [00:05<01:26, 21.78it/s]

Epoch 8:   6%|▋         | 126/2000 [00:05<01:26, 21.79it/s]

Epoch 8:   6%|▋         | 129/2000 [00:05<01:25, 21.78it/s]

Epoch 8:   7%|▋         | 132/2000 [00:06<01:25, 21.77it/s]

Epoch 8:   7%|▋         | 135/2000 [00:06<01:25, 21.77it/s]

Epoch 8:   7%|▋         | 138/2000 [00:06<01:25, 21.77it/s]

Epoch 8:   7%|▋         | 141/2000 [00:06<01:25, 21.75it/s]

Epoch 8:   7%|▋         | 144/2000 [00:06<01:25, 21.76it/s]

Epoch 8:   7%|▋         | 147/2000 [00:06<01:25, 21.76it/s]

Epoch 8:   8%|▊         | 150/2000 [00:06<01:25, 21.76it/s]

Epoch 8:   8%|▊         | 153/2000 [00:07<01:24, 21.76it/s]

Epoch 8:   8%|▊         | 156/2000 [00:07<01:24, 21.75it/s]

Epoch 8:   8%|▊         | 159/2000 [00:07<01:24, 21.77it/s]

Epoch 8:   8%|▊         | 162/2000 [00:07<01:24, 21.77it/s]

Epoch 8:   8%|▊         | 165/2000 [00:07<01:24, 21.77it/s]

Epoch 8:   8%|▊         | 168/2000 [00:07<01:24, 21.78it/s]

Epoch 8:   9%|▊         | 171/2000 [00:07<01:24, 21.77it/s]

Epoch 8:   9%|▊         | 174/2000 [00:08<01:23, 21.78it/s]

Epoch 8:   9%|▉         | 177/2000 [00:08<01:23, 21.76it/s]

Epoch 8:   9%|▉         | 180/2000 [00:08<01:23, 21.77it/s]

Epoch 8:   9%|▉         | 183/2000 [00:08<01:23, 21.76it/s]

Epoch 8:   9%|▉         | 186/2000 [00:08<01:23, 21.77it/s]

Epoch 8:   9%|▉         | 189/2000 [00:08<01:23, 21.79it/s]

Epoch 8:  10%|▉         | 192/2000 [00:08<01:23, 21.77it/s]

Epoch 8:  10%|▉         | 195/2000 [00:08<01:23, 21.68it/s]

Epoch 8:  10%|▉         | 198/2000 [00:09<01:23, 21.70it/s]

Epoch 8:  10%|█         | 201/2000 [00:09<01:22, 21.72it/s]

Epoch 8:  10%|█         | 204/2000 [00:09<01:22, 21.74it/s]

Epoch 8:  10%|█         | 207/2000 [00:09<01:22, 21.75it/s]

Epoch 8:  10%|█         | 210/2000 [00:09<01:22, 21.77it/s]

Epoch 8:  11%|█         | 213/2000 [00:09<01:22, 21.76it/s]

Epoch 8:  11%|█         | 216/2000 [00:09<01:21, 21.77it/s]

Epoch 8:  11%|█         | 219/2000 [00:10<01:21, 21.77it/s]

Epoch 8:  11%|█         | 222/2000 [00:10<01:21, 21.77it/s]

Epoch 8:  11%|█▏        | 225/2000 [00:10<01:21, 21.77it/s]

Epoch 8:  11%|█▏        | 228/2000 [00:10<01:21, 21.76it/s]

Epoch 8:  12%|█▏        | 231/2000 [00:10<01:21, 21.75it/s]

Epoch 8:  12%|█▏        | 234/2000 [00:10<01:21, 21.75it/s]

Epoch 8:  12%|█▏        | 237/2000 [00:10<01:21, 21.75it/s]

Epoch 8:  12%|█▏        | 240/2000 [00:11<01:20, 21.75it/s]

Epoch 8:  12%|█▏        | 243/2000 [00:11<01:20, 21.75it/s]

Epoch 8:  12%|█▏        | 246/2000 [00:11<01:20, 21.75it/s]

Epoch 8:  12%|█▏        | 249/2000 [00:11<01:20, 21.75it/s]

Epoch 8:  13%|█▎        | 252/2000 [00:11<01:20, 21.74it/s]

Epoch 8:  13%|█▎        | 255/2000 [00:11<01:20, 21.76it/s]

Epoch 8:  13%|█▎        | 258/2000 [00:11<01:20, 21.76it/s]

Epoch 8:  13%|█▎        | 261/2000 [00:12<01:19, 21.76it/s]

Epoch 8:  13%|█▎        | 264/2000 [00:12<01:19, 21.76it/s]

Epoch 8:  13%|█▎        | 267/2000 [00:12<01:19, 21.76it/s]

Epoch 8:  14%|█▎        | 270/2000 [00:12<01:19, 21.77it/s]

Epoch 8:  14%|█▎        | 273/2000 [00:12<01:19, 21.77it/s]

Epoch 8:  14%|█▍        | 276/2000 [00:12<01:19, 21.77it/s]

Epoch 8:  14%|█▍        | 279/2000 [00:12<01:19, 21.76it/s]

Epoch 8:  14%|█▍        | 282/2000 [00:12<01:18, 21.77it/s]

Epoch 8:  14%|█▍        | 285/2000 [00:13<01:18, 21.77it/s]

Epoch 8:  14%|█▍        | 288/2000 [00:13<01:18, 21.76it/s]

Epoch 8:  15%|█▍        | 291/2000 [00:13<01:18, 21.76it/s]

Epoch 8:  15%|█▍        | 294/2000 [00:13<01:18, 21.76it/s]

Epoch 8:  15%|█▍        | 297/2000 [00:13<01:18, 21.75it/s]

Epoch 8:  15%|█▌        | 300/2000 [00:13<01:18, 21.76it/s]

Epoch 8:  15%|█▌        | 303/2000 [00:13<01:18, 21.74it/s]

Epoch 8:  15%|█▌        | 306/2000 [00:14<01:17, 21.74it/s]

Epoch 8:  15%|█▌        | 309/2000 [00:14<01:17, 21.73it/s]

Epoch 8:  16%|█▌        | 312/2000 [00:14<01:17, 21.75it/s]

Epoch 8:  16%|█▌        | 315/2000 [00:14<01:17, 21.75it/s]

Epoch 8:  16%|█▌        | 318/2000 [00:14<01:17, 21.76it/s]

Epoch 8:  16%|█▌        | 321/2000 [00:14<01:17, 21.75it/s]

Epoch 8:  16%|█▌        | 324/2000 [00:14<01:16, 21.77it/s]

Epoch 8:  16%|█▋        | 327/2000 [00:15<01:16, 21.77it/s]

Epoch 8:  16%|█▋        | 330/2000 [00:15<01:16, 21.78it/s]

Epoch 8:  17%|█▋        | 333/2000 [00:15<01:16, 21.77it/s]

Epoch 8:  17%|█▋        | 336/2000 [00:15<01:16, 21.76it/s]

Epoch 8:  17%|█▋        | 339/2000 [00:15<01:16, 21.77it/s]

Epoch 8:  17%|█▋        | 342/2000 [00:15<01:16, 21.76it/s]

Epoch 8:  17%|█▋        | 345/2000 [00:15<01:16, 21.77it/s]

Epoch 8:  17%|█▋        | 348/2000 [00:15<01:15, 21.77it/s]

Epoch 8:  18%|█▊        | 351/2000 [00:16<01:15, 21.78it/s]

Epoch 8:  18%|█▊        | 354/2000 [00:16<01:15, 21.75it/s]

Epoch 8:  18%|█▊        | 357/2000 [00:16<01:15, 21.77it/s]

Epoch 8:  18%|█▊        | 360/2000 [00:16<01:15, 21.76it/s]

Epoch 8:  18%|█▊        | 363/2000 [00:16<01:15, 21.75it/s]

Epoch 8:  18%|█▊        | 366/2000 [00:16<01:15, 21.77it/s]

Epoch 8:  18%|█▊        | 369/2000 [00:16<01:14, 21.75it/s]

Epoch 8:  19%|█▊        | 372/2000 [00:17<01:14, 21.76it/s]

Epoch 8:  19%|█▉        | 375/2000 [00:17<01:14, 21.74it/s]

Epoch 8:  19%|█▉        | 378/2000 [00:17<01:14, 21.75it/s]

Epoch 8:  19%|█▉        | 381/2000 [00:17<01:14, 21.75it/s]

Epoch 8:  19%|█▉        | 384/2000 [00:17<01:14, 21.74it/s]

Epoch 8:  19%|█▉        | 387/2000 [00:17<01:14, 21.75it/s]

Epoch 8:  20%|█▉        | 390/2000 [00:17<01:13, 21.76it/s]

Epoch 8:  20%|█▉        | 393/2000 [00:18<01:13, 21.75it/s]

Epoch 8:  20%|█▉        | 396/2000 [00:18<01:13, 21.76it/s]

Epoch 8:  20%|█▉        | 399/2000 [00:18<01:13, 21.75it/s]

Epoch 8:  20%|██        | 402/2000 [00:18<01:13, 21.76it/s]

Epoch 8:  20%|██        | 405/2000 [00:18<01:13, 21.76it/s]

Epoch 8:  20%|██        | 408/2000 [00:18<01:13, 21.76it/s]

Epoch 8:  21%|██        | 411/2000 [00:18<01:13, 21.76it/s]

Epoch 8:  21%|██        | 414/2000 [00:19<01:12, 21.76it/s]

Epoch 8:  21%|██        | 417/2000 [00:19<01:12, 21.75it/s]

Epoch 8:  21%|██        | 420/2000 [00:19<01:12, 21.76it/s]

Epoch 8:  21%|██        | 423/2000 [00:19<01:12, 21.75it/s]

Epoch 8:  21%|██▏       | 426/2000 [00:19<01:12, 21.77it/s]

Epoch 8:  21%|██▏       | 429/2000 [00:19<01:12, 21.76it/s]

Epoch 8:  22%|██▏       | 432/2000 [00:19<01:12, 21.75it/s]

Epoch 8:  22%|██▏       | 435/2000 [00:19<01:11, 21.75it/s]

Epoch 8:  22%|██▏       | 438/2000 [00:20<01:11, 21.75it/s]

Epoch 8:  22%|██▏       | 441/2000 [00:20<01:11, 21.75it/s]

Epoch 8:  22%|██▏       | 444/2000 [00:20<01:11, 21.76it/s]

Epoch 8:  22%|██▏       | 447/2000 [00:20<01:11, 21.77it/s]

Epoch 8:  22%|██▎       | 450/2000 [00:20<01:11, 21.77it/s]

Epoch 8:  23%|██▎       | 453/2000 [00:20<01:11, 21.76it/s]

Epoch 8:  23%|██▎       | 456/2000 [00:20<01:10, 21.75it/s]

Epoch 8:  23%|██▎       | 459/2000 [00:21<01:10, 21.77it/s]

Epoch 8:  23%|██▎       | 462/2000 [00:21<01:10, 21.77it/s]

Epoch 8:  23%|██▎       | 465/2000 [00:21<01:10, 21.78it/s]

Epoch 8:  23%|██▎       | 468/2000 [00:21<01:10, 21.79it/s]

Epoch 8:  24%|██▎       | 471/2000 [00:21<01:10, 21.78it/s]

Epoch 8:  24%|██▎       | 474/2000 [00:21<01:10, 21.77it/s]

Epoch 8:  24%|██▍       | 477/2000 [00:21<01:09, 21.76it/s]

Epoch 8:  24%|██▍       | 480/2000 [00:22<01:09, 21.76it/s]

Epoch 8:  24%|██▍       | 483/2000 [00:22<01:09, 21.76it/s]

Epoch 8:  24%|██▍       | 486/2000 [00:22<01:09, 21.77it/s]

Epoch 8:  24%|██▍       | 489/2000 [00:22<01:09, 21.77it/s]

Epoch 8:  25%|██▍       | 492/2000 [00:22<01:09, 21.77it/s]

Epoch 8:  25%|██▍       | 495/2000 [00:22<01:09, 21.75it/s]

Epoch 8:  25%|██▍       | 498/2000 [00:22<01:09, 21.74it/s]

Epoch 8:  25%|██▌       | 501/2000 [00:23<01:08, 21.76it/s]

Epoch 8:  25%|██▌       | 504/2000 [00:23<01:08, 21.76it/s]

Epoch 8:  25%|██▌       | 507/2000 [00:23<01:08, 21.77it/s]

Epoch 8:  26%|██▌       | 510/2000 [00:23<01:08, 21.77it/s]

Epoch 8:  26%|██▌       | 513/2000 [00:23<01:08, 21.76it/s]

Epoch 8:  26%|██▌       | 516/2000 [00:23<01:08, 21.55it/s]

Epoch 8:  26%|██▌       | 519/2000 [00:23<01:10, 20.96it/s]

Epoch 8:  26%|██▌       | 522/2000 [00:24<01:10, 21.01it/s]

Epoch 8:  26%|██▋       | 525/2000 [00:24<01:09, 21.18it/s]

Epoch 8:  26%|██▋       | 528/2000 [00:24<01:09, 21.31it/s]

Epoch 8:  27%|██▋       | 531/2000 [00:24<01:08, 21.45it/s]

Epoch 8:  27%|██▋       | 534/2000 [00:24<01:08, 21.53it/s]

Epoch 8:  27%|██▋       | 537/2000 [00:24<01:07, 21.61it/s]

Epoch 8:  27%|██▋       | 540/2000 [00:24<01:07, 21.66it/s]

Epoch 8:  27%|██▋       | 543/2000 [00:24<01:07, 21.71it/s]

Epoch 8:  27%|██▋       | 546/2000 [00:25<01:06, 21.71it/s]

Epoch 8:  27%|██▋       | 549/2000 [00:25<01:06, 21.75it/s]

Epoch 8:  28%|██▊       | 552/2000 [00:25<01:06, 21.76it/s]

Epoch 8:  28%|██▊       | 555/2000 [00:25<01:06, 21.75it/s]

Epoch 8:  28%|██▊       | 558/2000 [00:25<01:06, 21.76it/s]

Epoch 8:  28%|██▊       | 561/2000 [00:25<01:06, 21.75it/s]

Epoch 8:  28%|██▊       | 564/2000 [00:25<01:06, 21.75it/s]

Epoch 8:  28%|██▊       | 567/2000 [00:26<01:05, 21.73it/s]

Epoch 8:  28%|██▊       | 570/2000 [00:26<01:05, 21.74it/s]

Epoch 8:  29%|██▊       | 573/2000 [00:26<01:05, 21.73it/s]

Epoch 8:  29%|██▉       | 576/2000 [00:26<01:05, 21.74it/s]

Epoch 8:  29%|██▉       | 579/2000 [00:26<01:05, 21.74it/s]

Epoch 8:  29%|██▉       | 582/2000 [00:26<01:05, 21.74it/s]

Epoch 8:  29%|██▉       | 585/2000 [00:26<01:05, 21.74it/s]

Epoch 8:  29%|██▉       | 588/2000 [00:27<01:04, 21.74it/s]

Epoch 8:  30%|██▉       | 591/2000 [00:27<01:04, 21.74it/s]

Epoch 8:  30%|██▉       | 594/2000 [00:27<01:04, 21.74it/s]

Epoch 8:  30%|██▉       | 597/2000 [00:27<01:05, 21.55it/s]

Epoch 8:  30%|███       | 600/2000 [00:27<01:04, 21.58it/s]

Epoch 8:  30%|███       | 603/2000 [00:27<01:04, 21.64it/s]

Epoch 8:  30%|███       | 606/2000 [00:27<01:04, 21.64it/s]

Epoch 8:  30%|███       | 609/2000 [00:28<01:04, 21.66it/s]

Epoch 8:  31%|███       | 612/2000 [00:28<01:04, 21.68it/s]

Epoch 8:  31%|███       | 615/2000 [00:28<01:03, 21.69it/s]

Epoch 8:  31%|███       | 618/2000 [00:28<01:03, 21.70it/s]

Epoch 8:  31%|███       | 621/2000 [00:28<01:03, 21.70it/s]

Epoch 8:  31%|███       | 624/2000 [00:28<01:03, 21.71it/s]

Epoch 8:  31%|███▏      | 627/2000 [00:28<01:03, 21.71it/s]

Epoch 8:  32%|███▏      | 630/2000 [00:28<01:03, 21.70it/s]

Epoch 8:  32%|███▏      | 633/2000 [00:29<01:02, 21.71it/s]

Epoch 8:  32%|███▏      | 636/2000 [00:29<01:02, 21.72it/s]

Epoch 8:  32%|███▏      | 639/2000 [00:29<01:02, 21.71it/s]

Epoch 8:  32%|███▏      | 642/2000 [00:29<01:02, 21.71it/s]

Epoch 8:  32%|███▏      | 645/2000 [00:29<01:02, 21.70it/s]

Epoch 8:  32%|███▏      | 648/2000 [00:29<01:02, 21.69it/s]

Epoch 8:  33%|███▎      | 651/2000 [00:29<01:02, 21.69it/s]

Epoch 8:  33%|███▎      | 654/2000 [00:30<01:02, 21.68it/s]

Epoch 8:  33%|███▎      | 657/2000 [00:30<01:01, 21.68it/s]

Epoch 8:  33%|███▎      | 660/2000 [00:30<01:01, 21.69it/s]

Epoch 8:  33%|███▎      | 663/2000 [00:30<01:01, 21.70it/s]

Epoch 8:  33%|███▎      | 666/2000 [00:30<01:01, 21.71it/s]

Epoch 8:  33%|███▎      | 669/2000 [00:30<01:01, 21.70it/s]

Epoch 8:  34%|███▎      | 672/2000 [00:30<01:01, 21.72it/s]

Epoch 8:  34%|███▍      | 675/2000 [00:31<01:01, 21.71it/s]

Epoch 8:  34%|███▍      | 678/2000 [00:31<01:00, 21.71it/s]

Epoch 8:  34%|███▍      | 681/2000 [00:31<01:00, 21.71it/s]

Epoch 8:  34%|███▍      | 684/2000 [00:31<01:00, 21.71it/s]

Epoch 8:  34%|███▍      | 687/2000 [00:31<01:00, 21.73it/s]

Epoch 8:  34%|███▍      | 690/2000 [00:31<01:00, 21.73it/s]

Epoch 8:  35%|███▍      | 693/2000 [00:31<01:00, 21.74it/s]

Epoch 8:  35%|███▍      | 696/2000 [00:32<00:59, 21.74it/s]

Epoch 8:  35%|███▍      | 699/2000 [00:32<00:59, 21.74it/s]

Epoch 8:  35%|███▌      | 702/2000 [00:32<00:59, 21.74it/s]

Epoch 8:  35%|███▌      | 705/2000 [00:32<00:59, 21.73it/s]

Epoch 8:  35%|███▌      | 708/2000 [00:32<00:59, 21.74it/s]

Epoch 8:  36%|███▌      | 711/2000 [00:32<00:59, 21.74it/s]

Epoch 8:  36%|███▌      | 714/2000 [00:32<00:59, 21.74it/s]

Epoch 8:  36%|███▌      | 717/2000 [00:32<00:59, 21.72it/s]

Epoch 8:  36%|███▌      | 720/2000 [00:33<00:58, 21.70it/s]

Epoch 8:  36%|███▌      | 723/2000 [00:33<00:58, 21.71it/s]

Epoch 8:  36%|███▋      | 726/2000 [00:33<00:58, 21.72it/s]

Epoch 8:  36%|███▋      | 729/2000 [00:33<00:58, 21.73it/s]

Epoch 8:  37%|███▋      | 732/2000 [00:33<00:58, 21.72it/s]

Epoch 8:  37%|███▋      | 735/2000 [00:33<00:58, 21.71it/s]

Epoch 8:  37%|███▋      | 738/2000 [00:33<00:58, 21.70it/s]

Epoch 8:  37%|███▋      | 741/2000 [00:34<00:57, 21.71it/s]

Epoch 8:  37%|███▋      | 744/2000 [00:34<00:57, 21.71it/s]

Epoch 8:  37%|███▋      | 747/2000 [00:34<00:57, 21.72it/s]

Epoch 8:  38%|███▊      | 750/2000 [00:34<00:57, 21.72it/s]

Epoch 8:  38%|███▊      | 753/2000 [00:34<00:57, 21.72it/s]

Epoch 8:  38%|███▊      | 756/2000 [00:34<00:57, 21.72it/s]

Epoch 8:  38%|███▊      | 759/2000 [00:34<00:57, 21.72it/s]

Epoch 8:  38%|███▊      | 762/2000 [00:35<00:56, 21.72it/s]

Epoch 8:  38%|███▊      | 765/2000 [00:35<00:56, 21.73it/s]

Epoch 8:  38%|███▊      | 768/2000 [00:35<00:56, 21.72it/s]

Epoch 8:  39%|███▊      | 771/2000 [00:35<00:56, 21.70it/s]

Epoch 8:  39%|███▊      | 774/2000 [00:35<00:56, 21.68it/s]

Epoch 8:  39%|███▉      | 777/2000 [00:35<00:56, 21.67it/s]

Epoch 8:  39%|███▉      | 780/2000 [00:35<00:56, 21.67it/s]

Epoch 8:  39%|███▉      | 783/2000 [00:36<00:56, 21.64it/s]

Epoch 8:  39%|███▉      | 786/2000 [00:36<00:56, 21.62it/s]

Epoch 8:  39%|███▉      | 789/2000 [00:36<00:55, 21.63it/s]

Epoch 8:  40%|███▉      | 792/2000 [00:36<00:55, 21.64it/s]

Epoch 8:  40%|███▉      | 795/2000 [00:36<00:55, 21.66it/s]

Epoch 8:  40%|███▉      | 798/2000 [00:36<00:55, 21.67it/s]

Epoch 8:  40%|████      | 801/2000 [00:36<00:55, 21.68it/s]

Epoch 8:  40%|████      | 804/2000 [00:37<00:55, 21.70it/s]

Epoch 8:  40%|████      | 807/2000 [00:37<00:54, 21.70it/s]

Epoch 8:  40%|████      | 810/2000 [00:37<00:54, 21.71it/s]

Epoch 8:  41%|████      | 813/2000 [00:37<00:54, 21.70it/s]

Epoch 8:  41%|████      | 816/2000 [00:37<00:54, 21.71it/s]

Epoch 8:  41%|████      | 819/2000 [00:37<00:54, 21.70it/s]

Epoch 8:  41%|████      | 822/2000 [00:37<00:54, 21.69it/s]

Epoch 8:  41%|████▏     | 825/2000 [00:37<00:54, 21.69it/s]

Epoch 8:  41%|████▏     | 828/2000 [00:38<00:54, 21.69it/s]

Epoch 8:  42%|████▏     | 831/2000 [00:38<00:53, 21.69it/s]

Epoch 8:  42%|████▏     | 834/2000 [00:38<00:53, 21.69it/s]

Epoch 8:  42%|████▏     | 837/2000 [00:38<00:53, 21.68it/s]

Epoch 8:  42%|████▏     | 840/2000 [00:38<00:53, 21.70it/s]

Epoch 8:  42%|████▏     | 843/2000 [00:38<00:53, 21.69it/s]

Epoch 8:  42%|████▏     | 846/2000 [00:38<00:53, 21.70it/s]

Epoch 8:  42%|████▏     | 849/2000 [00:39<00:53, 21.70it/s]

Epoch 8:  43%|████▎     | 852/2000 [00:39<00:52, 21.69it/s]

Epoch 8:  43%|████▎     | 855/2000 [00:39<00:52, 21.69it/s]

Epoch 8:  43%|████▎     | 858/2000 [00:39<00:52, 21.69it/s]

Epoch 8:  43%|████▎     | 861/2000 [00:39<00:52, 21.70it/s]

Epoch 8:  43%|████▎     | 864/2000 [00:39<00:52, 21.69it/s]

Epoch 8:  43%|████▎     | 867/2000 [00:39<00:52, 21.69it/s]

Epoch 8:  44%|████▎     | 870/2000 [00:40<00:52, 21.68it/s]

Epoch 8:  44%|████▎     | 873/2000 [00:40<00:51, 21.69it/s]

Epoch 8:  44%|████▍     | 876/2000 [00:40<00:51, 21.70it/s]

Epoch 8:  44%|████▍     | 879/2000 [00:40<00:51, 21.71it/s]

Epoch 8:  44%|████▍     | 882/2000 [00:40<00:51, 21.71it/s]

Epoch 8:  44%|████▍     | 885/2000 [00:40<00:51, 21.72it/s]

Epoch 8:  44%|████▍     | 888/2000 [00:40<00:51, 21.71it/s]

Epoch 8:  45%|████▍     | 891/2000 [00:41<00:51, 21.71it/s]

Epoch 8:  45%|████▍     | 894/2000 [00:41<00:50, 21.71it/s]

Epoch 8:  45%|████▍     | 897/2000 [00:41<00:50, 21.71it/s]

Epoch 8:  45%|████▌     | 900/2000 [00:41<00:50, 21.72it/s]

Epoch 8:  45%|████▌     | 903/2000 [00:41<00:50, 21.71it/s]

Epoch 8:  45%|████▌     | 906/2000 [00:41<00:50, 21.72it/s]

Epoch 8:  45%|████▌     | 909/2000 [00:41<00:50, 21.72it/s]

Epoch 8:  46%|████▌     | 912/2000 [00:41<00:50, 21.72it/s]

Epoch 8:  46%|████▌     | 915/2000 [00:42<00:49, 21.72it/s]

Epoch 8:  46%|████▌     | 918/2000 [00:42<00:49, 21.74it/s]

Epoch 8:  46%|████▌     | 921/2000 [00:42<00:49, 21.74it/s]

Epoch 8:  46%|████▌     | 924/2000 [00:42<00:49, 21.73it/s]

Epoch 8:  46%|████▋     | 927/2000 [00:42<00:49, 21.73it/s]

Epoch 8:  46%|████▋     | 930/2000 [00:42<00:49, 21.73it/s]

Epoch 8:  47%|████▋     | 933/2000 [00:42<00:49, 21.73it/s]

Epoch 8:  47%|████▋     | 936/2000 [00:43<00:48, 21.73it/s]

Epoch 8:  47%|████▋     | 939/2000 [00:43<00:48, 21.73it/s]

Epoch 8:  47%|████▋     | 942/2000 [00:43<00:48, 21.73it/s]

Epoch 8:  47%|████▋     | 945/2000 [00:43<00:48, 21.73it/s]

Epoch 8:  47%|████▋     | 948/2000 [00:43<00:48, 21.74it/s]

Epoch 8:  48%|████▊     | 951/2000 [00:43<00:48, 21.74it/s]

Epoch 8:  48%|████▊     | 954/2000 [00:43<00:48, 21.75it/s]

Epoch 8:  48%|████▊     | 957/2000 [00:44<00:47, 21.74it/s]

Epoch 8:  48%|████▊     | 960/2000 [00:44<00:47, 21.73it/s]

Epoch 8:  48%|████▊     | 963/2000 [00:44<00:47, 21.73it/s]

Epoch 8:  48%|████▊     | 966/2000 [00:44<00:47, 21.73it/s]

Epoch 8:  48%|████▊     | 969/2000 [00:44<00:47, 21.73it/s]

Epoch 8:  49%|████▊     | 972/2000 [00:44<00:47, 21.72it/s]

Epoch 8:  49%|████▉     | 975/2000 [00:44<00:47, 21.73it/s]

Epoch 8:  49%|████▉     | 978/2000 [00:45<00:47, 21.73it/s]

Epoch 8:  49%|████▉     | 981/2000 [00:45<00:46, 21.73it/s]

Epoch 8:  49%|████▉     | 984/2000 [00:45<00:46, 21.73it/s]

Epoch 8:  49%|████▉     | 987/2000 [00:45<00:46, 21.73it/s]

Epoch 8:  50%|████▉     | 990/2000 [00:45<00:46, 21.73it/s]

Epoch 8:  50%|████▉     | 993/2000 [00:45<00:46, 21.74it/s]

Epoch 8:  50%|████▉     | 996/2000 [00:45<00:46, 21.73it/s]

Epoch 8:  50%|████▉     | 999/2000 [00:45<00:46, 21.71it/s]

Epoch 8:  50%|█████     | 1002/2000 [00:46<00:45, 21.72it/s]

Epoch 8:  50%|█████     | 1005/2000 [00:46<00:45, 21.72it/s]

Epoch 8:  50%|█████     | 1008/2000 [00:46<00:45, 21.73it/s]

Epoch 8:  51%|█████     | 1011/2000 [00:46<00:45, 21.73it/s]

Epoch 8:  51%|█████     | 1014/2000 [00:46<00:45, 21.73it/s]

Epoch 8:  51%|█████     | 1017/2000 [00:46<00:45, 21.75it/s]

Epoch 8:  51%|█████     | 1020/2000 [00:46<00:45, 21.75it/s]

Epoch 8:  51%|█████     | 1023/2000 [00:47<00:44, 21.75it/s]

Epoch 8:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.75it/s]

Epoch 8:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.75it/s]

Epoch 8:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.72it/s]

Epoch 8:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.74it/s]

Epoch 8:  52%|█████▏    | 1038/2000 [00:47<00:44, 21.72it/s]

Epoch 8:  52%|█████▏    | 1041/2000 [00:47<00:44, 21.73it/s]

Epoch 8:  52%|█████▏    | 1044/2000 [00:48<00:44, 21.72it/s]

Epoch 8:  52%|█████▏    | 1047/2000 [00:48<00:43, 21.73it/s]

Epoch 8:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.72it/s]

Epoch 8:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.71it/s]

Epoch 8:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.73it/s]

Epoch 8:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.72it/s]

Epoch 8:  53%|█████▎    | 1062/2000 [00:48<00:43, 21.72it/s]

Epoch 8:  53%|█████▎    | 1065/2000 [00:49<00:43, 21.72it/s]

Epoch 8:  53%|█████▎    | 1068/2000 [00:49<00:42, 21.72it/s]

Epoch 8:  54%|█████▎    | 1071/2000 [00:49<00:42, 21.72it/s]

Epoch 8:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.73it/s]

Epoch 8:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.73it/s]

Epoch 8:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.74it/s]

Epoch 8:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.70it/s]

Epoch 8:  54%|█████▍    | 1086/2000 [00:49<00:42, 21.70it/s]

Epoch 8:  54%|█████▍    | 1089/2000 [00:50<00:41, 21.70it/s]

Epoch 8:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.71it/s]

Epoch 8:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.73it/s]

Epoch 8:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.72it/s]

Epoch 8:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.73it/s]

Epoch 8:  55%|█████▌    | 1104/2000 [00:50<00:41, 21.73it/s]

Epoch 8:  55%|█████▌    | 1107/2000 [00:50<00:41, 21.73it/s]

Epoch 8:  56%|█████▌    | 1110/2000 [00:51<00:40, 21.74it/s]

Epoch 8:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.74it/s]

Epoch 8:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.73it/s]

Epoch 8:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.72it/s]

Epoch 8:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.72it/s]

Epoch 8:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.71it/s]

Epoch 8:  56%|█████▋    | 1128/2000 [00:51<00:40, 21.71it/s]

Epoch 8:  57%|█████▋    | 1131/2000 [00:52<00:40, 21.72it/s]

Epoch 8:  57%|█████▋    | 1134/2000 [00:52<00:39, 21.71it/s]

Epoch 8:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.70it/s]

Epoch 8:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.69it/s]

Epoch 8:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.71it/s]

Epoch 8:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.72it/s]

Epoch 8:  57%|█████▋    | 1149/2000 [00:52<00:39, 21.72it/s]

Epoch 8:  58%|█████▊    | 1152/2000 [00:53<00:39, 21.71it/s]

Epoch 8:  58%|█████▊    | 1155/2000 [00:53<00:38, 21.72it/s]

Epoch 8:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.72it/s]

Epoch 8:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.71it/s]

Epoch 8:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.70it/s]

Epoch 8:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.69it/s]

Epoch 8:  58%|█████▊    | 1170/2000 [00:53<00:38, 21.70it/s]

Epoch 8:  59%|█████▊    | 1173/2000 [00:53<00:38, 21.70it/s]

Epoch 8:  59%|█████▉    | 1176/2000 [00:54<00:37, 21.72it/s]

Epoch 8:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.70it/s]

Epoch 8:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.71it/s]

Epoch 8:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.72it/s]

Epoch 8:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.69it/s]

Epoch 8:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.71it/s]

Epoch 8:  60%|█████▉    | 1194/2000 [00:54<00:37, 21.71it/s]

Epoch 8:  60%|█████▉    | 1197/2000 [00:55<00:36, 21.72it/s]

Epoch 8:  60%|██████    | 1200/2000 [00:55<00:36, 21.71it/s]

Epoch 8:  60%|██████    | 1203/2000 [00:55<00:36, 21.73it/s]

Epoch 8:  60%|██████    | 1206/2000 [00:55<00:36, 21.72it/s]

Epoch 8:  60%|██████    | 1209/2000 [00:55<00:36, 21.71it/s]

Epoch 8:  61%|██████    | 1212/2000 [00:55<00:36, 21.72it/s]

Epoch 8:  61%|██████    | 1215/2000 [00:55<00:36, 21.73it/s]

Epoch 8:  61%|██████    | 1218/2000 [00:56<00:35, 21.73it/s]

Epoch 8:  61%|██████    | 1221/2000 [00:56<00:35, 21.72it/s]

Epoch 8:  61%|██████    | 1224/2000 [00:56<00:35, 21.70it/s]

Epoch 8:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.49it/s]

Epoch 8:  62%|██████▏   | 1230/2000 [00:56<00:36, 20.91it/s]

Epoch 8:  62%|██████▏   | 1233/2000 [00:56<00:36, 20.96it/s]

Epoch 8:  62%|██████▏   | 1236/2000 [00:56<00:36, 21.12it/s]

Epoch 8:  62%|██████▏   | 1239/2000 [00:57<00:35, 21.24it/s]

Epoch 8:  62%|██████▏   | 1242/2000 [00:57<00:35, 21.37it/s]

Epoch 8:  62%|██████▏   | 1245/2000 [00:57<00:35, 21.46it/s]

Epoch 8:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.53it/s]

Epoch 8:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.59it/s]

Epoch 8:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.64it/s]

Epoch 8:  63%|██████▎   | 1257/2000 [00:57<00:34, 21.66it/s]

Epoch 8:  63%|██████▎   | 1260/2000 [00:58<00:34, 21.69it/s]

Epoch 8:  63%|██████▎   | 1263/2000 [00:58<00:33, 21.70it/s]

Epoch 8:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.72it/s]

Epoch 8:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.72it/s]

Epoch 8:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.75it/s]

Epoch 8:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.75it/s]

Epoch 8:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.74it/s]

Epoch 8:  64%|██████▍   | 1281/2000 [00:58<00:33, 21.74it/s]

Epoch 8:  64%|██████▍   | 1284/2000 [00:59<00:32, 21.74it/s]

Epoch 8:  64%|██████▍   | 1287/2000 [00:59<00:32, 21.73it/s]

Epoch 8:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.74it/s]

Epoch 8:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.74it/s]

Epoch 8:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.74it/s]

Epoch 8:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.74it/s]

Epoch 8:  65%|██████▌   | 1302/2000 [00:59<00:32, 21.73it/s]

Epoch 8:  65%|██████▌   | 1305/2000 [01:00<00:31, 21.74it/s]

Epoch 8:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.75it/s]

Epoch 8:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.75it/s]

Epoch 8:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.75it/s]

Epoch 8:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.75it/s]

Epoch 8:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.74it/s]

Epoch 8:  66%|██████▌   | 1323/2000 [01:00<00:31, 21.74it/s]

Epoch 8:  66%|██████▋   | 1326/2000 [01:01<00:30, 21.74it/s]

Epoch 8:  66%|██████▋   | 1329/2000 [01:01<00:30, 21.74it/s]

Epoch 8:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.75it/s]

Epoch 8:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.76it/s]

Epoch 8:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.75it/s]

Epoch 8:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.73it/s]

Epoch 8:  67%|██████▋   | 1344/2000 [01:01<00:30, 21.74it/s]

Epoch 8:  67%|██████▋   | 1347/2000 [01:02<00:30, 21.74it/s]

Epoch 8:  68%|██████▊   | 1350/2000 [01:02<00:29, 21.76it/s]

Epoch 8:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.76it/s]

Epoch 8:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.75it/s]

Epoch 8:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.75it/s]

Epoch 8:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.76it/s]

Epoch 8:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.76it/s]

Epoch 8:  68%|██████▊   | 1368/2000 [01:02<00:29, 21.77it/s]

Epoch 8:  69%|██████▊   | 1371/2000 [01:03<00:28, 21.75it/s]

Epoch 8:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.77it/s]

Epoch 8:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.76it/s]

Epoch 8:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.74it/s]

Epoch 8:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.74it/s]

Epoch 8:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.74it/s]

Epoch 8:  69%|██████▉   | 1389/2000 [01:03<00:28, 21.76it/s]

Epoch 8:  70%|██████▉   | 1392/2000 [01:04<00:27, 21.77it/s]

Epoch 8:  70%|██████▉   | 1395/2000 [01:04<00:27, 21.78it/s]

Epoch 8:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.77it/s]

Epoch 8:  70%|███████   | 1401/2000 [01:04<00:27, 21.76it/s]

Epoch 8:  70%|███████   | 1404/2000 [01:04<00:27, 21.77it/s]

Epoch 8:  70%|███████   | 1407/2000 [01:04<00:27, 21.76it/s]

Epoch 8:  70%|███████   | 1410/2000 [01:04<00:27, 21.77it/s]

Epoch 8:  71%|███████   | 1413/2000 [01:05<00:26, 21.77it/s]

Epoch 8:  71%|███████   | 1416/2000 [01:05<00:26, 21.76it/s]

Epoch 8:  71%|███████   | 1419/2000 [01:05<00:26, 21.78it/s]

Epoch 8:  71%|███████   | 1422/2000 [01:05<00:26, 21.78it/s]

Epoch 8:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.78it/s]

Epoch 8:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.77it/s]

Epoch 8:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.76it/s]

Epoch 8:  72%|███████▏  | 1434/2000 [01:06<00:26, 21.77it/s]

Epoch 8:  72%|███████▏  | 1437/2000 [01:06<00:25, 21.78it/s]

Epoch 8:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.76it/s]

Epoch 8:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.77it/s]

Epoch 8:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.77it/s]

Epoch 8:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.75it/s]

Epoch 8:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.77it/s]

Epoch 8:  73%|███████▎  | 1455/2000 [01:06<00:25, 21.76it/s]

Epoch 8:  73%|███████▎  | 1458/2000 [01:07<00:24, 21.76it/s]

Epoch 8:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.76it/s]

Epoch 8:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.76it/s]

Epoch 8:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.74it/s]

Epoch 8:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.75it/s]

Epoch 8:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.74it/s]

Epoch 8:  74%|███████▍  | 1476/2000 [01:07<00:24, 21.75it/s]

Epoch 8:  74%|███████▍  | 1479/2000 [01:08<00:23, 21.74it/s]

Epoch 8:  74%|███████▍  | 1482/2000 [01:08<00:23, 21.76it/s]

Epoch 8:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.76it/s]

Epoch 8:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.76it/s]

Epoch 8:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.75it/s]

Epoch 8:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.75it/s]

Epoch 8:  75%|███████▍  | 1497/2000 [01:08<00:23, 21.75it/s]

Epoch 8:  75%|███████▌  | 1500/2000 [01:09<00:22, 21.76it/s]

Epoch 8:  75%|███████▌  | 1503/2000 [01:09<00:22, 21.76it/s]

Epoch 8:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.77it/s]

Epoch 8:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.77it/s]

Epoch 8:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.77it/s]

Epoch 8:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.76it/s]

Epoch 8:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.76it/s]

Epoch 8:  76%|███████▌  | 1521/2000 [01:10<00:21, 21.77it/s]

Epoch 8:  76%|███████▌  | 1524/2000 [01:10<00:21, 21.78it/s]

Epoch 8:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.77it/s]

Epoch 8:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.77it/s]

Epoch 8:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.76it/s]

Epoch 8:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.75it/s]

Epoch 8:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.75it/s]

Epoch 8:  77%|███████▋  | 1542/2000 [01:10<00:21, 21.75it/s]

Epoch 8:  77%|███████▋  | 1545/2000 [01:11<00:20, 21.67it/s]

Epoch 8:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.67it/s]

Epoch 8:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.68it/s]

Epoch 8:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.69it/s]

Epoch 8:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.70it/s]

Epoch 8:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.69it/s]

Epoch 8:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.70it/s]

Epoch 8:  78%|███████▊  | 1566/2000 [01:12<00:19, 21.71it/s]

Epoch 8:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.71it/s]

Epoch 8:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.71it/s]

Epoch 8:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.71it/s]

Epoch 8:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.72it/s]

Epoch 8:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.73it/s]

Epoch 8:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.73it/s]

Epoch 8:  79%|███████▉  | 1587/2000 [01:13<00:19, 21.73it/s]

Epoch 8:  80%|███████▉  | 1590/2000 [01:13<00:18, 21.73it/s]

Epoch 8:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.74it/s]

Epoch 8:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.75it/s]

Epoch 8:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.75it/s]

Epoch 8:  80%|████████  | 1602/2000 [01:13<00:18, 21.74it/s]

Epoch 8:  80%|████████  | 1605/2000 [01:13<00:18, 21.73it/s]

Epoch 8:  80%|████████  | 1608/2000 [01:14<00:18, 21.73it/s]

Epoch 8:  81%|████████  | 1611/2000 [01:14<00:17, 21.74it/s]

Epoch 8:  81%|████████  | 1614/2000 [01:14<00:17, 21.74it/s]

Epoch 8:  81%|████████  | 1617/2000 [01:14<00:17, 21.73it/s]

Epoch 8:  81%|████████  | 1620/2000 [01:14<00:17, 21.74it/s]

Epoch 8:  81%|████████  | 1623/2000 [01:14<00:17, 21.72it/s]

Epoch 8:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.72it/s]

Epoch 8:  81%|████████▏ | 1629/2000 [01:14<00:17, 21.73it/s]

Epoch 8:  82%|████████▏ | 1632/2000 [01:15<00:16, 21.75it/s]

Epoch 8:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.75it/s]

Epoch 8:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.75it/s]

Epoch 8:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.74it/s]

Epoch 8:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.75it/s]

Epoch 8:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.73it/s]

Epoch 8:  82%|████████▎ | 1650/2000 [01:15<00:16, 21.74it/s]

Epoch 8:  83%|████████▎ | 1653/2000 [01:16<00:15, 21.75it/s]

Epoch 8:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.75it/s]

Epoch 8:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.75it/s]

Epoch 8:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.75it/s]

Epoch 8:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.75it/s]

Epoch 8:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.75it/s]

Epoch 8:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.72it/s]

Epoch 8:  84%|████████▎ | 1674/2000 [01:17<00:14, 21.74it/s]

Epoch 8:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.72it/s]

Epoch 8:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.72it/s]

Epoch 8:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.74it/s]

Epoch 8:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.74it/s]

Epoch 8:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.72it/s]

Epoch 8:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.72it/s]

Epoch 8:  85%|████████▍ | 1695/2000 [01:18<00:14, 21.72it/s]

Epoch 8:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.73it/s]

Epoch 8:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.74it/s]

Epoch 8:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.74it/s]

Epoch 8:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.74it/s]

Epoch 8:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.73it/s]

Epoch 8:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.74it/s]

Epoch 8:  86%|████████▌ | 1716/2000 [01:19<00:13, 21.75it/s]

Epoch 8:  86%|████████▌ | 1719/2000 [01:19<00:12, 21.74it/s]

Epoch 8:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.73it/s]

Epoch 8:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.71it/s]

Epoch 8:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.72it/s]

Epoch 8:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.71it/s]

Epoch 8:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.72it/s]

Epoch 8:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.71it/s]

Epoch 8:  87%|████████▋ | 1740/2000 [01:20<00:11, 21.72it/s]

Epoch 8:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.71it/s]

Epoch 8:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.73it/s]

Epoch 8:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.72it/s]

Epoch 8:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.73it/s]

Epoch 8:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.73it/s]

Epoch 8:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.74it/s]

Epoch 8:  88%|████████▊ | 1761/2000 [01:21<00:10, 21.75it/s]

Epoch 8:  88%|████████▊ | 1764/2000 [01:21<00:10, 21.75it/s]

Epoch 8:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.75it/s]

Epoch 8:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.75it/s]

Epoch 8:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.75it/s]

Epoch 8:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.73it/s]

Epoch 8:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.70it/s]

Epoch 8:  89%|████████▉ | 1782/2000 [01:22<00:10, 21.71it/s]

Epoch 8:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.72it/s]

Epoch 8:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.73it/s]

Epoch 8:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.74it/s]

Epoch 8:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.73it/s]

Epoch 8:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.67it/s]

Epoch 8:  90%|█████████ | 1800/2000 [01:22<00:09, 21.68it/s]

Epoch 8:  90%|█████████ | 1803/2000 [01:23<00:09, 21.70it/s]

Epoch 8:  90%|█████████ | 1806/2000 [01:23<00:08, 21.73it/s]

Epoch 8:  90%|█████████ | 1809/2000 [01:23<00:08, 21.74it/s]

Epoch 8:  91%|█████████ | 1812/2000 [01:23<00:08, 21.75it/s]

Epoch 8:  91%|█████████ | 1815/2000 [01:23<00:08, 21.70it/s]

Epoch 8:  91%|█████████ | 1818/2000 [01:23<00:08, 21.72it/s]

Epoch 8:  91%|█████████ | 1821/2000 [01:23<00:08, 21.73it/s]

Epoch 8:  91%|█████████ | 1824/2000 [01:23<00:08, 21.73it/s]

Epoch 8:  91%|█████████▏| 1827/2000 [01:24<00:07, 21.74it/s]

Epoch 8:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.75it/s]

Epoch 8:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.74it/s]

Epoch 8:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.75it/s]

Epoch 8:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.74it/s]

Epoch 8:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.75it/s]

Epoch 8:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.74it/s]

Epoch 8:  92%|█████████▏| 1848/2000 [01:25<00:06, 21.75it/s]

Epoch 8:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.75it/s]

Epoch 8:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.75it/s]

Epoch 8:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.75it/s]

Epoch 8:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.75it/s]

Epoch 8:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.74it/s]

Epoch 8:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.75it/s]

Epoch 8:  93%|█████████▎| 1869/2000 [01:26<00:06, 21.74it/s]

Epoch 8:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.74it/s]

Epoch 8:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.72it/s]

Epoch 8:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.74it/s]

Epoch 8:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.73it/s]

Epoch 8:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.76it/s]

Epoch 8:  94%|█████████▍| 1887/2000 [01:26<00:05, 21.75it/s]

Epoch 8:  94%|█████████▍| 1890/2000 [01:27<00:05, 21.75it/s]

Epoch 8:  95%|█████████▍| 1893/2000 [01:27<00:04, 21.76it/s]

Epoch 8:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.75it/s]

Epoch 8:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.77it/s]

Epoch 8:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.77it/s]

Epoch 8:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.78it/s]

Epoch 8:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.76it/s]

Epoch 8:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.78it/s]

Epoch 8:  96%|█████████▌| 1914/2000 [01:28<00:03, 21.76it/s]

Epoch 8:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.77it/s]

Epoch 8:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.78it/s]

Epoch 8:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.65it/s]

Epoch 8:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.67it/s]

Epoch 8:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.64it/s]

Epoch 8:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.67it/s]

Epoch 8:  97%|█████████▋| 1935/2000 [01:29<00:02, 21.71it/s]

Epoch 8:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.34it/s]

Epoch 8:  97%|█████████▋| 1941/2000 [01:29<00:02, 20.83it/s]

Epoch 8:  97%|█████████▋| 1944/2000 [01:29<00:02, 20.89it/s]

Epoch 8:  97%|█████████▋| 1947/2000 [01:29<00:02, 20.86it/s]

Epoch 8:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.03it/s]

Epoch 8:  98%|█████████▊| 1953/2000 [01:29<00:02, 21.23it/s]

Epoch 8:  98%|█████████▊| 1956/2000 [01:30<00:02, 21.37it/s]

Epoch 8:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.48it/s]

Epoch 8:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.57it/s]

Epoch 8:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.62it/s]

Epoch 8:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.66it/s]

Epoch 8:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.68it/s]

Epoch 8:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.68it/s]

Epoch 8:  99%|█████████▉| 1977/2000 [01:31<00:01, 21.67it/s]

Epoch 8:  99%|█████████▉| 1980/2000 [01:31<00:00, 21.67it/s]

Epoch 8:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.69it/s]

Epoch 8:  99%|█████████▉| 1986/2000 [01:31<00:00, 21.73it/s]

Epoch 8:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.73it/s]

Epoch 8: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.74it/s]

Epoch 8: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.73it/s]

Epoch 8: 100%|█████████▉| 1998/2000 [01:32<00:00, 21.73it/s]

Epoch 8: loss=0.3855, val_proxy=0.5125

Epoch 9:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 9:   0%|          | 3/2000 [00:00<01:32, 21.49it/s]

Epoch 9:   0%|          | 6/2000 [00:00<01:32, 21.65it/s]

Epoch 9:   0%|          | 9/2000 [00:00<01:31, 21.68it/s]

Epoch 9:   1%|          | 12/2000 [00:00<01:31, 21.71it/s]

Epoch 9:   1%|          | 15/2000 [00:00<01:31, 21.73it/s]

Epoch 9:   1%|          | 18/2000 [00:00<01:31, 21.75it/s]

Epoch 9:   1%|          | 21/2000 [00:00<01:30, 21.76it/s]

Epoch 9:   1%|          | 24/2000 [00:01<01:30, 21.76it/s]

Epoch 9:   1%|▏         | 27/2000 [00:01<01:30, 21.78it/s]

Epoch 9:   2%|▏         | 30/2000 [00:01<01:30, 21.80it/s]

Epoch 9:   2%|▏         | 33/2000 [00:01<01:30, 21.80it/s]

Epoch 9:   2%|▏         | 36/2000 [00:01<01:30, 21.79it/s]

Epoch 9:   2%|▏         | 39/2000 [00:01<01:30, 21.79it/s]

Epoch 9:   2%|▏         | 42/2000 [00:01<01:29, 21.78it/s]

Epoch 9:   2%|▏         | 45/2000 [00:02<01:29, 21.79it/s]

Epoch 9:   2%|▏         | 48/2000 [00:02<01:29, 21.79it/s]

Epoch 9:   3%|▎         | 51/2000 [00:02<01:29, 21.80it/s]

Epoch 9:   3%|▎         | 54/2000 [00:02<01:29, 21.80it/s]

Epoch 9:   3%|▎         | 57/2000 [00:02<01:29, 21.80it/s]

Epoch 9:   3%|▎         | 60/2000 [00:02<01:28, 21.82it/s]

Epoch 9:   3%|▎         | 63/2000 [00:02<01:28, 21.82it/s]

Epoch 9:   3%|▎         | 66/2000 [00:03<01:28, 21.82it/s]

Epoch 9:   3%|▎         | 69/2000 [00:03<01:28, 21.80it/s]

Epoch 9:   4%|▎         | 72/2000 [00:03<01:28, 21.81it/s]

Epoch 9:   4%|▍         | 75/2000 [00:03<01:28, 21.82it/s]

Epoch 9:   4%|▍         | 78/2000 [00:03<01:28, 21.82it/s]

Epoch 9:   4%|▍         | 81/2000 [00:03<01:27, 21.82it/s]

Epoch 9:   4%|▍         | 84/2000 [00:03<01:27, 21.83it/s]

Epoch 9:   4%|▍         | 87/2000 [00:03<01:27, 21.83it/s]

Epoch 9:   4%|▍         | 90/2000 [00:04<01:27, 21.83it/s]

Epoch 9:   5%|▍         | 93/2000 [00:04<01:27, 21.82it/s]

Epoch 9:   5%|▍         | 96/2000 [00:04<01:27, 21.82it/s]

Epoch 9:   5%|▍         | 99/2000 [00:04<01:27, 21.83it/s]

Epoch 9:   5%|▌         | 102/2000 [00:04<01:26, 21.83it/s]

Epoch 9:   5%|▌         | 105/2000 [00:04<01:26, 21.82it/s]

Epoch 9:   5%|▌         | 108/2000 [00:04<01:26, 21.83it/s]

Epoch 9:   6%|▌         | 111/2000 [00:05<01:26, 21.84it/s]

Epoch 9:   6%|▌         | 114/2000 [00:05<01:26, 21.83it/s]

Epoch 9:   6%|▌         | 117/2000 [00:05<01:26, 21.83it/s]

Epoch 9:   6%|▌         | 120/2000 [00:05<01:26, 21.82it/s]

Epoch 9:   6%|▌         | 123/2000 [00:05<01:25, 21.83it/s]

Epoch 9:   6%|▋         | 126/2000 [00:05<01:25, 21.82it/s]

Epoch 9:   6%|▋         | 129/2000 [00:05<01:25, 21.82it/s]

Epoch 9:   7%|▋         | 132/2000 [00:06<01:25, 21.83it/s]

Epoch 9:   7%|▋         | 135/2000 [00:06<01:25, 21.84it/s]

Epoch 9:   7%|▋         | 138/2000 [00:06<01:25, 21.83it/s]

Epoch 9:   7%|▋         | 141/2000 [00:06<01:25, 21.83it/s]

Epoch 9:   7%|▋         | 144/2000 [00:06<01:25, 21.83it/s]

Epoch 9:   7%|▋         | 147/2000 [00:06<01:24, 21.83it/s]

Epoch 9:   8%|▊         | 150/2000 [00:06<01:24, 21.84it/s]

Epoch 9:   8%|▊         | 153/2000 [00:07<01:24, 21.85it/s]

Epoch 9:   8%|▊         | 156/2000 [00:07<01:24, 21.84it/s]

Epoch 9:   8%|▊         | 159/2000 [00:07<01:24, 21.85it/s]

Epoch 9:   8%|▊         | 162/2000 [00:07<01:24, 21.86it/s]

Epoch 9:   8%|▊         | 165/2000 [00:07<01:23, 21.85it/s]

Epoch 9:   8%|▊         | 168/2000 [00:07<01:23, 21.85it/s]

Epoch 9:   9%|▊         | 171/2000 [00:07<01:23, 21.85it/s]

Epoch 9:   9%|▊         | 174/2000 [00:07<01:23, 21.85it/s]

Epoch 9:   9%|▉         | 177/2000 [00:08<01:23, 21.84it/s]

Epoch 9:   9%|▉         | 180/2000 [00:08<01:23, 21.85it/s]

Epoch 9:   9%|▉         | 183/2000 [00:08<01:23, 21.85it/s]

Epoch 9:   9%|▉         | 186/2000 [00:08<01:23, 21.79it/s]

Epoch 9:   9%|▉         | 189/2000 [00:08<01:23, 21.81it/s]

Epoch 9:  10%|▉         | 192/2000 [00:08<01:22, 21.81it/s]

Epoch 9:  10%|▉         | 195/2000 [00:08<01:22, 21.82it/s]

Epoch 9:  10%|▉         | 198/2000 [00:09<01:22, 21.84it/s]

Epoch 9:  10%|█         | 201/2000 [00:09<01:22, 21.83it/s]

Epoch 9:  10%|█         | 204/2000 [00:09<01:22, 21.82it/s]

Epoch 9:  10%|█         | 207/2000 [00:09<01:22, 21.83it/s]

Epoch 9:  10%|█         | 210/2000 [00:09<01:21, 21.84it/s]

Epoch 9:  11%|█         | 213/2000 [00:09<01:21, 21.85it/s]

Epoch 9:  11%|█         | 216/2000 [00:09<01:21, 21.84it/s]

Epoch 9:  11%|█         | 219/2000 [00:10<01:21, 21.85it/s]

Epoch 9:  11%|█         | 222/2000 [00:10<01:21, 21.84it/s]

Epoch 9:  11%|█▏        | 225/2000 [00:10<01:21, 21.84it/s]

Epoch 9:  11%|█▏        | 228/2000 [00:10<01:21, 21.84it/s]

Epoch 9:  12%|█▏        | 231/2000 [00:10<01:21, 21.83it/s]

Epoch 9:  12%|█▏        | 234/2000 [00:10<01:20, 21.84it/s]

Epoch 9:  12%|█▏        | 237/2000 [00:10<01:20, 21.84it/s]

Epoch 9:  12%|█▏        | 240/2000 [00:11<01:20, 21.85it/s]

Epoch 9:  12%|█▏        | 243/2000 [00:11<01:20, 21.85it/s]

Epoch 9:  12%|█▏        | 246/2000 [00:11<01:20, 21.85it/s]

Epoch 9:  12%|█▏        | 249/2000 [00:11<01:20, 21.83it/s]

Epoch 9:  13%|█▎        | 252/2000 [00:11<01:20, 21.83it/s]

Epoch 9:  13%|█▎        | 255/2000 [00:11<01:19, 21.82it/s]

Epoch 9:  13%|█▎        | 258/2000 [00:11<01:19, 21.84it/s]

Epoch 9:  13%|█▎        | 261/2000 [00:11<01:19, 21.84it/s]

Epoch 9:  13%|█▎        | 264/2000 [00:12<01:19, 21.79it/s]

Epoch 9:  13%|█▎        | 267/2000 [00:12<01:19, 21.81it/s]

Epoch 9:  14%|█▎        | 270/2000 [00:12<01:19, 21.81it/s]

Epoch 9:  14%|█▎        | 273/2000 [00:12<01:19, 21.82it/s]

Epoch 9:  14%|█▍        | 276/2000 [00:12<01:19, 21.82it/s]

Epoch 9:  14%|█▍        | 279/2000 [00:12<01:18, 21.81it/s]

Epoch 9:  14%|█▍        | 282/2000 [00:12<01:18, 21.81it/s]

Epoch 9:  14%|█▍        | 285/2000 [00:13<01:18, 21.83it/s]

Epoch 9:  14%|█▍        | 288/2000 [00:13<01:18, 21.82it/s]

Epoch 9:  15%|█▍        | 291/2000 [00:13<01:18, 21.84it/s]

Epoch 9:  15%|█▍        | 294/2000 [00:13<01:18, 21.84it/s]

Epoch 9:  15%|█▍        | 297/2000 [00:13<01:17, 21.84it/s]

Epoch 9:  15%|█▌        | 300/2000 [00:13<01:17, 21.85it/s]

Epoch 9:  15%|█▌        | 303/2000 [00:13<01:17, 21.83it/s]

Epoch 9:  15%|█▌        | 306/2000 [00:14<01:17, 21.83it/s]

Epoch 9:  15%|█▌        | 309/2000 [00:14<01:17, 21.82it/s]

Epoch 9:  16%|█▌        | 312/2000 [00:14<01:17, 21.83it/s]

Epoch 9:  16%|█▌        | 315/2000 [00:14<01:17, 21.83it/s]

Epoch 9:  16%|█▌        | 318/2000 [00:14<01:17, 21.83it/s]

Epoch 9:  16%|█▌        | 321/2000 [00:14<01:16, 21.82it/s]

Epoch 9:  16%|█▌        | 324/2000 [00:14<01:16, 21.83it/s]

Epoch 9:  16%|█▋        | 327/2000 [00:14<01:16, 21.84it/s]

Epoch 9:  16%|█▋        | 330/2000 [00:15<01:16, 21.83it/s]

Epoch 9:  17%|█▋        | 333/2000 [00:15<01:16, 21.84it/s]

Epoch 9:  17%|█▋        | 336/2000 [00:15<01:16, 21.84it/s]

Epoch 9:  17%|█▋        | 339/2000 [00:15<01:16, 21.83it/s]

Epoch 9:  17%|█▋        | 342/2000 [00:15<01:15, 21.83it/s]

Epoch 9:  17%|█▋        | 345/2000 [00:15<01:18, 21.19it/s]

Epoch 9:  17%|█▋        | 348/2000 [00:15<01:18, 21.06it/s]

Epoch 9:  18%|█▊        | 351/2000 [00:16<01:17, 21.21it/s]

Epoch 9:  18%|█▊        | 354/2000 [00:16<01:17, 21.31it/s]

Epoch 9:  18%|█▊        | 357/2000 [00:16<01:16, 21.46it/s]

Epoch 9:  18%|█▊        | 360/2000 [00:16<01:16, 21.56it/s]

Epoch 9:  18%|█▊        | 363/2000 [00:16<01:15, 21.64it/s]

Epoch 9:  18%|█▊        | 366/2000 [00:16<01:15, 21.70it/s]

Epoch 9:  18%|█▊        | 369/2000 [00:16<01:15, 21.73it/s]

Epoch 9:  19%|█▊        | 372/2000 [00:17<01:14, 21.75it/s]

Epoch 9:  19%|█▉        | 375/2000 [00:17<01:14, 21.76it/s]

Epoch 9:  19%|█▉        | 378/2000 [00:17<01:14, 21.78it/s]

Epoch 9:  19%|█▉        | 381/2000 [00:17<01:14, 21.78it/s]

Epoch 9:  19%|█▉        | 384/2000 [00:17<01:14, 21.80it/s]

Epoch 9:  19%|█▉        | 387/2000 [00:17<01:13, 21.80it/s]

Epoch 9:  20%|█▉        | 390/2000 [00:17<01:13, 21.82it/s]

Epoch 9:  20%|█▉        | 393/2000 [00:18<01:13, 21.81it/s]

Epoch 9:  20%|█▉        | 396/2000 [00:18<01:13, 21.82it/s]

Epoch 9:  20%|█▉        | 399/2000 [00:18<01:13, 21.83it/s]

Epoch 9:  20%|██        | 402/2000 [00:18<01:13, 21.84it/s]

Epoch 9:  20%|██        | 405/2000 [00:18<01:13, 21.82it/s]

Epoch 9:  20%|██        | 408/2000 [00:18<01:12, 21.83it/s]

Epoch 9:  21%|██        | 411/2000 [00:18<01:12, 21.81it/s]

Epoch 9:  21%|██        | 414/2000 [00:18<01:12, 21.81it/s]

Epoch 9:  21%|██        | 417/2000 [00:19<01:12, 21.82it/s]

Epoch 9:  21%|██        | 420/2000 [00:19<01:12, 21.81it/s]

Epoch 9:  21%|██        | 423/2000 [00:19<01:12, 21.83it/s]

Epoch 9:  21%|██▏       | 426/2000 [00:19<01:12, 21.81it/s]

Epoch 9:  21%|██▏       | 429/2000 [00:19<01:12, 21.82it/s]

Epoch 9:  22%|██▏       | 432/2000 [00:19<01:11, 21.82it/s]

Epoch 9:  22%|██▏       | 435/2000 [00:19<01:11, 21.82it/s]

Epoch 9:  22%|██▏       | 438/2000 [00:20<01:11, 21.82it/s]

Epoch 9:  22%|██▏       | 441/2000 [00:20<01:11, 21.83it/s]

Epoch 9:  22%|██▏       | 444/2000 [00:20<01:11, 21.84it/s]

Epoch 9:  22%|██▏       | 447/2000 [00:20<01:11, 21.83it/s]

Epoch 9:  22%|██▎       | 450/2000 [00:20<01:11, 21.83it/s]

Epoch 9:  23%|██▎       | 453/2000 [00:20<01:10, 21.83it/s]

Epoch 9:  23%|██▎       | 456/2000 [00:20<01:10, 21.83it/s]

Epoch 9:  23%|██▎       | 459/2000 [00:21<01:10, 21.83it/s]

Epoch 9:  23%|██▎       | 462/2000 [00:21<01:10, 21.84it/s]

Epoch 9:  23%|██▎       | 465/2000 [00:21<01:10, 21.83it/s]

Epoch 9:  23%|██▎       | 468/2000 [00:21<01:10, 21.77it/s]

Epoch 9:  24%|██▎       | 471/2000 [00:21<01:10, 21.80it/s]

Epoch 9:  24%|██▎       | 474/2000 [00:21<01:09, 21.82it/s]

Epoch 9:  24%|██▍       | 477/2000 [00:21<01:09, 21.82it/s]

Epoch 9:  24%|██▍       | 480/2000 [00:22<01:09, 21.78it/s]

Epoch 9:  24%|██▍       | 483/2000 [00:22<01:09, 21.77it/s]

Epoch 9:  24%|██▍       | 486/2000 [00:22<01:09, 21.78it/s]

Epoch 9:  24%|██▍       | 489/2000 [00:22<01:09, 21.79it/s]

Epoch 9:  25%|██▍       | 492/2000 [00:22<01:09, 21.80it/s]

Epoch 9:  25%|██▍       | 495/2000 [00:22<01:09, 21.79it/s]

Epoch 9:  25%|██▍       | 498/2000 [00:22<01:08, 21.80it/s]

Epoch 9:  25%|██▌       | 501/2000 [00:22<01:08, 21.80it/s]

Epoch 9:  25%|██▌       | 504/2000 [00:23<01:08, 21.80it/s]

Epoch 9:  25%|██▌       | 507/2000 [00:23<01:08, 21.82it/s]

Epoch 9:  26%|██▌       | 510/2000 [00:23<01:08, 21.83it/s]

Epoch 9:  26%|██▌       | 513/2000 [00:23<01:08, 21.82it/s]

Epoch 9:  26%|██▌       | 516/2000 [00:23<01:07, 21.83it/s]

Epoch 9:  26%|██▌       | 519/2000 [00:23<01:07, 21.84it/s]

Epoch 9:  26%|██▌       | 522/2000 [00:23<01:07, 21.84it/s]

Epoch 9:  26%|██▋       | 525/2000 [00:24<01:07, 21.84it/s]

Epoch 9:  26%|██▋       | 528/2000 [00:24<01:07, 21.84it/s]

Epoch 9:  27%|██▋       | 531/2000 [00:24<01:07, 21.85it/s]

Epoch 9:  27%|██▋       | 534/2000 [00:24<01:07, 21.85it/s]

Epoch 9:  27%|██▋       | 537/2000 [00:24<01:06, 21.85it/s]

Epoch 9:  27%|██▋       | 540/2000 [00:24<01:06, 21.85it/s]

Epoch 9:  27%|██▋       | 543/2000 [00:24<01:06, 21.85it/s]

Epoch 9:  27%|██▋       | 546/2000 [00:25<01:06, 21.84it/s]

Epoch 9:  27%|██▋       | 549/2000 [00:25<01:06, 21.83it/s]

Epoch 9:  28%|██▊       | 552/2000 [00:25<01:06, 21.85it/s]

Epoch 9:  28%|██▊       | 555/2000 [00:25<01:06, 21.84it/s]

Epoch 9:  28%|██▊       | 558/2000 [00:25<01:06, 21.84it/s]

Epoch 9:  28%|██▊       | 561/2000 [00:25<01:05, 21.82it/s]

Epoch 9:  28%|██▊       | 564/2000 [00:25<01:05, 21.82it/s]

Epoch 9:  28%|██▊       | 567/2000 [00:26<01:05, 21.82it/s]

Epoch 9:  28%|██▊       | 570/2000 [00:26<01:05, 21.82it/s]

Epoch 9:  29%|██▊       | 573/2000 [00:26<01:05, 21.81it/s]

Epoch 9:  29%|██▉       | 576/2000 [00:26<01:05, 21.81it/s]

Epoch 9:  29%|██▉       | 579/2000 [00:26<01:05, 21.82it/s]

Epoch 9:  29%|██▉       | 582/2000 [00:26<01:05, 21.81it/s]

Epoch 9:  29%|██▉       | 585/2000 [00:26<01:04, 21.82it/s]

Epoch 9:  29%|██▉       | 588/2000 [00:26<01:04, 21.81it/s]

Epoch 9:  30%|██▉       | 591/2000 [00:27<01:04, 21.80it/s]

Epoch 9:  30%|██▉       | 594/2000 [00:27<01:04, 21.82it/s]

Epoch 9:  30%|██▉       | 597/2000 [00:27<01:04, 21.82it/s]

Epoch 9:  30%|███       | 600/2000 [00:27<01:04, 21.83it/s]

Epoch 9:  30%|███       | 603/2000 [00:27<01:03, 21.85it/s]

Epoch 9:  30%|███       | 606/2000 [00:27<01:03, 21.86it/s]

Epoch 9:  30%|███       | 609/2000 [00:27<01:03, 21.84it/s]

Epoch 9:  31%|███       | 612/2000 [00:28<01:03, 21.84it/s]

Epoch 9:  31%|███       | 615/2000 [00:28<01:03, 21.84it/s]

Epoch 9:  31%|███       | 618/2000 [00:28<01:03, 21.84it/s]

Epoch 9:  31%|███       | 621/2000 [00:28<01:03, 21.84it/s]

Epoch 9:  31%|███       | 624/2000 [00:28<01:03, 21.83it/s]

Epoch 9:  31%|███▏      | 627/2000 [00:28<01:02, 21.83it/s]

Epoch 9:  32%|███▏      | 630/2000 [00:28<01:02, 21.82it/s]

Epoch 9:  32%|███▏      | 633/2000 [00:29<01:02, 21.82it/s]

Epoch 9:  32%|███▏      | 636/2000 [00:29<01:02, 21.82it/s]

Epoch 9:  32%|███▏      | 639/2000 [00:29<01:02, 21.82it/s]

Epoch 9:  32%|███▏      | 642/2000 [00:29<01:02, 21.83it/s]

Epoch 9:  32%|███▏      | 645/2000 [00:29<01:02, 21.80it/s]

Epoch 9:  32%|███▏      | 648/2000 [00:29<01:01, 21.81it/s]

Epoch 9:  33%|███▎      | 651/2000 [00:29<01:01, 21.81it/s]

Epoch 9:  33%|███▎      | 654/2000 [00:29<01:01, 21.82it/s]

Epoch 9:  33%|███▎      | 657/2000 [00:30<01:01, 21.82it/s]

Epoch 9:  33%|███▎      | 660/2000 [00:30<01:01, 21.82it/s]

Epoch 9:  33%|███▎      | 663/2000 [00:30<01:01, 21.82it/s]

Epoch 9:  33%|███▎      | 666/2000 [00:30<01:01, 21.82it/s]

Epoch 9:  33%|███▎      | 669/2000 [00:30<01:00, 21.82it/s]

Epoch 9:  34%|███▎      | 672/2000 [00:30<01:00, 21.82it/s]

Epoch 9:  34%|███▍      | 675/2000 [00:30<01:00, 21.83it/s]

Epoch 9:  34%|███▍      | 678/2000 [00:31<01:00, 21.84it/s]

Epoch 9:  34%|███▍      | 681/2000 [00:31<01:00, 21.82it/s]

Epoch 9:  34%|███▍      | 684/2000 [00:31<01:00, 21.81it/s]

Epoch 9:  34%|███▍      | 687/2000 [00:31<01:00, 21.81it/s]

Epoch 9:  34%|███▍      | 690/2000 [00:31<01:00, 21.83it/s]

Epoch 9:  35%|███▍      | 693/2000 [00:31<00:59, 21.83it/s]

Epoch 9:  35%|███▍      | 696/2000 [00:31<00:59, 21.83it/s]

Epoch 9:  35%|███▍      | 699/2000 [00:32<00:59, 21.82it/s]

Epoch 9:  35%|███▌      | 702/2000 [00:32<00:59, 21.82it/s]

Epoch 9:  35%|███▌      | 705/2000 [00:32<00:59, 21.83it/s]

Epoch 9:  35%|███▌      | 708/2000 [00:32<00:59, 21.83it/s]

Epoch 9:  36%|███▌      | 711/2000 [00:32<00:59, 21.83it/s]

Epoch 9:  36%|███▌      | 714/2000 [00:32<00:58, 21.84it/s]

Epoch 9:  36%|███▌      | 717/2000 [00:32<00:58, 21.82it/s]

Epoch 9:  36%|███▌      | 720/2000 [00:33<00:58, 21.82it/s]

Epoch 9:  36%|███▌      | 723/2000 [00:33<00:58, 21.83it/s]

Epoch 9:  36%|███▋      | 726/2000 [00:33<00:58, 21.83it/s]

Epoch 9:  36%|███▋      | 729/2000 [00:33<00:58, 21.68it/s]

Epoch 9:  37%|███▋      | 732/2000 [00:33<00:58, 21.72it/s]

Epoch 9:  37%|███▋      | 735/2000 [00:33<00:58, 21.78it/s]

Epoch 9:  37%|███▋      | 738/2000 [00:33<00:57, 21.79it/s]

Epoch 9:  37%|███▋      | 741/2000 [00:33<00:57, 21.82it/s]

Epoch 9:  37%|███▋      | 744/2000 [00:34<00:57, 21.82it/s]

Epoch 9:  37%|███▋      | 747/2000 [00:34<00:57, 21.83it/s]

Epoch 9:  38%|███▊      | 750/2000 [00:34<00:57, 21.83it/s]

Epoch 9:  38%|███▊      | 753/2000 [00:34<00:57, 21.84it/s]

Epoch 9:  38%|███▊      | 756/2000 [00:34<00:56, 21.85it/s]

Epoch 9:  38%|███▊      | 759/2000 [00:34<00:56, 21.84it/s]

Epoch 9:  38%|███▊      | 762/2000 [00:34<00:56, 21.84it/s]

Epoch 9:  38%|███▊      | 765/2000 [00:35<00:56, 21.84it/s]

Epoch 9:  38%|███▊      | 768/2000 [00:35<00:56, 21.83it/s]

Epoch 9:  39%|███▊      | 771/2000 [00:35<00:56, 21.83it/s]

Epoch 9:  39%|███▊      | 774/2000 [00:35<00:56, 21.83it/s]

Epoch 9:  39%|███▉      | 777/2000 [00:35<00:56, 21.82it/s]

Epoch 9:  39%|███▉      | 780/2000 [00:35<00:55, 21.81it/s]

Epoch 9:  39%|███▉      | 783/2000 [00:35<00:55, 21.80it/s]

Epoch 9:  39%|███▉      | 786/2000 [00:36<00:55, 21.82it/s]

Epoch 9:  39%|███▉      | 789/2000 [00:36<00:55, 21.83it/s]

Epoch 9:  40%|███▉      | 792/2000 [00:36<00:55, 21.83it/s]

Epoch 9:  40%|███▉      | 795/2000 [00:36<00:55, 21.84it/s]

Epoch 9:  40%|███▉      | 798/2000 [00:36<00:55, 21.84it/s]

Epoch 9:  40%|████      | 801/2000 [00:36<00:54, 21.84it/s]

Epoch 9:  40%|████      | 804/2000 [00:36<00:54, 21.85it/s]

Epoch 9:  40%|████      | 807/2000 [00:37<00:54, 21.84it/s]

Epoch 9:  40%|████      | 810/2000 [00:37<00:54, 21.85it/s]

Epoch 9:  41%|████      | 813/2000 [00:37<00:54, 21.84it/s]

Epoch 9:  41%|████      | 816/2000 [00:37<00:54, 21.84it/s]

Epoch 9:  41%|████      | 819/2000 [00:37<00:54, 21.83it/s]

Epoch 9:  41%|████      | 822/2000 [00:37<00:53, 21.85it/s]

Epoch 9:  41%|████▏     | 825/2000 [00:37<00:53, 21.84it/s]

Epoch 9:  41%|████▏     | 828/2000 [00:37<00:53, 21.84it/s]

Epoch 9:  42%|████▏     | 831/2000 [00:38<00:53, 21.83it/s]

Epoch 9:  42%|████▏     | 834/2000 [00:38<00:53, 21.81it/s]

Epoch 9:  42%|████▏     | 837/2000 [00:38<00:53, 21.82it/s]

Epoch 9:  42%|████▏     | 840/2000 [00:38<00:53, 21.83it/s]

Epoch 9:  42%|████▏     | 843/2000 [00:38<00:52, 21.85it/s]

Epoch 9:  42%|████▏     | 846/2000 [00:38<00:52, 21.87it/s]

Epoch 9:  42%|████▏     | 849/2000 [00:38<00:52, 21.87it/s]

Epoch 9:  43%|████▎     | 852/2000 [00:39<00:52, 21.83it/s]

Epoch 9:  43%|████▎     | 855/2000 [00:39<00:52, 21.82it/s]

Epoch 9:  43%|████▎     | 858/2000 [00:39<00:52, 21.82it/s]

Epoch 9:  43%|████▎     | 861/2000 [00:39<00:52, 21.83it/s]

Epoch 9:  43%|████▎     | 864/2000 [00:39<00:52, 21.84it/s]

Epoch 9:  43%|████▎     | 867/2000 [00:39<00:51, 21.84it/s]

Epoch 9:  44%|████▎     | 870/2000 [00:39<00:51, 21.83it/s]

Epoch 9:  44%|████▎     | 873/2000 [00:40<00:51, 21.85it/s]

Epoch 9:  44%|████▍     | 876/2000 [00:40<00:51, 21.85it/s]

Epoch 9:  44%|████▍     | 879/2000 [00:40<00:51, 21.86it/s]

Epoch 9:  44%|████▍     | 882/2000 [00:40<00:51, 21.87it/s]

Epoch 9:  44%|████▍     | 885/2000 [00:40<00:50, 21.89it/s]

Epoch 9:  44%|████▍     | 888/2000 [00:40<00:50, 21.87it/s]

Epoch 9:  45%|████▍     | 891/2000 [00:40<00:50, 21.86it/s]

Epoch 9:  45%|████▍     | 894/2000 [00:40<00:50, 21.86it/s]

Epoch 9:  45%|████▍     | 897/2000 [00:41<00:50, 21.87it/s]

Epoch 9:  45%|████▌     | 900/2000 [00:41<00:50, 21.86it/s]

Epoch 9:  45%|████▌     | 903/2000 [00:41<00:50, 21.87it/s]

Epoch 9:  45%|████▌     | 906/2000 [00:41<00:50, 21.87it/s]

Epoch 9:  45%|████▌     | 909/2000 [00:41<00:49, 21.88it/s]

Epoch 9:  46%|████▌     | 912/2000 [00:41<00:49, 21.87it/s]

Epoch 9:  46%|████▌     | 915/2000 [00:41<00:49, 21.89it/s]

Epoch 9:  46%|████▌     | 918/2000 [00:42<00:49, 21.89it/s]

Epoch 9:  46%|████▌     | 921/2000 [00:42<00:49, 21.88it/s]

Epoch 9:  46%|████▌     | 924/2000 [00:42<00:49, 21.87it/s]

Epoch 9:  46%|████▋     | 927/2000 [00:42<00:49, 21.87it/s]

Epoch 9:  46%|████▋     | 930/2000 [00:42<00:48, 21.87it/s]

Epoch 9:  47%|████▋     | 933/2000 [00:42<00:48, 21.87it/s]

Epoch 9:  47%|████▋     | 936/2000 [00:42<00:48, 21.87it/s]

Epoch 9:  47%|████▋     | 939/2000 [00:43<00:48, 21.87it/s]

Epoch 9:  47%|████▋     | 942/2000 [00:43<00:48, 21.89it/s]

Epoch 9:  47%|████▋     | 945/2000 [00:43<00:48, 21.89it/s]

Epoch 9:  47%|████▋     | 948/2000 [00:43<00:48, 21.88it/s]

Epoch 9:  48%|████▊     | 951/2000 [00:43<00:47, 21.87it/s]

Epoch 9:  48%|████▊     | 954/2000 [00:43<00:47, 21.87it/s]

Epoch 9:  48%|████▊     | 957/2000 [00:43<00:47, 21.87it/s]

Epoch 9:  48%|████▊     | 960/2000 [00:44<00:47, 21.87it/s]

Epoch 9:  48%|████▊     | 963/2000 [00:44<00:47, 21.87it/s]

Epoch 9:  48%|████▊     | 966/2000 [00:44<00:47, 21.88it/s]

Epoch 9:  48%|████▊     | 969/2000 [00:44<00:47, 21.88it/s]

Epoch 9:  49%|████▊     | 972/2000 [00:44<00:47, 21.87it/s]

Epoch 9:  49%|████▉     | 975/2000 [00:44<00:46, 21.86it/s]

Epoch 9:  49%|████▉     | 978/2000 [00:44<00:46, 21.87it/s]

Epoch 9:  49%|████▉     | 981/2000 [00:44<00:46, 21.87it/s]

Epoch 9:  49%|████▉     | 984/2000 [00:45<00:46, 21.88it/s]

Epoch 9:  49%|████▉     | 987/2000 [00:45<00:46, 21.87it/s]

Epoch 9:  50%|████▉     | 990/2000 [00:45<00:46, 21.87it/s]

Epoch 9:  50%|████▉     | 993/2000 [00:45<00:46, 21.88it/s]

Epoch 9:  50%|████▉     | 996/2000 [00:45<00:45, 21.89it/s]

Epoch 9:  50%|████▉     | 999/2000 [00:45<00:45, 21.89it/s]

Epoch 9:  50%|█████     | 1002/2000 [00:45<00:45, 21.88it/s]

Epoch 9:  50%|█████     | 1005/2000 [00:46<00:45, 21.88it/s]

Epoch 9:  50%|█████     | 1008/2000 [00:46<00:45, 21.88it/s]

Epoch 9:  51%|█████     | 1011/2000 [00:46<00:45, 21.89it/s]

Epoch 9:  51%|█████     | 1014/2000 [00:46<00:45, 21.89it/s]

Epoch 9:  51%|█████     | 1017/2000 [00:46<00:44, 21.89it/s]

Epoch 9:  51%|█████     | 1020/2000 [00:46<00:44, 21.89it/s]

Epoch 9:  51%|█████     | 1023/2000 [00:46<00:44, 21.90it/s]

Epoch 9:  51%|█████▏    | 1026/2000 [00:47<00:44, 21.90it/s]

Epoch 9:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.89it/s]

Epoch 9:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.89it/s]

Epoch 9:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.90it/s]

Epoch 9:  52%|█████▏    | 1038/2000 [00:47<00:43, 21.89it/s]

Epoch 9:  52%|█████▏    | 1041/2000 [00:47<00:43, 21.87it/s]

Epoch 9:  52%|█████▏    | 1044/2000 [00:47<00:43, 21.87it/s]

Epoch 9:  52%|█████▏    | 1047/2000 [00:47<00:43, 21.89it/s]

Epoch 9:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.89it/s]

Epoch 9:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.89it/s]

Epoch 9:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.89it/s]

Epoch 9:  53%|█████▎    | 1059/2000 [00:48<00:43, 21.69it/s]

Epoch 9:  53%|█████▎    | 1062/2000 [00:48<00:44, 21.12it/s]

Epoch 9:  53%|█████▎    | 1065/2000 [00:48<00:44, 21.13it/s]

Epoch 9:  53%|█████▎    | 1068/2000 [00:48<00:43, 21.31it/s]

Epoch 9:  54%|█████▎    | 1071/2000 [00:49<00:43, 21.42it/s]

Epoch 9:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.56it/s]

Epoch 9:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.66it/s]

Epoch 9:  54%|█████▍    | 1080/2000 [00:49<00:42, 21.71it/s]

Epoch 9:  54%|█████▍    | 1083/2000 [00:49<00:42, 21.75it/s]

Epoch 9:  54%|█████▍    | 1086/2000 [00:49<00:41, 21.78it/s]

Epoch 9:  54%|█████▍    | 1089/2000 [00:49<00:41, 21.81it/s]

Epoch 9:  55%|█████▍    | 1092/2000 [00:50<00:41, 21.84it/s]

Epoch 9:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.86it/s]

Epoch 9:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.86it/s]

Epoch 9:  55%|█████▌    | 1101/2000 [00:50<00:41, 21.87it/s]

Epoch 9:  55%|█████▌    | 1104/2000 [00:50<00:40, 21.88it/s]

Epoch 9:  55%|█████▌    | 1107/2000 [00:50<00:40, 21.88it/s]

Epoch 9:  56%|█████▌    | 1110/2000 [00:50<00:40, 21.79it/s]

Epoch 9:  56%|█████▌    | 1113/2000 [00:51<00:40, 21.81it/s]

Epoch 9:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.82it/s]

Epoch 9:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.81it/s]

Epoch 9:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.83it/s]

Epoch 9:  56%|█████▋    | 1125/2000 [00:51<00:40, 21.84it/s]

Epoch 9:  56%|█████▋    | 1128/2000 [00:51<00:39, 21.84it/s]

Epoch 9:  57%|█████▋    | 1131/2000 [00:51<00:39, 21.76it/s]

Epoch 9:  57%|█████▋    | 1134/2000 [00:51<00:39, 21.79it/s]

Epoch 9:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.81it/s]

Epoch 9:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.76it/s]

Epoch 9:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.74it/s]

Epoch 9:  57%|█████▋    | 1146/2000 [00:52<00:39, 21.78it/s]

Epoch 9:  57%|█████▋    | 1149/2000 [00:52<00:39, 21.80it/s]

Epoch 9:  58%|█████▊    | 1152/2000 [00:52<00:38, 21.82it/s]

Epoch 9:  58%|█████▊    | 1155/2000 [00:52<00:38, 21.82it/s]

Epoch 9:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.84it/s]

Epoch 9:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.84it/s]

Epoch 9:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.77it/s]

Epoch 9:  58%|█████▊    | 1167/2000 [00:53<00:38, 21.79it/s]

Epoch 9:  58%|█████▊    | 1170/2000 [00:53<00:38, 21.81it/s]

Epoch 9:  59%|█████▊    | 1173/2000 [00:53<00:37, 21.83it/s]

Epoch 9:  59%|█████▉    | 1176/2000 [00:53<00:37, 21.85it/s]

Epoch 9:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.85it/s]

Epoch 9:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.85it/s]

Epoch 9:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.86it/s]

Epoch 9:  59%|█████▉    | 1188/2000 [00:54<00:37, 21.86it/s]

Epoch 9:  60%|█████▉    | 1191/2000 [00:54<00:37, 21.86it/s]

Epoch 9:  60%|█████▉    | 1194/2000 [00:54<00:36, 21.87it/s]

Epoch 9:  60%|█████▉    | 1197/2000 [00:54<00:36, 21.86it/s]

Epoch 9:  60%|██████    | 1200/2000 [00:55<00:36, 21.85it/s]

Epoch 9:  60%|██████    | 1203/2000 [00:55<00:36, 21.86it/s]

Epoch 9:  60%|██████    | 1206/2000 [00:55<00:36, 21.81it/s]

Epoch 9:  60%|██████    | 1209/2000 [00:55<00:36, 21.82it/s]

Epoch 9:  61%|██████    | 1212/2000 [00:55<00:36, 21.83it/s]

Epoch 9:  61%|██████    | 1215/2000 [00:55<00:35, 21.84it/s]

Epoch 9:  61%|██████    | 1218/2000 [00:55<00:35, 21.84it/s]

Epoch 9:  61%|██████    | 1221/2000 [00:55<00:35, 21.85it/s]

Epoch 9:  61%|██████    | 1224/2000 [00:56<00:35, 21.86it/s]

Epoch 9:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.82it/s]

Epoch 9:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.83it/s]

Epoch 9:  62%|██████▏   | 1233/2000 [00:56<00:35, 21.84it/s]

Epoch 9:  62%|██████▏   | 1236/2000 [00:56<00:34, 21.84it/s]

Epoch 9:  62%|██████▏   | 1239/2000 [00:56<00:34, 21.85it/s]

Epoch 9:  62%|██████▏   | 1242/2000 [00:56<00:34, 21.86it/s]

Epoch 9:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.87it/s]

Epoch 9:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.86it/s]

Epoch 9:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.86it/s]

Epoch 9:  63%|██████▎   | 1254/2000 [00:57<00:34, 21.88it/s]

Epoch 9:  63%|██████▎   | 1257/2000 [00:57<00:33, 21.86it/s]

Epoch 9:  63%|██████▎   | 1260/2000 [00:57<00:33, 21.86it/s]

Epoch 9:  63%|██████▎   | 1263/2000 [00:57<00:33, 21.86it/s]

Epoch 9:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.86it/s]

Epoch 9:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.80it/s]

Epoch 9:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.82it/s]

Epoch 9:  64%|██████▍   | 1275/2000 [00:58<00:33, 21.83it/s]

Epoch 9:  64%|██████▍   | 1278/2000 [00:58<00:33, 21.85it/s]

Epoch 9:  64%|██████▍   | 1281/2000 [00:58<00:32, 21.84it/s]

Epoch 9:  64%|██████▍   | 1284/2000 [00:58<00:32, 21.84it/s]

Epoch 9:  64%|██████▍   | 1287/2000 [00:58<00:32, 21.84it/s]

Epoch 9:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.84it/s]

Epoch 9:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.84it/s]

Epoch 9:  65%|██████▍   | 1296/2000 [00:59<00:32, 21.85it/s]

Epoch 9:  65%|██████▍   | 1299/2000 [00:59<00:32, 21.85it/s]

Epoch 9:  65%|██████▌   | 1302/2000 [00:59<00:31, 21.86it/s]

Epoch 9:  65%|██████▌   | 1305/2000 [00:59<00:31, 21.86it/s]

Epoch 9:  65%|██████▌   | 1308/2000 [00:59<00:31, 21.87it/s]

Epoch 9:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.87it/s]

Epoch 9:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.86it/s]

Epoch 9:  66%|██████▌   | 1317/2000 [01:00<00:31, 21.87it/s]

Epoch 9:  66%|██████▌   | 1320/2000 [01:00<00:31, 21.87it/s]

Epoch 9:  66%|██████▌   | 1323/2000 [01:00<00:30, 21.87it/s]

Epoch 9:  66%|██████▋   | 1326/2000 [01:00<00:30, 21.87it/s]

Epoch 9:  66%|██████▋   | 1329/2000 [01:00<00:30, 21.88it/s]

Epoch 9:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.88it/s]

Epoch 9:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.89it/s]

Epoch 9:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.88it/s]

Epoch 9:  67%|██████▋   | 1341/2000 [01:01<00:30, 21.87it/s]

Epoch 9:  67%|██████▋   | 1344/2000 [01:01<00:29, 21.88it/s]

Epoch 9:  67%|██████▋   | 1347/2000 [01:01<00:29, 21.87it/s]

Epoch 9:  68%|██████▊   | 1350/2000 [01:01<00:29, 21.87it/s]

Epoch 9:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.88it/s]

Epoch 9:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.81it/s]

Epoch 9:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.84it/s]

Epoch 9:  68%|██████▊   | 1362/2000 [01:02<00:29, 21.86it/s]

Epoch 9:  68%|██████▊   | 1365/2000 [01:02<00:29, 21.87it/s]

Epoch 9:  68%|██████▊   | 1368/2000 [01:02<00:28, 21.87it/s]

Epoch 9:  69%|██████▊   | 1371/2000 [01:02<00:28, 21.86it/s]

Epoch 9:  69%|██████▊   | 1374/2000 [01:02<00:28, 21.88it/s]

Epoch 9:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.88it/s]

Epoch 9:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.86it/s]

Epoch 9:  69%|██████▉   | 1383/2000 [01:03<00:28, 21.85it/s]

Epoch 9:  69%|██████▉   | 1386/2000 [01:03<00:28, 21.84it/s]

Epoch 9:  69%|██████▉   | 1389/2000 [01:03<00:27, 21.86it/s]

Epoch 9:  70%|██████▉   | 1392/2000 [01:03<00:27, 21.88it/s]

Epoch 9:  70%|██████▉   | 1395/2000 [01:03<00:27, 21.88it/s]

Epoch 9:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.87it/s]

Epoch 9:  70%|███████   | 1401/2000 [01:04<00:27, 21.87it/s]

Epoch 9:  70%|███████   | 1404/2000 [01:04<00:27, 21.88it/s]

Epoch 9:  70%|███████   | 1407/2000 [01:04<00:27, 21.85it/s]

Epoch 9:  70%|███████   | 1410/2000 [01:04<00:26, 21.86it/s]

Epoch 9:  71%|███████   | 1413/2000 [01:04<00:26, 21.85it/s]

Epoch 9:  71%|███████   | 1416/2000 [01:04<00:26, 21.85it/s]

Epoch 9:  71%|███████   | 1419/2000 [01:05<00:26, 21.86it/s]

Epoch 9:  71%|███████   | 1422/2000 [01:05<00:26, 21.87it/s]

Epoch 9:  71%|███████▏  | 1425/2000 [01:05<00:26, 21.87it/s]

Epoch 9:  71%|███████▏  | 1428/2000 [01:05<00:26, 21.86it/s]

Epoch 9:  72%|███████▏  | 1431/2000 [01:05<00:26, 21.86it/s]

Epoch 9:  72%|███████▏  | 1434/2000 [01:05<00:25, 21.87it/s]

Epoch 9:  72%|███████▏  | 1437/2000 [01:05<00:25, 21.88it/s]

Epoch 9:  72%|███████▏  | 1440/2000 [01:05<00:25, 21.86it/s]

Epoch 9:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.88it/s]

Epoch 9:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.89it/s]

Epoch 9:  72%|███████▏  | 1449/2000 [01:06<00:25, 21.88it/s]

Epoch 9:  73%|███████▎  | 1452/2000 [01:06<00:25, 21.87it/s]

Epoch 9:  73%|███████▎  | 1455/2000 [01:06<00:24, 21.87it/s]

Epoch 9:  73%|███████▎  | 1458/2000 [01:06<00:24, 21.87it/s]

Epoch 9:  73%|███████▎  | 1461/2000 [01:06<00:24, 21.88it/s]

Epoch 9:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.88it/s]

Epoch 9:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.87it/s]

Epoch 9:  74%|███████▎  | 1470/2000 [01:07<00:24, 21.87it/s]

Epoch 9:  74%|███████▎  | 1473/2000 [01:07<00:24, 21.87it/s]

Epoch 9:  74%|███████▍  | 1476/2000 [01:07<00:23, 21.86it/s]

Epoch 9:  74%|███████▍  | 1479/2000 [01:07<00:23, 21.86it/s]

Epoch 9:  74%|███████▍  | 1482/2000 [01:07<00:23, 21.86it/s]

Epoch 9:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.87it/s]

Epoch 9:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.88it/s]

Epoch 9:  75%|███████▍  | 1491/2000 [01:08<00:23, 21.87it/s]

Epoch 9:  75%|███████▍  | 1494/2000 [01:08<00:23, 21.87it/s]

Epoch 9:  75%|███████▍  | 1497/2000 [01:08<00:23, 21.83it/s]

Epoch 9:  75%|███████▌  | 1500/2000 [01:08<00:22, 21.84it/s]

Epoch 9:  75%|███████▌  | 1503/2000 [01:08<00:22, 21.84it/s]

Epoch 9:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.85it/s]

Epoch 9:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.85it/s]

Epoch 9:  76%|███████▌  | 1512/2000 [01:09<00:22, 21.86it/s]

Epoch 9:  76%|███████▌  | 1515/2000 [01:09<00:22, 21.86it/s]

Epoch 9:  76%|███████▌  | 1518/2000 [01:09<00:22, 21.88it/s]

Epoch 9:  76%|███████▌  | 1521/2000 [01:09<00:21, 21.87it/s]

Epoch 9:  76%|███████▌  | 1524/2000 [01:09<00:21, 21.87it/s]

Epoch 9:  76%|███████▋  | 1527/2000 [01:09<00:21, 21.87it/s]

Epoch 9:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.87it/s]

Epoch 9:  77%|███████▋  | 1533/2000 [01:10<00:21, 21.88it/s]

Epoch 9:  77%|███████▋  | 1536/2000 [01:10<00:21, 21.87it/s]

Epoch 9:  77%|███████▋  | 1539/2000 [01:10<00:21, 21.87it/s]

Epoch 9:  77%|███████▋  | 1542/2000 [01:10<00:20, 21.86it/s]

Epoch 9:  77%|███████▋  | 1545/2000 [01:10<00:20, 21.85it/s]

Epoch 9:  77%|███████▋  | 1548/2000 [01:10<00:20, 21.84it/s]

Epoch 9:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.85it/s]

Epoch 9:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.84it/s]

Epoch 9:  78%|███████▊  | 1557/2000 [01:11<00:20, 21.84it/s]

Epoch 9:  78%|███████▊  | 1560/2000 [01:11<00:20, 21.84it/s]

Epoch 9:  78%|███████▊  | 1563/2000 [01:11<00:20, 21.82it/s]

Epoch 9:  78%|███████▊  | 1566/2000 [01:11<00:19, 21.84it/s]

Epoch 9:  78%|███████▊  | 1569/2000 [01:11<00:19, 21.85it/s]

Epoch 9:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.85it/s]

Epoch 9:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.85it/s]

Epoch 9:  79%|███████▉  | 1578/2000 [01:12<00:19, 21.86it/s]

Epoch 9:  79%|███████▉  | 1581/2000 [01:12<00:19, 21.87it/s]

Epoch 9:  79%|███████▉  | 1584/2000 [01:12<00:19, 21.86it/s]

Epoch 9:  79%|███████▉  | 1587/2000 [01:12<00:18, 21.86it/s]

Epoch 9:  80%|███████▉  | 1590/2000 [01:12<00:18, 21.85it/s]

Epoch 9:  80%|███████▉  | 1593/2000 [01:12<00:18, 21.86it/s]

Epoch 9:  80%|███████▉  | 1596/2000 [01:13<00:18, 21.87it/s]

Epoch 9:  80%|███████▉  | 1599/2000 [01:13<00:18, 21.88it/s]

Epoch 9:  80%|████████  | 1602/2000 [01:13<00:18, 21.87it/s]

Epoch 9:  80%|████████  | 1605/2000 [01:13<00:18, 21.88it/s]

Epoch 9:  80%|████████  | 1608/2000 [01:13<00:17, 21.88it/s]

Epoch 9:  81%|████████  | 1611/2000 [01:13<00:17, 21.89it/s]

Epoch 9:  81%|████████  | 1614/2000 [01:13<00:17, 21.90it/s]

Epoch 9:  81%|████████  | 1617/2000 [01:14<00:17, 21.89it/s]

Epoch 9:  81%|████████  | 1620/2000 [01:14<00:17, 21.89it/s]

Epoch 9:  81%|████████  | 1623/2000 [01:14<00:17, 21.88it/s]

Epoch 9:  81%|████████▏ | 1626/2000 [01:14<00:17, 21.87it/s]

Epoch 9:  81%|████████▏ | 1629/2000 [01:14<00:16, 21.88it/s]

Epoch 9:  82%|████████▏ | 1632/2000 [01:14<00:16, 21.88it/s]

Epoch 9:  82%|████████▏ | 1635/2000 [01:14<00:16, 21.88it/s]

Epoch 9:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.88it/s]

Epoch 9:  82%|████████▏ | 1641/2000 [01:15<00:16, 21.89it/s]

Epoch 9:  82%|████████▏ | 1644/2000 [01:15<00:16, 21.89it/s]

Epoch 9:  82%|████████▏ | 1647/2000 [01:15<00:16, 21.89it/s]

Epoch 9:  82%|████████▎ | 1650/2000 [01:15<00:15, 21.89it/s]

Epoch 9:  83%|████████▎ | 1653/2000 [01:15<00:15, 21.90it/s]

Epoch 9:  83%|████████▎ | 1656/2000 [01:15<00:15, 21.90it/s]

Epoch 9:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.89it/s]

Epoch 9:  83%|████████▎ | 1662/2000 [01:16<00:15, 21.89it/s]

Epoch 9:  83%|████████▎ | 1665/2000 [01:16<00:15, 21.89it/s]

Epoch 9:  83%|████████▎ | 1668/2000 [01:16<00:15, 21.88it/s]

Epoch 9:  84%|████████▎ | 1671/2000 [01:16<00:15, 21.87it/s]

Epoch 9:  84%|████████▎ | 1674/2000 [01:16<00:14, 21.87it/s]

Epoch 9:  84%|████████▍ | 1677/2000 [01:16<00:14, 21.88it/s]

Epoch 9:  84%|████████▍ | 1680/2000 [01:16<00:14, 21.88it/s]

Epoch 9:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.89it/s]

Epoch 9:  84%|████████▍ | 1686/2000 [01:17<00:14, 21.89it/s]

Epoch 9:  84%|████████▍ | 1689/2000 [01:17<00:14, 21.88it/s]

Epoch 9:  85%|████████▍ | 1692/2000 [01:17<00:14, 21.89it/s]

Epoch 9:  85%|████████▍ | 1695/2000 [01:17<00:13, 21.88it/s]

Epoch 9:  85%|████████▍ | 1698/2000 [01:17<00:13, 21.88it/s]

Epoch 9:  85%|████████▌ | 1701/2000 [01:17<00:13, 21.87it/s]

Epoch 9:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.88it/s]

Epoch 9:  85%|████████▌ | 1707/2000 [01:18<00:13, 21.88it/s]

Epoch 9:  86%|████████▌ | 1710/2000 [01:18<00:13, 21.89it/s]

Epoch 9:  86%|████████▌ | 1713/2000 [01:18<00:13, 21.88it/s]

Epoch 9:  86%|████████▌ | 1716/2000 [01:18<00:12, 21.89it/s]

Epoch 9:  86%|████████▌ | 1719/2000 [01:18<00:12, 21.88it/s]

Epoch 9:  86%|████████▌ | 1722/2000 [01:18<00:12, 21.88it/s]

Epoch 9:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.87it/s]

Epoch 9:  86%|████████▋ | 1728/2000 [01:19<00:12, 21.87it/s]

Epoch 9:  87%|████████▋ | 1731/2000 [01:19<00:12, 21.84it/s]

Epoch 9:  87%|████████▋ | 1734/2000 [01:19<00:12, 21.81it/s]

Epoch 9:  87%|████████▋ | 1737/2000 [01:19<00:12, 21.81it/s]

Epoch 9:  87%|████████▋ | 1740/2000 [01:19<00:11, 21.82it/s]

Epoch 9:  87%|████████▋ | 1743/2000 [01:19<00:11, 21.82it/s]

Epoch 9:  87%|████████▋ | 1746/2000 [01:19<00:11, 21.85it/s]

Epoch 9:  87%|████████▋ | 1749/2000 [01:20<00:11, 21.84it/s]

Epoch 9:  88%|████████▊ | 1752/2000 [01:20<00:11, 21.65it/s]

Epoch 9:  88%|████████▊ | 1755/2000 [01:20<00:11, 21.70it/s]

Epoch 9:  88%|████████▊ | 1758/2000 [01:20<00:11, 21.74it/s]

Epoch 9:  88%|████████▊ | 1761/2000 [01:20<00:10, 21.78it/s]

Epoch 9:  88%|████████▊ | 1764/2000 [01:20<00:10, 21.80it/s]

Epoch 9:  88%|████████▊ | 1767/2000 [01:20<00:10, 21.83it/s]

Epoch 9:  88%|████████▊ | 1770/2000 [01:21<00:10, 21.86it/s]

Epoch 9:  89%|████████▊ | 1773/2000 [01:21<00:10, 21.86it/s]

Epoch 9:  89%|████████▉ | 1776/2000 [01:21<00:10, 21.13it/s]

Epoch 9:  89%|████████▉ | 1779/2000 [01:21<00:10, 21.08it/s]

Epoch 9:  89%|████████▉ | 1782/2000 [01:21<00:10, 21.26it/s]

Epoch 9:  89%|████████▉ | 1785/2000 [01:21<00:10, 21.37it/s]

Epoch 9:  89%|████████▉ | 1788/2000 [01:21<00:09, 21.52it/s]

Epoch 9:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.63it/s]

Epoch 9:  90%|████████▉ | 1794/2000 [01:22<00:09, 21.71it/s]

Epoch 9:  90%|████████▉ | 1797/2000 [01:22<00:09, 21.76it/s]

Epoch 9:  90%|█████████ | 1800/2000 [01:22<00:09, 21.80it/s]

Epoch 9:  90%|█████████ | 1803/2000 [01:22<00:09, 21.82it/s]

Epoch 9:  90%|█████████ | 1806/2000 [01:22<00:08, 21.85it/s]

Epoch 9:  90%|█████████ | 1809/2000 [01:22<00:08, 21.86it/s]

Epoch 9:  91%|█████████ | 1812/2000 [01:23<00:08, 21.88it/s]

Epoch 9:  91%|█████████ | 1815/2000 [01:23<00:08, 21.87it/s]

Epoch 9:  91%|█████████ | 1818/2000 [01:23<00:08, 21.88it/s]

Epoch 9:  91%|█████████ | 1821/2000 [01:23<00:08, 21.88it/s]

Epoch 9:  91%|█████████ | 1824/2000 [01:23<00:08, 21.84it/s]

Epoch 9:  91%|█████████▏| 1827/2000 [01:23<00:07, 21.85it/s]

Epoch 9:  92%|█████████▏| 1830/2000 [01:23<00:07, 21.85it/s]

Epoch 9:  92%|█████████▏| 1833/2000 [01:23<00:07, 21.85it/s]

Epoch 9:  92%|█████████▏| 1836/2000 [01:24<00:07, 21.85it/s]

Epoch 9:  92%|█████████▏| 1839/2000 [01:24<00:07, 21.85it/s]

Epoch 9:  92%|█████████▏| 1842/2000 [01:24<00:07, 21.84it/s]

Epoch 9:  92%|█████████▏| 1845/2000 [01:24<00:07, 21.84it/s]

Epoch 9:  92%|█████████▏| 1848/2000 [01:24<00:06, 21.85it/s]

Epoch 9:  93%|█████████▎| 1851/2000 [01:24<00:06, 21.84it/s]

Epoch 9:  93%|█████████▎| 1854/2000 [01:24<00:06, 21.85it/s]

Epoch 9:  93%|█████████▎| 1857/2000 [01:25<00:06, 21.85it/s]

Epoch 9:  93%|█████████▎| 1860/2000 [01:25<00:06, 21.85it/s]

Epoch 9:  93%|█████████▎| 1863/2000 [01:25<00:06, 21.84it/s]

Epoch 9:  93%|█████████▎| 1866/2000 [01:25<00:06, 21.85it/s]

Epoch 9:  93%|█████████▎| 1869/2000 [01:25<00:05, 21.83it/s]

Epoch 9:  94%|█████████▎| 1872/2000 [01:25<00:05, 21.83it/s]

Epoch 9:  94%|█████████▍| 1875/2000 [01:25<00:05, 21.82it/s]

Epoch 9:  94%|█████████▍| 1878/2000 [01:26<00:05, 21.82it/s]

Epoch 9:  94%|█████████▍| 1881/2000 [01:26<00:05, 21.83it/s]

Epoch 9:  94%|█████████▍| 1884/2000 [01:26<00:05, 21.84it/s]

Epoch 9:  94%|█████████▍| 1887/2000 [01:26<00:05, 21.84it/s]

Epoch 9:  94%|█████████▍| 1890/2000 [01:26<00:05, 21.83it/s]

Epoch 9:  95%|█████████▍| 1893/2000 [01:26<00:04, 21.84it/s]

Epoch 9:  95%|█████████▍| 1896/2000 [01:26<00:04, 21.84it/s]

Epoch 9:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.83it/s]

Epoch 9:  95%|█████████▌| 1902/2000 [01:27<00:04, 21.84it/s]

Epoch 9:  95%|█████████▌| 1905/2000 [01:27<00:04, 21.84it/s]

Epoch 9:  95%|█████████▌| 1908/2000 [01:27<00:04, 21.84it/s]

Epoch 9:  96%|█████████▌| 1911/2000 [01:27<00:04, 21.85it/s]

Epoch 9:  96%|█████████▌| 1914/2000 [01:27<00:03, 21.85it/s]

Epoch 9:  96%|█████████▌| 1917/2000 [01:27<00:03, 21.84it/s]

Epoch 9:  96%|█████████▌| 1920/2000 [01:27<00:03, 21.85it/s]

Epoch 9:  96%|█████████▌| 1923/2000 [01:28<00:03, 21.83it/s]

Epoch 9:  96%|█████████▋| 1926/2000 [01:28<00:03, 21.84it/s]

Epoch 9:  96%|█████████▋| 1929/2000 [01:28<00:03, 21.83it/s]

Epoch 9:  97%|█████████▋| 1932/2000 [01:28<00:03, 21.83it/s]

Epoch 9:  97%|█████████▋| 1935/2000 [01:28<00:02, 21.83it/s]

Epoch 9:  97%|█████████▋| 1938/2000 [01:28<00:02, 21.83it/s]

Epoch 9:  97%|█████████▋| 1941/2000 [01:28<00:02, 21.83it/s]

Epoch 9:  97%|█████████▋| 1944/2000 [01:29<00:02, 21.81it/s]

Epoch 9:  97%|█████████▋| 1947/2000 [01:29<00:02, 21.82it/s]

Epoch 9:  98%|█████████▊| 1950/2000 [01:29<00:02, 21.81it/s]

Epoch 9:  98%|█████████▊| 1953/2000 [01:29<00:02, 21.82it/s]

Epoch 9:  98%|█████████▊| 1956/2000 [01:29<00:02, 21.83it/s]

Epoch 9:  98%|█████████▊| 1959/2000 [01:29<00:01, 21.82it/s]

Epoch 9:  98%|█████████▊| 1962/2000 [01:29<00:01, 21.82it/s]

Epoch 9:  98%|█████████▊| 1965/2000 [01:30<00:01, 21.83it/s]

Epoch 9:  98%|█████████▊| 1968/2000 [01:30<00:01, 21.84it/s]

Epoch 9:  99%|█████████▊| 1971/2000 [01:30<00:01, 21.84it/s]

Epoch 9:  99%|█████████▊| 1974/2000 [01:30<00:01, 21.83it/s]

Epoch 9:  99%|█████████▉| 1977/2000 [01:30<00:01, 21.83it/s]

Epoch 9:  99%|█████████▉| 1980/2000 [01:30<00:00, 21.83it/s]

Epoch 9:  99%|█████████▉| 1983/2000 [01:30<00:00, 21.84it/s]

Epoch 9:  99%|█████████▉| 1986/2000 [01:30<00:00, 21.86it/s]

Epoch 9:  99%|█████████▉| 1989/2000 [01:31<00:00, 21.85it/s]

Epoch 9: 100%|█████████▉| 1992/2000 [01:31<00:00, 21.84it/s]

Epoch 9: 100%|█████████▉| 1995/2000 [01:31<00:00, 21.83it/s]

Epoch 9: 100%|█████████▉| 1998/2000 [01:31<00:00, 21.84it/s]

Epoch 9: loss=0.3853, val_proxy=0.5147

Epoch 10:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 10:   0%|          | 2/2000 [00:00<01:45, 18.94it/s]

Epoch 10:   0%|          | 4/2000 [00:00<01:43, 19.19it/s]

Epoch 10:   0%|          | 6/2000 [00:00<01:43, 19.29it/s]

Epoch 10:   0%|          | 8/2000 [00:00<01:43, 19.32it/s]

Epoch 10:   0%|          | 10/2000 [00:00<01:42, 19.35it/s]

Epoch 10:   1%|          | 13/2000 [00:00<01:38, 20.14it/s]

Epoch 10:   1%|          | 16/2000 [00:00<01:35, 20.68it/s]

Epoch 10:   1%|          | 19/2000 [00:00<01:34, 21.01it/s]

Epoch 10:   1%|          | 22/2000 [00:01<01:33, 21.07it/s]

Epoch 10:   1%|▏         | 25/2000 [00:01<01:33, 21.22it/s]

Epoch 10:   1%|▏         | 28/2000 [00:01<01:32, 21.34it/s]

Epoch 10:   2%|▏         | 31/2000 [00:01<01:31, 21.43it/s]

Epoch 10:   2%|▏         | 34/2000 [00:01<01:31, 21.49it/s]

Epoch 10:   2%|▏         | 37/2000 [00:01<01:31, 21.52it/s]

Epoch 10:   2%|▏         | 40/2000 [00:01<01:30, 21.54it/s]

Epoch 10:   2%|▏         | 43/2000 [00:02<01:30, 21.57it/s]

Epoch 10:   2%|▏         | 46/2000 [00:02<01:30, 21.59it/s]

Epoch 10:   2%|▏         | 49/2000 [00:02<01:30, 21.59it/s]

Epoch 10:   3%|▎         | 52/2000 [00:02<01:30, 21.60it/s]

Epoch 10:   3%|▎         | 55/2000 [00:02<01:30, 21.59it/s]

Epoch 10:   3%|▎         | 58/2000 [00:02<01:29, 21.60it/s]

Epoch 10:   3%|▎         | 61/2000 [00:02<01:29, 21.59it/s]

Epoch 10:   3%|▎         | 64/2000 [00:03<01:29, 21.59it/s]

Epoch 10:   3%|▎         | 67/2000 [00:03<01:29, 21.61it/s]

Epoch 10:   4%|▎         | 70/2000 [00:03<01:29, 21.61it/s]

Epoch 10:   4%|▎         | 73/2000 [00:03<01:29, 21.63it/s]

Epoch 10:   4%|▍         | 76/2000 [00:03<01:29, 21.61it/s]

Epoch 10:   4%|▍         | 79/2000 [00:03<01:28, 21.61it/s]

Epoch 10:   4%|▍         | 82/2000 [00:03<01:28, 21.61it/s]

Epoch 10:   4%|▍         | 85/2000 [00:03<01:28, 21.63it/s]

Epoch 10:   4%|▍         | 88/2000 [00:04<01:28, 21.62it/s]

Epoch 10:   5%|▍         | 91/2000 [00:04<01:28, 21.61it/s]

Epoch 10:   5%|▍         | 94/2000 [00:04<01:28, 21.61it/s]

Epoch 10:   5%|▍         | 97/2000 [00:04<01:28, 21.61it/s]

Epoch 10:   5%|▌         | 100/2000 [00:04<01:27, 21.62it/s]

Epoch 10:   5%|▌         | 103/2000 [00:04<01:27, 21.61it/s]

Epoch 10:   5%|▌         | 106/2000 [00:04<01:27, 21.62it/s]

Epoch 10:   5%|▌         | 109/2000 [00:05<01:27, 21.63it/s]

Epoch 10:   6%|▌         | 112/2000 [00:05<01:27, 21.63it/s]

Epoch 10:   6%|▌         | 115/2000 [00:05<01:27, 21.63it/s]

Epoch 10:   6%|▌         | 118/2000 [00:05<01:27, 21.63it/s]

Epoch 10:   6%|▌         | 121/2000 [00:05<01:26, 21.64it/s]

Epoch 10:   6%|▌         | 124/2000 [00:05<01:26, 21.64it/s]

Epoch 10:   6%|▋         | 127/2000 [00:05<01:26, 21.62it/s]

Epoch 10:   6%|▋         | 130/2000 [00:06<01:26, 21.62it/s]

Epoch 10:   7%|▋         | 133/2000 [00:06<01:26, 21.62it/s]

Epoch 10:   7%|▋         | 136/2000 [00:06<01:26, 21.62it/s]

Epoch 10:   7%|▋         | 139/2000 [00:06<01:26, 21.62it/s]

Epoch 10:   7%|▋         | 142/2000 [00:06<01:25, 21.62it/s]

Epoch 10:   7%|▋         | 145/2000 [00:06<01:25, 21.62it/s]

Epoch 10:   7%|▋         | 148/2000 [00:06<01:25, 21.63it/s]

Epoch 10:   8%|▊         | 151/2000 [00:07<01:25, 21.64it/s]

Epoch 10:   8%|▊         | 154/2000 [00:07<01:25, 21.63it/s]

Epoch 10:   8%|▊         | 157/2000 [00:07<01:25, 21.63it/s]

Epoch 10:   8%|▊         | 160/2000 [00:07<01:25, 21.63it/s]

Epoch 10:   8%|▊         | 163/2000 [00:07<01:24, 21.63it/s]

Epoch 10:   8%|▊         | 166/2000 [00:07<01:24, 21.62it/s]

Epoch 10:   8%|▊         | 169/2000 [00:07<01:24, 21.63it/s]

Epoch 10:   9%|▊         | 172/2000 [00:08<01:24, 21.63it/s]

Epoch 10:   9%|▉         | 175/2000 [00:08<01:24, 21.64it/s]

Epoch 10:   9%|▉         | 178/2000 [00:08<01:24, 21.63it/s]

Epoch 10:   9%|▉         | 181/2000 [00:08<01:24, 21.62it/s]

Epoch 10:   9%|▉         | 184/2000 [00:08<01:24, 21.57it/s]

Epoch 10:   9%|▉         | 187/2000 [00:08<01:23, 21.60it/s]

Epoch 10:  10%|▉         | 190/2000 [00:08<01:23, 21.63it/s]

Epoch 10:  10%|▉         | 193/2000 [00:08<01:23, 21.64it/s]

Epoch 10:  10%|▉         | 196/2000 [00:09<01:23, 21.65it/s]

Epoch 10:  10%|▉         | 199/2000 [00:09<01:23, 21.65it/s]

Epoch 10:  10%|█         | 202/2000 [00:09<01:23, 21.65it/s]

Epoch 10:  10%|█         | 205/2000 [00:09<01:22, 21.65it/s]

Epoch 10:  10%|█         | 208/2000 [00:09<01:22, 21.64it/s]

Epoch 10:  11%|█         | 211/2000 [00:09<01:22, 21.58it/s]

Epoch 10:  11%|█         | 214/2000 [00:09<01:22, 21.59it/s]

Epoch 10:  11%|█         | 217/2000 [00:10<01:22, 21.60it/s]

Epoch 10:  11%|█         | 220/2000 [00:10<01:22, 21.62it/s]

Epoch 10:  11%|█         | 223/2000 [00:10<01:22, 21.61it/s]

Epoch 10:  11%|█▏        | 226/2000 [00:10<01:22, 21.62it/s]

Epoch 10:  11%|█▏        | 229/2000 [00:10<01:21, 21.61it/s]

Epoch 10:  12%|█▏        | 232/2000 [00:10<01:21, 21.61it/s]

Epoch 10:  12%|█▏        | 235/2000 [00:10<01:21, 21.61it/s]

Epoch 10:  12%|█▏        | 238/2000 [00:11<01:21, 21.63it/s]

Epoch 10:  12%|█▏        | 241/2000 [00:11<01:21, 21.62it/s]

Epoch 10:  12%|█▏        | 244/2000 [00:11<01:21, 21.60it/s]

Epoch 10:  12%|█▏        | 247/2000 [00:11<01:21, 21.61it/s]

Epoch 10:  12%|█▎        | 250/2000 [00:11<01:20, 21.61it/s]

Epoch 10:  13%|█▎        | 253/2000 [00:11<01:21, 21.44it/s]

Epoch 10:  13%|█▎        | 256/2000 [00:11<01:23, 20.87it/s]

Epoch 10:  13%|█▎        | 259/2000 [00:12<01:23, 20.89it/s]

Epoch 10:  13%|█▎        | 262/2000 [00:12<01:22, 21.06it/s]

Epoch 10:  13%|█▎        | 265/2000 [00:12<01:21, 21.19it/s]

Epoch 10:  13%|█▎        | 268/2000 [00:12<01:21, 21.33it/s]

Epoch 10:  14%|█▎        | 271/2000 [00:12<01:20, 21.42it/s]

Epoch 10:  14%|█▎        | 274/2000 [00:12<01:20, 21.48it/s]

Epoch 10:  14%|█▍        | 277/2000 [00:12<01:20, 21.51it/s]

Epoch 10:  14%|█▍        | 280/2000 [00:13<01:19, 21.54it/s]

Epoch 10:  14%|█▍        | 283/2000 [00:13<01:19, 21.56it/s]

Epoch 10:  14%|█▍        | 286/2000 [00:13<01:19, 21.58it/s]

Epoch 10:  14%|█▍        | 289/2000 [00:13<01:19, 21.59it/s]

Epoch 10:  15%|█▍        | 292/2000 [00:13<01:19, 21.60it/s]

Epoch 10:  15%|█▍        | 295/2000 [00:13<01:19, 21.37it/s]

Epoch 10:  15%|█▍        | 298/2000 [00:13<01:19, 21.44it/s]

Epoch 10:  15%|█▌        | 301/2000 [00:14<01:19, 21.49it/s]

Epoch 10:  15%|█▌        | 304/2000 [00:14<01:18, 21.52it/s]

Epoch 10:  15%|█▌        | 307/2000 [00:14<01:18, 21.45it/s]

Epoch 10:  16%|█▌        | 310/2000 [00:14<01:18, 21.48it/s]

Epoch 10:  16%|█▌        | 313/2000 [00:14<01:18, 21.53it/s]

Epoch 10:  16%|█▌        | 316/2000 [00:14<01:18, 21.55it/s]

Epoch 10:  16%|█▌        | 319/2000 [00:14<01:17, 21.57it/s]

Epoch 10:  16%|█▌        | 322/2000 [00:14<01:17, 21.60it/s]

Epoch 10:  16%|█▋        | 325/2000 [00:15<01:17, 21.60it/s]

Epoch 10:  16%|█▋        | 328/2000 [00:15<01:17, 21.60it/s]

Epoch 10:  17%|█▋        | 331/2000 [00:15<01:17, 21.63it/s]

Epoch 10:  17%|█▋        | 334/2000 [00:15<01:17, 21.62it/s]

Epoch 10:  17%|█▋        | 337/2000 [00:15<01:16, 21.62it/s]

Epoch 10:  17%|█▋        | 340/2000 [00:15<01:16, 21.62it/s]

Epoch 10:  17%|█▋        | 343/2000 [00:15<01:16, 21.62it/s]

Epoch 10:  17%|█▋        | 346/2000 [00:16<01:16, 21.62it/s]

Epoch 10:  17%|█▋        | 349/2000 [00:16<01:16, 21.62it/s]

Epoch 10:  18%|█▊        | 352/2000 [00:16<01:16, 21.63it/s]

Epoch 10:  18%|█▊        | 355/2000 [00:16<01:16, 21.61it/s]

Epoch 10:  18%|█▊        | 358/2000 [00:16<01:15, 21.61it/s]

Epoch 10:  18%|█▊        | 361/2000 [00:16<01:15, 21.61it/s]

Epoch 10:  18%|█▊        | 364/2000 [00:16<01:15, 21.62it/s]

Epoch 10:  18%|█▊        | 367/2000 [00:17<01:15, 21.62it/s]

Epoch 10:  18%|█▊        | 370/2000 [00:17<01:15, 21.62it/s]

Epoch 10:  19%|█▊        | 373/2000 [00:17<01:15, 21.62it/s]

Epoch 10:  19%|█▉        | 376/2000 [00:17<01:15, 21.61it/s]

Epoch 10:  19%|█▉        | 379/2000 [00:17<01:15, 21.60it/s]

Epoch 10:  19%|█▉        | 382/2000 [00:17<01:14, 21.59it/s]

Epoch 10:  19%|█▉        | 385/2000 [00:17<01:14, 21.59it/s]

Epoch 10:  19%|█▉        | 388/2000 [00:18<01:14, 21.59it/s]

Epoch 10:  20%|█▉        | 391/2000 [00:18<01:14, 21.60it/s]

Epoch 10:  20%|█▉        | 394/2000 [00:18<01:14, 21.61it/s]

Epoch 10:  20%|█▉        | 397/2000 [00:18<01:14, 21.61it/s]

Epoch 10:  20%|██        | 400/2000 [00:18<01:13, 21.62it/s]

Epoch 10:  20%|██        | 403/2000 [00:18<01:13, 21.62it/s]

Epoch 10:  20%|██        | 406/2000 [00:18<01:13, 21.63it/s]

Epoch 10:  20%|██        | 409/2000 [00:19<01:13, 21.61it/s]

Epoch 10:  21%|██        | 412/2000 [00:19<01:13, 21.62it/s]

Epoch 10:  21%|██        | 415/2000 [00:19<01:13, 21.63it/s]

Epoch 10:  21%|██        | 418/2000 [00:19<01:13, 21.62it/s]

Epoch 10:  21%|██        | 421/2000 [00:19<01:13, 21.63it/s]

Epoch 10:  21%|██        | 424/2000 [00:19<01:12, 21.62it/s]

Epoch 10:  21%|██▏       | 427/2000 [00:19<01:12, 21.60it/s]

Epoch 10:  22%|██▏       | 430/2000 [00:19<01:12, 21.59it/s]

Epoch 10:  22%|██▏       | 433/2000 [00:20<01:12, 21.57it/s]

Epoch 10:  22%|██▏       | 436/2000 [00:20<01:12, 21.60it/s]

Epoch 10:  22%|██▏       | 439/2000 [00:20<01:12, 21.60it/s]

Epoch 10:  22%|██▏       | 442/2000 [00:20<01:12, 21.60it/s]

Epoch 10:  22%|██▏       | 445/2000 [00:20<01:11, 21.60it/s]

Epoch 10:  22%|██▏       | 448/2000 [00:20<01:11, 21.60it/s]

Epoch 10:  23%|██▎       | 451/2000 [00:20<01:11, 21.61it/s]

Epoch 10:  23%|██▎       | 454/2000 [00:21<01:11, 21.61it/s]

Epoch 10:  23%|██▎       | 457/2000 [00:21<01:11, 21.60it/s]

Epoch 10:  23%|██▎       | 460/2000 [00:21<01:11, 21.61it/s]

Epoch 10:  23%|██▎       | 463/2000 [00:21<01:11, 21.62it/s]

Epoch 10:  23%|██▎       | 466/2000 [00:21<01:10, 21.62it/s]

Epoch 10:  23%|██▎       | 469/2000 [00:21<01:10, 21.63it/s]

Epoch 10:  24%|██▎       | 472/2000 [00:21<01:10, 21.63it/s]

Epoch 10:  24%|██▍       | 475/2000 [00:22<01:10, 21.64it/s]

Epoch 10:  24%|██▍       | 478/2000 [00:22<01:10, 21.63it/s]

Epoch 10:  24%|██▍       | 481/2000 [00:22<01:10, 21.62it/s]

Epoch 10:  24%|██▍       | 484/2000 [00:22<01:10, 21.63it/s]

Epoch 10:  24%|██▍       | 487/2000 [00:22<01:09, 21.62it/s]

Epoch 10:  24%|██▍       | 490/2000 [00:22<01:09, 21.63it/s]

Epoch 10:  25%|██▍       | 493/2000 [00:22<01:09, 21.57it/s]

Epoch 10:  25%|██▍       | 496/2000 [00:23<01:09, 21.57it/s]

Epoch 10:  25%|██▍       | 499/2000 [00:23<01:09, 21.58it/s]

Epoch 10:  25%|██▌       | 502/2000 [00:23<01:09, 21.60it/s]

Epoch 10:  25%|██▌       | 505/2000 [00:23<01:09, 21.61it/s]

Epoch 10:  25%|██▌       | 508/2000 [00:23<01:09, 21.62it/s]

Epoch 10:  26%|██▌       | 511/2000 [00:23<01:08, 21.62it/s]

Epoch 10:  26%|██▌       | 514/2000 [00:23<01:08, 21.60it/s]

Epoch 10:  26%|██▌       | 517/2000 [00:24<01:08, 21.61it/s]

Epoch 10:  26%|██▌       | 520/2000 [00:24<01:08, 21.62it/s]

Epoch 10:  26%|██▌       | 523/2000 [00:24<01:08, 21.61it/s]

Epoch 10:  26%|██▋       | 526/2000 [00:24<01:08, 21.62it/s]

Epoch 10:  26%|██▋       | 529/2000 [00:24<01:08, 21.63it/s]

Epoch 10:  27%|██▋       | 532/2000 [00:24<01:07, 21.63it/s]

Epoch 10:  27%|██▋       | 535/2000 [00:24<01:07, 21.56it/s]

Epoch 10:  27%|██▋       | 538/2000 [00:24<01:07, 21.56it/s]

Epoch 10:  27%|██▋       | 541/2000 [00:25<01:07, 21.57it/s]

Epoch 10:  27%|██▋       | 544/2000 [00:25<01:07, 21.59it/s]

Epoch 10:  27%|██▋       | 547/2000 [00:25<01:07, 21.60it/s]

Epoch 10:  28%|██▊       | 550/2000 [00:25<01:07, 21.61it/s]

Epoch 10:  28%|██▊       | 553/2000 [00:25<01:06, 21.61it/s]

Epoch 10:  28%|██▊       | 556/2000 [00:25<01:06, 21.59it/s]

Epoch 10:  28%|██▊       | 559/2000 [00:25<01:06, 21.59it/s]

Epoch 10:  28%|██▊       | 562/2000 [00:26<01:06, 21.60it/s]

Epoch 10:  28%|██▊       | 565/2000 [00:26<01:06, 21.59it/s]

Epoch 10:  28%|██▊       | 568/2000 [00:26<01:06, 21.59it/s]

Epoch 10:  29%|██▊       | 571/2000 [00:26<01:06, 21.60it/s]

Epoch 10:  29%|██▊       | 574/2000 [00:26<01:06, 21.59it/s]

Epoch 10:  29%|██▉       | 577/2000 [00:26<01:05, 21.59it/s]

Epoch 10:  29%|██▉       | 580/2000 [00:26<01:05, 21.61it/s]

Epoch 10:  29%|██▉       | 583/2000 [00:27<01:05, 21.62it/s]

Epoch 10:  29%|██▉       | 586/2000 [00:27<01:05, 21.62it/s]

Epoch 10:  29%|██▉       | 589/2000 [00:27<01:05, 21.61it/s]

Epoch 10:  30%|██▉       | 592/2000 [00:27<01:05, 21.62it/s]

Epoch 10:  30%|██▉       | 595/2000 [00:27<01:04, 21.63it/s]

Epoch 10:  30%|██▉       | 598/2000 [00:27<01:04, 21.63it/s]

Epoch 10:  30%|███       | 601/2000 [00:27<01:04, 21.63it/s]

Epoch 10:  30%|███       | 604/2000 [00:28<01:04, 21.64it/s]

Epoch 10:  30%|███       | 607/2000 [00:28<01:04, 21.65it/s]

Epoch 10:  30%|███       | 610/2000 [00:28<01:04, 21.65it/s]

Epoch 10:  31%|███       | 613/2000 [00:28<01:04, 21.65it/s]

Epoch 10:  31%|███       | 616/2000 [00:28<01:03, 21.65it/s]

Epoch 10:  31%|███       | 619/2000 [00:28<01:03, 21.64it/s]

Epoch 10:  31%|███       | 622/2000 [00:28<01:03, 21.65it/s]

Epoch 10:  31%|███▏      | 625/2000 [00:29<01:03, 21.65it/s]

Epoch 10:  31%|███▏      | 628/2000 [00:29<01:03, 21.64it/s]

Epoch 10:  32%|███▏      | 631/2000 [00:29<01:03, 21.64it/s]

Epoch 10:  32%|███▏      | 634/2000 [00:29<01:03, 21.65it/s]

Epoch 10:  32%|███▏      | 637/2000 [00:29<01:02, 21.64it/s]

Epoch 10:  32%|███▏      | 640/2000 [00:29<01:02, 21.64it/s]

Epoch 10:  32%|███▏      | 643/2000 [00:29<01:02, 21.64it/s]

Epoch 10:  32%|███▏      | 646/2000 [00:29<01:02, 21.63it/s]

Epoch 10:  32%|███▏      | 649/2000 [00:30<01:02, 21.63it/s]

Epoch 10:  33%|███▎      | 652/2000 [00:30<01:02, 21.63it/s]

Epoch 10:  33%|███▎      | 655/2000 [00:30<01:02, 21.63it/s]

Epoch 10:  33%|███▎      | 658/2000 [00:30<01:02, 21.63it/s]

Epoch 10:  33%|███▎      | 661/2000 [00:30<01:01, 21.64it/s]

Epoch 10:  33%|███▎      | 664/2000 [00:30<01:01, 21.65it/s]

Epoch 10:  33%|███▎      | 667/2000 [00:30<01:01, 21.64it/s]

Epoch 10:  34%|███▎      | 670/2000 [00:31<01:01, 21.66it/s]

Epoch 10:  34%|███▎      | 673/2000 [00:31<01:01, 21.65it/s]

Epoch 10:  34%|███▍      | 676/2000 [00:31<01:01, 21.65it/s]

Epoch 10:  34%|███▍      | 679/2000 [00:31<01:01, 21.65it/s]

Epoch 10:  34%|███▍      | 682/2000 [00:31<01:00, 21.64it/s]

Epoch 10:  34%|███▍      | 685/2000 [00:31<01:00, 21.63it/s]

Epoch 10:  34%|███▍      | 688/2000 [00:31<01:00, 21.63it/s]

Epoch 10:  35%|███▍      | 691/2000 [00:32<01:00, 21.62it/s]

Epoch 10:  35%|███▍      | 694/2000 [00:32<01:00, 21.62it/s]

Epoch 10:  35%|███▍      | 697/2000 [00:32<01:00, 21.63it/s]

Epoch 10:  35%|███▌      | 700/2000 [00:32<01:00, 21.63it/s]

Epoch 10:  35%|███▌      | 703/2000 [00:32<00:59, 21.63it/s]

Epoch 10:  35%|███▌      | 706/2000 [00:32<00:59, 21.64it/s]

Epoch 10:  35%|███▌      | 709/2000 [00:32<00:59, 21.64it/s]

Epoch 10:  36%|███▌      | 712/2000 [00:33<00:59, 21.62it/s]

Epoch 10:  36%|███▌      | 715/2000 [00:33<00:59, 21.62it/s]

Epoch 10:  36%|███▌      | 718/2000 [00:33<00:59, 21.62it/s]

Epoch 10:  36%|███▌      | 721/2000 [00:33<00:59, 21.61it/s]

Epoch 10:  36%|███▌      | 724/2000 [00:33<00:58, 21.63it/s]

Epoch 10:  36%|███▋      | 727/2000 [00:33<00:58, 21.64it/s]

Epoch 10:  36%|███▋      | 730/2000 [00:33<00:58, 21.64it/s]

Epoch 10:  37%|███▋      | 733/2000 [00:33<00:58, 21.63it/s]

Epoch 10:  37%|███▋      | 736/2000 [00:34<00:58, 21.64it/s]

Epoch 10:  37%|███▋      | 739/2000 [00:34<00:58, 21.62it/s]

Epoch 10:  37%|███▋      | 742/2000 [00:34<00:58, 21.62it/s]

Epoch 10:  37%|███▋      | 745/2000 [00:34<00:58, 21.57it/s]

Epoch 10:  37%|███▋      | 748/2000 [00:34<00:58, 21.58it/s]

Epoch 10:  38%|███▊      | 751/2000 [00:34<00:57, 21.59it/s]

Epoch 10:  38%|███▊      | 754/2000 [00:34<00:57, 21.63it/s]

Epoch 10:  38%|███▊      | 757/2000 [00:35<00:57, 21.62it/s]

Epoch 10:  38%|███▊      | 760/2000 [00:35<00:57, 21.62it/s]

Epoch 10:  38%|███▊      | 763/2000 [00:35<00:57, 21.62it/s]

Epoch 10:  38%|███▊      | 766/2000 [00:35<00:57, 21.62it/s]

Epoch 10:  38%|███▊      | 769/2000 [00:35<00:56, 21.62it/s]

Epoch 10:  39%|███▊      | 772/2000 [00:35<00:56, 21.63it/s]

Epoch 10:  39%|███▉      | 775/2000 [00:35<00:56, 21.63it/s]

Epoch 10:  39%|███▉      | 778/2000 [00:36<00:56, 21.62it/s]

Epoch 10:  39%|███▉      | 781/2000 [00:36<00:56, 21.63it/s]

Epoch 10:  39%|███▉      | 784/2000 [00:36<00:56, 21.63it/s]

Epoch 10:  39%|███▉      | 787/2000 [00:36<00:56, 21.61it/s]

Epoch 10:  40%|███▉      | 790/2000 [00:36<00:55, 21.62it/s]

Epoch 10:  40%|███▉      | 793/2000 [00:36<00:55, 21.63it/s]

Epoch 10:  40%|███▉      | 796/2000 [00:36<00:55, 21.63it/s]

Epoch 10:  40%|███▉      | 799/2000 [00:37<00:55, 21.63it/s]

Epoch 10:  40%|████      | 802/2000 [00:37<00:55, 21.64it/s]

Epoch 10:  40%|████      | 805/2000 [00:37<00:55, 21.63it/s]

Epoch 10:  40%|████      | 808/2000 [00:37<00:55, 21.62it/s]

Epoch 10:  41%|████      | 811/2000 [00:37<00:54, 21.63it/s]

Epoch 10:  41%|████      | 814/2000 [00:37<00:54, 21.62it/s]

Epoch 10:  41%|████      | 817/2000 [00:37<00:54, 21.63it/s]

Epoch 10:  41%|████      | 820/2000 [00:38<00:54, 21.63it/s]

Epoch 10:  41%|████      | 823/2000 [00:38<00:54, 21.63it/s]

Epoch 10:  41%|████▏     | 826/2000 [00:38<00:54, 21.63it/s]

Epoch 10:  41%|████▏     | 829/2000 [00:38<00:54, 21.62it/s]

Epoch 10:  42%|████▏     | 832/2000 [00:38<00:53, 21.63it/s]

Epoch 10:  42%|████▏     | 835/2000 [00:38<00:53, 21.64it/s]

Epoch 10:  42%|████▏     | 838/2000 [00:38<00:53, 21.64it/s]

Epoch 10:  42%|████▏     | 841/2000 [00:38<00:53, 21.64it/s]

Epoch 10:  42%|████▏     | 844/2000 [00:39<00:53, 21.64it/s]

Epoch 10:  42%|████▏     | 847/2000 [00:39<00:53, 21.64it/s]

Epoch 10:  42%|████▎     | 850/2000 [00:39<00:53, 21.64it/s]

Epoch 10:  43%|████▎     | 853/2000 [00:39<00:53, 21.63it/s]

Epoch 10:  43%|████▎     | 856/2000 [00:39<00:52, 21.61it/s]

Epoch 10:  43%|████▎     | 859/2000 [00:39<00:52, 21.62it/s]

Epoch 10:  43%|████▎     | 862/2000 [00:39<00:52, 21.64it/s]

Epoch 10:  43%|████▎     | 865/2000 [00:40<00:52, 21.65it/s]

Epoch 10:  43%|████▎     | 868/2000 [00:40<00:52, 21.64it/s]

Epoch 10:  44%|████▎     | 871/2000 [00:40<00:52, 21.61it/s]

Epoch 10:  44%|████▎     | 874/2000 [00:40<00:52, 21.62it/s]

Epoch 10:  44%|████▍     | 877/2000 [00:40<00:51, 21.62it/s]

Epoch 10:  44%|████▍     | 880/2000 [00:40<00:51, 21.63it/s]

Epoch 10:  44%|████▍     | 883/2000 [00:40<00:51, 21.63it/s]

Epoch 10:  44%|████▍     | 886/2000 [00:41<00:51, 21.64it/s]

Epoch 10:  44%|████▍     | 889/2000 [00:41<00:51, 21.63it/s]

Epoch 10:  45%|████▍     | 892/2000 [00:41<00:51, 21.64it/s]

Epoch 10:  45%|████▍     | 895/2000 [00:41<00:51, 21.62it/s]

Epoch 10:  45%|████▍     | 898/2000 [00:41<00:50, 21.62it/s]

Epoch 10:  45%|████▌     | 901/2000 [00:41<00:50, 21.62it/s]

Epoch 10:  45%|████▌     | 904/2000 [00:41<00:50, 21.56it/s]

Epoch 10:  45%|████▌     | 907/2000 [00:42<00:50, 21.59it/s]

Epoch 10:  46%|████▌     | 910/2000 [00:42<00:50, 21.60it/s]

Epoch 10:  46%|████▌     | 913/2000 [00:42<00:50, 21.60it/s]

Epoch 10:  46%|████▌     | 916/2000 [00:42<00:50, 21.62it/s]

Epoch 10:  46%|████▌     | 919/2000 [00:42<00:50, 21.62it/s]

Epoch 10:  46%|████▌     | 922/2000 [00:42<00:49, 21.61it/s]

Epoch 10:  46%|████▋     | 925/2000 [00:42<00:50, 21.46it/s]

Epoch 10:  46%|████▋     | 928/2000 [00:43<00:49, 21.52it/s]

Epoch 10:  47%|████▋     | 931/2000 [00:43<00:49, 21.55it/s]

Epoch 10:  47%|████▋     | 934/2000 [00:43<00:49, 21.59it/s]

Epoch 10:  47%|████▋     | 937/2000 [00:43<00:49, 21.59it/s]

Epoch 10:  47%|████▋     | 940/2000 [00:43<00:49, 21.61it/s]

Epoch 10:  47%|████▋     | 943/2000 [00:43<00:48, 21.62it/s]

Epoch 10:  47%|████▋     | 946/2000 [00:43<00:48, 21.60it/s]

Epoch 10:  47%|████▋     | 949/2000 [00:43<00:48, 21.58it/s]

Epoch 10:  48%|████▊     | 952/2000 [00:44<00:48, 21.60it/s]

Epoch 10:  48%|████▊     | 955/2000 [00:44<00:48, 21.61it/s]

Epoch 10:  48%|████▊     | 958/2000 [00:44<00:48, 21.61it/s]

Epoch 10:  48%|████▊     | 961/2000 [00:44<00:48, 21.45it/s]

Epoch 10:  48%|████▊     | 964/2000 [00:44<00:49, 20.88it/s]

Epoch 10:  48%|████▊     | 967/2000 [00:44<00:49, 20.92it/s]

Epoch 10:  48%|████▊     | 970/2000 [00:44<00:48, 21.09it/s]

Epoch 10:  49%|████▊     | 973/2000 [00:45<00:48, 21.22it/s]

Epoch 10:  49%|████▉     | 976/2000 [00:45<00:47, 21.35it/s]

Epoch 10:  49%|████▉     | 979/2000 [00:45<00:47, 21.45it/s]

Epoch 10:  49%|████▉     | 982/2000 [00:45<00:47, 21.49it/s]

Epoch 10:  49%|████▉     | 985/2000 [00:45<00:47, 21.53it/s]

Epoch 10:  49%|████▉     | 988/2000 [00:45<00:46, 21.54it/s]

Epoch 10:  50%|████▉     | 991/2000 [00:45<00:46, 21.57it/s]

Epoch 10:  50%|████▉     | 994/2000 [00:46<00:46, 21.59it/s]

Epoch 10:  50%|████▉     | 997/2000 [00:46<00:46, 21.61it/s]

Epoch 10:  50%|█████     | 1000/2000 [00:46<00:46, 21.61it/s]

Epoch 10:  50%|█████     | 1003/2000 [00:46<00:46, 21.62it/s]

Epoch 10:  50%|█████     | 1006/2000 [00:46<00:45, 21.63it/s]

Epoch 10:  50%|█████     | 1009/2000 [00:46<00:45, 21.63it/s]

Epoch 10:  51%|█████     | 1012/2000 [00:46<00:45, 21.64it/s]

Epoch 10:  51%|█████     | 1015/2000 [00:47<00:45, 21.65it/s]

Epoch 10:  51%|█████     | 1018/2000 [00:47<00:45, 21.65it/s]

Epoch 10:  51%|█████     | 1021/2000 [00:47<00:45, 21.65it/s]

Epoch 10:  51%|█████     | 1024/2000 [00:47<00:45, 21.65it/s]

Epoch 10:  51%|█████▏    | 1027/2000 [00:47<00:44, 21.64it/s]

Epoch 10:  52%|█████▏    | 1030/2000 [00:47<00:44, 21.64it/s]

Epoch 10:  52%|█████▏    | 1033/2000 [00:47<00:44, 21.64it/s]

Epoch 10:  52%|█████▏    | 1036/2000 [00:48<00:44, 21.64it/s]

Epoch 10:  52%|█████▏    | 1039/2000 [00:48<00:44, 21.64it/s]

Epoch 10:  52%|█████▏    | 1042/2000 [00:48<00:44, 21.63it/s]

Epoch 10:  52%|█████▏    | 1045/2000 [00:48<00:44, 21.63it/s]

Epoch 10:  52%|█████▏    | 1048/2000 [00:48<00:43, 21.64it/s]

Epoch 10:  53%|█████▎    | 1051/2000 [00:48<00:43, 21.62it/s]

Epoch 10:  53%|█████▎    | 1054/2000 [00:48<00:43, 21.62it/s]

Epoch 10:  53%|█████▎    | 1057/2000 [00:49<00:43, 21.63it/s]

Epoch 10:  53%|█████▎    | 1060/2000 [00:49<00:43, 21.63it/s]

Epoch 10:  53%|█████▎    | 1063/2000 [00:49<00:43, 21.63it/s]

Epoch 10:  53%|█████▎    | 1066/2000 [00:49<00:43, 21.63it/s]

Epoch 10:  53%|█████▎    | 1069/2000 [00:49<00:43, 21.62it/s]

Epoch 10:  54%|█████▎    | 1072/2000 [00:49<00:42, 21.63it/s]

Epoch 10:  54%|█████▍    | 1075/2000 [00:49<00:42, 21.62it/s]

Epoch 10:  54%|█████▍    | 1078/2000 [00:49<00:42, 21.63it/s]

Epoch 10:  54%|█████▍    | 1081/2000 [00:50<00:42, 21.63it/s]

Epoch 10:  54%|█████▍    | 1084/2000 [00:50<00:42, 21.61it/s]

Epoch 10:  54%|█████▍    | 1087/2000 [00:50<00:42, 21.61it/s]

Epoch 10:  55%|█████▍    | 1090/2000 [00:50<00:42, 21.62it/s]

Epoch 10:  55%|█████▍    | 1093/2000 [00:50<00:41, 21.63it/s]

Epoch 10:  55%|█████▍    | 1096/2000 [00:50<00:41, 21.65it/s]

Epoch 10:  55%|█████▍    | 1099/2000 [00:50<00:41, 21.64it/s]

Epoch 10:  55%|█████▌    | 1102/2000 [00:51<00:41, 21.66it/s]

Epoch 10:  55%|█████▌    | 1105/2000 [00:51<00:41, 21.66it/s]

Epoch 10:  55%|█████▌    | 1108/2000 [00:51<00:41, 21.64it/s]

Epoch 10:  56%|█████▌    | 1111/2000 [00:51<00:41, 21.65it/s]

Epoch 10:  56%|█████▌    | 1114/2000 [00:51<00:40, 21.65it/s]

Epoch 10:  56%|█████▌    | 1117/2000 [00:51<00:40, 21.63it/s]

Epoch 10:  56%|█████▌    | 1120/2000 [00:51<00:40, 21.62it/s]

Epoch 10:  56%|█████▌    | 1123/2000 [00:52<00:40, 21.62it/s]

Epoch 10:  56%|█████▋    | 1126/2000 [00:52<00:40, 21.61it/s]

Epoch 10:  56%|█████▋    | 1129/2000 [00:52<00:40, 21.61it/s]

Epoch 10:  57%|█████▋    | 1132/2000 [00:52<00:40, 21.62it/s]

Epoch 10:  57%|█████▋    | 1135/2000 [00:52<00:40, 21.62it/s]

Epoch 10:  57%|█████▋    | 1138/2000 [00:52<00:39, 21.62it/s]

Epoch 10:  57%|█████▋    | 1141/2000 [00:52<00:39, 21.62it/s]

Epoch 10:  57%|█████▋    | 1144/2000 [00:53<00:39, 21.63it/s]

Epoch 10:  57%|█████▋    | 1147/2000 [00:53<00:39, 21.62it/s]

Epoch 10:  57%|█████▊    | 1150/2000 [00:53<00:39, 21.61it/s]

Epoch 10:  58%|█████▊    | 1153/2000 [00:53<00:39, 21.63it/s]

Epoch 10:  58%|█████▊    | 1156/2000 [00:53<00:39, 21.62it/s]

Epoch 10:  58%|█████▊    | 1159/2000 [00:53<00:38, 21.63it/s]

Epoch 10:  58%|█████▊    | 1162/2000 [00:53<00:38, 21.63it/s]

Epoch 10:  58%|█████▊    | 1165/2000 [00:54<00:38, 21.64it/s]

Epoch 10:  58%|█████▊    | 1168/2000 [00:54<00:38, 21.65it/s]

Epoch 10:  59%|█████▊    | 1171/2000 [00:54<00:38, 21.65it/s]

Epoch 10:  59%|█████▊    | 1174/2000 [00:54<00:38, 21.65it/s]

Epoch 10:  59%|█████▉    | 1177/2000 [00:54<00:38, 21.66it/s]

Epoch 10:  59%|█████▉    | 1180/2000 [00:54<00:37, 21.64it/s]

Epoch 10:  59%|█████▉    | 1183/2000 [00:54<00:37, 21.64it/s]

Epoch 10:  59%|█████▉    | 1186/2000 [00:54<00:37, 21.65it/s]

Epoch 10:  59%|█████▉    | 1189/2000 [00:55<00:37, 21.64it/s]

Epoch 10:  60%|█████▉    | 1192/2000 [00:55<00:37, 21.64it/s]

Epoch 10:  60%|█████▉    | 1195/2000 [00:55<00:37, 21.64it/s]

Epoch 10:  60%|█████▉    | 1198/2000 [00:55<00:37, 21.64it/s]

Epoch 10:  60%|██████    | 1201/2000 [00:55<00:36, 21.64it/s]

Epoch 10:  60%|██████    | 1204/2000 [00:55<00:36, 21.62it/s]

Epoch 10:  60%|██████    | 1207/2000 [00:55<00:36, 21.62it/s]

Epoch 10:  60%|██████    | 1210/2000 [00:56<00:36, 21.62it/s]

Epoch 10:  61%|██████    | 1213/2000 [00:56<00:36, 21.63it/s]

Epoch 10:  61%|██████    | 1216/2000 [00:56<00:36, 21.63it/s]

Epoch 10:  61%|██████    | 1219/2000 [00:56<00:36, 21.61it/s]

Epoch 10:  61%|██████    | 1222/2000 [00:56<00:36, 21.60it/s]

Epoch 10:  61%|██████▏   | 1225/2000 [00:56<00:35, 21.62it/s]

Epoch 10:  61%|██████▏   | 1228/2000 [00:56<00:35, 21.61it/s]

Epoch 10:  62%|██████▏   | 1231/2000 [00:57<00:35, 21.62it/s]

Epoch 10:  62%|██████▏   | 1234/2000 [00:57<00:35, 21.63it/s]

Epoch 10:  62%|██████▏   | 1237/2000 [00:57<00:35, 21.63it/s]

Epoch 10:  62%|██████▏   | 1240/2000 [00:57<00:35, 21.64it/s]

Epoch 10:  62%|██████▏   | 1243/2000 [00:57<00:34, 21.64it/s]

Epoch 10:  62%|██████▏   | 1246/2000 [00:57<00:34, 21.61it/s]

Epoch 10:  62%|██████▏   | 1249/2000 [00:57<00:34, 21.61it/s]

Epoch 10:  63%|██████▎   | 1252/2000 [00:58<00:34, 21.63it/s]

Epoch 10:  63%|██████▎   | 1255/2000 [00:58<00:34, 21.63it/s]

Epoch 10:  63%|██████▎   | 1258/2000 [00:58<00:34, 21.62it/s]

Epoch 10:  63%|██████▎   | 1261/2000 [00:58<00:34, 21.62it/s]

Epoch 10:  63%|██████▎   | 1264/2000 [00:58<00:34, 21.63it/s]

Epoch 10:  63%|██████▎   | 1267/2000 [00:58<00:33, 21.63it/s]

Epoch 10:  64%|██████▎   | 1270/2000 [00:58<00:33, 21.65it/s]

Epoch 10:  64%|██████▎   | 1273/2000 [00:58<00:33, 21.64it/s]

Epoch 10:  64%|██████▍   | 1276/2000 [00:59<00:33, 21.64it/s]

Epoch 10:  64%|██████▍   | 1279/2000 [00:59<00:33, 21.63it/s]

Epoch 10:  64%|██████▍   | 1282/2000 [00:59<00:33, 21.64it/s]

Epoch 10:  64%|██████▍   | 1285/2000 [00:59<00:33, 21.63it/s]

Epoch 10:  64%|██████▍   | 1288/2000 [00:59<00:32, 21.61it/s]

Epoch 10:  65%|██████▍   | 1291/2000 [00:59<00:32, 21.62it/s]

Epoch 10:  65%|██████▍   | 1294/2000 [00:59<00:32, 21.62it/s]

Epoch 10:  65%|██████▍   | 1297/2000 [01:00<00:32, 21.62it/s]

Epoch 10:  65%|██████▌   | 1300/2000 [01:00<00:32, 21.64it/s]

Epoch 10:  65%|██████▌   | 1303/2000 [01:00<00:32, 21.64it/s]

Epoch 10:  65%|██████▌   | 1306/2000 [01:00<00:32, 21.64it/s]

Epoch 10:  65%|██████▌   | 1309/2000 [01:00<00:31, 21.64it/s]

Epoch 10:  66%|██████▌   | 1312/2000 [01:00<00:31, 21.64it/s]

Epoch 10:  66%|██████▌   | 1315/2000 [01:00<00:31, 21.63it/s]

Epoch 10:  66%|██████▌   | 1318/2000 [01:01<00:31, 21.64it/s]

Epoch 10:  66%|██████▌   | 1321/2000 [01:01<00:31, 21.64it/s]

Epoch 10:  66%|██████▌   | 1324/2000 [01:01<00:31, 21.64it/s]

Epoch 10:  66%|██████▋   | 1327/2000 [01:01<00:31, 21.63it/s]

Epoch 10:  66%|██████▋   | 1330/2000 [01:01<00:30, 21.62it/s]

Epoch 10:  67%|██████▋   | 1333/2000 [01:01<00:30, 21.63it/s]

Epoch 10:  67%|██████▋   | 1336/2000 [01:01<00:30, 21.64it/s]

Epoch 10:  67%|██████▋   | 1339/2000 [01:02<00:30, 21.64it/s]

Epoch 10:  67%|██████▋   | 1342/2000 [01:02<00:30, 21.62it/s]

Epoch 10:  67%|██████▋   | 1345/2000 [01:02<00:30, 21.63it/s]

Epoch 10:  67%|██████▋   | 1348/2000 [01:02<00:30, 21.63it/s]

Epoch 10:  68%|██████▊   | 1351/2000 [01:02<00:29, 21.63it/s]

Epoch 10:  68%|██████▊   | 1354/2000 [01:02<00:29, 21.64it/s]

Epoch 10:  68%|██████▊   | 1357/2000 [01:02<00:29, 21.62it/s]

Epoch 10:  68%|██████▊   | 1360/2000 [01:03<00:29, 21.63it/s]

Epoch 10:  68%|██████▊   | 1363/2000 [01:03<00:29, 21.64it/s]

Epoch 10:  68%|██████▊   | 1366/2000 [01:03<00:29, 21.65it/s]

Epoch 10:  68%|██████▊   | 1369/2000 [01:03<00:29, 21.65it/s]

Epoch 10:  69%|██████▊   | 1372/2000 [01:03<00:29, 21.64it/s]

Epoch 10:  69%|██████▉   | 1375/2000 [01:03<00:28, 21.63it/s]

Epoch 10:  69%|██████▉   | 1378/2000 [01:03<00:28, 21.61it/s]

Epoch 10:  69%|██████▉   | 1381/2000 [01:03<00:28, 21.60it/s]

Epoch 10:  69%|██████▉   | 1384/2000 [01:04<00:28, 21.59it/s]

Epoch 10:  69%|██████▉   | 1387/2000 [01:04<00:28, 21.59it/s]

Epoch 10:  70%|██████▉   | 1390/2000 [01:04<00:28, 21.60it/s]

Epoch 10:  70%|██████▉   | 1393/2000 [01:04<00:28, 21.62it/s]

Epoch 10:  70%|██████▉   | 1396/2000 [01:04<00:27, 21.62it/s]

Epoch 10:  70%|██████▉   | 1399/2000 [01:04<00:27, 21.62it/s]

Epoch 10:  70%|███████   | 1402/2000 [01:04<00:27, 21.61it/s]

Epoch 10:  70%|███████   | 1405/2000 [01:05<00:27, 21.62it/s]

Epoch 10:  70%|███████   | 1408/2000 [01:05<00:27, 21.63it/s]

Epoch 10:  71%|███████   | 1411/2000 [01:05<00:27, 21.64it/s]

Epoch 10:  71%|███████   | 1414/2000 [01:05<00:27, 21.62it/s]

Epoch 10:  71%|███████   | 1417/2000 [01:05<00:26, 21.62it/s]

Epoch 10:  71%|███████   | 1420/2000 [01:05<00:26, 21.62it/s]

Epoch 10:  71%|███████   | 1423/2000 [01:05<00:26, 21.62it/s]

Epoch 10:  71%|███████▏  | 1426/2000 [01:06<00:26, 21.63it/s]

Epoch 10:  71%|███████▏  | 1429/2000 [01:06<00:26, 21.65it/s]

Epoch 10:  72%|███████▏  | 1432/2000 [01:06<00:26, 21.65it/s]

Epoch 10:  72%|███████▏  | 1435/2000 [01:06<00:26, 21.65it/s]

Epoch 10:  72%|███████▏  | 1438/2000 [01:06<00:25, 21.66it/s]

Epoch 10:  72%|███████▏  | 1441/2000 [01:06<00:25, 21.66it/s]

Epoch 10:  72%|███████▏  | 1444/2000 [01:06<00:25, 21.67it/s]

Epoch 10:  72%|███████▏  | 1447/2000 [01:07<00:25, 21.66it/s]

Epoch 10:  72%|███████▎  | 1450/2000 [01:07<00:25, 21.65it/s]

Epoch 10:  73%|███████▎  | 1453/2000 [01:07<00:25, 21.65it/s]

Epoch 10:  73%|███████▎  | 1456/2000 [01:07<00:25, 21.64it/s]

Epoch 10:  73%|███████▎  | 1459/2000 [01:07<00:24, 21.65it/s]

Epoch 10:  73%|███████▎  | 1462/2000 [01:07<00:24, 21.66it/s]

Epoch 10:  73%|███████▎  | 1465/2000 [01:07<00:24, 21.65it/s]

Epoch 10:  73%|███████▎  | 1468/2000 [01:08<00:24, 21.64it/s]

Epoch 10:  74%|███████▎  | 1471/2000 [01:08<00:24, 21.63it/s]

Epoch 10:  74%|███████▎  | 1474/2000 [01:08<00:24, 21.63it/s]

Epoch 10:  74%|███████▍  | 1477/2000 [01:08<00:24, 21.62it/s]

Epoch 10:  74%|███████▍  | 1480/2000 [01:08<00:24, 21.63it/s]

Epoch 10:  74%|███████▍  | 1483/2000 [01:08<00:24, 21.49it/s]

Epoch 10:  74%|███████▍  | 1486/2000 [01:08<00:23, 21.54it/s]

Epoch 10:  74%|███████▍  | 1489/2000 [01:08<00:23, 21.56it/s]

Epoch 10:  75%|███████▍  | 1492/2000 [01:09<00:23, 21.58it/s]

Epoch 10:  75%|███████▍  | 1495/2000 [01:09<00:23, 21.60it/s]

Epoch 10:  75%|███████▍  | 1498/2000 [01:09<00:23, 21.61it/s]

Epoch 10:  75%|███████▌  | 1501/2000 [01:09<00:23, 21.62it/s]

Epoch 10:  75%|███████▌  | 1504/2000 [01:09<00:22, 21.64it/s]

Epoch 10:  75%|███████▌  | 1507/2000 [01:09<00:22, 21.63it/s]

Epoch 10:  76%|███████▌  | 1510/2000 [01:09<00:22, 21.63it/s]

Epoch 10:  76%|███████▌  | 1513/2000 [01:10<00:22, 21.64it/s]

Epoch 10:  76%|███████▌  | 1516/2000 [01:10<00:22, 21.63it/s]

Epoch 10:  76%|███████▌  | 1519/2000 [01:10<00:22, 21.64it/s]

Epoch 10:  76%|███████▌  | 1522/2000 [01:10<00:22, 21.64it/s]

Epoch 10:  76%|███████▋  | 1525/2000 [01:10<00:21, 21.65it/s]

Epoch 10:  76%|███████▋  | 1528/2000 [01:10<00:21, 21.63it/s]

Epoch 10:  77%|███████▋  | 1531/2000 [01:10<00:21, 21.64it/s]

Epoch 10:  77%|███████▋  | 1534/2000 [01:11<00:21, 21.63it/s]

Epoch 10:  77%|███████▋  | 1537/2000 [01:11<00:21, 21.64it/s]

Epoch 10:  77%|███████▋  | 1540/2000 [01:11<00:21, 21.64it/s]

Epoch 10:  77%|███████▋  | 1543/2000 [01:11<00:21, 21.64it/s]

Epoch 10:  77%|███████▋  | 1546/2000 [01:11<00:20, 21.65it/s]

Epoch 10:  77%|███████▋  | 1549/2000 [01:11<00:20, 21.64it/s]

Epoch 10:  78%|███████▊  | 1552/2000 [01:11<00:20, 21.63it/s]

Epoch 10:  78%|███████▊  | 1555/2000 [01:12<00:20, 21.62it/s]

Epoch 10:  78%|███████▊  | 1558/2000 [01:12<00:20, 21.62it/s]

Epoch 10:  78%|███████▊  | 1561/2000 [01:12<00:20, 21.62it/s]

Epoch 10:  78%|███████▊  | 1564/2000 [01:12<00:20, 21.60it/s]

Epoch 10:  78%|███████▊  | 1567/2000 [01:12<00:20, 21.61it/s]

Epoch 10:  78%|███████▊  | 1570/2000 [01:12<00:19, 21.62it/s]

Epoch 10:  79%|███████▊  | 1573/2000 [01:12<00:19, 21.62it/s]

Epoch 10:  79%|███████▉  | 1576/2000 [01:13<00:19, 21.64it/s]

Epoch 10:  79%|███████▉  | 1579/2000 [01:13<00:19, 21.64it/s]

Epoch 10:  79%|███████▉  | 1582/2000 [01:13<00:19, 21.64it/s]

Epoch 10:  79%|███████▉  | 1585/2000 [01:13<00:19, 21.65it/s]

Epoch 10:  79%|███████▉  | 1588/2000 [01:13<00:19, 21.65it/s]

Epoch 10:  80%|███████▉  | 1591/2000 [01:13<00:18, 21.65it/s]

Epoch 10:  80%|███████▉  | 1594/2000 [01:13<00:18, 21.65it/s]

Epoch 10:  80%|███████▉  | 1597/2000 [01:13<00:18, 21.64it/s]

Epoch 10:  80%|████████  | 1600/2000 [01:14<00:18, 21.65it/s]

Epoch 10:  80%|████████  | 1603/2000 [01:14<00:18, 21.63it/s]

Epoch 10:  80%|████████  | 1606/2000 [01:14<00:18, 21.64it/s]

Epoch 10:  80%|████████  | 1609/2000 [01:14<00:18, 21.66it/s]

Epoch 10:  81%|████████  | 1612/2000 [01:14<00:17, 21.66it/s]

Epoch 10:  81%|████████  | 1615/2000 [01:14<00:17, 21.65it/s]

Epoch 10:  81%|████████  | 1618/2000 [01:14<00:17, 21.65it/s]

Epoch 10:  81%|████████  | 1621/2000 [01:15<00:17, 21.65it/s]

Epoch 10:  81%|████████  | 1624/2000 [01:15<00:17, 21.62it/s]

Epoch 10:  81%|████████▏ | 1627/2000 [01:15<00:17, 21.62it/s]

Epoch 10:  82%|████████▏ | 1630/2000 [01:15<00:17, 21.64it/s]

Epoch 10:  82%|████████▏ | 1633/2000 [01:15<00:16, 21.64it/s]

Epoch 10:  82%|████████▏ | 1636/2000 [01:15<00:16, 21.64it/s]

Epoch 10:  82%|████████▏ | 1639/2000 [01:15<00:16, 21.65it/s]

Epoch 10:  82%|████████▏ | 1642/2000 [01:16<00:16, 21.65it/s]

Epoch 10:  82%|████████▏ | 1645/2000 [01:16<00:16, 21.65it/s]

Epoch 10:  82%|████████▏ | 1648/2000 [01:16<00:16, 21.64it/s]

Epoch 10:  83%|████████▎ | 1651/2000 [01:16<00:16, 21.64it/s]

Epoch 10:  83%|████████▎ | 1654/2000 [01:16<00:15, 21.64it/s]

Epoch 10:  83%|████████▎ | 1657/2000 [01:16<00:15, 21.64it/s]

Epoch 10:  83%|████████▎ | 1660/2000 [01:16<00:15, 21.63it/s]

Epoch 10:  83%|████████▎ | 1663/2000 [01:17<00:15, 21.63it/s]

Epoch 10:  83%|████████▎ | 1666/2000 [01:17<00:15, 21.62it/s]

Epoch 10:  83%|████████▎ | 1669/2000 [01:17<00:15, 21.46it/s]

Epoch 10:  84%|████████▎ | 1672/2000 [01:17<00:15, 20.89it/s]

Epoch 10:  84%|████████▍ | 1675/2000 [01:17<00:15, 20.89it/s]

Epoch 10:  84%|████████▍ | 1678/2000 [01:17<00:15, 21.06it/s]

Epoch 10:  84%|████████▍ | 1681/2000 [01:17<00:15, 21.17it/s]

Epoch 10:  84%|████████▍ | 1684/2000 [01:18<00:14, 21.32it/s]

Epoch 10:  84%|████████▍ | 1687/2000 [01:18<00:14, 21.41it/s]

Epoch 10:  84%|████████▍ | 1690/2000 [01:18<00:14, 21.48it/s]

Epoch 10:  85%|████████▍ | 1693/2000 [01:18<00:14, 21.53it/s]

Epoch 10:  85%|████████▍ | 1696/2000 [01:18<00:14, 21.55it/s]

Epoch 10:  85%|████████▍ | 1699/2000 [01:18<00:13, 21.58it/s]

Epoch 10:  85%|████████▌ | 1702/2000 [01:18<00:13, 21.61it/s]

Epoch 10:  85%|████████▌ | 1705/2000 [01:18<00:13, 21.61it/s]

Epoch 10:  85%|████████▌ | 1708/2000 [01:19<00:13, 21.60it/s]

Epoch 10:  86%|████████▌ | 1711/2000 [01:19<00:13, 21.61it/s]

Epoch 10:  86%|████████▌ | 1714/2000 [01:19<00:13, 21.62it/s]

Epoch 10:  86%|████████▌ | 1717/2000 [01:19<00:13, 21.62it/s]

Epoch 10:  86%|████████▌ | 1720/2000 [01:19<00:12, 21.63it/s]

Epoch 10:  86%|████████▌ | 1723/2000 [01:19<00:12, 21.63it/s]

Epoch 10:  86%|████████▋ | 1726/2000 [01:19<00:12, 21.62it/s]

Epoch 10:  86%|████████▋ | 1729/2000 [01:20<00:12, 21.63it/s]

Epoch 10:  87%|████████▋ | 1732/2000 [01:20<00:12, 21.63it/s]

Epoch 10:  87%|████████▋ | 1735/2000 [01:20<00:12, 21.62it/s]

Epoch 10:  87%|████████▋ | 1738/2000 [01:20<00:12, 21.63it/s]

Epoch 10:  87%|████████▋ | 1741/2000 [01:20<00:11, 21.63it/s]

Epoch 10:  87%|████████▋ | 1744/2000 [01:20<00:11, 21.63it/s]

Epoch 10:  87%|████████▋ | 1747/2000 [01:20<00:11, 21.63it/s]

Epoch 10:  88%|████████▊ | 1750/2000 [01:21<00:11, 21.63it/s]

Epoch 10:  88%|████████▊ | 1753/2000 [01:21<00:11, 21.63it/s]

Epoch 10:  88%|████████▊ | 1756/2000 [01:21<00:11, 21.64it/s]

Epoch 10:  88%|████████▊ | 1759/2000 [01:21<00:11, 21.64it/s]

Epoch 10:  88%|████████▊ | 1762/2000 [01:21<00:10, 21.64it/s]

Epoch 10:  88%|████████▊ | 1765/2000 [01:21<00:10, 21.64it/s]

Epoch 10:  88%|████████▊ | 1768/2000 [01:21<00:10, 21.65it/s]

Epoch 10:  89%|████████▊ | 1771/2000 [01:22<00:10, 21.65it/s]

Epoch 10:  89%|████████▊ | 1774/2000 [01:22<00:10, 21.64it/s]

Epoch 10:  89%|████████▉ | 1777/2000 [01:22<00:10, 21.63it/s]

Epoch 10:  89%|████████▉ | 1780/2000 [01:22<00:10, 21.63it/s]

Epoch 10:  89%|████████▉ | 1783/2000 [01:22<00:10, 21.63it/s]

Epoch 10:  89%|████████▉ | 1786/2000 [01:22<00:09, 21.63it/s]

Epoch 10:  89%|████████▉ | 1789/2000 [01:22<00:09, 21.62it/s]

Epoch 10:  90%|████████▉ | 1792/2000 [01:23<00:09, 21.63it/s]

Epoch 10:  90%|████████▉ | 1795/2000 [01:23<00:09, 21.63it/s]

Epoch 10:  90%|████████▉ | 1798/2000 [01:23<00:09, 21.64it/s]

Epoch 10:  90%|█████████ | 1801/2000 [01:23<00:09, 21.62it/s]

Epoch 10:  90%|█████████ | 1804/2000 [01:23<00:09, 21.62it/s]

Epoch 10:  90%|█████████ | 1807/2000 [01:23<00:08, 21.62it/s]

Epoch 10:  90%|█████████ | 1810/2000 [01:23<00:08, 21.62it/s]

Epoch 10:  91%|█████████ | 1813/2000 [01:23<00:08, 21.61it/s]

Epoch 10:  91%|█████████ | 1816/2000 [01:24<00:08, 21.60it/s]

Epoch 10:  91%|█████████ | 1819/2000 [01:24<00:08, 21.61it/s]

Epoch 10:  91%|█████████ | 1822/2000 [01:24<00:08, 21.63it/s]

Epoch 10:  91%|█████████▏| 1825/2000 [01:24<00:08, 21.61it/s]

Epoch 10:  91%|█████████▏| 1828/2000 [01:24<00:07, 21.60it/s]

Epoch 10:  92%|█████████▏| 1831/2000 [01:24<00:07, 21.61it/s]

Epoch 10:  92%|█████████▏| 1834/2000 [01:24<00:07, 21.61it/s]

Epoch 10:  92%|█████████▏| 1837/2000 [01:25<00:07, 21.60it/s]

Epoch 10:  92%|█████████▏| 1840/2000 [01:25<00:07, 21.62it/s]

Epoch 10:  92%|█████████▏| 1843/2000 [01:25<00:07, 21.60it/s]

Epoch 10:  92%|█████████▏| 1846/2000 [01:25<00:07, 21.61it/s]

Epoch 10:  92%|█████████▏| 1849/2000 [01:25<00:06, 21.62it/s]

Epoch 10:  93%|█████████▎| 1852/2000 [01:25<00:06, 21.63it/s]

Epoch 10:  93%|█████████▎| 1855/2000 [01:25<00:06, 21.63it/s]

Epoch 10:  93%|█████████▎| 1858/2000 [01:26<00:06, 21.63it/s]

Epoch 10:  93%|█████████▎| 1861/2000 [01:26<00:06, 21.63it/s]

Epoch 10:  93%|█████████▎| 1864/2000 [01:26<00:06, 21.64it/s]

Epoch 10:  93%|█████████▎| 1867/2000 [01:26<00:06, 21.64it/s]

Epoch 10:  94%|█████████▎| 1870/2000 [01:26<00:06, 21.64it/s]

Epoch 10:  94%|█████████▎| 1873/2000 [01:26<00:05, 21.63it/s]

Epoch 10:  94%|█████████▍| 1876/2000 [01:26<00:05, 21.61it/s]

Epoch 10:  94%|█████████▍| 1879/2000 [01:27<00:05, 21.62it/s]

Epoch 10:  94%|█████████▍| 1882/2000 [01:27<00:05, 21.62it/s]

Epoch 10:  94%|█████████▍| 1885/2000 [01:27<00:05, 21.64it/s]

Epoch 10:  94%|█████████▍| 1888/2000 [01:27<00:05, 21.64it/s]

Epoch 10:  95%|█████████▍| 1891/2000 [01:27<00:05, 21.64it/s]

Epoch 10:  95%|█████████▍| 1894/2000 [01:27<00:04, 21.63it/s]

Epoch 10:  95%|█████████▍| 1897/2000 [01:27<00:04, 21.63it/s]

Epoch 10:  95%|█████████▌| 1900/2000 [01:28<00:04, 21.64it/s]

Epoch 10:  95%|█████████▌| 1903/2000 [01:28<00:04, 21.64it/s]

Epoch 10:  95%|█████████▌| 1906/2000 [01:28<00:04, 21.65it/s]

Epoch 10:  95%|█████████▌| 1909/2000 [01:28<00:04, 21.64it/s]

Epoch 10:  96%|█████████▌| 1912/2000 [01:28<00:04, 21.64it/s]

Epoch 10:  96%|█████████▌| 1915/2000 [01:28<00:03, 21.65it/s]

Epoch 10:  96%|█████████▌| 1918/2000 [01:28<00:03, 21.65it/s]

Epoch 10:  96%|█████████▌| 1921/2000 [01:28<00:03, 21.65it/s]

Epoch 10:  96%|█████████▌| 1924/2000 [01:29<00:03, 21.64it/s]

Epoch 10:  96%|█████████▋| 1927/2000 [01:29<00:03, 21.63it/s]

Epoch 10:  96%|█████████▋| 1930/2000 [01:29<00:03, 21.64it/s]

Epoch 10:  97%|█████████▋| 1933/2000 [01:29<00:03, 21.63it/s]

Epoch 10:  97%|█████████▋| 1936/2000 [01:29<00:02, 21.64it/s]

Epoch 10:  97%|█████████▋| 1939/2000 [01:29<00:02, 21.63it/s]

Epoch 10:  97%|█████████▋| 1942/2000 [01:29<00:02, 21.62it/s]

Epoch 10:  97%|█████████▋| 1945/2000 [01:30<00:02, 21.62it/s]

Epoch 10:  97%|█████████▋| 1948/2000 [01:30<00:02, 21.64it/s]

Epoch 10:  98%|█████████▊| 1951/2000 [01:30<00:02, 21.64it/s]

Epoch 10:  98%|█████████▊| 1954/2000 [01:30<00:02, 21.65it/s]

Epoch 10:  98%|█████████▊| 1957/2000 [01:30<00:01, 21.63it/s]

Epoch 10:  98%|█████████▊| 1960/2000 [01:30<00:01, 21.64it/s]

Epoch 10:  98%|█████████▊| 1963/2000 [01:30<00:01, 21.64it/s]

Epoch 10:  98%|█████████▊| 1966/2000 [01:31<00:01, 21.64it/s]

Epoch 10:  98%|█████████▊| 1969/2000 [01:31<00:01, 21.65it/s]

Epoch 10:  99%|█████████▊| 1972/2000 [01:31<00:01, 21.66it/s]

Epoch 10:  99%|█████████▉| 1975/2000 [01:31<00:01, 21.67it/s]

Epoch 10:  99%|█████████▉| 1978/2000 [01:31<00:01, 21.66it/s]

Epoch 10:  99%|█████████▉| 1981/2000 [01:31<00:00, 21.64it/s]

Epoch 10:  99%|█████████▉| 1984/2000 [01:31<00:00, 21.64it/s]

Epoch 10:  99%|█████████▉| 1987/2000 [01:32<00:00, 21.64it/s]

Epoch 10: 100%|█████████▉| 1990/2000 [01:32<00:00, 21.64it/s]

Epoch 10: 100%|█████████▉| 1993/2000 [01:32<00:00, 21.64it/s]

Epoch 10: 100%|█████████▉| 1996/2000 [01:32<00:00, 21.66it/s]

Epoch 10: 100%|█████████▉| 1999/2000 [01:32<00:00, 21.64it/s]

Epoch 10: loss=0.3852, val_proxy=0.4998

Epoch 11:   0%|          | 0/2000 [00:00<?, ?it/s]

Epoch 11:   0%|          | 3/2000 [00:00<01:33, 21.33it/s]

Epoch 11:   0%|          | 6/2000 [00:00<01:32, 21.47it/s]

Epoch 11:   0%|          | 9/2000 [00:00<01:32, 21.50it/s]

Epoch 11:   1%|          | 12/2000 [00:00<01:32, 21.53it/s]

Epoch 11:   1%|          | 15/2000 [00:00<01:32, 21.54it/s]

Epoch 11:   1%|          | 18/2000 [00:00<01:31, 21.56it/s]

Epoch 11:   1%|          | 21/2000 [00:00<01:31, 21.57it/s]

Epoch 11:   1%|          | 24/2000 [00:01<01:31, 21.55it/s]

Epoch 11:   1%|▏         | 27/2000 [00:01<01:31, 21.56it/s]

Epoch 11:   2%|▏         | 30/2000 [00:01<01:31, 21.55it/s]

Epoch 11:   2%|▏         | 33/2000 [00:01<01:31, 21.56it/s]

Epoch 11:   2%|▏         | 36/2000 [00:01<01:31, 21.55it/s]

Epoch 11:   2%|▏         | 39/2000 [00:01<01:30, 21.56it/s]

Epoch 11:   2%|▏         | 42/2000 [00:01<01:30, 21.54it/s]

Epoch 11:   2%|▏         | 45/2000 [00:02<01:30, 21.55it/s]

Epoch 11:   2%|▏         | 48/2000 [00:02<01:30, 21.57it/s]

Epoch 11:   3%|▎         | 51/2000 [00:02<01:30, 21.57it/s]

Epoch 11:   3%|▎         | 54/2000 [00:02<01:30, 21.58it/s]

Epoch 11:   3%|▎         | 57/2000 [00:02<01:30, 21.58it/s]

Epoch 11:   3%|▎         | 60/2000 [00:02<01:29, 21.58it/s]

Epoch 11:   3%|▎         | 63/2000 [00:02<01:29, 21.58it/s]

Epoch 11:   3%|▎         | 66/2000 [00:03<01:29, 21.56it/s]

Epoch 11:   3%|▎         | 69/2000 [00:03<01:29, 21.59it/s]

Epoch 11:   4%|▎         | 72/2000 [00:03<01:29, 21.60it/s]

Epoch 11:   4%|▍         | 75/2000 [00:03<01:29, 21.60it/s]

Epoch 11:   4%|▍         | 78/2000 [00:03<01:28, 21.62it/s]

Epoch 11:   4%|▍         | 81/2000 [00:03<01:28, 21.61it/s]

Epoch 11:   4%|▍         | 84/2000 [00:03<01:28, 21.61it/s]

Epoch 11:   4%|▍         | 87/2000 [00:04<01:28, 21.61it/s]

Epoch 11:   4%|▍         | 90/2000 [00:04<01:28, 21.60it/s]

Epoch 11:   5%|▍         | 93/2000 [00:04<01:28, 21.59it/s]

Epoch 11:   5%|▍         | 96/2000 [00:04<01:28, 21.59it/s]

Epoch 11:   5%|▍         | 99/2000 [00:04<01:28, 21.60it/s]

Epoch 11:   5%|▌         | 102/2000 [00:04<01:27, 21.60it/s]

Epoch 11:   5%|▌         | 105/2000 [00:04<01:27, 21.60it/s]

Epoch 11:   5%|▌         | 108/2000 [00:05<01:27, 21.61it/s]

Epoch 11:   6%|▌         | 111/2000 [00:05<01:27, 21.61it/s]

Epoch 11:   6%|▌         | 114/2000 [00:05<01:27, 21.60it/s]

Epoch 11:   6%|▌         | 117/2000 [00:05<01:27, 21.60it/s]

Epoch 11:   6%|▌         | 120/2000 [00:05<01:27, 21.60it/s]

Epoch 11:   6%|▌         | 123/2000 [00:05<01:26, 21.60it/s]

Epoch 11:   6%|▋         | 126/2000 [00:05<01:26, 21.59it/s]

Epoch 11:   6%|▋         | 129/2000 [00:05<01:26, 21.59it/s]

Epoch 11:   7%|▋         | 132/2000 [00:06<01:26, 21.60it/s]

Epoch 11:   7%|▋         | 135/2000 [00:06<01:26, 21.59it/s]

Epoch 11:   7%|▋         | 138/2000 [00:06<01:26, 21.59it/s]

Epoch 11:   7%|▋         | 141/2000 [00:06<01:26, 21.57it/s]

Epoch 11:   7%|▋         | 144/2000 [00:06<01:25, 21.59it/s]

Epoch 11:   7%|▋         | 147/2000 [00:06<01:25, 21.59it/s]

Epoch 11:   8%|▊         | 150/2000 [00:06<01:25, 21.60it/s]

Epoch 11:   8%|▊         | 153/2000 [00:07<01:25, 21.60it/s]

Epoch 11:   8%|▊         | 156/2000 [00:07<01:25, 21.60it/s]

Epoch 11:   8%|▊         | 159/2000 [00:07<01:25, 21.60it/s]

Epoch 11:   8%|▊         | 162/2000 [00:07<01:25, 21.59it/s]

Epoch 11:   8%|▊         | 165/2000 [00:07<01:24, 21.60it/s]

Epoch 11:   8%|▊         | 168/2000 [00:07<01:24, 21.61it/s]

Epoch 11:   9%|▊         | 171/2000 [00:07<01:24, 21.60it/s]

Epoch 11:   9%|▊         | 174/2000 [00:08<01:24, 21.59it/s]

Epoch 11:   9%|▉         | 177/2000 [00:08<01:24, 21.54it/s]

Epoch 11:   9%|▉         | 180/2000 [00:08<01:24, 21.42it/s]

Epoch 11:   9%|▉         | 183/2000 [00:08<01:27, 20.86it/s]

Epoch 11:   9%|▉         | 186/2000 [00:08<01:26, 20.89it/s]

Epoch 11:   9%|▉         | 189/2000 [00:08<01:26, 21.04it/s]

Epoch 11:  10%|▉         | 192/2000 [00:08<01:25, 21.16it/s]

Epoch 11:  10%|▉         | 195/2000 [00:09<01:24, 21.25it/s]

Epoch 11:  10%|▉         | 198/2000 [00:09<01:24, 21.33it/s]

Epoch 11:  10%|█         | 201/2000 [00:09<01:24, 21.40it/s]

Epoch 11:  10%|█         | 204/2000 [00:09<01:23, 21.46it/s]

Epoch 11:  10%|█         | 207/2000 [00:09<01:23, 21.49it/s]

Epoch 11:  10%|█         | 210/2000 [00:09<01:23, 21.52it/s]

Epoch 11:  11%|█         | 213/2000 [00:09<01:22, 21.54it/s]

Epoch 11:  11%|█         | 216/2000 [00:10<01:22, 21.56it/s]

Epoch 11:  11%|█         | 219/2000 [00:10<01:22, 21.56it/s]

Epoch 11:  11%|█         | 222/2000 [00:10<01:22, 21.56it/s]

Epoch 11:  11%|█▏        | 225/2000 [00:10<01:22, 21.56it/s]

Epoch 11:  11%|█▏        | 228/2000 [00:10<01:22, 21.58it/s]

Epoch 11:  12%|█▏        | 231/2000 [00:10<01:22, 21.56it/s]

Epoch 11:  12%|█▏        | 234/2000 [00:10<01:21, 21.58it/s]

Epoch 11:  12%|█▏        | 237/2000 [00:11<01:21, 21.58it/s]

Epoch 11:  12%|█▏        | 240/2000 [00:11<01:21, 21.58it/s]

Epoch 11:  12%|█▏        | 243/2000 [00:11<01:21, 21.60it/s]

Epoch 11:  12%|█▏        | 246/2000 [00:11<01:21, 21.60it/s]

Epoch 11:  12%|█▏        | 249/2000 [00:11<01:21, 21.60it/s]

Epoch 11:  13%|█▎        | 252/2000 [00:11<01:20, 21.60it/s]

Epoch 11:  13%|█▎        | 255/2000 [00:11<01:20, 21.59it/s]

Epoch 11:  13%|█▎        | 258/2000 [00:11<01:20, 21.60it/s]

Epoch 11:  13%|█▎        | 261/2000 [00:12<01:20, 21.59it/s]

Epoch 11:  13%|█▎        | 264/2000 [00:12<01:20, 21.59it/s]

Epoch 11:  13%|█▎        | 267/2000 [00:12<01:20, 21.60it/s]

Epoch 11:  14%|█▎        | 270/2000 [00:12<01:20, 21.62it/s]

Epoch 11:  14%|█▎        | 273/2000 [00:12<01:19, 21.62it/s]

Epoch 11:  14%|█▍        | 276/2000 [00:12<01:19, 21.61it/s]

Epoch 11:  14%|█▍        | 279/2000 [00:12<01:19, 21.60it/s]

Epoch 11:  14%|█▍        | 282/2000 [00:13<01:19, 21.61it/s]

Epoch 11:  14%|█▍        | 285/2000 [00:13<01:19, 21.61it/s]

Epoch 11:  14%|█▍        | 288/2000 [00:13<01:19, 21.61it/s]

Epoch 11:  15%|█▍        | 291/2000 [00:13<01:19, 21.60it/s]

Epoch 11:  15%|█▍        | 294/2000 [00:13<01:18, 21.61it/s]

Epoch 11:  15%|█▍        | 297/2000 [00:13<01:18, 21.61it/s]

Epoch 11:  15%|█▌        | 300/2000 [00:13<01:18, 21.61it/s]

Epoch 11:  15%|█▌        | 303/2000 [00:14<01:18, 21.61it/s]

Epoch 11:  15%|█▌        | 306/2000 [00:14<01:18, 21.60it/s]

Epoch 11:  15%|█▌        | 309/2000 [00:14<01:18, 21.57it/s]

Epoch 11:  16%|█▌        | 312/2000 [00:14<01:18, 21.57it/s]

Epoch 11:  16%|█▌        | 315/2000 [00:14<01:18, 21.57it/s]

Epoch 11:  16%|█▌        | 318/2000 [00:14<01:17, 21.58it/s]

Epoch 11:  16%|█▌        | 321/2000 [00:14<01:17, 21.58it/s]

Epoch 11:  16%|█▌        | 324/2000 [00:15<01:17, 21.59it/s]

Epoch 11:  16%|█▋        | 327/2000 [00:15<01:17, 21.59it/s]

Epoch 11:  16%|█▋        | 330/2000 [00:15<01:17, 21.61it/s]

Epoch 11:  17%|█▋        | 333/2000 [00:15<01:17, 21.61it/s]

Epoch 11:  17%|█▋        | 336/2000 [00:15<01:17, 21.60it/s]

Epoch 11:  17%|█▋        | 339/2000 [00:15<01:16, 21.61it/s]

Epoch 11:  17%|█▋        | 342/2000 [00:15<01:16, 21.60it/s]

Epoch 11:  17%|█▋        | 345/2000 [00:16<01:16, 21.61it/s]

Epoch 11:  17%|█▋        | 348/2000 [00:16<01:16, 21.61it/s]

Epoch 11:  18%|█▊        | 351/2000 [00:16<01:16, 21.62it/s]

Epoch 11:  18%|█▊        | 354/2000 [00:16<01:16, 21.60it/s]

Epoch 11:  18%|█▊        | 357/2000 [00:16<01:16, 21.59it/s]

Epoch 11:  18%|█▊        | 360/2000 [00:16<01:15, 21.61it/s]

Epoch 11:  18%|█▊        | 363/2000 [00:16<01:15, 21.60it/s]

Epoch 11:  18%|█▊        | 366/2000 [00:16<01:15, 21.61it/s]

Epoch 11:  18%|█▊        | 369/2000 [00:17<01:15, 21.60it/s]

Epoch 11:  19%|█▊        | 372/2000 [00:17<01:15, 21.59it/s]

Epoch 11:  19%|█▉        | 375/2000 [00:17<01:15, 21.58it/s]

Epoch 11:  19%|█▉        | 378/2000 [00:17<01:15, 21.58it/s]

Epoch 11:  19%|█▉        | 381/2000 [00:17<01:15, 21.58it/s]

Epoch 11:  19%|█▉        | 384/2000 [00:17<01:14, 21.58it/s]

Epoch 11:  19%|█▉        | 387/2000 [00:17<01:14, 21.59it/s]

Epoch 11:  20%|█▉        | 390/2000 [00:18<01:14, 21.59it/s]

Epoch 11:  20%|█▉        | 393/2000 [00:18<01:14, 21.58it/s]

Epoch 11:  20%|█▉        | 396/2000 [00:18<01:14, 21.57it/s]

Epoch 11:  20%|█▉        | 399/2000 [00:18<01:14, 21.57it/s]

Epoch 11:  20%|██        | 402/2000 [00:18<01:14, 21.58it/s]

Epoch 11:  20%|██        | 405/2000 [00:18<01:13, 21.58it/s]

Epoch 11:  20%|██        | 408/2000 [00:18<01:13, 21.59it/s]

Epoch 11:  21%|██        | 411/2000 [00:19<01:13, 21.58it/s]

Epoch 11:  21%|██        | 414/2000 [00:19<01:13, 21.57it/s]

Epoch 11:  21%|██        | 417/2000 [00:19<01:13, 21.59it/s]

Epoch 11:  21%|██        | 420/2000 [00:19<01:13, 21.60it/s]

Epoch 11:  21%|██        | 423/2000 [00:19<01:13, 21.59it/s]

Epoch 11:  21%|██▏       | 426/2000 [00:19<01:12, 21.58it/s]

Epoch 11:  21%|██▏       | 429/2000 [00:19<01:12, 21.59it/s]

Epoch 11:  22%|██▏       | 432/2000 [00:20<01:12, 21.60it/s]

Epoch 11:  22%|██▏       | 435/2000 [00:20<01:12, 21.59it/s]

Epoch 11:  22%|██▏       | 438/2000 [00:20<01:12, 21.60it/s]

Epoch 11:  22%|██▏       | 441/2000 [00:20<01:12, 21.60it/s]

Epoch 11:  22%|██▏       | 444/2000 [00:20<01:12, 21.60it/s]

Epoch 11:  22%|██▏       | 447/2000 [00:20<01:11, 21.59it/s]

Epoch 11:  22%|██▎       | 450/2000 [00:20<01:11, 21.61it/s]

Epoch 11:  23%|██▎       | 453/2000 [00:21<01:11, 21.65it/s]

Epoch 11:  23%|██▎       | 456/2000 [00:21<01:11, 21.67it/s]

Epoch 11:  23%|██▎       | 459/2000 [00:21<01:11, 21.69it/s]

Epoch 11:  23%|██▎       | 462/2000 [00:21<01:10, 21.70it/s]

Epoch 11:  23%|██▎       | 465/2000 [00:21<01:10, 21.71it/s]

Epoch 11:  23%|██▎       | 468/2000 [00:21<01:10, 21.73it/s]

Epoch 11:  24%|██▎       | 471/2000 [00:21<01:10, 21.73it/s]

Epoch 11:  24%|██▎       | 474/2000 [00:21<01:10, 21.73it/s]

Epoch 11:  24%|██▍       | 477/2000 [00:22<01:10, 21.73it/s]

Epoch 11:  24%|██▍       | 480/2000 [00:22<01:09, 21.73it/s]

Epoch 11:  24%|██▍       | 483/2000 [00:22<01:09, 21.73it/s]

Epoch 11:  24%|██▍       | 486/2000 [00:22<01:09, 21.72it/s]

Epoch 11:  24%|██▍       | 489/2000 [00:22<01:09, 21.72it/s]

Epoch 11:  25%|██▍       | 492/2000 [00:22<01:09, 21.70it/s]

Epoch 11:  25%|██▍       | 495/2000 [00:22<01:09, 21.71it/s]

Epoch 11:  25%|██▍       | 498/2000 [00:23<01:09, 21.71it/s]

Epoch 11:  25%|██▌       | 501/2000 [00:23<01:08, 21.73it/s]

Epoch 11:  25%|██▌       | 504/2000 [00:23<01:08, 21.72it/s]

Epoch 11:  25%|██▌       | 507/2000 [00:23<01:08, 21.67it/s]

Epoch 11:  26%|██▌       | 510/2000 [00:23<01:08, 21.69it/s]

Epoch 11:  26%|██▌       | 513/2000 [00:23<01:08, 21.70it/s]

Epoch 11:  26%|██▌       | 516/2000 [00:23<01:08, 21.72it/s]

Epoch 11:  26%|██▌       | 519/2000 [00:24<01:08, 21.71it/s]

Epoch 11:  26%|██▌       | 522/2000 [00:24<01:08, 21.71it/s]

Epoch 11:  26%|██▋       | 525/2000 [00:24<01:07, 21.72it/s]

Epoch 11:  26%|██▋       | 528/2000 [00:24<01:07, 21.73it/s]

Epoch 11:  27%|██▋       | 531/2000 [00:24<01:07, 21.74it/s]

Epoch 11:  27%|██▋       | 534/2000 [00:24<01:07, 21.74it/s]

Epoch 11:  27%|██▋       | 537/2000 [00:24<01:07, 21.74it/s]

Epoch 11:  27%|██▋       | 540/2000 [00:25<01:07, 21.74it/s]

Epoch 11:  27%|██▋       | 543/2000 [00:25<01:07, 21.75it/s]

Epoch 11:  27%|██▋       | 546/2000 [00:25<01:06, 21.73it/s]

Epoch 11:  27%|██▋       | 549/2000 [00:25<01:06, 21.73it/s]

Epoch 11:  28%|██▊       | 552/2000 [00:25<01:06, 21.74it/s]

Epoch 11:  28%|██▊       | 555/2000 [00:25<01:06, 21.72it/s]

Epoch 11:  28%|██▊       | 558/2000 [00:25<01:06, 21.72it/s]

Epoch 11:  28%|██▊       | 561/2000 [00:25<01:06, 21.72it/s]

Epoch 11:  28%|██▊       | 564/2000 [00:26<01:06, 21.63it/s]

Epoch 11:  28%|██▊       | 567/2000 [00:26<01:06, 21.61it/s]

Epoch 11:  28%|██▊       | 570/2000 [00:26<01:06, 21.46it/s]

Epoch 11:  29%|██▊       | 573/2000 [00:26<01:06, 21.49it/s]

Epoch 11:  29%|██▉       | 576/2000 [00:26<01:06, 21.52it/s]

Epoch 11:  29%|██▉       | 579/2000 [00:26<01:06, 21.46it/s]

Epoch 11:  29%|██▉       | 582/2000 [00:26<01:06, 21.46it/s]

Epoch 11:  29%|██▉       | 585/2000 [00:27<01:05, 21.47it/s]

Epoch 11:  29%|██▉       | 588/2000 [00:27<01:05, 21.42it/s]

Epoch 11:  30%|██▉       | 591/2000 [00:27<01:05, 21.46it/s]

Epoch 11:  30%|██▉       | 594/2000 [00:27<01:05, 21.49it/s]

Epoch 11:  30%|██▉       | 597/2000 [00:27<01:05, 21.50it/s]

Epoch 11:  30%|███       | 600/2000 [00:27<01:05, 21.53it/s]

Epoch 11:  30%|███       | 603/2000 [00:27<01:04, 21.54it/s]

Epoch 11:  30%|███       | 606/2000 [00:28<01:04, 21.55it/s]

Epoch 11:  30%|███       | 609/2000 [00:28<01:04, 21.56it/s]

Epoch 11:  31%|███       | 612/2000 [00:28<01:04, 21.56it/s]

Epoch 11:  31%|███       | 615/2000 [00:28<01:04, 21.57it/s]

Epoch 11:  31%|███       | 618/2000 [00:28<01:04, 21.57it/s]

Epoch 11:  31%|███       | 621/2000 [00:28<01:03, 21.57it/s]

Epoch 11:  31%|███       | 624/2000 [00:28<01:03, 21.57it/s]

Epoch 11:  31%|███▏      | 627/2000 [00:29<01:03, 21.56it/s]

Epoch 11:  32%|███▏      | 630/2000 [00:29<01:03, 21.55it/s]

Epoch 11:  32%|███▏      | 633/2000 [00:29<01:03, 21.56it/s]

Epoch 11:  32%|███▏      | 636/2000 [00:29<01:03, 21.57it/s]

Epoch 11:  32%|███▏      | 639/2000 [00:29<01:03, 21.57it/s]

Epoch 11:  32%|███▏      | 642/2000 [00:29<01:02, 21.57it/s]

Epoch 11:  32%|███▏      | 645/2000 [00:29<01:02, 21.57it/s]

Epoch 11:  32%|███▏      | 648/2000 [00:30<01:02, 21.57it/s]

Epoch 11:  33%|███▎      | 651/2000 [00:30<01:02, 21.57it/s]

Epoch 11:  33%|███▎      | 654/2000 [00:30<01:02, 21.56it/s]

Epoch 11:  33%|███▎      | 657/2000 [00:30<01:02, 21.56it/s]

Epoch 11:  33%|███▎      | 660/2000 [00:30<01:02, 21.56it/s]

Epoch 11:  33%|███▎      | 663/2000 [00:30<01:01, 21.58it/s]

Epoch 11:  33%|███▎      | 666/2000 [00:30<01:01, 21.57it/s]

Epoch 11:  33%|███▎      | 669/2000 [00:30<01:01, 21.58it/s]

Epoch 11:  34%|███▎      | 672/2000 [00:31<01:01, 21.59it/s]

Epoch 11:  34%|███▍      | 675/2000 [00:31<01:01, 21.59it/s]

Epoch 11:  34%|███▍      | 678/2000 [00:31<01:01, 21.59it/s]

Epoch 11:  34%|███▍      | 681/2000 [00:31<01:01, 21.58it/s]

Epoch 11:  34%|███▍      | 684/2000 [00:31<01:00, 21.59it/s]

Epoch 11:  34%|███▍      | 687/2000 [00:31<01:00, 21.59it/s]

Epoch 11:  34%|███▍      | 690/2000 [00:31<01:00, 21.61it/s]

Epoch 11:  35%|███▍      | 693/2000 [00:32<01:00, 21.62it/s]

Epoch 11:  35%|███▍      | 696/2000 [00:32<01:00, 21.63it/s]

Epoch 11:  35%|███▍      | 699/2000 [00:32<01:00, 21.62it/s]

Epoch 11:  35%|███▌      | 702/2000 [00:32<01:00, 21.62it/s]

Epoch 11:  35%|███▌      | 705/2000 [00:32<00:59, 21.62it/s]

Epoch 11:  35%|███▌      | 708/2000 [00:32<00:59, 21.62it/s]

Epoch 11:  36%|███▌      | 711/2000 [00:32<00:59, 21.60it/s]

Epoch 11:  36%|███▌      | 714/2000 [00:33<00:59, 21.61it/s]

Epoch 11:  36%|███▌      | 717/2000 [00:33<00:59, 21.60it/s]

Epoch 11:  36%|███▌      | 720/2000 [00:33<00:59, 21.59it/s]

Epoch 11:  36%|███▌      | 723/2000 [00:33<00:59, 21.51it/s]

Epoch 11:  36%|███▋      | 726/2000 [00:33<00:59, 21.54it/s]

Epoch 11:  36%|███▋      | 729/2000 [00:33<00:58, 21.57it/s]

Epoch 11:  37%|███▋      | 732/2000 [00:33<00:58, 21.58it/s]

Epoch 11:  37%|███▋      | 735/2000 [00:34<00:58, 21.58it/s]

Epoch 11:  37%|███▋      | 738/2000 [00:34<00:58, 21.60it/s]

Epoch 11:  37%|███▋      | 741/2000 [00:34<00:58, 21.60it/s]

Epoch 11:  37%|███▋      | 744/2000 [00:34<00:58, 21.60it/s]

Epoch 11:  37%|███▋      | 747/2000 [00:34<00:58, 21.60it/s]

Epoch 11:  38%|███▊      | 750/2000 [00:34<00:57, 21.60it/s]

Epoch 11:  38%|███▊      | 753/2000 [00:34<00:57, 21.61it/s]

Epoch 11:  38%|███▊      | 756/2000 [00:35<00:57, 21.61it/s]

Epoch 11:  38%|███▊      | 759/2000 [00:35<00:57, 21.63it/s]

Epoch 11:  38%|███▊      | 762/2000 [00:35<00:57, 21.63it/s]

Epoch 11:  38%|███▊      | 765/2000 [00:35<00:57, 21.61it/s]

Epoch 11:  38%|███▊      | 768/2000 [00:35<00:57, 21.61it/s]

Epoch 11:  39%|███▊      | 771/2000 [00:35<00:56, 21.62it/s]

Epoch 11:  39%|███▊      | 774/2000 [00:35<00:56, 21.61it/s]

Epoch 11:  39%|███▉      | 777/2000 [00:35<00:56, 21.61it/s]

Epoch 11:  39%|███▉      | 780/2000 [00:36<00:56, 21.60it/s]

Epoch 11:  39%|███▉      | 783/2000 [00:36<00:56, 21.60it/s]

Epoch 11:  39%|███▉      | 786/2000 [00:36<00:56, 21.59it/s]

Epoch 11:  39%|███▉      | 789/2000 [00:36<00:56, 21.59it/s]

Epoch 11:  40%|███▉      | 792/2000 [00:36<00:55, 21.60it/s]

Epoch 11:  40%|███▉      | 795/2000 [00:36<00:55, 21.61it/s]

Epoch 11:  40%|███▉      | 798/2000 [00:36<00:55, 21.60it/s]

Epoch 11:  40%|████      | 801/2000 [00:37<00:55, 21.60it/s]

Epoch 11:  40%|████      | 804/2000 [00:37<00:55, 21.60it/s]

Epoch 11:  40%|████      | 807/2000 [00:37<00:55, 21.60it/s]

Epoch 11:  40%|████      | 810/2000 [00:37<00:55, 21.61it/s]

Epoch 11:  41%|████      | 813/2000 [00:37<00:54, 21.61it/s]

Epoch 11:  41%|████      | 816/2000 [00:37<00:54, 21.63it/s]

Epoch 11:  41%|████      | 819/2000 [00:37<00:54, 21.61it/s]

Epoch 11:  41%|████      | 822/2000 [00:38<00:54, 21.62it/s]

Epoch 11:  41%|████▏     | 825/2000 [00:38<00:54, 21.62it/s]

Epoch 11:  41%|████▏     | 828/2000 [00:38<00:54, 21.62it/s]

Epoch 11:  42%|████▏     | 831/2000 [00:38<00:54, 21.62it/s]

Epoch 11:  42%|████▏     | 834/2000 [00:38<00:53, 21.63it/s]

Epoch 11:  42%|████▏     | 837/2000 [00:38<00:53, 21.61it/s]

Epoch 11:  42%|████▏     | 840/2000 [00:38<00:53, 21.62it/s]

Epoch 11:  42%|████▏     | 843/2000 [00:39<00:53, 21.61it/s]

Epoch 11:  42%|████▏     | 846/2000 [00:39<00:53, 21.60it/s]

Epoch 11:  42%|████▏     | 849/2000 [00:39<00:53, 21.61it/s]

Epoch 11:  43%|████▎     | 852/2000 [00:39<00:53, 21.60it/s]

Epoch 11:  43%|████▎     | 855/2000 [00:39<00:53, 21.59it/s]

Epoch 11:  43%|████▎     | 858/2000 [00:39<00:52, 21.59it/s]

Epoch 11:  43%|████▎     | 861/2000 [00:39<00:52, 21.60it/s]

Epoch 11:  43%|████▎     | 864/2000 [00:40<00:53, 21.34it/s]

Epoch 11:  43%|████▎     | 867/2000 [00:40<00:52, 21.42it/s]

Epoch 11:  44%|████▎     | 870/2000 [00:40<00:52, 21.47it/s]

Epoch 11:  44%|████▎     | 873/2000 [00:40<00:52, 21.50it/s]

Epoch 11:  44%|████▍     | 876/2000 [00:40<00:52, 21.54it/s]

Epoch 11:  44%|████▍     | 879/2000 [00:40<00:52, 21.55it/s]

Epoch 11:  44%|████▍     | 882/2000 [00:40<00:51, 21.57it/s]

Epoch 11:  44%|████▍     | 885/2000 [00:40<00:51, 21.57it/s]

Epoch 11:  44%|████▍     | 888/2000 [00:41<00:52, 21.24it/s]

Epoch 11:  45%|████▍     | 891/2000 [00:41<00:53, 20.79it/s]

Epoch 11:  45%|████▍     | 894/2000 [00:41<00:52, 20.92it/s]

Epoch 11:  45%|████▍     | 897/2000 [00:41<00:52, 21.07it/s]

Epoch 11:  45%|████▌     | 900/2000 [00:41<00:51, 21.21it/s]

Epoch 11:  45%|████▌     | 903/2000 [00:41<00:51, 21.33it/s]

Epoch 11:  45%|████▌     | 906/2000 [00:41<00:51, 21.41it/s]

Epoch 11:  45%|████▌     | 909/2000 [00:42<00:50, 21.48it/s]

Epoch 11:  46%|████▌     | 912/2000 [00:42<00:50, 21.52it/s]

Epoch 11:  46%|████▌     | 915/2000 [00:42<00:50, 21.56it/s]

Epoch 11:  46%|████▌     | 918/2000 [00:42<00:50, 21.58it/s]

Epoch 11:  46%|████▌     | 921/2000 [00:42<00:49, 21.60it/s]

Epoch 11:  46%|████▌     | 924/2000 [00:42<00:49, 21.59it/s]

Epoch 11:  46%|████▋     | 927/2000 [00:42<00:49, 21.61it/s]

Epoch 11:  46%|████▋     | 930/2000 [00:43<00:49, 21.62it/s]

Epoch 11:  47%|████▋     | 933/2000 [00:43<00:49, 21.62it/s]

Epoch 11:  47%|████▋     | 936/2000 [00:43<00:49, 21.62it/s]

Epoch 11:  47%|████▋     | 939/2000 [00:43<00:49, 21.61it/s]

Epoch 11:  47%|████▋     | 942/2000 [00:43<00:48, 21.61it/s]

Epoch 11:  47%|████▋     | 945/2000 [00:43<00:48, 21.61it/s]

Epoch 11:  47%|████▋     | 948/2000 [00:43<00:48, 21.62it/s]

Epoch 11:  48%|████▊     | 951/2000 [00:44<00:48, 21.61it/s]

Epoch 11:  48%|████▊     | 954/2000 [00:44<00:48, 21.61it/s]

Epoch 11:  48%|████▊     | 957/2000 [00:44<00:48, 21.62it/s]

Epoch 11:  48%|████▊     | 960/2000 [00:44<00:48, 21.62it/s]

Epoch 11:  48%|████▊     | 963/2000 [00:44<00:47, 21.62it/s]

Epoch 11:  48%|████▊     | 966/2000 [00:44<00:47, 21.61it/s]

Epoch 11:  48%|████▊     | 969/2000 [00:44<00:47, 21.62it/s]

Epoch 11:  49%|████▊     | 972/2000 [00:45<00:47, 21.61it/s]

Epoch 11:  49%|████▉     | 975/2000 [00:45<00:47, 21.61it/s]

Epoch 11:  49%|████▉     | 978/2000 [00:45<00:47, 21.61it/s]

Epoch 11:  49%|████▉     | 981/2000 [00:45<00:47, 21.60it/s]

Epoch 11:  49%|████▉     | 984/2000 [00:45<00:47, 21.60it/s]

Epoch 11:  49%|████▉     | 987/2000 [00:45<00:46, 21.60it/s]

Epoch 11:  50%|████▉     | 990/2000 [00:45<00:46, 21.61it/s]

Epoch 11:  50%|████▉     | 993/2000 [00:46<00:46, 21.62it/s]

Epoch 11:  50%|████▉     | 996/2000 [00:46<00:46, 21.63it/s]

Epoch 11:  50%|████▉     | 999/2000 [00:46<00:46, 21.61it/s]

Epoch 11:  50%|█████     | 1002/2000 [00:46<00:46, 21.62it/s]

Epoch 11:  50%|█████     | 1005/2000 [00:46<00:46, 21.61it/s]

Epoch 11:  50%|█████     | 1008/2000 [00:46<00:45, 21.61it/s]

Epoch 11:  51%|█████     | 1011/2000 [00:46<00:45, 21.63it/s]

Epoch 11:  51%|█████     | 1014/2000 [00:46<00:45, 21.63it/s]

Epoch 11:  51%|█████     | 1017/2000 [00:47<00:45, 21.64it/s]

Epoch 11:  51%|█████     | 1020/2000 [00:47<00:45, 21.64it/s]

Epoch 11:  51%|█████     | 1023/2000 [00:47<00:45, 21.64it/s]

Epoch 11:  51%|█████▏    | 1026/2000 [00:47<00:45, 21.63it/s]

Epoch 11:  51%|█████▏    | 1029/2000 [00:47<00:44, 21.62it/s]

Epoch 11:  52%|█████▏    | 1032/2000 [00:47<00:44, 21.61it/s]

Epoch 11:  52%|█████▏    | 1035/2000 [00:47<00:44, 21.62it/s]

Epoch 11:  52%|█████▏    | 1038/2000 [00:48<00:44, 21.63it/s]

Epoch 11:  52%|█████▏    | 1041/2000 [00:48<00:44, 21.62it/s]

Epoch 11:  52%|█████▏    | 1044/2000 [00:48<00:44, 21.61it/s]

Epoch 11:  52%|█████▏    | 1047/2000 [00:48<00:44, 21.61it/s]

Epoch 11:  52%|█████▎    | 1050/2000 [00:48<00:43, 21.61it/s]

Epoch 11:  53%|█████▎    | 1053/2000 [00:48<00:43, 21.61it/s]

Epoch 11:  53%|█████▎    | 1056/2000 [00:48<00:43, 21.60it/s]

Epoch 11:  53%|█████▎    | 1059/2000 [00:49<00:43, 21.60it/s]

Epoch 11:  53%|█████▎    | 1062/2000 [00:49<00:43, 21.60it/s]

Epoch 11:  53%|█████▎    | 1065/2000 [00:49<00:43, 21.61it/s]

Epoch 11:  53%|█████▎    | 1068/2000 [00:49<00:43, 21.59it/s]

Epoch 11:  54%|█████▎    | 1071/2000 [00:49<00:43, 21.59it/s]

Epoch 11:  54%|█████▎    | 1074/2000 [00:49<00:42, 21.59it/s]

Epoch 11:  54%|█████▍    | 1077/2000 [00:49<00:42, 21.58it/s]

Epoch 11:  54%|█████▍    | 1080/2000 [00:50<00:42, 21.60it/s]

Epoch 11:  54%|█████▍    | 1083/2000 [00:50<00:42, 21.57it/s]

Epoch 11:  54%|█████▍    | 1086/2000 [00:50<00:42, 21.57it/s]

Epoch 11:  54%|█████▍    | 1089/2000 [00:50<00:42, 21.56it/s]

Epoch 11:  55%|█████▍    | 1092/2000 [00:50<00:42, 21.57it/s]

Epoch 11:  55%|█████▍    | 1095/2000 [00:50<00:41, 21.58it/s]

Epoch 11:  55%|█████▍    | 1098/2000 [00:50<00:41, 21.58it/s]

Epoch 11:  55%|█████▌    | 1101/2000 [00:51<00:41, 21.59it/s]

Epoch 11:  55%|█████▌    | 1104/2000 [00:51<00:41, 21.60it/s]

Epoch 11:  55%|█████▌    | 1107/2000 [00:51<00:41, 21.62it/s]

Epoch 11:  56%|█████▌    | 1110/2000 [00:51<00:41, 21.61it/s]

Epoch 11:  56%|█████▌    | 1113/2000 [00:51<00:41, 21.62it/s]

Epoch 11:  56%|█████▌    | 1116/2000 [00:51<00:40, 21.60it/s]

Epoch 11:  56%|█████▌    | 1119/2000 [00:51<00:40, 21.59it/s]

Epoch 11:  56%|█████▌    | 1122/2000 [00:51<00:40, 21.60it/s]

Epoch 11:  56%|█████▋    | 1125/2000 [00:52<00:40, 21.59it/s]

Epoch 11:  56%|█████▋    | 1128/2000 [00:52<00:40, 21.60it/s]

Epoch 11:  57%|█████▋    | 1131/2000 [00:52<00:40, 21.59it/s]

Epoch 11:  57%|█████▋    | 1134/2000 [00:52<00:40, 21.60it/s]

Epoch 11:  57%|█████▋    | 1137/2000 [00:52<00:39, 21.59it/s]

Epoch 11:  57%|█████▋    | 1140/2000 [00:52<00:39, 21.58it/s]

Epoch 11:  57%|█████▋    | 1143/2000 [00:52<00:39, 21.58it/s]

Epoch 11:  57%|█████▋    | 1146/2000 [00:53<00:39, 21.58it/s]

Epoch 11:  57%|█████▋    | 1149/2000 [00:53<00:39, 21.59it/s]

Epoch 11:  58%|█████▊    | 1152/2000 [00:53<00:39, 21.60it/s]

Epoch 11:  58%|█████▊    | 1155/2000 [00:53<00:39, 21.61it/s]

Epoch 11:  58%|█████▊    | 1158/2000 [00:53<00:38, 21.61it/s]

Epoch 11:  58%|█████▊    | 1161/2000 [00:53<00:38, 21.62it/s]

Epoch 11:  58%|█████▊    | 1164/2000 [00:53<00:38, 21.61it/s]

Epoch 11:  58%|█████▊    | 1167/2000 [00:54<00:38, 21.60it/s]

Epoch 11:  58%|█████▊    | 1170/2000 [00:54<00:38, 21.61it/s]

Epoch 11:  59%|█████▊    | 1173/2000 [00:54<00:38, 21.61it/s]

Epoch 11:  59%|█████▉    | 1176/2000 [00:54<00:38, 21.62it/s]

Epoch 11:  59%|█████▉    | 1179/2000 [00:54<00:37, 21.62it/s]

Epoch 11:  59%|█████▉    | 1182/2000 [00:54<00:37, 21.63it/s]

Epoch 11:  59%|█████▉    | 1185/2000 [00:54<00:37, 21.62it/s]

Epoch 11:  59%|█████▉    | 1188/2000 [00:55<00:37, 21.60it/s]

Epoch 11:  60%|█████▉    | 1191/2000 [00:55<00:37, 21.60it/s]

Epoch 11:  60%|█████▉    | 1194/2000 [00:55<00:37, 21.61it/s]

Epoch 11:  60%|█████▉    | 1197/2000 [00:55<00:37, 21.61it/s]

Epoch 11:  60%|██████    | 1200/2000 [00:55<00:37, 21.61it/s]

Epoch 11:  60%|██████    | 1203/2000 [00:55<00:36, 21.61it/s]

Epoch 11:  60%|██████    | 1206/2000 [00:55<00:36, 21.61it/s]

Epoch 11:  60%|██████    | 1209/2000 [00:56<00:36, 21.60it/s]

Epoch 11:  61%|██████    | 1212/2000 [00:56<00:36, 21.62it/s]

Epoch 11:  61%|██████    | 1215/2000 [00:56<00:36, 21.61it/s]

Epoch 11:  61%|██████    | 1218/2000 [00:56<00:36, 21.60it/s]

Epoch 11:  61%|██████    | 1221/2000 [00:56<00:36, 21.60it/s]

Epoch 11:  61%|██████    | 1224/2000 [00:56<00:35, 21.61it/s]

Epoch 11:  61%|██████▏   | 1227/2000 [00:56<00:35, 21.60it/s]

Epoch 11:  62%|██████▏   | 1230/2000 [00:56<00:35, 21.62it/s]

Epoch 11:  62%|██████▏   | 1233/2000 [00:57<00:35, 21.62it/s]

Epoch 11:  62%|██████▏   | 1236/2000 [00:57<00:35, 21.63it/s]

Epoch 11:  62%|██████▏   | 1239/2000 [00:57<00:35, 21.64it/s]

Epoch 11:  62%|██████▏   | 1242/2000 [00:57<00:35, 21.63it/s]

Epoch 11:  62%|██████▏   | 1245/2000 [00:57<00:34, 21.62it/s]

Epoch 11:  62%|██████▏   | 1248/2000 [00:57<00:34, 21.62it/s]

Epoch 11:  63%|██████▎   | 1251/2000 [00:57<00:34, 21.64it/s]

Epoch 11:  63%|██████▎   | 1254/2000 [00:58<00:34, 21.64it/s]

Epoch 11:  63%|██████▎   | 1257/2000 [00:58<00:34, 21.64it/s]

Epoch 11:  63%|██████▎   | 1260/2000 [00:58<00:34, 21.63it/s]

Epoch 11:  63%|██████▎   | 1263/2000 [00:58<00:34, 21.63it/s]

Epoch 11:  63%|██████▎   | 1266/2000 [00:58<00:33, 21.62it/s]

Epoch 11:  63%|██████▎   | 1269/2000 [00:58<00:33, 21.61it/s]

Epoch 11:  64%|██████▎   | 1272/2000 [00:58<00:33, 21.61it/s]

Epoch 11:  64%|██████▍   | 1275/2000 [00:59<00:33, 21.59it/s]

Epoch 11:  64%|██████▍   | 1278/2000 [00:59<00:33, 21.60it/s]

Epoch 11:  64%|██████▍   | 1281/2000 [00:59<00:33, 21.61it/s]

Epoch 11:  64%|██████▍   | 1284/2000 [00:59<00:33, 21.60it/s]

Epoch 11:  64%|██████▍   | 1287/2000 [00:59<00:33, 21.60it/s]

Epoch 11:  64%|██████▍   | 1290/2000 [00:59<00:32, 21.61it/s]

Epoch 11:  65%|██████▍   | 1293/2000 [00:59<00:32, 21.59it/s]

Epoch 11:  65%|██████▍   | 1296/2000 [01:00<00:32, 21.59it/s]

Epoch 11:  65%|██████▍   | 1299/2000 [01:00<00:32, 21.59it/s]

Epoch 11:  65%|██████▌   | 1302/2000 [01:00<00:32, 21.62it/s]

Epoch 11:  65%|██████▌   | 1305/2000 [01:00<00:32, 21.63it/s]

Epoch 11:  65%|██████▌   | 1308/2000 [01:00<00:31, 21.64it/s]

Epoch 11:  66%|██████▌   | 1311/2000 [01:00<00:31, 21.64it/s]

Epoch 11:  66%|██████▌   | 1314/2000 [01:00<00:31, 21.63it/s]

Epoch 11:  66%|██████▌   | 1317/2000 [01:01<00:31, 21.62it/s]

Epoch 11:  66%|██████▌   | 1320/2000 [01:01<00:31, 21.62it/s]

Epoch 11:  66%|██████▌   | 1323/2000 [01:01<00:31, 21.61it/s]

Epoch 11:  66%|██████▋   | 1326/2000 [01:01<00:31, 21.60it/s]

Epoch 11:  66%|██████▋   | 1329/2000 [01:01<00:31, 21.61it/s]

Epoch 11:  67%|██████▋   | 1332/2000 [01:01<00:30, 21.61it/s]

Epoch 11:  67%|██████▋   | 1335/2000 [01:01<00:30, 21.62it/s]

Epoch 11:  67%|██████▋   | 1338/2000 [01:01<00:30, 21.63it/s]

Epoch 11:  67%|██████▋   | 1341/2000 [01:02<00:30, 21.61it/s]

Epoch 11:  67%|██████▋   | 1344/2000 [01:02<00:30, 21.62it/s]

Epoch 11:  67%|██████▋   | 1347/2000 [01:02<00:30, 21.62it/s]

Epoch 11:  68%|██████▊   | 1350/2000 [01:02<00:30, 21.62it/s]

Epoch 11:  68%|██████▊   | 1353/2000 [01:02<00:29, 21.62it/s]

Epoch 11:  68%|██████▊   | 1356/2000 [01:02<00:29, 21.61it/s]

Epoch 11:  68%|██████▊   | 1359/2000 [01:02<00:29, 21.62it/s]

Epoch 11:  68%|██████▊   | 1362/2000 [01:03<00:29, 21.62it/s]

Epoch 11:  68%|██████▊   | 1365/2000 [01:03<00:29, 21.63it/s]

Epoch 11:  68%|██████▊   | 1368/2000 [01:03<00:29, 21.65it/s]

Epoch 11:  69%|██████▊   | 1371/2000 [01:03<00:29, 21.63it/s]

Epoch 11:  69%|██████▊   | 1374/2000 [01:03<00:28, 21.64it/s]

Epoch 11:  69%|██████▉   | 1377/2000 [01:03<00:28, 21.65it/s]

Epoch 11:  69%|██████▉   | 1380/2000 [01:03<00:28, 21.63it/s]

Epoch 11:  69%|██████▉   | 1383/2000 [01:04<00:28, 21.63it/s]

Epoch 11:  69%|██████▉   | 1386/2000 [01:04<00:28, 21.62it/s]

Epoch 11:  69%|██████▉   | 1389/2000 [01:04<00:28, 21.62it/s]

Epoch 11:  70%|██████▉   | 1392/2000 [01:04<00:28, 21.61it/s]

Epoch 11:  70%|██████▉   | 1395/2000 [01:04<00:28, 21.59it/s]

Epoch 11:  70%|██████▉   | 1398/2000 [01:04<00:27, 21.59it/s]

Epoch 11:  70%|███████   | 1401/2000 [01:04<00:27, 21.59it/s]

Epoch 11:  70%|███████   | 1404/2000 [01:05<00:27, 21.58it/s]

Epoch 11:  70%|███████   | 1407/2000 [01:05<00:27, 21.58it/s]

Epoch 11:  70%|███████   | 1410/2000 [01:05<00:27, 21.59it/s]

Epoch 11:  71%|███████   | 1413/2000 [01:05<00:27, 21.59it/s]

Epoch 11:  71%|███████   | 1416/2000 [01:05<00:27, 21.56it/s]

Epoch 11:  71%|███████   | 1419/2000 [01:05<00:26, 21.58it/s]

Epoch 11:  71%|███████   | 1422/2000 [01:05<00:26, 21.59it/s]

Epoch 11:  71%|███████▏  | 1425/2000 [01:06<00:26, 21.60it/s]

Epoch 11:  71%|███████▏  | 1428/2000 [01:06<00:26, 21.59it/s]

Epoch 11:  72%|███████▏  | 1431/2000 [01:06<00:26, 21.59it/s]

Epoch 11:  72%|███████▏  | 1434/2000 [01:06<00:26, 21.60it/s]

Epoch 11:  72%|███████▏  | 1437/2000 [01:06<00:26, 21.59it/s]

Epoch 11:  72%|███████▏  | 1440/2000 [01:06<00:25, 21.58it/s]

Epoch 11:  72%|███████▏  | 1443/2000 [01:06<00:25, 21.59it/s]

Epoch 11:  72%|███████▏  | 1446/2000 [01:06<00:25, 21.61it/s]

Epoch 11:  72%|███████▏  | 1449/2000 [01:07<00:25, 21.60it/s]

Epoch 11:  73%|███████▎  | 1452/2000 [01:07<00:25, 21.59it/s]

Epoch 11:  73%|███████▎  | 1455/2000 [01:07<00:25, 21.59it/s]

Epoch 11:  73%|███████▎  | 1458/2000 [01:07<00:25, 21.59it/s]

Epoch 11:  73%|███████▎  | 1461/2000 [01:07<00:24, 21.59it/s]

Epoch 11:  73%|███████▎  | 1464/2000 [01:07<00:24, 21.59it/s]

Epoch 11:  73%|███████▎  | 1467/2000 [01:07<00:24, 21.60it/s]

Epoch 11:  74%|███████▎  | 1470/2000 [01:08<00:24, 21.59it/s]

Epoch 11:  74%|███████▎  | 1473/2000 [01:08<00:24, 21.58it/s]

Epoch 11:  74%|███████▍  | 1476/2000 [01:08<00:24, 21.59it/s]

Epoch 11:  74%|███████▍  | 1479/2000 [01:08<00:24, 21.57it/s]

Epoch 11:  74%|███████▍  | 1482/2000 [01:08<00:24, 21.54it/s]

Epoch 11:  74%|███████▍  | 1485/2000 [01:08<00:23, 21.54it/s]

Epoch 11:  74%|███████▍  | 1488/2000 [01:08<00:23, 21.56it/s]

Epoch 11:  75%|███████▍  | 1491/2000 [01:09<00:23, 21.56it/s]

Epoch 11:  75%|███████▍  | 1494/2000 [01:09<00:23, 21.56it/s]

Epoch 11:  75%|███████▍  | 1497/2000 [01:09<00:23, 21.56it/s]

Epoch 11:  75%|███████▌  | 1500/2000 [01:09<00:23, 21.56it/s]

Epoch 11:  75%|███████▌  | 1503/2000 [01:09<00:23, 21.56it/s]

Epoch 11:  75%|███████▌  | 1506/2000 [01:09<00:22, 21.57it/s]

Epoch 11:  75%|███████▌  | 1509/2000 [01:09<00:22, 21.59it/s]

Epoch 11:  76%|███████▌  | 1512/2000 [01:10<00:22, 21.59it/s]

Epoch 11:  76%|███████▌  | 1515/2000 [01:10<00:22, 21.59it/s]

Epoch 11:  76%|███████▌  | 1518/2000 [01:10<00:22, 21.61it/s]

Epoch 11:  76%|███████▌  | 1521/2000 [01:10<00:22, 21.60it/s]

Epoch 11:  76%|███████▌  | 1524/2000 [01:10<00:22, 21.59it/s]

Epoch 11:  76%|███████▋  | 1527/2000 [01:10<00:21, 21.60it/s]

Epoch 11:  76%|███████▋  | 1530/2000 [01:10<00:21, 21.61it/s]

Epoch 11:  77%|███████▋  | 1533/2000 [01:11<00:21, 21.61it/s]

Epoch 11:  77%|███████▋  | 1536/2000 [01:11<00:21, 21.61it/s]

Epoch 11:  77%|███████▋  | 1539/2000 [01:11<00:21, 21.60it/s]

Epoch 11:  77%|███████▋  | 1542/2000 [01:11<00:21, 21.59it/s]

Epoch 11:  77%|███████▋  | 1545/2000 [01:11<00:21, 21.58it/s]

Epoch 11:  77%|███████▋  | 1548/2000 [01:11<00:20, 21.57it/s]

Epoch 11:  78%|███████▊  | 1551/2000 [01:11<00:20, 21.58it/s]

Epoch 11:  78%|███████▊  | 1554/2000 [01:11<00:20, 21.57it/s]

Epoch 11:  78%|███████▊  | 1557/2000 [01:12<00:20, 21.59it/s]

Epoch 11:  78%|███████▊  | 1560/2000 [01:12<00:20, 21.57it/s]

Epoch 11:  78%|███████▊  | 1563/2000 [01:12<00:20, 21.57it/s]

Epoch 11:  78%|███████▊  | 1566/2000 [01:12<00:20, 21.60it/s]

Epoch 11:  78%|███████▊  | 1569/2000 [01:12<00:19, 21.59it/s]

Epoch 11:  79%|███████▊  | 1572/2000 [01:12<00:19, 21.59it/s]

Epoch 11:  79%|███████▉  | 1575/2000 [01:12<00:19, 21.59it/s]

Epoch 11:  79%|███████▉  | 1578/2000 [01:13<00:19, 21.60it/s]

Epoch 11:  79%|███████▉  | 1581/2000 [01:13<00:19, 21.61it/s]

Epoch 11:  79%|███████▉  | 1584/2000 [01:13<00:19, 21.61it/s]

Epoch 11:  79%|███████▉  | 1587/2000 [01:13<00:19, 21.62it/s]

Epoch 11:  80%|███████▉  | 1590/2000 [01:13<00:18, 21.62it/s]

Epoch 11:  80%|███████▉  | 1593/2000 [01:13<00:18, 21.60it/s]

Epoch 11:  80%|███████▉  | 1596/2000 [01:13<00:19, 20.93it/s]

Epoch 11:  80%|███████▉  | 1599/2000 [01:14<00:19, 20.88it/s]

Epoch 11:  80%|████████  | 1602/2000 [01:14<00:18, 21.01it/s]

Epoch 11:  80%|████████  | 1605/2000 [01:14<00:18, 21.12it/s]

Epoch 11:  80%|████████  | 1608/2000 [01:14<00:18, 21.27it/s]

Epoch 11:  81%|████████  | 1611/2000 [01:14<00:18, 21.36it/s]

Epoch 11:  81%|████████  | 1614/2000 [01:14<00:17, 21.45it/s]

Epoch 11:  81%|████████  | 1617/2000 [01:14<00:17, 21.48it/s]

Epoch 11:  81%|████████  | 1620/2000 [01:15<00:17, 21.52it/s]

Epoch 11:  81%|████████  | 1623/2000 [01:15<00:17, 21.53it/s]

Epoch 11:  81%|████████▏ | 1626/2000 [01:15<00:17, 21.55it/s]

Epoch 11:  81%|████████▏ | 1629/2000 [01:15<00:17, 21.57it/s]

Epoch 11:  82%|████████▏ | 1632/2000 [01:15<00:17, 21.59it/s]

Epoch 11:  82%|████████▏ | 1635/2000 [01:15<00:16, 21.60it/s]

Epoch 11:  82%|████████▏ | 1638/2000 [01:15<00:16, 21.61it/s]

Epoch 11:  82%|████████▏ | 1641/2000 [01:16<00:16, 21.61it/s]

Epoch 11:  82%|████████▏ | 1644/2000 [01:16<00:16, 21.61it/s]

Epoch 11:  82%|████████▏ | 1647/2000 [01:16<00:16, 21.62it/s]

Epoch 11:  82%|████████▎ | 1650/2000 [01:16<00:16, 21.62it/s]

Epoch 11:  83%|████████▎ | 1653/2000 [01:16<00:16, 21.63it/s]

Epoch 11:  83%|████████▎ | 1656/2000 [01:16<00:15, 21.63it/s]

Epoch 11:  83%|████████▎ | 1659/2000 [01:16<00:15, 21.62it/s]

Epoch 11:  83%|████████▎ | 1662/2000 [01:17<00:15, 21.61it/s]

Epoch 11:  83%|████████▎ | 1665/2000 [01:17<00:15, 21.62it/s]

Epoch 11:  83%|████████▎ | 1668/2000 [01:17<00:15, 21.62it/s]

Epoch 11:  84%|████████▎ | 1671/2000 [01:17<00:15, 21.60it/s]

Epoch 11:  84%|████████▎ | 1674/2000 [01:17<00:15, 21.60it/s]

Epoch 11:  84%|████████▍ | 1677/2000 [01:17<00:14, 21.60it/s]

Epoch 11:  84%|████████▍ | 1680/2000 [01:17<00:14, 21.60it/s]

Epoch 11:  84%|████████▍ | 1683/2000 [01:17<00:14, 21.60it/s]

Epoch 11:  84%|████████▍ | 1686/2000 [01:18<00:14, 21.60it/s]

Epoch 11:  84%|████████▍ | 1689/2000 [01:18<00:14, 21.60it/s]

Epoch 11:  85%|████████▍ | 1692/2000 [01:18<00:14, 21.60it/s]

Epoch 11:  85%|████████▍ | 1695/2000 [01:18<00:14, 21.61it/s]

Epoch 11:  85%|████████▍ | 1698/2000 [01:18<00:13, 21.61it/s]

Epoch 11:  85%|████████▌ | 1701/2000 [01:18<00:13, 21.62it/s]

Epoch 11:  85%|████████▌ | 1704/2000 [01:18<00:13, 21.64it/s]

Epoch 11:  85%|████████▌ | 1707/2000 [01:19<00:13, 21.63it/s]

Epoch 11:  86%|████████▌ | 1710/2000 [01:19<00:13, 21.61it/s]

Epoch 11:  86%|████████▌ | 1713/2000 [01:19<00:13, 21.60it/s]

Epoch 11:  86%|████████▌ | 1716/2000 [01:19<00:13, 21.56it/s]

Epoch 11:  86%|████████▌ | 1719/2000 [01:19<00:13, 21.53it/s]

Epoch 11:  86%|████████▌ | 1722/2000 [01:19<00:12, 21.55it/s]

Epoch 11:  86%|████████▋ | 1725/2000 [01:19<00:12, 21.55it/s]

Epoch 11:  86%|████████▋ | 1728/2000 [01:20<00:12, 21.55it/s]

Epoch 11:  87%|████████▋ | 1731/2000 [01:20<00:12, 21.56it/s]

Epoch 11:  87%|████████▋ | 1734/2000 [01:20<00:12, 21.56it/s]

Epoch 11:  87%|████████▋ | 1737/2000 [01:20<00:12, 21.57it/s]

Epoch 11:  87%|████████▋ | 1740/2000 [01:20<00:12, 21.59it/s]

Epoch 11:  87%|████████▋ | 1743/2000 [01:20<00:11, 21.57it/s]

Epoch 11:  87%|████████▋ | 1746/2000 [01:20<00:11, 21.58it/s]

Epoch 11:  87%|████████▋ | 1749/2000 [01:21<00:11, 21.57it/s]

Epoch 11:  88%|████████▊ | 1752/2000 [01:21<00:11, 21.59it/s]

Epoch 11:  88%|████████▊ | 1755/2000 [01:21<00:11, 21.59it/s]

Epoch 11:  88%|████████▊ | 1758/2000 [01:21<00:11, 21.59it/s]

Epoch 11:  88%|████████▊ | 1761/2000 [01:21<00:11, 21.60it/s]

Epoch 11:  88%|████████▊ | 1764/2000 [01:21<00:10, 21.59it/s]

Epoch 11:  88%|████████▊ | 1767/2000 [01:21<00:10, 21.60it/s]

Epoch 11:  88%|████████▊ | 1770/2000 [01:22<00:10, 21.60it/s]

Epoch 11:  89%|████████▊ | 1773/2000 [01:22<00:10, 21.60it/s]

Epoch 11:  89%|████████▉ | 1776/2000 [01:22<00:10, 21.58it/s]

Epoch 11:  89%|████████▉ | 1779/2000 [01:22<00:10, 21.59it/s]

Epoch 11:  89%|████████▉ | 1782/2000 [01:22<00:10, 21.60it/s]

Epoch 11:  89%|████████▉ | 1785/2000 [01:22<00:09, 21.58it/s]

Epoch 11:  89%|████████▉ | 1788/2000 [01:22<00:09, 21.58it/s]

Epoch 11:  90%|████████▉ | 1791/2000 [01:22<00:09, 21.60it/s]

Epoch 11:  90%|████████▉ | 1794/2000 [01:23<00:09, 21.57it/s]

Epoch 11:  90%|████████▉ | 1797/2000 [01:23<00:09, 21.57it/s]

Epoch 11:  90%|█████████ | 1800/2000 [01:23<00:09, 21.57it/s]

Epoch 11:  90%|█████████ | 1803/2000 [01:23<00:09, 21.57it/s]

Epoch 11:  90%|█████████ | 1806/2000 [01:23<00:09, 21.47it/s]

Epoch 11:  90%|█████████ | 1809/2000 [01:23<00:08, 21.50it/s]

Epoch 11:  91%|█████████ | 1812/2000 [01:23<00:08, 21.54it/s]

Epoch 11:  91%|█████████ | 1815/2000 [01:24<00:08, 21.56it/s]

Epoch 11:  91%|█████████ | 1818/2000 [01:24<00:08, 21.58it/s]

Epoch 11:  91%|█████████ | 1821/2000 [01:24<00:08, 21.59it/s]

Epoch 11:  91%|█████████ | 1824/2000 [01:24<00:08, 21.59it/s]

Epoch 11:  91%|█████████▏| 1827/2000 [01:24<00:08, 21.59it/s]

Epoch 11:  92%|█████████▏| 1830/2000 [01:24<00:07, 21.60it/s]

Epoch 11:  92%|█████████▏| 1833/2000 [01:24<00:07, 21.61it/s]

Epoch 11:  92%|█████████▏| 1836/2000 [01:25<00:07, 21.61it/s]

Epoch 11:  92%|█████████▏| 1839/2000 [01:25<00:07, 21.59it/s]

Epoch 11:  92%|█████████▏| 1842/2000 [01:25<00:07, 21.59it/s]

Epoch 11:  92%|█████████▏| 1845/2000 [01:25<00:07, 21.60it/s]

Epoch 11:  92%|█████████▏| 1848/2000 [01:25<00:07, 21.59it/s]

Epoch 11:  93%|█████████▎| 1851/2000 [01:25<00:06, 21.59it/s]

Epoch 11:  93%|█████████▎| 1854/2000 [01:25<00:06, 21.59it/s]

Epoch 11:  93%|█████████▎| 1857/2000 [01:26<00:06, 21.60it/s]

Epoch 11:  93%|█████████▎| 1860/2000 [01:26<00:06, 21.60it/s]

Epoch 11:  93%|█████████▎| 1863/2000 [01:26<00:06, 21.61it/s]

Epoch 11:  93%|█████████▎| 1866/2000 [01:26<00:06, 21.61it/s]

Epoch 11:  93%|█████████▎| 1869/2000 [01:26<00:06, 21.61it/s]

Epoch 11:  94%|█████████▎| 1872/2000 [01:26<00:05, 21.59it/s]

Epoch 11:  94%|█████████▍| 1875/2000 [01:26<00:05, 21.58it/s]

Epoch 11:  94%|█████████▍| 1878/2000 [01:27<00:05, 21.60it/s]

Epoch 11:  94%|█████████▍| 1881/2000 [01:27<00:05, 21.59it/s]

Epoch 11:  94%|█████████▍| 1884/2000 [01:27<00:05, 21.60it/s]

Epoch 11:  94%|█████████▍| 1887/2000 [01:27<00:05, 21.62it/s]

Epoch 11:  94%|█████████▍| 1890/2000 [01:27<00:05, 21.61it/s]

Epoch 11:  95%|█████████▍| 1893/2000 [01:27<00:04, 21.62it/s]

Epoch 11:  95%|█████████▍| 1896/2000 [01:27<00:04, 21.60it/s]

Epoch 11:  95%|█████████▍| 1899/2000 [01:27<00:04, 21.60it/s]

Epoch 11:  95%|█████████▌| 1902/2000 [01:28<00:04, 21.61it/s]

Epoch 11:  95%|█████████▌| 1905/2000 [01:28<00:04, 21.60it/s]

Epoch 11:  95%|█████████▌| 1908/2000 [01:28<00:04, 21.61it/s]

Epoch 11:  96%|█████████▌| 1911/2000 [01:28<00:04, 21.61it/s]

Epoch 11:  96%|█████████▌| 1914/2000 [01:28<00:03, 21.61it/s]

Epoch 11:  96%|█████████▌| 1917/2000 [01:28<00:03, 21.61it/s]

Epoch 11:  96%|█████████▌| 1920/2000 [01:28<00:03, 21.63it/s]

Epoch 11:  96%|█████████▌| 1923/2000 [01:29<00:03, 21.61it/s]

Epoch 11:  96%|█████████▋| 1926/2000 [01:29<00:03, 21.62it/s]

Epoch 11:  96%|█████████▋| 1929/2000 [01:29<00:03, 21.63it/s]

Epoch 11:  97%|█████████▋| 1932/2000 [01:29<00:03, 21.61it/s]

Epoch 11:  97%|█████████▋| 1935/2000 [01:29<00:03, 21.61it/s]

Epoch 11:  97%|█████████▋| 1938/2000 [01:29<00:02, 21.62it/s]

Epoch 11:  97%|█████████▋| 1941/2000 [01:29<00:02, 21.62it/s]

Epoch 11:  97%|█████████▋| 1944/2000 [01:30<00:02, 21.62it/s]

Epoch 11:  97%|█████████▋| 1947/2000 [01:30<00:02, 21.61it/s]

Epoch 11:  98%|█████████▊| 1950/2000 [01:30<00:02, 21.61it/s]

Epoch 11:  98%|█████████▊| 1953/2000 [01:30<00:02, 21.62it/s]

Epoch 11:  98%|█████████▊| 1956/2000 [01:30<00:02, 21.63it/s]

Epoch 11:  98%|█████████▊| 1959/2000 [01:30<00:01, 21.61it/s]

Epoch 11:  98%|█████████▊| 1962/2000 [01:30<00:01, 21.61it/s]

Epoch 11:  98%|█████████▊| 1965/2000 [01:31<00:01, 21.61it/s]

Epoch 11:  98%|█████████▊| 1968/2000 [01:31<00:01, 21.61it/s]

Epoch 11:  99%|█████████▊| 1971/2000 [01:31<00:01, 21.61it/s]

Epoch 11:  99%|█████████▊| 1974/2000 [01:31<00:01, 21.60it/s]

Epoch 11:  99%|█████████▉| 1977/2000 [01:31<00:01, 21.60it/s]

Epoch 11:  99%|█████████▉| 1980/2000 [01:31<00:00, 21.61it/s]

Epoch 11:  99%|█████████▉| 1983/2000 [01:31<00:00, 21.62it/s]

Epoch 11:  99%|█████████▉| 1986/2000 [01:32<00:00, 21.62it/s]

Epoch 11:  99%|█████████▉| 1989/2000 [01:32<00:00, 21.62it/s]

Epoch 11: 100%|█████████▉| 1992/2000 [01:32<00:00, 21.62it/s]

Epoch 11: 100%|█████████▉| 1995/2000 [01:32<00:00, 21.62it/s]

Epoch 11: 100%|█████████▉| 1998/2000 [01:32<00:00, 21.62it/s]

Epoch 11: loss=0.3853, val_proxy=0.5066
Early stopping at epoch 11 (no val_proxy improvement in 10 epochs) -- best val_proxy=0.5233 at epoch 1.

    epoch      loss  val_proxy                model
0       0  0.394510   0.512188  sata_query_agnostic
1       1  0.388777   0.523281  sata_query_agnostic
2       2  0.388044   0.508437  sata_query_agnostic
3       3  0.387340   0.509687  sata_query_agnostic
4       4  0.386777   0.512813  sata_query_agnostic
5       5  0.387305   0.498125  sata_query_agnostic
6       6  0.386566   0.494063  sata_query_agnostic
7       7  0.385251   0.506563  sata_query_agnostic
8       8  0.385479   0.512500  sata_query_agnostic
9       9  0.385346   0.514687  sata_query_agnostic
10     10  0.385180   0.499844  sata_query_agnostic
11     11  0.385308   0.506563  sata_query_agnostic

## Gate 2 check

Compare SATA top-k vs. best protocol vs. random on validation tasks via `evaluate_sata_proxy`.

**Why beating both baselines, not just one, is the bar.** Beating random alone would only show that *some* form of non-uniform selection helps — which Notebook 02 will already have established for the hand-designed protocols. Beating the best hand-designed protocol specifically is what would justify the claim that *learned, query-conditioned* reweighting adds value beyond what a human-designed heuristic already captures — that's RQ4's actual question. If Gate 2 fails here, the spec is explicit about what that means: RQ4 becomes a **rigorous negative result**, not a bug to fix by relaxing the criterion. A negative result — "hand-designed diversity protocols already capture what's available; a learned reweighter adds nothing measurable" — is still a real, publishable finding, and the honest thing to do is report it and pivot to ablation analysis (which ingredient of SATA, if any, helps) rather than keep tuning until the number moves.

In [5]:
import os
from concurrent.futures import ThreadPoolExecutor

import torch
from src.models.sata_train import _task_batch, _fit_predict_one

# Gate 2 evaluates the *best* checkpoint (highest val_proxy during training),
# not whatever epoch the loop happened to end on.
model.load_state_dict(torch.load(resolve_path('models/sata_best.pt'), weights_only=True))

# Ground-truth-tag-based protocol proxies, mirroring src/selection's real-arm
# protocols but operating directly on generate_environment's metadata dicts
# (regime/is_counter_spurious/label) rather than a pandas pool -- avoids a
# numpy<->DataFrame round trip just for this proxy comparison.

def select_random(demo_meta, k, seed):
    rng = np.random.default_rng(seed)
    return rng.choice(len(demo_meta), size=k, replace=False)


def select_label_diversity(demo_meta, k, seed):
    rng = np.random.default_rng(seed)
    labels = np.array([m['label'] for m in demo_meta])
    classes = np.unique(labels)
    per_class = k // len(classes)
    selected = []
    for c in classes:
        idx = np.where(labels == c)[0]
        selected.extend(rng.choice(idx, size=min(per_class, len(idx)), replace=False))
    remaining = k - len(selected)
    if remaining > 0:
        leftover = np.setdiff1d(np.arange(len(demo_meta)), selected)
        selected.extend(rng.choice(leftover, size=min(remaining, len(leftover)), replace=False))
    return np.array(selected[:k])


def select_rule_diversity(demo_meta, k, seed):
    rng = np.random.default_rng(seed)
    regimes = np.array([m['regime'] for m in demo_meta])
    groups = {}
    for i, r in enumerate(regimes):
        groups.setdefault(r, []).append(i)
    keys = list(groups.keys())
    rng.shuffle(keys)
    selected = []
    for r in keys:
        if len(selected) >= k:
            break
        selected.append(rng.choice(groups[r]))
    remaining = k - len(selected)
    if remaining > 0:
        leftover = np.setdiff1d(np.arange(len(demo_meta)), selected)
        selected.extend(rng.choice(leftover, size=min(remaining, len(leftover)), replace=False))
    return np.array(selected[:k])


def select_counter_spurious(demo_meta, k, seed):
    rng = np.random.default_rng(seed)
    counter_idx = np.array([i for i, m in enumerate(demo_meta) if m['is_counter_spurious']])
    n_counter = min(k // 2 + 1, len(counter_idx))
    selected = list(rng.choice(counter_idx, size=n_counter, replace=False)) if n_counter else []
    remaining = k - len(selected)
    if remaining > 0:
        leftover = np.setdiff1d(np.arange(len(demo_meta)), selected)
        selected.extend(rng.choice(leftover, size=min(remaining, len(leftover)), replace=False))
    return np.array(selected[:k])


PROTOCOLS = {
    'random': select_random,
    'label_diversity': select_label_diversity,
    'rule_diversity': select_rule_diversity,
    'counter_spurious': select_counter_spurious,
}


def evaluate_protocol_proxy(select_fn, val_tasks, sata_cfg, k, n_jobs=None):
    if n_jobs is None:
        try:
            n_jobs = len(os.sched_getaffinity(0))
        except AttributeError:
            n_jobs = os.cpu_count() or 4

    accs = []
    # Same rationale as src/models/sata_train.py::evaluate_sata_proxy: each
    # query's XGBoost fit is independent and tiny, and XGBoost's C++ fit
    # releases the GIL, so a thread pool turns this into real parallelism
    # across the job's allocated cores instead of one fit at a time.
    with ThreadPoolExecutor(max_workers=n_jobs) as pool:
        for task in val_tasks:
            (demo_X, demo_y, demo_meta), (query_X, query_y, query_meta) = _task_batch(
                task, 'id', n_demos=sata_cfg.max_demos, n_queries=32
            )
            idx_per_query = [select_fn(demo_meta, k, seed=i) for i in range(query_X.shape[0])]
            futures = [
                pool.submit(_fit_predict_one, demo_X[idx], demo_y[idx], query_X[i], query_y[i])
                for i, idx in enumerate(idx_per_query)
            ]
            accs.extend(f.result() for f in futures)
    return float(np.mean(accs)) if accs else 0.0


sata_val_score = evaluate_sata_proxy(model, val_tasks, sata_cfg, k=config.k_primary)
protocol_scores = {
    name: evaluate_protocol_proxy(fn, val_tasks, sata_cfg, k=config.k_primary) for name, fn in PROTOCOLS.items()
}
best_protocol_name = max(protocol_scores, key=protocol_scores.get)
best_protocol_score = protocol_scores[best_protocol_name]

gate2_passed = sata_val_score > best_protocol_score and sata_val_score > protocol_scores['random']

print(f"SATA proxy accuracy: {sata_val_score:.4f}")
for name, score in protocol_scores.items():
    print(f"  {name}: {score:.4f}")
print(f"Best protocol: {best_protocol_name} ({best_protocol_score:.4f})")
print(
    "GATE 2 PASSED — SATA beats both random and the best protocol." if gate2_passed
    else "GATE 2 FAILED — RQ4 becomes a rigorous negative result; document why and pivot to ablation analysis."
)

gate2_summary = pd.DataFrame(
    [{'method': 'sata', 'proxy_accuracy': sata_val_score}]
    + [{'method': name, 'proxy_accuracy': score} for name, score in protocol_scores.items()]
)
gate2_summary

SATA proxy accuracy: 0.9614
  random: 0.5616
  label_diversity: 0.7236
  rule_diversity: 0.6167
  counter_spurious: 0.5437
Best protocol: label_diversity (0.7236)
GATE 2 PASSED — SATA beats both random and the best protocol.

             method  proxy_accuracy
0              sata        0.961406
1            random        0.561562
2   label_diversity        0.723594
3    rule_diversity        0.616719
4  counter_spurious        0.543750

## Output

- `models/sata_best.pt` — best checkpoint by validation loss
- `models/sata_query_agnostic.pt` — ablation checkpoint
- `models/sata_best_resume.pt` / `models/sata_query_agnostic_resume.pt` — full resume state, only present while a run is genuinely in progress or was interrupted; auto-deleted on normal completion (see "Training loop" above)
- `results/sata_training_log.parquet` — loss curves, validation metrics per epoch

In [6]:
# Checkpoints (models/sata_best.pt, models/sata_query_agnostic.pt) are already
# saved incrementally by train_sata's checkpoint_path -- nothing to do here but
# persist the logs.
resolve_path('results').mkdir(parents=True, exist_ok=True)

full_log = pd.concat([training_log_df, query_agnostic_log_df], ignore_index=True)
full_log.to_parquet(resolve_path('results/sata_training_log.parquet'), index=False)
gate2_summary.to_parquet(resolve_path('results/sata_gate2_summary.parquet'), index=False)

print(f"Saved {len(full_log)}-row training log + Gate 2 summary. "
      f"Checkpoints: models/sata_best.pt, models/sata_query_agnostic.pt")

Saved 23-row training log + Gate 2 summary. Checkpoints: models/sata_best.pt, models/sata_query_agnostic.pt