# Notebook 06: Synthetic Arm Evaluation

**Purpose**: Run the full evaluation matrix on synthetic tasks. Answers RQ2 and RQ4.

## Why this notebook exists (thesis framing)

This is the synthetic-arm mirror of Notebooks 02+03 combined — same frozen-LLM ICL mechanism, same demonstration-selection question, but on tasks where ground truth (π_true, the true causal features) is known by construction (Notebook 04), which real TableShift data can never provide. That's what makes this notebook able to answer **RQ4** (does SATA improve *correctness* of reliance, not just accuracy?) in a way Notebook 03 structurally cannot — Notebook 03 can only measure *internal consistency* (does the model's stated reasoning match its behaviour?), not whether that behaviour is actually right.

It also re-runs **RQ2**'s question (which demonstration diversity matters for which shift type?) on tasks where the shift type is exactly known, rather than inferred from a benchmark's metadata — a clean re-test of the real-arm finding from Notebook 02 under conditions with no ambiguity about what changed between train and test.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.utils.config import load_config, set_seed, resolve_path

config = load_config()
set_seed(config.seed_accuracy[0])

## Conditions (10 total)

1. Zero-shot
2. Random-k
3. Similarity-k
4. Label diversity
5. Feature-range diversity
6. Rule diversity (ground-truth regime labels — no decision tree needed)
7. Counter-spurious diversity (ground-truth is_counter_spurious tags)
8. Best protocol + SATA selection
9. SATA alone (full pool, no protocol pre-filtering)
10. SATA query-agnostic ablation

Conditions 1–7 mirror Notebook 02 exactly (same lit-review motivation — see that notebook's Conditions cell) except rule diversity and counter-spurious diversity now use the generator's *ground-truth* regime/is_counter_spurious tags directly, rather than approximating them with a fitted decision tree or a correlation search the way the real arm has to. Conditions 8–10 are the SATA-specific comparisons that operationalise RQ4:

- **"Best protocol + SATA"** doesn't mean SATA re-ranks the whole 256-row pool — it pre-filters with whichever protocol won Notebook 05's Gate 2 (determined empirically at Gate 2 time, not assumed here), then lets SATA pick the final k from within that larger candidate set. This tests whether SATA adds value *on top of* the best hand-designed heuristic, per `src/selection/sata_select.py`'s `pre_filtered_idx` design.
- **"SATA alone"** scores the entire pool with no protocol pre-filter, testing whether SATA's learned reweighting is sufficient by itself.
- **"SATA query-agnostic"** is the ablation from Notebook 05, included here specifically so its *downstream LLM accuracy* — not just its XGBoost proxy score — can be compared against full SATA. A gap between full SATA and this ablation at the LLM level is stronger evidence for query-conditioning mattering than the proxy metric alone.

In [2]:
import json

import numpy as np
import pandas as pd
import torch

from src.models.sata import SATA, SATAQueryAgnostic
from src.selection import sata_select

sata_model = SATA(
    n_features=config.generator.n_features, d_model=config.sata.d_model,
    n_heads=config.sata.n_heads, n_layers=config.sata.n_layers,
)
sata_model.load_state_dict(torch.load(resolve_path('models/sata_best.pt'), weights_only=True))
sata_model.eval()

sata_qa_model = SATAQueryAgnostic(
    n_features=config.generator.n_features, d_model=config.sata.d_model,
    n_heads=config.sata.n_heads, n_layers=config.sata.n_layers,
)
sata_qa_model.load_state_dict(torch.load(resolve_path('models/sata_query_agnostic.pt'), weights_only=True))
sata_qa_model.eval()

print("Loaded sata_best.pt and sata_query_agnostic.pt")

Loaded sata_best.pt and sata_query_agnostic.pt

## RQ2 evaluation: protocol x shift type grid

Accuracy on the 200 held-out test tasks, for each condition x shift type x k (`k_primary` and `k_sensitivity`, mirroring Notebook 02's real-arm sweep). **RQ2 success** = interaction effect: different protocols win on different shift types. Shift type is known by construction — no DISDE decomposition needed.

**Why "no DISDE decomposition needed" is worth spelling out.** On real TableShift data (Notebook 02), a protocol's accuracy gain can't automatically be attributed to a specific shift type — the shift attribution procedure the spec calls for (Liu et al. 2023, Lit-review §3, DISDE: decomposing the accuracy gap into covariate and conditional components) exists precisely because real shifts are naturally-occurring and mixed. Here, each column of this grid *is* a controlled instantiation of a single shift concept by construction (Notebook 04) — `covariate` only moves `P(x)`, `spurious_reversal`/`mechanism` only move `P(y|x)` — so the grid itself already gives the attribution the DISDE procedure would otherwise have to estimate. This is what makes the synthetic arm the clean test of RQ2's "different protocols win on different shift types" claim: any asymmetry in this grid is a real interaction effect, not an artefact of overlapping shift types muddying the picture.

**k-sensitivity**: `results/rq2_grid.parquet` stays k_primary-only (the headline number every other cell/notebook consumes); the full k_primary-vs-k_sensitivity comparison across all 10 conditions is saved separately to `results/rq2_grid_k_sensitivity.parquet` and printed below.

In [3]:
from tqdm import tqdm

from src.data.serialisation import serialise_row
from src.data.tableshift_loader import select_top_features
from src.inference.llm_runner import VLLMWorkerRunner
from src.inference.prompts import build_classification_prompt
from src.selection import random_select, similarity_select, label_diversity, feature_range, rule_diversity, counter_spurious
from src.utils.results_schema import append_results, load_results
from src.evaluation.accuracy import summarise

SHIFT_TYPES = ['id', 'covariate', 'spurious_reversal', 'extrapolation', 'missing_feature', 'mechanism']
FEATURE_COLS = [f'feature_{i}' for i in range(config.generator.n_features)]
LABEL_TOKENS = ('0', '1')
TASK_DESCRIPTION = "the label of a synthetic binary classification task"

SYN_ROOT = resolve_path(config.paths.data_synthetic)
RESULTS_PATH = resolve_path('results/synthetic_evaluation.parquet')

CONDITIONS = [
    'zero_shot', 'random', 'similarity', 'label_diversity', 'feature_range',
    'rule_diversity', 'counter_spurious', 'best_protocol_sata', 'sata_alone', 'sata_query_agnostic',
]

# k-sensitivity sweep for the RQ2 grid (mirrors Notebook 02): all 10
# conditions, including the SATA variants, at both k_primary (headline) and
# k_sensitivity. K_VALUES[0] must stay k_primary -- zero-shot dedup and the
# "headline" rq2_grid filter both key off it.
K_VALUES = (config.k_primary, config.k_sensitivity)

try:
    import vllm  # noqa: F401
    VLLM_AVAILABLE = True
except ImportError:
    VLLM_AVAILABLE = False
    print("vLLM not installed in this environment — skipping synthetic-arm inference. "
          "Run this notebook on a GPU box with vllm + the model weights available.")

# "Best protocol" per Notebook 05's Gate 2 proxy comparison -- used as the
# pre-filter for the "best protocol + SATA" condition (see
# src/selection/sata_select.py's pre_filtered_idx docstring).
try:
    gate2 = pd.read_parquet(resolve_path('results/sata_gate2_summary.parquet'))
    BEST_PROTOCOL = gate2[gate2.method != 'sata'].sort_values('proxy_accuracy', ascending=False).iloc[0]['method']
except FileNotFoundError:
    BEST_PROTOCOL = 'counter_spurious'
print(f"Best protocol (from Notebook 05 Gate 2): {BEST_PROTOCOL}")


def select_ground_truth_protocol(protocol, pool, query, k, seed, top3_continuous):
    if protocol == 'random':
        return random_select.select(pool, query, k, seed)
    if protocol == 'label_diversity':
        return label_diversity.select(pool, query, k, seed)
    if protocol == 'feature_range':
        return feature_range.select(pool, query, k, seed, top_features=top3_continuous)
    if protocol == 'rule_diversity':
        return rule_diversity.select(pool, query, k, seed, regimes=pool['regime'])
    if protocol == 'counter_spurious':
        return counter_spurious.select(pool, query, k, seed, is_counter_spurious=pool['is_counter_spurious'])
    raise ValueError(f"Unknown ground-truth protocol: {protocol}")


def precompute_similarity_demo_ids(pool, queries, k):
    """Similarity is deterministic (no seed dependency) -- one batched
    encode() call for every query in `queries` against `pool`, instead of
    select_demos_synthetic's per-query path embedding one query at a time.
    Returns a dict keyed by `queries`' index (matching each row's `.name`).

    Pass k=max(K_VALUES) and slice the result per k in the caller: a cosine-
    similarity argsort doesn't change when you later take a smaller prefix
    of it, so this only needs computing once per (pool, queries) regardless
    of how many k values are being swept.
    """
    pool_texts = [
        serialise_row({f: pool.loc[i, f] for f in FEATURE_COLS}, label=str(int(pool.loc[i, 'label'])))
        for i in pool.index
    ]
    query_texts = [serialise_row({f: row[f] for f in FEATURE_COLS}) for _, row in queries.iterrows()]
    local_idx_per_query = similarity_select.select_batch(pool_texts, query_texts, k)
    return {
        query_id: [pool.index[i] for i in local_idx]
        for query_id, local_idx in zip(queries.index, local_idx_per_query)
    }


def select_demos_synthetic(condition, pool, query, k, seed, top3_continuous, similarity_demo_ids=None):
    if condition == 'zero_shot':
        return []
    if condition == 'similarity':
        return similarity_demo_ids[query.name][:k]
    if condition in ('random', 'label_diversity', 'feature_range', 'rule_diversity', 'counter_spurious'):
        return select_ground_truth_protocol(condition, pool, query, k, seed, top3_continuous)
    if condition == 'best_protocol_sata':
        prefilter_k = min(len(pool), 4 * k)
        candidates = select_ground_truth_protocol(BEST_PROTOCOL, pool, query, prefilter_k, seed, top3_continuous)
        return sata_select.select(sata_model, pool, query, FEATURE_COLS, 'label', k, pre_filtered_idx=candidates)
    if condition == 'sata_alone':
        return sata_select.select(sata_model, pool, query, FEATURE_COLS, 'label', k)
    if condition == 'sata_query_agnostic':
        return sata_select.select(sata_qa_model, pool, query, FEATURE_COLS, 'label', k)
    raise ValueError(f"Unknown condition: {condition}")


def build_demo_lines(pool, demo_ids):
    return [
        serialise_row({f: pool.loc[i, f] for f in FEATURE_COLS}, label=str(int(pool.loc[i, 'label'])))
        for i in demo_ids
    ]


def build_query_line(query):
    return serialise_row({f: query[f] for f in FEATURE_COLS})


def evaluate_task_group(task_paths, model_cfg, runner, conditions=CONDITIONS, k_values=(config.k_primary,)):
    task_bar = tqdm(task_paths, desc=f"Tasks ({model_cfg.name})", leave=False)
    for task_path in task_bar:
        task_df = pd.read_parquet(task_path)
        task_id = task_path.stem
        task_bar.set_postfix(task=task_id)

        # Batch every (shift_type, k, condition) combo for this task into a
        # single runner.batch_predict call instead of one call per combo --
        # with queries_per_env=32 and ~19 k/condition combos x 6 shift types,
        # per-combo calls paid fixed subprocess-IPC/kernel-launch overhead
        # ~114 times per task (~22,800 times across all 200 test tasks).
        # Batching per-task cuts that to one call per task (~3,600 rows,
        # comparable to Notebook 02's batch sizes) with identical results --
        # this only changes how many calls carry the same prompts/rows.
        task_prompts, task_batch_rows = [], []
        for shift_type in SHIFT_TYPES:
            env_df = task_df[task_df['environment'] == shift_type]
            pool = env_df[env_df['split'] == 'demo'].reset_index(drop=True)
            queries = env_df[env_df['split'] == 'query'].reset_index(drop=True)
            top3_continuous = select_top_features(pool[FEATURE_COLS + ['label']], n_features=3)

            similarity_demo_ids = (
                precompute_similarity_demo_ids(pool, queries, max(k_values))
                if 'similarity' in conditions else None
            )
            for k in k_values:
                sliced_similarity_ids = (
                    {qid: ids[:k] for qid, ids in similarity_demo_ids.items()}
                    if similarity_demo_ids is not None else None
                )
                for condition in conditions:
                    # Zero-shot has no demos, so it's identical at every k --
                    # only run it once, at the primary k, rather than
                    # duplicating identical rows per k value.
                    if condition == 'zero_shot' and k != k_values[0]:
                        continue
                    seed = config.seed_accuracy[0]
                    for query_id, query in queries.iterrows():
                        demo_ids = select_demos_synthetic(condition, pool, query, k, seed, top3_continuous, sliced_similarity_ids)
                        prompt = build_classification_prompt(
                            TASK_DESCRIPTION, LABEL_TOKENS, build_demo_lines(pool, demo_ids), build_query_line(query)
                        )
                        task_prompts.append(prompt)
                        task_batch_rows.append({
                            'arm': 'synthetic', 'dataset': task_id, 'environment': shift_type,
                            'model': model_cfg.name, 'method': condition, 'seed': int(seed),
                            'query_id': int(query_id), 'label': str(int(query['label'])),
                            'demo_ids': [int(i) for i in demo_ids], 'k': len(demo_ids),
                        })

        predictions = runner.batch_predict(task_prompts, LABEL_TOKENS)
        for row, pred in zip(task_batch_rows, predictions):
            row['prediction'] = pred.prediction
            row['logprob_0'] = pred.logprob_0
            row['logprob_1'] = pred.logprob_1
        append_results(pd.DataFrame(task_batch_rows), RESULTS_PATH)
        tqdm.write(f"{model_cfg.name} | {task_id}: done")


test_task_paths = sorted((SYN_ROOT / 'tasks_test').glob('*.parquet'))

for model_cfg in (config.base_llms if VLLM_AVAILABLE else []):
    # Resume support: evaluate_task_group has no skip logic of its own --
    # if a prior run was interrupted partway through test_task_paths (e.g.
    # instance preemption), append_results already has full rows for every
    # task that finished (each task's rows are only written after its
    # single batch_predict call returns, so a task is either fully written
    # or not written at all -- no partial-task rows possible). Skip those
    # task_ids rather than re-running and duplicating them.
    try:
        existing = load_results(RESULTS_PATH)
        done_task_ids = set(existing.loc[existing['model'] == model_cfg.name, 'dataset'])
    except FileNotFoundError:
        done_task_ids = set()
    remaining_task_paths = [p for p in test_task_paths if p.stem not in done_task_ids]
    print(f"{model_cfg.name}: {len(done_task_ids)} test tasks already done, {len(remaining_task_paths)} remaining")
    runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))
    evaluate_task_group(remaining_task_paths, model_cfg, runner, k_values=K_VALUES)
    runner.shutdown()

# RQ2 grid: accuracy per (method, shift_type, k), averaged over test tasks.
# 'k' is included in group_cols -- without it, the k_primary and
# k_sensitivity sweep rows would get silently averaged together.
RQ2_COLS = ['method', 'shift_type', 'model', 'k', 'accuracy', 'macro_f1', 'invalid_rate', 'n']
try:
    synthetic_results = load_results(RESULTS_PATH)
except FileNotFoundError:
    synthetic_results = None

if synthetic_results is None or synthetic_results.empty:
    print("No synthetic-arm results yet — skipped (vLLM not available in this environment).")
    rq2_grid_all_k = pd.DataFrame(columns=RQ2_COLS)
else:
    rq2_source = synthetic_results[synthetic_results['dataset'].str.startswith('test_')]
    rq2_grid_all_k = summarise(rq2_source, group_cols=['method', 'environment', 'model', 'k'])
    rq2_grid_all_k = rq2_grid_all_k.rename(columns={'environment': 'shift_type'})

# Headline rq2_grid.parquet stays k_primary-only -- exactly the shape every
# downstream consumer (Notebook 08's figures/tables) already expects. The
# full k-sensitivity sweep is saved separately rather than folded in here.
rq2_grid = rq2_grid_all_k[rq2_grid_all_k['k'] == config.k_primary].drop(columns='k') if not rq2_grid_all_k.empty else rq2_grid_all_k.drop(columns='k')
rq2_grid.to_parquet(resolve_path('results/rq2_grid.parquet'), index=False)
rq2_grid_all_k.to_parquet(resolve_path('results/rq2_grid_k_sensitivity.parquet'), index=False)

if not rq2_grid_all_k.empty and len(rq2_grid_all_k['k'].unique()) > 1:
    print("k-sensitivity (accuracy, k_primary vs k_sensitivity):")
    display(rq2_grid_all_k.pivot_table(index=['model', 'method', 'shift_type'], columns='k', values='accuracy'))

if rq2_grid.empty:
    rq2_grid
else:
    rq2_grid.pivot_table(index=['model', 'method'], columns='shift_type', values='accuracy')

Best protocol (from Notebook 05 Gate 2): label_diversity

Llama-3.1-8B-Instruct: 200 test tasks already done, 0 remaining

INFO 09-12 17:03:38 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 17:03:38 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 17:03:38 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 17:03:38 [model.py:2021] Using max model len 8192
INFO 09-12 17:03:38 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 17:03:38 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 17:03:40 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 17:03:41 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_9f6a8a653aae499a8560739c0c8393aa backend=nccl
INFO 09-12 17:03:41 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 17:03:41 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 17:03:41 [model_runner.py:382] Loading model from scratch...
INFO 09-12 17:03:42 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 17:03:42 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 17:03:42 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 952.87 GiB.
INFO 09-12 17:03:42 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.30it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.27it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.27it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.81it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.57it/s]

INFO 09-12 17:03:44 [default_loader.py:430] Loading weights took 2.56 seconds

INFO 09-12 17:03:45 [model_runner.py:404] Model loading took 15.0 GiB memory and 3.513237 seconds
INFO 09-12 17:03:45 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 17:03:45 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 17:03:45 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 17:03:45 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 17:03:45 [monitor.py:53] torch.compile took 0.13 s in total
INFO 09-12 17:03:46 [monitor.py:81] Initial profiling/warmup run took 0.13 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:03<01:12,  1.11it/s]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:03<00:23,  3.19it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:12,  5.69it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:04<00:08,  8.18it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:04<00:06, 10.54it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:04<00:04, 12.23it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 13.74it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:05<00:03, 15.02it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:05<00:02, 16.19it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:05<00:02, 17.37it/s]

Capturing CUDA graphs (PIECEWISE):  53%|█████▎    | 44/83 [00:06<00:02, 18.02it/s]

Capturing CUDA graphs (PIECEWISE):  59%|█████▉    | 49/83 [00:06<00:01, 19.13it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:06<00:01, 19.83it/s]

Capturing CUDA graphs (PIECEWISE):  72%|███████▏  | 60/83 [00:06<00:01, 19.78it/s]

Capturing CUDA graphs (PIECEWISE):  78%|███████▊  | 65/83 [00:07<00:00, 19.58it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:07<00:00, 20.08it/s]

Capturing CUDA graphs (PIECEWISE):  92%|█████████▏| 76/83 [00:07<00:00, 19.73it/s]

Capturing CUDA graphs (PIECEWISE):  96%|█████████▋| 80/83 [00:07<00:00, 19.72it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:08<00:00, 10.24it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 20.85it/s]

INFO 09-12 17:03:55 [model_runner.py:960] Graph capturing finished in 8 secs, took 0.54 GiB

INFO 09-12 17:03:55 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 17:03:55 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8958 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9042. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 17:03:55 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,408 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 17:03:55 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 17:03:55 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 17:03:56 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 17:03:56 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 17:03:56 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 17:03:56 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 17:03:56 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 17:03:56 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 17:03:56 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 17:03:56 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 17:03:56 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 17:03:56 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 17:03:56 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 17:03:56 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 17:03:56 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 17:03:56 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 17:03:56 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 17:03:56 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 17:03:56 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 11.00it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.55it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 12.01it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.47it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:04, 13.30it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 14.17it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:01<00:03, 15.10it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 16.09it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:02, 17.06it/s]

Capturing CUDA graphs (PIECEWISE):  46%|████▌     | 38/83 [00:02<00:02, 18.28it/s]

Capturing CUDA graphs (PIECEWISE):  53%|█████▎    | 44/83 [00:02<00:01, 19.62it/s]

Capturing CUDA graphs (PIECEWISE):  57%|█████▋    | 47/83 [00:03<00:01, 20.27it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:03<00:01, 16.60it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:03<00:02, 13.79it/s]

Capturing CUDA graphs (PIECEWISE):  67%|██████▋   | 56/83 [00:03<00:02, 11.69it/s]

Capturing CUDA graphs (PIECEWISE):  72%|███████▏  | 60/83 [00:04<00:01, 11.77it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:04<00:01, 16.29it/s]

Capturing CUDA graphs (PIECEWISE):  87%|████████▋ | 72/83 [00:04<00:00, 18.90it/s]

Capturing CUDA graphs (PIECEWISE):  94%|█████████▍| 78/83 [00:05<00:00, 20.49it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 15.63it/s]
Capturing CUDA graphs (FULL):   0%|          | 0/83 [00:00<?, ?it/s]

Capturing CUDA graphs (FULL):   7%|▋         | 6/83 [00:00<00:03, 22.07it/s]

Capturing CUDA graphs (FULL):  14%|█▍        | 12/83 [00:00<00:03, 23.07it/s]

Capturing CUDA graphs (FULL):  22%|██▏       | 18/83 [00:00<00:02, 25.05it/s]

Capturing CUDA graphs (FULL):  30%|███       | 25/83 [00:00<00:02, 27.90it/s]

Capturing CUDA graphs (FULL):  40%|███▉      | 33/83 [00:01<00:01, 31.55it/s]

Capturing CUDA graphs (FULL):  51%|█████     | 42/83 [00:01<00:01, 36.28it/s]

Capturing CUDA graphs (FULL):  63%|██████▎   | 52/83 [00:01<00:00, 41.96it/s]

Capturing CUDA graphs (FULL):  75%|███████▍  | 62/83 [00:01<00:00, 44.65it/s]

Capturing CUDA graphs (FULL):  87%|████████▋ | 72/83 [00:02<00:00, 46.38it/s]

Capturing CUDA graphs (FULL):  94%|█████████▍| 78/83 [00:02<00:00, 47.67it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 16.03it/s]

INFO 09-12 17:04:06 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.30 GiB
INFO 09-12 17:04:06 [gpu_worker.py:797] CUDA graph pool memory: 0.3 GiB (actual), 0.74 GiB (estimated), difference: 0.45 GiB (150.7%).
INFO 09-12 17:04:06 [gpu_worker.py:860] Free memory on device (177.12/178.34 GiB) on startup. Desired GPU memory utilization is (0.9, 160.51 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.43 GiB for peak activation, and 0.3 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152278255514` (141.82 GiB) to fit into requested memory, or `--kv-cache-memory=170115247616` (158.43 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 17:04:12 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 17:04:12 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 17:04:12 [core.py:361] init engine (profile, create kv cache, warmup model) took 27.29 s (compilation: 0.13 s)

INFO 09-12 17:04:13 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Tasks (Llama-3.1-8B-Instruct): 0it [00:00, ?it/s]

[rank0]:[W912 17:04:14.483506370 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

k-sensitivity (accuracy, k_primary vs k_sensitivity):

k                                                                  0   \
model                 method              shift_type
Llama-3.1-8B-Instruct best_protocol_sata  covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      counter_spurious    covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      feature_range       covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      label_diversity     covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      random              covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      rule_diversity      covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      sata_alone          covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      sata_query_agnostic covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      similarity          covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN
                      zero_shot           covariate          0.387969
                                          extrapolation      0.505938
                                          id                 0.492344
                                          mechanism          0.448594
                                          missing_feature    0.468438
                                          spurious_reversal  0.492344

k                                                                  8   \
model                 method              shift_type
Llama-3.1-8B-Instruct best_protocol_sata  covariate          0.266250
                                          extrapolation      0.300156
                                          id                 0.379063
                                          mechanism          0.354687
                                          missing_feature    0.422812
                                          spurious_reversal  0.098906
                      counter_spurious    covariate          0.363438
                                          extrapolation      0.507031
                                          id                 0.496719
                                          mechanism          0.447500
                                          missing_feature    0.476719
                                          spurious_reversal  0.492969
                      feature_range       covariate          0.372031
                                          extrapolation      0.508750
                                          id                 0.499844
                                          mechanism          0.452188
                                          missing_feature    0.460313
                                          spurious_reversal  0.493281
                      label_diversity     covariate          0.488438
                                          extrapolation      0.536250
                                          id                 0.529062
                                          mechanism          0.463438
                                          missing_feature    0.516719
                                          spurious_reversal  0.513437
                      random              covariate          0.385156
                                          extrapolation      0.525156
                                          id                 0.508281
                                          mechanism          0.448750
                                          missing_feature    0.525156
                                          spurious_reversal  0.496250
                      rule_diversity      covariate          0.410156
                                          extrapolation      0.507969
                                          id                 0.498437
                                          mechanism          0.452813
                                          missing_feature    0.483594
                                          spurious_reversal  0.492969
                      sata_alone          covariate          0.246406
                                          extrapolation      0.359063
                                          id                 0.484219
                                          mechanism          0.405469
                                          missing_feature    0.398594
                                          spurious_reversal  0.098906
                      sata_query_agnostic covariate          0.333281
                                          extrapolation      0.507031
                                          id                 0.499375
                                          mechanism          0.450469
                                          missing_feature    0.431406
                                          spurious_reversal  0.493906
                      similarity          covariate          0.345313
                                          extrapolation      0.414375
                                          id                 0.464687
                                          mechanism          0.431406
                                          missing_feature    0.437656
                                          spurious_reversal  0.488125
                      zero_shot           covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN

k                                                                  16
model                 method              shift_type
Llama-3.1-8B-Instruct best_protocol_sata  covariate          0.532656
                                          extrapolation      0.580156
                                          id                 0.623437
                                          mechanism          0.565625
                                          missing_feature    0.557344
                                          spurious_reversal  0.399375
                      counter_spurious    covariate          0.495469
                                          extrapolation      0.511875
                                          id                 0.521875
                                          mechanism          0.453750
                                          missing_feature    0.514531
                                          spurious_reversal  0.489687
                      feature_range       covariate          0.460156
                                          extrapolation      0.523438
                                          id                 0.518125
                                          mechanism          0.459375
                                          missing_feature    0.526406
                                          spurious_reversal  0.506875
                      label_diversity     covariate          0.608125
                                          extrapolation      0.619531
                                          id                 0.611875
                                          mechanism          0.531719
                                          missing_feature    0.584375
                                          spurious_reversal  0.604844
                      random              covariate          0.486563
                                          extrapolation      0.519844
                                          id                 0.506875
                                          mechanism          0.457500
                                          missing_feature    0.505781
                                          spurious_reversal  0.497188
                      rule_diversity      covariate          0.489063
                                          extrapolation      0.517656
                                          id                 0.513906
                                          mechanism          0.460469
                                          missing_feature    0.518750
                                          spurious_reversal  0.499219
                      sata_alone          covariate          0.532656
                                          extrapolation      0.580156
                                          id                 0.623437
                                          mechanism          0.565625
                                          missing_feature    0.557344
                                          spurious_reversal  0.399375
                      sata_query_agnostic covariate          0.463125
                                          extrapolation      0.522500
                                          id                 0.515469
                                          mechanism          0.466094
                                          missing_feature    0.511719
                                          spurious_reversal  0.507031
                      similarity          covariate          0.463281
                                          extrapolation      0.505313
                                          id                 0.512813
                                          mechanism          0.455000
                                          missing_feature    0.492812
                                          spurious_reversal  0.494219
                      zero_shot           covariate               NaN
                                          extrapolation           NaN
                                          id                      NaN
                                          mechanism               NaN
                                          missing_feature         NaN
                                          spurious_reversal       NaN

## RQ4 evaluation: SATA vs protocols

Compare SATA + best protocol vs. best protocol alone on:
- Accuracy (all shift types, held-out test + held-out family tasks)
- Correctness-of-reliance faithfulness: rho(pi_behav, pi_true)

**Why both accuracy *and* faithfulness, on the *same* comparison?** This is the crux of RQ4 (Lit-review §3): "SATA combined with the best-performing protocol outperforms that protocol alone on **both** R-AUC and ρ(π_self, π_behav)." Improving accuracy alone would only replicate what Notebook 05's Gate 2 already checks with the cheap XGBoost proxy. What Gate 2 *can't* check — because it has no access to an LLM's stated feature ranking or causal ground truth — is whether SATA's demonstrations lead the frozen LLM toward *correct* reliance, not just correct predictions. A configuration that improves accuracy without improving ρ(π_behav, π_true) would be exactly the RQ3-style dissociation (accuracy up, faithfulness flat) the lit review flags as a real risk (§2.5.2) — predictive gains that don't reflect genuinely better task understanding.

**Why held-out test tasks *and* held-out-family tasks, not just one?** `tasks_test` shares SATA's training rule families (linear/threshold/tree), so strong performance there could just mean SATA memorised patterns specific to those families. `tasks_heldout_family` (sparse_interaction, entirely unseen during meta-training — see Notebook 04) is the harder generalisation test: if SATA's advantage holds there too, it's evidence the selector learned something about demonstration relevance *in general*, not something tied to the specific rule shapes it was trained on.

In [4]:
from src.evaluation.faithfulness import hot_deck_impute_feature, compute_accuracy_drop
from src.evaluation.faithfulness_correctness import true_importance_scores, correctness_rho_from_scores

RQ4_CONDITIONS = ['best_protocol_sata', BEST_PROTOCOL]
heldout_family_paths = sorted((SYN_ROOT / 'tasks_heldout_family').glob('*.parquet'))

# Accuracy: test tasks (already covered by the RQ2 pass above) + held-out
# *family* tasks (sparse_interaction, never seen during SATA training) --
# only need to additionally run inference on the latter, for just these 2
# conditions.
for model_cfg in (config.base_llms if VLLM_AVAILABLE else []):
    # Same resume logic as the RQ2 loop above -- heldout_family_paths' task
    # ids never overlap with test_task_paths', so this is a no-op unless a
    # run was previously interrupted partway through this second loop.
    try:
        existing = load_results(RESULTS_PATH)
        done_task_ids = set(existing.loc[existing['model'] == model_cfg.name, 'dataset'])
    except FileNotFoundError:
        done_task_ids = set()
    remaining_heldout_paths = [p for p in heldout_family_paths if p.stem not in done_task_ids]
    n_heldout_done = len(done_task_ids & {p.stem for p in heldout_family_paths})
    print(f"{model_cfg.name}: {n_heldout_done} heldout tasks already done, {len(remaining_heldout_paths)} remaining")
    runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))
    evaluate_task_group(remaining_heldout_paths, model_cfg, runner, conditions=RQ4_CONDITIONS)
    runner.shutdown()

RQ4_ACC_COLS = ['task_group', 'method', 'shift_type', 'model', 'accuracy', 'macro_f1', 'invalid_rate', 'n']
try:
    synthetic_results = load_results(RESULTS_PATH)
except FileNotFoundError:
    synthetic_results = None

if synthetic_results is None or synthetic_results.empty:
    rq4_accuracy = pd.DataFrame(columns=RQ4_ACC_COLS)
else:
    # RQ4_CONDITIONS' methods were also run at k_sensitivity in the RQ2 pass
    # above (it sweeps all 10 conditions); RQ4 itself only ever evaluates at
    # k_primary, so without this filter the two 'test' task_group rows would
    # silently blend k_primary and k_sensitivity accuracy together.
    rq4_accuracy_source = synthetic_results[
        synthetic_results['method'].isin(RQ4_CONDITIONS) & (synthetic_results['k'] == config.k_primary)
    ].copy()
    rq4_accuracy_source['task_group'] = np.where(
        rq4_accuracy_source['dataset'].str.startswith('heldout_'), 'heldout_family', 'test'
    )
    rq4_accuracy = summarise(rq4_accuracy_source, group_cols=['task_group', 'method', 'environment', 'model'])
    rq4_accuracy = rq4_accuracy.rename(columns={'environment': 'shift_type'})

# Correctness-of-reliance faithfulness: rho(pi_behav, pi_true) per task, via
# the same LOO hot-deck ablation as Notebook 03, computed on the 'id'
# environment's query set for each condition. Sampled (not all 250 tasks --
# each task needs 1 + n_features reruns per condition) for tractability.
FAITHFULNESS_TASK_SAMPLE = 50
rng = np.random.default_rng(config.seed_faithfulness[0])
all_task_paths = test_task_paths + heldout_family_paths
faith_task_paths = list(rng.choice(
    all_task_paths, size=min(FAITHFULNESS_TASK_SAMPLE, len(all_task_paths)), replace=False
)) if VLLM_AVAILABLE else []

CORRECTNESS_COLS = ['task_id', 'model', 'method', 'rho', 'pval']
correctness_rows = []
for model_cfg in (config.base_llms if VLLM_AVAILABLE else []):
    runner = VLLMWorkerRunner(model_cfg.path, **vars(config.vllm))

    task_bar = tqdm(faith_task_paths, desc=f"RQ4 faithfulness tasks ({model_cfg.name})", leave=False)
    for task_path in task_bar:
        task_df = pd.read_parquet(task_path)
        task_id = task_path.stem
        task_bar.set_postfix(task=task_id)
        meta = json.load(open(task_path.parent / f'{task_id}_meta.json'))

        id_df = task_df[task_df['environment'] == 'id']
        pool = id_df[id_df['split'] == 'demo'].reset_index(drop=True)
        queries = id_df[id_df['split'] == 'query'].reset_index(drop=True)
        top3_continuous = select_top_features(pool[FEATURE_COLS + ['label']], n_features=3)
        similarity_demo_ids = (
            precompute_similarity_demo_ids(pool, queries, config.k_primary)
            if 'similarity' in RQ4_CONDITIONS else None
        )

        # Family-aware true-importance scores (see faithfulness_correctness.py):
        # only 'linear' actually reads `coefficients`, so `thresholds3`/
        # `leaf_labels` (via .get -- None for families that don't set them)
        # are needed to score 'threshold'/'tree' correctly rather than by an
        # unused random coefficient vector.
        true_scores = true_importance_scores(
            meta['rule_family'], config.generator.n_features, meta['causal_features'],
            np.array(meta['coefficients']), thresholds3=meta.get('thresholds3'), leaf_labels=meta.get('leaf_labels'),
        )

        for condition in RQ4_CONDITIONS:
            seed = config.seed_faithfulness[0]
            demo_ids_per_query = [
                select_demos_synthetic(condition, pool, row, config.k_primary, seed, top3_continuous, similarity_demo_ids)
                for _, row in queries.iterrows()
            ]

            def run_inference(df):
                prompts = [
                    build_classification_prompt(
                        TASK_DESCRIPTION, LABEL_TOKENS, build_demo_lines(pool, demo_ids), build_query_line(row)
                    )
                    for (_, row), demo_ids in zip(df.iterrows(), demo_ids_per_query)
                ]
                preds = runner.batch_predict(prompts, LABEL_TOKENS)
                return np.array([p.prediction == str(int(row['label'])) for p, (_, row) in zip(preds, df.iterrows())])

            original_correct = run_inference(queries)
            deltas = {}
            for feature in FEATURE_COLS:
                modified = hot_deck_impute_feature(queries, feature, pool, FEATURE_COLS, seed=seed)
                modified_correct = run_inference(modified)
                deltas[feature] = compute_accuracy_drop(original_correct, modified_correct)

            # Raw per-feature delta scores, not a hand-built rank permutation
            # -- spearmanr rank-transforms internally (average ranks for
            # ties), which is the right way to handle the many legitimate
            # zero-importance ties in `true_scores`.
            behav_scores = np.array([deltas[f'feature_{j}'] for j in range(config.generator.n_features)])
            result = correctness_rho_from_scores(true_scores, behav_scores)
            correctness_rows.append({
                'task_id': task_id, 'model': model_cfg.name, 'method': condition,
                'rho': result['rho'], 'pval': result['pval'],
            })

    runner.shutdown()

correctness_df = pd.DataFrame(correctness_rows, columns=CORRECTNESS_COLS)

if not VLLM_AVAILABLE:
    print("Skipped RQ4/faithfulness inference — vLLM not installed in this environment.")

if correctness_df.empty:
    rq4_faithfulness = pd.DataFrame(columns=['model', 'method', 'rho_mean', 'rho_std'])
else:
    rq4_faithfulness = correctness_df.groupby(['model', 'method'])['rho'].agg(['mean', 'std']).reset_index()
    rq4_faithfulness = rq4_faithfulness.rename(columns={'mean': 'rho_mean', 'std': 'rho_std'})

if rq4_accuracy.empty:
    rq4_comparison = rq4_accuracy.assign(rho_mean=[], rho_std=[])
else:
    rq4_comparison = rq4_accuracy.merge(rq4_faithfulness, on=['model', 'method'], how='left')

rq4_comparison.to_parquet(resolve_path('results/rq4_comparison.parquet'), index=False)
correctness_df.to_parquet(resolve_path('results/faithfulness_synthetic.parquet'), index=False)

rq4_comparison

Llama-3.1-8B-Instruct: 0 heldout tasks already done, 50 remaining

INFO 09-12 17:04:26 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 17:04:26 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 17:04:26 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 17:04:26 [model.py:2021] Using max model len 8192
INFO 09-12 17:04:26 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 17:04:26 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 17:04:28 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 17:04:29 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_08218edd17b74aaaae5e3095713807b7 backend=nccl
INFO 09-12 17:04:29 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 17:04:29 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 17:04:30 [model_runner.py:382] Loading model from scratch...
INFO 09-12 17:04:30 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 17:04:30 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 17:04:30 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 951.06 GiB.
INFO 09-12 17:04:30 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.07it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.06it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.06it/s]

Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:03<00:00,  1.51it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:03<00:00,  1.31it/s]

INFO 09-12 17:04:33 [default_loader.py:430] Loading weights took 3.07 seconds

INFO 09-12 17:04:34 [model_runner.py:404] Model loading took 15.0 GiB memory and 4.099162 seconds
INFO 09-12 17:04:34 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 17:04:34 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 17:04:34 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 17:04:34 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 17:04:34 [monitor.py:53] torch.compile took 0.14 s in total
INFO 09-12 17:04:34 [monitor.py:81] Initial profiling/warmup run took 0.13 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:03<01:12,  1.11it/s]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:03<00:23,  3.18it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:12,  5.65it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:04<00:08,  8.13it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:04<00:06, 10.56it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:04<00:04, 12.33it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 13.90it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:05<00:03, 15.23it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:05<00:02, 16.47it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:05<00:02, 17.70it/s]

Capturing CUDA graphs (PIECEWISE):  53%|█████▎    | 44/83 [00:06<00:02, 18.30it/s]

Capturing CUDA graphs (PIECEWISE):  60%|██████    | 50/83 [00:06<00:01, 19.75it/s]

Capturing CUDA graphs (PIECEWISE):  67%|██████▋   | 56/83 [00:06<00:01, 20.31it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:07<00:01, 20.33it/s]

Capturing CUDA graphs (PIECEWISE):  82%|████████▏ | 68/83 [00:07<00:00, 20.46it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:07<00:00, 20.21it/s]

Capturing CUDA graphs (PIECEWISE):  96%|█████████▋| 80/83 [00:07<00:00, 19.90it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:08<00:00, 10.29it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 20.98it/s]

INFO 09-12 17:04:44 [model_runner.py:960] Graph capturing finished in 8 secs, took 0.54 GiB

INFO 09-12 17:04:44 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 17:04:44 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8958 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9042. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 17:04:44 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,408 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 17:04:44 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 17:04:44 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 17:04:44 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 17:04:44 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 17:04:44 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 17:04:44 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 17:04:44 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 17:04:44 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 17:04:44 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 17:04:44 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 17:04:44 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 17:04:44 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 17:04:44 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 17:04:44 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 17:04:44 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 17:04:44 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 17:04:44 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 17:04:44 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 17:04:44 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 11.10it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.68it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 12.16it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.73it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:04, 13.61it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 14.51it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:01<00:03, 15.51it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 16.55it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:02, 17.66it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:02<00:02, 19.07it/s]

Capturing CUDA graphs (PIECEWISE):  54%|█████▍    | 45/83 [00:02<00:01, 20.50it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:03<00:01, 21.61it/s]

Capturing CUDA graphs (PIECEWISE):  69%|██████▊   | 57/83 [00:03<00:01, 22.05it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:03<00:01, 18.46it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:03<00:00, 18.26it/s]

Capturing CUDA graphs (PIECEWISE):  84%|████████▍ | 70/83 [00:04<00:00, 14.22it/s]

Capturing CUDA graphs (PIECEWISE):  89%|████████▉ | 74/83 [00:04<00:00, 13.14it/s]

Capturing CUDA graphs (PIECEWISE):  92%|█████████▏| 76/83 [00:04<00:00, 12.54it/s]

Capturing CUDA graphs (PIECEWISE):  96%|█████████▋| 80/83 [00:05<00:00, 12.59it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:05<00:00, 15.40it/s]
Capturing CUDA graphs (FULL):   4%|▎         | 3/83 [00:00<00:03, 21.41it/s]

Capturing CUDA graphs (FULL):  11%|█         | 9/83 [00:00<00:03, 22.69it/s]

Capturing CUDA graphs (FULL):  18%|█▊        | 15/83 [00:00<00:02, 24.09it/s]

Capturing CUDA graphs (FULL):  25%|██▌       | 21/83 [00:00<00:02, 26.62it/s]

Capturing CUDA graphs (FULL):  35%|███▍      | 29/83 [00:01<00:01, 30.11it/s]

Capturing CUDA graphs (FULL):  45%|████▍     | 37/83 [00:01<00:01, 34.09it/s]

Capturing CUDA graphs (FULL):  57%|█████▋    | 47/83 [00:01<00:00, 39.78it/s]

Capturing CUDA graphs (FULL):  69%|██████▊   | 57/83 [00:01<00:00, 44.39it/s]

Capturing CUDA graphs (FULL):  82%|████████▏ | 68/83 [00:01<00:00, 47.18it/s]

Capturing CUDA graphs (FULL):  95%|█████████▌| 79/83 [00:02<00:00, 48.95it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 16.27it/s]

INFO 09-12 17:04:55 [model_runner.py:960] Graph capturing finished in 11 secs, took 0.30 GiB
INFO 09-12 17:04:55 [gpu_worker.py:797] CUDA graph pool memory: 0.3 GiB (actual), 0.74 GiB (estimated), difference: 0.45 GiB (150.7%).
INFO 09-12 17:04:55 [gpu_worker.py:860] Free memory on device (177.12/178.34 GiB) on startup. Desired GPU memory utilization is (0.9, 160.51 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.43 GiB for peak activation, and 0.3 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152278255514` (141.82 GiB) to fit into requested memory, or `--kv-cache-memory=170115247616` (158.43 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 17:04:56 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 17:04:56 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 17:04:56 [core.py:361] init engine (profile, create kv cache, warmup model) took 22.46 s (compilation: 0.14 s)

INFO 09-12 17:04:57 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

Tasks (Llama-3.1-8B-Instruct):   0%|          | 0/50 [00:00<?, ?it/s]

Tasks (Llama-3.1-8B-Instruct):   0%|          | 0/50 [00:00<?, ?it/s, task=heldout_0000]

Rendering prompts:  43%|████▎     | 167/384 [00:00<00:00, 842.32it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 865.05it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 17:05:04 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 17:05:08 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CachedTokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Processed prompts:  18%|█▊        | 70/384 [00:04<00:15, 20.06it/s, est. speed input: 12461.27 toks/s, output: 14.34 toks/s]

Processed prompts:  38%|███▊      | 145/384 [00:05<00:04, 50.21it/s, est. speed input: 23951.52 toks/s, output: 27.56 toks/s]

Processed prompts:  57%|█████▋    | 218/384 [00:05<00:02, 82.20it/s, est. speed input: 33605.50 toks/s, output: 38.67 toks/s]

Processed prompts:  84%|████████▍ | 322/384 [00:06<00:00, 146.57it/s, est. speed input: 46318.32 toks/s, output: 53.52 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:06<00:00, 62.83it/s, est. speed input: 54408.72 toks/s, output: 62.83 toks/s]

Tasks (Llama-3.1-8B-Instruct):   0%|          | 0/50 [00:14<?, ?it/s, task=heldout_0000]

Tasks (Llama-3.1-8B-Instruct):   2%|▏         | 1/50 [00:14<11:48, 14.46s/it, task=heldout_0000]

Tasks (Llama-3.1-8B-Instruct):   2%|▏         | 1/50 [00:14<11:48, 14.46s/it, task=heldout_0001]

Llama-3.1-8B-Instruct | heldout_0000: done

Rendering prompts:  20%|█▉        | 76/384 [00:00<00:00, 751.43it/s]

Rendering prompts:  64%|██████▍   | 247/384 [00:00<00:00, 825.97it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 829.89it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 1675.58it/s, est. speed input: 1451663.92 toks/s, output: 1676.19 toks/s]

Tasks (Llama-3.1-8B-Instruct):   2%|▏         | 1/50 [00:18<11:48, 14.46s/it, task=heldout_0001]

Tasks (Llama-3.1-8B-Instruct):   4%|▍         | 2/50 [00:18<06:31,  8.16s/it, task=heldout_0001]

Tasks (Llama-3.1-8B-Instruct):   4%|▍         | 2/50 [00:18<06:31,  8.16s/it, task=heldout_0002]

Llama-3.1-8B-Instruct | heldout_0001: done

Rendering prompts:  40%|███▉      | 153/384 [00:00<00:00, 763.07it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 823.09it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   6%|▌         | 23/384 [00:00<00:05, 69.50it/s, est. speed input: 52040.36 toks/s, output: 59.88 toks/s]

Processed prompts:  25%|██▌       | 96/384 [00:00<00:02, 142.66it/s, est. speed input: 109481.09 toks/s, output: 125.98 toks/s]

Processed prompts:  38%|███▊      | 145/384 [00:00<00:01, 184.39it/s, est. speed input: 132503.82 toks/s, output: 152.48 toks/s]

Processed prompts:  51%|█████     | 194/384 [00:01<00:00, 197.06it/s, est. speed input: 143375.48 toks/s, output: 164.99 toks/s]

Processed prompts:  69%|██████▉   | 266/384 [00:01<00:00, 218.25it/s, est. speed input: 153194.71 toks/s, output: 176.42 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 203.46it/s, est. speed input: 176206.93 toks/s, output: 203.47 toks/s]

Tasks (Llama-3.1-8B-Instruct):   4%|▍         | 2/50 [00:29<06:31,  8.16s/it, task=heldout_0002]

Tasks (Llama-3.1-8B-Instruct):   6%|▌         | 3/50 [00:29<07:21,  9.40s/it, task=heldout_0002]

Tasks (Llama-3.1-8B-Instruct):   6%|▌         | 3/50 [00:29<07:21,  9.40s/it, task=heldout_0003]

Llama-3.1-8B-Instruct | heldout_0002: done

Rendering prompts:  20%|██        | 78/384 [00:00<00:00, 776.26it/s]

Rendering prompts:  66%|██████▌   | 253/384 [00:00<00:00, 847.35it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 838.13it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   6%|▌         | 23/384 [00:00<00:05, 69.51it/s, est. speed input: 52100.10 toks/s, output: 59.95 toks/s]

Processed prompts:  19%|█▉        | 73/384 [00:00<00:01, 161.01it/s, est. speed input: 112426.59 toks/s, output: 129.37 toks/s]

Processed prompts:  38%|███▊      | 147/384 [00:00<00:01, 193.06it/s, est. speed input: 133606.95 toks/s, output: 153.75 toks/s]

Processed prompts:  57%|█████▋    | 218/384 [00:01<00:01, 164.82it/s, est. speed input: 130450.56 toks/s, output: 150.11 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 245.09it/s, est. speed input: 212260.65 toks/s, output: 245.10 toks/s]

Tasks (Llama-3.1-8B-Instruct):   6%|▌         | 3/50 [00:34<07:21,  9.40s/it, task=heldout_0003]

Tasks (Llama-3.1-8B-Instruct):   8%|▊         | 4/50 [00:34<05:55,  7.73s/it, task=heldout_0003]

Tasks (Llama-3.1-8B-Instruct):   8%|▊         | 4/50 [00:34<05:55,  7.73s/it, task=heldout_0004]

Llama-3.1-8B-Instruct | heldout_0003: done

Rendering prompts:  39%|███▉      | 150/384 [00:00<00:00, 763.16it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 805.89it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 735.93it/s, est. speed input: 637468.50 toks/s, output: 736.10 toks/s]

Tasks (Llama-3.1-8B-Instruct):   8%|▊         | 4/50 [00:38<05:55,  7.73s/it, task=heldout_0004]

Tasks (Llama-3.1-8B-Instruct):  10%|█         | 5/50 [00:38<04:53,  6.52s/it, task=heldout_0004]

Tasks (Llama-3.1-8B-Instruct):  10%|█         | 5/50 [00:38<04:53,  6.52s/it, task=heldout_0005]

Llama-3.1-8B-Instruct | heldout_0004: done

Rendering prompts:  20%|██        | 77/384 [00:00<00:00, 764.91it/s]

Rendering prompts:  65%|██████▌   | 250/384 [00:00<00:00, 837.16it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 826.20it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<01:15,  5.09it/s, est. speed input: 4423.44 toks/s, output: 5.09 toks/s]

Processed prompts:   7%|▋         | 25/384 [00:00<00:05, 69.19it/s, est. speed input: 52232.04 toks/s, output: 60.10 toks/s]

Processed prompts:  34%|███▎      | 129/384 [00:00<00:01, 223.81it/s, est. speed input: 148714.72 toks/s, output: 171.13 toks/s]

Processed prompts:  53%|█████▎    | 202/384 [00:01<00:00, 212.93it/s, est. speed input: 155581.73 toks/s, output: 179.03 toks/s]

Processed prompts:  72%|███████▏  | 275/384 [00:01<00:00, 203.99it/s, est. speed input: 156418.48 toks/s, output: 180.25 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 218.97it/s, est. speed input: 189638.63 toks/s, output: 218.98 toks/s]

Tasks (Llama-3.1-8B-Instruct):  10%|█         | 5/50 [00:43<04:53,  6.52s/it, task=heldout_0005]

Tasks (Llama-3.1-8B-Instruct):  12%|█▏        | 6/50 [00:43<04:21,  5.94s/it, task=heldout_0005]

Tasks (Llama-3.1-8B-Instruct):  12%|█▏        | 6/50 [00:43<04:21,  5.94s/it, task=heldout_0006]

Llama-3.1-8B-Instruct | heldout_0005: done

Rendering prompts:  20%|█▉        | 75/384 [00:00<00:00, 742.30it/s]

Rendering prompts:  63%|██████▎   | 241/384 [00:00<00:00, 781.43it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 531.58it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  24%|██▎       | 91/384 [00:00<00:01, 171.03it/s, est. speed input: 112636.50 toks/s, output: 129.61 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 422.20it/s, est. speed input: 365676.28 toks/s, output: 422.26 toks/s]

Tasks (Llama-3.1-8B-Instruct):  12%|█▏        | 6/50 [00:47<04:21,  5.94s/it, task=heldout_0006]

Tasks (Llama-3.1-8B-Instruct):  14%|█▍        | 7/50 [00:47<03:53,  5.44s/it, task=heldout_0006]

Tasks (Llama-3.1-8B-Instruct):  14%|█▍        | 7/50 [00:47<03:53,  5.44s/it, task=heldout_0007]

Llama-3.1-8B-Instruct | heldout_0006: done

Rendering prompts:  19%|█▉        | 74/384 [00:00<00:00, 734.12it/s]

Rendering prompts:  53%|█████▎    | 205/384 [00:00<00:00, 484.51it/s]

Rendering prompts:  78%|███████▊  | 299/384 [00:00<00:00, 403.08it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 434.59it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 779.23it/s, est. speed input: 674987.75 toks/s, output: 779.42 toks/s]

Tasks (Llama-3.1-8B-Instruct):  14%|█▍        | 7/50 [00:51<03:53,  5.44s/it, task=heldout_0007]

Tasks (Llama-3.1-8B-Instruct):  16%|█▌        | 8/50 [00:51<03:29,  4.98s/it, task=heldout_0007]

Tasks (Llama-3.1-8B-Instruct):  16%|█▌        | 8/50 [00:51<03:29,  4.98s/it, task=heldout_0008]

Llama-3.1-8B-Instruct | heldout_0007: done

Rendering prompts:  21%|██        | 79/384 [00:00<00:00, 783.65it/s]

Rendering prompts:  64%|██████▎   | 244/384 [00:00<00:00, 809.07it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 821.76it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<01:44,  3.68it/s, est. speed input: 3196.88 toks/s, output: 3.68 toks/s]

Processed prompts:  23%|██▎       | 88/384 [00:00<00:01, 175.82it/s, est. speed input: 131773.33 toks/s, output: 151.63 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 436.54it/s, est. speed input: 378122.28 toks/s, output: 436.63 toks/s]

Tasks (Llama-3.1-8B-Instruct):  16%|█▌        | 8/50 [00:56<03:29,  4.98s/it, task=heldout_0008]

Tasks (Llama-3.1-8B-Instruct):  18%|█▊        | 9/50 [00:56<03:19,  4.86s/it, task=heldout_0008]

Tasks (Llama-3.1-8B-Instruct):  18%|█▊        | 9/50 [00:56<03:19,  4.86s/it, task=heldout_0009]

Llama-3.1-8B-Instruct | heldout_0008: done

Rendering prompts:  20%|██        | 77/384 [00:00<00:00, 765.85it/s]

Rendering prompts:  62%|██████▎   | 240/384 [00:00<00:00, 800.78it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 812.63it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 640.82it/s, est. speed input: 555041.58 toks/s, output: 640.92 toks/s]

Tasks (Llama-3.1-8B-Instruct):  18%|█▊        | 9/50 [01:00<03:19,  4.86s/it, task=heldout_0009]

Tasks (Llama-3.1-8B-Instruct):  20%|██        | 10/50 [01:00<03:06,  4.67s/it, task=heldout_0009]

Tasks (Llama-3.1-8B-Instruct):  20%|██        | 10/50 [01:00<03:06,  4.67s/it, task=heldout_0010]

Llama-3.1-8B-Instruct | heldout_0009: done

Rendering prompts:  40%|████      | 155/384 [00:00<00:00, 782.90it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 800.99it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   6%|▋         | 24/384 [00:00<00:04, 72.54it/s, est. speed input: 54218.70 toks/s, output: 62.39 toks/s]

Processed prompts:  19%|█▉        | 73/384 [00:00<00:01, 161.91it/s, est. speed input: 113066.06 toks/s, output: 130.11 toks/s]

Processed prompts:  38%|███▊      | 145/384 [00:00<00:01, 189.87it/s, est. speed input: 132598.37 toks/s, output: 152.59 toks/s]

Processed prompts:  51%|█████     | 195/384 [00:01<00:00, 219.51it/s, est. speed input: 150004.85 toks/s, output: 172.62 toks/s]

Processed prompts:  71%|███████   | 272/384 [00:01<00:00, 213.04it/s, est. speed input: 154869.38 toks/s, output: 178.43 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 212.91it/s, est. speed input: 184398.57 toks/s, output: 212.93 toks/s]

Tasks (Llama-3.1-8B-Instruct):  20%|██        | 10/50 [01:05<03:06,  4.67s/it, task=heldout_0010]

Tasks (Llama-3.1-8B-Instruct):  22%|██▏       | 11/50 [01:05<03:07,  4.81s/it, task=heldout_0010]

Tasks (Llama-3.1-8B-Instruct):  22%|██▏       | 11/50 [01:05<03:07,  4.81s/it, task=heldout_0011]

Llama-3.1-8B-Instruct | heldout_0010: done

Rendering prompts:  19%|█▉        | 73/384 [00:00<00:00, 724.06it/s]

Rendering prompts:  53%|█████▎    | 202/384 [00:00<00:00, 512.60it/s]

Rendering prompts:  81%|████████▏ | 312/384 [00:00<00:00, 435.18it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 426.54it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 682.24it/s, est. speed input: 590938.11 toks/s, output: 682.37 toks/s]

Tasks (Llama-3.1-8B-Instruct):  22%|██▏       | 11/50 [01:10<03:07,  4.81s/it, task=heldout_0011]

Tasks (Llama-3.1-8B-Instruct):  24%|██▍       | 12/50 [01:10<02:55,  4.62s/it, task=heldout_0011]

Tasks (Llama-3.1-8B-Instruct):  24%|██▍       | 12/50 [01:10<02:55,  4.62s/it, task=heldout_0012]

Llama-3.1-8B-Instruct | heldout_0011: done

Rendering prompts:  19%|█▉        | 74/384 [00:00<00:00, 731.57it/s]

Rendering prompts:  62%|██████▏   | 237/384 [00:00<00:00, 792.42it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 804.11it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<01:15,  5.09it/s, est. speed input: 4421.16 toks/s, output: 5.09 toks/s]

Processed prompts:  20%|██        | 78/384 [00:00<00:01, 158.54it/s, est. speed input: 112204.83 toks/s, output: 129.12 toks/s]

Processed prompts:  34%|███▎      | 129/384 [00:00<00:01, 213.06it/s, est. speed input: 146655.20 toks/s, output: 168.76 toks/s]

Processed prompts:  40%|███▉      | 152/384 [00:00<00:01, 165.24it/s, est. speed input: 132266.46 toks/s, output: 152.20 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 240.78it/s, est. speed input: 208524.79 toks/s, output: 240.79 toks/s]

Tasks (Llama-3.1-8B-Instruct):  24%|██▍       | 12/50 [01:14<02:55,  4.62s/it, task=heldout_0012]

Tasks (Llama-3.1-8B-Instruct):  26%|██▌       | 13/50 [01:14<02:53,  4.70s/it, task=heldout_0012]

Tasks (Llama-3.1-8B-Instruct):  26%|██▌       | 13/50 [01:14<02:53,  4.70s/it, task=heldout_0013]

Llama-3.1-8B-Instruct | heldout_0012: done

Rendering prompts:  19%|█▉        | 74/384 [00:00<00:00, 738.75it/s]

Rendering prompts:  61%|██████    | 233/384 [00:00<00:00, 589.50it/s]

Rendering prompts:  92%|█████████▏| 353/384 [00:00<00:00, 443.91it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 485.60it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 773.91it/s, est. speed input: 670356.16 toks/s, output: 774.08 toks/s]

Tasks (Llama-3.1-8B-Instruct):  26%|██▌       | 13/50 [01:19<02:53,  4.70s/it, task=heldout_0013]

Tasks (Llama-3.1-8B-Instruct):  28%|██▊       | 14/50 [01:19<02:44,  4.56s/it, task=heldout_0013]

Tasks (Llama-3.1-8B-Instruct):  28%|██▊       | 14/50 [01:19<02:44,  4.56s/it, task=heldout_0014]

Llama-3.1-8B-Instruct | heldout_0013: done

Rendering prompts:  40%|███▉      | 152/384 [00:00<00:00, 762.20it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 805.51it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<01:12,  5.26it/s, est. speed input: 4572.99 toks/s, output: 5.26 toks/s]

Processed prompts:  19%|█▉        | 74/384 [00:00<00:01, 157.12it/s, est. speed input: 109459.36 toks/s, output: 125.96 toks/s]

Processed prompts:  25%|██▌       | 97/384 [00:00<00:01, 147.20it/s, est. speed input: 110361.81 toks/s, output: 126.99 toks/s]

Processed prompts:  51%|█████▏    | 197/384 [00:01<00:00, 204.87it/s, est. speed input: 144404.96 toks/s, output: 166.17 toks/s]

Processed prompts:  71%|███████   | 272/384 [00:01<00:00, 215.94it/s, est. speed input: 154552.57 toks/s, output: 178.07 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 213.82it/s, est. speed input: 185186.38 toks/s, output: 213.84 toks/s]

Tasks (Llama-3.1-8B-Instruct):  28%|██▊       | 14/50 [01:24<02:44,  4.56s/it, task=heldout_0014]

Tasks (Llama-3.1-8B-Instruct):  30%|███       | 15/50 [01:24<02:43,  4.67s/it, task=heldout_0014]

Tasks (Llama-3.1-8B-Instruct):  30%|███       | 15/50 [01:24<02:43,  4.67s/it, task=heldout_0015]

Llama-3.1-8B-Instruct | heldout_0014: done

Rendering prompts:   6%|▌         | 22/384 [00:00<00:01, 219.46it/s]

Rendering prompts:  26%|██▌       | 100/384 [00:00<00:00, 371.00it/s]

Rendering prompts:  45%|████▌     | 173/384 [00:00<00:00, 325.52it/s]

Rendering prompts:  62%|██████▎   | 240/384 [00:00<00:00, 305.28it/s]

Rendering prompts:  87%|████████▋ | 333/384 [00:00<00:00, 356.85it/s]

Rendering prompts: 100%|██████████| 384/384 [00:01<00:00, 350.74it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 648.05it/s, est. speed input: 561309.71 toks/s, output: 648.16 toks/s]

Tasks (Llama-3.1-8B-Instruct):  30%|███       | 15/50 [01:29<02:43,  4.67s/it, task=heldout_0015]

Tasks (Llama-3.1-8B-Instruct):  32%|███▏      | 16/50 [01:29<02:43,  4.81s/it, task=heldout_0015]

Tasks (Llama-3.1-8B-Instruct):  32%|███▏      | 16/50 [01:29<02:43,  4.81s/it, task=heldout_0016]

Llama-3.1-8B-Instruct | heldout_0015: done

Rendering prompts:  19%|█▉        | 74/384 [00:00<00:00, 735.68it/s]

Rendering prompts:  62%|██████▏   | 239/384 [00:00<00:00, 798.66it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 630.98it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   7%|▋         | 26/384 [00:00<00:04, 75.97it/s, est. speed input: 56766.19 toks/s, output: 65.32 toks/s]

Processed prompts:  34%|███▎      | 129/384 [00:00<00:01, 205.24it/s, est. speed input: 144086.64 toks/s, output: 165.80 toks/s]

Processed prompts:  53%|█████▎    | 203/384 [00:01<00:00, 199.44it/s, est. speed input: 148553.74 toks/s, output: 170.95 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 261.08it/s, est. speed input: 226116.54 toks/s, output: 261.10 toks/s]

Tasks (Llama-3.1-8B-Instruct):  32%|███▏      | 16/50 [01:33<02:43,  4.81s/it, task=heldout_0016]

Tasks (Llama-3.1-8B-Instruct):  34%|███▍      | 17/50 [01:33<02:36,  4.75s/it, task=heldout_0016]

Tasks (Llama-3.1-8B-Instruct):  34%|███▍      | 17/50 [01:33<02:36,  4.75s/it, task=heldout_0017]

Llama-3.1-8B-Instruct | heldout_0016: done

Rendering prompts:  11%|█         | 42/384 [00:00<00:00, 417.93it/s]

Rendering prompts:  41%|████      | 156/384 [00:00<00:00, 374.96it/s]

Rendering prompts:  70%|██████▉   | 267/384 [00:00<00:00, 374.58it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 427.13it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 991.13it/s, est. speed input: 858567.81 toks/s, output: 991.41 toks/s]

Tasks (Llama-3.1-8B-Instruct):  34%|███▍      | 17/50 [01:39<02:36,  4.75s/it, task=heldout_0017]

Tasks (Llama-3.1-8B-Instruct):  36%|███▌      | 18/50 [01:39<02:42,  5.07s/it, task=heldout_0017]

Tasks (Llama-3.1-8B-Instruct):  36%|███▌      | 18/50 [01:39<02:42,  5.07s/it, task=heldout_0018]

Llama-3.1-8B-Instruct | heldout_0017: done

Rendering prompts:  20%|█▉        | 76/384 [00:00<00:00, 755.53it/s]

Rendering prompts:  63%|██████▎   | 241/384 [00:00<00:00, 775.55it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 558.40it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  17%|█▋        | 67/384 [00:00<00:01, 214.01it/s, est. speed input: 146059.01 toks/s, output: 168.07 toks/s]

Processed prompts:  55%|█████▍    | 211/384 [00:00<00:00, 320.62it/s, est. speed input: 219772.39 toks/s, output: 252.90 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 348.53it/s, est. speed input: 301860.79 toks/s, output: 348.57 toks/s]

Tasks (Llama-3.1-8B-Instruct):  36%|███▌      | 18/50 [01:43<02:42,  5.07s/it, task=heldout_0018]

Tasks (Llama-3.1-8B-Instruct):  38%|███▊      | 19/50 [01:43<02:28,  4.80s/it, task=heldout_0018]

Tasks (Llama-3.1-8B-Instruct):  38%|███▊      | 19/50 [01:43<02:28,  4.80s/it, task=heldout_0019]

Llama-3.1-8B-Instruct | heldout_0018: done

Rendering prompts:  41%|████      | 157/384 [00:00<00:00, 790.00it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 822.41it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 717.62it/s, est. speed input: 621634.26 toks/s, output: 717.82 toks/s]

Tasks (Llama-3.1-8B-Instruct):  38%|███▊      | 19/50 [01:47<02:28,  4.80s/it, task=heldout_0019]

Tasks (Llama-3.1-8B-Instruct):  40%|████      | 20/50 [01:47<02:17,  4.59s/it, task=heldout_0019]

Tasks (Llama-3.1-8B-Instruct):  40%|████      | 20/50 [01:47<02:17,  4.59s/it, task=heldout_0020]

Llama-3.1-8B-Instruct | heldout_0019: done

Rendering prompts:  19%|█▉        | 73/384 [00:00<00:00, 725.26it/s]

Rendering prompts:  83%|████████▎ | 319/384 [00:00<00:00, 806.89it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 796.13it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 876.82it/s, est. speed input: 759513.66 toks/s, output: 877.03 toks/s]

Tasks (Llama-3.1-8B-Instruct):  40%|████      | 20/50 [01:52<02:17,  4.59s/it, task=heldout_0020]

Tasks (Llama-3.1-8B-Instruct):  42%|████▏     | 21/50 [01:52<02:10,  4.50s/it, task=heldout_0020]

Tasks (Llama-3.1-8B-Instruct):  42%|████▏     | 21/50 [01:52<02:10,  4.50s/it, task=heldout_0021]

Llama-3.1-8B-Instruct | heldout_0020: done

Rendering prompts:  18%|█▊        | 70/384 [00:00<00:00, 697.61it/s]

Rendering prompts:  58%|█████▊    | 222/384 [00:00<00:00, 750.47it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 727.31it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   7%|▋         | 26/384 [00:00<00:04, 79.89it/s, est. speed input: 57980.64 toks/s, output: 66.72 toks/s]

Processed prompts:  28%|██▊       | 108/384 [00:00<00:01, 154.66it/s, est. speed input: 114464.02 toks/s, output: 131.72 toks/s]

Processed prompts:  52%|█████▏    | 199/384 [00:01<00:00, 221.81it/s, est. speed input: 151636.25 toks/s, output: 174.49 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 251.43it/s, est. speed input: 217747.58 toks/s, output: 251.44 toks/s]

Tasks (Llama-3.1-8B-Instruct):  42%|████▏     | 21/50 [01:56<02:10,  4.50s/it, task=heldout_0021]

Tasks (Llama-3.1-8B-Instruct):  44%|████▍     | 22/50 [01:56<02:07,  4.54s/it, task=heldout_0021]

Tasks (Llama-3.1-8B-Instruct):  44%|████▍     | 22/50 [01:56<02:07,  4.54s/it, task=heldout_0022]

Llama-3.1-8B-Instruct | heldout_0021: done

Rendering prompts:  15%|█▌        | 59/384 [00:00<00:00, 588.51it/s]

Rendering prompts:  46%|████▌     | 177/384 [00:00<00:00, 451.70it/s]

Rendering prompts:  74%|███████▍  | 286/384 [00:00<00:00, 420.55it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 452.79it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 606.52it/s, est. speed input: 525314.40 toks/s, output: 606.59 toks/s]

Tasks (Llama-3.1-8B-Instruct):  44%|████▍     | 22/50 [02:00<02:07,  4.54s/it, task=heldout_0022]

Tasks (Llama-3.1-8B-Instruct):  46%|████▌     | 23/50 [02:00<01:59,  4.43s/it, task=heldout_0022]

Tasks (Llama-3.1-8B-Instruct):  46%|████▌     | 23/50 [02:00<01:59,  4.43s/it, task=heldout_0023]

Llama-3.1-8B-Instruct | heldout_0022: done

Rendering prompts:  18%|█▊        | 70/384 [00:00<00:00, 698.36it/s]

Rendering prompts:  54%|█████▍    | 208/384 [00:00<00:00, 556.26it/s]

Rendering prompts:  83%|████████▎ | 318/384 [00:00<00:00, 477.84it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 492.73it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 630.26it/s, est. speed input: 545896.48 toks/s, output: 630.36 toks/s]

Tasks (Llama-3.1-8B-Instruct):  46%|████▌     | 23/50 [02:05<01:59,  4.43s/it, task=heldout_0023]

Tasks (Llama-3.1-8B-Instruct):  48%|████▊     | 24/50 [02:05<01:54,  4.39s/it, task=heldout_0023]

Tasks (Llama-3.1-8B-Instruct):  48%|████▊     | 24/50 [02:05<01:54,  4.39s/it, task=heldout_0024]

Llama-3.1-8B-Instruct | heldout_0023: done

Rendering prompts:  19%|█▉        | 72/384 [00:00<00:00, 718.29it/s]

Rendering prompts:  62%|██████▎   | 240/384 [00:00<00:00, 810.51it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 815.18it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 1574.12it/s, est. speed input: 1363664.98 toks/s, output: 1574.65 toks/s]

Tasks (Llama-3.1-8B-Instruct):  48%|████▊     | 24/50 [02:09<01:54,  4.39s/it, task=heldout_0024]

Tasks (Llama-3.1-8B-Instruct):  50%|█████     | 25/50 [02:09<01:45,  4.22s/it, task=heldout_0024]

Tasks (Llama-3.1-8B-Instruct):  50%|█████     | 25/50 [02:09<01:45,  4.22s/it, task=heldout_0025]

Llama-3.1-8B-Instruct | heldout_0024: done

Rendering prompts:  20%|█▉        | 76/384 [00:00<00:00, 757.95it/s]

Rendering prompts:  87%|████████▋ | 334/384 [00:00<00:00, 848.30it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 835.20it/s]
Processed prompts:   0%|          | 1/384 [00:00<01:13,  5.23it/s, est. speed input: 4542.65 toks/s, output: 5.23 toks/s]

Processed prompts:   6%|▌         | 23/384 [00:00<00:05, 70.14it/s, est. speed input: 52458.06 toks/s, output: 60.36 toks/s]

Processed prompts:  25%|██▌       | 96/384 [00:00<00:01, 146.43it/s, est. speed input: 109635.46 toks/s, output: 126.16 toks/s]

Processed prompts:  51%|█████     | 196/384 [00:01<00:00, 221.42it/s, est. speed input: 151798.96 toks/s, output: 174.68 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 250.56it/s, est. speed input: 217001.98 toks/s, output: 250.58 toks/s]

Tasks (Llama-3.1-8B-Instruct):  50%|█████     | 25/50 [02:17<01:45,  4.22s/it, task=heldout_0025]

Tasks (Llama-3.1-8B-Instruct):  52%|█████▏    | 26/50 [02:17<02:13,  5.56s/it, task=heldout_0025]

Tasks (Llama-3.1-8B-Instruct):  52%|█████▏    | 26/50 [02:17<02:13,  5.56s/it, task=heldout_0026]

Llama-3.1-8B-Instruct | heldout_0025: done

Rendering prompts:  19%|█▉        | 72/384 [00:00<00:00, 716.08it/s]

Rendering prompts:  60%|█████▉    | 230/384 [00:00<00:00, 749.12it/s]

Rendering prompts:  95%|█████████▌| 365/384 [00:00<00:00, 454.66it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 499.66it/s]
Processed prompts:   0%|          | 1/384 [00:00<01:15,  5.05it/s, est. speed input: 4389.62 toks/s, output: 5.05 toks/s]

Processed prompts:  20%|█▉        | 75/384 [00:00<00:01, 155.44it/s, est. speed input: 109072.74 toks/s, output: 125.51 toks/s]

Processed prompts:  28%|██▊       | 109/384 [00:00<00:01, 162.43it/s, est. speed input: 119334.32 toks/s, output: 137.32 toks/s]

Processed prompts:  52%|█████▏    | 200/384 [00:01<00:00, 228.84it/s, est. speed input: 153169.32 toks/s, output: 176.26 toks/s]

Processed prompts:  72%|███████▏  | 275/384 [00:01<00:00, 213.97it/s, est. speed input: 156311.32 toks/s, output: 180.13 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 219.33it/s, est. speed input: 189950.87 toks/s, output: 219.34 toks/s]

Tasks (Llama-3.1-8B-Instruct):  52%|█████▏    | 26/50 [02:22<02:13,  5.56s/it, task=heldout_0026]

Tasks (Llama-3.1-8B-Instruct):  54%|█████▍    | 27/50 [02:22<02:03,  5.39s/it, task=heldout_0026]

Tasks (Llama-3.1-8B-Instruct):  54%|█████▍    | 27/50 [02:22<02:03,  5.39s/it, task=heldout_0027]

Llama-3.1-8B-Instruct | heldout_0026: done

Rendering prompts:  13%|█▎        | 50/384 [00:00<00:00, 498.70it/s]

Rendering prompts:  38%|███▊      | 144/384 [00:00<00:00, 418.01it/s]

Rendering prompts:  60%|█████▉    | 230/384 [00:00<00:00, 368.41it/s]

Rendering prompts:  89%|████████▉ | 341/384 [00:00<00:00, 433.91it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 423.03it/s]
Processed prompts:   0%|          | 1/384 [00:00<01:14,  5.12it/s, est. speed input: 4447.18 toks/s, output: 5.12 toks/s]

Processed prompts:  20%|██        | 78/384 [00:00<00:01, 165.82it/s, est. speed input: 117507.29 toks/s, output: 135.22 toks/s]

Processed prompts:  40%|███▉      | 153/384 [00:00<00:01, 177.53it/s, est. speed input: 139598.36 toks/s, output: 160.64 toks/s]

Processed prompts:  53%|█████▎    | 204/384 [00:01<00:00, 208.15it/s, est. speed input: 155091.14 toks/s, output: 178.47 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 264.21it/s, est. speed input: 228820.98 toks/s, output: 264.23 toks/s]

Tasks (Llama-3.1-8B-Instruct):  54%|█████▍    | 27/50 [02:36<02:03,  5.39s/it, task=heldout_0027]

Tasks (Llama-3.1-8B-Instruct):  56%|█████▌    | 28/50 [02:36<02:56,  8.02s/it, task=heldout_0027]

Tasks (Llama-3.1-8B-Instruct):  56%|█████▌    | 28/50 [02:36<02:56,  8.02s/it, task=heldout_0028]

Llama-3.1-8B-Instruct | heldout_0027: done

Rendering prompts:  17%|█▋        | 67/384 [00:00<00:00, 669.27it/s]

Rendering prompts:  53%|█████▎    | 204/384 [00:00<00:00, 449.66it/s]

Rendering prompts:  88%|████████▊ | 337/384 [00:00<00:00, 436.02it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 445.84it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 724.64it/s, est. speed input: 627734.66 toks/s, output: 724.86 toks/s]

Tasks (Llama-3.1-8B-Instruct):  56%|█████▌    | 28/50 [02:41<02:56,  8.02s/it, task=heldout_0028]

Tasks (Llama-3.1-8B-Instruct):  58%|█████▊    | 29/50 [02:41<02:24,  6.87s/it, task=heldout_0028]

Tasks (Llama-3.1-8B-Instruct):  58%|█████▊    | 29/50 [02:41<02:24,  6.87s/it, task=heldout_0029]

Llama-3.1-8B-Instruct | heldout_0028: done

Rendering prompts:  20%|█▉        | 75/384 [00:00<00:00, 746.17it/s]

Rendering prompts:  62%|██████▏   | 238/384 [00:00<00:00, 623.40it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 563.92it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  18%|█▊        | 68/384 [00:00<00:01, 180.70it/s, est. speed input: 127463.48 toks/s, output: 146.67 toks/s]

Processed prompts:  24%|██▍       | 94/384 [00:00<00:02, 144.85it/s, est. speed input: 115376.45 toks/s, output: 132.77 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 383.56it/s, est. speed input: 332206.43 toks/s, output: 383.61 toks/s]

Tasks (Llama-3.1-8B-Instruct):  58%|█████▊    | 29/50 [02:45<02:24,  6.87s/it, task=heldout_0029]

Tasks (Llama-3.1-8B-Instruct):  60%|██████    | 30/50 [02:45<02:01,  6.09s/it, task=heldout_0029]

Tasks (Llama-3.1-8B-Instruct):  60%|██████    | 30/50 [02:45<02:01,  6.09s/it, task=heldout_0030]

Llama-3.1-8B-Instruct | heldout_0029: done

Rendering prompts:  19%|█▉        | 72/384 [00:00<00:00, 719.11it/s]

Rendering prompts:  84%|████████▍ | 322/384 [00:00<00:00, 818.16it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 809.99it/s]
Processed prompts:   0%|          | 1/384 [00:00<01:16,  5.03it/s, est. speed input: 4372.79 toks/s, output: 5.03 toks/s]

Processed prompts:  19%|█▉        | 74/384 [00:00<00:01, 167.49it/s, est. speed input: 113905.51 toks/s, output: 131.07 toks/s]

Processed prompts:  38%|███▊      | 147/384 [00:01<00:01, 173.93it/s, est. speed input: 126401.18 toks/s, output: 145.45 toks/s]

Processed prompts:  52%|█████▏    | 198/384 [00:01<00:00, 231.35it/s, est. speed input: 151897.69 toks/s, output: 174.79 toks/s]

Processed prompts:  71%|███████▏  | 274/384 [00:01<00:00, 215.18it/s, est. speed input: 155572.69 toks/s, output: 179.27 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 223.02it/s, est. speed input: 193151.42 toks/s, output: 223.04 toks/s]

Tasks (Llama-3.1-8B-Instruct):  60%|██████    | 30/50 [02:50<02:01,  6.09s/it, task=heldout_0030]

Tasks (Llama-3.1-8B-Instruct):  62%|██████▏   | 31/50 [02:50<01:47,  5.68s/it, task=heldout_0030]

Tasks (Llama-3.1-8B-Instruct):  62%|██████▏   | 31/50 [02:50<01:47,  5.68s/it, task=heldout_0031]

Llama-3.1-8B-Instruct | heldout_0030: done

Rendering prompts:  20%|█▉        | 76/384 [00:00<00:00, 754.54it/s]

Rendering prompts:  63%|██████▎   | 241/384 [00:00<00:00, 774.30it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 688.54it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<02:50,  2.24it/s, est. speed input: 1948.97 toks/s, output: 2.24 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 477.20it/s, est. speed input: 413328.37 toks/s, output: 477.28 toks/s]

Tasks (Llama-3.1-8B-Instruct):  62%|██████▏   | 31/50 [02:54<01:47,  5.68s/it, task=heldout_0031]

Tasks (Llama-3.1-8B-Instruct):  64%|██████▍   | 32/50 [02:54<01:35,  5.30s/it, task=heldout_0031]

Tasks (Llama-3.1-8B-Instruct):  64%|██████▍   | 32/50 [02:54<01:35,  5.30s/it, task=heldout_0032]

Llama-3.1-8B-Instruct | heldout_0031: done

Rendering prompts:  20%|██        | 77/384 [00:00<00:00, 763.64it/s]

Rendering prompts:  65%|██████▍   | 248/384 [00:00<00:00, 830.45it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 635.97it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<01:33,  4.09it/s, est. speed input: 3556.11 toks/s, output: 4.09 toks/s]

Processed prompts:  19%|█▉        | 74/384 [00:00<00:01, 172.59it/s, est. speed input: 112212.78 toks/s, output: 129.13 toks/s]

Processed prompts:  39%|███▊      | 148/384 [00:00<00:01, 188.40it/s, est. speed input: 133220.28 toks/s, output: 153.30 toks/s]

Processed prompts:  52%|█████▏    | 198/384 [00:01<00:00, 217.86it/s, est. speed input: 150178.99 toks/s, output: 172.82 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 255.39it/s, est. speed input: 221183.21 toks/s, output: 255.41 toks/s]

Tasks (Llama-3.1-8B-Instruct):  64%|██████▍   | 32/50 [02:59<01:35,  5.30s/it, task=heldout_0032]

Tasks (Llama-3.1-8B-Instruct):  66%|██████▌   | 33/50 [02:59<01:26,  5.10s/it, task=heldout_0032]

Tasks (Llama-3.1-8B-Instruct):  66%|██████▌   | 33/50 [02:59<01:26,  5.10s/it, task=heldout_0033]

Llama-3.1-8B-Instruct | heldout_0032: done

Rendering prompts:  20%|█▉        | 75/384 [00:00<00:00, 746.42it/s]

Rendering prompts:  53%|█████▎    | 205/384 [00:00<00:00, 504.45it/s]

Rendering prompts:  85%|████████▌ | 328/384 [00:00<00:00, 543.48it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 481.04it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   8%|▊         | 32/384 [00:00<00:03, 93.53it/s, est. speed input: 69661.82 toks/s, output: 80.16 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 469.26it/s, est. speed input: 406458.33 toks/s, output: 469.35 toks/s]

Tasks (Llama-3.1-8B-Instruct):  66%|██████▌   | 33/50 [03:03<01:26,  5.10s/it, task=heldout_0033]

Tasks (Llama-3.1-8B-Instruct):  68%|██████▊   | 34/50 [03:03<01:17,  4.85s/it, task=heldout_0033]

Tasks (Llama-3.1-8B-Instruct):  68%|██████▊   | 34/50 [03:03<01:17,  4.85s/it, task=heldout_0034]

Llama-3.1-8B-Instruct | heldout_0033: done

Rendering prompts:  18%|█▊        | 68/384 [00:00<00:00, 677.20it/s]

Rendering prompts:  49%|████▉     | 190/384 [00:00<00:00, 491.45it/s]

Rendering prompts:  78%|███████▊  | 299/384 [00:00<00:00, 429.80it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 407.98it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:  56%|█████▌    | 214/384 [00:00<00:00, 441.70it/s, est. speed input: 303071.07 toks/s, output: 348.75 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 602.56it/s, est. speed input: 521908.53 toks/s, output: 602.66 toks/s]

Tasks (Llama-3.1-8B-Instruct):  68%|██████▊   | 34/50 [03:07<01:17,  4.85s/it, task=heldout_0034]

Tasks (Llama-3.1-8B-Instruct):  70%|███████   | 35/50 [03:07<01:09,  4.66s/it, task=heldout_0034]

Tasks (Llama-3.1-8B-Instruct):  70%|███████   | 35/50 [03:07<01:09,  4.66s/it, task=heldout_0035]

Llama-3.1-8B-Instruct | heldout_0034: done

Rendering prompts:  20%|█▉        | 76/384 [00:00<00:00, 753.44it/s]

Rendering prompts:  64%|██████▎   | 244/384 [00:00<00:00, 819.40it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 829.51it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 981.05it/s, est. speed input: 849818.30 toks/s, output: 981.31 toks/s]

Tasks (Llama-3.1-8B-Instruct):  70%|███████   | 35/50 [03:11<01:09,  4.66s/it, task=heldout_0035]

Tasks (Llama-3.1-8B-Instruct):  72%|███████▏  | 36/50 [03:11<01:03,  4.51s/it, task=heldout_0035]

Tasks (Llama-3.1-8B-Instruct):  72%|███████▏  | 36/50 [03:11<01:03,  4.51s/it, task=heldout_0036]

Llama-3.1-8B-Instruct | heldout_0035: done

Rendering prompts:  19%|█▉        | 74/384 [00:00<00:00, 739.51it/s]

Rendering prompts:  63%|██████▎   | 242/384 [00:00<00:00, 813.79it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 816.00it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 998.89it/s, est. speed input: 865260.64 toks/s, output: 999.14 toks/s]

Tasks (Llama-3.1-8B-Instruct):  72%|███████▏  | 36/50 [03:15<01:03,  4.51s/it, task=heldout_0036]

Tasks (Llama-3.1-8B-Instruct):  74%|███████▍  | 37/50 [03:15<00:55,  4.27s/it, task=heldout_0036]

Tasks (Llama-3.1-8B-Instruct):  74%|███████▍  | 37/50 [03:15<00:55,  4.27s/it, task=heldout_0037]

Llama-3.1-8B-Instruct | heldout_0036: done

Rendering prompts:   8%|▊         | 30/384 [00:00<00:01, 296.81it/s]

Rendering prompts:  37%|███▋      | 141/384 [00:00<00:00, 528.59it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 651.15it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   6%|▌         | 23/384 [00:00<00:05, 69.92it/s, est. speed input: 52364.68 toks/s, output: 60.26 toks/s]

Processed prompts:  19%|█▉        | 74/384 [00:00<00:01, 164.29it/s, est. speed input: 114515.30 toks/s, output: 131.78 toks/s]

Processed prompts:  38%|███▊      | 146/384 [00:00<00:01, 186.36it/s, est. speed input: 133654.48 toks/s, output: 153.80 toks/s]

Processed prompts:  51%|█████     | 196/384 [00:01<00:00, 216.82it/s, est. speed input: 150986.18 toks/s, output: 173.75 toks/s]

Processed prompts:  70%|███████   | 269/384 [00:01<00:00, 213.35it/s, est. speed input: 153445.66 toks/s, output: 176.75 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 211.41it/s, est. speed input: 183088.42 toks/s, output: 211.42 toks/s]

Tasks (Llama-3.1-8B-Instruct):  74%|███████▍  | 37/50 [03:36<00:55,  4.27s/it, task=heldout_0037]

Tasks (Llama-3.1-8B-Instruct):  76%|███████▌  | 38/50 [03:36<01:49,  9.15s/it, task=heldout_0037]

Tasks (Llama-3.1-8B-Instruct):  76%|███████▌  | 38/50 [03:36<01:49,  9.15s/it, task=heldout_0038]

Llama-3.1-8B-Instruct | heldout_0037: done

Rendering prompts:  19%|█▉        | 72/384 [00:00<00:00, 715.57it/s]

Rendering prompts:  62%|██████▏   | 239/384 [00:00<00:00, 804.85it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 702.43it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   7%|▋         | 25/384 [00:00<00:05, 68.59it/s, est. speed input: 50255.30 toks/s, output: 57.83 toks/s]

Processed prompts:  30%|███       | 116/384 [00:00<00:01, 189.20it/s, est. speed input: 132221.31 toks/s, output: 152.15 toks/s]

Processed prompts:  52%|█████▏    | 199/384 [00:01<00:00, 212.62it/s, est. speed input: 151783.17 toks/s, output: 174.66 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 258.93it/s, est. speed input: 224240.92 toks/s, output: 258.94 toks/s]

Tasks (Llama-3.1-8B-Instruct):  76%|███████▌  | 38/50 [03:40<01:49,  9.15s/it, task=heldout_0038]

Tasks (Llama-3.1-8B-Instruct):  78%|███████▊  | 39/50 [03:40<01:25,  7.79s/it, task=heldout_0038]

Tasks (Llama-3.1-8B-Instruct):  78%|███████▊  | 39/50 [03:40<01:25,  7.79s/it, task=heldout_0039]

Llama-3.1-8B-Instruct | heldout_0038: done

Rendering prompts:   5%|▌         | 21/384 [00:00<00:01, 206.45it/s]

Rendering prompts:  26%|██▌       | 99/384 [00:00<00:00, 365.18it/s]

Rendering prompts:  45%|████▌     | 174/384 [00:00<00:00, 352.35it/s]

Rendering prompts:  68%|██████▊   | 262/384 [00:00<00:00, 372.23it/s]

Rendering prompts: 100%|██████████| 384/384 [00:01<00:00, 367.25it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 999.02it/s, est. speed input: 865359.41 toks/s, output: 999.25 toks/s]

Tasks (Llama-3.1-8B-Instruct):  78%|███████▊  | 39/50 [03:46<01:25,  7.79s/it, task=heldout_0039]

Tasks (Llama-3.1-8B-Instruct):  80%|████████  | 40/50 [03:46<01:12,  7.24s/it, task=heldout_0039]

Tasks (Llama-3.1-8B-Instruct):  80%|████████  | 40/50 [03:46<01:12,  7.24s/it, task=heldout_0040]

Llama-3.1-8B-Instruct | heldout_0039: done

Rendering prompts:   7%|▋         | 27/384 [00:00<00:01, 268.58it/s]

Rendering prompts:  26%|██▋       | 101/384 [00:00<00:00, 347.90it/s]

Rendering prompts:  54%|█████▎    | 206/384 [00:00<00:00, 427.78it/s]

Rendering prompts:  80%|███████▉  | 307/384 [00:00<00:00, 403.31it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 411.05it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 828.94it/s, est. speed input: 718045.59 toks/s, output: 829.14 toks/s]

Tasks (Llama-3.1-8B-Instruct):  80%|████████  | 40/50 [03:52<01:12,  7.24s/it, task=heldout_0040]

Tasks (Llama-3.1-8B-Instruct):  82%|████████▏ | 41/50 [03:52<01:02,  6.98s/it, task=heldout_0040]

Tasks (Llama-3.1-8B-Instruct):  82%|████████▏ | 41/50 [03:52<01:02,  6.98s/it, task=heldout_0041]

Llama-3.1-8B-Instruct | heldout_0040: done

Rendering prompts:  19%|█▉        | 74/384 [00:00<00:00, 737.97it/s]

Rendering prompts:  61%|██████▏   | 236/384 [00:00<00:00, 592.43it/s]

Rendering prompts:  95%|█████████▌| 366/384 [00:00<00:00, 480.64it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 555.19it/s]
Processed prompts:   0%|          | 1/384 [00:00<01:15,  5.09it/s, est. speed input: 4420.20 toks/s, output: 5.09 toks/s]

Processed prompts:  19%|█▉        | 74/384 [00:00<00:01, 161.96it/s, est. speed input: 113080.02 toks/s, output: 130.12 toks/s]

Processed prompts:  29%|██▊       | 110/384 [00:00<00:01, 169.58it/s, est. speed input: 124461.68 toks/s, output: 143.22 toks/s]

Processed prompts:  52%|█████▏    | 199/384 [00:01<00:00, 218.19it/s, est. speed input: 152957.81 toks/s, output: 176.01 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 253.20it/s, est. speed input: 219285.12 toks/s, output: 253.22 toks/s]

Tasks (Llama-3.1-8B-Instruct):  82%|████████▏ | 41/50 [03:57<01:02,  6.98s/it, task=heldout_0041]

Tasks (Llama-3.1-8B-Instruct):  84%|████████▍ | 42/50 [03:57<00:50,  6.26s/it, task=heldout_0041]

Tasks (Llama-3.1-8B-Instruct):  84%|████████▍ | 42/50 [03:57<00:50,  6.26s/it, task=heldout_0042]

Llama-3.1-8B-Instruct | heldout_0041: done

Rendering prompts:   7%|▋         | 26/384 [00:00<00:01, 258.91it/s]

Rendering prompts:  30%|██▉       | 114/384 [00:00<00:00, 414.03it/s]

Rendering prompts:  51%|█████     | 196/384 [00:00<00:00, 390.49it/s]

Rendering prompts:  77%|███████▋  | 297/384 [00:00<00:00, 371.78it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 410.39it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   0%|          | 1/384 [00:00<02:24,  2.66it/s, est. speed input: 2307.40 toks/s, output: 2.66 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 489.04it/s, est. speed input: 423575.54 toks/s, output: 489.11 toks/s]

Tasks (Llama-3.1-8B-Instruct):  84%|████████▍ | 42/50 [04:09<00:50,  6.26s/it, task=heldout_0042]

Tasks (Llama-3.1-8B-Instruct):  86%|████████▌ | 43/50 [04:09<00:54,  7.84s/it, task=heldout_0042]

Tasks (Llama-3.1-8B-Instruct):  86%|████████▌ | 43/50 [04:09<00:54,  7.84s/it, task=heldout_0043]

Llama-3.1-8B-Instruct | heldout_0042: done

Rendering prompts:   6%|▌         | 23/384 [00:00<00:01, 226.21it/s]

Rendering prompts:  20%|██        | 78/384 [00:00<00:01, 261.54it/s]

Rendering prompts:  42%|████▏     | 160/384 [00:00<00:00, 340.96it/s]

Rendering prompts:  66%|██████▌   | 253/384 [00:00<00:00, 407.06it/s]

Rendering prompts: 100%|██████████| 384/384 [00:01<00:00, 364.46it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 655.01it/s, est. speed input: 567338.84 toks/s, output: 655.12 toks/s]

Tasks (Llama-3.1-8B-Instruct):  86%|████████▌ | 43/50 [04:24<00:54,  7.84s/it, task=heldout_0043]

Tasks (Llama-3.1-8B-Instruct):  88%|████████▊ | 44/50 [04:24<01:00, 10.07s/it, task=heldout_0043]

Tasks (Llama-3.1-8B-Instruct):  88%|████████▊ | 44/50 [04:24<01:00, 10.07s/it, task=heldout_0044]

Llama-3.1-8B-Instruct | heldout_0043: done

Rendering prompts:   5%|▌         | 21/384 [00:00<00:01, 208.05it/s]

Rendering prompts:  27%|██▋       | 105/384 [00:00<00:00, 390.93it/s]

Rendering prompts:  47%|████▋     | 182/384 [00:00<00:00, 357.34it/s]

Rendering prompts:  72%|███████▏  | 277/384 [00:00<00:00, 396.91it/s]

Rendering prompts: 100%|██████████| 384/384 [00:01<00:00, 373.57it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 976.05it/s, est. speed input: 845422.44 toks/s, output: 976.23 toks/s]

Tasks (Llama-3.1-8B-Instruct):  88%|████████▊ | 44/50 [04:34<01:00, 10.07s/it, task=heldout_0044]

Tasks (Llama-3.1-8B-Instruct):  90%|█████████ | 45/50 [04:34<00:50, 10.12s/it, task=heldout_0044]

Tasks (Llama-3.1-8B-Instruct):  90%|█████████ | 45/50 [04:34<00:50, 10.12s/it, task=heldout_0045]

Llama-3.1-8B-Instruct | heldout_0044: done

Rendering prompts:   8%|▊         | 30/384 [00:00<00:01, 296.73it/s]

Rendering prompts:  33%|███▎      | 126/384 [00:00<00:00, 457.05it/s]

Rendering prompts:  56%|█████▌    | 215/384 [00:00<00:00, 410.30it/s]

Rendering prompts:  84%|████████▍ | 322/384 [00:00<00:00, 443.18it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 420.37it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 763.31it/s, est. speed input: 661158.85 toks/s, output: 763.46 toks/s]

Tasks (Llama-3.1-8B-Instruct):  90%|█████████ | 45/50 [04:40<00:50, 10.12s/it, task=heldout_0045]

Tasks (Llama-3.1-8B-Instruct):  92%|█████████▏| 46/50 [04:40<00:35,  8.76s/it, task=heldout_0045]

Tasks (Llama-3.1-8B-Instruct):  92%|█████████▏| 46/50 [04:40<00:35,  8.76s/it, task=heldout_0046]

Llama-3.1-8B-Instruct | heldout_0045: done

Rendering prompts:  13%|█▎        | 51/384 [00:00<00:01, 332.65it/s]

Rendering prompts:  38%|███▊      | 147/384 [00:00<00:00, 443.71it/s]

Rendering prompts:  66%|██████▌   | 253/384 [00:00<00:00, 477.47it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 434.35it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 663.20it/s, est. speed input: 574444.87 toks/s, output: 663.33 toks/s]

Tasks (Llama-3.1-8B-Instruct):  92%|█████████▏| 46/50 [04:44<00:35,  8.76s/it, task=heldout_0046]

Tasks (Llama-3.1-8B-Instruct):  94%|█████████▍| 47/50 [04:44<00:21,  7.30s/it, task=heldout_0046]

Tasks (Llama-3.1-8B-Instruct):  94%|█████████▍| 47/50 [04:44<00:21,  7.30s/it, task=heldout_0047]

Llama-3.1-8B-Instruct | heldout_0046: done

Rendering prompts:  40%|████      | 154/384 [00:00<00:00, 776.33it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 796.46it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 1454.02it/s, est. speed input: 1259593.43 toks/s, output: 1454.48 toks/s]

Tasks (Llama-3.1-8B-Instruct):  94%|█████████▍| 47/50 [04:47<00:21,  7.30s/it, task=heldout_0047]

Tasks (Llama-3.1-8B-Instruct):  96%|█████████▌| 48/50 [04:47<00:12,  6.16s/it, task=heldout_0047]

Tasks (Llama-3.1-8B-Instruct):  96%|█████████▌| 48/50 [04:47<00:12,  6.16s/it, task=heldout_0048]

Llama-3.1-8B-Instruct | heldout_0047: done

Rendering prompts:  18%|█▊        | 71/384 [00:00<00:00, 709.29it/s]

Rendering prompts:  54%|█████▍    | 207/384 [00:00<00:00, 623.29it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 722.59it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:00<00:00, 997.67it/s, est. speed input: 864208.25 toks/s, output: 997.92 toks/s]

Tasks (Llama-3.1-8B-Instruct):  96%|█████████▌| 48/50 [04:50<00:12,  6.16s/it, task=heldout_0048]

Tasks (Llama-3.1-8B-Instruct):  98%|█████████▊| 49/50 [04:50<00:05,  5.33s/it, task=heldout_0048]

Tasks (Llama-3.1-8B-Instruct):  98%|█████████▊| 49/50 [04:51<00:05,  5.33s/it, task=heldout_0049]

Llama-3.1-8B-Instruct | heldout_0048: done

Rendering prompts:  20%|█▉        | 76/384 [00:00<00:00, 751.44it/s]

Rendering prompts:  64%|██████▍   | 247/384 [00:00<00:00, 827.00it/s]

Rendering prompts: 100%|██████████| 384/384 [00:00<00:00, 831.05it/s]
Processed prompts:   0%|          | 0/384 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   7%|▋         | 26/384 [00:00<00:04, 78.25it/s, est. speed input: 58322.63 toks/s, output: 67.11 toks/s]

Processed prompts:  32%|███▏      | 122/384 [00:00<00:01, 198.55it/s, est. speed input: 140544.38 toks/s, output: 161.73 toks/s]

Processed prompts:  52%|█████▏    | 200/384 [00:01<00:00, 210.13it/s, est. speed input: 153648.71 toks/s, output: 176.81 toks/s]

Processed prompts: 100%|██████████| 384/384 [00:01<00:00, 253.99it/s, est. speed input: 219963.65 toks/s, output: 254.00 toks/s]

Tasks (Llama-3.1-8B-Instruct):  98%|█████████▊| 49/50 [04:55<00:05,  5.33s/it, task=heldout_0049]

Tasks (Llama-3.1-8B-Instruct): 100%|██████████| 50/50 [04:55<00:00,  5.06s/it, task=heldout_0049]

[rank0]:[W912 17:09:53.243733283 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

Llama-3.1-8B-Instruct | heldout_0049: done

INFO 09-12 17:10:01 [api_utils.py:286] non-default args: {'max_model_len': 8192, 'gpu_memory_utilization': 0.9, 'disable_log_stats': True, 'model': 'meta-llama/Llama-3.1-8B-Instruct'}
WARNING 09-12 17:10:01 [arg_utils.py:1801] The global random seed is set to 0. Since VLLM_ENABLE_V1_MULTIPROCESSING is set to False, this may affect the random state of the Python process that launched vLLM.

INFO 09-12 17:10:02 [model.py:684] Resolved architecture: LlamaForCausalLM
INFO 09-12 17:10:02 [model.py:2021] Using max model len 8192
INFO 09-12 17:10:02 [scheduler.py:277] Chunked prefill is enabled with max_num_batched_tokens=16384.
INFO 09-12 17:10:02 [kernel.py:369] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])

INFO 09-12 17:10:04 [core.py:123] Initializing a V1 LLM engine (v0.29.0) with config: model='meta-llama/Llama-3.1-8B-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=main, tokenizer_revision=main, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=None, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, per_request_spec_decode_metrics='none', kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=meta-llama/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::qwen4_exp_compute_ple_ngram_ids', 'vllm::qwen4_exp_ple_short_conv', 'vllm::qwen4_exp_qsa_with_output', 'vllm::linear_attention', 'vllm::qwen_gdn_attention_core', 'vllm::qwen_gdn_attention_core_fused_norm_packed', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608, 624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784, 800, 816, 832, 848, 864, 880, 896, 912, 928, 944, 960, 976, 992, 1008, 1024], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 1024, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_jit_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')

INFO 09-12 17:10:04 [parallel_state.py:1775] world_size=1 rank=0 local_rank=0 distributed_init_method=file:///tmp/vllm_dist_befea0c589e143179914e8ad6df4359d backend=nccl
INFO 09-12 17:10:04 [parallel_state.py:2119] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
INFO 09-12 17:10:04 [gpu_worker.py:429] Using V2 Model Runner

INFO 09-12 17:10:05 [model_runner.py:382] Loading model from scratch...
INFO 09-12 17:10:05 [cuda.py:492] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'TRITON_ATTN', 'FLEX_ATTENTION'].
INFO 09-12 17:10:05 [flash_attn.py:897] Using FlashAttention version 4

INFO 09-12 17:10:05 [weight_utils.py:863] Filesystem type for checkpoints: OVERLAY. Checkpoint size: 14.96 GiB. Available RAM: 949.70 GiB.
INFO 09-12 17:10:05 [weight_utils.py:886] Auto-prefetch is disabled because the filesystem (OVERLAY) is not a recognized network FS (NFS/Lustre). If you want to force prefetching, start vLLM with --safetensors-load-strategy=prefetch.

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  1.67it/s]

Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.62it/s]

Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:01<00:00,  1.61it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  2.27it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.98it/s]

INFO 09-12 17:10:07 [default_loader.py:430] Loading weights took 2.03 seconds

INFO 09-12 17:10:08 [model_runner.py:404] Model loading took 15.0 GiB memory and 3.009769 seconds
INFO 09-12 17:10:08 [topk_topp_sampler.py:46] FlashInfer top-p/top-k sampling disabled via VLLM_USE_FLASHINFER_SAMPLER=0.
INFO 09-12 17:10:08 [utils.py:306] Using LBNHC KV cache layout.

INFO 09-12 17:10:09 [caching.py:343] reconstructed serializable fn from standalone compile artifacts. num_artifacts=3 num_submods=33
INFO 09-12 17:10:09 [decorators.py:313] Directly load AOT compilation from path /root/.cache/vllm/torch_compile_cache/torch_aot_compile/cef7e87221ab1c84d131580410633c84a50a07f79f9eca955bc2b736b10134b1/rank_0_0/model
INFO 09-12 17:10:09 [monitor.py:53] torch.compile took 0.14 s in total
INFO 09-12 17:10:09 [monitor.py:81] Initial profiling/warmup run took 0.13 s

Capturing CUDA graphs (PIECEWISE):   0%|          | 0/83 [00:00<?, ?it/s]

/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (PIECEWISE):   4%|▎         | 3/83 [00:03<01:15,  1.06it/s]

Capturing CUDA graphs (PIECEWISE):   8%|▊         | 7/83 [00:03<00:24,  3.06it/s]

Capturing CUDA graphs (PIECEWISE):  13%|█▎        | 11/83 [00:04<00:13,  5.48it/s]

Capturing CUDA graphs (PIECEWISE):  18%|█▊        | 15/83 [00:04<00:08,  7.93it/s]

Capturing CUDA graphs (PIECEWISE):  23%|██▎       | 19/83 [00:04<00:06, 10.19it/s]

Capturing CUDA graphs (PIECEWISE):  28%|██▊       | 23/83 [00:05<00:05, 11.90it/s]

Capturing CUDA graphs (PIECEWISE):  33%|███▎      | 27/83 [00:05<00:04, 13.47it/s]

Capturing CUDA graphs (PIECEWISE):  37%|███▋      | 31/83 [00:05<00:03, 14.79it/s]

Capturing CUDA graphs (PIECEWISE):  42%|████▏     | 35/83 [00:05<00:03, 15.93it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:06<00:02, 17.16it/s]

Capturing CUDA graphs (PIECEWISE):  52%|█████▏    | 43/83 [00:06<00:02, 17.58it/s]

Capturing CUDA graphs (PIECEWISE):  58%|█████▊    | 48/83 [00:06<00:01, 18.82it/s]

Capturing CUDA graphs (PIECEWISE):  65%|██████▌   | 54/83 [00:06<00:01, 19.47it/s]

Capturing CUDA graphs (PIECEWISE):  70%|██████▉   | 58/83 [00:07<00:01, 19.32it/s]

Capturing CUDA graphs (PIECEWISE):  75%|███████▍  | 62/83 [00:07<00:01, 19.52it/s]

Capturing CUDA graphs (PIECEWISE):  80%|███████▉  | 66/83 [00:07<00:00, 19.33it/s]

Capturing CUDA graphs (PIECEWISE):  86%|████████▌ | 71/83 [00:07<00:00, 19.69it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:07<00:00, 19.32it/s]

Capturing CUDA graphs (PIECEWISE):  95%|█████████▌| 79/83 [00:08<00:00, 18.88it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:08<00:00,  9.91it/s]
Capturing CUDA graphs (FULL): 100%|██████████| 2/2 [00:00<00:00, 20.58it/s]

INFO 09-12 17:10:18 [model_runner.py:960] Graph capturing finished in 9 secs, took 0.54 GiB

INFO 09-12 17:10:19 [gpu_worker.py:625] Available KV cache memory: 142.26 GiB
INFO 09-12 17:10:19 [gpu_worker.py:640] CUDA graph memory profiling is enabled (default since v0.21.0). The current --gpu-memory-utilization=0.9000 is equivalent to --gpu-memory-utilization=0.8958 without CUDA graph memory profiling. To maintain the same effective KV cache size as before, increase --gpu-memory-utilization to 0.9042. To disable, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=0.
INFO 09-12 17:10:19 [kv_cache_utils.py:2032] GPU KV cache size: 1,165,408 tokens, Maximum concurrency for 8,192 tokens per request: 142.26x
INFO 09-12 17:10:19 [kernel_warmup.py:124] JIT kernel warmup starting.
INFO 09-12 17:10:19 [kernel_warmup.py:134] JIT kernel warmup finished in 0.00s.

WARNING 09-12 17:10:19 [import_utils.py:408] Module vllm.third_party.deep_gemm was found but failed to import
WARNING 09-12 17:10:19 [import_utils.py:408] Traceback (most recent call last):
WARNING 09-12 17:10:19 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/utils/import_utils.py", line 406, in _has_module
WARNING 09-12 17:10:19 [import_utils.py:408]     importlib.import_module(module_name)
WARNING 09-12 17:10:19 [import_utils.py:408]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
WARNING 09-12 17:10:19 [import_utils.py:408]     return _bootstrap._gcd_import(name[level:], package, level)
WARNING 09-12 17:10:19 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
WARNING 09-12 17:10:19 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
WARNING 09-12 17:10:19 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
WARNING 09-12 17:10:19 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
WARNING 09-12 17:10:19 [import_utils.py:408]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
WARNING 09-12 17:10:19 [import_utils.py:408]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
WARNING 09-12 17:10:19 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 126, in <module>
WARNING 09-12 17:10:19 [import_utils.py:408]     _find_cuda_home()                           # CUDA home
WARNING 09-12 17:10:19 [import_utils.py:408]   File "/root/repo/sata-project/.venv/lib/python3.10/site-packages/vllm/third_party/deep_gemm/__init__.py", line 120, in _find_cuda_home
WARNING 09-12 17:10:19 [import_utils.py:408]     assert cuda_home is not None
WARNING 09-12 17:10:19 [import_utils.py:408] AssertionError

Capturing CUDA graphs (PIECEWISE):   2%|▏         | 2/83 [00:00<00:07, 10.84it/s]

Capturing CUDA graphs (PIECEWISE):   7%|▋         | 6/83 [00:00<00:06, 11.50it/s]

Capturing CUDA graphs (PIECEWISE):  12%|█▏        | 10/83 [00:00<00:06, 12.07it/s]

Capturing CUDA graphs (PIECEWISE):  17%|█▋        | 14/83 [00:01<00:05, 12.67it/s]

Capturing CUDA graphs (PIECEWISE):  22%|██▏       | 18/83 [00:01<00:04, 13.53it/s]

Capturing CUDA graphs (PIECEWISE):  27%|██▋       | 22/83 [00:01<00:04, 14.43it/s]

Capturing CUDA graphs (PIECEWISE):  31%|███▏      | 26/83 [00:01<00:03, 15.39it/s]

Capturing CUDA graphs (PIECEWISE):  36%|███▌      | 30/83 [00:02<00:03, 16.42it/s]

Capturing CUDA graphs (PIECEWISE):  41%|████      | 34/83 [00:02<00:02, 17.50it/s]

Capturing CUDA graphs (PIECEWISE):  47%|████▋     | 39/83 [00:02<00:02, 18.90it/s]

Capturing CUDA graphs (PIECEWISE):  54%|█████▍    | 45/83 [00:02<00:01, 20.25it/s]

Capturing CUDA graphs (PIECEWISE):  61%|██████▏   | 51/83 [00:03<00:01, 21.28it/s]

Capturing CUDA graphs (PIECEWISE):  69%|██████▊   | 57/83 [00:03<00:01, 19.74it/s]

Capturing CUDA graphs (PIECEWISE):  76%|███████▌  | 63/83 [00:03<00:00, 20.90it/s]

Capturing CUDA graphs (PIECEWISE):  83%|████████▎ | 69/83 [00:04<00:00, 21.26it/s]

Capturing CUDA graphs (PIECEWISE):  90%|█████████ | 75/83 [00:04<00:00, 21.55it/s]

Capturing CUDA graphs (PIECEWISE):  98%|█████████▊| 81/83 [00:04<00:00, 21.63it/s]

Capturing CUDA graphs (PIECEWISE): 100%|██████████| 83/83 [00:04<00:00, 17.62it/s]
Capturing CUDA graphs (FULL):   4%|▎         | 3/83 [00:00<00:03, 21.27it/s]

Capturing CUDA graphs (FULL):  11%|█         | 9/83 [00:00<00:03, 22.53it/s]

Capturing CUDA graphs (FULL):  18%|█▊        | 15/83 [00:00<00:02, 23.88it/s]

Capturing CUDA graphs (FULL):  25%|██▌       | 21/83 [00:00<00:02, 26.34it/s]

Capturing CUDA graphs (FULL):  35%|███▍      | 29/83 [00:01<00:01, 29.79it/s]

Capturing CUDA graphs (FULL):  45%|████▍     | 37/83 [00:01<00:01, 33.67it/s]

Capturing CUDA graphs (FULL):  57%|█████▋    | 47/83 [00:01<00:00, 39.26it/s]

Capturing CUDA graphs (FULL):  69%|██████▊   | 57/83 [00:01<00:00, 43.55it/s]

Capturing CUDA graphs (FULL):  81%|████████  | 67/83 [00:01<00:00, 45.99it/s]

Capturing CUDA graphs (FULL):  93%|█████████▎| 77/83 [00:02<00:00, 45.70it/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Te'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

Capturing CUDA graphs (FULL): 100%|██████████| 83/83 [00:05<00:00, 15.69it/s]

INFO 09-12 17:10:29 [model_runner.py:960] Graph capturing finished in 10 secs, took 0.30 GiB
INFO 09-12 17:10:29 [gpu_worker.py:797] CUDA graph pool memory: 0.3 GiB (actual), 0.74 GiB (estimated), difference: 0.45 GiB (150.7%).
INFO 09-12 17:10:29 [gpu_worker.py:860] Free memory on device (177.12/178.34 GiB) on startup. Desired GPU memory utilization is (0.9, 160.51 GiB). Actual usage is 15.81 GiB for consumed memory (weights + non-torch), 2.43 GiB for peak activation, and 0.3 GiB for CUDAGraph memory. Replace gpu_memory_utilization config with `--kv-cache-memory=152278255514` (141.82 GiB) to fit into requested memory, or `--kv-cache-memory=170115247616` (158.43 GiB) to fully utilize gpu memory. Current kv cache memory in use is 142.26 GiB.

INFO 09-12 17:10:30 [jit_monitor.py:85] Kernel JIT monitor activated; monitored JIT compilations during inference will use mode=warn.

WARNING 09-12 17:10:30 [torch_utils.py:265] OMP_NUM_THREADS=192 is set; leaving Torch threads at 96 for serving. Multi-threaded torch CPU ops during serving can degrade performance through spin-wait contention and cgroup CPU-quota throttling.
INFO 09-12 17:10:30 [core.py:361] init engine (profile, create kv cache, warmup model) took 22.38 s (compilation: 0.14 s)

INFO 09-12 17:10:31 [hf.py:547] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   0%|          | 0/50 [00:00<?, ?it/s]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   0%|          | 0/50 [00:00<?, ?it/s, task=test_0091]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 750.81it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]/root/repo/sata-project/.venv/lib/python3.10/site-packages/nvidia_cutlass_dsl/dsl_packages/cutlass/base_dsl/dsl.py:2309: UserWarning: Argument aux_data (position 19) cannot be converted to a JitArgument for function 'cutlass___call___vllmvllm_flash_attncuteflash_fwd_sm100FlashAttentionForwardSm100_object_at__Tensorgmemoi64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i64i641_Tensorgmemoi64i641_None_'. Its type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>` is not supported. If the value is known at compile time, annotate it: `aux_data: Constexpr`. Otherwise, implement the `JitArgument` or `DynamicExpression` protocol for type `<class 'vllm.vllm_flash_attn.cute.utils.AuxData'>`, or register a custom argument adapter.
  exe_args, func_types, adapted_args = self.generate_mlir_function_types(

WARNING 09-12 17:10:33 [jit_monitor.py:141] CuTeDSL JIT compilation during inference: FlashAttentionForwardSm100. This causes a latency spike; consider extending warmup to cover this shape/config.

WARNING 09-12 17:10:36 [jit_monitor.py:141] Triton kernel JIT compilation during inference: _topk_log_softmax_kernel. This causes a latency spike; consider extending warmup to cover this shape/config.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer CachedTokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Processed prompts: 100%|██████████| 32/32 [00:03<00:00,  8.58it/s, est. speed input: 7458.80 toks/s, output: 8.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 840.35it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 534.46it/s, est. speed input: 465548.27 toks/s, output: 535.70 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 782.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 602.94it/s, est. speed input: 524955.80 toks/s, output: 604.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.99it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.41it/s, est. speed input: 630048.49 toks/s, output: 724.98 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.63it/s, est. speed input: 629382.12 toks/s, output: 724.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 763.85it/s, est. speed input: 665380.46 toks/s, output: 765.64 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 814.52it/s, est. speed input: 709632.55 toks/s, output: 816.55 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 861.60it/s, est. speed input: 751012.24 toks/s, output: 864.17 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 997.11it/s, est. speed input: 869199.00 toks/s, output: 1000.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1130.00it/s, est. speed input: 985519.15 toks/s, output: 1133.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.43it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1307.85it/s, est. speed input: 1142776.58 toks/s, output: 1314.85 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 533.34it/s, est. speed input: 464249.29 toks/s, output: 534.21 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.76it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 622.88it/s, est. speed input: 542658.44 toks/s, output: 624.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 854.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.51it/s, est. speed input: 561204.86 toks/s, output: 645.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.56it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 731.68it/s, est. speed input: 637295.13 toks/s, output: 733.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 735.23it/s, est. speed input: 640416.45 toks/s, output: 736.91 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 841.70it/s, est. speed input: 733402.54 toks/s, output: 843.90 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 856.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 841.70it/s, est. speed input: 733374.87 toks/s, output: 843.87 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 854.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 956.25it/s, est. speed input: 833471.77 toks/s, output: 959.04 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 849.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1028.13it/s, est. speed input: 896304.48 toks/s, output: 1031.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1167.10it/s, est. speed input: 1017936.86 toks/s, output: 1171.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1351.73it/s, est. speed input: 1181343.30 toks/s, output: 1359.24 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   2%|▏         | 1/50 [00:06<04:59,  6.10s/it, task=test_0091]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   2%|▏         | 1/50 [00:06<04:59,  6.10s/it, task=heldout_0016]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.66it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.26it/s, est. speed input: 4567.40 toks/s, output: 5.26 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 126.88it/s, est. speed input: 110309.51 toks/s, output: 126.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 579.64it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 321.20it/s, est. speed input: 279405.25 toks/s, output: 321.52 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 617.93it/s, est. speed input: 538054.76 toks/s, output: 619.13 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.09it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.93it/s, est. speed input: 630535.55 toks/s, output: 725.54 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 719.27it/s, est. speed input: 626458.01 toks/s, output: 720.85 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 821.64it/s, est. speed input: 715834.47 toks/s, output: 823.69 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.88it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 807.20it/s, est. speed input: 703762.15 toks/s, output: 809.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 934.44it/s, est. speed input: 814406.35 toks/s, output: 937.10 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 994.76it/s, est. speed input: 867150.46 toks/s, output: 997.79 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1140.92it/s, est. speed input: 995002.65 toks/s, output: 1144.89 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1323.42it/s, est. speed input: 1154918.36 toks/s, output: 1328.86 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 562.81it/s, est. speed input: 489950.67 toks/s, output: 563.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.78it/s, est. speed input: 561420.97 toks/s, output: 646.02 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 649.96it/s, est. speed input: 566113.37 toks/s, output: 651.42 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 734.73it/s, est. speed input: 639959.65 toks/s, output: 736.39 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 742.23it/s, est. speed input: 646855.74 toks/s, output: 744.31 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.45it/s, est. speed input: 731058.12 toks/s, output: 841.21 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.12it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 830.74it/s, est. speed input: 724122.94 toks/s, output: 833.21 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 851.15it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 956.58it/s, est. speed input: 833865.05 toks/s, output: 959.50 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.13it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1020.73it/s, est. speed input: 890277.12 toks/s, output: 1024.40 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1148.06it/s, est. speed input: 1001237.91 toks/s, output: 1152.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.06it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1378.25it/s, est. speed input: 1202908.44 toks/s, output: 1384.09 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   4%|▍         | 2/50 [00:08<03:13,  4.04s/it, task=heldout_0016]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   4%|▍         | 2/50 [00:08<03:13,  4.04s/it, task=test_0099]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.58it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:06,  4.98it/s, est. speed input: 4325.50 toks/s, output: 4.98 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 127.19it/s, est. speed input: 110577.86 toks/s, output: 127.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 469.74it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 311.09it/s, est. speed input: 270524.31 toks/s, output: 311.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 632.26it/s, est. speed input: 550532.22 toks/s, output: 633.48 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.25it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 726.35it/s, est. speed input: 632645.76 toks/s, output: 727.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 726.95it/s, est. speed input: 633178.10 toks/s, output: 728.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.02it/s, est. speed input: 717953.93 toks/s, output: 826.10 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 807.38it/s, est. speed input: 703397.15 toks/s, output: 809.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 944.66it/s, est. speed input: 823334.46 toks/s, output: 947.37 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 996.54it/s, est. speed input: 869600.79 toks/s, output: 1000.61 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1122.77it/s, est. speed input: 979181.51 toks/s, output: 1126.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1301.61it/s, est. speed input: 1135743.76 toks/s, output: 1306.81 toks/s]

/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 562.38it/s, est. speed input: 489576.37 toks/s, output: 563.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.25it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.71it/s, est. speed input: 563147.68 toks/s, output: 648.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.75it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 649.40it/s, est. speed input: 565493.06 toks/s, output: 650.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.96it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.87it/s, est. speed input: 636609.88 toks/s, output: 732.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.95it/s, est. speed input: 638407.89 toks/s, output: 734.60 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.76it/s, est. speed input: 730797.03 toks/s, output: 840.90 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 830.19it/s, est. speed input: 723570.39 toks/s, output: 832.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.51it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 944.01it/s, est. speed input: 822788.49 toks/s, output: 946.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1023.21it/s, est. speed input: 892020.17 toks/s, output: 1026.40 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1152.89it/s, est. speed input: 1005527.92 toks/s, output: 1157.00 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1344.69it/s, est. speed input: 1174822.53 toks/s, output: 1351.69 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   6%|▌         | 3/50 [00:11<02:39,  3.39s/it, task=test_0099]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   6%|▌         | 3/50 [00:11<02:39,  3.39s/it, task=test_0017]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.96it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.25it/s, est. speed input: 4565.07 toks/s, output: 5.25 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 121.71it/s, est. speed input: 105804.81 toks/s, output: 121.75 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 586.87it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 306.58it/s, est. speed input: 266661.19 toks/s, output: 306.85 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.05it/s, est. speed input: 553114.27 toks/s, output: 636.46 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.98it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 726.81it/s, est. speed input: 633054.38 toks/s, output: 728.44 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 717.48it/s, est. speed input: 625061.39 toks/s, output: 719.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.42it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 828.45it/s, est. speed input: 721797.18 toks/s, output: 830.54 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 825.21it/s, est. speed input: 718989.56 toks/s, output: 827.31 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 940.92it/s, est. speed input: 820063.74 toks/s, output: 943.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.79it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 991.29it/s, est. speed input: 864162.92 toks/s, output: 994.34 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1150.11it/s, est. speed input: 1004402.24 toks/s, output: 1155.71 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1342.26it/s, est. speed input: 1172001.10 toks/s, output: 1348.53 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 562.42it/s, est. speed input: 489601.03 toks/s, output: 563.38 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.09it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.37it/s, est. speed input: 560194.07 toks/s, output: 644.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.17it/s, est. speed input: 562647.82 toks/s, output: 647.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.58it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 737.76it/s, est. speed input: 642604.05 toks/s, output: 739.43 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 737.07it/s, est. speed input: 642006.27 toks/s, output: 738.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 848.05it/s, est. speed input: 738922.40 toks/s, output: 850.25 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 852.33it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 847.82it/s, est. speed input: 738744.55 toks/s, output: 850.04 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 957.64it/s, est. speed input: 834688.56 toks/s, output: 960.44 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1024.59it/s, est. speed input: 893249.85 toks/s, output: 1027.81 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1166.86it/s, est. speed input: 1017688.17 toks/s, output: 1170.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1353.66it/s, est. speed input: 1181415.10 toks/s, output: 1359.35 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   8%|▊         | 4/50 [00:13<02:21,  3.08s/it, task=test_0017]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):   8%|▊         | 4/50 [00:13<02:21,  3.08s/it, task=test_0194]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.79it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 132.13it/s, est. speed input: 114898.85 toks/s, output: 132.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 301.75it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 287.24it/s, est. speed input: 249777.19 toks/s, output: 287.42 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.70it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 639.53it/s, est. speed input: 556856.22 toks/s, output: 640.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.14it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 728.49it/s, est. speed input: 634528.41 toks/s, output: 730.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 726.70it/s, est. speed input: 632923.84 toks/s, output: 728.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.78it/s, est. speed input: 721203.57 toks/s, output: 829.86 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.53it/s, est. speed input: 713125.28 toks/s, output: 820.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 951.06it/s, est. speed input: 828928.44 toks/s, output: 953.81 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 907.92it/s, est. speed input: 791240.68 toks/s, output: 910.44 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1131.47it/s, est. speed input: 986753.12 toks/s, output: 1135.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.62it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1328.76it/s, est. speed input: 1159534.00 toks/s, output: 1334.20 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 561.77it/s, est. speed input: 489040.60 toks/s, output: 562.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.90it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.69it/s, est. speed input: 563970.03 toks/s, output: 648.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 653.30it/s, est. speed input: 568880.07 toks/s, output: 654.60 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.46it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 738.42it/s, est. speed input: 643185.21 toks/s, output: 740.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 743.20it/s, est. speed input: 648139.00 toks/s, output: 745.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 839.85it/s, est. speed input: 731755.28 toks/s, output: 842.00 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 830.03it/s, est. speed input: 723615.28 toks/s, output: 832.62 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 961.76it/s, est. speed input: 838282.01 toks/s, output: 964.58 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1020.75it/s, est. speed input: 890950.38 toks/s, output: 1025.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1149.87it/s, est. speed input: 1002890.87 toks/s, output: 1153.98 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.86it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1348.45it/s, est. speed input: 1176730.82 toks/s, output: 1353.97 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  10%|█         | 5/50 [00:16<02:12,  2.94s/it, task=test_0194]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  10%|█         | 5/50 [00:16<02:12,  2.94s/it, task=heldout_0038]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.69it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 127.94it/s, est. speed input: 111238.79 toks/s, output: 128.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 296.26it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 285.23it/s, est. speed input: 248011.73 toks/s, output: 285.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.89it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 638.83it/s, est. speed input: 556277.24 toks/s, output: 640.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.06it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.21it/s, est. speed input: 629001.97 toks/s, output: 723.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 727.81it/s, est. speed input: 634228.23 toks/s, output: 729.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.42it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.03it/s, est. speed input: 720553.07 toks/s, output: 829.11 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.06it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.82it/s, est. speed input: 713391.35 toks/s, output: 820.88 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 938.58it/s, est. speed input: 818027.69 toks/s, output: 941.28 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1007.40it/s, est. speed input: 878197.80 toks/s, output: 1010.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1126.84it/s, est. speed input: 984022.52 toks/s, output: 1132.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1337.32it/s, est. speed input: 1167145.72 toks/s, output: 1342.92 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 562.05it/s, est. speed input: 489276.52 toks/s, output: 563.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 650.56it/s, est. speed input: 566646.94 toks/s, output: 652.03 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.39it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 629.57it/s, est. speed input: 548332.26 toks/s, output: 630.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 738.10it/s, est. speed input: 642898.04 toks/s, output: 739.76 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 741.28it/s, est. speed input: 645670.47 toks/s, output: 742.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.14it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 841.42it/s, est. speed input: 733144.38 toks/s, output: 843.60 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 823.26it/s, est. speed input: 717269.58 toks/s, output: 825.34 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 966.30it/s, est. speed input: 842819.09 toks/s, output: 969.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.35it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1020.09it/s, est. speed input: 889367.46 toks/s, output: 1023.32 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1147.09it/s, est. speed input: 1000396.31 toks/s, output: 1151.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1340.30it/s, est. speed input: 1169544.91 toks/s, output: 1345.72 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  12%|█▏        | 6/50 [00:19<02:05,  2.86s/it, task=heldout_0038]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  12%|█▏        | 6/50 [00:19<02:05,  2.86s/it, task=heldout_0025]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.33it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 113.93it/s, est. speed input: 99048.71 toks/s, output: 113.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 312.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 611.73it/s, est. speed input: 532743.83 toks/s, output: 613.02 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 633.61it/s, est. speed input: 551698.85 toks/s, output: 634.83 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 718.41it/s, est. speed input: 625705.21 toks/s, output: 719.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.73it/s, est. speed input: 629484.02 toks/s, output: 724.33 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 822.20it/s, est. speed input: 716304.87 toks/s, output: 824.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.79it/s, est. speed input: 710739.57 toks/s, output: 817.82 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.84it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 922.52it/s, est. speed input: 803987.05 toks/s, output: 925.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1002.60it/s, est. speed input: 874018.94 toks/s, output: 1005.69 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1109.77it/s, est. speed input: 968184.13 toks/s, output: 1114.00 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1323.07it/s, est. speed input: 1154632.54 toks/s, output: 1328.55 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 544.76it/s, est. speed input: 474219.38 toks/s, output: 545.68 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.57it/s, est. speed input: 563888.23 toks/s, output: 648.86 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 648.95it/s, est. speed input: 565093.05 toks/s, output: 650.25 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.26it/s, est. speed input: 636071.76 toks/s, output: 731.91 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 728.85it/s, est. speed input: 635074.30 toks/s, output: 730.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 845.32it/s, est. speed input: 736537.96 toks/s, output: 847.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 841.10it/s, est. speed input: 732844.95 toks/s, output: 843.26 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.02it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 953.37it/s, est. speed input: 830959.99 toks/s, output: 956.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1009.19it/s, est. speed input: 879767.72 toks/s, output: 1012.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.23it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1154.89it/s, est. speed input: 1007282.07 toks/s, output: 1159.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.38it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1344.95it/s, est. speed input: 1173758.47 toks/s, output: 1350.54 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  14%|█▍        | 7/50 [00:22<02:01,  2.81s/it, task=heldout_0025]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  14%|█▍        | 7/50 [00:22<02:01,  2.81s/it, task=test_0170]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.79it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 129.60it/s, est. speed input: 112692.76 toks/s, output: 129.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 306.02it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 604.77it/s, est. speed input: 526562.65 toks/s, output: 605.91 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 640.81it/s, est. speed input: 557991.10 toks/s, output: 642.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.36it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 725.11it/s, est. speed input: 631549.57 toks/s, output: 726.71 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.53it/s, est. speed input: 629300.62 toks/s, output: 724.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 821.32it/s, est. speed input: 715562.19 toks/s, output: 823.37 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.18it/s, est. speed input: 712937.85 toks/s, output: 820.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 935.87it/s, est. speed input: 816590.16 toks/s, output: 939.62 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1017.01it/s, est. speed input: 887796.90 toks/s, output: 1021.54 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1112.31it/s, est. speed input: 969995.81 toks/s, output: 1116.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1316.31it/s, est. speed input: 1148572.16 toks/s, output: 1321.57 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 558.72it/s, est. speed input: 486645.11 toks/s, output: 559.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 649.36it/s, est. speed input: 565449.20 toks/s, output: 650.65 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 619.60it/s, est. speed input: 539450.84 toks/s, output: 620.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 738.27it/s, est. speed input: 643046.91 toks/s, output: 739.94 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 689.47it/s, est. speed input: 600819.08 toks/s, output: 691.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 841.44it/s, est. speed input: 733144.38 toks/s, output: 843.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.64it/s, est. speed input: 713229.94 toks/s, output: 820.69 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 958.31it/s, est. speed input: 835268.38 toks/s, output: 961.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.95it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1018.27it/s, est. speed input: 888683.04 toks/s, output: 1022.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1164.03it/s, est. speed input: 1015305.11 toks/s, output: 1168.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1334.21it/s, est. speed input: 1164326.13 toks/s, output: 1339.70 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  16%|█▌        | 8/50 [00:24<01:55,  2.75s/it, task=test_0170]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  16%|█▌        | 8/50 [00:24<01:55,  2.75s/it, task=test_0066]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.60it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.35it/s, est. speed input: 4645.98 toks/s, output: 5.35 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 137.86it/s, est. speed input: 119878.15 toks/s, output: 137.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 312.60it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 578.37it/s, est. speed input: 503530.15 toks/s, output: 579.41 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.00it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 640.67it/s, est. speed input: 557868.33 toks/s, output: 641.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.97it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.06it/s, est. speed input: 628077.27 toks/s, output: 722.71 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 724.20it/s, est. speed input: 630753.79 toks/s, output: 725.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 831.91it/s, est. speed input: 724793.41 toks/s, output: 833.99 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.88it/s, est. speed input: 713452.44 toks/s, output: 820.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 934.90it/s, est. speed input: 815573.78 toks/s, output: 938.41 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.19it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 999.54it/s, est. speed input: 871283.27 toks/s, output: 1002.54 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1156.68it/s, est. speed input: 1008815.44 toks/s, output: 1160.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1333.14it/s, est. speed input: 1163280.99 toks/s, output: 1338.48 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 558.72it/s, est. speed input: 486498.96 toks/s, output: 559.81 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.36it/s, est. speed input: 563702.91 toks/s, output: 648.65 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 652.02it/s, est. speed input: 567753.02 toks/s, output: 653.31 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.42it/s, est. speed input: 638820.49 toks/s, output: 735.07 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.46it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 729.28it/s, est. speed input: 635392.59 toks/s, output: 731.13 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.96it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 843.12it/s, est. speed input: 734566.51 toks/s, output: 845.25 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.29it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 826.86it/s, est. speed input: 720410.66 toks/s, output: 828.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 964.39it/s, est. speed input: 840565.63 toks/s, output: 967.21 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.94it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1005.54it/s, est. speed input: 876560.99 toks/s, output: 1008.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1173.26it/s, est. speed input: 1023322.30 toks/s, output: 1177.46 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1355.27it/s, est. speed input: 1182816.87 toks/s, output: 1360.99 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  18%|█▊        | 9/50 [00:27<01:50,  2.70s/it, task=test_0066]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  18%|█▊        | 9/50 [00:27<01:50,  2.70s/it, task=heldout_0046]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.60it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 124.59it/s, est. speed input: 108327.87 toks/s, output: 124.65 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 607.65it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 593.68it/s, est. speed input: 516896.92 toks/s, output: 594.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 638.82it/s, est. speed input: 556237.45 toks/s, output: 640.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.29it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 728.16it/s, est. speed input: 634417.97 toks/s, output: 730.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 725.40it/s, est. speed input: 631806.15 toks/s, output: 727.00 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 817.54it/s, est. speed input: 712280.41 toks/s, output: 819.59 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.27it/s, est. speed input: 720771.26 toks/s, output: 829.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 894.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 937.43it/s, est. speed input: 817042.06 toks/s, output: 940.14 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 999.53it/s, est. speed input: 871315.81 toks/s, output: 1002.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1115.40it/s, est. speed input: 972705.79 toks/s, output: 1119.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1339.65it/s, est. speed input: 1169052.57 toks/s, output: 1345.12 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 574.97it/s, est. speed input: 500537.32 toks/s, output: 575.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 650.14it/s, est. speed input: 566531.34 toks/s, output: 651.89 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.98it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.82it/s, est. speed input: 561496.64 toks/s, output: 646.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 738.27it/s, est. speed input: 643032.73 toks/s, output: 739.92 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 739.92it/s, est. speed input: 644507.35 toks/s, output: 741.62 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 841.33it/s, est. speed input: 733337.98 toks/s, output: 843.83 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 836.77it/s, est. speed input: 729864.12 toks/s, output: 839.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 968.63it/s, est. speed input: 844711.33 toks/s, output: 971.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.59it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1018.65it/s, est. speed input: 888019.96 toks/s, output: 1021.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1168.20it/s, est. speed input: 1018870.54 toks/s, output: 1172.34 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.75it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1346.84it/s, est. speed input: 1175331.59 toks/s, output: 1352.35 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  20%|██        | 10/50 [00:29<01:47,  2.68s/it, task=heldout_0046]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  20%|██        | 10/50 [00:29<01:47,  2.68s/it, task=test_0086]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.32it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.23it/s, est. speed input: 4546.87 toks/s, output: 5.23 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 118.68it/s, est. speed input: 103185.58 toks/s, output: 118.74 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 618.44it/s, est. speed input: 538457.16 toks/s, output: 619.60 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 634.12it/s, est. speed input: 552148.07 toks/s, output: 635.35 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.28it/s, est. speed input: 629922.58 toks/s, output: 724.84 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.69it/s, est. speed input: 628554.52 toks/s, output: 723.26 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 829.91it/s, est. speed input: 723063.51 toks/s, output: 832.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.95it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 816.76it/s, est. speed input: 711602.49 toks/s, output: 818.82 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.69it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 938.36it/s, est. speed input: 817803.99 toks/s, output: 941.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1003.57it/s, est. speed input: 874844.97 toks/s, output: 1006.64 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1121.37it/s, est. speed input: 977949.99 toks/s, output: 1125.27 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1337.20it/s, est. speed input: 1167776.74 toks/s, output: 1343.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.40it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 574.29it/s, est. speed input: 499962.30 toks/s, output: 575.31 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.88it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 652.38it/s, est. speed input: 568062.72 toks/s, output: 653.66 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.68it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.07it/s, est. speed input: 563852.79 toks/s, output: 648.81 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.04it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 741.24it/s, est. speed input: 645652.60 toks/s, output: 742.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 740.73it/s, est. speed input: 645174.03 toks/s, output: 742.38 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 845.01it/s, est. speed input: 736259.00 toks/s, output: 847.19 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 833.30it/s, est. speed input: 726047.69 toks/s, output: 835.43 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 958.04it/s, est. speed input: 835041.14 toks/s, output: 960.84 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1023.60it/s, est. speed input: 892368.24 toks/s, output: 1026.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.53it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1147.17it/s, est. speed input: 1000473.54 toks/s, output: 1151.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1322.22it/s, est. speed input: 1155616.38 toks/s, output: 1329.63 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  22%|██▏       | 11/50 [00:32<01:43,  2.65s/it, task=test_0086]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  22%|██▏       | 11/50 [00:32<01:43,  2.65s/it, task=test_0168]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.09it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 124.14it/s, est. speed input: 107933.00 toks/s, output: 124.20 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.05it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 603.84it/s, est. speed input: 525715.34 toks/s, output: 604.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 637.43it/s, est. speed input: 555239.17 toks/s, output: 638.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 894.06it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 726.91it/s, est. speed input: 633432.57 toks/s, output: 728.87 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 900.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 725.61it/s, est. speed input: 631970.47 toks/s, output: 727.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 893.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 825.06it/s, est. speed input: 718807.89 toks/s, output: 827.11 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.54it/s, est. speed input: 713086.04 toks/s, output: 820.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 900.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 936.78it/s, est. speed input: 816401.54 toks/s, output: 939.41 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 897.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1001.24it/s, est. speed input: 873246.78 toks/s, output: 1004.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 893.99it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1121.86it/s, est. speed input: 979189.73 toks/s, output: 1126.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.05it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1329.82it/s, est. speed input: 1160318.40 toks/s, output: 1335.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 893.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 575.34it/s, est. speed input: 501070.60 toks/s, output: 576.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 896.60it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 651.41it/s, est. speed input: 567220.13 toks/s, output: 652.69 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 895.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.49it/s, est. speed input: 562916.66 toks/s, output: 647.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 892.49it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 694.73it/s, est. speed input: 605321.72 toks/s, output: 696.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 903.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 738.73it/s, est. speed input: 643962.91 toks/s, output: 740.98 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 899.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 839.03it/s, est. speed input: 731365.26 toks/s, output: 841.53 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 899.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 837.21it/s, est. speed input: 729403.12 toks/s, output: 839.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 901.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 947.08it/s, est. speed input: 825397.04 toks/s, output: 949.74 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 894.69it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1034.84it/s, est. speed input: 902190.64 toks/s, output: 1038.11 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1153.56it/s, est. speed input: 1006022.28 toks/s, output: 1157.56 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 898.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1371.56it/s, est. speed input: 1196995.13 toks/s, output: 1377.28 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  24%|██▍       | 12/50 [00:35<01:40,  2.64s/it, task=test_0168]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  24%|██▍       | 12/50 [00:35<01:40,  2.64s/it, task=test_0088]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 900.35it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 129.91it/s, est. speed input: 112948.56 toks/s, output: 129.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 347.74it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 607.42it/s, est. speed input: 528845.12 toks/s, output: 608.54 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 633.83it/s, est. speed input: 551852.86 toks/s, output: 635.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.46it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 724.22it/s, est. speed input: 630767.43 toks/s, output: 725.81 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.12it/s, est. speed input: 628907.00 toks/s, output: 723.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.00it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 826.41it/s, est. speed input: 720001.52 toks/s, output: 828.48 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 820.80it/s, est. speed input: 715092.77 toks/s, output: 822.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 935.36it/s, est. speed input: 815722.08 toks/s, output: 938.59 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.39it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 986.04it/s, est. speed input: 859438.11 toks/s, output: 988.91 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1131.92it/s, est. speed input: 987062.10 toks/s, output: 1135.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 892.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1350.33it/s, est. speed input: 1178359.54 toks/s, output: 1355.82 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 572.78it/s, est. speed input: 498624.30 toks/s, output: 573.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 636.21it/s, est. speed input: 554197.06 toks/s, output: 637.70 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 650.25it/s, est. speed input: 566206.81 toks/s, output: 651.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 742.22it/s, est. speed input: 646450.61 toks/s, output: 743.85 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 739.84it/s, est. speed input: 644407.64 toks/s, output: 741.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 842.36it/s, est. speed input: 733919.40 toks/s, output: 844.49 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 832.04it/s, est. speed input: 725135.88 toks/s, output: 834.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 960.89it/s, est. speed input: 838468.82 toks/s, output: 964.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.39it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1017.59it/s, est. speed input: 887938.83 toks/s, output: 1021.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1144.24it/s, est. speed input: 998452.32 toks/s, output: 1148.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1375.90it/s, est. speed input: 1200753.65 toks/s, output: 1381.62 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  26%|██▌       | 13/50 [00:37<01:36,  2.62s/it, task=test_0088]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  26%|██▌       | 13/50 [00:37<01:36,  2.62s/it, task=test_0016]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.07it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 151.57it/s, est. speed input: 131781.66 toks/s, output: 151.64 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 707.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 306.34it/s, est. speed input: 266489.38 toks/s, output: 306.65 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 627.97it/s, est. speed input: 546789.89 toks/s, output: 629.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.69it/s, est. speed input: 628598.56 toks/s, output: 723.31 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 720.03it/s, est. speed input: 627135.06 toks/s, output: 721.63 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 826.19it/s, est. speed input: 719850.43 toks/s, output: 828.32 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.14it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 814.98it/s, est. speed input: 710272.12 toks/s, output: 817.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 942.74it/s, est. speed input: 821739.26 toks/s, output: 945.54 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 856.85it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1006.55it/s, est. speed input: 877504.05 toks/s, output: 1009.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1113.72it/s, est. speed input: 971263.97 toks/s, output: 1117.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1311.67it/s, est. speed input: 1144627.04 toks/s, output: 1317.04 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 856.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 582.31it/s, est. speed input: 506959.71 toks/s, output: 583.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 648.68it/s, est. speed input: 564871.37 toks/s, output: 649.99 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.89it/s, est. speed input: 563283.67 toks/s, output: 648.17 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 691.27it/s, est. speed input: 602044.09 toks/s, output: 692.77 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 736.84it/s, est. speed input: 641811.97 toks/s, output: 738.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 843.38it/s, est. speed input: 734858.09 toks/s, output: 845.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.42it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 842.99it/s, est. speed input: 734548.01 toks/s, output: 845.21 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 948.35it/s, est. speed input: 826561.07 toks/s, output: 951.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1038.22it/s, est. speed input: 905201.44 toks/s, output: 1041.57 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1140.91it/s, est. speed input: 995308.32 toks/s, output: 1145.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1352.67it/s, est. speed input: 1180518.28 toks/s, output: 1358.33 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  28%|██▊       | 14/50 [00:40<01:33,  2.61s/it, task=test_0016]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  28%|██▊       | 14/50 [00:40<01:33,  2.61s/it, task=test_0169]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.67it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 132.65it/s, est. speed input: 115331.95 toks/s, output: 132.72 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 337.20it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 369.67it/s, est. speed input: 321618.32 toks/s, output: 370.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 638.72it/s, est. speed input: 556168.49 toks/s, output: 639.98 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.47it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.19it/s, est. speed input: 629025.71 toks/s, output: 723.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 716.86it/s, est. speed input: 624592.78 toks/s, output: 718.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.99it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 823.37it/s, est. speed input: 717379.87 toks/s, output: 825.47 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 817.22it/s, est. speed input: 712045.60 toks/s, output: 819.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 936.06it/s, est. speed input: 815830.49 toks/s, output: 938.73 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 985.61it/s, est. speed input: 859153.23 toks/s, output: 988.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1113.02it/s, est. speed input: 971692.83 toks/s, output: 1118.02 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 852.14it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1317.68it/s, est. speed input: 1149874.36 toks/s, output: 1323.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 582.64it/s, est. speed input: 507252.94 toks/s, output: 583.69 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.04it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.24it/s, est. speed input: 561867.21 toks/s, output: 646.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.39it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.95it/s, est. speed input: 562495.87 toks/s, output: 647.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.23it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 738.36it/s, est. speed input: 643163.93 toks/s, output: 740.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.77it/s, est. speed input: 639577.14 toks/s, output: 735.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 831.20it/s, est. speed input: 724806.93 toks/s, output: 833.99 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 822.97it/s, est. speed input: 717027.05 toks/s, output: 825.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 951.02it/s, est. speed input: 828934.34 toks/s, output: 953.81 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1015.82it/s, est. speed input: 885653.15 toks/s, output: 1019.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1125.89it/s, est. speed input: 981926.60 toks/s, output: 1129.85 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.38it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1362.10it/s, est. speed input: 1188748.07 toks/s, output: 1367.78 toks/s]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  30%|███       | 15/50 [00:42<01:31,  2.62s/it, task=test_0169]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  30%|███       | 15/50 [00:42<01:31,  2.62s/it, task=test_0111]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.24it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.31it/s, est. speed input: 4611.93 toks/s, output: 5.31 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 135.95it/s, est. speed input: 118203.65 toks/s, output: 136.02 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 335.40it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 347.31it/s, est. speed input: 302143.39 toks/s, output: 347.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.98it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 631.13it/s, est. speed input: 549556.89 toks/s, output: 632.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.12it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 724.66it/s, est. speed input: 631146.30 toks/s, output: 726.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 724.97it/s, est. speed input: 631446.99 toks/s, output: 726.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 825.27it/s, est. speed input: 719082.65 toks/s, output: 827.43 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 825.75it/s, est. speed input: 719912.63 toks/s, output: 828.38 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 942.92it/s, est. speed input: 821924.57 toks/s, output: 945.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1007.36it/s, est. speed input: 878204.41 toks/s, output: 1010.50 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1141.82it/s, est. speed input: 995826.69 toks/s, output: 1145.84 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1324.91it/s, est. speed input: 1156212.08 toks/s, output: 1330.38 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.51it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 557.27it/s, est. speed input: 485139.12 toks/s, output: 558.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.11it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.46it/s, est. speed input: 561364.22 toks/s, output: 645.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.43it/s, est. speed input: 563762.85 toks/s, output: 648.71 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.18it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.96it/s, est. speed input: 636700.23 toks/s, output: 732.64 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 812.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 740.02it/s, est. speed input: 645024.17 toks/s, output: 742.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 837.06it/s, est. speed input: 729311.90 toks/s, output: 839.20 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 839.01it/s, est. speed input: 731044.37 toks/s, output: 841.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 954.80it/s, est. speed input: 832228.83 toks/s, output: 957.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1028.50it/s, est. speed input: 896717.94 toks/s, output: 1031.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1172.21it/s, est. speed input: 1022963.29 toks/s, output: 1177.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1363.82it/s, est. speed input: 1190276.62 toks/s, output: 1369.55 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  32%|███▏      | 16/50 [00:45<01:29,  2.62s/it, task=test_0111]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  32%|███▏      | 16/50 [00:45<01:29,  2.62s/it, task=test_0110]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.62it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.25it/s, est. speed input: 4559.88 toks/s, output: 5.25 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 132.02it/s, est. speed input: 114785.33 toks/s, output: 132.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 454.33it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 368.36it/s, est. speed input: 320474.81 toks/s, output: 368.78 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 636.04it/s, est. speed input: 554070.69 toks/s, output: 637.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.05it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 718.97it/s, est. speed input: 626205.76 toks/s, output: 720.56 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.09it/s, est. speed input: 628273.50 toks/s, output: 722.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 825.29it/s, est. speed input: 719051.62 toks/s, output: 827.40 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 812.40it/s, est. speed input: 707798.03 toks/s, output: 814.44 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 937.14it/s, est. speed input: 816801.75 toks/s, output: 939.86 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.45it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1009.11it/s, est. speed input: 880159.42 toks/s, output: 1012.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1116.95it/s, est. speed input: 974070.53 toks/s, output: 1120.81 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1317.82it/s, est. speed input: 1151611.43 toks/s, output: 1325.06 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 585.10it/s, est. speed input: 509410.80 toks/s, output: 586.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.54it/s, est. speed input: 562110.92 toks/s, output: 646.81 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.90it/s, est. speed input: 560854.04 toks/s, output: 645.36 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 734.17it/s, est. speed input: 639499.99 toks/s, output: 735.85 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.43it/s, est. speed input: 637967.90 toks/s, output: 734.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.45it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 845.82it/s, est. speed input: 736994.06 toks/s, output: 848.04 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.69it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 829.75it/s, est. speed input: 722938.02 toks/s, output: 831.86 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 964.10it/s, est. speed input: 840353.66 toks/s, output: 966.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.73it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1024.30it/s, est. speed input: 893051.50 toks/s, output: 1027.58 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.96it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1138.79it/s, est. speed input: 993587.13 toks/s, output: 1143.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1353.96it/s, est. speed input: 1182541.04 toks/s, output: 1360.64 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  34%|███▍      | 17/50 [00:48<01:26,  2.61s/it, task=test_0110]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  34%|███▍      | 17/50 [00:48<01:26,  2.61s/it, task=heldout_0041]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.71it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:06,  5.15it/s, est. speed input: 4479.54 toks/s, output: 5.15 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 123.96it/s, est. speed input: 107774.22 toks/s, output: 124.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 362.03it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 603.20it/s, est. speed input: 525435.88 toks/s, output: 604.60 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 629.98it/s, est. speed input: 548853.48 toks/s, output: 631.55 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.49it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 717.01it/s, est. speed input: 624572.71 toks/s, output: 718.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.98it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.60it/s, est. speed input: 629392.31 toks/s, output: 724.22 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.38it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.97it/s, est. speed input: 711138.24 toks/s, output: 818.28 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.02it/s, est. speed input: 717958.35 toks/s, output: 826.13 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.13it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 938.88it/s, est. speed input: 818326.13 toks/s, output: 941.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 871.60it/s, est. speed input: 759536.64 toks/s, output: 873.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1106.95it/s, est. speed input: 965323.45 toks/s, output: 1110.73 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.49it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1312.80it/s, est. speed input: 1145616.40 toks/s, output: 1318.16 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 570.18it/s, est. speed input: 496377.05 toks/s, output: 571.18 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.73it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.60it/s, est. speed input: 562165.11 toks/s, output: 646.87 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.79it/s, est. speed input: 560983.52 toks/s, output: 645.50 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.57it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.61it/s, est. speed input: 638114.50 toks/s, output: 734.26 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 681.14it/s, est. speed input: 593276.56 toks/s, output: 682.67 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.89it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 837.07it/s, est. speed input: 729371.19 toks/s, output: 839.26 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 839.29it/s, est. speed input: 731264.38 toks/s, output: 841.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.92it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 951.19it/s, est. speed input: 830019.75 toks/s, output: 955.03 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 966.58it/s, est. speed input: 842819.09 toks/s, output: 969.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1159.65it/s, est. speed input: 1011431.15 toks/s, output: 1163.77 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1364.24it/s, est. speed input: 1191322.17 toks/s, output: 1370.76 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  36%|███▌      | 18/50 [00:50<01:23,  2.62s/it, task=heldout_0041]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  36%|███▌      | 18/50 [00:50<01:23,  2.62s/it, task=test_0042]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.63it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 135.06it/s, est. speed input: 117426.66 toks/s, output: 135.13 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 338.29it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 596.16it/s, est. speed input: 519061.55 toks/s, output: 597.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.96it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.32it/s, est. speed input: 553200.84 toks/s, output: 636.56 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.45it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 719.15it/s, est. speed input: 626373.90 toks/s, output: 720.75 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 717.84it/s, est. speed input: 625242.33 toks/s, output: 719.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.96it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 811.92it/s, est. speed input: 707390.21 toks/s, output: 813.97 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 812.60it/s, est. speed input: 707952.69 toks/s, output: 814.63 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 936.98it/s, est. speed input: 816670.21 toks/s, output: 939.70 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 995.41it/s, est. speed input: 867731.08 toks/s, output: 998.46 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1101.10it/s, est. speed input: 960521.83 toks/s, output: 1105.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.54it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1309.54it/s, est. speed input: 1143269.45 toks/s, output: 1315.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 582.80it/s, est. speed input: 507513.39 toks/s, output: 583.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.31it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.22it/s, est. speed input: 560255.96 toks/s, output: 644.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.06it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 637.05it/s, est. speed input: 554713.67 toks/s, output: 638.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.75it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 729.23it/s, est. speed input: 635195.35 toks/s, output: 730.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.33it/s, est. speed input: 636116.85 toks/s, output: 731.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 832.99it/s, est. speed input: 725790.17 toks/s, output: 835.14 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 814.86it/s, est. speed input: 709956.51 toks/s, output: 816.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 852.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 955.86it/s, est. speed input: 833174.08 toks/s, output: 958.69 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1010.58it/s, est. speed input: 881743.04 toks/s, output: 1014.55 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1147.47it/s, est. speed input: 1000739.65 toks/s, output: 1151.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1324.16it/s, est. speed input: 1155547.69 toks/s, output: 1329.60 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  38%|███▊      | 19/50 [00:53<01:21,  2.62s/it, task=test_0042]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  38%|███▊      | 19/50 [00:53<01:21,  2.62s/it, task=test_0183]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.69it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 133.59it/s, est. speed input: 116145.30 toks/s, output: 133.65 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 334.43it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 592.38it/s, est. speed input: 515758.64 toks/s, output: 593.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 631.93it/s, est. speed input: 550246.52 toks/s, output: 633.16 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.79it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 708.10it/s, est. speed input: 617137.08 toks/s, output: 710.11 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 719.62it/s, est. speed input: 626976.61 toks/s, output: 721.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.69it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 819.34it/s, est. speed input: 713867.28 toks/s, output: 821.42 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 823.80it/s, est. speed input: 717759.53 toks/s, output: 825.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 926.99it/s, est. speed input: 808271.58 toks/s, output: 930.05 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 996.95it/s, est. speed input: 869678.60 toks/s, output: 1000.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1142.59it/s, est. speed input: 996524.37 toks/s, output: 1146.63 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1316.11it/s, est. speed input: 1148549.54 toks/s, output: 1321.52 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 577.10it/s, est. speed input: 502426.10 toks/s, output: 578.13 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.66it/s, est. speed input: 561377.73 toks/s, output: 645.97 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.48it/s, est. speed input: 561491.24 toks/s, output: 646.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.54it/s, est. speed input: 636293.84 toks/s, output: 732.17 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 675.33it/s, est. speed input: 588136.96 toks/s, output: 676.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 845.60it/s, est. speed input: 736831.10 toks/s, output: 847.85 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 840.20it/s, est. speed input: 732085.98 toks/s, output: 842.38 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 953.18it/s, est. speed input: 830829.76 toks/s, output: 955.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.64it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1005.49it/s, est. speed input: 876607.11 toks/s, output: 1008.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1159.38it/s, est. speed input: 1011168.09 toks/s, output: 1163.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1350.27it/s, est. speed input: 1179622.81 toks/s, output: 1357.24 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  40%|████      | 20/50 [00:55<01:18,  2.61s/it, task=test_0183]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  40%|████      | 20/50 [00:55<01:18,  2.61s/it, task=test_0129]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.17it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 138.39it/s, est. speed input: 120328.45 toks/s, output: 138.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 352.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 590.83it/s, est. speed input: 514505.04 toks/s, output: 592.04 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.23it/s, est. speed input: 553164.11 toks/s, output: 636.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.45it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 717.25it/s, est. speed input: 624713.21 toks/s, output: 718.85 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.35it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.46it/s, est. speed input: 629259.88 toks/s, output: 724.08 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 814.11it/s, est. speed input: 709287.31 toks/s, output: 816.16 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 810.06it/s, est. speed input: 706413.37 toks/s, output: 812.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 938.20it/s, est. speed input: 818360.58 toks/s, output: 941.65 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.15it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1004.75it/s, est. speed input: 875909.29 toks/s, output: 1007.87 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1118.87it/s, est. speed input: 975732.88 toks/s, output: 1122.72 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1318.78it/s, est. speed input: 1150838.75 toks/s, output: 1324.19 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 571.15it/s, est. speed input: 497231.97 toks/s, output: 572.16 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 639.45it/s, est. speed input: 556832.29 toks/s, output: 640.74 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.70it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 639.47it/s, est. speed input: 556821.66 toks/s, output: 640.72 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.26it/s, est. speed input: 638687.56 toks/s, output: 734.93 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.00it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 731.50it/s, est. speed input: 637138.47 toks/s, output: 733.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 836.87it/s, est. speed input: 729147.76 toks/s, output: 839.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.85it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 808.30it/s, est. speed input: 704221.07 toks/s, output: 810.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 950.52it/s, est. speed input: 828480.95 toks/s, output: 953.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.70it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1018.71it/s, est. speed input: 888128.15 toks/s, output: 1021.92 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1156.94it/s, est. speed input: 1009033.62 toks/s, output: 1161.03 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1179.87it/s, est. speed input: 1030519.31 toks/s, output: 1185.74 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  42%|████▏     | 21/50 [00:58<01:15,  2.61s/it, task=test_0129]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  42%|████▏     | 21/50 [00:58<01:15,  2.61s/it, task=test_0187]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.93it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 127.70it/s, est. speed input: 111022.36 toks/s, output: 127.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 564.44it/s, est. speed input: 491379.05 toks/s, output: 565.43 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 634.15it/s, est. speed input: 552179.44 toks/s, output: 635.38 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 712.88it/s, est. speed input: 620895.43 toks/s, output: 714.45 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.09it/s, est. speed input: 628930.74 toks/s, output: 723.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 813.27it/s, est. speed input: 708550.50 toks/s, output: 815.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.27it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.50it/s, est. speed input: 710531.74 toks/s, output: 817.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 928.94it/s, est. speed input: 810664.78 toks/s, output: 932.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1006.40it/s, est. speed input: 877339.03 toks/s, output: 1009.52 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1120.90it/s, est. speed input: 977523.79 toks/s, output: 1124.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 856.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1314.87it/s, est. speed input: 1147442.21 toks/s, output: 1320.26 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 554.42it/s, est. speed input: 482645.75 toks/s, output: 555.38 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.64it/s, est. speed input: 563076.99 toks/s, output: 647.93 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.27it/s, est. speed input: 562043.20 toks/s, output: 646.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 859.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 731.66it/s, est. speed input: 637274.24 toks/s, output: 733.30 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 727.69it/s, est. speed input: 633838.76 toks/s, output: 729.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 805.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.94it/s, est. speed input: 730984.81 toks/s, output: 841.13 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.69it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 829.79it/s, est. speed input: 722987.32 toks/s, output: 831.92 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 957.27it/s, est. speed input: 834401.93 toks/s, output: 960.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.36it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 960.26it/s, est. speed input: 837601.75 toks/s, output: 963.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 343.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1038.44it/s, est. speed input: 905918.58 toks/s, output: 1042.37 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1359.84it/s, est. speed input: 1186776.48 toks/s, output: 1365.51 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  44%|████▍     | 22/50 [01:02<01:21,  2.92s/it, task=test_0187]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  44%|████▍     | 22/50 [01:02<01:21,  2.92s/it, task=test_0039]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.25it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.18it/s, est. speed input: 4501.79 toks/s, output: 5.18 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 122.61it/s, est. speed input: 106587.23 toks/s, output: 122.65 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 604.35it/s, est. speed input: 526182.56 toks/s, output: 605.47 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.01it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.04it/s, est. speed input: 553124.76 toks/s, output: 636.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 715.79it/s, est. speed input: 623444.30 toks/s, output: 717.39 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.40it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.36it/s, est. speed input: 628310.73 toks/s, output: 722.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 822.81it/s, est. speed input: 717543.16 toks/s, output: 825.64 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.32it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 810.86it/s, est. speed input: 706464.72 toks/s, output: 812.91 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 935.80it/s, est. speed input: 815630.81 toks/s, output: 938.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 993.78it/s, est. speed input: 866326.03 toks/s, output: 996.84 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1116.71it/s, est. speed input: 974314.64 toks/s, output: 1121.08 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1321.40it/s, est. speed input: 1153114.30 toks/s, output: 1326.79 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.26it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 581.91it/s, est. speed input: 506602.99 toks/s, output: 582.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.41it/s, est. speed input: 563128.65 toks/s, output: 647.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.08it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.40it/s, est. speed input: 563732.88 toks/s, output: 648.68 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 846.35it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 731.77it/s, est. speed input: 637563.37 toks/s, output: 733.63 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.45it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.09it/s, est. speed input: 635919.16 toks/s, output: 731.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.04it/s, est. speed input: 730215.97 toks/s, output: 840.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.80it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.55it/s, est. speed input: 721043.07 toks/s, output: 829.68 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.45it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 903.29it/s, est. speed input: 787713.79 toks/s, output: 906.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 435.12it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 401.64it/s, est. speed input: 349557.81 toks/s, output: 402.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1160.64it/s, est. speed input: 1012344.14 toks/s, output: 1164.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1354.05it/s, est. speed input: 1181726.32 toks/s, output: 1359.72 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  46%|████▌     | 23/50 [01:04<01:16,  2.83s/it, task=test_0039]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  46%|████▌     | 23/50 [01:04<01:16,  2.83s/it, task=test_0145]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 856.24it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 135.22it/s, est. speed input: 117554.13 toks/s, output: 135.27 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.35it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 596.84it/s, est. speed input: 519887.52 toks/s, output: 598.22 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.70it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.04it/s, est. speed input: 553237.58 toks/s, output: 636.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 714.84it/s, est. speed input: 622575.73 toks/s, output: 716.39 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.16it/s, est. speed input: 629868.15 toks/s, output: 724.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.19it/s, est. speed input: 710237.52 toks/s, output: 817.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.44it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 806.83it/s, est. speed input: 702922.37 toks/s, output: 808.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 932.19it/s, est. speed input: 812483.15 toks/s, output: 934.89 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 988.89it/s, est. speed input: 863075.84 toks/s, output: 993.07 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1135.80it/s, est. speed input: 991130.16 toks/s, output: 1140.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.69it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1306.85it/s, est. speed input: 1140363.18 toks/s, output: 1312.12 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 583.23it/s, est. speed input: 507760.85 toks/s, output: 584.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 642.23it/s, est. speed input: 559235.17 toks/s, output: 643.51 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 642.48it/s, est. speed input: 559444.40 toks/s, output: 643.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 734.19it/s, est. speed input: 639489.47 toks/s, output: 735.85 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.96it/s, est. speed input: 638411.38 toks/s, output: 734.61 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 783.21it/s, est. speed input: 682308.65 toks/s, output: 785.11 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.81it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 830.02it/s, est. speed input: 723175.59 toks/s, output: 832.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 383.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 357.22it/s, est. speed input: 310950.93 toks/s, output: 357.81 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1023.34it/s, est. speed input: 893393.53 toks/s, output: 1027.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1149.35it/s, est. speed input: 1002399.58 toks/s, output: 1153.39 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1348.37it/s, est. speed input: 1178180.99 toks/s, output: 1355.63 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  48%|████▊     | 24/50 [01:07<01:12,  2.79s/it, task=test_0145]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  48%|████▊     | 24/50 [01:07<01:12,  2.79s/it, task=heldout_0008]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 766.00it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1296.55it/s, est. speed input: 1131468.87 toks/s, output: 1301.87 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1238.34it/s, est. speed input: 1080786.21 toks/s, output: 1243.56 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1226.90it/s, est. speed input: 1070971.35 toks/s, output: 1232.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1075.72it/s, est. speed input: 937989.20 toks/s, output: 1079.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1142.69it/s, est. speed input: 996601.01 toks/s, output: 1146.72 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.35it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1237.45it/s, est. speed input: 1079645.71 toks/s, output: 1242.27 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1213.57it/s, est. speed input: 1058616.64 toks/s, output: 1218.07 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.69it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1276.25it/s, est. speed input: 1113579.52 toks/s, output: 1281.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1247.09it/s, est. speed input: 1089244.44 toks/s, output: 1253.27 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1306.92it/s, est. speed input: 1140385.48 toks/s, output: 1312.14 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1297.78it/s, est. speed input: 1132303.68 toks/s, output: 1302.86 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.99it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 582.29it/s, est. speed input: 506994.96 toks/s, output: 583.40 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.22it/s, est. speed input: 562699.40 toks/s, output: 647.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.00it/s, est. speed input: 560765.05 toks/s, output: 645.26 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.87it/s, est. speed input: 630470.79 toks/s, output: 725.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 856.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.95it/s, est. speed input: 636662.00 toks/s, output: 732.59 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 829.81it/s, est. speed input: 723027.65 toks/s, output: 831.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 836.71it/s, est. speed input: 729549.11 toks/s, output: 839.44 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.06it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 939.16it/s, est. speed input: 818573.09 toks/s, output: 941.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1011.93it/s, est. speed input: 882536.99 toks/s, output: 1015.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.62it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1156.44it/s, est. speed input: 1009077.27 toks/s, output: 1161.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1216.64it/s, est. speed input: 1062774.09 toks/s, output: 1222.82 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  50%|█████     | 25/50 [01:09<01:05,  2.62s/it, task=heldout_0008]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  50%|█████     | 25/50 [01:09<01:05,  2.62s/it, task=heldout_0021]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.53it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 137.95it/s, est. speed input: 119933.13 toks/s, output: 138.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 583.43it/s, est. speed input: 507924.48 toks/s, output: 584.47 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 632.54it/s, est. speed input: 550784.40 toks/s, output: 633.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.86it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.66it/s, est. speed input: 628551.13 toks/s, output: 723.26 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 714.90it/s, est. speed input: 622655.50 toks/s, output: 716.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 820.54it/s, est. speed input: 714886.77 toks/s, output: 822.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.68it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.67it/s, est. speed input: 710631.31 toks/s, output: 817.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 932.70it/s, est. speed input: 812958.85 toks/s, output: 935.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 990.54it/s, est. speed input: 863491.17 toks/s, output: 993.58 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1128.16it/s, est. speed input: 983906.31 toks/s, output: 1132.11 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1323.09it/s, est. speed input: 1154518.24 toks/s, output: 1328.41 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 855.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 571.07it/s, est. speed input: 497223.49 toks/s, output: 572.15 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 637.49it/s, est. speed input: 555257.67 toks/s, output: 638.93 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.86it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.75it/s, est. speed input: 561588.56 toks/s, output: 646.21 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 682.22it/s, est. speed input: 594458.86 toks/s, output: 684.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 351.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 334.74it/s, est. speed input: 291192.72 toks/s, output: 335.08 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 759.61it/s, est. speed input: 661666.18 toks/s, output: 761.36 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.86it/s, est. speed input: 718688.30 toks/s, output: 826.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.45it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 960.47it/s, est. speed input: 837156.86 toks/s, output: 963.28 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1019.55it/s, est. speed input: 889340.33 toks/s, output: 1023.32 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1130.93it/s, est. speed input: 986344.23 toks/s, output: 1134.92 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1344.96it/s, est. speed input: 1173793.91 toks/s, output: 1350.59 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  52%|█████▏    | 26/50 [01:12<01:06,  2.76s/it, task=heldout_0021]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  52%|█████▏    | 26/50 [01:12<01:06,  2.76s/it, task=test_0089]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.20it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 135.77it/s, est. speed input: 118032.00 toks/s, output: 135.82 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 588.19it/s, est. speed input: 512092.47 toks/s, output: 589.26 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 860.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 625.36it/s, est. speed input: 544960.66 toks/s, output: 627.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 701.18it/s, est. speed input: 610681.11 toks/s, output: 702.70 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 715.47it/s, est. speed input: 623167.82 toks/s, output: 717.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 819.56it/s, est. speed input: 714042.09 toks/s, output: 821.63 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.44it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 813.70it/s, est. speed input: 708938.10 toks/s, output: 815.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 943.97it/s, est. speed input: 822788.49 toks/s, output: 946.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1001.08it/s, est. speed input: 872697.93 toks/s, output: 1004.17 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1130.01it/s, est. speed input: 985527.48 toks/s, output: 1133.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1301.81it/s, est. speed input: 1136031.38 toks/s, output: 1307.13 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 581.06it/s, est. speed input: 505882.28 toks/s, output: 582.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.06it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.13it/s, est. speed input: 560013.86 toks/s, output: 644.40 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.64it/s, est. speed input: 562680.39 toks/s, output: 647.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 688.72it/s, est. speed input: 600049.42 toks/s, output: 690.46 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 344.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 708.76it/s, est. speed input: 617284.06 toks/s, output: 710.27 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 837.79it/s, est. speed input: 730078.84 toks/s, output: 840.08 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.02it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 831.29it/s, est. speed input: 724482.77 toks/s, output: 833.62 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 951.34it/s, est. speed input: 829146.48 toks/s, output: 954.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1023.00it/s, est. speed input: 891801.92 toks/s, output: 1026.16 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1162.02it/s, est. speed input: 1014492.65 toks/s, output: 1167.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1385.76it/s, est. speed input: 1209369.32 toks/s, output: 1391.52 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  54%|█████▍    | 27/50 [01:15<01:02,  2.72s/it, task=test_0089]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  54%|█████▍    | 27/50 [01:15<01:02,  2.72s/it, task=test_0021]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.99it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 143.01it/s, est. speed input: 124327.87 toks/s, output: 143.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 892.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 602.00it/s, est. speed input: 524233.80 toks/s, output: 603.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.12it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.43it/s, est. speed input: 553521.13 toks/s, output: 636.92 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.51it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.84it/s, est. speed input: 629575.76 toks/s, output: 724.44 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.94it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 713.22it/s, est. speed input: 621186.43 toks/s, output: 714.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.31it/s, est. speed input: 718179.39 toks/s, output: 826.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.23it/s, est. speed input: 720713.36 toks/s, output: 829.30 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 940.38it/s, est. speed input: 819608.49 toks/s, output: 943.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 990.10it/s, est. speed input: 862999.21 toks/s, output: 993.01 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.38it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1119.91it/s, est. speed input: 976607.07 toks/s, output: 1123.72 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1334.29it/s, est. speed input: 1164605.15 toks/s, output: 1339.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.67it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 571.04it/s, est. speed input: 497128.12 toks/s, output: 572.04 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 642.57it/s, est. speed input: 559516.86 toks/s, output: 643.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.81it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.41it/s, est. speed input: 561986.33 toks/s, output: 646.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 714.22it/s, est. speed input: 622712.01 toks/s, output: 716.27 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 335.61it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 700.95it/s, est. speed input: 610476.54 toks/s, output: 702.46 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 826.34it/s, est. speed input: 719921.52 toks/s, output: 828.39 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 788.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 839.35it/s, est. speed input: 731314.81 toks/s, output: 841.50 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 841.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 961.60it/s, est. speed input: 838107.32 toks/s, output: 964.38 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.51it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1017.74it/s, est. speed input: 887175.63 toks/s, output: 1020.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1137.01it/s, est. speed input: 991526.16 toks/s, output: 1140.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1362.34it/s, est. speed input: 1188820.77 toks/s, output: 1367.88 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  56%|█████▌    | 28/50 [01:18<00:59,  2.69s/it, task=test_0021]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  56%|█████▌    | 28/50 [01:18<00:59,  2.69s/it, task=test_0176]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.02it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.29it/s, est. speed input: 4594.95 toks/s, output: 5.29 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 121.67it/s, est. speed input: 105769.41 toks/s, output: 121.71 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 613.21it/s, est. speed input: 533977.97 toks/s, output: 614.43 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.94it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 631.69it/s, est. speed input: 550023.37 toks/s, output: 632.91 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 717.60it/s, est. speed input: 624991.05 toks/s, output: 719.16 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.33it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.61it/s, est. speed input: 630232.32 toks/s, output: 725.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 831.07it/s, est. speed input: 724113.95 toks/s, output: 833.22 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 820.49it/s, est. speed input: 714821.05 toks/s, output: 822.53 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.08it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 933.88it/s, est. speed input: 814230.11 toks/s, output: 936.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.28it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 992.68it/s, est. speed input: 866107.30 toks/s, output: 996.56 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1136.78it/s, est. speed input: 991382.89 toks/s, output: 1140.72 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1308.41it/s, est. speed input: 1141624.47 toks/s, output: 1313.58 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.12it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 567.34it/s, est. speed input: 494170.91 toks/s, output: 568.63 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 646.35it/s, est. speed input: 562818.87 toks/s, output: 647.63 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.54it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.92it/s, est. speed input: 562436.19 toks/s, output: 647.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 807.46it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 677.58it/s, est. speed input: 590303.95 toks/s, output: 679.24 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 816.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 725.91it/s, est. speed input: 632213.68 toks/s, output: 727.48 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.70it/s, est. speed input: 730755.82 toks/s, output: 840.86 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.09it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 836.50it/s, est. speed input: 728796.95 toks/s, output: 838.60 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 957.15it/s, est. speed input: 834276.60 toks/s, output: 959.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.34it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1029.05it/s, est. speed input: 897090.38 toks/s, output: 1032.23 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1166.03it/s, est. speed input: 1016960.55 toks/s, output: 1170.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.99it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1367.70it/s, est. speed input: 1193601.99 toks/s, output: 1373.38 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  58%|█████▊    | 29/50 [01:20<00:55,  2.67s/it, task=test_0176]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  58%|█████▊    | 29/50 [01:20<00:55,  2.67s/it, task=heldout_0007]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1315.06it/s, est. speed input: 1147419.63 toks/s, output: 1320.26 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1308.31it/s, est. speed input: 1141646.82 toks/s, output: 1313.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.42it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1326.28it/s, est. speed input: 1157267.51 toks/s, output: 1331.58 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1320.94it/s, est. speed input: 1152647.08 toks/s, output: 1326.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1322.16it/s, est. speed input: 1154804.02 toks/s, output: 1328.74 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.86it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1321.04it/s, est. speed input: 1152726.83 toks/s, output: 1326.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1340.90it/s, est. speed input: 1170061.15 toks/s, output: 1346.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1330.39it/s, est. speed input: 1162770.72 toks/s, output: 1337.91 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1334.07it/s, est. speed input: 1164024.01 toks/s, output: 1339.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1320.01it/s, est. speed input: 1151782.01 toks/s, output: 1325.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.45it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1313.21it/s, est. speed input: 1146889.34 toks/s, output: 1319.59 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1351.11it/s, est. speed input: 1179050.43 toks/s, output: 1356.64 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1357.19it/s, est. speed input: 1184450.46 toks/s, output: 1362.80 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.97it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1354.01it/s, est. speed input: 1181606.60 toks/s, output: 1359.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1354.87it/s, est. speed input: 1184474.52 toks/s, output: 1362.82 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1228.21it/s, est. speed input: 1071414.06 toks/s, output: 1232.81 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1364.25it/s, est. speed input: 1190653.29 toks/s, output: 1369.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1208.08it/s, est. speed input: 1054930.32 toks/s, output: 1213.79 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1355.90it/s, est. speed input: 1183188.83 toks/s, output: 1361.40 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1234.61it/s, est. speed input: 1077969.35 toks/s, output: 1240.32 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 498.95it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 399.82it/s, est. speed input: 347870.92 toks/s, output: 400.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1332.56it/s, est. speed input: 1163362.22 toks/s, output: 1338.60 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  60%|██████    | 30/50 [01:22<00:49,  2.48s/it, task=heldout_0007]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  60%|██████    | 30/50 [01:22<00:49,  2.48s/it, task=test_0151]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.59it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 123.73it/s, est. speed input: 107559.65 toks/s, output: 123.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 610.32it/s, est. speed input: 531372.52 toks/s, output: 611.45 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 634.25it/s, est. speed input: 552268.33 toks/s, output: 635.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.80it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 715.45it/s, est. speed input: 623317.69 toks/s, output: 717.24 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.61it/s, est. speed input: 628496.94 toks/s, output: 723.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.94it/s, est. speed input: 721341.85 toks/s, output: 830.03 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.01it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 811.33it/s, est. speed input: 706794.36 toks/s, output: 813.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 892.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 928.31it/s, est. speed input: 809034.07 toks/s, output: 930.92 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 995.58it/s, est. speed input: 867827.93 toks/s, output: 998.58 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1119.95it/s, est. speed input: 976615.25 toks/s, output: 1123.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1305.99it/s, est. speed input: 1139494.18 toks/s, output: 1311.13 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 581.24it/s, est. speed input: 506005.18 toks/s, output: 582.26 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 641.95it/s, est. speed input: 558959.12 toks/s, output: 643.19 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.56it/s, est. speed input: 562127.18 toks/s, output: 646.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.30it/s, est. speed input: 637821.37 toks/s, output: 733.93 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 727.05it/s, est. speed input: 633243.42 toks/s, output: 728.66 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 833.80it/s, est. speed input: 726427.54 toks/s, output: 835.87 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.53it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.15it/s, est. speed input: 718236.88 toks/s, output: 826.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 867.75it/s, est. speed input: 756555.96 toks/s, output: 870.52 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 348.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1010.20it/s, est. speed input: 880637.90 toks/s, output: 1013.31 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1159.93it/s, est. speed input: 1011553.95 toks/s, output: 1163.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.98it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1343.48it/s, est. speed input: 1172330.94 toks/s, output: 1348.91 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  62%|██████▏   | 31/50 [01:25<00:48,  2.53s/it, task=test_0151]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  62%|██████▏   | 31/50 [01:25<00:48,  2.53s/it, task=test_0132]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.80it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.27it/s, est. speed input: 4578.22 toks/s, output: 5.27 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 123.02it/s, est. speed input: 106940.51 toks/s, output: 123.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.89it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 602.25it/s, est. speed input: 524481.32 toks/s, output: 603.51 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.00it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 632.95it/s, est. speed input: 551226.92 toks/s, output: 634.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 716.52it/s, est. speed input: 624038.04 toks/s, output: 718.06 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.23it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 716.95it/s, est. speed input: 624418.90 toks/s, output: 718.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.04it/s, est. speed input: 712715.66 toks/s, output: 820.10 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.70it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 818.71it/s, est. speed input: 713273.56 toks/s, output: 820.74 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 940.93it/s, est. speed input: 820052.21 toks/s, output: 943.60 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.50it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 996.01it/s, est. speed input: 869088.89 toks/s, output: 1000.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 880.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1112.81it/s, est. speed input: 970407.40 toks/s, output: 1116.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1320.86it/s, est. speed input: 1152555.96 toks/s, output: 1326.14 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.58it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 571.42it/s, est. speed input: 497437.67 toks/s, output: 572.40 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 649.73it/s, est. speed input: 565737.18 toks/s, output: 650.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.78it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 636.78it/s, est. speed input: 554526.42 toks/s, output: 638.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.38it/s, est. speed input: 636200.13 toks/s, output: 732.07 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.08it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.00it/s, est. speed input: 638400.90 toks/s, output: 734.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.23it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 837.33it/s, est. speed input: 729535.43 toks/s, output: 839.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.49it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 744.07it/s, est. speed input: 648567.89 toks/s, output: 746.28 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 362.75it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 381.30it/s, est. speed input: 331744.91 toks/s, output: 381.74 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1025.22it/s, est. speed input: 894688.76 toks/s, output: 1029.46 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1139.74it/s, est. speed input: 993908.87 toks/s, output: 1143.63 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.39it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1333.05it/s, est. speed input: 1163222.99 toks/s, output: 1338.43 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  64%|██████▍   | 32/50 [01:28<00:46,  2.56s/it, task=test_0132]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  64%|██████▍   | 32/50 [01:28<00:46,  2.56s/it, task=heldout_0012]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.96it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 141.95it/s, est. speed input: 123405.22 toks/s, output: 142.01 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 609.77it/s, est. speed input: 530912.96 toks/s, output: 610.91 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.74it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 636.01it/s, est. speed input: 553789.20 toks/s, output: 637.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.46it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 714.24it/s, est. speed input: 622034.52 toks/s, output: 715.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.64it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.12it/s, est. speed input: 628537.59 toks/s, output: 723.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 830.66it/s, est. speed input: 723718.55 toks/s, output: 832.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.40it/s, est. speed input: 719260.02 toks/s, output: 827.63 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 926.07it/s, est. speed input: 807974.82 toks/s, output: 929.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 958.34it/s, est. speed input: 835304.27 toks/s, output: 961.15 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1127.38it/s, est. speed input: 983110.15 toks/s, output: 1131.21 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1318.25it/s, est. speed input: 1150362.02 toks/s, output: 1323.61 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.84it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 553.98it/s, est. speed input: 482254.61 toks/s, output: 554.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 795.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.91it/s, est. speed input: 561545.30 toks/s, output: 646.16 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.20it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.61it/s, est. speed input: 563915.49 toks/s, output: 648.89 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.67it/s, est. speed input: 636429.25 toks/s, output: 732.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.45it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 726.09it/s, est. speed input: 632896.37 toks/s, output: 728.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 837.60it/s, est. speed input: 730380.58 toks/s, output: 840.42 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 786.34it/s, est. speed input: 685686.10 toks/s, output: 788.98 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 347.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 916.24it/s, est. speed input: 798882.22 toks/s, output: 919.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 800.77it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 909.59it/s, est. speed input: 792913.56 toks/s, output: 912.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.23it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1142.26it/s, est. speed input: 996166.90 toks/s, output: 1146.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1348.42it/s, est. speed input: 1176707.08 toks/s, output: 1353.94 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  66%|██████▌   | 33/50 [01:30<00:43,  2.58s/it, task=heldout_0012]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  66%|██████▌   | 33/50 [01:30<00:43,  2.58s/it, task=test_0104]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.18it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 134.37it/s, est. speed input: 116815.22 toks/s, output: 134.42 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 587.20it/s, est. speed input: 511268.65 toks/s, output: 588.31 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.85it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 634.15it/s, est. speed input: 552338.94 toks/s, output: 635.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 719.11it/s, est. speed input: 626693.63 toks/s, output: 721.12 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.15it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 718.16it/s, est. speed input: 625493.81 toks/s, output: 719.75 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 811.17it/s, est. speed input: 706712.99 toks/s, output: 813.19 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.40it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 813.27it/s, est. speed input: 708524.67 toks/s, output: 815.27 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 938.17it/s, est. speed input: 817672.13 toks/s, output: 940.86 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 984.74it/s, est. speed input: 858388.14 toks/s, output: 987.72 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1117.32it/s, est. speed input: 974339.06 toks/s, output: 1121.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1323.79it/s, est. speed input: 1155147.13 toks/s, output: 1329.13 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 564.25it/s, est. speed input: 491341.79 toks/s, output: 565.38 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.16it/s, est. speed input: 560897.19 toks/s, output: 645.42 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.85it/s, est. speed input: 560635.67 toks/s, output: 645.11 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.07it/s, est. speed input: 637612.17 toks/s, output: 733.69 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 734.37it/s, est. speed input: 639619.23 toks/s, output: 736.00 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 831.87it/s, est. speed input: 724766.39 toks/s, output: 833.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.30it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 601.47it/s, est. speed input: 523857.07 toks/s, output: 602.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 318.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 937.51it/s, est. speed input: 817168.00 toks/s, output: 940.28 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 818.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 976.03it/s, est. speed input: 850730.89 toks/s, output: 978.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 823.45it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1113.86it/s, est. speed input: 971830.47 toks/s, output: 1118.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 815.62it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1300.60it/s, est. speed input: 1134716.17 toks/s, output: 1305.63 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  68%|██████▊   | 34/50 [01:33<00:41,  2.60s/it, task=test_0104]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  68%|██████▊   | 34/50 [01:33<00:41,  2.60s/it, task=heldout_0011]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.34it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.21it/s, est. speed input: 4525.68 toks/s, output: 5.21 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 123.85it/s, est. speed input: 107663.90 toks/s, output: 123.89 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 605.61it/s, est. speed input: 527276.78 toks/s, output: 606.73 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.85it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 618.44it/s, est. speed input: 538479.53 toks/s, output: 619.62 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 817.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 704.94it/s, est. speed input: 614202.47 toks/s, output: 706.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 818.92it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 698.30it/s, est. speed input: 608187.75 toks/s, output: 699.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 821.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 805.30it/s, est. speed input: 702080.36 toks/s, output: 807.85 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 810.75it/s, est. speed input: 706340.65 toks/s, output: 812.77 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 929.18it/s, est. speed input: 809775.51 toks/s, output: 931.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.93it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 868.23it/s, est. speed input: 756521.61 toks/s, output: 870.50 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1139.35it/s, est. speed input: 993604.06 toks/s, output: 1143.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1322.65it/s, est. speed input: 1155181.45 toks/s, output: 1329.15 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.60it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 569.40it/s, est. speed input: 495676.70 toks/s, output: 570.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.89it/s, est. speed input: 560670.71 toks/s, output: 645.16 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.44it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.21it/s, est. speed input: 560226.36 toks/s, output: 644.64 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 734.25it/s, est. speed input: 639521.03 toks/s, output: 735.88 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.21it/s, est. speed input: 637751.62 toks/s, output: 733.85 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 796.08it/s, est. speed input: 693988.67 toks/s, output: 798.54 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 482.38it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 377.70it/s, est. speed input: 328751.76 toks/s, output: 378.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 957.14it/s, est. speed input: 834216.93 toks/s, output: 959.89 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 972.83it/s, est. speed input: 847972.36 toks/s, output: 975.71 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1158.45it/s, est. speed input: 1010300.97 toks/s, output: 1162.50 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1359.54it/s, est. speed input: 1186655.74 toks/s, output: 1365.39 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  70%|███████   | 35/50 [01:35<00:39,  2.61s/it, task=heldout_0011]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  70%|███████   | 35/50 [01:35<00:39,  2.61s/it, task=test_0154]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.54it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 143.17it/s, est. speed input: 124470.37 toks/s, output: 143.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 584.31it/s, est. speed input: 508695.39 toks/s, output: 585.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.46it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 633.51it/s, est. speed input: 551604.92 toks/s, output: 634.72 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.70it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 712.70it/s, est. speed input: 620743.42 toks/s, output: 714.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.27it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 716.48it/s, est. speed input: 624018.01 toks/s, output: 718.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 823.54it/s, est. speed input: 717485.78 toks/s, output: 825.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.80it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 810.38it/s, est. speed input: 706242.28 toks/s, output: 812.64 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 791.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 930.20it/s, est. speed input: 811567.30 toks/s, output: 933.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1004.19it/s, est. speed input: 875370.24 toks/s, output: 1007.25 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.38it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1095.65it/s, est. speed input: 956143.83 toks/s, output: 1100.15 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1341.76it/s, est. speed input: 1172814.26 toks/s, output: 1349.42 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.17it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 554.14it/s, est. speed input: 482380.26 toks/s, output: 555.07 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 353.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 640.51it/s, est. speed input: 557734.95 toks/s, output: 641.78 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.94it/s, est. speed input: 560705.75 toks/s, output: 645.20 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.75it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.44it/s, est. speed input: 638809.99 toks/s, output: 735.07 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.20it/s, est. speed input: 638596.64 toks/s, output: 734.82 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 834.27it/s, est. speed input: 726875.72 toks/s, output: 836.40 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.97it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.97it/s, est. speed input: 721355.23 toks/s, output: 830.04 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 852.50it/s, est. speed input: 742809.50 toks/s, output: 854.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1014.33it/s, est. speed input: 884269.94 toks/s, output: 1017.49 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1140.15it/s, est. speed input: 994883.83 toks/s, output: 1144.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1380.43it/s, est. speed input: 1204747.35 toks/s, output: 1386.19 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  72%|███████▏  | 36/50 [01:38<00:36,  2.62s/it, task=test_0154]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  72%|███████▏  | 36/50 [01:38<00:36,  2.62s/it, task=test_0015]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.22it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 138.26it/s, est. speed input: 120195.89 toks/s, output: 138.31 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 602.80it/s, est. speed input: 525125.98 toks/s, output: 604.25 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 633.32it/s, est. speed input: 551709.29 toks/s, output: 634.84 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.14it/s, est. speed input: 628978.22 toks/s, output: 723.76 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 715.32it/s, est. speed input: 622981.43 toks/s, output: 716.86 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 829.59it/s, est. speed input: 722763.31 toks/s, output: 831.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.69it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 820.19it/s, est. speed input: 714558.29 toks/s, output: 822.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 937.88it/s, est. speed input: 817397.07 toks/s, output: 940.55 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 990.73it/s, est. speed input: 863561.49 toks/s, output: 993.66 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.38it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1119.45it/s, est. speed input: 976247.40 toks/s, output: 1123.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1324.05it/s, est. speed input: 1155364.54 toks/s, output: 1329.39 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 573.25it/s, est. speed input: 499339.43 toks/s, output: 574.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 332.51it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 640.00it/s, est. speed input: 557273.94 toks/s, output: 641.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 644.06it/s, est. speed input: 560775.84 toks/s, output: 645.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.11it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 729.89it/s, est. speed input: 635728.53 toks/s, output: 731.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.50it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.11it/s, est. speed input: 635915.70 toks/s, output: 731.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 828.56it/s, est. speed input: 721886.52 toks/s, output: 830.65 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 806.72it/s, est. speed input: 702833.42 toks/s, output: 808.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 953.10it/s, est. speed input: 830735.08 toks/s, output: 955.89 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1018.43it/s, est. speed input: 887810.42 toks/s, output: 1021.55 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1129.77it/s, est. speed input: 986152.42 toks/s, output: 1134.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1339.82it/s, est. speed input: 1169158.04 toks/s, output: 1345.24 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  74%|███████▍  | 37/50 [01:41<00:33,  2.61s/it, task=test_0015]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  74%|███████▍  | 37/50 [01:41<00:33,  2.61s/it, task=test_0162]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 884.76it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 135.46it/s, est. speed input: 117776.34 toks/s, output: 135.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 569.20it/s, est. speed input: 495504.02 toks/s, output: 570.17 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 622.77it/s, est. speed input: 542259.81 toks/s, output: 623.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 717.70it/s, est. speed input: 625068.09 toks/s, output: 719.26 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 710.98it/s, est. speed input: 619227.45 toks/s, output: 712.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.18it/s, est. speed input: 710181.30 toks/s, output: 817.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 876.16it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 801.24it/s, est. speed input: 698046.57 toks/s, output: 803.22 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.42it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 928.96it/s, est. speed input: 809629.36 toks/s, output: 931.60 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 991.25it/s, est. speed input: 864041.29 toks/s, output: 994.22 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1120.67it/s, est. speed input: 977261.69 toks/s, output: 1124.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1296.61it/s, est. speed input: 1132930.60 toks/s, output: 1303.52 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 783.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 436.04it/s, est. speed input: 379580.46 toks/s, output: 436.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 345.49it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 636.71it/s, est. speed input: 554418.35 toks/s, output: 637.97 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 868.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 641.75it/s, est. speed input: 558793.09 toks/s, output: 643.00 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.24it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.64it/s, est. speed input: 630280.00 toks/s, output: 725.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.39it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 732.83it/s, est. speed input: 638271.64 toks/s, output: 734.44 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.07it/s, est. speed input: 730220.54 toks/s, output: 840.24 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 823.39it/s, est. speed input: 717627.04 toks/s, output: 825.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 878.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 848.54it/s, est. speed input: 739381.45 toks/s, output: 850.78 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.53it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1019.77it/s, est. speed input: 889028.50 toks/s, output: 1022.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1145.90it/s, est. speed input: 999693.20 toks/s, output: 1150.27 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1384.90it/s, est. speed input: 1209218.87 toks/s, output: 1391.29 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  76%|███████▌  | 38/50 [01:43<00:31,  2.62s/it, task=test_0162]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  76%|███████▌  | 38/50 [01:43<00:31,  2.62s/it, task=test_0101]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.33it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:05,  5.21it/s, est. speed input: 4528.50 toks/s, output: 5.21 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 130.54it/s, est. speed input: 113487.63 toks/s, output: 130.59 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 605.00it/s, est. speed input: 526969.47 toks/s, output: 606.38 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.66it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 632.54it/s, est. speed input: 550776.59 toks/s, output: 633.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 718.33it/s, est. speed input: 625624.66 toks/s, output: 719.89 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.81it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 713.59it/s, est. speed input: 621474.39 toks/s, output: 715.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 795.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 749.44it/s, est. speed input: 653085.57 toks/s, output: 751.48 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 847.54it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 808.78it/s, est. speed input: 704616.72 toks/s, output: 810.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 934.75it/s, est. speed input: 814668.02 toks/s, output: 937.41 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.54it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 969.62it/s, est. speed input: 845115.29 toks/s, output: 972.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1122.91it/s, est. speed input: 979255.50 toks/s, output: 1126.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1316.16it/s, est. speed input: 1148470.37 toks/s, output: 1321.46 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.89it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 564.79it/s, est. speed input: 491778.92 toks/s, output: 565.88 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.38it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 640.16it/s, est. speed input: 557545.65 toks/s, output: 641.56 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.85it/s, est. speed input: 553804.98 toks/s, output: 637.26 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 881.75it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.06it/s, est. speed input: 638498.75 toks/s, output: 734.71 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.20it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 729.24it/s, est. speed input: 635683.48 toks/s, output: 731.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.58it/s, est. speed input: 719025.02 toks/s, output: 827.35 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.64it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 826.30it/s, est. speed input: 720424.01 toks/s, output: 828.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 950.85it/s, est. speed input: 829441.30 toks/s, output: 954.38 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1022.04it/s, est. speed input: 891720.10 toks/s, output: 1026.03 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1132.58it/s, est. speed input: 987747.55 toks/s, output: 1136.54 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1340.98it/s, est. speed input: 1170143.32 toks/s, output: 1346.38 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  78%|███████▊  | 39/50 [01:46<00:28,  2.61s/it, task=test_0101]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  78%|███████▊  | 39/50 [01:46<00:28,  2.61s/it, task=heldout_0003]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1315.01it/s, est. speed input: 1147385.77 toks/s, output: 1320.20 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1337.83it/s, est. speed input: 1169322.13 toks/s, output: 1345.45 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 875.68it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1300.48it/s, est. speed input: 1134727.21 toks/s, output: 1305.66 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 861.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1299.93it/s, est. speed input: 1135168.96 toks/s, output: 1306.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 852.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1278.29it/s, est. speed input: 1115315.23 toks/s, output: 1283.31 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 874.79it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1327.25it/s, est. speed input: 1158106.34 toks/s, output: 1332.56 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1296.36it/s, est. speed input: 1131381.07 toks/s, output: 1301.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1332.82it/s, est. speed input: 1163095.39 toks/s, output: 1338.28 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1315.59it/s, est. speed input: 1147860.03 toks/s, output: 1320.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 688.59it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 392.20it/s, est. speed input: 341226.19 toks/s, output: 392.65 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1332.87it/s, est. speed input: 1163060.59 toks/s, output: 1338.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1315.67it/s, est. speed input: 1148040.81 toks/s, output: 1320.95 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1294.99it/s, est. speed input: 1130668.17 toks/s, output: 1300.92 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 867.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1359.68it/s, est. speed input: 1186583.30 toks/s, output: 1365.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 879.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1322.02it/s, est. speed input: 1153559.09 toks/s, output: 1327.31 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 858.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1335.19it/s, est. speed input: 1165058.84 toks/s, output: 1340.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1354.26it/s, est. speed input: 1181881.99 toks/s, output: 1359.90 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.15it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1352.70it/s, est. speed input: 1180422.69 toks/s, output: 1358.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 883.99it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1317.28it/s, est. speed input: 1149409.76 toks/s, output: 1322.52 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 794.92it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1354.79it/s, est. speed input: 1182373.21 toks/s, output: 1360.46 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 882.15it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1367.43it/s, est. speed input: 1193296.70 toks/s, output: 1373.03 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 886.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1357.97it/s, est. speed input: 1185112.39 toks/s, output: 1363.60 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  80%|████████  | 40/50 [01:48<00:24,  2.45s/it, task=heldout_0003]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  80%|████████  | 40/50 [01:48<00:24,  2.45s/it, task=test_0124]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.17it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 130.13it/s, est. speed input: 113129.22 toks/s, output: 130.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 857.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 599.44it/s, est. speed input: 522161.46 toks/s, output: 600.84 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 806.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 628.86it/s, est. speed input: 547917.53 toks/s, output: 630.48 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 822.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 697.48it/s, est. speed input: 607430.74 toks/s, output: 698.96 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.15it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 683.93it/s, est. speed input: 595989.81 toks/s, output: 685.79 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 849.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 808.95it/s, est. speed input: 704897.78 toks/s, output: 811.08 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 811.50it/s, est. speed input: 707008.58 toks/s, output: 813.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.15it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 939.68it/s, est. speed input: 819009.94 toks/s, output: 942.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.43it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1001.53it/s, est. speed input: 872998.40 toks/s, output: 1004.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 885.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1123.37it/s, est. speed input: 979609.16 toks/s, output: 1127.18 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1114.62it/s, est. speed input: 972600.34 toks/s, output: 1119.08 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 332.51it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 586.38it/s, est. speed input: 510480.98 toks/s, output: 587.41 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 902.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.92it/s, est. speed input: 561002.41 toks/s, output: 645.53 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 888.05it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 647.44it/s, est. speed input: 563732.88 toks/s, output: 648.68 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.29it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.64it/s, est. speed input: 636338.97 toks/s, output: 732.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 898.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 733.50it/s, est. speed input: 638851.98 toks/s, output: 735.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 892.65it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 838.70it/s, est. speed input: 730911.52 toks/s, output: 841.04 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 897.86it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 833.52it/s, est. speed input: 726156.18 toks/s, output: 835.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 894.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 964.40it/s, est. speed input: 840589.86 toks/s, output: 967.22 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 893.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1029.67it/s, est. speed input: 898610.93 toks/s, output: 1033.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 910.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1156.35it/s, est. speed input: 1008405.50 toks/s, output: 1160.30 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 900.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1365.57it/s, est. speed input: 1191833.46 toks/s, output: 1371.35 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  82%|████████▏ | 41/50 [01:51<00:22,  2.50s/it, task=test_0124]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  82%|████████▏ | 41/50 [01:51<00:22,  2.50s/it, task=test_0052]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 896.41it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 136.98it/s, est. speed input: 119095.36 toks/s, output: 137.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 598.52it/s, est. speed input: 521065.07 toks/s, output: 599.59 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 899.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 632.60it/s, est. speed input: 550810.41 toks/s, output: 633.81 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 893.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 723.39it/s, est. speed input: 630028.07 toks/s, output: 724.96 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 889.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 721.22it/s, est. speed input: 628121.24 toks/s, output: 722.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 901.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 827.23it/s, est. speed input: 720708.91 toks/s, output: 829.29 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 887.31it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 817.90it/s, est. speed input: 712571.97 toks/s, output: 819.93 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 894.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 938.10it/s, est. speed input: 817591.89 toks/s, output: 940.76 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 891.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1010.91it/s, est. speed input: 881223.41 toks/s, output: 1013.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 904.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1130.97it/s, est. speed input: 986661.30 toks/s, output: 1135.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 896.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1330.05it/s, est. speed input: 1160445.39 toks/s, output: 1335.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 596.56it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 323.57it/s, est. speed input: 281458.33 toks/s, output: 323.88 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 899.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.96it/s, est. speed input: 562466.03 toks/s, output: 647.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 890.55it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 645.77it/s, est. speed input: 562295.20 toks/s, output: 647.02 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 895.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 731.15it/s, est. speed input: 636825.38 toks/s, output: 732.78 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 895.67it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 730.56it/s, est. speed input: 636255.66 toks/s, output: 732.13 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 900.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 834.93it/s, est. speed input: 727705.65 toks/s, output: 837.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 896.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 833.90it/s, est. speed input: 726499.94 toks/s, output: 835.96 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 652.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 867.05it/s, est. speed input: 756237.11 toks/s, output: 870.17 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 727.10it/s, est. speed input: 633301.87 toks/s, output: 728.73 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 871.38it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1131.24it/s, est. speed input: 986561.15 toks/s, output: 1135.17 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 727.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1280.79it/s, est. speed input: 1117623.66 toks/s, output: 1285.96 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  84%|████████▍ | 42/50 [01:53<00:20,  2.53s/it, task=test_0052]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  84%|████████▍ | 42/50 [01:53<00:20,  2.53s/it, task=heldout_0006]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1252.49it/s, est. speed input: 1094508.52 toks/s, output: 1259.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1241.86it/s, est. speed input: 1084323.02 toks/s, output: 1247.61 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 853.91it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1182.08it/s, est. speed input: 1031768.21 toks/s, output: 1187.20 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 803.94it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1059.81it/s, est. speed input: 924106.72 toks/s, output: 1063.32 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.73it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1203.99it/s, est. speed input: 1050285.05 toks/s, output: 1208.48 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1207.50it/s, est. speed input: 1053377.34 toks/s, output: 1212.04 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 828.63it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1227.77it/s, est. speed input: 1071256.61 toks/s, output: 1232.62 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 830.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1214.68it/s, est. speed input: 1059684.24 toks/s, output: 1219.31 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1237.36it/s, est. speed input: 1079485.83 toks/s, output: 1242.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 831.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1237.54it/s, est. speed input: 1079675.69 toks/s, output: 1242.31 toks/s]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 841.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1267.59it/s, est. speed input: 1106448.91 toks/s, output: 1273.09 toks/s]
/root/repo/sata-project/src/evaluation/faithfulness_correctness.py:116: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  rho, pval = spearmanr(true_scores, behav_scores)
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1306.48it/s, est. speed input: 1142798.97 toks/s, output: 1314.79 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.98it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1258.24it/s, est. speed input: 1098115.18 toks/s, output: 1263.44 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 830.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1011.82it/s, est. speed input: 883011.37 toks/s, output: 1015.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts:  88%|████████▊ | 28/32 [00:00<00:00, 278.76it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 299.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 465.31it/s, est. speed input: 404996.01 toks/s, output: 466.02 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 812.14it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1208.19it/s, est. speed input: 1053977.03 toks/s, output: 1212.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 813.96it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1274.30it/s, est. speed input: 1111796.22 toks/s, output: 1279.26 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 824.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1253.48it/s, est. speed input: 1093687.46 toks/s, output: 1258.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.93it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1172.38it/s, est. speed input: 1022855.64 toks/s, output: 1176.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1277.89it/s, est. speed input: 1115059.33 toks/s, output: 1282.99 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 832.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1286.94it/s, est. speed input: 1122863.55 toks/s, output: 1291.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 837.52it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1211.67it/s, est. speed input: 1058434.11 toks/s, output: 1217.88 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  86%|████████▌ | 43/50 [01:55<00:17,  2.43s/it, task=heldout_0006]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  86%|████████▌ | 43/50 [01:55<00:17,  2.43s/it, task=test_0175]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 816.57it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:06,  5.14it/s, est. speed input: 4466.36 toks/s, output: 5.14 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 129.29it/s, est. speed input: 112406.58 toks/s, output: 129.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 595.91it/s, est. speed input: 518837.57 toks/s, output: 597.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.87it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 623.67it/s, est. speed input: 543045.00 toks/s, output: 624.88 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 824.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 693.51it/s, est. speed input: 604002.02 toks/s, output: 695.01 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 781.89it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 691.35it/s, est. speed input: 602199.51 toks/s, output: 692.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 806.27it/s, est. speed input: 703274.16 toks/s, output: 809.23 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.24it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 792.25it/s, est. speed input: 690243.08 toks/s, output: 794.24 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 822.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 884.44it/s, est. speed input: 771004.22 toks/s, output: 887.16 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 830.07it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 924.62it/s, est. speed input: 805814.52 toks/s, output: 927.22 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 797.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1090.35it/s, est. speed input: 951401.84 toks/s, output: 1094.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.02it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1162.02it/s, est. speed input: 1013487.71 toks/s, output: 1166.15 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 828.80it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 545.77it/s, est. speed input: 475100.23 toks/s, output: 546.69 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 815.05it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 634.68it/s, est. speed input: 552660.86 toks/s, output: 635.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 702.92it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 310.57it/s, est. speed input: 270143.36 toks/s, output: 310.85 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 760.73it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 709.77it/s, est. speed input: 618183.78 toks/s, output: 711.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 810.36it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 690.41it/s, est. speed input: 601578.31 toks/s, output: 692.23 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 800.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 808.29it/s, est. speed input: 704199.81 toks/s, output: 810.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 823.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 811.82it/s, est. speed input: 707308.71 toks/s, output: 813.87 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.68it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 924.24it/s, est. speed input: 805992.71 toks/s, output: 927.41 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 837.23it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 808.63it/s, est. speed input: 704693.35 toks/s, output: 810.85 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 827.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1112.22it/s, est. speed input: 970036.14 toks/s, output: 1116.16 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 797.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1328.51it/s, est. speed input: 1161219.47 toks/s, output: 1336.08 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  88%|████████▊ | 44/50 [01:58<00:15,  2.51s/it, task=test_0175]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  88%|████████▊ | 44/50 [01:58<00:15,  2.51s/it, task=test_0156]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 810.73it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 119.38it/s, est. speed input: 103789.21 toks/s, output: 119.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 594.45it/s, est. speed input: 517555.20 toks/s, output: 595.55 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 837.16it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 618.61it/s, est. speed input: 538882.57 toks/s, output: 620.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 828.86it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 704.01it/s, est. speed input: 613546.58 toks/s, output: 705.99 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 704.21it/s, est. speed input: 613875.97 toks/s, output: 706.36 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 643.41it/s, est. speed input: 560560.23 toks/s, output: 645.03 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 730.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 793.06it/s, est. speed input: 691843.96 toks/s, output: 796.08 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.12it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 779.98it/s, est. speed input: 680298.90 toks/s, output: 782.80 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 863.49it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 950.88it/s, est. speed input: 828804.75 toks/s, output: 953.66 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 869.31it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1115.87it/s, est. speed input: 973079.09 toks/s, output: 1119.65 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1165.17it/s, est. speed input: 1018950.65 toks/s, output: 1172.44 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 870.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 558.19it/s, est. speed input: 485909.16 toks/s, output: 559.14 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 714.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 380.60it/s, est. speed input: 331204.17 toks/s, output: 381.12 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 801.51it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 624.93it/s, est. speed input: 544314.68 toks/s, output: 626.34 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 817.01it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 714.76it/s, est. speed input: 622522.57 toks/s, output: 716.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 822.31it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 707.63it/s, est. speed input: 616543.35 toks/s, output: 709.44 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 816.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 812.15it/s, est. speed input: 708098.82 toks/s, output: 814.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 820.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 799.34it/s, est. speed input: 696495.91 toks/s, output: 801.44 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 923.07it/s, est. speed input: 805058.09 toks/s, output: 926.36 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 995.96it/s, est. speed input: 868267.23 toks/s, output: 999.07 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 809.34it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1126.07it/s, est. speed input: 982091.96 toks/s, output: 1130.03 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 809.35it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1291.28it/s, est. speed input: 1126888.42 toks/s, output: 1296.63 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  90%|█████████ | 45/50 [02:01<00:12,  2.56s/it, task=test_0156]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  90%|█████████ | 45/50 [02:01<00:12,  2.56s/it, task=test_0040]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 646.45it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 120.11it/s, est. speed input: 104417.24 toks/s, output: 120.16 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 862.86it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 616.70it/s, est. speed input: 537360.66 toks/s, output: 618.32 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 866.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 626.05it/s, est. speed input: 545263.83 toks/s, output: 627.43 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 865.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 710.05it/s, est. speed input: 618416.49 toks/s, output: 711.60 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.42it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 715.02it/s, est. speed input: 622745.26 toks/s, output: 716.58 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 877.37it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 814.95it/s, est. speed input: 710021.34 toks/s, output: 817.00 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 873.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 812.46it/s, est. speed input: 707840.98 toks/s, output: 814.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 864.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 917.99it/s, est. speed input: 800406.30 toks/s, output: 921.00 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 872.41it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 773.09it/s, est. speed input: 674601.38 toks/s, output: 776.25 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 733.97it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 988.74it/s, est. speed input: 861966.00 toks/s, output: 991.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 812.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1267.81it/s, est. speed input: 1106239.03 toks/s, output: 1272.88 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 548.40it/s, est. speed input: 477402.69 toks/s, output: 549.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 832.83it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 597.69it/s, est. speed input: 520388.55 toks/s, output: 598.81 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 827.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 610.18it/s, est. speed input: 531251.51 toks/s, output: 611.30 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.73it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 706.23it/s, est. speed input: 615330.10 toks/s, output: 708.03 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 838.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 708.31it/s, est. speed input: 616879.22 toks/s, output: 709.83 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 839.02it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 825.91it/s, est. speed input: 719632.80 toks/s, output: 828.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.04it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 805.78it/s, est. speed input: 702025.42 toks/s, output: 807.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 930.14it/s, est. speed input: 810738.03 toks/s, output: 932.88 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 831.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 978.23it/s, est. speed input: 852764.84 toks/s, output: 981.24 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 647.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1117.13it/s, est. speed input: 974322.78 toks/s, output: 1121.10 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 839.82it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1354.08it/s, est. speed input: 1182672.94 toks/s, output: 1360.79 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  92%|█████████▏| 46/50 [02:03<00:10,  2.59s/it, task=test_0040]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  92%|█████████▏| 46/50 [02:03<00:10,  2.59s/it, task=test_0082]

Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 428.72it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts:   3%|▎         | 1/32 [00:00<00:06,  5.01it/s, est. speed input: 4352.11 toks/s, output: 5.01 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 143.03it/s, est. speed input: 124349.47 toks/s, output: 143.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 756.40it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 577.95it/s, est. speed input: 503180.41 toks/s, output: 579.00 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 808.35it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 619.27it/s, est. speed input: 539208.93 toks/s, output: 620.46 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 821.28it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 711.47it/s, est. speed input: 619658.42 toks/s, output: 713.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.13it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 681.11it/s, est. speed input: 593518.08 toks/s, output: 682.94 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 821.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 809.32it/s, est. speed input: 705123.64 toks/s, output: 811.36 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.42it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 810.55it/s, est. speed input: 706199.51 toks/s, output: 812.61 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 831.10it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 913.02it/s, est. speed input: 795786.24 toks/s, output: 915.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 801.99it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 958.73it/s, est. speed input: 835657.37 toks/s, output: 961.55 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 832.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1089.68it/s, est. speed input: 950277.87 toks/s, output: 1093.42 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 817.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1292.53it/s, est. speed input: 1127781.91 toks/s, output: 1297.65 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 772.27it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 571.11it/s, est. speed input: 497516.18 toks/s, output: 572.35 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 817.44it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 634.27it/s, est. speed input: 552281.41 toks/s, output: 635.50 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 827.69it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 628.50it/s, est. speed input: 547274.80 toks/s, output: 629.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 820.77it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 688.08it/s, est. speed input: 600308.84 toks/s, output: 690.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 828.05it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 710.38it/s, est. speed input: 618734.71 toks/s, output: 711.96 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.23it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 823.40it/s, est. speed input: 717971.61 toks/s, output: 826.15 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 839.51it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 819.36it/s, est. speed input: 713862.91 toks/s, output: 821.43 toks/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 827.81it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 880.60it/s, est. speed input: 768692.20 toks/s, output: 884.51 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 832.72it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 985.85it/s, est. speed input: 859374.79 toks/s, output: 988.84 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.19it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1121.26it/s, est. speed input: 977868.00 toks/s, output: 1125.17 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 820.22it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1327.85it/s, est. speed input: 1158819.73 toks/s, output: 1333.38 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  94%|█████████▍| 47/50 [02:06<00:07,  2.60s/it, task=test_0082]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  94%|█████████▍| 47/50 [02:06<00:07,  2.60s/it, task=test_0027]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 814.29it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 137.36it/s, est. speed input: 119415.07 toks/s, output: 137.41 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 821.46it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 603.64it/s, est. speed input: 525556.63 toks/s, output: 604.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 837.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 624.64it/s, est. speed input: 543893.33 toks/s, output: 625.85 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.65it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 705.10it/s, est. speed input: 614066.65 toks/s, output: 706.60 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 840.60it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 709.84it/s, est. speed input: 618259.14 toks/s, output: 711.42 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 843.25it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 808.62it/s, est. speed input: 704880.74 toks/s, output: 811.09 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 770.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 784.38it/s, est. speed input: 683372.04 toks/s, output: 786.34 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 837.41it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 911.21it/s, est. speed input: 794095.82 toks/s, output: 913.74 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 822.81it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 974.03it/s, est. speed input: 849015.52 toks/s, output: 976.92 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 827.36it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1093.03it/s, est. speed input: 953158.99 toks/s, output: 1096.75 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1290.23it/s, est. speed input: 1126986.42 toks/s, output: 1296.75 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 823.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 562.05it/s, est. speed input: 489559.93 toks/s, output: 563.33 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.87it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 603.46it/s, est. speed input: 525426.41 toks/s, output: 604.60 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.80it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 628.14it/s, est. speed input: 546951.43 toks/s, output: 629.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.56it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 720.04it/s, est. speed input: 627168.78 toks/s, output: 721.67 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 842.32it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 712.49it/s, est. speed input: 621126.88 toks/s, output: 714.70 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 817.30it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 817.57it/s, est. speed input: 712323.92 toks/s, output: 819.65 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 825.88it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 809.46it/s, est. speed input: 705234.49 toks/s, output: 811.49 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 830.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 935.05it/s, est. speed input: 815699.26 toks/s, output: 938.57 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 848.59it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1000.51it/s, est. speed input: 872221.52 toks/s, output: 1003.62 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 821.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 831.95it/s, est. speed input: 724869.99 toks/s, output: 834.09 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.62it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1313.50it/s, est. speed input: 1147216.49 toks/s, output: 1319.94 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  96%|█████████▌| 48/50 [02:09<00:05,  2.61s/it, task=test_0027]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  96%|█████████▌| 48/50 [02:09<00:05,  2.61s/it, task=test_0019]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.22it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 127.52it/s, est. speed input: 110853.95 toks/s, output: 127.56 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.33it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 597.97it/s, est. speed input: 520634.78 toks/s, output: 599.09 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 840.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 617.86it/s, est. speed input: 537985.27 toks/s, output: 619.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 839.84it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 676.07it/s, est. speed input: 588754.48 toks/s, output: 677.47 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 702.63it/s, est. speed input: 611940.28 toks/s, output: 704.15 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.21it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 804.93it/s, est. speed input: 701278.31 toks/s, output: 806.94 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 838.13it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 781.26it/s, est. speed input: 680588.69 toks/s, output: 783.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 840.07it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 915.59it/s, est. speed input: 797925.78 toks/s, output: 918.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 820.59it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 994.06it/s, est. speed input: 866557.74 toks/s, output: 997.10 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.11it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1091.55it/s, est. speed input: 952466.24 toks/s, output: 1095.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 804.27it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1252.43it/s, est. speed input: 1093246.65 toks/s, output: 1257.86 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.95it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 575.65it/s, est. speed input: 501145.95 toks/s, output: 576.67 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 844.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 636.76it/s, est. speed input: 554471.06 toks/s, output: 638.02 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 845.09it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 635.57it/s, est. speed input: 553408.20 toks/s, output: 636.80 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.17it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 714.72it/s, est. speed input: 622492.66 toks/s, output: 716.29 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 830.47it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 719.54it/s, est. speed input: 626737.41 toks/s, output: 721.17 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 842.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 822.96it/s, est. speed input: 717013.83 toks/s, output: 825.05 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 827.18it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 815.25it/s, est. speed input: 710990.85 toks/s, output: 818.06 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 847.64it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 935.79it/s, est. speed input: 815596.59 toks/s, output: 938.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 839.33it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1025.05it/s, est. speed input: 893653.65 toks/s, output: 1028.28 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 840.71it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1121.47it/s, est. speed input: 978064.80 toks/s, output: 1125.39 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.93it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1318.08it/s, est. speed input: 1151668.29 toks/s, output: 1325.15 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  98%|█████████▊| 49/50 [02:11<00:02,  2.61s/it, task=test_0019]

RQ4 faithfulness tasks (Llama-3.1-8B-Instruct):  98%|█████████▊| 49/50 [02:11<00:02,  2.61s/it, task=test_0196]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 821.50it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 125.91it/s, est. speed input: 109454.96 toks/s, output: 125.95 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 819.80it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 595.74it/s, est. speed input: 518685.29 toks/s, output: 596.84 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.55it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 623.81it/s, est. speed input: 543148.69 toks/s, output: 625.00 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 824.68it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 706.39it/s, est. speed input: 615235.97 toks/s, output: 707.94 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 829.72it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 699.65it/s, est. speed input: 609325.22 toks/s, output: 701.14 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 826.48it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 803.92it/s, est. speed input: 700406.58 toks/s, output: 805.93 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 840.57it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 759.02it/s, est. speed input: 661223.55 toks/s, output: 760.85 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 811.74it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 899.76it/s, est. speed input: 784091.68 toks/s, output: 902.23 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 790.95it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 952.84it/s, est. speed input: 830528.04 toks/s, output: 955.65 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 824.43it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1086.83it/s, est. speed input: 947714.35 toks/s, output: 1090.48 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 823.26it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1271.45it/s, est. speed input: 1110737.43 toks/s, output: 1277.98 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 844.03it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 556.95it/s, est. speed input: 484965.64 toks/s, output: 558.05 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 831.66it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 630.13it/s, est. speed input: 548982.64 toks/s, output: 631.71 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 731.78it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 617.98it/s, est. speed input: 538278.24 toks/s, output: 619.37 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 839.76it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 718.61it/s, est. speed input: 625899.96 toks/s, output: 720.21 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 835.83it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 722.13it/s, est. speed input: 628998.57 toks/s, output: 723.77 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 833.46it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 817.55it/s, est. speed input: 712315.22 toks/s, output: 819.65 toks/s]
Rendering prompts:   0%|          | 0/32 [00:00<?, ?it/s]

Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 836.90it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 824.38it/s, est. speed input: 718422.69 toks/s, output: 826.63 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 845.59it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 939.24it/s, est. speed input: 818688.01 toks/s, output: 942.02 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 831.63it/s]
Processed prompts:   0%|          | 0/32 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1005.45it/s, est. speed input: 879223.91 toks/s, output: 1011.66 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.58it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 909.92it/s, est. speed input: 793005.21 toks/s, output: 912.47 toks/s]
Rendering prompts: 100%|██████████| 32/32 [00:00<00:00, 834.15it/s]
Processed prompts: 100%|██████████| 32/32 [00:00<00:00, 1348.80it/s, est. speed input: 1178490.51 toks/s, output: 1355.98 toks/s]
RQ4 faithfulness tasks (Llama-3.1-8B-Instruct): 100%|██████████| 50/50 [02:14<00:00,  2.61s/it, task=test_0196]

[rank0]:[W912 17:12:47.235474131 ProcessGroupNCCL.cpp:1624] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

,task_group,method,shift_type,model,accuracy,macro_f1,invalid_rate,n,rho_mean,rho_std
0,heldout_family,best_protocol_sata,covariate,Llama-3.1-8B-Instruct,0.294375,0.239718,0.0,1600,0.085616,0.351917
1,heldout_family,best_protocol_sata,extrapolation,Llama-3.1-8B-Instruct,0.396250,0.287126,0.0,1600,0.085616,0.351917
2,heldout_family,best_protocol_sata,id,Llama-3.1-8B-Instruct,0.400625,0.308863,0.0,1600,0.085616,0.351917
3,heldout_family,best_protocol_sata,mechanism,Llama-3.1-8B-Instruct,0.390000,0.307585,0.0,1600,0.085616,0.351917
4,heldout_family,best_protocol_sata,missing_feature,Llama-3.1-8B-Instruct,0.033750,0.032648,0.0,1600,0.085616,0.351917
5,heldout_family,best_protocol_sata,spurious_reversal,Llama-3.1-8B-Instruct,0.073125,0.071947,0.0,1600,0.085616,0.351917
6,heldout_family,label_diversity,covariate,Llama-3.1-8B-Instruct,0.598125,0.471573,0.0,1600,0.069208,0.342535
7,heldout_family,label_diversity,extrapolation,Llama-3.1-8B-Instruct,0.540000,0.362655,0.0,1600,0.069208,0.342535
8,heldout_family,label_diversity,id,Llama-3.1-8B-Instruct,0.563125,0.437983,0.0,1600,0.069208,0.342535
9,heldout_family,label_diversity,mechanism,Llama-3.1-8B-Instruct,0.545000,0.375256,0.0,1600,0.069208,0.342535
10,heldout_family,label_diversity,missing_feature,Llama-3.1-8B-Instruct,0.000000,0.000000,0.0,1600,0.069208,0.342535
11,heldout_family,label_diversity,spurious_reversal,Llama-3.1-8B-Instruct,0.553125,0.414282,0.0,1600,0.069208,0.342535
12,test,best_protocol_sata,covariate,Llama-3.1-8B-Instruct,0.266250,0.243154,0.0,6400,0.085616,0.351917
13,test,best_protocol_sata,extrapolation,Llama-3.1-8B-Instruct,0.300156,0.242689,0.0,6400,0.085616,0.351917
14,test,best_protocol_sata,id,Llama-3.1-8B-Instruct,0.379063,0.310361,0.0,6400,0.085616,0.351917
15,test,best_protocol_sata,mechanism,Llama-3.1-8B-Instruct,0.354687,0.286080,0.0,6400,0.085616,0.351917
16,test,best_protocol_sata,missing_feature,Llama-3.1-8B-Instruct,0.422812,0.375009,0.0,6400,0.085616,0.351917
17,test,best_protocol_sata,spurious_reversal,Llama-3.1-8B-Instruct,0.098906,0.095735,0.0,6400,0.085616,0.351917
18,test,label_diversity,covariate,Llama-3.1-8B-Instruct,0.488438,0.454876,0.0,6400,0.069208,0.342535
19,test,label_diversity,extrapolation,Llama-3.1-8B-Instruct,0.536250,0.410923,0.0,6400,0.069208,0.342535
20,test,label_diversity,id,Llama-3.1-8B-Instruct,0.529062,0.424125,0.0,6400,0.069208,0.342535
21,test,label_diversity,mechanism,Llama-3.1-8B-Instruct,0.463438,0.348308,0.0,6400,0.069208,0.342535
22,test,label_diversity,missing_feature,Llama-3.1-8B-Instruct,0.516719,0.443822,0.0,6400,0.069208,0.342535
23,test,label_diversity,spurious_reversal,Llama-3.1-8B-Instruct,0.513437,0.395176,0.0,6400,0.069208,0.342535

## RQ3 correctness-of-reliance (synthetic only)

This is the strongest version of the faithfulness question the project asks, and it only exists on the synthetic arm. Notebook 03's ρ(π_self, π_behav) checks *internal consistency* — does the model's self-report match its own behaviour? — but says nothing about whether that behaviour is actually *correct*, because no real dataset can hand us π_true. Here, `true_importance_scores` derives π_true directly from the generator's own causal structure — family-aware, since `SyntheticTask._apply_rule` only reads `coefficients` for the `linear` family: `threshold` scores its thresholded features, `tree` scores each causal feature by its Boolean influence on the leaf function, `sparse_interaction` scores its two interacting features, and the spurious/noise features plus any unused causal-family "decoy" always score 0 — the one thing that's impossible to obtain on TableShift data. ρ(π_behav, π_true) therefore asks the sharper question: not just "is the model consistent with itself," but "does the model rely on the features that actually determine the label."

In [5]:
# rho(pi_behav, pi_true) is computed once, per condition/task, in the RQ4 cell
# above (its faithfulness component *is* this RQ3 computation -- the spec
# describes them identically) and saved to faithfulness_synthetic.parquet.
# This cell just presents the summary view.
if correctness_df.empty:
    print("No correctness-of-reliance results yet (see RQ4 cell above).")
else:
    correctness_df.groupby(['model', 'method'])['rho'].describe()

## Output

- `results/synthetic_evaluation.parquet`
- `results/rq2_grid.parquet`
- `results/rq4_comparison.parquet`
- `results/faithfulness_synthetic.parquet`